### ISSUE TITLE
Subtitle provider RegieLive fails with "BadZipFile"

### ISSUE THREAD

**Issue by marcel5454** [morpheus65535/bazarr#1001]
**Describe the bug**
When downloading Subtitles with Regielive often it fails with BadZipFile and then is being throttled for 10 minutes. The Zip file is not bad though because other times the same Subtitles download just fine

**To Reproduce**
1. Go to: Manual search Subtitle (also happens with automatic search though)
2. Click on. download subtitle 
3. See error in log and subtitles not downloaded

**Software (please complete the following information):**
 - Bazarr: v0.8.4.4

**Additional context**
Log: 
[bazarr (6).log](https://github.com/morpheus65535/bazarr/files/4688665/bazarr.6.log)

**Comment by morpheus65535** [comment]
@GermanG you have time to look into this one? Thanks!

**Comment by morpheus65535** [comment]
Do you still get this issue?

**Comment by morpheus65535** [comment]
Closing this issue, no answer.
