### ISSUE TITLE
Not able to write subtitles

### ISSUE THREAD

**Issue by fhennema** [morpheus65535/bazarr#1002]
Hello, I am running Bazarr in Docker container on Raspberry Pi. Some how Bazarr is not able to write subtitles to disk. Looks like retrieving information works fine, finding subtitles works fine, but writing them to disk gives an error.

Error:
Traceback (most recent call last):
 File "/app/bazarr/get_subtitle.py", line 202, in download_subtitle
  saved_subtitles = save_subtitles(video.original_path, subtitles, single=single,
 File "/app/bazarr/../libs/subliminal_patch/core.py", line 879, in save_subtitles
  with open(subtitle_path, \wb\) as f:
PermissionError: [Errno 13] Permission denied: \/tv/The Fix/Season 1/The.Fix.S01E02.720p.WEB-DL.nl.srt\

When I access the directory on the Raspberry Pi, I am able to create and delete files.

Create/start the container using:
docker run -d -p 6767:6767 \
  --name=bazarr \
  -e PUID=1000 \
  -e PGID=1000 \
 -e UMASK_SET=022 \
  -e TZ=Europe/Amsterdam \
  -v /home/pi/Apps/Bazarr/config:/config \
  -v /home/pi/Apps/Radarr/films:/movies \
  -v /home/pi/Apps/Sonarr/series:/tv \
--restart unless-stopped \
--name bazarr \
hotio/bazarr

Saw a couple of issues regarding writing subtitles, but did not find exact simular issue yet.

Hope someone can help me out here.

**Comment by morpheus65535** [comment]
For support question, please come to Discord. This is issue tracking system. This is clearly a permission issue.
