### ISSUE TITLE
For support, please come to Discord first!

### ISSUE THREAD

**Issue by morpheus65535** [morpheus65535/bazarr#1004]
This board is dedicated to issues reporting.

Discord server: https://discord.com/invite/MH2e2eb
Then use the `Support` channel.

**Comment by michaeldrouin** [comment]
invite link is invalid :(

**Comment by BodingClockchian** [comment]
https://discord.gg/ZrEqqj8

**Comment by BodingClockchian** [comment]
> 
> 
> invite link is invalid :(

https://discord.gg/ZrEqqj8

**Comment by morpheus65535** [comment]
The invite url is valid and I just tested it. There's probably a glitch on Discord side today.

**Comment by michaeldrouin** [comment]
> The invite url is valid and I just tested it. There's probably a glitch on Discord side today.

ah. i'll try it again later. it's weird because i click the link and i get the server datails:

> morpheus65535 invited you to join
> Bazarr
> 336 Online
> 1,722 Members
> Accept Invite

but then when i click "Accept Invite" is when i get the message:

> Invite Invalid
> This invite may be expired, or you might not have permission to join.

**Comment by TRaSH-** [comment]
Bazarr: https://discord.gg/MH2e2eb
try this one.

**Comment by trex005** [comment]
I noticed the link here and the link in github are both invalid.

When creating an invite link, there is an option to edit the link:
![sEQ1avhz9L](https://user-images.githubusercontent.com/4133282/190111405-78e799f0-edad-40bc-82f0-b8ff9874cbb3.png)

And then you can set the expiration to "Never" and the user limit to "No Limit"
![Discord_PYFWQwDfCc](https://user-images.githubusercontent.com/4133282/190111605-cc395f89-bddd-43b9-9baa-3c4420525c09.png)

**Comment by morpheus65535** [comment]
@trex005 the invites works perfectly fine: 
![image](https://user-images.githubusercontent.com/5130500/190129267-b40ced9f-7462-4714-bbcc-7b1b84453b15.png)

**Comment by trex005** [comment]
Interestingly enough, I tested it again and it *was* still not working:
![brave_uQk0Jo2rTZ](https://user-images.githubusercontent.com/4133282/190229288-cf6c4ca3-655f-4759-acb6-1cc61358cc38.png)

I then tested it on mobile and it did work.

I decided to try a different browser, and chrome is also working. It seems like it is just an issue with the desktop version of Brave.

**Comment by morpheus65535** [comment]
> It seems like it is just an issue with the desktop version of Brave.

Not the first time Brave is causing issues...
