### ISSUE TITLE
Sync frequencies intervals are ridiculous short. No way to change these

### ISSUE THREAD

**Issue by just-Addict** [morpheus65535/bazarr#1005]
I would like to reduce the sync frequencies with the Sonarr series List and Radarr movies list to a more realistic interval but cannot find any place to do so.

A 60 second interval to `Update Series list from Sonarr` is ridiculously often. once or maybe even twice every 24 hours is more than sufficient.
Also, `Sync episodes with Sonarr` would then of course need to be set to the same interval, e.g. once or maybe even twice every 24 hours.
Same for the `Update Movie list from Radarr` interval, 5 minutes is again ridiculously often and again, once or maybe even twice every 24 hours would be more than sufficient

How do I change these values?

**Comment by morpheus65535** [comment]
You wait for v0.9 that is in dev branch right now.

**Comment by just-Addict** [comment]
Thank you.
