### ISSUE TITLE
Episodes from Sonarr v3 not loaded

### ISSUE THREAD

**Issue by klara31** [morpheus65535/bazarr#1007]
**Describe the bug**
Bazarr is not loading episodes from sonarr v3. Each series tells:
```
No episode files available for this Series or Bazarr is still synchronizing with Sonarr. Please come back later. 
```

**To Reproduce**
Add series in Sonarr

**Expected behavior**
Episodes from Sonarr should be visible

**Software (please complete the following information):**
Bazarr Version: 0.8.4.4
Sonarr Version: 3.0.3.834
Radarr Version: 0.2.0.1480
Operating System: Linux-5.4.0-33-generic-x86_64-with

**Additional context**
Radarr is working correctly. I have also tried to remove and add a serie, same result

**Comment by morpheus65535** [comment]
How long since you completed the initial configuration? In System--Tasks, does the episode sync with Sonarr task is still running? Can you provide a debug log?

**Comment by klara31** [comment]
I was able to figure it out myself.

log shows:
```01/06/2020 13:23:27|ERROR   |root                            |BAZARR Error trying to get episodes from Sonarr. Http error.|Traceback (most recent call last):  File "/app/bazarr/bazarr/get_episodes.py", line 47, in sync_episodes    r.raise_for_status()  File "/app/bazarr/bazarr/../libs/requests/models.py", line 940, in raise_for_status    raise HTTPError(http_error_msg, response=self)requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http://192.168.10.10:80/sonarr/api/episode?seriesId=12&apikey=xxxx|```

I checked the Sonarr API URL, which returned a JSON containing ```"message": "database disk image is malformed\ndatabase disk image is malformed"```

Next, I stopped sonarr, and checked the database with sqlite3 command ```PRAGMA integrity_check;```, which returned: ```wrong # of entries in index IX_Episodes_SeriesId_AirDate```.

Did a backup/restore on sonarr.db, and that solved the problem!
Thanks anyway :)

**Comment by morpheus65535** [comment]
Thanks for sharing your resolution!

**Comment by clobber88** [comment]
> I was able to figure it out myself.
> 
> Did a backup/restore on sonarr.db, and that solved the problem!
> Thanks anyway :)

OP, I'm having the same problem. How did you do the backup/restore? Just like is described here: [https://github.com/Sonarr/Sonarr/wiki/Backup-and-Restore](url)

I tried that and it did not solve my problem.

**Comment by klara31** [comment]
I used Linux command line commandos:
```
sqlite3 sonarr.db .dump > sonarr.sql
rm sonarr.db
sqlite3 sonarr.db < sonarr.sql
```

**Comment by clobber88** [comment]
> I used Linux command line commandos:
> 
> ```
> sqlite3 sonarr.db .dump > sonarr.sql
> rm sonarr.db
> sqlite3 sonarr.db < sonarr.sql
> ```

sonarr.db is the name of the file on disk? Mine is showing as nzbdrone.db.
