### ISSUE TITLE
"Error trying to get video information for this file..."

### ISSUE THREAD

**Issue by rscm** [morpheus65535/bazarr#1008]
**Description**
Manual search (and probably automatic), fail to get video file info.

**Fragment of the log:**
`01/06/2020 00:38:22|ERROR   |root                            |BAZARR Error trying to get video information for this file: /tv/Penny Dreadful/Season 2/flhd-pds02e01-1080p.mkv|Traceback (most recent call last):  File "/app/bazarr/bazarr/get_subtitle.py", line 71, in get_video    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,  File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 529, in scan_video    video = Video.fromguess(path, guessed_result)  File "/app/bazarr/bazarr/../libs/subliminal/video.py", line 94, in fromguess    return Episode.fromguess(name, guess)  File "/app/bazarr/bazarr/../libs/subliminal/video.py", line 171, in fromguess    raise ValueError('Insufficient data to process the guess')ValueError: Insufficient data to process the guess|`

**To Reproduce**
1. Go to the Series episode list
2. Click on manual search
3. Wait for the list of subtitles
4. Nothing happens, just says "Scenename is: None"

**Expected behavior**
After step 3, I expect to have a list of subtitles to choose from

**Screenshots**
![Screenshot_2020-06-02 Penny Dreadful - Bazarr](https://user-images.githubusercontent.com/6588120/83495627-f0749800-a485-11ea-9952-2580e1d68e78.png)

**Software:**
 - Bazarr: Docker | Linuxserver.io version:- v0.8.4.4-ls80 Build-date:- 2020-05-28T21:59:47+00:00
 - Sonarr: Docker | Linuxserver.io version:- 2.0.0.5344-ls65 Build-date:- 2020-05-21T14:38:55+02:00
 - OS: Armbian - Debian Buster | Open Media Vault 5

**Additional context**
This only have happened with this Series and Season, with others it works as expected.
If you need more tests for me to do, just ask.

All files are: (0664/-rw-rw-r--)

**Media info**
`$ ffprobe flhd-pds02e01-1080p.mkv 
ffprobe version 4.1.4-1~deb10u1 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --arch=arm --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, matroska,webm, from 'flhd-pds02e01-1080p.mkv':
  Metadata:
    encoder         : libebml v0.8.0 + libmatroska v0.9.0
    creation_time   : 2015-10-05T09:33:02.000000Z
  Duration: 00:55:02.05, start: 0.000000, bitrate: 11349 kb/s
    Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 640 kb/s (default)`

**LOG**
[bazarr.log](https://github.com/morpheus65535/bazarr/files/4715698/bazarr.log)

**Comment by morpheus65535** [comment]
`Insufficient data to process the guess` mean that GuessIt on which we rely to get video properties (including series name and episode number) is unable to interpret those poorly named file: `flhd-pds02e01-1080p.mkv`.

Rename those files to include human readable series name, make sure to have a dash before s02e01, put the release group at the end of the file name (flhd?) and you should be all good.

**Comment by vtzarkov** [comment]
got similar issue with "Scenename is: None"
![image](https://user-images.githubusercontent.com/23626891/83512093-60137300-a4d8-11ea-9ab4-b3983ccb7de7.png)
S01E08.WEBRip.x264-ION10.mp4 - filename looks good but its not working

**Comment by morpheus65535** [comment]
If scenename is None, we don't use it at all. In that case, we use GuessIt with the path of the file to guess the metadata of the media file. We use an updated version of GuessIt in v0.9 (dev branch for now) and you could give it a try. With this version (3.1.1), it seems to be working fine for me.
