### ISSUE TITLE
If "Encode Subtitles To UTF8" is selected, it should also apply to manually uploaded subtitle files

### ISSUE THREAD

**Issue by fgordon-maker** [morpheus65535/bazarr#1009]
**Describe the bug**
This is rather a feature request.
When manually uploading a file, its encoding is left unchanged. I would expect that if "Encode Subtitles To UTF8" is selected in the Settings, the UTF encoding to be applied to it, too.

**To Reproduce**
1. Manually upload a non-UTF-8 subtitle file
2. Verify encoding of the resulting file

**Expected behavior**
If "Encode Subtitles To UTF8" is selected in the Settings, I would expect the UTF encoding to be applied to the manually uploaded subtitle files as well.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: v0.8.4.4
 - Radarr version: N/A
 - Sonarr version: 2.0.0.5344
 - OS: docker-armhf

**Additional context**

**Comment by morpheus65535** [comment]
This is already been done in 0.8.4.4: https://github.com/morpheus65535/bazarr/blob/20c3a3c55d9174334da96740a27c643368907da9/bazarr/get_subtitle.py#L513
