### ISSUE TITLE
Update from Sonarr failing

### ISSUE THREAD

**Issue by faulander** [morpheus65535/bazarr#101]
We had this discussion already, but you closed the topic. I still get the error:
'Traceback (most recent call last):\n File "/usr/lib/python2.7/site-packages/apscheduler/executors/base.py", line 125, in run_job\n retval = job.func(*job.args, **job.kwargs)\n File "/bazarr/get_episodes.py", line 41, in sync_episodes\n if episode[\'hasFile\'] is True:\nTypeError: string indices must be integers'

**Comment by morpheus65535** [comment]
I've added another check but the fact remain, your Sonarr instance is returning incomplete JSON. "hasFile" is a mandatory metadata that is present for every episode.

Give me feedback after you've updated your Bazarr instance.

**Comment by faulander** [comment]
Can i find out which Series it is? Then i might raise an issue with Sonarr ...
Updated and give feedback asap.

**Comment by morpheus65535** [comment]
Not with the current code. When I’ll get back home, I’ll add some logging when « hasFile » isn’t there for an episode.

**Comment by faulander** [comment]
![2018-07-09 19_30_52-system - bazarr](https://user-images.githubusercontent.com/38588197/42466255-a4ccc746-83ae-11e8-8855-dfa2e4a2d682.png)
it looks like it's doing nothing anymore :/

**Comment by morpheus65535** [comment]
Normal operation doesn’t log every 5 minutes unless there’s an error.

**Comment by faulander** [comment]
Last download from Bazarr was 4 days ago and i have a ton of Shows with missing subtitles. I am sure there should be at least a few in missing subtitles. It seems it doesn't do anything - at least nothing related to Sonarr.

**Comment by faulander** [comment]
Todays downloads:
![2018-07-09 21_43_06-activity - sonarr](https://user-images.githubusercontent.com/38588197/42472307-22f6ad64-83c1-11e8-80d2-5a082fcaa00b.png)
Wanted in Bazarr:
![2018-07-09 21_43_48-wanted - bazarr](https://user-images.githubusercontent.com/38588197/42472342-39868554-83c1-11e8-93be-e9df39c59620.png)

**Comment by morpheus65535** [comment]
Have you verified if those episode are indexed in Bazarr? Can you see it in series pages?

**Comment by faulander** [comment]
yes, example from Post. S01E06 has been indexed, but it doesn't show up in "Wanted Subtitles":
![2018-07-10 09_04_24-pose - bazarr](https://user-images.githubusercontent.com/38588197/42494360-599a0726-8420-11e8-9fcf-1104a6758318.png)
Wanted is still the same as yesterday ...

**Comment by faulander** [comment]
Restarted Sonarr, found this regarding to the API in the logs:
18-7-10 08:47:34.5|Debug|Api|[GET] /api/episode?seriesId=117&apikey=(removed) 200.OK (34 ms)
18-7-10 08:47:34.6|Debug|Api|[GET] /api/episode?seriesId=118&apikey=(removed) 200.OK (17 ms)
18-7-10 08:47:50.7|Debug|Api|[GET] /api/profile?apikey=(removed) 200.OK (12 ms)
18-7-10 08:47:50.7|Debug|Api|[GET] /api/v3/languageprofile?apikey=(removed) 404.NotFound (1 ms)
18-7-10 08:47:51.2|Debug|Api|[GET] /api/series?apikey=(removed) 200.OK (435 ms)
18-7-10 08:48:01.1|Debug|Api|[GET] /api/health: 200.OK (8 ms)
18-7-10 08:48:01.1|Debug|Api|[GET] /api/health: 200.OK (2 ms)
18-7-10 08:48:01.3|Debug|Api|[GET] /api/diskspace: 200.OK (196 ms)
18-7-10 08:48:01.3|Debug|Api|[GET] /api/diskspace: 200.OK (264 ms)
18-7-10 08:48:02.6|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (10 ms)
18-7-10 08:48:02.6|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (8 ms)
18-7-10 08:48:26.9|Debug|Api|[GET] /api/log/file/update: 200.OK (42 ms)
18-7-10 08:48:27.1|Debug|Api|[GET] /api/log/file/update/2018.06.26-13.58.txt: 200.OK (43 ms)
18-7-10 08:48:29.4|Debug|Api|[GET] /api/log/file: 200.OK (54 ms)
18-7-10 08:48:29.7|Debug|Api|[GET] /api/log/file/sonarr.debug.txt: 200.OK (22 ms)
18-7-10 08:48:33.3|Debug|Api|[GET] /api/log/file/sonarr.debug.txt: 200.OK (21 ms)

But nothing else. Still not working ...

**Comment by faulander** [comment]
i found the problem. Newly added shows in Sonarr don't get a language flag in Bazarr. As soon as you set it manually, it works. It would be nice that you can set a standard language for newly added shows.

**Comment by faulander** [comment]
and now i found out that there is a setting for this ... i am so dumb sometimes! :)

**Comment by morpheus65535** [comment]
That was my next question: did you set a desired language for this show? ;-)

Don't be so hard on you, default settings for newly added shows is a functionality that have been added to Bazarr 2 weeks ago only! :-)

You can use the series editor to change all your shows desired languages at the same time.

Is everything working has expected now?
