### ISSUE TITLE
Force provider retry

### ISSUE THREAD

**Issue by Tom-van-Grinsven** [morpheus65535/bazarr#1011]
Not a bug. I have a couple of opensubtitle accounts to speed up downloading subs when migrating or when my plex server crashes (again). Right now i have about 900 subtitles to be downloaded, so I would like to be able to force a retry for subtitle providers that are marked as limit exceeded. Also, when the wrong credentials are used to connect to opensubtitles, i can't retry until 10 minutes later. Could you make it possible to give the user an option to force a retry when either the download limit is exceeded or wrong credentials are given?

**Comment by morpheus65535** [comment]
In v0.9 there 's a button to reset throttling globally.
