### ISSUE TITLE
Development Branch: Text in 'Loading Series/Movies' popup misaligned

### ISSUE THREAD

**Issue by just-Addict** [morpheus65535/bazarr#1012]
When you perform an action that causes the mentioned popup to show, the text isn't properly centered in the box. 

See attached images. 
Note: the color is caused by the list being selected.

![MassEdit-Loading-Movies](https://user-images.githubusercontent.com/19715616/83806102-41b49f80-a6b1-11ea-975e-40ebad194ff3.png)
![MassEdit-Loading-Series](https://user-images.githubusercontent.com/19715616/83806103-424d3600-a6b1-11ea-9232-ffb011221b0b.png)

**Comment by morpheus65535** [comment]
Clear your cache, it's working fine for me.

**Comment by just-Addict** [comment]
browser cache or the cache folder in programdata\bazarr?

**Comment by morpheus65535** [comment]
browser cache of course if it's a rendering issue in the browser. :-)
