### ISSUE TITLE
Bazarr fresh install but doesnt't download any sub. It detects movies/series, but log says  "Path does not exist"

### ISSUE THREAD

**Issue by esturniolo** [morpheus65535/bazarr#1017]
**Describe the bug**
Same as title.
It detects all movies but when try to download the subs doesn't find the path.

**To Reproduce**
1. Setup Bazarr
2. Wait or force wanted subtitles
3. See error

**Expected behavior**
Download all or missing subtitles.

**Screenshots**
![image](https://user-images.githubusercontent.com/5169045/84679533-c7351c80-af07-11ea-8a3d-51e7661348db.png)
![image](https://user-images.githubusercontent.com/5169045/84679573-d3b97500-af07-11ea-93be-d45e788f1929.png)
![image](https://user-images.githubusercontent.com/5169045/84679615-e3d15480-af07-11ea-8ada-3b40e4ccee77.png)

**Software (please complete the following information):**
 - Bazarr 0.8.4.4
 - Radarr version 0.2.0.1480
 - Sonarr version 2.0.0.5344
 - All docker containers on Ubuntu 18.04

**Additional context**
I don't understand why Bazarr found all the movies, but says that it can't download because the path it's not valid and not exist...

I attached the logs too.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/4781547/bazarr.log)

**Comment by halali** [comment]
Come to discord for support, you haven't properly set pathmappings
