### ISSUE TITLE
Bazarr does not download subtitles automatically

### ISSUE THREAD

**Issue by vitrox64** [morpheus65535/bazarr#1018]
Dear Morpheus please you help!

Bazarr does not download subtitles automatically, but in the wanted section they will appear correctly as lost and I can click to download them manually

I am not sure is I must to configure anything else?

Subtitle folder is Alongside media file and have 777 permisson.
 
<img width="893" alt="Capture" src="https://user-images.githubusercontent.com/67041452/84862142-a02e3600-b040-11ea-8d66-2c6a4ff8f52f.PNG">

**Comment by vitrox64** [comment]
Bazarr, radarr and sonarr is in same raspberry then path for radarr and path for bazarr is equal "local Path"
Example: /media/movies that is correct?

**Comment by morpheus65535** [comment]
Don't put anything in path mapping if Bazarr can access the media files using the same path as Sonarr/Radarr.
