### ISSUE TITLE
Cannot Save Settings

### ISSUE THREAD

**Issue by burrellbloke** [morpheus65535/bazarr#102]
I have installed Bazarr on a newly created Windows 10 VM. I am running Python 2.7.15, and followed the installation instructions in the wiki.

I can start Bazarr but whenever I try to save any setting I get this error:
Error: 500 Internal Server Error
Sorry, the requested URL 'http://192.168.86.71:6767/save_settings' caused an error:

Internal Server Error
Exception:
KeyError('HTTP_REFERER',)
Traceback:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\bottle.py", line 862, in _handle
    return route.call(**args)
  File "C:\Python27\lib\site-packages\bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "bazarr.py", line 645, in save_settings
    ref = request.environ['HTTP_REFERER']
KeyError: 'HTTP_REFERER'

I have restarted the machine several times but get the same error each time.

**Comment by morpheus65535** [comment]
Your browser is probably blocking the referer header that Bazarr need to redirect you the page where you come from after saving settings. Disable any incognito or secret options your browser might have enabled.

**Comment by burrellbloke** [comment]
Doh...

Thank you.
