### ISSUE TITLE
Bazarr not downloading subtitles after giving it proper permissions

### ISSUE THREAD

**Issue by tovy14** [morpheus65535/bazarr#1020]
Hi, 

I have been scratching my head for a couple of weeks now about the downloading of subtitles. After doing a fresh install and giving the right permissions to the folders, i am running on a RPi 4: 

Bazarr Version:
0.8.4.4
Sonarr Version:
2.0.0.5344
Radarr Version:
0.2.0.1480
Operating System:
Linux-4.19.118-v7l+-armv7l-with-debian-10.4
Python Version:
3.7.3

The issue is that i have managed to download 1 out of 42 that are missing from my series. I have requested a Download of wanted files manually.

The first log is from when the 1 sub downloaded, the second one is from the next search. I used Wetransfer for lack of a better solution.
[First log](https://wetransfer.com/downloads/eae16a3cd09be8851c3f0958e57ad93120200618132605/eb513d5bddcda2dabdd4b865bf1dda2c20200618132635/0c8e34) 
[Second log](https://wetransfer.com/downloads/1bed9e89bfe7c73445fee6826a030dc320200618132720/9a54ed215dd636ed231f727cf5a620ba20200618132737/291124) 

Any help will be appreciated.

Thank you

**Comment by morpheus65535** [comment]
You can simply attach your logs by drop them in this issue comment write input box.

**Comment by tovy14** [comment]
[bazarr (4).log](https://github.com/morpheus65535/bazarr/files/4799681/bazarr.4.log)
[bazarr (5).log](https://github.com/morpheus65535/bazarr/files/4799683/bazarr.5.log)

Thanks for the info, i have attached them

**Comment by morpheus65535** [comment]
From what I can see, you require a minimum score of 90% for automatic search and there's no subtitles scoring that high. You're going to have to search manually for those missing subs.

**Comment by tovy14** [comment]
Thank you very much, i lowered the score to 60 and it got some more

**Comment by halali** [comment]
With score 60 you wil get many bad subtitles.

**Comment by tovy14** [comment]
I understand, but i tried with 80 also, and still no results

**Comment by morpheus65535** [comment]
I will close this as it isn't an issue with Bazarr. There's just not proper subtitles available for your episodes. You can try other providers  but I doubt you'll get better English subtitles from others.

**Comment by tovy14** [comment]
Thank you for all your help
