### ISSUE TITLE
Exception on /api/movie_search_missing [GET]

### ISSUE THREAD

**Issue by lukjod** [morpheus65535/bazarr#1021]
Again I'm getting such error along with Exception on /api/sync_subtitles [POST]

my setup: docker images of sonarr3 radarr and bazarr from linuxserver.io on qnap 251+ x64

Bazarr Version:
0.9
Sonarr Version:
3.0.3.892
Radarr Version:
0.2.0.1480
Operating System:
Linux-4.14.24-qnap-x86_64-with
Python Version:
3.8.3
Bazarr Directory:
/app/bazarr
Bazarr Config Directory:
/config

first log message of Exception on /api/movie_search_missing [GET] :
`Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
  rv = self.dispatch_request()
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper
  resp = resource(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask/views.py", line 89, in view
  return self.dispatch_request(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request
  resp = meth(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 56, in wrapper
  return actual_method(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 1038, in get
  movies_download_subtitles(radarrid)
 File "/app/bazarr/bazarr/get_subtitle.py", line 761, in movies_download_subtitles
  result = download_subtitle(path_mappings.path_replace_movie(movie[\path\]),
 File "/app/bazarr/bazarr/get_subtitle.py", line 241, in download_subtitle
  radarr_id=movie_metadata[\radarrId\])
TypeError: \NoneType\ object is not subscriptable`

second log message on Exception on /api/sync_subtitles [POST] ;
`Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
  rv = self.dispatch_request()
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper
  resp = resource(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask/views.py", line 89, in view
  return self.dispatch_request(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request
  resp = meth(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 56, in wrapper
  return actual_method(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 1434, in post
  srt_lang=language, media_type=media_type, radarr_id=movie_metadata[\radarrId\])
TypeError: \NoneType\ object is not subscriptable`

**Comment by morpheus65535** [comment]
Can you confirm which movie is problematic and send me your bazarr.db (can be in private) so I can investigate. It's working fine for me so I suspect some incoherence in your db.

**Comment by lukjod** [comment]
this can be connected somehow with my today change of bazarr from qnap qpkg and switch to docker. Same happen lately with sonarr but next version of bazarr simply corrected it. I was checking on random movie i picked up and ita was Bad Education (2019) [WEBDL-1080p, AAC, 5.1] In attach my databese. Maybe best way is to delete all configuration of bazarr and start from beginning in that case?
[bazarr.zip](https://github.com/morpheus65535/bazarr/files/4807933/bazarr.zip)

**Comment by morpheus65535** [comment]
All your paths have changed so the minimal that you should do is a full disk scan for both movies and series. If that doesn't make it, delete your bazarr.db and restart Bazarr. You'll have to setup languages and notifications again but the rest should be fine.

**Comment by lukjod** [comment]
nope, this did not help, will try to install it again from beginning

**Comment by lukjod** [comment]
new database in attach
[bazarr.zip](https://github.com/morpheus65535/bazarr/files/4808039/bazarr.zip)

**Comment by morpheus65535** [comment]
There's a misconfiguration with your path mapping. Can you provide a screenshot please?

**Comment by lukjod** [comment]
Hi again, if talking about sonar I have  deleted old episodes from disc but keep shows in it for future upcoming seasons, regarding radar all should be ok.
In attach screens from radarr 0.8.4.4 configuration.
Do You been configs from sonarr3 or radarr? 
[Screenshots.zip](https://github.com/morpheus65535/bazarr/files/4813870/Screenshots.zip)

**Comment by lukjod** [comment]
I mean all shows from screenshot with exclamation mark are deleted from disk
![Screenshot_20200622-165036_Firefox](https://user-images.githubusercontent.com/1781446/85301906-bdcc2700-b4a8-11ea-9a95-5fafc76ce6b4.jpg)

**Comment by lukjod** [comment]
Thank You as always,
Problem solved by deleting folder maps as advised in discord
Very Big Thank You

**Comment by EmilMoe** [comment]
If anyone knows what this Discord message is, that would be useful to know. I have the same problem, but the solution is not included here.
