### ISSUE TITLE
Bazarr won't clean-up child(ren) on SIGTERM 

### ISSUE THREAD

**Issue by maran** [morpheus65535/bazarr#1023]
**Describe the bug**
When gracefully shutting Bazarr down with a -15 it does not clean up it's children.

**To Reproduce**

1. Run `python3.7 bazarr.py`
2. Lookup the original parent pid and do a `kill PID`
3. Expect to see no more Bazarr processes but notice there is still the child process running

**Expected behavior**
Cleaning up the child (or other children if there is an event that causes more to spawn).

**Software (please complete the following information):**
 - Bazarr Master as of today.

**Additional context**
This seems to be caused by signals not being caught in the main thread, so even though there is an atexit it does not appear to catch the signal. One potential work around is to use `signal.signal` to listen to certain events in the `start_bazarr` method, expose the subprocess globally and kill it when a signal is handled in the main thread. Not sure if there is a better way of solving this, if the above method is deemed acceptable I can provide a PR.

**Comment by morpheus65535** [comment]
We've made some improvement a month ago in dev branch. Could you take a look and confirm if it work as expected?

https://github.com/morpheus65535/bazarr/blob/development/bazarr.py

**Comment by maran** [comment]
I can confirm this is solved in development! 👍
