### ISSUE TITLE
Login to Bazarr instance without using a password. 

### ISSUE THREAD

**Issue by maran** [morpheus65535/bazarr#1024]
**Describe the bug**
You can login to any running Bazarr on the development branch if the authentication is set to forms.

**To Reproduce**
1. Install two instances of Bazarr, let's call them Y and Z
2. Login to instance Y and copy the session cookie.
3. Open instance Z and create a new session cookie with the contents of Y
4. Navigate to /settings/general/ on instance Z and you will be logged in.

**Expected behavior**
You should be redirect to the login screen if the session was made for an other Bazarr instance.

**Software (please complete the following information):**
 - Bazarr on 'development' at 6f4f42bb2d93bcc18b517c3e5adb13a107c90af0

**Comment by morpheus65535** [comment]
Thank you for reporting this one, I had hard coded the Flask secret_key for testing purpose. Now I generate a random secret_key stored in config.ini and reuse it when starting Bazarr. Can you confirm if it fix this issue?

**Comment by maran** [comment]
Confirmed I can no longer login by creating a fake cookie! :)
