### ISSUE TITLE
Weird exceptions when trying to pull subtitles

### ISSUE THREAD

**Issue by phyzical** [morpheus65535/bazarr#1026]
**Describe the bug**
I just moved from the master branch to development using the linuxserver/bazarr:development docker image

Last night i was just testing stuff and i noticed that an episode would find matches but then throw the following exception
```
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
  rv = self.dispatch_request()
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper
  resp = resource(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask/views.py", line 89, in view
  return self.dispatch_request(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request
  resp = meth(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 57, in wrapper
  return actual_method(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 568, in post
  result = manual_download_subtitle(episodePath, language, audio_language, hi, forced, subtitle,
 File "/app/bazarr/bazarr/get_subtitle.py", line 476, in manual_download_subtitle
  sonarr_series_id=episode_metadata[\sonarrSeriesId\],
TypeError: \NoneType\ object is not subscriptable
```
Looking at the code its when it tries to access 'sonarrSeriesId' from a database call for the episode metadata

So i left it for the night to do episode and series syncing. in the morning the episode in question had found the subtitle, yay.

Buut if i try again for another episode of the same series and season the same issue occurs for both endpoints `api/episodes_subtitles_download` and `api/episodes_subtitles_manual_download`

```
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
  rv = self.dispatch_request()
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper
  resp = resource(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask/views.py", line 89, in view
  return self.dispatch_request(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request
  resp = meth(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 57, in wrapper
  return actual_method(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 503, in post
  result = download_subtitle(episodePath, language, audio_language, hi, forced, providers_list, providers_auth, sceneName,
 File "/app/bazarr/bazarr/get_subtitle.py", line 232, in download_subtitle
  sonarr_series_id=episode_metadata[\sonarrSeriesId\],
TypeError: \NoneType\ object is not subscriptable
```
**Expected behavior**
should find any of the available, or at very least do an index check on the db call to return a friendly error.

(i assume it doesn't cause the seriesid for an episode should always exist?)
**Screenshots**
![image](https://user-images.githubusercontent.com/5182053/86524785-6dde5e80-beb1-11ea-80b0-3512c80eeb50.png)

**Software (please complete the following information):**
 - Bazarr: development branch
 - Radarr version 0.2.0.1480
 - Sonarr version 2.0.0.5344
 - OS: docker  linuxserver/bazarr:development

**Comment by phyzical** [comment]
i wonder if something is funky with my bazarr db? 

i do have alot of series and movies incase that makes any difference

**Comment by morpheus65535** [comment]
Can you provide a debug reproducing the whole download process? I need to see the call done to the DB.

**Comment by phyzical** [comment]
righto, i turned debug back on and infact i do see things more verbose errors
like  "The show has no tvdb_id and series_tvdb_id: the search can't be done" i assume is what lines up with whats failing db side

but i also see `BAZARR Subtitles file saved to disk: /tv/Tv Shows/30 rock/season 7/30.Rock.S07E06.HDTV.x264-LOL.en.srt` so it must be working... but not working?

i also saw a "fps mismatch" 

anyway log file attached cause there is alot
[bazarr.log](https://github.com/morpheus65535/bazarr/files/4874918/bazarr.log)

**Comment by phyzical** [comment]
oh i also checked for that file in my system but it was not there

**Comment by morpheus65535** [comment]
That's really strange because Bazarr cannot found an episode in database using the provided path. Are you using path mapping?

**Comment by phyzical** [comment]
yes as its docker based so sonarr is in another docker image. the weirder thing is the first subtitle i tried that failed yesterday ended up downloading by morning 😅 

but i wouldnt doubt if it is configured wrong

so my media is located at
`/mnt/user/Media/Tv\ shows\ 1` and
`/mnt/user/Media/Tv\ shows\ 2`

then docker side
my sonar map is `/tv -> /mnt/user/Media/` (sonar has the folders added as normal)
my bazaarr map is `/tv -> /mnt/user/Media/`


then bazarr has 

![image](https://user-images.githubusercontent.com/5182053/86534325-1c15f280-bf0a-11ea-8621-b0218683b17a.png)


hmm is that the issue maybe? should it maybe be /tv -> /tv  in bazarr ?

**Comment by morpheus65535** [comment]
As written in the wiki, you don't need to put anything in path mapping if it's the same on both sides: https://github.com/morpheus65535/bazarr/wiki/Settings-General#path-mappings-for-shows

**Comment by phyzical** [comment]
👍 welll... dont i feel silly 😄 delete the mapping and bam both manual and auto grab work like a charm.

easy close for this then.

Keep up the great work my dude :)

(fyi the new integration ffsubsync how cool!)

**Comment by morpheus65535** [comment]
np mate, enjoy it!
