### ISSUE TITLE
ffsubsync can't synchronise Greek subtitles based on extracted audio

### ISSUE THREAD

**Issue by pen-ops** [morpheus65535/bazarr#1027]
Great work so far ! However, I would like to say that ffsubsync for some reason, fails to synchronise Greek subs based on extracted Audio (whether that is English or another language). When it synchronises based on another subs, it does it really well, and I am very satisfied. However with Audio it always has issues. I am on latest dev branch .

**Comment by morpheus65535** [comment]
There's nothing I can do on my side to improve ffsubsync. I suggest you open an issue on ffsubsync github if you have a specific case that can be reproduced. I've approved your feature request and will probably add an option to choose the preferred reference track (audio or subtitles).

**Comment by morpheus65535** [comment]
I was looking at Bazarr synchronization algorithm again and here's how it works (in this order):

1. Try to sync with English embedded subtitles track
2. If no English embedded subtitles track, try to sync with first embedded subtitles track
3. If no embedded subtitles track, try with the audio track where language match downloaded subtitles language
4. If no matching audio track can be found, use English audio track
5. If no English audio track is available, use the first audio track.

In your case, the video file probably doesn't include any embedded subtitles track so it fall back to Greek audio track (# 3). Would it be best to go to English audio track first then Greek audio track if no English audio track is found (swap # 3 and # 4)?

I can also add an option to prevent syncing with audio track as reference but you'll end up without any sync if there's no embedded subtitles track...

**Comment by pen-ops** [comment]
Thank you for your fast response. Thanks for looking into the algorithm, your provided information is without doubt insightful and helpful. Apologies for not specifying the audio tracks. They are 90% English audio tracks, and they dont synchronise well with Greek subs. I dont know if ffsubsync requires additional language packages for English/Greek, although it does work perfect when it synchronises based on an embedded sub.

The option to disable syncing with audio track as a reference would be amazing !

**Comment by morpheus65535** [comment]
ffsubsync doesn't require language packs or anything like that.

I'll add the option to choose in the upcoming days.
