### ISSUE TITLE
cannot download subtitles from assrt?

### ISSUE THREAD

**Issue by justinluy** [morpheus65535/bazarr#1028]
here is the debug log

[bazarr.log](https://github.com/morpheus65535/bazarr/files/4918300/bazarr.log)

**Comment by morpheus65535** [comment]
`https://api.assrt.net/v1/sub/search?token=KJZERJXFk6MwMt0EgdRinOEdpoiU9fgA&q=TheWalkingDead+S03E05&is_file=1` url is working perfectly fine for me in Bazarr and in browser (even if I reuse Bazarr user-agent). If it's still not working for you, your IP have probably been blocked by assrt (temporarily or not). HTTP 509 error code meens `Bandwidth Limit Exceeded`.

**Comment by morpheus65535** [comment]
As I cannot reproduce, I'll close this issue. Reopen it if you face it again in the future.
