### ISSUE TITLE
Betaseries API Key

### ISSUE THREAD

**Issue by hyperhydra98** [morpheus65535/bazarr#1029]
For Betaseries, it may be nice if you put the link to the API key generation page (https://www.betaseries.com/en/api/) on the "Providers" tab. I had a bit of trouble finding where I could get my API key and later realized I need to generate one as opposed to finding it in my profile.

Also, the box in Bazarr asks for the "Token/Secret Key", however when you generate a key on Betaseries, it gives you two, the "API key" and the "secret key". I initially pasted in the secret key since it matched what the text in the box said, however, I realized later (after getting errors) that I needed to paste in the API key instead. Maybe you could change the wording to say "API key" instead, or maybe throw an error when the inputted key is too long (the secret key is longer than the API key).

**Comment by morpheus65535** [comment]
Thanks for your feedback! I've made the changes in dev branch.
