### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by lennvilardi** [morpheus65535/bazarr#103]
Hi !
I use a docker image with a synology NAS and I don't know how to restart ?
I went to the docker app made a restart of the docker image but still got "Bazarr updated to latest version and need to be restarted. 3 files changed, 0 insertions(+), 0 deletions(-)"
Thanks

**Comment by morpheus65535** [comment]
I don't have a Synology so I can't confirmhow to restart a docker container.

Do you still have the banner below the "Series/Movies/History/Wanted/Settings/System" buttons? If not, you're up-to-date.

**Comment by lennvilardi** [comment]
Yes got the banner Bazarr need to be restarted to apply last update.
How to restart

**Comment by lennvilardi** [comment]
11/07/2018 18:49:45|INFO|Bazarr is started and waiting for request on http://0.0.0.0:6767/|
11/07/2018 18:50:26|INFO|Bazarr updated to latest version and need to be restarted.  3 files changed, 0 insertions(+), 0 deletions(-)|
11/07/2018 18:56:27|INFO|Bazarr has been stopped.|
11/07/2018 18:56:43|INFO|Installing Python modules required for Bazarr...|
11/07/2018 18:56:44|INFO|Required Python modules installed if missing.|
11/07/2018 18:56:45|INFO|Bazarr is started and waiting for request on http://0.0.0.0:6767/|
11/07/2018 18:57:25|INFO|Bazarr updated to latest version and need to be restarted.  3 files changed, 0 insertions(+), 0 deletions(-)|

**Comment by morpheus65535** [comment]
You did not restarted the container after updating. I suggest your read how to use docker in Synology documentation. This is not an issue with Bazarr.

**Comment by lennvilardi** [comment]
I did see the log 18:56:27 Bazarr has been stopped ant then 20s later Bazarr is started... (Just to switch a button in the control panel of Docker). I use docker for others containers and upgrading is fine.

**Comment by morpheus65535** [comment]
Bazarr has been updated after this. You need to restart it again.

**Comment by morpheus65535** [comment]
Upgrading work fine with docker for a couple of hundred of users at the moment.

**Comment by lennvilardi** [comment]
If it's working fine why I can't update ?
12/07/2018 15:14:31|INFO|Bazarr is started and waiting for request on http://0.0.0.0:6767/|
12/07/2018 15:14:56|INFO|Bazarr updated to latest version and need to be restarted.  3 files changed, 0 insertions(+), 0 deletions(-)|
12/07/2018 15:20:21|INFO|Installing Python modules required for Bazarr...|
12/07/2018 15:20:22|INFO|Required Python modules installed if missing.|
12/07/2018 15:20:23|INFO|Bazarr is started and waiting for request on http://0.0.0.0:6767/|
12/07/2018 15:20:42|INFO|Bazarr updated to latest version and need to be restarted.  3 files changed, 0 insertions(+), 0 deletions(-)|
12/07/2018 15:21:00|INFO|Installing Python modules required for Bazarr...|
12/07/2018 15:21:01|INFO|Required Python modules installed if missing.|
12/07/2018 15:21:02|INFO|Bazarr is started and waiting for request on http://0.0.0.0:6767/|
12/07/2018 15:21:59|INFO|Bazarr updated to latest version and need to be restarted.  3 files changed, 0 insertions(+), 0 deletions(-)|

**Comment by morpheus65535** [comment]
12/07/2018 15:21:59|INFO|Bazarr updated to latest version and need to be restarted. 3 files changed, 0 insertions(+), 0 deletions(-)|

It is updated. You only need to restart the container.

**Comment by lennvilardi** [comment]
Already done many times :
 12/07/2018 15:14:31|INFO|Bazarr is started and waiting for request on http://0.0.0.0:6767/|
 12/07/2018 15:20:23|INFO|Bazarr is started and waiting for request on http://0.0.0.0:6767/|
 12/07/2018 15:21:02|INFO|Bazarr is started and waiting for request on http://0.0.0.0:6767/|

**Comment by morpheus65535** [comment]
```
12/07/2018 15:21:02|INFO|Bazarr is started and waiting for request on http://0.0.0.0:6767/|
12/07/2018 15:21:59|INFO|Bazarr updated to latest version and need to be restarted. 3 files changed, 0 insertions(+), 0 deletions(-)|
```

You understand, by looking at the timestamp, that it's been updated after your last restart?

**Comment by lennvilardi** [comment]
I've restarted the container many time and it's still in 0.5.4 and when I search for an update it always find one.
At 15:14:31 I've started the container. At 15:14:56 I've Update bazarr from source on Github. At 15:20:23 I have restarted the container and again it find the same update (at 15:20:42) and I restarted again at 15:21:02

**Comment by lennvilardi** [comment]
Sorry.
I'm updating from master.

**Comment by morpheus65535** [comment]
Could you give me the return from:

    docker inspect <CONTAINERID>

Where <CONTAINERID> is your Bazarr container name?

**Comment by lennvilardi** [comment]
I've try the development branch

> 12/07/2018

 18:36:08|INFO|Settings saved succesfully.|
12/07/2018 18:36:19|INFO|Bazarr updated to latest version and need to be restarted.  18 files changed, 168 insertions(+), 296 deletions(-)|
12/07/2018 18:37:18|INFO|Installing Python modules required for Bazarr...|
12/07/2018 18:37:19|INFO|Required Python modules installed if missing.|
12/07/2018 18:37:20|INFO|Bazarr is started and waiting for request on http://0.0.0.0:6767/|
12/07/2018 18:38:06|INFO|Bazarr updated to latest version and need to be restarted.  3 files changed, 0 insertions(+), 0 deletions(-)|
12/07/2018 18:38:50|INFO|Installing Python modules required for Bazarr...|
12/07/2018 18:38:50|INFO|Required Python modules installed if missing.|
12/07/2018 18:38:51|INFO|Bazarr is started and waiting for request on http://0.0.0.0:6767/|
12/07/2018 18:39:09|INFO|Bazarr updated to latest version and need to be restarted.  3 files changed, 0 insertions(+), 0 deletions(-)|

> 
But sill got 3 files not updating

**Comment by lennvilardi** [comment]
`[`
    {
        "Id": "8e198ceaea22604e992503ddb7972f33d2b85778edbc4e77a8f9d6adc099e323"                                                                                                                                                             ,
        "Created": "2018-07-11T21:48:31.308077072Z",
        "Path": "/init",
        "Args": [
            "python",
            "/bazarr/bazarr.py"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 21497,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-07-12T16:38:49.723266561Z",
            "FinishedAt": "2018-07-12T16:38:46.741543438Z",
            "StartedTs": 1531413529,
            "FinishedTs": 1531413526
        },
        "Image": "sha256:32ec80c2b3ab1957dbdba50755116f8436b87dc606462e2fda7f4d5                                                                                                                                                             6911fbdb4",
        "ResolvConfPath": "/volume1/@docker/containers/8e198ceaea22604e992503ddb                                                                                                                                                             7972f33d2b85778edbc4e77a8f9d6adc099e323/resolv.conf",
        "HostnamePath": "/volume1/@docker/containers/8e198ceaea22604e992503ddb79                                                                                                                                                             72f33d2b85778edbc4e77a8f9d6adc099e323/hostname",
        "HostsPath": "/volume1/@docker/containers/8e198ceaea22604e992503ddb7972f                                                                                                                                                             33d2b85778edbc4e77a8f9d6adc099e323/hosts",
        "LogPath": "/volume1/@docker/containers/8e198ceaea22604e992503ddb7972f33                                                                                                                                                             d2b85778edbc4e77a8f9d6adc099e323/log.db",
        "Name": "/morpheus65535-bazarr",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/volume1/video/Series:/tv:rw",
                "/volume1/docker/bazarr:/bazarr/data:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "db",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": [],
            "CapDrop": [],
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/b                                                                                                                                                             in",
                "PS1=$(whoami)@$(hostname):$(pwd)$ ",
                "HOME=/root",
                "TERM=xterm",
                "PYTHONIOENCODING=UTF-8",
                "PGID=100",
                "PUID=1026",
                "TZ=Europe/Paris"
            ],
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 50,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": null,
            "Name": "aufs"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/volume1/video/Series",
                "Destination": "/tv",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/volume1/docker/bazarr",
                "Destination": "/bazarr/data",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "49de5db11c90984af527e7a4822f9a4981e618105fd73f461f637c8                                                                                                                                                             c58a83820",
                "Source": "/volume1/@docker/volumes/49de5db11c90984af527e7a4822f                                                                                                                                                             9a4981e618105fd73f461f637c8c58a83820/_data",
                "Destination": "/movies",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "morpheus65535-bazarr",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "6767/tcp": {}
            },
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/b                                                                                                                                                             in",
                "PS1=$(whoami)@$(hostname):$(pwd)$ ",
                "HOME=/root",
                "TERM=xterm",
                "PYTHONIOENCODING=UTF-8",
                "PGID=100",
                "PUID=1026",
                "TZ=Europe/Paris"
            ],
            "Cmd": [
                "python",
                "/bazarr/bazarr.py"
            ],
            "Image": "morpheus65535/bazarr:latest",
            "Volumes": {
                "/bazarr/data": {},
                "/movies": {},
                "/tv": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/init"
            ],
            "OnBuild": null,
            "Labels": {},
            "DDSM": false
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "25734fc2784571da0ff44f1451957597064c1c616471c58b3d7d3c                                                                                                                                                             a802bae3b3",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/default",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "6d96317584bc0d9377dc532af8442b69c70cd2eba63ecc                                                                                                                                                             26cab3038a395be873",
                    "EndpointID": "a85afcde70c40e569ee69ee666ebb0543b92a3b7d2102                                                                                                                                                             51a9823cd895980c1dd",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
        }
    }
]

**Comment by morpheus65535** [comment]
Looks good. Could you try to execute inside the container a "git pull" inside the /bazarr directory?

**Comment by lennvilardi** [comment]
sudo docker exec -it morpheus65535-bazarr bash
Password:
root@morpheus65535-bazarr:/$ cd bazarr
root@morpheus65535-bazarr:/bazarr$ ls
Dockerfile                get_movies.py            notifier.py
Dockerfile.amd64          get_movies.pyc           notifier.pyc
Dockerfile.arm64          get_providers.py         requirements.txt
Dockerfile.armhf          get_providers.pyc        root
LICENSE                   get_radarr_settings.py   scheduler.py
README.md                 get_radarr_settings.pyc  scheduler.pyc
bazarr.py                 get_series.py            screenshot
check_update.py           get_series.pyc           static
check_update.pyc          get_sonarr_settings.py   update_db.py
create_db.sql             get_sonarr_settings.pyc  update_db.pyc
data                      get_subtitle.py          update_modules.py
get_episodes.py           get_subtitle.pyc         update_modules.pyc
get_episodes.pyc          init_db.py               utils.py
get_general_settings.py   init_db.pyc              utils.pyc
get_general_settings.pyc  libs                     views
get_languages.py          list_subtitles.py
get_languages.pyc         list_subtitles.pyc
root@morpheus65535-bazarr:/bazarr$ git clone https://github.com/morpheus65535/ba                                                                                                                                                             zarr.git
Cloning into 'bazarr'...
remote: Counting objects: 2261, done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 2261 (delta 28), reused 40 (delta 12), pack-reused 2193
Receiving objects: 100% (2261/2261), 7.51 MiB | 2.87 MiB/s, done.
Resolving deltas: 100% (1402/1402), done.

**Comment by lennvilardi** [comment]
And now I get Bazarr updated to latest version and need to be restarted. 4 files changed, 1 insertion(+), 1 deletion(-)

**Comment by lennvilardi** [comment]
root@morpheus65535-bazarr:/bazarr$ git pull https://github.com/morpheus65535/bazarr.git                                                                                                                                                      From https://github.com/morpheus65535/bazarr
 * branch            HEAD       -> FETCH_HEAD
Already up to date.

root@morpheus65535-bazarr:/bazarr$ git pull https://github.com/morpheus65535/bazarr.git development
From https://github.com/morpheus65535/bazarr
 * branch            development -> FETCH_HEAD
Already up to date.

**Comment by morpheus65535** [comment]
And if you restart?

**Comment by lennvilardi** [comment]
Same

**Comment by morpheus65535** [comment]
I seriously don't know what could be causing this issue and I can't reproduce it. You could try to start from scratch or, at least, recreate the container after pulling the last version of the image.

**Comment by morpheus65535** [comment]
Are you still having an issue?
