### ISSUE TITLE
Initial Configuration of Large Library

### ISSUE THREAD

**Issue by ShadowKindjal** [morpheus65535/bazarr#1031]
**Bug**
Bazarr seems to become unresponsive during my initial configuration of all my subtitles. Prior to installing Bazarr, I had 2631 movies in Radarr and 585 series in Sonarr. As part of the initial configuration, the wiki recommends using the mass editor to set the desired language for all series and movies but attempting to do this seems to use a lot of resources. This results in not only Bazarr slowing down to a crawl but all of the other docker containers as well.

**Additional context**
A snippet of my logs (with debug logging enabled) can be found here: 
[bazarr.debug.log](https://github.com/morpheus65535/bazarr/files/4966777/bazarr.4.log)

**Software:**
 - Bazarr: 0.9 dev
 - Radarr: 3.0.3.899
 - Sonarr: 0.2.0.1504
 - OS: Ubuntu 20.04 LTS (Linux-5.4.0-40-generic-x86_64-with)

**System Configuration**
 - Intel i7-4820k
 - 32GB DDR3 Ram
 - OS Drive: 500GB SSD
 - Zpool: 10x 10TB WD Red Hard Drives

**Comment by morpheus65535** [comment]
I guess you're using v0.9 in dev branch? For each changes, Bazarr send an event to connected browser to update the datatables but I guess that there's to much event sent and it makes Bazarr unresponsive. I'll look into this.

**Comment by ShadowKindjal** [comment]
> I guess you're using v0.9 in dev branch?

I'm sorry for not making this clear. Yes, I'm using v0.9 in the dev branch.

**Comment by morpheus65535** [comment]
Should be better now but there's still room for improvement by doing executemany.

**Comment by morpheus65535** [comment]
I guess everything is fine now. I'll close this issue. Re-open it if required.
