### ISSUE TITLE
opensubtitles retry interval by a download limit is to low (10 minutes instead of 6 hours)

### ISSUE THREAD

**Issue by PotatoQuality** [morpheus65535/bazarr#1032]
**Describe the bug**
Bazarr retry interval for opensubtitles provider when you reached your download limit (In my case, 1000 (vip)) is 10 minutes instead of 6 hours.
Bazarr keeps retrying every 10 minutes

**To Reproduce**
1. Search for subtitles
2. Reached your download limit for opensubtitles
3. Bazarr retry count is 10 minutes.

**Expected behavior**
I except an higher retry interval ten 10 minutes.

**Screenshots**
![image](https://user-images.githubusercontent.com/2944704/88459327-d60ed780-ce94-11ea-8969-dc4c05f265a2.png)

![image](https://user-images.githubusercontent.com/2944704/88458382-f12a1900-ce8d-11ea-9e57-5e280578ede8.png)

**Software (please complete the following information):**
 - Bazarr: 0.8.4.4
 - Radarr version [e.g. v 0.2.0.0001]
 - Sonarr version [e.g. v 2.0.0.0001]
 - OS: Unraid 6.8.3

**Additional context**

**Comment by morpheus65535** [comment]
I've just pushed a fix to dev branch that should fix this issue. Please test and report.

**Comment by PotatoQuality** [comment]
looking good!!!
