### ISSUE TITLE
Search for wanted Movies Subtitles fails on sync step (V0.9)

### ISSUE THREAD

**Issue by PotatoQuality** [morpheus65535/bazarr#1033]
**Describe the bug**
Execute movie subtitles search, it will crash after a minut of 3 a 4 it will crash.

**To Reproduce**
1.Execute movie subtitles search
2. Wait
3. Execute failed

**Expected behavior**
Finishing without an error ;)

**Screenshots**

**Software (please complete the following information):**
- Bazarr Version: 0.9
- Sonarr Version: 3.0.3.899
- Radarr Version: 0.2.0.1504
- Operating System: Linux-4.19.107-Unraid-x86_64-with

**Additional context**
Debug logs:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/4978967/bazarr.log)

**Comment by morpheus65535** [comment]
This is an issue with this subtitles (`/movies/Films 1080P/Promare (2019)/Promare.2019.REPACK.1080p.BluRay.FLAC.5.1.x265-Meakes.mkv-xpost.en.srt`) and ffsubsync:

`raise SRTParseError(expected_start, actual_start, unmatched_content)srt.SRTParseError: Expected contiguous start of match or end of input at char 0, but started at char 92 (unmatched content: '00:00:00,000 --> 00:00:00,000\nsubtitles edited and timed by sunshinesubs @ subscene & tumblr')`

Did you try to blacklist this subtitles and get another one?

@smacke is this a known issue or could you give some tips to fix the issue?

**Comment by PotatoQuality** [comment]
Hi @morpheus65535,

The subtitle wasn't on my history movies list, so im unable to blacklist it.
For debug purpose, here is the subtitle that triggering the error
[subtitle.zip](https://github.com/morpheus65535/bazarr/files/4980742/subtitle.zip)

**Comment by morpheus65535** [comment]
I've improved the exception management when trying to sync a subtitles. If something goes wrong, only the sync should fail and the rest of the process should go as planned (including history logging). Can you test it please?

**Comment by smacke** [comment]
@morpheus65535  the original issue should only occur if the subtitle is malformed somehow, in which case the `srt` package throws an error.

**Comment by morpheus65535** [comment]
> @morpheus65535 the original issue should only occur if the subtitle is malformed somehow, in which case the `srt` package throws an error.

Thanks mate for the feedback! Really appreciated :-)

**Comment by PotatoQuality** [comment]
Still testing the fix, a lot of providers are down at the moment, so im unable to test it right now :(

**Comment by PotatoQuality** [comment]
Its fixed, i see a nice error message in the logs and the search continu's.

Thanks @morpheus65535, you can this one

**Comment by morpheus65535** [comment]
Thanks!
