### ISSUE TITLE
ffsubsync fails on Bazarr's end but works fine if done manually

### ISSUE THREAD

**Issue by incognit-o** [morpheus65535/bazarr#1035]
**Describe the bug**

When Bazarr syncs a sub via ffsubsync, it will always fail. Here is the log with debug turned on:
https://gist.github.com/incognit-o/067d792acffa54845ec1c5b56eb5c58d

ffsubsync will successfully sync my subs ONLY when I do it manually via terminal:
https://i.imgur.com/TOjJerD.png

**Expected behavior**
ffsubsync via bazarr and manual should have the same result.

**Software (please complete the following information):**
 - Bazarr: [v0.9]
 - OS: Ubuntu; hortio's unstable bazarr docker image

**Comment by morpheus65535** [comment]
We are probably not using the same reference track as you do (you probably default to first audio trask).

I've added more logging to better know which track is used. Can you give it a try?

**Comment by incognit-o** [comment]
> We are probably not using the same reference track as you do (you probably default to first audio trask).
> 
> I've added more logging to better know which track is used. Can you give it a try?

https://gist.github.com/incognit-o/c86199a0351780a3d38753a016d1fba6

I don't see any changes to the logging.

I'm on this version of Bazarr that was built 2 hours ago, you pushed your commit 3 hours ago at the time of writing.
https://github.com/hotio/docker-bazarr/commit/2ac905d78098243b75a40d1e81d64c8de517f377

**Comment by morpheus65535** [comment]
We now have confirmation of which track was used as reference: `BAZARR unable to sync subtitles using first audio track(a:0): /gmedia/plex/movies/Bullitt (1968)/Bullitt.en.srt`

What version of ffsubsync are you using for your test? The one included in Bazarr could be different.

**Comment by incognit-o** [comment]
Makes sense. I'm using ffsubsync 0.4.6 (latest stable) on the host computer. I'm not really sure how to extract the version number from the ffsubsync included with Bazarr but I'm pretty sure you already know that.

**Comment by morpheus65535** [comment]
> Makes sense. I'm using ffsubsync 0.4.6 (latest stable) on the host computer. I'm not really sure how to extract the version number from the ffsubsync included with Bazarr but I'm pretty sure you already know that.

We are using sources from master branch that are newer than 0.4.6 release. There's no way we can go back to 0.4.6 as it doesn't give us the opportunity to choose de reference track. I guess the only option here is to open an issue on ffsubsync github.
