### ISSUE TITLE
HTTPS connection messing with bazarr

### ISSUE THREAD

**Issue by virusperfect** [morpheus65535/bazarr#1037]
**Describe the bug**
When connecting to Bazarr remotely via HTTPS I can't save changes in the settings. When I connect via localhost (HTTP) everything works.

**To Reproduce**
1. Connect to Bazarr via HTTPS
2. Try changing a setting (as an example enable Adaptive Searching in the Subtitles settings)
3. Click on the "Save" button. The button will not work and when reloading the site all changes are gone.

**Expected behavior**
The changes in the settings should be saved just like they would if not connected via HTTPS.

**Software (please complete the following information):**
 - Bazarr: v 0.9
 - Radarr version 0.2.0.1504
 - Sonarr version 3.0.3.904
 - OS: Ubuntu 20.04.1 LTS

**Additional context**
The browser console shows this warning:
DevTools failed to load SourceMap: Could not load content for https://example.com/bazarr/static/css/bootstrap-select.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE (there are lots of other files with the same error)

**Comment by morpheus65535** [comment]
I guess you are using Organizr authentication? HTTPS provided by nginx or apache reverse proxy are working great but Organizr have been known to mess with cookies.

**Comment by virusperfect** [comment]
Yes you are right. HTTPS wasn't the problem. Turning off Organizr authentication for Bazarr fixed it. Is there a reason why other services work (like Sonarr or Radarr) and the new version of Bazarr doesn't?

**Comment by morpheus65535** [comment]
> Is there a reason why other services work (like Sonarr or Radarr) and the new version of Bazarr doesn't?

Because they don't share a single line of code. 😜 

To be honest I've never tried Organizr authentication as I rely on my own 2FA Nginx reverse proxy authentication. I would have to install it and see how it works and find what's the problem.

**Comment by virusperfect** [comment]
Ok makes sense😂. It's not a big deal anyway.
Thank you for your help!
