### ISSUE TITLE
404 Console errors

### ISSUE THREAD

**Issue by esticle** [morpheus65535/bazarr#1039]
**Describe the bug**

Whilst attempting to figure out why v0.9 gives me a lot of 'backend connection lost' errors I noticed a couple of 404's on the console in v0.9

**To Reproduce**
1. Force-refresh the root URL
2. In Chrome, F12 -> Console
4. See errors

**Expected behavior**

404's are not expected. Unsure about the 401 as it might be my RP.

**Screenshots**

```
12:21:03.569 manifest.json:1 GET https://xx.xx/static/manifest.json 401
12:21:03.569 manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
12:21:12.176 DevTools failed to load SourceMap: Could not load content for https://xx.xx/static/css/icons/material-design-iconic-font/css/materialdesignicons.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
12:21:12.176 DevTools failed to load SourceMap: Could not load content for https://xx.xx/static/css/bootstrap-select.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
12:21:12.177 DevTools failed to load SourceMap: Could not load content for https://xx.xx/static/css/bootstrap-slider.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
12:21:12.264 DevTools failed to load SourceMap: Could not load content for https://xx.xx/static/js/socket.io.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
12:21:12.264 DevTools failed to load SourceMap: Could not load content for https://xx.xx/static/js/bootstrap-select.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Software (please complete the following information):**
 - Bazarr: v0.9
 - OS: Linuxserver.io Docker / Ubuntu 18.04

**Comment by morpheus65535** [comment]
I don't get 401 error but I've fixed most of the 404 that were related to SourceMap file missing. The only one remaining is the one from bootstrap-slider. I cannot fix it as the dev behind this plugin doesn't provide map file.
