### ISSUE TITLE
Radarr and Bazarr movie list out of sync; how to manually delete?

### ISSUE THREAD

**Issue by stefandevo** [morpheus65535/bazarr#104]
I regularly remove movies out of the Radarr list becuase I move around files and once Bazarr has found subtitles it's not necessary for me to manage Radarr movies.
But when I delete movies out of Radarr they are not deleted in the list of Bazarr. Is there a way to delete these, either manually, but most prefer that Bazarr does this automatically.

I think the same happens with series in Sonarr.

Thanks for looking into it! GREAT tool BTW!!!

**Comment by morpheus65535** [comment]
Normaly that should be already done by Bazarr automatically: https://github.com/morpheus65535/bazarr/blob/8825a83c957d40db59543baa657b0179a3ad6701/get_movies.py#L82-L86

**Comment by stefandevo** [comment]
That's weird because my two lists are out of sync. Is there any log I can provide?
I just did a sync of both systems, and in Bazarr my deleted movies are still there.

**Comment by morpheus65535** [comment]
Merged to master. You can give it a try and give me feedback please? Only movies weren't removed.

**Comment by stefandevo** [comment]
I have v0.5.4 -- will it take some time to get this patch?

**Comment by morpheus65535** [comment]
You can force an update in task right now. You should get 0.5.5.

**Comment by stefandevo** [comment]
Working! Movies are synced!
Thanks!
