### ISSUE TITLE
LegendasDivx and legendas.tv - Problem downloading subtitles

### ISSUE THREAD

**Issue by khr0n** [morpheus65535/bazarr#1040]
**Describe the bug**
LegendasDivx is not wotking, it keeps calling an error.
Legendas.tv most of the times gives 404 error

**To Reproduce**

1. Enable LegedasDivx and Legendas.tv as a provider'
2. Search for subtitles

**Expected behavior**
Subtitles download

**Screenshots**
![123](https://user-images.githubusercontent.com/20689862/88807015-1332dc80-d1a9-11ea-81d6-e15aaf99d32a.png)

Throttling legendastv for 10 minutes, until 20/07/29 14:24, because of: HTTPError. Exception info: '404 Client Error: Not Found for url: http://legendas.tv/notfound'
Throttling legendasdivx for 20 minutes, until 20/07/29 13:59, because of: ServiceUnavailable. Exception info: 'LegendasDivx.pt :: Uncaught error: %r'

**Software (please complete the following information):**
 - Bazarr: [v.0.9]
 - Radarr version [0.2.0.1504]
 - Sonarr version [2.0.0.5344]
 - OS: [Windows 10]

**Comment by morpheus65535** [comment]
Legendas.tv is working properly for me. Can you provide a debug log while reproducing the search (reset providers throttling first).

I can't do nothing for LegendasDivx.pt as I don't have an account and registrations are closed.

**Comment by khr0n** [comment]
as requested i attached the log.
as for legendasdivx i will try to get an account so you can check, but manually its working.
previous version of bazarr was working.


[bazarr.log](https://github.com/morpheus65535/bazarr/files/4995421/bazarr.log)

**Comment by morpheus65535** [comment]
@josdion did you made changes to LegendasDivx?

**Comment by khr0n** [comment]
no.
all settigs are the same.
this only happened after the update of bazarr

**Comment by morpheus65535** [comment]
@khr0n the question wasn't for you. :-P

Do you have lxml module installed? It's in requirements.txt and is required by Legendas.tv.

**Comment by khr0n** [comment]
@morpheus65535 , sorry for that.
legendas.tv is working now,
only legedasdivx not working

**Comment by morpheus65535** [comment]
NP. We'll wait for @josdion feedback before going further in investigation.

**Comment by morpheus65535** [comment]
@redglory I see that you've made some changes in May. Could it be causing issue? Can you confirm if it works for you?

**Comment by josdion** [comment]
> 
> 
> @josdion did you made changes to LegendasDivx?

I don't think so. I've changed subdivx using some of the code from legendasdivx .

**Comment by morpheus65535** [comment]
> > @josdion did you made changes to LegendasDivx?
> 
> I don't think so. I've changed subdivx using some of the code from legendasdivx .

Oh, ok perfect then. Thanks!

**Comment by khr0n** [comment]
new debug log.
hope this helps solving the issue.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5002874/bazarr.log)

**Comment by morpheus65535** [comment]
@redglory this one's for you! :-)

**Comment by redglory** [comment]
> @redglory this one's for you! :-)

Ok I'll take a look :)

**Comment by redglory** [comment]
@khr0n what branch are you using?

@morpheus65535, it seems to be related to cloudscraper. This lib has been updated on past 2/3 weeks.

I'm using RetryingCFSession from libs/subliminal_patch/http.py which inherits from CloudScraper

@khr0n 's query got redirected (too much downloads ?!) and the culprit code was:
`        # Check if Cloudflare anti-bot is on
        try:
            if self.isChallengeRequest(resp):
                if resp.request.method != 'GET':
                    # Work around if the initial request is not a GET,
                    # Supersede with a GET then re-request the original METHOD.
                    CloudScraper.request(self, 'GET', resp.url)
                    resp = ourSuper.request(method, url, *args, **kwargs)
                else:
                    # Solve Challenge
                    resp = self.sendChallengeResponse(resp, **kwargs)`

**Comment by morpheus65535** [comment]
@redglory I've rolled back to previous version of CF libs as it was causing issues with other providers also.

@khr0n can you confirm if the issue is still there in latest dev branch?

**Comment by khr0n** [comment]
@morpheus65535 is there any way i can use (update) bazarr to run on dev branch on windows 10?

**Comment by morpheus65535** [comment]
https://github.com/morpheus65535/bazarr/wiki/Installation#windows

**Comment by morpheus65535** [comment]
@khr0n following our discussion on Discord, can I consider this one as fixed?

**Comment by n0pe0n** [comment]
I'm still having difficulties, still continue to make the same mistake as our friend @khr0n.

right now it's running on version 9.01 and the old one I had (v0.8.4.4) this provider worked perfect.

**Comment by khr0n** [comment]
Yes. its fixed for me in dev branch.

**Comment by n0pe0n** [comment]
here is also solved! v0.9.0.2 works well!
