### ISSUE TITLE
FreeNas UI

### ISSUE THREAD

**Issue by ToonVanEyck** [morpheus65535/bazarr#1041]
**Describe the bug**
The UI changed its look

**Expected behavior**
The first time I installed the plugin the UI looked like the picture in the Repo (like sonarr and radarr) But it suddenly changed.

**Screenshots**
![image](https://user-images.githubusercontent.com/24410099/88932561-89edd980-d27e-11ea-842c-b61d3139d909.png)

**Software (please complete the following information):**
 - Bazarr: v0.9
 - OS: FreeNas Plugin

**Comment by morpheus65535** [comment]
I'm aware as I'm the one who developed it... what is the issue with the new UI?

**Comment by ToonVanEyck** [comment]
Well originally it looked like sonarr and radarr, I didn't know you changed it on purpose. Any reason why you changed it? I kinde liked it all looking the similar...

**Comment by morpheus65535** [comment]
You should take a look at Sonarr and Radarr in version 3. New UI is based on the new UI of those two.

Also: Thanks!
