### ISSUE TITLE
Error trying to get video information for this file

### ISSUE THREAD

**Issue by doopler** [morpheus65535/bazarr#1045]
bazarr stopped searching for subtitles completely after 0.9 update, i looked in logs and i got many error messages saying "Error trying to get video information for this file:..."
i have attached a screenshot of one of the logs.
thanks.
![image](https://user-images.githubusercontent.com/42199374/89129784-dea48500-d508-11ea-8692-923fcb4c76e3.png)

**Comment by halali** [comment]
You have missing ffprobe Install it by apt

**Comment by morpheus65535** [comment]
Can you confirm that installing ffmpeg/ffprobe fixed the issue?

**Comment by doopler** [comment]
it was installed already but something has changed. i reinstalled ffmpeg in terminal (i'm using macos 10.14.6) and now it works when i launch it in terminal but when  i load the launch agent i get the same error

**Comment by morpheus65535** [comment]
I'm not very comfortable with MacOS but I guess there's something wrong with ffmpeg access for the user running your launch agent.

**Comment by doopler** [comment]
thats weird because i have ffmpeg installed.i also reinstalled python and ffmpeg but i still get that error.

**Comment by morpheus65535** [comment]
I've included MacOS ffmpeg/ffprobe binaries in Bazarr source so you wont need to install it by yourself anymore. It's available in dev branch (0.9.0.2) for now. Can you test it?

**Comment by doopler** [comment]
yes i will test it later today.
thanks

**Comment by morpheus65535** [comment]
Another user confirmed it works on Discord. I'll close it but don't hesitate to comment again if it's not working for you.

**Comment by doopler** [comment]
just tested it on 9.0.2 and it seems to be working again.
thank you 👍
