### ISSUE TITLE
Increase menu contrast

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#1046]
Nice work with the new version. The only issue I have found is the text contrast in the menu. It's really hard to read the selected items (history / series) with dark background. I don't like the purple color neither but that is a personal taste. Maybe a lighter purple in the header and the menu....

![image](https://user-images.githubusercontent.com/10577978/89130948-b23d3880-d509-11ea-883d-14986983a53d.png)

UPDATE: The logo in the left menu is a bit weird. It should be aligned with the menu items and maybe fill the empty space with the word "Bazarr". IMHO it's easy to create a new img with the logo + title than trying to align the image with the text with CSS.

**Comment by morpheus65535** [comment]
I'm aware that purple text on dark grey is kinda hard to read. I haven't decided how I'll fix it yet but I have it on my to-do list. As for the logo, I have a lot of thing on my plate most critical than this ;-)

**Comment by morpheus65535** [comment]
Can you take a look at the latest commit I did? This should make it easier to read.

**Comment by ngosang** [comment]
The text is now readable, but the UI looks really bad.
I think you should revert those changes and take your time to find a better solution.
![imagen](https://user-images.githubusercontent.com/10577978/89223892-de26ef80-d5d7-11ea-8dad-a5c3df3911dc.png)

**Comment by morpheus65535** [comment]
I agree, it was ugly! ;-)

What do you think about my last commit?

**Comment by ngosang** [comment]
Much better!
