### ISSUE TITLE
Show expand / cursor in the season list

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#1047]
This is a minor thing. It's not clear in the UI if you can expand the season (click in season to see the episodes) or if the Season is empty (no episodes). I don't know what will be the better way. Click cursor + hover text, expand arrows...
![image](https://user-images.githubusercontent.com/10577978/89131078-7fe00b00-d50a-11ea-8b82-8346477d217d.png)

**Comment by morpheus65535** [comment]
Fixed in v0.9.0.2 in dev branch.

**Comment by ngosang** [comment]
Nice. Could you change the cursor?
https://www.w3schools.com/cssref/playit.asp?filename=playcss_cursor&preval=pointer

**Comment by morpheus65535** [comment]
> Nice. Could you change the cursor?
> https://www.w3schools.com/cssref/playit.asp?filename=playcss_cursor&preval=pointer

Done

**Comment by ngosang** [comment]
Nice
