### ISSUE TITLE
Restart / shutdown features are not intuitive

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#1048]
You have to click the "user" icon to restart? You should change the "user" icon with a "shutdown" icon. Or move those features to the System tab.
![image](https://user-images.githubusercontent.com/10577978/89131182-25937a00-d50b-11ea-8553-23f8f341ec6a.png)

**Comment by morpheus65535** [comment]
This is exactly the same design as other *arr software based on Sonarr v3 UI. We won't change that.
