### ISSUE TITLE
Suggestion: blacklist certain subtitles and make Bazarr search for alternative

### ISSUE THREAD

**Issue by stefandevo** [morpheus65535/bazarr#105]
Hi,
In Sonarr there is an option that if the release is not good enough (for example bad size, format, etc) you can blacklist that certain release and let Sonarr search for alternatives.
Would be great if you could do this with .srt files also! Sometimes the srt is wrong, out of sync or sometimes even wrong language (not fault of Bazarr of course). Currently there is no way to blacklist that srt in Bazarr; would be great if this feature would exist!

**Comment by morpheus65535** [comment]
Unfortunately, I have no way of excluding a subtitles when Subliminal do the scoring. :-/
