### ISSUE TITLE
The notification badge is hidden

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#1051]
The notification badge (wanted subtitles) is hidden. I have to click in wanted to see it. I think you should show the sum of sub-badges in the "wanted" menu.
![image](https://user-images.githubusercontent.com/10577978/89132512-00a40480-d515-11ea-8b96-d4c429956798.png)

**Comment by morpheus65535** [comment]
That's not an issue, that's a feature request. You can make a PR of create a feature request.

**Comment by ngosang** [comment]
I disagree. In the previous UI I could see all alerts/badges at a glance. With the changes I have to click on all the sections to see the hidden alerts. I think it is a major setback.

**Comment by morpheus65535** [comment]
Should match your expectations now.

**Comment by ngosang** [comment]
It's perfect now. Thank you!
