### ISSUE TITLE
Error in manual sub upload form

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#1052]
The first time I manually upload a subtitle from the UI everything is fine.
If I try to upload another subtitle (without reloading the browser page) I see the from already filled with the previous upload. The button is spinning.
![image](https://user-images.githubusercontent.com/10577978/89132869-7e690f80-d517-11ea-9435-0f5599928116.png)

**Comment by morpheus65535** [comment]
Fixed in v0.9.0.2 in dev branch.
