### ISSUE TITLE
Unable to sync subtitles

### ISSUE THREAD

**Issue by jasonsansone** [morpheus65535/bazarr#1054]
**Describe the bug**
On a majority of my titles, the new sync feature errors out with:

"BAZARR unable to sync subtitles using English embedded subtitle track(s:0):
Synchronization failed; consider passing --max-offset-seconds with a number larger than 600"

A log is attached.  The files are in an MKV container, x265 video codec for the video stream, with PGS subtitle streams.  They are re-encodes of disc remuxes.

**To Reproduce**
Add new subtitles for movies and wait to attempted auto-sync.

**Expected behavior**

**Screenshots**

Software:
Bazarr Version: 0.9.0.2
Sonarr Version:
Radarr Version: 3.0.0.3352
Operating System: FreeBSD-12.1-STABLE-amd64-64bit-ELF
Python Version: 3.7.8
Bazarr Directory: /root/bazarr
Bazarr Config Directory: /root/bazarr/data

[bazarr.log](https://github.com/morpheus65535/bazarr/files/5016412/bazarr.log)

**Comment by morpheus65535** [comment]
I've just push a potential fix in dev branch. Could you test it and report? Thanks!

**Comment by jasonsansone** [comment]
Thank you for your prompt attention and awesome development of this tool!  I appreciate it.

Can I update from within Bazarr using Tasks to update on the dev branch or do I need to manually download or build a release?  I clicked to force update on Tasks, it still indicates 0.9.0.2 under Status, and there is no change when attempting to sync.

**Comment by morpheus65535** [comment]
How did you install? Using Docker image (which one?)? From sources? Some strange package built by someone else than me? :-)

**Comment by jasonsansone** [comment]
My system, is [TrueNAS 12-BETA](https://www.ixsystems.com/blog/truenas-12-beta/) (formerly FreeNAS) which is based on FreeBSD 12.1.  I am running a jail.  I installed using the [wiki instructions](https://github.com/morpheus65535/bazarr/wiki/Installation#freebsd).  After installing, I changed the release branch from master to development while I was attempting to diagnose this issue.  Otherwise, its a standard install following your guide (I did have to install some additional pkgs not listed in the wiki).

**Comment by morpheus65535** [comment]
In that case just make sure you have development branch selected in Settings --> General and force an update in Sustem --> Tasks. You won't notice change in version number in dev branch.

**Comment by jasonsansone** [comment]
No change.  Do you want a log?

**Comment by jasonsansone** [comment]
Here is a debug log.  Interestingly, it returns "Video file appears to lack subtitle stream".  However, the file has a PGS subtitle stream.

`04/08/2020 09:01:44|INFO    |subliminal_patch.core           |Downloaded 1 subtitle(s)|
04/08/2020 09:01:44|DEBUG   |subliminal.core                 |Terminating initialized providers|
04/08/2020 09:01:44|INFO    |subliminal_patch.core           |Terminating provider podnapisi|
04/08/2020 09:01:44|INFO    |subliminal_patch.core           |Terminating provider titrari|
04/08/2020 09:01:44|INFO    |subliminal_patch.core           |Terminating provider yifysubtitles|
04/08/2020 09:01:44|INFO    |subliminal_patch.core           |Terminating provider opensubtitles|
04/08/2020 09:01:44|DEBUG   |subliminal_patch.core           |Subtitle formats requested: ('srt',)|
04/08/2020 09:01:44|DEBUG   |subliminal_patch.core           |Saving <OpenSubtitlesSubtitle 'http://www.opensubtitles.org/en/subtitles/3557145/sid-23p,GAemWqLHZ5SY7q39Zrny4Q4/batman-returns-en' [en:utf-8]> to '/media/Plex/Movies-4K/Batman Returns (1992)/Batman Returns (1992) [Remux-2160p].en.srt'|
04/08/2020 09:01:44|INFO    |subliminal_patch.subtitle       |Applying mods: ['remove_HI', 'remove_tags', 'OCR_fixes', 'common', 'fix_uppercase']|
04/08/2020 09:01:45|DEBUG   |root                            |BAZARR Subtitles file saved to disk: /media/Plex/Movies-4K/Batman Returns (1992)/Batman Returns (1992) [Remux-2160p].en.srt|
04/08/2020 09:01:45|DEBUG   |root                            |BAZARR FFprobe used is /usr/local/bin/ffprobe|
04/08/2020 09:01:45|INFO    |engineio.server                 |14cdf06a67314b03b751eb64c8c8e5f3: Received packet PING data None|
04/08/2020 09:01:45|INFO    |engineio.server                 |14cdf06a67314b03b751eb64c8c8e5f3: Sending packet PONG data None|
04/08/2020 09:01:45|DEBUG   |root                            |BAZARR FFmpeg used is /usr/local/bin/ffmpeg|
04/08/2020 09:01:45|INFO    |ffsubsync.ffsubsync             |extracting speech segments from reference '/media/Plex/Movies-4K/Batman Returns (1992)/Batman Returns (1992) [Remux-2160p].mkv'...|
04/08/2020 09:01:45|INFO    |ffsubsync.speech_transformers   |Checking video for subtitles stream...|
04/08/2020 09:01:46|INFO    |ffsubsync.speech_transformers   |Video file appears to lack subtitle stream|
04/08/2020 09:01:50|INFO    |engineio.server                 |5d0ab74058894f2e83d1fb190fe9d561: Client is gone, closing socket|
04/08/2020 09:01:50|INFO    |engineio.server                 |5d0ab74058894f2e83d1fb190fe9d561: Client is gone, closing socket|
04/08/2020 09:01:52|INFO    |ffsubsync.ffsubsync             |...done|
04/08/2020 09:01:52|INFO    |ffsubsync.ffsubsync             |extracting speech segments from subtitles '/media/Plex/Movies-4K/Batman Returns (1992)/Batman Returns (1992) [Remux-2160p].en.srt'...|
04/08/2020 09:01:52|INFO    |ffsubsync.subtitle_parser       |detected encoding: ASCII|
04/08/2020 09:01:52|INFO    |ffsubsync.ffsubsync             |...done|
04/08/2020 09:01:52|INFO    |ffsubsync.ffsubsync             |computing alignments...|
04/08/2020 09:01:56|ERROR   |ffsubsync.ffsubsync             |Synchronization failed; consider passing --max-offset-seconds with a number larger than 600|
04/08/2020 09:01:56|ERROR   |root                            |BAZARR unable to sync subtitles using English embedded subtitle track(s:0): /media/Plex/Movies-4K/Batman Returns (1992)/Batman Returns (1992) [Remux-2160p].en.srt|`

**Comment by morpheus65535** [comment]
PGS subtitles track are image based and cannot be used as reference. That's the reason why ffsubsync say there's no subtitles track.

**Comment by jasonsansone** [comment]
They can be OCR'd, but understood.

**Comment by jasonsansone** [comment]
I found [this](https://github.com/smacke/ffsubsync/issues/60#issuecomment-637963200).  I think the problem is.. there is no problem.  It is ffsubsync and outside of your control.  Thank you for the support.  I am closing this issue.

**Comment by morpheus65535** [comment]
Ok, anyway I'm working to make sure we provide the best reference track to ffsubsync.

**Comment by jasonsansone** [comment]
Kudos on an amazing piece of software.  Thank you for the hard work.
