### ISSUE TITLE
Don't show forced subs in "Wanted" if Forced is set to "Both"

### ISSUE THREAD

**Issue by Flippage** [morpheus65535/bazarr#1057]
My subtitles are set to:
Subtitle Language: English
Forced: Both 

**To Reproduce**
Set Forced to "Both" option

**Expected behavior**
Because "Both" for Forced essentially means "If it exists", I don't class it as a "Missing" subtitle.
I don't think they should show up in the "Wanted" tab.
I basically just want the Wanted tab to show movies/shows that don't have subtitles.

**Screenshots**
![image](https://user-images.githubusercontent.com/10948118/89263566-a15b0700-d670-11ea-805c-865e0a593877.png)
![image](https://user-images.githubusercontent.com/10948118/89263593-b172e680-d670-11ea-9d90-b1cb21950c2f.png)

**Software (please complete the following information):**
 - Bazarr: 0.9.0.1
 - Radarr: 3.0.0.3352
 - Sonarr: 3.0.3.905
 - OS: Windows 10 Pro 64-bit

**Additional context**
This could possibly be an option.
"Treated (Forced: Both) option as missing subtitles?" Yes/No
Essentially, I only want episodes/movies that are missing regular english subs, to show up in the Wanted list.

**Comment by morpheus65535** [comment]
That's currently impossible because of the way we store subtitles. This could change in the future but it's unplanned yet. .
