### ISSUE TITLE
Can't edit series in Bazarr behind Nginx reverse proxy

### ISSUE THREAD

**Issue by Flippage** [morpheus65535/bazarr#1060]
**Describe the bug**
When I access my webserver by Organizr through Nginx reverse proxy, I am not able to "Save" changes in "Edit Series".

**To Reproduce**
1. Open a series in Bazarr.
2. Click on "Edit Series" in the top right
3. Make a change
4. Hit "Save"

**Expected behavior**
Nothing happens. It just sits there. Expect the "Edit Series" prompt to disappear and the changes to have applied to the series.
This works fine when I access Bazarr directly without going through Nginx.

**Screenshots**
![image](https://user-images.githubusercontent.com/10948118/89379896-cb2a3180-d735-11ea-9622-4f063a77e01e.png)

**Software (please complete the following information):**
 - Bazarr: 0.9.0.1
 - OS: Windows 10 64-bit

**Comment by morpheus65535** [comment]
Duplicate #951 and #1037.

**Comment by Flippage** [comment]
Hey @morpheus65535 - Neither of those worked. But, it does look like it's Organizr auth that's causing it.

However, I was able to save settings in the "Settings" tab fine. It's only "Edit Movie" or "Edit Series" that I can't save.

Everything else was working fine.

Any ideas what I need to allow through ? E.g.
`location /bazarr/save_settings {
	auth_request off;
	proxy_pass http://127.0.0.1:6767/bazarr/save_settings;
}`

But for "Edit Series" / "Edit Movie"

**Comment by Flippage** [comment]
With a bit more testing, it looks like it's just "Edit Series" that's having issues. I'm able to "Edit Movie" from behind Nginx/Organizr.

**Comment by Flippage** [comment]
Ok, I reckon I figured it out.

Saving the "Settings" changes wasn't working either, even with the Nginx config change from #951 

Looking at Chrome dev tools in F12, while connected locally to Bazarr, it looks like it's using /bazarr/api to save "Edit Movie"/"Edit Series"/"Settings" changes.

I've added this to Nginx conf and everything is working properly:

`location /bazarr/api {`
`     auth_request off;`
`     proxy_pass http://127.0.0.1:6767/bazarr/api;`
`}`

This is the same fix that I had to apply to both Radarr and Sonarr in the past as well.

**Comment by morpheus65535** [comment]
@Flippage I would guess that there something odd with your nginx config because I didn't had to add this to mine, even for Sonarr/Radarr. Here's my location config:
```
location /bazarr {
        proxy_pass              http://10.0.0.4:6767/bazarr;
        proxy_set_header        X-Real-IP               $remote_addr;
        proxy_set_header        Host                    $host;
        proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_$
        proxy_set_header        X-Forwarded-Proto       $scheme;
        proxy_redirect off;
        proxy_http_version      1.1;
        proxy_set_header        Upgrade                 $http_upgrade;
        proxy_set_header        Connection              "Upgrade";
}
```

By adding `auth_request off;` to `/bazarr/api`, you're exposing it to anyone on the internet.

**Comment by morpheus65535** [comment]
My actual guess is that Organizr overwrite the apikey sent with FormData by Sonarr, Radarr and Bazarr. He's the one to blame and he should take care of others as it's mean to be a global portal.
