### ISSUE TITLE
subscene can't find subtitles

### ISSUE THREAD

**Issue by andrsm** [morpheus65535/bazarr#1062]
**Describe the bug**
When searching for subtitles with subscene it can't find subtitles for the movie I'm searching for. I've checked the website itself and there are available subtitles for the movie.
See debuglog file.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5035023/bazarr.log)

**To Reproduce**
1. Search for subtitles for movie

**Expected behavior**
Expect to find the subtitles listed on the site.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: v0.9.0.2
 - OS: Ubunutu 20.04

**Additional context**

**Comment by morpheus65535** [comment]
@pannal could you give some time to this one please?

**Comment by andrsm** [comment]
Any news on this?
Still getting this error on movies:
|INFO    |subscene_api.subscene           |Falling back to non-year results as year wasn't found (2013)|
and
|INFO    |subscene_api.subscene           |Falling back to non-year results as year wasn't found (2008)|
for another movie, both with correct year.

The year is correctly identified from the movie on disk, but there seem break when searching the API of subscene.

**Comment by morpheus65535** [comment]
Still waiting on @pannal to look inti this one.

**Comment by morpheus65535** [comment]
Is it still an issue with v0.9.0.4? I've rework the year matching and it could have affected this issue. Please confirm.

**Comment by andrsm** [comment]
Yes, still getting the same error. Bazarr recognize the year correctly, it just seems like the communication with the subscene api seems to break. I have a plugin in emby for subscene subtitles and that one works for these movies.

06/10/2020 00:02:06|INFO    |subscene_api.subscene           |Falling back to non-year results as year wasn't found (2013)|

It finds a few results from subscene but it's the wrong movies.

**Comment by morpheus65535** [comment]
Can you test dev branch? You should get better result with this fix.

**Comment by andrsm** [comment]
Awesome. Seems to be good now.

**Comment by morpheus65535** [comment]
Perfect then! I'll close this issue but if you're still facing it in the future, you can open a new one referring to this one.
