### ISSUE TITLE
Update Movie list from Radarr throws exception

### ISSUE THREAD

**Issue by faxity123** [morpheus65535/bazarr#1063]
**Describe the bug**
The task `Update Movie list from Radarr` throws an exception specifically in development branch (hotio/bazarr:unstable)

**Software (please complete the following information):**
 - Bazarr: 0.9.0.2
 - Radarr version 3.0.0.3374-ls18 by linuxserver.io
 - Docker: hotio/bazarr:unstable

**Additional context**
```python
Traceback (most recent call last):
 File "/app/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/get_movies.py", line 134, in update_movies
  videoCodec = RadarrFormatVideoCodec(videoFormat, videoCodecID, videoProfile, videoCodecLibrary)
 File "/app/bazarr/get_movies.py", line 336, in RadarrFormatVideoCodec
  if videoCodecLibrary.startswith("x265"): return "h265"
AttributeError: \NoneType\ object has no attribute \startswith\
```
Most likely due to c98fd111cd0a7b9dd3c207294994f5cb960197b0

When I switched to to master branch (hotio/bazarr:latest) it was working again
Switching then back again to development (hotio/bazarr:unstable) it is not working again

Feel free to tag me on discord if needed > Faxity

**Edit;**
Just tried linuxserver/bazarr:development as well, same problem.
Likely something to do with Radarr, currently investigating.

`http://xxxxxxx:7878/api/movie/?apikey=x` in response here I see `videoCodecLibrary` either empty string or filled, for all movies though.

**Edit2;** 
While debugging I noticed radarr v3 api is now being used `/api/v3/movie?apikey=`  however the mediainfo returned on this endpoint is way different from the original.
More specifically below, videoCodecLibrary is missing from /v3 which might be causing my problem

For the same movie;
Mediainfo on `/api/movie`
```json
"mediaInfo": {
    "containerFormat": "BDAV",
    "videoFormat": "HEVC",
    "videoCodecID": "36",
    "videoProfile": "Main 10@L5.1@Main",
    "videoCodecLibrary": "",
    "videoBitrate": 0,
    "videoBitDepth": 10,
    "videoMultiViewCount": 0,
    "videoColourPrimaries": "BT.2020",
    "videoTransferCharacteristics": "PQ",
    "width": 3840,
    "height": 2160,
    "audioFormat": "AC-3",
    "audioCodecID": "131",
    "audioCodecLibrary": "",
    "audioAdditionalFeatures": "MLP FBA 16-ch",
    "audioBitrate": 640000,
    "runTime": "01:57:03.0270000",
    "audioStreamCount": 3,
    "audioChannels": 8,
    "audioChannelPositions": "3/2/2.1",
    "audioChannelPositionsText": "Front: L C R, Side: L R, Back: L R, LFE",
    "audioProfile": "",
    "videoFps": 59.940,
    "audioLanguages": "",
    "subtitles": "",
    "scanType": "",
    "schemaRevision": 5
}
```

Mediainfo on `/api/v3/movie`
```json
"mediaInfo": {
    "audioAdditionalFeatures": "MLP FBA 16-ch",
    "audioBitrate": 640000,
    "audioChannels": 7.1,
    "audioCodec": "AC3",
    "audioLanguages": "",
    "audioStreamCount": 3,
    "videoBitDepth": 10,
    "videoBitrate": 0,
    "videoCodec": "HEVC",
    "videoFps": 59.940,
    "resolution": "3840x2160",
    "runTime": "1:57:3",
    "scanType": "",
    "subtitles": ""
}
```

**Comment by morpheus65535** [comment]
Thanks for all this information, it makes me easier to provide a fix. :-)

Can you test and report please?

**Comment by faxity123** [comment]
It's working again, thanks for fix!
