### ISSUE TITLE
Bazarr won't upload subtitles

### ISSUE THREAD

**Issue by aevans0001** [morpheus65535/bazarr#1064]
**Describe the bug**
I tried to upload some subtitles using bazarr's manual upload, it doesn't give me the place that it is trying to upload to, it then just spins and spins, and never lets me upload another subtitle till i restart.  However the first one never sends.

**To Reproduce**
1. Go to series, the series you wan to upload from
2. Click on the season and episode you want to upload
3. push manual upload button and fill out pop up window, hit submit
4. never processes

**Expected behavior**
it should process, upload, and then go back to normal state (not spinning)

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: V .9.0.1
 - Radarr version [e.g. v 0.2.0.0001]
 - Sonarr version V3.0.3.906
 - OS: WINDOWS 10 NEWEST BUILD

**Additional context**

**Comment by morpheus65535** [comment]
Can you provide me the output of the dev console of your browser when you press the submit  button, it could help me confirm if your issue will be fixed in v0.9.0.2.

**Comment by morpheus65535** [comment]
Is it still an issue? Can I close it?

**Comment by morpheus65535** [comment]
No answer, I close.
