### ISSUE TITLE
Upgrade previously Subtitles failed: TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by PotatoQuality** [morpheus65535/bazarr#1066]
**Describe the bug**
Running the Upgrade previously Subtitles task, will stop after 1 minute due to an exception.

**To Reproduce**
1. Run manually or wait for the schedule to kick in for the upgrade subtitle job.
2. Wait
3. See logs, the task stops after a short time of running

**Expected behavior**
Finishing the job without an error.

**Screenshots**

`10/08/2020 16:53:40|ERROR   |apscheduler.executors.default   |Job "Upgrade previously downloaded Subtitles (trigger: interval[1 day, 0:00:00], next run at: 2020-08-11 16:53:14 CEST)" raised an exception|Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "/app/bazarr/bazarr/get_subtitle.py", line 1163, in upgrade_subtitles    result = download_subtitle(path_mappings.path_replace(episode['video_path']),  File "/app/bazarr/bazarr/get_subtitle.py", line 237, in download_subtitle    sonarr_series_id=episode_metadata['sonarrSeriesId'],TypeError: 'NoneType' object is not subscriptable|`

**Software (please complete the following information):**
- Bazarr Version: 0.9.0.2
- Sonarr Version: 3.0.3.906
- Radarr Version: 0.2.0.1504
- Operating System: Linux-4.19.107-Unraid-x86_64-with
- Python Version: 3.8.5

**Additional context**
Debug logs:
[bazarr (1).log](https://github.com/morpheus65535/bazarr/files/5051617/bazarr.1.log)

**Comment by morpheus65535** [comment]
I would guess it either a path mapping issue or a corrupt database row. Let's talk about it over Discord PM.
