### ISSUE TITLE
Download subtitles with new Plex Movie agent installed?

### ISSUE THREAD

**Issue by cphmichael** [morpheus65535/bazarr#1067]
I am using Sub-Zero, but after I upgraded to the new Plex movie agent, Sub-Zero is no longer able to access Plex Movie. 
It still works for TV Series.

Introducing the new Plex Movie agent:
https://forums.plex.tv/t/introducing-the-new-plex-movie-agent/615989

Sub-Zero github:
https://user-images.githubusercontent.com/1359593/88648840-a72c7780-d0c7-11ea-9300-51872a1dc3bd.png

Is Bazarr able to download subtitles for Movies if the new Plex movie agent is installed?

**Comment by morpheus65535** [comment]
Bazarr is media server agnostic. We don't care what you use to manage/play your media. Bazarr will work with Sonarr and Radarr to get subtitles. After that, it's up to Plex (or any other player) to detect the subtitles and play it with the media file.
