### ISSUE TITLE
Throttling subscene because of AttributeError

### ISSUE THREAD

**Issue by cphmichael** [morpheus65535/bazarr#1068]
Maybe my issue is related to #1062 

I can see those errors in the log:

* Throttling subscene for 10 minutes, until 20/08/14 07:12, because of: AttributeError. Exception info: "'RetryingCFSession' object has no attribute 'isChallengeRequest'"
* Using subscene again after 10 minutes, (disabled because: AttributeError)

Attached logfile:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5073143/bazarr.log)

**Comment by morpheus65535** [comment]
Fixed in next release.
