### ISSUE TITLE
Providers constant errors

### ISSUE THREAD

**Issue by davidsaraiva** [morpheus65535/bazarr#1070]
**Describe the bug**
Subtitle providers issues:
LegendasDivx -> Status: Service unavailable
Opensubtitles -> Status: Permission error

**To Reproduce**
1. Enable LegedasDivx and Opensubtitles as a provider'
2. Search for subtitles

**Expected behavior**
Search has results and the providers keep an healthy status

**Screenshots**
![image](https://user-images.githubusercontent.com/28621567/90254920-6fe5f680-de3b-11ea-9bbc-45bccc601d78.png)

**Software (please complete the following information):** 
Bazarr Version: 0.9.0.1
Sonarr Version: 2.0.0.5344
Radarr Version: 0.2.0.1504
Operating System: Linux-5.4.51-v7l+-armv7l-with

**Additional context**
Running in a Linuxserver docker [container](https://hub.docker.com/r/linuxserver/bazarr).
Also one additional question, I recently updated to the version 0.9.0.1 (was previously on 0.8.x.x) and now the UI is really strange, it's nothing similar to sonarr and radar, is this something expected? Can I change it?
![image](https://user-images.githubusercontent.com/28621567/90255241-ebe03e80-de3b-11ea-94a3-2263a3c93d1a.png)

**Comment by morpheus65535** [comment]
LegendasDivx -> Fixed in v0.9.0.2 (dev branch for now)
Opensubtitles -> This is an issue with PUID/PGID that doesn't have write access on disk.

The UI isn't strange, Sonarr and Radarr v3 UI are similar. You are probably still running Sonarr v2.x and Radarr v0.2.x. You ca n safely move to Sonarr v3. Radarr v3 is still in early adopter phase.

**Comment by davidsaraiva** [comment]
> Opensubtitles -> This is an issue with PUID/PGID that doesn't have write access on disk.

Thanks for the quick reply, can you tell me how to solve these permission issues? I created the configuration folders for the container with the same user the container is now running...

**Comment by morpheus65535** [comment]
Please come to Discord support channel for live support.
