### ISSUE TITLE
Log says: BAZARR unable to sync subtitles

### ISSUE THREAD

**Issue by cphmichael** [morpheus65535/bazarr#1073]
Bazarr > Releases: v0.9.0.1
Bazarr > Status > About > Version: 0.9.0.2

I have downloaded the docker with this repository: linuxserver/bazarr:development

Is there a homepage where I can see which version is the latest 'development' and what problems you have solved?

In the log I see this errors:
* BAZARR unable to sync subtitles: /tv/The Blacklist/Season 07/The Blacklist - S07E02 - Louis T. Steinhil - Conclusion (2) - Bluray-1080p.en.srt
* Synchronization failed; consider passing --max-offset-seconds with a number larger than 600

Logfile:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5078639/bazarr.log)

**Comment by morpheus65535** [comment]
Releases page update every 6 hours in Bazarr. You can also check releases on github.

**Comment by cphmichael** [comment]
Is the "BAZARR unable to sync subtitles" solved in the next release?

**Comment by morpheus65535** [comment]
It should be.
