### ISSUE TITLE
Log says: Job "Search for wanted Series Subtitles" raised an exception

### ISSUE THREAD

**Issue by cphmichael** [morpheus65535/bazarr#1074]
Bazarr > Releases: v0.9.0.1
Bazarr > Status > About > Version: 0.9.0.2
Docker: linuxserver/bazarr:development

* Job "Search for wanted Series Subtitles (trigger: interval[3:00:00], next run at: 2020-08-15 16:33:58 CEST)" raised an exception

Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/bazarr/get_subtitle.py", line 923, in wanted_search_missing_subtitles_series
  wanted_download_subtitles(episode[\path\], i, count_episodes)
 File "/app/bazarr/bazarr/get_subtitle.py", line 824, in wanted_download_subtitles
  result = download_subtitle(path_mappings.path_replace(episode[\path\]),
 File "/app/bazarr/bazarr/get_subtitle.py", line 234, in download_subtitle
  sync_subtitles(video_path=path, srt_path=downloaded_path,
 File "/app/bazarr/bazarr/get_subtitle.py", line 1279, in sync_subtitles
  subsync.sync(video_path=video_path, srt_path=srt_path, srt_lang=srt_lang, media_type=media_type,
 File "/app/bazarr/bazarr/subsyncer.py", line 54, in sync
  "{:.2f}".format(result[\framerate_scale_factor\]))
TypeError: unsupported format string passed to NoneType.__format__

Logfile:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5078646/bazarr.log)

**Comment by morpheus65535** [comment]
Are you able to confirm the values or args passed to `subsync.sync`?

**Comment by cphmichael** [comment]
How can I confirm that - Where do I have to look?

**Comment by morpheus65535** [comment]
My bad, from your other issue, I was under the impression that you had Bazarr running within a debugger. There's no way of confirming those values without it.

**Comment by cphmichael** [comment]
I am running Bazarr on unRAID in a docker container “linuxserver/bazarr:development”

**Comment by morpheus65535** [comment]
What is the audio language for this specific series?

**Comment by cphmichael** [comment]
I am from Denmark but use English subtitles.

**Comment by morpheus65535** [comment]
I mean, in series view (where you see the series list), what is the language in the audio language colimn?

**Comment by cphmichael** [comment]
I have English in the language column:

![Series View](https://user-images.githubusercontent.com/45288008/90475774-753b8d80-e128-11ea-997b-dacbe6053908.JPG)

**Comment by morpheus65535** [comment]
Can you test my latest fix in dev branch?

**Comment by cphmichael** [comment]
I can see the update is "committed 29 minutes ago", so I don't think the docker is ready with the latest update.

**Comment by morpheus65535** [comment]
> I installed the latest development.
> It still says "Bazarr Version: 0.9.0.3" and in Releases it says v0.9.0.2.
> There is no release information for 0.9.0.3

Like I sad to you before, releases page only present version released in master branch. You won't see dev version here. Also, we don't increment version number every time we do a commit so it's normal to not see any change in version number.

**Comment by morpheus65535** [comment]
> I can see the update is "committed 29 minutes ago", so I don't think the docker is ready with the latest update.

LSIO images take a long time to be rebuilt. You can the progress here: https://ci.linuxserver.io/job/Docker-Pipeline-Builders/job/docker-bazarr/

**Comment by cphmichael** [comment]
Very interesting - I have bookmarked  :-)

**Comment by cphmichael** [comment]
I haven't seen the problem the last two days, so I think you have solved it.
