### ISSUE TITLE
Synchronization failed; consider passing --max-offset-seconds with a number larger than 600

### ISSUE THREAD

**Issue by JpF4E** [morpheus65535/bazarr#1076]
**Describe the bug**
When going on tools and trying to sync subtitles, the following appears on logs:
"Synchronization failed; consider passing --max-offset-seconds with a number larger than 600"

**To Reproduce**
Click a movie, select tools and use the syn tool.

**Expected behavior**
I expected a successful sync.

**Screenshots**
No need.

**Software (please complete the following information):**
 - Bazarr: 0.9.0.3
 - Radarr version 0.2.0.1504
 - Sonarr version 2.0.0.5343
 - OS: CentOS 8

**Additional context**
No need.

**Comment by mmaghometech** [comment]
I'm having the same issue.  I posted on discord also.

**Comment by cphmichael** [comment]
unRAID: linuxserver/bazarr:development
Bazarr Version: 0.9.0.3

* BAZARR unable to sync subtitles: /tv/The Blacklist/Season 07/The Blacklist - S07E19 - The Kazanjian Brothers - Bluray-1080p.en.srt
* Synchronization failed; consider passing --max-offset-seconds with a number larger than 600

**Comment by morpheus65535** [comment]
There's nothing more I can do on Bazarr side. You can open an issue on ffsubsync github. Keep in mind that subtitles synchronization can't do miracle. If the subtitles is more than 10 minutes out of sync, you probably find a better match in the first place.
