### ISSUE TITLE
HTTPConnectionPool: Throttling bsplayer for 10 minutes - Exception info: 'Too many tries...'

### ISSUE THREAD

**Issue by cphmichael** [morpheus65535/bazarr#1077]
Bazarr Version: 0.9.0.3

* HTTPConnectionPool(host='s103.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: /v1.php (Caused by ConnectTimeoutError(, 'Connection to s103.api.bsplayer-subtitles.com timed out. (connect timeout=10)')), retrying in 5 seconds...
* HTTPConnectionPool(host='s4.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: /v1.php (Caused by ConnectTimeoutError(, 'Connection to s4.api.bsplayer-subtitles.com timed out. (connect timeout=10)')), retrying in 5 seconds...
* Throttling bsplayer for 10 minutes, until 20/08/15 23:24, because of: Exception. Exception info: 'Too many tries...'

Logfile:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5079528/bazarr.log)

**Comment by morpheus65535** [comment]
Connection timeout like, the website is unavailable or your IP have been blocked. There's nothing I can do on my side.
