### ISSUE TITLE
ffsubsync Synchronization failed --max-offset-seconds

### ISSUE THREAD

**Issue by BodingClockchian** [morpheus65535/bazarr#1081]
**Describe the bug**
ffsubsync shows this error sometimes
"ERROR (ffsubsync:108) - Synchronization failed; consider passing --max-offset-seconds with a number larger than 600"
Could it be possible to map the settings for ffsubsync within Bazarr? This way it would be possible to 'tweak' this settings manually.

**Software:**
Bazarr Version: 0.9.0.2
Sonarr Version: 3.0.3.911
Radarr Version: 0.2.0.1504
Operating System: Linux-5.4.0-42-generic-x86_64-with
Python Version: 3.8.5

**Comment by morpheus65535** [comment]
https://github.com/morpheus65535/bazarr/wiki/FAQ#synchronization-failed
