### ISSUE TITLE
Throttling addic7ed for 1 hour

### ISSUE THREAD

**Issue by cphmichael** [morpheus65535/bazarr#1082]
Every day I have a lot of this error in the log:

* Throttling addic7ed for 10 minutes, until 20/08/19 13:49, because of: HTTPError. Exception info: '503 Server Error: Service Temporarily Unavailable for url: https://www.addic7ed.com/ajax_loadShow.php?show=7697&season=1'

I have paid for addic7ed VIP, but still getting the error.

Is that a problem at addic7ed or could it be something in Bazarr?

Logfile:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5096349/bazarr.log)

**Comment by morpheus65535** [comment]
Addic7ed doesn't care if you've paid for VIP, when they get too much query from the same IP in a short period of time, they block the requester IP temporarily. There's nothing we can do about if on Bazarr side except from throttling our requests to this provider when they block your IP.

**Comment by cphmichael** [comment]
* Downloads by User Today | 0 of 80
* Downloads from IP Today | 0

As you can see I haven’t downloaded any subtitles from my IP today but Bazarr says ‘Throttling’

**Comment by morpheus65535** [comment]
I didn't said "download", I said "query". That include login, search, etc.
