### ISSUE TITLE
Subscene: Falling back to non-year results as year wasn't found (2019)

### ISSUE THREAD

**Issue by cphmichael** [morpheus65535/bazarr#1083]
I have this error in the logs:

* Falling back to non-year results as year wasn't found (2019)

The attached Bazarr.log says:

* subscene_api.subscene - Falling back to non-year results as year wasn't found (2019)

[bazarr.log](https://github.com/morpheus65535/bazarr/files/5096369/bazarr.log)

![image](https://user-images.githubusercontent.com/45288008/90634852-aac7a000-e228-11ea-99ca-bcb7cdc6ea6c.png)

**Comment by morpheus65535** [comment]
This isn't an error, this is an info level log. This is a normal behaviour.
