### ISSUE TITLE
Error trying to get video information for this file

### ISSUE THREAD

**Issue by Horatius314** [morpheus65535/bazarr#1085]
To Reproduce Steps to reproduce the behavior:

Added my 4K Sonarr and Radarr instances, grabbing went well until I saw these errors popping up.

Explanation about my library:
300TB library mounted with rclone, 4K is split off and way smaller (I run 2 instances of Bazarr, 1080 and 4k). The mounts are fine as Plex can index and play media files correctly. I'm using Cloudbox which utilizes docker.

Expected behavior A clear and concise description of what you expected to happen.

Grabbing subtitles and not throwing value errors.

Screenshots If applicable, add screenshots to help explain your problem.
![afbeelding](https://user-images.githubusercontent.com/50734579/90905035-e18bea80-e3cf-11ea-9a9c-66ec19990249.png)

Software (please complete the following information):

    Bazarr: [v0.9.0.2]
    Radarr version [3.0.0.3453]
    Sonarr version [3.0.3.911]
    OS: [Ubuntu 18.04]

Additional context Add any other context about the problem here.

https://pastebin.com/UnR0qfgC

**Comment by Spacetech** [comment]
I'm seeing this same error. [Here's the full traceback](https://pastebin.com/WJvwUeft)

**Comment by morpheus65535** [comment]
I don't have a rclone based setup so it's kind of hard to debug. My first suggestion would be to open an issue on guessit Github page and link it to this one. We'll see what is the conclusion of their devs.

**Comment by morpheus65535** [comment]
Is it still an issue? Did you set your TZ correctly?

**Comment by morpheus65535** [comment]
No news for more than 2 weeks. Re-open the issue if required.
