### ISSUE TITLE
bazarr is throwing API error "Exception on /api/movie_subtitles_manual_download [POST]"

### ISSUE THREAD

**Issue by G1zm0** [morpheus65535/bazarr#1088]
**Describe the bug**
Although the the subtitle is downloaded bazarr is trouwing an error

**To Reproduce**
1. Go to 'a movie without subtitle'
2. download a sub manually
3. refresh the movie
4. See error in the log
`Exception on /api/movie_subtitles_manual_download [POST]|Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request    rv = self.dispatch_request()  File "/app/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request    return self.view_functions[rule.endpoint](**req.view_args)  File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper    resp = resource(*args, **kwargs)  File "/app/bazarr/bazarr/../libs/flask/views.py", line 89, in view    return self.dispatch_request(*args, **kwargs)  File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request    resp = meth(*args, **kwargs)  File "/app/bazarr/bazarr/api.py", line 59, in wrapper    return actual_method(*args, **kwargs)  File "/app/bazarr/bazarr/api.py", line 1071, in post    result = manual_download_subtitle(moviePath, language, audio_language, hi, forced, subtitle,  File "/app/bazarr/bazarr/get_subtitle.py", line 501, in manual_download_subtitle    percent_score=score, radarr_id=movie_metadata['radarrId'])TypeError: 'NoneType' object is not subscriptable|`

**Expected behavior**
No errors in the log 

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: [e.g. v v0.9.0.2]
 - Radarr version [e.g. v0.2.0.1504]
 - Sonarr version [e.g. v2.0.0.5344]
 - OS: [Synology NAS OS DSM 6.2.3-25426 Update 2]

**Additional context**
bazarr is a docker behind a reverse proxy on the synology. I use subdomains (bazarr.mydomain.ext) config looks like this:
```
location / {
        proxy_pass              http://localhost:8310;
        proxy_set_header        X-Real-IP               $remote_addr;
        proxy_set_header        Host                    $host;
        proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_$
        proxy_set_header        X-Forwarded-Proto       $scheme;
        proxy_set_header        Upgrade                 $http_upgrade;
        proxy_set_header        Connection              "Upgrade";
}

```

full debug log [HERE](https://pastebin.com/1GfrUhqv)

**Comment by morpheus65535** [comment]
Looks to me like a path mapping issue. Can you come by our Discord channel to make sure they are configured properly?

**Comment by G1zm0** [comment]
Solved:
Deleted existing portmappings and recreated them using the browser function.
After a restart everything worked!

thanks @morpheus65535 & @TRaSH-
