### ISSUE TITLE
[Update Provider Mirror] YIFY Subtitles

### ISSUE THREAD

**Issue by dalkain** [morpheus65535/bazarr#1089]
yifysubtitles.com no longer functions. Can the system be updated to reflect the current working mirror: yts-subs.com

Previous request:
https://bazarr.featureupvote.com/suggestions/54297/provider-request-add-yifi-subtitles-as-provider

Cross posting from:
https://bazarr.featureupvote.com/suggestions/116185/provider-request-update-yify-subtitles-to-working-mirror

**Comment by josdion** [comment]
Fixed in development branch.

**Comment by dalkain** [comment]
I'm sure other people will want to test, but I manually replaced the yifysubtitles.py script in my container and it works now 👍
