### ISSUE TITLE
Portuguese (Brazilian) issues

### ISSUE THREAD

**Issue by alfablac** [morpheus65535/bazarr#109]
Awesome app!
But it has a few issues with brazilian portuguese subtitles.
Pretty common because often people don't know they are languages a little bit different (but we can understand each other, lol)

bazarr doesn't recognize .pt-BR .pob as brazilian portuguese subs, so it thinks there's a subtitle missing when portuguese is selected (which I think only matches .pt or .por subtitles)

**Comment by Rodrigueztb** [comment]
will be awesome if its possible to add brazilian portuguese(pt-br) support. We can understand pt-pt subs, but its weird.

**Comment by morpheus65535** [comment]
The problem with Brazilian Portuguese is that this language doesn't have an ISO-639 language code. It's more of an non-official usage when we use ```pb``` or ```pob```.

I'm going to have to refactorize all the language code conversion in Bazarr to take care of custom language code...

**Comment by morpheus65535** [comment]
Subliminal seems to have a issue with pt-BR: https://github.com/Diaoul/subliminal/issues/930

**Comment by morpheus65535** [comment]
The best I can do is this:

- Existing external subtitles file with ```.pb```, ```.pob``` or ```.pt-br``` just before the file extension are going to be recognized as Brazilian Portuguese;
- Existing external subtitles file without any language code before the extension are going to be recognized as Portuguese (langdetect do not support Brazilian Portuguese);
- New subtitles file are going to be save with ```.pt-BR.srt```. Nothing I can do here, Subliminal do not support ```.br``` or ```.pob``` language code.

Is this ok for you? Does your media player are going to be able to interpret ```.pt-BR.srt``` file?

If not, maybe I could give a try renaming the subtitles file after Subliminal have saved it to disk but I would prefer not to go down that road... exception could occur that I would prefer not have to manage.

**Comment by morpheus65535** [comment]
You can try this in dev branch. Please give me feedback!

**Comment by alfablac** [comment]
Testing. I think `.pob` is something that only media players will accept as Brazilian Portuguese besides `pt-BR`. And IIRC `pob` is also the code that OpenSubtitles use for brazilian portuguese. Subliminal indeed saves subtitles as `pt-BR`, so `pt-BR` will probably be the best way to save it.

**Comment by morpheus65535** [comment]
@alfablac @Rodrigueztb I need your feedback guys! :-)

**Comment by alfablac** [comment]
Sorry man. I keep getting this error on the dev-branch... installed all the packages required

```
Error: 500 Internal Server Error
Sorry, the requested URL 'http://briareus.feralhosting.com:6767/settings' caused an error:

Internal Server Error
Exception:
TypeError("'int' object has no attribute '__getitem__'",)
Traceback:
Traceback (most recent call last):
  File "/media/sdaa1/alfablac/.local/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/media/sdaa1/alfablac/.local/lib/python2.7/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "bazarr.py", line 120, in wrapper
    return func(*a, **ka)
  File "bazarr.py", line 710, in settings
    return template('settings', __file__=__file__, bazarr_version=bazarr_version, settings_general=settings_general, settings_auth=settings_auth, settings_languages=settings_languages, settings_providers=settings_providers, settings_sonarr=settings_sonarr, settings_radarr=settings_radarr, settings_notifier=settings_notifier, base_url=base_url)
  File "/media/sdaa1/alfablac/.local/lib/python2.7/site-packages/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/media/sdaa1/alfablac/.local/lib/python2.7/site-packages/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "/media/sdaa1/alfablac/.local/lib/python2.7/site-packages/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/media/sdaa1/alfablac/Bazarr/bazarr-development/views/settings.tpl", line 419, in <module>
    %		path_movie = path_substitutions_movie[x]
TypeError: 'int' object has no attribute '__getitem__'
```

**Comment by morpheus65535** [comment]
Good to know that I got another happy user! :-)

I'll merge this to master in the coming days.

Have fun!

**Comment by Rodrigueztb** [comment]
Sorry, my NAS was off and i couldnt test. It seems ok! Ty
