### ISSUE TITLE
restarting loop in freebsd

### ISSUE THREAD

**Issue by hros** [morpheus65535/bazarr#1090]
I've updated bazarr to the latest version (git pull) on my freebsd server
I updated to python3.7
When I start bazarr I get the following messages in and endless loop:
```
Bazarr is being restarted...
BAZARR installing requirements...
BAZARR requirements installed.
```

**Comment by morpheus65535** [comment]
Install requirements.txt following wiki instructions.

**Comment by hros** [comment]
the issue is due to a problem with freebsd ([bug report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=248962))
instead of installing the py37-numpy pkg, using pip install numpy works
