### ISSUE TITLE
The container of bazarr has allocated 1 GB of memory while doing nothing(Included logs + Image)

### ISSUE THREAD

**Issue by Xarishark** [morpheus65535/bazarr#1093]
The container is consuming 1GB of ram on my nas while doing nothing 

![Screenshot_4](https://user-images.githubusercontent.com/21146743/91782143-f43ec480-ec04-11ea-90ac-2ac9abe2d10c.png)
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5153285/bazarr.log)

latest docker version 

all my other dockers run normaly

**Comment by Xarishark** [comment]
![image](https://user-images.githubusercontent.com/21146743/91782237-35cf6f80-ec05-11ea-805a-e0c30a08e657.png)
Here is the version just to be sure because I use the linuxserver repo

**Comment by morpheus65535** [comment]
Can you provide a graph of memory usage over time to help identify the task that may be causing this?

Also, can you test with Hotio's image (`hotio/bazarr:stable`)? Don't forget to modify your volume from `/path/to/config:/config` to `/path/to/config:/config/app`.

**Comment by morpheus65535** [comment]
Is it still an issue or should I close it?

**Comment by morpheus65535** [comment]
No news for a week. Re-open the issue if required.
