### ISSUE TITLE
BAZARR is started and waiting for request on http://0.0.0.0:6767/

### ISSUE THREAD

**Issue by Bboy486** [morpheus65535/bazarr#1094]
**Describe the bug**
Bazarr starting...
2020-09-01 19:27:49,863 - root                             (2c9c) :  INFO (server:38) - BAZARR is started and waiting for request on http://0.0.0.0:6767/

Bazarr hangs on this step. It is likely because I have both python3.7.0 and python 2.7.18 for different scripts. Is there a way to force bazarr to use python 3?

**To Reproduce**
cd c:\Bazarr
python bazarr.py 

**Expected behavior**
Complete the installation 

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 
 - OS: Windows 10

**Comment by morpheus65535** [comment]
That's a support question, not an issue. Come and ask your question on Discord support channel.
