### ISSUE TITLE
Subdivx provider not working anymore (ServiceUnavailable: Bad status code: 503)

### ISSUE THREAD

**Issue by CarlosMC** [morpheus65535/bazarr#1098]
**Describe the bug**
Some couple of days ago (or week maybe) Subdivx provider stop to work.
It is always returning Bad status code: 503 no matter if it's movie or series episode.
Even manual search with subs already downloaded from the site some days ago failed now.

**To Reproduce**
1.- disable all providers but subdivx
2.- reset providers status errors
3.- do some automatic search and/or manual search
4.- subdivx  returns error code 503.

**Expected behavior**
Subs to be found on automatic and manual searches.

**LOG**
```
05/09/2020 13:16:01|INFO    |subliminal_patch.core           |Initializing provider subdivx|
05/09/2020 13:16:01|DEBUG   |subliminal_patch.providers.subdivx|Searching subtitles 'Ava 2020'|
05/09/2020 13:16:01|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): www.subdivx.com:443|
05/09/2020 13:16:01|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on www.subdivx.com|
05/09/2020 13:16:02|DEBUG   |urllib3.connectionpool          |https://www.subdivx.com:443 "GET /index.php?q=Ava+2020&accion=5&oxdown=1&pg=1 HTTP/1.1" 503 None|
05/09/2020 13:16:02|ERROR   |subliminal_patch.core           |Unexpected error in provider 'subdivx': Traceback (most recent call last):  File "/home/mcbox/Bazarr/bazarr/../libs/subliminal_patch/core.py", line 170, in list_subtitles_prov
ider    results = self[provider].list_subtitles(video, provider_languages)  File "/home/mcbox/Bazarr/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 160, in list_subtitles    return self.query(video, languages)  File "/home/a
ppbox/Bazarr/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 141, in query    self._check_response(response)  File "/home/mcbox/Bazarr/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 183, in _check_response    rai
se ServiceUnavailable('Bad status code: ' + str(response.status_code))subliminal.exceptions.ServiceUnavailable: Bad status code: 503|Traceback (most recent call last):  File "/home/mcbox/Bazarr/bazarr/../libs/subliminal_patch/core.py", l
ine 170, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/home/mcbox/Bazarr/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 160, in list_subtitles    return self.query(v
ideo, languages)  File "/home/mcbox/Bazarr/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 141, in query    self._check_response(response)  File "/home/mcbox/Bazarr/bazarr/../libs/subliminal_patch/providers/subdivx.py", line
 183, in _check_response    raise ServiceUnavailable('Bad status code: ' + str(response.status_code))subliminal.exceptions.ServiceUnavailable: Bad status code: 503|
05/09/2020 13:16:02|INFO    |root                            |Provider subdivx throttle count 1 of 5, waiting 5sec and trying again|
```

**Software (please complete the following information):**

- Bazarr Version: 0.9.0.2
- Sonarr Version: 3.0.3.913
- Radarr Version: 0.2.0.1504
- Operating System: Linux-5.5.6-050506-generic-x86_64-with-debian-10.4
- Python Version: 3.7.3
- Bazarr Directory: /home/mcbox/Bazarr
- Bazarr Config Directory: /home/mcbox/Bazarr-data

**Additional context**
Searching directly on the website is working fine: 
https://www.subdivx.com/index.php?q=Ava+2020&accion=5&oxdown=1&pg=1

**Comment by ilcavero** [comment]
I also see:
Throttling subdivx for 10 minutes, until 20/09/05 21:38, because of: MissingSchema. Exception info: "Invalid URL 'bajar.php?id=604205&u=9': No schema supplied. Perhaps you meant http://bajar.php?id=604205&u=9?"

**Comment by CarlosMC** [comment]
> I also see:
> Throttling subdivx for 10 minutes, until 20/09/05 21:38, because of: MissingSchema. Exception info: "Invalid URL 'bajar.php?id=604205&u=9': No schema supplied. Perhaps you meant http://bajar.php?id=604205&u=9?"

I don't know the internals of subdivx, but I think that URL you indicated is to direct download the subtitle once the best subtitle is selected (manual or auto).

The thing is it's not showing any result at manual search. Also automatic search fails with Error code 503. So the error is previous to the subtitle best match selection. If you follow the link I put you should see at least 3 available subtitles.

**Comment by morpheus65535** [comment]
I've just test manual search and it works fine for me:
![image](https://user-images.githubusercontent.com/5130500/92325876-e54c7d80-f01b-11ea-99ff-18613308d7f7.png)

But, I also got the missing schema exception. I look into it.

**Comment by morpheus65535** [comment]
MissingSchema exception fixed in dev branch.

**Comment by CarlosMC** [comment]
After update to 0.9.0.3 version it seems to be solved.
Although my issue was not related with the MissingSchema exception.

Thank you for the hard and great work you've done with Bazarr!

**Comment by morpheus65535** [comment]
@CarlosMC Thanks for the feedback! Please re-open this issue if you face it again.
