### ISSUE TITLE
Another "time offset" Windows server 2019 Py 3.7 Ita Rome Time Zone

### ISSUE THREAD

**Issue by zFerry98** [morpheus65535/bazarr#1099]
**Describe the bug**
When I start bazarr it crashes with this error.

**To Reproduce**
Installing either version 1.6 for windows or version from GIT (hence Python) from bazarr-master.zip both give this error as soon as they start.

**Expected behavior**
That works. xD

**Screenshots**
![image](https://user-images.githubusercontent.com/17975351/92409363-a06e3700-f140-11ea-86eb-e94905256b32.png)

**Software (please complete the following information):**
 - Bazarr: Win 1.6 and or 0.9.0.3
 - OS: Windows Server 2019 (latest Stable)

**Additional context**
I have read about the various time offset problems. Changing my time is NOT feasible on this production.
I've checked the config.ini but can't find anything about the time zone

**Comment by halali** [comment]
As this isn't an issue, just bad configuration. Please come to discord for support.
