### ISSUE TITLE
Implement UTF8 encoding option

### ISSUE THREAD

**Issue by Zeusy123** [morpheus65535/bazarr#11]
When dealing with arabix or korean, etc.. subtitles files, can be in very different encoding and you only see ??? ?? ??????? ? ????? as the text in the srt file/player.

I have found forcing UTF8 encoder, limits those type of files being grabbed.

So option for users to enable the -e UTF8 encoding.
perhaps just drop down box which user can seelct the type of enciding they want to force.

and your string adds -e (encding selection) to the query to sublinimal

**Comment by Zeusy123** [comment]
Hi morph, just wondering if you could put this top proirty??

then i can begin using this again and utf8 encoding is vital for us in UK

**Comment by morpheus65535** [comment]
Should be working in latest commit. Could you give it a try?

**Comment by morpheus65535** [comment]
Done in commit a6197a09f2ad9f0af3ce692ea9f09130aa8554a7
