### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by Try2Fly** [morpheus65535/bazarr#110]
Hi, I would like to try out this program. I installed it through docker on a Pi 3. I'm running Sonarr and Radarr on the same pi (also in docker). For the set up I only inserted the API key, but I get a Connection error. I also tried to change the hostname but this give the same error. I used the same PGID and PUID as for Sonarr and Radarr. What I'm I doing wrong?

the following is in the log:

> Error trying to get series from Sonarr. Connection Error.

> Traceback (most recent call last):
>  File "/bazarr/get_series.py", line 30, in update_series
>   r = requests.get(url_sonarr_api_series, timeout=15)
>  File "/usr/lib/python2.7/site-packages/requests/api.py", line 72, in get
>   return request(\get\, url, params=params, **kwargs)
>  File "/usr/lib/python2.7/site-packages/requests/api.py", line 58, in request
>   return session.request(method=method, url=url, **kwargs)
>  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
>   resp = self.send(prep, **send_kwargs)
>  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
>   r = adapter.send(request, **kwargs)
>  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 513, in send
>   raise ConnectionError(e, request=request)
> ConnectionError: HTTPConnectionPool(host=\0.0.0.0\, port=8989): Max retries exceeded with url: /api/series?apikey=XXXXXXXXXXXXXXXXXXXXXX (Caused by NewConnectionError(\: Failed to establish a new connection: [Errno 111] Connection refused\,))

**Comment by morpheus65535** [comment]
You cannot use 0.0.0.0 to contact Sonarr and Bazarr. Use your rpi3 ip instead.

**Comment by morpheus65535** [comment]
I suppose you run Sonarr and Radarr container in network bridge mode?

**Comment by Try2Fly** [comment]
Ok thanks, it connects now.

getting the following error:
Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-07-22 22:07:26 CEST)" raised an exception

Traceback (most recent call last):
 File "/usr/lib/python2.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/bazarr/get_series.py", line 25, in update_series
  get_profile_list()
 File "/bazarr/get_series.py", line 131, in get_profile_list
  profiles_list.append([profile[\id\], profile[\language\].capitalize()])
TypeError: string indices must be integers

**Comment by morpheus65535** [comment]
What did you put in Sonarr Base URL?

**Comment by Try2Fly** [comment]
the ip of the rpi3: 192.168.1.201

**Comment by Try2Fly** [comment]
ow sorry base url I did not change so /

**Comment by morpheus65535** [comment]
Try to clear the field and save. Restart then try again.

**Comment by Try2Fly** [comment]
get the same error. This is in the log:

> Starting new HTTP connection (1): 192.168.1.201
> http://192.168.1.201:8989 "GET /api/profile?apikey=XXXXXXXXXXXXXXXXXXXX HTTP/1.1" 401 None
> http://192.168.1.201:8989 "GET /api/v3/languageprofile?apikey=XXXXXXXXXXXXXXXX HTTP/1.1" 401 None
http://192.168.1.201:8989 "GET /api/profile?apikey=6056fce7c4cc446ba13397e0aff8d3b4 HTTP/1.1" 401 None
--
>Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-07-22 23:47:56 CEST)" raised an exception
> Traceback (most recent call last):
 File "/usr/lib/python2.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/bazarr/get_series.py", line 25, in update_series
  get_profile_list()
 File "/bazarr/get_series.py", line 131, in get_profile_list
  profiles_list.append([profile[\id\], profile[\language\].capitalize()])
TypeError: string indices must be integers


I don't know if correct, but I also left the listening IP in the general to 0.0.0.0

**Comment by morpheus65535** [comment]
0.0.0.0 in general settings is correct. 

Please show me a screenshot of the General tab in Sonarr settings (not in Bazarr).

**Comment by Try2Fly** [comment]
Sure (the api is just one created by Sonarr)

![screenshotsonarr](https://user-images.githubusercontent.com/18633213/43092320-16fef920-8ead-11e8-8145-263a899f41ed.png)

**Comment by morpheus65535** [comment]
Sorry but could you enable advanced settings and post a screenshot again? Thanks!

**Comment by Try2Fly** [comment]
![screenshot](https://user-images.githubusercontent.com/18633213/43096556-c25c1256-8eb9-11e8-8ca3-f0d44ed51577.jpg)

**Comment by morpheus65535** [comment]
What do you got if you try to access this URL from your browser?

    http://192.168.1.201:8989/api/profile?apikey=XXXXXXXXXXXXXXXXXXXX

**Comment by Try2Fly** [comment]
A long list with profiles:

```
[
  {
    "name": "Any",
    "cutoff": {
      "id": 1,
      "name": "SDTV",
      "source": "television",
      "resolution": 480
    },
    "items": [
      {
        "quality": {
          "id": 0,
          "name": "Unknown",
          "source": "unknown",
          "resolution": 0
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 1,
          "name": "SDTV",
          "source": "television",
          "resolution": 480
        },
        "allowed": true
      },
```

**Comment by Try2Fly** [comment]
Ok I know they were the same, because I copied them. I disabled radarr for the moment, and pasted the api again (nothing changed in the form) saved and restarted. And now I can see the series turning up. Will check the rest and radarr tomorrow, but so far looking good!

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________

**Comment by morpheus65535** [comment]
Should be any relation between the two. Wait tomorrow and enable radarr again. Please gove me feedback!

**Comment by Try2Fly** [comment]
Ok, turned on Radarr too, and movies are loaded. However the 404 error remains in the logs (you said 401 correct?). Also does it download the subtitles now automatically when a new episode is added, or should I first activate the default enabled switch?

And I could not find a restart button in the settings, so I'm restarting through ssh now. Is this button missing, or I'm I not seeing it?

**Comment by morpheus65535** [comment]
If you still got 401 error, you still have an issue with your API key.

Subtitles are automatically downloaded every 3 hours for episodes of series with a wanted language not met.

For now Bazarr cannot restart itself. I have a feature request for that but I cannot address it for now. The back log is quite large and I'm alone coding Bazarr.

**Comment by Try2Fly** [comment]
Ok thank you. Don't know what is wrong then. It is downloading some subs. I'll keep an eye on it how it performs over the coming weeks!

It is remarkable to see what you achieved already on your own! THANK YOU, hope you can get some help!

**Comment by morpheus65535** [comment]
It’s a pleasure!
