### ISSUE TITLE
BAZARR 0.9.0.4 unable to index external subtitles.

### ISSUE THREAD

**Issue by lukjod** [morpheus65535/bazarr#1103]
After update to docker development ver:

Bazarr Version:
0.9.0.4
Sonarr Version:
3.0.3.924
Radarr Version:
3.0.0.3700
Operating System:
Linux-4.14.24-qnap-x86_64-with
Python Version:
3.8.5

bazarr seems not to see previously downloaded subs on disk and tries to download them again and again.
After I ve rolled back to 0.9.0.3 all is ok

log:
```
Traceback (most recent call last):
 File "/app/bazarr/bazarr/list_subtitles.py", line 64, in store_subtitles
  subtitles = guess_external_subtitles(get_subtitle_destination_folder() or os.path.dirname(reversed_path), subtitles)
 File "/app/bazarr/bazarr/list_subtitles.py", line 433, in guess_external_subtitles
  if not language.hi:
AttributeError: \NoneType\ object has no attribute \hi\
```

**Comment by morpheus65535** [comment]
I need the full traceback to investigate.

**Comment by lukjod** [comment]
Here is a full log, if not enough i will come back to development version and run in debug mode
[https://www.dropbox.com/s/f6ak1j960efc29n/bazarr_log.zip?dl=0](url)

**Comment by cphmichael** [comment]
I have exactly the same problem.

**Comment by morpheus65535** [comment]
I've pushed a fix to dev branch. You can test it?

**Comment by lukjod** [comment]
will report back asap watchtower will update it from linuxserver.io
Which buid shoud it show 0.9.0.5?

**Comment by morpheus65535** [comment]
No it eill stay .4.

**Comment by lukjod** [comment]
problem with log dissapered but now it detects wrong subs as HI (hearing imaired)
below please find some samples of subs which Bazarr identified as HI and i think they are not
[https://www.dropbox.com/s/qyximtmiz52e35g/Nowy%20folder%20%283%29.zip?dl=0](url)

**Comment by morpheus65535** [comment]
When there's a `en:HI` detected (for exemple), does it want to download the `en`?

I'll fine tune the HI classification algorithm later.

**Comment by lukjod** [comment]
Yes exactly
