### ISSUE TITLE
Exception on /api/episodes_search_missing [GET]

### ISSUE THREAD

**Issue by compoab** [morpheus65535/bazarr#1105]
**Describe the bug**
Subtitle search ends abrupty and I see the abovementioned error in the logs.

**To Reproduce**
1. Search for subtitles for certain episodes or movies
2. Random ones will fail, and will keep failing consistently
3. Check log and see this error.
4. Repeat manual search and get the same error

**Expected behavior**
Continue to find subtitles or skip this file and move on

**Software (please complete the following information):**
 - Bazarr: [0.9.0.3]
 - Radarr version [e.g. v 0.2.0.1504]
 - Sonarr version [e.g. v 2.0.0.5344]
 - OS: Linux-4.19.107-Unraid-x86_64-with Python Version: 
[bazarr (1).log](https://github.com/morpheus65535/bazarr/files/5212686/bazarr.1.log)
3.8.5
**Additional context**
Error at the end of the log file, tried reinstalling bazarr completely and ditching old app data, tried hotio/bazarr, same problem. Please help. Thanks.

**Comment by morpheus65535** [comment]
I've added a fix to dev branch to prevent this issue. Please confirm.

**Comment by compoab** [comment]
I have switched to Sonarr v3 and it went away. Would you like me to go back to v2 and test again?

**Comment by morpheus65535** [comment]
Nah it's fine. We'll see if it happen again for someone else ;-)
