### ISSUE TITLE
Job "Search for wanted Series Subtitles (trigger: interval[3:00:00], next run at: 2020-09-13 23:21:24 WEST)" raised an exception

### ISSUE THREAD

**Issue by JpF4E** [morpheus65535/bazarr#1107]
**Describe the bug**
I have more than 100 subtitles pending download.
When the search for wanted series subtitles run (with subtitle sync active), it gets some of them, say 20, but then at some point the error below is shown in the logs (the error refers to House MD S04E08).
The thing is: the next time the task runs, it throws this exception and it won't download any of the wanted subtitles ever again, until I solve the missing file problem.

Message:
`Job "Search for wanted Series Subtitles (trigger: interval[3:00:00], next run at: 2020-09-13 23:21:24 WEST)" raised an exception`

Exception:
```
Traceback (most recent call last):
 File "/opt/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/opt/bazarr/bazarr/get_subtitle.py", line 965, in wanted_search_missing_subtitles_series
  wanted_download_subtitles(episode[\path\], i, count_episodes)
 File "/opt/bazarr/bazarr/get_subtitle.py", line 866, in wanted_download_subtitles
  \series\)
 File "/opt/bazarr/bazarr/get_subtitle.py", line 246, in download_subtitle
  sonarr_episode_id=episode_metadata[\sonarrEpisodeId\])
 File "/opt/bazarr/bazarr/get_subtitle.py", line 1326, in sync_subtitles
  sonarr_series_id=sonarr_series_id, sonarr_episode_id=sonarr_episode_id, radarr_id=radarr_id)
 File "/opt/bazarr/bazarr/subsyncer.py", line 59, in sync
  os.rename(self.srtout, self.srtin)
FileNotFoundError: [Errno 2] No such file or directory: "/home/joao/Series/House/Season 4/House MD Season 4 Episode 08 - You Don\t Want to Know.pt-BR.synced.srt" -> "/home/joao/Series/House/Season 4/House MD Season 4 Episode 08 - You Don\t Want to Know.pt-BR.srt"
```

**To Reproduce**
It's easy to reproduce, just have a bunch of missing subtitles with auto sync enabled and run the "Search for wanted Series Subtitles" task.

**Expected behavior**
Either throw the exception but continue the processing of other subtitles, or don't throw this exception at all.

**Screenshots**
No need.

**Software (please complete the following information):**
Bazarr Version: 0.9.0.4
Sonarr Version: 2.0.0.5343
Radarr Version: 0.2.0.1504
Operating System: Linux-4.18.0-193.14.2.el8_2.x86_64-x86_64-with-centos-8.2.2004-Core
Python Version: 3.7.7

**Additional context**
DEBUG logs attached:
[rip.txt](https://github.com/morpheus65535/bazarr/files/5215058/rip.txt)

Also, this is the second time it happened. Before it got stuck in this episode it got stuck in another episode of another series. I had to solve manually so it could advance to the next wanted subtitles.

**Comment by morpheus65535** [comment]
Duplicate #1105
