### ISSUE TITLE
In a Debug-log I set the filter to Error - but the filter still display the Debugs

### ISSUE THREAD

**Issue by cphmichael** [morpheus65535/bazarr#1108]
Latest "hotio/bazarr:unstable"

In a Debug-log I set the filter to Error - but the filter still display the Debugs:

![image](https://user-images.githubusercontent.com/45288008/93056123-43a4dc00-f66c-11ea-858c-f4e8f9dd4381.png)

**Comment by morpheus65535** [comment]
That's normal behavior. Filter work like `Error or greater`.
