### ISSUE TITLE
Vote: Revamp existing icons

### ISSUE THREAD

**Issue by agneevX** [morpheus65535/bazarr#1109]
I think Bazarr's web assets need to be revamped. 

These are my suggestions:

1. <img src="https://cdn.discordapp.com/attachments/540191312964485120/754963882614980688/unknown.png" width="200">

2. <img src="https://user-images.githubusercontent.com/19761269/93056531-2c74e700-f68a-11ea-941d-b71e4f368c8a.png" width="200">

3. <img src="https://user-images.githubusercontent.com/19761269/93056537-30086e00-f68a-11ea-8055-a1e046e0f519.png" width="200">

**VOTE NOW**:

[![](https://api.gh-polls.com/poll/01EJ5S8V20W1YFZVFY5KDF1C3Y/1)](https://api.gh-polls.com/poll/01EJ5S8V20W1YFZVFY5KDF1C3Y/1/vote)
[![](https://api.gh-polls.com/poll/01EJ5S8V20W1YFZVFY5KDF1C3Y/2)](https://api.gh-polls.com/poll/01EJ5S8V20W1YFZVFY5KDF1C3Y/2/vote)
[![](https://api.gh-polls.com/poll/01EJ5S8V20W1YFZVFY5KDF1C3Y/3)](https://api.gh-polls.com/poll/01EJ5S8V20W1YFZVFY5KDF1C3Y/3/vote)

**Comment by morpheus65535** [comment]
First one is the actual logo, right? How does the other looks on the actual purple background?

**Comment by agneevX** [comment]
Yes it is. As of now, this change is only for the favicon/PWA app icons, not for anything else. 

For those, a new icon has to be created tbh.

**Comment by morpheus65535** [comment]
Go for the first one! :-)

Thanks!
