### ISSUE TITLE
Search for other language subtitle if main language is not available

### ISSUE THREAD

**Issue by ShadXo** [morpheus65535/bazarr#111]
Is there an option to search for a second language sub(as fallback option) if first language sub is not found?
If the wanted first language sub is found overwrite the existing subtitle/second language sub.

I only want 1 subtitle file and dont need the second language if the first one is available.

Is there already an option somewhere I can find?

**Comment by morpheus65535** [comment]
Unfortunately, that's not an option. Bazarr rely on Subliminal module that do not support this use case. You'Re going to have to live with single language mode enabled and wait for the desired language subtitle to come out.

**Comment by ShadXo** [comment]
Oke, thats why I didn't find anything :). Thanks for your response and work on Bazarr!
