### ISSUE TITLE
podnapisi.net can't find subtitles

### ISSUE THREAD

**Issue by dl1ch** [morpheus65535/bazarr#1112]
**Describe the bug**
When manually searching for subtitles with the provider "podnapisi", it cannot find subtitles for the series i am looking for (Game of Thrones). I checked the website itself and the subtitles are available for the series. When I tried to access the search string

https://podnapisi.net/subtitles/search/old?sXML=1&sL=en&sK=game+of+thrones&sTS=8&sTE=6&sY=2010

it gives no results. If you delete the year (2010) it finds the wanted subtitles

https://podnapisi.net/subtitles/search/old?sXML=1&sL=en&sK=game+of+thrones&sTS=8&sTE=6&sY=

Add feature to search subtitles without year?

Debug log:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5222864/bazarr.log)

**To Reproduce**
Manually search for subtitles for movie/series (podnapisi provider)

**Expected behavior**
Expect to find the subtitles listed on the site.

**Software (please complete the following information):**
 - Bazarr: v0.9.0.3
 - Radarr version 0.2.0.1504
 - Sonarr version 2.0.0.5344
 - OS: Docker container (linuxserver/bazarr, linuxserver/sonarr, linuxserver/radarr)

**Comment by morpheus65535** [comment]
We can't drop year from search criteria as you'll start getting subtitles from series with the same name but released years ago. In fact, the issue here is that Bazarr use the wrong year from Sonarr. There's not really anything I can do about it. Bad information need to be fixed at source.

**Comment by dl1ch** [comment]
I couldn't agree more, but the issue is mostly, that the source (it could be Sonarr/Radarr information or the subtitles owner that set the wrong information) is never 100% correct. I just meant if you would consider making a filter for the search for each series (and while searching for subtitles apply that filter), such as:

Filter:
Search by: Name, Year, IMDB ID if supported etc.

Then you could unselect "Year" for only this series and it would work. Better than not having / receiving subtitles at all.

Or maybe considering extending the search for + or - few years (example: +-3 years) if no subtitles were found for that year. As its difficult to have two series with the exact name on a "short" time frame... I don't say its not possible, but its rather rare :)

Anyway, big thanks for this awesome tool!

**Comment by morpheus65535** [comment]
Your first suggestion would mean a major refactoring of subliminal. In fact, I was thinking about the second one and think it could be easier. I must look into it.

**Comment by morpheus65535** [comment]
Should be fixed in dev branch right now.

**Comment by dl1ch** [comment]
Tested the dev branch (linuxserver/bazarr:development) and now its finding the searched subtitles. Thanks!
