### ISSUE TITLE
BAZARR subtitles file doesn't seems to be text based. Skipping this file .......

### ISSUE THREAD

**Issue by cphmichael** [morpheus65535/bazarr#1114]
I am running latest: hotio/bazarr:unstable

I have a few error like this:

![image](https://user-images.githubusercontent.com/45288008/93435478-cf677400-f8c9-11ea-89f7-76d3752a346f.png)

17/09/2020 04:06:49|ERROR   |root                            |BAZARR subtitles file doesn't seems to be text based. Skipping this file: /tv/Killjoys/Season 05/Killjoys - S05E02 - Blame It on the Rain Bluray-1080p.en.srt|'Traceback (most recent call last):\n  File "/app/bazarr/list_subtitles.py", line 447, in guess_external_subtitles\n    text = text.decode(guess["encoding"])\n  File "/usr/lib/python3.8/encodings/cp1254.py", line 15, in decode\n    return codecs.charmap_decode(input,errors,decoding_table)\nUnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 27521: character maps to <undefined>'|

17/09/2020 04:06:50|ERROR   |root                            |BAZARR subtitles file doesn't seems to be text based. Skipping this file: /tv/Killjoys/Season 05/Killjoys - S05E10 - Last Dance Bluray-1080p.en.srt|'Traceback (most recent call last):\n  File "/app/bazarr/list_subtitles.py", line 447, in guess_external_subtitles\n    text = text.decode(guess["encoding"])\n  File "/usr/lib/python3.8/encodings/cp1254.py", line 15, in decode\n    return codecs.charmap_decode(input,errors,decoding_table)\nUnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 11794: character maps to <undefined>'|

This is the Killjoys S05E10 - .srt

https://pastebin.com/FMRAcrX3

**Comment by josdion** [comment]
@cphmichael What is original character encoding of your srt files. If they are UTF-8, it's probably related to this chardet issue:  
[https://github.com/chardet/chardet/issues/148](https://github.com/chardet/chardet/issues/148)

**Comment by cphmichael** [comment]
In Bazarr is "Encode Subtitles To UTF8" enable.

I was advised to do that in Discord.

![image](https://user-images.githubusercontent.com/45288008/93458184-490a5c80-f8e0-11ea-8889-7aa06196a409.png)

**Comment by morpheus65535** [comment]
@josdion you want to give a try to [Charamel](https://github.com/chomechome/charamel)?

**Comment by cphmichael** [comment]
Here is "Killjoys - S05E10 - Last Dance Bluray-1080p.en.srt"

https://pastebin.com/XYm8EuBe

**Comment by josdion** [comment]
> 
> 
> @josdion you want to give a try to [Charamel](https://github.com/chomechome/charamel)?

Sure, why not. It seems pretty easy to replace chardet and it's also faster.

**Comment by cphmichael** [comment]
I got help from Discord:
classiccrimei:
@Michael look @ line 804, i believe the ” needs to be replaced with "
(of your .SRT)

**Comment by morpheus65535** [comment]
@josdion I was looking at it and it was quite easy to implement charamel. I did it for Bazarr but not submodules. It should be enough to see if it improve the situation.

@cphmichael can you test my latest commit to dev branch?

**Comment by cphmichael** [comment]
I updated to latest: hotio/bazarr:unstable
Click'ed on: Update all Episode Subtitles from disk

In the log I can see these new errors that wasn't there before: **BAZARR unable to index external subtitles.**
I can see new "Wanted" there wasn't there before.

I checked some of the "Wanted" series. 
It seems like the problem is there are some old .srt that are missing the language code "en".
If I delete the .srt with the missing "en" and do another scan, then it is removed from the "Wanted".

You can see a 'debug' log here (search for "BAZARR unable to index external subtitles")

https://pastebin.com/P9Nh5FK6

**Comment by cphmichael** [comment]
![image](https://user-images.githubusercontent.com/45288008/94043873-bc730900-fdcd-11ea-8761-447950329695.png)

![image](https://user-images.githubusercontent.com/45288008/94044008-e1677c00-fdcd-11ea-9871-3360141ce5c2.png)

**Comment by morpheus65535** [comment]
Send me one of those srt please.

**Comment by cphmichael** [comment]
This is a link to:

Britannia - S01E04 - Episode 4.srt

https://pastebin.com/LyW6QgVY

**Comment by morpheus65535** [comment]
My bad. I've just pushed a fix to dev branch and your subtitles without language code in filename should be recognized now. Can you confirm?

**Comment by cphmichael** [comment]
The latest update fixed the problem.
No errors in the log and no Wanted items :-)

Thank you very much.

**Comment by morpheus65535** [comment]
Pleasure mate! Enjoy!
