### ISSUE TITLE
Error with postprocessing

### ISSUE THREAD

**Issue by michpas** [morpheus65535/bazarr#1115]
**Describe the bug**
Postprocessing error

**To Reproduce**
Install fresh bazarr linux server docker
Add environmental parameter: -e DOCKER_MODS = wayller/bazarr-mod-subsync:latest
(https://hub.docker.com/r/wayller/bazarr-mod-subsync)
Start container. Let it install.
Turn on postprocessing option.
enter in pp script: subsync --cli sync --sub '{{subtitles}}' --ref '{{episode}}' --out '{{subtitles}}' --overwrite
Configure sonarr, radarr
Activly trigger search for a wanted subtitle.
Results in error in log and no postprocessing

Tries:
Tried it with clean installs in 0.9.0.3 and clean install in 0.9.0.4 (dev docker); with starting fresh with the congfig folder.
When turning postprocessing off, there is no error
When leaving the postprocessing turned 'on', but with an empty CLI command; it still produces the same error
When running the CLI command manually in the docker it runs ok.

**Expected behavior**
The postprocessing script to run and bazarr to complete the subtitle dl without issues.

**Software (please complete the following information):**
 - LinuxServer bazarr docker latest. Also tried development version. Same issue

Included the debug log.

 
[bazarr-pp-error.log](https://github.com/morpheus65535/bazarr/files/5251412/bazarr-pp-error.log)

**Comment by morpheus65535** [comment]
Wait, why do you think you can call `subsybc` directly when using LinuxServer images? Subsync isn't included in any supported images (including (LSIO/Hotio) thta I'm aware. If you want to sync subtitles, you have to use the embedded subtitles synchronization feature (checkbox at the bottom of Settings-->Subtitles) or manage to get subsync installed by yourself.

**Comment by michpas** [comment]
Hi morpheus. The docker: wayller/bazarr-mod-subsync:latest
Is an add on.docker for the linuxserver version. 
It basically installs sunsync in the linuxserver bazarr docker.
I have done further testing and sometimes the post processing works and sometomes not.
This doesnt seem to be related to the cli command itself, but more related to the video file.
My conclusuon so far: if the video file has an audio stream without a language tag, the cli cmd seems to error out. 

Ill test this some more over the next days.
An videofile with an audiotrack without audio-langauge set might be causing the error.

**Comment by morpheus65535** [comment]
I've pushed a fix to dev branch. Can you test it please? Thanks!

**Comment by RikP** [comment]
i just checked with the development build and postprocessing is happening. BUT i am getting an error that subsync doesn't find the correct asset dictionary:

```
[+] updating asset list [!] there is no assets needed to perform synchronization [-] asset dictionary None / Dutch is missing 
```

Seems the None in that string is wrong. I opened a ticket also at subsync

**Comment by morpheus65535** [comment]
The fix I made was to prevent custom post-processing from interrupting the subtitles download process. If the audio language code2 still cannot be converted from the actual video first audio track language name, You'll just get `None` as a replacement. Send me your `bazarr.db` in private on Discord and tell me which episode/movie is giving you this error.

**Comment by michpas** [comment]
Thanks both. Ill check later when time.
My assumption:
If indeed no.language tag.is set in the audiostream, subsync cant work. As it simply cant recoginze the language.
If bazarr sends through in these cases 'none'. That is fine as sunsync will simply do nothing (no dic)'and sub is still dled.
The root problem is with the audiostream in the videofile (missing lang tag) and that caused bazarr to crash. Understanding morpheus put a fix on.place to avoid bazarr crash.

Thanks morpheus !

Ill test later

**Comment by morpheus65535** [comment]
@RikP If you can't get an audio track language from your files, you should remove the `--ref-lang` argument from your subsync post-processing command and let subsync guess it.

**Comment by morpheus65535** [comment]
Is it ok if I close this issue?

**Comment by michpas** [comment]
Hi Morpheus. Thanks for inquiry. 
I was fixing some other items. and modified the original video files. 
For proper retesting I'll need to find/download the original files. Haven't had the time. I'll try to do so within a week.
Thanks
M

**Comment by michpas** [comment]
Hi Morpheus,
I wanted to test this quickly. Found the file.
All looks great.
Below the debug log on the previous version and the latest version. Same videofile.
Works now perfectly. 
Thanks for this great work.

**Previous version**

27/09/2020 23:11:26|DEBUG   |subliminal_patch.core           |Saving <OpenSubtitlesSubtitle 'http://www.opensubtitles.org/en/subtitles/8341946/sid-usQXfjVra4DQNeYbtx8MsumPY,4/sputnik-nl' [nl:utf-8]> to '/media/filmsHD/Sputnik (2020)/Sputnik 2020 1080p WEB-DL DD5 1 H 264-EVO.nl.srt'|
27/09/2020 23:11:26|INFO    |subliminal_patch.subtitle       |Applying mods: ['remove_HI', 'remove_tags', 'common', 'fix_uppercase']|
27/09/2020 23:11:27|DEBUG   |root                            |BAZARR Subtitles file saved to disk: /media/filmsHD/Sputnik (2020)/Sputnik 2020 1080p WEB-DL DD5 1 H 264-EVO.nl.srt|
27/09/2020 23:11:27|ERROR   |app                             |Exception on /api/movie_subtitles_download [POST]|Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request    rv = self.dispatch_request()  File "/app/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request    return self.view_functions[rule.endpoint](**req.view_args)  File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper    resp = resource(*args, **kwargs)  File "/app/bazarr/bazarr/../libs/flask/views.py", line 89, in view    return self.dispatch_request(*args, **kwargs)  File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request    resp = meth(*args, **kwargs)  File "/app/bazarr/bazarr/api.py", line 62, in wrapper    return actual_method(*args, **kwargs)  File "/app/bazarr/bazarr/api.py", line 1112, in post    result = download_subtitle(moviePath, language, audio_language, hi, forced, providers_list,  File "/app/bazarr/bazarr/get_subtitle.py", line 262, in download_subtitle    command = pp_replace(postprocessing_cmd, path, downloaded_path, downloaded_language,  File "/app/bazarr/bazarr/helper.py", line 109, in pp_replace    pp_command = pp_command.replace('{{episode_language_code2}}', episode_language_code2)TypeError: replace() argument 2 must be str, not None|


new version
27/09/2020 23:27:48|DEBUG   |subliminal_patch.core           |Saving <OpenSubtitlesSubtitle 'http://www.opensubtitles.org/en/subtitles/8341946/sid-usQXfjVra4DQNeYbtx8MsumPY,4/sputnik-nl' [nl:utf-8]> to '/media/filmsHD/Sputnik (2020)/Sputnik 2020 1080p WEB-DL DD5 1 H 264-EVO.nl.srt'|
27/09/2020 23:27:48|INFO    |subliminal_patch.subtitle       |Applying mods: ['remove_HI', 'remove_tags', 'common', 'fix_uppercase']|
27/09/2020 23:27:49|DEBUG   |root                            |BAZARR Subtitles file saved to disk: /media/filmsHD/Sputnik (2020)/Sputnik 2020 1080p WEB-DL DD5 1 H 264-EVO.nl.srt|
27/09/2020 23:27:49|DEBUG   |root                            |BAZARR Using post-processing command: subsync --cli sync --sub '/media/filmsHD/Sputnik (2020)/Sputnik 2020 1080p WEB-DL DD5 1 H 264-EVO.nl.srt' --ref '/media/filmsHD/Sputnik (2020)/Sputnik 2020 1080p WEB-DL DD5 1 H 264-EVO.mkv' --out '/media/filmsHD/Sputnik (2020)/Sputnik 2020 1080p WEB-DL DD5 1 H 264-EVO.nl.srt' --overwrite|
27/09/2020 23:27:51|INFO    |root                            |BAZARR Post-processing result for file /media/filmsHD/Sputnik (2020)/Sputnik 2020 1080p WEB-DL DD5 1 H 264-EVO.mkv : [*] starting synchronization /media/filmsHD/Sputnik (2020)/Sputnik 2020 1080p WEB-DL DD5 1 H 264-EVO.nl.srt [+] updating asset list [!] there is no assets needed to perform synchronization [-] asset dictionary Dutch / Russian is missing |
27/09/2020 23:27:51|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): 192.***.***.***:8310|
