### ISSUE TITLE
postprocessing. last charakter in command is not saved

### ISSUE THREAD

**Issue by michpas** [morpheus65535/bazarr#1116]
**Describe the bug**
In 0.9.0.4 development build. Linux server docker

Steps:
Make an entry in the post command cli postprocessing box. 
Press  'save' 
Press refresh
The last charakter is no longer there. See included the images of before and after.

Note: Also when debug is turned on: I can see the CLI-command being pushed; but it lacks the final charakter.
Therefor the postprocessing script doesn't return any valid value. See debug statement below; where the last "'" is gone.

..
09-20 10:12:34	stdout	2020-09-20 12:12:34,470 - root                             (7eff371d8b20) :  DEBUG (get_subtitle:275) - BAZARR Using post-processing command: subsync --cli sync --sub-lang 'nld' --ref-lang 'rus' --sub '/media/filmsHD/Name of videofile.nl.srt' --ref '/media/filmsHD/Name of videofile.mkv' --out '/media/filmsHD/Name of videofile.srt
..

**Expected behavior**
After pressing save and refresh that the command box has the full command.

**Screenshots**
![last charakter lost](https://user-images.githubusercontent.com/66222810/93709021-36d82a80-fb3b-11ea-9f9e-814e31af2e45.jpg)

Bazarr Version:
0.9.0.4
Sonarr Version:
2.0.0.5344
Radarr Version:
0.2.0.1504
Operating System:
Linux-4.4.59+-x86_64-with
Python Version:
3.8.5
Bazarr Directory:
/app/bazarr
Bazarr Config Directory:
/config

**Comment by morpheus65535** [comment]
Duplicate #309
