### ISSUE TITLE
Parsing existing subtitles fails for some movies

### ISSUE THREAD

**Issue by joachimbaten** [morpheus65535/bazarr#1119]
**Describe the bug**
After switching to develop branch I got movies with existing titles appearing in the missing section.

**To Reproduce**
1. Switch to the 'Develop' branch
2. Go to a movie with 'sub' subtitles
3. Scan disk
4. Existing detected subtitles are gone

**Software (please complete the following information):**
- Bazarr Version: Latest Develop
- Sonarr Version: 3.0.3.924
- Radarr Version: 0.2.0.1504
- Operating System: Linux-5.4.60-1-pve-x86_64-with-debian-10.5
- Python Version: 3.7.3

**Additional context**
After some testing I also saw the problem with a movie with only 'srt' subtitles. Investigating the log file it has something to do with the encoding: " text = text.decode('utf-8')UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte"

_Switching back to master branch, and scanning the disk again fixes the issue._

I attached 2 debug logs, 1 when scanning when there is a .sub and .srt file. And 1 where there are 2 .srt files.

[bazarr-error-with-srt.log](https://github.com/morpheus65535/bazarr/files/5277310/bazarr-error-with-srt.log)
[bazarr-error-with-sub.log](https://github.com/morpheus65535/bazarr/files/5277311/bazarr-error-with-sub.log)

**Comment by joachimbaten** [comment]
I did some more investigation myself, and I think the .sub files have nothing to do with it. It's the encoding in the files itself.
Bazarr logs it detects an encoding:

>  |BAZARR detected encoding <Encoding.TIS_620: 'tis_620'>|

But tries to read it with utf-8

> |Traceback (most recent call last):  File "/opt/bazarr/bazarr/list_subtitles.py", line 444, in guess_external_subtitles    text = text.decode('utf-8')UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 3: invalid start byte

**Comment by morpheus65535** [comment]
TBH, that's the problem with encoding guessing... in latest dev we moved from chardet to charamel module for encoding detection as it seems to be better at guessing encoding but it doesn't means it will never fail... Is it the only subtitles file causing this issue or do you have a lot?

**Comment by morpheus65535** [comment]
And BTW, how is guessed the encoding by notepad++ or sublime text 3?

**Comment by joachimbaten** [comment]
I did some more testing and I think it failes on 'guessing the encoding of binary sub files'.
I have a movie with 3 subtitle files, 2 srt with different encodings and 1 binary sub file. In the log you see 2 detected encodings, those are correct according to notepad++. Then the error occures and I guess this is on de 'binary sub'-file.

If I remove the sub-file and let it scan the movie folder again, no errors occure and the 2 subtitles are detected.

Log file with the '*.sub' file present:
[bazarr_with_sub_file.log](https://github.com/morpheus65535/bazarr/files/5291876/bazarr_with_sub_file.log)

Log file with the '*.sub' file removed:
[bazarr_without_sub_file.log](https://github.com/morpheus65535/bazarr/files/5291875/bazarr_without_sub_file.log)

**Comment by morpheus65535** [comment]
Can you share one of those .sub file with me so I can debug? You can send it in private on Discord.

**Comment by joachimbaten** [comment]
Ok, I send you some samples on Discord. I hope you can reproduce the issue.

**Comment by morpheus65535** [comment]
This should fix your issue. Please confirm.

**Comment by morpheus65535** [comment]
Shit... it seems to not be working with python 3.7... I'm going to rework that.

**Comment by joachimbaten** [comment]
I worked around it by replacing the continue on line 461 by a simple log-line "logging.debug("Type Error duing subtitle parsing " + subtitle_path)"

Since it's the end of the loop, the 'continue' is not mandatory I think

At least now it is running again, and de files are detected corretly

**Comment by morpheus65535** [comment]
I've push a fix, you can pull it?

**Comment by joachimbaten** [comment]
Fixed, thx!
