### ISSUE TITLE
I just got bazarr setup and started it getting subs for all tv  since i could not aim it at just the foreign folder.

### ISSUE THREAD

**Issue by tostane** [morpheus65535/bazarr#1120]
**Describe the bug**
I went to plex and watched a show    xxxyyy   just fine  last night     after running bazarr  all night today i check sonar and that show shows if i search for it but if i browse sonar to the show its not there   it is also not on plex any longer.     the folder still exists and the show is in it.     sonarr says all the episodes are there if i search it and check that way.        

A long time ago about 2 years back there was a problem on sonarr with over so many files but it seems to be fixed the only problem i notice now is some times using mergerfs joining my drives it seems to be slow pulling all the names in when i open shows.    im wondering if bazarr still has the bug when you get past so many thousand files why would it make shows disappear in sonars database?    I have a script that updated changed to sonar to plex so something make the show disappeared in sonarr.    I think im going to stop using bazarr  it just not ready yet.    It also needs filters like sonar has.

I looked at sonar log files and everything looked normal for that show.  I hope this helps find something.    Im done messing with it for a while.
im' using the python 3 version of everything on debian 10.5.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: [e.g. v 0.6.1]
 - Radarr version [e.g. v 0.2.0.0001]
 - Sonarr version [e.g. v 2.0.0.0001]
 - OS: [e.g. Windows 10]

**Additional context**

**Comment by morpheus65535** [comment]
Sorry but I don't get what's your issue here... if you need support, please come to Discord for live support with the team.
