### ISSUE TITLE
JSONDecodeError. Exception info: 'Expecting value: line 1 column 1 (char 0)'|

### ISSUE THREAD

**Issue by cphmichael** [morpheus65535/bazarr#1123]
Bazarr Version: 0.9.0.4 (latest hotio/bazarr:nightly)
Sonarr Version: 3.0.3.928
Radarr Version: 3.0.0.3820
Operating System: Linux-4.19.107-Unraid-x86_64-with
Python Version: 3.8.5

I seems like there is a problem with SuperSubtitles.

I have errors saying:
* JSONDecodeError. Exception info: 'Expecting value: line 1 column 1 (char 0)'
* IndexError. Exception info: 'list index out of range'
* Falling back to non-year results as year wasn't found (2018)
* (disabled because: IndexError)|

![image](https://user-images.githubusercontent.com/45288008/94560183-8ec11080-0262-11eb-88ee-b9be38d06942.png)

bazarr.log
https://pastebin.com/kK8MribP

**Comment by morpheus65535** [comment]
If they are providing invalid JSON, there's not much we can do about it. :-/

**Comment by cphmichael** [comment]
It only happens sometime - most of the time I don’t see errors from them.

**Comment by morpheus65535** [comment]
```
29/09/2020 12:34:13|INFO    |root                            |Throttling supersubtitles for 10 minutes, until 20/09/29 12:44, because of: JSONDecodeError. Exception info: 'Expecting value: line 1 column 1 (char 0)'|
```

This means that the JSON returned by the provider isn't valid. The `IndexError` exception is because we try to access the returned JSON when is none (or it is invalid so it cannot be parsed).

**Comment by morpheus65535** [comment]
I've been working yesterday and this morning on improving supersubtitles provider. I think the fixes I've made should make it more robust and should fix your issue. Can you test with the latest commit in dev branch?

**Comment by cphmichael** [comment]
I have installed the latest hotio/bazarr:nightly
Thank you very much for your effort to improve supersubtitles.
Lets hope that fixed it.

**Comment by cphmichael** [comment]
The updated Bazarr has been running for about 16 hours and downloaded two subtitles from SuperSubtitles - with no errors in the log, so I think you have fixed the problem:

![image](https://user-images.githubusercontent.com/45288008/94797823-f9985600-03e0-11eb-9f03-ebe7909956cc.png)

**Comment by morpheus65535** [comment]
Good news, I'll close this issue but you can re-open it if it happens again.

**Comment by anonyme123** [comment]
Getting the same error: 

Throttling supersubtitles for 10 minutes, until 21/12/28 16:52, because of: JSONDecodeError. Exception info: 'Expecting value: line 1 column 1 (char 0)' | 28/12/2021 16:42:20 
Using supersubtitles again after 10 minutes, (disabled because: JSONDecodeError) | 28/12/2021 16:42:19

**Comment by morpheus65535** [comment]
Seems to be an issue on their side: https://github.com/pannal/Sub-Zero.bundle/issues/778

BTW open your own issue, do not try to necromancy a 14 months old closed issue.
