### ISSUE TITLE
Skipping , because it doesn't match our series/episode

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#1124]
**Describe the bug**
I can't find subtitles for one tv series.

**To Reproduce**
1. Enable opensubtitles provider
2. Add `Raised by Wolves (2020) S01E01` in Sonarr and try to find subtitles (in Spanish in my case).
3. I can see `Found 8 subtitle(s)` message in the logs but then `Skipping , because it doesn't match our series/episode`
4. The subtitles are available in opensubtitles. I think the year in the title is causing some issues...

**Software (please complete the following information):**
 - Bazarr: v0.9.0.3

**Comment by halali** [comment]
Fixed in dev Branch

**Comment by ngosang** [comment]
@halali Could you point me to the issue/commit?

**Comment by halali** [comment]
https://github.com/morpheus65535/bazarr/commit/dd93072274a379448f813f0b7a0598fa0efc64a7#diff-8401ECE7B43731AE8A86F0D2FE0BBA32

**Comment by ngosang** [comment]
Thank you!
