### ISSUE TITLE
Web UI bug in manual search

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#1125]
**Describe the bug**
I can't see the matches in manual search because there is a bug in the UI. I see a scrollbar but I can't scroll.
Browser Firefox. Development branch.

**Screenshots**
![image](https://user-images.githubusercontent.com/10577978/94601368-aebcf800-0293-11eb-8cf1-112d3fd97f42.png)

**Software (please complete the following information):**
 - Bazarr: development

**Comment by morpheus65535** [comment]
Fixed in b2f6eececfaa74571bb2066ddcef83b5924267d4 2 hours ago but pushed right now.
