### ISSUE TITLE
Radarr/Sonarr to Bazarr path mapping fails

### ISSUE THREAD

**Issue by jaretclifton** [morpheus65535/bazarr#1126]
**Describe the bug**
Until one month ago, path mapping for my Windows Radarr/Sonarr installs to my Linux Bazarr install worked perfectly. \\\host\share to /mountpoint/folder. Now I get a "the path does not appear to be valid \\\host\share" for all items, series and movies.

**To Reproduce**
1. Go to series or movies.
2. Mouse over the Path Exists exclamation triangle.
3. Receive the error message.
4. View logs
5. See "Search is not active for this movie/series"

**Expected behavior**
Path mapping should work as designed. The network share is available via /mountpoint/folder and can be traversed from the Bazarr host.

**Screenshots**
N/A

**Software (please complete the following information):**
Bazarr Version: 0.9.0.4
Sonarr Version: 3.0.3.935
Radarr Version: 3.0.0.3824
Operating System: Linux-5.4.55-1-pve-x86_64-with-Ubuntu-18.04-bionic
Python Version: 3.7.5
Bazarr Directory: /opt/bazarr
Bazarr Config Directory: /opt/bazarr/data

**Comment by morpheus65535** [comment]
If you see an UNC path in error message, it's because your path mapping doesn't include a substring of this path to replace by something that Bazarr can access (ie: the mountpoint). I suggest you come see us on Discord for live support with the dev team.
