### ISSUE TITLE
A question about OpenSubtitles in Bazarr?

### ISSUE THREAD

**Issue by cphmichael** [morpheus65535/bazarr#1128]
In Bazarr I have set Sonarr
 
* Minimum Score = 90
*  Subtitles synchronization, Only for score below 95

If I enable OpenSubtitles with VIP and Skip wrong FPS - Bazarr download most of the subtitles from OpenSubtitles.
When I play the series in Plex a lot of the subtitles are very much out of sync.
When I look into History > Series I can see those (out of sync) subtitles have a score of 95/96 something % (95.40-96.40).
If I do a manual sync, the 95/96% subtitles are about 15 - 25 seconds off.

If I disable OpenSubtitles, Bazarr find a subtitles from addic7ed, SuperSubtitles or SubScene around 94.xx % and the sync has an offset about 0.01 - 0.20 seconds.

I thought the problem maybe could be that I in Sonarr have disabled 'Rename Episodes' and the file naming therefore confused Bazarr.

I therefore asked for help in Discord and I have now enabled Sonarr 'Rename Episodes' and copied TRaSH setup:
* {Series CleanTitle} - S{season:00}E{episode:00} - {Episode CleanTitle} [{Quality Full}] [{MediaInfo Simple}]{-Release Group}

but the Bazarr score is exactly the same with or without 'Rename Episodes' enabled.

Do you use OpenSubtitles - and if Yes, do you see the same behavior?

Is it possible you can do some magic to the OpenSubtitle code - like you did to the SuperSubtitles problem :-)

**Comment by morpheus65535** [comment]
Unfortunately, OpenSubtitles often have bad subtitles with good metadata. There's nothing I can do about this because we trust the metadata of subtitles as we got them from the providers. You'll have to rely on subtitles synchronization or stop using OS.
