### ISSUE TITLE
Can't start bazarr as a non root user

### ISSUE THREAD

**Issue by virusperfect** [morpheus65535/bazarr#1130]
Ever since the update to 0.9.0.4 I can't run bazarr as a non root user.
I used to have a daemon running with User=bazarr and Group=media but now bazarr won't start anymore with this configuration. When I type `sudo systemctl status bazarr` I get this:

(7f0e7d62f740) :  INFO (init:60) - BAZARR installing requirements...
(7f0e7d62f740) :  INFO (init:64) - BAZARR requirements installed.
(7f0e7d62f740) :  INFO (init:70) - Bazarr is being restarted...
(7fc1a3962740) :  INFO (init:60) - BAZARR installing requirements...
(7fc1a3962740) :  INFO (init:64) - BAZARR requirements installed.
(7fc1a3962740) :  INFO (init:70) - Bazarr is being restarted...

over and over again.
The user bazarr does own everything in `/opt/bazarr`.

When I run the daemon as User=root and Group=root everything works.

**Comment by morpheus65535** [comment]
Duplicate #1087
