### ISSUE TITLE
invalid date in log

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#1134]
1. Enable debug log
2. Go to 1 wanted subtitle and click automatic search for that subtitle
3. Go to the logs

PD: As enhancement you can do something to keep time column in one line (no word wrap)
![image](https://user-images.githubusercontent.com/10577978/95002885-4050a080-05d9-11eb-88e5-3ee845948368.png)

Raw traces:
```
04/10/2020 00:37:49|DEBUG   |subliminal_patch.core           |GuessIt found: {
    "title": "Millennium",
    "year": 1996,
    "season": 3,
    "episode": 22,
    "episode_title": "Goodbye to All That",
    "container": "avi",
    "mimetype": "video/x-msvideo",
    "type": "episode"
}|
04/10/2020 00:37:49|DEBUG   |subliminal_patch.core           |Size is 367560704|
```

Bazarr Version: 0.9.0.4
Sonarr Version: 3.0.3.938
Python Version: 3.7.3

**Comment by morpheus65535** [comment]
Log viewer cannot parse debug log properly. Debug log should be consulted using a text editor. I'm not planning to fix this one.

**Comment by ngosang** [comment]
> As enhancement you can do something to keep time column in one line (no word wrap)

@morpheus65535 I see that in normal log too. I think you can add `white-space: nowrap;` in time column.

**Comment by morpheus65535** [comment]
It should be good now, can you confirm?

**Comment by ngosang** [comment]
Yes it's fixed.
