### ISSUE TITLE
show pointer cursor in tasks

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#1135]
Show pointer/hand cursor in "run task". I know is minor but it's not a feature request.
![image](https://user-images.githubusercontent.com/10577978/95003101-e7363c00-05db-11eb-8c7d-8c0ea220e86b.png)

Bazarr Version: 0.9.0.4
Sonarr Version: 3.0.3.938
Python Version: 3.7.3

**Comment by morpheus65535** [comment]
I agree, it should have been that way from the beginning. Thanks for reporting!
