### ISSUE TITLE
New season not synced

### ISSUE THREAD

**Issue by stefandevo** [morpheus65535/bazarr#114]
Hi, a new season of a series has been automatically added to Sonarr, but in Bazarr this season is not visible and of course it will not search for subtitles. I tried to manually sync via System tab but the season is not found.
Any ideas?

**Comment by stefandevo** [comment]
Also for some series, I have for example 10 episodes, and Bazarr only sees 3.

**Comment by morpheus65535** [comment]
In Bazarr, you'll only see episode that have an episode indexed in Sonarr. As the new season doesn't have episode on disk, it won't be in Bazarr.

**Comment by stefandevo** [comment]
But it does have files on disk...

**Comment by morpheus65535** [comment]
Can you give me the returned JSON from this API call:

    http://<sonarr-host>:8989/api/episode?seriesId=<series-id>&apikey=<your-sonarr-api-key>

```<series-id>``` is the ```id``` that you'll get by using this call:

    http://<sonarr-host>:8989/api/series?apikey=<your-sonarr-api-key>

**Comment by stefandevo** [comment]
[Archive.zip](https://github.com/morpheus65535/bazarr/files/2228632/Archive.zip)
Pls find two json files. One with the specific episode (first call) and the second with part of all the series.
You'll notice that season 8 already has 1 file.
Is there anything I can sent from Bazarr??

**Comment by stefandevo** [comment]
I see now this in my logs when refresh everything:

```
Traceback (most recent call last):
 File "/Users/USER/Library/Python/2.7/lib/python/site-packages/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/Users/USER/bazarr/bazarr/get_episodes.py", line 71, in sync_episodes
  c.execute(\\\INSERT INTO table_episodes(sonarrSeriesId, sonarrEpisodeId, title, path, season, episode, scene_name) VALUES (?, ?, ?, ?, ?, ?, ?)\\\, added_episode)
IntegrityError: UNIQUE constraint failed: table_episodes.path
```

Maybe this causes a stop on further processing?

**Comment by morpheus65535** [comment]
Haha! You got it!

Like a some of the early Bazarr adopter before you, you're running into a UNIQUE constraint that I put in the first version of the DB (which was a bad idea that I couldn't easily remove from code).

If you have a SQlite editor, you can stop bazarr and remove this constraint. You won't run into an issue like this after that. If you don't have one or don't know how to do this, I can do it for you. Just join me on Discord and send me your bazarr.db file.

**Comment by morpheus65535** [comment]
I've added an exception handling to inform early adopter of what to do in this case.

**Comment by stefandevo** [comment]
Ok thx. Tried with some editors, but it seems like I have to rebuild, not just drop. How can I connect to discord? Do you have server, channel, dm name?

**Comment by morpheus65535** [comment]
https://discord.gg/MH2e2eb

**Comment by Julien-D** [comment]
Would it be possible to post the solution please? I am running into the same issue?
Thank you :)

**Comment by Julien-D** [comment]
Could you help me the SQL command to run?
`ALTER TABLE table_episodes DROP UNIQUE (path)` does not work

**Comment by morpheus65535** [comment]
I would use this tools: https://sqlitebrowser.org/

**Comment by Julien-D** [comment]
It worked. Thank you
