### ISSUE TITLE
header is not responsive

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#1140]
**To Reproduce**
1. Open Bazarr (maximized window)
2. Resize the window horizontally until the sidebar disappears
3. Maximize the window again
4. You will the the grey menu does not return to his original position

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/10577978/95252075-c4469a80-081c-11eb-916f-2de3ed423c3b.png)

**Software (please complete the following information):**
 - Bazarr: development

**Comment by morpheus65535** [comment]
I can't reproduce it by doing the step you described. Can you confirm what browser you are using? I'm using latest Chrome and it's working fine.

**Comment by ngosang** [comment]
Firefox 81

**Comment by morpheus65535** [comment]
I've just tested with Firefox 81.0.1 on Windows 10 and I still cannot reproduce. I don't have a Linux desktop to test it.

**Comment by ngosang** [comment]
You have to resize until the sidebar disappear, then maximize.

![image](https://user-images.githubusercontent.com/10577978/95504595-4960b980-09ad-11eb-8fe9-a44d974d04aa.png)

**Comment by morpheus65535** [comment]
Ok sorry I was only minimizing it, not hiding it. I can reproduce with both Firefox and Chrome. I'm looking into it.

**Comment by morpheus65535** [comment]
Should be better with my latest fix to dev branch. Can you test it?

**Comment by ngosang** [comment]
Much better
