### ISSUE TITLE
Hearing-Impaired subtitles keep re-downloading every day

### ISSUE THREAD

**Issue by Flippage** [morpheus65535/bazarr#1141]
**Describe the bug**
I have all my shows set to find English or English: Hearing-Impaired subtitles. 
When Bazarr searches for missing subtitles, it will find Hearing-Impaired subs, and download them.
Once they're downloaded, it identifies them as just "en" subs, and thus "en:HI" is still missing.
The next time it searches, it will find the same subtitle release again, and then re-download it.

**To Reproduce**
1. Check history for an episode that appears in the history each day.
2. Go to that episode page, and look at the "Missing subtitles" - "en:HI" is missing.
3. Check the history for that episode - "en:HI" downloaded every day.

**Expected behavior**
When downloading en:HI subtitles, they should be marked as en:HI.
What I'm assuming is happening, is that the sub providers have the subs labelled as Hearing-Impaired, but when Bazarr looks at the downloaded file, it's not finding any Hearing-Impaired subtitles inside the file, just dialogue.
So, Bazarr then marks it as "en" instead, and en:HI is still missing.

It's happening on both OpenSubtitles and podnapisi providers. Both of which are basically the only ones that have subtitles for my shows. This is causing these providers to hit the free download limit each day, then the next day it downloads all the same subtitles again, and hits the limit before it can get subs for new videos.

**Screenshots**
![image](https://user-images.githubusercontent.com/10948118/95292437-fc032000-08b8-11eb-9a33-542306acab0f.png)

![image](https://user-images.githubusercontent.com/10948118/95291886-f5c07400-08b7-11eb-91d4-367ccee531a4.png)

![image](https://user-images.githubusercontent.com/10948118/95292484-12a97700-08b9-11eb-9c55-2e1969036548.png)

![image](https://user-images.githubusercontent.com/10948118/95292566-3e2c6180-08b9-11eb-8d76-63d17c6e9be6.png)

**Software (please complete the following information):**
 - Bazarr: v0.9.0.4
 - Radarr: 3.0.0.3873
 - Sonarr: 3.0.3.956
 - OS: Windows 10 - 64bit

**Additional context**
I guess the fix for this would be that if you download the en:HI sub, and it's not actually Hearing-Impaired, then Bazarr can keep it there as "en", but then blacklist that subtitle file?
Or, possibly an option in Bazarr to mark EITHER as Wanted, instead of both?

**Comment by morpheus65535** [comment]
Can you provide one specific subtitles with this issue?

I already have planned to use en.hi.srt for hearing-impaired subtitles but I have to wait for Plex, Emby and Jellyfin to support it. Without it, those subtitles be listed as English in those players. BTW, I'm in communication with them and there's plan to make it happen.

**Comment by Flippage** [comment]
That's awesome. Would be good to see in Plex whether it's going to be HI or not.

Here's one of the subtitle files:
[Below Deck - S04E14 - 50 Shades of Ben WEBDL-720p.en.srt.txt](https://github.com/morpheus65535/bazarr/files/5345240/Below.Deck.-.S04E14.-.50.Shades.of.Ben.WEBDL-720p.en.srt.txt)

And the contents of the srt in a pastebin:
https://pastebin.com/LnDMapNZ

**Comment by morpheus65535** [comment]
I've taken a look at this srt file and, although it's been reported as HI by the provider, there's no HI content in it. Currently, the only solution I see is to rename from `file.en.srt` to `file.en.hi.srt` and Bazarr will index it as an HI subtitles and will stop to try to download it again and again.

I'll give a couple of weeks to Plex, Emby and Jellyfin to implement it and I will start adding the `.hi` tag to the subtitles filename downloaded through Bazarr.

**Comment by ditmarvisser** [comment]
It seems to be an issue in Plex for at least 6 years now. https://forums.plex.tv/t/subtitle-naming-conventions-for-forced-and-hearing-impaired/78124. 

I'm also having this issue, and since the subtitle gets synced every time it is an unnecessary strain on my machine. 

Will this be retroactively applied to all downloaded HI subtitles?

**Comment by morpheus65535** [comment]
Plex implemented the required fix. I'm waiting on Emby and Jellyfin to enable file naming fix.

No, we won't be able to retroactively fix HI subtitles. It will only apply to newly downloaded subtitles.

**Comment by ditmarvisser** [comment]
Any update on this? Maybe a toggle if you only use Plex in the meantime?

**Comment by morpheus65535** [comment]
> Any update on this? Maybe a toggle if you only use Plex in the meantime?

I'm planning to bundle this in v0.9.1. No ETA for now.

**Comment by morpheus65535** [comment]
It's now enabled in v0.9.1 (dev branch for now). New HI subtitles will use the new naming scheme (ie: en.hi.srt).

**Comment by tyrysss** [comment]
> It's now enabled in v0.9.1 (dev branch for now). New HI subtitles will use the new naming scheme (ie: en.hi.srt).

I just came with a confused issue today. When it comes with that naming scheme en.hi.srt, VLC will auto see it as Hindi language.

Is there a way to make it .hi.en.srt or something equivalent automatically (other than manually edit it)?

Also thanks a lot for your creation of this app. <3

[https://imgur.com/Js86IuD](url)
[https://imgur.com/IzBgtlS](url)

<img width="309" height="64" alt="Image" src="https://github.com/user-attachments/assets/940835b9-6466-4740-94a9-bb927dd6e00f" />

<img width="585" height="463" alt="Image" src="https://github.com/user-attachments/assets/9baaa5c8-b109-44f0-a5b6-e18a66f2253e" />
