### ISSUE TITLE
Opensubtitles error "Download Limited Reached" (forced to wait 6 hours, even when changing VIP account)

### ISSUE THREAD

**Issue by FiyiK** [morpheus65535/bazarr#1144]
**Describe the bug**
For a massive subtitle downloader as me, bazarr is helping me a lot! Except the problem i have since the new Bazarr version with the new UI.
I have 5 VIP accounts on Opensubtitles.org and contacted the admin if it's OK to exceed the limits with downloading subtitles. Admin confirmed that i'll need to pay for each account to get VIP, that way i would have 1000 subtitles each day for one account separately. There is no IP blocking. 

I worked for a long time with Bazarr without any issues and by changing my VIP accounts all the time when i reached the limit on one. 

But last months, even if i change my VIP account. The problem with error " download limit reached " won't go away. Even if i change my VIP account, i am forced to wait for 6 hours. Some kind of, after 6 hours, my second VIP account works while it should directly after changing it. 

I have found a way to force enable my VIP account. But it doesn't work each time, especially last 2 weeks.
What i did was, when i got the " download limit reached " error. I did go to settings->providers and changed my VIP 1 account to VIP 2.

After that i did go to system->providers and resetted the provider, refreshed and choose to restart Bazarr.
After the restart completed, i did go to a serie episode and searched for 1 episode with 1 language manually. When that works, i was able to hit "Search All" and everything worked normally afterwise.

If i did this trick with a movie, i was still stuck with the 6 hour limit reached. If i clicked " Search all " directly after the restart, i was stuck again with the 6 hour limit reached error. So it would go in to a permanent bug which wouldn't allow me to search for any subtitles. Forced me to wait for 6 hours.

But the trick above worked regularly, it was something like forcing the program to change the account from VIP 1 to VIP 2 with searching 1 subtitle individually.
Nothing else did it. But last weeks, also this doesn't help all the time. Sometimes it works, sometimes it doesn't and i don't know what has changed.

When it goes in the stuck mode with 6 hours limit reached, nothing works! Even if i change to my VIP 3/4/5 accounts. Forced to wait that 6 hours till the last seconds.

**To Reproduce**
1. Go to settings
2. Go to provider
3. Change VIP account
4. Go to system
5. Go to provider
6. Click on "reset provider"
7. Click on "refresh"
8. Restart Bazarr
9. Search for subtitles
10. Opensubtitles stucked with 6 hour limit

**Expected behavior**
I wish the reset provider should have worked like it should for Opensubtitles.
When i change my account and hit "reset provider", that should be everything which is needed to make your second account work.
Next to that, i wish to have the 6 hour waiting limit being lowered to 2 hours like before. In case we have this problem again, that we won't need to wait 6 hours but wait 2 hours instead.

**Screenshots**
As desribed.

**Software (please complete the following information):**
 - Bazarr: v0.9.0.5
 - Radarr version 0.2.0.1504
 - Sonarr version 2.0.0.5344
 - OS: Windows 10

**Additional context**
None

**Comment by morpheus65535** [comment]
Can you try to replace step8 bye this:

8 Shutdown Bazarr
9. Rename `config/cache` directory
10. Start Bazarr

Are you able to start downloading right away?

**Comment by FiyiK** [comment]
What do you mean by step 9 ?
Just change the folder name for both paths? 

That way i'd lose all my settings i guess, right?

I found out that my trick works only when Bazarr isn't searching for subtitles.
Example: When bazarr searches subtitles and finishes,  and i got the "download limit reached" error, i can change my VIP account and follow the steps i explained before to make it work with my VIP 2 account.
Example 2: When bazarr searches for subtitles but is NOT finished yet and i get the error while bazarr is still searching. In that time if i change my account to VIP 2, it will get stuck for 6 hours with the error.

**Comment by cphmichael** [comment]
I think morpheus suspects there are something in your cache folder (like when you clear your cache in a browser), so he would like you to rename your cache folder.
I guess Bazarr will create a new clean cache folder when you start it again.

**Comment by FiyiK** [comment]
I just deleted the cache folder, didn't know how to start up bazarr so i restarted my laptop. 
And it WORKED!

**Comment by morpheus65535** [comment]
Cache cleanup should happen automatically when changing username. You can test dev branch please?

**Comment by FiyiK** [comment]
How can i test that? What is dev branch?

**Comment by morpheus65535** [comment]
If you installed using Windows installer, you can't. You need to be running using sources installation and make the switch in Settings-->General

**Comment by morpheus65535** [comment]
I consider this one as fixed. Re-open this issue if required when you'll be able to test.
