### ISSUE TITLE
Bazarr display a subtitle as "en.HI" - Provider display the subtitle as "en"

### ISSUE THREAD

**Issue by cphmichael** [morpheus65535/bazarr#1147]
Bazarr Version: 0.9.0.5
Sonarr Version: 3.0.4.975
Radarr Version: 3.0.0.3918
Operating System: Linux-4.19.107-Unraid-x86_64-with
Python Version: 3.8.5
- - - -
I have manually downloaded a subtitle from supersubtitles that is displayed as "en" but when downloaded, Bazarr display it as "en.HI".

**This is the downloaded subtitle** (there is a "Warning - Potentially offensive content ahead!") click "Ok, show me the paste"
https://pastebin.com/5HQcDHRy

LOG-file:
[sonarr.txt](https://github.com/morpheus65535/bazarr/files/5364063/sonarr.txt)

- - - - 
![Bazarr - lovecraft country](https://user-images.githubusercontent.com/45288008/95725543-1736ac80-0c78-11eb-950b-dc29c3894507.png)
- - - - 
![Manually search](https://user-images.githubusercontent.com/45288008/95725618-2e759a00-0c78-11eb-8bec-1fbcb824c622.png)
- - - - 
![History](https://user-images.githubusercontent.com/45288008/95725686-45b48780-0c78-11eb-8304-e4ffc8b355e4.png)
- - - -

**Comment by morpheus65535** [comment]
This isn't an issue with Bazarr. Provider report the subtitles as `en` but it contain 54 line of music lyrics which should be considered as hearing-impaired(HI). Once downloaded, Bazarr analyze the file for indexing purpose and tag it as `en:hi` as it should have been in the first place.
