### ISSUE TITLE
Questions about bazarr stop running after closing "CMD", and bazarr cannot automatically run in the background

### ISSUE THREAD

**Issue by hoong7** [morpheus65535/bazarr#1150]
**Describe the bug**

I have reported this problem in discord before and many times, but it has not been solved
The specific phenomenon is this. After running bazarr, I cannot close "Git CMD" because once I close the window, my bazarr service will immediately stop running.
Before this time, according to the instructions of my friends in discord and the wiki, I have tried to reinstall python after adjusting the default installation path. I have tried to operate each of the "Autostart on Linux-Windows-MacOS-FreeBSD" tutorials in the wiki. One step operation, but so far, it still does not work, hope to get help

**To Reproduce**

The specific phenomenon is like this. According to the tutorial "Installation", run it from source, after running bazarr (python bazarr.py), I cannot close "Git CMD" because once I close the window, my bazarr The service will immediately stop running.

**Expected behavior**

I hope that bazarr can be started automatically and run in the background normally, instead of having to perform steps 6, 7, and 8 of the windows operation in the tutorial "Installation" every time. And don’t always have a "git cmd" window in the taskbar
I don’t know if there is something wrong with my current operation, or there may be a bug that I don’t know about. Please let me understand and solve the problem correctly.
thank

**Screenshots**

![image](https://user-images.githubusercontent.com/71035460/96127993-54749600-0f27-11eb-9e5f-66eaa37b9935.png)
![image](https://user-images.githubusercontent.com/71035460/96128014-5b030d80-0f27-11eb-9f80-038264f00e66.png)
![image](https://user-images.githubusercontent.com/71035460/96128020-5e969480-0f27-11eb-86b1-ced7ed724e37.png)

The first screenshot is a screenshot taken early this morning, I don’t remember when I closed the "git cmd" window
The last one is a screenshot of the log after I actively closed the "git cmd" window at 20:37 (after closing, the log file did not generate any logs)
And the error that the browser actively prompts

**Software (please complete the following information):**
 - Bazarr: [e.g.v 0.9.0.5] 
 - Radarr version [e.g. v 0.2.0.1504]
 - Sonarr version [e.g. v 3.0.4.982]
 - OS: [e.g. Windows 10 2004 19041.572]

**Comment by morpheus65535** [comment]
This is the expected result: if you close a program, you can't expect it to be still running. Have you tried running it as a servcie instead of starting it by hand using a command prompt?

**Comment by hoong7** [comment]
> This is the expected result: if you close a program, you can't expect it to be still running. Have you tried running it as a servcie instead of starting it by hand using a command prompt?

In fact, I don’t understand these very well, I just think the function of bazarr is really good, if possible, can you tell me how to start it as a service?

**Comment by morpheus65535** [comment]
The good news is that it is already documented on the wiki: https://github.com/morpheus65535/bazarr/wiki/Autostart-on-Linux-Windows-MacOS-FreeBSD#windows

**Comment by hoong7** [comment]
> The good news is that it is already documented on the wiki: https://github.com/morpheus65535/bazarr/wiki/Autostart-on-Linux-Windows-MacOS-FreeBSD#windows

I don’t know if the author did not read my question carefully. When asking a question, I said that I have tried the method given in your link above many times, and I should have told you in discord yesterday. Yes, I also reinstalled python, do you remember
![image](https://user-images.githubusercontent.com/71035460/96165169-da580780-0f4e-11eb-8c78-997fd1193c36.png)

**Comment by morpheus65535** [comment]
If you want help, you should step to Discord for live support. The wiki is accurate and it works. So I don't see an issue here.
