### ISSUE TITLE
Wizdom show empty names

### ISSUE THREAD

**Issue by Churator** [morpheus65535/bazarr#1152]
Wizdom provider show subtitles, but empty name so I can't decide between releases.

![image](https://user-images.githubusercontent.com/62523824/96174056-6d824480-0f31-11eb-8c81-d4bf869cd6fd.png)

**Comment by morpheus65535** [comment]
I've tested with both series and movies and I get releases without any issue. Could be related to this specific subtitles.

**Comment by Churator** [comment]
@morpheus65535  nope, everywhere. I can only see N/A.
I'm using the docker version from Linuxserver. can it be related ?

**Comment by morpheus65535** [comment]
What version of Bazarr?

**Comment by Churator** [comment]
v0.9.0.5

**Comment by morpheus65535** [comment]
I would be surprised as this is fixed in v0.9.0.5 and is working perfectly fine: https://github.com/morpheus65535/bazarr/commit/be37a8112ee6f5d60888dfc94d859a45256a1cec

**Comment by Churator** [comment]
I've removed all images and retrieved new one, seems like the updated version now works ok.
Thanks!
