### ISSUE TITLE
Subtitle Sync failing

### ISSUE THREAD

**Issue by jenssels** [morpheus65535/bazarr#1153]
Lately it seems like I have a lot of subtitle syncs that fail but I have no idea why.

Currently setup on a overclocked raspberry pi 4 8GB model.

Status:
![image](https://user-images.githubusercontent.com/36538788/96222253-35f4b600-0f8c-11eb-8336-5175b9f933f6.png)

Left debug running over night to provide some extra information:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5389684/bazarr.log)

**Comment by morpheus65535** [comment]
Make sure you have latest requirements installed. I would guess that you don't have `webrtcvad-wheels` installed.

**Comment by jenssels** [comment]
So I did miss that dependency dependency (not sure how I missed it). Left it running for a few more days but I still get a lot of failed syncs.

[bazarr.log](https://github.com/morpheus65535/bazarr/files/5406408/bazarr.log)

**Comment by morpheus65535** [comment]
Does this file exist?

`/mnt/selsmedia/Series/Library/Supernatural/Season 5/Supernatural - S05E19 - Hammer of the Gods Bluray-1080p.nl.synced.srt`

**Comment by jenssels** [comment]
Nope doesn't exist

![image](https://user-images.githubusercontent.com/36538788/96576368-60b77500-12d2-11eb-88e4-72de6eb03406.png)

**Comment by morpheus65535** [comment]
It means that ffsubsync is unable to create the synced subtitles. If you can confirm it's not a permission issue, I suggest you enable `Subtitles synchronization debugging` under Settings-->Subtitles and try to reproduce it. Then, you'll be able to open an issue on their Github. There's nothing much I can do on my side. Good luck!
