### ISSUE TITLE
BAZARR unable to index external subtitles.

### ISSUE THREAD

**Issue by lukjod** [morpheus65535/bazarr#1156]
I had 2 times such error as on title.
Newest development version from linuxserver.io Docker build on watchtower.
log:
`Traceback (most recent call last):
 File "/app/bazarr/bazarr/list_subtitles.py", line 157, in store_subtitles_movie
  subtitles = guess_external_subtitles(full_dest_folder_path, subtitles)
 File "/app/bazarr/bazarr/list_subtitles.py", line 461, in guess_external_subtitles
  if not subtitles[subtitle].hi:
AttributeError: \NoneType\ object has no attribute \hi\`

**Comment by halali** [comment]
Can you provide some example ? se i can try to reproduce this ?

**Comment by lukjod** [comment]
so far log is clean, so dont have the possibility to reproduce it. Will turn back to it if smthg happen again
thx

**Comment by morpheus65535** [comment]
I'll close this one. Just re-open it if required.
