### ISSUE TITLE
[BUG] "Timezone offset does not match system offset: {0} != {1}." if automatic daylight saving time is disabled from windows settings.

### ISSUE THREAD

**Issue by zFerry98** [morpheus65535/bazarr#1157]
**Describe the bug**
If automatic daylight saving time is disabled from windows settings, this error appears. The problem is that by enabling automatic daylight saving time, windows adds 1 more WRONG hour. I can't keep a wrong clock on windows server. Europe / Rome (time: 14:12; with the option enabled: 15:12 BAD TIME).

**To Reproduce**
1 leave automatic daylight saving time disabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/17975351/96367157-494e7f80-114c-11eb-94b1-1deddcd6ac87.png)

**Software (please complete the following information):**
 - Bazarr: All version [0.9.0.5]
 - OS: Windows Server 2019 x64 Datacenter

**Comment by morpheus65535** [comment]
Can you try a "dirty" fix?

1. Stop Bazarr
2. Replace the content of this directory: `bazarr/libs/pytz`
3. with the file available there: https://github.com/morpheus65535/bazarr/tree/master/libs/pytz
4. Start Bazarr and test if it fix your issue.

This is an updated version of the timezone definitions.

**Comment by zFerry98** [comment]
![image](https://user-images.githubusercontent.com/17975351/96622163-e276c500-1309-11eb-8b41-2cc32c6f7e8f.png)
No. Same problem also copying the entire contents of pytz.
I downloaded the entire master. Deleted pytz in libs (where bazarr is installed) and copied the new pytz. Process started. Same mistake.

**Comment by morpheus65535** [comment]
Seems like a bug with tzlocal then. I suggest you open an issue on https://github.com/regebro/tzlocal/ and refer to this issue so I can follow it.

**Comment by zFerry98** [comment]
https://github.com/regebro/tzlocal/issues/79 
It appears that it is already present and not resolved.

**Comment by morpheus65535** [comment]
There's nothing I can do on my side. Tzlocal is required by the scheduler used in Bazarr.

I'll close this one as it is out of my control.
