### ISSUE TITLE
Custom postprocessing command issue.

### ISSUE THREAD

**Issue by azza10** [morpheus65535/bazarr#1158]
In the dialog used to enter custom post processing, trailing quotations marks are being deleted.

For example, after saving settings, this:

`C:\subsync.bat "{{subtitles}}" "{{episode}}"
`

Turns into this:

`C:\subsync.bat "{{subtitles}}" "{{episode}}`

And my script fails to run properly.

A workaround I found was to leave a trailing space. This seems to work until another update is released and it deletes the trailing quote again.

**Comment by morpheus65535** [comment]
Duplicate #309
