### ISSUE TITLE
Blank TV series pages

### ISSUE THREAD

**Issue by dak180** [morpheus65535/bazarr#1161]
**Describe the bug**
When I try to view any tv show on my computer I see:
![2020-10-19](https://user-images.githubusercontent.com/324812/96517428-e2f25b80-1236-11eb-82db-cbc6f48c800e.png)

**To Reproduce**
1. Go to series
2. Click on any series page
3. See error

**Software (please complete the following information):**
 - Bazarr: 0.9.0.5
 - Radarr version 0.2.0.1504
 - Sonarr version 3.0.3.928
 - OS: FreeBSD-12.2-PRERELEASE-amd64-64bit-ELF

**Comment by morpheus65535** [comment]
Did you reconfigure Sonarr after syncing the previous installation with Bazarr? You can't do that. You need to start Bazarr DB from scratch.

**Comment by dak180** [comment]
The really interesting thing is that the page works on an iphone (though some of the buttons render in places where you cannot interact with them which makes it less useful) and no, sonarr has not been reconfigured at all.

**Comment by dak180** [comment]
@morpheus65535 if there is any specific information that would be useful, let me know.

**Comment by morpheus65535** [comment]
If it's working from another browser, it's definitely related to your browser. Which one are you using? Did you tried incognito/privte browsing?

**Comment by dak180** [comment]
@morpheus65535 except it does the same thing on both chrome and safari and a different computer too.

**Comment by morpheus65535** [comment]
Is there something in Chrome debug console? Any error that could help us?

**Comment by dak180** [comment]
@morpheus65535 `113:1772 Uncaught SyntaxError: Unexpected token ?` is what comes up on the chrome console.

**Comment by morpheus65535** [comment]
Please provide your config.ini and bazarr.db files so I can try to reproduce. You can send them in private on Discord.

**Comment by dak180** [comment]
@morpheus65535 files hav been PMed to you on Discord.

**Comment by morpheus65535** [comment]
You're facing a browser issue or you have some security software blocking. I can load your bazarr.db/config.ini without any issue on my laptop using Python 3.8.6 and Chrome 86.0.x:

![image](https://user-images.githubusercontent.com/5130500/97064901-9fba2480-1577-11eb-9a44-242b0dbad1a7.png)

**Comment by dak180** [comment]
@morpheus65535 since it happens across browsers something being blocked seems more likely; it is however something relatively recent because I know it was working not that long ago (maybe 1-2 months or less). Purely local lan resources should not be getting blocked with my setup, so any suggestions on where I should be looking based on observed behavior?

**Comment by morpheus65535** [comment]
Is Bazarr behind a reverse proxy? If it is, can you access it directly?

**Comment by dak180** [comment]
@morpheus65535 it is not behind any kind of proxy; I always access it directly.

**Comment by morpheus65535** [comment]
No idea then... your db and config are fine so I would try to save them and git clone again. Maybe something related to your jail... I don't use FreeNAS so it's kind of hard to guess. 

If you want, you can come by Discord support channel and see if other users have hints for you.

**Comment by lyz-code** [comment]
Upgrading Firefox solved the issue for me

**Comment by jtambasco** [comment]
I've got this weird issue too...  Series info doesn't show on either chrome, chromium or edge on my computer; however, it shows on Firefox on my computer, and it works on chrome on my phone...  I've rebuilt the DB, reinstalled it a few times, but that didn't help.  I'm running Manjaro.

Movie info displays fine on all browsers.

**Comment by morpheus65535** [comment]
@jtambasco this is browser related issue on your client. Probably some security parameters. Bazarr is tested and work fine on Chrome, Firefox and Edge. I suggest you look at your browser dev console and try incognito mode.
