### ISSUE TITLE
Video files not parsed on FreeBSD

### ISSUE THREAD

**Issue by hros** [morpheus65535/bazarr#1162]
configutation: Bazarr version v0.9.0.5 running in FreeBSD version 11.3-RELEASE-p14

subtitles are not being downloaded
the log output (I changed the name of the file to `aaa`):
```
BAZARR Error trying to get video information for this file: /mnt/series/aaa.mkv	
BAZARR is started and waiting for request on http://0.***.***.***:6767/
```
from the source code I see that this error message is thrown in bazarr/get_subtitles.py:get_video() which calls libs/subzero/video.py:parse_video().
However, parse_video() starts with
```python
logger.debug("Parsing video: %s, hints: %s", os.path.basename(fn), hints)
```
However, this debug log message is not being displayed in my log.
Could it be some sort of python configuration issue meanig that subzero.video:parse_video is not found?

**Comment by morpheus65535** [comment]
Provide complete debug log, not only was suits you. Do not alter the log.

**Comment by hros** [comment]
That is the full log (including debugging log messages) from log screen after restarting Bazarr and pressing on search for one of the files with missing subtitles.
The only change I made was to alter the name of the downloaded mkv video file for the same reason people use a vpn when downloading files.
I'd appreciate your help and would gladly supply any additional debug information

**Comment by morpheus65535** [comment]
Please provide the bazarr.log file that can be downloaded from the UI or can be found in `config/log`directory.

**Comment by hros** [comment]
thanks for the pointer to the full log file
looking at the log it became clear that the `ffprobe` tool is missing
apparently several freebsd `pkg`s were lost after an o/s upgrade. reinstalling `ffmpeg` seems to have fixed the issue

**Comment by morpheus65535** [comment]
I'm happy to see that you've fixed your issue. Thanks for sharing with others the root cause!
