### ISSUE TITLE
TypeError: NoneType object is not iterable when attempting to update list

### ISSUE THREAD

**Issue by gregoryduckworth** [morpheus65535/bazarr#1163]
**Describe the bug**
When attempting to download subtitles I get the following error logs (this occurs on both Sonarr and Radarr):

```
Job "Update all Episode Subtitles from disk (trigger: cron[hour='4'], next run at: 2020-10-22 04:00:00 UTC)" raised an exception
```

```
Traceback (most recent call last):
 File "/opt/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/opt/bazarr/bazarr/get_episodes.py", line 14, in update_all_episodes
  series_full_scan_subtitles()
 File "/opt/bazarr/bazarr/list_subtitles.py", line 354, in series_full_scan_subtitles
  store_subtitles(episode[\path\], path_mappings.path_replace(episode[\path\]))
 File "/opt/bazarr/bazarr/list_subtitles.py", line 102, in store_subtitles
  list_missing_subtitles(epno=episode[\sonarrEpisodeId\])
 File "/opt/bazarr/bazarr/list_subtitles.py", line 238, in list_missing_subtitles
  for i, desired_subtitle in desired_subtitles_enum:
TypeError: \NoneType\ object is not iterable
```

**To Reproduce**
This happens on a fresh install of bazarr.

**Expected behavior**
Subtitles should download

**Software (please complete the following information):**
 - Bazarr: v0.9.0.5
 - Radarr version 3.0.0.3966
 - Sonarr version 3.0.4.982
 - OS: Ubuntu 20.04

**Comment by morpheus65535** [comment]
You have something wrong with your database. Please send me your bazarr.db file on Discord in PM.

**Comment by morpheus65535** [comment]
Ok looks like there something wrong in this part of code but I'm completely refactoring this in v0.9.1. I don't think it worth to fix it and maybe cause other issues.

**Comment by gregoryduckworth** [comment]
Thanks, will wait for that update and keep you posted.

**Comment by morpheus65535** [comment]
I'll close this issue, reopen it if the bug persist in upcoming v0.9.1.
