### ISSUE TITLE
TV series blacklist 

### ISSUE THREAD

**Issue by dralkaar** [morpheus65535/bazarr#1165]
I'm blacklisting some subtitles that are not correct (bad translation, bad timing) but they are getting redownloaded.

![Capture](https://user-images.githubusercontent.com/73301030/96893411-f72e9680-148a-11eb-8c60-3634ff724e99.PNG)

Attached a screenshot of the blacklist.

The log:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5424177/bazarr.log)

The DB:
[bazarr.zip](https://github.com/morpheus65535/bazarr/files/5447857/bazarr.zip)

**Comment by morpheus65535** [comment]
Fill the whole issue template and provide debug log and bazarr.db so we can investigate.

**Comment by morpheus65535** [comment]
No news, good news.

**Comment by halali** [comment]
Please provide debug log https://github.com/morpheus65535/bazarr/wiki/FAQ#how-do-i-enable-the-debug-log

**Comment by dralkaar** [comment]
Here's the log with debug enabled (i cleared the log, blacklisted the subtitles and waited to be redownloaded).
At this point these 2 are getting redownloaded:

NOS4A2 | 2x9 | Welcome to Christmasland | 5 hours ago | Romanian subtitles downloaded from bsplayer with a score of 100.0%.
NOS4A2 | 2x7 | Cripple Creek | 5 hours ago | Romanian subtitles downloaded from bsplayer with a score of 100.0%.


[bazarr.log](https://github.com/morpheus65535/bazarr/files/5459814/bazarr.log)

**Comment by morpheus65535** [comment]
Could be related to bsplayer provider implementation of `id`. We're going to require to see your bazarr.db file to analyze the content of the blacklist tables.

**Comment by dralkaar** [comment]
Attached the DB freshly downloaded from the host.
[bazarr.zip](https://github.com/morpheus65535/bazarr/files/5460553/bazarr.zip)

**Comment by morpheus65535** [comment]
We are using subtitles file download url as unique id with bsplayer. Blacklist keep track of the the subtitles using this unique id. The problem is that bsplayer generate download url dynamically and return an http 500 if we try to reuse the url. We are going to change the unique id for bsplayer to something unique and invariable.

As I'm not the one who developed this provider, I have no idea what could be used...

**Comment by morpheus65535** [comment]
@GermanG can you take a look?

**Comment by GermanG** [comment]
I made a tentative fix (untested) in #1188

**Comment by morpheus65535** [comment]
@GermanG and subid is unique?

**Comment by dralkaar** [comment]
@GermanG i will do it later on today

**Comment by GermanG** [comment]
> @GermanG and subid is unique?

Seems to be, tested with my old python script for bsplayer.

**Comment by morpheus65535** [comment]
> Seems to be, tested with my old python script for bsplayer.

Good, I'll wait for @dralkaar test and merge your PR if everything is working fine. Thanks!

**Comment by dralkaar** [comment]
Seems to work fine now. I blacklisted again the faulty subtitles and they're not being downloaded.

**Comment by morpheus65535** [comment]
Good news! Thanks for the feedback!
