### ISSUE TITLE
Can i sync subtitle with referenced srt?

### ISSUE THREAD

**Issue by Dr0bac** [morpheus65535/bazarr#1167]
I,m running bazarr on raspberry pi 3 with limited memory etc.. and ffsubsync in bazarr use audio extraction from video file which is resource intensive task. Bazarr will sometimes crash trough this process. Is there a way to only sync my language.srt with reference.srt file with best score?

**Comment by morpheus65535** [comment]
Not with embedded sync feature. You need to rely on custom post-processing.

**Comment by Dr0bac** [comment]
Sorry, didn't played with that option yet.. how would i do that with post processing? I need to tell bazarr to download english subtitles beside my language subtitles and then ... ?

**Comment by morpheus65535** [comment]
TBH, I don't have any idea... maybe have a script that check if another subs exist and use it to call ffsubsync or subsync.

**Comment by Dr0bac** [comment]
When i click on "Collection of Custom Post-Processing Scripts" in bazarr wiki i get 404.. is there are some simple examples of post processing scripts used in bazarr?

**Comment by TRaSH-** [comment]
Sorry it broke after I changed my Guides collection,
but what you're after no one provided to me yet.

**Comment by Dr0bac** [comment]
I just want an example how to pass bazarr variable to python script..

**Comment by PeeVv** [comment]
Would it be possible to change it so you can select the standard source for the sync? I have a movie with embedded subtitles which are not in sync, and every subtitle gets synced with this embedded subtitle so they are also not in sync. Using ffsubsync with `_--reference-stream 0:a:0_` so it syncs with the first audio stream gives me a properly synced subtitle. 

So, in short, can there be a way to set the _--reference-stream_ flag from the ui?

**Comment by morpheus65535** [comment]
You can make a feature request for this.
