### ISSUE TITLE
forced subtitles being incorrectly categorized as HI

### ISSUE THREAD

**Issue by kitch-jared** [morpheus65535/bazarr#1169]
I have a couple of movies that are not recognizing the forced subtitles. I often have to manually find forced subtitles and add them and then have it scan the folder, and it comes up fine. However, these movies are recognizing them as HI.

Bazarr Screenshot - https://ibb.co/fppqchP
Filenames - https://ibb.co/DD5JMqF

**Comment by morpheus65535** [comment]
Should be fixed in dev branch now. Can you test it?

**Comment by kitch-jared** [comment]
I apologize, but I'm not sure how to convert over to the dev branch. I am
on Windows. I made a copy of my install folder and tried just overwriting
everything with the dev branch downloaded files, but it would not start
back up. I had to switch back to my backed up folder.

**Comment by morpheus65535** [comment]
If you've installed using the Windows Installer, there's no way to run the dev branch. You must install Bazarr from sources as it use Github to update.

**Comment by kitch-jared** [comment]
OK. I'll uninstall and do it from source.

**Comment by kitch-jared** [comment]
Probably won't have time to get to this until early next week though. I
appreciate you looking at it, and I'm sorry I can't help quicker.

**Comment by morpheus65535** [comment]
I've tested it and it seems fixed. I'll close this issue but re-open it if you are still facing the issue after switching to dev branch.

**Comment by kitch-jared** [comment]
thanks. I'll let you know if there is still an issue.
