### ISSUE TITLE
Movies not being listed: path mappings for external hard drive

### ISSUE THREAD

**Issue by dboekhout** [morpheus65535/bazarr#117]
### What is the problem?
Movies are not being listed in the "Movies" tab.

### What is my setup?
I'm using radarr housed in a docker container which manages my movies on an external hard drive (say /run/media/username/ext_drive/radarr). For radarr this external drive is mounted at /movies in the container.

The same goes for bazarr. I mounted my external drive on the same location: /movies in the docker container. When I open a shell I can indeed see my movies on the external drive in /movies. But for some reason they are not showing up in the WebGUI

### My question
What should I put in the "Path for radarr" and "Path for bazarr" fields?

### What I have tried so far
**Path for Radarr:Path for Bazarr**
/movies:/movies
/run/media/username/ext_drive/radarr/movies:/movies
/run/media/username/ext_drive/radarr/movies:/run/media/username/ext_drive/radarr/movies
/movies:/run/media/username/ext_drive/radarr/movies
empty:empty

Restarting bazarr on each try.

**Comment by morpheus65535** [comment]
If your path are the same for radarr and bazarr (/movies), you don’t need to use path mapping at all. 

Your problem is more at the radarr settings level. Bazarr do not discover movies from disk, it get his information from the radarr API.

Can you show me a screenshot of your radarr settings in bazarr. Take care to remove tou API key.

**Comment by dboekhout** [comment]
Thanks for the quick response!
That could explain a thing or two. Settings attached.
![radarr_settings](https://user-images.githubusercontent.com/26926485/43663663-a836ed1a-976a-11e8-96bd-baa3d93c17a0.png)

**Comment by morpheus65535** [comment]
You can't use 0.0.0.0 to reach Radarr. 0.0.0.0 is only for the binding address of Bazarr.

You need to use the same IP you use to access it directly from your browser.

**Comment by dboekhout** [comment]
Changed it to the Radarr IP but it's not working, still nothing showing up.  Are you sure that IP is reachable for the bazarr container to the radarr container?

**Comment by morpheus65535** [comment]
What network mode are you using for your container?

**Comment by morpheus65535** [comment]
I use bridged mode for most of my container and I can reach each other using the docker host IP address and published port without any problem.

**Comment by dboekhout** [comment]
I'll double check tonight if I have a bridge configured and can ping each of the containers. Will report back to you

**Comment by morpheus65535** [comment]
Thanks!

**Comment by dboekhout** [comment]
Sorted this out with you on discord. For other people:
I fixed it by entering the docker bridged IP address and not the actual LAN adress of my host machine. 
(So: 172.17.0.3 instead of e.g. 192.168.1.140)
