### ISSUE TITLE
Getting 500 when trying to access Bazarr

### ISSUE THREAD

**Issue by Nightliss** [morpheus65535/bazarr#1172]
**Describe the bug**
So suddenly I got error refused to connect when trying to access bazaar. Sonarr/Radarr are working fine. Then installed over latest version, now getting internal server error. Tried to restart service but no dice. 

Here's the log
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5439187/bazarr.log)

Also stopped the service and deleted db file. Didn't help.

**To Reproduce**
-

**Expected behavior**
-

**Screenshots**
![image](https://user-images.githubusercontent.com/30467858/97180919-fb182c80-179a-11eb-9978-8d04c573a0c7.png)

**Software (please complete the following information):**
 - Bazarr: 0.9.0.5
 - Radarr version 0.2.0.1504
 - Sonarr version 2.0.0.5344
 - OS: Win10 Pro build 2004

**Additional context**

**Comment by morpheus65535** [comment]
Corrupted update. Uninstall Bazarr, make sure C:\Bazarr directory have been deleted. Then, install again. Wait for an hour before trying to access Bazarr to make sure it get updated properly.

**Comment by Nightliss** [comment]
Works now, thanks :)
