### ISSUE TITLE
Provider assrt occasionally fails because of: GuessitException.

### ISSUE THREAD

**Issue by kSotin** [morpheus65535/bazarr#1175]
**Describe the bug**
Provider assrt occasionally fails, reporting an error message like below. 

**Message**

> Throttling assrt for 10 minutes, until 20/10/31 10:30, because of: GuessitException. Exception info: 'An internal error has occured in guessit.\n===================== Guessit Exception Report =====================\nversion=3.1.1\nstring=Civilisations.2018.S01E04.The.Eye.of.Faith.720p.iP.WEB-DL.AAC2.0.H.264-NeuCIV.简体&英文.ass\noptions={\'expected_title\': [\'OSS 117\', \'This is Us\'], \'allowed_countries\': [\'au\', \'gb\', \'us\', None], \'allowed_languages\': [\'ca\', \'cs\', \'de\', \'en\', \'es\', \'fr\', \'he\', \'hi\', \'hu\', \'it\', \'ja\', \'ko\', \'mul\', \'nl\', \'no\', \'pl\', \'pt\', \'ro\', \'ru\', \'sv\', \'te\', \'uk\', \'und\', \'zho\', \'eng\'], \'advanced_config\': {\'common_words\': [\'ca\', \'cat\', \'de\', \'he\', \'it\', \'no\', \'por\', \'rum\', \'se\', \'st\', \'sub\'], \'groups\': {\'starting\': \'([{\', \'ending\': \')]}\'}, \'audio_codec\': {\'audio_channels\': {\'1.0\': [\'1ch\', \'mono\'], \'2.0\': [\'2ch\', \'stereo\', \'re:(2[\\\\W_]0(?:ch)?)(?=[^\\\\d]

**Exception**

> $)\], \5.1\: [\5ch\, \6ch\, \re:(5[\\\\W_][01](?:ch)?)(?=[^\\\\d]

**Software (please complete the following information):**
 - Bazarr: 0.9.0.5
 - OS: Ubuntu 20.04

**Comment by morpheus65535** [comment]
Could already be fixed in v0.9.0.6 (dev branch). Can you test it?

**Comment by kSotin** [comment]
Sorry for the delay. I've tested in dev branch and there's no more errors of this kind. Really appreciate your work!
