### ISSUE TITLE
Bazarr doesn't find non English subs on OpenSubtitles 

### ISSUE THREAD

**Issue by TRaSH-** [morpheus65535/bazarr#1176]
**Describe the bug**
Seems Bazarr doesn't find non English subs anymore on opensubtitles.
Did several test to see if it's only 1 certain show etc but it seems to happen to more shows.
I've tested it with Bazarr dev and latest/stable version

**To Reproduce**
1. Enable opensubtitles provider
2. Make sure its status is Good
3. Do a manual search on any common show.(enable in this case dutch subtitles)
4. See opensubtitles missing in the results

**Expected behavior**
It should show up in the manual search if the subs exist on the site and the same show was matched fine by bazarr to opensubtitles before.

**Screenshots**
Bazarr Search:
![image](https://user-images.githubusercontent.com/6155095/97775753-7561fb80-1b63-11eb-8298-54f44998ad55.png)

OpenSubtitles Results:
https://www.opensubtitles.org/en/search/sublanguageid-dut,eng/imdbid-11664252
![image](https://user-images.githubusercontent.com/6155095/97775693-169c8200-1b63-11eb-8540-37ed6100ba46.png)

Debug log: https://pastebin.com/spD8KBfw

---

Bazarr Search:
![image](https://user-images.githubusercontent.com/6155095/97775833-0933c780-1b64-11eb-890a-8e8e7e5d584c.png)

OpenSubtitles Results:
https://www.opensubtitles.org/en/search/sublanguageid-dut,eng/imdbid-10151040
![image](https://user-images.githubusercontent.com/6155095/97775844-249ed280-1b64-11eb-9569-d8834decddeb.png)

Debug log: https://pastebin.com/GzLS4pe4

**Software (please complete the following information):**
 - Bazarr: 0.9.0.6 and 0.9.0.5 (dockers)
 - Radarr version [3.0.0.3977]
 - Sonarr version [3.0.4.991]
 - OS: [Unraid Running Dockers]

**Additional context**
I wonder if this is related to #1168

**Comment by morpheus65535** [comment]
@opensubtitles here's another one for you my friend. There's clearly some trouble with your API. We've tested with some previous versions of Bazarr and the issue is still there.

**Comment by morpheus65535** [comment]
I've just pushed some changes to OpenSubtitles provider in dev branch. Seems to be working for me. Can you test it?
