### ISSUE TITLE
Where is the password Stored?

### ISSUE THREAD

**Issue by ElAdri1999** [morpheus65535/bazarr#1177]
I (stupidly) added a password to my (windows version) Bazarr, and i changed it from  basic to form,  i think somehow changing it(hashing it?) and now i cant access my Bazarr, tried reinstalling, where is the password stored? and what hashing uses?

**Comment by morpheus65535** [comment]
You can take a look at the wiki:
https://github.com/morpheus65535/bazarr/wiki/FAQ#how-do-i-reset-my-password

**Comment by ElAdri1999** [comment]
> You can take a look at the wiki:
> https://github.com/morpheus65535/bazarr/wiki/FAQ#how-do-i-reset-my-password

Thx

**Comment by mohkale** [comment]
This has been moved to here for anyone else stumbling on this issue:

https://wiki.bazarr.media/Troubleshooting/FAQ/#how-do-i-reset-my-password
