### ISSUE TITLE
TypeError: Object of type Country is not JSON serializable when uploading subtitles

### ISSUE THREAD

**Issue by jomp16** [morpheus65535/bazarr#1182]
**Describe the bug**
When trying to upload subtitles with Bazarr, it errs with `TypeError: Object of type Country is not JSON serializable`

**To Reproduce**
1. Add series `Filthy Rich (US)`
2. Click on `Upload`
3. Add attached srt subtitles (rename TXT to SRT) [Filthy.Rich.US.S01E03.720p.WEB.h264-BAE.txt](https://github.com/morpheus65535/bazarr/files/5484500/Filthy.Rich.US.S01E03.720p.WEB.h264-BAE.txt)

**Expected behavior**

It match correctly the subtitles season and episode.

**Screenshots**

![Screenshot_20201103_195130](https://user-images.githubusercontent.com/2255920/98049203-fcd29780-1e0d-11eb-8e77-8337941b1787.png)

![Screenshot_20201103_195157](https://user-images.githubusercontent.com/2255920/98049239-0cea7700-1e0e-11eb-84f6-a371a9428dca.png)

**Software (please complete the following information):**
- Bazarr Version: 0.9.0.6
- Sonarr Version: 3.0.4.993
- Radarr Version: 3.0.0.3978
- Operating System: Linux-5.8.7-arch1-1-x86_64-with
- Python Version: 3.8.5
- Bazarr Directory: /app/bazarr
- Bazarr Config Directory: /config

**Additional context**

Tried using a new, clean container, still show the same error.

Logs:  [bazarr.log](https://github.com/morpheus65535/bazarr/files/5484540/bazarr.log)

**Comment by jomp16** [comment]
And even when I set the season and episode number, the upload button doesn't work at all, see the Javascript error when adding subtitles to upload screen, maybe the javascript error stops the function, which makes the upload button works?

![Screenshot_20201103_200027](https://user-images.githubusercontent.com/2255920/98049847-44a5ee80-1e0f-11eb-835d-7dcd1a9c7c85.png)

**Comment by morpheus65535** [comment]
@LASER-Yi can you take a look at this one please?

**Comment by LASER-Yi** [comment]
> @LASER-Yi can you take a look at this one please?

OK I‘ll check

**Comment by morpheus65535** [comment]
Thanks to @LASER-Yi for fixing this issue! Please test and report result.

**Comment by jomp16** [comment]
Sorry for the delay, I've tested with attached subtitles, it now can find the season and episode number correctly, and the import button works.

Thank you!
