### ISSUE TITLE
Greeksubs.net not showing results / DNS fallback

### ISSUE THREAD

**Issue by pizzabe** [morpheus65535/bazarr#1187]
**Describe the bug**
Tried using the new provider Greeksubs.net with bazarr dev 0.9.0.6 but it either does not show me any results (even if they exist) or there's an http error.  Also in this particular example I noticed that instead for looking for tt11150494 it looked for tt8111088 which is the whole tv series . Dont know though how this works

https://imgur.com/a/cVYyixC

Here's the debug log https://pastebin.com/a6GwSQsG

**Software (please complete the following information):**

**Bazarr Version:** 0.9.0.6
**Sonarr Version:** 3.0.4.993
**Radarr Version:** 0.2.0.1504
**Operating System:** Linux-5.4.0-52-generic-x86_64-with
**Python Version:** 3.8.5
Docker hotio image.

My server is with Hetzner

Keep up the great work devs. thanks, Pizza

**Comment by pizzabe** [comment]
also I ve been getting this, cause it cant find any subs apparently for this movie. 
```Throttling greeksubs for 10 minutes, until 20/11/04 18:26, because of: HTTPError. Exception info: '404 Client Error: Not Found for url: https://greeksubs.net/en/view/tt0117091'```

which is weird cause no other provider does that if it can't find something

**Comment by morpheus65535** [comment]
`03/11/2020 18:24:58|INFO    |root                            |Throttling greeksubs for 10 minutes, until 20/11/03 18:34, because of: HTTPError. Exception info: '403 Client Error: Forbidden for url: https://greeksubs.net/en/view/tt8111088'|`

I don't know why you get a 403. It's working fine for me.

As for the 404, it's because this imdb id isn't available on their site. I could catch this and return no result instead.

**Comment by pizzabe** [comment]
Same thing happens with other titles. I was able to download Person of Interest Just fine. Which is a show that has finished. But for shows that still have episodes coming out , it does not work properly. Try the Undoing for instance . 2020. Despite being there it shows no results. bazarr looks for the subs using this link https://greeksubs.net/en/view/tt0117091 . This is the correct imdb id but it should have searched the subs like this instead https://greeksubs.net/en/view/tt8134470/subtitle-for-the-undoing%CE%AD%CF%89%CF%82-s01e02. The bazzar page, does NOT lead anywhere, however second does. As this is an ongoing show the link leading to the subs, will be changing every time a new episode comes outs.  I think that's the problem.

**Comment by morpheus65535** [comment]
Bazarr is searching subs using `https://greeksubs.net/en/view/tt8134470/` + imdb_id. This work perfectly fine and you can try it: `https://greeksubs.net/en/view/tt8134470`.

**Comment by morpheus65535** [comment]
Can you test if this fixes your issue?

**Comment by pizzabe** [comment]
you beautiful beautiful man. Works like a charm now ! For anyone looking at this post, the problem was the encoding on the website's urls. Bazarr initial encoding (latin-1), could not ''read'' some greek characters, which might have existed on the urls.
