### ISSUE TITLE
PT-BR Subtitles for Fargo TV show are not found by Bazarr

### ISSUE THREAD

**Issue by maestrozezinho** [morpheus65535/bazarr#1189]
**Describe the bug**
Starting from S04E04, Bazarr does not find any subtitles for Fargo the TV show, either on automatic or manual search.

Enabled providers:
* legendas.tv
* opensubtitles.org
* podnapisi

Log:
[Pastebin](https://pastebin.com/23tEcH6S)

**Software (please complete the following information):**
Bazarr Version: 0.9.0.5
Sonarr Version: 3.0.4.993
Radarr Version: 3.0.0.3987
Operating System: Linux-5.4.0-52-generic-x86_64-with
Python Version: 3.8.5
Bazarr Directory: /app/bazarr
Bazarr Config Directory: /config

**Additional context**
Docker image used: Linuxserver/bazarr

**Comment by morpheus65535** [comment]
OpenSubtitles API had issues with recent episode. I've made a fix yesterday in v0.9.0.6 that should be released to master in the upcoming days.

I can't tell for the others but maybe you can test with v0.9.0.4 to see if it works.

**Comment by maestrozezinho** [comment]
Only with v0.9.0.6 [(Log)](https://pastebin.com/qHZAmi9k) I was able to find subtitles, but only with opensubtitles.

Legendas.tv returns nothing for the versions I tested:
0.9.0.3 - [Log](https://pastebin.com/j3ETDHN5)
0.9.0.4 - [Log](https://pastebin.com/qHZAmi9k)
0.9.0.5 - [Log](https://pastebin.com/23tEcH6S)
0.9.0.6 - [Log](https://pastebin.com/qHZAmi9k)

From the logs it seems that legendas.tv returns results for the Fargo movie, maybe due to the lack of the TV Show's year (removed due to Raised by Wolves, if I recall correctly).

**Comment by morpheus65535** [comment]
Just tested with the exact same episode as you used (Fargo S04E04) and it works perfectly fine for me:

![image](https://user-images.githubusercontent.com/5130500/98617196-7cf47380-22cc-11eb-9aa0-22567c27492e.png)

**Comment by maestrozezinho** [comment]
I've tested today with a new container just with legendas.tv and the basic options and still got nothing.

[Log](https://pastebin.com/5bEAitiD)

From the logs, Bazarr is searching only for the Fargo movie.

Bazarr Version:
0.9.0.6
Sonarr Version:
3.0.4.993
Radarr Version:
Operating System:
Linux-5.4.0-52-generic-x86_64-with
Python Version:
3.8.5
Bazarr Directory:
/app
Bazarr Config Directory:
/config/app

**Comment by morpheus65535** [comment]
I don't ever see the search starting in your log. Make sure no other tasks are running, clear your log and reproduce the issue.

**Comment by maestrozezinho** [comment]
[Cleaned log](https://gist.github.com/maestrozezinho/b8c24c8106da6eef3620de28694cb5bd)

Search starts at line 11.

**Comment by loray-zz** [comment]
The same thing is happening to me,  Bazarr does not find any subtitles for Fargo TV show. My only provider is Legendas.Tv, and my Bazarr version is 0.9.0.6.

**Comment by loray-zz** [comment]
Here is the log

<script src="https://gist.github.com/loray-zz/42ffdcfbd5711511231ea6c42831cb46.js"></script>

**Comment by loray-zz** [comment]
Here is the log
[Log](https://gist.github.com/loray-zz/42ffdcfbd5711511231ea6c42831cb46)

**Comment by morpheus65535** [comment]
Can you show me a screenshot of your manual search dialog?

**Comment by maestrozezinho** [comment]
[Manual search dialog screenshot](https://ibb.co/6RdxNjG)

**Comment by loray-zz** [comment]
[Search dialog](https://ibb.co/0szck3Z)

**Comment by morpheus65535** [comment]
I'm still working on this. I can't reproduce on Windows, Mac or Linux but I can on LSIO or Hotio Docker images. For now I have no real clue...

**Comment by morpheus65535** [comment]
I've made some improvement. I hope it fixed your issue but I would appreciate if you could confirm. Thanks!

**Comment by morpheus65535** [comment]
I've been able to test this morning and I now get subs when searching manually in my Hotio's nightly container.

**Comment by maestrozezinho** [comment]
It's strange, but I wasn't able to find with 0.9.7 (hotio nightly), but was able to find with 0.9.6 (linuxserver):

[0.9.7 Log](https://pastebin.com/aw1G4sth)
[0.9.6 Log](https://pastebin.com/FMf9PQpC)

**Comment by loray-zz** [comment]
I do not understand the coding, but it seems that Bazarr is looking in the wrong place for the subtitles, in legendas.tv provider.

[print_legendas.TV](https://ibb.co/5RjPFS4)

[0.9.6 log](https://gist.github.com/loray-zz/1c04bed5de7f8f0457dda9ac4f212dbd)

**Comment by morpheus65535** [comment]
You should both try to empty your cache directory.

**Comment by loray-zz** [comment]
> 
> 
> You should both try to empty your cache directory.

It worked, thanks

**Comment by maestrozezinho** [comment]
> You should both try to empty your cache directory.

It also worked for me, thanks!

I think we can consider this issue as closed.
