### ISSUE TITLE
Some specific Movies and TV Shows seems to not be researched

### ISSUE THREAD

**Issue by GhostPyxel** [morpheus65535/bazarr#1190]
**Describe the bug**
My Bazarr setup works perfectly and as expected but only for a part of my libraries of movies and TV shows. Some of them are not researched (or at least it seems like it) and therefore not downloaded. 

I've tried automatic researches based on scheduled tasks, mass research through the Wanted Tab and individual researches on specific missing movies. None of them gave results so far. 

For example, I tried to research for the english subtitle for the movie "The Kennel Murder Case". This subtitle is available to download on OpenSubtitles.org but is not found by Bazarr. The weirdest thing is that Bazarr research history about this movie (which I triggered earlier) is completely empty.

And this goes for about less of the half of my libraries, some of them simply seems ignored. I get that some of them may be not added because the subtitles are simply not available but for the most part that I've searched, a lot of them are ready to be downloaded on my subtitles providers (especially OpenSubtitles and Addicted).

**To Reproduce**
1. Pick a missing Movie or TV Show
2. Check if the subtitle of the requested language is available on any provider
3. Click on Search (any method wanted)
4. See error - No subtitles are downloaded

**Expected behavior**
Download the existing subtitles for the requested movie / tv show.

**Software:**
 - Bazarr v0.9.0.5 [based on LinuxServer Docker Image "latest" - should be "Build 8462386b-ls46"]
 - Radarr version 0.2.0.1504
 - Sonarr version 2.0.0.5344
 - OS [Synology DSM 6.2.3-25426 Update 2 - Docker Version 18.09.0-0513]

**Lastest Log**
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5497497/bazarr.log)

(All missing subtitles are also marked as "Search is not active for this Movie / TV Show". I'm not sure what it means but from what I've seen in previous posts referring to this issue, "Yes" my Adaptive Searching is activated and always has been).

**Comment by morpheus65535** [comment]
The "issue" is that you enabled adaptive searching. All your movies/episodes are skipped because of it. You can read more about it here: https://github.com/morpheus65535/bazarr/wiki/Performance-Tuning#enable-adaptive-searching

Also, all your providers are throttled for multiple reason.

So you don't have an issue but need help to configure. You can rely on support team on Discord for that.

**Comment by GhostPyxel** [comment]
The wiki specifically says: "Adaptive searching should be (**Always**) enabled when you have many missing subtitles." 
I have over 4000 subtitles missing, how could I have known if your responses on Reddit about this and your wiki says otherwise ?

I'm on my own then, thanks.

**Comment by morpheus65535** [comment]
What I mean is that this is a normal behavior when you enable adaptive searching: it search less often for a missing subtitles after some attempt. It's not that Bazarr isn't searching for your subtitles, Bazarr is trying to put subs that it can't find on hold to be able to search for others.

And, BTW, your not on your own. I said that you can come to Discord for support. Github Issues is there to report bugs. :-)

**Comment by GhostPyxel** [comment]
Alright, I'll try to explain the errors in my Bazarr the best I'll can on Discord. 
Thanks for your help and time.
