### ISSUE TITLE
Authelia auth_request over NginX causes `DataTables warning: table id=series - Ajax error.` on Series and Movies page

### ISSUE THREAD

**Issue by jarylc** [morpheus65535/bazarr#1191]
**Describe the bug**
After integrating Authelia with NginX proxy, I am unable to view the list of Series and Movies in Bazarr. I am able to when I relax my firewall and access Bazarr directly by port.

**To Reproduce**
I have confirmed that only after adding `auth_request /sso;` to Bazarr's block causes this issue 100% of the time.

My `/sso` block configuration follows the standard Authelia documentation with not much changes:
```nginx
location /sso {
    internal;
    proxy_pass_request_body off;
    proxy_pass http://Authelia:9091/api/verify;
    proxy_set_header Content-Length "";

    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

    client_body_buffer_size 128k;
    proxy_set_header Host $host;
    proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr; 
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Uri $request_uri;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_redirect  http://  $scheme://;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_cache_bypass $cookie_session;
    proxy_no_cache $cookie_session;
    proxy_buffers 4 32k;

    send_timeout 5m;
    proxy_read_timeout 240;
    proxy_send_timeout 240;
    proxy_connect_timeout 240;
}
```

**Expected behavior**
I am able to view the list of Series and Movies even with Authelia integrated.

**Screenshots**
![image](https://user-images.githubusercontent.com/1162128/98316947-61f8d980-2016-11eb-9fe4-b3ad354e7b5a.png)

**Software (please complete the following information):**
Running linuxserver's development docker image:
- Bazarr Version: 0.9.0.6
- Sonarr Version: 3.0.4.993
- Radarr Version: 3.0.0.3987
- Operating System: Linux-5.9.1-1-edge-x86_64-with
- Python Version: 3.8.5

**Comment by morpheus65535** [comment]
https://github.com/morpheus65535/bazarr/wiki/Reverse-Proxy-Help#using-authelia-authentication

**Comment by jarylc** [comment]
Yes I've thought of doing that, but isn't that just exposing the API endpoints unprotected by Authelia?

Unless there's API/CSRF tokens used on the front-end, I don't believe this should be the right way. If there is, I think maybe it's a good idea to include in the documentation.

I assume it's the `X-Api-Key` looking at the network logs?

**Comment by morpheus65535** [comment]
The API is protected by an APIKEY the same way Sonarr and Radarr are. Why is this an issue to leave it open?

**Comment by jarylc** [comment]
Looking at it further, yeah I guess it's a viable workaround to leave the API endpoints unprotected. The only way to retrieve the API-Key is through the main UI anyway and it's required for all queries through /api.

I was always using `None` authentication on all my -arr applications and was assuming API key wasn't compulsory until this.

Anyway solved I guess, thanks for the help.
