### ISSUE TITLE
No Subtitles Found For This Episode

### ISSUE THREAD

**Issue by malatu14** [morpheus65535/bazarr#1193]
**Describe the bug**
Hi,

I'm a Bazarr user for one year now. When I've made my first setup, everything worked really good. But since few weeks, Bazarr doesn't work greats anymore for me, because apparently, It doesn't found any subtitles for any content (fresh-released episodes or older, It's the same) despite the fact I have 5-6 providers installed.

Nothing has changed recently on my Synology/Plex/Sonarr/Radarr setup. When I make a manual search, it's returns me : "No Subtitles Found For This Episode"

Do you have an idea to help me please ?

Kindly,

.

**Screenshots**

<img width="1146" alt="Capture d’écran 2020-11-10 à 07 17 16" src="https://user-images.githubusercontent.com/74229922/98635315-0afc4880-2325-11eb-8a4f-b07248181726.png">

**Software (please complete the following information):**
 - Bazarr: v0.9.0.5
 - Radarr version 0.2.0.1450

 - Sonarr version 2.0.0.5344

 - OS:Raspbian

**Comment by morpheus65535** [comment]
Debug log please?

**Comment by malatu14** [comment]
Hi,

Here's my logs : 

[bazarr (1).log](https://github.com/morpheus65535/bazarr/files/5517590/bazarr.1.log)

**Comment by morpheus65535** [comment]
`10/11/2020 11:41:55|ERROR   |root                            |BAZARR Error trying to get video information for this file: /media/NAS/video/Plex/TV shows/The Mandalorian/Season 2/The.Mandalorian.S02E02.1080p.DSNP.WEBRip.DDP5.1.Atmos.x264-PHOENiX[rartv].mkv|'Traceback (most recent call last):\n  File "/home/pi/bazarr/bazarr/get_subtitle.py", line 67, in get_video\n    refine_from_ffprobe(original_path, video)\n  File "/home/pi/bazarr/bazarr/get_subtitle.py", line 1080, in refine_from_ffprobe\n    exe = get_binary(\'ffprobe\')\n  File "/home/pi/bazarr/bazarr/utils.py", line 102, in get_binary\n    raise BinaryNotFound\nutils.BinaryNotFound'|`

You need to install ffmpeg as described on the wiki: https://github.com/morpheus65535/bazarr/wiki/Installation#linux.

**Comment by malatu14** [comment]
This solved my issues. Thanks you !
