### ISSUE TITLE
GreekSubs bug or ffsubsync bug? Different synchronisations

### ISSUE THREAD

**Issue by pizzabe** [morpheus65535/bazarr#1194]
**Describe the bug**
when downloading from bazarr a sub from the provider GreekSubs, sometimes the synchronisation is done wrong. However, if downloading to my local pc the same sub from same provider and then uploading it to bazarr and then clicking on synch, the synchronisation is done correctly. Any ideas why this might be?

Haven't noticed happening this with other providers. 

Here's me reproducing the issue: https://pastebin.com/KAc8V3YD

**Software (please complete the following information):**
Bazarr Version: 0.9.0.6
Sonarr Version: 3.0.4.993
Radarr Version: 0.2.0.1504
Operating System: Linux-5.4.0-52-generic-x86_64-with
Python Version: 3.8.5
Docker hotio image.

I'm on dev branch

**Comment by morpheus65535** [comment]
`BAZARR subsync skipped because subtitles score isn't below this threshold value: 100%`

Configuration issue.

**Comment by pizzabe** [comment]
what do you mean ? there are 2 different synchs 
10/11/2020 16:28:22|INFO    |ffsubsync.ffsubsync             |computing alignments...|
10/11/2020 16:28:23|INFO    |ffsubsync.ffsubsync             |...done|
10/11/2020 16:28:23|INFO    |ffsubsync.ffsubsync             |offset seconds: 10.480|
AND 
10/11/2020 16:29:50|INFO    |ffsubsync.ffsubsync             |computing alignments...|
10/11/2020 16:29:51|INFO    |ffsubsync.ffsubsync             |...done|
10/11/2020 16:29:51|INFO    |ffsubsync.ffsubsync             |offset seconds: 5.380|

**Comment by pizzabe** [comment]
what you posted has nothing to do with the issue

**Comment by morpheus65535** [comment]
You set threshold for subtitles synchronization to 100%. The subs from the provider website doesn't have a perfect score so sync is skipped. When you upload it, Bazarr always consider the score as perfect then sync it. Does that make sense?

**Comment by pizzabe** [comment]
Not if you manually request the sub. It syncs if not 100%.

**Comment by pizzabe** [comment]
In both cases, the sub was synched.

**Comment by pizzabe** [comment]
It's pretty clear in the logs as well.
![bazarr23](https://user-images.githubusercontent.com/73953139/99364405-9b570200-28be-11eb-8c54-55076e344b13.png)

this is the same sub. First time, I manually requested to download it. When you manually request a non 100% score sub, it synchs. Like it happened. 

then I downloaded the sub myself, and uploaded it through the web interface. I then clicked synch. It synched. Gave me different results. Hope this helps.

**Comment by morpheus65535** [comment]
If it synced the subs with a score lower than 100%, it's because your settings was set lower at time. I've check the code again and it's called the same way for automatic/manual/upload except for upload we force the score to 100%.

Now, if you got different results when running the sync multiple times, I don't know what's the issue as it is called exactly the same way. Must be some logic in ffsubsync that choose a different reference track.

If that's an issue for you, I suggest you enable sync debug and open an issue on ffsubsync github by proving the requested ffsubsync debug files.

There's nothing I can do on my side.
