### ISSUE TITLE
Postprocessing fails due to stripped trailing quote

### ISSUE THREAD

**Issue by geluk** [morpheus65535/bazarr#1195]
**Describe the bug**
The configuration parser strips trailing quotes from configuration variables, which can cause issues with custom post processing commands.

**To Reproduce**
1. Go to 'Settings > Subtitles'
2. Enable 'Use custom post processing'
3. Enter the following post processing command: `echo 'hello'`
4. Go to Series or Movies, and download a new subtitle to trigger the post processing command

**Expected behavior**
The logs should contain the following message, to indicate that the post processing succeeded:
```
BAZARR Post-processing result for file /video/tv/test.mkv : hello
```

**Actual behavior**
No output is produced by the command, because the trailing `'` got stripped, so the shell fails to interpret it:
```
BAZARR Post-processing result for file /video/tv/test.mkv : Nothing returned from command execution
```

**Additional context**
The problem originates in [`simpleconfigparser/__init__.py`](https://github.com/morpheus65535/bazarr/blob/master/libs/simpleconfigparser/__init__.py), lines 81 and 129.

The configuration parser strips all leading and trailing quotes from the configuration keys, which causes this issue.
The post-processing command gets written to the configuration file as:
```ini
postprocessing_cmd = echo 'hello'
```
But, when it's subsequently read from the configuration file, the trailing comma gets stripped, and the value of the variable becomes:
```
echo 'hello
```
This causes the shell to fail to interpret the command, which is why no output gets generated.

I considered creating a PR for this, but there are a few ways this can be resolved, and I am not sure which one you'd prefer. As far as I can tell from my local installation,, quoted configuration values are not used. If that is the case everywhere, perhaps the `strip('"\'')`s can simply be removed.

However, if they are required, I think it would be good to only remove quotes from the string if matching quotes are found on both ends, and to not remove more than one level of quotes.

**Comment by morpheus65535** [comment]
Duplicate #309
