### ISSUE TITLE
Synced subtitles are saved as *.en.synced.srt?

### ISSUE THREAD

**Issue by maxtheking** [morpheus65535/bazarr#1196]
Hi,

I recently enabled the subtitle sync option in Bazarr to sync all downloaded subs if they have a score lower than 100, and it's working well, but it outputs a [new file](https://i.maxkoning.nl/2020-11-13_15-52-30.jpg) instead of overwriting the original one, is this the way it's supposed to work? Because now in Plex for movies with synced subs I have both the original (out of sync) ones, and the [synced ones](https://i.maxkoning.nl/2020-11-13_15-53-14.jpg) which is confusing for users.

Thanks in advance!

**Comment by morpheus65535** [comment]
If you check your log, you'll see that subtitles synchronization failed. The .synced file is a leftover file that can be removed.

A simple search for `.synced.` in closed issues would have returned 23 other issues like yours. 😛
