### ISSUE TITLE
Not downloading  subs anymore

### ISSUE THREAD

**Issue by spijkey87** [morpheus65535/bazarr#1197]
I cant download subtitles anymore. Only movie subs not from tv shows. the logs shows

('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')), retrying in 5 seconds...

**Comment by halali** [comment]
Please fill full issue template with all informations.

**Comment by halali** [comment]
But conn3ction aborted is probably issue on your side.

**Comment by morpheus65535** [comment]
Any news? Is it still an issue?

**Comment by morpheus65535** [comment]
No news, good news.

**Comment by wieluk** [comment]
Hi, I am having the same problem how did you fix it?

**Comment by lunks** [comment]
Hey, I just started having this problem. Can this be reopened? Happy to give more info.

**Comment by morpheus65535** [comment]
> Hey, I just started having this problem. Can this be reopened? Happy to give more info.

No, open your own issue.
