### ISSUE TITLE
Autostart plist on mac not working

### ISSUE THREAD

**Issue by X8PX** [morpheus65535/bazarr#1199]
launchctl load ~/Library/LaunchAgents/com.github.morpheus65535.bazarr.plist

Running the code above gives "Load failed: 5: Input/output error".
I'm on macOS Big Sur. I've had this happen on High Sierra, but reinstalling bazarr usually worked. This time it didn't. Any idea?

**Comment by halali** [comment]
Please come to discord channel. There you can get support... I'm closing this as its not an bazarr issue.
