### ISSUE TITLE
Clicking Edit button on Notifications page does nothing

### ISSUE THREAD

**Issue by misleadingrhino** [morpheus65535/bazarr#1200]
**Describe the bug**
Clicking Edit button on Notifications page does nothing.

**To Reproduce**
1. Go to Settings/Notification. 
2. Click on Edit.
3. Nothing happens. 
4. It still works with providers that are set up (Discord in this case). Can't find anything in the config directory to edit manually. Created a new config file from a fresh container but had the same issue.  

**Expected behavior**
Some type of editor for the notifications is brought up. 

**Software (please complete the following information):**
linuxserver.io's bazarr container
Bazarr Version: 0.9.0.7
Sonarr Version:
Radarr Version:
Operating System: Linux-5.4.0-54-generic-x86_64-with
Python Version: 3.8.5
Bazarr Directory: /app/bazarr
Bazarr Config Directory: /config

**Comment by morpheus65535** [comment]
Select a provider first then click Edit button.

**Comment by misleadingrhino** [comment]
Of course. Thank you!
