### ISSUE TITLE
Addic7ed times out too quickly

### ISSUE THREAD

**Issue by Skamba** [morpheus65535/bazarr#1201]
**Describe the bug**
After not getting a response from Addic7ed for 10 seconds, it times out. However, this seems to be on the short side as the Addic7ed website can be rather slow at times when looking up a season. Often, it will time out 5 times in a row and then block Addic7ed.

**To Reproduce**
1) Use Addic7ed
2) Search for a large number of subtitles
3) Check the logs to see that Addic7ed timed out

**Expected behavior**
No timeouts.

**Logs**
Bazarr log:

> 
> 02/12/2020 09:40:44|WARNING |retry.api                       |HTTPSConnectionPool(host='www.addic7ed.com', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
> 02/12/2020 09:40:49|ERROR   |subliminal_patch.core           |Provider 'addic7ed' timed out|
> 02/12/2020 09:40:49|INFO    |root                            |Throttling addic7ed for 1 hour, until 20/12/02 10:40, because of: ReadTimeout. Exception info: ReadTimeoutError("HTTPSConnectionPool(host='www.addic7ed.com', port=443): Read timed out. (read timeout=10)")|
> 

I've also ran a few curls to see how long it can take to load this page:

> C:\temp\curl-7.73.0_3-win64-mingw\bin>curl -o C:\temp\output.txt https://www.addic7ed.com/ajax_loadShow.php?show=255&season=3
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  1959    0  1959    0     0     74      0 --:--:--  0:00:26 --:--:--   510
> 
> C:\temp\curl-7.73.0_3-win64-mingw\bin>curl -o C:\temp\output.txt https://www.addic7ed.com/ajax_loadShow.php?show=255&season=3
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  1959    0  1959    0     0    129      0 --:--:--  0:00:15 --:--:--   504
> 
> C:\temp\curl-7.73.0_3-win64-mingw\bin>curl -o C:\temp\output.txt https://www.addic7ed.com/ajax_loadShow.php?show=255&season=3
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  1959    0  1959    0     0    102      0 --:--:--  0:00:19 --:--:--   502
> 
> C:\temp\curl-7.73.0_3-win64-mingw\bin>curl -o C:\temp\output.txt https://www.addic7ed.com/ajax_loadShow.php?show=255&season=3
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  1959    0  1959    0     0     84      0 --:--:--  0:00:23 --:--:--   510

All of the above requests did lead to correct output.

Suggestion: Increase the time-out for Addic7ed. 

**Software (please complete the following information):**
Bazarr Version: 0.9.0.7
Sonarr Version: 3.0.4.1023
Radarr Version: 3.0.0.4204
Operating System: Windows-10-10.0.19041-SP0

**Additional context**
On a gigabit fiber connection near the AMS-IX - my connection has no problems.

**Comment by morpheus65535** [comment]
Thanks for investigating this one. I've increased the timeout to 60 seconds for each an every calls made to Addic7ed in version v0.9.0.8 in dev branch. I hope it will fix your issue. Please confirm.

**Comment by Skamba** [comment]
That fixed the error - although it seems like today is an even worse day for Addic7ed as their web server is also throwing in 503s every now and then - but I guess the expected behavior of Bazarr blocking it temporarily makes sense in that case.
