### ISSUE TITLE
Missing post-processing on "synced" files.

### ISSUE THREAD

**Issue by Aginarikar** [morpheus65535/bazarr#1206]
The post-processing option is activated and has worked for a long time in my setup.
Recently «Automatic subtitles synchronization» has been activated and synchronization is also working normally.

But files which now have names like _Some.Movie.**synced**.en.srt_ have not been post-processed.
For the record, all .srt and .synced.en.srt files still have the identical file permissions.

**Comment by morpheus65535** [comment]
`Some.Movie.synced.en.srt` is a failed synced left over file. Check your log file for details on why.
