### ISSUE TITLE
No longer able to install

### ISSUE THREAD

**Issue by colinjacques** [morpheus65535/bazarr#1208]
Had an issue accessing the GUI, figured it was something to do with a windows update so decided to do a clean install. Now i am no longer able to install on windows.

**Comment by morpheus65535** [comment]
Uninstall, delete `C:\bazarr directory` (or wherever you've installed it) and make sure do delete `%programdata%\bazarr` directory.

Install using installer and let it update for at least 15 minutes. Now, change service user account if required, restart service and access UI.
