### ISSUE TITLE
Installation Instructions Will Not Work For Ubuntu 16.04.*

### ISSUE THREAD

**Issue by kennbr34** [morpheus65535/bazarr#1209]
**Describe the bug**
The provided installation instructions on the Wiki will not work for Ubuntu 16.04 because the versions of python and pip in its software repositories are out of date. 

**To Reproduce**
1. Try to run 'pip install -r requirements.tx'

**Unexpected behavior**
Python/pip will throw an error and not allow the installation of packages in requirements.txt

Error encountered...

`Collecting numpy>=1.12.0 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/c5/63/a48648ebc57711348420670bb074998f79828291f68aebfff1642be212ec/numpy-1.19.4.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-tugwhu9q/numpy/setup.py", line 68
        f"NumPy {VERSION} may not yet support Python "
                                                     ^
    SyntaxError: invalid syntax
    
    ----------------------------------------`

**Software (please complete the following information):**
 - Bazarr: 0.9.0.7
 - OS: */ubuntu 16.04.*

**Additional context**
Obviously since 16.04 is nearing its EOL, there will not be many users that encounter this, but I thought it might be helpful to mention.

**Solution**
Install Python 3.8 and pip 20.3.1 manually

**Comment by halali** [comment]
You use unsupported python version for numpy.
