### ISSUE TITLE
"Invalid credentials, try again." Can't login in Web-UI

### ISSUE THREAD

**Issue by wieluk** [morpheus65535/bazarr#1212]
**Describe the bug**
It is giving me "Invalid credentials, try again." when I try to login on web-Ui

**To Reproduce**
Honestly I am not sure just happend. I am always using passwordmanager nothing changed also tried without because I know the username and Password but still not working.

**Expected behavior**
Let me acces the web Ui

**Software (please complete the following information):**
 - Bazarr version: latest:stable

**Additional context**
How can I change user/password in console ?

**Comment by morpheus65535** [comment]
You read the wiki...

https://github.com/morpheus65535/bazarr/wiki/FAQ#how-do-i-reset-my-password

**Comment by wieluk** [comment]
yeah but why is it happening though ? It is not like I forgot my password

**Comment by morpheus65535** [comment]
Did you just upgrade to v0.9.x? Were you running older version last time you accessed the web UI?

**Comment by wieluk** [comment]
I have auto update enabled so yeah I am on the newest version but I was on v0.9x before.
I'll let you know if it happens again if you want thanks for your help :)

**Comment by morpheus65535** [comment]
It could also be a bug in the upgrade process for the username/password (we had to reset password for those upgrading from 0.8.x to 0.9.x. I've just check and more than 99% of the users have already upgraded. I'll disable this password reset in next version and the few that are gonna get locked out will have to manually reset their password using the procedure mentioned in the wiki.
