### ISSUE TITLE
link subtitle files to the video

### ISSUE THREAD

**Issue by victorfau** [morpheus65535/bazarr#1213]
Help wanted 

What I want to do : 

After downloading subtitles in two languages, I  want to link .srt files to the .mkv (or .mp4) file automatically. For this I tried to move many options but nothing did what I want. 

If someone has a solution it will be very helpful 
Thank you

**Comment by morpheus65535** [comment]
If you want to formulate feature request, please go to https://bazarr.featureupvote.com, sesrch for existing request and if you don't find it, create a new one.
