### ISSUE TITLE
[provider] legendas divx - 1s delay everywhere

### ISSUE THREAD

**Issue by Norin-Radd** [morpheus65535/bazarr#1215]
legendasdivx provider gets IP blocked because the number of requests per minute is higher than 60, or more than 1 request per second.

Please implement 1second delay everywhere.

thanks

 - Bazarr: v0.9.0.7
 - Radarr version 3.0.1.4260
 - Sonarr version 3.0.4.1026
 - OS: docker containers

**Comment by morpheus65535** [comment]
Should be fixed in dev branch.
