### ISSUE TITLE
Empty movies / series list, no interesting logs, wrong timezone

### ISSUE THREAD

**Issue by jeromegn** [morpheus65535/bazarr#1216]
**Describe the bug**

I've just installed Bazarr for the first time on my QNAP TS-451+. Pulled the latest from `master`. Everything seems fine according to the settings (testing sonarr and radarr is successful).

However, there are no movies or series. Even if I trigger manual updates. The logs aren't helpful (see screesnhot). I tried filtering different log levels but I only get simple boot logs and the hashes shown in the screenshot.

I think this might be due to a timezone issue as shown in the screenshot. Some tasks are show their "Next Execution" with "x minutes ago". I'm in the EST timezone, which would fit with the time column in the logs.

My QNAP did not have a `/etc/timezone` file at all. I manually created one and restarted Bazarr, but it didn't help.

**To Reproduce**
1. Install Bazarr from QNAP Club
2. Setup Bazarr normally

**Expected behavior**

Expecting to see series and movies or error logs if it didn't work.

Times should also not show in the future.

**Screenshots**

![image](https://user-images.githubusercontent.com/43325/102693813-2ba0a380-41eb-11eb-9eed-7be5c5b54874.png)

**Software (please complete the following information):**
 - Bazarr: v0.9.0.7
 - Radarr version v3.0.1.4259
 - Sonarr version v3.0.4.1033
 - OS: QNAP 4.5.1.1495

**Comment by halali** [comment]
Please read wiki how to report an issue and come to discord for support with settings... This is for issue reporting.

Thank you.
