### ISSUE TITLE
[Provider] www.sous-titres.eu isn't working

### ISSUE THREAD

**Issue by NeZios** [morpheus65535/bazarr#1217]
Hi everyone,

**Describe the bug**
Bazarr can't reach out [www.sous-titres.eu](url) which has a lot of **good french substitles**.

**Log**
Here is the log that I have :
`Throttling soustitreseu for 1 hour, until 20/12/21 10:47, because of: ReadTimeout. Exception info: ReadTimeoutError("HTTPSConnectionPool(host='www.sous-titres.eu', port=443): Read timed out. (read timeout=10)")`

**Screenshot**
![image](https://user-images.githubusercontent.com/38002539/102757628-e5c21780-4371-11eb-8600-2caa57cc612b.png)

**Software**
 - Bazarr: v0.9.0.7 
 - Sonarr version 3.0.4.1033
 - OS: Windows Server 2019

Thanks in advance for your help

**Comment by halali** [comment]
This isn't an issue. Read times means provider don't respond for your requests in 10 second. It may have couple reasons.
Your is is blocked.
Site is down.
