### ISSUE TITLE
wiki improvement

### ISSUE THREAD

**Issue by RobinMM** [morpheus65535/bazarr#1218]
hi there,

I am using Bazarr on windows. I am not running Bazarr in program files folder but created a separate folder 'Tools\Bazarr' on my  C drive to install it. 

Because Bazarr needs to access to folders over the network I changed the user (local/non-admin) that the service should use. 

After changing this I was not able to access the web interface anymore. After digging deeper into this problem I found its because when installing Bazarr files are also created in the programdata\bazarr folder. 

After I added write rights to this folder for the user that the service is using it started to work again. Maybe this info can be mentioned on the WIKI page? :)

**Comment by morpheus65535** [comment]
Done. Thanks for reporting!
