### ISSUE TITLE
Not able to move to any page other thant 1 on WANTED

### ISSUE THREAD

**Issue by dcbinder** [morpheus65535/bazarr#1219]
**Describe the bug**
When you are on series or movies and you click on any page other than 1 Bazarr moves to the page you clicked on, but, a few seconds after that Bazarr automatically returns to the page 1.

**To Reproduce**
1. Go to WANTED
2. Click on ANY PAGE OTHER THAN 1
3. WAIT FOR A FEW SECONDS
4. BAZARR WILL RETURN AUTOMATICALLY TO PAGE 1 AFTER A FEW SECONDS

**Expected behavior**
BAZARR REMAINS ON THE PAGE YOU CLICKED ON

**Screenshots**
N/A

**Software (please complete the following information):**
 - Bazarr: LATEST
 - Radarr version LATEST
 - Sonarr version LATEST
 - OS: WINDOWS 10

**Additional context**
N/A

**Comment by halali** [comment]
This is caused probably by some plugin in your browser. Or something in your environment.

**Comment by halali** [comment]
And also please fill corretly issue template... Bazarr latest isn't good version number... For you could be latest different than for us.

**Comment by dcbinder** [comment]
Hello there !

Actually it is not caused by any plugin. I have tested on a Chrome with no plugins running at all and also tested on MS Edge where the same issue occurs.

Bazarr version: v0.9.0.7
Radarr version: v3.0.1.4284
Sonarr version: v3.0.4.1033

I can record the screen if you want.

Regards.

**Comment by halali** [comment]
Can't reproduce.

**Comment by halali** [comment]
Any error in your browser console?

**Comment by dcbinder** [comment]
I have recorded the error.

https://1drv.ms/u/s!Aku1Eb4BhjflnI1MRXRKUS8byTyGXg?e=TymSZU

Regards

**Comment by halali** [comment]
Any error in your browser console?

**Comment by morpheus65535** [comment]
@halali Indexing was still in progress or Bazarr was downloading new subtitles that were getting removed from the wanted list. For that reason, Datatables was being redrawn and paging reset (going back to page 1) even if we set resetPaging to false. 

@dcbinder I've changed it a bit in dev branch if you can test it and confirm if it fix your issue.

**Comment by dcbinder** [comment]
Seems to be working !! Congrats !
