### ISSUE TITLE
Feature request : basic http auth 

### ISSUE THREAD

**Issue by cams87** [morpheus65535/bazarr#122]
Hi

I'm accessing all my docker cotainers through a revese proxy. Basic http auth is mandatory for my use :)

Thanks

**Comment by cams87** [comment]
I've just seen it has already been asked...

**Comment by halali** [comment]
It's part of development branch https://github.com/morpheus65535/bazarr/commit/55be0aad60b4e3970fd84975e2dcbba6bb00da29
