### ISSUE TITLE
Score thresholds not applied to manually uploaded subtitles

### ISSUE THREAD

**Issue by kSotin** [morpheus65535/bazarr#1221]
**Describe the bug**
Manually uploaded subtitles always trigger the post-processing execution, despite that a score threshold between 0-99 is set. 

**Expected behavior**
Manually uploaded subtitles, which are always scored 100 as shown in the UI, should not go through a post-processing execution under a score threshold between 0-99. 

**Software (please complete the following information):**
 - Bazarr: 0.9.0.7
 - OS: Ubuntu 20.04

**Comment by halali** [comment]
Can you attach also debuglog with issue?

**Comment by morpheus65535** [comment]
That's the expected behavior.

**Comment by kSotin** [comment]
Thanks for the clarification.
