### ISSUE TITLE
Same movies and TV show subs downloaded over and over.

### ISSUE THREAD

**Issue by iesou** [morpheus65535/bazarr#1223]
**Describe the bug**
Same subs are being downloaded over and over, bazarr seems stuck on these for some reason

**To Reproduce**
1. let bazarr attempt to grab files
2. see it only grabs subs it already has

**Expected behavior**

**Screenshots**
![2021-01-01_11-50-41](https://user-images.githubusercontent.com/76846282/103443061-65c96680-4c29-11eb-9c05-fcdcc6574ab0.jpg)
![2021-01-01_11-50-54](https://user-images.githubusercontent.com/76846282/103443062-6661fd00-4c29-11eb-86d6-f36b645cd8d8.jpg)

**Software (please complete the following information):**
 - Bazarr: [v0.9.0.7]
 - Radarr version [3.0.1.4259]
 - Sonarr version [2.0.0.5344]
 - OS: [Unraid 6.9.0-rc2]

**Additional context**
Bazarr debug log here:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5759185/bazarr.log)

**Comment by morpheus65535** [comment]
Duplicate from #1141

**Comment by iesou** [comment]
> Duplicate from #1141

Thanks, sorry I missed that one
