### ISSUE TITLE
Buttons on 'manual subtitle search' page inaccesible on mobile view

### ISSUE THREAD

**Issue by Elmardus** [morpheus65535/bazarr#1224]
When accessing a TV series episode on a mobile device (Xiaomi Mi Mix 3, Firefox for Android) the subtitle download buttons are off-screen on the 'manual subtitle search' results page. This is shown below:

![image](https://user-images.githubusercontent.com/25563589/103540447-fc03c380-4e99-11eb-8f54-bdfeef6933dc.png)

I am unable to scroll sideways to download any subtitles.

**Software (please complete the following information):**
 - Bazarr: v0.9.0.7
 - OS: Android, using Firefox 84.1.2

**Comment by morpheus65535** [comment]
Should be fixed now in dev branch.
