### ISSUE TITLE
.css not downloading

### ISSUE THREAD

**Issue by djjoakim** [morpheus65535/bazarr#1226]
**Describe the bug**
When accesing the site localhost:6767 the site won't load .css, i have tried the "Windows installer" and also tried to install Bazarr from cmd with python and git.
I have also tried to run with virus program off, windows firewall off, vpn off... i also tried to run on another computer but with the local adress and it's the same.

![wrong](https://user-images.githubusercontent.com/77078108/103820872-599c3980-506d-11eb-90be-8936c5788732.png)

**Software (please complete the following information):**
 - Bazarr: [e.g. v 0.9.7] ? Latest Windows
 - OS:  Windows 10]

**Comment by morpheus65535** [comment]
Please send me your config.ini file.

Other than that, it could be a misconfiguration of MIME type on your client computer or a security software interfering with Bazarr or you browser.
