### ISSUE TITLE
Bazarr docker container from Linuxserver running on x86 is taking over 4gb RAM

### ISSUE THREAD

**Issue by arthursoares** [morpheus65535/bazarr#1227]
![WhatsApp Image 2021-01-11 at 16 32 25](https://user-images.githubusercontent.com/533339/104211934-f4619300-5434-11eb-948b-55b887509b6d.jpeg)

**Describe the bug**
The app is hogging a lot of RAM even when it is sitting idle

**Expected behavior**

**Screenshots**

**Software (please complete the following information):**
Bazarr Version: 0.9.0.7
Sonarr Version: 3.0.4.1059
Radarr Version: 3.0.1.4259
Operating System: Linux-4.4.59+-x86_64-with
Python Version: 3.8.5
Bazarr Directory: /app/bazarr
Bazarr Config Directory: /config

Enclosed is the log file.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5797130/bazarr.log)

**Comment by morpheus65535** [comment]
That's a bug in Sinology Docker interface. That's not active RAM but cached RAM. To get the real amount of RAM, use `top` command instead or Portainer if you want a UI.

**Comment by arthursoares** [comment]
@morpheus65535 thank you.
