### ISSUE TITLE
Assrt Subtitle selection error

### ISSUE THREAD

**Issue by zpengcom** [morpheus65535/bazarr#1228]
When bazarr downloads a multi-subtitle compressed package from assrt, the compressed package contains:
Name.EN.srt
Name.CN.srt
Name.CN.saa
Name.CN&EN.srt
Etc. file

Although my bazarr is set to download Chinese subtitles
But bazarr often only chooses Name.EN.srt as Chinese subtitles
So is it possible to set matching keywords as download subtitles
 For example, set matching keywords in bazzar: CN, CHS, CN&EN
When downloading to multiple file contents, the file containing keywords can be selected first

![image](https://user-images.githubusercontent.com/8217132/104265015-a77acc80-54c7-11eb-960e-aeea5a14fac9.png)

Bazarr Version:
0.9.0.7
Sonarr Version:
2.0.0.5344
Radarr Version:
3.0.1.4259
Operating System:
Linux-3.10.105-x86_64-with
Python Version:
3.8.5

**Comment by morpheus65535** [comment]
Bazarr should not download multiple files archives (and no archives at all anyway) and we don't even have zip or rar module used in this provider. Are you sure you're not mixing up providers?

**Comment by zpengcom** [comment]
It seems that I made a mistake. I'll go to Assr to solve it

**Comment by morpheus65535** [comment]
No problem, keep me informed if can be of any help.

**Comment by zpengcom** [comment]
I read the api doc of assrt
Assrt provides a filelist (not zip/rar)

I'm not sure if it is related to this part
-----
filelist The list of files contained in the subtitle compression package (optional)
	s : file size
	f : file name
	url : The file download address
------

**Comment by morpheus65535** [comment]
Yes, in fact it provide the listing of the content of the .rar file you would normally download on their website. The `url` is in fact a download link for a single .srt inside that .rar file. Bazarr use guessit to guess the subtitles metadata (including language) from the filename (f).

**Comment by morpheus65535** [comment]
I guess I can close this one? Reopen it if it's still an issue and explain what is expected.

**Comment by kkycble** [comment]
@morpheus65535 is there any way to make Bazarr only pick srt files with certain keywords/ tags? like cht/ 繁体(traditional)?

**Comment by morpheus65535** [comment]
> @morpheus65535 is there any way to make Bazarr only pick srt files with certain keywords/ tags? like cht/ 繁体(traditional)?

No.

**Comment by kkycble** [comment]
> > @morpheus65535 is there any way to make Bazarr only pick srt files with certain keywords/ tags? like cht/ 繁体(traditional)?
> 
> 
> 
> No. 

Oh I see. That would have been great for downloading Tradition Chinese subs. Thanks anyways 😉

**Comment by morpheus65535** [comment]
https://github.com/morpheus65535/bazarr/pull/1236 should achieve the same goal.

**Comment by kkycble** [comment]
> https://github.com/morpheus65535/bazarr/pull/1236 should achieve the same goal.

Fingers crossed!! Thank you for your great work and efforts man 😁
