### ISSUE TITLE
[PROVIDER] sous-titres.eu ReadTimeOut

### ISSUE THREAD

**Issue by WoisWoi** [morpheus65535/bazarr#1229]
Hi !

**To Reproduce**
Simply add sous-titres.eu as provider
I'm sorry if it's not a bug, but I don't see where and how I could fix it.

**Screenshots**
![image](https://user-images.githubusercontent.com/75491231/104620412-43a30000-568f-11eb-9076-36c1cd3844b8.png)

**Software :**
 - Bazarr: v0.9.0.7
 - OS: Linux debian x64

Thanks a lot !

**Comment by morpheus65535** [comment]
What was the cause of this issue?

**Comment by WoisWoi** [comment]
> 
> 
> What was the cause of this issue?

I don’t know the origin of the problem, all the other providers worked correctly, but a simple deactivation/ reactivation of the provider fixed the problem... I forgot to check this out before posting.
Is it a common "issue" with providers ?

Sorry if I wasted your time :)

**Comment by morpheus65535** [comment]
That could happen if provider is down or is throttling the requests coming from your IP. Shared IP could increase the risk of this to happen.

**Comment by WoisWoi** [comment]
> 
> 
> > What was the cause of this issue?
> 
> I don’t know the origin of the problem, all the other providers worked correctly, but a simple deactivation/ reactivation of the provider fixed the problem... I forgot to check this out before posting.
> Is it a common "issue" with providers ?
> 
> Sorry if I wasted your time :)



> 
> 
> That could happen if provider is down or is throttling the requests coming from your IP. Shared IP could increase the risk of this to happen.

https://www.sous-titres.eu/
Provider seems to be up, but the problem is back. I suppose it's not related to Bazarr

**Comment by WoisWoi** [comment]
> 
> 
> That could happen if provider is down or is throttling the requests coming from your IP. Shared IP could increase the risk of this to happen.

Well, the problem is back and still there :(

**Comment by morpheus65535** [comment]
Seems like they are throttling too frequent requests. I've made an attempt to fix this in 0.9.0.8 in dev branch. Can you test it?

**Comment by WoisWoi** [comment]
> 
> 
> Seems like they are throttling too frequent requests. I've made an attempt to fix this in 0.9.0.8 in dev branch. Can you test it?

The release is available ? I only see the 0.9.0.7

**Comment by morpheus65535** [comment]
It's in dev branch. You must running using docker or from sources to test it.

**Comment by WoisWoi** [comment]
> 
> 
> It's in dev branch. You must running using docker or from sources to test it.

Oh, well I see now. My bad. 
Can I deploy it through portainer ?

**Comment by morpheus65535** [comment]
Yes but you need to use images dev tag (different for lsio and hotio) and redeploy the container using this image.

**Comment by WoisWoi** [comment]
> 
> 
> Yes but you need to use images dev tag (different for lsio and hotio) and redeploy the container using this image.

Something like that : "linuxserver/bazarr:dev" ?

**Comment by morpheus65535** [comment]
`linuxserver/bazarr:development`

**Comment by WoisWoi** [comment]
> 
> 
> `linuxserver/bazarr:development`

For now, it is working 👍 :)

**Comment by morpheus65535** [comment]
> For now, it is working 👍 :)
> 
> Thanks a lot !

Keep me informed. I eould like to merge to master in the next days. Thanks!

**Comment by WoisWoi** [comment]
> 
> 
> > For now, it is working 👍 :)
> > Thanks a lot !
> 
> Keep me informed. I would like to merge to master in the next days. Thanks!

I have another problem : 
![image](https://user-images.githubusercontent.com/75491231/104960844-6148d000-59d5-11eb-8019-ca2cdcca948b.png)

when I restart the container it's fine, but then, after some times it does this

**Comment by morpheus65535** [comment]
That's unrelated, please come to Discord for support. Bazarr can't access those directories, it's either a permission issue or the volume is not available anymore.

**Comment by WoisWoi** [comment]
> 
> 
> > For now, it is working 👍 :)
> > Thanks a lot !
> 
> Keep me informed. I would like to merge to master in the next days. Thanks!

I have another problem : 
![image](https://user-images.githubusercontent.com/75491231/104960844-6148d000-59d5-11eb-8019-ca2cdcca948b.png)

when I restart the container it's fine, but then, after some times it does this


> 
> 
> That's unrelated, please come to Discord for support. Bazarr can't access those directories, it's either a permission issue or the volume is not available anymore.

The volume is available, but every 9 000 seconds I have a script that unmount and remount the volume.
I do not believe it's a right issue, but maybe.

**Comment by WoisWoi** [comment]
> 
> 
> > For now, it is working 👍 :)
> > Thanks a lot !
> 
> Keep me informed. I would like to merge to master in the next days. Thanks!

I think the problem is solved, it's still working :)

**Comment by obygyv** [comment]
> > > For now, it is working 👍 :)
> > > Thanks a lot !
> > 
> > 
> > Keep me informed. I would like to merge to master in the next days. Thanks!
> 
> I think the problem is solved, it's still working :)

Hi @WoisWoi 
How did you setup sous-titres.eu to work in bazarr? I can't make it grab any tv show subtitle, I don't know why. I can see on sous-titres.eu that the sub has been posted, but bazarr can't find it. It only works with opensubtitles.org.

What's your setup?
