### ISSUE TITLE
Unable to detect speech. Perhaps try specifying a different stream

### ISSUE THREAD

**Issue by andonevris** [morpheus65535/bazarr#1231]
**Describe the bug**
When trying to sync any file I get error message: Unable to detect speech. Perhaps try specifying a different stream

>  File "c:\\program files\\bazarr\\bazarr\\subsyncer.py", line 56, in sync
>   result = run(self.args)
>  File "c:\\program files\\bazarr\\bazarr\\../libs\\ffsubsync\\ffsubsync.py", line 283, in run
>   reference_pipe.fit(args.reference)
>  File "c:\\program files\\bazarr\\bazarr\\../libs\\ffsubsync\\sklearn_shim.py", line 214, in fit
>   self._final_estimator.fit(Xt, y, **fit_params)
>  File "c:\\program files\\bazarr\\bazarr\\../libs\\ffsubsync\\speech_transformers.py", line 250, in fit
>   raise ValueError(

> ValueError: Unable to detect speech. Perhaps try specifying a different stream / track, or a different vad.

**To Reproduce**
Sync on any file causes above error.  Have tried with AC3 DTS AAC

**Expected behavior**
Sync file without error

**Software (please complete the following information):**
 - Bazarr: 0.9.0.7
 - Sonarr Version: 3.0.4.1077
 - Radarr Version: 3.0.2.4369

 - OS: Windows 10 20H2 x86
 - python version 3.8.7  (also tested with python 2.7)
 - Media files hosted on NAS via SMB

Have opened a ticket with ffsubsync they believe the issue may be on the bazarr side
https://github.com/smacke/ffsubsync/issues/113

**Comment by morpheus65535** [comment]
Please provide the complete debug log.

**Comment by andonevris** [comment]
When I set filter in bazarr-> system->logs to debug I get 0 entries.

In settings I have enabled 

> Subtitles synchronization debugging
> Do not actually sync the subtitles but generate a .tar.gz file to be able to open an issue for ffsubsync. This file will reside alongside the media file.

There is no .tar.gz residing next to the media file.

the ffsubsync.log is empty

Anywhere else I should be looking for debug log files?

**Comment by morpheus65535** [comment]
You need to enable debug logging: https://github.com/morpheus65535/bazarr/wiki/FAQ#how-do-i-enable-the-debug-log

**Comment by andonevris** [comment]
Checking the debug logs it seems bazarr was using an old ffmpeg.exe path with a higher priority than the latest version.  Deleting the old path reference returned normal functionality.

Thanks for your help.

**Comment by morpheus65535** [comment]
Pleasure mate, enjoy!
