### ISSUE TITLE
Sonarr not updating - exception thrown

### ISSUE THREAD

**Issue by mobamoba** [morpheus65535/bazarr#1233]
**Describe the bug**
Sonarr isn't updating at all. I get this error:

```
Traceback (most recent call last):
 File "c:\\bazarr\\bazarr\\../libs\\apscheduler\\executors\\base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "c:\\bazarr\\bazarr\\get_series.py", line 33, in update_series
  audio_profiles = get_profile_list()
 File "c:\\bazarr\\bazarr\\get_series.py", line 194, in get_profile_list
  profiles_list.append([profile[\id\], profile[\name\].capitalize()])
TypeError: string indices must be integers
````
**To Reproduce**
1. It reproduces itself every minute when it tries to update series from Sonarr.

**Expected behavior**
It should update.

**Software (please complete the following information):**
 - Bazarr: v0.9.0.8
 -  - Sonarr version [e.g. v 2.0.0.0001] 3.0.4.1077
 - OS: [e.g. Windows 10] Server 2016

**Additional context**
I tried stopping the Bazarr service and deleting the DB and letting it recreate a new one, but that didn't solve the problem, so DB corruption isn't the issue. Not sure what else to try, thanks.

**Comment by morpheus65535** [comment]
Sound stupid but did you try to restart Sonarr?

**Comment by mobamoba** [comment]
Just tried - didn't solve the problem.

**Comment by morpheus65535** [comment]
Can you show me the json returned by this call in your browser?

http://sonarr:8989/api/v3/languageprofile?apikey=################################

**Comment by mobamoba** [comment]
Sure, filling in Sonarr API key, I get the following:

[
  {
    "name": "English",
    "upgradeAllowed": true,
    "cutoff": {
      "id": 1,
      "name": "English"
    },
    "languages": [
      {
        "language": {
          "id": 0,
          "name": "Unknown"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 13,
          "name": "Vietnamese"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 17,
          "name": "Turkish"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 14,
          "name": "Swedish"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 3,
          "name": "Spanish"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 11,
          "name": "Russian"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 18,
          "name": "Portuguese"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 12,
          "name": "Polish"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 15,
          "name": "Norwegian"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 24,
          "name": "Lithuanian"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 21,
          "name": "Korean"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 8,
          "name": "Japanese"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 5,
          "name": "Italian"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 9,
          "name": "Icelandic"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 22,
          "name": "Hungarian"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 23,
          "name": "Hebrew"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 20,
          "name": "Greek"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 4,
          "name": "German"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 2,
          "name": "French"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 19,
          "name": "Flemish"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 16,
          "name": "Finnish"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 1,
          "name": "English"
        },
        "allowed": true
      },
      {
        "language": {
          "id": 7,
          "name": "Dutch"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 6,
          "name": "Danish"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 25,
          "name": "Czech"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 10,
          "name": "Chinese"
        },
        "allowed": false
      }
    ],
    "id": 1
  }
]

**Comment by morpheus65535** [comment]
If you click on the test button in Settings-->Sonarr, does it fail or pass?

**Comment by mobamoba** [comment]
That was it. Just FYI I've been using Bazarr and Sonarr for years I never generated a new Sonarr key so I have no idea why some random key wound up in Bazarr but that solved it thanks.

**Comment by morpheus65535** [comment]
That's strange. I'll see if somebody else face the same issue. Thanks for the feedback!
