### ISSUE TITLE
BAZARR Error trying to get video information for this file

### ISSUE THREAD

**Issue by JpF4E** [morpheus65535/bazarr#1234]
**Describe the bug**
When trying to search for a subtitle the error below appears. My guess is that the anime notation to search for subtitles is not being considered, am I right? Usually series are named SXXEYY but in anime it sometimes can be different and many files are downloaded with the notation SX - Y.
Shouldn't Bazarr read some of this information from the Sonarr metadata instead of the filename?
```
BAZARR Error trying to get video information for this file: /home/joao/Series/Attack on Titan/Season 3/[HorribleSubs] Shingeki no Kyojin S3 - 38 [1080p].mkv
Traceback (most recent call last):
 File "/mnt/ext/opt/bazarr/bazarr/get_subtitle.py", line 63, in get_video
  hash_from=hash_from)
 File "/mnt/ext/opt/bazarr/bazarr/../libs/subzero/video.py", line 62, in parse_video
  skip_hashing=skip_hashing, hash_from=hash_from)
 File "/mnt/ext/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 534, in scan_video
  video = Video.fromguess(path, guessed_result)
 File "/mnt/ext/opt/bazarr/bazarr/../libs/subliminal/video.py", line 94, in fromguess
  return Episode.fromguess(name, guess)
 File "/mnt/ext/opt/bazarr/bazarr/../libs/subliminal/video.py", line 171, in fromguess
  raise ValueError(\Insufficient data to process the guess\)
ValueError: Insufficient data to process the guess
```

**To Reproduce**
1. Search for Anime subtitles with anime notation in the filename. Example in the stacktrace.
2. See error

**Expected behavior**
No error.

**Screenshots**
N/A

**Software (please complete the following information):**
Bazarr Version: 0.9.1
Sonarr Version: 3.0.4.1077
Radarr Version: 3.0.2.4446
Operating System: Linux-4.18.0-240.1.1.el8_3.x86_64-x86_64-with-centos-8.3.2011

**Additional context**
N/A

**Comment by JpF4E** [comment]
Another example:

`BAZARR Error trying to get video information for this file: /home/joao/Series/Dr. Stone/Season 1/[EMBER] Dr. Stone S02 - 01.mkv
`

**Comment by JpF4E** [comment]
Another example:
`BAZARR Error trying to get video information for this file: /home/joao/Series/That Time I Got Reincarnated as a Slime/Season 2/[EMBER] Tensei Shitara Slime Datta Ken S2 - 01.mkv`
Could it be the Japanese name in it that Bazarr does not recognize as the correct name?

**Comment by morpheus65535** [comment]
Could it be related to square brackets? Can you test it?

And, TBH, I never really tested anime episode numbering as I don't watch anime. :-/

**Comment by JpF4E** [comment]
Usually anime comes with subtitles in English so I've never used Bazarr for anime. But today I wanted to include subtitles in my own language (portuguese) and I couldn't do it in most animes due to this error.

**Comment by morpheus65535** [comment]
I've investigate and I confirm I can reproduce the issue.

One of the first step of searching a subtitle is creating the video object. During that process, we use GuessIt to guess the video properties from the file path and the scene name. Unfortunately, GuessIt is unable to parse the episode number from this naming scheme:
```
For: Attack on Titan/Season 3/[HorribleSubs] Shingeki no Kyojin S3 - 59 [1080p].mkv
GuessIt found: {
    "season": 3,
    "release_group": "HorribleSubs",
    "title": "Shingeki no Kyojin",
    "episode_title": "59",
    "screen_size": "1080p",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```
There's nothing I can really do about it. You can rename to have a "traditional" naming scheme or open an issue on GuessIt github and try to make them add support for this use case.

**Comment by morpheus65535** [comment]
As there's nothing else I can do until GuessIt deals with it, I'll close this issue.

**Comment by JpF4E** [comment]
I started to rename all my media.
Thanks.
