### ISSUE TITLE
Unsupported URL: localhost:2000

### ISSUE THREAD

**Issue by Visne** [morpheus65535/bazarr#1237]
**Describe the bug**
The log shows "Unsupported URL: localhost:2000" about once every minute. According to scheduler settings, Sonarr series list is updated once a minute, nothing else. I currently have Kodi on port 2000, but I don't see how that would relate to Bazarr.

**Software (please complete the following information):**
 - Bazarr: v0.9.0.8
 - Radarr version v3.0.2.4369
 - Sonarr version v3.0.4.1083
 - OS: Raspbian 10 (5.10.7-v7l+ armv7l)

**Comment by Visne** [comment]
![image](https://user-images.githubusercontent.com/39844191/105434964-c9f5ae00-5c5c-11eb-823a-811087873ae6.png)

This makes me feel like it's related to subtitle synchronization somehow.

**Comment by morpheus65535** [comment]
You probably have Common Fixes enabled in Settings-->Subtitles. Can you disable it and retry?

**Comment by Visne** [comment]
> 
> 
> You probably have Common Fixes enabled in Settings-->Subtitles. Can you disable it and retry?

No, still happening. I also have reencoding, OCR fixes, uppercase and custom enabled.

**Comment by morpheus65535** [comment]
That an issue with Notifications configuration. The URL for one Apprise provider is unsupported.

**Comment by Visne** [comment]
Ah, I added kodi:// to the front and now it works.
