### ISSUE TITLE
Invalid series path

### ISSUE THREAD

**Issue by D3nn3** [morpheus65535/bazarr#124]
Hi there,

I'm using OpenMediaVault and installed Bazarr through Docker. It seems to run fine with one exception: Bazarr says for every TV Show that the path seems to be invalid (Don't have Radarr so can't say if movies would work). The path shown is correct and the same as in Sonarr. The logs didn't help since there is no mention of any problem concerning paths and directories.

When starting the Docker image I set the path to the directory where all my TV Shows are (see screen). Am I doing anything wrong?

![docker](https://user-images.githubusercontent.com/20516965/44255306-e2e51400-a205-11e8-9636-a93cd6c7103b.jpg)

**Comment by morpheus65535** [comment]
Does sonarr see episode with the exact same path (ie: /tv/series/season/episode)? If not, you need to use path mapping.

**Comment by D3nn3** [comment]
Yes. Here is an example from Sonarr (taken from the Series page in the weg UI): /media/36b05725-fab4-48b1-8bf6-56bdaa16c292/media/tv/The 100/Season 5/The 100 - S05E13 - Damocles (2) (WEBDL-720p TBS).mkv

**Comment by D3nn3** [comment]
Thank you very much, that was it. I thought mapping was only necessary if Sonarr and Bazarr don't run on the same machine - my bad! Should have read the instructions more carefully.

**Comment by morpheus65535** [comment]
Good news! Have fun!
