### ISSUE TITLE
Menu counter tooltips on Wanted menu frozen under certain conditions

### ISSUE THREAD

**Issue by forkless** [morpheus65535/bazarr#1240]
**Describe the bug**
When forced subtitles are set to Both, the counters on the Wanted menu no longer decrease on added subtitles.

**To Reproduce**
1. Go to Settings > Languages > Default Settings 
2. Click on pulldown menu for the Forced option
3. Select Both
4. Save Settings
5. Go Series/Movies > Mass Edit > Select All
6. Select Both on Forced
7. Save

**Expected behavior**
The counters on the Wanted menu entries should decrease as subtitles are being added, like they do on the False setting.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 0.9.0.8
 - Radarr version 3.0.2.4423
 - Sonarr version 3.0.4.1083
 - OS: Linux-4.4.0-197-generic-x86_64-with-Ubuntu-16.04-xenial - Python 3.7.9
 
**Additional context**

**Comment by morpheus65535** [comment]
This issue won't be fixed because we have completely reworked this in 0.9.1. You can give it a try by switching to dev branch. Be aware that you won't be able to switch back to previous version without reconfiguring your desired languages.
