### ISSUE TITLE
Can't connect to tusubtitulo.com provider

### ISSUE THREAD

**Issue by dtalens** [morpheus65535/bazarr#1242]
Bazarr is unable to connect to tusubtitulo.com provider. This provider use cloudflare protection. I use flareresolverr in jacket and it work fine. Can it be used with bazaar?

`Unexpected error in provider 'tusubtitulo': Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 170, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/tusubtitulo.py", line 253, in list_subtitles    return self.query(languages, video)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/tusubtitulo.py", line 226, in query    results = self.search(video.series, str(video.season), str(video.episode))  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/tusubtitulo.py", line 203, in search    titles = self.index_titles()  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/tusubtitulo.py", line 89, in index_titles    r.raise_for_status()  File "/opt/bazarr/bazarr/../libs/requests/models.py", line 940, in raise_for_status    raise HTTPError(http_error_msg, response=self)requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.tusubtitulo.com/series.php?/`
`Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 170, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/tusubtitulo.py", line 253, in list_subtitles    return self.query(languages, video)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/tusubtitulo.py", line 226, in query    results = self.search(video.series, str(video.season), str(video.episode))  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/tusubtitulo.py", line 203, in search    titles = self.index_titles()  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/tusubtitulo.py", line 89, in index_titles    r.raise_for_status()  File "/opt/bazarr/bazarr/../libs/requests/models.py", line 940, in raise_for_status    raise HTTPError(http_error_msg, response=self)requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.tusubtitulo.com/series.php?/`

Bazarr Version: 0.9.8
Sonarr Version: 3.0.4.1083
Radarr Version: 3.0.2.4369
Operating System: Linux-5.4.0-64-generic-x86_64-with-glibc2.29
Python Version: 3.8.5

**Comment by morpheus65535** [comment]
IT seems that they've implemented captcha protection, not only cloudflare anti-bot. Taht's a totally different game. I'll see what I can do but @pannal is more qualified on that.

**Comment by vitiko98** [comment]
I can pass that 403 with another User-Agent. Nonetheless, it looks like they just modified the HTML, so a scrape update is needed.

**Comment by morpheus65535** [comment]
Fixed by @vitiko98 in 0.9.1 currently in dev branch. Thanks!
