### ISSUE TITLE
Bazarr ffprobe failures

### ISSUE THREAD

**Issue by forkless** [morpheus65535/bazarr#1244]
**Describe the bug**
Bazarr fails to parse media with ffprobe. It appears Bazarr fetches the source title instead of the sanitized path to parse it through ffprobe.

**To Reproduce**
1. Go to Sonarr/Radarr and drill into a series episode or movie and use the rename feature.
2. Go to Bazarr drill into the series episode/movie just renamed and try to sync newly renamed item
3. Check log file
4. See error, it fails to parse physical media that has been renamed.

**Expected behavior**
Bazarr should fetch the media path for the series episode or movie for ffprobe and not the source title.

**Screenshots**
n/a

**Software (please complete the following information):**
 - Bazarr version v 0.9.0.8
 - Radarr version v 3.0.2.4423
 - Sonarr version v 3.0.4.1085
 - OS: Linux-4.4.0-197-generic-x86_64-with-Ubuntu-16.04-xenial
 - Python version v 3.7.9

**Additional context**

**Comment by morpheus65535** [comment]
I need a debug log because right now I can't reproduce. FFprobe use the actuel file path.

**Comment by forkless** [comment]
I hope this will be of more help;

https://pastebin.com/89cGnW6V

**Comment by morpheus65535** [comment]
How is the file named on disk?

`/media/movies/Hitman Agent 47 (2015)/Hitman.Agent.47.2015.1080p.BluRay.DD5.1.x264-GeneMige.mkv`
or
`/media/movies/Hitman Agent 47 (2015)/Hitman Agent 47 (2015).mkv`

**Comment by forkless** [comment]
As the sanatized one at the bottom

**Comment by forkless** [comment]
I took a screenshot of the filtered debug log;

https://imgur.com/a/8nQ6E11

**Comment by morpheus65535** [comment]
Ok the good news is that there's an error in debug logging. The debug line should state the real path, not the one we built to fake use scene name.

The bad news is that this is clearly not your issue. From your log: `Command '['/usr/bin/ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', '-sexagesimal', '/media/movies/Hitman Agent 47 (2015)/Hitman Agent 47 (2015).mkv']'`

I see that you are using a pretty old version of ffprobe (v2.8.17). Current version is 4.3.1. You should either upgrade it or use the one included in Bazarr sources. Just make sure you don't have one in your path and Bazarr will use the embedded one.

Please confirm if it fix your issue.

**Comment by forkless** [comment]
How do I tell Bazarr to use the included ffmpeg/ffprobe? Is there a configuration option somewhere or do I need to prepend the PATH?

**Comment by morpheus65535** [comment]
You need to uninstall it from your system or update it to a recent stable version (no nightly).

**Comment by forkless** [comment]
https://pastebin.com/gWNbDMYh

Upgraded ffmpeg to 4.3.1

**Comment by morpheus65535** [comment]
And what is the output from this command?

`/usr/bin/ffprobe -v quiet -print_format json -show_format -show_streams -sexagesimal "/media/movies/Hitman Agent 47 (2015)/Hitma Agent 47 (2015).mkv"`

**Comment by forkless** [comment]
That's returning an empty JSON object

**Comment by morpheus65535** [comment]
And this one?

`/usr/bin/ffprobe "/media/movies/Hitman Agent 47 (2015)/Hitma Agent 47 (2015).mkv"`

**Comment by forkless** [comment]
[matroska,webm @ 0x559d5d500040] Format matroska,webm detected only with low score of 1, misdetection possible!
[matroska,webm @ 0x559d5d500040] 0x00 at pos 0 (0x0) invalid as first byte of an EBML number
[matroska,webm @ 0x559d5d500040] EBML header parsing failed
/media/movies/Hitman Agent 47 (2015)/Hitman Agent 47 (2015).mkv: Invalid data found when processing input****

**Comment by morpheus65535** [comment]
Seems like you'Ve got your answer... something's wrong with your mkv.

**Comment by forkless** [comment]
I get that, why is it reporting a file that doesn't exist in the log though? A non-existing file is an automatic Access Denied no?

**Comment by morpheus65535** [comment]
The erroneous filename logging have been fixe in my latest commit to dev branch.

As for the damaged state of the mkv container, the library that we use to parse ffprobe output doesn't seems to support that. I'll look into it and see if I can add this feature.

**Comment by forkless** [comment]
All good, thanks for all your help and making this awesome tool.

Next mission getting ffsubsync to behave (LOL) I have a feeling this may be related to some of the MKV headers being damaged as well. Anyway, not your problem -)
