### ISSUE TITLE
Feature request: don't show subtitles that are non existent on the web as wanted

### ISSUE THREAD

**Issue by mattiaskagstrom** [morpheus65535/bazarr#125]
**Example:** 
a library with 700 episodes where English and Swedish subtitles are "wanted".
Bazarr fetches all subtitles it can find.
most have subtitles for both languages, some have only for one, and some have none.
all missing subtitles are still "wanted" yes, but none of the wanted ones are possible to download.

**Feature request:** 
show the wanted as "0" wanted out of those that are available, and add a category of "unavailable subtitles" that have a re-scan period of.. a week? (preferably configurable) when the unavailable subtitles should be scanned again if any of them have become available. if they are available, add them to wanted again.

**Comment by halali** [comment]
added in https://github.com/morpheus65535/bazarr/commit/53f3338ef7940313580a18d44ed903c5e4669fc7
