### ISSUE TITLE
Movies/Series history throws ajax error

### ISSUE THREAD

**Issue by Helerr** [morpheus65535/bazarr#1250]
**Describe the bug**
When opening History -> Series or Movies, Bazarr throws the following ajax error: DataTables warning: table id=history_movies - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**To Reproduce**
1. Go to 'Bazarr'
2. Click on 'History'
3. Click on Series or Movies
4. Bazarr shows a popup with the error mentioned.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31351317/105868115-7be6fe80-5ffe-11eb-9932-48a66a8d02a6.png)

**Software (please complete the following information):**
 - Bazarr: [v0.9.0.8]
 - Radarr version [3.0.2.4369]
 - Sonarr version [3.0.4.1091]
 - OS: [Windows 10 20H2 build 19042.782]

**Additional context**
Bazarr downloads the subtitles just fine, statistics are working but the History for Series and Movies throw that error.
I already tried to empty cache and remove the DB file from ProgramData/Bazarr/db but it still does the same thing.

In logs I see the following error: 
![image](https://user-images.githubusercontent.com/31351317/105868645-11828e00-5fff-11eb-998f-b38b477f9d04.png)
![image](https://user-images.githubusercontent.com/31351317/105868697-1fd0aa00-5fff-11eb-8252-0a6c38883117.png)

**Comment by morpheus65535** [comment]
Go to Settings-->Subtitles and define the number of days you want to upgrade subtitles. Save settings and check if your issue is fixed.

**Comment by Helerr** [comment]
Yep, that solved it. I kept trying to set that up but it wouldn't let me for some reason. (Couldn't move slider or change the number of days in any way) but now that seems to work too. Thanks! :D
