### ISSUE TITLE
Podnapisi SSLError

### ISSUE THREAD

**Issue by Dr0bac** [morpheus65535/bazarr#1251]
I'm using bazarr for maybe two weeks and from the start podnapisi provider is not working, i have only few movies in radarr/bazarr, and searching tasks for missing and upgrading movies are every 12 hours.

logs

[bazarr.log](https://github.com/morpheus65535/bazarr/files/5878146/bazarr.log)

**Comment by morpheus65535** [comment]
Duplicate from #927 ?

https://github.com/morpheus65535/bazarr/issues/927#issuecomment-613156380

Check the part about podnapisi.

**Comment by Dr0bac** [comment]
Yes i'm on debian buster (raspberry pi 3b)

I changed SECLEVEL to value "1" in `/etc/ssl/openssl.cnf` and after i restarted raspberry pi i tried to search for subtitles and SSLError was listed in logs again, i now tried again to check, and everything went ok, no errors. I will check from time to time.

Two questions:
1. After i clicked on "search all" icon in wanted tab, my hdd were movies are woke up from sleep.
When i check in history tab, no subtitles are downloaded at the moment, so what option did wake up my hdd?

2. In history tab i see this icon that say "this subtitle file is eligible for an upgrade". Is that mean that only those subtitles with this icon will upgrade at some time if better subtitle is found? I ask because some subtitles with smaller score than these subtitles with upgrade sign doesn't have that icon.
I guess because all subtitles that have score lower than 100% are eligible for upgrade? And those subtitles that are 3 weeks old are not checked anymore because in setting it is set to watch for upgrades i guess 10 days.
![Untitled](https://user-images.githubusercontent.com/43797966/106215044-61fd1580-61d0-11eb-948d-b77d1cdb72fb.png)

**Comment by morpheus65535** [comment]
In answer to your questions:
1. On each subtitles search (successful or not), we use ffprobe to refine our search using media file metadata.
2. You guessed it right. :-)

I'll close this issue but reopen it if it happen again. It shouldn't ;-)

**Comment by Dr0bac** [comment]
Can i turn this metadata reading off somewhere in settings, i like to keep my hdd in sleep mode as much as possible.
Why don't just use metadata information from radarr api?
If it is looking for embedded subtitles i think that i turned off that option in settings.

**Comment by morpheus65535** [comment]
This is done to get the best possible information about the media file. Sonarr and Radarr API do a great job but doesn't provide everything that we could use.

Currently, there's a user on Discord that propose himself to make a PR to cache those result to prevent doing each and every time. I haven't heard from him since last week so I don't know how it goes.

Alternatively, I could add a setting to disable refine_from_ffprobe(). You can do a feature request for it or, even better, draft a PR :-)

**Comment by Dr0bac** [comment]
I see that you mentioned the user on discord that was thinking on including ffprobe results in cache, but he gave no feedback.

so can i create feature request: "Don't wake external hdd on subtitle search or subtitle upgrade if no subtitles are found"?

**Comment by morpheus65535** [comment]
Yes you can create a feature but it's the other way around: we run ffprobe before searching for subtitles to get video container attributes to refine the video object passed to subliminal. Let phrase it that way: `Cache video file attributes to prevent running ffprobe on every subtitles search`. Sounds good to you?
