### ISSUE TITLE
Problem with 2 providers

### ISSUE THREAD

**Issue by WoisWoi** [morpheus65535/bazarr#1254]
Hi ! 

Describe the bug
First problem : ![image](https://user-images.githubusercontent.com/75491231/106362232-017ded80-6322-11eb-940d-96f7d0a2edf0.png)
Second one : ![image](https://user-images.githubusercontent.com/75491231/106362236-09d62880-6322-11eb-9d2d-6034dbcd0742.png)

Could we reduce the number of request to bsplayer to avoid this ?

**Comment by halali** [comment]
Please fill issue template, if you have questions go to discord for support.

**Comment by WoisWoi** [comment]
> 
> 
> Please fill issue template, if you have questions go to discord for support.
> 
> And dont forgot to include debug logs...

I gave all the information I had...

**Comment by halali** [comment]
You have to fill issue template... That one you deleted when you posting this issue.

**Comment by WoisWoi** [comment]
**Describe the bug**
The screenshot describe everyhting.

**To Reproduce**
Use bazarr to... find subtitles.


**Expected behavior**
Working providers.

**Screenshots**
(above)

**Software (please complete the following information):**

Bazarr Version: 0.9.1
Operating System: Linux-5.4.0-56-generic-x86_64-with

(not related) Sonarr Version :3.0.4.1091

**Additional context**
Nothing to say, I guess.

**Comment by morpheus65535** [comment]
Enable debug log and provide a log reproducing your issues. Thanks.

**Comment by WoisWoi** [comment]
> 
> 
> Enable debug log and provide a log reproducing your issues. Thanks.
> 
> BTW: providing version is the least you can do. We implement fix between versions and not providing this info could lead us to investigate issues that were already fixed in newer version you could haven't installed yet. In your case, you're running latest dev so you should have all the latest fixes.

Yes, that's why I haven't mentionned it. But I understand it was a mistake, since you never know...

How can I enable debug log ? I only see the logging debug option in general.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5899418/bazarr.log)

**Comment by halali** [comment]
hi, this isnt debug log, and there also not your issue with provider.

only issue is that bazarr is try to delete subtitles that doesnt exist 
```
BAZARR cannot delete subtitles file: /series/Animés/Death Note/Season 1/[Ryuuga] - Death Note  - 12 - Love [1080p].fr.srt|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/utils.py", line 236, in delete_subtitles\n    os.remove(path_mappings.path_replace(subtitles_path))\nFileNotFoundError: [Errno 2] No such file or directory: \'/series/Animés/Death Note/Season 1/[Ryuuga] - Death Note  - 12 - Love [1080p].fr.srt\''
```

Reasons can be: 

1.  you or something deleted that file by hand and you didnt refresh existing subtitles for that series.
2. Sonarr changed location of that file and bazarr isnt sync with sonarr.

Again not an bazarr issue.

**Comment by WoisWoi** [comment]
> 
> 
> hi, this isnt debug log, and there also not your issue with provider.
> 
> only issue is that bazarr is try to delete subtitles that doesnt exist
> 
> ```
> BAZARR cannot delete subtitles file: /series/Animés/Death Note/Season 1/[Ryuuga] - Death Note  - 12 - Love [1080p].fr.srt|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/utils.py", line 236, in delete_subtitles\n    os.remove(path_mappings.path_replace(subtitles_path))\nFileNotFoundError: [Errno 2] No such file or directory: \'/series/Animés/Death Note/Season 1/[Ryuuga] - Death Note  - 12 - Love [1080p].fr.srt\''
> ```
> 
> Reasons can be:
> 
>     1. you or something deleted that file by hand and you didnt refresh existing subtitles for that series.
> 
>     2. Sonarr changed location of that file and bazarr isnt sync with sonarr.
> 
> 
> Again not an bazarr issue.

I blacklisted those sub. But you still have the providers error.

**Comment by halali** [comment]
For 1st. I need to see exception you got... And that i can see only in debug log.

2nd... This is totally normal.

**Comment by WoisWoi** [comment]
> 
> 
> For 1st. I need to see exception you got... And that i can see only in debug log.
> 
> 2nd... This is totally normal.

as I said "How can I enable debug log ? I only see the logging debug option in general.", it's not that I don't want to do it...

**Comment by halali** [comment]
https://github.com/morpheus65535/bazarr/wiki/Logging-and-Log-Files

**Comment by WoisWoi** [comment]
> 
> 
> https://github.com/morpheus65535/bazarr/wiki/Logging-and-Log-Files

Well, I thought it was the "login" debug... X_x I’m a little distracted, sorry...
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5899466/bazarr.log)

**Comment by halali** [comment]
Ok this looks like issue with anime naming. bazarr except naming like S01E01 but provider return subtitles with absolute series number...

For now there is nothing we can do about it...

**Comment by halali** [comment]
you can open FR for support anime in bazarr... for now there isnt support for absolute episode.

**Comment by WoisWoi** [comment]
> 
> 
> Ok this looks like issue with anime naming. bazarr except naming like S01E01 but provider return subtitles with absolute episode number...
> 
> For now there is nothing we can do about it...

All because there is not the "S01" in front of "Ep X" ? 
![image](https://user-images.githubusercontent.com/75491231/106380399-405b8400-63b2-11eb-9c3a-9823c82042e9.png)

**Comment by halali** [comment]
yes, bazarr dont know what season is it.

And this naming is because this is absolute episode number, so for example season 2 will start with ep.11 not ep.01

**Comment by WoisWoi** [comment]
> 
> 
> yes, bazarr dont know what season is it.
> 
> And this naming is because this is absolute episode number, so for example season 2 will start with ep.11 not ep.01

Yeah, unfortunately, I already know about this 'annoying japanesse absolute number'. It's a problem on so many level.
In any way, thanks you 👍
