### ISSUE TITLE
ffsub (auto sync) -> subtitles offset

### ISSUE THREAD

**Issue by WoisWoi** [morpheus65535/bazarr#1255]
**Describe the bug**
Synchronization failed; consider passing --max-offset-seconds with a number larger than 600
-> How to change this setting (of ffsub) without loosing the modification when updating bazarr ?

**Expected behavior**
Subtitle to be properly sync (not 50 minutes off, for a 25 min episode)

**Screenshots**
Properly sync (for example Death note E3)  ![image](https://user-images.githubusercontent.com/75491231/106365417-c1286a80-6335-11eb-9168-a952195df788.png)

Total mess (death note E33) : 
![image](https://user-images.githubusercontent.com/75491231/106365434-f1700900-6335-11eb-8f4d-e452132e8410.png)

**Comment by halali** [comment]
Read wiki and come to discord if you have questions and stop open issues with questions. Thank you
