### ISSUE TITLE
Subscene RAR files cause provider to be throttled

### ISSUE THREAD

**Issue by demize** [morpheus65535/bazarr#1256]
**Describe the bug**
A number of releases on Subscene appear to be released in RAR archives rather than ZIP archives, which causes Bazarr to fail to extract from the archive and throttle the Subscene provider.

**To Reproduce**
I'll use the series "The Inbetweeners" as an example here, as it's one that's missing subtitles and suffers from this issue.
1. Go to the series page for The Inbetweeners
2. Do a manual search for subtitles for S01E05 with Subscene as an enabled provider.
3. Attempt to download the release at hxxps://subscene.com/subtitles/the-inbetweeners-first-season/english/373014
4. The download fails and Subscene gets throttled for 10 minutes.

**Expected behavior**
Bazarr recognizes and extracts the RAR file.

**Software (please complete the following information):**

- Bazarr Version: 0.9.0.8 (LSIO docker)
- Sonarr Version: 3.0.4.1095
- Radarr Version: 3.1.0.4519
- Operating System: Linux-5.4.51-v7l+-armv7l-with
- Python Version: 3.8.5

**Additional context**
[Logs](https://github.com/morpheus65535/bazarr/files/5902874/bazarr.cut.log), censored and cut a little bit to include only the relevant content.

**Comment by morpheus65535** [comment]
I've made a small fix, can you confirm that RAR archives are now managed correctly?

**Comment by demize** [comment]
Tested with a couple episodes that had subtitles in RAR files, both worked. Looks good now!
