### ISSUE TITLE
The subtitles file extension should not change when it is manually uploaded.

### ISSUE THREAD

**Issue by isyangban** [morpheus65535/bazarr#1257]
**Describe the bug**
When manually uploading subtitles, their extensions are manually changed. (*.smi -> *.ko.srt)

**To Reproduce**
1.  Click on any series
2.  Click upload on the top toolbar or manual upload button in the episode list
3. Upload any files that ends with *.smi 
4. They are uploaded and renamed correctly, but the extensions should not change

**Expected behavior**
Instead of `*.ko.srt` it should be `*.ko.smi`. SRT and SAMI (SMI) are different formats.

**Software (please complete the following information):**
 - Bazarr Version: 0.9.0.8
 - Sonarr Version: 3.0.4.1093 
 - Operating System: Linux-5.7.6-arch1-1-x86_64-with

SMI subtitles should be supported because it is the most popular format in Korea and popular media players such as mpv, vlc, or plex supports such extensions.

**Comment by morpheus65535** [comment]
It shouldn't be possible as the code underneath subtitles upload is only able to process .srt file. I've pushed a fix to prevent the upload of other kind of files. Thanks for reporting.
