### ISSUE TITLE
Update from disk task causes bazarr to become unresponsive and / or crashing.

### ISSUE THREAD

**Issue by HamilcarH** [morpheus65535/bazarr#1259]
**Describe the bug**

I've recently noticed that when this task is running, I can no longer access the GUI and subs no longer download.

**To Reproduce**

Update from disk is set to run weekly, running the task causes the issue

**Expected behavior**

Bazarr should still be available and downloading subs.

**Screenshots**

none available.

**Software (please complete the following information):**

 - Bazarr: 0.9.0.8
 - Radarr version 3.0.1.4259
 - Sonarr version 3.0.4.1096
 - OS: Bazarr is running in docker using LSIO container on Unraid

I think that's the relevant log:

https://pastebin.com/B3eDf90g

**Comment by halali** [comment]
Please upload your log to pastebin or gist. Thank you

**Comment by morpheus65535** [comment]
I would bet on Docker network configuration issue. Come back to Discord and provide docker-compose.

**Comment by HamilcarH** [comment]
Here is my docker compose: https://pastebin.com/VG1J0rQ9

**Comment by morpheus65535** [comment]
Fixed on Discord.
