### ISSUE TITLE
Bazarr scanning disk problem

### ISSUE THREAD

**Issue by WoisWoi** [morpheus65535/bazarr#1261]
**Describe the bug**
I have embed sub on this media (for example) :  
![image](https://user-images.githubusercontent.com/75491231/107122765-e703c100-6899-11eb-891b-1c1fc5d49d80.png)
![image](https://user-images.githubusercontent.com/75491231/107122774-f420b000-6899-11eb-80a9-187495e6af75.png)
Bazarr doesn't find them when I'm doing a scan.
[bazarr(1).log](https://github.com/morpheus65535/bazarr/files/5937104/bazarr.1.log)

**Software (please complete the following information):**
![image](https://user-images.githubusercontent.com/75491231/107122798-27fbd580-689a-11eb-99a7-d0cf0930f295.png)

**Comment by morpheus65535** [comment]
That's a support question. Keep investigating on Discord with support team. I would look into embedded options in Settings-->Subtitles.

**Comment by WoisWoi** [comment]
I forgot to send this screenshot 
![image](https://user-images.githubusercontent.com/75491231/107122985-59c16c00-689b-11eb-9e4e-08e655101b0b.png)

**Comment by morpheus65535** [comment]
Do a disk scan for this movie and they should appear. If not you have a path mapping issue or cloud access issue. There's no issue with disk indexing in Bazarr.
