### ISSUE TITLE
System>Providers shows opensubtitlescom instead of opensubtitles.com

### ISSUE THREAD

**Issue by Casvt** [morpheus65535/bazarr#1262]
**Describe the bug**
Very small and simple bug. It isn't even a bug, it's just a little mistake. In the System>Providers page, it says opensubtitlescom, instead of opensubtitles.com

**To Reproduce**
1. Have opensubtitles.com as a provider
2. Go to System>Providers
3. Look at the name

**Expected behavior**
opensubtitles.com instead of opensubtitlescom

**Screenshots**
Not needed. Its very clear what's wrong

**Software (please complete the following information):**
 - Bazarr: 0.9.1
 - OS: Ubuntu 20.04.1 LTS

**Additional context**
I don't have crashes. The provider works perfectly. It's just that you forgot the ".". That's all.

**Comment by morpheus65535** [comment]
We can't have non-alphabetical characters in provider names. That's normal behavior.
