### ISSUE TITLE
Name of language profile was changed to ['en'] (false/false) after upgrading to 0.9

### ISSUE THREAD

**Issue by Casvt** [morpheus65535/bazarr#1263]
**Describe the bug**
Before upgrading to 0.9, the name of my language profile was "en". After updating to 0.9, it was changed from "en" to "['en'] (false/false)".

**To Reproduce**
1. Have a Language Profile
2. Upgrade to 0.9
3. See that everywhere where the name of the language profile is showed, it says ['en'] (false/false). Where "en" the name of the language profile is.

**Expected behavior**
To show "en" instead of ['en'] (false/false)

**Screenshots**
![image](https://user-images.githubusercontent.com/76659058/107124644-6945b280-68a5-11eb-911b-8e4b39e6f40d.png)

**Software (please complete the following information):**
 - Bazarr: 0.9.1
 - Radarr version: 3.0.2.4552
 - Sonarr version: 3.0.4.1100
 - OS: Ubuntu 20.04.1 LTS

**Additional context**
After going to Settings>Languages>Languages Profiles and then editing the profile, I was able to change the name back to "en" and it show "en" after that change. The problem is more that after updating to 0.9(.1), it automatically changed the name of the profile.

**Comment by morpheus65535** [comment]
That's normal behavior during the upgrade process to v0.9.1. We've move from language to languages profile and have to create unique name in the process. As you've did, the rename profile is the way to go.
