### ISSUE TITLE
The filename format for Brazilian Portuguese is not compatible with Plex.

### ISSUE THREAD

**Issue by madpin** [morpheus65535/bazarr#1265]
**Describe the bug**
The Brazilian Portuguese is currently renamed to pt-BR, but unfortunately this is no compatible with Plex, that follows:
ISO-639-1 (2-letter) or ISO-639-2/B

**To Reproduce**
You can just download a subtitle in Brazilian Portuguese, that you'll see the filename, when you open it with Plex, it just ignores it.

**Expected behavior**
In those tables, there is not a Brazilian Portuguese, what I understand for most uses is important, so I'd suggest or to be able to overwrite the default filename apendix, or having a box to select compatibility with Plex, and any other that may encounter the same problem.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: v0.9.0.8 
 - Plex: Version 1.27.2.1599-7689068b

**Comment by halali** [comment]
I think this issue is more plex issue than bazarr.

**Comment by morpheus65535** [comment]
Works fine for me with Plex 1.21.3.4021. Looks like a regression on Plex ends. I suggest you open an issue with them.

![image](https://user-images.githubusercontent.com/5130500/107810800-3f740c00-6d3b-11eb-81e4-0c4eac78c8f8.png)


![image](https://user-images.githubusercontent.com/5130500/107810728-1f444d00-6d3b-11eb-99c7-259c30881452.png)

**Comment by halali** [comment]
You are probably using some test unreleased version of plex... I cant find this version.

**Comment by madpin** [comment]
Owww, yes, now it's working!
Probably it was loading yet.
And hey, thanks for the quick reply.
<3

**Comment by halali** [comment]
Ok you gave us plex client version not server
