### ISSUE TITLE
optimize identifying Traditional and Simplified Chinese subtitles

### ISSUE THREAD

**Issue by kkycble** [morpheus65535/bazarr#1267]
First off, I think there can be a better way to optimize the logic detecting traditional subtitles. 
![image](https://user-images.githubusercontent.com/21995214/107886110-b1657480-6f38-11eb-9e49-b48b1af2fe65.png)
The logic above may cause some traditional subtitles to be blocked from grabbing. If the word like .chs or 簡 is present, then it won't see the Traditional Chinese subtitles in the same release. 

![image](https://user-images.githubusercontent.com/21995214/107886204-55e7b680-6f39-11eb-82ad-8d6f0422250c.png)

The release page in zimuku
![image](https://user-images.githubusercontent.com/21995214/107886323-0b1a6e80-6f3a-11eb-8892-b5e3f104a4d9.png)

I think it shows that:

1.  some subtitles releases may not have every language code listed in their filenames. 
2.  whereas the title of the releases may fully specify all the subtitles languages they contain. 
3.  in cases like this, the presence of Simplified Chinese subtitles would effectively block Bazarr from grabbing the Traditional Chinese subtitles that are present in the same zip folder. 
4. maybe due to the fact that it grabs the first subtitles in the zip folder, it would potentially grab the multiple language subtitles (like in this case, Simplified Chinese + English), or the wrong language (like English), depends on the order of the subtitles files.

Also, Plex only recognize .zh/ .chi as Chinese subtitles but not .zt (unknown). So I suggest labelling Simplified Chinese subtitles .zh-hans and Traditional Chinese subtitles as .zh-hant, so that it remains clear that which is which and Plex would still see both as Chinese subtitles. 

Also, maybe add tools that allow translation between Simplified and Traditional Chinese, and remove a language in dual-language subtitles (like removing English in an English/ Traditional Chinese subtitles). 

Thank you for your time in making this wonderful application. Hopefully my post can be of some help to you guys. :)

**Comment by morpheus65535** [comment]
Although I appreciate the comment, I don't speak a single word of Chinese (whatever the declination) so I'm unable to appreciate or implement this. I'm open to PR fi you're willing to give it a try.

I add @zx900930 who's made the first PR so he can jump in.

**Comment by zx900930** [comment]
@kkycble The logic for extension detection is ok, the `zt` is only showing in bazzar and will not be the extension of your subtitles.
The current chinese traditional subtitles's extension are `*.zh-TW.srt` because `cht` is already taken by Cholón (Cholona) in ISO 639-2 (but I could make a rename after downloaded the subs).

The assrt website search function need a bit more works, too. I'll take a look next week(and maybe add another provider https://subhd.tv/).

The Plex subtitle recognition problem is a bug of plex, they shouldn't ignore any subtitles they can't identify (Their old version is working fine but they changed it). You should send a ticket to plex to address this problem. 

btw, I can add a switch for plex compatibility(simply rename the downloaded subs extension) as a temporary workaround.

If you have any questions please discuss this on discord my id is TriATK#9001.

**Comment by kkycble** [comment]
@zx900930 Yeah you are right. My bad to think that it would be named as .zt. I just tested with WandaVison and it successfully returned Traditional Chinese subtitles!!! The reason that my example (The Rookie) above didn't work was that zimuku.py didn't get updated!! I think once the Zimuku part of the code is updated, it can provide Traditional Chinese subtitles as well. 

I seem to understand that both Assrt and Zimuku are currently configured to prefer ass/ssa double language subtitles? Is it possible to make it Traditional/ Simplified Chinese only or as options in Bazarr's language profile? Also, wouldn't it be nicer to prefer native srt rather than ass/ssa? 

I'm sorry that I can't contribute much as I am pretty much a coding newbie. Thank you and @morpheus65535 for your time and efforts in this issue. I wish you all a happy Lunar New Year. 

祝大家農曆新年快樂

**Comment by zx900930** [comment]
little improvements, too many possible combinations can't add all of them:
![image](https://user-images.githubusercontent.com/734749/107894273-7b6fc280-6f2f-11eb-8403-c9473fb83291.png)

**Comment by morpheus65535** [comment]
Any other improvement to be made? May I close this issue?
