### ISSUE TITLE
deep_translator dependency not listed in libs/version.txt

### ISSUE THREAD

**Issue by mvanbaak** [morpheus65535/bazarr#1270]
**Describe the bug**
The file ```libs/version.txt``` lists all vendored dependencies.
Recently deep_translator was added as dependency, but it's not listed in the file.

The current vendored version of that library is '1.3.2'
This should be added to this file.

**Comment by mvanbaak** [comment]
Ok, maybe I should reword this issue as I see the version.txt file is simply out-of-date. More changes to the libs/ directory were not documented in this file (chardet, simpleconfig etc etc)

**Comment by morpheus65535** [comment]
Yes I agree that this file is quite outdated. In fact, I don't update it because I don't really use it. As it is a fully manual process, it could get time consuming.

**Comment by mvanbaak** [comment]
Ok, I went over all the files in the bazarr/ library (the actuall application) and tried to find all direct dependencies.

The dependencies used and listed in the version.txt file:
```
apprise=0.8.8
apscheduler=3.5.1
dogpile.cache=0.6.5
enzyme=0.4.1
ffsubsync=2020-08-04
Flask=1.1.1
gitpython=2.1.9
guess_language-spirit=0.5.3
guessit=3.1.1
knowit=0.3.0-dev
py-pretty=1
pycountry=18.2.23
pyga=2.6.1
rarfile=3.0
requests=2.18.4
SimpleConfigParser=0.1.0 <-- modified version: do not update!!!
subliminal=2.1.0dev
Waitress=1.4.3
```

Dependencies used but not listed:
```
bs4
charamel
dateutil
deep_translator
flask_debugtoolbar
flask_restful
flask_socketio
pysubs2
sqlite3worker
subliminal_patch
subzero
webrtcvad
whichcraft
```

Besides the SimpleConfigParser there's one package listed with 'local modifications' and that's the js2py. This is an indirect dependency with a local fix for python3. Upstream has merged that fix a year ago, so we can probably get an updated version without local changes.

The version numbers of the unlisted dependencies will be some work to get, but I'm willing to do that later this week.

With all that said and looked at, it looks like the only two dependencies we cannot simply grab with pip or another install method are the subliminal_patch and SimpleConfigParser.

My suggestion is to move those to a seperate directory called eg ```modified_libs```.
That way, we can make updating dependencies easier with ```PIP_TARGET=./libs pip ...``` and have a clear view of what libraries we are editing locally for changes that cannot or will not be upstreamed.

This would also make packaging the app for various systems a lot easier (I, for example, will simply remove the libs/ directory and use the packaging tooling of a linux distribution or FreeBSD portstree to handle those)

Ideas?

**Comment by mvanbaak** [comment]
Oh, I did not look at the other vendored libraries as they are all indirect dependencies and we should not list ad/or care about those as pip/pkg/apt etc will handle those. That's also why I didn't try to explain those in the current version.txt file. I only looked at the dependencies of the bazarr application.

**Comment by mvanbaak** [comment]
The SimpleConfigParser local changes are no longer in use. The changes only apply to python versions that dont have a ```configparser``` module (python2). From the python documentation:
```
 The ConfigParser module has been renamed to configparser in Python 3.
```

**Comment by mvanbaak** [comment]
sqlite3worker has been heavily modified, cant use upstream version. Should also be marked as 'local code' like the subliminal_patch etc

**Comment by mvanbaak** [comment]
Subzero is also a 'weird' one as there's no python package for it, and looking at the history of that directory there are a lot of local modifications.

Best to move this library to a 'local code' one as well

**Comment by mvanbaak** [comment]
@morpheus65535 Can you explain why lxml, numpy and webrtcvad are in the requirements.txt file, and not bundled?

**Comment by morpheus65535** [comment]
I suggest we move to Discord to have a chat about all of this. :-)

**Comment by morpheus65535** [comment]
As we are dealing with this on Discord, I'll close this issue.
