### ISSUE TITLE
Bazarr can not found subtitle a specific series on supersubtitles

### ISSUE THREAD

**Issue by vampywiz17** [morpheus65535/bazarr#1271]
**Describe the bug**
Bazarr can not found hungarian subtitle "WandaVision" series on Supersubtitles (feliratok.hu) provider.

**To Reproduce**
1. Download Wandavision episode
2. Try auto or manual subtitle search

**Expected behavior**
Found subtitle and download it.

**Software (please complete the following information):**
 - bazarr version v0.9.1
 - Sonarr version v3.0.4.1126
 - OS: Ubuntu Linux (Bazarr run in docker)

**Additional context**
Try to set the "Minimum Score" but it not help at all... If i try other series subtitles, it working well. (It possiblet that is a parse error?)

**Comment by morpheus65535** [comment]
I need a debug log while reproducing the issue. Thanks.

**Comment by vampywiz17** [comment]
@morpheus65535 

[bazarr.log](https://github.com/morpheus65535/bazarr/files/5984094/bazarr.log)

**Comment by morpheus65535** [comment]
Should be fixed in v0.9.1.1 in dev branch. Can you test it please?

**Comment by vampywiz17** [comment]
@morpheus65535 

It working, thanks!
