### ISSUE TITLE
Bazarr Detects That Subtitles Are Already Downloaded When They're Not

### ISSUE THREAD

**Issue by TomKatom** [morpheus65535/bazarr#1272]
**Describe the bug**
The bug is that Bazarr detects both for TV shows and movies that all subtitle files exist on disk and are downloaded when they're not there at all.
I tried googling for similar bugs but haven't found any.
This is really odd and kinda ruins the point of even having Bazarr for me.

**To Reproduce**
1. Download any show or movie from Sonarr or Radarr
2. Wait for Bazarr to recognize it
3. See that Bazarr shows that the subtitle file exists on disk and thus doesn't search/download the subtitles

**Expected behavior**
Bazarr detects a new episode or a movie, scans the show/movie's folder for subtitles, doesn't find such file and then searches for the subtitles and downloads the right subtitles.

**Screenshots**

- [Example Of TV Show](https://imgur.com/a/oq8g0uF) - What you can see in this image is the show in Bazarr which recognizes the episodes and path correctly but it shows that subtitles exist (which you cans see they don't in the screenshot of the directory)

- [Example Of Movie](https://imgur.com/a/rEkGipg) - What you can see in this image is the movie in Bazarr which recognizes everything correctly, the movie name and the path to the files but for some reason it detects subtitles that do not exist on disk (as you can see in the screenshot of the directory)

I want to make it clear that those are just examples, but this happens for all shows and movies I download.

**Software (please complete the following information):**
 - Bazarr: v0.9.1 
 - Radarr version 3.0.2.4369
 - Sonarr version 2.0.0.5344
 - OS: Ubuntu 18.04.5 LTS

**Additional context**
This is happening ever since I installed it, this might be a problem in the way I configured it but I looked at all the options and I didn't find anything that could be the cause of the issue.

**Comment by morpheus65535** [comment]
Dude... those subtitles are embedded inside the video container... if you want Bazarr to index those embedded subtitles, disable this option in Settings-->Subtitles. The wiki can probably help you with that kind of questions.

**Comment by TomKatom** [comment]
> Dude... those subtitles are embedded inside the video container... if you want Bazarr to index those embedded subtitles, disable this option in Settings-->Subtitles. The wiki can probably help you with that kind of questions.

Oh wow my bad, I'm sorry for wasting your time.
Yeah, I found it in the wiki and disabled it - thanks.

**Comment by morpheus65535** [comment]
Np, enjoy! :-)
