### ISSUE TITLE
New version keeps crashing 

### ISSUE THREAD

**Issue by Buster14** [morpheus65535/bazarr#1274]
**Describe the bug**
Ever since updating to 0.9.1 I keep getting "connection to the backend lost"  even after reload and restart service it would happen again

**Software (please complete the following information):**
Bazarr Version:0.9.1
Sonarr Version:3.0.4.1129
Radarr Version:3.0.2.4552
Operating System:Windows-10-10.0.17763-SP0
Python Version:3.8.0
Bazarr Directory:z:\programs\bazarr
Bazarr Config Directory:C:\ProgramData\Bazarr

The log is huge, so im uploading it to drive

https://drive.google.com/file/d/11nZXCzD3YWBZBrRjpvgFQghra1R2Q49J/view?usp=sharing

**Comment by morpheus65535** [comment]
Your log is full of `MemoryError`. You're probably out of memory.

**Comment by Buster14** [comment]
My machine has 128gb and it never goes above 50%, (i just checked again). I doubt its memory, i'm using it some other memory intensive apps like utorrent and it would've crashed if the machine run out of memory, but it hasnt crashed for a long time. Any changes from previous version that might cause this?

**Comment by morpheus65535** [comment]
This error come from Python Interpreter. There's nothing related to Bazarr code here. Regarding what's new in this version, you can check release notes.

**Comment by Buster14** [comment]
Hmm odd cause i didnt make any changes at all to my server, the python was always eating <1gb ram, but it never went past that, and it didnt cause crash like this version.. I'll try rolling back to previous version then...

**Comment by morpheus65535** [comment]
WinPython that is embedded in Windows Installer version of Bazarr is 32bits so it's limited to 2gb of RAM for the python process. It could be useful to investigate by installing from sources using a 64bits Python interpreter. Make sur to keep your config directory and use it with your new instance.

**Comment by Buster14** [comment]
Programs and Features> Uninstall  Python 32 bit

Then install the 64-bit version.

Would this be enough? I dont wanna break anything since i never play around with python

**Comment by morpheus65535** [comment]
That's unrelated. Take a look at the wiki and come see us on Discord for live support:

https://github.com/morpheus65535/bazarr/wiki/Installation#windows

**Comment by sum01** [comment]
I'm seeing this same issue on Linux (Ubuntu server v20 LTS).

Specifically, it only starts happening if I enable form authentication, set a password, then reboot.
If I leave off authentication everything is fine.
