### ISSUE TITLE
Discord apprise avatar_url and avatar construction gives no avatar and defaults to apprise avatar

### ISSUE THREAD

**Issue by jpdsceu** [morpheus65535/bazarr#1275]
**Describe the bug**
When adding the Discord Webhook integration, the avatar_url and avatar values aren't passed and therefore the default apprise avatar is used instead of the one set in the Webhook integration.

**To Reproduce**
1. Create a Discord notification
2. Add the Webhook URL
3. Click on Test
4. Check bot avatar, it is different than the one set in Discord

**Expected behavior**
Users should be able to set an own avatar through Bazarr or use avatar=No to let Discord sort out the avatar.
To do this, after the https://discord.com/api/webhooks/#/# it should state:

`?avatar=No # to let Discord handle it`

```
?avatar=Yes # enable avatar from custom URL
?avatar_url=URL # use avatar from inputted URL
```

**Screenshots**
![image](https://user-images.githubusercontent.com/7014736/108211021-85124980-712c-11eb-945d-560c554c590a.png)

**Software (please complete the following information):**
Bazarr Version: 0.9.1
Sonarr Version: 3.0.4.1129
Radarr Version: 3.1.0.4634

Reference issue I made on the apprise github: https://github.com/caronc/apprise/issues/362

**Comment by morpheus65535** [comment]
It was a configuration issue on your end as stated on Apprise issue. I'm closing this one.
