### ISSUE TITLE
erroneous language or hearing-impaired classification of subtitles

### ISSUE THREAD

**Issue by rmichelena** [morpheus65535/bazarr#1276]
it's happening to me on a couple of shows, it downloads the (correct) subtitle, and then it saves it correctly named, but into the database it records it with a different language or hearing-impaired classification

make an MKV show named "Stargate.SG1-s09e17.The.Scourge.mkv" with language profile "es" (not forced, not HI)
make another MKV show named "His Dark Materials - S02E07 - Æsahættr WEBRip-1080p.mkv" with language profile "es" (not forced, not HI)

it'll download Spanish subtitles for "Stargate.SG1-s09e17.The.Scourge.mkv" from podnapisi with a score of 95.28%.
it'll download Spanish subtitles for "His Dark Materials - S02E07 - Æsahættr WEBRip-1080p.mkv" from subdivx with a score of 95.28%

But it will enter the first as Chinese (zh), and it will enter the second as hearing-impaired 
So hours later, it'll again download the same subtitles. And so the cycle will go on, endlessly.

<img width="2021" alt="Screen Shot 2021-02-18 at 12 35 19" src="https://user-images.githubusercontent.com/77797875/108397326-d3cfea00-71e5-11eb-994b-e09d0c63ba29.png">

**Software
 - Bazarr: 0.9.1
 - Sonarr version 3.0.4.1126
 - OS: Ubuntu

**Additional context**
Series are pre-existing so no scene name available

**Comment by rmichelena** [comment]
LOGS:
case 1:

18/02/2021 19:11:49|DEBUG   |root                            |BAZARR started subtitles indexing for this file: /tv/Stargate SG1/Season 9/Stargate.SG1-s09e17.The.Scourge.mkv|
18/02/2021 19:11:49|DEBUG   |root                            |BAZARR is trying to index embedded subtitles.|
18/02/2021 19:11:49|DEBUG   |root                            |BAZARR returning this binary: /usr/bin/ffprobe|
18/02/2021 19:11:50|DEBUG   |root                            |BAZARR embedded subtitles detected: en|
18/02/2021 19:11:50|DEBUG   |subliminal_patch.core           |external subs: scanning path /tv/Stargate SG1/Season 9/Stargate.SG1-s09e17.The.Scourge.mkv|
18/02/2021 19:11:50|DEBUG   |subliminal_patch.core           |Found subtitles {'Stargate.SG1-s09e17.The.Scourge.es.srt': <Language [es]>}|
18/02/2021 19:11:50|DEBUG   |subliminal_patch.core           |external subs: found {'Stargate.SG1-s09e17.The.Scourge.es.srt': <Language [es]>}|
18/02/2021 19:11:50|DEBUG   |root                            |BAZARR external subtitles detected: zh|
18/02/2021 19:11:50|DEBUG   |root                            |BAZARR storing those languages to DB: [['en', None], ['zh', '/tv/Stargate SG1/Season 9/Stargate.SG1-s09e17.The.Scourge.es.srt']]|
18/02/2021 19:11:50|DEBUG   |root                            |BAZARR ended subtitles indexing for this file: /tv/Stargate SG1/Season 9/Stargate.SG1-s09e17.The.Scourge.mkv|


Case 2:
18/02/2021 19:16:31|DEBUG   |root                            |BAZARR started subtitles indexing for this file: /tv/His Dark Materials/Season 2/His Dark Materials - S02E07 - Æsahættr WEBRip-1080p.mkv|
18/02/2021 19:16:31|DEBUG   |root                            |BAZARR is trying to index embedded subtitles.|
18/02/2021 19:16:31|DEBUG   |root                            |BAZARR returning this binary: /usr/bin/ffprobe|
18/02/2021 19:16:34|DEBUG   |root                            |BAZARR embedded subtitles detected: en:hi|
18/02/2021 19:16:34|DEBUG   |subliminal_patch.core           |external subs: scanning path /tv/His Dark Materials/Season 2/His Dark Materials - S02E07 - Æsahættr WEBRip-1080p.mkv|
18/02/2021 19:16:34|DEBUG   |subliminal_patch.core           |Found subtitles {'His Dark Materials - S02E07 - Æsahættr WEBRip-1080p.es.srt': <Language [es]>}|
18/02/2021 19:16:34|DEBUG   |subliminal_patch.core           |external subs: found {'His Dark Materials - S02E07 - Æsahættr WEBRip-1080p.es.srt': <Language [es]>}|
18/02/2021 19:16:34|DEBUG   |root                            |BAZARR external subtitles detected: es:hi|
18/02/2021 19:16:34|DEBUG   |root                            |BAZARR storing those languages to DB: [['en:hi', None], ['es:hi', '/tv/His Dark Materials/Season 2/His Dark Materials - S02E07 - Æsahættr WEBRip-1080p.es.srt']]|
18/02/2021 19:16:34|DEBUG   |root                            |BAZARR ended subtitles indexing for this file: /tv/His Dark Materials/Season 2/His Dark Materials - S02E07 - Æsahættr WEBRip-1080p.mkv|

**Comment by morpheus65535** [comment]
Fix merged to 0.9.1.1 in dev branch. Please confirm if your issue is fixed.

**Comment by morpheus65535** [comment]
Fix now in master. If you still have the issue, reopen it.
