### ISSUE TITLE
erroneous classification of hearing-impaired

### ISSUE THREAD

**Issue by rmichelena** [morpheus65535/bazarr#1277]
A perfectly clean subtitle (Spanish) is being classified as hearing impaired after download.

subtitle attached.

It'll keep downloading the same subtitle again, saving it and naming it correctly, but then entering into the database as hearing-impaired. So now it considers it missing (as the profile asks for not-HI), and next cycle it'll download the same subtitle again. And cycle will continue endlessly.

**Software (please complete the following information):**
 - Bazarr: 0.9.1

**Additional context**
Subtitle attached.
[His Dark Materials - S02E07 - Æsahættr WEBRip-1080p.es.srt.txt](https://github.com/morpheus65535/bazarr/files/6004809/His.Dark.Materials.-.S02E07.-.AEsahaettr.WEBRip-1080p.es.srt.txt)

**Comment by morpheus65535** [comment]
Line 109: `(FINAL DE TEMPORADA)`

This line does match normal HI pattern. So the issue is with the subtitles content, not the indexing process.
