### ISSUE TITLE
Removing Hearing Impaired Tags between squared brackets

### ISSUE THREAD

**Issue by costaht** [morpheus65535/bazarr#1281]
**Describe the bug**
Bazzar does a great job removing Hearing Impaired tags from the subtitles, but I've found a case where it fails to remove the music notes from the subtitles.
When the music notes are in between squared brackets, Bazarr can't remove it.

**To Reproduce**
Import the content below and the first line will be removed, the other ones won't
```
1
00:00:12,772 --> 00:00:15,675
♪♪♪

2
00:03:09,148 --> 00:03:10,783
- Diablos!

3
00:03:13,753 --> 00:03:15,520
[♪♪♪]

4
00:04:24,090 --> 00:04:26,626
[♪♪♪]

5
00:05:08,768 --> 00:05:11,369
Falcon
Main, this is Bravo Team.

6
00:05:14,240 --> 00:05:17,375
Falcon Main, this is
Bravo Team. Do you copy?
```

**Expected behavior**
It's expected that the tags "[♪♪♪]" are removed

**Software (please complete the following information):**
 - Bazarr: 0.9.1.1
 - OS: Centos 8 Stream

**Comment by morpheus65535** [comment]
Can you confirm if my latest fix in dev branch correct that issue as expected? Thanks.

**Comment by costaht** [comment]
Yes, it did! Thank you!
