### ISSUE TITLE
Bazarr Downloads subtitles with a score below Minimum Score

### ISSUE THREAD

**Issue by cphmichael** [morpheus65535/bazarr#1282]
Bazarr Version: 0.9.1.1
Sonarr Version: 3.0.4.1130
Radarr Version: 3.1.0.4634
Operating System: Linux-4.19.107-Unraid-x86_64-with

- - - - -

I have set Settings > Sonarr > Options > Minimum Score = 94

![image](https://user-images.githubusercontent.com/45288008/108495887-a3ea1a80-72a9-11eb-9957-2ebacfc5865f.png)

Bazarr download subtitles for series with a score below 94%

![image](https://user-images.githubusercontent.com/45288008/108496404-460a0280-72aa-11eb-837c-c0a030a51d90.png)

[bazarr.log](https://github.com/morpheus65535/bazarr/files/6009472/bazarr.log)

**Comment by morpheus65535** [comment]
Please enable debug log and reproduce the issue.

**Comment by cphmichael** [comment]
Can I manually reproduce the issue - or do I have to wait for it to happens by itself?

I can see the debug log gets huge so I empty it from time to time.

Maybe it could be an idea to make a log rollover function.

**Comment by halali** [comment]
Just remove subtitles in screenshot and trigger automatic search for issued subtitle language

**Comment by cphmichael** [comment]
I emptied the log and did a subtitles search for Gang of London 1x9:

![Gangs of London 1x9](https://user-images.githubusercontent.com/45288008/108592022-03a8fa00-736c-11eb-91ee-7d54ca90e710.png)

![image](https://user-images.githubusercontent.com/45288008/108592046-2affc700-736c-11eb-838e-b3364c2c51eb.png)

![image](https://user-images.githubusercontent.com/45288008/108592074-5682b180-736c-11eb-8aed-8abddec7ea1c.png)

DEBUG log:

[bazarr.log](https://github.com/morpheus65535/bazarr/files/6014578/bazarr.log)

**Comment by halali** [comment]
Can you please provide log in pastebin?

**Comment by cphmichael** [comment]
DEBUG log:

https://pastebin.pl/view/84763d0c

**Comment by morpheus65535** [comment]
Score for episode is calculated over 360 points. 94% of 360 is 338,4. Once rounded to the unit to get an integer, you end up with a minimum score of 338 which is the score of this subtitles (93,89% once rounded). That's the expected behavior and is the drawback of using percents representation.

**Comment by cphmichael** [comment]
Thank you for your reply and explanation.
I will increase the Minimum Score to compensate for the calculation.
Regards,
Michael
