### ISSUE TITLE
BAZARR Post-processing : Nothing returned from command execution?

### ISSUE THREAD

**Issue by cphmichael** [morpheus65535/bazarr#1283]
Bazarr Version:
0.9.1.1
Sonarr Version:
3.0.4.1130
Radarr Version:
3.1.0.4634
Operating System:
Linux-4.19.107-Unraid-x86_64-with

- - - -

I am seeing a lot of "Nothing returned from command execution"

Is that an error or what does it mean?

![image](https://user-images.githubusercontent.com/45288008/108497671-1b20ae00-72ac-11eb-9083-f9f9f5307d7f.png)

[bazarr.log](https://github.com/morpheus65535/bazarr/files/6009549/bazarr.log)

**Comment by morpheus65535** [comment]
Depends of what's the output from your post processing command. If nothing is returned to stdout, you'll get this message in your log.
