### ISSUE TITLE
Strange part in Languages profile

### ISSUE THREAD

**Issue by vampywiz17** [morpheus65535/bazarr#1284]
**Describe the bug**
It found a (False/False) text in Languages Profile part of the series and movies list view.

**To Reproduce**
1. Go to Series orr movies list view.

**Expected behavior**
Only want to see Country code

**Screenshots**
![image](https://user-images.githubusercontent.com/14281430/108513454-ec620200-72c2-11eb-9f8e-e8917d280e48.png)

**Software (please complete the following information):**
 - Bazarr: 0.9.1.1 (Dev)

**Comment by morpheus65535** [comment]
Duplicate #1263
