### ISSUE TITLE
Cannot start bazarr on docker after upgrade to v0.9.1

### ISSUE THREAD

**Issue by eevlogiev** [morpheus65535/bazarr#1289]
**Describe the bug**
I am trying to start the Docker container once I pulled the latest bazarr docker image from linuxserver.io. Process is failing with the following error:

```
Current thread 0x75f79390 (most recent call first):                                                                                                                               
<no Python frame>                                                                                                                                                                 
Fatal Python error: pyinit_main: can't initialize time                                                                                                                            
Python runtime state: core initialized                                                                                                                                            
PermissionError: [Errno 1] Operation not permitted   
```

**To Reproduce**
On NAS QNAP TS-231P2, Pull latest Docker image from linuxserver.io - version 0.9.1 and try to start it.

**Expected behavior**
Normal process startup listening on port 6767.

**Screenshots**
<img width="802" alt="Screenshot 2021-02-22 at 4 07 48" src="https://user-images.githubusercontent.com/27862102/108648295-8c867980-74c3-11eb-9022-ed233e1abcc4.png">

**Software (please complete the following information):**
 - Bazarr: v 0.9.1
 - Docker 20.10.3 on linux, arm
 - QNAP TS-231P2
 - OS: Arm 32bit

**Additional context**

**Comment by morpheus65535** [comment]
Seems to be related to a permission issue but I can't say permission to what exactly. Could it be related to this issue?
https://github.com/linuxserver/docker-papermerge/issues/4

**Comment by eevlogiev** [comment]
@morpheus65535 ,
thanks for the quick feedback. I really don't know how this would be a permission issue as I am using same settings for the last 3 versions and this issue started happening since I upgraded to 0.9.1.

This is the permissions I have for the bazarr folder where /config is mapped to:
drwxrwxr-x    6 911      911           4096 Oct  9 02:36 bazarr/

I also tried to downgrade to docker version 0.9.0.8 but now I am seeing same error:
```
Current thread 0x75fef390 (most recent call first):                                                                                                                                  
<no Python frame>                                                                                                                                                                    
Fatal Python error: pyinit_main: can't initialize time                                                                                                                               
Python runtime state: core initialized                                                                                                                                               
PermissionError: [Errno 1] Operation not permitted  
```

Any clue how can I fix this?

Thanks!

**Comment by morpheus65535** [comment]
I would set PUID and PGID as stated in the documentation to match an existing user on your docker host (let's say 1000/1000). I would also run `sudo chown -R 1000:1000 bazarr && sudo chmod -R 775 bazarr`.

**Comment by morpheus65535** [comment]
BTW: https://docs.linuxserver.io/images/docker-bazarr#environment-variables-e

**Comment by gust42** [comment]
I have the same issue since upgrade to 0.9.1 on docker

**Comment by eevlogiev** [comment]
Ok, I downgraded to version v0.9.0.8-ls101 and it's back to normal. I don't think this is a permission issue as I was just fine before with the 911 user.

**Comment by morpheus65535** [comment]
More of an issue with LSIO image than with Bazarr itself. Let continue this on https://github.com/linuxserver/docker-bazarr/issues/54

**Comment by eevlogiev** [comment]
@morpheus65535 ,
I tried that already. Some similar Python error:
```
[services.d] done.                                                                                                                                                                   
Fatal Python error: pyinit_main: can't initialize time                                                                                                                               
Python runtime state: core initialized                                                                                                                                               
PermissionError: [Errno 1] Operation not permitted                                                                                                                                   
                                                                                                                                                                                     
Current thread 0x75fdf390 (most recent call first):                                                                                                                                  
<no Python frame>                                                                                                                                                                    
[cont-finish.d] executing container finish scripts...                                                                                                                                
[cont-finish.d] done.                                                                                                                                                                
[s6-finish] waiting for services.                                                                                                                                                    
[s6-finish] sending all processes the TERM signal.                                                                                                                                   
[s6-finish] sending all processes the KILL signal and exiting.     
```

**Comment by gust42** [comment]
https://docs.linuxserver.io/faq#libseccomp worked for me on RPI4

**Comment by eevlogiev** [comment]
The issue was fixed after upgrading QNAP Container Station to latest version 2.3.4.1698.

Thanks.
