### ISSUE TITLE
Subtitles use .lang.hi.srt instead of the plex supported .lang.sdh.srt or .lang.cc.srt.

### ISSUE THREAD

**Issue by dak180** [morpheus65535/bazarr#1290]
**Describe the bug**
Subtitles use .en.hi.srt instead of the plex supported .en.sdh.srt or .en.cc.srt; this causes the sub language to be misidentified in Plex.

**To Reproduce**
1. Download any HI sub
2. Check the reported lang in Plex.

**Expected behavior**
Since these are generally not closed captions the .lang.sdh.srt method should be prefered

**Screenshots**

**Software (please complete the following information):**
 - Bazarr Version: 0.9.1
 - Sonarr Version: 3.0.4.1011
 - Radarr Version: 0.2.0.1504
 - Operating System: FreeBSD-12.2-RELEASE-p3-amd64-64bit-ELF

**Additional context**
See the [plex article](https://support.plex.tv/articles/200471133-adding-local-subtitles-to-your-media/#toc-3) in the `Subtitles for the Deaf and Hard of Hearing` subsection.

**Comment by morpheus65535** [comment]
Following discussion with Plex team, .hi is also supported: https://forums.plex.tv/t/hi-cc-sdh-subtitles-naming-convention/627100/3

**Comment by dak180** [comment]
@morpheus65535 from what I can tell since it definitely does not show up as english it is not supported well enough to use.
![2021-02-22](https://user-images.githubusercontent.com/324812/108803178-0b34f280-7568-11eb-980f-56266e80b556.png)

**Comment by morpheus65535** [comment]
It's working fine with the new movie agent and should be the same pretty soon with the series agent:
![image](https://user-images.githubusercontent.com/5130500/108838479-b01ff180-75a1-11eb-8a55-c52b683ae507.png)

**Comment by morpheus65535** [comment]
Anything else I can help you on that matters?

**Comment by costaht** [comment]
> @morpheus65535 from what I can tell since it definitely does not show up as english it is not supported well enough to use.
> ![2021-02-22](https://user-images.githubusercontent.com/324812/108803178-0b34f280-7568-11eb-980f-56266e80b556.png)

I can confirm that on version 1.21.4.4079, `lang.sdh.srt` is recognized as a SDH subtitle .

Try this:
* Update Plex
* Click on the ellipsis next to your library name and upgrade to the new scanner. 
* Refresh metadata of that title

**Comment by morpheus65535** [comment]
My previous screenshot was taken using this exact same version with a library upgraded to the new movie agent. I don't know what's the issue with yours but `lang.hi.srt` is working perfectly fine for me. It looks more like a bug in Plex.

TBH, we're using `Hearing-impaired` everywhere in Bazarr and using `sdh` in subtitles filename won't be intuitive for most of the users. That's why we choose to use `hi` instead.

**Comment by costaht** [comment]
> My previous screenshot was taken using this exact same version with a library upgraded to the new movie agent. I don't know what's the issue with yours but `lang.hi.srt` is working perfectly fine for me. It looks more like a bug in Plex.
> 
> TBH, we're using `Hearing-impaired` everywhere in Bazarr and using `sdh` in subtitles filename won't be intuitive for most of the users. That's why we choose to use `hi` instead.

Sorry, I meant `lang.hi.srt` and my suggestion was to the person who opened the issue so they can get the same results

**Comment by morpheus65535** [comment]
The new Plex Series Agent (in beta) available in Plex Server 1.22.x is indexing `en.hi.srt` external subtitles as English SDH.

I'll close this issue as it's working as expected.
