### ISSUE TITLE
scenename: null , But other movies get the Scenename well ! [BUG]

### ISSUE THREAD

**Issue by CyberPoison** [morpheus65535/bazarr#1292]
**Describe the bug**
The Bazarr doesn't get SceneNames (Torrents or Original Name file)

**To Reproduce**
1. Create a new Radarr for UHD movies and them add some movies with DoVi or etc..
2. Add the Radarr API and URL:Port to Bazarr 
3.Monitor the movies downloaded from IPT or HD-T on Bazarr 
4. Check the Scenename on all movies you get.

**Expected behavior**
Grab the Scenename as the original file from rtorrent or bazarr etc... downloaded 

**Screenshots**

As you can see the scenename is not avalaible 
![image](https://user-images.githubusercontent.com/60718477/108845830-31957500-75de-11eb-988d-d40d9c420615.png)

But for some weird raisons the movies get grabbed. 

![image](https://user-images.githubusercontent.com/60718477/108845936-512c9d80-75de-11eb-9dc4-50be69a1d2ed.png)

**Software (please complete the following information):**
Bazarr Version:
0.9.1
Sonarr Version:
3.0.4.1131
Radarr Version:
3.1.0.4641
 - OS: Ubuntu but use Docker (Image linuxserver/bazarr:latest)

**Additional context**
Some movies i have marked failed the download not sure if this can help to troubleshot the issue but there is some additional screen shots.

What i have done on Radarr
1#
![image](https://user-images.githubusercontent.com/60718477/108846413-d0ba6c80-75de-11eb-83fb-69acf49b0af4.png)

2#
![image](https://user-images.githubusercontent.com/60718477/108846689-268f1480-75df-11eb-8987-fb7a78a7b06e.png)

What i get on scenename on bazarr
1#
![image](https://user-images.githubusercontent.com/60718477/108846521-f47db280-75de-11eb-8976-c54a8fdd162a.png)

2#
![image](https://user-images.githubusercontent.com/60718477/108846832-4cb4b480-75df-11eb-8533-bc6aafc8ecea.png)

But some others get the scenename well.

1#
![image](https://user-images.githubusercontent.com/60718477/108847066-8685bb00-75df-11eb-94a4-72b8587b7299.png)

on bazarr there is the scenename

![image](https://user-images.githubusercontent.com/60718477/108847765-64406d00-75e0-11eb-8089-3ae17d99d6d1.png)

If logs needed please request if needed from bazarr,radarr,sonarr and i will add in this bug report

**Comment by CyberPoison** [comment]
https://github.com/Radarr/Radarr/issues/5962
I also reported here on radarr but need to be reported on sonarr also

**Comment by bakerboy448** [comment]
Radarr side; those releases would not qualify as scene names https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/Parser/SceneChecker.cs

**Comment by morpheus65535** [comment]
You understand right that Scenename and History are completely different thing? We don't use Sonarr/Radarr history, we use the value they provide under `scenename` attribute. If they don't provide it, we can't use it.
