### ISSUE TITLE
Ajax Error when opening Movie View

### ISSUE THREAD

**Issue by pluusla** [morpheus65535/bazarr#1294]
**Describe the bug**
When opening the movie view I always get an Ajax error message regarding id=movies.

**To Reproduce**
1. Click on 'Movies' Section
2. See error

**Expected behavior**
No error message when the movie view is opened. Movie view can be opened

**Screenshots**
https://i.imgur.com/7FYBlKi.jpeg

**Software (please complete the following information):**
 - Bazarr: 0.9.1
 - Radarr version 3.0.2.4552
 - Sonarr version 3.0.4.1131
 - OS: Linux-4.19.0-0.bpo.9-amd64-x86_64-with

**Additional context**
I have also already completely deleted and reinstalled Bazarr. The error still occurs

Error from log:
`Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request    rv = self.dispatch_request()  File "/app/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request    return self.view_functions[rule.endpoint](**req.view_args)  File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper    resp = resource(*args, **kwargs)  File "/app/bazarr/bazarr/../libs/flask/views.py", line 89, in view    return self.dispatch_request(*args, **kwargs)  File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request    resp = meth(*args, **kwargs)  File "/app/bazarr/bazarr/api.py", line 60, in wrapper    return actual_method(*args, **kwargs)  File "/app/bazarr/bazarr/api.py", line 906, in get    item[languages] = str(get_desired_languages(item[profileId]))  File "/app/bazarr/bazarr/database.py", line 306, in get_desired_languages    if profileId == int(profile_id):ValueError: invalid literal for int() with base 10: en`

Here the full bazarr log:
https://gist.github.com/pluusla/616c93ce2d2d2979f09f7414510ee8e2

**Comment by morpheus65535** [comment]
Come see me on Discord and share you bazarr.db with me.

**Comment by morpheus65535** [comment]
Fixed by manual correction to DB. If it happen again, we'll investigate.
