### ISSUE TITLE
External subtitles incorrectly classified as Simplified/Traditional Chinese

### ISSUE THREAD

**Issue by fventiel** [morpheus65535/bazarr#1296]
**Describe the bug**
Bazarr keeps redownloading certain subtitle files. Once downloaded, instead of the actual language (English/Dutch), Bazarr reports the English/Dutch subtitle file as missing, and reports the existence of a Simplified Chinese or Traditional Chinese subtitle file. It seems the subtitle filename is being parsed incorrectly. After a few hours Bazarr downloads the same subtitle file again. Permissions are correct: Bazarr has read/write access to all applicable files and folders.

**To Reproduce**
Have a subtitle file with one of the following names:
`The Walking Dead.S09E14.Scars.en.srt` (reported as Simplified Chinese)
`Mr. Robot.S02E01-E02.eps2.0_unm4sk-pt1.tc + eps2.0_unm4sk-pt2.tc.nl.srt` (reported as Traditional Chinese)

**Expected behavior**
These subtitle files being classified as English and Dutch, respectively.

**Software:**
 - Bazarr: v0.9.1
 The issue does not occur under release v0.9.0.8.

**Comment by morpheus65535** [comment]
Confirmed as fixed in 0.9.1.1 currently in dev branch. Should be in master today.
