### ISSUE TITLE
Cannot upgrade to v0.9.1.1 on Windows.

### ISSUE THREAD

**Issue by AbeltjeNL** [morpheus65535/bazarr#1299]
**Describe the bug**
Cannot upgrade Bazarr from v0.9.1 to v0.9.1.1 on Windows. 
BAZARR JSON validation result failed & BAZARR Could not get releases from GitHub.

**To Reproduce**
1. Go to 'System'
2. Click on 'Logs'
3. Scroll down to 'Error'

**Expected behavior**
Didn't expect any update error. Would expect that Bazarr performed the update as normal.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: [v0.9.1]
 - Radarr version [3.1.0.4648]
 - Sonarr version [3.0.4.1132]
 - OS: [Windows Server 2019]

**Additional context**
26/02/2021 17:01:38|ERROR   |root                            |BAZARR JSON validation result failed|
26/02/2021 17:01:38|WARNING |root                            |BAZARR Could not get releases from GitHub.|
26/02/2021 17:02:29|ERROR   |root                            |BAZARR JSON validation result failed|
26/02/2021 17:02:29|WARNING |root                            |BAZARR Could not get releases from GitHub.|
26/02/2021 17:02:29|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:6767/|
26/02/2021 17:02:45|ERROR   |root                            |BAZARR JSON validation result failed|
26/02/2021 17:02:45|WARNING |root                            |BAZARR Could not get releases from GitHub.|
26/02/2021 17:05:43|ERROR   |root                            |BAZARR JSON validation result failed|
26/02/2021 17:05:43|WARNING |root                            |BAZARR Could not get releases from GitHub.|
26/02/2021 17:08:51|ERROR   |root                            |BAZARR JSON validation result failed|
26/02/2021 17:08:51|WARNING |root                            |BAZARR Could not get releases from GitHub.|
26/02/2021 17:08:53|ERROR   |root                            |BAZARR JSON validation result failed|
26/02/2021 17:08:53|WARNING |root                            |BAZARR Could not get releases from GitHub.|
26/02/2021 17:08:54|ERROR   |root                            |BAZARR JSON validation result failed|
26/02/2021 17:08:54|WARNING |root                            |BAZARR Could not get releases from GitHub.|
26/02/2021 17:08:55|ERROR   |root                            |BAZARR JSON validation result failed|
26/02/2021 17:08:55|WARNING |root                            |BAZARR Could not get releases from GitHub.|

**Comment by morpheus65535** [comment]
Please enable debug log and try to update.

**Comment by AbeltjeNL** [comment]
Thank you for the quick respons!!

26/02/2021 17:22:21|DEBUG   |root                            |Bazarr version: 0.9.1|
26/02/2021 17:22:21|DEBUG   |root                            |Bazarr branch: master|
26/02/2021 17:22:21|DEBUG   |root                            |Operating system: Windows-10-10.0.17763-SP0|
26/02/2021 17:22:21|DEBUG   |root                            |Python version: 3.8.0|
26/02/2021 17:22:21|INFO    |apscheduler.scheduler           |Added job "Update Series list from Sonarr" to job store "default"|
26/02/2021 17:22:21|INFO    |apscheduler.scheduler           |Added job "Sync episodes with Sonarr" to job store "default"|
26/02/2021 17:22:21|DEBUG   |apscheduler.scheduler           |Looking for jobs to run|
26/02/2021 17:22:21|INFO    |apscheduler.scheduler           |Added job "Update Movie list from Radarr" to job store "default"|
26/02/2021 17:22:21|DEBUG   |apscheduler.scheduler           |Next wakeup is due at 2021-02-26 20:22:21.195794+01:00 (in 10799.996090 seconds)|
26/02/2021 17:22:21|INFO    |apscheduler.scheduler           |Added job "Update all Episode Subtitles from disk" to job store "default"|
26/02/2021 17:22:21|DEBUG   |apscheduler.scheduler           |Looking for jobs to run|
26/02/2021 17:22:21|INFO    |apscheduler.scheduler           |Added job "Update all Movie Subtitles from disk" to job store "default"|
26/02/2021 17:22:21|DEBUG   |apscheduler.scheduler           |Next wakeup is due at 2021-02-26 20:22:21.195794+01:00 (in 10799.989250 seconds)|
26/02/2021 17:22:21|INFO    |apscheduler.scheduler           |Added job "Update Bazarr from release on Github" to job store "default"|
26/02/2021 17:22:21|DEBUG   |apscheduler.scheduler           |Looking for jobs to run|
26/02/2021 17:22:21|INFO    |apscheduler.scheduler           |Added job "Search for wanted Series Subtitles" to job store "default"|
26/02/2021 17:22:21|DEBUG   |apscheduler.scheduler           |Next wakeup is due at 2021-02-26 20:22:21.195794+01:00 (in 10799.985338 seconds)|
26/02/2021 17:22:21|INFO    |apscheduler.scheduler           |Added job "Search for wanted Movies Subtitles" to job store "default"|
26/02/2021 17:22:21|DEBUG   |apscheduler.scheduler           |Looking for jobs to run|
26/02/2021 17:22:21|INFO    |apscheduler.scheduler           |Added job "Upgrade previously downloaded Subtitles" to job store "default"|
26/02/2021 17:22:21|DEBUG   |apscheduler.scheduler           |Next wakeup is due at 2021-02-26 20:22:21.195794+01:00 (in 10799.981432 seconds)|
26/02/2021 17:22:21|DEBUG   |apscheduler.scheduler           |Looking for jobs to run|
26/02/2021 17:22:21|DEBUG   |apscheduler.scheduler           |Next wakeup is due at 2021-02-26 19:39:20.215340+01:00 (in 8218.996069 seconds)|
26/02/2021 17:22:24|INFO    |engineio.server                 |e9294839a2af4211895096dff42d179f: Received packet MESSAGE data 1|
26/02/2021 17:22:24|INFO    |engineio.server                 |e9294839a2af4211895096dff42d179f: Received packet CLOSE data None|
26/02/2021 17:22:25|INFO    |engineio.server                 |535cb82853774b209c3d1324a6970ba9: Sending packet OPEN data {'sid': '535cb82853774b209c3d1324a6970ba9', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}|
26/02/2021 17:22:25|INFO    |engineio.server                 |535cb82853774b209c3d1324a6970ba9: Sending packet MESSAGE data 0|
26/02/2021 17:22:30|DEBUG   |apscheduler.scheduler           |Looking for jobs to run|
26/02/2021 17:22:30|INFO    |socketio.server                 |emitting event "event" to all [/]|
26/02/2021 17:22:30|INFO    |engineio.server                 |535cb82853774b209c3d1324a6970ba9: Sending packet MESSAGE data 2["event","{\"type\": \"task\", \"action\": null, \"series\": null, \"episode\": null, \"movie\": null, \"task\": \"update_bazarr\"}"]|
**26/02/2021 17:22:30|INFO    |apscheduler.executors.default   |Running job "Update Bazarr from release on Github (trigger: interval[6:00:00], next run at: 2021-02-26 23:22:30 CET)" (scheduled at 2021-02-26 17:22:30.869446+01:00)|
26/02/2021 17:22:30|DEBUG   |apscheduler.scheduler           |Next wakeup is due at 2021-02-26 19:39:20.215340+01:00 (in 8209.343941 seconds)|
26/02/2021 17:22:30|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): api.github.com:443|
26/02/2021 17:22:30|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on api.github.com|
26/02/2021 17:22:31|DEBUG   |urllib3.connectionpool          |https://api.github.com:443 "GET /repos/morpheus65535/Bazarr/releases HTTP/1.1" 200 8613|
26/02/2021 17:22:31|DEBUG   |root                            |BAZARR Requesting URL via GET method: https://api.github.com/repos/morpheus65535/bazarr/releases/latest|
26/02/2021 17:22:31|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): api.github.com:443|
26/02/2021 17:22:31|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on api.github.com|
26/02/2021 17:22:31|DEBUG   |urllib3.connectionpool          |https://api.github.com:443 "GET /repos/morpheus65535/bazarr/releases/latest HTTP/1.1" 200 802|
26/02/2021 17:22:31|ERROR   |root                            |BAZARR JSON validation result failed|
26/02/2021 17:22:31|WARNING |root                            |BAZARR Could not get releases from GitHub.|
26/02/2021 17:22:31|INFO    |apscheduler.executors.default   |Job "Update Bazarr from release on Github (trigger: interval[6:00:00], next run at: 2021-02-26 23:22:30 CET)" executed successfully|
26/02/2021 17:22:31|INFO    |socketio.server                 |emitting event "event" to all [/]|
26/02/2021 17:22:31|INFO    |engineio.server                 |535cb82853774b209c3d1324a6970ba9: Sending packet MESSAGE data 2["event","{\"type\": \"task\", \"action\": null, \"series\": null, \"episode\": null, \"movie\": null, \"task\": \"update_bazarr\"}"]|
26/02/2021 17:22:33|INFO    |engineio.server                 |535cb82853774b209c3d1324a6970ba9: Received packet MESSAGE data 1|
26/02/2021 17:22:33|INFO    |engineio.server                 |535cb82853774b209c3d1324a6970ba9: Received packet CLOSE data None|
26/02/2021 17:22:34|INFO    |engineio.server                 |72ef44fa6dbe4f418847ca75ead7277f: Sending packet OPEN data {'sid': '72ef44fa6dbe4f418847ca75ead7277f', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}|
26/02/2021 17:22:34|INFO    |engineio.server                 |72ef44fa6dbe4f418847ca75ead7277f: Sending packet MESSAGE data 0|
26/02/2021 17:22:43|INFO    |engineio.server                 |72ef44fa6dbe4f418847ca75ead7277f: Received packet MESSAGE data 1|
26/02/2021 17:22:43|INFO    |engineio.server                 |72ef44fa6dbe4f418847ca75ead7277f: Received packet CLOSE data None|**

**Comment by morpheus65535** [comment]
Please try to delete this file: `%programdata%\Bazarr\config\releases.txt` and try to update again.

**Comment by AbeltjeNL** [comment]
Just tried deleting the file you mentioned and tried to update. Same result with same errors. 
Tried to delete the file, restart the Bazarr service and update once more. Same result with same errors.

**Comment by morpheus65535** [comment]
I guess I've broken the update process for those that have used the Windows installer version of Bazarr. 👎 

I've created a new installer that is now available to download on www.bazarr.media. You can uninstall your version and install the new one and you should be up and running in no time without loosing anything.

**Comment by AbeltjeNL** [comment]
> I guess I've broken the update process for those that have used the Windows installer version of Bazarr. 👎 
> 
> 
> 
> I've created a new installer that is now available to download on www.bazarr.media. You can uninstall your version and install the new one and you should be up and running in no time without loosing anything.

Now it's realy, realy broken.. Uninstalled my version and installed the new version you mentioned. Service is started but no GUI available (waited 10 minutes).

**Comment by AbeltjeNL** [comment]
Tried to uninstall and save/copy/delete my current config and database to start with a fresh copy of Bazarr to import settings (config/DB later). Also with a fresh copy the log file is created with just one line:
'26/02/2021 18:43:51|INFO    |root                            |BAZARR Database created successfully|'

**Comment by morpheus65535** [comment]
I've just added a new installer version. It's working for me but please try it and confirm.

**Comment by hnorgaar** [comment]
Worked fine for service option, but not for py. Comes up empty even I have backed up my db and config and replace them

**Comment by morpheus65535** [comment]
Should be working. Make sure you restored your backup at the same place you took it and restart Bazarr.

**Comment by hnorgaar** [comment]
I have done that, it replaces my ini with a fresh one. I started the app by service first, all came up, disabled and stopped the service and started with py. Empty

**Comment by hnorgaar** [comment]
Actually it is wrong, the ini is correct, but bazarr dont read it correct

**Comment by morpheus65535** [comment]
I don't understand what you mean with "py"?

**Comment by hnorgaar** [comment]
Python

**Comment by morpheus65535** [comment]
you're trying to start bazarr.py directly from the command line? If so you need to specify the config directory: `--config %programdata%\Bazarr`.

**Comment by hnorgaar** [comment]
Ok, that might work but I didnt need that 3 hours ago, just clicked on bazarr.py in C://bazarr

**Comment by hnorgaar** [comment]
And no not from CMD, just clicked the bazarr.py in C://bazarr

**Comment by morpheus65535** [comment]
Ok you're mixing up stuff. If you installed with installer, don't try to run it from command line. There's too much arguments required that are configured by the installer.

I have multiple confirmation on Discord that the latest installer is working as expected.

**Comment by hnorgaar** [comment]
Right, but thats the only way to get mapped network drives to work, and it worked just fine that way 3 hours ago. I will do an uninstall and try another way

**Comment by hnorgaar** [comment]
Ok, back in business again. I missed 1 step as the data files is placed different places for the working options. With pythom, they are inside the bazarr library. Thx for your good work, this is an excellent app for us movie fans

**Comment by hnorgaar** [comment]
However as I could use the same data files before, I think the data files have switched place for the python option in this version, just my 2 cents. Now they are in C:\Bazarr\bazarr\data

**Comment by AbeltjeNL** [comment]
Allright, I'm back in business again. The only thing I can't get to work is running the Bazarr service as my administrator account. It will run perfectly under my local account..

**Comment by morpheus65535** [comment]
Check the wiki, it's pretty well documented. Come to Discord if you need help. Thanks for testing!
