### ISSUE TITLE
Superman & Lois - not found in Supersubtitles provider

### ISSUE THREAD

**Issue by vampywiz17** [morpheus65535/bazarr#1300]
I use latest stable version of Bazarr. Try to download Superman & Lois subtitle, but bazarr can not found it. 

it similar problem with this: https://github.com/morpheus65535/bazarr/issues/1271

I attach the log.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/6055858/bazarr.log)

![image](https://user-images.githubusercontent.com/14281430/109402941-42394880-795a-11eb-96e9-0b4bc6f8be66.png)

**Comment by morpheus65535** [comment]
Should be fixed in v0.9.3-beta.0. Can you confirm?

**Comment by vampywiz17** [comment]
@morpheus65535 It working!
