### ISSUE TITLE
Provider "legendas.tv" (status Good) issue finding multiple releases

### ISSUE THREAD

**Issue by v9999** [morpheus65535/bazarr#1303]
Hey there, I use the legendas.tv provider and it it set as good on Bazarr status.
However, most of the manual and automatic searches don't work, Bazarr most of the times retrieves nothing from the provider.

I've confirmed that the subtitles for the releases are available in the provider.

From the log, I think it has to do with this HTTP 302 message, but I'm not sure, since sometimes the provider works under some very limited circunstances.

Here's the full log of a few searches:
https://pastebin.com/CnrntCi3

I'm running RaspberryPi with Ubuntu and using Bazarr with Docker

Bazarr Version:
0.9.1
Sonarr Version:
3.0.4.1130
Radarr Version:
3.0.2.4552
Operating System:
Linux-5.4.0-1028-raspi-aarch64-with
Python Version:
3.8.7

**Comment by morpheus65535** [comment]
Please update to latest version (0.9.2) and confirm if this issue s fixed. We've improved this provider in 0.9.1 and it's working perfectly fine from my dev instance but also from my Hotio's Docker container.

**Comment by v9999** [comment]
> Please update to latest version (0.9.2) and confirm if this issue s fixed. We've improved this provider in 0.9.1 and it's working perfectly fine from my dev instance but also from my Hotio's Docker container.

Hello, thanks for answering. I just updated the docker image, enabled debug and ran three tests, searching manually for subtitles for two series and a movie (all of them have subtitles in the provider).

Bazarr only listed subtitles for the movie, and reported zero results for the series.

Here's the log: https://pastebin.com/TBbq0fe2

The log shows that Bazarr is parsing the info on the episodes perfectly, but is not getting any data from the provider:
`03/03/2021 09:06:56|INFO    |subliminal_patch.core           |Initializing provider legendastv|
03/03/2021 09:06:56|INFO    |subliminal.providers.legendastv |Logging in|
03/03/2021 09:06:56|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): legendas.tv:80|
03/03/2021 09:06:56|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on legendas.tv|
03/03/2021 09:06:57|DEBUG   |urllib3.connectionpool          |http://legendas.tv:80 "POST /login HTTP/1.1" 302 20|
03/03/2021 09:06:57|DEBUG   |chardet.universaldetector       |no data received!|
03/03/2021 09:06:57|DEBUG   |chardet.universaldetector       |no probers hit minimum threshold|
03/03/2021 09:06:57|DEBUG   |chardet.universaldetector       |no data received!|
03/03/2021 09:06:57|DEBUG   |chardet.universaldetector       |no probers hit minimum threshold|
03/03/2021 09:06:57|DEBUG   |subliminal.providers.legendastv |Logged in|`

The subtitle in the provider looks like this in a regular search: Young.Sheldon.S04E06.WEBRip.x264-ION10-SYNCOPY-GGEZ-GGEZ-TOMMY-TOMMY

Looking at the log for the subtitle search for the movie, we can see that, at first, the same behaviour occurs "|no data received!|", but it immediately searches for the title id and is able to find the subtitles for the movie.

Whereas in the series, it looks like it tries to search for an alias in spanish:
`|subliminal_patch.providers.legendastv|Searching episode title 'el joven sheldon' for season 4|`

Let me know if I can provide something else.
Thanks!

**Comment by morpheus65535** [comment]
Should be fixed in v0.9.3-beta.3. Can you test it please?

**Comment by v9999** [comment]
> Should be fixed in v0.9.3-beta.3. Can you test it please?

I pulled and recreated the docker image: "image: hotio/bazarr:testing-0.9.3-beta.3"

I couldn't find subtitles for three episodes I manually searched on bazarr for (Young Sheldon S04E06 and S04E07 [TOMMY], American Gods S03E06 [GLHF]).
On the provider website, these are the entries I can find manually while searching for the episodes:

1) Young.Sheldon.S04E06.WEBRip.x264-ION10-SYNCOPY-GGEZ-GGEZ-TOMMY-TOMMY
2) Young.Sheldon.S04E07.720p.WEB.H264-GGEZ-GGEZ-SYNCOPY-aFi-ION10-TOMMY-TOMMY
3) American.Gods.S03E06.WEBRip.x264-ION10-PHOENiX-GLHF-NTG-NTb-iKA-PSA-Vyndros-Joy-worldmkv-Mobile-AFG-mSD-MiNX-MeGusta-RMX-RMTeam

Here's my debug log:
https://pastebin.com/MPmC2i9u

I don't know if this helps, but I've always noticed that this provider's search is a bit problematic. For instance, if I search for "Young.Sheldon.S04E06" in the search box, I get nothing. However, if I search for "Young Sheldon S04E06", the first result is the one I'm looking for.

**Comment by morpheus65535** [comment]
Sorry I forgot to mention you have to empty the config/cache directory first. Young Sheldon is working fine for me.

**Comment by v9999** [comment]
> Sorry I forgot to mention you have to empty the config/cache directory first. Young Sheldon is working fine for me.

I stopped the container with docker-compose stop, deleted the cache folder and started the container. It didn't work for me.
I'll delete everything and start from scratch to make sure every config is correct. Which container image should I use?

**Comment by morpheus65535** [comment]
I've just tested it again: emptied cache directory (without even stopping Bazarr), searched for pt-BR subtitles using v0.9.3-beta.4 with hotio/bazarr:nightly:

![image](https://user-images.githubusercontent.com/5130500/110022424-e7a54100-7cf9-11eb-8d75-cf97a2da0456.png)

**Comment by v9999** [comment]
> I've just tested it again: emptied cache directory (without even stopping Bazarr), searched for pt-BR subtitles using v0.9.3-beta.4 with hotio/bazarr:nightly:
> 
> ![image](https://user-images.githubusercontent.com/5130500/110022424-e7a54100-7cf9-11eb-8d75-cf97a2da0456.png)

Hey there, morpheus, thanks for the attention on this case. I tried beta 4 and deleting the cache folder and went through all the configs, but it didn't work.
I deleted everything and started from scratch. **Now it works!** Same settings, same logins, same connection to Sonarr etc. 
I guess that's it! Thanks again for the hard work! :)

**Comment by morpheus65535** [comment]
Thanks for the feedback! I appreciate that you got it working, enjoy it! :-)
