### ISSUE TITLE
Logger PublicIPFilter is changing the path to files in save_subtitles

### ISSUE THREAD

**Issue by nightime7** [morpheus65535/bazarr#1304]
Getting a but when attempting to download subtitles where the open(filename,"wb") command fails due to invalid argument.

observing the code I'm seeing the ip is getting masked by asterix in the actual code and not just in the log:

"//192.***.***.***.."

I've commented out line 71 in logger.py fh.addFilter(PublicIPFilter()) and the issue was solved so for some reason this is being applied to the video.original_path and causing errors. 

Also, interestingly, when I tried to comment out the line it wouldn't let me access they file until I closed pycharm completely and edited the file as admin in notepad++...

**Comment by morpheus65535** [comment]
Ok I can confirm the issue that only happen if you're in debug logging. I'm not able to debug it right now as I don't have a Windows machine with pycharm. Any chance you can find where the file path get corrupted?

**Comment by morpheus65535** [comment]
Should be fixed by my latest commit in v0.9.3-beta.6. Can you test it and confirm please?

**Comment by morpheus65535** [comment]
No news, good news. I'll close this issue. Feel free to re-open it if you still have it.
