### ISSUE TITLE
Table view for movies broken

### ISSUE THREAD

**Issue by anonyme123** [morpheus65535/bazarr#1309]
**Describe the bug**
Can't view the list of movies in Bazarr with an alert saying:
DataTables warning: table id=movies - Ajax error. 
For more information about this error, please see http://datatables.net/tn/7

**To Reproduce**
1. Go to .../bazarr/movies

**Expected behavior**
See the list of movies

**Screenshots**
<img width="1071" alt="Screen Shot 2021-03-05 at 21 46 18" src="https://user-images.githubusercontent.com/19681420/110171648-536fd280-7dfc-11eb-8c36-421fbfe5cf72.png">

**Software (please complete the following information):**
 - Bazarr: 0.9.2
 - Radarr version 3.0.2.4552
 - Sonarr version 3.0.4.1132
 - OS: Debian 9.12 in a Docker instance
 
**Additional context**
Log says:

Message
Exception on /bazarr/api/movies [GET]

Exception
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
  rv = self.dispatch_request()
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper
  resp = resource(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask/views.py", line 89, in view
  return self.dispatch_request(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request
  resp = meth(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 60, in wrapper
  return actual_method(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 948, in get
  item[\subtitles\] = sorted(item[\subtitles\], key=itemgetter(
ame\, \forced\))
TypeError: \<\ not supported between instances of \str\ and \NoneType\

**Comment by morpheus65535** [comment]
Force the task to index subtitles from disk for movies and it should fix itself. Please confirm.

**Comment by anonyme123** [comment]
Indeed it resolved the issue.

**Comment by anonyme123** [comment]
Hang on you should still fix the root cause lol ^^'

**Comment by morpheus65535** [comment]
The root cause is unknown and TBH I have no idea how to replicate it. During the previous scan, one movie got a subtitles indexed as None. Without having your setup and know how to reproduce the issue, there's not more I can do.
