### ISSUE TITLE
Search buttons hidden

### ISSUE THREAD

**Issue by AliMickey** [morpheus65535/bazarr#1310]
**Describe the bug**
The Search and Upload buttons are missing when i select movie from the list

**To Reproduce**
1. Fresh install of bazarr
2. add radarr/sonarr connection
3. try hitting search on any movie/episode, the buttons disappear. 

**Expected behavior**
Buttons should not disappear. 

**Screenshots**
![image](https://user-images.githubusercontent.com/60691199/110476690-5d643f00-8136-11eb-9139-3ca1392b2129.png)

**Software (please complete the following information):**
- Bazarr (Latest 0.9.2)

**Additional context**
If i inspect element an adjacent button such as scan disk, i can see the buttons (shown below) and i remove the style=none code i can click the button. It then shows a different error also attached below.

![image](https://user-images.githubusercontent.com/60691199/110476713-65bc7a00-8136-11eb-8cb4-92b05719bfe8.png)
![image](https://user-images.githubusercontent.com/60691199/110476734-6ce38800-8136-11eb-89f2-b2646db439cc.png)

Log upon clicking manual search after un-hiding it.
![image](https://user-images.githubusercontent.com/60691199/110476767-7967e080-8136-11eb-935a-1fcad7fb5a8d.png)

**Comment by morpheus65535** [comment]
Did you at least choose a desired languages profile for this movie?

**Comment by AliMickey** [comment]
hmm so i had this in settings already.

however i tried what you said and manually set a language profile and then search worked. 

i then removed radarr and ran the movie list task. 

re-added radarr and ran the task again.

however they still do not automatically get assigned the language profile.

![image](https://user-images.githubusercontent.com/60691199/110557101-fc6b5400-8193-11eb-9267-1c6a72ca1063.png)

**Comment by morpheus65535** [comment]
Future movies and series will inherit from Settings-->Languages-->Defaults.
