### ISSUE TITLE
Datatables warning and OSError - Subtitles not found

### ISSUE THREAD

**Issue by v9999** [morpheus65535/bazarr#1313]
Hello,
I'm using the lasted development version on docker and I'm having two issues (maybe correlated) while manually searching subtitles for an episode on legendas.tv.

The first one is a prompt in the browser that says something about datatables, here it is: https://imgur.com/Utb965Z

And the second one also happens when manually searching on legendas.tv provider. Bazarr doesn't find the releases and also reports an OSError on the provider. Sometimes this happens almost instantly.

Here's the log: https://pastebin.com/rAaJqe6J

Let me know if I can provide more info.

**Comment by morpheus65535** [comment]
For your DB, send me your bazarr.db in private on Discord and I'll look into it.

For the OSError:
`OSError: [Errno 36] Filename too long: `'/config/cache/7375626c696d696e616c5f70617463682e70726f7669646572732e6c6567656e64617374763a7365617263685f7469746c65737c5b275468652053696d70736f6e73272c20274469652053696d70736f6e73272c20274c65732053696d70736f6e272c20274c6f732053696d70736f6e272c20274c6f732053696d70736f6e73272c20275468652053696d70736f6e73205143275d203332204e6f6e6520747430303936363937'`

Your OS doesn't seems to support long file name for an unknown reason. Maybe some kind of encryption layer or something else getting in the way. I've never seen this one before.

**Comment by morpheus65535** [comment]
Maybe related to: https://stackoverflow.com/questions/34503540/why-does-python-give-oserror-errno-36-file-name-too-long-for-filename-short

**Comment by morpheus65535** [comment]
I would open an issue with your docker image provider and refer to this one.

**Comment by morpheus65535** [comment]
Just looked again to your screenshot and datatables issue is related to the exception thrown by manual search. Fixing the long filename issue will solve this one also.

**Comment by v9999** [comment]
Yes, looks related to the filename created on the cache folder, bigger than 255 characters that EXT4 allows.
I tried manually creating a file with the same name in multiple places of the system, but linux wouldn't allow.
So the path itself is not a problem.

**Comment by mvanbaak** [comment]
I got the same error about the cache filename being too long. My system is FreeBSD 12.2 with ZFS as filesystem.
I dont think a lot of filesystems out there support filenames of over 250 characters.

**Comment by morpheus65535** [comment]
I've just merged it. Can you confirm if it fix your issue?

**Comment by v9999** [comment]
> I've just merged it. Can you confirm if it fix your issue?

Hello, on hotio/bazarr:testing-0.9.3-beta.10 I get a new error searching for the same Simpsons episode: "AttributeError", which deactivates the provider for a while.

Here's the log: https://pastebin.com/5WF9cTB4

The cache folder remains empty during this manual search.

**Comment by morpheus65535** [comment]
@mvanbaak you have a moment to check this out?

**Comment by mvanbaak** [comment]
https://github.com/morpheus65535/bazarr/pull/1316/files

If that does not fix it, back to the drawing board...

**Comment by morpheus65535** [comment]
I've merged it. Let see if it works :-)

Thanks!

**Comment by v9999** [comment]
> I've merged it. Let see if it works :-)
> 
> Thanks!

The issue that shows up now is TypeError, here's the log:

https://pastebin.com/0q9LSKxP

It's not in the logs, but I tried searching for "The Good Doctor - S04E11 WEBDL-1080p STRONTiUM" after reseting the providers and had the same error come up.

Thanks!

**Comment by morpheus65535** [comment]
@mvanbaak anything we can fix here?

**Comment by mvanbaak** [comment]
Sorry for all the errors before.

Can you test the latest beta? 0.9.3-beta.13

Thanks

**Comment by v9999** [comment]
> Sorry for all the errors before.
> 
> Can you test the latest beta? 0.9.3-beta.13
> 
> Thanks

It worked!

Here's a log, in case you guys still want to dwelve into something: https://pastebin.com/QMDnWKCs

Thanks again!
