### ISSUE TITLE
Unable to select both forced and HI types in language profile

### ISSUE THREAD

**Issue by tctx79** [morpheus65535/bazarr#1321]
When I set up my language profile, with shows a true/false dropdown for both HI and forced.  If I enable both as TRUE, only the forced option shows up.  I am able to make two different profiles for the same language, and enable one each on each profile, but that doesn't allow me to have Bazarr search for both types.

**To Reproduce**
1. Go to Settings -. Languages
2. Click on Languages Profiles, add, create a new profile, enable both options as true, save

**Expected behavior**
In prvious instances of Bazarr I have used I was able to create a profile that searched for both forced AND HI on Movies and TV shows.  The instructions online show a screenshot of something like this, but it does not match what I see when I go to my options page.

**Screenshots**
My options:

![image](https://user-images.githubusercontent.com/16073076/111187915-7fb8eb00-8582-11eb-9952-34a7b6128c02.png)

Showing only the forced option enabled:

![image](https://user-images.githubusercontent.com/16073076/111188045-9eb77d00-8582-11eb-93dc-1fdfdacd2d48.png)

The WIKI page for setup shows a different version of BAZARR:

![image](https://user-images.githubusercontent.com/16073076/111188236-d8888380-8582-11eb-9798-14ef042ae3f2.png)

![image](https://user-images.githubusercontent.com/16073076/111188282-e5a57280-8582-11eb-8dfb-3eb200224e9d.png)

**Software (please complete the following information):**
 - Bazarr: 0.9.2 (ghcr.io/linuxserver/bazarr)
 - Radarr version 3.1.0.4700 (Using SMA branch from https://hub.docker.com/r/mdhiggins**/radarr-sma)**
 - Sonarr version 3.0.4.1139 (Using SMA branch from https://hub.docker.com/r/mdhiggins**/sonarr-sma)**
 - OS: Windows 10 running Bazarr in Docker 3.2.2 (61853) in WSL mode

**Additional context**
Sonarr/Radarr seem to be running fine.  I know these are not the main branches but I'm utilizing the media automation packaged with these builds and all of that is working.

**Comment by morpheus65535** [comment]
That's a config issue. Come to Discord if you need help in configuration. Hint: add English:HI and English:Forced in the same profiles but as 2 languages.

**Comment by tctx79** [comment]
> That's a config issue. Come to Discord if you need help in configuration. Hint: add English:HI and English:Forced in the same profiles but as 2 languages.

Got it.  My apologies, this is just different than I was used to, and I noted that the online instructions didn't match.  I have updated per your suggestion.

**Comment by morpheus65535** [comment]
Yes we still need to update this part of the wiki. Thanks for the reminder ;-)
