### ISSUE TITLE
 Bazarr does not auto downloading subtitles

### ISSUE THREAD

**Issue by phanosp** [morpheus65535/bazarr#1325]
Hi bazzar does not automatically download subtitles. I have read the post 

https://github.com/morpheus65535/bazarr/issues/440

but I already have 777 permissions on all folders including the root folder starting from /

The only difference that I have is that I use nfs mount for the Series but both on nfs server and nfs client (bazzar) the permissions are set to 777. Could this be a bug? I can download manually the subtitles, the problem is only with automatically downloading subtitles. 

Thanks

**Comment by morpheus65535** [comment]
Can be multiple thing but, without any information on what version you use and other stuff that would have been included if you didn't strip out the issue template, it would have been easier. Also, I will need a debug log reproducing the issue.

**Comment by phanosp** [comment]
Hi I am uploading the bazzar log file. 
[bazarr.log](https://github.com/morpheus65535/bazarr/files/6170515/bazarr.log)

My version is v0.9.3-beta.14 — 2021-03-15Development

What else do you need to troubleshoot this?

**Comment by morpheus65535** [comment]
Start by fixing your connection issue to Sonarr and disable bsplayer which is probably causing more trouble than goods. Let it run for a day and provide a new debug log.

**Comment by phanosp** [comment]
Hi,

I disable bsplayer and change the localhost ip for connecting to sonnar. For some reason 127.0.0.1:8989 does not work although the test button says that everything was ok. I will wait for a day and get back to you, 

Thanks.

**Comment by phanosp** [comment]
Hi the error "BAZARR Error trying to get series from Sonarr. Timeout Error." did not go away and it is still present although that when I click on test it says everything is ok and I can see the series and episodes of sonarr on bazarr. Is this normal or do I need to do something else?

**Comment by morpheus65535** [comment]
You can try to restart Sonarr.

**Comment by phanosp** [comment]
I reboot now the machine that both sonarr and bazarr are running just to be on the safe side. I will report back. Thanks

**Comment by phanosp** [comment]
I was able to solve the problem. For anyone that will come here looking here is the solution (it might be of use to someone).

The problem was a misconfiguration profile under Settings-->Languages. The default profile that bazarr was searching for was (for some reason) set to search for hearing impaired subtitles in greek only. Given that in greek language there are only a few subtitles with HI the bazarr could not locate anything. After fixing the profiles and configurating the tv shows to the correct profile bazarr started downloading subtitles. 

Thanks for the help

**Comment by morpheus65535** [comment]
Thanks for sharing the root cause. It may of course help others in the future!
