### ISSUE TITLE
Sonarr test wont load ever even with same settings as Radarr

### ISSUE THREAD

**Issue by Render343** [morpheus65535/bazarr#1328]
Hi I'm fairly new to the world of servers and bazarr and sonarr but I've been trying to connect the two but it never seems to click. I've entered the correct api keys, the default hostname/ip, a different hostname/ip and a different base url but it just doesn't seem to connect. attached are some screenshots of the settings page, is there anything else i need? 
![Screenshot_2021-03-21 Sonarr - Bazarr](https://user-images.githubusercontent.com/38626486/111933880-b3ba7180-8a96-11eb-977a-b378b827185e.png)
![Screenshot_2021-03-21 Radarr - Bazarr](https://user-images.githubusercontent.com/38626486/111933881-b4530800-8a96-11eb-961b-22d596430c7f.png)

**Comment by morpheus65535** [comment]
That's a configuration issue. Please come on Discord support channel for live support.
