### ISSUE TITLE
BAZARR Error trying to get video information for this file....

### ISSUE THREAD

**Issue by lukjod** [morpheus65535/bazarr#1330]
Recently when radar has upgraded quality of file and changed it from .avi to .mkv Bazarr gives error about missing .avi file although it has downloaded successfully subs for newly created .mkv movie.
Message:
BAZARR Error trying to get video information for this file: /movies/Adverse (2021)//Adverse.avi

Newest dev version from linuxserver.io docker on qnap x64

Bazarr Version:
0.9.3-beta.20
Sonarr Version:
3.0.5.1144
Radarr Version:
3.1.0.4799
Operating System:
Linux-4.14.24-qnap-x86_64-with
Python Version:
3.8.8
Bazarr Directory:
/app/bazarr
Bazarr Config Directory:
/config

`Traceback (most recent call last):
 File "/app/bazarr/bazarr/get_subtitle.py", line 63, in get_video
  video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,
 File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video
  return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 556, in scan_video
  video.size = os.path.getsize(hash_path)
 File "/usr/lib/python3.8/genericpath.py", line 50, in getsize
  return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: \/movies/Adverse (2021)//Adverse.avi\`

**Comment by morpheus65535** [comment]
As the new filename isn't synced, I would enable debug log and force an episode sync. There's probably some SQLite error in there.

**Comment by lukjod** [comment]
Nope nothing interesting there concerning Adverse.avi, Did not happen there. So should I delete database and start from beginning or can somehow repair it?

**Comment by morpheus65535** [comment]
If you can use a sqlite editor, open the db and remove the row for this specific episode from table_episodes.

**Comment by lukjod** [comment]
But this is movie, i guess have to delete it form table movies?

**Comment by lukjod** [comment]
ok, deleted 2 rows from history_movies table with that name, hope will be al right

**Comment by morpheus65535** [comment]
sorry I answered too fast. Remove the row from table_movies.

**Comment by lukjod** [comment]
thx for help, so far no errors on log
