### ISSUE TITLE
tusubtitulo provider is not working

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#1332]
**Describe the bug**
Tested episode =>New Amsterdam (2018) 3x1 (Spanish)

Error => Throttling tusubtitulo for 10 minutes, until 21/03/25 22:20, because of: HTTPError. Exception info: '403 Client Error: Forbidden for url: https://www.tusubtitulo.com/series.php?/'

**Software (please complete the following information):**
 - Bazarr:  v0.9.3 
 - OS: Linux

**Comment by morpheus65535** [comment]
Thank you very much for taking care of this one. As always, your help is greatly appreciated!
