### ISSUE TITLE
logs display is not correcting for browser (client) timezone

### ISSUE THREAD

**Issue by rmichelena** [morpheus65535/bazarr#1337]
Hi, when my server is in a different timezone than the browser from which I'm accessing the UI, the log entries show as in the future. Should be an easy fix.

History on the other hand does show correctly both for movies and series.

<img width="1391" alt="Screen Shot 2021-03-25 at 19 09 42" src="https://user-images.githubusercontent.com/77797875/112558844-b4584e00-8d9d-11eb-968c-8840ad932d3d.png">

**Comment by morpheus65535** [comment]
Should be fixed in upcoming v0.9.4-beta.9. Can you test it and confirm please?
