### ISSUE TITLE
GuessIt corrupting log files on debug mode

### ISSUE THREAD

**Issue by costaht** [morpheus65535/bazarr#1338]
**Describe the bug**
The log entry `GuessIt found:{ .... }` is "corrupting" Bazarr logs. Every time a new movie is added and a new occurrence of GuessIt is added to the log, Bazarr can't read it anymore. Deleting the `GuessIt found` lines will solve the problem and Bazarr is able to read the logs again.

```26/03/2021 02:29:17|DEBUG   |root                            |BAZARR Searching subtitles for this file: /mnt/hometheater/Movies/A/The Accountant (2016)/The.Accountant.2016.1080p.BluRay.H264.AAC-RARBG.mp4|
26/03/2021 02:29:17|DEBUG   |subzero.video                   |Parsing video: The.Accountant.2016.1080p.BluRay.H264.AAC-RARBG.mp4, hints: {'title': 'The Accountant', 'type': 'movie'}|
26/03/2021 02:29:17|INFO    |subliminal_patch.core           |Determining basic video properties for 'The.Accountant.2016.1080p.BluRay.H264.AAC-RARBG.mp4' in '/mnt/hometheater/Movies/A/The Accountant (2016)'|
26/03/2021 02:29:17|INFO    |subliminal_patch.core           |Determining basic video properties for 'The.Accountant.2016.1080p.BluRay.H264.AAC-RARBG.mp4' in '/mnt/hometheater/Movies/A/The Accountant (2016)'|
26/03/2021 02:29:18|DEBUG   |subliminal_patch.core           |GuessIt found: {
    "title": "The Accountant",
    "year": 2016,
    "screen_size": "1080p",
    "source": "Blu-ray",
    "video_codec": "H.264",
    "audio_codec": "AAC",
    "release_group": "RARBG",
    "container": "mp4",
    "mimetype": "video/mp4",
    "type": "movie"
}|
26/03/2021 02:29:18|DEBUG   |subliminal_patch.core           |Size is 2613328234|
26/03/2021 02:29:18|DEBUG   |subliminal_patch.core           |Computed hashes {'opensubtitles': 'aa62df9c06ee5200', 'opensubtitlescom': 'aa62df9c06ee5200'}|
26/03/2021 02:29:18|DEBUG   |root                            |BAZARR returning this binary: /usr/bin/ffprobe|
26/03/2021 02:29:18|DEBUG   |root                            |BAZARR FFprobe used is /usr/bin/ffprobe|
```
**To Reproduce**
1. Enable debug mode
2. Search for a subtitle
3. Go to Log page
4. Error 500 will be shown

**Screenshots**
![image](https://user-images.githubusercontent.com/50637431/112593289-a75b4f00-8ddd-11eb-9261-a5c391198f4c.png)
![image](https://user-images.githubusercontent.com/50637431/112593303-ac200300-8ddd-11eb-8d80-deadd907d733.png)

**Software (please complete the following information):**
 - Bazarr: v0.9.4-beta.7
 - OS: CentOS 8 Stream

**Additional context**
Using Bazarr with debug mode disabled will prevent it from corrupt the logs

**Comment by morpheus65535** [comment]
@LASER-Yi this is the one we've talked about last night. Can you look into it please?

**Comment by LASER-Yi** [comment]
Should be fixed in upcoming v0.9.4-beta.9. Can you test it and confirm please?

**Comment by costaht** [comment]
Tested again on version v0.9.4-beta.10 and the problem has been solved. Guessit stopped corrupting the logs and it is now shown properly.

![Screenshot from 2021-03-29 21-20-28](https://user-images.githubusercontent.com/50637431/112919233-b0e20100-90d4-11eb-903d-341d5643c86c.png)

**Comment by costaht** [comment]
Tested again on version v0.9.4-beta.10 and the problem has been solved. Guessit stopped corrupting the logs and it is now shown properly.

![Screenshot from 2021-03-29 21-20-28](https://user-images.githubusercontent.com/50637431/112919233-b0e20100-90d4-11eb-903d-341d5643c86c.png)
