### ISSUE TITLE
[Feature Request] Allow changing umask of downloaded subtitle file

### ISSUE THREAD

**Issue by wywywywy** [morpheus65535/bazarr#134]
Hi,

Is there any chance we can get an option to specify the umask of the downloaded files please?

Sonarr & Radarr already support it.

Currently Bazarr sets all files to 0644 by default.  Personally I want it to be 0666 so for example my Kodi user can overwrite it if needed.

Thanks.

Example from Sonarr -

![image](https://user-images.githubusercontent.com/19997747/45040772-abc48e80-b05e-11e8-8b30-5493822613cd.png)

**Comment by morpheus65535** [comment]
I'll look into this. Should be difficult with os.umask: https://docs.python.org/2/library/os.html

**Comment by wywywywy** [comment]
Thank you.

In the mean time I tried putting `chmod 666 {{subtitles}}` into the post-processing command box, but it doesn't seem to work.  Any ideas please?

**Comment by morpheus65535** [comment]
That's a good idea. I've tested it and it doesn't seems to work on my setup neither.

**Comment by wywywywy** [comment]
So any idea why?

I looked at the code and it's simple enough that it should just work.

get_subtitle.py

```
if use_postprocessing is True:
	command = pp_replace(postprocessing_cmd, path, downloaded_path, downloaded_language, downloaded_language_code2, downloaded_language_code3)
	try:
		if os.name == 'nt':
			codepage = subprocess.Popen("chcp", shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
			# wait for the process to terminate
			out_codepage, err_codepage = codepage.communicate()
			encoding = out_codepage.split(':')[-1].strip()

		process = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
		# wait for the process to terminate
		out, err = process.communicate()

		if os.name == 'nt':
			out = out.decode(encoding)
```

Unless the `downloaded_path` above isn't passed in properly?

**Comment by wywywywy** [comment]
I'm not familiar with subprocess in Python, but I just found this [in the docs](https://docs.python.org/3/library/subprocess.html) -

> args should be a sequence of program arguments or else a single string. By default, the program to execute is the first item in args if args is a sequence. If args is a string, the interpretation is platform-dependent and described below. See the shell and executable arguments for additional differences from the default behavior. Unless otherwise stated, it is recommended to pass args as a sequence.
> 
> On POSIX, if args is a string, the string is interpreted as the name or path of the program to execute. However, **this can only be done if not passing arguments to the program**.

So maybe it should do `process = subprocess.Popen(shlex.split(command), shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)` ?

**Comment by morpheus65535** [comment]
I've tested briefly shlex.split() but it doesn't work neither. I won't be able to look at this until friday. I'll come back to you ASAP on this.

**Comment by halali** [comment]
I've tested it and for me chmod command work

**Comment by wywywywy** [comment]
Ohhh of course! Quotes!

Thank you I will give it a try.

**Comment by morpheus65535** [comment]
Is this still an issue? I'll close this one in 2 days.

**Comment by wywywywy** [comment]
The workaround works but preferably it should be in the UI like Sonarr/Radarr.

So it's up to you whether you want to close it.

And thank you for making this great tool once again.

**Comment by morpheus65535** [comment]
Ok, thanks for the feedback. I'll keep it opened as a feature request.

**Comment by claym** [comment]
I’d like to see this as well, I currently add everything with 0664 :)

**Comment by halali** [comment]
added in https://github.com/morpheus65535/bazarr/commit/acbbf6e58bf83246bcd786649641b3e5a0493537
