### ISSUE TITLE
No column headers name on gui

### ISSUE THREAD

**Issue by lukjod** [morpheus65535/bazarr#1340]
On dev version no column headers as on screenshot
Bazarr Version
0.9.4-beta.7
Sonarr Version
3.0.5.1144
Radarr Version
3.1.0.4799
Operating System
Linux-4.14.24-qnap-x86_64-with
Python Version
3.8.8
Bazarr Directory
/app/bazarr
Bazarr Config Directory
/config
![obraz](https://user-images.githubusercontent.com/1781446/112594528-6416d580-8e09-11eb-8f78-1b24ba7c9cee.png)

**Comment by morpheus65535** [comment]
You mean the `Missing subtitles` table header?

**Comment by lukjod** [comment]
Yes

**Comment by morpheus65535** [comment]
Will be fixed in next release.
