### ISSUE TITLE
Not able to save subtitle

### ISSUE THREAD

**Issue by eeyoredk2** [morpheus65535/bazarr#1346]
Bazarr v0.9.4-beta.7

Hi
After updating, bazarr is not able to download subtitles, and I get the following error in the log: 

(filename replaced with XXXXXXXXXXXX)

BAZARR Error saving Subtitles file to disk for this file:/media/shares/XXXXXXXXXXXX: ValueError('not enough values to unpack (expected 2, got 1)')

Traceback (most recent call last):
  File "/opt/bazarr/bazarr/get_subtitle.py", line 211, in download_subtitle
    saved_subtitles = save_subtitles(video.original_path, subtitles, single=single,
  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 917, in save_subtitles
    content = subtitle.get_modified_content(format=format, debug=debug_mods)
  File "/opt/bazarr/bazarr/../libs/subliminal_patch/subtitle.py", line 389, in get_modified_content
    submods.modify(*self.mods)
  File "/opt/bazarr/bazarr/../libs/subzero/modification/main.py", line 215, in modify
    line_mods, non_line_mods, mods_used = self.prepare_mods(*mods)
  File "/opt/bazarr/bazarr/../libs/subzero/modification/main.py", line 85, in prepare_mods
    parsed_mods = [(SubtitleModifications.parse_identifier(mod), mod) for mod in mods]
  File "/opt/bazarr/bazarr/../libs/subzero/modification/main.py", line 85, in <listcomp>
    parsed_mods = [(SubtitleModifications.parse_identifier(mod), mod) for mod in mods]
  File "/opt/bazarr/bazarr/../libs/subzero/modification/main.py", line 72, in parse_identifier
    args = dict((key, value) for key, value in [sub.split("=") for sub in split_args])
  File "/opt/bazarr/bazarr/../libs/subzero/modification/main.py", line 72, in <genexpr>
    args = dict((key, value) for key, value in [sub.split("=") for sub in split_args])
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by morpheus65535** [comment]
Try to disable mods in Settings-->Subtitles, save settings, then re-enable them and save again. I didn't had mods enabled but when I do, I don't have any issue.

**Comment by eeyoredk2** [comment]
Disabling mods in subtitles and saving resulted in subtitles being saved. Unfortunately the subtitle settings page is now blank without any information at all and it is still blank after restart of Bazarr and the VM it is running in. It happend on both my Bazarr VM's so it is not an isolated incident.

**Comment by morpheus65535** [comment]
Can you provide one of your config.ini file after corruption? You can share it with me over PM on Discord.

**Comment by eeyoredk2** [comment]
I think that I found the cause. Removing **OCR_fixes** from subzero_mods and restarting Bazarr, allows me to enter the subtitle settings page again.
After that everything works perfectly until I re-enable OCR Fixes, then I am back to the original error. I have disabled it for now.

**Comment by morpheus65535** [comment]
In fact, as soon as there's a mod enabled (only one) it broke because there's no comma to split the string.

**Comment by morpheus65535** [comment]
It's now fixed and will be working in next nightly.

**Comment by bphd** [comment]
I have `  ::  bazarr[]: -- ::, - root () :  INFO (get_providers:303) - Throttling addic7ed for 10 minutes, until // :, because of: ValueError. Exception info: 'not enough values to unpack (expected 2, got 1)'` after putting `PHPSESSID:` in `Settings > Providers > Addic7ed > Cookies, e.g., PHPSESSID=abc; wikisubtitlesuser=xyz; wikisubtitlespass=efg`. Before that I've had `  ::  bazarr[]: -- ::, - root () :  INFO (get_providers:303) - Throttling addic7ed for 10 minutes, until // :, because of: Exception. Exception info: 'AntiCaptcha class not given, exiting'`

**Comment by morpheus65535** [comment]
@bphd this is addic7ed and you shouldn't use both username/password and phpsessionid. It's one or the other. If you choose username/password, you need an anti-captcha provider.

**Comment by bphd** [comment]
It should be written somewhere on the interface. Or just a switch system that toggle one form or the other

**Comment by morpheus65535** [comment]
@bphd feel free to create a feature request or, even better, submit a pull request with the required changes! 😄
