### ISSUE TITLE
Add ''catch a 404'' for provider ''GreekSubs''

### ISSUE THREAD

**Issue by pizzabe** [morpheus65535/bazarr#1347]
_Throttling greeksubs for 10 minutes, until 21/03/26 15:24, because of: HTTPError. Exception info: '404 Client Error: Not Found for url: https://greeksubs.net/en/view/tt4761112'_

This keeps throttling the provider. I was told that a catch 404 would resolve this issue, as it only keeps happening with this provider.

 - Bazarr:  0.9.3-beta.16
- OS:  Linux-5.4.0-70-generic-x86_64-with HWE enabled. Bazarr running on Hotio's docker.

**Comment by morpheus65535** [comment]
Should be fixed in upcoming v0.9.4-beta.9. Can you test it and confirm please?

**Comment by pizzabe** [comment]
I think this fixed it. Thanks!
