### ISSUE TITLE
Bazarr downloads English subtitles only

### ISSUE THREAD

**Issue by costaht** [morpheus65535/bazarr#1349]
**Describe the bug**
When Bazarr syncs new movies with Radarr, it is **automatically** downloading English subtitles only. The other languages will be kept in the Wanted queue until you manually trigger an **individual** search by clicking on their magnifiers.

**To Reproduce**
1. Set a profile with more than one language, including English. In my case, English, Brazilian Portuguese, and Spanish.
2. Sync the new movies with Radarr;
3. Wait for Bazarr to automatically download the requested subtitles;
4. Only English subtitles will be downloaded and some errors will be shown in the logs;
5. Click on _Search All_ and you'll get an error 500 on the Network tab on developer mode.

**Logs**
Log generated when you let Bazarr search for the subtitles profile automatically
https://paste.centos.org/view/f2715186

Logs generated when you click *Search All* on the Wanted page
https://paste.centos.org/view/753be1b7

**Expected behavior**
It's expected the available subtitles to be downloaded

**Screenshots**
![Screenshot from 2021-03-27 13-19-42](https://user-images.githubusercontent.com/50637431/112728764-314f0900-8eff-11eb-96be-536161816190.png)

**Software (please complete the following information):**
 - Bazarr: v0.9.4-beta.8
 - Radarr version 3.1.0.4799
 - Sonarr version 3.0.5.1144
 - OS: CentOS 8-Stream

**Additional context**
So far, all manual searches work fine.

**Comment by morpheus65535** [comment]
Should be fixed in upcoming v0.9.4-beta.9. Can you test it and confirm please?

**Comment by halali** [comment]
I can confirm, this one is fixed.
