### ISSUE TITLE
[Provider Request] Add SuperSubtitles

### ISSUE THREAD

**Issue by gurabli** [morpheus65535/bazarr#135]
I wonder if you could add the Hungarian site SuperSubtitles, at https://www.feliratok.info

It has a working Kodi addon. 
Thanks

**Comment by pcdevil** [comment]
Hey,

I want this feature too as part of an excercise I would like to implement it.
I don't really know about Python or this project either, but happy to help if I can!

I am a professional web developer, so not somebody who needs to learn how to write a code, but I am not familiar with the syntax and best practices in Python.

@morpheus65535, do you have time to help me and create a basic "getting started with the providers/converters" guide?

**Comment by gurabli** [comment]
@pcdevil I would be very happy if you could implement SuperSubtitles. I'm afraid I can't help you as I don't know coding, but happy to test. Bazarr is using subliminal for downloading subtitles. I see that a fork of subliminal called Sub-Zero.bundle (designed for Plex) already has SuperSubtitles site added, please take a look at here: [Sub-Zero SuperSubtitles](https://github.com/pannal/Sub-Zero.bundle/pull/501)
@morpheus65535 Do you think that code can be imported to Bazarr? I see that you were in charge of that commit too. Would be so nice to have this. None of the available providers are reliable for Hungarian language.

**Comment by pcdevil** [comment]
As I can see they are implementing a very similar or the same interface.

In that case I wouldn't rewrite it again. And because of ethical reasons copy-pasting is out of question as well 🙂 Instead I would humbly ask @morpheus133 to make a pull request about it here as well.

(Sidenote: It's a shame that Subliminal is not maintained anymore because it would be a simple dependency update..)

**Comment by gurabli** [comment]
Well, I tried to look at the code, but I don't know Python at all (should learn), as far as I can tell, it is indeed quite the same. At least both services rely on Subliminal as a backend for subtitle search, so under the hood it should be very similar. Again, I only think it is similar, if I was sure, I could done it myself :)
I think you can do it with copy/paste of it can be done like that, of course, keeping the credits and reference.
And Hossszupuska code is also there, would be great to have that too (not tbat I want too much).

**Comment by morpheus65535** [comment]
FYI we are planning to merge Bazarr and SubZero. You’ll benefit for that it’s going to be done. No ETA as we speak.

**Comment by gurabli** [comment]
This is excellent news, thank you for sharing.
Would be nice to have for xmas :) 
Let me know if you need any testing!

**Comment by pcdevil** [comment]
Yaaay, wonderful news!   
In that case I think this issue can be closed!

**Comment by morpheus133** [comment]
@morpheus65535 will it somehow possible to make provider development independent after the merge?
I mean that providers can change faster then releases happen to tools. (eg. subzero release Jun15 and next one is nov7. ) 
Between this time providers created by me was not working. 
I think something like this: instead of having providers.py in the repo they can fetch them for other one where others can also modify.

**Comment by morpheus65535** [comment]
@pannal What do you think about this?

**Comment by alneven** [comment]
and we had to manually change the providers.py :-) in the meantime

**Comment by pannal** [comment]
Subzero changes how providers are registered in subliminal_patch so that contents of the providers folder get scanned and registered automatically. 

Adding custom settings per provider would be the last step needed for a first dynamic implementation.

**Comment by morpheus65535** [comment]
@morpheus133 Bazarr release more often so we should be able to manage it in the same repo.

**Comment by gurabli** [comment]
> FYI we are planning to merge Bazarr and SubZero. You’ll benefit for that it’s going to be done. No ETA as we speak.

I wonder if the plan to merge Bazarr and SubZero is still an aim? Would be so great to see all the providers SubZero supports. Thanks!

**Comment by halali** [comment]
Added in development branch bazarr version 0.7.1

**Comment by gurabli** [comment]
Thank you so much! I'm already running it in docker.
Hosszupuskasub seams to work nice, SuperSubtitles doesn't work, if only enabled, no results at all. I can't provide logs now, but will look into.

**Comment by morpheus65535** [comment]
Would be appreciated, thanks!

**Comment by gurabli** [comment]
@morpheus65535 
It looks that something is wrong with SuperSubtitles. Here are the debug logs, hope it helps. Hosszupuska works.
[Logs](https://pastebin.com/ZYQAuDGk)

**Comment by gurabli** [comment]
Updated, now I get results from SuperSubtiltes too. Will test more and report back!
Again, your work is very much appreciated, well done!
