### ISSUE TITLE
Visual bug on language profiles

### ISSUE THREAD

**Issue by costaht** [morpheus65535/bazarr#1351]
**Describe the bug**
When you are editing a language profile and try, for example, to delete the first language on the list, Bazarr will delete the last one, but if you save those changes they will be applied correctly.

**To Reproduce**
1. Edit a profile with multiple languages
2. Delete the first one on the list

**Screenshots**
![bazarr](https://user-images.githubusercontent.com/50637431/112743287-f9c67800-8f63-11eb-9740-f17e0c6a4dec.gif)

**Software (please complete the following information):**
 - Bazarr: 0.9.4-beta.8
- Tested on Brave and Firefox

**Comment by LASER-Yi** [comment]
Should be fixed in upcoming v0.9.4-beta.10. Can you test it and confirm please?

**Comment by costaht** [comment]
Tested on version v0.9.4-beta.10 and the issue has been fixed.
