### ISSUE TITLE
Provider tvsubtitles.net cannot download subtitles anymore

### ISSUE THREAD

**Issue by mvanbaak** [morpheus65535/bazarr#1354]
**Describe the bug**

The tvsubtitles.net website changed their download page. It no longer redirects directly to a zipfile.
At the moment they use a page with some javascript to create a downloadlink, and redirect the browser to it.

See https://pastebin.com/WieGWHkE
And a debug log sent by discord user ```DarkKnight```: https://pastebin.com/hGXUd9aF

**To Reproduce**
1. Enable provider tvsubtitles.net
2. Search for subtitles on any tv show episode
3. Click 'download on any subtitle listed on the provider tvsubtitles.net

**Expected behavior**
The subtitle file is downloaded, unzipped, and saved

**Software (please complete the following information):**
 - Bazarr: 0.9.4-beta.11 but probably in all bazarr versions. It's a subliminal provider bug

**Comment by morpheus65535** [comment]
This one is quite simple:
```
var s1= 'fil';
...
var s2= 'es/P';
var s3= 'ea';
var s4= 'ky Blinders_4x01_HDTV.BRISK.en.zip';
document.location = s1+s2+s3+s4;
 ```
 Download link is a concatenation of s1, s2, s3 and s4.

I'll update the provider.

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta.12

**Comment by mvanbaak** [comment]
Confirmed. Working in beta.12
