### ISSUE TITLE
API access

### ISSUE THREAD

**Issue by Florentin68** [morpheus65535/bazarr#1355]
**Describe the bug**
I can't access API via cURL.
Login via form required.

command:
`curl "http://192.168.0.150:6767/api/system/status?apikey=xxxx"`

returns:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="/login/">/login/</a>.  If not click the link.
```

What am I doing wrong?

**Software (please complete the following information):**
 - Bazarr: v 0.9.0.8
 - OS: Linux-5.10.17-v8+-aarch64 (Docker container)

**Comment by halali** [comment]
This is only for issues, if you have questions please come to discord...

But you try to access api endpoint that doesn't exist

**Comment by morpheus65535** [comment]
`api/systemstatus` should work. BTW, update to 0.9.3 and be prepare for breaking change in 0.9.4 API.

**Comment by Florentin68** [comment]
Ok thank you. I updated yesterday it was the same.
I'll try what you indicated.

Le jeu. 1 avr. 2021 à 12:34, morpheus65535 ***@***.***> a
écrit :
