### ISSUE TITLE
Running Two or more syncs at the same time produce .synced.srt files

### ISSUE THREAD

**Issue by ArabCoders** [morpheus65535/bazarr#1363]
**Describe the bug**
It seems whenever i try to sync 1 or more subs at the same time the first one always fails and create sub.synced.srt file, last one works correctly.

**To Reproduce**
open two or more pages, then tools > sync multiple subs.
 
**Expected behavior**
I think the correct behavior is to run in parallel or queue subsequent sync requests.

**Software (please complete the following information):**
Bazarr Version:
0.9.3
Sonarr Version:
Radarr Version:
3.0.2.4552
Operating System:
Linux-5.4.0-70-generic-x86_64-with
Python Version:
3.8.8
Bazarr Directory:
/app/bazarr
Bazarr Config Directory:
/config

**Comment by halali** [comment]
Please post debug log with issue.

**Comment by ArabCoders** [comment]
@halali I'll try to replicate new docker setup to give detailed log.

**Comment by morpheus65535** [comment]
Reopen this issue if you still face the issue.
