### ISSUE TITLE
Bazarr doesn't show options for searching, downloading subtitle, etc.

### ISSUE THREAD

**Issue by sang-ook** [morpheus65535/bazarr#1365]
**Describe the bug**
After a fresh Bazarr installation via Portainer, I open movie and there isn't any option to search subtitles on the menu panel. Only options are for scanning, history and tools, nothing more. Sometimes those options for searching show just for a fraction of a second and then they disappear. I have Radarr, Sonarr set up in Bazarr settings and path mapping as well + subtitle provider.

**To Reproduce**
1. Select any movie in Bazarr
4. See no options for searching subtitle on menu panel

**Expected behavior**
Menu panel should have options for editing, searching and downloading subtitle.

**Screenshots**
![Snímka obrazovky z 2021-04-04 13-07-54](https://user-images.githubusercontent.com/67825889/113506763-4b5b9d80-9536-11eb-9b01-2d807af3417f.png)

**Software (please complete the following information):**
 - Bazarr: v0.9.3
 - Radarr version 3.0.2.4552
 - Sonarr version 3.0.6.1196
 - OS: Linux

**Additional context**

**Comment by morpheus65535** [comment]
You haven't selected a languages profile.
