### ISSUE TITLE
Audio language in bazarr not related to actual file information

### ISSUE THREAD

**Issue by efelon** [morpheus65535/bazarr#1366]
I come from discord (https://discord.com/channels/382221826564030464/540191312964485120/828352618974806026). After clarifying some question this problem remained which confused me.

**Describe the bug**
1. The displayed "Audio Language" in the series episode view does not reflect the actual file information. Neither from Sonarr nor from the ffprobe information. Instead it takes the information from the selected language profile from Sonarr as I was told on discord.
2. The header in the series overview shows "Audio Profile Language". This suggests a different information as the one in the series episodes view "Audio Language".

**To Reproduce**
1. Add a anime series in Sonarr with Japanese  language and english subtitles (embedded in my case)
![Bildschirmfoto von 2021-04-04 21-57-31](https://user-images.githubusercontent.com/10722552/113521541-6829bc80-959a-11eb-9840-a421c649f2a8.png)
2. Make a Bazarr language profile with Japanese and "Skip if matching audio track"
![Bildschirmfoto von 2021-04-04 23-01-11](https://user-images.githubusercontent.com/10722552/113521457-d8840e00-9599-11eb-97cc-99a69ab084d9.png)
3. Sync Sonarr with Bazarr
4. Audio Language will be displayed as "English"
5. Japanese subtitles will be displayed as "missing"
![Bildschirmfoto von 2021-04-04 23-09-12](https://user-images.githubusercontent.com/10722552/113521608-da9a9c80-959a-11eb-803a-5f729aedbc50.png)

**Expected behavior**
Bazarr should always display the actual audio language(s), independent of the information Sonarr or Radarr provides.

**Software (please complete the following information):**
- Sonarr Version:  3.0.6.1196
- Radarr Version:  3.0.2.4552
- Operating System:  Linux-5.10.0-0.bpo.4-arm64-aarch64-with-debian-10.9 (raspberry pi 4)
- Python Version:  3.7.3

**Comment by morpheus65535** [comment]
https://bazarr.featureupvote.com/
