### ISSUE TITLE
subtitle is not synchronizing after the download

### ISSUE THREAD

**Issue by VozDeOuro** [morpheus65535/bazarr#1367]
**Describe the bug**
the subtitle is not synchronizing after the download
it only syncs if I enter the episode and press to sync

**Expected behavior**
after downloading the subtitle is synchronized

**Software (please complete the following information):**
 - Bazarr: [0.9.3]
 - Radarr version [3.0.2.4552]
 - Sonarr version [3.0.6.1196]
 - OS: [Unraid(Docker)]

**Comment by mvanbaak** [comment]
Can you what your settings are under ```Settings -> Subtitles -> Post Processing -> Automatic Subtitles Synchronization``` ?

Also, if you can provide debug logs for when the subtitle gets downloaded, but does not get synced please.
https://github.com/morpheus65535/bazarr/wiki/Logging-and-Log-Files

**Comment by VozDeOuro** [comment]
![image](https://user-images.githubusercontent.com/36045463/113574758-1b260480-95f3-11eb-85ec-8c1572529418.png)
[bazarr.log](https://github.com/morpheus65535/bazarr/files/6258204/bazarr.log)

here it is

**Comment by morpheus65535** [comment]
`BAZARR subsync skipped because subtitles score isn't below this threshold value: 85%`

That's normal behavior with your settings.

**Comment by VozDeOuro** [comment]
> 
> 
> `BAZARR subsync skipped because subtitles score isn't below this threshold value: 85%`
> 
> That's normal behavior with your settings.

so if i upper those number they will be sync ?

**Comment by morpheus65535** [comment]
yes
