### ISSUE TITLE
Traditional Chinese profile sometimes return Simplified Chinese subtitles

### ISSUE THREAD

**Issue by kkycble** [morpheus65535/bazarr#1369]
I'm on Bazarr 0.9.3. This problem can be replicated when searching subtitles for The Simpsons S32E17. 

![Screenshot 2021-04-06 at 3 58 56 PM](https://user-images.githubusercontent.com/21995214/113678789-9e2d8480-96f1-11eb-8700-6cfc4094391e.png)

Where there are both TC and SC subtitles, they somehow got the same score of 7.

**Comment by morpheus65535** [comment]
@zx900930 are you able to take a look please?

**Comment by zx900930** [comment]
will look into it after work.

**Comment by morpheus65535** [comment]
@zx900930 any news about this one?

**Comment by morpheus65535** [comment]
@zx900930 Same here, anything you can do about it?

**Comment by morpheus65535** [comment]
@kkycble is it still an issue with 0.9.5?

**Comment by kkycble** [comment]
> @kkycble is it still an issue with 0.9.5?

I haven’t got into this issue for a while, so I guess it’s fixed?

**Comment by morpheus65535** [comment]
> I haven’t got into this issue for a while, so I guess it’s fixed?

Ok then, let's close it and if it happen again, just reopen it and provide a new debug log. Thanks for the fast feedback!
