### ISSUE TITLE
Memory after doing a lot of work is not released

### ISSUE THREAD

**Issue by bruuteuzius** [morpheus65535/bazarr#1375]
**Describe the bug**
When there are a lot of subtitles to be downloaded, bazarr tends to spike in memory usage and it looks like it is not able to release the memory usage.

**To Reproduce**
1. Go to sonarr or radarr and download a bunch of subtitles needed shows/movies.
2. Watch the memory usage climb up and up and up to several gigs of memory (docker ps or kubernetes or ..)

**Expected behavior**
After the subtitles are downloaded, I expect the GC to clean up used memory.

**Screenshots**
![image](https://user-images.githubusercontent.com/74918413/114171335-6d895d00-9934-11eb-841b-18f238d3b8d0.png)

**Software (please complete the following information):**
- Bazarr Version: 0.9.2
- Sonarr Version: 3.0.5.1144
- Radarr Version: 3.0.2.4552
- Operating System: Linux-4.4.59+-x86_64-with
- Python Version: 3.8.8

**Additional context**
I did not put a max on the memory usage on my Synology NAS. It's unrestricted.

**Comment by morpheus65535** [comment]
That's a known issue in Synology Docker UI. It's reporting cached memory that is being released as "in use". In fact, this memory can be used by other processes. Don't worry about it, the garbage collector is run after searching for subtitles to make sure that doesn't happen.

**Comment by bruuteuzius** [comment]
Ok thanks! You're right! I see a 163MB in docker stats :+1:  and 4gb on the synology :')
