### ISSUE TITLE
Choosing Language in language profile is Empty

### ISSUE THREAD

**Issue by NickCh11** [morpheus65535/bazarr#1377]
![image](https://user-images.githubusercontent.com/58607503/114286377-c527e580-9a66-11eb-9b3f-240c7fa61026.png)

Bazarr Version:
0.9.3
Operating System:
Linux-5.10.17-v7l+-armv7l-with
Python Version:
3.8.8

**Comment by morpheus65535** [comment]
Press cancel and start by selecting languages in filter languages dropdown.
