### ISSUE TITLE
On first startup: ValueError: Already registered

### ISSUE THREAD

**Issue by ChristofferGreen** [morpheus65535/bazarr#1378]
Attempting to install the software for the first time on a 32bit raspberry pi 4 system. Have tried master as well as v0.9.3 and v0.9.2 with the same error.

When starting it for the first time this happens:
 

/opt/bin/bazarr:master$ python3 bazarr.py
Bazarr starting...
Traceback (most recent call last):
  File "bazarr/main.py", line 25, in <module>
    from init import *
  File "/opt/bin/bazarr/bazarr/init.py", line 197, in <module>
    init_binaries()
  File "/opt/bin/bazarr/bazarr/init.py", line 178, in init_binaries
    from utils import get_binary
  File "/opt/bin/bazarr/bazarr/utils.py", line 20, in <module>
    from list_subtitles import store_subtitles, store_subtitles_movie
  File "/opt/bin/bazarr/bazarr/list_subtitles.py", line 9, in <module>
    from subliminal_patch import core, search_external_subtitles
  File "/opt/bin/bazarr/bazarr/../libs/subliminal_patch/__init__.py", line 8, in <module>
    from .providers import Provider
  File "/opt/bin/bazarr/bazarr/../libs/subliminal_patch/providers/__init__.py", line 30, in <module>
    mod = importlib.import_module("subliminal_patch.providers.%s" % module_name.lower())
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/bin/bazarr/bazarr/../libs/subliminal_patch/providers/legendastv.py", line 8, in <module>
    from subliminal.providers.legendastv import LegendasTVSubtitle as _LegendasTVSubtitle, \
  File "/opt/bin/bazarr/bazarr/../libs/subliminal/providers/legendastv.py", line 28, in <module>
    language_converters.register('legendastv = subliminal.converters.legendastv:LegendasTVConverter')
  File "/opt/bin/bazarr/bazarr/../libs/babelfish/converters/__init__.py", line 276, in register
    raise ValueError('Already registered')
ValueError: Already registered
Bazarr exited.

Putting a print line at /opt/bin/bazarr/bazarr/../libs/babelfish/converters/__init__.py", line 276 gives:

`Bazarr starting...
addic7ed = subliminal.converters.addic7ed:Addic7edConverter [] 

legendastv = subliminal.converters.legendastv:LegendasTVConverter ['addic7ed = subliminal.converters.addic7ed:Addic7edConverter'] 

shooter = subliminal.converters.shooter:ShooterConverter ['legendastv = subliminal.converters.legendastv:LegendasTVConverter', 'addic7ed = subliminal.converters.addic7ed:Addic7edConverter'] 

thesubdb = subliminal.converters.thesubdb:TheSubDBConverter ['shooter = subliminal.converters.shooter:ShooterConverter', 'legendastv = subliminal.converters.legendastv:LegendasTVConverter', 'addic7ed = subliminal.converters.addic7ed:Addic7edConverter'] 

tvsubtitles = subliminal.converters.tvsubtitles:TVsubtitlesConverter ['thesubdb = subliminal.converters.thesubdb:TheSubDBConverter', 'shooter = subliminal.converters.shooter:ShooterConverter', 'legendastv = subliminal.converters.legendastv:LegendasTVConverter', 'addic7ed = subliminal.converters.addic7ed:Addic7edConverter'] 

addic7ed = subliminal_patch.language:PatchedAddic7edConverter ['tvsubtitles = subliminal.converters.tvsubtitles:TVsubtitlesConverter', 'thesubdb = subliminal.converters.thesubdb:TheSubDBConverter', 'shooter = subliminal.converters.shooter:ShooterConverter', 'legendastv = subliminal.converters.legendastv:LegendasTVConverter'] 

szopensubtitles = subliminal_patch.language:PatchedOpenSubtitlesConverter ['addic7ed = subliminal_patch.language:PatchedAddic7edConverter', 'tvsubtitles = subliminal.converters.tvsubtitles:TVsubtitlesConverter', 'thesubdb = subliminal.converters.thesubdb:TheSubDBConverter', 'shooter = subliminal.converters.shooter:ShooterConverter', 'legendastv = subliminal.converters.legendastv:LegendasTVConverter'] 

hosszupuska = subliminal_patch.converters.hosszupuska:HosszupuskaConverter ['szopensubtitles = subliminal_patch.language:PatchedOpenSubtitlesConverter', 'addic7ed = subliminal_patch.language:PatchedAddic7edConverter', 'tvsubtitles = subliminal.converters.tvsubtitles:TVsubtitlesConverter', 'thesubdb = subliminal.converters.thesubdb:TheSubDBConverter', 'shooter = subliminal.converters.shooter:ShooterConverter', 'legendastv = subliminal.converters.legendastv:LegendasTVConverter'] 

legendastv = subliminal.converters.legendastv:LegendasTVConverter ['hosszupuska = subliminal_patch.converters.hosszupuska:HosszupuskaConverter', 'szopensubtitles = subliminal_patch.language:PatchedOpenSubtitlesConverter', 'addic7ed = subliminal_patch.language:PatchedAddic7edConverter', 'tvsubtitles = subliminal.converters.tvsubtitles:TVsubtitlesConverter', 'thesubdb = subliminal.converters.thesubdb:TheSubDBConverter', 'shooter = subliminal.converters.shooter:ShooterConverter', 'legendastv = subliminal.converters.legendastv:LegendasTVConverter'] 

Traceback (most recent call last):
  File "bazarr/main.py", line 25, in <module>
    from init import *
  File "/opt/bin/bazarr/bazarr/init.py", line 197, in <module>
    init_binaries()
...`

**Comment by morpheus65535** [comment]
You didn't specify which OS and python version you use. Also if you can provide `pip list` output.

**Comment by ChristofferGreen** [comment]
Sorry about that, here is the requested information:

/opt/bin/bazarr:master$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"


/opt/bin/bazarr:master$ python3 --version
Python 3.7.3


/opt/bin/bazarr:master$ pip3 list
Package            Version
------------------ ------------
acme               0.31.0
appdirs            1.4.4
asn1crypto         0.24.0
attrs              20.3.0
bcrypt             3.2.0
beautifulsoup4     4.7.1
better-exceptions  0.3.2
borgbackup         1.1.9
cached-property    1.5.2
certbot            0.31.0
certbot-nginx      0.31.0
certifi            2018.8.24
cffi               1.14.4
chardet            3.0.4
cloudscraper       1.2.52
ConfigArgParse     0.13.0
configobj          5.0.6
cryptography       2.6.1
cssselect          1.1.0
distro             1.5.0
docker             4.4.1
docker-compose     1.27.4
dockerpty          0.4.1
docopt             0.6.2
entrypoints        0.3
future             0.16.0
guessit            3.2.0
html5lib           1.0.1
idna               2.6
importlib-metadata 3.3.0
josepy             1.1.0
jsonschema         3.2.0
keyring            17.1.1
keyrings.alt       3.1.1
llfuse             1.3.6
lxml               4.6.2
manga-py           1.29.5
mock               2.0.0
msgpack            0.5.6
mysqlclient        2.0.3
numpy              1.20.2
packaging          20.8
paramiko           2.7.2
parsedatetime      2.4
pbr                4.2.0
Pillow             8.1.0
pip                21.0.1
pipenv             11.9.0
progressbar2       3.53.1
pycparser          2.20
pycrypto           2.6.1
pycryptodome       3.9.9
PyExecJS           1.5.1
PyGObject          3.30.4
PyNaCl             1.4.0
pyOpenSSL          19.0.0
pyparsing          2.4.7
pyRFC3339          1.1
pyrsistent         0.17.3
PySocks            1.7.1
python-apt         1.8.4.3
python-dotenv      0.15.0
python-utils       2.4.0
pytz               2019.1
pyxattr            0.6.1
pyxdg              0.25
PyYAML             5.3.1
rarfile            4.0
rebulk             3.0.1
requests           2.25.1
requests-toolbelt  0.9.1
SecretStorage      2.3.1
setuptools         40.8.0
six                1.12.0
soupsieve          1.8
ssh-import-id      5.7
stevedore          1.20.0
subliminal         2.1.0
texttable          1.6.3
typing-extensions  3.7.4.3
ufw                0.36
urllib3            1.24.1
virtualenv         15.1.0
virtualenv-clone   0.3.0
webencodings       0.5.1
webrtcvad-wheels   2.0.10.post2
websocket-client   0.57.0
wheel              0.32.3
youtube-dl         2019.1.17
zipp               3.4.0
zope.component     4.3.0
zope.event         4.2.0
zope.hookable      4.0.4
zope.interface     4.3.2

**Comment by morpheus65535** [comment]
You've got many conflictual packages here. Please try to reproduce using venv.

**Comment by ChristofferGreen** [comment]
I did not know about venv, thank you for letting me know. That appears to have fixed the issue.
