### ISSUE TITLE
Autoupdate not working for Development - Beta releases

### ISSUE THREAD

**Issue by Gaudi111** [morpheus65535/bazarr#1379]
**Describe the bug**
Autoupdate is not working in my current installation: 
QNAP NAS
installed and updated manually up to v0.9.4-beta.252021-04-13

**To Reproduce**
Neither it auto updates, nor the Update Bazarr in Tasks button appear to work.

**Expected behavior**
Program should auto update.

**Screenshots**

**Software (please complete the following information):**
Bazarr Version v0.9.4-beta.24
Sonarr Version 3.0.6.1196
Radarr Version 3.0.2.4552
Operating System Linux-3.4.6-x86_64-with-glibc2.2.5
QNAP NAS 4.3.4
Python Version: 3.8.1

**Additional context**
I do not seem to find any reference in the log.

![Bazarr](https://user-images.githubusercontent.com/5664943/114590032-a2602180-9c5e-11eb-998a-54064626c053.png)

**Comment by morpheus65535** [comment]
Should be fixed in upcoming v0.9.4-beta.27
