### ISSUE TITLE
Wizdom.XYZ provider not working

### ISSUE THREAD

**Issue by hros** [morpheus65535/bazarr#1382]
Subtitles are not being downloaded from Wizdom.XYZ (hebrew subtitles)

For example, downloading the movie file: "Tinker.Tailor.Soldier.Spy.2011.BluRay.1080p.x264-LTT"
Searching for the subtitle in Wizdom.XYZ, shows a long list of compatible subtitles ([link](https://wizdom.xyz/movie/tt1340800)), yet the subtitles are not downloaded automatically or found when manually clicking the search button of the missing button

Needless to say that that provider is selected in the Bazarr settings:
![image](https://user-images.githubusercontent.com/2613469/114874182-bd6c9600-9e04-11eb-89d5-3523816e8ce3.png)

How can I help debugging this problem?

**Comment by halali** [comment]
You can help with debuglog where you reproduce that issue.

**Comment by morpheus65535** [comment]
I've just tested with an episode and a movie and they both work fine. That's probably something specific with this movie. Without a debug log reproducing the issue, there's nothing I can do about it. I'm closing this issue since we haven't heard from the OP for a week.
