### ISSUE TITLE
Series/Movies empty - Mass Editor not working on 0.9.5 beta4 - QNAP NAS

### ISSUE THREAD

**Issue by Gaudi111** [morpheus65535/bazarr#1387]
**Describe the bug**
After doing a clean install and editing the settings manually, movies and series are empty.
Pressing "Mass Editor" in either screen results in a blank page.

**To Reproduce**
1. Go to Series/Movies Screen
2. Click on Mass Edit
3. UI dissappear and result in a blank page.

Tested in Chrome, Waterfox Classic, Edge.

**Expected behavior**
Open Mass Edit interface.

**Screenshots**

**Software (please complete the following information):**
Bazarr Version v0.9.5-beta.4
Sonarr Version 3.0.6.1196
Radarr Version 3.1.0.4893
Operating System Linux-3.4.6-x86_64-with-glibc2.2.5 (on QNAP NAS package)
[bazarr.log](https://github.com/morpheus65535/bazarr/files/6385662/bazarr.log)

Python Version 3.8.1

**Additional context**

**Comment by morpheus65535** [comment]
Your Series, Episodes and Movies haven't been synced to Bazarr yet. You can see the status in System-->Tasks and for run the jobs one by one if you want or wait for the specified delay.

I don't see anything wrong in your debug log so unless you've got something in browser console, there's no problem here.

**Comment by Gaudi111** [comment]
Thank for your reply. I have forced the sync many times, but movies do not appear, and mass edit does not work.. 
Tested downgrading to v0.9.4 stable, same behaviour.

Is there any way to check for syncing progress?
It is unclear to me if there is an error that prevents the movies/series to be synced, or if it is taking its time.
I have a backup of the database prior to the clean reinstall that I may use to speed up new scan.

Am including a new log:
[bazarr (1).log](https://github.com/morpheus65535/bazarr/files/6385856/bazarr.1.log)

Please also note that there are some errors showing while starting the script (it may be related to the QNAP package itself and not Bazarr):
[Startup Log.txt](https://github.com/morpheus65535/bazarr/files/6385888/Startup.Log.txt)

**Comment by Gaudi111** [comment]
Edit:

I can confirm that overwriting the bazarr.db with the old database enabled the use of Mass Edit.

Apparently having the list emply breaks its functionality. (I can see that it adds checkboxes to the existing items in the list (movie/serie), so an empty list may break havoc).

I am still to check why the sync was not working with a fresh install, as  have no way of testing the progress.

**Comment by morpheus65535** [comment]
You may have problem with the QNAP package and you would have to see with those who created it.

As for the "no way to confirm the sync progress", debug log is clearly logging the progress that doesn't seems to start in your case. I don't see a single call to Sonarr /series or /episodes API endpoints or to Radarr /movies endpoint. It looks like you haven't enabled Sonarr and Radarr in settings or you haven't run the sync jobs.
