### ISSUE TITLE
(Manual)Search not finding subtitles upon many providers

### ISSUE THREAD

**Issue by Gaudi111** [morpheus65535/bazarr#1388]
**Describe the bug**
Doing manual search for subtitles (not found automatically even though there are many providers that do have subs) does not work, and throw some errors in log.

**To Reproduce**
Open a Movie/Series Episode, select manual search, perform the actual search.
Progress screen stuck for a long time.

**Expected behavior**
Find subtitles/show a "not found" message.

**Screenshots**

**Software (please complete the following information):**
Bazarr Version v0.9.5-beta.4
Sonarr Version 3.0.6.1196
Radarr Version 3.1.0.4893
Operating System Linux-3.4.6-x86_64-with-glibc2.2.5 (on QNAP NAS)
Python Version 3.8.1

**Additional context**
Issue appeared about 3 weeks ago, when even though there are many subtitles available in different providers, Bazarr does not download them (it used to work fine).
Tried manual search, but ot does not find subtitles either.

Have to manually upload the subs, or use Kodi internal subtitle downloader feature.
[bazarr (3).log](https://github.com/morpheus65535/bazarr/files/6386160/bazarr.3.log)

**Comment by morpheus65535** [comment]
You haven't configured languages profiles or providers first... please stop opening issues and start by reading the wiki and asking for help to configure your Bazarr properly on Discord support channel. Thanks.
