### ISSUE TITLE
Provider Subtitulamos.tv is broken.

### ISSUE THREAD

**Issue by GermanG** [morpheus65535/bazarr#1397]
When added, every subtitle search is empty. Looking at the logs 
```
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/get_subtitle.py", line 385, in manual_search
    subtitles = list_all_subtitles([video], language_set,
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 755, in list_all_subtitles
    subtitles = pool.list_subtitles(video, languages - video.subtitle_languages)
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 225, in list_subtitles
    provider_subtitles = self.list_subtitles_provider(name, video, languages)
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 148, in list_subtitles_provider
    if not provider_registry[provider].check(video):
AttributeError: \'NoneType\' object has no attribute \'check\
```
**To Reproduce**
1. Add provider subtitulamos.tv 
2. Manually search for movie or episode.

**Expected behavior**
Find subtitles :)

**Software (please complete the following information):**
 - Bazarr: latest development docker (also latest development branch)

A quick troubleshooting showed the provider "subtitulamos" at the moment of the search while the provider registry has a "subtitulamostv", that's why the `provider_registry[provider]`  is None

I'll try to fix it my self, but reporting first as I don't know when I can do it.

Edit: I think the culprit is frontend/build/static/js/main.05a5c2ae.chunk.js 
```bash
$ grep -o subtitulamos.. frontend/build/static/js/main.05a5c2ae.chunk.js                       
subtitulamos",
```

**Comment by morpheus65535** [comment]
Should be fixed in upcoming v0.9.5-beta.10.

**Comment by GermanG** [comment]
I'll let you know as soon as v0.9.5-beta.10 is out

**Comment by GermanG** [comment]
Checked now, it's fixed. I had an issue while doing it: the config.ini had "subtitulamos" -because I didn't remove the provider-, so then adding/removing subtitulamos.tv won't affect that, had to edit the config.ini to solve that.

**Comment by morpheus65535** [comment]
Of course, thanks for the feedback!
