### ISSUE TITLE
Cannot create a profile with 'forced' and normal subtitles in the same language

### ISSUE THREAD

**Issue by bpeffer** [morpheus65535/bazarr#1398]
**Describe the bug**
I'm trying to add an English language profile and have Bazarr pull both regular and forced subs. I set the language to "English" in the filter and created a profile with 2 English rows. When I select the checkbox under 'forced' in the second row, ID 2, it will only check off the box in the top row, ID 1 (I cannot modify the second row, ID 2.) When searching for subtitles, Bazarr will ignore the second row and use whatever settings are in the top row.

**Expected behavior**
To be able to search for both regular and forced subtitles in the same language.

**Screenshots**
![image](https://user-images.githubusercontent.com/26173743/116883610-cc6c8a00-abf3-11eb-8cdf-76eed08c480d.png)

**Software:**
 - Bazarr: 0.9.4
 - OS: Ubuntu Server 20.04

**Comment by morpheus65535** [comment]
We're aware of this issue that have been fixed in dev branch (65e68d44098a01b13277fdc6a20651c51403014a). Will be included in 0.9.5. Thanks for reporting!
