### ISSUE TITLE
Napiprojekt provider with subliminal

### ISSUE THREAD

**Issue by maryanoo** [morpheus65535/bazarr#140]
I can't see napiprojekt provider in subtitle providers. I don't know it is a bug or a feature, because in Your github bazarr/libs/subliminal/providers/ there is a napiprojekt.py. It will be greate, if you add this provider (with authentication).
My version is 0.6.2 (Linux -Arch)

**Comment by morpheus65535** [comment]
After some validation, it appear that this provider isn't fully functional. Diaoul, the developer of Subliminal need to finish development before he could enable it: https://github.com/Diaoul/subliminal/issues/744
