### ISSUE TITLE
Suggestion/request

### ISSUE THREAD

**Issue by michpas** [morpheus65535/bazarr#1401]
**Describe the bug**
Some devices (although 4k/hdr enabled) do not handle subtitles well.  An example is all lg oled televisions in combination with internal apps as plex. 
When playing an hdr movie, the srt subtitles are extremely white. To the extend ot hurts the eye.
Therefor i was really pleased with the bazarr option to embed color codes in the srt files.selecting a dark color helps. This ensures it plays well.

However when playing the file on another television, these srt are (obvious) too dark.

Question, would it be possible to add an option behind the color tag that makes and stores a copy srt with the color tags and leaves in the original without color tags?
This would allow individuals to choose and switch as they see fit.

**To Reproduce**
1. Openal a hdr movie on plex oled lg tv with external srt. 

**Expected behavior**
Keepnon colored version, bit create a2nd srt with color

**Screenshots**

**Software (please complete the following information):**
 - latest docker on synologt nas

**Additional context**

**Comment by morpheus65535** [comment]
FR can be added at: https://bazarr.featureupvote.com/
