### ISSUE TITLE
Disable ASS/SSA conversion to SRT

### ISSUE THREAD

**Issue by ThibaultNocchi** [morpheus65535/bazarr#1404]
**Describe the bug**
Bazarr converts the downloaded SSA subs to SRT, and I'd like to avoid that. I disabled all post processing options but it still happens.

**To Reproduce**
1. Try to automatically fetch an ASS file (for instance, I have an anime where the only file my providers find in my language is an ASS sub)
2. Let it download it, see it is converted to SRT

**Expected behavior**
Either make the post processing work with ASS files, or just have an option to disable any processing for them.

**Software (please complete the following information):**
 - Bazarr: v0.9.5

**Additional context**
ASS subtitles contain variable positions for lines of texts, can display many lines at the same time, etc. It's really useful in animes for instance.

**Comment by morpheus65535** [comment]
This isn't the place for feature requests. There's already a FR for that and I don't plan to go down that path anyway.

**Comment by ThibaultNocchi** [comment]
Oops sorry, I should've read the readme. Have a nice day :)
