### ISSUE TITLE
Running as service Ubuntu with python3

### ISSUE THREAD

**Issue by Amateur-God** [morpheus65535/bazarr#1406]
Please add this to the wiki, systemd file for running bazarr as a service with python3 

to use this file login as root or as user with sudo privelages then:

```
sudo nano /etc/systemd/system/bazarr.service
```

then copy code below and insert changing the "USER" and "GROUP" to whichever user and group you want bazarr to run as

```
[Unit]
Description=Bazarr Service daemon
After=syslog.target network.target

[Service]
User="user"
Group="group"

Type=simple
ExecStart=/usr/bin/python3 /opt/bazarr/bazarr.py
TimeoutStopSec=10
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

then ctrl+x -> y -> enter

reload daemon
```
sudo systemctl daemon-reload
```

start and make sure it all works
```
sudo systemctl start bazarr.service
```

```
sudo systemctl status bazarr.service
```
if its returns 

```
● bazarr.service - Bazarr Service Daemon
     Loaded: loaded (/etc/systemd/system/bazarr.service; enabled; vendor preset: enabled)
     Active: active (running) since 
```

then run the command to enable at system start

```
sudo systemctl enable bazarr.service
```

**Comment by morpheus65535** [comment]
I haven't compared but how is this different than this one: https://wiki.bazarr.media/Getting-Started/Autostart/Linux/linux/#systemd-service-file-for-debian-ubuntu
?

**Comment by NH-Networks** [comment]
it's same and will work for ubuntu also.. no need for update.

**Comment by Amateur-God** [comment]
> I haven't compared but how is this different than this one: https://wiki.bazarr.media/Getting-Started/Autostart/Linux/linux/#systemd-service-file-for-debian-ubuntu
> ?

Ahh I see I missed a page on the wiki, sorry about that. I hadn't seen that page

**Comment by morpheus65535** [comment]
Thank you guys!
