### ISSUE TITLE
tusubtitulo provider is missing relevant information

### ISSUE THREAD

**Issue by Sockolet** [morpheus65535/bazarr#1411]
**Describe the bug**
Tusubtitulo provider is missing relevant information regarding the regional information of the Spanish language. Specifically, provider should information if the language is Spanish (Spain/European) or Spanish (Latinamerican).

**To Reproduce**
1. Manually search subtitles.
2. Check Tusubtitulo provider and you see that information is just the release name.

**Expected behavior**
Release field should contain more info.

**Screenshots**
EXAMPLE:

![image](https://user-images.githubusercontent.com/8806527/118462197-b6d08780-b6fe-11eb-98cb-7dfa74985c65.png)

![image](https://user-images.githubusercontent.com/8806527/118462252-c354e000-b6fe-11eb-9627-44e90d19c747.png)

GOOD BEHAVIOR (Subdivx):

![image](https://user-images.githubusercontent.com/8806527/118462311-d4055600-b6fe-11eb-9a31-f69cd75ac2a6.png)

**Software (please complete the following information):**
Bazarr Version: v0.9.5
Sonarr Version: 3.0.6.1196
Radarr Version: 3.1.1.4954
Ubuntu server 18.04 up-to-date.

**Additional context**
Also, is there anyway to set one of those regional subcategories (Spain/European or Latinamerican) as preferred?

**Comment by morpheus65535** [comment]
Bazarr rely on official IETF/ISO-639 language codes and there is no specific code to distinguish those two similar languages. They both fall under the ES code. There's nothing I can do on my side about it. The Release info column is there to show the release/version names, not the commentaries. Sorry but from  my point of view, there's nothing I can do about this.

**Comment by Sockolet** [comment]
Hi @morpheus65535 . Thank you very much for your reply.
I totally understand your point of view, but there is something that I've noticed and considering the information that you shared with me in your coment above, I would like to get your opinion too.
As you can imagine at this point, I download Spanish subtitles with Bazarr. I use 3 main providers: Subdivx, tusubtitulo and subtitulamostv.
There is no way to set a preference for them (as far as I know), but the thing is that my subtitles are always downloaded from Subdivx in the automatic search, because they always have a better score.
I understand that this is because the Release field includes much more information in the description, but tusubtitulo and subtitulamostv ones are usually better subtitles than Subdivx's ones.
So in my mind, ts and subtv should receive priority by the system in comparison to Subdvx.

Any explanation on why Subdivx's ones get always a better score?

Thank you very much in advance.

**Comment by kevindevm** [comment]
@morpheus65535 the thing is that tusubtitulo its pretty strict and wont release a bad subtittle ever. they actually dont let u download a subtittle without being cheked by a moderator. so maybe you can add a score multiplier for sites? cuz i would definitly say tusubtitulo is 100% the best in spanish

**Comment by morpheus65535** [comment]
> @morpheus65535 the thing is that tusubtitulo its pretty strict and wont release a bad subtittle ever. they actually dont let u download a subtittle without being cheked by a moderator. so maybe you can add a score multiplier for sites? cuz i would definitly say tusubtitulo is 100% the best in spanish

Someone is actually working on a score boost system. More to come. In the meantime, I'll close this issue if it's ok with you.

**Comment by Sockolet** [comment]
Hello again. I have something to add before closing.
@morpheus65535 as I said in my previous message: I totally understand your point of view.
The thing is that if we don't think about how Bazarr works nowadays, but about what is the purpose of the application, I think there are reasons to consider adding some kind of filter for this kind of regional subcategories.

Let me explain: Bazarr is aimed to automatize the way in which we get subtitles and it pretends to do it in an efficient way, this means to get the best subtitle avaialable.
So in this case, we aren't getting the best subtitle available because relevant information, that sould be considered in the moment of chosing one sub instead of the other, is not taken in consideration.

Even if I don't want to rely on the score algorithm, and I would like to manually download the subtitle that I prefer from Bazarr menu, I cannot distinguish among the different versions that tusubtitulo has available because the regional subcategory is not there. This means I have to download the first one blindly, check by playing the file if it is the proper one, and if it's not, download the next available.
So maybe, if the application isn't designed to consider regional subcategories, the tusubtitulo provider should, as it is capital for its users.

I don't think modifying the scraper to distinguish between "Spain" and "Latinoamerica" is a by change. Maybe in the provider settings (the same place in which you set your credentials for opensubtitles, for example) a dropdown menu can be added to choose whether you want to prioritize "Spain" or "Latinoamerica".

Well, this is my suggestion :)
Thank you very much for taking the time to discuss this with us!

**Comment by morpheus65535** [comment]
@Sockolet this is already being address in https://github.com/morpheus65535/bazarr/pull/1412
