### ISSUE TITLE
This Sonarr/Radarr root directory does not seems to be accessible by Bazarr. Please check path mapping

### ISSUE THREAD

**Issue by kodifan** [morpheus65535/bazarr#1413]
**Describe the bug**
Not exactly a bug but issue/misbehavior
Bazarr is reporting that cant reach two root directories (from one Sonar and one from Radar). Those root directories are Download and Torrents in my case and they are used by Download Station and Transmission to download movies and tv shows   and sometimes I use them to import into Sonar or Radarr.
Since media files are moved when they are imported to tv and movies directories, its not a wise solution to add them to Bazarr i guess. 

**To Reproduce**
1. Go to System/Status
/torrents/	This Sonarr root directory does not seems to be accessible by Bazarr. Please check path mapping.
/downloads/	This Radarr root directory does not seems to be accessible by Bazarr. Please check path mapping.

**Expected behavior**
Some kind of exclusion for "not media"/temporary root folders imported from Sonarr/Radarr

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 0.9.6-beta.9
 - Radarr version 3.2.0.5048
 - Sonarr version 3.0.6.1196
 - OS: Linux-3.10.105-x86_64-with / Synology

**Additional context**
![radarr](https://user-images.githubusercontent.com/7819312/119222605-81101200-baf5-11eb-942b-8a14d860b3bf.png)
![sonarr](https://user-images.githubusercontent.com/7819312/119222607-81a8a880-baf5-11eb-8394-03050880c63c.png)
![bazarr](https://user-images.githubusercontent.com/7819312/119222608-81a8a880-baf5-11eb-939a-008da23934cd.png)

**Comment by morpheus65535** [comment]
In beta.14, they should be there if you don't have any series or movies under those root folders. Please test and confirm.

**Comment by kodifan** [comment]
> In beta.14, they should be there if you don't have any series or movies under those root folders. Please test and confirm.

Sure will test it when beta 14 will be released.
