### ISSUE TITLE
Bazarr handling subtitle scoring poorly and grabbing a lot of wrong sourced subtitles.

### ISSUE THREAD

**Issue by batuhankrmn** [morpheus65535/bazarr#1418]
**Describe the bug**
Hello, I get a lot of wrong sourced subtitles lately and I did manual search to check and I was shocked. Bazarr was allowing to download CAM release subtitle for 4K Bluray movie and says source matched. Same thing valid for WEBDL too. I dont know what causing these but this happens a lot specially for Turkish subtitles. Maybe uploader of the subtitle added wrong metadata to subtitle, so subtitle seemed as bluray but let me show you how Plex OpenSubtitles search engine handle the same subtitle. It's perfect match in first result. (screenshot 2) Bazarr is super important for automation systems like radarr/sonarr but getting wrong subtitles again and againg ruining the user experience... It'd be appreciated If you to examine and invest this problem, it's a game changer issue (scoring, matching subtitles), thanks!

**To Reproduce**
1. Let bazarr download a subtitle (for Turkish in this situation)
2. see that subtitle is out of sync with movie
3. do manual search and check which subtitle grabbed (CAM release subtitle grabbed for 4k bluray in this situation)
3. check little yellow info icon which is saying source is matched ( but that is not true at all)

**Expected behavior**
 Bazarr must detect source from the title/hash/metadata (not sure) and can grab the right subtitle for the movies/shows. Maybe this conflict caused by opensubtitle metadata but If plex can handle matching/scoring easily and find right subtitle, so same thing expected for Bazarr too.

**Screenshots**
![image](https://user-images.githubusercontent.com/57859656/119980694-4f9bb880-bfc5-11eb-9727-4d2f1b9df84e.png)
Bazarr subtitle results, yellow info icon says both of the two results at the bottom is matched for source, It's obviously not matching tho

![image](https://user-images.githubusercontent.com/57859656/119981374-39dac300-bfc6-11eb-8730-a0b6ed0b86c1.png)
Same file with plex opensubtitles search engine, It is 720p but it's subtitle for bluray source, I checked and It's perfectly matched with audio.

**Software (please complete the following information):**
 Bazarr Version v0.9.5
Sonarr Version 3.0.6.1262
Radarr Version 3.2.0.5048
Operating System Windows-10
Python Version 3.8.0

**Additional context**
https://pastebin.ubuntu.com/p/pchtJsJBs4/ debug log of this wrong matched subtitle download.

**Comment by batuhankrmn** [comment]
![06 05 21 (18 43)](https://user-images.githubusercontent.com/57859656/120897312-1a7b1000-c62e-11eb-9753-9acf830fcb56.png)
![06 05 21 (18 44) (2)](https://user-images.githubusercontent.com/57859656/120897313-1bac3d00-c62e-11eb-90f3-8389b1613956.png)
![06 05 21 (18 44)](https://user-images.githubusercontent.com/57859656/120897314-1bac3d00-c62e-11eb-9fcb-46485d14129c.png)

I wish we can get metadata via subtitle name. It seems a tons of wrong uploaded to OpenSubtitles but it's still best tho. I can think the only solution is  getting metadata by subtitle name.

**Comment by Prince25** [comment]
Hi @morpheus65535. I'm not sure if my issue is the same as mine but it's definitely similar. For me, however, it doesn't download the subtitle at all. In the following example, it downloaded subtitles for every other episode automatically except for this particular episode. I can search and download the subtitle manually with no problem. I'm not sure what exactly the yellow info icon is showing but I don't think it's related to the issue since subtitles for other episodes also show this icon but they've downloaded automatically just fine. This issue is not exclusive to this particular show, it also occurs for other shows. I've looked through the wiki and tried googling about the yellow info icon but to no avail. I also tried changing my minimum score to 60%.

![image](https://user-images.githubusercontent.com/28243638/121481062-9c49a100-c980-11eb-8afb-4df1e01cabbc.png)

The yellow info icon shows: 
![image](https://user-images.githubusercontent.com/28243638/121481128-a9669000-c980-11eb-9639-59d9abe1a4b1.png)

**Comment by morpheus65535** [comment]
> Hi @morpheus65535. I'm not sure if my issue is the same as mine but it's definitely similar. For me, however, it doesn't download the subtitle at all. 

This is a totally different issue probably related to a misconfiguration. Please come by Discord channel to get support of the team.

**Comment by batuhankrmn** [comment]
I'll definitely check and give feedback. I am already on develop branch.

**Comment by batuhankrmn** [comment]
![06 11 21 (12 56)](https://user-images.githubusercontent.com/57859656/121669308-db790e80-cab4-11eb-9862-96c55ca27074.png)
Here is the scoring of the same file with latest develop build and looks like this is an obvious improvement! Cam releases have less score now and proper releases have higher matching in new scoring system. I have tried a few more searching and results were good without issue but I wonder If it's okey, what kind of improvement have done with latest release? Like checking subtitles names instead of metadata provided by subtitles providers? I can totally understand If you don't want to explain, cheers and thanks!

**Comment by morpheus65535** [comment]
It's a complete rework of the scoring system. You can take a look at this PR to get the specifics: https://github.com/morpheus65535/bazarr/pull/1437.
