### ISSUE TITLE
Subtitle search takes forever

### ISSUE THREAD

**Issue by Nakda** [morpheus65535/bazarr#1422]
**Describe the bug**
Performing a manual search on a single episode of a serie takes between 5 and 10 minutes. 

**To Reproduce**
1. Go to a Serie dedicated page, with seasons and episodes displayed
2. Click on the User icon (first of three), on an episode row
3. Click on Start Search
4. Wait

**Expected behavior**
Search result should be generated rather quickly (< 1 min).

**Screenshots**
Generated search results page
![image](https://user-images.githubusercontent.com/25755503/120217774-5b3ae980-c228-11eb-8524-046f3f6847d1.png)

**Software (please complete the following information):**
 - Bazarr: v0.9.5
 - Sonarr version 3.0.6.1196
 - OS: Rasperry Pi OS Lite (Linux raspberrypi 5.10.17-v7l+ #1414 SMP Fri Apr 30 13:20:47 BST 2021 armv7l GNU/Linux)

**Additional context**
- Podnapisi provider returns a SSLError on the providers status page

**Log file**
Debug mode enabled, and cleaned before starting the search
[bazarr_search.log](https://github.com/morpheus65535/bazarr/files/6571310/bazarr_search.log)

**Comment by morpheus65535** [comment]
Try to disable BSplayer and run the search again.

**Comment by Nakda** [comment]
There is still a SSLError for podnapisi, but the process is significantly faster (it took 35 seconds).
Should I keep BSplayer disabled? Or should I expect longer searches when using BSplayer?

[bazarr_searchbis.log](https://github.com/morpheus65535/bazarr/files/6571372/bazarr_searchbis.log)

**Comment by morpheus65535** [comment]
BSplayer is broken. No way to fix it for now.

As for Podnapisi it's caused by a config of openssl that require an SSL version higher than the one supported by Podnapisi. Check this: https://github.com/morpheus65535/bazarr/issues/927#issuecomment-613156380

**Comment by Nakda** [comment]
Ok, thanks. Didn't find this issue while looking for WRONG_SIGNATURE_TYPE. I will also disable Podnapisi then.
