### ISSUE TITLE
Broken with new Radarr nightly branch (Radarr v4.0.0.5077)

### ISSUE THREAD

**Issue by brettg0396** [morpheus65535/bazarr#1424]
It would appear that the latest commit to Radarr's nightly branch has "Removed Legacy API Support".

I suspect that that's to blame (and Bazarr is not the only radarr-connected service that has experienced failures since this update), but nevertheless, here is a sample error from my Bazarr logs:

```
Traceback (most recent call last):

  File "/opt/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job

    retval = job.func(*job.args, **job.kwargs)

  File "/opt/bazarr/bazarr/get_movies.py", line 166, in update_movies

    tags = [d[\'label\'] for d in tagsDict if d[\'id\'] in movie[\'tags\']]

  File "/opt/bazarr/bazarr/get_movies.py", line 166, in <listcomp>

    tags = [d[\'label\'] for d in tagsDict if d[\'id\'] in movie[\'tags\']]

TypeError: string indices must be integers
```

Attempting to test the connection in the "Radarr" settings of Bazarr simply hangs. All connection information is correct and - unless not-yet-documented changes need to be made to the standard reverse-proxy setup for Radarr - so is my webserver configuration.

Not the most formal issue submission, but as "downgrading" from the nightly branch is no easy task due to database changes, I thought it prudent to raise this issue as soon as possible.

**Comment by morpheus65535** [comment]
Thanks for reporting this. It's been fixed in latest beta.16.
