### ISSUE TITLE
Bazarr fails to start after auto update on QNAP NAS

### ISSUE THREAD

**Issue by Gaudi111** [morpheus65535/bazarr#1428]
**Describe the bug**
Bazarr fails to start after automatically updating on QNAP NAS installed as .qpkg.
Manually starting Bazarr fixes the issue until next update.

**To Reproduce**
Run Bazarr and wait until next update. Bazarr udpates correctly, but fails to start afterwards.
i.e.: v0.9.6 beta 18 is running, after a while, when new version is released, Bazarr seems to download and copy the files, but does not start. Process is not found running in NAS. 
Manually starting the script completes the startup and checking installed version in UI shows v0.9.6 beta 19.

**Expected behavior**
Autoupdate and start without hiccups.

**Screenshots**

**Software (please complete the following information):**
Bazarr Version: 0.9.6-beta.19
Sonarr Version: 3.0.6.1196
Radarr Version: 3.2.2.5080
Operating System: Linux-3.4.6-x86_64-with-glibc2.2.5 runnning on QNAP NAS TS-469 Pro
Python Version: 3.8.1

**Additional context**
For former versions this used to work (initial v0.9.6 beta versions, but cannot confirm exactly).
Tested by uninstalling and reinstalling NAS package, to no avail.

It may be related to the NAS package, but am unaware how to double check.

**Comment by Gaudi111** [comment]
Hi @morpheus65535 , I think I have spotted where the issue resides (at least what I could figure out).
The auto update script wipes the folder where it will decompress the new version. As the QNAP package stores some scripts in the same folder, this results in a non working version after update.
This may also result in deleting customizations that some users may have done.

Would it be possible to prevent this in the upgrade feature for your version?

In parallel I am checking with the QNAP package maintainer if he can address this by setting up a special folder where your release files should be located.


Thank you and regards

**Comment by halali** [comment]
This is way how bazarr update self... There is no plans to change it...

**Comment by Gaudi111** [comment]
Thank you, I have already contacted the QNAP package creator to request the modifications based on how the update method works. 

Regards
