### ISSUE TITLE
Mod OCR_fixed not loaded

### ISSUE THREAD

**Issue by modem7** [morpheus65535/bazarr#1433]
**Describe the bug**

Some subtitle downloads are throwing up the following error:

```
<!--StartFragment-->
Mod OCR_fixed not loaded | 08/06/2021 22:55:19 | &nbsp;
-- | -- | --
&nbsp; | Mod OCR_fixed not loaded | 08/06/2021 22:55:19 | &nbsp;
&nbsp; | Mod OCR_fixed not loaded | 08/06/2021 22:54:07

<!--EndFragment-->
```

**To Reproduce**
1. Try to manually scan for and download subtitles

**Expected behavior**
For subtitles to download and post process successfully 

**Screenshots**
![image](https://user-images.githubusercontent.com/4349962/121262862-b619b400-c8ac-11eb-8df6-72d3ed2e95f7.png)
![image](https://user-images.githubusercontent.com/4349962/121262487-270c9c00-c8ac-11eb-8706-e280bd7dd746.png)

**Software (please complete the following information):**
Bazarr Version v0.9.5
Sonarr Version 3.0.6.1196
Radarr Version 3.2.2.5080
Ubuntu 20.04

**Comment by morpheus65535** [comment]
This issue have been fixed in this commit from 0.9.4-beta-15: https://github.com/morpheus65535/bazarr/commit/7c61b3509c186b1c75db857bc481f2edcb931509

Simply open your config.ini file and replace `OCR_fixed` by `OCR_fixes` then restart Bazarr.
