### ISSUE TITLE
Embedded PGS track not being picked up by Bazarr

### ISSUE THREAD

**Issue by olimeca** [morpheus65535/bazarr#1434]
**Describe the bug**
Movie was upgraded by Radarr and the new movie has embedded English PGS subtitles. Bazarr is not recognizing the embedded PGS subtitle and instead is downloading subtitles as if they are missing. Ignore Embedded PGS is not enabled in settings. Clicking Scan Disk while viewing that movie in Bazarr does not force the embedded subtitle to appear.

**To Reproduce**
1) View updated Movie within Bazarr
2) Check Subtitle Path for embedded sub
3) Only newly downloaded external SRT is listed in Subtitle Path
4) Click Scan Disk but embedded track still does not appear

**Expected behavior**
When this movie is upgraded by Radarr and Bazarr picks up the change it should find the embedded PGS subtitles and ignore downloading new subtitles (depending on user settings). 

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: v0.9.5
 - Radarr version 3.2.1.5070
 - Sonarr version 3.0.6.1196
 - OS: Docker on Ubuntu

**Additional context**

**Comment by olimeca** [comment]
[bazarr.log](https://github.com/morpheus65535/bazarr/files/6625213/bazarr.log)
![PGSTrack](https://user-images.githubusercontent.com/72573700/121389867-d41dfd80-c91a-11eb-846e-aea938ce61c8.PNG)

**Comment by morpheus65535** [comment]
It works as expected in 0.9.6-beta.21. Can you give it a try?

**Comment by olimeca** [comment]
Same result. Clicking Scan Disk does not show the embedded PGS subtitle.

**Comment by morpheus65535** [comment]
Was caused by an outdated cached ffprobe result after an upgrade in Radarr. You can now simply click scan disk button in Bazarr for that movie or series and cache will be refreshed. Enjoy!
