### ISSUE TITLE
Language profiles cutoff not working as expected

### ISSUE THREAD

**Issue by danielb7390** [morpheus65535/bazarr#1435]
**Describe the bug**
I'm trying to use Language Profiles and the Cutoff feature. I expected bazarr to not download any more subs after the cutoff is met, but it's not what what is happening.

**To Reproduce**
1. Go to **Settings => Languages => Languages Profiles**
2. Click on **Add New Profile**
3. Add the following languages in order: **EN, PT, PT-BR**
4. Set cutoff to **ID 2 (PT)**
5. Associate a movie/show to this profile
6. Bazarr will download subtitles in **EN + PT + PT-BR**

**Expected behavior**
Since i set cutoff to **PT**, i expected bazarr to never download the **PT-BR** subtitle.

**Screenshots**
![image](https://user-images.githubusercontent.com/5844389/121406621-4a8c2100-c956-11eb-9456-b9ed0605d397.png)
![image](https://user-images.githubusercontent.com/5844389/121406636-4d871180-c956-11eb-8c42-afc8ee7bbc6a.png)
![image](https://user-images.githubusercontent.com/5844389/121406642-4fe96b80-c956-11eb-95a8-4758fb182088.png)

**Software:**
 - Bazarr: 0.9.5
 - Radarr 3.2.2.5080
 - Sonarr 3.0.6.1196
 - OS: Docker (Unraid)

**Comment by halali** [comment]
Once it start search it will download all languages from memory cutoff work only for next search...

**Comment by danielb7390** [comment]
Okay, so it works just not the way i thought it would? But i think what i'm asking also makes sense no?

**Comment by morpheus65535** [comment]
I've made a major rework of the DB queries in 0.9.6 (still beta). Can you give it a try by switching to development/nightly image tag?

**Comment by danielb7390** [comment]
![image](https://user-images.githubusercontent.com/5844389/121414517-a064c700-c95e-11eb-958d-abc4a2288b88.png)
![image](https://user-images.githubusercontent.com/5844389/121414580-b2466a00-c95e-11eb-99ae-64fb1b9bb26a.png)

Changed to last dev, same result.
Should i be cleaning the database?
Would a debug log help?

**Comment by morpheus65535** [comment]
In fact that the expected behavior although I agree it's not what you could be expecting. When searching for a series missing subtitles, we get all the missing subtitles in an array and iterate over it. We don't update the array if cutoff is reached. Of course, on the next run of search all missing subtitles, the new array will use the updated missing subtitles that will exclude pt-BR as pt as been found in previous run.

I think that what's @halali was saying in his comment.

I can see what I can do about this. Maybe I can fix this but it will implied a new call to db before every search to confirm if the subtitles is still missing.

**Comment by morpheus65535** [comment]
This fix will be included in upcoming 0.9.6-beta.23. Can you confirm it works as expected?

**Comment by danielb7390** [comment]
Yup, it's working! Thanks!

**Comment by maurogsp** [comment]
Hi, I'm still facing the issue where subtitles are being downloaded even if cutoff has been reached during the actual search. It only works during the second search, when subtitles were already downloaded. Is that the expected behavior or am I not setting things up properly? Thanks!

**Comment by morpheus65535** [comment]
> Hi, I'm still facing the issue where subtitles are being downloaded even if cutoff has been reached during the actual search. It only works during the second search, when subtitles were already downloaded. Is that the expected behavior or am I not setting things up properly? Thanks!

Don't know. Depends of what Bazarr version you are using. Come to Discord and once we confirm it's an actual issue, you'll be able to open a new one.
