### ISSUE TITLE
Bazarr on QNAP not automatic downloading subtitles 

### ISSUE THREAD

**Issue by jotavip** [morpheus65535/bazarr#1436]
Hi, I installed yeasterday Bazarr 0.9.5 on my QNAP, and it isn't searching automatically for subtitles. When I do a manual search for a series or movie wanted subtitle, it works. But the automatic task isn't working for me. I configured correct, the language profiles, providers and settings. 

Checked the debug log and when the task is suposed to run, It simply don't run. How can I fix this? Before that I was using version 0.9.2 and the automatic search was working.

**Comment by halali** [comment]
Did you setup correctly also timezone ?

**Comment by morpheus65535** [comment]
We don't support unofficial QNAP club package. You'll have to see with them. From here, it looks like your timezone isn't propagated from your OS to Bazarr.

**Comment by jotavip** [comment]
ok. Thanks very much. I will check this.
