### ISSUE TITLE
Bazarr need to be restarted to apply the last update

### ISSUE THREAD

**Issue by thyeestes** [morpheus65535/bazarr#144]
I have this message time after the task to update Bazarr from Github runs even if Bazarr hasn't been updated.

**Comment by morpheus65535** [comment]
Small fixes doesn't always implied a increment in Bazarr version. I suggest you restart it and see what's in the log when this message come up again.

**Comment by morpheus65535** [comment]
I'm closing this one. Open it back if you run into an issue like this again.
