### ISSUE TITLE
help wanted for tag

### ISSUE THREAD

**Issue by anschein** [morpheus65535/bazarr#1440]
Bazarr is the best with sonarr
For match the best subtitle,Is there any possible to have a tag function like Sonarr?

**Comment by morpheus65535** [comment]
I'm not sure I understand your question. If it's a configuration issue (Bazarr should use Sonarr tags) then come to Discord support channel. If it's a feature request, please open a FR on https://bazarr.featureupvote.com

**Comment by anschein** [comment]
thanks it`s a feature request and i`m going to the FR website
