### ISSUE TITLE
Radarr Nightly branch API issues

### ISSUE THREAD

**Issue by dixonbg** [morpheus65535/bazarr#1441]
Hello,

Bazarr v0.9.5 (Python 3.8.10) cannot talk to Radarr v4.0.0.5093

`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://test.test:7878/api/system/status?apikey=somekey`
`{
  "message": "NotFound"
}`

the call to `http://test.test:7878/api/v3/system/status?apikey=somekey` returns:
`{
  "version": "4.0.0.5093",
  "buildTime": "2021-06-12T03:09:13Z",
  "isDebug": false,
  "isProduction": true,
  "isAdmin": false,
  "isUserInteractive": true,
  "startupPath": "/app/radarr/bin",
  "appData": "/config",
  "osName": "ubuntu",
  "osVersion": "20.04",
  "isNetCore": true,
  "isMono": false,
  "isLinux": true,
  "isOsx": false,
  "isWindows": false,
  "isDocker": true,
  "mode": "console",
  "branch": "nightly",
  "authentication": "none",
  "sqliteVersion": "3.31.1",
  "migrationVersion": 195,
  "urlBase": "",
  "runtimeVersion": "5.0.5",
  "runtimeName": "netCore",
  "startTime": "2021-06-19T12:15:45Z",
  "packageVersion": "4.0.0.5093-ls95",
  "packageAuthor": "linuxserver.io",
  "packageUpdateMechanism": "docker"
}`

Will they fix their API? or should it be fixed in Bazarr?
Regards,
dixonbg

**Comment by morpheus65535** [comment]
Duplicate
#1424 and #1432
