### ISSUE TITLE
subs4series HTTPError again

### ISSUE THREAD

**Issue by sotiris-bos** [morpheus65535/bazarr#1442]
**Describe the bug**
Getting HTTPError for subs4series, at least for manual searches. I can browse the site and download just fine from other computers.

**Software (please complete the following information):**
 - Bazarr: v0.9.5
  - Sonarr version 3.0.6.1196
 - OS: Docker Linux

I am attaching a debug log.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/6681786/bazarr.log)

**Comment by morpheus65535** [comment]
They're now using a more recent version of cloudflare antibot that our version of cloudflare module can't bypass: `Access denied | www.subs4series.com used Cloudflare to restrict access`

For now I don't have a solution for this. I'll try to see what I can do about it in the future.

**Comment by morpheus65535** [comment]
It should be fixed in 0.9.6-beta.32. Can you test and confirm please?

**Comment by sotiris-bos** [comment]
The HTTP error is gone, however I am getting `Throttling subs4series for 10 minutes, until 21/06/24 13:51, because of: Exception. Exception info: 'AntiCaptcha class not given, exiting'` error now.

I know there is no anticaptcha provider for this subtitle provider, I do however have the suspicion than there is no anticaptcha implemented on the mobile site.

**Comment by morpheus65535** [comment]
Unfortunately they now require you to solve a reCaptcha to download a subtitles:

![image](https://user-images.githubusercontent.com/5130500/123262848-53d4cc00-d4c6-11eb-8691-bd95e6ad5884.png)

Switching to mobile site would require a complete rewrite. TBH, if we start hitting their mobile site massively, they will simply add raCaptcha there also...

**Comment by sotiris-bos** [comment]
Yeah that is what I thought as well, I will try with an Anti-Captcha provider and see if it works.

HTTPError is gone though so I guess consider it fixed!

**Comment by morpheus65535** [comment]
Keep me informed if it's not completely fixed!
