### ISSUE TITLE
Throttling subs4series for 10 minutes, until 21/06/24 17:08, because of: HTTPError.

### ISSUE THREAD

**Issue by panaris** [morpheus65535/bazarr#1449]
**Describe the bug**
It give me the following error when I try to download from subs4series provider. 
Throttling subs4series for 10 minutes, until 21/06/24 17:08, because of: HTTPError. Exception info: '403 Client Error: Forbidden for url: https://www.subs4series.com/search_report.php?search=greys%20anatomy&searchType=1'

**Software (please complete the following information):**
 - Bazarr: v0.9.5
 - Radarr version v3.2.2.5080
 - Sonarr version v3.0.6.1265
 - OS: Windows 10

**Comment by morpheus65535** [comment]
Fixed in dev branch. Now require anti-captcha provider.
