### ISSUE TITLE
[Subsynchro] Error when downloading subtitle file

### ISSUE THREAD

**Issue by Adelscott** [morpheus65535/bazarr#1450]
**Describe the bug**
Error when processing subtitle zip file 

**To Reproduce**
Couldn't convert subtitle <SubsynchroSubtitle 'https://www.subsynchro.com/telecharger-le-fichier-61276-wrath-of-man-2021-1080p-amzn-web-dl-ddp5-1-h-264-tepes-srt.html' [fr:iso-8859-15]> to .srt format: Traceback (most recent call last): File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/subtitle.py", line 287, in is_valid subs = pysubs2.SSAFile.from_string(text) File "/app/bazarr/bin/bazarr/../libs/pysubs2/ssafile.py", line 126, in from_string return cls.from_file(fp, format_, fps=fps, **kwargs) File "/app/bazarr/bin/bazarr/../libs/pysubs2/ssafile.py", line 153, in from_file format_ = autodetect_format(fragment) File "/app/bazarr/bin/bazarr/../libs/pysubs2/formats.py", line 67, in autodetect_format raise FormatAutodetectionError("No suitable formats")pysubs2.exceptions.FormatAutodetectionError: No suitable formats	

**Software (please complete the following information):**
Bazarr version: v0.9.5
Bazarr branch: master
Operating system: Linux-3.10.105-x86_64-with
Python version: 3.8.10

**Additional context**

**Comment by vitiko98** [comment]
It should be fixed in the next beta release. Please confirm.

**Comment by Adelscott** [comment]
> 
> 
> It should be fixed in the next beta release. Please confirm.

Ok with development-version-v0.9.6-beta.33 !
