### ISSUE TITLE
Radarr 4.0x version causing API HTTP exceptions

### ISSUE THREAD

**Issue by jaretclifton** [morpheus65535/bazarr#1452]
**Describe the bug**
Updating to Radarr version 4 builds have created HTTP exceptions for Bazarr. Unable to complete test connectivity check and all updates of movie lists return the same failure:

File "/opt/bazarr/bazarr/filesystem.py", line 79, in browse_radarr_filesystem

    r.raise_for_status()

  File "/opt/bazarr/bazarr/../libs/requests/models.py", line 940, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://OBFUSCATED:7878/api/filesystem?path=%5C&allowFoldersWithoutTrailingSlashes=true&includeFiles=false&apikey=OBFUSCATED

**To Reproduce**
1. Go to Settings -> Radarr
2. Click on Test
3. Page appears to do nothing.
4. View logs and you will see the errors.
5. This is also visible on the scheduled task for movie list sync.

**Expected behavior**
API connectivity completes successfully.

**Screenshots**
N/A

**Software (please complete the following information):**
 - Bazarr: 0.9.5
 - Radarr version 4.0.0.5109
 - Sonarr version 3.0.6.1265
 - OS: Ubuntu Linux 18.04 LXC Container

**Additional context**
N/A

**Comment by morpheus65535** [comment]
Fixed in upcoming 0.9.6. You can try searching for issue first next time :-P

**Comment by jaretclifton** [comment]
> Fixed in upcoming 0.9.6. You can try searching for issue first next time :-P

Apologies for wasting your time! I will make sure I search before I post next time. :)
