### ISSUE TITLE
Bazarr Proxy field Ignored Addresses is being parsed incorrectly

### ISSUE THREAD

**Issue by aim60** [morpheus65535/bazarr#1453]
**Describe the bug**
Bazarr Proxy field Ignored Addresses is being parsed incorrectly.

**To Reproduce**
1. Go to Settings | General | Proxy
2. Select proxy type HTTP(S)
3. Enter Host address 10.10.10.10
4. Enter Port 8118
5. In field Ignored Addresses, add ip address 10.10.10.10
6. Click Save
7. View the incorrect proxy configuration in config.ini

[proxy]
type = http
url = 10.10.10.10
port = 8118
username = 
password = 
exclude = ['localhost', '127.0.0.1', '10', '10', '10', '10']

**Software (please complete the following information):**
 - Bazarr: [e.g. v 0.9.5]
 - OS: Docker - linuxserver or hotio

**Comment by morpheus65535** [comment]
Can you confirm if it's still an issue in 0.9.6-beta? You can use hotio nightly image tag.

**Comment by aim60** [comment]
Same results hotio nightly-0.9.6-beta.34

**Comment by morpheus65535** [comment]
Should be fixed in beta.35. Can you test and confirm please?

**Comment by aim60** [comment]
Confirmed working in beta.35.  I'm new to bazarr.  Thanks for the great app.
