### ISSUE TITLE
Bazarr shows 0 results for subdivx but manually getting same url shows 1

### ISSUE THREAD

**Issue by Panderine** [morpheus65535/bazarr#1454]
**Describe the bug**
When I search using subdivx provider, bazarr shows 0 results, but if I manually use the same URL I get hits

**To Reproduce**
1. URL in logs> https://www.subdivx.com:443/index.php?q=Rick+and+Morty+S05E02&accion=5&oxdown=1&pg=1
2. Via browser I get 1 hit.
3.  Via Bazarr I dont get any
[bazarr.log](https://github.com/morpheus65535/bazarr/files/6728920/bazarr.log)

**Expected behavior**
find same results.

**Screenshots**
![image](https://user-images.githubusercontent.com/4042199/123695448-f11a6200-d830-11eb-952f-fcd0d5b00e41.png)

**Software (please complete the following information):**
 - Bazarr: v0.9.6-beta.34
 - OS: linux

**Comment by vitiko98** [comment]
What languages are you using? Subdivx is (mostly) a LATAM Spanish provider now.

**Comment by morpheus65535** [comment]
Can't reproduce:
![image](https://user-images.githubusercontent.com/5130500/124026334-8e0b0580-d9bf-11eb-80a7-b11a32d7ce62.png)

**Comment by morpheus65535** [comment]
> What languages are you using? Subdivx is (mostly) a LATAM Spanish provider now.

From his log:
`|Listing subtitles with provider 'subdivx' and languages {<Language [es]>, <Language [es-MX]>}|`

**Comment by Panderine** [comment]
using spanish and Latin American Spanish (ea and es)

**Comment by Panderine** [comment]
![image](https://user-images.githubusercontent.com/4042199/124027582-6d47ad80-d9c9-11eb-9909-b4e591d5456d.png)

**Comment by Panderine** [comment]
![image](https://user-images.githubusercontent.com/4042199/124027737-936d4d80-d9c9-11eb-9f76-3557e49170c2.png)

**Comment by morpheus65535** [comment]
The issue was caused by the year in series directory name that wasn't present in subtitles title on the provider website. I've added a validation to confirm if there's a year in title before comparing it with the one from video object.

Please test the upcoming beta and confirm.

**Comment by Panderine** [comment]
fixed
