### ISSUE TITLE
Wizdom.XYZ provider does not work

### ISSUE THREAD

**Issue by hasamba** [morpheus65535/bazarr#1456]
**Describe the bug**
wizdom provider returns HTTPError

**To Reproduce**
1. choose wizdom provider
2. search for any movie/tv sub

**Expected behavior**
download sub

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: [e.g. v 0.9.5]
 - Radarr version v 3.2.2.5080
 - Sonarr version v 3.0.6.1265
 - OS: Docker on Ubuntu Server

**Additional context**
log: https://pastebin.com/ZPKmPpJp

**Comment by morpheus65535** [comment]
I can't reproduce. Please disable all other providers, enable debug logging and reproduce the issue. Provide the debug log here for investigation.

**Comment by hasamba** [comment]
i hope this is enough:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/6754210/bazarr.log)

**Comment by morpheus65535** [comment]
I,ve made an attempt to fix in in upcoming 0.9.6-beta.38. Test it and confirm please.

**Comment by hasamba** [comment]
now i dont get anything in the log but no subtitle is downloaded also
![2021-07-05_744](https://user-images.githubusercontent.com/7392290/124442473-721faf00-dd85-11eb-8474-c273be492ea7.gif)

**Comment by morpheus65535** [comment]
Don't change the test case without confirming if the original one is fixed. This could be a totally different issue.

**Comment by hasamba** [comment]
i dont understand, what test case did i change?

**Comment by morpheus65535** [comment]
> i dont understand, what test case did i change?

You were searching subtitles for Asia (2020). If you search for another movie, please provide a debug log. I've search for movies and series and it works fine for those I've tested.

**Comment by hasamba** [comment]
here is another screenshot,
im searching for another movie, it's says complete but nothing is in the log and no subtitle was downloaded
![2021-07-06_755](https://user-images.githubusercontent.com/7392290/124602640-be481d80-de71-11eb-97e8-63744e2ef581.gif)

**Comment by morpheus65535** [comment]
It just can't find a subtitles for your movie. Can you try a manual search and show me the results modal?

**Comment by hasamba** [comment]
manual seems to work fine, thanks
