### ISSUE TITLE
Colornames in bazarr settings doesn't match colornames in subzero

### ISSUE THREAD

**Issue by andrsm** [morpheus65535/bazarr#1457]
subzero spells colors with two names with an "-", bazarr spells it without. Ex dark-grey and darkgrey.
So in subtitles settings and tools for color does nothing for these colors.

I think colornames in these files:
frontend/src/Settings/Subtitles/options.ts
bazarr/frontend/src/components/modals/toolOptions.ts 

needs to match the colornames in this file
libs/subzero/modification/mods/colors.py

 - Bazarr: [e.g. v 0.9.5]

**Comment by morpheus65535** [comment]
Should be fixed. Can you test and confirm please?

**Comment by andrsm** [comment]
Fix confirmed
