### ISSUE TITLE
Discord Notification Issues

### ISSUE THREAD

**Issue by Gingey231** [morpheus65535/bazarr#146]
Morning All,

Noticed this morning my log was absolutely stacked with errors for the Discord Notification that I am trying to use for Notifications.

Doing all the normal things, create webhook in discord, copy that URL, popped into the `Discord` field in `Notifications`, and all I'm getting are the below errors:

`Failed to load notification url: https://discordapp.com/api/webhooks/491650316685672458/JEySTejUcJid_BiUWHj9TFYqjKfNoQ-d0U5uRkHRJwnt3036b13gO2SyJj6KK75M8PC9/`
+
`https is not a supported server type (url=https://discordapp.com/api/webhooks/491650316685672458/JEySTejUcJid_BiUWHj9TFYqjKfNoQ-d0U5uRkHRJwnt3036b13gO2SyJj6KK75M8PC9/)`

I know somethings only like it when the webhook has /slack appended to it, which i have tried but same error. Have also created a couple of test webhooks and each failing the same.

I have also tried adding into the Slack notification field but getting the same error (With and without the `/slack` on the end of the URL).

Definitely not an urgent one so one!

Cheers

**Comment by halali** [comment]
https://github.com/caronc/apprise/wiki/Notify_discord
and use valid syntax for discord started with discord://

**Comment by morpheus65535** [comment]
Does it fix your issue?

**Comment by Gingey231** [comment]
Morning all!

Many apologies, just seen this response. Tested using both of the methods from the article and all seems to be working :)

Cheers lads

**Comment by morpheus65535** [comment]
Have fun!
