### ISSUE TITLE
Bazarr error connecting to Sonarr

### ISSUE THREAD

**Issue by ionutm80** [morpheus65535/bazarr#1460]
Hi, I'm getting this error when Bazarr try to connect to Sonarr, with Radarr everything is fine. All version are main branch.

13/06/2021 14:25:11|ERROR   |apscheduler.executors.default   |Job "Update Series list from Sonarr (trigger: interval[0:01:00], next run at: 2021-06-13 14:26:11 EEST)" raised an exception|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File "/app/bazarr/bin/bazarr/get_series.py", line 56, in update_series\n    current_shows_db_list = [x[\'sonarrSeriesId\'] for x in current_shows_db]\n  File "/app/bazarr/bin/bazarr/get_series.py", line 56, in <listcomp>\n    current_shows_db_list = [x[\'sonarrSeriesId\'] for x in current_shows_db]\nTypeError: string indices must be integers'|

**Comment by ionutm80** [comment]
See below a screenshot of the error in Bazarr:
![01528F3B-C088-4C2E-85F8-2F859BE4DBB5](https://user-images.githubusercontent.com/68031938/124346829-b70ede80-dbe9-11eb-918e-5f93e14e6f98.jpeg)

**Comment by ionutm80** [comment]
When I test connection with Sonarr it works.
![5AD7E8F1-2659-4E0E-ACB9-E9A225925C20](https://user-images.githubusercontent.com/68031938/124346950-559b3f80-dbea-11eb-935b-a51eda140abe.png)

**Comment by ionutm80** [comment]
When I test connection with Sonarr it works:
![971DB7CC-4040-4BBE-8A5E-2210890D7C65](https://user-images.githubusercontent.com/68031938/124347004-91cea000-dbea-11eb-9450-3cbc29912f49.jpeg)

**Comment by morpheus65535** [comment]
Corrupted database. Stop Bazarr and delete bazarr.db. For support, come to Discord.
