### ISSUE TITLE
Mem usage ballooning after episode/movie update from disk at 4am

### ISSUE THREAD

**Issue by aptalca** [morpheus65535/bazarr#1465]
**Describe the bug**
Memory usage goes up after episode and movie update from disk at 4am everyday and does not go back down after.

**To Reproduce**
1. Set up a docker container with the linuxserver image
2. Add a bunch of shows and movies, wait until 4am
3. Check mem usage via `docker stats bazarr` as well as `docker exec -it bazarr top` (res usage)

**Expected behavior**
Mem usage going down after task completion

**Screenshots**

![Screenshot 2021-07-10 10 42 53](https://user-images.githubusercontent.com/541623/125167356-16cb3380-e16e-11eb-9d8c-4cbbe3ac7c50.png)
This screenshot shows the resident memory usage of bazarr over 4 days. Everyday at 4am, it goes up with the episode and movie update from disk, but does not go back down after. The numbers match the output of docker stats and top inside the container for redsident mem usage.

**Software (please complete the following information):**
 - Bazarr: v0.9.5
 - Radarr version 3.2.2.5080
 - Sonarr version 3.0.6.1265
 - OS: Linux-5.4.0-73-generic-x86_64-with
 - Python Version: 3.8.10

**Additional context**
Using the linuxserver docker image, latest (stable) tag
Have a rather large library, with 667 currently wanted items

Also, not sure if it's related, but even though clicking on movie history works fine, I get a 500 error when I click on episode history. Here's the trace from the log
```
Traceback (most recent call last):

  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request

    rv = self.dispatch_request()

  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1935, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

  File "/app/bazarr/bin/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper

    resp = resource(*args, **kwargs)

  File "/app/bazarr/bin/bazarr/../libs/flask/views.py", line 89, in view

    return self.dispatch_request(*args, **kwargs)

  File "/app/bazarr/bin/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request

    resp = meth(*args, **kwargs)

  File "/app/bazarr/bin/bazarr/api.py", line 66, in wrapper

    return actual_method(*args, **kwargs)

  File "/app/bazarr/bin/bazarr/api.py", line 1276, in get

    item[\'score\'] = str(round((int(item[\'score\']) * 100 / 360), 2)) + "%"

ValueError: invalid literal for int() with base 10: \'i\
```

Oh and also, the media is on an rclone mount of google drive. Bazarr does not seem to have any issues with putting new subs there.

Thanks

**Comment by morpheus65535** [comment]
Hey @aptalca, I've tried to reproduce the memory leak issue without any success. Did you try with 0.9.6-beta to confirm if you have the same issue? I've made a lot of improvement in 0.9.6 so it could already "fixed".

Regarding your episode history, you probably have a row in your DB `table_history` table with garbage in the `score` column. You can take a look at it or come see me on Discord and I'll clean it for you.

**Comment by aptalca** [comment]
Cool, I'll give the beta a try, I'll also dig into the database. Although I'm moving right now so it may be a week or so before I get to it. I'll let you know.

Thanks

**Comment by aptalca** [comment]
Yup, tested the development tag and the memory usage remains stable through the disk scans. It looks like it's already fixed.

I also looked through the `table_history` table and there was indeed a garbage entry. Removed it and I can view the episode history again.

Thanks

**Comment by morpheus65535** [comment]
Excellent news! Thank for reporting!
