### ISSUE TITLE
api/system/status endpoint does not require API key

### ISSUE THREAD

**Issue by jamesmacwhite** [morpheus65535/bazarr#1467]
**Describe the bug**

Not exactly a bug, but more curious, Both Sonarr and Radarr require the API key for the /api/system/status endpoint, but with Bazarr you can access this unauthenticated. While it doesn't have any sensitive info really, it seems to be a deliberate change made specifically for Bazarr, just wondering why that is? Other endpoints do require the API key as expected.

It seems `@authenticate` (sorry for accidentally pinging the GiHub user authenticate!) was removed from this call:

https://github.com/morpheus65535/bazarr/blob/2bceafe5af9dbd5cb5d7a3aba719dd88f838ef4d/bazarr/api.py#L523-L533

**Comment by morpheus65535** [comment]
My mistake, thanks for reporting!

**Comment by jamesmacwhite** [comment]
Thanks for fixing!
