### ISSUE TITLE
Radarr v1 API is not supported in v4 - Bazarr incompatible with Radarr v4

### ISSUE THREAD

**Issue by bakerboy448** [morpheus65535/bazarr#1469]
https://github.com/morpheus65535/bazarr/blob/2bceafe5af9dbd5cb5d7a3aba719dd88f838ef4d/bazarr/utils.py#L247

looks like this line and several others need updating.

the v1 API is dead in radarr nightly/v4  only the V3 api is supported

**Comment by morpheus65535** [comment]
Duplicate of at least 5 issues... use search please. Fixed in 0.9.6-beta.

**Comment by bakerboy448** [comment]
yup that one is on me; should have expanded my search query a bit
