### ISSUE TITLE
Error trying to get video information for this file

### ISSUE THREAD

**Issue by drlmorice** [morpheus65535/bazarr#1472]
**Bug description**
I am new to Bazarr but love the program
I have unfortunately not been able to get it working yet.
I completed the setup after following the guide here: https://wiki.bazarr.media/
No issues were identified during setup but now the program is running, I am not getting any subtitles and the error below is what occurs for every movie
"Error trying to get video information for this file"

**Log of error**
Traceback (most recent call last):
  File "c:\\bazarr\\bazarr\\get_subtitle.py", line 70, in get_video
    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,
  File "c:\\bazarr\\bazarr\\../libs\\subzero\\video.py", line 61, in parse_video
    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,
  File "c:\\bazarr\\bazarr\\../libs\\subliminal_patch\\core.py", line 557, in scan_video
    video.size = os.path.getsize(hash_path)
  File "C:\\Bazarr\\WinPython\\python-3.8.0\\lib\\genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [WinError 3] The system cannot find the path specified: \'C:\\\\Volumes\\\\8TBHDD\\\\Movies\\\\The Nun (2018)\\\\The Nun (2018) - [BLURAY-1080P][DTS 5.1][X264]-GECKOS The Movie Title (2010) - [ULTIMATE EXTENDED EDITION][BLURAY-1080P PROPER][DTS 5.1][X264]-EVOLVE.mkv\

Any help with this is greatly appreciated as I have a few movies that I really need forced subtitles for. 

**log file**
[bazarr.log](https://github.com/morpheus65535/bazarr/files/6835916/bazarr.log)

**Comment by halali** [comment]
Im sure you didnt read wiki at all.
You need set path mapping.

If you need support please come to diacord. This is only for issues.
