### ISSUE TITLE
Wanted Series Order changed from ascending to descending

### ISSUE THREAD

**Issue by littlerooster** [morpheus65535/bazarr#1475]
**Describe the bug**
So far (before v.0.9.6), wanted Series episodes, showed the latest synced files on first pages. Whereas, now with v.0.9.6 this has changed, and they now appear on the last page. 

**Software (please complete the following information):**
**Bazarr Version** 0.9.6
**Sonarr Version** 3.0.6.1265
**Radarr Version** 3.2.2.5080
**Operating System** Linux-5.4.0-77-generic-x86_64-with
**Python Version** 3.8.10

**Additional context**
It's no biggie, but this new ordering is kinda counter-productive. I would say a solution here would either be to return it back to its old ordering or allow the user to select which ordering they prefer.

**Comment by morpheus65535** [comment]
Fixed in upcoming 0.9.7-beta.0. Thanks for reporting!
