### ISSUE TITLE
Permission setting

### ISSUE THREAD

**Issue by zebbe152** [morpheus65535/bazarr#1478]
I've enabled the "Permission (chmod)" setting. When I download a subtitle bazarr applies the permissions I've entered.

However if I use one of the tools on the subtitle (OCR fixes, Common Fixes, Sync subtitle etc) the permissions changes back to the default permissions again, not the one I've entered in the settings.

 - Bazarr: 0.9.6
 - FreeBSD

**Comment by morpheus65535** [comment]
Should be working as expected in upcoming 0.9.7-beta.4. Can you test and report please?

**Comment by zebbe152** [comment]
It works just fine! Thanks for the quick fix!

**Comment by morpheus65535** [comment]
Pleasure!

**Comment by morpheus65535** [comment]
> I am still seeing this issue. Essentially the same as described. It appears that the correct permissions are set on download but after processing, they revert to default.

Was missing a fix for this with custom post-processing. Should be fixed in upcoming beta.
