### ISSUE TITLE
bazarr unable to find subtitles

### ISSUE THREAD

**Issue by poplolnman** [morpheus65535/bazarr#148]
hi. whenever i click the find missing subtitles button i get this page:

![screenshot_13](https://user-images.githubusercontent.com/12866874/45907954-3380fb80-bdc8-11e8-86b0-b6a377cedc5c.png)

and here are the logs:

[bazarr.log](https://github.com/morpheus65535/bazarr/files/2407166/bazarr.log)

**Comment by morpheus65535** [comment]
How long did you wait after configuring Bazarr? It look like you're still running the initial scan.

**Comment by morpheus65535** [comment]
From what I see in your log file, Radarr is returning trough his API many corrupted movies. You cannot have `movieFile` key missing if Radarr say that `hasFile` is true. I've added a check to skip those movie in Bazarr but that's just a band-aid.

**Comment by ShadXo** [comment]
Did it work before?

Kind of look like the screen I get when there is a bazarr update, maybe you need to restart bazarr.

**Comment by morpheus65535** [comment]
Should be fixed in 0.6.5.
