### ISSUE TITLE
Downloaded subtitles episode mismatch

### ISSUE THREAD

**Issue by Nakda** [morpheus65535/bazarr#1481]
**Describe the bug**
Bazarr identifies subtitles of S02E01 as valid, whereas we are looking for subtitles for S01E01.

**To Reproduce**
1. Go to Serie page, and nagivate to S01E01
2. Click on Manual Search

**Expected behavior**
Bazarr should flag S02E01 as an invalid match.

**Screenshots**
![image](https://user-images.githubusercontent.com/25755503/126771689-f730329a-5d30-421e-8b2e-4b28121b3fea.png)

**Software (please complete the following information):**
 - Bazarr: 0.9.6
 - Sonarr: 3.0.6.1265
 - OS: Rasperry Pi OS Lite

**Comment by morpheus65535** [comment]
We only show the release name here without parsing it or validating it at all. This specific subtitles is probably classified as S01E01 and this is why the BetaSeries API is returning it. It can happen from time to time and there's not much we can do about it. Providers some time are wrong.
