### ISSUE TITLE
bazarr cant detect episodes from sonarr in order to scan the subtitle... any idea check the image 

### ISSUE THREAD

**Issue by makhatib** [morpheus65535/bazarr#1482]
**Describe the bug**

**To Reproduce**
1. Go to 'series'
2. Click on 'any series'
4. See error no episode at all 

**Expected behavior**
bazarr cant detect episodes from sonarr

**Screenshots**
![image](https://user-images.githubusercontent.com/16227316/126788506-82a9b57a-41ff-4b68-bc15-afb1bc55a02e.png)
![image](https://user-images.githubusercontent.com/16227316/126788649-54ef7d38-a2db-4b95-89cd-354ed453293e.png)

**Software (please complete the following information):**
Bazarr Version
0.9.6
Sonarr Version
10.0.0.32815
Radarr Version
10.0.0.32906
Operating System
Linux-5.10.27-gentoo-whatbox-x86_64-Intel-R-_Xeon-R-_CPU_E5-2697_v4_@_2.30GHz-with-glibc2.33

**Additional context**
check the log in the below link 
https://hastebin.com/ipupufoveh.sql

**Comment by morpheus65535** [comment]
Sonarr and Radarr doesn't have version 10.x. Lates versions are in 3.x. I suppose those are whatbox modified versions. That's a pretty bad idea and I'm not supporting custom build like those one. Sorry but you'll have to deploy the official Sonarr and Radarr package.

**Comment by morpheus65535** [comment]
I've made some changes in upcoming v0.9.7-beta.3 that should make it works again. Nevertheless, I do not recommend or support custom build for Sonarr and/or Radarr.

**Comment by makhatib** [comment]
thanks for your understand the problem and you support 

i already send your replay to whatbox team and i think they fix the issue from their side 

but till now i didn't get the official answer from them but yeah my bazarr now working 

i think they change the version of sonarr and radarr as below 

Bazarr Version
0.9.6
Sonarr Version
3.0.0.0
Radarr Version
3.0.0.0
Operating System
Linux-5.10.27-gentoo-whatbox-x86_64-Intel-R-_Xeon-R-_CPU_E5-2697_v4_@_2.30GHz-with-glibc2.33
Python Version
3.9.5

thanks again Morpheus

**Comment by makhatib** [comment]
Whatbox answer 


For some reason, despite not doing this for Radarr, Bazarr was checking Sonarr's version and strictly requiring it to be 3.*.

Thanks again

**Comment by binitGajera** [comment]
I was also facing this issue in Whatbox, I was tracking this issue in GitHub, and can verify that for me also the issue was resolved. Thanks @makhatib for sending the ticket to Whatbox, I see the same version now that you posted. Thanks to @morpheus65535 too for the support.

**Comment by morpheus65535** [comment]
Thanks guys for the feedback!
