### ISSUE TITLE
Inconsistency in Wanted List

### ISSUE THREAD

**Issue by rmichelena** [morpheus65535/bazarr#1483]
The list of Wanted subtitles can get out of sync with the actual missing subtitles and it's count.
e.g. in my case, the "wanted"->"series" submenu shows a badge indicating a count of 79 ; but the list itself is 100 items long, does display the count of 100 in the bottom (pages) count, and does show 100 items.
Some of these items, however, when verified in the show's page, are existing subtitles that should not appear as "wanted"; and a look at the directory shows they indeed exist.
Doing a "scan disk" on the show's page, waiting 24 hours, and restarting nothing makes those phantom "wanted" subtitles go away from the list. 

How did it happen? not entirely sure, but it'd seem those are subtitles that were obtained through manually clicking the purple "search" loupe in the episode's line on the show's page. They were found, downloaded, updated on the show's page, but not taken off the displayed "wanted" list.

Bazarr 0.9.6 on Docker, Ubuntu 18.0.4.5 LTS

<img width="1307" alt="Screen Shot 2021-07-26 at 06 17 06" src="https://user-images.githubusercontent.com/77797875/126980731-0c3233c2-48c3-4689-95f4-107b38f434a3.png">
<img width="1315" alt="Screen Shot 2021-07-26 at 06 18 10" src="https://user-images.githubusercontent.com/77797875/126980790-c7650601-9d3f-4316-9bbc-8993edc48203.png">

**Comment by morpheus65535** [comment]
Did you try to refresh the browser window? It could be a data caching issue on client side because of events not sent from server to client.

**Comment by rmichelena** [comment]
Refreshing didn't seem to do much, but quitting the browser and restarting did the trick. So it should be indeed some data caching issue.

**Comment by morpheus65535** [comment]
You wanna give a try to the beta version just in case? LSIO and hotio both provide development/nightly tags.

**Comment by morpheus65535** [comment]
@LASER-Yi is that one fixed?

**Comment by LASER-Yi** [comment]
> @LASER-Yi is that one fixed?

Yep

**Comment by morpheus65535** [comment]
> Yep

Thanks!
