### ISSUE TITLE
Synced subtitles leftovers

### ISSUE THREAD

**Issue by rmichelena** [morpheus65535/bazarr#1484]
Every now and then on the directories, I'm finding synced subtitles that have not been renamed...
show.s01e03.en.srt
show.s01e03.en.synced.srt

and they're indeed different in timing.

syncing is triggered automatically by thresholds.

bazarr 0.9.6 on Docker, Ubuntu 18.0.4.5

**Comment by morpheus65535** [comment]
https://wiki.bazarr.media/Troubleshooting/FAQ/#synchronization-failed
