### ISSUE TITLE
Struggling due to large library.

### ISSUE THREAD

**Issue by stevezau** [morpheus65535/bazarr#1487]
**Describe the bug**
Hi, I have a very large lib. I've noticed Bazarr is struggling to keep up during sync tasks. Is there an option to change the frequency to reduce the load? 

**Software (please complete the following information):**
 - Bazarr:Latest from docker

**Comment by costaht** [comment]
You can change the sync frequency in Settings > Scheduler.

Issues are used to address problems with the software. If you need further help, refer to the [Discord channel](https://discord.gg/txGZG7P2)
