### ISSUE TITLE
WorkingDirectory not honored, data/config is always saved on Bazarr install folder

### ISSUE THREAD

**Issue by pkreuzt** [morpheus65535/bazarr#1490]
**Describe the bug**

I created a system user for Bazarr with home in /var/lib/bazarr. This alone didn't make Bazarr save its config on that folder, so I specified: 

`WorkingDirectory=/var/lib/bazarr`

 in systemd service file. That didn't work either, and config/data is always stored on install folder (/opt/bazarr in my setup). Not sure if this is the intended behavior, but it's clearly suboptimal.

**Expected behavior**

Bazarr should save its config on the home of the user running the service, or at least have a directive to change data and config location that works.

**Software (please complete the following information):**
 - Bazarr: v0.9.6
 - Radarr version: v3.2.2.5080
 - Sonarr version: v3.0.6.1265
 - OS: Debian Bullseye, arm64

**Comment by morpheus65535** [comment]
To save config to another directory, you need to specify the `--config` args. There's no other way.
