### ISSUE TITLE
Keeps downloading unmonitored episodes (Rick and Morty)

### ISSUE THREAD

**Issue by bassterror** [morpheus65535/bazarr#1491]
**Describe the bug**
I didn't notice at first, but since the last update, Bazarr keeps downloading subtitles for Rick and Morty episodes that are unmonitored. I'm constantly removing them manually and on the next day, they are back in. The episodes are not shown in the "Wanted" section, they are correctly marked as unmonitored in the "Series" section, but it keeps downloading them constantly. Also, some of the subtitles are marked as "HI" which is set to false in the "language profile" (not to mention that in my language there are no Hearing Impaired subtitles). This bug seems to be related only to this TV show (I can't seem to find other unwanted episodes or movies, and the "History" section doesn't show such ones).

**Screenshots**
[TV Show](https://ibb.co/Y7Vjpy7)
[Wanted](https://ibb.co/m4ffv98)
[History](https://ibb.co/TkpftkG)

**Software (please complete the following information):**
 - Bazarr: 0.9.6
 - Radarr: 3.2.2.5080
 - Sonarr: 3.0.6.1265
 - OS: Linux-4.4.59+-x86_64-with

**Comment by morpheus65535** [comment]
Did you enable `Download Only Monitored` in `Settings-->Sonarr`?

As for HI, when you uncheck the HI box in language profiles, it won't ignore HI, it will get one or the other (HI or non-HI). If you check the HI box, you'll simply get HI subtitles.

**Comment by bassterror** [comment]
Yes, the `Download Only Monitored` is enabled. And again, this is happening only with `Rick and Morty`. There are hundreds of other episodes that are unmonitored, but they are not downloaded.

**Comment by morpheus65535** [comment]
Can you try to scan disk for this show just to be sure it's properly indexed? It's really weird if it happens only to this show...

**Comment by bassterror** [comment]
I scanned the show and I deleted the subtitles again. I'll report back tomorrow if there is any progress. Also, the same thing happened to the `The Grand Tour` show. Yesterday, Bazarr downloaded the subtitles for all the episodes even though they are unmonitored.

**Comment by morpheus65535** [comment]
I tried to reproduce with Rick and Morty S05E01 and wasn't able to. Monitored status is always taken into consideration. Can you provide your config.ini and bazarr.db in private on Discord?

**Comment by bassterror** [comment]
As it seems the issue is resolved. Since I did a full rescan of all TV shows a couple of days ago, no unwanted downloads occurred. Maybe the problem was indeed a problematic index or something. Thank you @morpheus65535!

ps: I guess you can add this to the FAQ in Bazarr Wiki.

**Comment by s1p2a3m** [comment]
It's happening to me too for episodes, movies work correctly (when I mark it as unmonitored it stops being wanted).
But episodes no matter if they are monitored or unmonitored they are still wanted.

Of course the option `Download Only Monitored` is enabled.
Kind of did every tasks available, restarted the service, marked it as monitored/unmonitored... not sure what else I can try.

Not sure if the show is at fault, but for the ones I've noticed it is `The West Wing`,`Q: Into the Storm`, `What We Do in the Shadows`
```
Bazarr Version
1.1.1
Sonarr Version
3.0.9.1549
Radarr Version
4.2.4.6635
Operating System
Linux-5.4.0-99-generic-x86_64-with-glibc2.31
Python Version
3.9.2
```

**Comment by morpheus65535** [comment]
@s1p2a3m if you still have an issue, please open your own issue, do not necro more than 1 year old issue.
