### ISSUE TITLE
Presence of embedded en:HI subtitle disables automatic search for regular English subtitle

### ISSUE THREAD

**Issue by DarkwaterV3** [morpheus65535/bazarr#1494]
Hi morpheus, love the app first off.

I've noticed that if I have files in my library with embedded en:HI subtitles, Bazarr will not search for regular English subtitles automatically, despite having instructed the app to do so. This seems like an oversight/bug: I've told Bazarr I want English subtitles without the HI/SDH elements, so if those subs are not present, I wish to have them downloaded.

Thanks,

DarkwaterV3

**Comment by morpheus65535** [comment]
HI subtitles are simply normal subtitles with additional tags. Bazarr have always considered the job done if there's an existing HI subtitles for your language. Not checking the HI checkbox in your language profile doesn't mean you do not want HI subtitles, it simply means that you don't require the subtitles to be HI. It will get what he find: HI or non-HI.

**Comment by DarkwaterV3** [comment]
Then is there a way to have Bazarr download English subs automatically in cases where there are already English HI subs embedded?

**Comment by morpheus65535** [comment]
Ignore embedded subtitles.

**Comment by DarkwaterV3** [comment]
Thanks for the speedy replies.

Your solution would however lead to duplicate subtitles in cases where the wanted languages are already present in embedded form. That would cause the subtitle menu in the media player to become unnecessarily long and confusing. Ignoring embedded subtitles would in this case be substituting one problem with another.

Do you not agree that an option or function to treat 'en' and 'en:HI' as more distinct subtitles would be a helpful feature?

**Comment by morpheus65535** [comment]
I agree but that not how Bazarr was designed in the first place. You can open a feature request for this if there's not already one.

**Comment by DarkwaterV3** [comment]
I've posted a feature request. Thanks for your time.
