### ISSUE TITLE
Job Sync episodes with Sonarr raised an exception

### ISSUE THREAD

**Issue by madjo1983** [morpheus65535/bazarr#1495]
Hi,

Since last Master Update, I have several jobs in error, here some logs overviews:
![image](https://user-images.githubusercontent.com/26038638/128403902-78a05b3a-ea65-4595-b7ff-6ec71df2b990.png)

![image](https://user-images.githubusercontent.com/26038638/128403943-24a05eac-b623-4f56-ad8b-479d5624f37b.png)

It prevents any subtitles list update and retrieval.

Bazarr Version
0.9.6
Sonarr Version
2.0.0.5344
Radarr Version
3.0.2.4552
Operating System
Linux-5.10.17-v7+-armv7l-with-debian-10.9
Python Version
3.7.3
Bazarr Directory
/opt/bazarr
Bazarr Config Directory
/opt/bazarr/data

Running on a Raspberry Pi 3.

Could you help me please to understand what happens?

Thanks.

Madjo

**Comment by halali** [comment]
Your database is corupted probably. Delete database and run bazarr again.

You should also update sonarr v2 is EOL

**Comment by morpheus65535** [comment]
That's an issue fixed in 0.9.7-beta.

**Comment by madjo1983** [comment]
> 
> 
> That's an issue fixed in 0.9.7-beta: [d5b8980](https://github.com/morpheus65535/bazarr/commit/d5b898064d7188d5bc47bcb3a73405a38133d5d6)

Do you have an idea of when it will be pushed to master ?

then relatively to halali 


> 
> 
> Your database is corupted probably. Delete database and run bazarr again.
> 
> You should also update sonarr v2 is EOL

then I guess that my database is not corrupted... ?
what is EOL ? Sonarr seems to be up to date, what should I do ?

Many thanks.

**Comment by morpheus65535** [comment]
There's no ETA but it should be soon. Your DB is perfectly fine.

Current stable build of Sonarr is 3.0.6.x. You're in the less than 10% users of Bazarr who are still using this deprecated version of Sonarr.

**Comment by TiboGabriels** [comment]
there seem to be some issues with upgrading to v3 (in docker), i'm currently trying to fix the same issue.

The linuxserver docker stable release is already on v3 yet on my system keeps pulling v2. If you want i'll keep you posted.

**Comment by TiboGabriels** [comment]
removing the docker image and pulling the new one seemed to have done the trick, but make sure you backup you /config dir, ive read of v3 corrupting the old DB

**Comment by madjo1983** [comment]
I succeeded with that:
https://sonarr.tv/#downloads-v3-linux
working as I'm not using docker.
Then, bazarr seems alive...
I thought that update for sonarr were automatized...

**Comment by morpheus65535** [comment]
> I thought that update for sonarr were automatized...

Not between v2 and v3. There's too much breaking changes.
