### ISSUE TITLE
BAZARR unable to install requirements (user without home directory), when running as a demon

### ISSUE THREAD

**Issue by Nimmsis** [morpheus65535/bazarr#1498]
**Describe the bug**
OS: FreeBSD
when running as a demon the service starts, ands stops when running  init.py with the error "BAZARR unable to install requirements (user without home directory)."

when using the same account, but runs "python3 bazarr.py" from a normal shell. it works.

before 0.96 it worked perfect. but after 0.96 it stopped working. no dependency's have been updated for a couple of months.
confirmed not working in 0.97.beta13 aswell

seems the error lies in os.path.expanduser

**Comment by morpheus65535** [comment]
It's probably related to the fact that your service doesn't have a HOME environment variable defined. you might take a look at this: https://stackoverflow.com/questions/30041891/get-users-home-folder-under-python-process-started-by-supervisord

**Comment by Nimmsis** [comment]
it does have a home variable defined. 
and as I said, it works from a normal shell with the same account, so if it would have a HOME, it wouldnt work from the shell either.

**Comment by morpheus65535** [comment]
This part of code haven't changed since 0.9.4 so if it works previously, it's because something changed on your side. You can always deploy requirements.txt manually using pip but it will eventually break when a new one is added.

**Comment by morpheus65535** [comment]
MAybe add the HOME environment variable definition to your service configuration and see if it help?

**Comment by Nimmsis** [comment]
Did a full reinstall (scrapped the jail (freebsd container)) and reinstalled.

works now.
