### ISSUE TITLE
Big log files

### ISSUE THREAD

**Issue by evripidesk** [morpheus65535/bazarr#1501]
Hello

I just found tha the bazarr create every day log file that are so big 2-3GB

The name if file are like this bazarr.log.2021-08-11
 and are under opt/bazarr/data/log

also if i tried to open the logs from bazarr (system-logs) i ger the below error 

Ouch! You got an error
Request failed with status code 500

Any idea what happened

**Comment by halali** [comment]
Probably you have enabled debug logging. Disable it under general settings.

**Comment by evripidesk** [comment]
It’s disable

**Comment by morpheus65535** [comment]
Probably an issue with Sonarr SignalR connection. Open the log file in a text editor and share some part with us.

**Comment by morpheus65535** [comment]
Is it still an issue?

**Comment by morpheus65535** [comment]
No news, good news.
