### ISSUE TITLE
Run `Scan Disk` sometimes does not remove series from `Wanted`

### ISSUE THREAD

**Issue by salomj** [morpheus65535/bazarr#1503]
**Describe the bug**
I haven't seen this happen in `Movies` yet, but sometimes after running `Scan Disk` with a series that had subtitles added outside of Bazarr, it finds that the subtitles were added, but still keeps the series under `Wanted` for subtitle requests.

The workaround is just to hit `Scan Disk` multiple times until it realizes what is happening.

**To Reproduce**
1. Create a Series without subtitles
2. Manually add subtitles
3. Run `Scan Disk` on the Series
4. Notice how the series has new detected subtitles, but it is also still in the `Wanted` for subtitles

**Expected behavior**
Episodes should be removed

**Screenshots**
At least the UI makes it somewhat obvious what is going on
![image](https://user-images.githubusercontent.com/23242186/129285333-641a5a32-5e56-4ff7-8748-2f0e2544008d.png)

**Software (please complete the following information):**
 - Bazarr: v0.9.6
 - Radarr version: v3.0.6.1265
 - Sonarr version v3.2.2.5080
 - OS: Ubuntu 20.04.2 LTS [Linux-5.4.0-1041-raspi-aarch64-with] 
 - Docker Image `ghcr.io/linuxserver/bazarr:arm64v8-latest`

**Additional context**

**Comment by morpheus65535** [comment]
@LASER-Yi can you take a look at this one please?

**Comment by LASER-Yi** [comment]
Will this issue resolved after refreshing the page?

**Comment by salomj** [comment]
> Will this issue resolved after refreshing the page?

I'll give it a try the next time it happens. My suspicion is yes, but I will confirm.

**Comment by LASER-Yi** [comment]
If this issue is related to Web UI I think the upcoming PR #1499 will fix this issue

**Comment by LASER-Yi** [comment]
Should be fixed in the upcoming v0.9.8-beta.0

**Comment by morpheus65535** [comment]
No news, good news.
