### ISSUE TITLE
Large number of `Connection Refused` error messages

### ISSUE THREAD

**Issue by salomj** [morpheus65535/bazarr#1504]
**Describe the bug**
I am getting a large number of `Connection Refused` error messages, approximately 20,000 per a day. Unfortunately, they don't tell me which host is causing the issue. It would be nice if there were someway it would tell me what host was causing this issue, also it would be nice if this error message way much more human readable.

`Retrying (Retry(total=8, connect=3, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7a23d7c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /`

**To Reproduce**
1. Add a subtitle provider than does not work like `BSplayer`
2. Have some wanted subtitles

**Expected behavior**
An error message like `Connection Refused: <Hostname>` or even better `Connection Refused: <Provider Name>`

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: v0.9.6
 - Radarr version: v3.0.6.1265
 - Sonarr version v3.2.2.5080
 - OS: Ubuntu 20.04.2 LTS [Linux-5.4.0-1041-raspi-aarch64-with] 
 - Docker Image `ghcr.io/linuxserver/bazarr:arm64v8-latest`

**Additional context**
I have removed several providers, but none seem to reduce the message count.

I think `BSPlayer` provider has something to do with it because I see this message pop up `HTTPConnectionPool(host='s102.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7bac2310>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...` 

But I have removed the `BSPlayer` provider, and I am still having the issue. Including the above message, which would imply that `BSPlayer` has for some reason not been removed as a provider.

**Comment by ToXinE** [comment]
exact same problem with BSplayer : moreover when you go to Status ; Health is good
![image](https://user-images.githubusercontent.com/6205053/129317555-91555a5f-aa93-498a-9927-d6024ec444e2.png)
or in providers
![image](https://user-images.githubusercontent.com/6205053/129317489-32aa72e8-6f4b-48fe-a5d8-54e8b9d95c4d.png)

**Comment by morpheus65535** [comment]
BSplayer is broken. It works for some but not many. We've stop fighting with them because they never stop implementing new protection to prevent Bazarr from grabbing subtitles.

Just disable this provider and you should be good. If you still have issues with other providers, start by asking help on Discord.

**Comment by salomj** [comment]
Can we at least prevent this from spamming my logs/have a better log message? It is hitting the logs so hard that it causes Bazarr to lag.
