### ISSUE TITLE
Bazarr considers `Hearing Impaired` and `Forced` subtitles sufficient

### ISSUE THREAD

**Issue by salomj** [morpheus65535/bazarr#1505]
**Describe the bug**
Have a video which only has an English subtitle stream with disposition HI (Hearing Impaired) or forced set to 1.  In your subtitle's profile have English set but do not have `HI` nor `forced` enabled. I would expect this to not be considered sufficient. 

**To Reproduce**
1. Have a video which only has an English subtitle stream with disposition HI (Hearing Impaired) or forced set to 1.  
2. In your subtitle's profile have English set but do not have `HI` nor `forced` enabled.
3. Set the video to the new profile

**Expected behavior**
Subtitles should be set to `Wanted` as I do not wish to have `Forced` nor `Hearing Impaired` subtitles.

**Screenshots**
![image](https://user-images.githubusercontent.com/23242186/129287815-cc82a9cd-3050-4796-914f-18f38e01c8f7.png)
![image](https://user-images.githubusercontent.com/23242186/129287849-f8286ec1-b539-4d61-8944-4acac2536fca.png)
![image](https://user-images.githubusercontent.com/23242186/129287967-7ccd706b-de8d-4eb9-9d6c-39a5c16bee35.png)

**Software (please complete the following information):**
 - Bazarr: v0.9.6
 - Radarr version: v3.0.6.1265
 - Sonarr version v3.2.2.5080
 - OS: Ubuntu 20.04.2 LTS [Linux-5.4.0-1041-raspi-aarch64-with] 
 - Docker Image `ghcr.io/linuxserver/bazarr:arm64v8-latest`

**Additional context**
This is especially problematic for anime, as the `forced` subtitles assume you are watching the dubbed version.

**Comment by morpheus65535** [comment]
This is expected behavior. If you don't require explicitly HI or Forced, anything matching the language will be considered good enough.

**Comment by salomj** [comment]
This should not be expected behavior, as "forced" for anime means you are watching a dubbed version. If you are watching the original version of the anime, this means you will essentially have no subtitles.

**Comment by morpheus65535** [comment]
Bazarr has very limited support for anime anyway. Episode numbering is problematic.

**Comment by salomj** [comment]
Fair enough, I put this into a feature request. https://bazarr.featureupvote.com/suggestions/203029/add-option-to-not-allow-forced-nor-hi-subtitles
