### ISSUE TITLE
Bazarr won´t start if Sonarr / Radarr is down

### ISSUE THREAD

**Issue by costaht** [morpheus65535/bazarr#1506]
**Describe the bug**
Once Sonarr/Radarr is set up on Bazarr, Bazarr won't restart if one of them goes down

**To Reproduce**
1. Set up Sonarr on Bazarr
2. Stop Sonarr service
3. Restart Bazarr
4. Bazarr won´t be able to connect to Sonarr and it will stay in loop, throwing exceptions

**Expected behavior**
Bazarr should start normally and report that it wasn´t able to connect to Sonarr/Radarr and keep trying until the ARR is available again.

**Software (please complete the following information):**
Bazarr Version 0.9.7
Sonarr Version 3.0.6.1265
Radarr Version 3.2.2.5080
OS: Centos 8

**Additional context**
https://paste.centos.org/view/ce9a9ccd

**Comment by morpheus65535** [comment]
This one will be fixed in upcoming 0.9.8-beta.3.
