### ISSUE TITLE
Uploading subtitles can lead to wrong subtitle files being replaced if you have multiple subtitle languages.

### ISSUE THREAD

**Issue by Senjar** [morpheus65535/bazarr#1508]
**Describe the bug**
If you select the language before the files, after the files have been selected the language button will still say the language you selected but the button will have a different value (I think the first language on the dropdown)

**To Reproduce**

0. Have at least 2 languages (Lets say English and Italian)
1. Go to a show
2. Click on Upload
3. Select language (Italian)
4. Click Browse
5. Select files
6. Click upload

**Expected behavior**
Upload and replace files of the selected language (Italian)

**What happens**
Uploads and replaces the files from the first language (English) in the dropdown.

**Workaround**
Select language AFTER you browse and select the files.

**Software (please complete the following information):**
 - Bazarr: 0.9.7

**Comment by LASER-Yi** [comment]
Should be fixed in the upcoming beta version (0.9.8-beta.2).

**Comment by morpheus65535** [comment]
No news, good news.
