### ISSUE TITLE
Can't access Settings menu

### ISSUE THREAD

**Issue by mobamoba** [morpheus65535/bazarr#151]
**Describe the bug**
IP Address:6767/bazarrsettings throws this error:
Internal Server Error

Exception:

NameError("name 'settings_proxy' is not defined",)

Traceback:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\bottle.py", line 862, in _handle
    return route.call(**args)
  File "C:\Python27\lib\site-packages\bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "C:\Bazarr\bazarr.py", line 115, in wrapper
    app = app()
  File "C:\Bazarr\bazarr.py", line 703, in settings
    db.create_function("path_substitution", 1, path_replace)
  File "C:\Python27\lib\site-packages\bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "C:\Python27\lib\site-packages\bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "C:\Python27\lib\site-packages\bottle.py", line 3396, in execute
    eval(self.co, env)
  File "C:\Bazarr\views\settings.tpl", line 226, in <module>
    <input id="settings_proxy_url" name="settings_proxy_url" type="text" value="{{settings_proxy[1]}}">
NameError: name 'settings_proxy' is not defined

**To Reproduce**
Click on Settings. It puts IP Address:6767/bazarrsettings in the URL bar but throws the error above. All other bazarr urls (e.g. bazarrwanted, bazarrsystem, etc.) work fine. Settings is the only one that doesn't work.

**Expected behavior**
The settings menu should open.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: .6.4
 - Radarr version [e.g. v 0.2.0.0001]
 - Sonarr version [e.g. v 2.0.0.0001]
 - OS: [e.g. Windows 10]

**Additional context**

**Comment by morpheus65535** [comment]
Did you configure Bazarr using Safari?

**Comment by mobamoba** [comment]
No, Firefox. On Windows.

**Comment by mobamoba** [comment]
Here you go:

[general]
ip = 0.0.0.0
port = 6767
base_url = /bazarr
path_mappings = [['', ''], ['', ''], ['', ''], ['', ''], ['', '']]
log_level = INFO
branch = master
auto_update = True
single_language = True
minimum_score = 90
use_scenename = True
use_postprocessing = False
postprocessing_cmd = 
use_sonarr = True
use_radarr = True
path_mappings_movie = [['', ''], ['', ''], ['', ''], ['', ''], ['', '']]
serie_default_enabled = True
serie_default_language = ['en']
serie_default_hi = False
movie_default_enabled = True
movie_default_language = ['en']
movie_default_hi = False
page_size = 25
minimum_score_movie = 70
use_embedded_subs = True
only_monitored = False

[auth]
enabled = False
username = 
password = 

[sonarr]
ip = 127.0.0.1
port = 8989
base_url = /
ssl = False
apikey = API
full_update = Daily

[radarr]
ip = 127.0.0.1
port = 7878
base_url = /
ssl = False
apikey = API
full_update = Daily

**Comment by morpheus65535** [comment]
The url you access should be http://127.0.0.1:6767/bazarr/settings

Try this and save settings.

**Comment by halali** [comment]
Still have this issue ?

**Comment by mobamoba** [comment]
Yes and the URL above doesn't work either.

**Comment by morpheus65535** [comment]
In settings, try to put a slash at the and of your Bazarr base url: /bazarr/

**Comment by mobamoba** [comment]
Except I can't access Settings. And as I mentioned, what I have works perfectly for every menu except settings which is why I'm reporting this bug, i..e it's odd that the base url fails in only one place.

**Comment by morpheus65535** [comment]
Thanks, you were right and something was wrong. Should be fix in 0.6.5 that get out tonight.

**Comment by mobamoba** [comment]
Cool thanks!

**Comment by mobamoba** [comment]
This issue came back again in most recent version update.

**Comment by morpheus65535** [comment]
I cannot reproduce this error. Could you provide more details?

**Comment by mobamoba** [comment]
This is the URL that worked perfectly until the most recent update and here's what happens now:
![untitled](https://user-images.githubusercontent.com/11135869/51604473-e7aba380-1eda-11e9-9846-ce01993ddae3.png)

Here's the URL that works with the most recent update - note that lack of the "/" between "bazarr" and "wanted". This has happened before so something in the code is slightly changing the URL on updating:

![untitled3png](https://user-images.githubusercontent.com/11135869/51604530-0d38ad00-1edb-11e9-8742-2c6a2fca1b6f.png)

**Comment by morpheus65535** [comment]
Please post your config.ini content and obfuscate confidential informations.

**Comment by mobamoba** [comment]
https://github.com/morpheus65535/bazarr/issues/151#issuecomment-424508085

**Comment by morpheus65535** [comment]
Nothing changed? It’s working for with the exact same settings. Reverse proxy?

**Comment by halali** [comment]
but i think he have old bazarr, some time is supposed to save with / at the end

**Comment by morpheus65535** [comment]
Good point. Could you confirm your current Bazarr version?

**Comment by mobamoba** [comment]
0.7.0 nothing has changed in my config or anywhere. You found the bug before and fixed it so maybe it's the same bug?

**Comment by halali** [comment]
i think save settings can solve your issue... but you can solve it by self adding / at the end of you base url

**Comment by mobamoba** [comment]
True but that doesn't solve the source of bug where the slash wasn't needed in a prior version and upgrading breaks access.

**Comment by halali** [comment]
The slash is added after you save settings. You have probably old config and long time didn't do save settings.
