### ISSUE TITLE
|Throttling titlovi for 10 minutes, until xxx, because of: AuthenticationError. Exception info: 'Login failed'|

### ISSUE THREAD

**Issue by micki88** [morpheus65535/bazarr#1511]
Hi guys,

No mather what I do, change password, user, I allways get this authenticationerror with titlovi provider.

Any ideas?

Thx

**Comment by Magikarplvl4** [comment]
Why did you delete the support template?

**Comment by morpheus65535** [comment]
Working perfectly fine for me with v0.9.7. Lowercase username, special characters password.

**Comment by micki88** [comment]
Thx guys, managed to download titles with only text username. If user has numbers I get auth error. Now its workinh

**Comment by morpheus65535** [comment]
Thanks let's hope it may help other user in future

**Comment by mariosemes** [comment]
Reopening cause getting the same error. My username and password is only letters without symbols and numbers or whatever. Getting Auth errors.

**Comment by morpheus65535** [comment]
> Reopening cause getting the same error. My username and password is only letters without symbols and numbers or whatever. Getting Auth errors.

Open a new issue and provide required informations.

**Comment by mojrs10** [comment]
I have this problem to

**Comment by phpavelic** [comment]
Getting this error aswell

**Comment by morpheus65535** [comment]
Could you stop necro a 2 years old issue? You have a configuration issue. Double check your login password and use simple characters.

**Comment by phpavelic** [comment]
> 

I even made an account which has characters only and a simple password, still getting the errors

**Comment by morpheus65535** [comment]
Then please, open a new issue with all the required informations. Necromancy isn't the way to do this.
