### ISSUE TITLE
Translating subs to Hebrew not working

### ISSUE THREAD

**Issue by NatiSayada** [morpheus65535/bazarr#1513]
**Describe the bug**
its look like when bazarr is trying to translate to Hebrew is using the code he which is no longer valid for google translate.

the language code should be iw as listed here:
https://cloud.google.com/translate/docs/languages
and here:
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

manually updating the code in google_trans.py resolve the issue.

**To Reproduce**
try to translate sub to he and you will see in the debug logs the bazarr is calling https://translate.google.com/m?tl=he&sl=auto.

it should be tl=iw

**Expected behavior**
call translate.google.com with iw for target lang he

**Comment by morpheus65535** [comment]
It should be fixed in upcoming 0.9.8-beta.7.

**Comment by morpheus65535** [comment]
No news, good news.
