### ISSUE TITLE
The subtitle provider Yavka.net is no longer working

### ISSUE THREAD

**Issue by chitalov** [morpheus65535/bazarr#1514]
**Describe the bug**
Тhere are changes in the site Yavka.net and the subtitle provider Yavka.net is no longer working.

Bazarr Version
0.9.8-beta.5
Sonarr Version
3.0.6.1309
Radarr Version
4.0.0.5219
Operating System
Linux-5.4.0-81-generic-x86_64-with
Python Version
3.8.10
![photo_2021-08-18_21-03-53](https://user-images.githubusercontent.com/73425550/130331348-eac16796-87e1-4aa1-a8c3-460a79fec333.jpg)

**Additional context**

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta.8. Can you test it and confirm?

**Comment by chitalov** [comment]
Yes, it already works, but I can't find the subtitles that are available, I tried different TV series.
https://gist.github.com/chitalov/a7e2bab53f7e74897d3a1e957a45e3ca#file-debug-log
![Screenshot_2021-08-24-17-32-10-779_com android chrome](https://user-images.githubusercontent.com/73425550/130640176-50f22506-833f-4ded-8ebf-a635e398617b.jpg)
![Screenshot_2021-08-24-17-01-36-620_com android chrome](https://user-images.githubusercontent.com/73425550/130640198-c2578992-1336-4965-a982-5756242d0c59.jpg)

**Comment by chitalov** [comment]
Yes 
![Screenshot_2021-08-24-16-57-34-302_com android chrome](https://user-images.githubusercontent.com/73425550/130640847-525d4a17-850f-4aba-a31c-5cae44963e29.jpg)

**Comment by morpheus65535** [comment]
Empty your config/cache directory and try again.

**Comment by chitalov** [comment]
Yes . works great thanks !!! 
![Uploading Screenshot_2021-08-24-20-33-45-396_com.android.chrome.jpg…]()
