### ISSUE TITLE
Bazarr searches for the same subtitles every few minutes

### ISSUE THREAD

**Issue by maxim-sm** [morpheus65535/bazarr#1521]
**Describe the bug**
bazarr appears to look for subtitles for the same episodes over and over in a loop.
If I understand the log correctly, bazarr searches for subtitles for a given episode from several providers, it concludes that it cannot find what it is looking for and finishes with the episode. A few minutes later, it searches for the same episode again.

**To Reproduce**
1. Enable debug logging
2. Initiate *Search for wanted Series Subtitles* manually from the Tasks menu
3. Follow the debug log

**Expected behavior**
After bazarr is able to conclude that it cannot find subtitles for a specific episode and language it should wait for the next time the task is initiated to retry.

**Software (please complete the following information):**
 - Bazarr: 0.9.7
 - Radarr version: 3.2.2.5080
 - Sonarr version: 3.0.6.1265
 - OS: Unraid 6.9.2

All software is running in Docker containers provided by linuxserver.io

**Additional context**
For example I have the show The Boondocks in Sonarr. It can be seen in the attached log that Bazarr is looking for Hebrew subtitles for episode 13 from season 2 every 6-7 minutes from the same providers (I ran `grep -A 10 "episode_number=13&season_number=2" bazarr.log` to see it).

I searched other issues to avoid opening duplicates, but didn't find anything, sorry if I missed it.
Also, I'm sorry if this the intended behavior and I just don't understand how bazarr searches for subtitles.
Please let me know if I can provide any additional information and thank you for this great software.

[bazarr.log](https://github.com/morpheus65535/bazarr/files/7072932/bazarr.log)

**Comment by TRaSH-** [comment]
Did you make sure the following setting is disabled ?

![image](https://user-images.githubusercontent.com/6155095/131259510-92ebff52-42ff-4337-bdcc-baa8a688edb9.png)

if you want faster support i suggest to join discord

**Comment by maxim-sm** [comment]
Yes, this option is disabled. Thanks!

**Comment by TRaSH-** [comment]
come to discord so we can try to help you

**Comment by maxim-sm** [comment]
@TRaSH- Thanks a lot for trying to help but, if possible, I would prefer to keep it as an open issue on GitHub as I believe it is a bug.
I would appreciate if the issue can remain open until someone addresses this issue here.

**Comment by TRaSH-** [comment]
Come in to discord so we can solve it, it will be reopened if it's a actual bug.
for now it's not considered a bug but a setup error, that we might be able to solve in discord.
click on the link to join discord https://docs.bazarr.media/discord

**Comment by morpheus65535** [comment]
The fix will be included in upcoming 0.9.8-beta.12 that should get released around 6:15am GMT. Can you test it and confirm please?

**Comment by maxim-sm** [comment]
Sure. I'll test it today. Thanks for the quick fix 😃

**Comment by maxim-sm** [comment]
Everything works perfectly with version 0.9.8-beta.12. I just ran a search for all my missing episodes (800+), all found subtitles were downloaded and there were no repetitions. Naturally the search now is very quick. Thanks a lot for debugging and fixing it!
