### ISSUE TITLE
Reading media files way too often

### ISSUE THREAD

**Issue by Inrego** [morpheus65535/bazarr#1534]
**Describe the bug**
When looking for subtitles, Bazarr is doing a lot of reads of the media files. This is a problem, because my media is stored on Google Drive and accessed via rclone. There's a limited amount of requests allowed per day.
I just installed Bazarr, and specified a language profile for a single TV show. The show was missing subtitles for 87 media files. But after unleashing Bazarr to look for these subtitles, I started to get a lot of requests to google service (500-1k requests per minute).

**Expected behavior**
Reading of media files shouldn't really happen while seaching for subtitles I think? All needed information is already scanned and stored in Bazarr database.

**Screenshots**
Screenshot of queries on pihole:
![image](https://user-images.githubusercontent.com/2242329/132683883-2bee0dff-66b1-43f7-bb6d-6c7386d4638f.png)

**Software (please complete the following information):**
 - Bazarr: 0.9.8
 - Radarr version: 3.2.2.5080
 - Sonarr version: 3.0.6.1333
 - OS: Docker on ubuntu

**Comment by morpheus65535** [comment]
Bazarr needs ffprobe output to refine the information available in Sonarr/Radarr that was previously imported in its database. This is done once and cached in db during the initial scan and, after that, when we receive a notification from Sonarr or Radarr that the file have changed. Once this ffprobe output is cached, you shouldn't see much more call to disk/API. You're gonna have to deal with that during the initial scan.

I suggest you take the time to read the wiki performance tuning section: https://wiki.bazarr.media/Additional-Configuration/Performance-Tuning/

If you still have question, don't hesitate to come to our Discord support channel.

**Comment by TRaSH-** [comment]
Did you look at the FAQ on the wiki ?
https://wiki.bazarr.media/Troubleshooting/FAQ/#im-a-cloud-user-or-run-on-a-low-powered-device

Don't forget any suggested settings, this has been tested by multiple cloud users with really large libraries (100k+)
Any further questions about this can be asked in our discord server where we handle support questions.
We try to keep GitHub for only real bugs.
If you joined discord and followed all instructions and we consider it's a actual bug then the issue will be re-opened.

**Comment by Inrego** [comment]
The show was already scanned on disk, so ffprobe was done and all embedded subtitles was shown in Bazarr.
So I don't understand why 500 requests/minute was done to gdrive while just searching for subtitles.

**Comment by morpheus65535** [comment]
ffprobe is run on ALL your episodes and movies, not just the one you've assigned a languages profile and run a search.

**Comment by Inrego** [comment]
But after searching for subtitles for that 1 show, the api request amounts went back to normal. So it was for sure related to searching for subtitles (even though the show was already scanned). I'll continue this on Discord support chat.

**Comment by k29t59dh** [comment]
Was this ever resolved?

I'm seeing similar behavior with local storage - any media missing subtitles is scanned on disk every 3 hours (when search runs.)

I saw references to caching ffprobe results, which looks like it's working, so why re-scan?
```
04/07/2022 08:01:56|DEBUG   |peewee                          |('SELECT "t1"."ffprobe_cache" FROM "table_movies" AS "t1" WHERE ("t1"."path" = ?) LIMIT ? OFFSET ?', ...
04/07/2022 08:01:56|DEBUG   |root                            |FFprobe found: ...
```

**Comment by morpheus65535** [comment]
> Was this ever resolved?

Yes, long time ago. Make sure that caching is enabled in Settings-->Scheduler.

**Comment by k29t59dh** [comment]
Yes it's enabled.
Anywhere else I should look?

<img width="519" alt="Screen Shot 2022-07-04 at 8 57 33 AM" src="https://user-images.githubusercontent.com/76966241/177159872-d7e2473d-5db1-4a37-818e-dcf5b7059a59.png">

**Comment by morpheus65535** [comment]
@k29t59dh not easily. Open your own issue with debug log while reproducing.
