### ISSUE TITLE
Ktuvit provider without `hashed password`

### ISSUE THREAD

**Issue by ilikektuvit** [morpheus65535/bazarr#1537]
today i thought to myself, huh i like ktuvit. its good.
why not write a provider? 
so i finished mine, just to find out that someone already made a pr (https://github.com/morpheus65535/bazarr/pull/1522) and merged it to dev lmao
keep your hard work @GuyKh, youre a saint. really.  
i thought i should open new issue cos i dont want to comment on merged pr :|  

the only differenceis the weird hashed password thingy:
``(Get `hashed_password` using method described [here](https://github.com/XBMCil/service.subtitles.ktuvit))``

i dont like this auth workaround, so i implemented the password encryption algo in python:
```
def generate_iv(data):
    iv = []
    for i in range(0, len(data), 2):
        hx = ""
        for c in data[i : i + 2]:
            try:
                int(c, 16)
                hx += c
            except ValueError:
                break
        iv.append(int(hx or "0", 16))

    iv += [0] * (16 - len(iv))
    return bytes(iv)


def pkcs7_padding(m):
    return m + chr(16 - len(m) % 16).encode() * (16 - len(m) % 16)


def encrypt_password(email: str, password: str, salt: bytes) -> str:
    key = hashlib.pbkdf2_hmac("SHA1", salt, email.encode(), 3000, 16)
    cipher = AES.new(key, AES.MODE_CBC, iv=generate_iv(email))
    data = cipher.encrypt(pkcs7_padding(password.encode()))
    data_sha256 = hashlib.sha256(data).digest()
    return b64encode(data_sha256).decode()
```

full provider code:
https://gist.github.com/ilikektuvit/eda3c2e1efa2e7d3718f6f2496e56ae5

the only problem that remains is the python crypto module.
i dont think we can put one in bazarr/libs and leave it due to distro compatibility.
usually the crypto modules are pain to build in some distros so maybe itll be annoyin to add it to requirements.
on the other hand, most bazarr dockerfiles already have the alpine build-dependencies for the other reqs...

@morpheus65535 - your opinion? 
should we leave the `hashed password` as is  or generate the password provider side?

**Comment by morpheus65535** [comment]
Thanks for your efforts on this one! Unfortunately, for the exact reason you mentioned, we won't add crypto as a dependency in Python. In fact, we're stuck with an "old" version of apprise because of that. I think we should keep it the way it is until we can do with the embedded python libraries like hashlib.

**Comment by ilikektuvit** [comment]
the expected answer, but the sad one((
if for some reason in the future crypto module is added to bazarr, i would love to see this ^^ in it too.
im closing the issue, appreciate the fast reply and all your work on bazarr!
