### ISSUE TITLE
Ktuvit provider does not find any subs (login issue)

### ISSUE THREAD

**Issue by ilikektuvit** [morpheus65535/bazarr#1538]
**Describe the bug**
when added to the provider list, doesnt find any subtitles

**To Reproduce**
1. add ktuvit to the provider list
2.  search for movie / series (i searched for queen gambit / chappie)
3. no subs found, but there are subs on the site

**Expected behavior**
i want it to search and find subs lol 

**Software (please complete the following information):**
 - Bazarr: v0.9.9-beta.4
 - OS: linuxserver docker

**Additional context**
so i wanted to try out the new dev ktuvit provider, but unfortunately it seems it doesnt work as expected((
logs:  [issue logs.log](https://github.com/morpheus65535/bazarr/files/7147642/issue.logs.log)
the logs were little confusing, cos the provider indicated that something with search / imdb comparison was off.
maybe its related to how bazarr / subliminal searches the providers.
i dumped the response of the movie page request and boom no subs on site, cos you are not logged in. 

for some reason after the login request the cookie is added as header:
```
logger.debug("Logged in")
self.loginCookie = (
    r.headers["set-cookie"][1].split(";")[0].replace("Login=", "")
)

self.session.headers["Accept"]="application/json, text/javascript, */*; q=0.01"
self.session.headers["Cookie"]="Login=" + self.loginCookie

self.logged_in = True
```
but the session saves all cookies to cookiejar, and sends them if needed...
idk maybe my cookies were different than @GuyKh.
after i removed the cookie header lines, everything was working:
```
logger.debug("Logged in")
self.session.headers["Accept"]="application/json, text/javascript, */*; q=0.01"
self.logged_in = True
```
logs after patch: [after patch.log](https://github.com/morpheus65535/bazarr/files/7147645/after.patch.log)
:)

**Comment by GuyKh** [comment]
I've tried it before, but I'll try again and verify. I'll keep you posted

**Comment by GuyKh** [comment]
I've just reproduced this myself.
Not sure if there's an issue with the Login itself.
Created #1539 - as per your suggestion. Will test it out soon

**Comment by GuyKh** [comment]
Fixed (in #1539) and double-verified.
Now the cookie used is also printed out in the debug log and validated (it's there).
Ready to merge

**Comment by GuyKh** [comment]
Thanks @ilikektuvit for the **very quick** bug report and solution solving

**Comment by morpheus65535** [comment]
Merged. Thanks!
