### ISSUE TITLE
[Feature Request] Download subtitles to a subtitles directory 

### ISSUE THREAD

**Issue by jrsdead** [morpheus65535/bazarr#154]
As discussed it would be great if bazarr could download subtitles to a subtitles directory
 e.g. the following directory structure 

TV 
|
|--> Show A
|-----> Season 1
| --------->Subtitles
| -----> Season 2
| ---------> Subtitles
|--> Show B
| -----> Season 1
|----------->Subtitles
| -----> Season 2
|-----------> Subtitles

This is how i had subzero set up within plex.  The code for subzero can be found here https://github.com/pannal/Sub-Zero.bundle  and one of the relevant pieces of subliminal looks to be https://subliminal.readthedocs.io/en/latest/api/core.html?highlight=directory#subliminal.core.search_external_subtitles

**Comment by hami** [comment]
Can I second this request. As a new user coming from SubZero, I like the tidiness of being able to store the subtitle files in a sub folder as I have about 5 default languages.

Do you plan to allow the user to specify the name of the sub folder the files will be stored in?

Thanks for creating Bazarr @morpheus65535

**Comment by morpheus65535** [comment]
You can expect this kind of functionality to be available when we'll finish merging SZ into Bazarr.

**Comment by halali** [comment]
added in https://github.com/morpheus65535/bazarr/commit/181e71fe65d9996a8949b35ebabbef420d178744
