### ISSUE TITLE
Ktuvit provider KeyError

### ISSUE THREAD

**Issue by doopler** [morpheus65535/bazarr#1541]
**Describe the bug**

|Throttling ktuvit for 10 minutes, until 21/09/13 15:12, because of: KeyError. Exception info: 'd'|

**To Reproduce**

this happens when trying to search for any subtitle

**Software (please complete the following information):**
 - Bazarr: [e.g. v 09.10 beta0]
 - OS: [linux]
![WhatsApp Image 2021-09-13 at 15 31 48](https://user-images.githubusercontent.com/42199374/133084124-857b72cc-916b-4c39-b055-af1c7e5ce4fa.jpeg)

**Comment by morpheus65535** [comment]
@GuyKh can you take a look please?

**Comment by GuyKh** [comment]
Sure. Will take a look

**Comment by GuyKh** [comment]
I think the issue is with a bad login.
I'll have a potential fix but I'll have to test it out later.
In the meanwhile - @doopler  - make sure you use the method described here: https://github.com/XBMCil/service.subtitles.ktuvit in order to get the hashed_password

Ping me for more question

**Comment by doopler** [comment]
@GuyKh Thanks for response
I did used that method before.
How can i test it after the fix?

**Comment by GuyKh** [comment]
Ummm good question. 
I think I've generalized the code which uses the login methods and others - so the exception should be more clear now, if there's a problem.

**Comment by morpheus65535** [comment]
Should be good with @GuyKh PR. Thanks mate!

**Comment by doopler** [comment]
thanks
the provider login is working now but i still get KeyError when bazarr is searching for missing subtitles .
Throttling ktuvit for 10 minutes, until 21/09/19 15:46, because of: KeyError. Exception info: 'sub_id'
![image](https://user-images.githubusercontent.com/42199374/133928704-c74f030d-b785-42f8-a545-fdc44273baa5.png)

**Comment by GuyKh** [comment]
Could you write which file are you looking for?
I think it's a case of handling missing subtitle from the site

**Comment by doopler** [comment]
hi @GuyKh 
yes i also think its a missing subtitles on the website error.
you can try the walking dead s01e06 for instance that is probably still missing
but i think it shouldn't get an error when no subtitle found...just skip or something..
correct me if i'm wrong 🤷‍♂️ 😀

**Comment by GuyKh** [comment]
@doopler - youre right,
but there are many cases of "missing subtitles"
1. Cannot find the series.
2. Cannot find the episode
3. No subtitles yet for that episode.

I guess you're at issue 3, but i'll have to try to check

**Comment by doopler** [comment]
thanks @GuyKh 
i appreciate that
😃

**Comment by GuyKh** [comment]
@doopler 
Tried to reproduce your problem - and didn't succeed:
![image](https://user-images.githubusercontent.com/3136012/134323557-41f8ae11-7aa0-42e1-8acc-8fbecf1fe992.png)

**Comment by morpheus65535** [comment]
@GuyKh you've searched for TWD World Beyond and get subtitles for TWD.

**Comment by GuyKh** [comment]
@morpheus65535 Fail point - didn't know it's a thing... Will check again...

**Comment by doopler** [comment]
oh sorry i just noticed that i wrote s01 and i meant s11...
sorry my bad.🤦‍♂️

**Comment by GuyKh** [comment]
@doopler  - I was able to reproduce it specificly with TWD S11E06.
Will update you shortly

**Comment by doopler** [comment]
Hi @GuyKh 
i've updated bazarr to v0.9.10-beta.10 and now there is new error when searching for missing subtitle.

|Throttling ktuvit for 10 minutes, until 21/10/10 13:14, because of: JSONDecodeError. Exception info: 'Missing Films/Series 

here is a screenshot of the error.....
![WhatsApp Image 2021-10-10 at 13 06 08](https://user-images.githubusercontent.com/42199374/136691725-10e31c7a-4c83-475e-9f12-925d96267223.jpeg)

thanks again guys for great work.👍

**Comment by doopler** [comment]
this error happens when search for all missing subtitles is triggered.
currently i'm on the last beta version 0.9.10-beta.10

**Comment by GuyKh** [comment]
@doopler I meant - which movie/series? the exact version
i.e. `Armageddon.720p.THISandTHAT.x265.mkv` etc

**Comment by GuyKh** [comment]
Right, but which one is problematic?
I need to reproduce it :)
