### ISSUE TITLE
e.value is null when clicking through to any series with episodes

### ISSUE THREAD

**Issue by mvemjsunp1790** [morpheus65535/bazarr#1546]
**Describe the bug**
Clicking on any series displays 'Oops! UI is crashed!
e.value is null'

**To Reproduce**
1. Go to Series tab
2. Click on any series that currently has episodes downloaded
3. UI crashes

**Expected behavior**
Series displays available episodes

**Software (please complete the following information):**
Bazarr Version 0.9.9
Sonarr Version 2.0.0.5344
Radarr Version 3.0.1.4259
Operating System Linux-5.11.0-25-generic-x86_64-with
Python Version 3.8.10

**Comment by mvemjsunp1790** [comment]
Appeared to be caused by a mapping issue for Sonarr.
I removed the mappings and Sync episodes with Sonarr (from the tasks menu) error no longer displays

**Comment by LASER-Yi** [comment]
> Appeared to be caused by a mapping issue for Sonarr.
> I removed the mappings and Sync episodes with Sonarr (from the tasks menu) error no longer displays

So this issue is causes by incorrect data from backend or just frontend doesn’t handle it properly?
