### ISSUE TITLE
Bazarr is not recognizing changes to filenames and subtitles on disk.

### ISSUE THREAD

**Issue by tehniemer** [morpheus65535/bazarr#1547]
**Describe the bug**
If movie or show filenames change on the disk, or subtitles are removed externally, Bazarr does not see the change and a folder scan in Bazarr does not pick up the change either.

**To Reproduce**
1. Rename a file or remove a subtitle in Radarr or Sonarr.
2. Observe name and subtitle file changes in that application and on the disk.
3. Find the same movie or show in Bazarr.
4. See old filename and/or subtitle file.

**Expected behavior**
Bazarr recognizes changed filenames and removed subtitles from disk.

**Screenshots**

![Image 1631804276](https://user-images.githubusercontent.com/11021632/133646721-11cf110f-2e36-4287-ae84-d577625ef091.png)
![Image 1631804296](https://user-images.githubusercontent.com/11021632/133646725-dc6ab239-5bda-4bfa-8235-6d4575588c56.png)
![Image 1631804305](https://user-images.githubusercontent.com/11021632/133646726-7612c23c-5eb9-4104-933c-395f8b19fa5f.png)

**Software (please complete the following information):**
 - Bazarr: 0.9.9
 - Radarr version 3.2.2.5080
 - Sonarr version 3.0.6.1265
 - OS: Docker linux

**Comment by morpheus65535** [comment]
Bazarr is being informed of the filename change by Sonarr/Radarr. Both tools should be emitting a new file id when it happens but both don't do it and they are aware of that bug. It's in backlog for more than 2 years on Sonarr sides but Radarr team have acknowledged to address it.

There's nothing I can do on Bazarr side if I don't receive a proper notification.

**Comment by tehniemer** [comment]
Can you pull that information from sonarr and radarr as a scheduled task? If this isn't happening as part of the  sonarr and radarr sync tasks what are they doing? And what does scan disk do on the individual movie or show page?

**Comment by morpheus65535** [comment]
Yes we take it from Sonarr/Radarr live but also on a scheduled task. Is Sonarr aware of the change in it's UI?

Scan disk button only try to find embedded and external subtitles for the episodes file list that we got from Sonarr.

**Comment by tehniemer** [comment]
This specific case is Radarr, but yes it is aware of the change. The first screenshot above is from Radarr, the second from Bazarr, and the third is what's actually in the folder (which matches with what Radarr shows).

In this case Bazarr isn't getting the updated file name from Radarr or seeing that the subtitle file is no longer in the folder.

**Comment by maxkve** [comment]
I had a similar issue...a couple of days ago when I started up Bazarr all my settings were wiped, but I didn't notice at the time that it had also forgotten about Sonarr and Radarr, so I had to re-enter my API keys etc again. You've probably already checked all that, but just in case you haven't... :)

**Comment by tehniemer** [comment]
Connections to Radarr/Sonarr are still good in my instance.

**Comment by morpheus65535** [comment]
> This specific case is Radarr, but yes it is aware of the change. The first screenshot above is from Radarr, the second from Bazarr, and the third is what's actually in the folder (which matches with what Radarr shows).

Sorry I got mixed up between issues. So Bazarr is not aware of the change. Can you provide a debug log while forcing the execution of this task: `Update Movie list from Radarr`. We'll try to see what's happening here.

**Comment by morpheus65535** [comment]
Anything left to investigate here?

**Comment by tehniemer** [comment]
Sorry, this fell off my radar. I'll try to get the logs in the next couple of days.

**Comment by tehniemer** [comment]
I just tested and it saw the change, so I'm not sure what was going on before, but it seems to be working as expected now.

**Comment by morpheus65535** [comment]
Oh ok. Let me know if it happens again!
