### ISSUE TITLE
Wrong tv show subtitle downloaded

### ISSUE THREAD

**Issue by LittleLama** [morpheus65535/bazarr#1548]
Hi
For "Evil" tvshow, I use addic7ed to download french subtitles. Tvshow is imported from Sonarr. 
Subs fetch works fine, but downloaded subs are from another tvshow, looks like it is NCIS. 

**Expected behavior**
To have the good tvshow subs, or been told there is an exception

**Software (please complete the following information):**
 - Bazarr: 0.9.9
 - Sonarr 3.0.6.1265
 - OS: Docker on Linux 5.10.28 Unraid x86-64 with

Thank you !

**Comment by morpheus65535** [comment]
Please come to Discord for support. This could be related to file naming.
