### ISSUE TITLE
Addic7ed failing on movie search and download. on v0.9.10-beta.2

### ISSUE THREAD

**Issue by jaycedk** [morpheus65535/bazarr#1550]
**Describe the bug**
Addic7ed failing on movie search and download.

**To Reproduce**
Task search for wanted movies
See error

https://www.addic7ed.com:443 "GET /search.php?search=Rock+Dog HTTP/1.1" 200 None
Released creation lock
Unexpected error in provider 'addic7ed': Traceback (most recent call last): File "f:\bazarr\bazarr\../libs\subliminal_patch\core.py", line 170, in list_subtitles_provider results = self[provider].list_subtitles(video, provider_languages) File "f:\bazarr\bazarr\../libs\subliminal_patch\providers\addic7ed.py", line 534, in list_subtitles movie_id = self.get_movie_id(title, video.year) File "<f:\bazarr\bazarr\../libs\decorator.py:decorator-gen-10>", line 2, in get_movie_id File "f:\bazarr\bazarr\../libs\dogpile\cache\region.py", line 1271, in get_or_create_for_user_func return self.get_or_create(key, user_func, timeout, File "f:\bazarr\bazarr\../libs\dogpile\cache\region.py", line 874, in get_or_create with Lock( File "f:\bazarr\bazarr\../libs\dogpile\lock.py", line 186, in __enter__ return self._enter() File "f:\bazarr\bazarr\../libs\dogpile\lock.py", line 93, in _enter generated = self._enter_create(value, createdtime) File "f:\bazarr\bazarr\../libs\dogpile\lock.py", line 179, in _enter_create return self.creator() File "f:\bazarr\bazarr\../libs\dogpile\cache\region.py", line 839, in gen_value created_value = creator(*creator_args[0], **creator_args[1]) File "f:\bazarr\bazarr\../libs\subliminal_patch\providers\addic7ed.py", line 252, in get_movie_id type, media_id = link['href'].split('/')ValueError: too many values to unpack (expected 2)
Throttling addic7ed for 10 minutes, until 21/09/18 06:51, because of: ValueError. Exception info: 'too many values to unpack (expected 2)'

**Expected behavior**
I expect it to download subtitles.
**Screenshots**
![billede](https://user-images.githubusercontent.com/17232146/133872855-07bf8fdb-7eeb-461a-b701-1380ee3ff3d2.png)

**Software (please complete the following information):**
 - Bazarr: v0.9.10-beta.2
 - Radarr version 3.2.2.5080
 - Sonarr version 3.0.6.1265
 - OS: Windows 10

**Additional context**

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta.4. Can you test and confirm please?

**Comment by jaycedk** [comment]
Will have a look and test when beta.4 is released.

**Comment by morpheus65535** [comment]
Just released. You can force an update.

**Comment by jaycedk** [comment]
Thank you, that did it :)
