### ISSUE TITLE
Handling multiple instances of Sonarr / Radarr?

### ISSUE THREAD

**Issue by claym** [morpheus65535/bazarr#156]
Not really a bug / feature request, but is there a way to handle multiple instances of radarr?

I have two - one which handles most movies, another that handles UHD movies. 

Is there any way for Bazarr to handle this situation?

**Comment by claym** [comment]
hahahah that's fair

**Comment by morpheus65535** [comment]
:-D

**Comment by zer0ish** [comment]
I know this is old but I have a similar want, but wondering if this can be done via the Path Mappings.
I have 1 HD and 1 4K Radarr setup, would mapping the HD and 4K in the Path Mapping section in Bazarr download the proper subs for the 4K or would it rely on the HD versions?

I don't mind setting up another Bazarr instance for the 4K, but was curious if the Path Mapping could be utilized this way?

**Comment by morpheus65535** [comment]
@zer0ish You need two instances of Bazarr.
