### ISSUE TITLE
Cannot start Bazaar, fresh installation

### ISSUE THREAD

**Issue by soenneker** [morpheus65535/bazarr#1560]
**Describe the bug**
I have a brand new installation of bazaar because a broken update apparently wiped everything.

**To Reproduce**
1. Download Bazarr release
2. Run pip install requirements
3. Run python bazaar.py

**Expected behavior**
Not break.

** Log messages **
`26/09/2021 14:30:25|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
26/09/2021 14:30:32|ERROR   |app                             |Exception on / [GET]|'Traceback (most recent call last):\n  File "C:\\Bazarr\\bazarr\\../libs\\flask\\app.py", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File "C:\\Bazarr\\bazarr\\../libs\\flask\\app.py", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "C:\\Bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 269, in error_router\n    return original_handler(e)\n  File "C:\\Bazarr\\bazarr\\../libs\\flask\\app.py", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "C:\\Bazarr\\bazarr\\../libs\\flask\\_compat.py", line 39, in reraise\n    raise value\n  File "C:\\Bazarr\\bazarr\\../libs\\flask\\app.py", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "C:\\Bazarr\\bazarr\\../libs\\flask\\app.py", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "bazarr\\main.py", line 119, in catch_all\n    return render_template("index.html", BAZARR_SERVER_INJECT=inject, baseUrl=template_url)\n  File "C:\\Bazarr\\bazarr\\../libs\\flask\\templating.py", line 138, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File "C:\\Bazarr\\bazarr\\../libs\\jinja2\\environment.py", line 869, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File "C:\\Bazarr\\bazarr\\../libs\\jinja2\\environment.py", line 830, in get_template\n    return self._load_template(name, self.make_globals(globals))\n  File "C:\\Bazarr\\bazarr\\../libs\\jinja2\\environment.py", line 804, in _load_template\n    template = self.loader.load(self, name, globals)\n  File "C:\\Bazarr\\bazarr\\../libs\\jinja2\\loaders.py", line 113, in load\n    source, filename, uptodate = self.get_source(environment, name)\n  File "C:\\Bazarr\\bazarr\\../libs\\flask\\templating.py", line 60, in get_source\n    return self._get_source_fast(environment, template)\n  File "C:\\Bazarr\\bazarr\\../libs\\flask\\templating.py", line 89, in _get_source_fast\n    raise TemplateNotFound(template)\njinja2.exceptions.TemplateNotFound: index.html'|
26/09/2021 14:30:32|ERROR   |app                             |Exception on /favicon.ico [GET]|'Traceback (most recent call last):\n  File "C:\\Bazarr\\bazarr\\../libs\\flask\\app.py", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File "C:\\Bazarr\\bazarr\\../libs\\flask\\app.py", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "C:\\Bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 269, in error_router\n    return original_handler(e)\n  File "C:\\Bazarr\\bazarr\\../libs\\flask\\app.py", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "C:\\Bazarr\\bazarr\\../libs\\flask\\_compat.py", line 39, in reraise\n    raise value\n  File "C:\\Bazarr\\bazarr\\../libs\\flask\\app.py", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "C:\\Bazarr\\bazarr\\../libs\\flask\\app.py", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "bazarr\\main.py", line 119, in catch_all\n    return render_template("index.html", BAZARR_SERVER_INJECT=inject, baseUrl=template_url)\n  File "C:\\Bazarr\\bazarr\\../libs\\flask\\templating.py", line 138, in render_template\n    ctx.app.jinja_env.get_or_select_template(template_name_or_list),\n  File "C:\\Bazarr\\bazarr\\../libs\\jinja2\\environment.py", line 869, in get_or_select_template\n    return self.get_template(template_name_or_list, parent, globals)\n  File "C:\\Bazarr\\bazarr\\../libs\\jinja2\\environment.py", line 830, in get_template\n    return self._load_template(name, self.make_globals(globals))\n  File "C:\\Bazarr\\bazarr\\../libs\\jinja2\\environment.py", line 804, in _load_template\n    template = self.loader.load(self, name, globals)\n  File "C:\\Bazarr\\bazarr\\../libs\\jinja2\\loaders.py", line 113, in load\n    source, filename, uptodate = self.get_source(environment, name)\n  File "C:\\Bazarr\\bazarr\\../libs\\flask\\templating.py", line 60, in get_source\n    return self._get_source_fast(environment, template)\n  File "C:\\Bazarr\\bazarr\\../libs\\flask\\templating.py", line 89, in _get_source_fast\n    raise TemplateNotFound(template)\njinja2.exceptions.TemplateNotFound: index.html'|`

**Software (please complete the following information):**
 - OS: Windows 10
 - Python 3.8.10

**Comment by halali** [comment]
How did you intall bazarr?

Because you have missing frontend from your installation.

**Comment by morpheus65535** [comment]
Known issue with dev branch that happened last week. Broken release due to a Github API malfunction.

Download lates bazarr.zip from latest release asset and put in in config/update directory. Restart bazarr and it should be fine.

**Comment by morpheus65535** [comment]
@soenneker May I close this issue?

**Comment by rudnypc** [comment]
I have the same problem with bazarr after the version 0.9.5

**Comment by morpheus65535** [comment]
@rudnypc cannot be as this issue is related only to beta releases. Update to 0.9.9 and if the issue happens again, open a new issue with proper informations.

**Comment by rudnypc** [comment]
> @rudnypc cannot be as this issue is related only to beta releases. Update to 0.9.9 and if the issue happens again, open a new issue with proper informations.

I have this problem with a provider, I installed the docker version and works fine.

**Comment by morpheus65535** [comment]
@rudnypc This issue is related to a broken installation, not to providers issues. If you have another issue, please open your own issue.
