### ISSUE TITLE
Podnapisi ssl error

### ISSUE THREAD

**Issue by lukjod** [morpheus65535/bazarr#1565]
Since a few days I always have SSL error on podnapisi provider, can smth be done on it

on qnap x64 docker latest stable version:
Bazarr Version
0.9.9
Sonarr Version
3.0.6.1342
Radarr Version
3.2.2.5080
Operating System
Linux-4.14.24-qnap-x86_64-with
Python Version
3.8.10
Bazarr Directory
/app/bazarr/bin
Bazarr Config Directory
/config

log of error:
Throttling podnapisi for 10 minutes, until 21/10/01 18:25, because of: SSLError. Exception info: MaxRetryError("HTTPSConnectionPool(host='podnapisi.net', port=443): Max retries exceeded with url: /subtitles/search/old?sXML=1&sL=pl&sK=The+Many+Saints+of+Newark&sY=2021 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)')))")

**Comment by morpheus65535** [comment]
Nothing good can be do on our side. Their SSL certificate is expired (in fact the root certificate is) and the only thing we can do is disable SSL certificate verification but it expose Bazarr to a man in the middle attack. I hope they'll replace their certificate ASAP.

**Comment by MrBrax** [comment]
the issue is how some devices handle the r3 cert, remove it from your certificate store and this should be fixed, also depends on what openssl version you use

**Comment by MrBrax** [comment]
> 
> 
> @MrBrax the users shouldn't have to worry about this. The webadmin have to properly include the full chain to prevent this kind of situation.

that's correct too, but it's still the default behaviour for certbot i'm pretty sure, so updating openssl or removing the cert would probably be easier

**Comment by MrBrax** [comment]
> 
> 
> > append to the crt file? it should be done automatically by certbot
> > Agreed but it doesn't seems to work...
> > odd, it's not expired for me when checking the certificate in the browser, looks the same as my domains
> > You're using Firefox? What OS and browser?

Firefox 92.0.1, Windows 10. Podnapisi R3 expires at Mon, 15 Sep 2025 16:00:00 GMT, X1 expires at Mon, 04 Jun 2035 11:04:38 GMT.

**Comment by morpheus65535** [comment]
I've just tested and with Chrome on Windows 10 it seems to work properly. Doesn't work on MacOS though neither older Linux distribution that won't get updated certification store.

TBH, I'm using Let's Encrypt certbot my self and I have no issue with my certificates that include the full chain.

**Comment by MrBrax** [comment]
Very odd. Maybe more and more software gets updated for it.

That's what i mean with clients, both sonarr/radarr/lidarr can be updated or ran on other mono versions to patch this behavior without disabling ssl, the library used for requests here must be using an older method or something

**Comment by MrBrax** [comment]
Gotcha, something else in the dependency chain causing problems then.
