### ISSUE TITLE
Select Subtitles will not save

### ISSUE THREAD

**Issue by ansuz07** [morpheus65535/bazarr#158]
**Describe the bug**
For select subtitles for specific shows, the subtitles will not save to the directory

**To Reproduce**
Normal searching for subtitles (manual or automatic)

**Expected behavior**
Subtilties should save

**Screenshots**
Here is the debug error:

     Traceback (most recent call last):
      File "c:\\bazarr\\get_subtitle.py", line 215, in manual_download_subtitle
       result = save_subtitles(video, [best_subtitle], single=True, encoding=\utf-8\)
      File "c:\\bazarr\\libs/subliminal\\core.py", line 771, in save_subtitles
       return [saved_subtitles, subtitle_path]
     UnboundLocalError: local variable \subtitle_path\ referenced before assignment

**Software (please complete the following information):**
 - Bazarr: 0.64
- Radarr version - latest
 - Sonarr version - latest
 - OS: - Win 10

**Comment by morpheus65535** [comment]
Should be fixed in 0.6.5

**Comment by morpheus65535** [comment]
0.6.5 not merged to master yet.

**Comment by hotio** [comment]
That's why I said that I'm running development :-)

A restart solved the problem for this particular episode

**Comment by morpheus65535** [comment]
Lol ok you right. :-)

I’m going to look at it again.

**Comment by hotio** [comment]
Seems like a hit or miss affair, second try it worked...

**Comment by morpheus65535** [comment]
That’s the problem, I have no clue how to reproduce it...
