### ISSUE TITLE
downloading forced subtitle remove the want for non-forced subtitle of the same language.

### ISSUE THREAD

**Issue by KBlixt** [morpheus65535/bazarr#1580]
**Describe the bug**
Downloading forced subtitles disables want for normal subtitle. opposite isn't true.

**To Reproduce**
- Have a movie on a profile that want subtitles for both English and forced English.
- Make sure the profile doesn't have a cut-off subtitle.
- Download only forced English.
- Movie want for normal English subtitle disappears.

**Expected behavior**
Movie still wanting normal English subtitle. 

**Software:**
 - Bazarr: 0.9.9 (:latest docker)
 - Radarr version 3.2.2.5080 (:latest docker)
 - OS: Linux

**Comment by KBlixt** [comment]
ok, sorry. great job (y)

**Comment by KBlixt** [comment]
I'm sorry, but this is still an issue. could you confirm that this is fixed? I'm on the latest docker image (v1.0.0)
![what am i doing wrong?](https://user-images.githubusercontent.com/32000265/141288584-a61db9aa-cd27-47d3-a11c-dc62c96574d3.png)

**Comment by morpheus65535** [comment]
@KBlixt It's been fixed for movies in 1.0.1-beta.7.

**Comment by KBlixt** [comment]
Excellent!
