### ISSUE TITLE
Removing our website (TuSubtitulo.com) from your script

### ISSUE THREAD

**Issue by TuSubtitulo** [morpheus65535/bazarr#1591]
Hello.

Firstable, greetings from our team at TuSubtitulo.com.

We thank you for thinking about us and incluiding us on "Bazarr".

However, we never received an email or any communication asking us for our permission in order to allow the use of any script or program on our servers,

The use of any script/program on our website it's prohibited right now, as we're working on some new features that are coming soon. In addition that our website it's fully centered to be a community, where the visits of our users are very important for us, cause it's the only way to keep us alive. We rely entirely of ads. And you would understand that your script it's interfering with the only thing that keep us on the Web.

We kindly ask you to remove us and stop using our website as a provider for subtitles as we asked several others in the past in doing so. (Which never asked us about any permission.)

Looking forward to any updates on this.

You can also communicate with us via contacto@tusubtitulo.com.

Thanks!

**Comment by TuSubtitulo** [comment]
Hello @morpheus65535, thanks for your answer.

I would like to have something clear. When you say "a paying tier (VIP or premium)", are you talking about us creating a paid system where users will have some exclusive features? And therefore you guys will be there? 

Or do you mean a "paid subcription" that's going to come from you because of the use of your script/program on our website?

Thanks in advance!

**Comment by Sockolet** [comment]
This is absolutely hilarious.
