### ISSUE TITLE
Username and password fields in settings of one provider are displaying information of previous provider

### ISSUE THREAD

**Issue by sambartik** [morpheus65535/bazarr#1592]
**Describe the bug**
The username and password fields show outdated information of currently selected provider settings. Instead of correct information, the username and password fields have filled out data of a previously selected provider.

**To Reproduce**
1. Go to Settings > Providers.
2. Have two providers added that have configurable username and password fields, and fill them out with test values.
3. Click on the first provider. All fields are correctly filled out.
4. Click on the second provider. The fields are filled out with provider's A data.

**Expected behavior**
The fields should be filled with second provider's data.

**Software (please complete the following information):**
 - Bazarr: 1.0.0
 - Radarr version 3.0.6.1342
 - Sonarr version 3.2.2.5080
 - OS: Linux-5.13.0-20-generic-x86_64-with

**Comment by LASER-Yi** [comment]
Should be fixed in the upcoming beta version
