### ISSUE TITLE
Can not remove a Notification setting

### ISSUE THREAD

**Issue by Ussagui** [morpheus65535/bazarr#1594]
**Describe the bug**
Can not remove a Notification setting

**To Reproduce**
1. Open Bazarr 
2. Go to settings/notifications
3. Add new notification
4. Try to remove it

**Expected behavior**
Remove the Notification setup (card/settings)

**Software (please complete the following information):**
 - Bazarr: [1.0.0]

**Comment by morpheus65535** [comment]
No news, good news.
