### ISSUE TITLE
Standard Subs not Seen as Missing when Forced Subs have been Downloaded

### ISSUE THREAD

**Issue by spaceboy76** [morpheus65535/bazarr#1596]
**Describe the bug**
where both standard and forced subs are required and bazarr has obtained forced subs for a movie, bazarr does not see the standard subs as missing

**To Reproduce**
set up as per image below

**Expected behavior**
standard subs should show as missing

**Screenshots**
![image](https://user-images.githubusercontent.com/9905053/139491732-9845cc8f-76e6-426b-8e71-0d859c2ab853.png)

settings
![image](https://user-images.githubusercontent.com/9905053/139491812-751a3867-ffbe-4425-82ec-b9111d7dd9e4.png)

**Software (please complete the following information):**
 - Bazarr: v1.0.1-beta.5
 - Radarr version 4.0.0.5391
 - Sonarr version 3.0.6.1357
 - OS: Windows 10

**Additional context**
none

**Comment by morpheus65535** [comment]
Fixed in upcoming beta.6: 3bc700225fc69737b466ed560519696094aa987d
