### ISSUE TITLE
Titulky.com: Skipping, because it doesn't match our series/episode

### ISSUE THREAD

**Issue by vysmaty** [morpheus65535/bazarr#1597]
**Describe the bug**
Skipping, because it doesn't match our series/episode. - Skips the result even if the subtitles found match.

**To Reproduce**
1. Manual search for: "Better Call Saul (2015) - S04E10 - Winner (1080p BluRay x265 RZeroX).mkv" _(Log ↓)_
2. No results.

**Expected behavior**
It should be located: https://premium.titulky.com/?action=detail&id=332647

**Log**
[clip.log](https://github.com/morpheus65535/bazarr/files/7448371/clip.log)

`31/10/2021 09:16:39|DEBUG   |root                            |BAZARR Manually searching subtitles for this file: /tv/Better Call Saul (2015)/Season 4/Better Call Saul (2015) - S04E10 - Winner (1080p BluRay x265 RZeroX).mkv|`
…
```
31/10/2021 09:16:39|DEBUG   |subliminal_patch.core           |GuessIt found: {
    "title": "Better Call Saul",
    "year": 2015,
    "season": 4,
    "episode": 10,
    "episode_title": "Winner",
    "screen_size": "1080p",
    "source": "Blu-ray",
    "video_codec": "H.265",
    "release_group": "RZeroX",
    "container": "mkv",
    "type": "episode"
}|
```
…
`31/10/2021 09:16:42|DEBUG   |root                            |BAZARR Skipping <TitulkySubtitle 'https://premium.titulky.com/?action=detail&id=332647' [cs:None]>, because it doesn't match our series/episode|`

`31/10/2021 09:16:42|DEBUG   |root                            |BAZARR 0 Subtitles have been found for this file: /tv/Better Call Saul`

**Software (please complete the following information):**
Bazarr Version: 1.0.1-beta.7
Sonarr Version: 3.0.6.1342
Radarr Version: 3.2.2.5080
Operating System: Linux-4.4.180+-x86_64-with (Docker)
Python Version: 3.9.5

**Additional context**
Thank you for this provider!

**Comment by sambartik** [comment]
Thank you for sharing the issue. I will look into it.

**Comment by morpheus65535** [comment]
@vysmaty can you test upcoming beta and co firm please?

**Comment by vysmaty** [comment]
@morpheus65535 Fixed. @sambartik Thank you.
