### ISSUE TITLE
[Feature Request] Reduce github api url hits

### ISSUE THREAD

**Issue by hotio** [morpheus65535/bazarr#160]
**Is your feature request related to a problem? Please describe.**
Everytime when `System` is clicked a request is made to github to check if a new Bazarr release is available, redundant in my opinion if you need to be on `Tasks` or `Logs`. Not sure what Github's policy is on this. What do they consider to much hits.....

**Describe the solution you'd like**
Do the  checking of a new release on a time interval (daily) and add a `Check for new release` button on the `Releases` tab page.

**Alternative for docker**
When running in docker/bare metal with `--no-update` the entire releases check and the tab page could even be ommited.

**Comment by morpheus65535** [comment]
I have read the policy and they talk about excessive or abusive usage. I will look into this but it won't be a top priority.

**Comment by hotio** [comment]
It really is only a problem when setting up and troubleshooting bazarr at the moment, because it clutters up the log when switching around in the interface, so low-priority is fine.

**Comment by morpheus65535** [comment]
This one is completed?

**Comment by halali** [comment]
Yes it was commited here https://github.com/morpheus65535/bazarr/commit/ac640e40541e10824950d8aa1be6f7c29a55d56e
