### ISSUE TITLE
Synchronization failed; consider passing --max-offset-seconds with a number larger than 60

### ISSUE THREAD

**Issue by ajkis** [morpheus65535/bazarr#1607]
Any chance we could add --max-offset-seconds to settings. 
I keep all my data in cloud in there could be an issue with access times. 

```
Bazarr Version 1.0.0
Sonarr Version 3.0.6.1342
Radarr Version 3.2.2.5080
Operating System Linux-4.4.0-210-generic-x86_64-with-Ubuntu-16.04-xenial
Python Version 3.7.10
Bazarr Directory /opt/bazarr
Bazarr Config Directory /opt/bazarr/data
```

```
ERROR   |ffsubsync.ffsubsync             |Synchronization failed; consider passing --max-offset-seconds with a number larger than 60|
07/11/2021 21:00:18|ERROR   |root                            |BAZARR unable to sync subtitles: /mnt/cloud/series/Scorpion/Season 01/Scorpion - S01E19 - Bluray-1080p.en.srt|
```
I can manually open and edit file /mnt/cloud/series/Scorpion/Season 01/Scorpion - S01E19 - Bluray-1080p.en.srt so there is no permission problems.

**Comment by morpheus65535** [comment]
The subtitles is too much out of sync to be properly synced. There's dozens of similar issues. Please use search prior to open a mew issue.
