### ISSUE TITLE
FeatureNotFound

### ISSUE THREAD

**Issue by chitalov** [morpheus65535/bazarr#1610]
these providers, subssabbz,subsunacs,yavkanet providers give an error FeatureNotFound !
[bazarr (2).log](https://github.com/morpheus65535/bazarr/files/7534447/bazarr.2.log)

docker-compose
Bazarr Version 
1.0.1-beta.13
Sonarr Version
3.0.6.1373
Radarr Version
4.0.0.5473
Operating System
Linux-5.4.0-90-generic-x86_64-with
Python Version
3.9.5
Bazarr Directory
/app/bazarr/bin
Bazarr Config Directory
/config

**Comment by morpheus65535** [comment]
You haven't installed lxml that is in requirements.txt?

**Comment by chitalov** [comment]
No, this is something new for me, and I always use the latest beta!

**Comment by morpheus65535** [comment]
Your log is clear, lxml is present. You must install it. You can provide output of `python3 -m pip list`?

**Comment by chitalov** [comment]
root@e52fe11ea332:/# python3 -m pip list
Package          Version
---------------- ------------
appdirs          1.4.4
CacheControl     0.12.6
certifi          2020.12.5
chardet          4.0.0
colorama         0.4.4
contextlib2      0.6.0
distlib          0.3.1
distro           1.5.0
html5lib         1.1
idna             3.2
lockfile         0.12.2
lxml             4.6.4
msgpack          1.0.2
numpy            1.21.4
ordered-set      4.0.2
packaging        20.9
pep517           0.10.0
pip              21.3.1
progress         1.5
pyparsing        2.4.7
requests         2.25.1
retrying         1.3.3
setuptools       58.5.3
six              1.15.0
toml             0.10.2
urllib3          1.26.5
webencodings     0.5.1
webrtcvad-wheels 2.0.10.post2

**Comment by chitalov** [comment]
root@e52fe11ea332:/# python3 -m pip list
Package          Version
---------------- ------------
appdirs          1.4.4
CacheControl     0.12.6
certifi          2020.12.5
chardet          4.0.0
colorama         0.4.4
contextlib2      0.6.0
distlib          0.3.1
distro           1.5.0
html5lib         1.1
idna             3.2
lockfile         0.12.2
lxml             4.6.4
msgpack          1.0.2
numpy            1.21.4
ordered-set      4.0.2
packaging        20.9
pep517           0.10.0
pip              21.3.1
progress         1.5
pyparsing        2.4.7
requests         2.25.1
retrying         1.3.3
setuptools       58.5.3
six              1.15.0
toml             0.10.2
urllib3          1.26.5
webencodings     0.5.1
webrtcvad-wheels 2.0.10.post2
root@e52fe11ea332:/#

**Comment by morpheus65535** [comment]
Who did produce that docker image? There's way to much module installed.

**Comment by morpheus65535** [comment]
BTW I've just tested with lxml==4.6.4 and it works as expected: 
![image](https://user-images.githubusercontent.com/5130500/141696323-8309b547-5699-4037-9b6f-63ff3c4c6dfc.png)

**Comment by chitalov** [comment]
from https://hub.docker.com/r/linuxserver/bazarr

---
version: "2.1"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:development
    container_name: bazarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Sofia
    volumes:
      - /opt/bazarr/config:/config
      - /data/Movies:/Movies
      - /data/TV-Shows:/TV-Shows
    ports:
      - 6767:6767
    restart: unless-stopped

**Comment by chitalov** [comment]
![image](https://user-images.githubusercontent.com/73425550/141696472-bef4da1c-2b96-4280-861e-32b5e0574a41.png)

**Comment by morpheus65535** [comment]
It was related to an issue with lxml wheel used in LSIO images. They moved to building it themself and it now works as expected.

https://github.com/linuxserver/docker-bazarr/pull/83

Can you update your container and confirm please?

**Comment by chitalov** [comment]
I Updated and everything works great. Thanks!!!
![image](https://user-images.githubusercontent.com/73425550/141829138-ed81c281-c5d3-45b4-b2b2-6c1595d8dad7.png)
