### ISSUE TITLE
Provider yifysubtitles error: "403 Client Error: Forbidden for url: https://yifysubtitles.org/..."

### ISSUE THREAD

**Issue by anonyme123** [morpheus65535/bazarr#1615]
**Describe the bug**
Throttling yifysubtitles for 10 minutes, until 21/11/20 07:26, because of: HTTPError. Exception info: '403 Client Error: Forbidden for url: https://yifysubtitles.org/movie-imdb/tt7097896'

**Screenshots**
<img width="1127" alt="Screen Shot 2021-11-20 at 14 50 14" src="https://user-images.githubusercontent.com/19681420/142728766-5f58bac5-eb5d-43fc-b27d-ac7fa3d562eb.png">

**Software (please complete the following information):**
Bazarr Version 1.0.1
Sonarr Version 3.0.6.1342
Radarr Version 3.2.2.5080
Operating System Linux-4.19.0-0.bpo.17-amd64-x86_64-with
Python Version 3.9.5
Bazarr Directory /app/bazarr/bin
Bazarr Config Directory /config

**Additional context**

**Comment by anonyme123** [comment]
Is this how Bazarr is supposed to behave when yifysubtitles has no entry for a given imdb ID? (tt7097896)

**Comment by morpheus65535** [comment]
This page doesn't even return a 403 but a 404. I suspect you've been blocked on their side.

**Comment by anonyme123** [comment]
I have not been blocked, it's just that yifysubtitles doesn't have an entry for that particular imdb ID (tt7097896)

Here is a random movie where I get a 200 OK:
<img width="877" alt="Screen Shot 2021-11-20 at 19 10 15" src="https://user-images.githubusercontent.com/19681420/142736821-3ba01390-8c6e-4579-a56a-e48d895d0b02.png">

Here is the movie with imdb ID tt7097896 that returns a 404:
<img width="598" alt="Screen Shot 2021-11-20 at 19 12 03" src="https://user-images.githubusercontent.com/19681420/142736836-1a0eb97f-c93f-4de8-975d-a51e69bc0c92.png">

My question is: should the provider be throttled when a 404 is returned? i.e. will subs for other movies/tv shows continue to be searched using that provider?

**Comment by morpheus65535** [comment]
404 is throttled but you had a 403, not a 404.

**Comment by anonyme123** [comment]
Did Bazarr incorrectly report a 403 when it actually was a 404?

Does throttling mean the provider will stop being used for a while for any movie/show? Or just tor the movie/show it got the http 4xx error?

**Comment by morpheus65535** [comment]
Not possible. The http error is raised by the requests Python module, not by Bazarr itself. 

Once a provider is throttled, it's for all search.

**Comment by anonyme123** [comment]
Got it. Could we pause querying the provider for just the show/movie that failed?
This way one movie not being yet in a provider's database doesn't negatively impact sub search for all other content.

**Comment by morpheus65535** [comment]
No, that's not possible. Either you disable the language profile on this movie or find it elsewhere using manual search or even upload function.

**Comment by anonyme123** [comment]
Ok it's too complicated to implement?

**Comment by morpheus65535** [comment]
Holy shit yes!

**Comment by anonyme123** [comment]
Ok I can imagine ^^
