### ISSUE TITLE
opensubtitlescom ProviderError. Exception info: 'Invalid JSON returned by provider'

### ISSUE THREAD

**Issue by anonyme123** [morpheus65535/bazarr#1616]
**Describe the bug**
Throttling opensubtitlescom for 10 minutes, until 21/11/20 22:05, because of: ProviderError. Exception info: 'Invalid JSON returned by provider'

**Screenshots**
<img width="1214" alt="Screen Shot 2021-11-20 at 22 08 55" src="https://user-images.githubusercontent.com/19681420/142740955-dbff58cf-ee1e-4dfb-b9f8-c78510a5f536.png">

**Software (please complete the following information):**
Bazarr Version 1.0.1
Sonarr Version 3.0.6.1342
Radarr Version 3.2.2.5080
Operating System Linux-4.19.0-0.bpo.17-amd64-x86_64-with
Python Version 3.9.5
Bazarr Directory /app/bazarr/bin
Bazarr Config Directory /config

**Additional context**

**Comment by morpheus65535** [comment]
Probably a temporary issue with this provider, working fine now.

**Comment by pittbull** [comment]
I'm seeing this error constantly now and I am unable to download subtitles. If the OS is refreshed and listed as good it will fail again when I force a search on my list of missing subtitles.

Running version 1.0.2 and the standard logs does not show any error except what is stated by anonyme123.

**Comment by morpheus65535** [comment]
@pittbull I've confirmed with os.com admin that it's an issue with the service. From time to time (like very often), they return a 502/503 with a Bad Gateway status. v1.0.3 show this as throttled status instead of json error.

**Comment by pittbull** [comment]
aha... Thank you. Let's hope they are on the case.

**Comment by morpheus65535** [comment]
Let say that they are a bit overwhelmed by the last week hack. I hope they get on track ASAP.
