### ISSUE TITLE
Error when scanning for subtitles from bsplayer

### ISSUE THREAD

**Issue by corylowry12** [morpheus65535/bazarr#1618]
**Describe the bug**
When i have bsplayer added, and i go to manually scan for subtitles. It throws an exception.

**To Reproduce**
1. Go to settings and add bsplayer
2. Click on which movie has missing subtitles
3. Click on manual search
4. It will never show subtitles and throw an error in command prompt

**Expected behavior**
I expect it to find subtitles from bsplayer

**Software (please complete the following information):**
 - Bazarr: 10.1
 - Radarr version 4.0.0.5519
 - OS: Windows 11

**Comment by morpheus65535** [comment]
Bazarr 10.1 doesn't exist. Check with your seedbox provider. You can disable BSplayer, it's broken for a long time.
