### ISSUE TITLE
Bazarr does not return the subtitles of addic7ed for the series Dexter: New Blood

### ISSUE THREAD

**Issue by florianfranconi** [morpheus65535/bazarr#1619]
**Describe the bug**
I have a problem with addic7ed and the new Dexter series. Bazarr can't find any subtitles even though there are some.
After exchanges on Discord and sharing my logs, it seems that the `-` in the file name is a problem. Indeed, sonarr considers the `:` as a special character and renames the file from `Dexter: New Blood` to `Dexter - New Blood`. Bazarr does a search on Dexter where it finds a match for the series but not for the episode in question and therefore does not search for the alternative title Dexter New Blood.

**To Reproduce**
1. Download episodes of the new series [Dexter: New Blood (2021)](https://www.imdb.com/title/tt14164730/) with sonarr
2. Go on Bazarr and click on this serie
3. Make a manual search to download subtitles
4. Bazarr can't find any subtitle for addic7ed even though there are [some](https://www.addic7ed.com/show/8661)

**Expected behavior**
Bazarr should return the subtitles of addic7ed as he does for the others provide

**Screenshots**
![bazarr_dexter](https://user-images.githubusercontent.com/23030829/143033498-80f5745c-e53a-4c41-9013-6af4eaff9e7a.png)

**Software (please complete the following information):**
 - Bazarr: [e.g. v1.0.1]
 - Radarr version [e.g. v 3.2.2.5080]
 - Sonarr version [e.g. v 3.0.6.1342]
 - OS: [e.g. Synology DSM7 - Docker]

**Comment by morpheus65535** [comment]
Should be fixed in upcoming 1.0.2-beta.1.

**Comment by florianfranconi** [comment]
Yes I confirm it works perfectly on the 1.0.2-beta.1.

Thanks a lot!
