### ISSUE TITLE
Hosszupuska provider not returning any results

### ISSUE THREAD

**Issue by GhostPunk** [morpheus65535/bazarr#1620]
**Describe the bug**
[Hosszupuska](http://hosszupuskasub.com) not parsing the results page right. I'm not sure if they changed something or not, this is my first try with the provider and bazarr itself.
The problem seems to be that the parser chooses the wrong table.

**To Reproduce**
1. Search (almost) any subtitle with Hosszupuska provider. It is a hungarian page so language should be hungarian and/or english. Example: AHS http://hosszupuskasub.com/sorozatok.php?cim=American+Horror+Story&evad=10&resz=01&nyelvtipus=%25&x=24&y=8
2. Get no results

**Expected behavior**
Getting results.

**Software (please complete the following information):**
 - Bazarr: 1.0.1
 - Sonarr version 3.0.6.1342
 - OS: Ubuntu 20.04 LXC container Linux-5.11.22-5-pve-x86_64-with-glibc2.29

**Additional context**
After running the code in debug mode I found out that in subliminal_patch/providers/hosszupuska.py
` table = soup.find_all("table")[9]`
probably should be
` table = soup.find_all("table")[10]`
When the parser loads [9] it is the "Mai 5 legnézettebb:" (means Top 5 most watched on this day) box from the left bottom side. See my previous example link.
So unless you searched for any of this 5 particular shows you will get no results.

**Comment by morpheus65535** [comment]
Are you willing to open PR to dev branch for both issues? If not I will do it but TBH I'm quite busy right now and having this fixed would benefit to everyone.

**Comment by vitiko98** [comment]
See #1621

**Comment by GhostPunk** [comment]
fixed with #1621
