### ISSUE TITLE
Hosszupuska not returning all the results

### ISSUE THREAD

**Issue by GhostPunk** [morpheus65535/bazarr#1621]
**Describe the bug**
I have decided to open a separate bug for this since the two are unrelated. See #1620 
Even after fixing the provider to parse the right table it does not return all the results.

**To Reproduce**
1. Search for something on Hosszupuska after the fix in #1620 
2. See the results
3. Compare it with result from the site itself. Example with many results, this one is wrong for sure: http://hosszupuskasub.com/sorozatok.php?cim=American+Horror+Story&evad=10&resz=01&nyelvtipus=%25&x=24&y=8

**Expected behavior**
Return all matching subtitles.

**Software (please complete the following information):**
- Bazarr: 1.0.1
- Sonarr version 3.0.6.1342
- OS: Ubuntu 20.04 LXC container Linux-5.11.22-5-pve-x86_64-with-glibc2.29

**Additional context**
Problem might be related to this line in subliminal_patch/providers/hosszupuska.py:
`if "this.style.backgroundImage='url(css/over2.jpg)" in str(row) and i > 5:`
I'm not sure why in the past it was necessary to start from i > 5 but deleting that condition and parsing all trs with over2.jpg seems to fix it:
`if "this.style.backgroundImage='url(css/over2.jpg)" in str(row):`

**Comment by vitiko98** [comment]
It should work now.

**Comment by vitiko98** [comment]
It looks like four results is the expected behavior. Note that the last two in the link you provided [link](http://hosszupuskasub.com/sorozatok.php?cim=American+Horror+Story&evad=10&resz=01&nyelvtipus=%25&x=24&y=8) are from season 1, not season 10.

**Comment by GhostPunk** [comment]
> It looks like four results is the expected behavior. Note that the last two in the [link](http://hosszupuskasub.com/sorozatok.php?cim=American+Horror+Story&evad=10&resz=01&nyelvtipus=%25&x=24&y=8) you provided are from season 1, not season 10.

Yes, four is expected here, results from season 1 is a bug in the site.
Thank you for the fix, after checking it it's much better than the one I threw together.
