### ISSUE TITLE
streaming_provider not considered in score

### ISSUE THREAD

**Issue by GhostPunk** [morpheus65535/bazarr#1622]
**Describe the bug**
I'm not sure if this is intentional or not but streaming_provider is not adding anything to the subtitle score. I have managed to find a case on my first download where because of this bazarr chooses the wrong subtitle.

**Screenshots**

![Screen Shot 2021-11-23 at 16 38 51](https://user-images.githubusercontent.com/1549673/143056726-1f147e66-d705-407c-baca-6dc366871156.png)
![Screen Shot 2021-11-23 at 16 38 41](https://user-images.githubusercontent.com/1549673/143056762-ddd77788-d6cd-46a9-809d-678444f40257.png)

**Software (please complete the following information):**
- Bazarr: 1.0.1
- Sonarr version 3.0.6.1342
- OS: Ubuntu 20.04 LXC container Linux-5.11.22-5-pve-x86_64-with-glibc2.29

**Comment by morpheus65535** [comment]
In the current implementation, streaming_service worth 0. This should evolve in the future once @vitiko98 resume his work on custom scoring.
