### ISSUE TITLE
Error trying to get releases from Github. Http error.	

### ISSUE THREAD

**Issue by anonyme123** [morpheus65535/bazarr#1625]
**Describe the bug**
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/check_update.py", line 23, in check_releases
    r.raise_for_status()
  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100

**Software (please complete the following information):**
Bazarr Version 1.0.1
Sonarr Version 3.0.6.1342
Radarr Version 3.2.2.5080
Operating System Linux-4.19.0-0.bpo.17-amd64-x86_64-with
Python Version 3.9.5
Bazarr Directory /app/bazarr/bin
Bazarr Config Directory /config

**Comment by morpheus65535** [comment]
There's been issue with Github in the last hours. Bazarr is normaly making one single call to their API every 6 hours so there's no chance to get rate limited by them unless something else is abusing from their API from your IP.

**Comment by anonyme123** [comment]
Ah yes, seems to be all good now:

<img width="595" alt="Screen Shot 2021-11-29 at 13 05 42" src="https://user-images.githubusercontent.com/19681420/143865238-dc2e96dc-0329-4ff4-9f6e-15e565321476.png">

**Comment by anonyme123** [comment]
Issue still occurring today (30/11/2021 10:53:11 CET):

Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/check_update.py", line 23, in check_releases
    r.raise_for_status()
  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100

**Comment by morpheus65535** [comment]
Something else is causing this. Bazarr doesn't call the API that much.

**Comment by anonyme123** [comment]
According to this: https://docs.github.com/en/rest/overview/resources-in-the-rest-api

- For API requests using Basic Authentication or OAuth, you can make up to 5,000 requests per hour.
- When using the built-in GITHUB_TOKEN in GitHub Actions, the rate limit is 1,000 requests per hour per repository.
- For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.

If you multiply by the amount of Bazarr installs worldwide, could the limit be reached?
Are those requests authenticated? If not, in my case I'm using a shared VPS which might explain the limit reach on my provider's IP.

**Comment by morpheus65535** [comment]
> If you multiply by the amount of Bazarr installs worldwide, could the limit be reached? 
Unless all Bazarr users come from the same IP, no, there's no reason that they get throttled.

> Are those requests authenticated? 
Nope, unauthenticated call.

> If not, in my case I'm using a shared VPS which might explain the limit reach on my provider's IP.
If there's a lot of users making requests to Github from this shared IP (from Bazarr or ny other way), this is certainly the cause.

**Comment by anonyme123** [comment]
Yes it's a pretty popular VPS provider, not sure how many users they have on a single IP, it might be a lot.
Could a fix from your side be provided to remedy this situation? (authenticate the api call maybe?) 🙏

**Comment by morpheus65535** [comment]
> Yes it's a pretty popular VPS provider, not sure how many users they have on a single IP, it might be a lot. Could a fix from your side be provided to remedy this situation? (authenticate the api call maybe?) 🙏

This would need to be authenticated with your credentials. There's nothing planned about this and I don't see how it could change for a long time.

Anyway, running Bazarr on a VPS is highly discouraged because you'll run into throttling with providers all the time.

**Comment by anonyme123** [comment]
Gotcha, is there an option somewhere to disable auto updates? I cannot find any.

**Comment by morpheus65535** [comment]
No there's no way to prevent from getting the release notes.

**Comment by anonyme123** [comment]
What about this?

<img width="617" alt="Screen Shot 2021-11-30 at 22 09 09" src="https://user-images.githubusercontent.com/19681420/144128453-42edd48d-3587-439c-bae1-ca946fcbfc8f.png">

**Comment by morpheus65535** [comment]
Your Docker isn't trying to update but simply to get the release notes. There's no way to disable it.

**Comment by anonyme123** [comment]
What if I comment this block?

<img width="705" alt="Screen Shot 2021-11-30 at 22 12 50" src="https://user-images.githubusercontent.com/19681420/144128927-4c92b49b-7291-461f-ac21-6ebab092ccdd.png">

**Comment by morpheus65535** [comment]
The scheduled task will raise an ImportError every 3 hours.

You can comment out the scheduled job but it will be overwriten on each version upgrade:
https://github.com/morpheus65535/bazarr/blob/master/bazarr/scheduler.py#L224-L227
