### ISSUE TITLE
Request failed with status code 431

### ISSUE THREAD

**Issue by redglory** [morpheus65535/bazarr#1628]
**Describe the bug**
Bazarr can't refresh any series when clicking "Scan Disk"

**To Reproduce**
1. Go to any series
2. Click on 'Scan Disk'
3. See error

**Expected behavior**
Series should be refreshed and subtitles scanned.

**Screenshots**
https://i.imgur.com/VG1qiHz.png

**Software (please complete the following information):**
Bazarr Version
1.0.1
Sonarr Version
3.0.6.1342
Radarr Version
4.0.0.5553
Operating System
Windows-10-10.0.19041-SP0
Python Version
3.8.0

Brave browser inspect:
Failed to load resource: the server responded with a status of 431 (Request Header Fields Too Large)

when opening source request (can be seen here: https://paste.kodi.tv/etodevenif)
Request Header Fields Too Large

exceeds max_header of 262144

(generated by waitress)

It looks that the query is somewhat weird ?!

**Comment by redglory** [comment]
Well... Just clearing browser's cache solved this issue.

Tried first to open in another browser and it opened as expected.

**Comment by morpheus65535** [comment]
This iften happen with improperly configured reverse proxy. Maybe it's your case?

**Comment by redglory** [comment]
Hi @morpheus65535 I don't use any reverse proxy :)

Thanks anyway
