### ISSUE TITLE
legendas.tv download packs

### ISSUE THREAD

**Issue by rudnypc** [morpheus65535/bazarr#1629]
**Describe the bug**
When I download "Buffy the Vampire Slayer" Bargaining: Part 2, the legendas.tv has a pack of subtitle with s06e02 in portuguese, but the bazarr doesn't download this files.
Bazarr
![image](https://user-images.githubusercontent.com/50679581/144725353-75d26b9d-74b1-4e36-8fff-53f2ccc33341.png)

![image](https://user-images.githubusercontent.com/50679581/144725442-a736a641-1fbe-4a75-adf3-ca1ba6b50b5b.png)

Legendas.tv
![image](https://user-images.githubusercontent.com/50679581/144725461-614382c1-3e7d-4b01-85dc-bb420f251b1c.png)

**Comment by morpheus65535** [comment]
Where's the debug log when you reproduce the issue? 

BTW I won't put much effort for a single show issue. This provider is so shitty anyway they have no decent way of organizing tv show properly. It's free text search and you can even search with imdb id or something like this.

**Comment by morpheus65535** [comment]
No news, good news.
