### ISSUE TITLE
SDH Subtitles

### ISSUE THREAD

**Issue by Protektor-Desura** [morpheus65535/bazarr#1634]
Subtitles for the Deaf or Hard-of-Hearing (SDH) is a form of subtitles originating in America. SDH combines the benefits of both Subtitles and Closed Captions. SDH are intended for viewers who are both Deaf or Hard-of-Hearing and do not understand the language spoken in the video.

Subtitles for the deaf and hearing impaired are not being labeled properly. They are suppose to be labeled SDH then language code.

So the subtitle should be titled.
/movie/Blade Runner (1982)/Blade Runner (1983).sdh.en.srt
/movie/Blade Runner (1982)/Blade Runner (1983).sdh.eng.srt

**Comment by morpheus65535** [comment]
Sorry but you're wrong. The modifier must be after the language code. Bazarr use "hi" for both sdh and hi but will recognize "hi", "sdh" and "cc" as hearing impaired in Bazarr.

Some references:
https://support.plex.tv/articles/200471133-adding-local-subtitles-to-your-media/

Kodi, Plex, Emby and Jellyfin should all recognize them properly.

**Comment by LostOnTheLine** [comment]
Does the program detect if the subtitles are SDH or HI or CC? The OP's post sounds like it's doing the detection he's just confused about the formatting order. But I've been looking for a program to autodetect language for Subtitle files, which I found, now I would like to be able to detect if they are CC/SDH. This issue suggests it does, but I cannot find anything in the details that says it does.

**Comment by morpheus65535** [comment]
> Does the program detect if the subtitles are SDH or HI or CC? The OP's post sounds like it's doing the detection he's just confused about the formatting order. But I've been looking for a program to autodetect language for Subtitle files, which I found, now I would like to be able to detect if they are CC/SDH. This issue suggests it does, but I cannot find anything in the details that says it does.

Yes it does using regex.

**Comment by LostOnTheLine** [comment]
> Yes it does using regex.

Cool. Is there a way to use bazarr to do that if I don't use the other programs it works with? If not which programs would I need if all I am using it for is detecting & labeling subtitle files that I already have?

**Comment by LostOnTheLine** [comment]
> Bazarr require Sonarr/Radarr

I don't mind having the program so long as it lets me work with files I bring myself & not just what those programs download.

Also is there a way to edit the expressions used in RegEx to detect the language? I've been using SRT-Lang-Detect for language detection, which often gives a lot of ENG results that are not ENG, if I can edit the detecting parameters to look for certain contractions like don't & can't or whichever it was I used to use when I was manually doing it years ago, & could do the SDH detection in the same go & rename it the way I choose that saves me like 5 steps.

**Comment by LostOnTheLine** [comment]
> Maybe you can give filebot a try.

Darn. Thanks. The reason I was looking into this was because I saw that it could detect & label SDH. I remember looking at filebot at one point & there was something I didn't like, maybe it didn't support VTT subtitles or something, but I'll give it another look

**Comment by LostOnTheLine** [comment]
I just looked at FileBot, it doesn't seem to be able to give language codes or sdh tags at all, plus it's a paid software, I'm not paying for something that doesn't even look like it will do anything that I can't already do better with stuff I already have or get for free. Thanks for trying though.
Is there possibly a way to make it think it's downloading them from a source that is actually on my local network? If it'll only rename things it downloads then I think this is my last ditch attempt to make it work. I don't want to get in trouble for downloading better subtitles for things I already own through a torrent, I don't want srt or ssa/assa subtitles unless they are the only things available, so using a program like this to automagically find them doesn't work for me, plus if it just gets them then I don't know if they are in sync or out of sync until I'm watching them, or worse when someone else is watching them. I guess I'll just keep looking
