### ISSUE TITLE
Subscene provider: login is not mandatory

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#1635]
**Describe the bug**
When I try to configure Subscene in Bazarr it request the user/password but the credentials are not required in the website. Could you make the login optional?

**Software (please complete the following information):**
 - Bazarr: 1.0.1
 - Radarr version [e.g. v 0.2.0.0001]
 - Sonarr version [e.g. v 2.0.0.0001]
 - OS: [e.g. Windows 10]

**Comment by morpheus65535** [comment]
It's not a bug but a feature request. Please use the proper platform to make that request.

**Comment by ngosang** [comment]
https://bazarr.featureupvote.com/suggestions/258248/make-login-optional-in-subscene-provider
