### ISSUE TITLE
Any way to prevent Addic7ed IP ban?

### ISSUE THREAD

**Issue by jant90** [morpheus65535/bazarr#1637]
**Describe the bug**
After enabling Addic7ed provider I get IP banned (almost immediately). Also mentioned in #1034.

**To Reproduce**
1. Enable Addic7ed provider
2. Download a season of a TV show.

**Expected behavior**
Search Addic7ed and throttle before hitting the IP ban?

**Software (please complete the following information):**
 - Bazarr: 1.0.1
 - Radarr 3.2.2.5080
 - Sonarr 3.0.6.1342
 - OS: Manjaro

**Additional context**
I get IP banned in minutes after enabling Addi7ed in Bazarr. Can I do anything to prevent this from happening? Throttling AFTER getting banned obviously doesn't help with that. And when the IP ban expires it doesn't take long before I'm IP banned again.

Bottom-line is that Addic7ed as a provider is useless like this because I'm banned all the time and other providers will download the subs, I would greatly prefer Addic7ed however for their high quality subs.

**Comment by TRaSH-** [comment]
Do you have a anti captcha provider enabled and in use ?

**Comment by jant90** [comment]
Yes, I use Anti-Captcha. I have credits in my account and set the API key in Bazarr. I assume Bazarr will then use it right? There is not some hidden button to enable the anti captcha provider?

**Comment by morpheus65535** [comment]
There's some issue with Addic7ed being throttled for HTTPError once in a while. I need to put some time into it.

On a side note, are you running Bazarr from a VPS/seedbox or using a VPN? Those are subject to be IP banned because of multiple instance running from the same IP.

**Comment by jant90** [comment]
I'm hosting at home, so I'm on a residential IP. I do have a small, relatively unknown ISP however.

I can imagine this is hard to debug because with an IP ban there are no server errors that can give a hint why this is happening.

Is there anything I can try? I get the feeling that people are using Addic7ed without these issues so I'm hoping there;s something.

**Comment by morpheus65535** [comment]
The problem is that there's no warning, they just stop responding to our requests. I have to figure out what's triggering the ip ban (how much requests per period they support). I should be able to work on this during the holidays.

**Comment by jant90** [comment]
Alright thanks! Maybe it would be possible to add a rate limit option for Addic7ed as well? So every user can limit requests as they see fit until there are no more IP bans.

**Comment by morpheus65535** [comment]
This commit should help: https://github.com/morpheus65535/bazarr/commit/5d1dccde995138e631916dcef44a7527b7cdc6b6
