### ISSUE TITLE
Wrong Series Match

### ISSUE THREAD

**Issue by MrBamse** [morpheus65535/bazarr#1639]
**Describe the bug**
Path and name matching series A but poster and episodes are from series B.

**To Reproduce**
1. Setup Docker container from lscr.io/linuxserver/bazarr using docker-compose
2. Configured Sonarr connection in Bazarr successfully 
3. Noticed that some, not all, series are missmatched, so far haven't found any movies being missmatched.
4. See attached images for results.

**Expected behavior**
To path and name to match poster and episode list.

**Screenshots**
The "mixed" series in Bazarr:
<img width="1780" alt="Bazarr" src="https://user-images.githubusercontent.com/80944276/145677311-0a8184b1-3cb1-406c-b8ed-c55aa617ccb4.png">

Original series A in Sonarr:
<img width="1759" alt="Sonarr" src="https://user-images.githubusercontent.com/80944276/145677312-2ae07152-5225-4d73-976f-580af4fd182e.png">

Original series B in Sonarr:
<img width="1763" alt="Sonarr-2" src="https://user-images.githubusercontent.com/80944276/145677327-29580edb-342b-4dc9-8626-8790488360a7.png">

**Software (please complete the following information):**
 - Bazarr: v1.0.12021-11-19 Master
 - Radarr version 3.2.2.508 (3.2.2.5080-ls124 by linuxserver.io)
 - Sonarr version 3.0.6.13420 (3.0.6.1342-ls128 by linuxserver.io)
 - OS: Debian 11.1 Buster

**Edits**
- 20211211-1 Seems like the error starts around F where every series is "shifted" one step and "mixes" with the adjacent series.

**Comment by morpheus65535** [comment]
Did you reinstall Sonarr?

**Comment by MrBamse** [comment]
Not to my knowledge I installed all three (Bazarr, Sonarr, Radarr) roughly one week ago.
The containers update if there is a new image but other than that, no update. And they all have their own separate persistent config-folders setup in their docker-compose.yml

**Comment by morpheus65535** [comment]
Enable debug logging and force the series sync with Sonarr task. Provide the log and I'll try to see what's wrong during the weekend.

**Comment by MrBamse** [comment]
Cool, thank you. You are the best! :
[20211211_docker_reboot_sonarr_sync.log](https://github.com/morpheus65535/bazarr/files/7697112/20211211_docker_reboot_sonarr_sync.log)
)

**Comment by morpheus65535** [comment]
First, disable bsplayer, it's broken anyway and will just cause trouble.

Second, `UNIQUE constraint failed: table_shows.tvdbId` means that you have either 2 times the same series in Sonarr and Bazarr isn't dealing with that or, you've recreated your Sonarr config after starting the synchronization with Bazarr.

Could you provide the output from this request: `http://localhost:8989api/v3/series?apikey=###############################`. Replace localhost fi required and make sur to put your Sonarr apikey also.

If you want, you can send me the JSON output in PM on Discord.

**Comment by MrBamse** [comment]
Cause: Seem to be like I updated my series in Sonarr while Bazarr was indexing/syncing with Sonarr. This caused the "out of sync" behavior.

Solution: Stop Bazarr, and empty the tables of series. I use a docker container so my sqlite-db could be found under config/db/
sqlite3 bazarr.db
DELETE FROM table_shows;
DELETE FROM table_episodes;
(ctrl-d)
Start up Bazarr again and let it index everything before you do any additional changes.

Thank you so much to morpheus65535 for helping me out with this issue! :)
