### ISSUE TITLE
[Feature Request] Only search for x number of weeks

### ISSUE THREAD

**Issue by hotio** [morpheus65535/bazarr#164]
A feature that will only search the latest movies/tvshows from the last x number of weeks to reduce the api hits for subtitles that probably will never be found.

**Comment by morpheus65535** [comment]
Have you taken a look to adaptive search?

**Comment by morpheus65535** [comment]
I don't remember what are exactly the parameters but after a couple of weeks, it search less often.

**Comment by hotio** [comment]
After a quick look at the code I think Adaptive Searching could be what I wanted....? Perhaps @halali can confirm this? Does adaptive searching prevent bazarr from trying to get subtitles for over 1000 old episodes all at once eliminating a block by one of the providers?

**Comment by halali** [comment]
after 3 weeks of searching, it will search only once per week

**Comment by hotio** [comment]
So it will still try to search 1000's of subtitles once a week if no subtitles are found. It will not ignore old files for which probably no subtitles can be found?


This will need manual attention from the user to prevent being blocked....

**Comment by morpheus65535** [comment]
What would be your criteria to determine that we should not search again?

**Comment by halali** [comment]
If you dont want search subs for some episodes, just unmonitor them in sonarr

**Comment by hotio** [comment]
A user configurable option for x number of recent days. Only files that are more recent will be searched. The user can increase this until his entire library is in order or keep at a reasonable value. No point in searching for subtitles if the movie is older than a year, again and again....

**Comment by morpheus65535** [comment]
Maybe. We’ll see what we do when we get there. Btw, API call are counted on download, not search.

**Comment by hotio** [comment]
All I know is that I lett bazarr search for 1900 subtitles and addi7ed blocked my ip

**Comment by halali** [comment]
i downloaded 3500 subs in 7 hours from addi7ed ans OS with stop download after 200subs. and no problem

**Comment by hotio** [comment]
Dunno, not making this stuff up

**Comment by morpheus65535** [comment]
For now, we won't take this one as there's workaround.

**Comment by hotio** [comment]
Fine for me, I'm however blocked again by Addic7ed. lol

You guys probably have a paid account, no?

**Comment by hotio** [comment]
Offcourse I have an account, just a free account, I saw the counter on my account page go up to 16 for downloads from IP, that was the highest I got to see, after a page refresh the IP was banned. Does bazarr properly login? Because it should have been substracted from the 40 downloads for a user.

**Comment by halali** [comment]
if you have problem with  Addic7ed try another providers. with OpenSubtitles you can download 200 subs per account/ip

**Comment by hotio** [comment]
I think I found the problem and I should be ashamed of myself, it had nothing to do with bazarr. Doing a search on opensubtitles now with a minimum score of 100%, that should stay under 200.

**Comment by morpheus65535** [comment]
Could be something to try. Normally I suggest 90 or even 95 but to achieve what you want, start with 100.
