### ISSUE TITLE
Visual bug when movies have the same title

### ISSUE THREAD

**Issue by plexembybr** [morpheus65535/bazarr#1642]
**Describe the bug**
When searching for a movie that has the same title as another movie, Bazarr will start to create new "movies entries" every time your search for that title.

**To Reproduce**
1. Add movies with the same title to your library [tt13207508](https://www.imdb.com/title/tt13207508/) [tt10832274](https://www.imdb.com/title/tt10832274)
2. Search for the title and click on one of the results
3. Search again for that title and see the bug happen

**Expected behavior**
Bazarr auto-complete should suggest only two titles instead of multiples

**Screenshots**

https://gifyu.com/image/SSNVV

**Logs**
 https://paste.centos.org/view/7603caaf

**Software (please complete the following information):**
 - Bazarr:1.0.2-beta.8
 - Radarr version 3.2.2.5080
 - OS: CentOS 8 Stream

**Comment by morpheus65535** [comment]
@LASER-Yi can you look into this one please?

**Comment by LASER-Yi** [comment]
> @LASER-Yi can you look into this one please?

Let me check

**Comment by LASER-Yi** [comment]
Should be fixed in next beta. Thanks for reporting!

**Comment by plexembybr** [comment]
I can confirm that this issue has been fixed. Thank you!
