### ISSUE TITLE
not working provider LegendasDvix "AttributeError"

### ISSUE THREAD

**Issue by n0pe0n** [morpheus65535/bazarr#1644]
Describe the bug
When searching for subtitles with the provider "legendasdivx", he cannot find subtitles for the movie or series i am looking for. something is going wrong "AttributeError" in status.

See debuglog file.
[Bazarr.log](https://pastebin.com/qbkZhQhE)

To Reproduce

Search for subtitles for movie/series
Expected behavior
Expect to find the subtitles listed on the site.

Screenshots

Software (please complete the following information):

Bazarr Version: 1.0.2-beta.9
Sonarr Version: 3.0.6.1342
Radarr Version: 3.2.2.5080
Operating System: Linux-4.15.0-163-generic-x86_64-with
Python Version: 3.9.7

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta release. Can you test and confirm please?

**Comment by n0pe0n** [comment]
> Should be fixed in upcoming beta release. Can you test and confirm please?

yes in the next update we will test it, thhks for the help

**Comment by n0pe0n** [comment]
@morpheus65535 got resolved! Thks buddy, happy holidays :)

**Comment by morpheus65535** [comment]
You to mate!
