### ISSUE TITLE
Update AppRise to 0.9.6+

### ISSUE THREAD

**Issue by nicjansma** [morpheus65535/bazarr#1647]
**Describe the bug**
I would like to request the included Apprise dependency be updated to latest (e.g. `0.9.6`)

I'm looking to get this bug fix, for my single-character hostname: https://github.com/caronc/apprise/pull/475

https://github.com/caronc/apprise/releases/tag/v0.9.6

**To Reproduce**
1. Go to Notifications
2. Click on Add, choose Gotify
3. Put in a URL with a single-character hostname portion (e.g. `gotifys://a.home.com`)
4. See message `ERROR (__init__:491) - Unparseable Gotify URL gotifys://a.home.com/`

This is fixed in a recent version of apprise.

**Expected behavior**
A Gotify notification happens

**Screenshots**
n/a

**Software (please complete the following information):**
- Bazarr Version: 1.0.1
- Sonarr Version: 3.0.6.1342
- Radarr Version: 3.2.2.5080
- Operating System: Linux-5.10.61-1.ph4-x86_64-with

**Additional context**
I realize updates to dependencies aren't always easy but I'm hoping it's simple to upgrade.

**Comment by morpheus65535** [comment]
Already included in 1.0.2-beta. Should be in master before the new year.
