### ISSUE TITLE
standard release subs

### ISSUE THREAD

**Issue by distributorofpain** [morpheus65535/bazarr#1649]
**Describe the bug**
generic sub files are not detected.  Many releases have subs that are named 1_english.srt, 2_english.srt, 3_english.srt ( not sure why there is more than one but i see it all the time, perhaps some are just for forced ).  

**To Reproduce**
Go to main list after all movies imported into, find a movie with a known file or files with the #_english.srt naming and hit scan disk.  Nothing comes up. 

**Expected behavior**
existing srt file(s) found

**Screenshots**
Used an example with multiple languages, but really only concerned about english, just thought it was a good example since others using the other language files may want them detected.
![image](https://user-images.githubusercontent.com/18275482/147265100-d2851545-c9fa-40eb-aca2-1a4a7191f219.png)

**Software (please complete the following information):**
 - Bazarr: v1.0.1
 - Radarr version 4.0.0.5653
 - Sonarr version 3.0.6.1342
 - OS: Windows 10 Pro

**Additional context**
 I can hit the import button and upload the numbered srt files and they import without a problem.  Importing that many files will be painful when plex already detects and offers them up for use.  Might be able to write a script to rename them, but the ones that have multiple #_english.srt files would be odd to handle and my guess wouldnt end up getting detected ( perhaps not a big deal though ).

**Comment by morpheus65535** [comment]
This isn't a bug, it's per design. Your file naming doesn't match subtitles naming convention. Even Plex wiki doesn't mention it: https://support.plex.tv/articles/200471133-adding-local-subtitles-to-your-media/

we're not going to add support for any possible non-standard subtitles naming.
