### ISSUE TITLE
[Feature Request] Decouple Sonarr/Radarr watched status

### ISSUE THREAD

**Issue by hotio** [morpheus65535/bazarr#165]
Instead of using the Sonarr/Radarr watched status, decouple this into its own status for subtitles. A unmonitored tvshow in Sonarr might still need subtitles and a monitored tvshow might never get subtitles posted. Let the user decide for which shows/movies subtitles should be searched.

**Comment by morpheus65535** [comment]
You can always set a movie of shows to no required subtitles. Just set it to None.

**Comment by morpheus65535** [comment]
Nope you're right. BTW Bazarr do not know about season, we only render it on the UI.
