### ISSUE TITLE
InvalidFile error in embeddedsubtitles provider on utf-8 decode error

### ISSUE THREAD

**Issue by mvanbaak** [morpheus65535/bazarr#1652]
**Describe the bug**
While running the *AWESOME* new  embeddedsubtitles provider (thanks for this one) on my library, it errored out on some movie files with an InvalidFile error, resulting in the provider to be marked and skipped for 10 minutes.
While this skipping makes sense for providers that contact 3rd party sites (to not flood the logs with the same error etc), I think the embedded provider should not be skipped if it runs into this utf-8 decode error for a single subtitle.
If there are more movies/episodes to process, it will take manual reset of the provider state or waiting for 10 minutes for the other files to be processed, IF the problem item is not handled first.

**Expected behavior**
In my opinion, a logline at level ERROR should be enough. The provider should not be marked in error so it will continue with the rest of the files.

**Software (please complete the following information):**
- Bazarr version: 1.0.2-beta.13
- Radarr version: 3.2.2.5080
- Sonarr version: 3.0.6.1342
- OS: FreeBSD-13.0-RELEASE-p4-amd64-64bit-ELF
- Python version: 3.8.12

**Debug log**
[bazarr.log.decode-error.txt](https://github.com/morpheus65535/bazarr/files/7784027/bazarr.log.decode-error.txt)

**Comment by vitiko98** [comment]
Thanks a lot for the report! This will be no longer an issue in next beta.
