### ISSUE TITLE
Update Movie list from Radarr throws exception

### ISSUE THREAD

**Issue by truenicoco** [morpheus65535/bazarr#1657]
**Describe the bug**
Movies are not updated from radarr anymore, probably because audio format of one movie is weird:

```
Job "update_movies (trigger: date[2022-01-01 19:54:42 CET], next run at: 2022-01-01 19:54:42 CET)" raised an exception

Traceback (most recent call last):
  File "/opt/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/bazarr/bazarr/get_movies.py", line 84, in update_movies
    audio_profiles=audio_profiles))
  File "/opt/bazarr/bazarr/get_movies.py", line 434, in movieParser
    audioAdditionalFeatures)
  File "/opt/bazarr/bazarr/get_movies.py", line 292, in RadarrFormatAudioCodec
    if audioFormat.strip() == "mp3": return "MP3"
AttributeError: \'NoneType\' object has no attribute \'strip\
```

**Software (please complete the following information):**
 - Bazarr: v1.0.2
 - Radarr version: 4.0.0.5724
 - OS: Debian buster

**Additional context**
The background tasks 'syncing movies' is stuck on the first move (1/116) in the bazarr ui. I tried to enable debug logs temporarily to identify which movie is causing this, but I didn't manage to get more info from them. Let me know how to help debug this.

**Comment by morpheus65535** [comment]
Should be fixed in upcoming 1.0.3-beta.2. Please test and confirm.

**Comment by nicolascedilnik** [comment]
Indeed, thanks! I switch to 'dev' updates to try it. Is it safe to switch back to 'master' at some point or should I stay in 'dev' now?

**Comment by morpheus65535** [comment]
There's no problem switching back but you should wait for 1.0.3 final.
