### ISSUE TITLE
JSON notification provider not working

### ISSUE THREAD

**Issue by anonyme123** [morpheus65535/bazarr#1659]
**Describe the bug**
JSON notification provider is not working (not sending the JSON to the specified URL)

**To Reproduce**
1. Go to 'Settings > Notifications'
2. Click on the '+' sign
3. Select 'JSON' in the list of notification providers
4. Test sending a notification by pressing the 'Test' button

**Expected behavior**
To receive the JSON at the specified URL

**Screenshots**
<img width="707" alt="Screen Shot 2022-01-02 at 15 42 56" src="https://user-images.githubusercontent.com/19681420/147879453-ad5b4b31-6c0c-4d58-839d-43d4078bec26.png">

**Software (please complete the following information):**
 - Bazarr: 1.0.2
 - Radarr version 3.2.2.5080
 - Sonarr version 3.0.6.1342
 - OS: Linux-3.10.0-1160.11.1.el7.x86_64-x86_64

**Additional context**

**Comment by halali** [comment]
You probably didnt read wiki how to use it.
Work for me 
https://github.com/caronc/apprise/wiki/Notify_Custom_JSON

**Comment by anonyme123** [comment]
I did read the wiki, still nothing.

**Comment by halali** [comment]
You use wrong path must start jsons:// not https://

Dňa ne 2. 1. 2022, 17:28 anonyme123 ***@***.***> napísal(a):

**Comment by anonyme123** [comment]
Nice, may I suggest updating the profile value to 'jsons://example.com' instead of the current 'URL'?

**Comment by halali** [comment]
Yes its possible, but its lot of work for nothing... Its generated dynamically... There is wiki with instructions.

Just read it and you will be ok.
