### ISSUE TITLE
Job "update_movies" raised an exception - Sync with Radarr gets stuck after updating Bazarr

### ISSUE THREAD

**Issue by netplexflix** [morpheus65535/bazarr#1667]
I had my Bazarr still on an old version, since it was working fine. Today I read about some new features so I decided to update to the latest version. Since doing so, My sync with Radarr gets stuck every time.
It starts Syncing Movies but gets stuck on one of the first movies (sometimes the first, sometimes a few movies in).
The log gives the following error:

`Job "update_movies" raised an exception`

Stack Traceback:
`Traceback (most recent call last):

  File "p:\\bazarr\\bazarr\\../libs\\apscheduler\\executors\\base.py", line 125, in run_job

    retval = job.func(*job.args, **job.kwargs)

  File "p:\\bazarr\\bazarr\\get_movies.py", line 86, in update_movies

    movies_to_add.append(movieParser(movie, action=\'insert\',

  File "p:\\bazarr\\bazarr\\get_movies.py", line 433, in movieParser

    audioCodec = RadarrFormatAudioCodec(audioFormat, audioCodecID, audioProfile,

  File "p:\\bazarr\\bazarr\\get_movies.py", line 292, in RadarrFormatAudioCodec

    if audioFormat.strip() == "mp3": return "MP3"

AttributeError: \'NoneType\' object has no attribute \'strip\`

I've read several previous issues and tried every suggestion, such as deleting my Bazarr.db, reconfiguring language settings and scanning disk. It keeps happening.
Sonarr is working fine.

Bazarr Version 1.0.2
Sonarr Version 2.0.0.5344
Radarr Version 4.0.0.5745
Operating System Windows-10-10.0.19044-SP0
Python Version 3.10.0

Bazarr.db, as well as my original .db which I backed up, attached.
Thanks in advance for any feedback!
[Bazarr.db.zip](https://github.com/morpheus65535/bazarr/files/7809874/Bazarr.db.zip)
![screenshot](https://user-images.githubusercontent.com/97123790/148113805-28441980-936f-47a3-a763-89b8663871f3.jpg)

**Comment by morpheus65535** [comment]
Fixed in latest beta in dev branch.

**Comment by netplexflix** [comment]
hi! thanks for replying so fast!
I tried extracting the latest beta, but when I did, i couldn't reach Bazarr anymore. so I reinstalled 1.02.
How should I correctly install the beta?

**Comment by morpheus65535** [comment]
Simply by switching to development branch in Settings-->General and running the Bazarr upgrade task in System-->Tasks.

**Comment by netplexflix** [comment]
That simple! (I feel stupid :) )
Sorry for taking your time. I've made a modest donation as a thank you .

**Comment by morpheus65535** [comment]
Appreciated!
