### ISSUE TITLE
Law and order SVU no result

### ISSUE THREAD

**Issue by protectxme** [morpheus65535/bazarr#1669]
All épisodes of law and order SVU show no result 
![9A5F24A8-FC7B-4D89-8B41-267B97FCE67A](https://user-images.githubusercontent.com/81614901/148273814-0e16f6d9-6c5f-4893-af18-fe3345e89449.jpeg)
![B817551D-8F47-4E59-B433-914B14EAB9F0](https://user-images.githubusercontent.com/81614901/148273816-9154aa44-f9dd-4e81-a310-bf4c6dadcfb3.jpeg)

**Comment by morpheus65535** [comment]
Maybe you could fill out the complete issue form? I don't even know what provider it is...

**Comment by protectxme** [comment]
Sorry, it’s addic7ed

**Comment by morpheus65535** [comment]
Series title name doesn't match. Of course it won't show as matching subtitles. It would require to do custom name matching with this provider and it's not something we have in place right now.

**Comment by protectxme** [comment]
thank you for the answer. So nothing to do for the moment?

**Comment by morpheus65535** [comment]
Should be fixed in upcoming v1.0.3-beta.7. Please test and confirm.

**Comment by protectxme** [comment]
It’s ok ! Thanks
