### ISSUE TITLE
Can't login to "Ktuvit" provider

### ISSUE THREAD

**Issue by ItamarBM** [morpheus65535/bazarr#1670]
Every time I login to this provider I get "AuthenticationError" in the Providers section in the System tab. I tried using 3 different accounts and none of them work (they do work on browser). (I used the method to get the hashed password that is linked in the readme of bazarr, not the normal password)

**Comment by ItamarBM** [comment]
this is the log 
![image](https://user-images.githubusercontent.com/73859016/148419527-bf425a8b-5d77-4e7a-a968-837da30a798e.png)

**Comment by morpheus65535** [comment]
I don't read Hebrew. You must be doing something wrong while creating the hashed password because it works for many users. 10% of the Hebrew subtitles have been downloaded from this providers since 1 week.

**Comment by ItamarBM** [comment]
This means "login failed". I get the hashed password in the same format that appears in the github of the method, so I'm not sure if it has to do with the method

**Comment by morpheus65535** [comment]
@GuyKh is there something new with this provider?

**Comment by ItamarBM** [comment]
I forgot to paste my password in the first line of the command to get the hashed password. Thanks for helping and sorry for bothering
