### ISSUE TITLE
Skipping provider 'hosszupuska': not a valid video| for movies

### ISSUE THREAD

**Issue by xenophobentx** [morpheus65535/bazarr#1674]
Hello using,

Bazarr v1.0.2 and noticed that hosszupuska provider is not used for movies only for series.

Actually the site is the main source for Hungarian subtitles for fresh releases.

Debug log:

11/01/2022 10:34:18|INFO    |subliminal_patch.core           |Listing subtitles for <Movie ['Black Friday', 2021]>|
11/01/2022 10:34:18|INFO    |subliminal_patch.core           |Listing subtitles with provider 'opensubtitles' and languages {<Language [hu]>, <Language [hu]>}|
11/01/2022 10:34:18|INFO    |subliminal_patch.core           |Initializing provider opensubtitles|
11/01/2022 10:34:18|DEBUG   |subliminal_patch.providers.opensubtitles|Using timeout: 15|
11/01/2022 10:34:18|DEBUG   |subliminal_patch.providers.opensubtitles|Using previous login token: 'removed'|
11/01/2022 10:34:18|INFO    |subliminal_patch.providers.opensubtitles|Searching subtitles [{'moviehash': '321931af24d43811', 'moviebytesize': '3653989515', 'sublanguageid': 'hun,hun'}, {'imdbid': '11649338', 'sublanguageid': 'hun,hun'}]|
11/01/2022 10:34:18|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): api.opensubtitles.org:80|
11/01/2022 10:34:18|DEBUG   |urllib3.connectionpool          |http://api.opensubtitles.org:80 "POST /xml-rpc HTTP/1.1" 200 1067|
11/01/2022 10:34:18|DEBUG   |subliminal_patch.providers.opensubtitles|Found subtitle <OpenSubtitlesSubtitle 'http://www.opensubtitles.org/en/subtitles/8936367/sid-xjUilitnysAB4LZ5pu6oPvjn5Cf/black-friday-hu' [hu:None]> by imdbid|

**11/01/2022 10:34:18|INFO    |subliminal_patch.core           |Skipping provider 'hosszupuska': not a valid video|**

11/01/2022 10:34:18|INFO    |subliminal_patch.core           |Listing subtitles with provider 'supersubtitles' and languages {<Language [hu]>}|
11/01/2022 10:34:18|INFO    |subliminal_patch.core           |Initializing provider supersubtitles|
11/01/2022 10:34:18|INFO    |subliminal_patch.providers.supersubtitles|URL for subtitles https://www.feliratok.info/index.php?search=Black+Friday&soriSorszam=&nyelv=&tab=film|
11/01/2022 10:34:18|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): www.feliratok.info:443|
11/01/2022 10:34:21|DEBUG   |urllib3.connectionpool          |https://www.feliratok.info:443 "GET /index.php?search=Black+Friday&soriSorszam=&nyelv=&tab=film HTTP/1.1" 200 None|

**Comment by morpheus65535** [comment]
This provider wasn't storing movies subtitles when this part of code was done. If it change over time, it's fine but this isn't an issue. I f you want it to support movies, you can either create a feature request or submit a pull request with the required changes.
