### ISSUE TITLE
Sonarr/episodeFile Endpoint Issue

### ISSUE THREAD

**Issue by Davo1624** [morpheus65535/bazarr#1676]
Issue:
Bazarr is reporting a 404 error when trying to obtain the episodeFile endpoint from Sonarr

To reproduce:
Import new episodes into Sonarr

**Software (please complete the following information):**
 - Bazarr: 1.0.3-beta.8
 - Sonarr: 4.0.0.2087

**Additional context**
Relevant log error:

```python3
ERROR   |root                            |BAZARR Error trying to get episodeFiles from Sonarr. Http error.|
```

```python3
Traceback (most recent call last):
  File "/app/bin/bazarr/get_episodes.py", line 402, in get_episodesFiles_from_sonarr_api
    r.raise_for_status()
  File "/app/bin/bazarr/../libs/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://sonarr:8989/api/v3/episodeFile/9654?apikey=(removed)'
```

`episodeFile` id will vary based on the respective file in Sonarr

**Comment by morpheus65535** [comment]
This one should be fixed in upcoming beta.

**Comment by morpheus65535** [comment]
No news, good news!
