### ISSUE TITLE
bug in subscene API

### ISSUE THREAD

**Issue by Nnawaff01** [morpheus65535/bazarr#1678]
**Describe the bug**
bug in subscene API occurs when the name of United States content match another country content they add "US" in the URL and the API ignores it

**To Reproduce**
try it on this tv show "The Good Doctor" with any subtitle language
imdb:tt6470478

**Expected behavior**
add 'US' in url of the http post requests bettwen the the title name and the season number

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/61884938/149206904-7144a8aa-79f3-4637-8df5-cd3f7ee72b6e.png)
![Screenshot_3](https://user-images.githubusercontent.com/61884938/149206920-28368a75-fa14-4cbe-bd76-2e67715841b9.png)

   Software
 - Bazarr: 1.0.2
 - Sonarr version 3.0.6.1342
 - OS: Windows 10

**Comment by morpheus65535** [comment]
Should be fixed in upcoming 1.0.3-beta.12. Please test and confirm.

**Comment by Nnawaff01** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/61884938/149790266-896fb536-5eef-41eb-ae88-0ea5456a88da.png)
thank you
