### ISSUE TITLE
AudioFormat: AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by redglory** [morpheus65535/bazarr#1680]
**Describe the bug**
When updating movies from Radarr, when the is no AudioFormat detected, Bazarr throws the error:
`13/01/2022 16:12:13|ERROR   |apscheduler.executors.default   |Job "Update Movie list from Radarr (trigger: interval[1:00:00], next run at: 2022-01-13 17:12:11 GMT)" raised an exception|'Traceback (most recent call last):\n  File "c:\\programdata\\bazarr\\bazarr\\../libs\\apscheduler\\executors\\base.py", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File "c:\\programdata\\bazarr\\bazarr\\get_movies.py", line 81, in update_movies\n    movies_to_update.append(movieParser(movie, action=\'update\',\n  File "c:\\programdata\\bazarr\\bazarr\\get_movies.py", line 433, in movieParser\n    audioCodec = RadarrFormatAudioCodec(audioFormat, audioCodecID, audioProfile,\n  File "c:\\programdata\\bazarr\\bazarr\\get_movies.py", line 292, in RadarrFormatAudioCodec\n    if audioFormat.strip() == "mp3": return "MP3"\nAttributeError: \'NoneType\' object has no attribute \'strip\''|
13/01/2022 16:14:20|INFO    |root                            |Throttling opensubtitles for 10 minutes, until 22/01/13 16:24, because of: ValueError. Exception info: 'Not enough information'|`

And as it can't update movie details, opensubtitles gets throttled for 10min because of a ValueError.

**To Reproduce**
1. Go to 'System->Taks'
2. Click on 'Update Movie list from Radarr'
3. Open Bazarr logfile

**Expected behavior**
No error on Movie update if Bazarr cannot retrive correct AudioFormat.

[if audioFormat.strip() == "mp3": return "MP3"](https://github.com/morpheus65535/bazarr/blob/master/bazarr/get_movies.py#L292) should be checked if audioFormat is not null.

**Screenshots**

**Software (please complete the following information):**
Bazarr Version
1.0.2
Sonarr Version
3.0.6.1432
Radarr Version
4.0.2.5817
Operating System
Windows-10-10.0.19041-SP0
Python Version
3.8.0
Bazarr Directory
c:\programdata\bazarr\bazarr\api
Bazarr Config Directory
C:\ProgramData\Bazarr\data

**Comment by morpheus65535** [comment]
Duplicate from #1667
