### ISSUE TITLE
opensubtitles.org

### ISSUE THREAD

**Issue by AtlAntA118** [morpheus65535/bazarr#1686]
Bazarr cant authenticate my credentials. I have reset the password because of their  leak last year. I think they have implemented an anti captcha now which bazarr isnt using?

**Comment by morpheus65535** [comment]
Bazarr is using their official XML-RPC API that doesn't use captcha. We've seen issues with complex password. Use a simple one to test.

1.3 millions subtitles have been downloaded from opensubtitles.org through Bazarr during the last 7 days. I guess it prove it's working. ;-)

**Comment by jeremysherriff** [comment]
@morpheus65535 might be worth pinning this issue for visibility, or putting a note on the provider like you did with Tusubtitulo

**Comment by davidmartos96** [comment]
I'm also experiencing Authentication issues after resetting the password. The password requires a special character now.

**Comment by morpheus65535** [comment]
> 

You can try to empty the config/cache directory just in case. Otherwise, you have an issue with your credentials.

**Comment by davidmartos96** [comment]
> > 
> 
> You can try to empty the config/cache directory just in case. Otherwise, you have an issue with your credentials.

I solved it, but I had to change the password. I had an asterisk at the end of the password. Could that be interfering with the config file?

**Comment by morpheus65535** [comment]
I've just tested and it's passed properly to and from config file. No idea what could be causing this. I would need to change my password on provider. I'll tyr this later.

**Comment by morpheus65535** [comment]
@davidmartos96 Tested again with an asterick at the end of my password and it works perfectly fine.

**Comment by halali** [comment]
I think he didnt changes paswword after os hack

**Comment by davidmartos96** [comment]
After some more investigation I think it was a caching issue. Probably the app was using the previous invalid auth token.

**Comment by morpheus65535** [comment]
@davidmartos96 you're right, cache get invalidated only on username change. I'll fix this. Thanks for the investigation!
