### ISSUE TITLE
Titlovi provider keeps asking for login credentials

### ISSUE THREAD

**Issue by pentago** [morpheus65535/bazarr#1687]
**Describe the bug**
Even though I have a titlovi.com account and antered it correctly in the provider settings, I constantly kep seeing this in logs:

`2022-01-20 13:07:29,484 - root                             (7f6f1149d8) :  INFO (get_providers:241) - Throttling titlovi for 10 minutes, until 22/01/20 13:17, because of: AuthenticationError. Exception info: 'Login failed'
`

**Software (please complete the following information):**
 - Bazarr: 1.0.2
 - OS: Raspberry Pi OS

**Additional context**
I noticed the same question is asked at titlovi.com forums (in Serbian language) as well, seems it's not just me.

Could someone take a look?
Thanks!

**Comment by morpheus65535** [comment]
Provider seems to be working as expected. 1178 Serbian subtitles downloaded from titlovi yesterday. Mak sure your username and password are all alphanumeric characters ([a-z][A-Z][0-9]). If ti doesn't work with that, you have an issue with your Titlovi account.

**Comment by pentago** [comment]
I just realized I had symbols in my password so I changed it only to letters and numbers but again, I'm getting this error:
`Throttling titlovi for 10 minutes, until 22/01/20 14:50, because of: AuthenticationError. Exception info: 'Login failed'`

Can you let me know where exactly are you getting your login credentials from?

I'm asking because the only place where I see it's possible registering are their forums at this URL below which is kinda strange:
https://forum.titlovi.com/login_user.asp

Perhaps there's some other place to register for this provider to work?

Thanks in advance!

**Comment by morpheus65535** [comment]
You're not using the proper registration form. There's a link on the main Titlovi page that point to: https://forum.titlovi.com/registration_rules.asp

**Comment by pentago** [comment]
No, that's the same forum thing, initially, I was referring to forum subdomain.

Okay, not sure then what can be the issue, perhaps the password length? Mine is 20 chars long, could that be the issue?
Perhaps something else? My username is 4-letter string.

**Comment by morpheus65535** [comment]
Yes I figured out and deleted my answer. I have no idea to be honnest, I don't use this provider and I'm not the one who develop it. I've created and account on the forum and I use it with the provider without any issue. Could be an issue on their API with long password but I can't say.

**Comment by pentago** [comment]
I just tried simple 8-char password, also doesn't work.

**Comment by pentago** [comment]
@pannal @halali any idea on this provider auth issue?

**Comment by pentago** [comment]
@halali I noticed you were one of the [committers to this provider](https://github.com/morpheus65535/bazarr/commits/afd9cd6ddbbdab9e6a6d5d8844fbda1882054c8f/libs/subliminal_patch/providers/titlovi.py), so I thought you could have some idea.

**Comment by pentago** [comment]
I just created a new account and the provider now works. No clue what could've gone wrong with my first account.
