### ISSUE TITLE
[Bug] Sonarr + Radarr. Connection and Timeout Errors.

### ISSUE THREAD

**Issue by Gingey231** [morpheus65535/bazarr#169]
**Describe the bug**
Random connection timeout errors in my logs.

**To Reproduce**
I am seeing my logs fill up with the following errors for both Sonarr and Radarr every couple of minutes:

Connection error
```
Traceback (most recent call last):
 File "/bazarr/get_episodes.py", line 51, in sync_episodes
  r = requests.get(url_sonarr_api_episode, timeout=15, verify=False)
 File "/bazarr/libs/requests/api.py", line 72, in get
  return request(\get\, url, params=params, **kwargs)
 File "/bazarr/libs/requests/api.py", line 58, in request
  return session.request(method=method, url=url, **kwargs)
 File "/bazarr/libs/requests/sessions.py", line 512, in request
  resp = self.send(prep, **send_kwargs)
 File "/bazarr/libs/requests/sessions.py", line 622, in send
  r = adapter.send(request, **kwargs)
 File "/bazarr/libs/requests/adapters.py", line 495, in send
  raise ConnectionError(err, request=request)
ConnectionError: (\Connection aborted.\, error(104, \Connection reset by peer\))
```

Timeout Error:
```
Traceback (most recent call last):
 File "/bazarr/get_movies.py", line 137, in get_profile_list
  profiles_json = requests.get(url_radarr_api_movies, timeout=15, verify=False)
 File "/bazarr/libs/requests/api.py", line 72, in get
  return request(\get\, url, params=params, **kwargs)
 File "/bazarr/libs/requests/api.py", line 58, in request
  return session.request(method=method, url=url, **kwargs)
 File "/bazarr/libs/requests/sessions.py", line 512, in request
  resp = self.send(prep, **send_kwargs)
 File "/bazarr/libs/requests/sessions.py", line 622, in send
  r = adapter.send(request, **kwargs)
 File "/bazarr/libs/requests/adapters.py", line 526, in send
  raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host=\172.16.60.15\, port=7878): Read timed out. (read timeout=15)
```

Possibly during some of the tasks but im not running anything manually.

**Expected behavior**
Cannot tell if it is affecting anything but havent fully checked out everything to see if anything is missing (waaaay too much to check!)

**Software (please complete the following information):**
 - Bazarr: 0.65
 - Radarr version 0.2.0.1120
 - Sonarr version 2.0.0.5228
 - OS: Ubuntu 64-bit (Docker host)

**Additional context**
This is running as a docker container as are sonarr and radarr, all on the same bridge connection.

**Comment by morpheus65535** [comment]
Is this a new behavior?

**Comment by morpheus65535** [comment]
I would try with your docker host IP instead of the container IP.

**Comment by Gingey231** [comment]
This happened when i updated to 0.64 (after the fixes for the auth you found out with me over teamviewer). Was waiting on the next update as i saw there was a lot in there and thought it may fix it, but alas it did not.

The .60.15 is the docker host IP

It seems that i can manually test the connections, and for 10-15 mins i dont get the errors if this helps

**Comment by morpheus65535** [comment]
Ok, remember you now.

For what it worth, I had those kind of error for a time. They stopped after I've recreated Sonarr and Radarr container.

Which version of Docker you're running?

**Comment by Gingey231** [comment]
Hey bud,

Just an update on this:

So far i recreated the container, deleting the old image completing and all associated volumes, and re-pulled the latest image just to be sure.

Got it all set up again how it was before (bridged network) and got the same errors.

Decided to change this to the `host` network, just to force it to use the host IP, and still getting the same.

Recreated the Sonarr and Radarr containers in the same way, however sadly the errors still persist.

Not that urgent as it doesn't seem to be causing any issues? All subtitles are downloading fine, and the bars for the tv shows seem up to date. Strange one!

**Comment by Gingey231** [comment]
Ah awesome, no worries bud, cheers for letting me know :)

Not switching to Debian so i will put up with the errors 😛

**Comment by DennisYildirim** [comment]
Well this error actually still happens in the year of 2022. 

![image](https://user-images.githubusercontent.com/81414162/161425261-bacdf5ed-dac8-4f47-82e5-2610722a224a.png)


[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Bazarr: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1026
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2022-04-03 10:56:41,889 - root                             (7f81f189bb48) :  INFO (server:37) - BAZARR is started and waiting for request on http://0.0.0.0:6767
2022-04-03 11:06:55,675 - root                             (7f81e4dbfb38) :  INFO (signalr_client:163) - BAZARR trying to connect to Radarr SignalR feed...
2022-04-03 11:13:50,377 - root                             (7f81e5ef2b38) :  ERROR (filesystem:97) - BAZARR Error trying to get series from Radarr. Connection Error.
Bazarr starting...
Bazarr exited.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Bazarr: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1026
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2022-04-03 11:15:40,659 - root                             (7f229fda0b38) :  INFO (signalr_client:163) - BAZARR trying to connect to Radarr SignalR feed...
2022-04-03 11:15:40,659 - root                             (7f22ae1cab48) :  INFO (server:37) - BAZARR is started and waiting for request on http://0.0.0.0:6767

**Comment by maplepy** [comment]
@DennisYildirim did you manage to make it work? It's broken for me too but its working fine on my laptop with exactly the same config, same docker-compose etc...

**Comment by morpheus65535** [comment]
> @DennisYildirim did you manage to make it work? It's broken for me too but its working fine on my laptop with exactly the same config, same docker-compose etc...

Please open your own issue. This one is 4 years old. You can start by asking for support on Discord. we may be able to fix it directly if it's a configuration issue.

**Comment by maplepy** [comment]
**Managed to fix it** by deleting all of the containers, their images, their volumes etc.. Basically nuked the thing and reinstalled it from the docker-compose file and it's working fine now

**Comment by maplepy** [comment]
> > @DennisYildirim did you manage to make it work? It's broken for me too but its working fine on my laptop with exactly the same config, same docker-compose etc...
> 
> we may be able to fix it directly if it's a configuration issue.

It wasn't :/ I literally copied the docker-compose file from my laptop and it wasn't working but I explained how I fixed it in the comment just above this one :) Thanks though :+1:
