### ISSUE TITLE
Exclude audio flag in language profile works only for the first language

### ISSUE THREAD

**Issue by pluusla** [morpheus65535/bazarr#1691]
**Describe the bug**
I have a general language profile for bazarr (series) which looks like this:
https://imgur.com/a/72Jk7Dv

With this I download the general subtitles for my series. So bazarr should download english subtitles if they are missing. German subtitles I only want to download manually if I want them. Therefore I set the cutoff at ID 1 english. 

In the subtitles settings I have specified that embedded subtitles should be used, embedded PGS/VobSub/ASS subtitles should be ignored.

Now I have anime as well as conventional series. For these the same language profile is set by Sonarr Sync. But here I would expect that the embedded subtitles provider (flag set at include srt and include ASS) converts the ass subtitles to srt. However, as you can see, the anime series with this profile does not set any subtles to wanted at all:

https://imgur.com/a/ECiq0ib

if i change the language profile and set german to first (with flag exclude audio, custoff any), the search button for german and english is displayed

**To Reproduce**
1. set a new language profile for two languages for example german and english
2. set english first, no flags
3. set german second, flag on exclude audio
4. set cutoff to id1 english
4. set profile to a anime series. Audio is english

**Expected behavior**
no matter at which position or which language the exclude audio is set, the flag should apply

**Screenshots**
not working profile:
https://i.imgur.com/pj608IW.jpeg

result (expected: search button for eng):
https://i.imgur.com/Qbu2nTh.jpeg

change german to the first place in profile, search button appears on series:
https://i.imgur.com/7sR4zkT.jpeg

**Software (please complete the following information):**
Bazarr version
1.0.2
Sonarr Version
3.0.6.1342
Radarr Version
3.2.2.5080
OS: 
Linux

**Additional context**
see discord discussion under support

**Comment by morpheus65535** [comment]
Should be fixed in upcoming 1.0.3-beta.18. Can you test and confirm? Make sure to scan disk or reassign languages profile to force a missing subtitles recalculation.

**Comment by pluusla** [comment]
Awesome! No, unfortunately I cannot test it. Bazarr is installed on a seedbox provider and I can't change the docker-branch/tag there... so I have to rely on the stable version, sorry.
But I am convinced that your fix works :)

**Comment by siankatabg** [comment]
> Should be fixed in upcoming 1.0.3-beta.18. Can you test and confirm? Make sure to scan disk or reassign languages profile to force a missing subtitles recalculation.

I've a different issue now with this change. 

As the author of the issue, I've a profile set for 2 languages, first is Bulgarian and the second one is English. Bulgarian is set to exclude audio and as a cut-off, so English subs won't be downloaded if the audio is Bulgarian or there are Bulgarian subtitles available (at least that was my logic and it was working like that before this change). After this change was merged my profile doesn't care anymore if the audio is Bulgarian and downloaded English subtitles to all of them...

Is there a way I could achieve the old behaviour or something?

**Comment by morpheus65535** [comment]
@siankatabg should be fixed in tonight beta. Thanks for reporting!

**Comment by morpheus65535** [comment]
No news, good news!
