### ISSUE TITLE
Updating seems to be breaking bazarr

### ISSUE THREAD

**Issue by klepp0906** [morpheus65535/bazarr#1693]
**Describe the bug**
I awoke today to find bazarr unable to connect.   after a reinstall i was able to connect but only until I hit settings > tasks > update and at that point it would disconnect from the backend, never to work again.  (at least with it set to development branch)  I surmise thats why it stopped working this AM.  it attempted to update itself on the schedule and it breaks whether manually or automatic.

 after trying the install in several locations (programdata, program files, root of c) the result was the same.   I also attempted in a clean unmolested windows 10 virtual machine.  

**To Reproduce**
1. Go to settings > general > and change to development branch.
2. Go to tasks > click on update bazarr
3. it will hang on connecting and eventually disconnect from the backend at which point you can no longer reconnect. 

**Expected behavior**
triggering an update to update and carry on :)

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: whichever version is downloaded by the most recent installer off the main website (newest master i assume) however on my main pc i was using development and only noticed it no longer connecting as of this AM and thus discovered the issue.  So i assume it had to have happened within the last few dev builds at most. 
 - Radarr version 4.0.3.5879
 - Sonarr version 3.0.6.1451
 - OS: Windows 10

**Additional context**

**Comment by klepp0906** [comment]
messing around uninstalling/reinstalling it some more as i click through the menu's waiting for it to "disconnect from backend" i also happened to get this error just now.  unsure if its related, or a consequence of it "disconnecting from backend" while i click around :P

Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=Error%3A%20You%20have%20disconnected%20to%20Bazarr%20backend for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by morpheus65535** [comment]
This should be fixed in upcoming beta.17. Can you test and confirm?

**Comment by klepp0906** [comment]
you bet, as soon as its up ill install it.  been watching :P

**Comment by klepp0906** [comment]
unfortunately without an installer, RIP.  just a dumb windows user here :)

tried using the currently pushed windows installer and stopping the service and overwriting the files with the beta 17 zip but it didnt connect at all that way.

**Comment by morpheus65535** [comment]
You can download the latest bazarr.zip asset and put it in `%programdata%\Bazarr\update`:

https://github.com/morpheus65535/bazarr/releases/download/v1.0.3-beta.17/bazarr.zip

It's working for me, I can switch from master to dev without any issue.

**Comment by klepp0906** [comment]
do you have to click update after placing it in the update subfolder or just wait for it to update?

**Comment by morpheus65535** [comment]
Sorry you need to restart the service.

**Comment by klepp0906** [comment]
okay, im not having a whole lot of luck here.  i skipped trying to import my db/config file until i get this back up and running properly.

so started with clean install to C drive.  moved bazarr.zip into the update subfolder.   changed branch to development.  restarted the service.

bazarr.zip is still in the update folder and the status page still says im on 1.0.2

**Comment by morpheus65535** [comment]
If you can load the UI, just run the update Bazarr task. The zip file is a last resort solution.

**Comment by klepp0906** [comment]
okay, now we're talkin.  it appears to be working if i go barebones, update via the GUI, then move my old config/db etc back.  now i can freely swap between master & development.   

gonna move it back to programdata now but i assume all should be well.

**Comment by morpheus65535** [comment]
Yes keep me informed please after the next update if your config get wiped again. Thanks for reporting!

**Comment by klepp0906** [comment]
two things ive noticed.

1) after the change to development channel and updating, if you attempt to uninstall bazarr via add/remove programs - the entry is broken and you get the prompt "would you like to remove bazarr from this list, it appears this was already uninstalled" or some such.

this requires using command prompt sc delete bazarr to remove the service then deleting the files manually.

2) bazarr installed to programdata will not update properly.  it results in being unable to connect after hititng update.  this may have to do with the folder not having the "everyone" group added to permissions, similar to the other "arr" softwares.

**Comment by klepp0906** [comment]
nope, just added the permission manually and same result, so nothing to do with that.

**Comment by morpheus65535** [comment]
> 1. after the change to development channel and updating, if you attempt to uninstall bazarr via add/remove programs - the entry is broken and you get the prompt "would you like to remove bazarr from this list, it appears this was already uninstalled" or some such.

This one should be fixed in upcoming beta. Of course switching to master will still cause this issue until you're on 1.0.3 final.

**Comment by morpheus65535** [comment]
> 2. bazarr installed to programdata will not update properly.  it results in being unable to connect after hititng update.  this may have to do with the folder not having the "everyone" group added to permissions, similar to the other "arr" softwares?

This wont be completely fixed until 1.0.3 final is out.
