### ISSUE TITLE
Only one subtitle downloaded although many wanted and available

### ISSUE THREAD

**Issue by spitz66** [morpheus65535/bazarr#1694]
**Describe the bug**
Seems to only happen for Series.
When "Search for wanted Series Subtitles" is run either from schedule or triggered manually only one subtitle is downloaded.
Next time one  more is downloaded and so on...

Each time an error message in log: 

> Traceback (most recent call last):
> 
>   File "c:\\bazarr\\bazarr\\../libs\\apscheduler\\executors\\base.py", line 125, in run_job
>     retval = job.func(*job.args, **job.kwargs)
>   File "c:\\bazarr\\bazarr\\get_subtitle.py", line 1198, in wanted_search_missing_subtitles_series
>     wanted_download_subtitles(episode[\'sonarrEpisodeId\'])
>   File "c:\\bazarr\\bazarr\\get_subtitle.py", line 1081, in wanted_download_subtitles
>     send_notifications(episode[\'sonarrSeriesId\'], episode[\'sonarrEpisodeId\'], message)
>   File "c:\\bazarr\\bazarr\
> otifier.py", line 95, in send_notifications
>     apobj.notify(
>   File "c:\\bazarr\\bazarr\\../libs\\apprise\\Apprise.py", line 369, in notify
>     return py3compat.asyncio.tosync(
>   File "c:\\bazarr\\bazarr\\../libs\\apprise\\py3compat\\asyncio.py", line 66, in tosync
>     return asyncio.run(cor, debug=debug)
>   File "C:\\Bazarr\\WinPython\\python-3.8.0\\lib\\asyncio\\runners.py", line 50, in run
>     loop.close()
>   File "C:\\Bazarr\\WinPython\\python-3.8.0\\lib\\asyncio\\proactor_events.py", line 679, in close
>     signal.set_wakeup_fd(-1)
> ValueError: set_wakeup_fd only works in main thread 
> 

**To Reproduce**

System --> Tasks --> Search for wanted Series Subtitles

**Expected behavior**
All available subtitles should be downloaded from wanted que

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 1.0.2
 - Radarr version 3.2.2.5080
 - Sonarr version 3.0.6.1342
 - OS: Windows 10

**Additional context**

**Comment by morpheus65535** [comment]
This is an issue with Python 3.8.0. Use the latest Bazarr installer tht include Python 3.10 instead.
