### ISSUE TITLE
CAN sync with Radarr but error in logfile: raised an exception

### ISSUE THREAD

**Issue by BodingClockchian** [morpheus65535/bazarr#170]
**Describe the bug**
Same bug description as [https://github.com/morpheus65535/bazarr/issues/162](url) but with a different log file error

**The movies are still imported/synced regarding this error in the log?**

**To Reproduce**
Task buttonSync with Radarr

**Expected behavior**
Get movies from Bazarr

**Log**
`02/10/2018 20:05:15|ERROR|Job "Update movies list from Radarr (trigger: interval[0:05:00], next run at: 2018-10-02 20:10:15 CEST)" raised an exception|'Traceback (most recent call last):\n  File "libs/apscheduler\\executors\\base.py", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File "C:\\bazarr\\get_movies.py", line 109, in update_movies\n    c.executemany(\'DELETE FROM table_movies WHERE tmdbId = ?\', removed_movies)\nProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 6 supplied.'|`

**Software (please complete the following information):**
 - Bazarr Ver. 0.6.5
 - Radarr Ver. 0.2.0.1120
 - OS: Windows 7

**Comment by morpheus65535** [comment]
Is going to be fixed in 0.6.6 in a week max. Maybe a maintenance release before. If you running from source, you can switch to dev branch now, force update and restart.

**Comment by BodingClockchian** [comment]
> Is going to be fixed in 0.6.6 in a week max. Maybe a maintenance release before. If you running from source, you can switch to dev branch now, force update and restart.

Nice, that quick response. Im already on dev branch

**Comment by morpheus65535** [comment]
Please, confirm if it's fixed.

**Comment by BodingClockchian** [comment]
> Please, confirm if it's fixed.

Confirm, its fixed.
Thank you
