### ISSUE TITLE
supersubtitles provider throws a JSON Decode error when trying to search for a subtitle

### ISSUE THREAD

**Issue by shifoc** [morpheus65535/bazarr#1700]
**Describe the bug**
supersubtitles provider throws a JSON Decode error when trying to search for a subtitle
**To Reproduce**

**Software (please complete the following information):**
 - Bazarr: v1.0.3-beta.21
 - OS: Windows 10

**Additional context**
Throttling supersubtitles for 10 minutes, until 22/01/30 02:00, because of: JSONDecodeError. Exception info: 'Expecting value'

**Comment by morpheus65535** [comment]
This means that the provider returned malformed JSON. Without a proper debug log reproducing the issue, there's nothing I can do.

**Comment by shifoc** [comment]
[bazarr.log](https://github.com/morpheus65535/bazarr/files/7966150/bazarr.log)

**Comment by shifoc** [comment]
I sent the logs on discord

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Nothing I can do ther than preventing the exception from getting the provider throttled.

**Comment by shifoc** [comment]
The provider is not getting throttled anymore, thanks.
