### ISSUE TITLE
some shows that don't have episodes are purple

### ISSUE THREAD

**Issue by shifoc** [morpheus65535/bazarr#1701]
**Describe the bug**
some shows that don't have episodes are purple (usually after the first page)
**Screenshots**
![image](https://user-images.githubusercontent.com/32818143/151681521-32e59934-9869-429f-9bf0-ea2c093d7b47.png)

**Software (please complete the following information):**
 - Bazarr: v1.0.3-beta.21
 - Sonarr version 3.0.6.1342
 - OS: Windows 10

**Comment by morpheus65535** [comment]
@LASER-Yi can you take a look? I'm able to reproduce. `episodeFileCount` and `episodeMissingCount` are both `0`.

**Comment by LASER-Yi** [comment]
> @LASER-Yi can you take a look? I'm able to reproduce. `episodeFileCount` and `episodeMissingCount` are both `0`.

No problem

**Comment by LASER-Yi** [comment]
Should be fixed in the upcoming version

**Comment by shifoc** [comment]
I confirm that the issue is fixed in the latest beta. Thanks
