### ISSUE TITLE
Other languages appear in the statistics section

### ISSUE THREAD

**Issue by shifoc** [morpheus65535/bazarr#1703]
**Describe the bug**
My language profiles are only English and French but other languages appear in the statistics section

**Screenshots**
![image](https://user-images.githubusercontent.com/32818143/151681666-dadd7627-a389-47db-8ea8-71aa03b2c645.png)

**Software (please complete the following information):**
 - Bazarr: v1.0.3-beta.21
 - OS: Windows 10

**Comment by morpheus65535** [comment]
This dropdown will show every language found in history. That's the expected behavior.

**Comment by shifoc** [comment]
![image](https://user-images.githubusercontent.com/32818143/151704875-cf32751d-6464-48a2-b2ae-edd219f8bb6c.png)
I have never downloaded a subtitle in these languages

**Comment by morpheus65535** [comment]
Sorry my bad, this dropdown will show all the enabled languages in Settings-->Languages-->Languages Filter.

**Comment by shifoc** [comment]
> Sorry my bad, this dropdown will show all the enabled languages in Settings-->Languages-->Languages Filter.

![image](https://user-images.githubusercontent.com/32818143/151707509-552eee2e-3ea2-45a5-9dc9-32315b15527f.png)

**Comment by morpheus65535** [comment]
No idea and cannot reproduce.
