### ISSUE TITLE
Bazarr becomes unresponsive after a while (Windows Server 2016 nssm service)

### ISSUE THREAD

**Issue by jamesmacwhite** [morpheus65535/bazarr#1705]
**Describe the bug**

Bazarr becomes unresponsive after some time of being started. The Python process is still running looking at task manager and TCP port 6767 is still open as I can telnet to it, but the UI will not load along with requests at the API (timeout). It seems after a few hours the running process goes into zombie state or is possibly crashing.

I have Bazarr running through nssm, the application is installed at `C:\Bazarr`, it is running under the Local System user.

**Software (please complete the following information):**
 - Bazarr: v1.0.2
 - Radarr version N/A
 - Sonarr version N/A
 - OS: Windows Server 2016

**Additional context**

Bazarr is running under Python 3.10 it was previously 3.8 up until recently but I can see the Windows installer now bundles WinPython 3.10 with it, are there any major issues between 3.8 and 3.10 that could be related, it's the only thing I can think of that's changed lately.

I checked the logs and didn't find anything obvious, I have enabled debug logging and will provide any useful logs if it happens again. If it's consistent it will happen maybe in a few hours after the service has been started.

Failing that I will run it via Command Prompt so I can see the console output in case that yields anything that the logs don't.

**Comment by morpheus65535** [comment]
Nothing have been reported yet. Waiting on your debug log or terminal output.

**Comment by jamesmacwhite** [comment]
Will do, my monitoring has shown that Bazarr has gone down again after a few hours, but I cannot retrieve the debug logs currently, but will post them as soon as can have a look.

**Comment by jamesmacwhite** [comment]
Back home and able to access the logs. Weirdly, there is nothing obvious in the logs and it's a little strange.

My monitoring pinged me to say Bazarr had gone down at 10:39 AM this morning (the monitoring interval is every minute). This is checked using the system status API endpoint, this timed out causing the monitor failure. The logs indicate Bazarr stopped writing logs at 10:34.

The logs do seem to stop writing during the main period where Bazarr appears to be down, although it still is running because there are log entries for 12 PM and 2 PM. Although the API system health endpoint isn't responding still, given my monitor is saying down still through the day.

Then just as I got home, it seemed Bazarr recovered itself as the API responded again and I hadn't touch it.

Checking the system uptime indicates Bazarr had not exited and crashed and the process remained up and the uptime confirms this as it's the time since the service was manually restarted by me, so it's remained "up" just not responsive. 

Wondering if there's a network issue somewhere here.

**Comment by morpheus65535** [comment]
That's strange of course. Could it be that something is heating up all the webserver available threads that are limited to 100? I'm just driving blnd here... not sure what could be the issue.

**Comment by jamesmacwhite** [comment]
Certainly possible. I can rule out firewall as when I've had this happen, I've confirmed it's certainly related to the webserver itself as localhost:6767 doesn't load (removing any network layers).

I am querying the Bazarr API every 60 seconds on the system health endpoint, is it possible that each API query is keeping the connection alive and eventually exhausting the threads. It does seem to happen after a few hours each time from the Bazarr service via nssm being cycled.

**Comment by morpheus65535** [comment]
It depends how you watcher operate. Does it keep the connection opened?

I've just tried calling `/api/system/status?apikey=###` in loop 500 times and didn't faced any issue.

**Comment by jamesmacwhite** [comment]
I'm not setting any specific keepalive settings, the request is coming from Uptime Kuma, I shouldn't think it will be doing anything related to keepalive, but I haven't inspected the source code to confirm what the HTTP(s) test is specifically doing.

I'll have to see if it happens again. It is the first time I've left it after seeing it do this and it's recovered itself, it's been about 8 hours. The logs seem to suggest that Bazarr itself hasn't crashed though, otherwise it wouldn't be able to write to the logs between the time when the monitor stated the API request was failing and now.

With debugging on the logs were very quiet for this period though, but the fact it logged "something" means the process was still alive to a degree.

Shouldn't be memory as the server has 24 GB available, possible the CPU could of been maxed but I doubt it.

**Comment by morpheus65535** [comment]
You're right, if the logging still happen, the back is working properly. If you can find a pattern, it could help.

**Comment by jamesmacwhite** [comment]
Will do, I appreciate there isn't much here to go on, I'll report back if I can find anything of interest.

**Comment by jamesmacwhite** [comment]
Going to close this, as this is probably localised to the environment Bazarr is running on. Will re-open if I can reproduce.
