### ISSUE TITLE
Migrating from macOS to Ubuntu

### ISSUE THREAD

**Issue by SteffanCline** [morpheus65535/bazarr#1706]
Have a question and need some guidance on migrating from macOS to Ubuntu.

I want to migrate my settings from macOS Bazarr to my new Ubuntu install. Is it the contents of ./data which contains cache, config, db, log and update or something else?

**Comment by morpheus65535** [comment]
You can use `--config` argument to bazarr.py to specify the config directory location. By default it use the `data` subdirectory. This config directory is all you need to backup/restore.
