### ISSUE TITLE
Imported movies from Radarr not added to wanted list

### ISSUE THREAD

**Issue by BodingClockchian** [morpheus65535/bazarr#171]
**Describe the bug**
Synced movies from Radarr are not added to the wanted list.
The new imported movies show Hearing-impaired 0 instead of False
In default movie settings the Hearing-impaired option is disabled.

**To Reproduce**
Import new movie from Radarr

**Expected behavior**
Added movies to the wanted list

**Screenshots**
![bazarr bug1](https://user-images.githubusercontent.com/28387829/46368529-bf284100-c680-11e8-8596-31e90b86742b.png)

**Software (please complete the following information):**
- Bazarr Ver. 0.6.4
- Radarr version 0.2.0.1120
- OS: Windows 7

*edit. A workaround is to manual select the movies and set Hearing-impaired to false

**Comment by halali** [comment]
have you this
`movie_default_hi = False`
in your config file ?

**Comment by BodingClockchian** [comment]
> have you this
> `movie_default_hi = False`
> in your config file ?

Yea I do

**Comment by morpheus65535** [comment]
They are going to be added to wanted list once the fix for #170 is applied.

**Comment by halali** [comment]
same as #170 fix in next release or in development branch

**Comment by BodingClockchian** [comment]
I still got this issue with the lastest version
