### ISSUE TITLE
LegendasTV "AttributeError"

### ISSUE THREAD

**Issue by n0pe0n** [morpheus65535/bazarr#1711]
**Describe the bug**
when looking for automatic subtitles, error appears in the provider LegendasTV

**To Reproduce**
1. Go to ''Tasks"
2. Click on 'Search for wanted Movies&Series Subtitles'
4. See error `05/02/2022 19:59:56|INFO    |root                            |Using legendastv again after 10 minutes, (disabled because: AttributeError)|
05/02/2022 20:00:10|INFO    |root                            |Throttling legendastv for 10 minutes, until 22/02/05 20:10, because of: AttributeError. Exception info: "module 'rarfile' has no attribute 'custom_check'"`

**Expected behavior**
to find movies and series on the provider

**Software (please complete the following information):**
 - Bazarr: [1.0.3-beta.25]
 - Radarr version [4.0.4.5922]
 - Sonarr version [3.0.6.1342]
 - OS: Linux-4.15.0-167

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Can you test it and confirm please?

**Comment by n0pe0n** [comment]
> Should be fixed in upcoming beta. Can you test it and confirm please?

solved myfriend for his effort and dedication! 
Hug
