### ISSUE TITLE
Bazarr hangs on wanted subtitle search with ValueError: set_wakeup_fd only works in main thread

### ISSUE THREAD

**Issue by xAyx** [morpheus65535/bazarr#1719]
**Describe the bug**
Bazarr hangs on wanted subtitle search (manual/automatic).
The job starts and the first subtitle are downloaded successfully, but then Bazarr hangs and not moving forward to the next wanted subtitle.
When checking 'Background Tasks' under the GUI, you can see that the task is running but it's stuck on the first successful downloaded subtitle.

Manual search is working for a specific episode/movie.
Manual/Automatic search is not working when using a 'Wanted' bulk search.

**To Reproduce**
1. Go to 'Wanted'
2. Click on 'Search All'
3. See error

**Expected behavior**
After the first downloaded subtitle, keep going for the next one.

**Screenshots**
![image](https://user-images.githubusercontent.com/16591809/153735775-62447565-7dd6-4370-a3de-a34cbfa35634.png)
Keep in mind, when the screenshot was taken the job is running for 32min.

**Software (please complete the following information):**
 - Bazarr Version 1.0.2
 - Sonarr Version 3.0.6.1342
 - Radarr Version 4.0.4.5922
 - Operating System Windows-10-10.0.19041-SP0
 - Python Version 3.8.0

**Additional context**
[bazarr.log](https://github.com/morpheus65535/bazarr/files/8054845/bazarr.log)

**Comment by morpheus65535** [comment]
`ValueError: set_wakeup_fd only works in main thread`

It's a bug in early Python 3.8.x that have been fixed since then. You can note the user of your Bazarr service, uninstall Bazarr and reinstall using the latest installer that use 3.10. Unless you've installed Bazarr itsefl in `%programdata%\Bazarr`, you wont loose your settings.

**Comment by xAyx** [comment]
[morpheus65535](https://github.com/morpheus65535) As you said, reinstalling Bazarr with the latest installer solved the problem.
Python is now version 3.10.0 and search for wanted subtitle does not hang.

morpheus65535 Thank you for your help.
