### ISSUE TITLE
Function to sync monitored movies or delete missing movies

### ISSUE THREAD

**Issue by BodingClockchian** [morpheus65535/bazarr#172]
**Is your feature request related to a problem? Please describe.**
Once the download is complete and subtitles are added I move the files to a different location.
In Radarr the movies become unmonitored which is fine because you are able to filter on that.
Bazarr does not delete the movies if the files aren't there anymore.

**Describe the solution you'd like**
Option to delete movies from the movielist OR a sync with only the monitored movies from Radarr
Perhaps a filter option to only see the 'active' movies.

**Comment by morpheus65535** [comment]
Bazarr only keep track of movies that Radarr report to have a file on disk. Be sure that Radarr is updated correctly when file is deleted and Bazarr will remove it from his list.

**Comment by BodingClockchian** [comment]
> Bazarr only keep track of movies that Radarr report to have a file on disk. Be sure that Radarr is updated correctly when file is deleted and Bazarr will remove it from his list.

You are right, I thought Radarr updated more frequently.
