### ISSUE TITLE
Bazarr not converting embed ASS

### ISSUE THREAD

**Issue by king8084** [morpheus65535/bazarr#1720]
New animes added have ass sub which bazarr recognize as embed sub. But how do i make it convert it to srt? The checkbox is enabled for embedded source to convert but its not working automatically

**Comment by vitiko98** [comment]
Enable debug logging and post the log file.

**Comment by king8084** [comment]
Well i didnt add an anime after enabling debug. But heres a log what the error without debug

[bazarr.log](https://github.com/morpheus65535/bazarr/files/8061140/bazarr.log)

**Comment by vitiko98** [comment]
You don't have the Embedded Subtitles provider enabled. Also, if you want to use this provider, you need to disable "Use Embedded Subtitles" on Settings/Subtitles.

I also suggest you to disable bsplayer provider. This provider is hot garbage; it's just slowing down your setup.

**Comment by king8084** [comment]
Thank you

but it is added in providers. Is there anything else needed to enable it?

**Comment by vitiko98** [comment]
> Thank you
> 
> but it is added in providers. Is there anything else needed to enable it?

Please join our [Discord](https://discord.gg/MH2e2eb) and ask for help on `#support`

**Comment by king8084** [comment]
Ok now it works. But now even shows with srt embedded gets (external srt) since i disabled use embedded. If i disable srt in provider and enabled use embedded again will it work only for ass?
