### ISSUE TITLE
NFKC normalization blocks valid characters. Better switch to NFC normalization instead.

### ISSUE THREAD

**Issue by janusn** [morpheus65535/bazarr#1724]
**Describe the bug**
NFKC normalization marks valid characters as invalid. Better switch to NFC normalization instead.

**To Reproduce**
1. Add "OpenSubtitles.org" as a provider in Settings.
2. Add "Chinese Simplified" to a language profile in Settings/Language.
3. Add movie "Indiana Jones and the Temple of Doom (1984)" to the wanted movie list.
4. Enable "Encode Subtitles To UTF8" in Settings/Subtitle.
5. Start task "Search for wanted Movies Subtitles"

**Expected behavior**
A Chinese Simplified subtitle was downloaded and added from OpenSubtitles.org.

**Actual behavior**
The following error is logged and no subtitle was added to the movie "Indiana Jones and the Temple of Doom (1984)".

`BAZARR Error saving Subtitles file to disk for this file:/mnt/shared/Animes/Movies/Superman - Red Son (2020)/Superman - Red Son (2020) - [Bluray-1080p][x264.AC3][EVO][Superman Red Son.2020.1080p.Bluray.DTS-HD.MA.5.1.X264-EVO[TGx]].mkv: ValueError("netloc '支持我们，欢迎购买vip移除所有广告，具体：www.opensubtitles.org' contains invalid characters under NFKC normalization")`

**Software (please complete the following information):**
 - Bazarr: v.1.0.2
 - Radarr version v.4.0.4.5922
 - Sonarr version v.3.0.6.1342
 - OS: DSM v.DSM 7.0.1-42218 Update 2
 - Docker v.20.10.3-1239

**Comment by morpheus65535** [comment]
Can you try disabling "Common Fixes" and see if you still have the issue? I just want to be sure it's related to part of code I guessing.

If it's not the case, please provide a complete debug log while reproducing the issue.

**Comment by janusn** [comment]
Could you elaborate where do I disable “Common Fixes”? Is it “Enabled subtitle to UTF-8” in settings/subtitle pane?

**Comment by morpheus65535** [comment]
> Could you elaborate where do I disable “Common Fixes”? Is it “Enabled subtitle to UTF-8” in settings/subtitle pane?

It's just 3 options underneat that one.

**Comment by janusn** [comment]
Sorry for the long delay. I was out of country and the DDNS was down. Hence I cannot access the bazarr until I've returned. I have tried to disable "Common Fixes" for twelve hours and enabled it yesterday.

Strangely, I have not seen any NFKC errors either enabled or disabled. I guess it has something to do with adaptive search. I am planning to disable it and try again.

**Comment by morpheus65535** [comment]
I've just realized that I've upgraded the tld module in upcoming 1.0.3. I will release it and let you test it again to be sure this is still an actual issue.

**Comment by morpheus65535** [comment]
No news, good news.
