### ISSUE TITLE
Bazarr not finding existing subtitles on provider (legendas.tv)

### ISSUE THREAD

**Issue by altanir84** [morpheus65535/bazarr#1726]
**Describe the bug**
While trying to find subtitles for the show Walking Dead Season 11, Bazarr claimed that no subtitles were found, even though the provider has the subtitles for the season. Sarching other shows, including the season 10 of the same show, results are found.

**To Reproduce**
1. Go to walking dead season 11
2. Click on find subtitles

**Expected behavior**
Bazarr should find the subtitles for every episode available on the provider

**Screenshots**

![image](https://user-images.githubusercontent.com/52831296/154377383-19b6616e-c189-4af5-8ad9-668246dff0bc.png)

![image](https://user-images.githubusercontent.com/52831296/154377453-9bc80fa0-d963-4800-a72f-bd6d0eb65cfe.png)

![image](https://user-images.githubusercontent.com/52831296/154377965-3820e95f-55b9-480f-9630-601ca9ff9485.png)
![image](https://user-images.githubusercontent.com/52831296/154377923-da2b053e-45bb-4d65-bdcd-b0aa0c1b8c58.png)

![image](https://user-images.githubusercontent.com/52831296/154377563-44b2f599-50b7-469d-bfe9-7fa4a979da01.png)

**Software (please complete the following information):**
Bazarr Version
1.0.2
Sonarr Version
3.0.6.1457
Radarr Version
4.0.4.5922
Operating System
Linux-4.4.180+-aarch64-with-glibc2.26
Python Version
3.10.1

Ps.: Running on synology NAS DS418 DSM 7.0.1-42218 Update 2

**Additional context**

**Comment by altanir84** [comment]
[bazarr.log](https://github.com/morpheus65535/bazarr/files/8084651/bazarr.log)

**Comment by morpheus65535** [comment]
From your log, there's something wrong when trying to login to the provider. The search is not even tried. Check your credentials.

**Comment by altanir84** [comment]
Thanks for the reply. Here are two logs, created seconds apart from each other. One is a search for TWD S11E09 and the other is a search for Pam & Tommy S01E04.

The credentials and configurations are all the same for both requests.
[bazarr_twd.log](https://github.com/morpheus65535/bazarr/files/8085406/bazarr_twd.log)
[bazarr_pam&tommy.log](https://github.com/morpheus65535/bazarr/files/8085407/bazarr_pam.tommy.log)

Bazarr did not find any subtitles for TWD while it did find for Pam & Tommy.

**Comment by morpheus65535** [comment]
Sorry for the delay. I've just tried to search for TWD S11E09 pt-BR subtitles on legendas.tv and I've got results:
![image](https://user-images.githubusercontent.com/5130500/155261076-eea0a65f-7a2b-4da8-9db1-e4b18a027630.png)

Is it still an issue for you? Maybe they just fixed "something" on their side. BTW I'm using latest beta but I don't see any change that could have fix this since 1.0.2.

**Comment by morpheus65535** [comment]
No news, good news.

**Comment by altanir84** [comment]
Sorry for the late reply, I dit not see your reply.

Anyway, the issue is still going on.

![image](https://user-images.githubusercontent.com/52831296/157681121-99aeabd8-9a3b-45f8-8845-a067ee0e22e4.png)
 
Only opensubitles are working for this episode.

![image](https://user-images.githubusercontent.com/52831296/157681248-494f357c-f3d2-436f-80e6-cceb02db93ff.png)

When only with legendas.tv as a provider, no results.

![image](https://user-images.githubusercontent.com/52831296/157681774-064e9c97-347e-4376-92de-0bd597ba4f9f.png)

Other tv shows are working as expected.

**Comment by morpheus65535** [comment]
@altanir84 I still can't reproduce this issue:

![image](https://user-images.githubusercontent.com/5130500/158059833-4085d482-f1fc-418d-ac3e-5159d3352da0.png)

**Comment by altanir84** [comment]
I saw you suggesting to erase the contents of cache and config folders, I'll try that. Should I delete all the files under the config folder?

**Comment by morpheus65535** [comment]
> I saw you suggesting to erase the contents of cache and config folders, I'll try that. Should I delete all the files under the config folder?

Only erase the file from the cache subfolder.

**Comment by altanir84** [comment]
Deleted the file, but the issue still remais. Only get results using opensubtitles provider.
