### ISSUE TITLE
[Argenteam provider] Wrong subtitle returned (another series)

### ISSUE THREAD

**Issue by JMVS** [morpheus65535/bazarr#1728]
**Describe the bug**
When searching for Severance S01E01, Bazaar downloaded and applied the subtitle for Castle Rock S01E01 which is called "Severance" (https://argenteam.net/episode/103041/Castle.Rock.%282018%29.S01E01-Severance). At the time of checking of subtitles this was the only provider showing a result.

**To Reproduce**
Have Bazaar download the Spanish subtitles for Severance S01E01 having selected Argenteam as the solely subs provider (this to prevent other providers returning the right one, when available).

**Expected behavior**
Bazaar should have discarded the subtitle.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/7751148/154746301-b6550b04-ece5-41b9-95ca-2a53c7c03778.png)

**Software (please complete the following information):**
Bazarr Version 1.0.2
Sonarr Version 3.0.6.1342
Radarr Version 4.0.4.5922
Operating System Linux-5.4.0-99-generic-x86_64-with (Docker)

**Additional context**
The year of the series is different (2018 vs 2022).
[20220218-bazarr-argenteam.log](https://github.com/morpheus65535/bazarr/files/8099794/20220218-bazarr-argenteam.log)

**Comment by vitiko98** [comment]
Thanks a lot for the report!
