### ISSUE TITLE
Latest nightly no longer shows missing subtitles for series

### ISSUE THREAD

**Issue by wastingaeons** [morpheus65535/bazarr#1731]
**Describe the bug**
On latest nightly, missing subtitles are no longer shown on Wanted or series pages. Bazarr shows that all subs are 100% complete when viewing the 'Series' page that lists all series.

Going back to release 1.0.2 works as expected.

**To Reproduce**
1. Go to a show you know you're missing subtitles
2. Scan disc for subtitles
3. Observe no missing subtitles are shown
4. Optional: Go back to release 1.0.2 and repeat steps 1-3 and observe proper missing counts

**Expected behavior**
Missing subtitles should be shown in both 'Wanted' and series pages.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 1.0.3-beta.29
 - Sonarr version 3.0.6.1460
 - OS: Hotio container

**Additional context**
I've noticed a new clause in the SQL query between this nightly and the latest release. Removing the `"t1"."missing_subtitles" IS NOT` clause from this query returns proper missing counts when querying the db directly: 
`SELECT COUNT(1) FROM (SELECT 1 FROM "table_episodes" AS "t1" INNER JOIN "table_shows" AS "t2" ON ("t1"."sonarrSeriesId" = "t2"."sonarrSeriesId") WHERE (((("t1"."missing_subtitles" IS NOT ?) AND ("t1"."missing_subtitles" != ?)) AND NOT ("t2"."tags" LIKE ?)) AND ("t1"."monitored" = ?))) AS "_wrapped"', [None, '[]', "%'nosubs'%", 'True']`

**Comment by morpheus65535** [comment]
Are you sure the issue is not that the series has the `nosubs` tag in Sonarr? I've just checked and I can see missing subtitles for episodes as expected.

BTW, I've tested the query and it works as expected:
`SELECT COUNT(1) FROM (SELECT 1 FROM "table_episodes" AS "t1" INNER JOIN "table_shows" AS "t2" ON ("t1"."sonarrSeriesId" = "t2"."sonarrSeriesId") WHERE (((("t1"."missing_subtitles" IS NOT NULL) AND ("t1"."missing_subtitles" != "[]")) AND NOT ("t2"."tags" LIKE "%'nosubs'%")) AND ("t1"."monitored" = "True"))) AS "_wrapped"`

**Comment by morpheus65535** [comment]
![image](https://user-images.githubusercontent.com/5130500/154871030-290ee1ac-622a-4cef-acba-87fc4aeea0ca.png)
![image](https://user-images.githubusercontent.com/5130500/154871054-08336c00-97fc-4f8a-bc58-3954d63f491c.png)

**Comment by wastingaeons** [comment]
I did make sure it wasnt the exclude tag.

I completely nuked my db and started over with latest nightly. Same issue. the 'missing_subtitle' field is always '[]' - going back to 1.02 and rescanning disc 'missing_subtitle' field in db shows correct ['en']

Something strange is going on, looks like it 'finds' subtitles when there are none embedded nor sidecar'd. See log for an example
[log.txt](https://github.com/morpheus65535/bazarr/files/8105877/log.txt)
.

**Comment by wastingaeons** [comment]
Okay figured it out finally lol - I only have 1 profile with only english. I also had the cutoff set to the english. Removing the cutoff and it's working normally. I see there was cutoff changes with `list_subtitles.py`

**Comment by morpheus65535** [comment]
Thanks for the investigation! Should be fixed in upcoming beta.
