### ISSUE TITLE
RTL Mod bug?

### ISSUE THREAD

**Issue by Shasoosh** [morpheus65535/bazarr#1732]
Example1 - Proper Hebrew (Bad for Kodi and Infuse):

> שלום!

Example2 - Bad punctuation (Good for Kodi and Infuse):

> !שלום

Today, most subtitles in Hebrew are written like "Example2". Popular players such as Kodi and Infuse are expecting "Example2" and fix the punctuation automatically. This has been a common standard for years. Hebrew subtitles are written with punctuation at the beginning of the sentence. 

The problem is that MKVs ripped from apple & amazon embed Hebrew subtitles with the "Example1" format. Something that most if not all players can't handle and display reversed punctuation.

From what I can tell (and from what I've tested) **RTL Mod** will only convert "Example2" to "Example1" which isn't helpful in that case.

Unfortunately **RTL Mod** doesn't work the other way around so "Example1" will not be converted to "Example2".

Not sure if this is a bug or intended behavior but I was wondering if it would be possible to extend that mod by selecting the desired punctuation location.

**Comment by morpheus65535** [comment]
Duplicate from #850 and #1444 ?

**Comment by Shasoosh** [comment]
Thanks for the reply. 

No. I’ve reviewed both of these before opening the ticket. One talks about Arabic (not related) and the other is about a fix for the old behavior.

**Comment by morpheus65535** [comment]
OK I've read you question again and, if I understand correctly, you would want Bazarr to modify how it fix bad punctuation position to do the opposite: unfix proper punctuation. Am I right? TBH, the current fix is working as intended.

The issue is with Kodi and they are about to release the fix: https://github.com/xbmc/xbmc/issues/18648

**Comment by Shasoosh** [comment]
You are right. The ask here is to "unfix" "proper" punctuation. 

The issue you linked proves my point. Kodi did had a punctuation bug BUT, if you'll download the [Hebrew_subs.zip](https://github.com/xbmc/xbmc/files/5440000/Hebrew_subs.zip) from the issue, you will notice that the subtitles there (and what the issue is based on) are also "Example2" as mentioned above.

What I'm saying here is that Kodi always expected "Example2", that is the convention for years for Hebrew subtitles. They even fixed a bug that caused "Example2" not showing up properly. 

Afaik "Example1" was never displayed properly on Kodi. 

I'm not sure what problem the RTL Mod was trying to solve and for what players but currently it is doing the opposite of what popular players are expecting.

Hebrew subtitles are a huge mess and bazarr is defiantly not the one to blame but maybe using the RTL Mod and some mild tweaks it can help mitigate this.

**Comment by morpheus65535** [comment]
@pannal maybe you can jump in since the RTL mod was originaly part of subzero. I've never fully understood what was the expected result from this mod.

**Comment by pannal** [comment]
This is where this comes from: https://github.com/pannal/Sub-Zero.bundle/issues/409
Might be that this isn't necessary anymore, but back then the RTL markers in subtitles weren't necessarily correct. The mod reverses the whole subtitles.

**Comment by Shasoosh** [comment]
Thanks for the info @pannal 

So the RTL Mod was originally created to fix a PLEX for Android bug. 

Offline question, is it possible for me to tweak that code and trigger it from bazarr's "Custom Post-Processing"?
