### ISSUE TITLE
Bazarr does not connect to Sonarr/Radarr using docker hostnames.

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [morpheus65535/bazarr#1733]
**Describe the bug**
Bazarr does not connect to Sonarr/Radarr using docker hostnames. Docker allows you to use hostnames to connect to other docker containers. You can either use the name of the docker container or specific a hostename to connect. 

**To Reproduce**
1. Go to Sonarr/Radarr Setting in Bazarr
2. Enter a docker hostname/container name of Sonarr/Radarr Ex. "Sonarr"
3. See error
```
2022-02-21 02:08:49,339 - app  (7fcb5206ab38) :  ERROR (app:1457) - Exception on /bazarr/test/http/Sonarr:8989/sonarr/api/system/status [GET]
2022-02-21 02:08:49,823 - app  (7fcb52373b38) :  ERROR (app:1457) - Exception on /bazarr/test/http/Sonarr:8989/sonarr/api/v3/system/status [GET]
```

**Expected behavior**
Able to connect to Sonarr/Radarr.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 1.0.3-beta.29
 - Radarr version 4.0.4.5922
 - Sonarr version 3.0.6.1457
 - OS: Ubuntu 20.04

**Additional context**

**Comment by morpheus65535** [comment]
Bazarr work perfectly fine with docker container name resolution on custom bridge interface. The issue is something else. I'm gonna need your log file to see the exception trace. Make sure it's the actual bazarr.log file, not the console output.

**Comment by Cookie-Monster-Coder** [comment]
Solved. Proxy was turned on, which was causing the issue. I put in Sonarr/Radarr container name in "Ignored Addresses" and rebooted Bazarr. Works now!
