### ISSUE TITLE
Manual downloaded subtitle not automaticly imported

### ISSUE THREAD

**Issue by Kopernikus1979** [morpheus65535/bazarr#1737]
**Describe the bug**
When I manually download a subtitle for a movie it gets downloaded in the correct movie folder, however it doens't get linked automaticly, I have to manually upload it.

**Software (please complete the following information):**
 - Bazarr: v1.0.3-beta.32
  - OS: Unraid 6.10 rc2

**Additional context**

**Comment by morpheus65535** [comment]
Reproduce the issue with debug log. I can't do anything without it.

**Comment by morpheus65535** [comment]
No news, good news.
