### ISSUE TITLE
Bazarr doesn't find subtitles for South Park S25 that are available on legendas.tv

### ISSUE THREAD

**Issue by maestrozezinho** [morpheus65535/bazarr#1738]
Log: https://pastebin.com/qy3ACkMh

Bazarr doesn't find subtitles for South Park S25 that are available on legendas.tv

**Software (please complete the following information):**
Bazarr Version
1.0.2
Sonarr Version
3.0.6.1342
Radarr Version
4.0.4.5922
Operating System
Linux-5.4.0-100-generic-x86_64-with
Python Version
3.9.5
Bazarr Directory
/app/bazarr/bin/bazarr/api

Docker image: linuxserver/bazarr

**Comment by morpheus65535** [comment]
Seems to be the same behavior than #1726 that "fixed" by itself. Maybe some glitch on provider side. Can you test again using latest beta?

**Comment by maestrozezinho** [comment]
Tested using the development image by linuxserver and it didn't fix:

https://pastebin.com/ZtVqDEAM

Bazarr Version
1.0.3
Package Version
v1.0.3-ls286 by [linuxserver.io](https://linuxserver.io)
Sonarr Version
3.0.6.1342
Radarr Version
4.0.4.5922
Operating System
Linux-5.4.0-100-generic-x86_64-with
Python Version
3.9.5
Bazarr Directory
/app/bazarr/bin
Bazarr Config Directory
/config
Uptime

**Comment by morpheus65535** [comment]
The search to legendas.tv isn't done at all. Please disable all other providers, empty the config/cache directory and reproduce again please.

**Comment by morpheus65535** [comment]
No news, good news.
