### ISSUE TITLE
Can sync with Sonarr but not Radarr

### ISSUE THREAD

**Issue by randommonth** [morpheus65535/bazarr#1740]
I have installed the linuxserver container of Bazarr on Unraid. I have sucessfully synced with Sonarr but Radarr is not working. The connection to Radarr is working (through the Test button) and I've mapped the right paths. The notifications show that it appears to fail on the first movie in the folder. I've attached the logs.
Thanks

[bazarr.log](https://github.com/morpheus65535/bazarr/files/8146108/bazarr.log)

**Comment by halali** [comment]
Duplicate #1739
