### ISSUE TITLE
Cannot start Bazarr

### ISSUE THREAD

**Issue by MrMdemiC** [morpheus65535/bazarr#1742]
**Describe the bug**
Ive seen that my bazarr has been offline so i tried to restart it again.
After downloading the latest version and restarting it again its giving an error when starting.
Ive cleared all the logs but still it does not want to start.

**Expected behavior**
Bazarr to start

**Screenshots**
[Screenshot off the error](https://i.imgur.com/kupWhcY.png)
Also here is the error in pastebin: https://pastebin.com/XPZBHQcF

**Software (please complete the following information):**
 - Bazarr: Latest from yesterday
 - OS: Windows Server 2019 version 1809

**Comment by morpheus65535** [comment]
Uninstall and make sure that the c:\Bazarr directory is deleted. After that you can reinstall properly. It should work.

**Comment by MrMdemiC** [comment]
it is working now,, thank you very much! 

I created an new folder named BazarrV2 and renamed the old one to Bazarr.old

Now its all working, thank you very much for the quick reply!
