### ISSUE TITLE
Titlovi provider always returns AuthenticationError

### ISSUE THREAD

**Issue by d3kstr0za** [morpheus65535/bazarr#1746]
**Describe the bug**
Titlovi provider always returns AuthenticationError.

**To Reproduce**
I'm using a lowercase username with no digits. Also no digits or numbers in the password.
Logging through their website works fine.

[Another person](https://forum.titlovi.com/bazarr-titlovi_t100373.html) has reported this on their forum a couple of weeks ago.

**Expected behavior**
I should be able to use titlovi.

**Software (please complete the following information):**
- Bazarr Version 1.0.3
- Package Version v1.0.3-ls286 by [linuxserver.io](https://linuxserver.io)
- Sonarr Version 3.0.6.1342
- Radarr Version 4.0.5.5972
- Operating System Linux-5.4.0-100-generic-x86_64-with
- Python Version 3.9.5

**Comment by morpheus65535** [comment]
Duplicate from #1511 #1512 #1687

**Comment by d3kstr0za** [comment]
Damn, I did find the first two but couldn't get it to work. 
The latest one mentioned that only creating a new account fixed the issue on their end, and it did the same for me. Really weird.

Thank you for the triage!
