### ISSUE TITLE
Bazarr doesn't find subtitles for some TVSHOW like "1883", "the cleaning lady" that are available on (subscene)

### ISSUE THREAD

**Issue by Mohsin1222222** [morpheus65535/bazarr#1747]
Log: https://pastebin.com/wzh9HvqM

Bazarr doesn't find subtitles for some TVSHOW like "1883", "the cleaning lady" that are available on (subscene)

 - Bazarr: [e.g. v 1.0.3]
 - Radarr version [e.g. v 3.0.6.1342]
 - Sonarr version [e.g. v 2.0.0.0001]
 - Operating System
Linux-4.4.249-1.el7.elrepo.x86_64-x86_64-with
Python Version
3.9.5
Bazarr Directory
/app/bazarr/bin

**Comment by morpheus65535** [comment]
You can send it to me in PM on Discord.

**Comment by morpheus65535** [comment]
It sounds quite clear to me: `ConfigurationError: Username and password must be specified`

You could have seen that in System-->Providers
