### ISSUE TITLE
Can't start Bazarr

### ISSUE THREAD

**Issue by gyCfjSnO** [morpheus65535/bazarr#1748]
**Describe the bug**
Unable to start Bazarr

**To Reproduce**
`sudo systemctl start bazarr`

**Expected behavior**
Should be able to access Bazarr

**Software (please complete the following information):**
 - Bazarr: N/A
 - Radarr version 4.0.4.5922
 - Sonarr version 3.0.6.1342
 - OS: Debian 11

**Additional context**

[bazarr_log.txt](https://github.com/morpheus65535/bazarr/files/8167332/bazarr_log.txt)

**Comment by morpheus65535** [comment]
Did you configure a proxy in Bazarr settings?

**Comment by gyCfjSnO** [comment]
> Did you configure a proxy in Bazarr settings?

Not that I'm aware of, I used swizzin to set it up.

https://github.com/swizzin/swizzin

**Comment by morpheus65535** [comment]
If you delete the config directory content and restart Bazarr service, does it works? If not, it's not a Bazarr issue and I suggest you see with your seedbox provider support.

**Comment by gyCfjSnO** [comment]
> If you delete the config directory content and restart Bazarr service, does it works? If not, it's not a Bazarr issue and I suggest you see with your seedbox provider support.

Deleting the config file worked thanks! Service now starts. I am self hosting using Swizzin.
