### ISSUE TITLE
Bazarr rev proxy with apache different then sonarr/radarr

### ISSUE THREAD

**Issue by djratza** [morpheus65535/bazarr#1750]
**Describe the bug**
Configuring bazarr using apache proxy is different then sonarr and radarr, in the proxy menu the rev proxy BASE URL needs to be with a / at the end -> bazarr/

**To Reproduce**
1. Configure BASE URL to bazarr
2. Confgure apache rev proxy:
  ProxyPass /bazarr http://127.0.0.1:6767/bazarr
  ProxyPassReverse /bazarr http://127.0.0.1:6767/bazarr
4.Testu URL with https://URL/bazarr -> not working only if you add https://URL/bazarr/login
5. See error

**Expected behavior**
Should redirect to correct URL

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: latest version v1.0.3
 - Radarr version [e.g. v 0.2.0.0001]
 - Sonarr version [e.g. v 2.0.0.0001]
 - OS: [e.g. Windows 10]

**Additional context**
In order to also share a fix:

Configure BASE URL to bazarr/
configure proxy as:

  ProxyPass /bazarr/ http://127.0.0.1:6767/bazarr/
  ProxyPassReverse /bazarr/ http://127.0.0.1:6767/bazarr/

Then it will be accessible as expected - https://URL/bazarr

**Comment by morpheus65535** [comment]
It's technically impossible to make `/bazarr` redirect to `/bazarr/` due to web server limitation in Bazarr. Keep in mind that Bazarr doesn't share a single line of code with the other *ARR.

We can update the wiki with proper configuration.

@TRaSH- are you able to take a look at it? I'm out of town.

**Comment by morpheus65535** [comment]
I've just checked the wiki page and it's fine. Using that should work as expected: https://wiki.bazarr.media/Additional-Configuration/Reverse-Proxy-Help/#using-apache-2312-or-greater-and-bazarr-base-url
