### ISSUE TITLE
Bazarr API, update movie profile?

### ISSUE THREAD

**Issue by stevezau** [morpheus65535/bazarr#1753]
Hi, I am trying to use the bazarr api to clear the profile id for movies/series. 

I have a LOT of missing movies/series. Some of them are old and will likely never be filled. I am writing a script to check the bazarr wanted queue, check if the series/movie is old and if so clear the profile language so bazarr does not keep trying to search for it.

This is not possible via the GUI as it would take be a very long time to do it 1 by 1.

I am using this approach via python. Note I have also sent the x-api-key but removed it below.

``` requests.post('%smovies' % bazarr_url, files=(('radarrid', 34343), ('profileid', 'null')))```

This sends a "multipart/form-data ". I get a 204 response but it does not update in bazarr. 

Any ideas or is there an actual json API I can hit?

**Comment by halali** [comment]
Please come to discord for support. This isnt an issue. Closing.
