### ISSUE TITLE
Not getting movies and subtitles from Radarr

### ISSUE THREAD

**Issue by cptduckie** [morpheus65535/bazarr#1754]
Except from auto updating Bazarr, Sonarr and Radarr there is nothing changed in the setup. 
As far as I can see in the logs, there is a 404 error and some exception. Bazarr/Radarr/Sonarr are runing in Docker on Synology and I tried restarting and resetting the container. I have not tried downgrading yet.

Job "Update Movie list from Radarr (trigger: interval[0:05:00], next run at: 2022-03-07 14:24:02 CET)" raised an exception

07/03/2022 14:19:02	BAZARR cannot get Radarr version	

07/03/2022 14:19:02	http://192.***.***.***:32703 "GET /api/system/status?apikey=********8c HTTP/1.1" 404 0	

07/03/2022 14:19:02	Starting new HTTP connection (1): 192.***.***.***:32703	

07/03/2022 14:19:02	BAZARR Starting movie sync from Radarr.	07/03/2022 14:19:02

```
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/bazarr/bin/bazarr/get_movies.py", line 41, in update_movies
    tagsDict = get_tags()
  File "/app/bazarr/bin/bazarr/get_movies.py", line 389, in get_tags
    return tagsDict.json()
  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Bazarr is on version 1.0.3 and Radarr 4.0.5.5981.
I have no clue where to start fixing this..

**Comment by halali** [comment]
I will give my 5 cents that you have wrongly setup your container. You didnt have setup port... So it changed dynamically and you get 404 hont found after sonarr container upgraded self

**Comment by cptduckie** [comment]
> I will give my 5 cents that you have wrongly setup your container. You didnt have setup port... So it changed dynamically and you get 404 hont found after radarr container upgraded self

Thank you for your reply but I did configure a port and there is nothing changed there. It has been running like this for months. I have checked it to be sure and port 32703 is still allocated to Radarr on the same IP address.

**Comment by morpheus65535** [comment]
What's returned when you access this url in your browser? Make sure to complete with obfuscated information.
http://192.***.***.***:32703/api/system/status?apikey=********8c

**Comment by cptduckie** [comment]
I get an 404, page not found. Just did a reset of the API key and tested it again with a new key but same error. So the issue is probably somewhere at Radarr?

Checked the Radarr logfile and do see the following which seems ok.
2022-03-09 17:47:24.5|Info|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was challenged.

But after enabling debug log:

2022-03-09 17:50:56.8|Debug|Api|[GET] /api/system/status?apikey=(removed) 404.NotFound (0 ms)

**Comment by morpheus65535** [comment]
You're not really using 1.0.3.
```
File "/app/bazarr/bin/bazarr/get_movies.py", line 389, in get_tags
    return tagsDict.json()
```
This should be line 400 in 1.0.3.
https://github.com/morpheus65535/bazarr/blob/master/bazarr/get_movies.py#L400

**Comment by morpheus65535** [comment]
Still an issue to be fixed here?

**Comment by cptduckie** [comment]
> You're not really using 1.0.3.
> 
> ```
> File "/app/bazarr/bin/bazarr/get_movies.py", line 389, in get_tags
>     return tagsDict.json()
> ```
> 
> This should be line 400 in 1.0.3. https://github.com/morpheus65535/bazarr/blob/master/bazarr/get_movies.py#L400

I have fixed it with a reinstall and it is working now. Tried updating to 1.0.3 a few times but it was still showing 0.9.5 when looking closer while saying everything was updated. Reinstall with the latest version fixed it.

**Comment by morpheus65535** [comment]
> I have fixed it with a reinstall and it is working now. Tried updating to 1.0.3 a few times but it was still showing 0.9.5 when looking closer while saying everything was updated. Reinstall with the latest version fixed it.

Nice to know you got it fixed! Thanks for reporting!
