### ISSUE TITLE
LegendasDivx - IPAdressBlocked

### ISSUE THREAD

**Issue by n0pe0n** [morpheus65535/bazarr#1757]
Describe the bug
I have currently always had the server IP blocked in the provider "LegendasDivx" and the develop of the provider said that there is now daily limit of searches per day.
Limit of 150 searches per day

To Reproduce

limit calls to the provider so as not to be blocked.

Bazarr Version: 1.0.4-beta.3
Sonarr Version: 3.0.7.1477
Radarr Version: 4.0.5.5981
Operating System: Linux-4.15.0-169-generic-x86_64-with
Python Version: 3.9.7

**Comment by morpheus65535** [comment]
If eh can tell us what http code we need to deal with after 150 search, we could throttle this provider for 24 hours. He need to give us a hint that the limit is reached prior returning `bloqueado` as request response.

**Comment by guardiaopt** [comment]
The code is the same as ip blocked. Because after 150 searches the ip is blocked and has to be manually unblocked.

**Comment by morpheus65535** [comment]
After some discussion with @guardiaopt, he implemented the feedback we needed to make sure IP would not get blocked anymore. Please test upcoming beta and report results.

**Comment by n0pe0n** [comment]
> After some discussion with @guardiaopt, he implemented the feedback we needed to make sure IP would not get blocked anymore. Please test upcoming beta and report results.

ok i've pulled to the latest version, I'm trying and later I give you feedback.
thks.

**Comment by n0pe0n** [comment]
yes, that sounds good. I did now automatic search and after a few minutes already appears the message "SearchLimitReached". I no longer got the IP Locked. Thanks for fixed

**Comment by Generator** [comment]
Can we reopen this, since the issue persists 

```
29/05/2022 12:26:45|INFO    |root                            |Using legendasdivx again after 15 hours, (disabled because: IPAddressBlocked)|
29/05/2022 12:26:47|INFO    |root                            |Throttling legendasdivx for 15 hours, until 22/05/30 02:39, because of: IPAddressBlocked. Exception info: 'LegendasDivx.pt :: Your IP is blocked on this server.'|
```

**Bazarr:** v1.0.4

**Comment by guardiaopt** [comment]
I don't think there are any problems, but If the abuse was too big your ip can be banned forever... or you are not using the latest version of the program.

**Comment by Generator** [comment]
I can login on the webpage but need to unblock the IP. 
Im using the docker version (linuxserver/bazarr:latest)

**Comment by morpheus65535** [comment]
@Generator there's no black magic here, if you use the website with your browser from the same IP, you're at risk of being blocked.

**Comment by Generator** [comment]
I only need to go to the website because isn't working on Bazarr
