### ISSUE TITLE
Bazarr doesn't register video file extension change

### ISSUE THREAD

**Issue by anonyme123** [morpheus65535/bazarr#1759]
**Describe the bug**
Bazarr is not registering video file extension changes, for instance hello.mkv --> hello.mp4
I tried:
- running task "Update all Episode Subtitles from disk" with ffprobe cache off in Settings > Scheduler
- update all in Sonarr then running task "Update Series list from Sonarr" and "Sync episodes with Sonarr"
- running task "Cache maintenance"
- restarting Bazarr

**To Reproduce**
1. Download a file
2. Change the file extension / remux the file

**Expected behavior**
Bazarr registers the updated file extension

**Screenshots**
<img width="1186" alt="Screen Shot 2022-03-10 at 9 44 13 AM" src="https://user-images.githubusercontent.com/19681420/157686619-4d55527b-cc3a-4362-b5a5-fbcaa0842445.png">

**Software** 
Bazarr Version: 1.0.3
Package Version: v1.0.3-ls146 by [linuxserver.io](https://linuxserver.io)
Sonarr Version: 3.0.7.1477
Radarr Version: 4.0.5.5981
Operating System: Linux-3.10.0-1160.11.1.el7.x86_64-x86_64-with
Python Version: 3.9.5

**Comment by morpheus65535** [comment]
I can't reproduce your issue. I've just tested this and it works as expected:

1. rename file (.mkv --> .mp4)
2. go to this specific series page in Sonarr
3. click on Refresh & Scan to make sure Sonarr catch the change
4. once completed, the episode filename is update in Sonarr and in Bazarr.

**Comment by anonyme123** [comment]
Yep I've done refresh & scan in Sonarr and waited for Bazarr to update itself, but it seems it never wants to let go of the old file extension.

Is there a cache somewhere I can clean ? 
Or another way to force Bazarr to register the extension change?

**Comment by morpheus65535** [comment]
This task would force the sync of all episodes: `Sync episodes with Sonarr`

**Comment by anonyme123** [comment]
Yes I did it several times but no luck. Anything else I can do?

**Comment by morpheus65535** [comment]
If Bazarr doesn't update, it's because Sonarr didn't updated properly itself. This task you run directly use the episode API endpoint of Sonarr to retrieve, the episodeId and path of episode file so it can't get wrong as we update those values on each run. Unfortunately, Sonarr have a history of not detecting properly file altered by external process/script.

**Comment by anonyme123** [comment]
I double checked and Sonarr definitely registered the extension change:
<img width="1240" alt="Screen Shot 2022-03-15 at 10 40 39 AM" src="https://user-images.githubusercontent.com/19681420/158402766-6ba9afe0-6ec1-4cf7-b368-4ef25e37a712.png">

**Comment by anonyme123** [comment]
Here it is [bazarr.log](https://github.com/morpheus65535/bazarr/files/8254388/bazarr.log)

**Comment by morpheus65535** [comment]
Thanks. Can you give me the json output from those calls to Sonarr API:
/api/v3/episode?seriesId=86&apikey=(removed)
/api/v3/episodeFile?seriesId=86&apikey=(removed)

**Comment by anonyme123** [comment]
Here they are [json files.zip](https://github.com/morpheus65535/bazarr/files/8255326/json.files.zip)

**Comment by morpheus65535** [comment]
Can you send me your bazarr.db in PM on Discord so I can check what's in there?
