### ISSUE TITLE
Delay after translate

### ISSUE THREAD

**Issue by Whininie** [morpheus65535/bazarr#1761]
**Describe the bug**
Delay when translate subtitles

**To Reproduce**
1. Go to 'the episode subtitle'
2. Click on 'toolbox'
3. Click on 'translate'
4. subtitle translated, but with delay

**Expected behavior**
Translate subtitle without delay

**Screenshots**
![1](https://user-images.githubusercontent.com/41687543/157997877-5d3fa578-9257-4459-a9c6-b40631d44355.png)
![2](https://user-images.githubusercontent.com/41687543/157997880-36f99a88-176e-4d3f-8761-86c3c1bc4e9d.png)
![3](https://user-images.githubusercontent.com/41687543/157997883-61425614-890d-42b9-928c-eb4820978610.png)

**Software (please complete the following information):**
 - Bazarr: [1.0.2]
 - Radarr version [4.0.5.5981]
 - Sonarr version [3.0.7.1477]
 - OS: [Truenass > Debian VM > Docker]

**Additional context**
Tested on: _The Rookie - Season 4 Episode 14 & 15_

**Comment by morpheus65535** [comment]
Fixed in 1.0.4-beta.2

**Comment by Whininie** [comment]
Oh my bad!, Ty for fast response!
