### ISSUE TITLE
Using subdivx again after 10 minutes, (disabled because: RarCannotExec)

### ISSUE THREAD

**Issue by farid77cl** [morpheus65535/bazarr#1762]
**Describe the bug**
when trying to download subtitles from suvdivx it indicates that there are no valid subtitles

**To Reproduce**
1. Go to wanted series subtitles
2. Click on the misisng subtitle, a manual search is generated and the subtitle is downloaded
3. See error "BAZARR No valid Subtitles file found for this file:..."

**Expected behavior**
download the selected subtitle

**Software (please complete the following information):**
 - Bazarr: 1.0.4-beta.6
 - Radarr version 4.0.5.5981
 - Sonarr version 3.0.7.1477
 - OS: Linux-5.10.78-5-osmc-aarch64-with-debian-10.11

**Comment by morpheus65535** [comment]
You didn't install rar executable.
