### ISSUE TITLE
Bazarr behind reverse proxy with custom base path - logo broken

### ISSUE THREAD

**Issue by sambartik** [morpheus65535/bazarr#1767]
**Describe the bug**
The logo's image src does not take into consideration the configured based path in settings. The result is that instead of image the alt text is shown.

**Software (please complete the following information):**
 - Bazarr: v1.0.4-beta.9

**Additional info**
Occurs only from the v1.0.4-beta.9 version.

**Comment by morpheus65535** [comment]
@LASER-Yi I guess you've just broke something my friend! ;-)

Can you take a look into it please?

**Comment by LASER-Yi** [comment]
Should be fixed in the upcoming beta version

**Comment by sambartik** [comment]
@morpheus65535 @LASER-Yi 

I have just noticed that another functionalities are broken after this update and might have something to do with base URL again? The background tasks indicator doesn't work at all (for example after executing search command or sync, etc). Syncing subtitles doesn't seem to do anything based on logs. I can't see any output of the syncing process.

Log after clicking sync subtitles:
```
18/03/2022 20:40:57|INFO    |root                            |BAZARR Log file emptied|
18/03/2022 20:41:00|DEBUG   |SignalRCoreClient               |Sending message <signalrcore.messages.ping_message.PingMessage object at 0x7f050a4da790>|
18/03/2022 20:41:00|DEBUG   |SignalRCoreClient               |{"type": 6}|
18/03/2022 20:41:04|DEBUG   |SignalRCoreClient               |Message received{"type":6}|
18/03/2022 20:41:04|DEBUG   |SignalRCoreClient               |Raw message incomming: |
18/03/2022 20:41:04|DEBUG   |SignalRCoreClient               |{"type":6}|
18/03/2022 20:41:05|DEBUG   |SignalRCoreClient               |Sending message <signalrcore.messages.ping_message.PingMessage object at 0x7f050a4dafd0>|
18/03/2022 20:41:05|DEBUG   |SignalRCoreClient               |{"type": 6}|
18/03/2022 20:41:10|DEBUG   |SignalRCoreClient               |Sending message <signalrcore.messages.ping_message.PingMessage object at 0x7f0511058a00>|
18/03/2022 20:41:10|DEBUG   |SignalRCoreClient               |{"type": 6}|
18/03/2022 20:41:12|INFO    |engineio.server                 |rwdx74jHatwS4x09AAAE: Sending packet PING data None|
18/03/2022 20:41:12|INFO    |engineio.server                 |rwdx74jHatwS4x09AAAE: Received packet PONG data |
18/03/2022 20:41:13|INFO    |engineio.server                 |qSxFt776Y9Sesmm8AAAC: Sending packet PING data None|
18/03/2022 20:41:13|INFO    |engineio.server                 |qSxFt776Y9Sesmm8AAAC: Received packet PONG data |
18/03/2022 20:41:15|DEBUG   |SignalRCoreClient               |Sending message <signalrcore.messages.ping_message.PingMessage object at 0x7f05110586d0>|
18/03/2022 20:41:15|DEBUG   |SignalRCoreClient               |{"type": 6}|
18/03/2022 20:41:19|DEBUG   |SignalRCoreClient               |Message received{"type":6}|
18/03/2022 20:41:19|DEBUG   |SignalRCoreClient               |Raw message incomming: |
18/03/2022 20:41:19|DEBUG   |SignalRCoreClient               |{"type":6}|
18/03/2022 20:41:20|DEBUG   |SignalRCoreClient               |Sending message <signalrcore.messages.ping_message.PingMessage object at 0x7f050a4f3070>|
18/03/2022 20:41:20|DEBUG   |SignalRCoreClient               |{"type": 6}|
```

Reverting to previous beta helped here as well.

PS: The theme-park theme is having weird background for the sidebar here after update.  This is an issue that has to be dealt on theme-park's side, right? 
![sidebar](https://user-images.githubusercontent.com/63553146/159073482-b5237cc4-3c94-456a-8f2d-29165d83d28d.png)

**Comment by morpheus65535** [comment]
@LASER-Yi in fact I thing that every command in UI aren't sent to backend. I've try the scan disk button but also the translate tools. Nothing happen and no call to backend in browser dev console network tab.

**Comment by LASER-Yi** [comment]
> @LASER-Yi in fact I thing that every command in UI aren't sent to backend. I've try the scan disk button but also the translate tools. Nothing happen and no call to backend in browser dev console network tab.

Should also be fixed in the next upcoming beta version

**Comment by LASER-Yi** [comment]
> @morpheus65535 @LASER-Yi
> 
> I have just noticed that another functionalities are broken after this update and might have something to do with base URL again? The background tasks indicator doesn't work at all (for example after executing search command or sync, etc). Syncing subtitles doesn't seem to do anything based on logs. I can't see any output of the syncing process.
> 
> Log after clicking sync subtitles:
> 
> ```
> 18/03/2022 20:40:57|INFO    |root                            |BAZARR Log file emptied|
> 18/03/2022 20:41:00|DEBUG   |SignalRCoreClient               |Sending message <signalrcore.messages.ping_message.PingMessage object at 0x7f050a4da790>|
> 18/03/2022 20:41:00|DEBUG   |SignalRCoreClient               |{"type": 6}|
> 18/03/2022 20:41:04|DEBUG   |SignalRCoreClient               |Message received{"type":6}|
> 18/03/2022 20:41:04|DEBUG   |SignalRCoreClient               |Raw message incomming: |
> 18/03/2022 20:41:04|DEBUG   |SignalRCoreClient               |{"type":6}|
> 18/03/2022 20:41:05|DEBUG   |SignalRCoreClient               |Sending message <signalrcore.messages.ping_message.PingMessage object at 0x7f050a4dafd0>|
> 18/03/2022 20:41:05|DEBUG   |SignalRCoreClient               |{"type": 6}|
> 18/03/2022 20:41:10|DEBUG   |SignalRCoreClient               |Sending message <signalrcore.messages.ping_message.PingMessage object at 0x7f0511058a00>|
> 18/03/2022 20:41:10|DEBUG   |SignalRCoreClient               |{"type": 6}|
> 18/03/2022 20:41:12|INFO    |engineio.server                 |rwdx74jHatwS4x09AAAE: Sending packet PING data None|
> 18/03/2022 20:41:12|INFO    |engineio.server                 |rwdx74jHatwS4x09AAAE: Received packet PONG data |
> 18/03/2022 20:41:13|INFO    |engineio.server                 |qSxFt776Y9Sesmm8AAAC: Sending packet PING data None|
> 18/03/2022 20:41:13|INFO    |engineio.server                 |qSxFt776Y9Sesmm8AAAC: Received packet PONG data |
> 18/03/2022 20:41:15|DEBUG   |SignalRCoreClient               |Sending message <signalrcore.messages.ping_message.PingMessage object at 0x7f05110586d0>|
> 18/03/2022 20:41:15|DEBUG   |SignalRCoreClient               |{"type": 6}|
> 18/03/2022 20:41:19|DEBUG   |SignalRCoreClient               |Message received{"type":6}|
> 18/03/2022 20:41:19|DEBUG   |SignalRCoreClient               |Raw message incomming: |
> 18/03/2022 20:41:19|DEBUG   |SignalRCoreClient               |{"type":6}|
> 18/03/2022 20:41:20|DEBUG   |SignalRCoreClient               |Sending message <signalrcore.messages.ping_message.PingMessage object at 0x7f050a4f3070>|
> 18/03/2022 20:41:20|DEBUG   |SignalRCoreClient               |{"type": 6}|
> ```
> 
> Reverting to previous beta helped here as well.
> 
> PS: The theme-park theme is having weird background for the sidebar here after update. This is an issue that has to be dealt on theme-park's side, right? ![sidebar](https://user-images.githubusercontent.com/63553146/159073482-b5237cc4-3c94-456a-8f2d-29165d83d28d.png)

Yes I have refactored the sidebar in the development version. Some class names are changed

**Comment by sambartik** [comment]
Above issues seem to be fixed. Thanks!

I have found another bugs, though, still connected to the UI refactor in v1.0.4-beta.9.

- history button for episode opens up a search window instead of history window
- interactive search window contains cached **results** for previously searched episode, i. e. if you interactively search episode 1 and then episode 2, the window still shows episode 1 search results. (similar to #1592)

Should I open a new issue and move it there?

**Comment by LASER-Yi** [comment]
> Above issues seem to be fixed. Thanks!
> 
> I have found another bugs, though, still connected to the UI refactor in v1.0.4-beta.9.
> 
> * history button for episode opens up a search window instead of history window
> * interactive search window contains cached **results** for previously searched episode, i. e. if you interactively search episode 1 and then episode 2, the window still shows episode 1 search results. (behaviour similar to [Username and password fields in settings of one provider are displaying information of previous provider #1592](https://github.com/morpheus65535/bazarr/issues/1592))
> 
> Should I open a new issue and move it there?

Yes please. Thanks!
