### ISSUE TITLE
manually upload episode number is wrong

### ISSUE THREAD

**Issue by xloooolx** [morpheus65535/bazarr#1769]
**Describe the bug**

**To Reproduce**
1. Go to series, the series you wan to upload from
3. Click on the season and episode you want to upload
5. push manual upload button and fill out pop up window
7. all episode number is wrong

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/2715006/159159279-e5b46ced-9fc9-4952-add9-fd1657bdfecc.png)

**Software (please complete the following information):**
 - Bazarr: 1.0.4-beta.11

**Comment by LASER-Yi** [comment]
Should be fixed in the upcoming beta version

**Comment by xloooolx** [comment]
Thank you, it works.
