### ISSUE TITLE
Error during start phase

### ISSUE THREAD

**Issue by Jorman** [morpheus65535/bazarr#177]
Hi, I just installed from source Bazarr on my debian 9.5
I found a "problem" during installation, I can't install libjpeg8-dev
```
sudo apt install libjpeg8-dev
[sudo] password for jorman:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libjpeg8-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libjpeg62-turbo-dev

E: Package 'libjpeg8-dev' has no installation candidate
```
So I installed the replacement, but during a start I got this:
```
python bazarr.py
/usr/lib/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/usr/local/lib/python2.7/dist-packages/backports': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
Bottle v0.12.13 server starting up (using WaitressServer())...
Listening on http://0.0.0.0:6767/
Hit Ctrl-C to quit.
```

I don't know if is related to the lib, what do you think?

Have a nice day.
Jo

**Comment by morpheus65535** [comment]
I've removed the libjpeg8-dev isn't required anymore. I've removed it from the wiki. Thanks!

The ImportWarning you get is caused by a missing file in Python installation. Nothing related to Bazarr and it doesn't cause any issue. You can just ignore it.

Have fun!

**Comment by Jorman** [comment]
Many thanks!

**Comment by halali** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/zywpDs4T/1-test)
