### ISSUE TITLE
Settings link in sidebar has incorrect icon

### ISSUE THREAD

**Issue by sambartik** [morpheus65535/bazarr#1770]
It has the same icon as "Wanted". Should have been a cog icon.

![settings icon](https://user-images.githubusercontent.com/63553146/159184403-ffd41e2f-867d-45fc-9c2a-6a15db09df7e.png)

Bazarr version: v1.0.4-beta.11

**Comment by LASER-Yi** [comment]
Should be fixed in the upcoming beta version
