### ISSUE TITLE
Bazarr doesn't recognize missing subtitles if Cutoff is active with only one language

### ISSUE THREAD

**Issue by nicopoore** [morpheus65535/bazarr#1771]
**Describe the bug**
If a profile only has one language (from now on, [lang]) and the cutoff is not empty (can be Any or [lang]), Bazarr will recognize movies with [lang] audio as not missing subtitles, and will therefore not search subtitles for it unless manually triggered.

**To Reproduce**
1. Create a profile with only one language ([lang])
2. Select Any or [lang] as Cutoff
3. Add a movie with [lang] audio and the profile created in steps 1 and 2

**Expected behavior**
Bazarr to download subtitles for the movie added in step 3, since neither "Forced" nor "Exclude audio" options are checked

**Screenshots**
![image](https://user-images.githubusercontent.com/24538153/159311523-fc066b1c-3704-434a-8501-522ae74230fb.png)
![image](https://user-images.githubusercontent.com/24538153/159312099-2b35c96d-74b4-4f73-8485-88d309634570.png)

**Software (please complete the following information):**
 - Bazarr: 1.0.3-beta.29
 - Radarr version: 4.0.4.5922
 - Sonarr version: N/A
 - OS: Ubuntu, Docker with linuxserver/radarr:develop and linuxserver/bazarr:development

**Additional context**
Bug can be fixed by user by removing Cutoff option, but shouldn't be necessary

**Comment by morpheus65535** [comment]
Sorry for the delay. I've just tested it and it works fine for me. I've created exactly the same profile as your screenshot and it show English subtitles as missing. Maybe upgrade to latest beta and try again. Other than that I wouldn't know what's your issue.

**Comment by morpheus65535** [comment]
No news, good news.
