### ISSUE TITLE
Exception on / [GET] while trying to open

### ISSUE THREAD

**Issue by MightyMrMuesli** [morpheus65535/bazarr#1772]
**Describe the bug**
Bazarr doesn't open and presents a return code 500 in browser. The service logs the following:

    ERROR (app:1457) - Exception on / [GET]
    ERROR (app:1457) - Exception on /favicon.ico [GET]

Debug log around pageview:

    21/03/2022 21:03:07|DEBUG   |SignalRCoreClient               |Sending message <signalrcore.messages.ping_message.PingMessage object at 0x7fe0b81dab00>|
    21/03/2022 21:03:07|DEBUG   |SignalRCoreClient               |{"type": 6}|
    21/03/2022 21:03:12|DEBUG   |SignalRCoreClient               |Sending message <signalrcore.messages.ping_message.PingMessage object at 0x7fe0b81dab00>|
    21/03/2022 21:03:12|DEBUG   |SignalRCoreClient               |{"type": 6}|
    21/03/2022 21:03:17|DEBUG   |SignalRCoreClient               |Sending message <signalrcore.messages.ping_message.PingMessage object at 0x7fe0b81dad10>|
    21/03/2022 21:03:17|DEBUG   |SignalRCoreClient               |{"type": 6}|
    21/03/2022 21:03:21|DEBUG   |peewee                          |('SELECT "t1"."configured", "t1"."updated" FROM "system" AS "t1" LIMIT ? OFFSET ?', [1, 0])|
    21/03/2022 21:03:21|ERROR   |app                             |Exception on / [GET]|Traceback (most recent call last):  File "/usr/lib/bazarr/bazarr/../libs/flask/app.py", line 2073, in wsgi_app    response = self.full_dispatch_request()  File "/usr/lib/bazarr/bazarr/../libs/flask/app.py", line 1518, in full_dispatch_request    rv = self.handle_user_exception(e)  File "/usr/lib/bazarr/bazarr/../libs/flask_restful/__init__.py", line 271, in error_router    return original_handler(e)  File "/usr/lib/bazarr/bazarr/../libs/flask_restful/__init__.py", line 271, in error_router    return original_handler(e)  File "/usr/lib/bazarr/bazarr/../libs/flask_restful/__init__.py", line 271, in error_router    return original_handler(e)  [Previous line repeated 7 more times]  File "/usr/lib/bazarr/bazarr/../libs/flask/app.py", line 1516, in full_dispatch_request    rv = self.dispatch_request()  File "/usr/lib/bazarr/bazarr/../libs/flask/app.py", line 1502, in dispatch_request    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)  File "/usr/lib/bazarr/bazarr/main.py", line 113, in catch_all    return render_template("index.html", BAZARR_SERVER_INJECT=inject, baseUrl=template_url)  File "/usr/lib/bazarr/bazarr/../libs/flask/templating.py", line 148, in render_template    ctx.app.jinja_env.get_or_select_template(template_name_or_list),  File "/usr/lib/bazarr/bazarr/../libs/jinja2/environment.py", line 1068, in get_or_select_template    return self.get_template(template_name_or_list, parent, globals)  File "/usr/lib/bazarr/bazarr/../libs/jinja2/environment.py", line 997, in get_template    return self._load_template(name, globals)  File "/usr/lib/bazarr/bazarr/../libs/jinja2/environment.py", line 958, in _load_template    template = self.loader.load(self, name, self.make_globals(globals))  File "/usr/lib/bazarr/bazarr/../libs/jinja2/loaders.py", line 125, in load    source, filename, uptodate = self.get_source(environment, name)  File "/usr/lib/bazarr/bazarr/../libs/flask/templating.py", line 59, in get_source    return self._get_source_fast(environment, template)  File "/usr/lib/bazarr/bazarr/../libs/flask/templating.py", line 95, in _get_source_fast    raise TemplateNotFound(template)jinja2.exceptions.TemplateNotFound: index.html|
    21/03/2022 21:03:22|DEBUG   |SignalRCoreClient               |Message received{"type":6}|
    21/03/2022 21:03:22|DEBUG   |SignalRCoreClient               |Raw message incomming: |
    21/03/2022 21:03:22|DEBUG   |SignalRCoreClient               |{"type":6}|
    21/03/2022 21:03:22|DEBUG   |SignalRCoreClient               |Sending message <signalrcore.messages.ping_message.PingMessage object at 0x7fe0b81da5f0>|
    21/03/2022 21:03:22|DEBUG   |SignalRCoreClient               |{"type": 6}|
    21/03/2022 21:03:27|DEBUG   |SignalRCoreClient               |Sending message <signalrcore.messages.ping_message.PingMessage object at 0x7fe0b81da5f0>|
    21/03/2022 21:03:27|DEBUG   |SignalRCoreClient               |{"type": 6}|
    21/03/2022 21:03:32|DEBUG   |SignalRCoreClient               |Sending message <signalrcore.messages.ping_message.PingMessage object at 0x7fe0b81dab00>|
    21/03/2022 21:03:32|DEBUG   |SignalRCoreClient               |{"type": 6}|

**To Reproduce**
1. Install bazarr  v1.0.4-beta.5,  v1.0.4-beta.11 or  v1.0.4-beta.12
2. Start the bazarr systemd service
3. Open http://bazarr:6767

**Expected behavior**
Site opens.

**Software (please complete the following information):**
 - Bazarr: v1.0.4-beta.5, v1.0.4-beta.11 or  v1.0.4-beta.12
 - OS: Arch Linux

**Additional context**
Referenced in #1712

**Comment by morpheus65535** [comment]
`TemplateNotFound(template)jinja2.exceptions.TemplateNotFound: index.html`

You haven't used the release zip file that include prebuild user interface templates: https://github.com/morpheus65535/bazarr/releases/latest/download/bazarr.zip

**Comment by MightyMrMuesli** [comment]
Yeah, I've just pulled the tagged source from the beta, didn't realize there where pre-release builds. This fixed the issue, thank you! v1.0.4-beta.12 is working on my machine.
