### ISSUE TITLE
Python dock icon appears while running bazarr [macOS]

### ISSUE THREAD

**Issue by alexreg** [morpheus65535/bazarr#1775]
**Describe the bug**
The Python dock icon (the rocketship) appears as long as bazarr is running, which is somewhat annoying.

**To Reproduce**
1. Launch bazarr on macOS from terminal (or from launchd daemon)
3. Observe Python icon in dock for as long as it is running.

**Expected behavior**
No dock icon for Python.

**Software (please complete the following information):**
 - Bazarr: 1.0.3
 - OS: macOS 12.2.1

**Comment by alexreg** [comment]
It seems this may be something to do with matplotlib, which I noticed that some of the dependencies are using. A solution is suggested [here](https://leancrew.com/all-this/2014/01/stopping-the-python-rocketship-icon/) (see the *Update 1/16/14* section) — though I'm not sure if this needs to be done by patching the individual dependencies. Or perhaps it is another dependency that macOS thinks is using a GUI, causing the Python dock icon to apepar.

**Comment by morpheus65535** [comment]
How did you install Python? What version?

I've just tested using Brew installed Python (multiple versions) without being able to reproduce.

**Comment by alexreg** [comment]
That's odd. I'm using Homebrew Python (3.9).

**Comment by morpheus65535** [comment]
![image](https://user-images.githubusercontent.com/5130500/159401786-719896cb-55a7-40f7-99f2-479ad15996c3.png)

**Comment by alexreg** [comment]
Yeah, my installation looks very similar. Not sure how to explain this. I'll see if it keeps occurring. Thanks for your response in any case.

**Comment by morpheus65535** [comment]
No problem. Keep me informed and we'll work together to open issues on those problematics modules. Reopen if required.

**Comment by alexreg** [comment]
Hi @morpheus65535. Unfortunately this is still happening for me. As far as I see, we have a few options.
1. Get this fixed in problematic modules (matplotlib? maybe others?), as you mentioned. Probably ideal.
2. Monkey-patch the problematic bits of the dependencies, if possible.
3. Patch the source code of the problematic dependencies, if monkey patching is not feasible.

Any thoughts?

**Comment by morpheus65535** [comment]
@alexreg I would defenitely go with the first suggestion. The others wont age well.

**Comment by alexreg** [comment]
@morpheus65535 You're right, although I mainly mentioned the other two because some project maintainers are very slow to respond and accept PRs. (Happily not at all you, though!)

**Comment by alexreg** [comment]
@morpheus65535 I have tracked it down to the *pyenchant* library, which Bazarr (optionally) imports. There's an [open issue](https://github.com/pyenchant/pyenchant/issues/238) for this problem.

**Comment by alexreg** [comment]
Incidentally, my first impression was that it could be caused by `bazarr.py` launching its own instance of Python. This is not actually the culprit, but I'm curious if there's a good reason you do this rather than just importing the `bazarr.main` module?

**Comment by morpheus65535** [comment]
> I'm curious if there's a good reason you do this rather than just importing the `bazarr.main` module?

bazarr.py is the daemon process. It's only job is to give the possibility of restarting main.py without relying on specific operating system daemons.
