### ISSUE TITLE
Bazarr marks manually uploaded sub as HI even though it is not selected

### ISSUE THREAD

**Issue by Ruvon** [morpheus65535/bazarr#1776]
**Describe the bug**
pretty much the title; I select a movie (Some like it hot 1959) and press on 'upload', select my file and then select english, no HI, no forced, press 'upload' and voila, for some reason Bazarr tags it with 'English HI'

**To Reproduce**
1. have 'Some like it hot' in your library, because it's an awesome film
2. Click on it in the Bazarr list
3. Click on 'upload' in top right
4. Select subtitle file
5. Select just english and press 'upload'
6. ...
7. profit

**Expected behavior**
it should be tagged english

**Screenshots**
can do, but I don't think it's necessary

**Software (please complete the following information):**
 - Bazarr: 1.0.3, Package Version v1.0.3-ls148 by [linuxserver.io]
 - Radarr version 4.0.5.5981
 - OS: Docker

**Additional context**
checking through the file it doesn't have anything special, just some \<i> italic \</i> tags and some ♪ lyrics ♪, nowhere any [...] which would be used for closed captions I think? attached file anyway
[3_English.txt](https://github.com/morpheus65535/bazarr/files/8321298/3_English.txt)

**Comment by morpheus65535** [comment]
Although I respect your right to disagree, I would suggest some reading regarding HI/CC/SDH subtitles:
https://en.wikipedia.org/wiki/Subtitles#Closed_captions
https://en.wikipedia.org/wiki/Closed_captioning#Syntax

Both link clearly state that songs lyrics are subtitles.

As for your suggestion, this would require a new process of remembring user input for specific subtitles. Actually, we simply replace the index subtitles when required without taking previous values into account. I don't see this in an upcoming future.

**Comment by Ruvon** [comment]
thank you for providing the links (:
I understand your point, and also from the standpoint of implementing it I understand the need for generalisation and simplification.

However, I would be curious to hear your thoughts on this:
suppose you are watching a musical. all that's happening is singing. so what's gonna be in a non-HI subtitlefile? nothing? well, that's a shitty UX if you ask me
and it is sufficient for a HI person if the lyrics are provided? however no ambiance, no tone of voice, no descriptive text of auditory experience whatsoever? also pretty shitty UX imo.

I fully understand that lyrics will in most cases be for a song playing in the background and therefore precisely fall into this category of descriptive text that I was just talking about. however that's not always the case. when characters talk in a singing voice subtitlesfiles might already put ♪, but you couldn't just leave that part out of the normal subtitles and only put it for HI, that would make absolutely no sense.

In any way, I don't think people are gonna die because bazarr lables subtitles as HI when they're not, just thought I would give my input on the matter (:
cheers, and have a nice rest of the week
