### ISSUE TITLE
Subtitle Folder "Absolute Path" is not respected.

### ISSUE THREAD

**Issue by henrikhasell** [morpheus65535/bazarr#1781]
**Describe the bug**
Subtitle Folder "Absolute Path" is not respected.

**To Reproduce**
1. Go to Settings > Subtitles
2. Choose "Absolute Path" in "Subtitle Folder" section
3. Set the "Absolute Path" to be `/output` or some other absolute path.
4. Downloaded subtitles will be written alongside the video file.

**Expected behavior**
Files should be written to `/output`.

**Actual  behavior**
Files are witten to `/mnt/sonarr`.

**Screenshot**
![Screenshot from 2022-03-26 17-19-42](https://user-images.githubusercontent.com/8373963/160250436-1b85278e-c9fe-4180-bf75-208057366643.png)

**Sample Log Line**
```
2022-03-26 16:28:40,003 - root                             (7f7c84b59b38) :  ERROR (download:91) - BAZARR Error saving Subtitles file to disk for this file:/mnt/sonarr/Twin Peaks/Season 2/Twin.Peaks.S02E13.Checkmate.1080p.10bit.BluRay.6CH.x265.HEVC-PSA.mkv: PermissionError(13, 'Permission denied')
```
See it is writing to Sonarr subdirectory. Subtitle folder is set to "Absolute Path" "/output" in this screenshot.

**Software (please complete the following information):**
 - Bazarr: 1.0.3
 - Radarr version 4.0.5
 - Sonarr version 3.0.7
 - OS: Docker Image (Linux host)

**Additional context**

**Comment by henrikhasell** [comment]
I also tested with the latest dev build (built 9 hours ago at time of writing)

**Comment by halali** [comment]
Did you read log line you posted ? `PermissionError(13, 'Permission denied')`

Bazarr don't have permission to write to that folder

**Comment by henrikhasell** [comment]
Added screenshot.

**Comment by halali** [comment]
I understand, but have bazarr write access to /output folder ?

in this log line is movie file not subtitle destination... maube its not good to show movie location... but your issue is that subtitles cant be written to /output directory because have permissions issue

**Comment by henrikhasell** [comment]
The log says the "permission denied" error is for the `/mnt/sonarr` directory.
I can confirm that Bazarr does have write access to `/output`.

**Comment by henrikhasell** [comment]
Docker container was running as `root` and when exec'ing into the container, I was able to write to `/output`.
However, bazarr seems to run as UID 1000 in Docker.
The docker image I am using is [linuxserver/bazarr](https://hub.docker.com/r/linuxserver/bazarr).
