### ISSUE TITLE
Bazarr unable to grab the correct subtitle

### ISSUE THREAD

**Issue by Fhd-pro** [morpheus65535/bazarr#1782]
**Describe the bug**

When searching for a subititle that is available in subscene with is the exact file name letter by letter
it’s no been grabbed and the final score is very low while other wrong subtitles ( cam releases ) scored 73
My score settings is set on 82 if lowered it will garb the cam releases

**Screenshots**

![15172F8E-3060-4699-B45F-FBD91E981A9E](https://user-images.githubusercontent.com/82862079/160257309-60444501-4f32-4b24-99cf-286e93592c17.jpeg)

**Software**

 - Bazarr: [v1.0.3]

 - Package Version v1.0.3-ls147 by [linuxserver.io]

 - Sonarr Version 3.0.7.1477

 - Radarr Version 4.0.5.5981

  - OS: Linux-5.4.0-80-generic-x86_64-with

**Additional context**

The subscene link for the correct subtitle - language Arabic.

https://subscene.com/subtitles/death-on-the-nile-2022/arabic/2730469

**Comment by Fhd-pro** [comment]
Properly has something to do in how subscene has one single upload with multiple names set by the uploader and bazarr maybe only sees a single one of them , manual search doesn’t work at all for subscene it’s always shows no result if that’s matter

**Comment by halali** [comment]
Do you have enabled anticaptcha enabled?

We will need full log file not only small part.

**Comment by morpheus65535** [comment]
> I have attached the latest log 

Where it is?

**Comment by Fhd-pro** [comment]
[bazarr.log](https://github.com/morpheus65535/bazarr/files/8371509/bazarr.log) 

I replied using the email in the last time,  it should be attached this time.

**Comment by morpheus65535** [comment]
Maybe you can try ith latest beta. There's been an issue with subscene in 1.0.3.

**Comment by Fhd-pro** [comment]
> Maybe you can try ith latest beta. There's been an issue with subscene in 1.0.3.

Unfortunately I'm using a dedicated seedbox provider so I will have to wait for the official release to update.

Thank you for taking the time to reply.

**Comment by morpheus65535** [comment]
Then I'll close this issue. Re-open it once you're going to be able to test it.

**Comment by Fhd-pro** [comment]
> Then I'll close this issue. Re-open it once you're going to be able to test it.

Just to confirm the issue is still persist with subscene
Bazarr version 1.0.4-beta.20

Seems subscene issue more than Bazarr properly they are encountering Bazarr and death by captcha is not doing any activities with it

**Comment by Fhd-pro** [comment]
Tested the latest beta 1.0.4 20 and still having the issue with subscene

No activities in death by captcha and bazarr doesn't seem to try that hard to search in subscene throttle immediately or in few seconds

*I did made a comment before this one but cannot see it for some reason

**Comment by Fhd-pro** [comment]
Just to update you that today and without changing or doing anything Bazarr start grabbing subtitles from subscene
Not sure if this is temporary or what

My version as mentioned before the latest beta 1.0.4 beta 20

**Comment by morpheus65535** [comment]
@Fhd-pro you're IP have probably been blocker on their side because its been working fine for many users:
![image](https://user-images.githubusercontent.com/5130500/162179849-20e29be9-e1d4-4aac-a643-73b2fea53d10.png)

**Comment by morpheus65535** [comment]
@Fhd-pro thanks I appreciate the feedback! :-)
