### ISSUE TITLE
Same language is downloaded multiple times

### ISSUE THREAD

**Issue by Beta66** [morpheus65535/bazarr#1785]
**Describe the bug**
Searching for subtitles on Bazarr will download languages in profiles to be pulled multiple times from the same and/or seperate sources.

**To Reproduce**
Add, English, Spanish, Dutch, German, Norwegian, Danish, Swedish, Portuguese and create a profile
Add profile to wanted titles
Search for subtitles
Bazarr will show one subtitle downloaded, when looking at history, bazarr will download up to 11 times the same subtitle from the same source.

**Expected behavior**
Download 1 subtitle per language in profiles per title.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: v1.0.4-beta.17
 - Radarr version 4.0.5.5981
 - Sonarr version 3.0.7.1485
 - OS: Ubuntu 18.04

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Please test and confirm.

**Comment by morpheus65535** [comment]
Thanks!
