### ISSUE TITLE
Bazarr not starting anymore

### ISSUE THREAD

**Issue by L2v2P** [morpheus65535/bazarr#1786]
Seemingly after an update of my Raspberry Pi OS bazarr (running in Docker pulled from https://hub.docker.com/r/linuxserver/bazarr) won't start anymore. In the log files I see entries related to connection errors:

- Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases?per_page=100 (Caused by NewConnectionError(\'<urllib3.connection.HTTPSConnection object at 0x74b0cf88>: Failed to establish a new connection: [Errno -3] Try again\'))'.

It may be related to https://github.com/morpheus65535/bazarr/issues/235 as I noticed that openssl was upgraded recently. Any idea how to fix this?

**Comment by morpheus65535** [comment]
Bad configuration of your docker networking. In anycase, it's not a Bazarr issue. I'll close this but you can come by our Discord support server and some users may be able to help you pin point your issue.
