### ISSUE TITLE
cant login to ktuvit provider

### ISSUE THREAD

**Issue by biGdada** [morpheus65535/bazarr#1790]
**Describe the bug**
got the hashed password, according to this guide:
https://github.com/XBMCil/service.subtitles.ktuvit

i am getting thefollowing message in the log:
Throttling ktuvit for 10 minutes, until 22/04/05 11:32, because of: AuthenticationError. Exception info: 'Error Logging in to Ktuvit Provider: ההתחברות נכשלה'
(the hebrew part says: connection failed)

**Expected behavior**
successful login

**Software (please complete the following information):**
 - Bazarr: [e.g. v 1.0.3]
 - Radarr version [e.g. v 4.0.5.5981]
 - Sonarr version [e.g. v 3.0.7.1477]
 - OS: [e.g. FreeBSD-12.2-RELEASE-p12-amd64-64bit-ELF]

**Comment by morpheus65535** [comment]
This procedure works perfectly well as far as I know. This is more of a support question than an issue. You can try to search existing issues or get to Discord for live support.

**Comment by biGdada** [comment]
> This procedure works perfectly well as far as I know.
you mean "used to work perfectly well". 
a few month ago i used a similar procedure to connect the kodi addon to ktuvit.me. i am familiar with it and truly believe that i did everything correctly.

oh well, if you dont want bug reports, i'll probably try to solve it myself. 

cheers

**Comment by morpheus65535** [comment]
Seriously dude, there's been over 500 subtitles downloaded from ktuvit in the last week. I'm pretty sure this provider works as expected.

Just to be sure, I've created an account on ktuvit.me and followed the procedure:
![image](https://user-images.githubusercontent.com/5130500/161970754-c3808be1-8d42-4f8d-babc-9af9e9687f2c.png)

**Comment by biGdada** [comment]
just fyi, my credentials are correct.
i am able to authenticate against the endpoint.
![Screen Shot 2022-04-06 at 16 08 09](https://user-images.githubusercontent.com/1241522/161982232-bf9ff1b4-4ebb-4509-bc67-de8d123635a6.png)


i guess it means that something IS wrong with your amazing piece of software, but you probably know better...
