### ISSUE TITLE
Bazarr latest Nightly - exception/throttling due to missing attributes. Only happens on certain providers.

### ISSUE THREAD

**Issue by polt13** [morpheus65535/bazarr#1792]
**Describe the bug**
With certain providers, on Python 3.10, Bazarr raises an exception due to mising attributes. Others, like OpenSubtitles work properly.

Small log message after a couple of minutes of trying to fetch subs:

|BAZARR Log file emptied|
06/04/2022 18:12:49|INFO    |root                            |Throttling supersubtitles for 10 minutes, until 22/04/06 18:22, because of: AttributeError. Exception info: "'list' object has no attribute 'values'"|
06/04/2022 18:13:17|INFO    |root                            |Throttling opensubtitlescom for 24 hours, until 22/04/07 18:13, because of: DownloadLimitExceeded. Exception info: 'Daily download limit reached
'|

**To Reproduce**
* Run Bazarr latest Nightly  with Python 3.10.2 from source
* Add supersubtitles/subscenter as provider
* Try to fetch any subs

**Expected behavior**
Get subs

**Software (please complete the following information):**
 - Bazarr: 1.0.4-beta.20
 - OS: Windows 10

**Comment by vitiko98** [comment]
Could you attach a debug log? To see where the faulty line of code is.

**Comment by polt13** [comment]
I tried to reproduce the issue today regarding the missing attribute, but I can only trigger it when searching for multiple episodes at the same time and all I've managed to get is 06/04/2022 18:12:49|INFO |root |Throttling supersubtitles for 10 minutes, until 22/04/06 18:22, because of: AttributeError. Exception info: "'list' object has no attribute 'values'"|
Which is not helpful but I can't get it to show more info

**Comment by polt13** [comment]
I actually found this from the console logging (I can't see it from the log directly for some reason):

`2022-04-07 23:06:21,181 - root                             (6498) :  INFO (get_providers:319) - Using supersubtitles again after 10 minutes, (disabled because: AttributeError)`

**Comment by vitiko98** [comment]
Thanks for the report. It should be fixed on upcoming beta. 

P.S. It looks like you don't have debug logging enabled (Settings - General - Logging)
