### ISSUE TITLE
Opensubtitles doesn't find episodes subtitles

### ISSUE THREAD

**Issue by so1ar** [morpheus65535/bazarr#1793]
**Describe the bug**
Opensubtitles can find movies subtitles but cannot find episodes subtitles.

**To Reproduce**
1. Enable debug logging;
2. Go to series and manual search for an episode's subtitls;
3. No results from opensubtitles;
4. In the logs there is an eorr `Skipping discarded provider 'opensubtitles' ` ;
5. Go to movies and manual search for a movie's subtitles;
6. There are some results from opensubtitles.

**Expected behavior**
Opensubtitles can find episodes subtitles.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr Version 1.0.3
 - Sonarr Version 3.0.7.1477
 - Radarr Version 4.0.5.5981
 - Operating System Linux-5.15.28-1-MANJARO-ARM-RPI-aarch64-with-glibc2.35
 - Python Version 3.10.2
**Additional context**

**Comment by halali** [comment]
Provide debug log with mentioned error

**Comment by so1ar** [comment]
> Provide debug log with mentioned error

[bazarr.log](https://github.com/morpheus65535/bazarr/files/8440730/bazarr.log)

**Comment by so1ar** [comment]
I rebooted the system and tried it again, find out opensubtitles can search episodes subtitles just fine. Not sure what's going wrong, but it works now.
