### ISSUE TITLE
Translating out-sync

### ISSUE THREAD

**Issue by resuarez** [morpheus65535/bazarr#1794]
**Describe the bug**
Using the translation tool generates a subtitle with jumps in the time of the subtitle.

In the image, left side is the original and the right is the translation.  The 144 subtitle is correct, but the 145 appears empty in the translation.  But, the 146 contains the translation for the 145 subtitle.  Then, the out-sync starts.

**To Reproduce**
1. Go to Serie
2. Click on Tool button
3. Select the original subtitle
4. Click arrow down
5. Click Translate
6. Select the language to translate 

**Expected behavior**
Translated subtitle in sync with the original

**Screenshots**
![image](https://user-images.githubusercontent.com/15803627/162418487-3665e223-ee1a-40a5-8320-dc168e97c8ca.png)

**Software (please complete the following information):**
 - Bazarr 1.0.3
 - OS: Unraide

**Comment by morpheus65535** [comment]
Fixed in 1.0.4-beta.2

**Comment by resuarez** [comment]
wow.. that it was fast, I imagine that it was already reported.  Sorry about that.

Any case, thank you for your work. It is really appreciated.

**Comment by morpheus65535** [comment]
No problem mate and thanks for the donation btw!
