### ISSUE TITLE
Error on click "Download wantted

### ISSUE THREAD

**Issue by Bresol** [morpheus65535/bazarr#180]
![unknown](https://user-images.githubusercontent.com/43558616/46809264-79384080-cd44-11e8-8196-93af07f479ae.png)

Version Bazarr Ver. 0.6.6.1

**Comment by morpheus65535** [comment]
Should be fixed in next version.

**Comment by morpheus65535** [comment]
Next version isn't release yet :-P

**Comment by morpheus65535** [comment]
0.6.6.3. I just want to fix a couple of things before releasing it. You can expect it in the next few days.

**Comment by irritatedcone** [comment]
Alright, good to know!
Have a good weekend ^^
