### ISSUE TITLE
Unable to edit Languages Profiles

### ISSUE THREAD

**Issue by kimfr** [morpheus65535/bazarr#1801]
**Describe the bug**
Unable to add/remove "ticks" under Languages Profiles.

**To Reproduce**
1. Go to 'Settings, Languages'
2. Click on 'wrench to edit existing Language Profile'
3. Scroll down to 'Enable/Disable Forced/HI/Exclude Audio'
4. You are not able to either add or remove "tick" for existing Languages.

**Expected behavior**
To be able to enable/disable Forced,HI or Exclude Audio

**Screenshots**
m.

**Software (please complete the following information):**
 - Bazarr: v1.0.4-beta.21

**Comment by LASER-Yi** [comment]
Should be fixed in the next upcoming beta

**Comment by kimfr** [comment]
Confirmed resolved v1.0.4-beta.22 - Thanks
