### ISSUE TITLE
Remember login when using 'form' auth

### ISSUE THREAD

**Issue by jansengorilla** [morpheus65535/bazarr#1803]
------------------------------

## Desired Behavior

Not having to enter my credentials every time i use the web page
## Current Behavior

Form login screen every time, with no option to remember details (like possible with similar method in radarr)
## Alternatives Considered

'Basic' popup screen not nice to use in apple portable environment (iOS/iPadOS)

**Comment by morpheus65535** [comment]
Please open a feature request on https://bazarr.featureupvote.com/.
