### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by AdamJacobMuller** [morpheus65535/bazarr#1804]
**Describe the bug**

**To Reproduce**
leave bazarr alone for a few days, check memory and CPU utilization on your server.

**Expected behavior**
Not having load at 200 with bazarr using 65gb of memory.

**Screenshots**
![CleanShot 2022-04-15 at 22 50 46@2x](https://user-images.githubusercontent.com/623767/163658680-73aaad14-ec6b-4afa-89bb-cac8b3d289fd.png)
![CleanShot 2022-04-15 at 22 51 26@2x](https://user-images.githubusercontent.com/623767/163658711-1ec3fc1e-fa42-4900-ba33-3867205f743e.png)

**Software (please complete the following information):**
Bazarr v1.0.3
Sonarr 3.0.7.1477
Radarr 4.1.0.6175
All running in docker on linux

**Additional context**
Sonarr also shows elevated CPU/Memory in lock-step with bazarr increases but i think it's just from Bazarr querying it a lot as stopping bazarr returns sonarr cpu to normal.

![CleanShot 2022-04-15 at 22 53 36@2x](https://user-images.githubusercontent.com/623767/163658786-e03576d3-0f68-4e74-be91-38a5d94946aa.png)
![CleanShot 2022-04-15 at 22 56 48@2x](https://user-images.githubusercontent.com/623767/163658876-edf2dd9c-9721-46b5-bbec-5f0fbcd724f6.png)

I tried to get debug logs but the web interface was totally non-functional to access. I enabled debug logs now and will get them if/when it recurs. What other information can I provide?

**Comment by halali** [comment]
You can find log file inside your data/logs directory.

Screenshot without blur all data will be better...

**Comment by AdamJacobMuller** [comment]
Hi,

![CleanShot 2022-04-16 at 12 38 36@2x](https://user-images.githubusercontent.com/623767/163683677-2cac820f-922d-40bf-8a37-5b2353b2299e.png)

The only thing I'm redacting from the screenshots are the names of other containers.

It generally takes a few days for the issue to recur as badly as it was yesterday (I have debug logs enabled now -- the issue before wasn't that I couldn't find logs, I couldn't reach the webui to enable debug logs).

Can I unicast you the logs? They do have some private information in them.

**Comment by halali** [comment]
All sensitive info in bazarr log is redacted. So you can feel free to post it there.

**Comment by morpheus65535** [comment]
@AdamJacobMuller what'S Bazarr doing during that time? Downloading subtitles? Syncing them? Doing a full indexing from disk? It could be useful to pinpoint the leaking module...

**Comment by AdamJacobMuller** [comment]
Hi,

Log from the past few days is here: https://adam.gs/bazarr.log.xz

Memory:
<img width="1350" alt="CleanShot 2022-04-18 at 18 59 43@2x" src="https://user-images.githubusercontent.com/623767/163890377-c20c86d4-5f94-46ae-bde4-3e416bda789a.png">

CPU:
<img width="1135" alt="CleanShot 2022-04-18 at 19 00 19@2x" src="https://user-images.githubusercontent.com/623767/163890420-ecd89eb0-e67c-4af5-93b3-dabc4cf8eaf2.png">


@morpheus65535 logs probably say, but, me perusing them doesn't really say much to me. I don't think my media library is large enough in any event to cause *that* much of an increase. Also worth noting that the web interface is entirely unusable when this happens, so, I can't look at tasks to see what's going on.

**Comment by morpheus65535** [comment]
Your log is full (almost 96000 occurence) of this: `BAZARR connection to Sonarr SignalR feed has been lost.`.

There's clearly something wrong with your Sonarr instance or the way you connetc to it. It too much unstable and Bazarr can't keep up and simply use all available ressources to keep reconnecting.

**Comment by AdamJacobMuller** [comment]
thanks for looking @morpheus65535.

I agree there's also something weird going on with Sonarr. It's just very difficult for me to understand what is causing the root of the issue. I started out looking at Bazarr simply because it was using proportionally more resources than Sonarr was.

Also seemed to me that even if Sonarr was badly misbehaving that Bazarr shouldn't try to use 60GB+ of memory :)

What seems to me to be happening is that Bazarr is making lots of connections to Sonarr and overwhelming it.

I can see some periods based on logs where Bazarr is making lots and lots of parallel connections to Sonarr. 

I just restarted again because I was seeing connection errors and when I did there were almost 500 open connections between Bazarr and Sonarr

I see a lot of lines like this:

```
bazarr                             | 2022-04-19 02:17:28,445 - urllib3.connectionpool           (7fd7855e0b38) :  DEBUG (connectionpool:1001) - Starting new HTTPS connection (1): sonarr.adam.gs:443                                                                                ]
bazarr                             | 2022-04-19 02:17:28,534 - urllib3.connectionpool           (7fd784899b38) :  DEBUG (connectionpool:1001) - Starting new HTTPS connection (1): sonarr.adam.gs:443
bazarr                             | 2022-04-19 02:17:28,734 - urllib3.connectionpool           (7fd7886c0b38) :  DEBUG (connectionpool:1001) - Starting new HTTPS connection (1): sonarr.adam.gs:443
bazarr                             | 2022-04-19 02:17:29,119 - urllib3.connectionpool           (7fd78ac87b38) :  DEBUG (connectionpool:1001) - Starting new HTTPS connection (1): sonarr.adam.gs:443
bazarr                             | 2022-04-19 02:17:29,287 - urllib3.connectionpool           (7fd784899b38) :  DEBUG (connectionpool:1001) - Starting new HTTPS connection (1): sonarr.adam.gs:443
bazarr                             | 2022-04-19 02:17:29,370 - urllib3.connectionpool           (7fd7855e0b38) :  DEBUG (connectionpool:1001) - Starting new HTTPS connection (1): sonarr.adam.gs:443
bazarr                             | 2022-04-19 02:17:29,451 - urllib3.connectionpool           (7fd7886c0b38) :  DEBUG (connectionpool:1001) - Starting new HTTPS connection (1): sonarr.adam.gs:443
bazarr                             | 2022-04-19 02:17:29,602 - urllib3.connectionpool           (7fd78ac87b38) :  DEBUG (connectionpool:1001) - Starting new HTTPS connection (1): sonarr.adam.gs:443
bazarr                             | 2022-04-19 02:17:29,921 - urllib3.connectionpool           (7fd7855e0b38) :  DEBUG (connectionpool:1001) - Starting new HTTPS connection (1): sonarr.adam.gs:443
bazarr                             | 2022-04-19 02:17:30,032 - urllib3.connectionpool           (7fd784899b38) :  DEBUG (connectionpool:1001) - Starting new HTTPS connection (1): sonarr.adam.gs:443
bazarr                             | 2022-04-19 02:17:30,034 - urllib3.connectionpool           (7fd7886c0b38) :  DEBUG (connectionpool:1001) - Starting new HTTPS connection (1): sonarr.adam.gs:443
bazarr                             | 2022-04-19 02:17:30,522 - urllib3.connectionpool           (7fd78ac87b38) :  DEBUG (connectionpool:1001) - Starting new HTTPS connection (1): sonarr.adam.gs:443
bazarr                             | 2022-04-19 02:17:30,650 - urllib3.connectionpool           (7fd7855e0b38) :  DEBUG (connectionpool:1001) - Starting new HTTPS connection (1): sonarr.adam.gs:443
bazarr                             | 2022-04-19 02:17:30,895 - urllib3.connectionpool           (7fd784899b38) :  DEBUG (connectionpool:1001) - Starting new HTTPS connection (1): sonarr.adam.gs:443
bazarr                             | 2022-04-19 02:17:31,009 - urllib3.connectionpool           (7fd78ac87b38) :  DEBUG (connectionpool:1001) - Starting new HTTPS connection (1): sonarr.adam.gs:443
bazarr                             | 2022-04-19 02:17:31,025 - urllib3.connectionpool           (7fd7886c0b38) :  DEBUG (connectionpool:1001) - Starting new HTTPS connection (1): sonarr.adam.gs:443
bazarr                             | 2022-04-19 02:17:31,160 - urllib3.connectionpool           (7fd7855e0b38) :  DEBUG (connectionpool:1001) - Starting new HTTPS connection (1): sonarr.adam.gs:443
bazarr                             | 2022-04-19 02:17:31,550 - urllib3.connectionpool           (7fd7886c0b38) :  DEBUG (connectionpool:1001) - Starting new HTTPS connection (1): sonarr.adam.gs:443
bazarr                             | 2022-04-19 02:17:31,589 - urllib3.connectionpool           (7fd784899b38) :  DEBUG (connectionpool:1001) - Starting new HTTPS connection (1): sonarr.adam.gs:443
```

in the log. 

Those aren't "connected, got disconnected, reconnecting" but just seems like Bazarr is making lots of parallel connections to Sonarr for some reason.

**Comment by morpheus65535** [comment]
Without the exact recipe to reproduce your issue, I don't see how I can find in the half-dozen Python modules used to use Sonarr SignalR feed which one is causing this issue.

Also, seeing you connect using port 443, are you trying to connect through a reverse proxy? We do not recommand that. Make sure Bazarr can talk to Sonarr directly. Also, are you using self-signed SSL certificate?

**Comment by AdamJacobMuller** [comment]
> you trying to connect through a reverse proxy? 
Yes

> are you using self-signed SSL certificate?
No.

> We do not recommand that.

I can try removing it, but, I ultimately after investigating (and discussing with the Sonarr people as well) I'm reasonably sure the inciting issue is sonarr becomes unresponsive which leads to bazarr having issues. While it would be great if bazarr handled that situation better, I don't think the root cause is with bazarr so I'll close this issue, but, feel free to reopen if you want me to grab more data on it like memory profiles or whatever.

**Comment by morpheus65535** [comment]
Ok thanks for the feedback. I'm clearly overloaded those days so I'll pass but thanks for offering. Don't hesitate if you have further issues!
