### ISSUE TITLE
Bazarr only detects movies in one root folder of Radarr

### ISSUE THREAD

**Issue by GitJamz** [morpheus65535/bazarr#1807]
Used Bazarr from Hotio previosuly, switched to Linuxserver due to Hotio not being updated.

Now in Linuxserver Bazarr, Sonarr works fine and detects everything. But Bazarr can only detect movies found in one of my two root folders from Radarr.

Looking in logs I see bunch of :

INFO (server:310) - emitting event "data" to all [/]

But that is only clue I get... I hae tried with path mapping but same problem. path mapping is not normally needed either for my setup to work, and as mentioned Sonarr works fine with same setup. And Previous versions of Bazarr has worked fine with the same config.

I have also tried using "development" tag with image so I'm on Bazarr 1.0.4-beta.24, Radarr is latest nightly: 4.2.0.6206

**Comment by morpheus65535** [comment]
> Used Bazarr from Hotio previosuly, switched to Linuxserver due to Hotio not being updated.

Hotio's image are updated faster than LSIO. You should make sure you didn't use a deprecated tag.

> Now in Linuxserver Bazarr, Sonarr works fine and detects everything. But Bazarr can only detect movies found in one of my two root folders from Radarr.

Bazarr does not "detect" movies, it show the movies provided by Radarr and only detect embedded and external subtitles for movies provided by Radarr.

> Looking in logs I see bunch of :
> 
> INFO (server:310) - emitting event "data" to all [/]

It's unrelated, those are events sent to your browser to refresh UI.

> But that is only clue I get... I hae tried with path mapping but same problem. path mapping is not normally needed either for my setup to work, and as mentioned Sonarr works fine with same setup. And Previous versions of Bazarr has worked fine with the same config.

If you can't see movies in Bazarr, why fiddling with path mapping? Path mapping is only useful to fix different paths to access the same file.

> I have also tried using "development" tag with image so I'm on Bazarr 1.0.4-beta.24, Radarr is latest nightly: 4.2.0.6206

All of this doesn't look like a bug but more like a configuration issue. Did you get by our Discord support channel? This is the proper way to get this fixed ASAP.
