### ISSUE TITLE
Created Systemd file for Ubuntu/Debian system

### ISSUE THREAD

**Issue by neuman1812** [morpheus65535/bazarr#181]
new user,  Love it so far.   Possible to add this to your wiki?

I noticed your wiki does not include directions for creating a systemd start file.  So I thought I might try and see if I can get one work.  Based on the information for sonarr/radarr/lidarr, this is how I installed it on my Raspberry pi.

git clone in to /opt/bazarr

Then create a bazarr.service file in /etc/systemd/system

In that file add 

```
[Unit]
Description=bazarr Daemon
After=syslog.target network.target

[Service]
User=pi  (or user name of choice)
Group=pi

Type=simple
ExecStart=/usr/bin/python /opt/bazarr/bazarr.py
TimeoutStopSec=20
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

This is tested and working on my Raspberry pi 3, running Debian Stretch and python 2.7.13

**Comment by xman0980** [comment]
Thanks for this. I was having probs getting it working. I kept forgetting the ```/usr/bin/python ``` portion.

**Comment by morpheus65535** [comment]
Thank you for sharing, I've added it to the wiki!

**Comment by edjalmobf** [comment]
I tried, but this aways appers "error: bazarr Default-Start contains no runlevels, aborting."
What I do?
