### ISSUE TITLE
Provider LegendasDivx is not working

### ISSUE THREAD

**Issue by andregdias** [morpheus65535/bazarr#1811]
**Describe the bug**
The provider LegendasDivx is not working, due to a SSL error.

`|HTTPSConnectionPool(host='www.legendasdivx.pt', port=443): Max retries exceeded with url: /forum/ucp.php?mode=login (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)'))), retrying in 5 seconds...|`

**Software (please complete the following information):**
Bazarr Version 1.0.3
Sonarr Version 3.0.7.1477
Radarr Version 4.1.0.6175
Operating System Windows-10-10.0.22000-SP0

**Comment by morpheus65535** [comment]
Seems to be ok now, could you test again? aybe they've renewed their SSL certicate or they had a temporary issue.

**Comment by andregdias** [comment]
I'm still getting the same. Is there something I should try on my end?

**Comment by morpheus65535** [comment]
Maybe you have PiHole or something else altering your web browsing?

**Comment by andregdias** [comment]
Hmm not really. I've also cleared cache and cookies but still no luck.

**Comment by andregdias** [comment]
Managed to sort it out. Followed these steps and it worked:
https://stackoverflow.com/a/69550170
