### ISSUE TITLE
Translated subtitle gets out of sync

### ISSUE THREAD

**Issue by Johan1976** [morpheus65535/bazarr#1813]
I'm on v1.0.3 installed as docker on unraid. 

Tried translation from English to Swedish a few times.

A bit into the translated subtitle one subtitle-line is blank and all the reaming lines are now one step ahead (all time stamps are intact but the wrong line). 

Tried Ambulance and Swedish line 153 is present with time but left blank and now Swedish line 154 is actually English line 153. 

Kind of same for Moonfall but now line 161 is blank. 

What other information do you need to track this?

**Comment by morpheus65535** [comment]
Fixed in v1.0.4-beta.2

**Comment by Johan1976** [comment]
Thanks alot!
