### ISSUE TITLE
Bazarr getting wrong movie from Radarr

### ISSUE THREAD

**Issue by altanir84** [morpheus65535/bazarr#1814]
**Describe the bug**

The movie The Batman is being referred to another batman movie file, on bazarr. But on raddar it shows fine.

![image](https://user-images.githubusercontent.com/52831296/165115391-3a81fbe3-66c8-4aa1-8194-b84f03ba66ec.png)

![image](https://user-images.githubusercontent.com/52831296/165115474-b0cdbfbc-109b-40a4-accc-b8f733a0515d.png)

**To Reproduce**
1. Go to raddar, get batman movie
2. go to bazarr and see if it is correct

**Expected behavior**
being able to get the right movie

**Screenshots**

**Software (please complete the following information):**
Bazarr Version
1.0.2
Sonarr Version
3.0.7.1506
Radarr Version
4.1.0.6175
Operating System
Linux-4.4.180+-aarch64-with-glibc2.26
Python Version
3.10.4

**Additional context**

**Comment by morpheus65535** [comment]
Looks like a sync issue. You can try this:

1. Remove the movie from Radarr
2. In Bazarr, go to System-->Tasks and run `Update Movie list from Radarr` task
3. Import the movie in Radarr

BTW you should update to 1.0.3.

**Comment by altanir84** [comment]
Deleted the movie, running update movie list. Will get back to you when it ends.

![image](https://user-images.githubusercontent.com/52831296/165118221-907eebaf-1c29-488c-9ab6-b27c393ec7cb.png)

I'm running the lastest version available for my system. My NAS does not support docker, so all I have is the package from synocommunity.

**Comment by morpheus65535** [comment]
> I'm running the lastest version available for my system. My NAS does not support docker, so all I have is the package from synocommunity.

You should open an issue to get the package updated. 1.0.2 has been released last December and I'm about to release 1.0.4.

**Comment by altanir84** [comment]
I'll try that.

So, removed both movies from Radarr and set bazarr to update movie list, but the issue still goes on. Both movies are still appearing on bazarr and the lastest batman is still being referred to the wrong file.

**Comment by morpheus65535** [comment]
I'll need the debug while you run this sequence. Doesn't make sense that it doesn't remove the orphaned movie and create the "new" one.

**Comment by altanir84** [comment]
[bazarr (2).log](https://github.com/morpheus65535/bazarr/files/8566831/bazarr.2.log)

**Comment by morpheus65535** [comment]
Radarr sync fails in during the process because it try to parse invalid metadata related to audio codec returned by Radarr. Check line 2488 of your log. I've added failsafe in 1.0.3 for this.

**Comment by morpheus65535** [comment]
Unless you can upgrade to 1.0.3 or greater, there's nothing else I can do here. I'll close it. Re-open it back if needed once you've updated.
