### ISSUE TITLE
Legendasdivx blacklist not blocking download

### ISSUE THREAD

**Issue by Ap0ph1s-W4ite** [morpheus65535/bazarr#1818]
**Describe the bug**
Blacklist not blocking download from Legendasdivx provider. After block the subtitle it seems to be blocked but after some time or next cycle the subtitle is downloaded again.
Looking for the Bazarr db and GUI there's a lack of information from DB.

**To Reproduce**
1. Go to 'History'
2. Click on 'Blaslist Button'
3. Wait next cycle to download
4. Subtitle downloaded again

**Expected behavior**
Block the download of blacklisted subtitles. Some subtitles have bag quality and this method could prevent them form being downloaded again or upgraded.

**Screenshots**
Bazarr Database and Blacklist
![image](https://user-images.githubusercontent.com/6775289/165397291-458a9f21-f3c6-4788-a11f-2f86658946cb.png)
![image](https://user-images.githubusercontent.com/6775289/165397313-44232556-ab66-4b8c-9327-1295722bec57.png)

Bazarr Database .db-wal
![image](https://user-images.githubusercontent.com/6775289/165397483-46371af9-ba33-44ab-b3d3-257d79d59664.png)

**Software (please complete the following information):**
 - Bazarr: v1.0.3

**Additional context**
As we talked on Discord, the `wal` file doesn't merge with the principal db.
Also, for Legendasdivx subtitle ID the link is composed by:
`https://www.legendasdivx.pt/modules.php?name=Downloads&d_op=getit&cat=<Random Cat>&lid=<Sub ID>`

Example:
`https://www.legendasdivx.pt/modules.php?name=Downloads&d_op=getit&cat=otvyoo&lid=385872`

**Comment by vitiko98** [comment]
Should be fixed in upcoming beta.
