### ISSUE TITLE
embeddedsubtitles "could not convert string to float: '26,673000000'"

### ISSUE THREAD

**Issue by nitschis** [morpheus65535/bazarr#1819]
No other information in the log.
It also says that the scan is finished, but I don't believe that this is true.

I will try to enable debug logging and running the scan again, will post the mediainfo output of the file as well.

```
27/04/2022 03:26:31|INFO    |root                            |Throttling embeddedsubtitles for 10 minutes, until 22/04/27 03:36, because of: ValueError. Exception info: "could not convert string to float: '26,673000000'"|
27/04/2022 03:26:31|INFO    |root                            |BAZARR All providers are throttled|
27/04/2022 03:26:31|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
```

 - Bazarr: v1.0.4-beta.26
 - OS: docker-image

**Comment by nitschis** [comment]
Luckily, my files were still cached, so the scan was much faster.

Here is the correct log

`27/04/2022 06:22:38|DEBUG   |root                            |BAZARR pools update elapsed time: 1.26ms|
27/04/2022 06:22:38|DEBUG   |root                            |BAZARR Searching subtitles for this file: /Movies/Movies/Turtles Forever (2009)/Turtles Forever (2009) - DVD Remux.mkv|
27/04/2022 06:22:38|DEBUG   |subzero.video                   |Parsing video: Turtles Forever (2009) - DVD Remux.mkv, hints: {'title': 'Turtles Forever', 'type': 'movie'}|
27/04/2022 06:22:38|INFO    |subliminal_patch.core           |Determining basic video properties for 'Turtles Forever (2009) - DVD Remux.mkv' in '/Movies/Movies/Turtles Forever (2009)'|
27/04/2022 06:22:38|DEBUG   |subliminal_patch.core           |GuessIt found: {
    "title": "Turtles Forever",
    "year": 2009,
    "source": "DVD",
    "other": "Remux",
    "container": "mkv",
    "type": "movie"
}|
27/04/2022 06:22:38|DEBUG   |subliminal_patch.core           |Size is 1828154373|
27/04/2022 06:22:38|DEBUG   |subliminal_patch.core           |Computed hashes {}|
27/04/2022 06:22:38|DEBUG   |root                            |Running refiner: database|
27/04/2022 06:22:38|DEBUG   |peewee                          |('SELECT "t1"."title", "t1"."year", "t1"."alternativeTitles", "t1"."format", "t1"."resolution", "t1"."video_codec", "t1"."audio_codec", "t1"."imdbId" FROM "table_movies" AS "t1" WHERE ("t1"."path" = ?)', ['/movies/Movies/Turtles Forever (2009)/Turtles Forever (2009) - DVD Remux.mkv'])|
27/04/2022 06:22:38|DEBUG   |root                            |Running refiner: ffprobe|
27/04/2022 06:22:38|DEBUG   |peewee                          |('SELECT "t1"."movie_file_id", "t1"."file_size" FROM "table_movies" AS "t1" WHERE ("t1"."path" = ?) LIMIT ? OFFSET ?', ['/movies/Movies/Turtles Forever (2009)/Turtles Forever (2009) - DVD Remux.mkv', 1, 0])|
27/04/2022 06:22:38|DEBUG   |peewee                          |('SELECT "t1"."ffprobe_cache" FROM "table_movies" AS "t1" WHERE ("t1"."path" = ?) LIMIT ? OFFSET ?', ['/movies/Movies/Turtles Forever (2009)/Turtles Forever (2009) - DVD Remux.mkv', 1, 0])|
27/04/2022 06:22:38|DEBUG   |root                            |FFprobe found: {'title': 'title_t00', 'path': '/Movies/Movies/Turtles Forever (2009)/Turtles Forever (2009) - DVD Remux.mkv', 'duration': datetime.timedelta(seconds=4355, microseconds=762000), 'size': 1828154373, 'bit_rate': 3357675, 'container': 'mkv', 'video': [{'id': 0, 'width': 720, 'height': 364, 'scan_type': 'Progressive', 'aspect_ratio': Decimal('1.758'), 'pixel_aspect_ratio': Decimal('0.889'), 'resolution': '480p', 'frame_rate': Decimal('23.976'), 'bit_depth': 8, 'codec': 'H.264', 'profile': 'High', 'default': True}], 'audio': [{'id': 1, 'name': 'Stereo', 'language': <Language [en]>, 'codec': 'AC-3', 'channels_count': 2, 'channels': '2.0', 'bit_rate': 192000, 'sampling_rate': 48000, 'default': True}], 'subtitle': [{'id': 2, 'language': <Language [en]>, 'format': 'ASS'}], 'provider': {'name': 'ffmpeg', 'version': {'/usr/bin/ffprobe': 'v4.4.1'}}}|
27/04/2022 06:22:38|DEBUG   |root                            |BAZARR is using these video object properties: {'name': '/Movies/Movies/Turtles Forever (2009)/Turtles Forever (2009) - DVD Remux.mkv', 'source': 'DVD', 'release_group': None, 'resolution': '480p', 'video_codec': 'H.264', 'audio_codec': 'Dolby Digital', 'imdb_id': 'tt1543920', 'hashes': {}, 'size': 1828154373, 'subtitle_languages': set(), 'original_name': 'Turtles Forever (2009) - DVD Remux.mkv', 'plexapi_metadata': {}, 'hints': {'title': 'Turtles Forever', 'type': 'movie', 'single_value': True, 'expected_title': ['Turtles Forever']}, 'audio_languages': {'eng'}, 'external_subtitle_languages': set(), 'streaming_service': None, 'edition': None, 'original_path': '/Movies/Movies/Turtles Forever (2009)/Turtles Forever (2009) - DVD Remux.mkv', 'title': 'Turtles Forever', 'year': 2009, 'alternative_titles': ['TMNT: Turtles Forever', 'Teenage Mutant Ninja Turtles: Turtles Forever'], 'used_scene_name': False, 'fps': Decimal('23.976')}|
27/04/2022 06:22:38|INFO    |subliminal_patch.core_persistent|Downloading best subtitles for <Movie ['Turtles Forever', 2009]>|
27/04/2022 06:22:38|INFO    |subliminal_patch.core           |Listing subtitles with provider 'embeddedsubtitles' and languages {<Language [en]>, <Language [de]>}|
27/04/2022 06:22:38|ERROR   |subliminal_patch.core           |Unexpected error in provider 'embeddedsubtitles': Traceback (most recent call last):  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 241, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/embeddedsubtitles.py", line 170, in list_subtitles    return self.query(  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/embeddedsubtitles.py", line 114, in query    streams = filter(_check_allowed_extensions, video.get_subtitles())  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/embeddedsubtitles.py", line 232, in get_subtitles    return super().get_subtitles(*args, **kwargs)  File "/app/bazarr/bin/bazarr/../libs/fese/__init__.py", line 237, in get_subtitles    subs.append(FFprobeSubtitleStream(stream))  File "/app/bazarr/bin/bazarr/../libs/fese/__init__.py", line 141, in __init__    self.duration = float(s) + float(m) * 60 + float(h) * 60 * 60ValueError: could not convert string to float: '26,673000000'|Traceback (most recent call last):  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 241, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/embeddedsubtitles.py", line 170, in list_subtitles    return self.query(  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/embeddedsubtitles.py", line 114, in query    streams = filter(_check_allowed_extensions, video.get_subtitles())  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/embeddedsubtitles.py", line 232, in get_subtitles    return super().get_subtitles(*args, **kwargs)  File "/app/bazarr/bin/bazarr/../libs/fese/__init__.py", line 237, in get_subtitles    subs.append(FFprobeSubtitleStream(stream))  File "/app/bazarr/bin/bazarr/../libs/fese/__init__.py", line 141, in __init__    self.duration = float(s) + float(m) * 60 + float(h) * 60 * 60ValueError: could not convert string to float: '26,673000000'|
27/04/2022 06:22:38|INFO    |root                            |Throttling embeddedsubtitles for 10 minutes, until 22/04/27 06:32, because of: ValueError. Exception info: "could not convert string to float: '26,673000000'"|
27/04/2022 06:22:38|INFO    |socketio.server                 |emitting event "data" to all [/]|
27/04/2022 06:22:38|INFO    |engineio.server                 |YUUaoaiI6SlngX2jAAAE: Sending packet MESSAGE data 2["data",{"type":"badges","action":"update","payload":null}]|
27/04/2022 06:22:38|INFO    |subliminal_patch.core           |Discarding provider embeddedsubtitles|
27/04/2022 06:22:38|INFO    |subliminal_patch.core_persistent|Downloaded 0 subtitle(s)|
27/04/2022 06:22:38|DEBUG   |root                            |BAZARR No Subtitles were found for this file: /Movies/Movies/Turtles Forever (2009)/Turtles Forever (2009) - DVD Remux.mkv|
27/04/2022 06:22:38|INFO    |socketio.server                 |emitting event "data" to all [/]|
27/04/2022 06:22:38|INFO    |engineio.server                 |YUUaoaiI6SlngX2jAAAE: Sending packet MESSAGE data 2["data",{"type":"progress","action":"update","payload":{"id":"wanted_movies_progress","header":"Searching subtitles...","name":"The Shawshank Redemption","value":834,"count":3020}}]|
27/04/2022 06:22:38|DEBUG   |root                            |Not using embeddedsubtitles until 22/04/27 06:32, because of: ValueError|
27/04/2022 06:22:38|INFO    |root                            |BAZARR All providers are throttled|
27/04/2022 06:22:38|INFO    |socketio.server                 |emitting event "data" to all [/]|
27/04/2022 06:22:38|INFO    |engineio.server                 |YUUaoaiI6SlngX2jAAAE: Sending packet MESSAGE data 2["data",{"type":"progress","action":"delete","payload":"wanted_movies_progress"}]|
27/04/2022 06:22:38|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
27/04/2022 06:22:38|INFO    |apscheduler.executors.default   |Job "Search for wanted Movies Subtitles (trigger: interval[1 day, 0:00:00], next run at: 2022-04-28 06:17:27 CEST)" executed successfully|
27/04/2022 06:22:38|INFO    |socketio.server                 |emitting event "data" to all [/]|
27/04/2022 06:22:38|INFO    |engineio.server                 |YUUaoaiI6SlngX2jAAAE: Sending packet MESSAGE data 2["data",{"type":"task","action":"update","payload":null}]|
27/04/2022 06:22:39|DEBUG   |peewee                          |('SELECT COUNT(1) FROM (SELECT 1 FROM "table_episodes" AS "t1" INNER JOIN "table_shows" AS "t2" ON ("t1"."sonarrSeriesId" = "t2"."sonarrSeriesId") WHERE (("t1"."missing_subtitles" IS NOT ?) AND ("t1"."missing_subtitles" != ?))) AS "_wrapped"', [None, '[]'])|
27/04/2022 06:22:39|DEBUG   |peewee                          |('SELECT COUNT(1) FROM (SELECT 1 FROM "table_movies" AS "t1" WHERE (("t1"."missing_subtitles" IS NOT ?) AND ("t1"."missing_subtitles" != ?))) AS "_wrapped"', [None, '[]'])|
27/04/2022 06:22:39|DEBUG   |peewee                          |('SELECT "t1"."path", "t1"."accessible", "t1"."error" FROM "table_movies_rootfolder" AS "t1" WHERE ("t1"."accessible" = ?)', [0])|
27/04/2022 06:23:01|INFO    |engineio.server                 |YUUaoaiI6SlngX2jAAAE: Sending packet PING data None|
27/04/2022 06:23:01|INFO    |engineio.server                 |YUUaoaiI6SlngX2jAAAE: Received packet PONG data |
27/04/2022 06:23:06|DEBUG   |root                            |BAZARR got this Sonarr version from its API: |
27/04/2022 06:23:06|DEBUG   |peewee                          |('SELECT "t1"."path", "t1"."accessible", "t1"."error" FROM "table_movies_rootfolder" AS "t1" WHERE ("t1"."accessible" = ?)', [0])|
27/04/2022 06:23:06|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): radarr:7878|
27/04/2022 06:23:06|DEBUG   |urllib3.connectionpool          |http://radarr:7878 "GET /radarr/api/system/status?apikey=(removed) HTTP/1.1" 404 0|
27/04/2022 06:23:06|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): radarr:7878|
27/04/2022 06:23:06|DEBUG   |urllib3.connectionpool          |http://radarr:7878 "GET /radarr/api/v3/system/status?apikey=(removed) HTTP/1.1" 200 None|
27/04/2022 06:23:06|DEBUG   |root                            |BAZARR got this Radarr version from its API: 4.1.0.6175|`


Mediainfo:

`Format                                   : Matroska
Format version                           : Version 4
File size                                : 1.70 GiB
Duration                                 : 1 h 12 min
Overall bit rate                         : 3 358 kb/s
Movie name                               : title_t00
Encoded date                             : UTC 2019-01-22 21:01:59
Writing application                      : HandBrake 1.2.0 2019010200
Writing library                          : Lavf58.20.100
ErrorDetectionType                       : Per level 1

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 5 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 5 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Bit rate                                 : 3 099 kb/s
Width                                    : 720 pixels
Height                                   : 364 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Writing library                          : x264 core 155 r2917 0a84d98
Encoding settings                        : cabac=1 / ref=5 / deblock=1:0:0 / analyse=0x3:0x133 / me=umh / subme=9 / psy=1 / psy_rd=1,00:0,00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=11 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=5 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=240 / keyint_min=24 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=crf / mbtree=1 / crf=10,0 / qcomp=0,60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=25000 / vbv_bufsize=31250 / crf_max=0,0 / nal_hrd=none / filler=0 / ip_ratio=1,40 / aq=1:1,00
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.601 NTSC
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.601
DURATION                                 : 01:12:35,762000000

Audio
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 1 h 12 min
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 99.7 MiB (6%)
Title                                    : Stereo
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No
DURATION                                 : 01:12:35,264000000

Text
ID                                       : 3
Format                                   : ASS
Codec ID                                 : S_TEXT/ASS
Codec ID/Info                            : Advanced Sub Station Alpha
Compression mode                         : Lossless
Language                                 : English
Default                                  : No
Forced                                   : No
DURATION                                 : 01:12:26,673000000

Menu
00:00:00.000                             : :Chapter 1
00:10:52.761                             : :Chapter 2
00:18:53.691                             : :Chapter 3
00:25:16.699                             : :Chapter 4
00:32:37.865                             : :Chapter 5
00:43:17.137                             : :Chapter 6
00:50:26.733                             : :Chapter 7
00:56:39.739                             : :Chapter 8
01:09:00.947                             : :Chapter 9
`

**Comment by vitiko98** [comment]
Fixed in upcoming beta. Thanks!
