### ISSUE TITLE
Opensubtitles.org doesn't work due to regional restrictions

### ISSUE THREAD

**Issue by mikecodre** [morpheus65535/bazarr#1824]
**Describe the bug**
It searches for a few seconds and stops, doesn't download anything. I know the subs exist for both languages, I've found them manually.

**To Reproduce**
1. Have only opensubtitles.org provider enabled
2. Go to a wanted movie and search with the manual or automated way

**Expected behavior**
Find and download subtitles

**Software (please complete the following information):**
 - Bazarr: 1.0.5-beta.0
 - Radarr version 4.1.0.6175
 - Sonarr version 3.0.8.1507
 - OS: Windows-10-10.0.19043-SP0

**Additional context**
I live in Greece, the edpi_block means my isp, I think, has blocked the connection even though I can access and use the site manually without any issues.
Debug logs for manual and automatic search of specific movie:
[opensubtitlesorg.log](https://github.com/morpheus65535/bazarr/files/8604972/opensubtitlesorg.log)
[opensubtitlesorg_manual.log](https://github.com/morpheus65535/bazarr/files/8604973/opensubtitlesorg_manual.log)

**Comment by morpheus65535** [comment]
Try to enable SSL and restart Bazarr.

**Comment by mikecodre** [comment]
[bazarr (7).log](https://github.com/morpheus65535/bazarr/files/8605345/bazarr.7.log)
I did both and the result is the same.


> Try to enable SSL and restart Bazarr.

**Comment by morpheus65535** [comment]
Regional blocking by internet provider DNS. Use another DNS server or use hosts file.
