### ISSUE TITLE
translation tasks/subtitles do not show in history

### ISSUE THREAD

**Issue by rmichelena** [morpheus65535/bazarr#1827]
Bazarr 1.0.4
when translating a subtitle, that should appear in "history" the same way downloads and syncs appear

**Comment by morpheus65535** [comment]
@LASER-Yi could we add `Translated` to your new history views? It would be action `6`. I'll do the backend part once we merge your branch to dev.

**Comment by LASER-Yi** [comment]
> @LASER-Yi could we add `Translated` to your new history views? It would be action `6`. I'll do the backend part once we merge your branch to dev.

Got it

**Comment by LASER-Yi** [comment]
> @LASER-Yi any news on that one?

Icon is added in the latest commit. Your turn now ;)

**Comment by morpheus65535** [comment]
Should be available in upcoming beta. Please test and confirm.
