### ISSUE TITLE
sync events should always appear in history after the corresponding download event

### ISSUE THREAD

**Issue by rmichelena** [morpheus65535/bazarr#1828]
Bazarr 1.0.4
obviously Bazarr first downloads a sub and then syncs it
in history, sometimes it's shown that way ; but some other times the sync is shown as if it had happened before the download

**Comment by morpheus65535** [comment]
Could you share an exemple and send me your bazarr.db in private on Discord?

**Comment by rmichelena** [comment]
<img width="1847" alt="Screen Shot 2022-05-06 at 13 50 49" src="https://user-images.githubusercontent.com/77797875/167692205-41b4c276-cf4d-4b7b-97b0-1d4ed0c72075.png">

**Comment by rmichelena** [comment]
not an isolated event, happens every day

**Comment by rmichelena** [comment]
sent you the db via discord

**Comment by morpheus65535** [comment]
@vitiko98 seems to be a consequence of generate_subtitles() that call process_subtitle() before episode_download_subtitles() been able to call history_log(). Any thoughs about this one?

It should always act the same (sync then download) but it seems to be changing. Maybe a consequence of yield?

**Comment by morpheus65535** [comment]
@vitiko98 any news on that one?

**Comment by vitiko98** [comment]
Still could't reproduce :/. We'll re-open if the issue persists.

**Comment by rmichelena** [comment]
Still present in 1.1.0 ... will try 1.1.1
Might have to do with the fact that the media is remote (google drive), which makes sub sync probably slower than in your environment.
