### ISSUE TITLE
Support `unar`

### ISSUE THREAD

**Issue by alexreg** [morpheus65535/bazarr#1833]
The latest `rarfile` package has support for using the `unar` insterad of the `unrar` program. I believe you already use this in the master branch. Could we add support to use unar, please? Ideally both as a fallback for `unrar`, as well as setting an environment variable, e.g. `UNRAR_TOOL=unrar` vs. `UNRAR_TOOL=urar`. This would be the final hurdle to overcome for getting my [macOS Homebrew formula](https://github.com/Homebrew/homebrew-core/pull/97444) accepted.

**Comment by morpheus65535** [comment]
I'm open to a PR dealing with this. Maybe having a command line argument to use unar. You have to deal with this in bazarr.init.init_binaries() but also in libs.subliminal_patch.providers.* and subzero. I would use an env variable to pass the unar usage boolean to those two modules.

**Comment by alexreg** [comment]
Sounds good. I looked at submitting a PR myself, and I fixed it in `init_binaries`, but wasn't sure the best way to patch subliminal & subzero. I agree, an env var is the best way to deal with this.

**Comment by morpheus65535** [comment]
I'll close this one while waiting for your PR.

**Comment by alexreg** [comment]
@morpheus65535 I think you misunderstood. I didn't know how to create a PR. I had no idea what to do with patching those dependencies. I mean, I could have done something very hacky, but would rather note!

**Comment by morpheus65535** [comment]
Should be good in upcoming beta.

**Comment by alexreg** [comment]
@morpheus65535 Thanks!
