### ISSUE TITLE
Apprise NTFY notification

### ISSUE THREAD

**Issue by SMAW** [morpheus65535/bazarr#1834]
**Describe the bug**
NTFY.sh not working with apprise API while it's working in another program that uses apprise and should work accourding to their website.

Proberbly it needs to be updated to the latest version

**To Reproduce**
1. Go to 'settings'
2. Go to 'notifications'
3. Click on ' + '
4. Scroll down to 'Apprise API
5. Fill in the correct vaulues
7. See error in the log "
  | Unparseable URL ntfys://username:password@domain/topic
"

**Expected behavior**
Recieving an notification on NTFY (Apprise)

**Software (please complete the following information):**
 - Bazarr: [v 1.0.4] Linuxserver.io container (latest)

**Comment by binwiederhier** [comment]
ntfy was just added to Apprise , so probably just have to update it.

**Comment by morpheus65535** [comment]
Will be available in upcoming beta release.

**Comment by BlastboomStrice** [comment]
Umm, am I the only one who currently encounters this issue?
Adding my ntfy server address `https://ntfy.aegean-paridae.ts.net/` and testing returns in the logs:
```log
Sep 23 12:25:17 bazarr bazarr[264]: 2026-09-23 12:25:17,821 - apprise                          (7180417ea6c0) :  ERROR (__init__:454) - Unparseable URL https://n...t/
Sep 23 12:25:17 bazarr bazarr[264]: 2026-09-23 12:25:17,821 - apprise                          (7180417ea6c0) :  ERROR (apprise:944) - There are no service(s) to notify
```

I'm running bazarr inside a nixos-container (systemd nspawn essentially), the other arr services seem to properly work with ntfy.
I also tried logging in the container and running `curl -d "Hi" https://ntfy.aegean-paridae.ts.net/bazarr` which worked.
I tried some variations to the address field in ntfy, they all failed:
```
https://ntfy.aegean-paridae.ts.net/
https://ntfy.aegean-paridae.ts.net
ntfy.aegean-paridae.ts.net
https://ntfy.aegean-paridae.ts.net/bazarr
https://ntfy.aegean-paridae.ts.net/bazarr/
```

System info:
- Bazarr Version: 1.6.0
- ntfy Version: 2.28.0
 - system: `"x86_64-linux"`
 - host os: `Linux 6.18.53, NixOS, 26.11 (Zokor), 26.11.20260922.6774f7b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Lix, like Nix) 2.95.2
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/cmjj2ss5jschdlmd9x0dgsdb9frrjgzp-lix-2.95.2/share`
 - nixpkgs: `/nix/store/zc9xvdvz642n6q20m04ixm30s98m6281-source`
