### ISSUE TITLE
Bazarr error "An internal error has occured in guessit"

### ISSUE THREAD

**Issue by sanderjacobsen** [morpheus65535/bazarr#1835]
**To Reproduce**
When searching for subtitles this error shows up in the logging. Result no subtitle.

**Software (please complete the following information):**
 - Bazarr: [v1.0.4]
 - Radarr version [v4.1.0.6175]
 - Sonarr version v3.0.8.1507]

**Error**
BAZARR Error (An internal error has occured in guessit.===================== Guessit Exception Report =====================version=3.4.3string=Turning Red (2022)/Turning.Red.2022.1080p.Bluray.DTS-HD.MA.7.1.X264-EVO.mkvoptions={'expected_title': ['OSS 117', 'This is Us', 'Turning Red'], 'allowed_countries': ['au', 'gb', 'us'], 'allowed_languages': ['ca', 'cs', 'de', 'en', 'es', 'fr', 'he', 'hi', 'hu', 'it', 'ja', 'ko', 'mul', 'nl', 'no', 'pl', 'pt', 'ro', 'ru', 'sv', 'te', 'uk', 'und'], 'advanced_config': {'common_words': ['ca', 'cat', 'de', 'he', 'it', 'no', 'por', 'rum', 'se', 'st', 'sub'], 'groups': {'starting': '([{', 'ending': ')]}'}, 'audio_codec': {'audio_codec': {'MP3': {'string': ['MP3', 'LAME'], 'regex': ['LAME(?:\\d)+-?(?:\\d)+']}, 'MP2': 'MP2', 'Dolby Digital': {'string': ['Dolby', 'DolbyDigital'], 'regex': ['Dolby-Digital', 'DD', 'AC3D?']}, 'Dolby Atmos': {'string': ['Atmos'], 'regex': ['Dolby-?Atmos']}, 'AAC': 'AAC', 'Dolby Digital Plus': ['EAC3', 'DDP', 'DD+'], 'FLAC': 'Flac', 'DTS': 'DTS', 'DTS-HD': {'regex': ['DTS-?HD', 'DTS(?=-?MA)'], 'conflict_solver': "lambda match, other: other if other.name == 'audio_codec' else '__default__'"}, 'Dolby TrueHD': {'regex': ['True-?HD']}, 'Opus': 'Opus', 'Vorbis': 'Vorbis', 'PCM': 'PCM', 'LPCM': 'LPCM'}, 'audio_channels': {'1.0': ['1ch', 'mono', 're:(1[\\W_]0(?:ch)?)(?=[^\\d]

**Comment by morpheus65535** [comment]
I need a full debug log while reproducing to see what's causing this issue.

**Comment by sanderjacobsen** [comment]
Very strange but the error is gone after the update to version v1.0.4.
