### ISSUE TITLE
Image broken in authentication window when using base URL

### ISSUE THREAD

**Issue by dglava** [morpheus65535/bazarr#1837]
**Describe the bug**
The bazarr logo isn't displayed on the login page when using the base URL feature (reverse proxy). It is still pointing to `static/logo128.png` instead of `base_url/static/logo128.png`.

**To Reproduce**
1. Enter a base URL (set up your reverse proxy)
2. Set Security->Authentication->Form
3. Open bazarr page
4. Logo isn't being displayed

**Expected behavior**
The logo should show up.

**Screenshots**
https://i.imgur.com/BwoMQAQ.png

**Software (please complete the following information):**
 - Bazarr: 1.0.4
 
I assume it's a similar fix to https://github.com/morpheus65535/bazarr/commit/967795e1a69a253a0743e16eaae9f90274075501. I tried changing the image src in https://github.com/morpheus65535/bazarr/blob/135bdf2d452ab3844aad71652b36c909d08aa4d5/frontend/src/pages/Authentication.tsx#L32 to ``{`${Environment.baseUrl}/static/logo128.png`}``, building it and replacing my frontend directory, but it didn't work. I have literally zero JS/Node.js knowledge though. I guess it should be easy to fix for someone with actual knowledge.

**Comment by halali** [comment]
Duplicate #1823
