### ISSUE TITLE
Issue not finding forced subtitles in opensubtitles.org - despite manually checking they exist.

### ISSUE THREAD

**Issue by mrpauljames** [morpheus65535/bazarr#1838]
This is a single example, I have bazarr set to download english forced subtitles. The specific movie I'm using for reference is The Thing (2011). The subtitles definitely exist on opensubtitles - https://www.opensubtitles.org/en/search/sublanguageid-eng/foreignpartsonly-on/idmovie-69658

However, despite setting match rating to 0, I can not get it to manually or automatically find any subtitles for this movie.

**Expected behavior**
Bazarr to find the correct forced subtitles for the movie match and provide the ability to download those subtitles.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: v1.0.4
 - Radarr: v4.1.0.6175
 - OS: Unraid 6.9.2 (Docker - container: lscr.io/linuxserver/bazarr:latest)

**Additional context**
Debug logs attached, latest entries are specific to the manual search and failure to find subtitles.
[bazarr (2).log](https://github.com/morpheus65535/bazarr/files/8663443/bazarr.2.log)
Thanks, any help is much apprecaited!

**Comment by morpheus65535** [comment]
Probably an improperly tagged subtitles on opensubtitles side. Bazarr can easily find English forced subtitles with this provider:
![image](https://user-images.githubusercontent.com/5130500/168052338-e10c8df9-f7b3-4ae9-9fc6-60f6c78d0abf.png)
Nothing I can do on my side.

**Comment by mrpauljames** [comment]
Not sure I understand. I've linked to the subtitles, which are all correctly tagged. This isn't just happening for a single movie but for all 1500.

**Comment by morpheus65535** [comment]
Show me your languages profile definition.

**Comment by morpheus65535** [comment]
I guess I can reproduce your issue. Forced subtitles are only returned on first search after Bazarr is started. I've asked @vitiko98 to take a look.

**Comment by morpheus65535** [comment]
Should be fixed now in latest beta. Can you test and confirm?

**Comment by morpheus65535** [comment]
No news, good news!
