### ISSUE TITLE
Not syncing new Sonarr episodes since v1.0.4

### ISSUE THREAD

**Issue by anonyme123** [morpheus65535/bazarr#1839]
**Describe the bug**
When importing a new episode in Sonarr, Bazarr does not pick up the change.

**To Reproduce**
1. Download a new episode via Sonarr
2. Bazarr doesn't list the new episode

**Expected behavior**
Bazarr lists the new episode as soon as it is imported in Sonarr

**Screenshots**

**Software (please complete the following information):**
 - Bazarr Version: 1.0.4
 - Package Version: v1.0.4-ls153 by [linuxserver.io](https://linuxserver.io)
 - Sonarr Version: 3.0.8.1507
 - Radarr Version: 4.1.0.6175
 - Operating System: Linux-3.10.0-1160.11.1.el7.x86_64-x86_64-with
 - Python Version: 3.9.5

**Additional context**

**Comment by morpheus65535** [comment]
Does the episode appear if you trigger the task `Sync episodes with Sonarr` in System-->Tasks?

Can you clear the log, enable debug logging, import an episode in Sonarr and provide the resulting log file content?

**Comment by anonyme123** [comment]
It does appear if I trigger the task Sync episodes with Sonarr in System-->Tasks

Here is the debug log file: [bazarr.log](https://github.com/morpheus65535/bazarr/files/8695528/bazarr.log)

**Comment by morpheus65535** [comment]
Then it could be an issue with the SignalR feed. Make sure debug log is enable, clear the log then restart Bazarr. Provide this new log please.

**Comment by anonyme123** [comment]
It works after a restart 🤦‍♂️ thanks for your help

**Comment by morpheus65535** [comment]
lol np! Happens t the best of us ;-)
