### ISSUE TITLE
Permissions (chmod) option doesn't result in correct permissions

### ISSUE THREAD

**Issue by trolley** [morpheus65535/bazarr#1841]
**Describe the bug**
I have the __Permission (chmod)__ option enabled with value `0644` but new files are being created with permissions `0666`.

**To Reproduce**
1. Go to __Settings__.
2. Click on __Subtitles__.
3. Scroll down to __Permissions (chmod)__.
4. Set value to `0644`.

**Expected behavior**
Newly downloaded files should have permissions `0644`.

An example of a correct file: `-rw-r--r-- 1 user user 128023 Nov  9  2021 ./Ready Player One (2018)/Ready Player One (2018).en.hi.srt`
An example of the actual permissions that are set: `-rw-rw-rw- 1 user user 62707 May 13 01:38 ./The Northman (2022)/The Northman (2022).en.hi.srt`

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 1.0.4
 - Radarr version: 3.2.2.5080
 - Sonarr version: 3.0.6.1342
 - OS: Alpine linux (linuxserver.io Docker image https://hub.docker.com/r/linuxserver/bazarr)

**Additional context**
N/A

**Comment by morpheus65535** [comment]
I've just tested out and it wrk as expected:
![image](https://user-images.githubusercontent.com/5130500/168476088-f86a5ad3-d196-4aff-a09a-c97d0183b1d2.png)
![image](https://user-images.githubusercontent.com/5130500/168476105-66138308-91eb-43d6-a629-c636721ae41f.png)

Probably some inheritance overriding Bazarr chmod or something forced on your mount point definition.

**Comment by trolley** [comment]
Ok thanks, I’ll investigate it more here.
