### ISSUE TITLE
Zimuku provider 404 Client Error

### ISSUE THREAD

**Issue by Cyriltra** [morpheus65535/bazarr#1842]
Hello,

since few days i have this error with Zimuku on all movies:

Throttling zimuku for 10 minutes, until 22/05/14 22:30, because of: HTTPError. Exception info: '404 Client Error: Not Found for url: http://zimuku.org/search?q=The%20Northman%202022'

But when browsing to the address, it seems to work fine. Any idea ?

Thank you

**Comment by morpheus65535** [comment]
Here's what's returned by this link (of course it a 404):
![image](https://user-images.githubusercontent.com/5130500/168476292-16c56ac4-c2eb-4160-8725-281f9cefbe14.png)

I can't even reach out the main page without solving this challenge using my up to date Chrome browser.

**Comment by Cyriltra** [comment]
i'm not an expert in coding, but this may help: https://github.com/taxigps/xbmc-addons-chinese/commit/d47e00506a6d65a4d57f0d6d38b0393dc40dcd06

@taxigps has updated is kodi addon to work with Zimuku captcha. You may found a solution for Bazarr in his code ?

**Comment by vitiko98** [comment]
> i'm not an expert in coding, but this may help: [taxigps/xbmc-addons-chinese@d47e005](https://github.com/taxigps/xbmc-addons-chinese/commit/d47e00506a6d65a4d57f0d6d38b0393dc40dcd06)


Can you confirm that this Kodi addon is working properly?

I tried applying the same logic and got no luck.

**Comment by Cyriltra** [comment]
Hello, indeed i test it afterward and it is not working. I also contacted the website, they dont offer any API...
So the only solution is to use a anti captcha solution for this provider

**Comment by morpheus65535** [comment]
Should be fixed in next release.
