### ISSUE TITLE
[Provider] Improved Addic7ed API

### ISSUE THREAD

**Issue by Belphemur** [morpheus65535/bazarr#1845]
Hello,

First, sorry for opening a bug for this, but I don't thing this should be a "feature" request, more of an improvement of an existing provider.

I've built a proper API for Addic7ed with caching of data and other retry method to reduce the amount of request they are receiving. Also found a way to not have to ask user to provide credentials.

The website is here:
https://www.gestdown.info

And API definition is here:
https://www.gestdown.info/Api

I would love to do a PR for this, unfortunately I don't have much Python knowledge.

ps: Source code of my project: https://github.com/Belphemur/AddictedProxy

**Comment by vitiko98** [comment]
We need to know if this proxy is ready for [thousands of queries from Bazarr users](https://wiki.bazarr.media/bazarr-stats/). I don't know what techniques you are using, but Addic7ed is already pretty restrictive.

I can start writing a provider for this though. I like the idea.

**Comment by Belphemur** [comment]
From your stats a week is around 12k request to addic7ed.
That make it around 70 request per hours.

The proxy should be able to handle that without issues. Worst case, I can spin more of them or increase the size of the VPS.

My proxy API has a limit of 15 request per seconds per ip to avoid having too much spam.

**Comment by vitiko98** [comment]
Let's do it and see how it goes

**Comment by vitiko98** [comment]
Done. It will be available in upcoming beta.

**Comment by Belphemur** [comment]
That's awesome :D
I put couple of comments on the code, nothing major.

Also do you think of the beta goes well this could replace the current addic7ed subtitles provider ?

The proxy should help reduce the load on their website since I store everything in a proper db and only query them if nothing can be found.

**Comment by vitiko98** [comment]
> Also do you think of the beta goes well this could replace the current addic7ed subtitles provider ?
> 
> The proxy should help reduce the load on their website since I store everything in a proper db and only query them if nothing can be found.

I don't think it's necessary to replace Addic7ed. Both providers can coexist. 

Not to mention that we don't know if Addic7ed admins will block your proxy at some point (I hope not!!)

**Comment by Belphemur** [comment]
They're going to have a hard time blocking it to be honest ^^'

But that's fair and also better to see how the load change from one service to the other.
