### ISSUE TITLE
Uploading HI sub track overrides normal sub track and is named "movie.en.srt" instead of "movie.en.hi.srt"

### ISSUE THREAD

**Issue by ianabney** [morpheus65535/bazarr#1846]
Description:
When trying to upload a normal srt sub track and a HI srt sub track, both track files end up being named "movie.en.srt" and so they override each other.

To Reproduce:
1. Go to a movie on Bazarr
2. Upload a normal sub track
3. Upload a HI sub track and mark it as HI

Expected Behavior:
Have the HI sub track uploaded and saved as "movie.en.hi.srt" and show up alongside the "movie.en.srt" track, instead of overriding it.

Software:
 - Bazarr: 1.0.3 package:v1.0.3-ls146 by [linuxserver.io](https://linuxserver.io)
 - Radarr version 4.1.0.6175
 - Sonarr version 3.0.7.1477
 - OS: docker running on PopOS 22.04

Additional context:
I have the Hearing-impaired subtitles extension setting set to ".hi" in the subtitle options

**Comment by morpheus65535** [comment]
No news, good news!
