### ISSUE TITLE
[Provider] Gestdown: Retry on status code 423 

### ISSUE THREAD

**Issue by Belphemur** [morpheus65535/bazarr#1848]
@vitiko98 As discussed, I've changed the status code in case the episode data isn't available yet. It will return a `423`.

**Comment by vitiko98** [comment]
How many retires do you suggest?

**Comment by Belphemur** [comment]
I'd say to wait around 30 seconds and retry 4 times.

If after that nothing comes, just let the app try again later on a normal schedule.

For future work, I use SignalR for a part of the application. If wanted this could be leveraged by bazarr to be notified when requested episodes have subtitles available.

Sent from Nine
________________________________

**Comment by vitiko98** [comment]
Done.

Thanks!
