### ISSUE TITLE
Bazarr won't find subtitle but Plex find it.

### ISSUE THREAD

**Issue by rickytin** [morpheus65535/bazarr#185]
First thanks for Bazarr.
I try to find a subtitle for a TV show with Bazarr and it didn't find it but then I try with the new subtitle finder in Plex and found one.
Plex use opensubtitles and I have opensubtitles as provider in Bazarr, why Plex found it and Bazarr didn't?

Another question, how often Bazarr do a search for subtitle?

Thanks, Ricky

**Comment by rickytin** [comment]
Thanks for the replay Morpheus.
The one that Plex found it's a match to the episode, that it's why I ask.

**Comment by morpheus65535** [comment]
That's quite strange. Did you enable scenename? If so, try to disable it.

**Comment by rickytin** [comment]
Yes If I disable it find the same that Plex found.

**Comment by morpheus65535** [comment]
What version of Bazarr are you using?

**Comment by rickytin** [comment]
v0.6.6.2

**Comment by morpheus65535** [comment]
So Bazarr found it using hash. Using scenename, we expect series name, season number and episode number match those returned by opensubtitles. If not, it is discarded. Probably what happen here.

**Comment by morpheus65535** [comment]
Test
