### ISSUE TITLE
Legendas.tv provider not working with TV Series

### ISSUE THREAD

**Issue by lucianor** [morpheus65535/bazarr#1852]
**Describe the bug**
Legendas.tv provider is not working and downloading any subtitles.

**To Reproduce**
1. Go to a Series that has a missing subtitle with pt-br language;
2. Click on Manual search or Auto Search

**Expected behavior**
Expected: Manual search - Subtitles found are shown
Auto Search - best fit subtitle is downloaded.

**Screenshots**
Logs attached. Screenshots of the site and bazarr attached.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/8780504/bazarr.log)

**Software (please complete the following information):**
Bazarr Version: 1.0.4
Package Version: v1.0.4-ls156 by [linuxserver.io](https://linuxserver.io)
Sonarr Version: 3.0.8.1507
Radarr Version: 4.1.0.6175
Operating System: Linux-5.15.0-33-generic-x86_64-with (Docker container)
Python Version: 3.9.5

**Additional context**
- Adaptive search is disabled
- Other providers such as Opensubtitles are working fine - but no pt-br subtitles either.

![legendastv](https://user-images.githubusercontent.com/4389998/170531701-b005f044-0da7-4155-8086-ad9fc97cb776.png)
![radarr01](https://user-images.githubusercontent.com/4389998/170531707-1f1701ce-c7ec-421e-994b-55376e5934d2.png)
![radarr02](https://user-images.githubusercontent.com/4389998/170531711-a2494f5b-570c-4a76-ad96-1e1a381377d1.png)

**Comment by morpheus65535** [comment]
Can you empty the config/cache directory, restart Bazarr and retry?

**Comment by lucianor** [comment]
Yeah, I figured that was the next step and stopped the container, deleted the config folder (backup the old one), and started it all over again. Just finished configuring Sonarr, Radarr and the LegendasTV provider. 
Once I configured Radarr, movies were loaded automatically. 
After configuring Sonarr, series were **NOT** loaded automatically.
Enabled Debug.
Run manually the task 'Update Series list from Sonarr' and 'Sync episodes lists from Sonarr" and they were loaded.
Then tried manually searching the subtitles for this specific episode:
26/05/2022 15:51:59|DEBUG   |subzero.video                   |Parsing video: Billions - S06E03 - STD.mkv, hints: {'title': 'Billions', 'type': 'episode'}|
26/05/2022 15:51:59|INFO    |subliminal_patch.core           |Determining basic video properties for 'Billions - S06E03 - STD.mkv' in '/tv/Billions/Season 6'|
26/05/2022 15:51:59|DEBUG   |subliminal_patch.core           |GuessIt found: {
    "title": "Billions",
    "season": 6,
    "episode": 3,
    "episode_title": "STD",
    "container": "mkv",
    "type": "episode"
}|
26/05/2022 15:51:59|DEBUG   |subliminal_patch.core           |Size is 2494351328|
26/05/2022 15:51:59|DEBUG   |subliminal_patch.core           |Computed hashes {}|
26/05/2022 15:51:59|DEBUG   |root                            |Running refiner: database|
26/05/2022 15:51:59|DEBUG   |peewee                          |('SELECT "t1"."title" AS "seriesTitle", "t2"."season", "t2"."episode", "t2"."title" AS "episodeTitle", "t1"."year", "t1"."tvdbId", "t1"."alternateTitles", "t2"."format", "t2"."resolution", "t2"."video_codec", "t2"."audio_codec", "t2"."path", "t1"."imdbId" FROM "table_episodes" AS "t2" INNER JOIN "table_shows" AS "t1" ON ("t2"."sonarrSeriesId" = "t1"."sonarrSeriesId") WHERE ("t2"."path" = ?)', ['/tv/Billions/Season 6/Billions - S06E03 - STD.mkv'])|
26/05/2022 15:51:59|DEBUG   |root                            |Running refiner: ffprobe|
26/05/2022 15:51:59|DEBUG   |peewee                          |('SELECT "t1"."episode_file_id", "t1"."file_size" FROM "table_episodes" AS "t1" WHERE ("t1"."path" = ?) LIMIT ? OFFSET ?', ['/tv/Billions/Season 6/Billions - S06E03 - STD.mkv', 1, 0])|
26/05/2022 15:51:59|DEBUG   |peewee                          |('SELECT "t1"."ffprobe_cache" FROM "table_episodes" AS "t1" WHERE ("t1"."path" = ?) LIMIT ? OFFSET ?', ['/tv/Billions/Season 6/Billions - S06E03 - STD.mkv', 1, 0])|
26/05/2022 15:51:59|DEBUG   |root                            |FFprobe found: {'path': '/tv/Billions/Season 6/Billions - S06E03 - STD.mkv', 'duration': datetime.timedelta(seconds=2907, microseconds=438000), 'size': 2494351328, 'bit_rate': 6863365, 'container': 'mkv', 'video': [{'id': 0, 'width': 1920, 'height': 1080, 'scan_type': 'Progressive', 'aspect_ratio': Decimal('1.778'), 'pixel_aspect_ratio': Decimal('1.0'), 'resolution': '1080p', 'frame_rate': Decimal('23.976'), 'bit_depth': 8, 'codec': 'H.264', 'profile': 'High', 'default': True}], 'audio': [{'id': 1, 'language': <Language [en]>, 'codec': 'E-AC-3', 'channels_count': 6, 'channels': '5.1', 'bit_rate': 640000, 'sampling_rate': 48000, 'default': True}], 'subtitle': [{'id': 2, 'name': 'English', 'language': <Language [en]>, 'format': 'SubRip'}], 'provider': {'name': 'ffmpeg', 'version': {'/usr/bin/ffprobe': 'v4.4.1'}}}|
26/05/2022 15:51:59|DEBUG   |root                            |BAZARR is using these video object properties: {'name': '/tv/Billions/Season 6/Billions - S06E03 - STD.mkv', 'source': 'HDTV', 'release_group': None, 'resolution': '1080p', 'video_codec': 'H.264', 'audio_codec': 'Dolby Digital Plus', 'imdb_id': None, 'hashes': {}, 'size': 2494351328, 'subtitle_languages': set(), 'original_name': 'Billions - S06E03 - STD.mkv', 'plexapi_metadata': {}, 'hints': {'title': 'Billions', 'type': 'episode', 'single_value': True, 'expected_title': ['Billions']}, 'audio_languages': {'eng'}, 'external_subtitle_languages': set(), 'streaming_service': None, 'edition': None, 'original_path': '/tv/Billions/Season 6/Billions - S06E03 - STD.mkv', 'series': 'Billions', 'season': 6, 'episode': 3, 'title': 'STD', 'year': None, 'original_series': True, 'tvdb_id': None, 'series_tvdb_id': 279536, 'series_imdb_id': 'tt4270492', 'alternative_series': ['Milliárdok nyomában'], 'used_scene_name': False, 'fps': Decimal('23.976')}|
26/05/2022 15:51:59|INFO    |subliminal_patch.core_persistent|Listing subtitles for <Episode ['Billions', 6x3]>|
26/05/2022 15:51:59|INFO    |subliminal_patch.core           |Listing subtitles with provider 'legendastv' and languages {<Language [pt-BR]>, <Language [en]>}|

Still can't find. But that might be a problem with this specific episode. So I tried others and same results.

**Comment by lucianor** [comment]
Another info.. I rebuilt my Sonarr recently and imported Series files from the disk. 
This probably led to less metadata being pulled for each episode which would explain why it does not match to the data available on site.
I'm getting results from legendas.tv on a series that has been downloaded entirely by Sonarr (Barry)

**Comment by morpheus65535** [comment]
Of course it may be the case. Keeping original naming is always better. I'm currently testing the same episode and will report result in a couple of minutes.

**Comment by morpheus65535** [comment]
Ok so basicaly I have the same behavior as you have. I've look into the code and we are using the search bar query to get show seasons (http://legendas.tv/legenda/sugestao/Billions). If subtitles aren't attached to a season, they won't appear in Bazarr search results.

**Comment by lucianor** [comment]
Thanks. Closing this. When Sonarr is lacking metadata for a specific video file, it's harder for indexing / matching with this specific provider (LegendasTV) that does not provide a rich API. This is a limitation of the provider and not a Bazarr limitation.
