### ISSUE TITLE
Exception on / [GET]

### ISSUE THREAD

**Issue by alexreg** [morpheus65535/bazarr#1855]
Following on from [this comment](https://github.com/morpheus65535/bazarr/pull/1854#issuecomment-1140148020) and the replies by @morpheus65535, I thought I'd create a separate issue, since that was piggy-backing on a PR inappropriately.

I have done `npm install` from within `frontend`, following the instructions [here](https://github.com/morpheus65535/bazarr/blob/master/frontend/README.md). However, I still get the following error when request pages in the browser.

```console
Bazarr starting...
2022-05-29 01:08:22,672 - root                             (104624580) :  INFO (server:39) - BAZARR is started and waiting for request on http://0.0.0.0:6767
2022-05-29 01:08:25,520 - app.app                          (28e873000) :  ERROR (app:1457) - Exception on / [GET]
```

This occurs on master branch, development branch, or a release, it seems.

**Comment by alexreg** [comment]
Okay, the exception is the following.

```console
EXCEPTION (<class 'jinja2.exceptions.TemplateNotFound'>, TemplateNotFound('index.html'), <traceback object at 0x17f6dbfc0>)
```

**Comment by alexreg** [comment]
Ah, `npm run build` fixes this. (The instructions in `Getting Started` do not seem to work, however.)

**Comment by morpheus65535** [comment]
@LASER-Yi could you take a look at frontend readme to make sure it's up-to-date? Thanks!

**Comment by LASER-Yi** [comment]
@morpheus65535 I will let Vite open the developing page after started
