### ISSUE TITLE
Opensubtitles (.org and .com) keep getting authentication errors.

### ISSUE THREAD

**Issue by Bono-Boy** [morpheus65535/bazarr#1861]
![image](https://user-images.githubusercontent.com/95429653/171403131-379c73eb-235b-42a5-ac4c-30c1631a5e55.png)
I checked login by entering both websites. There the same username and password is accepted.
I have attached the debug log.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/8814052/bazarr.log)

**Comment by morpheus65535** [comment]
Are you using your email as username?

**Comment by Bono-Boy** [comment]
For .org I use my email address.
For .com I use my username.

**Comment by Bono-Boy** [comment]
Will do it now. I let you know the outcome.
Thanks for the swift response. Bazarr is awesome by the way.

**Comment by Bono-Boy** [comment]
I did a reset of my username and password on both sides.
Changed username (email) for org to my username and added the new password. This is functioning now. :)
Added new username and password to .com  but still a problem.
Deletd the cache files. And now no error anymore.
I am a happy puppy again.
Thanks for the support!

**Comment by morpheus65535** [comment]
Thanks for reporting the resolution!
