### ISSUE TITLE
Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=Error%3A%20Request%20failed%20with%20status%20code%20504 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### ISSUE THREAD

**Issue by dannymichel** [morpheus65535/bazarr#1862]
When loading ``series/edit``

Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=Error%3A%20Request%20failed%20with%20status%20code%20504 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by morpheus65535** [comment]
What version of Bazarr?

**Comment by dannymichel** [comment]
> What version of Bazarr?

v1.0.42022-04-30MasterInstalled

**Comment by morpheus65535** [comment]
We wont fix this as 1.0.5 include a new UI. If the issue oersist with new UI, let us know and we'll take care of it.

**Comment by dannymichel** [comment]
> We wont fix this as 1.0.5 include a new UI. If the issue oersist with new UI, let us know and we'll take care of it.

I thought I was on the latest build. Am I missing something?

**Comment by morpheus65535** [comment]
@dannymichel 1.0.5 is still in beta. You can get it from development branch.
