### ISSUE TITLE
Legendasdvix Providers keeps getting ip blocked

### ISSUE THREAD

**Issue by jorgeelima** [morpheus65535/bazarr#1863]
Hello, 
Bazarr is still getting the issue for IP blocked in the legendasdvix provider

I've changed all the tasks to 24h to make the search happening only once a day but I'm still getting the IP blocked in the provider. 

Scheduler screenshots
![image](https://user-images.githubusercontent.com/79458010/171837688-aa5d2b84-dea9-4f4e-9589-0698ab88b505.png)
![image](https://user-images.githubusercontent.com/79458010/171837726-f9414a10-8aca-48ff-accd-48bff5f33289.png)

Is there anhything in the scheduler that I'm doing wrong? 

**Software (please complete the following information):**
 - Bazarr: [v 1.0.4]
 - Radarr version [e.g. v 0.2.0.0001]
 - Sonarr version [4.1.0.6175]
 - OS: [Synology DSM7-latest]

Thanks

**Comment by redglory** [comment]
You have a limit of 150 queries every day. If you exceed them, you'll be locked for 24h.

**Comment by jorgeelima** [comment]
Hello, 

The question is that I didn't performed any action. Bazarr should limit the search in this provider and something seems off

**Comment by morpheus65535** [comment]
Please share a log where I can see the throttling hapenning.

**Comment by jorgeelima** [comment]
Here it is
[Arquivo.zip](https://github.com/morpheus65535/bazarr/files/8883527/Arquivo.zip)

**Comment by jorgeelima** [comment]
You can find the logs from today and yesterday. If you need more, please let me know

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Please test and confirm.

**Comment by jorgeelima** [comment]
When will it be available the new release? How can I install betas from the Bazarr app? I can only. see the releases

**Comment by jorgeelima** [comment]
I'm sorry but I don't see. 
It's on the github page? or on the Bazzarr app?

![image](https://user-images.githubusercontent.com/79458010/174312986-0236189b-b8a0-438f-86c7-a37e307f685d.png)

The Bazarr is running on docker in DSM 7 (Synology) so how can I install the latest version?

**Comment by morpheus65535** [comment]
If you're using Docker, you must change the tag and it depends which docker image provider you use.

Other than that, you should be able to switch to development branch in Settings-->General. Once it's done, go to System-->Tasks and force an upgrade of Bazarr. Give it a couple of minutes and you should be running latest beta version.

**Comment by jorgeelima** [comment]
On Settings- General I don't see any development branch. 

But it's ok. I don't its gonna take long to have the new release public, is it?

**Comment by morpheus65535** [comment]
So you're probably using the DSM package that we do not support. You'll have to see withthe package provider.

This fix should get to master branch within 2 weeks.

**Comment by jorgeelima** [comment]
I'm using the linuxserver/bazarr

https://hub.docker.com/r/linuxserver/bazarr

**Comment by morpheus65535** [comment]
Ok in that case you can switch to `linuxserver/bazarr:development`.

**Comment by jorgeelima** [comment]
ok, but if you say it takes 2 weeks, then I can also wait. 

Thanks a lot for your work and for trying to fix the issue. If it doesn't fix with the new release, I'll let you know

**Comment by morpheus65535** [comment]
Nothing else to fix here, I'm closing this.
