### ISSUE TITLE
[Development][UI] Can't search in the provider list anymore

### ISSUE THREAD

**Issue by Belphemur** [morpheus65535/bazarr#1864]
**Describe the bug**
Before the redesign, we could search in the provider dropdown when adding a new one. Not anymore.

@LASER-Yi 

**To Reproduce**
1. Go to Settings > Providers
2. Click on `+`
3. Try to use the keyboard to search
4. nothing

**Expected behavior**
Be able to have an autocomplete on the dropdown as before

**Screenshots**
![image](https://user-images.githubusercontent.com/197810/171938831-4bdd1d03-c4de-4ad5-885c-ac2e669b63b8.png)

**Software (please complete the following information):**
 - Bazarr: [v1.0.5-beta.20](https://github.com/morpheus65535/bazarr/releases/tag/v1.0.5-beta.20)
 - OS: Linux

**Comment by LASER-Yi** [comment]
Should be fixed in the upcoming beta version
