### ISSUE TITLE
AttributeError. Exception info: "'NoneType' object has no attribute 'find_all'"

### ISSUE THREAD

**Issue by m33ts4k0z** [morpheus65535/bazarr#1866]
Hello,

addic7ed reports this error every time when bazarr tries to get a sub. I'm using anti-captcha.com but it doesnt seem to have received any challenges to solve.

I'm using Bazarr 1.0.4 on Unraid 6.10.2

**Comment by morpheus65535** [comment]
Show me a screenshot of addic7ed provider settings.

**Comment by m33ts4k0z** [comment]
I suppose it could have been temporarily.  It seems to work now. I will let you know if I get any more issues. Thanks :)
