### ISSUE TITLE
A forward slash is added for every keypress in sonarr base url entry

### ISSUE THREAD

**Issue by Dnkhatri** [morpheus65535/bazarr#1872]
**Describe the bug**
A forward slash is added for every keypress in sonarr base url entry

**To Reproduce**
Go to settings>sonarr try to type anything in the base url dialog

**Expected behavior**
forward slashes should not be added

**Screenshots**
![Capture](https://user-images.githubusercontent.com/7855682/173286193-96ad6cf7-3de8-4116-8fa8-a8b31edebb9d.PNG)

**Software (please complete the following information):**
 - Bazarr: 1.0.5-beta.25
 - Radarr version 3.0.8.1537
 - Sonarr version [e.g. v 2.0.0.0001]
 - OS: linux mint 20.3

**Comment by TylerVigario** [comment]
Also, can confirm this happens on Radarr settings page as well.

Here is the probable issue: https://github.com/morpheus65535/bazarr/blob/135bdf2d452ab3844aad71652b36c909d08aa4d5/frontend/src/pages/Settings/Sonarr/index.tsx#L55

**Comment by morpheus65535** [comment]
Fix confirmed to be working. I'll close this one.
