### ISSUE TITLE
Upload Button does not work

### ISSUE THREAD

**Issue by Dnkhatri** [morpheus65535/bazarr#1873]
**Describe the bug**
Upload Button does not work

**To Reproduce**
go to series page press upload button

**Expected behavior**
upload dialog should open

**Screenshots**

https://user-images.githubusercontent.com/7855682/173289811-8fc22cf2-11b8-45b8-bd3d-08f21f501676.mp4

**Software (please complete the following information):**
 - Bazarr: 1.0.5-beta.25
 - Radarr version 3.0.8.1537
 - Sonarr version [e.g. v 2.0.0.0001]
 - OS: linux mint 20.3

**Additional context**
this bug started since the new ui update a few beta versions ago

**Comment by Dnkhatri** [comment]
Btw apart from manual upload. I think a folder monitor provider should be added where bazaar searches a local folder to find subtitles

**Comment by morpheus65535** [comment]
> Btw apart from manual upload. I think a folder monitor provider should be added where bazaar searches a local folder to find subtitles

You can create a feature request for that one.

**Comment by morpheus65535** [comment]
@LASER-Yi could you take a look?

**Comment by LASER-Yi** [comment]
Should be fixed in the next beta version
