### ISSUE TITLE
BAZARR Error - An internal error has occured in guessit

### ISSUE THREAD

**Issue by BacchusFLT** [morpheus65535/bazarr#1876]
**Describe the bug**
Bazarr fetches subtitles for movies, but not Tv shows for me. My History -> Statistics shows nicely added movies but no TV shows. 

The setting is the same and access rights to my media (on a QNAOP NAS - TV shows accessed via T: and Movies via U: ) should also be the same. 

In the log I find a lot of issues such as these:

BAZARR Error (An internal error has occured in guessit.===================== Guessit Exception Report =====================version=3.4.3string=_TV\Doctor Who (1963)\Doctor Who - S23E13 - The Ultimate Foe (1).avioptions={'expected_title': ['OSS 117', 'This is Us', 'Doctor Who'], 'allowed_countries': ['au', 'gb', 'us'], 'allowed_languages': ['ca', 'cs', 'de', 'en', 'es', 'fr', 'he', 'hi', 'hu', 'it', 'ja', 'ko', 'mul', 'nl', 'no', 'pl', 'pt', 'ro', 'ru', 'sv', 'te', 'uk', 'und'], 'advanced_config': {'common_words': ['ca', 'cat', 'de', 'he', 'it', 'no', 'por', 'rum', 'se', 'st', 'sub'], 'groups': {'starting': '([{', 'ending': ')]}'}, 'audio_codec': {'audio_codec': {'MP3': {'string': ['MP3', 'LAME'], 'regex': ['LAME(?:\\d)+-?(?:\\d)+']}, 'MP2': 'MP2', 'Dolby Digital': {'string': ['Dolby', 'DolbyDigital'], 'regex': ['Dolby-Digital', 'DD', 'AC3D?']}, 'Dolby Atmos': {'string': ['Atmos'], 'regex': ['Dolby-?Atmos']}, 'AAC': 'AAC', 'Dolby Digital Plus': ['EAC3', 'DDP', 'DD+'], 'FLAC': 'Flac', 'DTS': 'DTS', 'DTS-HD': {'regex': ['DTS-?HD', 'DTS(?=-?MA)'], 'conflict_solver': "lambda match, other: other if other.name == 'audio_codec' else '__default__'"}, 'Dolby TrueHD': {'regex': ['True-?HD']}, 'Opus': 'Opus', 'Vorbis': 'Vorbis', 'PCM': 'PCM', 'LPCM': 'LPCM'}, 'audio_channels': {'1.0': ['1ch', 'mono', 're:(1[\\W_]0(?:ch)?)(?=[^\\d]

I do note that there is no delimiter between the filename and the options parameter. Is this just in the report or also in the command?

**To Reproduce**
The program scans my media and this happens in the process.

**Expected behavior**
Naturally that it fetches the subtitles which it can find.

**Screenshots**
The paste above should tell the story, but a snap to broaden the view.

![image](https://user-images.githubusercontent.com/28536010/173564371-9e64b9e7-2ac8-4356-baa6-2ccdb74a27d0.png)

**Software (please complete the following information):**
 - Bazarr: v 1.0.4
 - Radarr version 4.1.0.6175
 - Sonarr version 2.0.0.5344
 - OS: Windows 10
 
**Additional context**

**Comment by morpheus65535** [comment]
Duplicate #1858 ?

**Comment by BacchusFLT** [comment]
Looks very much the same, yes...

Den tis 14 juni 2022 21:58morpheus65535 ***@***.***> skrev:

**Comment by morpheus65535** [comment]
@BacchusFLT that's fine. The information you provided may help @vitiko98 during his debug. I will close it.

**Comment by vitiko98** [comment]
@BacchusFLT Please test with upcoming beta. #1858
