### ISSUE TITLE
Bazaar converts .ass subtitles to .srt on manual upload, despite Original Format ticked

### ISSUE THREAD

**Issue by tomthebotfly** [morpheus65535/bazarr#1879]
**Describe the bug**
Bazaar converts .ass/.ssa format subtitles into .srt subtitles when manually uploading from a computer despite "Original Format" being enabled in the language profile. This is not the case when downloading .ass subtitles from a provider (tested with OpenSubtitles.org), where the conversion does not occur.

**To Reproduce**
1. Enable "Original Format" in language profile
2. Manually upload a subtitle file (with the "Upload" button next to edit series and tools in the top right)
3. Select a .ass subtitle file and complete the upload
4. The subtitle file is converted to a .srt file

**Expected behavior**
The subtitle file should remain as a .ass/.ssa file format rather than be converted to .srt

**Screenshots**
![image](https://user-images.githubusercontent.com/64895167/174481769-6fcc4a21-8ae7-4eee-ad37-bfd13845f323.png)
![image](https://user-images.githubusercontent.com/64895167/174481774-fbec1d1a-e085-4ef9-971f-0045b69d90f1.png)
![image](https://user-images.githubusercontent.com/64895167/174481777-5462d838-2e87-4b3e-8786-8a8f439ed355.png)

**Software (please complete the following information):**
 - Bazarr: [v 1.0.4]
 - Sonarr version [v 3.0.8.1507]
 - OS: [Ultra.cc seedbox, some version of Linux]

**Additional context**
In the case that you *manually* add a .ass subtitle file to the video folder and rename it to the name of the video and then press "Scan Disk", Bazaar does not perform the conversion and recognises it as a subtitle file (but that would take ages to do individually)

**Comment by TylerVigario** [comment]
Looks like the issue stems from when saving the uploaded subtitle. It does not consider the "Use Original Format" language option. 
https://github.com/morpheus65535/bazarr/blob/135bdf2d452ab3844aad71652b36c909d08aa4d5/bazarr/get_subtitle/upload.py#L34-L67

The `original_format` variable is most likely available via the `lang_obj` variable.

I do not have a test environment available at the moment. I might set one up in the very-near future to help with issues on this project, if I find enough time.

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Can you test it and confirm please?

**Comment by morpheus65535** [comment]
In that case, we'll close this issue as my test are conclusive. Once 1.0.5 is released, let me know if you still have issues.
