### ISSUE TITLE
List index out of range - Searching for updates error

### ISSUE THREAD

**Issue by Gingey231** [morpheus65535/bazarr#188]
**Describe the bug**
While trying to search for all wanted subtitles, the following error appears:

**Title:** `Job "Search for wanted subtitles (trigger: interval[3:00:00], next run at: 2018-10-13 18:46:07 BST)" raised an exception`

**Error:**
`
Traceback (most recent call last):
 File "/app/bazarr/libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/get_subtitle.py", line 449, in wanted_search_missing_subtitles
  wanted_download_subtitles(episode[0])
 File "/app/bazarr/get_subtitle.py", line 375, in wanted_download_subtitles
  message = download_subtitle(path_replace(episode[0]), str(alpha3_from_alpha2(language)), episode[4], providers_list, providers_auth, str(episode[5]), \series\)
 File "/app/bazarr/get_subtitle.py", line 105, in download_subtitle
  downloaded_provider = result[0].provider_name
IndexError: list index out of range
`

**To Reproduce**
1. Search manually or allow the scheduler to search for updates
2. Sometimes will find a couple of subs, sometimes not.
3. See error.

**Expected behavior**
Expected to search for updates without error. Once error appears, searching stops and error continues until Bazarr is restarted.

**Screenshots**
N/A

**Software (please complete the following information):**
 - Bazarr: 0.6.6.2
 - Radarr version: 0.2.0.1120
 - Sonarr version: 2.0.0.5252
 - OS: Ubuntu 16.04 - Docker host - Docker version: 18.06.1-ce

**Additional context**
Only noticed this since 0.6.6.1.

**Comment by Gingey231** [comment]
Forgot to upload the log file :)

[bazarr (2).log](https://github.com/morpheus65535/bazarr/files/2475608/bazarr.2.log)

**Comment by halali** [comment]
this should be fixed in 3163b4dcf9301aeba7bf8130fdbde5aa355337de and will be in upcoming release 0.6.6.3
