### ISSUE TITLE
Subtitle syncing log output breaks docker logs

### ISSUE THREAD

**Issue by hugalafutro** [morpheus65535/bazarr#1883]
**Describe the bug**
Subtitle syncing log output "breaks" docker logs somehow. I first noticed it is completely missing from dozzle (https://github.com/amir20/dozzle) output with dozzle only displaying the timestamp and blank line, then I tried lazydocker (https://github.com/jesseduffield/lazydocker) where the sub sync output shows, but cuts off the date and timestamp lazydocker adds to each line. Finally using `docker compose logs -f bazarr` also shows the sub sync output, but breaks off the `name_of container  | timestamp | ` string from the start of the line.

**To Reproduce**
1. Sync any subtitle
2. Check docker logs in any of the ways described above
3. Observe the behaviour described above

**Expected behavior**
The sub sync log output should not affect docker log monitoring in any way and should retain any prefixes the monitoring tool adds to the log line.

**Screenshots**
The same log output in:
dozzle -
![image](https://user-images.githubusercontent.com/30209689/175802297-6fca7279-d77f-4c0c-ab9b-b3c8e5f10b6a.png)

lazydocker- 
![image](https://user-images.githubusercontent.com/30209689/175802337-2634c83b-44ed-4f46-a46a-c6c9c2be98a3.png)

docker compose logs -f output:
```
bazarr  | 2022-06-26 07:06:18,365 - root                             (7fb1e2b2fb38) :  INFO (get_providers:274) - Throttling supersubtitles for 10 minutes, until 22/06/26 07:16, because of: IndexError. Exception info: 'list index out of range'
100%|█████████▉| 4463.210666666667/4463.243 [00:32<00:00, 138.50it/s]
100%|█████████▉| 6810.176/6810.208 [00:45<00:00, 150.00it/s]

```

**Software (please complete the following information):**
- Bazarr Version 1.0.4
- Package Version v1.0.4-ls156 by [linuxserver.io](https://linuxserver.io)
- Sonarr Version 3.0.8.1507
- Radarr Version 4.1.0.6175
- Operating System Linux-5.15.0-40-generic-x86_64-with
- Python Version 3.9.5

**Additional context**
n/a

**Comment by morpheus65535** [comment]
Bazarr use ffsubsync for subtitles synchronization. ffsubsync rely on [tqdm](https://github.com/tqdm/tqdm) to display a progress bar to stdout. This is more a bug with tqdm than with Bazarr itself. You'll probably get the same issue if you install ffsubsync inside a generic Python docker container and sync a subtitles.
