### ISSUE TITLE
Sonarr & Radarr score slider not displaying the score

### ISSUE THREAD

**Issue by DJScias** [morpheus65535/bazarr#1893]
**Describe the bug**
The score slider for both the Sonarr & Radarr settings does not show the score amount on its tooltip, unlike the sliders in Subtitles. This makes it very hard to know what you're setting it at.

**To Reproduce**
1. Click on Settings > Sonarr/Radarr
2. Scroll down to `Options`
3. Hover over `Minimum Score`
4. Notice how instead of the score number, the tooltip says `Minimum Score`

**Expected behavior**
The tooltip displays the score number so you know what it is set on.

**Screenshots**
The sliders in `Subtitles`, which work as they should (96 tooltip):
![image](https://user-images.githubusercontent.com/439655/177040872-576ca5aa-f03f-49df-92c1-e4cf3f86debc.png)

The slider on Sonarr which just shows `Minimum Score`:
![image](https://user-images.githubusercontent.com/439655/177040884-2b2d6164-becc-43da-91cb-f5904e03029a.png)

The slider on Radarr which also just shows `Minimum Score`:
![image](https://user-images.githubusercontent.com/439655/177040895-1e57c899-e0f1-432a-972d-cf8a78f9697e.png)

**Software (please complete the following information):**
 - Bazarr: v1.1.0
 - Radarr version: 4.1.0.6175
 - Sonarr version: 3.0.8.1507
 - OS: Ubuntu 20.04

**Additional context**
N/A

**Comment by TRaSH-** [comment]
Good catch @LASER-Yi think this is your department ?
