### ISSUE TITLE
[Bug] Unicode issue

### ISSUE THREAD

**Issue by logicalshrapnel** [morpheus65535/bazarr#190]
**Describe the bug**
Unicode issue when handling folders with non-standard characters (such as Swedish)

**To Reproduce**
1. Go to IP:port/series
2. See error

**Expected behavior**

**Screenshots**
Error: 500 Internal Server Error
Sorry, the requested URL 'http://192.168.200.1:6767/series' caused an error:

Internal Server Error
Exception:
UnicodeEncodeError('ascii', u'/mnt/4TB/tvseries/V\xe4rldens s\xe4msta indier', 19, 20, 'ordinal not in range(128)')
Traceback:
Traceback (most recent call last):
  File "/home/bazaarUser/bazarr/libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/bazaarUser/bazarr/libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/bazaarUser/bazarr/bazarr.py", line 140, in wrapper
    return func(*a, **ka)
  File "/home/bazaarUser/bazarr/bazarr.py", line 291, in series
    output = template('series', __file__=__file__, bazarr_version=bazarr_version, rows=data, missing_subtitles_list=missing_subtitles_list, total_subtitles_list=total_subtitles_list, languages=languages, missing_count=missing_count, page=page, max_page=max_page, base_url=base_url, single_language=single_language, page_size=page_size)
  File "/home/bazaarUser/bazarr/libs/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/home/bazaarUser/bazarr/libs/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "/home/bazaarUser/bazarr/libs/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/home/bazaarUser/bazarr/views/series.tpl", line 75, in <module>
    %if os.path.isdir(row[2]):
  File "/usr/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 19: ordinal not in range(128)

**Software (please complete the following information):**
 - Bazarr: [0.6.6.3]
 - Sonarr version [2.0.0.5252]
 - OS: [Debian stretch]

**Other useful information**
Manually installed using git clone https://github.com/morpheus65535/bazarr.git
Series works fine in sonarr

**Comment by morpheus65535** [comment]
Are you able to open bazarr.db in a SQlite editor? I would like to know if the path is stored correctly in `table_shows` table.

**Comment by logicalshrapnel** [comment]
sqlite> select * from table_shows where tvdbid = 353670;
353670|Världens sämsta indier|/mnt/4TB/tvseries/Världens sämsta indier|['en', 'ja', 'sv']|0|19|||/MediaCover/19/fanart.jpg|English|världens sämsta indier

**Comment by pannal** [comment]
What's the output of `locale -v`?

**Comment by logicalshrapnel** [comment]
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by pannal** [comment]
Are you running behind a separate HTTPD? Is that `locale` output from the exact same shell bazarr runs in?

**Comment by pannal** [comment]
Can you try adding `LANG=en_US.UTF8` to `/etc/environment`?

**Comment by logicalshrapnel** [comment]
> Are you running behind a separate HTTPD? Is that `locale` output from the exact same shell bazarr runs in?

I think you are onto something. I'm starting it from /etc/init.d/bazaar and get this issue. When I start directly from my user it is working correctly.

**Content of /etc/init.d/bazaar**
### BEGIN INIT INFO
# Provides: Runs a Python script on startup
# Required-Start: BootPython start
# Required-Stop: BootPython stop
# Default-Start:  3 4 5
# Default-stop: 0  6
# Short-Description: Simple script to run python program at boot
# Description: Runs a python program at boot
### END INIT INFO

case "$1" in
start)
  echo "Starting Python"
  sudo -u bazaarUser python /home/marten/bazarr/bazarr.py
  ;;

*)
  echo "Usage: /etc/init.d/bazarr {start}"
  exit 1
  ;;
esac

exit 0

> Can you try adding LANG=en_US.UTF8 to /etc/environment?
That file is empty for me but I created it, added the line and restarted bazarr with no change.

**Comment by pannal** [comment]
Try adding `export LANG=en_US.UTF8` to the init script. 
You could also try to add bash to the sudo call, I think there are multiple ways to fix this.

**Comment by pannal** [comment]
`sudo -u user bash -c 'python bazaar.py'` might do the trick, if your default bash environment is properly configured.

**Comment by logicalshrapnel** [comment]
Your comment about same shell made me wonder why sonarr/radarr was working. While waiting to hear back I looked around on my own as well and managed to figure out how to use systemctl to start it instead instead and ran it that way. It seems that makes it run in a shell with correct locale.

> Try adding `export LANG=en_US.UTF-8` to the init script.

I found that suggestion on another page and tried it without success.

**My solution**
edit `/etc/systemd/system/bazaar.service`

Paste the following (with changes to user, group and path)
```
[Unit]
Description=bazarr Daemon
After=syslog.target network.target

[Service]
User=bazarrUser
Group=bazarrUser
Type=simple
ExecStart=/usr/bin/python [path-to-bazaar]/bazarr.py
TimeoutStopSec=20
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target

```
Then run `systemctl daemon-reload`
Then run  `sudo systemctl enable bazarr.service`
To try it run `sudo systemctrl start bazarr.service`

Thank you very much for the help, especially since it was a problem on my end! And thank you for making bazarr!

**Comment by morpheus65535** [comment]
That's pretty much what we have on the wiki. :-)
https://github.com/morpheus65535/bazarr/wiki/systemd-service-file-for-Debian-Ubuntu

It's a pleasure to give you Bazarr.

Thanks to @pannal for the debug session! I'll let you guys close the issue when you'll be ready.

**Comment by logicalshrapnel** [comment]
Eerily similar, I still don't understand why I didn't get it working the first time and went down the init.d road instead. Again, thanks @pannal for the assistance!
