### ISSUE TITLE
Search for Wanted Subtitles Wakes Disks

### ISSUE THREAD

**Issue by k29t59dh** [morpheus65535/bazarr#1900]
**Describe the bug**
My disks are awakened every 3 hours when the scheduled subtitle search task runs.

**Software (please complete the following information):**
 - Bazarr: v1.1.0 (via docker)
 - Radarr version 4.1.0.6175
 - Sonarr version 3.0.8.1507
 - OS: unRAID 6.10.3

**Additional context**
I've attached an inotify log in addition to the bazaar debug log. 
The disk activity begins at 20:50:47

[inotify.log.zip](https://github.com/morpheus65535/bazarr/files/9068178/inotify.log.zip)
[bazarr.log.zip](https://github.com/morpheus65535/bazarr/files/9068179/bazarr.log.zip)

**Comment by morpheus65535** [comment]
Sorry for the delay, I was on vacation.

This is the expected behaviour. Bazarr only cache the ffprobe output for indexation purpose but, on each search, we run guessit on the media file. There's no plan to change that in the upcoming future.

**Comment by k29t59dh** [comment]
No problem, hope you enjoyed it.

There must be something else going on because guessit only checks filenames, which the OS has in page cache. 
I confirmed by running guessit manually on a bunch files that, when bazarr runs searches on, wakes the disks and saw no disk reads whatsoever.

When I get time I'll dig into the code, see if I spot anything. 
(And thank you for this handy app.)

**Comment by morpheus65535** [comment]
I don't what else could be causing this other than subtitles sync (ffsubsync) but I'm pretty sure you'vee tought about it. ;-)

Keep me informed of your finding.

**Comment by k29t59dh** [comment]
> I don't what else could be causing this other than subtitles sync (ffsubsync)

I have that disabled.

> but I'm pretty sure you'vee tought about it. ;-)

Ha! No if anything I'm stumbling in the dark.

I do have some new info:
I keep TV show and movies on separate disks.
I "unmonitored" all the movies with missing subtitles and now those disks stay spun down – so it's definitely search-related.

Is there a setting to "give up searching" after a specified amount of time?
I have adaptive search enabled but it looks like it only reduces frequency, unless I'm misunderstanding.

**Comment by morpheus65535** [comment]
> Is there a setting to "give up searching" after a specified amount of time? I have adaptive search enabled but it looks like it only reduces frequency, unless I'm misunderstanding.

No, adaptive searching is the only way to achieve something "similar".

I'll try to look into this today.

**Comment by morpheus65535** [comment]
Probably relted to the hasing calculation that we don't cache: https://github.com/morpheus65535/bazarr/blob/development/libs/subliminal/utils.py
