### ISSUE TITLE
Multiple "Error 401 You have disconnected from the server" popup on Login

### ISSUE THREAD

**Issue by BHWarrior** [morpheus65535/bazarr#1901]
**Describe the bug**
Multiple "Error 401 You have disconnected from the server" notification on login page.

**To Reproduce**
Go to login page.

**Expected behavior**
Normal login page with no errors because application is actually works.

**Screenshots**
![](https://i.imgur.com/2Yco3mQ.png)

**Software (please complete the following information):**
 - Bazarr: LinuxServer Docker 1.1.0 
 - Radarr version 4.1.0.6175
 - Sonarr version 3.0.8.1507
 - OS: Debian 11

**Comment by halali** [comment]
Do you have any proxy that can return unauthorized access to bazarr api?

**Comment by BHWarrior** [comment]
Yes, there is traefik in front of bazarr instance. And there are no problems with connecting bazarr to sonarr and radarr using its API. All is fine.

It happened after bazarr new UI was released and container was updated. With old UI, there was no problem.

**Comment by kstlouis** [comment]
Similar issue here; remote and local access works for all of my other *arr instances, only seeing this issue (AFAIK) after recent container update.

**Comment by mvanbaak** [comment]
<img width="1689" alt="Screenshot 2022-07-22 at 15 47 17" src="https://user-images.githubusercontent.com/1928231/180453310-1a070814-0399-451f-8314-3da34b9c2ae0.png">

It's just a UI issue. User is not logged in, so data is missing etc.

Best to not show notifications when the user is not yet logged in?

**Comment by morpheus65535** [comment]
@BHWarrior Can you confirm if in the next upcoming beta this error is not present anymore?

**Comment by BHWarrior** [comment]
> Owner


> @BHWarrior Can you confirm if in the next upcoming beta this error is not present anymore?



> @BHWarrior Can you confirm if in the next upcoming beta this error is not present anymore?

Unfortunately, I'm using LinuxServer docker image so it depends on whether they update the image or not. Literally in stable version. Other users with latest version perhaps?

**Comment by morpheus65535** [comment]
> Unfortunately, I'm using LinuxServer docker image so it depends on whether they update the image or not. Literally in stable version. Other users with latest version perhaps?

You can switch to `linuxserver/bazarr:development` once they build the new image within 24 hours.

**Comment by BHWarrior** [comment]
> > Unfortunately, I'm using LinuxServer docker image so it depends on whether they update the image or not. Literally in stable version. Other users with latest version perhaps?
> 
> You can switch to `linuxserver/bazarr:development` once they build the new image within 24 hours.

Alright, then. I edited my docker compose file per your instruction. Issue still persist in v1.1.1-beta.6. Will wait for next beta version.

**Comment by morpheus65535** [comment]
> Will wait for next beta version.

They released 1.1.1-beta.7 image 4 hours ago.

**Comment by BHWarrior** [comment]
I can confirm that with v1.1.1-beta.7, error is gone. Many thanks!!!

**Comment by mvanbaak** [comment]
It still shows `syncing movies` notification on the login screen though :(

**Comment by BHWarrior** [comment]
> It still shows `syncing movies` notification on the login screen though :(

I didn't experience this. Only 401 error. They were gone in recent beta. Different setting perhaps.

**Comment by morpheus65535** [comment]
@LASER-Yi can you look into this again please?

**Comment by LASER-Yi** [comment]
Should be fixed in the upcoming version

**Comment by morpheus65535** [comment]
@mvanbaak can you confirm tomorrow if this fix your issue?

**Comment by mvanbaak** [comment]
> @mvanbaak can you confirm tomorrow if this fix your issue?

tested on 2 installs of radarr and I no longer get any notifications before logging in.
Thanks!
