### ISSUE TITLE
Bazarr: Not syncinc subtitles correctly, also unable to mass edit and delete subtitles.

### ISSUE THREAD

**Issue by grrminator** [morpheus65535/bazarr#1902]
https://i.imgur.com/KRAtGv8.png

Image there showing what I am doing,

Log file is absolutely massive just for the past 24 hours (108MB and am struggling to see what I need to look for)

The sync function refuses to seemingly work. Even with highly rated subtitles, etc.

And I cannot delete the subtitles already downloaded with actions to help me troubleshoot. So right now, I am currently stuck.

EDIT: Debug for subtitle sync was on and I do not remember flipping that switch. That seems to fix the issue, but the delete is still greyed out.

**Comment by morpheus65535** [comment]
@LASER-Yi can you check the batch delete menu option please?

**Comment by halali** [comment]
I think delete in mass edit is greyed because mass edit was never made for mass delete

**Comment by morpheus65535** [comment]
> I think delete in mass edit is greyed because mass edit was never made for mass delete

You may be right about this. Lets wait for @LASER-Yi feedback.

**Comment by grrminator** [comment]
> @LASER-Yi can you check the batch delete menu option please?

Where would this be? I must be blind

**Comment by morpheus65535** [comment]
@halali you were right, the API to delete subtitles doesn't support batch delete.

@grrminator I was talking about the frontend code for the disabled menu item. In fact it's expected to be disabled as backend doesn't support batch deletion of subtitles.

Nothing left to fix so I'll close this issue.
