### ISSUE TITLE
Base URL forward slash

### ISSUE THREAD

**Issue by dglava** [morpheus65535/bazarr#1903]
**Describe the bug**
The entry field implies a forward slash, but one has to add it manually before the URL, otherwise it won't work.

**To Reproduce**
1. Go to the Sonarr/Radarr settings page
2. Enter a base URL **without** a forward slash
3. Click "Test"
4. Error message showing the misformed URL `InvalidURL('Failed to parse: http://localhost:8012sonarr/api/v3/system/status')` pops up
5. Enter a base URL **with** a forward slash
6. Click "Test"
7. The version string is shown and it works

**Expected behavior**
Since the entry field already shows a forward slash that can't be deleted, one might assume that it's not needed.

**Screenshots**
https://i.postimg.cc/sXjrXrpY/2022-07-13-11-30-17.png
https://i.postimg.cc/SsgpYvrw/2022-07-13-11-30-25.png

**Software**
 - Bazarr: 1.1.0
 - Radarr: 4.1.0.6175
 - Sonarr: 3.0.8.1507
 - OS: Debian 11

**Comment by morpheus65535** [comment]
Cannot reproduce. Probably related to your "corrupted" config.ini

**Comment by dglava** [comment]
I have tried the v1.1.1-beta.9 version and there is still some weird stuff happening.

When I enter `/sonarr` as the base URL (additional manual forward slash) and click "Test", it shows the version correctly, implying that it's working. The config file shows `base_url = //sonarr`, with 2 forward slashes (my manually added one and the implied one from the settings page). My logs show this whenever I try to perform a task and I assume it's because it's not working due to the faulty base URL (with 2 forward slashes):
```
Jul 30 09:46:29 masina-s bazarr[1764]: 2022-07-30 09:46:29,654 - apscheduler.executors.default    (7f02547b8700) :  ERROR (base:131) - Job "Sync episodes with Sonarr (trigger: interval[1:00:00], next run at: 2022-07-30 10:46:29 CEST)" raised an exception
```

When I leave out the manual forward slash, everything is working correctly.

The problem is that Bazarr is implying that it's working even when one enters an additional forward slash manually ("Test" shows the version string). I don't know if it's the wrong approach to fixing this, but perhaps it should strip the forward slash when a user tries to enter it in addition to not showing the correct version upon clicking test.
