### ISSUE TITLE
Clicking "Save" in Radarr/Sonarr settings resets base URL

### ISSUE THREAD

**Issue by dglava** [morpheus65535/bazarr#1904]
**Describe the bug**
Clicking "Save" after modifying Radarr/Sonarr settings, the base URL gets reverted back to "bazarr".

**To Reproduce**
1. Enter custom base URL
2. Click on "Save"
3. The base URL changes to "bazarr"

**Expected behavior**
The base URL shouldn't change.

**Screenshots**
Here's a video showing the issue: https://webm.red/view/CWNe.webm (the API key was deleted just for the video, it's displaying the same behaviour with a valid API key).

**Software**
 - Bazarr: 1.1.0
 - Radarr: 4.1.0.6175
 - Sonarr: 3.0.8.1507
 - OS: Debian 11

**Comment by LASER-Yi** [comment]
Sorry for the inconvenience, this issue should be fixed in the upcoming beta version

**Comment by dglava** [comment]
No worries, thanks for fixing it so quickly.

**Comment by motoridersd** [comment]
I'm seeing the same issue, even on v1.1.1-beta.6

**Comment by morpheus65535** [comment]
> I'm seeing the same issue, even on v1.1.1-beta.6

Can you confirm how you fixed it as stated on Discord?

**Comment by motoridersd** [comment]
I noticed the config.ini file had the base url for both Sonarr and Radarr as "//sonarr" and "//radarr" respectively. I edited the file manually to remove the extra / and restarted the service. This fixed it. (This was on Ubuntu with v1.1.1.-beta.6)

I know the GUI doesn't like you leaving the / out when editing the config in the GUI, but it seems that if you add it, it's getting added twice into the config file.

**Comment by mvanbaak** [comment]
I also still have the issue on 1.1.1-beta.6.
I checked the config file, i do NOT have the double / for the base url: `base_url = /radarr`

**Comment by morpheus65535** [comment]
@LASER-Yi we can't use the same `BaseUrlModification` constant for all 3 base url (Bazarr/Sonarr/Radarr) if you point it to `settings.general.base_url`.

**Comment by LASER-Yi** [comment]
Should be fixed in the upcoming beta version

**Comment by mvanbaak** [comment]
Can confirm this one is fixed in beta.7
