### ISSUE TITLE
Radarr/Sonarr not recognized

### ISSUE THREAD

**Issue by dglava** [morpheus65535/bazarr#1905]
**Describe the bug**
After updating to Bazarr version 1.1.0, Radarr/Sonarr aren't being picked up anymore, i.e. no episodes and movies are showing up in Bazarr. Under "System->Status" it's showing Radarr/Sonarr as "unknown". Clicking on "Test" while setting Sonarr/Radarr up seems to return the correct version string and implies that it should be working.

Log:
```
Jul 14 14:09:02 masina-s systemd[1]: Started Bazarr subtitles.
Jul 14 14:09:09 masina-s bazarr[3629]: 2022-07-14 14:09:09,856 - root                             (7f06a44b4740) :  INFO (server:41) - BAZARR is started and waiting for request on http://0.0.0.0:8014/bazarr
Jul 14 14:10:33 masina-s bazarr[3629]: 2022-07-14 14:10:33,257 - root                             (7f05ffff7700) :  INFO (signalr_client:103) - BAZARR trying to connect to Sonarr SignalR feed...
Jul 14 14:11:18 masina-s bazarr[3629]: 2022-07-14 14:11:18,831 - root                             (7f05f9feb700) :  INFO (signalr_client:162) - BAZARR trying to connect to Radarr SignalR feed...
```
I have noticed 2 oddities and reported them #1903 and #1904. I don't know if these are related, but I suspect that #1904 might be related and it's not actually saving the settings?

I am accessing Bazarr remotely via an nginx reverse proxy if relevant (also experiencing #1901). It used to work before updating to 1.1.0. Perhaps I am missing something obvious.

**Software (please complete the following information):**
    Bazarr: 1.1.0
    Radarr: 4.1.0.6175
    Sonarr: 3.0.8.1507
    OS: Debian 11

**Comment by dglava** [comment]
Editing the config file manually seems to have fixed it. As assumed, it seems to be related to #1904. My config file had `base_url = //sonarr` after saving it via the web UI. Manually changing it back to `base_url = /sonarr` fixed it.

Should I close this issue as a problem on my end or are other people also experiencing this, i.e. it's something that has to be fixed?

**Comment by LASER-Yi** [comment]
Move to #1904
