### ISSUE TITLE
BAZARR Error (Insufficient data to process the guess)

### ISSUE THREAD

**Issue by CarlDog** [morpheus65535/bazarr#1910]
Describe the bug
Continued errors appearing logs:
Error (Insufficient data to process the guess) trying to get video information for this file: #####

Traceback (most recent call last):
  File "c:\\programdata\\bazarr\\bazarr\\subtitles\\utils.py", line 39, in get_video
    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,
  File "c:\\programdata\\bazarr\\bazarr\\../libs\\subzero\\video.py", line 61, in parse_video
    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,
  File "c:\\programdata\\bazarr\\bazarr\\../libs\\subliminal_patch\\core.py", line 768, in scan_video
    video = Video.fromguess(path, guessed_result)
  File "c:\\programdata\\bazarr\\bazarr\\../libs\\subliminal\\video.py", line 94, in fromguess
    return Episode.fromguess(name, guess)
  File "c:\\programdata\\bazarr\\bazarr\\../libs\\subliminal\\video.py", line 171, in fromguess
    raise ValueError(\'Insufficient data to process the guess\')
ValueError: Insufficient data to process the guess

To Reproduce
Scheduled task searching for missing Series Subtitles

Expected behavior
Being able to process the guess successfully?

Software (please complete the following information):
Bazarr Version 1.1.0
Sonarr Version 3.0.8.1507
Radarr Version 4.1.0.6175
Operating System Windows-10-10.0.19044-SP0
Python Version 3.10.5
[bazarr.log](https://github.com/morpheus65535/bazarr/files/9128880/bazarr.log)

**Comment by halali** [comment]
Can you please fill issue template?

**Comment by morpheus65535** [comment]
@vitiko98 anything else we can try to fix this goddamm issue?

**Comment by ezeholz** [comment]
![image](https://user-images.githubusercontent.com/30635862/184786845-0a9acdc4-719c-46fc-870c-a7c11fe5f7c4.png)
It's enough info? @morpheus65535 
Seems like it's not grabbing the whole name.

**Comment by vitiko98** [comment]
Thanks for the reports. It should be fixed in upcoming beta.

Btw, this issue is not related to #1858

**Comment by morpheus65535** [comment]
> Thanks for the reports. It should be fixed in upcoming beta.
> 
> Btw, this issue is not related to #1858

Thanks mate! I hope it put that behind us!
