### ISSUE TITLE
Cannot decrease manual subtitle adjustment

### ISSUE THREAD

**Issue by Crazyhead90** [morpheus65535/bazarr#1911]
**Describe the bug:**
When trying to adjust the time of a external .srt subtitle.

![afbeelding](https://user-images.githubusercontent.com/20604229/181020912-7a3ec521-d1e2-45bf-acad-063b3a89871c.png)

It will only INCREASE the subtitle time, regardless if there is a minus (-) or plus (+) icon in front.

**Reproduce bug:**
Try manually decreasing downloaded .srt subtitle times

**Expected behavior:**
Normally when there is a plus (+) in front, it should increase the subtitle time by the time input, and decrease the time when there is a minus (-) icon in front.

Software (please complete the following information):
Bazarr Version 1.1.0
Sonarr Version 3.0.8.1507
Radarr Version 4.1.0.6175
Operating System Windows 11 21H2 22000.795
Python Version 3.10.5

**Comment by morpheus65535** [comment]
Duplicate #1894
