### ISSUE TITLE
Bazarr embedded sub extractor removing words

### ISSUE THREAD

**Issue by anonyme123** [morpheus65535/bazarr#1913]
**Describe the bug**
Hello, it seems that Bazarr's embedded subs extractor is removing some words.
We can see that it extracted the embedded English subs:
<img src="https://user-images.githubusercontent.com/19681420/181636518-81b73748-78f7-4faf-8ff6-8b04ed2c28e6.jpg" alt="drawing" width="800"/>

But it removed the word "SPAN" from the sub file:
<img src="https://user-images.githubusercontent.com/19681420/181636757-fda32097-a0d7-4561-a142-974963f7f333.jpg" alt="drawing" width="500"/>

I re-downloaded the original file outside of Bazarr and the word was not removed:
![001009-IINA-Curb Your Enthusiasm S11E08 What Have I Done 1080p HMAX WEB-DL DD5 1 x264-NTb mkv](https://user-images.githubusercontent.com/19681420/181636614-aa38d9a8-7e30-4bd0-a92c-245168870a89.jpg)

Here are my Post-Processing settings, I don't know if they are also used during embedded subs extraction:
<img src="https://user-images.githubusercontent.com/19681420/181637892-357dabd5-7073-45d2-abbe-a81d7cb8186c.jpg" alt="drawing" width="500"/>

**To Reproduce**
1. Configure Bazarr to extract embedded subs
2. Download a video that has embedded subs with the word 'SPAN' in them
3. Let Bazarr extract the embedded subs

**Software (please complete the following information):**
 - Bazarr: 1.1.0
 - Radarr version: 4.1.0.6175
 - Sonarr version: 3.0.8.1507
 - OS: Linux-3.10.0-1160.11.1.el7.x86_64-x86_64-with

**Comment by vitiko98** [comment]
Embedded Provider won't touch any subtitles. This issue is related to post-processing logic.

**Comment by anonyme123** [comment]
Ok so the embedded provider just extracts the subs as-is, and then the post-processing logic runs:
- encode to UTF-8
- remove hearing impaired
- OCR fixes
- common fixes
- fix uppercase
so one of those is removing the 'SPAN' word?

**Comment by vitiko98** [comment]
Yes, I assume the hearing impaired processor is making the change.

**Comment by anonyme123** [comment]
Will you be able to fix it?

**Comment by vitiko98** [comment]
I'll try.

Please send the untouched subtitle file if you can.

**Comment by anonyme123** [comment]
Here you go: https://demo.lufi.io/r/AS3jQ9Mc6z#V2fXl71NM5mEZTQYK/AJTRsBYIFIVHC/VBy5pcJaIrQ=

**Comment by vitiko98** [comment]
Should be fixed in upcoming beta. Thanks!
