### ISSUE TITLE
High CPU usage at idle

### ISSUE THREAD

**Issue by 2fst4u** [morpheus65535/bazarr#1914]
**Describe the bug**
Bazarr seems to have consistently high CPU at idle, with no tasks in particular running other than the regular searches. Without limits in place on my system I see over 1 whole core of CPU used consistently.

**To Reproduce**
1. Nothing in particular. Just always high CPU 

**Expected behavior**
At idle I'd expect no more than 100 milicores of CPU. I understand some tasks are intensive but they're not always running.

**Software (please complete the following information):**
 - Bazarr: v1.1.0 however I've seen this consistently for many versions so far
 - Radarr version: 4.1.0.6175
 - Sonarr version: 3.0.8.1507
 - OS: Ubuntu 21.10

**Additional context**
Running on kubernetes (so docker)

**Comment by halali** [comment]
Can you show as some graph with debug log?

We need to see what is bazarr doing at that time.

**Comment by 2fst4u** [comment]
I don't have a graph because it's just constant. Left unlimited the CPU usage just stays above 1 full core. I have it limited to about 500 milicores currently and it's still working fine so I'm continually lowering the limit to see what breaks.

What's the best way to upload debug logs? I have one for the last hour or two.

**Comment by morpheus65535** [comment]
> What's the best way to upload debug logs? I have one for the last hour or two.

You can simply put it here or use 0bin.

**Comment by 2fst4u** [comment]
I started a new debug log since it was a while ago now that I opened this but the CPU usage is still high while it was logging.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/9312287/bazarr.log)

**Comment by morpheus65535** [comment]
@2fst4u there's nothing wrong in your log. Can you show us `top` output or anything that cna show us the process using that much CPU? 

If possible, send me your last Bazarr backup in private on Discord so I look into your db and config just in case.

**Comment by 2fst4u** [comment]
![This is a TOP from inside the container](https://user-images.githubusercontent.com/15257926/184573823-00d33003-13c1-4bed-b2df-b92d90520f0f.png)
![This is a static output from kubectl top](https://user-images.githubusercontent.com/15257926/184573890-ef0aa3b4-0a81-48ec-b074-bc387eca8a3f.png) which shows resource usage from the Kubernetes cluster. This is with the pod limited to 400milicores (so it maxes it out).


I will send db via discord.

**Comment by morpheus65535** [comment]
What kind of hardware are you using to run Bazarr?

First impression:
- You should enable multithreading to search concurrently on all enabled providers.
- Sonarr and Radarr should be accessed directly, not through your reverse proxy.
- `Embeddedsubtitles provider` is resource intensive but it doesn't seems to be your issue here.
- Subtitles synchronization is also resource intensive.

Other than that, I don't see anything wrong in your database or config.ini file.

**Comment by GazaShaggy** [comment]
I may have an issue relating to this I updated on the 25th of August (Australia) to latest linuxserver docker file and have witnessed high CPU usage finally was able to investigate it tonight and narrowed it down to Bazarr and the python3 process.
I thought it might be the Custom Post Processing running Subcleaner as that's python3 but disabling that and restarting still has high usage.

**Comment by light-bit** [comment]
> I may have an issue relating to this I updated on the 25th of August (Australia) to latest linuxserver docker file and have witnessed high CPU usage finally was able to investigate it tonight and narrowed it down to Bazarr and the python3 process. I thought it might be the Custom Post Processing running Subcleaner as that's python3 but disabling that and restarting still has high usage.

Same for me. Since a few days my fans are blasting every hour or so. Also using linuxserver docker (compose). I tried reinstalling but no luck yet. Never had such high CPU before, my server is in my room and it kept me up at night (so that is saying something). I am going to disable bazarr for now, waiting for a fix.

**Comment by morpheus65535** [comment]
@light-bit there no fix in the pipeline as I don't know what's causing this issue and I can't replicate.

**Comment by light-bit** [comment]
> @light-bit there no fix in the pipeline as I don't know what's causing this issue and I can't replicate.

Sure. I understand. The weird thing is that I did not change any settings, maybe it is a connection issue with external sources. I am going to do another clean install with minimum settings, see if that helps. Maybe it is the sub providers? Cuz I did notice Subscene being disconnected a few times.

**Comment by morpheus65535** [comment]
> Sure. I understand. The weird thing is that I did not change any settings, maybe it is a connection issue with external sources. I am going to do another clean install with minimum settings, see if that helps. Maybe it is the sub providers? Cuz I did notice Subscene being disconnected a few times.

Thanks for teting out. You can also try hotio image without changing your config directory. Just to see if it's related to LSIO. Also, subscene is a broken providers for many, you can try subf2m as a replacement.

**Comment by light-bit** [comment]
> > Sure. I understand. The weird thing is that I did not change any settings, maybe it is a connection issue with external sources. I am going to do another clean install with minimum settings, see if that helps. Maybe it is the sub providers? Cuz I did notice Subscene being disconnected a few times.
> 
> Thanks for teting out. You can also try hotio image without changing your config directory. Just to see if it's related to LSIO. Also, subscene is a broken providers for many, you can try subf2m as a replacement.

I deleted my config dir (to start fresh) and ran the LSIO Docker Compose once again. I decided to **not** add Subscene this time. I am only using OpenSubtitles.org, which should be enough anyway. It seems to have fixed my issue. I do not see any CPU spikes on my server anymore, and the fans are not blasting every now and then. Not sure if this will help the other guys with high CPU usage but wanted to get the word out at least. 

Could it be that Bazarr constantly trying to connect to a faulty provider, such as Subscene, causes this? Cuz it doesn't sound like a CPU heavy task.

**Comment by morpheus65535** [comment]
@light-bit did you try to simply remove subscene from you previous config?

**Comment by light-bit** [comment]
@morpheus65535 Nope, honestly I did not expect it to be the culprit. But you are right, I should have tried. :)

**Comment by morpheus65535** [comment]
> honestly I did not expect it to be the culprit

Me neither and that's why I would have appreciated if we could have cleared that (or not) as the root cause.

**Comment by light-bit** [comment]
I will try to reproduce it, I will let you know.

**Comment by 2fst4u** [comment]
I didn't have sub scene to start with for context. So I don't think it's related.

**Comment by endquote** [comment]
I installed Bazarr under Docker on a Synology just now -- the config is completely default and it's showing rather high CPU usage.

![Screen Shot 2022-09-30 at 11 54 21 AM](https://user-images.githubusercontent.com/330010/193337947-65af37fc-b6c9-4a47-be63-9caf39c29122.png)

![Screen Shot 2022-09-30 at 11 57 25 AM](https://user-images.githubusercontent.com/330010/193338401-a97fe999-0fc1-4184-9971-ba6aac67520d.png)

The web server also doesn't seem to respond, I'm not able to pull up the home page.

**Comment by halali** [comment]
Dont think this is an issue..

You installed bazarr and bazarr need to index your database, and also bazarr use ffmpeg to extract some info from files... This can be cpu intensive especially on nas device... If this cpu usage will be high also after some time... Post debug log so we can at least see what bazarr is doing. Its hard debug something from screenshots.

**Comment by endquote** [comment]
This is a fresh install on an empty machine -- there is nothing to index.

Looking at the logs, it was caught in some kind of loop because the time zone wasn't set correctly:
`tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like %s. \nPlease use a timezone in the form of Continent/City'`

Maybe a more graceful failure is possible here.

**Comment by morpheus65535** [comment]
@endquote of course we can catch it but we'll need the full stack trace, not just the error.

**Comment by morpheus65535** [comment]
I don't have anything left to investigate here. Unless someone is able to provide useful informations to find the root cause, I won't be able to do anything about it.

**Comment by 2fst4u** [comment]
Yea sorry I haven't been able to get a time series logger installed so I can't pinpoint when it happens. I hope I'm not the only one with this and that others experience this.

I guess this should be closed with a view to reopen if there is anymore information.

-------- Original Message --------

**Comment by morpheus65535** [comment]
@2fst4u feel free to reopen once you have time to bring more information to pinpoint the root cause.

**Comment by hamishm456** [comment]
Was having same issue then reversed the Continent/City timezone in the environmental variables used in the container. Recreated the container and it no longer consumed high CPU and would now launch web app.

E.G

This didn't work - - TZ=Sydney/Australia

This worked - - TZ=Australia/Sydney

**Comment by 2fst4u** [comment]
That's really odd because it shouldn't work. Maybe that just "breaks" the timezone setting and stops whatever was causing the bug from occurring?

I still get this issue on the latest version. I'll try just commenting out my timezone.

**Comment by hamishm456** [comment]
very odd. I have all my docker-compose scripts in a single stack file and deploy in Portainer.
Every other container uses City/Continent except Bazarr which uses Continent/City.

**Comment by 2fst4u** [comment]
Yea but what I mean is, is it _actually_ using it in the reversed form? Or is it just broken and therefore ignored by bazarr?

**Comment by 2fst4u** [comment]
Incredibly removing the timezone envvar seems to have done the trick. I'll leave it for a day and see what happens.

**Comment by morpheus65535** [comment]
@2fst4u what was the value?

**Comment by 2fst4u** [comment]
I had:

```
- name: TZ
  value: "Pacific/Auckland"
```

**Comment by morpheus65535** [comment]
> Every other container uses City/Continent except Bazarr which uses Continent/City.

I've never seen support for improper usage of timezone like City/Continent. If you check the exemple on each docker image instructions, they are always in the form of Continent/City.

Maybe othe software have patch to convert it to a proper timezone but it's up to them. It's not the case with Bazarr. We expect the operating system to provide a valid timezone.

You can always refer to wikipedia for a list of timezone: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by morpheus65535** [comment]
> "Pacific/Auckland"

This should have worked. Strange.

**Comment by 2fst4u** [comment]
Yea very weird. I have that set for a lot of other containers. It's been a couple of days now and it seems like the issue hasn't come back.

**Comment by morpheus65535** [comment]
> Yea very weird. I have that set for a lot of other containers. It's been a couple of days now and it seems like the issue hasn't come back.

Just to be sure, I've deployed on my Ubuntu 20.04.5 LTS host both `linuxserver/bazarr:latest` and `hotio/bazarr:latest` with only PUID/PGID and your timezone `Pacific/Auckland `. Both are running under 0.1% of CPU usage. Doesn't seems to be the issue here or maybe it's something specific to your operating system?

**Comment by morpheus65535** [comment]
Should be fixed by my last commit. Invalid timezone will simply be ignored and we'll use UTC instead.

**Comment by morpheus65535** [comment]
> Unfortunately I have high CPU usage at idle. On a 56-thread server it uses a minimum of 16.5 threads 100%, constantly, even when not scanning. No Timezone (or timezone/localtime) mounts and no TZ env.

What if you define a proper TZ environment variable?

**Comment by morpheus65535** [comment]
> Tried that too, no change. I might have to just add poor-man's debug outputs everywhere and see what sticks. Using hotio images but hijacking entrypoints to modify images is easy enough. Time-consuming, though.

What version of Bazarr are you running?

**Comment by morpheus65535** [comment]
@OdinVex should be fixed in upcoming nightly that will be available in about 8 hours using hotio/bazarr:nightly

Let me know of it goes.

**Comment by morpheus65535** [comment]
@OdinVex What is the timezone used by Bazarr when you check the first log line after starting Bazarr?

Can you show me your docker-compose so I can try to reproduce this issue?

**Comment by morpheus65535** [comment]
@OdinVex using your stripped docker-compose, I'm unable to reproduce.

P.S.: I don't know why you don't want to set TZ but it should be done for all your container that support it.

**Comment by morpheus65535** [comment]
> ??? I think you missed the part where I had a TZ first and simply removed it for testing (to allow your default UTC bit). I set TZ and localtime and timezone for all containers. Bazarr is the only one that has an issue.

Sorry, I may have mixed this with something else.

In regard to SignalR threads, there's a time.sleep in the consume_queue that should take care of not using 100% of CPU.
https://github.com/morpheus65535/bazarr/blob/master/bazarr/app/signalr_client.py

What I don't understand is why does it only happen to you (and maybe a couple of others) out of about 80 000 Bazarr instances running currently.

I've just checked my instance again and it's using less dans 0.1% of one core idling while both SignalR feed are open and waiting for events.

**Comment by morpheus65535** [comment]
If you remove the no_signalr argument and modify the time.sleep() inside your docker container, does it fixes your issue?

**Comment by morpheus65535** [comment]
> Do you mean if I restore the `no_signalr` and just tamper with a `time.sleep()` (which? the `signalr_client.py` one is just `sleep`, not `time.sleep`) ? This is a non-busy 2S14C56T (2 socket 14-core 56-thread) 256GB of RAM server on TBs of data with almost zero load, so I don't imagine it needing more sleep.

I mean: if you don't use the no_signalr argument anymore and modify the signalr_client.py file manually to put the sleep before the try, doesn't it fix your issue or not?

**Comment by morpheus65535** [comment]
Do you want to move to Discord dev_community channel?

**Comment by morpheus65535** [comment]
Both Sonarr and Radarr clients are exactly the same on your side (except variable names or stuff like that) so the difference would be on their side?

**Comment by jzucker2** [comment]
This still keeps happening for me, did anyone ever investigate this?

**Comment by OdinVex** [comment]
> This still keeps happening for me, did anyone ever investigate this?

The issue unexpectedly disappeared for me or I'd have tried to do just that.
