### ISSUE TITLE
Settings messed up when sonarr and radarr use a custom base path

### ISSUE THREAD

**Issue by fr500** [morpheus65535/bazarr#1915]
**Describe the bug**
When sonarr or radarr use a custom base path, bazarr is unable to save the settings properly. Two things happen:

1. If I add the base path without a / (sonarr) it will fail the test
2. If I add the base path with a / (/sonarr) it will pass the test but will reset to the default value upon save

So in case 1
URL on testing is parsed as http://192.168.x.x:8989sonarr instead of 192.168.x.x:8989/sonarr as it should so test fails
It's failing to add the / on it's own

In case 2
URL is correct since I add the /, but when I save it sees the / as an error so it resets to bazarr

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1721040/182098256-b11911cc-15ce-4e10-87f9-216c106179e6.png)

If I add the /
![image](https://user-images.githubusercontent.com/1721040/182098217-b102abf3-0147-4c20-a1f4-9c61a6332107.png)

When I hit save it resets /sonarr to bazarr
![image](https://user-images.githubusercontent.com/1721040/182098552-05cba866-ca65-46a3-86c5-61ccf5bb0e73.png)

**Software (please complete the following information):**
 - Bazarr: [e.g. v 1.10]
 - Sonarr version [e.g. v 3.0.8.157]

**Additional context**

**Comment by morpheus65535** [comment]
Multiple issues already fixed in dev branch.
