### ISSUE TITLE
Original "scenename" is not shown in manual search anymore

### ISSUE THREAD

**Issue by Zamana** [morpheus65535/bazarr#1917]
**Describe the bug**
Original "scenename" is not shown in manual search anymore

**To Reproduce**
1. Go to any movie/series episode
2. Click on "Manual Search"
3. The list of subtitles found is shown, but the "scenename" is not.

**Expected behavior**
I don't know for sure, but I guess that until before version 1.0, the "scenename" was shown in the Manual Search window, so you could pick up the exactly subtitle for your file, or the nearest one.

**Screenshots**

Radarr keeps track of original filenames, 

![radarr](https://user-images.githubusercontent.com/6900313/182695318-bd2162ec-f9db-4b31-acb9-4c8ca963a29b.png)

but Bazarr does not show it:

![bazarr](https://user-images.githubusercontent.com/6900313/182695342-469944f5-8a25-41c3-adcd-93d35cba5eb2.png)

**Software (please complete the following information):**
 - Bazarr: v1.1.0
 - Radarr version 4.1.0.6175
 - Sonarr version 3.0.8.1507
 - OS: Docker (on Debian 11)
 - 
**Additional context**
N/A

**Comment by morpheus65535** [comment]
Confirmed. @LASER-Yi could you take a look at this one please? Before new UI, we were showing scenename if available or filename if not.

**Comment by LASER-Yi** [comment]
Should be fixed in the upcoming version
