### ISSUE TITLE
Scheduled Task for Series not getting subtitles from opensubtitles.org

### ISSUE THREAD

**Issue by fadwen** [morpheus65535/bazarr#1919]
**Describe the bug**
opensubtitles.org provider is not grabbing series subtitles during scheduled task, despite there being threshold matches.

**To Reproduce**
Automated scheduled tasks and manually running via System > Tasks > Run and nothing gets downloaded.

**Expected behavior**
Currently every day provider opensubtitles.com is grabbing 20/day for series before being rate limited.  Provider opensubtitles.org IS working with movies as they are added, but not working on series.

**Screenshots**
![bazarr1](https://user-images.githubusercontent.com/110697945/183211515-ce046d41-0ce1-4249-ad43-e22788686cc5.png)
![bazarr2](https://user-images.githubusercontent.com/110697945/183211541-10c9abb1-4677-49e3-a858-83edf8664306.png)
![vip](https://user-images.githubusercontent.com/110697945/183211616-bfbc4b1c-31bd-4776-a1b6-fa3adb603598.png)
![bazarr3](https://user-images.githubusercontent.com/110697945/183215143-4543a6a9-6c9b-46d9-b6fe-db100c6aa1fc.png)

**Software (please complete the following information):**
 - Bazarr: 1.1.0 -- v1.1.0-ls157 by [linuxserver.io](https://linuxserver.io)
 - Radarr version 4.1.0.6175
 - Sonarr version 3.0.8.1507
 - OS: Ubuntu 22.04
 - Docker: 20.10.17

**Additional context**
Scheduled task "Search for wanted Series Subtitles" every 3 hours does not pick up any subtitles from provider opensubtitle.org
Manually searching for subtitle shows acceptable available, searching per episode will grab and replace.  Running task manually also presents Status as "ValueError"
Searching per series I have to first delete \config\cache\* after stopping container, and container start it will successfully grab one series manually.
I am betar#3228 in discord for a quicker response
Attaching log as requested:
[bazarr (8).log](https://github.com/morpheus65535/bazarr/files/9273620/bazarr.8.log)

**Comment by morpheus65535** [comment]
@vitiko98 isn't that one supposed to be fixed?
`Provider 'opensubtitles' is discarded`

If he clear it cache and restart Bazarr it works for a while then get back to this issue.

Any idea?

**Comment by codefaux** [comment]
I feel like my issue is related. I went through setting all of this up (can't help but notice there's now adjustable scheduling as per my previous Issue #725) and for the last week I've been waiting for the five digit figure indicating Wanted subtitles to begin to go down, instead of up. Long story short, I believe I'm dealing with an issue related to this. Issue #1939.

**Comment by vitiko98** [comment]
Should be fixed in upcoming beta.
