### ISSUE TITLE
Docker Mods not working anymore

### ISSUE THREAD

**Issue by dnmaia** [morpheus65535/bazarr#1921]
I was using the docker mod that install the sc0ty subsync on bazarr from the docker below:

https://hub.docker.com/r/wayller/bazarr-mod-subsync

But after a certain update it is not working anymore. it doen'st install again. This feature was removed from the latest bazarr container?

**Comment by halali** [comment]
We are not supporting this docker... 

Ask maintainer... bazarr has its own subsync implementation

**Comment by dnmaia** [comment]
ok. thanks
