### ISSUE TITLE
Base URL setting in "Radarr" and "Sonarr" do not reflect values shown in config.ini file and setting tests have unexpected and inconsistent results.

### ISSUE THREAD

**Issue by klingonhighcmd** [morpheus65535/bazarr#1922]
**Describe the bug**

I am running the latest versions of all software discussed in this post. 

I have registered a domain and have a CA SSL certificate to be able to use my domain coupled to NGINX configured to support a reverse proxy that accepts URLs on port 80 and moves them to port 443. This gives me SSL for all of my ARR apps (only router port open is 80). All of my ARR apps and Plex run on the same server. I actually have 3 instances (3 domains, 3 certificates, etc running on 3 dedicated servers - 3 Windows 10 Pro machines (two i7s and one i5)).  All 3 servers exhibit the same behavior I am describing in this post. So, for example, I enter "mydomain/sonarr" in my browser (chrome or edge) and end up on "https://mydomain/sonarr". 

I am able to access Sonarr via mydomain/sonarr and Radarr via mydomain/radarr with no issues. Those apps are running flawlessly in this configuration. I can also access Bazarr via mydomain/bazarr. To achieve this, each app required "Base URL" to be changed from the default to either "/sonarr", "/radarr", or "/bazarr". 

Testing Sonarr and Radarr in the Bazarr settings with all 3 apps behind an NGINX reverse proxy has unexpected and inconsistent results. 

**To Reproduce**

TEST 1:
1. Enter bazarr via "mydomain/bazarr" and go to "Radarr" in settings. 
2. Enter API key for Radarr instance and /radarr for "Base URL" then click "Test". Test button displays "Version 4.1.0.6175". 
3. Click Save. Note that "Base URL" reverts to "bazarr". 
4. Inspect Bazarr config.ini file and see that "base_url = //radarr" in "[radarr]" section as desired but not as reflected in UI. 
5. Return to "Radarr" settings in Bazarr app and click on different settings group then return to "Radarr" settings. 
6. Click "Test" button again and observe Test button displays "Wrong URL Base." This message is correct for what is displayed in the "Base URL" display but not for the value as shown in the config.ini file. 

TEST 2:
1. Enter bazarr via "mydomain/bazarr" and go to "Sonarr" in settings. 
2. Enter API key for Sonarr instance and /sonarr for "Base URL" then click "Test". Test button displays "Version: 3.0.9.1549". 
3. Click Save. Note that "Base URL" reverts to "bazarr". 
4. Inspect Bazarr config.ini file and see that "base_url = //sonarr" in "[sonarr]" section as desired but not as reflected in UI. 
5. Return to "Sonarr" settings in Bazarr app and click on different settings group then return to "Sonarr" settings. 
6. Click "Test" button again and observe Test button display "Version: 3.0.9.1549" correctly again (even though the displayed "Base URL" value is "bazarr" not the value "/sonarr" that should be required to achieve correct test results. 

**Expected behavior**
Upon entering the settings area, the values displayed in "Base URL" fields in "Radarr" and "Sonarr" settings should be the same as what is stored in the Bazarr config.ini "[radarr]" and "[sonarr]" sections respectively. When the value shown in the "Base URL" field is correct, the test should work. When the value shown in the "Base URL" field is incorrect, the test should fail. 

**Screenshots** 
Superfluous in the case of this problem description.

**Software (please complete the following information):**
 - Bazarr: v 1.1.0
 - Radarr version v 4.1.0.6175
 - Sonarr version v 3.0.9.1549
 - OS: Windows 10 Pro 10.0.19044 Build 19044

**Additional context**
Given that I have decades of experience as a software engineer and work for a major tech company, I am reluctant to file a bug without thorough testing and attempts to resolve the issue myself.

**Comment by morpheus65535** [comment]
Thanks for taking the time to fill that issue. All of those base_url issues that appears with v1.1.0 should be fixed in 1.1.1-beta. Can you test and confirm if there's a remaining issue?

**Comment by klingonhighcmd** [comment]
Thanks for getting back to me so quickly. I downloaded the latest beta and
tested with it. The config files are slightly different, but I believe I
migrated from the old version to the new version correctly. The app seems
to work perfectly now. Also, all my missing subtitle files appeared! That
was an added bonus.

I can set up the installed beta version to run as a service with no
problem. However, I would really prefer not to have to install (and later
uninstall) Visual Studio, etc on my other 2 servers to get the beta version
installed. Is there a way to build the exe install version of the beta app
so I can keep those servers clean/lightweight and avoid the extra
installs/uninstalls for the sake of the app install?

Thank you for your help,
A huge fan!

**Comment by morpheus65535** [comment]
To use the beta version, you can simply install the latest version using the Windows installer and in Settings-->General, you can switch to `development` branch. Run the `Update Bazarr` task in System-->Tasks and wait for Bazarr to update an restart.
