### ISSUE TITLE
ENHANCEMENT - New Logo

### ISSUE THREAD

**Issue by hernandito** [morpheus65535/bazarr#1923]
Hi Morpheus...

I have created a Bazarr logo variation. Please feel free to use it if you like it, or let me know if you want to make changes. I feel the current icon looks too generic (like a fallback for a missing graphic).

Also the favicon is a fallback graphic in Firefox.
![image](https://user-images.githubusercontent.com/787317/183670937-0191f9ab-ded6-47dc-9f6a-8a6b680b9d4f.png)

Here is the new logo.
![Bazarr 2022](https://user-images.githubusercontent.com/787317/183671204-e4e6e67b-c1cd-4e90-a9d1-6c759859f117.png)

Thank you for your amazing work!

H.

**Comment by morpheus65535** [comment]
Thanks for this suggestion. I'm not planning to change the actual logo/icon for Bazarr. BTW your seems to have an issue because this is the favicon you should be seeing: 
![image](https://user-images.githubusercontent.com/5130500/184935680-ee9616f1-9ed3-4d3d-87d7-560a84db6ef2.png)

Maybe a cache issue in your browser.

**Comment by yannduran** [comment]
I'm also seeing this problem. It just shows Edge's default icon.

![image](https://user-images.githubusercontent.com/2031126/197369507-54264431-86a9-41cb-a571-1906568eccad.png)

I've cleared the image cache and restarted Edge. I still don't get the Bazarr icon.

**Comment by pto199** [comment]
This logo is much better than the official one.  Official one I was confused recently when I saw it and didnt know what docker it was referencing until I clicked it.  Thought it was a credit card and was wonder what app I had.  This logo makes it more clear that its referring to subtitles.  Updated my shortcuts, Thanks!
