### ISSUE TITLE
"Adjust times..." option only delays the subtitles

### ISSUE THREAD

**Issue by jgroboredo** [morpheus65535/bazarr#1928]
**Describe the bug**
When I try to adjust the times of a given subtitle with the "-" option selected, the given amount of time is always summed and not subtracted.

**To Reproduce**
Try the option "Adjust Times..." on any given subtitle with the "-" option selected and verify the subtitles are delayed by the amount of time specified (instead of appearing earlier). 

**Expected behavior**
The time specified should be subtracted to the timestamps of the subtitles when the "-" option is selected (so that the subtitles appear earlier by that amount of time). 

**Software (please complete the following information):**
 - Bazarr: 1.1.0
 - OS: Linux-5.15.56-3-rpi-ARCH-aarch64-with

**Comment by morpheus65535** [comment]
Duplicate #1894
