### ISSUE TITLE
Unable to save/store subtitles?

### ISSUE THREAD

**Issue by MaartenMol96** [morpheus65535/bazarr#193]
**Describe the bug**
When trying to download a subtitle for just anything, I get no errors or whatever but also not getting the subtitles.... Permissions are correct and same as radarr/sonarr. Even with debugging enabled I get no clue on why it won't save subs.

**To Reproduce**
Try and download subs with Bazarr running on latest Docker CE (linuxserver repo)

**Expected behavior**
Subtitles next to my media files?

**Software (please complete the following information):**
 - Bazarr: [v0.6.6.3 ]
 - OS: [CentOS 7]

**Comment by morpheus65535** [comment]
Please give me a fresh debug log please. I'll look at it. Thanks!

**Comment by MaartenMol96** [comment]
My Debug logging can be found in this [GIST](https://gist.github.com/MaartenMol96/06475f078285451210467d747bff357c)

I was looking for subs for "Hotel Artemis" by manual search and trying to download Dutch subs (NL) from opensubtitles

**Comment by morpheus65535** [comment]
I would like you to give a try to 0.6.7 which should come out later this week. I think this one should have been fixed last night.

**Comment by MaartenMol96** [comment]
> I would like you to give a try to 0.6.7 which should come out later this week. I think this one should have been fixed last night.

Alright, I will!

**Comment by morpheus65535** [comment]
If you’re running Bazarr from source, you can switch to dev branch and update to give it a try tight now.

**Comment by MaartenMol96** [comment]
> If you’re running Bazarr from source, you can switch to dev branch and update to give it a try tight now.

Using Docker, possible with the linuxserver/bazarr repo?

**Comment by morpheus65535** [comment]
Ok you’re running it in docker. You can try development tag on LSIO image.

**Comment by MaartenMol96** [comment]
> Ok you’re running it in docker. You can try development tag on LSIO image.

There is none, maybe I can make my own image...

**Comment by morpheus65535** [comment]
They have a development image, that's the one I use. :-)

linuxserver/bazarr:development
https://hub.docker.com/r/linuxserver/bazarr/

**Comment by MaartenMol96** [comment]
> They have a development image, that's the one I use. :-)
> 
> linuxserver/bazarr:development
> https://hub.docker.com/r/linuxserver/bazarr/

Alright, running this now but still not working :(

**Comment by morpheus65535** [comment]
Can you come to Discord so we can try to get it working?

**Comment by Deuxgod** [comment]
I’m having the same issue, was it fixed?

**Comment by morpheus65535** [comment]
@deuxgod I would have close the issue if it was fixed... :-p

Still a work in progress.

**Comment by morpheus65535** [comment]
You can try the dev branch but I should be able to merge it in the next days.

**Comment by SeaquestNet** [comment]
When trying the dev branch the issue seems fixed, it's download crazy amounts of subs now!

**Comment by morpheus65535** [comment]
Good news! :-)
