### ISSUE TITLE
BadZipFile Wizdom provider

### ISSUE THREAD

**Issue by realitymolder** [morpheus65535/bazarr#1932]
**Describe the bug**
When adding the Wizdom subtitle provider, we get the error "BadZipFile" or the other error " HTTPError"  
Might be that the API has changed. 

**To Reproduce**
1. Go to providers
2. Add the provider: Wizdom.xyz
3. Refresh the provider list
4. See the error : "BadZipFile"

**Expected behavior**
Should work / add dialog to ask for username + password if required by the API of wizdom. 

**Screenshots**
![image](https://user-images.githubusercontent.com/26459151/186537194-e029d0c6-2ae1-494c-9a8e-5ee7d34245b0.png)

**Software (please complete the following information):**
 - Bazarr: v1.1.0-ls162 by [linuxserver.io](https://linuxserver.io)
 - Radarr 4.1.0.6175
 - Sonarr 3.0.9.1549
 - OS: [e.g. running on Docker Linux-5.15.0-46-generic-x86_64-with]

**Comment by morpheus65535** [comment]
I've just tested this provider and I downloaded a subtitles without any issue. I've just checked and about 750 subtitles have been downloaded from this provider in the last 7 days.

You probably just got a corrupted zip file, that happens from time to time with diffrent providers.

**Comment by realitymolder** [comment]
> I've just tested this provider and I downloaded a subtitles without any issue. I've just checked and about 750 subtitles have been downloaded from this provider in the last 7 days.
> 
> You probably just got a corrupted zip file, that happens from time to time with diffrent providers.

Thanks, I thought it is an error with the provider itself.
