### ISSUE TITLE
This Sonarr/Radarr root directory does not seems to be accessible by Bazarr. Please check path mapping

### ISSUE THREAD

**Issue by Borstel1558** [morpheus65535/bazarr#1937]
**Describe the bug**
I have movies and series on my Synology NAS. I use Sonarr, Radarr and SABnzbd on my desktop and this works perfectly. Now i want to add the service of Bazarr. It can add all my movies and series but it can't seem to write the subs to my NAS. 

**To Reproduce**
1. Go to 'System/status
2. See: 
Z:\ | This Sonarr root directory does not seems to be accessible by Please check path mapping.
X:\ | This Radarr root directory does not seems to be accessible by Please check path mapping.

When I check the path mappings sonarr can see the map Z:\ but bazarr can't. 
![image](https://user-images.githubusercontent.com/112540741/187615552-9c0bae86-2184-4850-9adc-a024f393d2fb.png)
![image](https://user-images.githubusercontent.com/112540741/187615602-5ce6c347-87e4-42e0-b11e-185e304adc4d.png)

The same goes for the mappings of Radarr.

I think Bazarr is able to read but not write in my network folders. 
Is their anything I can do to make this work?

Ps. I already tried //sever/rootfolder/

Thank you in advance!

**Comment by morpheus65535** [comment]
You need to use UNC path and change the account used to run the Bazarr service (Local System won't make it). This is documented on the wiki and you can get support on Discord. This isn't an issue.
