### ISSUE TITLE
Exception when syncing subtitles

### ISSUE THREAD

**Issue by Nakda** [morpheus65535/bazarr#1938]
**Describe the bug**
I noticed a TV show episode where the subtitles were not properly synced. I wanted to force the synchronization manually, but even if a new file was created the issue did persist. While looking at the logs I noticed an exception was raised everytime I try to sync the subtitles.

**To Reproduce**
1. Go to a Serie page
2. Click on Mass Edit
3. Select the episode you want to sync
4. Click on Select Action -> Sync
5. The task popup shows up for a while but nothing happens in the background because of the raised exception

**Expected behavior**
Synchronization process to run without exception.

**Screenshots**
![image](https://user-images.githubusercontent.com/25755503/188124196-139f5071-1aa9-463d-9a42-1782924b6792.png)

**Software (please complete the following information):**
 - Bazarr: v1.1.1
 - Bazarr Package Version: v1.1.1-ls164 by [linuxserver.io](https://linuxserver.io)
 - Radarr version 4.1.0.6175
 - Sonarr version 3.0.9.1549
 - OS: Linux-5.15.32-v8+-aarch64-with
 - Python Information: 3.9.5

**Additional context**

Exception raised by Bazarr
```
02/09/2022 12:49:03|ERROR   |waitress                        |Exception when servicing <waitress.channel.HTTPChannel connected ***.***.***.***:35728 at 0x7f992a0a60>
```

Logs from Bazarr docker container:
```
usage: main.py [-h] [-i [SRTIN [SRTIN ...]]] [-o SRTOUT]
               [--merge-with-reference] [--make-test-case]
               [--reference-stream REFERENCE_STREAM] [-v] [--overwrite-input]
               [--encoding ENCODING]
               [--max-subtitle-seconds MAX_SUBTITLE_SECONDS]
               [--start-seconds START_SECONDS]
               [--max-offset-seconds MAX_OFFSET_SECONDS]
               [--apply-offset-seconds APPLY_OFFSET_SECONDS]
               [--frame-rate FRAME_RATE] [--skip-infer-framerate-ratio]
               [--non-speech-label NON_SPEECH_LABEL]
               [--output-encoding OUTPUT_ENCODING]
               [--reference-encoding REFERENCE_ENCODING]
               [--vad {subs_then_webrtc,webrtc,subs_then_auditok,auditok}]
               [--no-fix-framerate] [--serialize-speech]
               [--extract-subs-from-stream EXTRACT_SUBS_FROM_STREAM]
               [--suppress-output-if-offset-less-than SUPPRESS_OUTPUT_IF_OFFSET_LESS_THAN]
               [--ffmpeg-path FFMPEG_PATH] [--log-dir-path LOG_DIR_PATH]
               [--gss]
               [reference]
main.py: error: unrecognized arguments: --no-fix-framerate 
2022-09-02 12:49:03,491 - waitress                         (7f9c6939d8) :  ERROR (task:86) - Exception when servicing <waitress.channel.HTTPChannel connected ********:35728 at 0x7f992a0a60>
```

**Full logs**
[bazarr.container.log.txt](https://github.com/morpheus65535/bazarr/files/9477349/bazarr.container.log.txt)
[bazarr.debug.log](https://github.com/morpheus65535/bazarr/files/9477350/bazarr.debug.log)
[bazarr.nodebug.log](https://github.com/morpheus65535/bazarr/files/9477351/bazarr.nodebug.log)

**Comment by changochulo** [comment]
I have the same issue. Same error and repro steps as OP. Just started using Bazarr and I get the same error everytime I try to use the sync feature.
Bazarr: v1.1.1
Sonarr: 3.0.9.1549
Radarr: 4.1.0.6175
Docker

**Comment by changochulo** [comment]
@Nakda @morpheus65535  I figured it out. There is typo in the "subsyncer.py" script. There is an extra space after "--no-fix-framerate". To fix it, simply edit the script and delete the extra space and save. Im able to manually sync now.

**Comment by Nakda** [comment]
> @Nakda @morpheus65535 I figured it out. There is typo in the "subsyncer.py" script. There is an extra space after "--no-fix-framerate". To fix it, simply edit the script and delete the extra space and save. Im able to manually sync now.

Indeed, the sync process seems to run without issue now! The subtitles are still not synced properly, but that will be an issue for ffsubsync.

Thanks @changochulo

**Comment by morpheus65535** [comment]
@changochulo @Nakda thank you both for finding this bug and fixing it! :-)

I've made the change in dev branch and this should reflect in upcoming 1.1.2-beta.3.
