### ISSUE TITLE
Test for Sonarr just shows "Failed" -- No log entries?!

### ISSUE THREAD

**Issue by Rawh** [morpheus65535/bazarr#194]
**Describe the bug**
git cloned bazarr onto a synology box. Ran bazarr.py script. Site starts up fine with default settings. Adjusted the config a bit to include language and what sub-site to use. All fine up till this point.

Wanted to add Sonarr. It's running on the same machine (so I'm using 127.0.0.1) but has a basedir set (which I fill in to "sonarr"), plus I enter the API. I hit test and it just says "test failed"

**To Reproduce**
1. Clone new repository
2. Fill in all required settings to allow the save button.
3. Restart Bazarr to apply settings
4. Enable Sonarr
5. Fill in requested details for Sonarr and hit the test button.
6. "Test Failed".

**Expected behavior**
The logs show nothing... I enabled debug (and restarted bazarr), I can see some debug stuff about github API and version checking... But still nothing about Bazarr trying to connect to the Sonarr instance.

**Screenshots**
![bazarr_hates_me_001](https://user-images.githubusercontent.com/10486655/47084730-bc972100-d214-11e8-8e34-5bab204b218b.JPG)
![bazarr_hates_me_002](https://user-images.githubusercontent.com/10486655/47084739-c28d0200-d214-11e8-8a02-0b37e8537e9e.JPG)
![bazarr_hates_me_003](https://user-images.githubusercontent.com/10486655/47084745-c751b600-d214-11e8-9f4a-bf345a53481f.JPG)

**Software (please complete the following information):**
 - Bazarr: Current version.
 - Sonarr version 2.0.0.5252
 - OS: Synology

**Additional context**
I have Sonarr setup with a basedir + login&pw because of reverse proxy. Bazarr has no need of the login&pw values for Sonarr? Does not use them? Or is it failed because Bazarr is missing these details? 

I would be able to tell more if there was any kind of error logging :(

**Comment by morpheus65535** [comment]
Try changing Sonarr and Radarr base url to have a trailing slash: /sonarr

**Comment by Rawh** [comment]
That was the quickest success I've ever seen 👍 

Sadly thought I had to enter the exact IP address of the box. 127.0.0.1 doesnt seem to work.

![bazarr_hates_me_004](https://user-images.githubusercontent.com/10486655/47091607-78f8e300-d225-11e8-9c2c-f43fd5b1c4ac.JPG)

![bazarr_hates_me_005](https://user-images.githubusercontent.com/10486655/47091620-7dbd9700-d225-11e8-9aa4-f68192a54179.JPG)

**Comment by Rawh** [comment]
Hmm even though it's linked, it doesn't seem to sync any of the series I have in Sonarr. :(

**Comment by duhio** [comment]
@Rawh I think this ticket stems from a lack of understanding of Docker networking rather than being a bug.

In the context of the container, localhost (127.0.0.1) is in fact Bazarr, not the address of your device. It works when putting the network IP of your device because you've bound ports from the container to your device.

You should be able to use the name of the container (in my case, simply `sonarr`), as below, instead of the IP of the device. Assuming Docker is relatively up-to-date anyway.

![screen shot 2018-10-17 at 20 27 40](https://user-images.githubusercontent.com/34654219/47111395-524da300-d24b-11e8-861e-33f4b51b1b2e.png)

**Comment by morpheus65535** [comment]
@duhio Rawh said that he had git cloned Bazarr. I assume he's not using Docker but installation from source.

**Comment by Rawh** [comment]
@duhio  I'm afraid you did not understand my question. I'm using git to clone it onto a machine and run it locally. I'm not using docker. 

@morpheus65535 I can see the sync timer. I also hit the manual sync button a few times when we just fixed the connection. It's been about 6 hours ago. Seems to be fine now, the list is live and shows my series. :)

**Comment by morpheus65535** [comment]
Ok, let me know if you run into something else.

**Comment by asymetricbalance** [comment]
@duhio  - If you misunderstood the question, thank you from my end!
I had issues getting bazarr running in a docker set up and your suggestion to simply use the container name fixed it.
