### ISSUE TITLE
Sync does nothing if list in radarr/sonarr is cleared

### ISSUE THREAD

**Issue by givemeurhats** [morpheus65535/bazarr#1941]
**Describe the bug**
Sync does nothing if radarr/sonnar list is empty.

**To Reproduce**
1. Add a series to sonarr
2. Update Series list from Sonarr
3. After a series is synced to bazarr, remove series from sonarr so sonarr list is empty
4. Sync does nothing

**Expected behavior**
Sync should clear all series from list.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: v1.1.1
 - Radarr version 4.1.0.6175
 - Sonarr version 3.0.9.1549
 - OS: linux

**Additional context**
Same problem is in sonarr and radarr.
Problem is that if returned list is an empty array we do nothing..
https://github.com/morpheus65535/bazarr/blob/master/bazarr/sonarr/sync/series.py#L40
https://github.com/morpheus65535/bazarr/blob/master/bazarr/radarr/sync/movies.py#L48

**Comment by morpheus65535** [comment]
Thanks for this one! It should be fixed in upcoming beta.
