### ISSUE TITLE
Error 500 You have disconnected from the server

### ISSUE THREAD

**Issue by Bazzu85** [morpheus65535/bazarr#1942]
**Describe the bug**
When doing something like manual subtitle search or testing the telegram connection the messagge appear

**To Reproduce**
check the description above..

**Expected behavior**
no errors. for example the telegram message is sended.
the manual search on subtitle seems to do nothing..

**Screenshots**
![image](https://user-images.githubusercontent.com/7345587/188378352-98f1d275-01ec-4dcc-a91d-4f83441fa170.png)

**Software (please complete the following information):**
 - Bazarr: v1.1.1
 - Radarr version 4.1.0.6175
 - Sonarr version 3.0.9.1549
 - OS: Windows 11 pro

**Additional context**
--

**Comment by Bazzu85** [comment]
Additional infos:
I fixed the telegram bot string adding the chat_id at the end but the logs constantly says:
`
05/09/2022 08:59:34|ERROR   |app.app                         |Exception on /api/system/notifications [PATCH]|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1502, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n  File "c:\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 467, in wrapper\n    resp = resource(*args, **kwargs)\n  File "c:\\bazarr\\bazarr\\../libs\\flask\\views.py", line 84, in view\n    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)\n  File "c:\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 582, in dispatch_request\n    resp = meth(*args, **kwargs)\n  File "c:\\bazarr\\bazarr\\api\\utils.py", line 30, in wrapper\n    return actual_method(*args, **kwargs)\n  File "c:\\bazarr\\bazarr\\api\\system\\notifications.py", line 22, in patch\n    apobj.notify(\n  File "c:\\bazarr\\bazarr\\../libs\\apprise\\Apprise.py", line 374, in notify\n    return py3compat.asyncio.tosync(\n  File "c:\\bazarr\\bazarr\\../libs\\apprise\\py3compat\\asyncio.py", line 66, in tosync\n    return asyncio.run(cor, debug=debug)\n  File "C:\\Bazarr\\WinPython\\python-3.8.0\\lib\\asyncio\\runners.py", line 50, in run\n    loop.close()\n  File "C:\\Bazarr\\WinPython\\python-3.8.0\\lib\\asyncio\\proactor_events.py", line 679, in close\n    signal.set_wakeup_fd(-1)\nValueError: set_wakeup_fd only works in main thread'|
`
but the test message is sended

**Comment by Bazzu85** [comment]
Additional updates: I tried to use other notifications provider and the error 500 is still there.
This cause problem when searching the subtitles because after the first download the task stops..

is this an apprise problem?

**Comment by morpheus65535** [comment]
This bug is caused by Python 3.8. Upgrade Python if you've installed it by yourself. If you've used the Bazarr installer, note the Bazarr service username, uninstall Bazarr and reinstall using the latest installer that use Python 3.10. You won't lose you config but just in case you can take a backup and put it somewhere safe.

**Comment by eturk1** [comment]
Just noticed this error today trying manual search.
recent install of Bazarr

Bazarr reports Python 3.10.0

**Comment by DrakeJones** [comment]
Me too.  Still happening.

**Comment by morpheus65535** [comment]
> Me too. Still happening.

Create you own issue with evrything required. This issue as been solve a long time ago. You're probably facing something similar but a totaly different cause.

**Comment by DrakeJones** [comment]
Okay.

**Comment by DrakeJones** [comment]
This is still an issue.

**Comment by morpheus65535** [comment]
> This is still an issue.

https://github.com/morpheus65535/bazarr/issues/1942#issuecomment-1238846150

**Comment by morpheus65535** [comment]
@ekk88d this is unrelated to this issue. See #1924

**Comment by morpheus65535** [comment]
Error 500 is a generic http error that means"Internal Server Error". It's the default return code when an unhandled exception is raised server side.

**Comment by DrakeJones** [comment]
Installing on Windows 10 from source using Python 3.10.8, _then switching to development branch_ solve the problem for me.

**Comment by paulmorabito** [comment]
Same thing happening to me with linuxserver.io image when trying to update notification config.

**Comment by morpheus65535** [comment]
> Same thing happening to me with linuxserver.io image when trying to update notification config.

It's a different issue that have been fixed in 1.1.4-beta since #2005

**Comment by paulmorabito** [comment]
> 

Got it. Thank you.
