### ISSUE TITLE
Embeddedsubtitles: All subtitles being considered English, despite having proper language codes. Wrong track being extracted

### ISSUE THREAD

**Issue by azsry** [morpheus65535/bazarr#1945]
**Describe the bug**
Bazarr is considering all 7 subtitle tracks in the provided video as English, even though both MPV and MKVToolNix can determine their actual language. I have tried both with and without checking the "Use subtitles with unknown info/language as english" option in the embeddedsubtitles provider settings. Bazarr seems to be able to tell what the actual language is after it has been extracted. 

Further, trying to extract any of the other subtitle tracks always seems to extract the Indonesian track. I assume this is because it is the final one that is being scanned, and all are being considered English.

**To Reproduce**
1. Download the provided video;
2. Scan for subtitles using embeddedsubtitles in Bazarr;
3. View results

**Expected behavior**
The 7 subtitle tracks should show with their actual language based on language code.

**Screenshots**
![image](https://user-images.githubusercontent.com/11460271/189775274-1a4c2ca6-52cf-4727-a0b6-a3d166162f9b.png)
![image](https://user-images.githubusercontent.com/11460271/189775346-4e33ed36-ab47-465a-af0d-c78f95fe70bd.png)
![image](https://user-images.githubusercontent.com/11460271/189776854-48637fca-64e2-46ed-a250-a3d14167a84d.png)
![image](https://user-images.githubusercontent.com/11460271/189775375-a92eda79-39be-45ad-9f75-255d6d08e66e.png)
![image](https://user-images.githubusercontent.com/11460271/189775627-efabdd7f-5edf-450d-96af-833a3434f665.png)

**Software (please complete the following information):**
 - Bazarr: v1.1.2-beta.3
 - Radarr version: 3.0.9.1549
 - Sonarr version: 4.1.0.6175
 - OS: Docker

**Additional context**

Log file cleared and manual subtitle search performed on file:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/9552421/bazarr.log)

This is my first time submitting a bug report so please let me know if you require anything else!

**Comment by morpheus65535** [comment]
@vitiko98 have you seen this one?

**Comment by vitiko98** [comment]
Thanks for the extensive report. I'll have a look as soon as possible.

**Comment by vitiko98** [comment]
Should be fixed in upcoming beta.

**Comment by azsry** [comment]
Excellent, thank you so much! Just tested after updating to v1.1.2-beta.9 and the offending episodes are scanning properly.
