### ISSUE TITLE
Bazarr does not automatically download subtitles after being wanted (via Sonarr)

### ISSUE THREAD

**Issue by jockebq** [morpheus65535/bazarr#1946]
**Describe the bug**
When I add an episode or show to Sonarr, it will show up in Bazarr. Once the episode is downloaded Bazarr detects this and puts it in Wanted, however it will not download a subtitle automatically when this happens.
Instead it will only download subtitles when the Task "Search for wanted Series Subtitles" is run or "Search All" is pressed under Wanted.

**Expected behavior**
That the subtitles are automatically downloaded once the series is detected and put in Wanted.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/40036309/189891676-e966c548-1a75-40d5-aabd-26a235a9f395.png)
![unknown2](https://user-images.githubusercontent.com/40036309/189891685-f1cfd388-fd35-40eb-8e30-d539c067f2b3.png)

**Software (please complete the following information):**
 - Bazarr: [1.1.2-beta.3]
 - Sonarr version [3.0.9.1549]
 - OS: [Unraid, Docker]

**Additional context**
Logs:
[bazarr-3.log](https://github.com/morpheus65535/bazarr/files/9556675/bazarr-3.log)

**Comment by morpheus65535** [comment]
I don't see any `Event received from Sonarr for episode` in your log file, are you sure Sonarr really imported an episode during this time?

**Comment by morpheus65535** [comment]
Should be fixed in upcoming 1.1.2-beta.10. Can you test and confirm?

**Comment by morpheus65535** [comment]
No news, good news.
