### ISSUE TITLE
Can't find subtitle in zip with Podnapisi.net and possibly other providers

### ISSUE THREAD

**Issue by ThePhaseless** [morpheus65535/bazarr#1947]
**Describe the bug**
Bazarr downloads zip with subtitle from www.podnapisi.net, but cant find subtitle in it.

**To Reproduce**
1. Use podnapisi
2. Try to download subtitle for anything from that provider.

**Expected behavior**
Subtitle should be imported from zip.

**Software (please complete the following information):**
 - Bazarr: v1.1.1 and v1.1.2-beta.3
 - OS: docker on open media vault

Logs:
[bazarr (3).log](https://github.com/morpheus65535/bazarr/files/9559063/bazarr.3.log)

**Comment by morpheus65535** [comment]
Log file is way too large (47k lines). Make sure to empty log first.

Normaly this error means that nothing useful is found inside the zip file.

**Comment by ThePhaseless** [comment]
Updated. Check new logs please <3

**Comment by ThePhaseless** [comment]
> Normaly this error means that nothing useful is found inside the zip file.
This zip can be downloaded with link from logs. There is only one txt file with subtitles.

**Comment by morpheus65535** [comment]
Bazarr only cares about valid subtitles extensions. TXT isn't one of them. Also, even the content of the TXT file isn't a normalized subtitles format:
```
{1}{72}movie info: XVID  624x352 23.976fps 349.9 MB|/SubEdit b.4060 ()/
{879}{927}Wyobra¿asz to sobie?
{931}{1009}OK. Twoja kolej, mój tygrysie.
{1013}{1085}Wszystko w porz¹dku? Wygl¹dasz nieszczególnie.
{1089}{1156}- Wszystko w porz¹dku. -|Czy kark wci¹¿ ci dokucza?
{1160}{1248}- Nic mi nie bêdzie. - Mo¿e|powinnaœ wykonaæ tylko 2,5 obrotu.
{1252}{1317}- Mam zamiar wykonaæ 3. -|Mo¿e jednak lepiej 2,5....
{1321}{1401}Mam zamiar zrobiæ 3.
{1405}{1449}Dobrze.
{1453}{1563}Có¿, poka¿ wiêc doros³ym na co staæ|dobrze wytrenowan¹ dwunastolatkê, OK?
{1949}{2062}Nastêpnym zawodnikiem jest dwukrotna|mistrzyni juniorów - Mary Carroll.
{2556}{2600}Cholera.
{2604}{2711}Mo¿esz to zrobiæ. No dalej,|tylko... zobacz to. Zobacz.
{2996}{3124}Odbicie. Pikowanie. Zanurzenie.
{3752}{3806}Lekarza! Potrzebna karetka!
{5383}{5466}- Zauwa¿y³em, ¿e œwieci siê u|ciebie. - Przecie¿ jest dzieñ.
...
```

**Comment by morpheus65535** [comment]
Nothing else to do here. Closing.
