### ISSUE TITLE
UnboundLocalError: local variable \video\ referenced before assignment

### ISSUE THREAD

**Issue by RichardHoekstra** [morpheus65535/bazarr#195]
**Describe the bug**
1.
Message
`Error trying to get subtitle list from provider`
Exception
```
Traceback (most recent call last):
 File "/app/bazarr/get_subtitle.py", line 61, in download_subtitle
  subtitles = p.list_subtitles(video, language_set)
UnboundLocalError: local variable \video\ referenced before assignment
```

2.
Message
`Job "Search for wanted subtitles (trigger: interval[3:00:00], next run at: 2018-10-19 17:34:18 UTC)" raised an exception`
Exception
```
Traceback (most recent call last):
 File "/app/bazarr/libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/get_subtitle.py", line 451, in wanted_search_missing_subtitles
  wanted_download_subtitles(episode[0])
 File "/app/bazarr/get_subtitle.py", line 377, in wanted_download_subtitles
  message = download_subtitle(path_replace(episode[0]), str(alpha3_from_alpha2(language)), episode[4], providers_list, providers_auth, episode[5], \series\)
 File "/app/bazarr/get_subtitle.py", line 107, in download_subtitle
  downloaded_provider = result[0].provider_name
IndexError: list index out of range
```
[bazarr.log](https://github.com/morpheus65535/bazarr/files/2496853/bazarr.log)

Cannot download subtitles.

**To Reproduce**
No idea.

**Expected behavior**
I expected to at least see Bazarr try and pull subtitles from the sources but all it is giving is that error and 
"Error trying to get video information."

**Software (please complete the following information):**
 - Bazarr: linuxserver/bazarr.latest
 - Radarr version linuxserver/radarr.latest
 - Sonarr version linuxserver/sonarr.latest
 - OS: Docker

**Additional context**
Note: actual movies/series are on a NAS, shared via NFS, mounted on a proxmox host and then passed to docker via volume binds. I have had permission issues before, but this I doubt that this is one. The other docker containers are working just fine. The config is saved on a local HDD.

**Comment by morpheus65535** [comment]
Both are addressed in dev branch.

You can try development image or wait a couple of days for me to merge to master:

linuxserver/bazarr:development
