### ISSUE TITLE
Zimuku provider 404 Client Error still

### ISSUE THREAD

**Issue by ycflash** [morpheus65535/bazarr#1952]
Hello, zimuku provider still not working with 1.1.1 release.  Seams  issue #1842 not resolved.

`Throttling zimuku for 10 minutes, until 22/09/22 10:52, because of: HTTPError. Exception info: "404 Client Error: Not Found for url: https://so.zimuku.org/search?q=How%20It's%20Made.S06&vertoken="`

Any idea?

**Comment by morpheus65535** [comment]
Should be fixed by e2ba532cee04b6fbf1e536d18666dc4d017f23ee in 1.2.1. It now require anti-captcha.com.
