### ISSUE TITLE
ASS subtitle is converted to SRT format unexpectedly via manual upload

### ISSUE THREAD

**Issue by SteinX** [morpheus65535/bazarr#1955]
**Describe the bug**
My ASS format subtitle is converted to SRT format even though **the "Use Original Format" was checked in my Language profile** (Only the extension of the file is kept as ASS).

**To Reproduce**
1. Go to 'Series'
2. Click on 'Upload' button and pick a ASS subtitle
3. Confirm the upload by clicking "Upload" button
4. Go the series media folder to check the uploaded subtitle file

**Expected behavior**
No side effects should be introduced to the content of subtitle files with "Use Original Format" enabled in Language Profile.

**Software (please complete the following information):**
- Bazarr Version 1.1.1
- Package Version v1.1.1-ls166 by [linuxserver.io](https://linuxserver.io)
- Sonarr Version 3.0.9.1549
- Radarr Version 4.1.0.6175

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Can you test and confirm please?

**Comment by SteinX** [comment]
Sure

**Comment by SteinX** [comment]
It's no longer reproducible in the latest dev version
