### ISSUE TITLE
Manual search screen, incorrect column width.

### ISSUE THREAD

**Issue by BaukeZwart** [morpheus65535/bazarr#1957]
**Describe the bug**
Result screen after manual search isn't shown correct, Right column width is incorrect.
Tried on PC and mobile.

**To Reproduce**
1. Go to 'Manual Search'
2. Wait for results'
3. Right column width is incorrect.

**Expected behavior**
Right column to be wider, as it is now it's unreadable, specially on small screens like a phone.

**Screenshots**
![chrome_wm9mVUjxeE](https://user-images.githubusercontent.com/1872733/192271873-4fa2a7a7-c94c-418a-9e42-e35b93c7d817.png)

**Software (please complete the following information):**
 - Bazarr: v1.1.2-beta.10
 - Radarr version 4.3.0.6637
 - Sonarr version 4.0.0.124
 - OS: Synology/Docker Version: 7.1-42661 Update 2

**Additional context**

**Comment by morpheus65535** [comment]
Matches icon with tooltip is broken. @LASER-Yi will look into this.

**Comment by LASER-Yi** [comment]
Should be fixed in the latest beta version

**Comment by BaukeZwart** [comment]
I will test and let you know as soon as the new beta becomes available.

**Comment by morpheus65535** [comment]
@LASER-Yi is it just me or there still an issue with popop width? Matching block and not matching block were side by side before IIRC.

![image](https://user-images.githubusercontent.com/5130500/192501831-1ffc687f-cdc8-4f15-b137-9ffa0acfe7b4.png)

**Comment by LASER-Yi** [comment]
> @LASER-Yi is it just me or there still an issue with popop width? Matching block and not matching block were side by side before IIRC.
> 
> ![image](https://user-images.githubusercontent.com/5130500/192501831-1ffc687f-cdc8-4f15-b137-9ffa0acfe7b4.png)

Will be fixed in the upcoming beta version

**Comment by morpheus65535** [comment]
> Will be fixed in the upcoming beta version

Thanks!
