### ISSUE TITLE
Unmonitored series keeps monitored seasons as wanted

### ISSUE THREAD

**Issue by s1p2a3m** [morpheus65535/bazarr#1964]
**Describe the bug**
If you unmonitor a whole show in sonar (title bookmark icon becomes empty), the seasons monitor status stays like it's monitored (gray bookmark icon), but the buttons are disabled.
In bazarr the episodes are marked as wanted even though the whole show is unmonitored. If I mark the whole show as monitored (title bookmark icon gray) and then go to each season and mark it as unmonitored (bookmark icon empty) then they stop showing up as wanted.

**To Reproduce**
1. Go to sonarr monitored show (which has seasons/episodes that are marked as monitored)
2. Click on unmonitor show (near the title, not season/episode)
3. Go to bazarr wanted section
4. See episodes are still wanted

**Expected behavior**
Since the whole show is unmonitored, it should mark all episodes as unwanted (even though if the season or single episode is marked as monitored, since sonarr wont monitor them since the parent show is marked as unmonitored)

**Software (please complete the following information):**
 - Bazarr: 1.1.1
 - Radarr: 3.0.9.1549
 - Sonarr: 4.2.4.6635
 - OS: Linux-5.4.0-99-generic-x86_64-with-glibc2.31

**Comment by morpheus65535** [comment]
This one should be fixed in upcoming beta. Can you test and confirm please?

**Comment by s1p2a3m** [comment]
I've used swizzin to install it https://swizzin.ltd/applications/bazarr

How can I update it the upcoming beta?

**Comment by morpheus65535** [comment]
> How can I update it the upcoming beta?

I don't know. I do not maintain nor use this package.

**Comment by morpheus65535** [comment]
Yes it's beta.17

**Comment by s1p2a3m** [comment]
Ok, I'll check it out when I'll get the chance, hopefully today

**Comment by s1p2a3m** [comment]
It seems to be working correctly.

PS: You could have let me know that there was an auto update feature, I've been bashing my head because I was trying to manually update the files then after the service was started the changes were reverted and I couldnt understand why... then I saw the auto updater and in the check_update.sh that it has an option to update from master or development, so it was overriding my manual download, after selecting the development branch it worked.

**Comment by morpheus65535** [comment]
Good to know it's now working. BTW, the update script isn't mine. It must have come with the package.

**Comment by s1p2a3m** [comment]
I was referring to the auto update bazarr has https://github.com/morpheus65535/bazarr/blob/master/bazarr/app/check_update.py

Anyways, thanks for the quick fix!

**Comment by morpheus65535** [comment]
Hehe ok but you referred to a shell script (.sh). Any, enjoy! :-)
