### ISSUE TITLE
Language Profile - can't add 'contain' & 'not contain' strings

### ISSUE THREAD

**Issue by rastarr** [morpheus65535/bazarr#1965]
**Describe the bug**
The Language Profile contains a means to exclude subtitles based on a string.
With the current beta v1.1.2-beta.14, entering any string into the 'must contain' or 'must not contain' areas and pressing 'add' does not save anything.

This is a great feature if it worked since I prefer to not pollute my Thai subtitles with machine-generated releases since this language has a very poor result from Google Translate and others.

Being able to add strings like 'translatesubtitles' would go a long way towards eventually finding valid subs and stopping rubbish from being repeatedly downloaded.

**Software (please complete the following information):**
 - Bazarr: [v1.1.2-beta.14]
 - Radarr version [v4.2.4.6635]
 - Sonarr version [v3.0.9.1549]
 - OS: [Synology Docker]

**Additional context**
![CleanShot 2022-10-02 at 7 44 17](https://user-images.githubusercontent.com/2160922/193433330-c0882fde-7210-4545-aaff-9ccf04da9b9d.png)

**Comment by morpheus65535** [comment]
I can reproduce. Whatever we put in there isn't sent to backend. @LASER-Yi could you take a look once you're back from vacation please?
