### ISSUE TITLE
Addic7ed doesn't work

### ISSUE THREAD

**Issue by zeppelinlg** [morpheus65535/bazarr#197]
Bazarr doesn't find Addic7ed subtitle even in manual search. There is subtitle on website.

I use latest docker version for bazarr and sonarr

It seems Addic7ed work sometimes. I had some result with some episode but later they doesn't appear.

Login and password are filled and valid.

**Comment by morpheus65535** [comment]
Debug log?

**Comment by morpheus65535** [comment]
I close this issue. Feel free to reopen it if you still have the issue.
