### ISSUE TITLE
"Error 500 You have disconnected from the server" when trying to save language profile

### ISSUE THREAD

**Issue by Billyboii** [morpheus65535/bazarr#1971]
**Describe the bug**
On a fresh install, I've tried to create a new language profile. I get the message: "Error 500 You have disconnected from the server" when trying to save the page after configuring the settings for the profile.

**To Reproduce**
1. Go to 'Settings -> Languages"
2. Click on 'Add New Profile'
3. Add a default English profile and hit Save
4. Hit save at the top of the Languages settings page, then the error will appear in the bottom right corner.

**Expected behavior**
Settings should be saved with the new profile.

**Screenshots**
![bazarr error](https://user-images.githubusercontent.com/21184185/196052967-852235da-248e-4ae1-9c77-43fb41093f3a.png)

**Software (please complete the following information):**
 - Bazarr: v 1.1.2
 - Radarr version v 4.1.0.6175
 - Sonarr version v 3.0.9.1549
 - OS: Ubuntu 22.04.1 LTS 

**Additional context**
Other settings on the page will save (filter languages for example) just the language profile settings will not.

I have read through other issues here about similar errors, all suggesting different browsers or disabling security software. Tried upgrading to Python3.10. None of them have worked so far.
https://github.com/morpheus65535/bazarr/issues/435
https://github.com/morpheus65535/bazarr/issues/1942
https://github.com/morpheus65535/bazarr/issues/1924

**Comment by halali** [comment]
Duplicate #1968

**Comment by morpheus65535** [comment]
We'll follow this in #1924. I still cannot reproduce but got multiple report of still being an issue.

**Comment by beljim** [comment]
Same for me using Bazarr on Unraid and accessing via Windows. No issues with any other apps.
Tried Firefox, Chrome, Vivaldi and Edge on Windows. No add blockers. No luck.
***The only way I could proceed was via my Mobile phone.

**Comment by Th0rHere** [comment]
Just set up a brand new install of bazarr and having the exact same issue.
