### ISSUE TITLE
Searching for subtitles for a whole series doesn't work

### ISSUE THREAD

**Issue by vin047** [morpheus65535/bazarr#1977]
**Describe the bug**
When searching for subtitles for a series, the subtitles fail to download. But if I manually search for subtitles for individual episodes, the matching subtitle downloads correctly.

**To Reproduce**
1. Select series from home page.
2. Tap the "Search" button near the top.
3. Bazarr scans files and attempts to search but fails to download any subtitles.

**Expected behavior**
Full series search should find matching subtitles for each episode that are above the minimum threshold.

**Screenshots**
Here's some screenshots if I manually search for the subtitle for the first episode. As you can see, it does find a high matching value (my minimum threshold is set to 90%) albeit with some reasons for disqualifying.
![SCR-20221023-n7p](https://user-images.githubusercontent.com/1881273/197389299-1faef947-d94d-46c1-928f-a68c301f71a9.png)
![SCR-20221023-n7x](https://user-images.githubusercontent.com/1881273/197389302-d15c1ded-7874-4da3-95ce-5801bb577182.png)

**Software (please complete the following information):**
 - Bazarr: v1.1.2
 - Sonarr version: v3.0.9.1549
 - OS: macOS 10.13.3 High Sierra

**Additional context**
- The series is set to a language profile named "English" which is set to search for "EN" and "EN:FORCED", no cut off is defined as I want both subtitles if available.
- I only have opensubtitles.org as a provider.
- Attached debug log, which starts from when the search button is pressed. 
[bazarr.log](https://github.com/morpheus65535/bazarr/files/9846405/bazarr.log)

Looking at the logs, focusing on the first episode, I see some lines stating:
```
23/10/2022 11:40:19|DEBUG   |subliminal_patch.core           |Config changed. Restarting provider: opensubtitles|
23/10/2022 11:40:19|DEBUG   |subliminal_patch.providers.opensubtitles|Using timeout: 15|
23/10/2022 11:40:19|DEBUG   |subliminal_patch.providers.opensubtitles|Using HTTPS connection|
23/10/2022 11:40:19|INFO    |subliminal_patch.providers.opensubtitles|Only searching for foreign/forced subtitles|
```
I'm not sure why it says "only searching for foreign/forced subtitles" since I wish for both types. However, later on it does seem to search for both, and fails at downloading the full english subtitle:
```
23/10/2022 11:40:19|INFO    |subliminal_patch.core_persistent|Downloading best subtitles for <Episode ['My Wife and Kids', 1x1]>|
23/10/2022 11:40:19|INFO    |subliminal_patch.core           |Listing subtitles with provider 'opensubtitles' and languages {<Language [en]>, <Language [en:forced]>}|
23/10/2022 11:40:19|INFO    |subliminal_patch.providers.opensubtitles|Searching subtitles [{'moviehash': '908dc33cbfdbf990', 'moviebytesize': '2426348116', 'sublanguageid': 'eng,eng'}, {'imdbid': '0273855', 'season': 1, 'episode': 1, 'sublanguageid': 'eng,eng'}]|
23/10/2022 11:40:19|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): api.opensubtitles.org:443|
23/10/2022 11:40:19|DEBUG   |urllib3.connectionpool          |https://api.opensubtitles.org:443 "POST /xml-rpc HTTP/1.1" 200 1406|
23/10/2022 11:40:19|INFO    |subliminal_patch.core_persistent|Downloaded 0 subtitle(s)|
23/10/2022 11:40:19|DEBUG   |root                            |BAZARR No Subtitles were found for this file: /Volumes/G-RAID Studio Disk 1/TV Shows/My Wife and Kids/Season 1/My.Wife.and.Kids.S01E01.Pilot.WEBDL-1080p.x264.EAC3-Obfuscated.mkv|
```

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Can you test and confirm please?

**Comment by morpheus65535** [comment]
No news, good news.
