### ISSUE TITLE
Opensubtiles API key authentication

### ISSUE THREAD

**Issue by BoBeR182** [morpheus65535/bazarr#1982]
**Describe the bug**
OpenSubtitles provider does not use API to authenticate which allows for more downloads per day.

**To Reproduce**
1. Create a opensubtitles provider
2. No space to provide API key

**Expected behavior**
Allow API authentication

**Software (please complete the following information):**
- Bazarr Version 1.1.2
- Sonarr Version 3.0.9.1549
- Radarr Version 4.2.4.6635
- Operating System Linux-6.0.2-arch1-1-x86_64-with-glibc2.36

**Comment by halali** [comment]
Bazarr use its own api key... You need only your username and password.

**Comment by BoBeR182** [comment]
I have an API with more daily requests, how would I start using it?

**Comment by halali** [comment]
If you have VIP account, just put your username and password. You dont need any API key.

**Comment by BoBeR182** [comment]
My account has 20 downloads daily, my personal testing API key has 100.

**Comment by halali** [comment]
Do you really talk about opensubtitles provider? Because normall user have 200 downloads per day and VIP user have 1000

**Comment by morpheus65535** [comment]
There's no apikey with opensubtitles.org. I suppose he's talking about opensubtitles.com where the daily limit is unrelated to the apikey used but to your username status.

**Comment by BoBeR182** [comment]
Correct, as per their support page a Sub Leecher account can only download 20 a day. An account with an API can do up to 100.
![image](https://user-images.githubusercontent.com/525433/199321946-0d852213-c846-489c-b21d-a0050af55f20.png)

**Comment by morpheus65535** [comment]
There's no link between apikey and silver member. Bazarr is already using an apikey, I am in constant discussion with os.org/com admin and we are doing things the proper way. If you want more download, get an upgraded status.
