### ISSUE TITLE
Bazarr working on M1 Mac after 18 months of stuck at "installing requirements.txt"

### ISSUE THREAD

**Issue by dkids** [morpheus65535/bazarr#1984]
I've been unable to get Bazarr working for many months.   The symptoms are that I'd untag the latest version, run python3 bazaar.py, and it would loop at installing requirements.txt until I ^C'd it.

There was never anything on the screen or in the log indicating what was wrong.

Yesterday, I installed Plex Meta Manager and it failed like this:

Traceback (most recent call last):
  File "/Users/kids/src/Plex-Meta-Manager/plex_meta_manager.py", line 118, in <module>
    from modules.builder import CollectionBuilder
  File "/Users/kids/src/Plex-Meta-Manager/modules/builder.py", line 3, in <module>
    from modules import anidb, anilist, flixpatrol, icheckmovies, imdb, letterboxd, mal, plex, radarr, reciperr, sonarr, tautulli, tmdb, trakt, tvdb, mdblist, util
  File "/Users/kids/src/Plex-Meta-Manager/modules/tvdb.py", line 3, in <module>
    from lxml.etree import ParserError
ImportError: dlopen(/opt/homebrew/lib/python3.10/site-packages/lxml/etree.cpython-310-darwin.so, 0x0002): tried: '/opt/homebrew/lib/python3.10/site-packages/lxml/etree.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/python3.10/site-packages/lxml/etree.cpython-310-darwin.so' (no such file), '/opt/homebrew/lib/python3.10/site-packages/lxml/etree.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'

It took some doing, because even with export ARCHFLAGS="-arch amd64" set, pip insisted on making the x86_64 version of lxml. 

Eventually, I ran across references to manually downloading, compiling, and installing lxml.   That's what I did and that's the only thing that worked (for me, anyway).   Bazarr now seems to be operating great.   

I followed the instructions on https://stackoverflow.com/questions/71737316/problems-installing-lxml-on-m1-mac#comment130458015_72835621    You either need to add the ARCHFLAGS to your .{z|ba}shri or put them on the command line like ARCHFLAGS="-arch arm64" python3 setup.py bdist_wheel

My reason for posting this is that it would have been really helpful to have more verbose debugging.   There are only 4 requirements in requirements.txt but I had no idea where to look.

This is what the PMM install looks like.

pip install -r requirements.txt 
Defaulting to user installation because normal site-packages is not writeable
Collecting PlexAPI==4.12.1
  Downloading PlexAPI-4.12.1-py3-none-any.whl (147 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 kB 7.9 MB/s eta 0:00:00
Collecting tmdbapis==1.0.6
  Downloading tmdbapis-1.0.6-py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 kB 6.3 MB/s eta 0:00:00
Requirement already satisfied: arrapi==1.3.1 in /opt/homebrew/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (1.3.1)

Obviously this is a weird edge case that only Mac M1 users might have.     And there might be something wrong with my setup.  But I have lots of other programs running without any issues.  

Posting mostly so that if there are any other M1 users in the same boat, they'll have a recipe for what to do if they check closed issues.

**Comment by morpheus65535** [comment]
I'm not sure I get what you want from that issue... can you provide the log when you tried to install and got into a loop? Something for me to work on and improve user experience? If not I don't know what to do with that...

**Comment by morpheus65535** [comment]
No news, good news!
