### ISSUE TITLE
Unable to save changes to page size in Settings...UI

### ISSUE THREAD

**Issue by edsilberberg** [morpheus65535/bazarr#1987]
I am currently running v1.1.2

When I go to settings...UI... and attempt to change the page size from the default of 50 to any other number I am unable to save my changes.

The save button at the top does list one change to be made but no save ever completes. I have tried every value in the page size options list.

When I try to navigate away I get the "You have 1 unsaved changes, are you sure you want to leave?" message.

**Comment by edsilberberg** [comment]
The plot thickens! (Cue dramatic noises) using the provided workaround with a value of 250 or 500 in wanted… Episodes… My display counter shows  increments of 100 regardless of the 2 settings changes I attempted in  /config/config/config.ini  Same results in history… Episodes.
I've done a restart within the web interface from the gear as well as restarting my Docker instance

**Comment by morpheus65535** [comment]
@LASER-Yi something missing here I think... we use local storage but we don't use the config.ini value. Am I right?

**Comment by LASER-Yi** [comment]
> @LASER-Yi something missing here I think... we use local storage but we don't use the config.ini value. Am I right?

Yes, we are using local storage so if you change the browser the UI settings will be reset
