### ISSUE TITLE
When manual uploading substitle with"SRT" extension,  error of invlid format, but works all OK with "srt" extension

### ISSUE THREAD

**Issue by neotaburiss** [morpheus65535/bazarr#1988]
**Describe the bug**
When manual uploading substitle with"SRT" extension,  error of invlid format, but works all OK with "srt" extension

**To Reproduce**
1. Go to upload substitle with"SRT" extension
2. Click on upload
3. See error 500 (disconnected from server),
4. System log as below:

**Expected behavior**
Manual upload successful
![image](https://user-images.githubusercontent.com/78628322/202904881-daabd3b8-e122-4645-bbcb-c8b21900d090.png)

Bazarr Version
1.1.2
Package Version
release-671c5dd by [hotio](https://github.com/hotio)
Sonarr Version
3.0.9.1555
Radarr Version
4.3.0.6671
Operating System
Linux-4.19.94-Unraid-x86_64-with
Python Version
3.10.8
Bazarr Directory
/app/bin
Bazarr Config Directory
/config
Uptime
0d 00:16:30
Time Zone
Asia/Shanghai

**Comment by morpheus65535** [comment]
Should be fixe din upcoming beta. Thanks for reporting!
