### ISSUE TITLE
using bazarr as a service bazarr will not connect to sonarr until it is restarted

### ISSUE THREAD

**Issue by mhmm555** [morpheus65535/bazarr#1989]
**Describe the bug**
using bazarr as a service with mac bazarr will not connect to sonarr until it is restarted via the restart button in the ui, at which the user is required to go into the wanted tab and manually downloaded the episodes if they are showing.

logs if needed are attached bellow 

**To Reproduce**
1. Go to download a show from sonarr
3. Scroll down to files after download is completed
4. subtitle file not there

**Expected behavior**
download a show from sonarr and the subtitle file automatically get downloaded by bazarr which is running as a service

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 1.1.3-beta.22

 - Sonarr version: 3.0.9.1549
 - OS: [mac os ventura 13.0.1]

[bazarr.log](https://github.com/morpheus65535/bazarr/files/10054633/bazarr.log)

**Comment by morpheus65535** [comment]
`UnAuthorizedHubError` means that you provided an incorrect APIKEY for Sonarr.
