### ISSUE TITLE
Errors on installation  help

### ISSUE THREAD

**Issue by luisalves73** [morpheus65535/bazarr#1990]
ematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.macosx-10.9-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.macosx-10.9-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.macosx-10.9-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.macosx-10.9-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    creating build/temp.macosx-10.9-x86_64-3.8
    creating build/temp.macosx-10.9-x86_64-3.8/src
    creating build/temp.macosx-10.9-x86_64-3.8/src/lxml
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -DCYTHON_CLINE_IN_TRACEBACK=0 -I/usr/include/libxml2 -Isrc -Isrc/lxml/includes -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c src/lxml/etree.c -o build/temp.macosx-10.9-x86_64-3.8/src/lxml/etree.o -w -flat_namespace
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    Compile failed: command 'gcc' failed with exit status 1
    creating var
    creating var/folders
    creating var/folders/pz
    creating var/folders/pz/ktg_q7_n7fx49gkwkp2z84mw0000gn
    creating var/folders/pz/ktg_q7_n7fx49gkwkp2z84mw0000gn/T
    cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /var/folders/pz/ktg_q7_n7fx49gkwkp2z84mw0000gn/T/xmlXPathInitggztqba1.c -o var/folders/pz/ktg_q7_n7fx49gkwkp2z84mw0000gn/T/xmlXPathInitggztqba1.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    Perhaps try: xcode-select --install
    *********************************************************************************
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pz/ktg_q7_n7fx49gkwkp2z84mw0000gn/T/pip-install-xhsmwk5d/lxml/setup.py'"'"'; __file__='"'"'/private/var/folders/pz/ktg_q7_n7fx49gkwkp2z84mw0000gn/T/pip-install-xhsmwk5d/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/pz/ktg_q7_n7fx49gkwkp2z84mw0000gn/T/pip-record-j1nnz4na/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8/lxml Check the logs for full command output.
WARNING: You are using pip version 20.2.1; however, version 22.3.1 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -m pip install --upgrade pip' command.

**Comment by halali** [comment]
for support we have discord channel.

For issue fill issue template.
