### ISSUE TITLE
Error 500 "You have disconnected from the server" on subtitle search for specific episode, other episodes s

### ISSUE THREAD

**Issue by logoster** [morpheus65535/bazarr#1994]
**Describe the bug**
bazarr gives me an error 500 message saying i've disconnected from server, but only when searching for subtitles, and weirdly enough, only on this one specific episode, every other episode in this show searches just fine, and all the other shows were able to search just fine

**To Reproduce**
1. have doctor who (2005) season 2 episode 5 rise of the cyberman
2. click search for subtitles
3. wait for attempted search to error out
4. get error 500 "You have disconnected from server"

**Expected behavior**
i would expect that it would search my selected providers for subtitles, and then choose the best result it can find.

**Screenshots**
<img width="1361" alt="Screenshot 2022-11-24 at 11 51 57 AM" src="https://user-images.githubusercontent.com/5215622/203856355-0f5fe027-6e3a-49a3-b449-40586fe4e947.png">

**Software (please complete the following information):**
 - Bazarr: 1.1.2
 - Radarr version 4.2.4.6635
 - Sonarr version 3.0.9.1549
 - OS: Linux-5.4.0-99-generic-x86_64-with (it's a seedbox, i don't know the exact operating system they use)

Debug log is attached
 
[bazarr (1).log](https://github.com/morpheus65535/bazarr/files/10087047/bazarr.1.log)

**Comment by Blisk** [comment]
I have the same error can not save language settings

**Comment by morpheus65535** [comment]
> I have the same error can not save language settings

Unrelated, please check #1924

**Comment by morpheus65535** [comment]
@logoster this one should be fixed in upcoming beta. Can you test and confirm?

**Comment by Blisk** [comment]
> @logoster this one should be fixed in upcoming beta. Can you test and confirm?

I use it on qnap, don't know how to update and test?

**Comment by morpheus65535** [comment]
> > @logoster this one should be fixed in upcoming beta. Can you test and confirm?
> 
> I use it on qnap, don't know how to update and test?

Dude I'm not talking to you. Go to the issue I've refered to you earlier.

**Comment by Blisk** [comment]
ok thank you that worked

**Comment by morpheus65535** [comment]
No news, good news!
