### ISSUE TITLE
UI crashed on latest LSIO version

### ISSUE THREAD

**Issue by JDFS404** [morpheus65535/bazarr#1995]
**Describe the bug**
The message I'm getting (can't get past this screen):
```
RangeError: Invalid array length at Fg (http://********/assets/index.1094ca3e.js:784:102694) at Fu (http://********/assets/vendors.42674e4c.js:30:52884) at Os (http://********/assets/vendors.42674e4c.js:30:62361) at sd (http://********/assets/vendors.42674e4c.js:34:9591) at rd (http://********/assets/vendors.42674e4c.js:34:940) at Hp (http://********/assets/vendors.42674e4c.js:34:871) at Zn (http://********/assets/vendors.42674e4c.js:34:728) at Us (http://********/assets/vendors.42674e4c.js:32:10882) at http://********/assets/vendors.42674e4c.js:30:38716 at e.unstable_runWithPriority (http://********/assets/vendors.42674e4c.js:19:3822)
```

**To Reproduce**
1. Updated to latest LSIO docker
2. Open Bazarr on localhost:6767

**Screenshots**
![image](https://user-images.githubusercontent.com/26678110/204241142-e1e5ad8e-d603-44f5-b037-ede281dad256.png)

**Comment by morpheus65535** [comment]
What latest? 1.0.2 in master? 1.1.3-beta.X in development? Please provide the image tag.

**Comment by JDFS404** [comment]
> What latest? 1.0.2 in master? 1.1.3-beta.X in development? Please provide the image tag.

Latest master, sorry

**Comment by morpheus65535** [comment]
I've just pulled latest and it works as expected: lscr.io/linuxserver/bazarr:latest

![image](https://user-images.githubusercontent.com/5130500/204287356-73e25576-b614-4832-89fc-ec570df226b3.png)

**Comment by platj3** [comment]
I have the same issue on latest version.

**Comment by platj3** [comment]
docker, amd64 : latest

**Comment by platj3** [comment]
I think i found the issue. I managed to go to the settings page (settings page didnt gave me the error) and then UI. there I saw that the Page size value wasn't set. When I select 25 or an other value the problems went away.

**Comment by Kitt3120** [comment]
> I think i found the issue. I managed to go to the settings page (settings page didnt gave me the error) and then UI. there I saw that the Page size value wasn't set. When I select 25 or an other value the problems went away.

This fixed it for me. My error was:
```Fg@http://********/assets/index.a3eedeb0.js:784:102694 Fu@http://********/assets/vendors.42674e4c.js:30:52884 Os@http://********/assets/vendors.42674e4c.js:30:62361 sd@http://********/assets/vendors.42674e4c.js:34:9591 rd@http://********/assets/vendors.42674e4c.js:34:942 Hp@http://********/assets/vendors.42674e4c.js:34:873 Zn@http://********/assets/vendors.42674e4c.js:34:728 Us@http://********/assets/vendors.42674e4c.js:32:10882 Tf/<@http://********/assets/vendors.42674e4c.js:30:38716 e.unstable_runWithPriority@http://********/assets/vendors.42674e4c.js:19:3822 Ut@http://********/assets/vendors.42674e4c.js:30:38494 Tf@http://********/assets/vendors.42674e4c.js:30:38664 Qe@http://********/assets/vendors.42674e4c.js:30:38597 Zf@http://********/assets/vendors.42674e4c.js:32:11310 wm</t.flush/<@http://********/assets/vendors.42674e4c.js:34:28855```

**Comment by morpheus65535** [comment]
Thanks for reporting this issue! Should be fixed in upcoming beta. Improper value will be replaced by default value (25).

**Comment by JDFS404** [comment]
> > What latest? 1.0.2 in master? 1.1.3-beta.X in development? Please provide the image tag.
> 
> Latest master, sorry

Woops @morpheus65535 I was on `development`. After switching to `master `it got rid of the issue!
