### ISSUE TITLE
Don't access depreciated LanguageProfile API Endpoint in Sonarr v4

### ISSUE THREAD

**Issue by bakerboy448** [morpheus65535/bazarr#1998]
Sonarr v4 dropped the Language Profiles endpoint and now logs 
`2022-12-01 06:24:17.5|Warn|LanguageProfileController|API call made to deprecated endpoint from Bazarr/1.1.3-beta.26`

**Comment by morpheus65535** [comment]
Will be fixed in upcoming 1.1.3-beta.27. Thanks for reporting!
