### ISSUE TITLE
Change frame rate unusable due to rounding

### ISSUE THREAD

**Issue by Lunarpac** [morpheus65535/bazarr#1999]
Bazarr Version: 1.1.2
Package Version: v1.1.2-ls173 by linuxserver.io
Operating System: Linux-5.15.0-53-generic-x86_64-with
Python Version: 3.10.8

The change frame rate tool currently rounds numbers (i.e. 23,98 becomes 23, 23.98 becomes 24), which makes it impossible to accurately convert subtitles from say 23.98 to 25. I've yet to find another tool which allows changing frame rate in batch, so a fix here would be much appreciated!

Thanks for your work, loving Bazarr. :)

**Comment by morpheus65535** [comment]
Will be fixed in upcoming beta. Thanks for reporting!

**Comment by Lunarpac** [comment]
Sweet! Thanks for the quick fix!
