### ISSUE TITLE
Job "Update movies list from Radarr" raised an exception

### ISSUE THREAD

**Issue by DisturbedSun567** [morpheus65535/bazarr#200]
**Describe the bug**
I am unable to get subtitles for my movies due to the bug which states:

_Traceback (most recent call last):
 File "libs/apscheduler\\executors\\base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "C:\\Program Files\\bazarr\\get_movies.py", line 118, in update_movies
  store_subtitles_movie(path_replace_movie(added_path[0]))
TypeError: \NoneType\ object has no attribute \__getitem__\_

**To Reproduce**
1. N/A

**Expected behavior**
Expected job to complete and scan movies directory for missing subtitles. All movies are listed on the movie tab with the check mark stating that these paths all seem to be valid.

**Screenshots**
![image](https://user-images.githubusercontent.com/44451980/47468314-a109b880-d7c8-11e8-81f5-0bb9a23a5f00.png) --This continues for 52 pages with all items listed as valid paths

![image](https://user-images.githubusercontent.com/44451980/47468343-c0a0e100-d7c8-11e8-8b1d-ef4f954e2eb4.png)  -- All other aspects of the system appear to be working as expected, however, this same error continues happening

![image](https://user-images.githubusercontent.com/44451980/47468382-f0e87f80-d7c8-11e8-9bc2-a826decf28cf.png)  -- Radarr settings test successfully

![image](https://user-images.githubusercontent.com/44451980/47468393-0f4e7b00-d7c9-11e8-8013-a768b285fe40.png)  -- No path mappings are set which could potentially be throwing off the system.

**Software (please complete the following information):**
 - Bazarr: 0.6.6.3 
 - Radarr version 0.2.0.1120 develop
 - Sonarr version 2.0.0.5252
 - OS: ![image](https://user-images.githubusercontent.com/44451980/47468470-753b0280-d7c9-11e8-9c73-25779e3cd98c.png)  -- Running up-to-date Windows 10

**Additional context**

Library Information
-- 1,357 Movies
-- 3,233 Episodes

**Comment by morpheus65535** [comment]
Could you send me a copy of your bazarr.db? It seems you have a movie without a path. Would like to understand why...

**Comment by DisturbedSun567** [comment]
Here you go. I may have missed the movie in the list without the path as I
was going through looking to see if they all had check marks.
