### ISSUE TITLE
Wizdom.xyz provider when no subtitle is found

### ISSUE THREAD

**Issue by omrij** [morpheus65535/bazarr#2001]
When searching for subtitle and the subtitle is found, all is working OK
Like this one
https://wizdom.xyz/api/releases/tt2953050
But when no subtitle is found, like this one (movie or tv show)
https://wizdom.xyz/api/releases/tt17043230
It's disabling the provider for 10 minutes
This is the lig
`Throttling wizdom for 10 minutes, until 22/12/04 22:48, because of: HTTPError. Exception info: '500 Server Error: Internal Server Error for url: https://wizdom.xyz/api/releases/tt17043230'`

**Expected behavior**
Don't throttle the provider :)

**Software**
 - Bazarr: v1.1.2
 - Radarr version: 4.2.4.6635
 - Sonarr version: 3.0.9.1549
 - OS: lsio docker on unRAID 

Thanks in advance

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta.

**Comment by omrij** [comment]
Thank you
