### ISSUE TITLE
Subtitle search broken after 1.1.3 upgrade

### ISSUE THREAD

**Issue by Ellargo333** [morpheus65535/bazarr#2003]
**Describe the bug**
Error when trying to search for subtitles.

Job "Search for wanted Series Subtitles (trigger: interval[3:00:00], next run at: 2022-12-05 13:55:56 -03)" raised an exception.
Detail:
`Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/bazarr/bin/bazarr/subtitles/wanted/series.py", line 130, in wanted_search_missing_subtitles_series
    wanted_download_subtitles(episode[\'sonarrEpisodeId\'])
  File "/app/bazarr/bin/bazarr/subtitles/wanted/series.py", line 94, in wanted_download_subtitles
    _wanted_episode(episode)
  File "/app/bazarr/bin/bazarr/subtitles/wanted/series.py", line 47, in _wanted_episode
    for result in generate_subtitles(path_mappings.path_replace(episode[\'path\']),
  File "/app/bazarr/bin/bazarr/subtitles/download.py", line 63, in generate_subtitles
    if check_if_still_required and language not in check_missing_languages(path, media_type):
TypeError: argument of type \'NoneType\' is not iterable`

**To Reproduce**
1. Go to 'System'
2. Click on 'Tasks'
3. Click on 'Search for wanted Series Subtitles'

**Software (please complete the following information):**
 - Bazarr: [1.1.3]
 - Radarr version [4.2.4.6635]
 - Sonarr version [3.0.9.1549]
 - OS: [installed via Docker]

**Comment by morpheus65535** [comment]
Looks like an edge case where no episodes with that path have been found in database. I'll add some debug logging for that and gracefully get to the next missing subtitles instead of raising an exception.

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Can you test and confirm please?

**Comment by Ellargo333** [comment]
> Should be fixed in upcoming beta. Can you test and confirm please?

Hi!. How can I upgrade to Beta version in Docker?

Thanks

**Comment by Ellargo333** [comment]
> > Should be fixed in upcoming beta. Can you test and confirm please?
> 
> Hi!. How can I upgrade to Beta version in Docker?
> 
> Thanks
Already found it on the guide. I will tell you if the error is fixed. Thanks!

**Comment by Ellargo333** [comment]
@morpheus65535 well, now when I do a Search of wanted series, it does not crash, but it doesn't fetch any subtitle.

It only works if I manually click on each episode language search button.

![image](https://user-images.githubusercontent.com/7736405/205917667-110a52d4-5037-4fd0-8780-7934df4cd984.png)

That seach all button do not work.

![image](https://user-images.githubusercontent.com/7736405/205917774-c41bbe72-dfa8-4276-819f-53ac3dd08a4d.png)

Those individual search buttons do work.

**Comment by morpheus65535** [comment]
Then I guess you definitely have an issue with path. Please provide a complete debug log.

**Comment by morpheus65535** [comment]
`BAZARR no media with this path...`

Can you confirm if this file exist at this location?

**Comment by morpheus65535** [comment]
No news, good news. Please reopen if required.
