### ISSUE TITLE
UI is crashed. Invalid array length

### ISSUE THREAD

**Issue by BodingClockchian** [morpheus65535/bazarr#2006]
**Describe the bug**
`Fg@http://********/assets/index.a3eedeb0.js:784:102694 Fu@http://********/assets/vendors.42674e4c.js:30:52884 Os@http://********/assets/vendors.42674e4c.js:30:62361 sd@http://********/assets/vendors.42674e4c.js:34:9591 rd@http://********/assets/vendors.42674e4c.js:34:942 Hp@http://********/assets/vendors.42674e4c.js:34:873 Zn@http://********/assets/vendors.42674e4c.js:34:728 Us@http://********/assets/vendors.42674e4c.js:32:10882 Tf/<@http://********/assets/vendors.42674e4c.js:30:38716 e.unstable_runWithPriority@http://********/assets/vendors.42674e4c.js:19:3822 Ut@http://********/assets/vendors.42674e4c.js:30:38494 Tf@http://********/assets/vendors.42674e4c.js:30:38664 Qe@http://********/assets/vendors.42674e4c.js:30:38597 Gp@http://********/assets/vendors.42674e4c.js:34:6758 e.unstable_runWithPriority@http://********/assets/vendors.42674e4c.js:19:3822 Ut@http://********/assets/vendors.42674e4c.js:30:38494 Ot@http://********/assets/vendors.42674e4c.js:34:6042 Yp/<@http://********/assets/vendors.42674e4c.js:34:5956 Le@http://********/assets/vendors.42674e4c.js:19:2868 m.port1.onmessage@http://********/assets/vendors.42674e4c.js:19:1547 EventHandlerNonNull*@http://********/assets/vendors.42674e4c.js:19:1471 @http://********/assets/vendors.42674e4c.js:19:4441 `

Chrome console view gives me the following error
`vendors.42674e4c.js:32 RangeError: Invalid array length
    at Fg (index.a3eedeb0.js:784:102694)
    at Fu (vendors.42674e4c.js:30:52884)
    at Os (vendors.42674e4c.js:30:62361)
    at sd (vendors.42674e4c.js:34:9591)
    at rd (vendors.42674e4c.js:34:940)
    at Hp (vendors.42674e4c.js:34:871)
    at Zn (vendors.42674e4c.js:34:728)
    at Us (vendors.42674e4c.js:32:10882)
    at vendors.42674e4c.js:30:38716
    at e.unstable_runWithPriority (vendors.42674e4c.js:19:3822)`

**To Reproduce**
Visit bazarr thourgh webbrowser firefox/chrome/edge over HTTP

**Expected behavior**
When browsing the bazarr webpage the UI crashes

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/28387829/206455615-40e03d15-3f29-45b3-9f09-0ca62342a4e1.png)

**Software (please complete the following information):**
 - Bazarr: v1.1.3 stable
 - OS: Ubuntu 20.04.5 LTS
 - Docker version 20.10.5, build 55c4c88
 - Using linuxserver images

**Comment by morpheus65535** [comment]
Duplicate #2002. Fixed in dev branch.
