### ISSUE TITLE
Can't open web gui.

### ISSUE THREAD

**Issue by Richardraabu** [morpheus65535/bazarr#2008]
**Describe the bug**
Can't open web GUI, it just keeps loading, if i shut down Bazarr it displays "cannot connect". If i delete config file i can open web GUI until i add API key for Sonarr and Radarr, when i restart i can no longer open GUI. Don't know when this issue startet as i have not tried to open GUI in several months. There is one error when starting, see screenshot. Have tried with Firefox and Chrome.

**To Reproduce**

**Expected behavior**

**Screenshots**
![Bazarr](https://user-images.githubusercontent.com/41997671/206920277-dcb20493-b4f2-4f15-b6b2-a8318b60db62.PNG)

**Software (please complete the following information):**
 - Bazarr: 1.1.3
 - Radarr version: 4.2.4.6635
 - Sonarr version: 3.0.9.1549
 - OS: Windows 7

**Additional context**

**Comment by morpheus65535** [comment]
Why are you running Bazarr from a command prompt? It should be running as a Windows service.

**Comment by Richardraabu** [comment]
> Why are you running Bazarr from a command prompt? It should be running as a Windows service.

No idea, don't know how to do that.

**Comment by morpheus65535** [comment]
BTW you haven't told us what Python version you have. Also, Windows 7 is unsupported. It's an 11 years old deprecated operating system.

**Comment by morpheus65535** [comment]
> No idea, don't know how to do that.

When you use the Windows installer, it's the default behavior.

I'm closing this because this isn't an issue with Bazarr but a configuration question. Please move that to Discord support server.
