### ISSUE TITLE
Request for api to legendei.top provider. 

### ISSUE THREAD

**Issue by jotavip** [morpheus65535/bazarr#2011]
Hi. The brazilian subtitle provider legendas.tv has ceased their operations.

I wish tô request a api to search subtitles From provider legendei.top, it has a lot of subtitles and updates with New releases everyday.

Thanks.

**Comment by morpheus65535** [comment]
https://wiki.bazarr.media/Troubleshooting/FAQ/#im-missing-or-want-a-subtitle-provider-added-to-bazarr
