### ISSUE TITLE
Wizdom provider incorrect urls

### ISSUE THREAD

**Issue by idanlah** [morpheus65535/bazarr#2016]
**Describe the bug**
Wizdom provider has incorrect urls which returns no data
if fixed the issue in my branch but I can't open a PR

**Comment by morpheus65535** [comment]
You haven't forked the repo first. You need to fork it under your account, clone it, make changes, commit and push them. Then, you'll be able to create a PR.

**Comment by idanlah** [comment]
done https://github.com/morpheus65535/bazarr/pull/2017
tnx

**Comment by morpheus65535** [comment]
Fixed by 577a0d65428f950b0074307e21145258120f5769
