### ISSUE TITLE
No subtitle is downloaded for any of my series

### ISSUE THREAD

**Issue by EuSoyVictor** [morpheus65535/bazarr#2018]
**Describe the bug**
After Bazarr detects the new downloaded series, it tries to download the Romanian subtitles for them, using 2 providers, but fails...for every TV show possible. From what I've seen from the log, Bazarr actually skips downloading them 

> 17/12/2022 22:49:49|DEBUG   |subliminal_patch.score          |Scores to use for <Episode ['Breaking Bad', 2008, 1x5]>: {'hash': 359, 'series': 180, 'year': 90, 'season': 30, 'episode': 30, 'release_group': 15, 'source': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'streaming_service': 0, 'hearing_impaired': 1, 'edition': 0}|
> 17/12/2022 22:49:49|DEBUG   |subliminal_patch.score          |Matched hearing_impaired|
> 17/12/2022 22:49:49|INFO    |subliminal_patch.score          |Breaking Bad (2008): Computed score 271 with final matches {'year', 'series', 'other', 'edition', 'streaming_service', 'hearing_impaired'}|
> 17/12/2022 22:49:49|DEBUG   |subliminal_patch.core           |Breaking Bad (2008): Skipping subtitle with score 271, because it doesn't match our series/episode|

Every episode, from any series has this 271 score. On the log, I see the link with the subtitles, so I know that the providers are working, 100%. It is worth mentioning that Radarr has no problems at all, it downloads subtitles correctly. I've tried changing the minimum score on Bazarr, unchecking the Rename Episodes mark on Sonarr.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/10252733/bazarr.log)

**Software:**
 - Bazarr: v 1.1.3
 - Radarr version 4.2.4.6635
 - Sonarr version 3.0.9.1549
 - OS: openmediavault 6.0.46-1 (Shaitan)

**Comment by vitiko98** [comment]
Should be fixed in upcoming beta. Please reopen if you notice related problems.

**Comment by EuSoyVictor** [comment]
I can't reopen the issue. The problem with the skipped subtitle is fixed, but something else occurs now.

> 22/12/2022 21:06:29|DEBUG   |root                            |BAZARR Searching subtitles for this file: /movies/Seriale/Seinfeld/Season 2/Seinfeld.S02E12.1080p.WEBRip.x265-RARBG.mp4|
22/12/2022 21:06:29|DEBUG   |subliminal_patch.core           |No provider config updates|
22/12/2022 21:06:29|DEBUG   |subzero.video                   |Parsing video: Seinfeld.S02E12.1080p.WEBRip.x265-RARBG.mp4, hints: {'title': 'Seinfeld', 'type': 'episode'}|
22/12/2022 21:06:29|INFO    |subliminal_patch.core           |Determining basic video properties for 'Seinfeld.S02E12.1080p.WEBRip.x265-RARBG.mp4' in '/movies/Seriale/Seinfeld/Season 2'|
22/12/2022 21:06:29|DEBUG   |subliminal_patch.core           |GuessIt found: {
    "title": "Seinfeld",
    "season": 2,
    "episode": 12,
    "screen_size": "1080p",
    "source": "Web",
    "other": "Rip",
    "video_codec": "H.265",
    "release_group": "RARBG",
    "container": "mp4",
    "mimetype": "video/mp4",
    "type": "episode"
}|
22/12/2022 21:06:29|DEBUG   |subliminal_patch.core           |Size is 386561052|
22/12/2022 21:06:29|DEBUG   |subliminal_patch.core           |Computed hashes {}|
22/12/2022 21:06:29|DEBUG   |root                            |Running refiner: database|
22/12/2022 21:06:29|DEBUG   |peewee                          |('SELECT "t1"."title" AS "seriesTitle", "t2"."season", "t2"."episode", "t2"."title" AS "episodeTitle", "t1"."year", "t1"."tvdbId", "t1"."alternateTitles", "t2"."format", "t2"."resolution", "t2"."video_codec", "t2"."audio_codec", "t2"."path", "t1"."imdbId" FROM "table_episodes" AS "t2" INNER JOIN "table_shows" AS "t1" ON ("t2"."sonarrSeriesId" = "t1"."sonarrSeriesId") WHERE ("t2"."path" = ?)', ['/movies/Seriale/Seinfeld/Season 2/Seinfeld.S02E12.1080p.WEBRip.x265-RARBG.mp4'])|
22/12/2022 21:06:29|DEBUG   |root                            |Running refiner: ffprobe|
22/12/2022 21:06:29|DEBUG   |peewee                          |('SELECT "t1"."episode_file_id", "t1"."file_size" FROM "table_episodes" AS "t1" WHERE ("t1"."path" = ?) LIMIT ? OFFSET ?', ['/movies/Seriale/Seinfeld/Season 2/Seinfeld.S02E12.1080p.WEBRip.x265-RARBG.mp4', 1, 0])|
22/12/2022 21:06:29|DEBUG   |peewee                          |('SELECT "t1"."ffprobe_cache" FROM "table_episodes" AS "t1" WHERE ("t1"."path" = ?) LIMIT ? OFFSET ?', ['/movies/Seriale/Seinfeld/Season 2/Seinfeld.S02E12.1080p.WEBRip.x265-RARBG.mp4', 1, 0])|
22/12/2022 21:06:29|ERROR   |root                            |BAZARR **Error** ('mediainfo') trying to get video information for this file: /movies/Seriale/Seinfeld/Season 2/Seinfeld.S02E12.1080p.WEBRip.x265-RARBG.mp4|Traceback (most recent call last):  File "/app/bazarr/bin/bazarr/subtitles/utils.py", line 47, in get_video    refiner(original_path, video)  File "/app/bazarr/bin/bazarr/subtitles/refiners/ffprobe.py", line 35, in refine_from_ffprobe    if not any([data['ffprobe'], data['mediainfo'], data['enzyme']]):KeyError: 'mediainfo'|
22/12/2022 21:06:29|DEBUG   |root                            |BAZARR Ended searching Subtitles for file: /movies/Seriale/Seinfeld/Season 2/Seinfeld.S02E12.1080p.WEBRip.x265-RARBG.mp4|
22/12/2022 21:06:29|INFO    |socketio.server                 |emitting event "data" to all [/]|
22/12/2022 21:06:29|INFO    |engineio.server                 |UQEntvqn5yUDMX4PAAAA: Sending packet MESSAGE data 2["data",{"type":"episode","action":"update","payload":593}]|

**Comment by vitiko98** [comment]
That's not related to this issue.

Open a new issue with more info and append logs.

**Comment by morpheus65535** [comment]
It's a known issue fixed in upcoming beta.9
