### ISSUE TITLE
Part of the how much subs needed is out of border move it to the right like the rest.

### ISSUE THREAD

**Issue by TRaSH-** [morpheus65535/bazarr#202]
**Describe the bug**
Part of the how much subs needed is out of border move it to the right like the rest.
screenshot shows it all

**To Reproduce**
Goto series TAB and look

**Expected behavior**
It should line out with the right side

**Screenshots**
![image](https://user-images.githubusercontent.com/6155095/47601372-f2d05f80-d9cf-11e8-94a0-09012b135f3c.png)

**Software (please complete the following information):**
 - Bazarr: Bazarr Ver. 0.6.7
 - Radarr version [e.g. v 0.2.0.0001]
 - Sonarr version 3.0.0.266
 - OS: Debian Linux 9

**Additional context**

**Comment by morpheus65535** [comment]
It’s a UI framework bug, nothing I can do on my side. Waiting for a fix.
