### ISSUE TITLE
Opensubtitles.org not working -  Exception info: 'hbs'

### ISSUE THREAD

**Issue by DAndreyD** [morpheus65535/bazarr#2022]
**Describe the bug**
I have a number of providers set up that are all working fine, except opensubtitles. It's broken for more than half a year now. The login and everything is correct, but it gives out the error listed below, and it won't download any subtitles from there.

ERROR - Throttling opensubtitles for 10 minutes, until 22/12/22 09:45, because of: LanguageConvertError. Exception info: 'hbs'

**Software:**
 - Bazarr: 1.1.2
 - Radarr version 3.0.9.1549
 - Sonarr version 4.2.4.6635
 - OS: Linux-5.10.131+truenas-x86_64-with

**Comment by morpheus65535** [comment]
hbs means Serbo-Croatian. I don't see a single download for this language for the past year. Although it's a official language, it's probably unsupported by all providers. Remove it from your languages profile and use Serbian or Croatian instead.
