### ISSUE TITLE
[BUG] Can not save notifcation providers. Error 500: You have disconnected from the server

### ISSUE THREAD

**Issue by rdangdev** [morpheus65535/bazarr#2024]
**Describe the bug**
When trying to add a notification(could only try with discord so not sure if others work too), it does not save properly. I get a 500 error saying I've disconnected from the server.

**To Reproduce**
1. Settings -> Notifications
2. Click "+" -> Discord
3. Add a URL, and tested to be working.
4. Click save(from the add box)
5. Click save(from the settings)
6. Get a notification in the bottom right that says "Error 500: You have disconnected from the server"

**Expected behaviour**
It is supposed to save normally. 

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: v1.1.3
 - Radarr version v4.2.4.6635
 - Sonarr version v3.0.9.1549
 - OS: Linux(OMV6)

**Comment by morpheus65535** [comment]
Duplicate #2005.
