### ISSUE TITLE
mass edit does not allow deletion of subs

### ISSUE THREAD

**Issue by rmichelena** [morpheus65535/bazarr#2027]
maybe it's not a bug but a feature...
some webrips are imported by Sonarr with lots of unwanted subtitles (e.g. 20 languages or so)
I try to delete them using "mass edit", but "delete" is not allowed in Mass Edit it seems, the action is greyed out. 
The only alternative is deleting them one by one from the main show window, which is of course infinitely tedious.
The best way to do it would be a button to delete all the subtitles not specified in the show's profile. The second best way would be a button on mass edit to select all but the ones in the show's profile, and then being able to delete them. The third best way would be that the delete button is not greyed out in mass edit, that would still require manual selection but at least is some solution.
Currently I'm going into the show's directory, manually deleting the unwanted subs, and then rescanning the show in Bazarr.

**Comment by TRaSH-** [comment]
You can't delete embedded subs

**Comment by rmichelena** [comment]
Of course they're not embedded. And there's no way to ask the arr apps to import some languages and not others. And setting them to not import any subs would risk bazarr not finding them in the providers, besides it'd be a waste of resources to search for subtitles that are already available in the download.

**Comment by morpheus65535** [comment]
Bazarr API doesn't support mass delete.This is the expected behavior. You can open a feature request if desired.

**Comment by convexshiba** [comment]
If there's any reason this can't already inherently supported, would love to hear it.

If the ability already exists to loop through all files and apply (selected treatment), one would assume it's easily doable to just loop through the files and delete them.

For anyone who ended up here through searches, go here to upvote the new feature request. https://bazarr.featureupvote.com/suggestions/463444/mass-delete-subtitle-files
