### ISSUE TITLE
Strange DNS requests for yify

### ISSUE THREAD

**Issue by luispabon** [morpheus65535/bazarr#2029]
**Describe the bug**
I have enabled the yify subtitles provider and I'm getting a ton of errors on the logs like this one:

```
HTTPSConnectionPool(host='yifysubtitles.orghttps', port=443): Max retries exceeded with url: //yifysubtitles.ch/subtitles/johnny-english-strikes-again-2018-spanish-yify-3653 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f750f07beb0>: Failed to establish a new connection: [Errno -2] Name does not resolve')), retrying in 5 seconds...
```

If I check my pihole, I can confirm requests for resolving `yifysubtitles.orghttps` are coming in from bazarr.

**To Reproduce**
1. Enable yifysubtitles provider
2. Scan your library

**Expected behavior**
The correct host is used to query yify

**Screenshots**
![image](https://user-images.githubusercontent.com/6388823/210139141-211f280a-0eee-4bee-a65f-912f5b431894.png)
![image](https://user-images.githubusercontent.com/6388823/210139166-f35893f8-f8c0-4109-8a6a-73bc19074905.png)

**Software (please complete the following information):**
 - Bazarr: v1.1.3-ls176 by linuxserver.io
 - Radarr: 4.2.4.6635
 - Sonarr: 3.0.9.1549
 - OS: Ubuntu 22.04 / Docker

**Additional context**
n/a

**Comment by morpheus65535** [comment]
Will be fixed in upcoming release.

**Comment by luispabon** [comment]
👍
