### ISSUE TITLE
[Feature Request] Show in System a about with the info you need when reporting a bug (like Sonarr/Radarr)

### ISSUE THREAD

**Issue by TRaSH-** [morpheus65535/bazarr#203]
**Describe the solution you'd like**
Show in System a about with the info you need when reporting a bug (like Sonarr/Radarr)
![image](https://user-images.githubusercontent.com/6155095/47601416-8bff7600-d9d0-11e8-9a0d-55eb75b80425.png)
![image](https://user-images.githubusercontent.com/6155095/47601454-1d6ee800-d9d1-11e8-8fd0-aca07e6b09c7.png)

**Describe alternatives you've considered**
Show the info needed when you need to report a bug.
 - Bazarr: [e.g. v 0.6.1]
 - Radarr version [e.g. v 0.2.0.0001]
 - Sonarr version [e.g. v 2.0.0.0001]
 - OS: [e.g. Windows 10]
All except the OS can be found in Radarr somewhere already,
The version of Radarr and Sonarr show up when doing a Test.

**Comment by morpheus65535** [comment]
This one have already been implemented in system-->status.
