### ISSUE TITLE
Bazarr shouldn't throttle provider on guessit error

### ISSUE THREAD

**Issue by JuniperMS** [morpheus65535/bazarr#2034]
Opening at the request of morpheus65535.

This line of log is the important one: Throttling opensubtitlescom for 10 minutes, until 23/01/10 05:11, because of: GuessitException.

[bazarr (2).log](https://github.com/morpheus65535/bazarr/files/10382252/bazarr.2.log)

**Comment by morpheus65535** [comment]
Should be fixed by now. Did you had a chance to test latest beta?

**Comment by morpheus65535** [comment]
No news, good news!
