### ISSUE TITLE
"Sync episodes with Sonarr" creates roughly 2k DNS requests

### ISSUE THREAD

**Issue by honelnik** [morpheus65535/bazarr#2036]
Hi,

I have Bazarr running in docker, running a separate PiHole machine as the DNS server. 
Every time Bazarr tries to sync episodes with sonarr, Bazarr sends roughly 2.8k DNS requests for my sonarr server. 
Bazarr shows it's syncing 369 episodes in the lilttle "popup" showing progress.

The problem is that pihole rate-limits the host running Bazarr container due to excessive amount of requests. 
A workaround is to set-up the Sonarr connection with IP address instead of hostname.

Is this a normal behaviour?

**To Reproduce**
1. Run the "Sync episodes with Sonarr" task
2. After receiving few thousand DNS requests, pihole temporarily blocks Bazarr

**Expected behavior**
Bazarr caches the DNS entry or uses a single connection to poll the shows?

**Software (please complete the following information):**
 - Bazarr: 1.1.4
 - Sonarr version 3.0.9.1549
 - OS: Linux-5.15.0-57-generic-x86_64-with

**Comment by morpheus65535** [comment]
I'll explain some stuff here:
1.Bazarr sync episodes for 369 **series**, not episodes
2.The way Sonarr works, you have to do an API call for each series, one after the other, to get the episodes list.
3.Once your get the episodes list, you need to do one call per episode to get episode file info. So, for a single series of 19 episodes, it means 20 calls must be made to Sonarr API. If your have 369 series like that, it adds up to 7380 requests...
4.DNS caching is the responsibility of the operating system. If the DNS client query to get the IP for a FQDN, it get a TTL and will use this IP until the TTL is reached. Bazarr rely on the OS DNS client, if it doesn't deal properly with DNS caching, it's not up to Bazarr to deal with that.
5.The way HTTP works, you do a request, you get the response, the conenction is closed. You need something else? You do another request. There's no way to open a single connection and do call over it.
6.Why do you care about limiting DNS queries for cached entries? Pi-Hole will query the DNS server once and cache the result and serve it until the TTL is reached. Even a RPi can do that thousands of times every seconds.

**Comment by morpheus65535** [comment]
It seems that most Linux do not cache query by default: https://stackoverflow.com/a/11021207/2722651

Maybe you can try to add your sonarr and radarr IP to your host file? This should be used before making a query to DNS.

**Comment by honelnik** [comment]
I think I'm about to ready to give up at this point - the host machine is running Ubuntu 20.04.5 and indeed the sonarr's hostname is held in DNS cache for 5s, but bazarr keeps asking for it

I guess it's something finicky with DNS cache <-> docker implementation. Anyway - using IP address instead of hostname in bazarr's setting works for me

Thank you for your help

**Comment by morpheus65535** [comment]
It's my understanding also that docker rely on host DNS caching but even that your host should answer to Bazarr for every requests made during the 5 seconds TTL. If not, I guess your host caching is misonfigured or docker is not using it and simply call the DNS server. I think the later is probably the reason why you end up with many DNS queries from Bazarr.

This link could help understand: https://medium.com/@huynhquangthao/how-does-the-docker-dns-work-ab69bde4c82a

I'll be happy to know the ends of your investigation as it may shed some light on how it works. Let me know if you find out the final explanation.

**Comment by morpheus65535** [comment]
This could be intesting also: https://github.com/flaktack/systemd-resolved-docker

**Comment by morpheus65535** [comment]
Did you found a solution to your issue?

**Comment by morpheus65535** [comment]
No news, good news! Don't hesitate to update this issue with the solution you've found.
