### ISSUE TITLE
Remove LegendasTV provider as it is no longer active

### ISSUE THREAD

**Issue by eduardobobsin** [morpheus65535/bazarr#2037]
**Describe the bug**
LegendasTV provider is failing due to being discontinued.

**To Reproduce**
1. Go to 'Settings' -> 'Providers'
2. Add 'LegendasTV' as a new provider, click 'Save'
3. Trigger the search for series or movie subtitles

**Expected behavior**
No errors, possibly subtitles found and downloaded

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: [e.g. v 1.1.4]

**Additional context**
Check their page: http://legendas.tv/

**Comment by morpheus65535** [comment]
It's been removed in 1.1.4: https://github.com/morpheus65535/bazarr/commit/383d906749656491aedf333fda6fa8f50983c2bd

**Comment by oilervoss** [comment]
I was took by surprise as my Bazarr still shows legendas.tv provider. 

I suggest to set an announcement as for OpenSubtitles.Org (Opensubtitles.org will be deprecated soon, migrate to Opensubtitles.com ASAP and disable this provider to remove this announcement.)

**Comment by morpheus65535** [comment]
@oilervoss TBH, I was waitin to see if it would come back online. I guess we can simply remove it now. We'll leave to users the choice of replacement provider. It will be removed in next beta.
