### ISSUE TITLE
Language Cutoff Still Doesn’t Work

### ISSUE THREAD

**Issue by DanAykroyd256** [morpheus65535/bazarr#2038]
Hi,

I’ve been trying to use the Language Profile cutoff feature and it still doesn’t work. I saw mentions of this problem from users and @morpheus65535 in [GitHub](https://github.com/morpheus65535/bazarr/issues/1435) and [FeatureUpvote](https://bazarr.featureupvote.com/suggestions/54264/subtitle-language-priority); from years ago, so it should be working by now, but still doesn’t for me.

I’m running Bazarr 1.1.4 and I’m trying to achieve exactly the same thing the user at that GitHub thread mentioned; but with Latin American Spanish and Spanish instead of Brazilian Portuguese and Portuguese.

This is my setup for the Language Profile:
<img width="599" alt="image" src="https://user-images.githubusercontent.com/64184474/213784237-7952d6f6-c4b3-45b0-a668-ab0d49fe6301.png">

Whats happening is that I’m getting both Spanish variations and no english, for all files. After manually running search a lot of times, what I think is going on in the dozen of media items I tested this:

1) Bazarr searches, find or downloads Spanish first
2) Bazarr searches, find or downloads Latin American Spanish second
3) Bazarr doesn’t search anymore (for English), because it “found” the cutoff and stopped

I’ve tried every combination of cutoffs and language ordering in the profle (inverting the list, changing cutoff, etc.), but none would achieve what I wanted.

The desired result would be: **ALWAYS** download English, **ALWAYS** download Latin American Spanish, **CONDITIONALLY** download Spanish if not Latin American Spanish subtitle was found.

What I think its going on is that Bazarr seems to not search subtitles in the order ID specified in the Language Profile (I always seem to get ES, EA and EN - if Cutoff is not used), so the Cutoff is triggering in the wrong time; before searching English. As mentioned, not even changing the order of the languages in the profile affects the order in which I get them.

Thanks in advance for your awesome support on this!

**Comment by morpheus65535** [comment]
Bazarr doesn't care about the order of languages in the profile. You can't achieve what you want with cutoff. You have three choices:

- don't use cutoff and get all those 3 languages
- use one language as cutoff (ex: en) and as soon as it find English subtitles, it will stop looking for the others
- use `Any` as cutoff and it will stop looking for other languages as soon as it find one

Be aware that embedded subtitles are taken into account and `exclude audio` also.

**Comment by DanAykroyd256** [comment]
Thanks for the quick reply @morpheus65535.

I don’t understand then the point of “Cutoff” for this scenario. Cutoff implies a priority (do something until a certain desired state is reached). If the search for languages doesn’t in the order set up in the profile, what’s the point of doing a Cutoff value other than “Any”? Since you can guarantee the order in which you get the subtitles, it might as well be random where it will cut of:

- You might get EN, ES, EA and **CUT**
- You might get EA and **CUT**
- You might get ES, EA and **CUT**

Thanks.

**Comment by morpheus65535** [comment]
The point is that if I would like to have French subtitles but I'm ok with English one, I set 1 languages profile with French and English and set French as cutoff. If I find French first, it's fine, if not, I may get English until the day one French subtitles get released.

**Comment by dRoskar** [comment]
The cutoff feature as it is currently implemented makes no sense. Nobody needs a feature that finds one of the languages at random. Or that randomly downloads some of the languages and not others. People require a feature that let's them prioritize languages.

This should be re-opened and fixed.

**Comment by morpheus65535** [comment]
@dRoskar there's nothing to fix here. This is by design. It could be refactored or improved but this is a feature request and not a bug. Again, there's no language priority in profile.

**Comment by JurgenCruz** [comment]
Hi, I would like to request that the order of languages is actually considered. For some reason my Jellyfin instance does not like when I have both es.srt and es-MX.srt files so I would like to only download one.

The way I have it setup is:

1. Latin American Spanish
2. Spanish
3. English

With cutoff for Latin American.

My expectation would be, search for Latin Spanish, then, ONLY if not found, try searching for Spanish, then ONLY if still not found, search for English. It would be even better if in a second search it founds Latin Spanish and it already had Spanish, that it DELETES Spanish and leaves Latin Spanish.

Think of it like Radarr and Sonarr use qualities. Maybe they found a 720p version of the movie and they download it. Later a better version is found for 1080p, so it grabs it and DELETES the 720p version. And you can say 1080p is my cutoff so even if a 4k version comes, it won't download it cause you are fine with 1080p
