### ISSUE TITLE
Embedded EN:HI Subtitles Blocks Downloading of EN Subtitles

### ISSUE THREAD

**Issue by DanAykroyd256** [morpheus65535/bazarr#2039]
Hi,

I’m running Bazarr 1.1.4 on a large set of media items; configured from scratch, and noticed this one thing. If I choose the option in Settings to use the embedded subtitles and don’t download extra ones if the language is already present, I’ve noticed that if the embedded subtitle is for Hearing Impaired (in this case, EN:HI), Bazarr won’t download the EN subtitle; as it seems to think that it already is present in the media file (which is not).

There are mentions of this problem here in [Reddit](https://www.reddit.com/r/bazarr/comments/xsjhps/random_enhi_downloads/) and [GitHub](https://github.com/morpheus65535/bazarr/issues/69); from 2018, where @morpheus65535 mentioned that "There’s no way for me to detect if they are HI.”, which I think might be a thing of the past and there is a way to detect that now, as I see that Bazarr clearly marks if the media items have EN or EN:HI in grey, for embedded subtitles, and even many items have several EN and EN:HI in them.

The expected result would be, if I choose in my Language Profile that I want to download english and I also choose to respect the embedded subtitles already present in the media file (in order to not duplicate the same language with an external srt), Bazarr should still look to download the subtitle if the one present in the media is the HI variation. Those subtitles have a lot of extra information; not needed for me, like musical notes with songs, barking, planes noise, etc., so having a clean EN subtitle in SRT along the media file would be great for those cases where the embedded ones are only of the HI variation.

As always, thanks again!

**Comment by morpheus65535** [comment]
In Bazarr you can require HI but you can't exclude them. HI is considered as including normal subtitles so it will mark `en` as achieved if it already have `en:hi`.

If you have further questions, please come to Discord as this is an issue/bug tracking system.

**Comment by DanAykroyd256** [comment]
Thanks again for the quick reply @morpheus65535! You are great! :)

Does the other way round works, though? I mean, if the embedded subtitles are EN and my language profile has EN:HI, will Bazarr download the SRT for EN:HI (I assume it will)? So wouldn’t make sense for my proposed way to also work as well; using the same logic, for people that would like to have both regular and HI variations; combined with the already existing embedded ones?

**Comment by morpheus65535** [comment]
The other way works: if you require HI, you'll only get HI. I don't say your proposed way doesn't make sense, it's not just designed like this.
