### ISSUE TITLE
[Feature Request]  Make a filter option like Sonarr/Radarr for the log files

### ISSUE THREAD

**Issue by TRaSH-** [morpheus65535/bazarr#204]
**Describe the solution you'd like**
Sonarr/Radarr have a filter option for the log files to find fast if there're any issues.
![image](https://user-images.githubusercontent.com/6155095/47601506-1399b480-d9d2-11e8-9d5d-0e81ae6eefa2.png)

**Describe alternatives you've considered**
See scfeenshot

**Comment by rodalpho** [comment]
I would find something like this very useful. The real problem is the difference between debug and info log levels is huge. With info, I can't tell if the application is actually doing anything until after it's complete. And with debug, it scrolls multiple pages for each media file it examines.

**Comment by morpheus65535** [comment]
Already implemented.
