### ISSUE TITLE
Bazarr Not Retrieving Subtitles - Wanted ~4,000 series, 600 Movies

### ISSUE THREAD

**Issue by godman84** [morpheus65535/bazarr#2041]
**Describe the bug**
I'm new to Bazaar. I have plenty of series and movies waiting in the queue in Bazaar trying to find subtitles. The subtitles I have to look for are 1) English, 2) English Forced. I have a VIP account on OpenSubtitles, which I used as my provider. Bazaar has retrieved subtitles for some of the media previously, so I know its not an access or permissions issue and it see's all of my Sonarr / Radarr library. I don't know why it is hitting a wall and not continuing to locate the rest of the subtitles. 

**To Reproduce**
1. Go to Wanted
2. Click on Episodes/Movies and then click Search All
3. It may search the episodes/movies for a tiny bit, then stops and no subtitles are added

**Expected behavior**
I'm expecting subtitles to be found for the media in my library. 

**PasteBin**
https://pastebin.com/jDALtUnP

**Software (please complete the following information):**
 - Bazarr: v1.1.4
 - Radarr version 4.3.2.6857
 - Sonarr version 4.0.0.361
 - OS: Windows 11

**Additional context**
My Setup:
1) Windows 11 PC running Bazaar, Radarr, Sonarr, Prowlarr, Qbittorrent (only running on this PC)
2) Synology NAS DS1817 that has all my media saved
3) Ubuntu Desktop - Running my Plex Media Server (only thing running)

Things I've tried - made no difference:
1) Completely Removed Bazaar and doing a clean install
2) Manual Checks for subtitles may or may not work - sometimes it doesn't even hit the log

![Bazarr Home Screen](https://user-images.githubusercontent.com/32034602/213939292-84078653-941c-467c-884d-cf40c547850f.png)

![Bazarr Episode History](https://user-images.githubusercontent.com/32034602/213939298-b73eb1e0-e725-42ce-918b-1e93531359c7.png)

![Bazarr Movie History](https://user-images.githubusercontent.com/32034602/213939309-d648e9c0-b486-4e9e-a7f9-f9c4a1d98d3d.png)

![Bazaar Subtitle Options](https://user-images.githubusercontent.com/32034602/213939540-9a409cbe-3cdc-4e3a-9ed8-4e197070d919.png)

![Bazaar Subtitle Performance Optimization](https://user-images.githubusercontent.com/32034602/213939548-0937b003-5c90-45b6-8389-e5a5a1889164.png)

![Bazaar Subtitle Post Processing](https://user-images.githubusercontent.com/32034602/213939551-c92870c0-9211-48a9-b2ba-b053ce6bfc54.png)

**Comment by godman84** [comment]
I was able to figure it out - had to do with forced subtitles...

**Comment by godman84** [comment]
I was able to figure it out - had to do with forced subtitles...

**Comment by hugomickael** [comment]
Hi, I think I have the same issue. What have you done to solve it? Regards ,

**Comment by driesmp** [comment]
What did you change to make it work?

**Comment by bee-san** [comment]
Go to:
Settings -> Tasks -> Search for Missing Series Subtitles

By default Bazarr auto downloads every 6 hours, you need to force it to do that now.

I assumed you just installed it like me and wondered why there's no subs :)
