### ISSUE TITLE
All Latin American Spanish subtitles marked as "eligible for upgrade"; even with high score

### ISSUE THREAD

**Issue by DanAykroyd256** [morpheus65535/bazarr#2046]
Hi @morpheus65535,

All the Latin American Spanish subtitles that I’m downloading get marked for upgrading; even when they have higher scoring that the others (English and Spanish) that I’m also downloading with my profile. None of those two languages got a single one marked for upgrading; all the Latin American Spanish ones do, no matter the scoring I’m getting.

This is my profile:
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/64184474/214887725-98f51c71-00ab-4904-91aa-f5f2ec18817f.png">
<img width="704" alt="image" src="https://user-images.githubusercontent.com/64184474/214887768-ae6f3828-cb10-472c-a4a3-3ddcfb62b584.png">

As mentioned, I’m running a fresh Bazarr (1.1.4) installation and I started seeing this behavior on the first couple of subtitles that go downloaded. Now, overnight, I have downloaded 200+ for Episodes and 200+ for Movies and all act the same:

![image](https://user-images.githubusercontent.com/64184474/214884748-429b40e3-38ef-49d9-9a56-8d201e1d843f.png)

In all of the Movies download history, I only see one English subtitle marked for upgrading, with a score of 86.67%, when, for another movie, a score of 77.5% for the English subtitle, doesn’t get marked for upgrading:

<img width="1375" alt="image" src="https://user-images.githubusercontent.com/64184474/214885191-651205a4-ef64-4e76-ae03-e130a475bdf2.png">

I don’t know if I don’t understand the upgrading logic, but I don’t think this makes much sense. Again, in my fresh installation of Bazarr,  have set it to look for upgrades for the max amount of days possible (30), and all of these were downloaded a few hours ago, with minutes of difference between each other, so it’s not that setting that is affecting this neither

I can post the log but it doesn’t indicate anything related to scoring or criteria. Do you need me to set it to a higher Debug level and keep downloading (no way to see what happened with this already downloaded)?

Thanks

**Comment by morpheus65535** [comment]
@DanAykroyd256 is it still an issue with latest beta?

**Comment by morpheus65535** [comment]
No news, good news!
