### ISSUE TITLE
Utilities.binaries.BinaryNotFound

### ISSUE THREAD

**Issue by justbest23** [morpheus65535/bazarr#2049]
I've got Bazarr running on launch with a systemd unit file. It's been running fine for about a month, and is now failing with the following:

```
Jan 30 06:09:29 troggoman-Super-Server bazarr[11248]:     from init import *  # noqa E402
Jan 30 06:09:29 troggoman-Super-Server bazarr[11248]:   File "/home/troggoman/bazarr/bazarr/init.py>
Jan 30 06:09:29 troggoman-Super-Server bazarr[11248]:     init_binaries()
Jan 30 06:09:29 troggoman-Super-Server bazarr[11248]:   File "/home/troggoman/bazarr/bazarr/init.py>
Jan 30 06:09:29 troggoman-Super-Server bazarr[11248]:     raise BinaryNotFound
Jan 30 06:09:29 troggoman-Super-Server bazarr[11248]: utilities.binaries.BinaryNotFound
Jan 30 06:09:30 troggoman-Super-Server bazarr[11243]: Bazarr starting...
Jan 30 06:09:30 troggoman-Super-Server bazarr[11243]: Bazarr exited.
Jan 30 06:09:30 troggoman-Super-Server systemd[1]: bazarr.service: Deactivated successfully.
Jan 30 06:09:30 troggoman-Super-Server systemd[1]: bazarr.service: Consumed 2.446s CPU time.

```

**Software:**
 - Bazarr: v1.1.4
 - Radarr version 4.3.2.6857
 - Sonarr version 3.0.9.1549
 - OS: Ubuntu 22.04.1 LTS

**Additional context**
I've tried setting "Use Radarr" and "Use Sonarr" to False and that didn't work. I also tried reinstalling Bazarr and that hasn't worked either. 

Any help would be greatly appreciated! Can't watch without subtitles!

**Comment by morpheus65535** [comment]
Probably missing unrar.

**Comment by justbest23** [comment]
Heyo. Yep. Turns out just running `sudo apt install unrar` fixed it. I wonder where unrar went though. Because Bazarr was working fine previously. Thanks for the quick reply!
