### ISSUE TITLE
Subtitles aren't showing up-Cannot download 

### ISSUE THREAD

**Issue by Escondido** [morpheus65535/bazarr#205]
This software is really cool. I have it installed on Ubuntu 16.04 with all the required dependencies.

All of my tv shows/movies show up correctly, however, the program isn't showing any of the subtitles. Next to each tv show/movie I see an icon that says, "this path doesn't seem to be valid." It's a mounted drive.  I assume the program is pulling the data from Sonarr/Radarr and not my mounted drive. I left path mapping or tv shows/movies blank 

The series seems to display the number of episodes in green. I'm not entirely sure why the software parses all the shows/movies, but cannot access the subtitles contained within those folders. I assume it's a permission issue or something I'm missing.  The structure for the mounted folder is as follows;
 
mount/media/tv
Show Name
  Season 1
    showname,s01e01.mkv
    showname,s01e01.srt
    showname,s01e01.en.srt
    showname,s01e02/mkv
     blah blah blah 

mount/media/movies
Movie Title (2018)
 movietitle 2018.mk4
 movietitle 2018.srt
movietitle 2018.en.srt

Anybody know what might be the issue. I'm thinking it's a read/write issue, but I'm not sure.

**Comment by morpheus65535** [comment]
Bazarr do not scan disk to detect media file, it get them from Sonarr/Radarr. When it get an episode path, it have to analyze this file to index existing subtitles. For that, he need to have read access to the file (write acces to save downloaded subtitles later on). 

Does Sonarr access an episode file trough the path than Bazarr? If not, you need to configure path mapping so Bazarr is able to replace the part of the path that is different.

Ex.: 
Sonarr access episode like this: /media/tv/24/Season 01/s01e01.mkv
Bazarr access the same episode like this: /mytvshows/24/Season 01/s01e01.mkv

Your path mapping rule would be: /media/tv —> /mytvshows

**Comment by Escondido** [comment]
I got it to work after modifying the folders. Thanks for the help.
