### ISSUE TITLE
Bazarr marks every single show and movie as English Audio when it's not. And that is an issue. 

### ISSUE THREAD

**Issue by Arturoe1** [morpheus65535/bazarr#2050]
**Describe the bug**
Why is all the shows and movies shown in english when the audio track  in the movies / shows  clearly states is not. 

**To Reproduce**
1. In Bazarr specify "Exclude Audio"
2. use Radarr / Sonarr to download a show in foreign language with interactive search 
3. check Bazarr marks the language is in English although the show it is not. 

**Expected behavior**
I expect Bazarr to use the audio track metadata from each file  to decide whenever to exclude the file from subs search. 

**Software (please complete the following information):**
 - Bazarr: 1.1.4
 - Sonarr version 3.0.9.1549
 - OS: Docker

**Additional context**
I do not understand why this is not implemented already, there is no point to have the option "Exclude Audio" if Bazarr will use Sonarr/Radarr default system-wide option. If you download foreign movies ( anime, eurpoean movies, asian movies) they are all marked as English when even Plex shows the tracks as other languages or unknown. 

So currently Bazarr does not add any value, OR i have to download the subs manually OR i set it to download all and saturate the providers. It really needs to work with the audio tracks metadata. 

If it's very taxing on the system just inform of that when activating the flag the same as Sonarr / Radarr do when activating "Analyze media".

**Comment by morpheus65535** [comment]
![image](https://user-images.githubusercontent.com/5130500/215589560-2ea26e95-5e10-48d9-b4da-360bb21ba615.png)

![image](https://user-images.githubusercontent.com/5130500/215589393-f1be73ce-3070-43de-9492-c8f43a46d34f.png)

**Comment by Arturoe1** [comment]
Look one example of many complains: 
![image](https://user-images.githubusercontent.com/58043011/215611676-e9b1af60-205c-48ea-a069-c06c1e3a7df3.png)
![image](https://user-images.githubusercontent.com/58043011/215611706-f814b681-6ea0-4ced-b642-c503e34c29b7.png)

I am just asking to use the **actual audio track id from the video** instead whatever you are using now. For most Asian/European shows it fails. 

Radarr fails from time to time, sometimes it gets the language right other it simply doesn't.

It doesn't matter if it works for your french shows, the truth is still it fails. Probably most give up and just forget about bazarr but i do believe this is not an impossible fix.

**Comment by morpheus65535** [comment]
I don't say it cannot be improved by scanning the file ourself, all I say is that's the expected behavior because we are using the information provided by Sonarr. What's the media info for this episode in Sonarr? In my case, this is what I see:

![image](https://user-images.githubusercontent.com/5130500/215634350-0e833de3-d491-4063-852b-95ad80b8e304.png)

You're bashing on my French content but it could be any goddamm language... this is what's reported by Sonarr. It works also with half a dozen language I have on disk to test. This does work as expected, it's just not the result you expect and I can get that. Let just agree that garbage in, garbage out apply here: if Sonarr provide shit, we live with it.

I'm open to improvement and I hope you get that. Once we get out of the way that the actual behavior is what can be expected taking into account the way it's actually coded, we can move on and talk about improvement.

**Comment by halali** [comment]
i think Sonarr have its own file analyse, if its enabled... its useless do twice what was already done. else someone will complain his hdd is spining too much because bazarr do extra file analyse for nothing

**Comment by Arturoe1** [comment]
> I'm open to improvement and I hope you get that. Once we get out of the way that the actual behavior is what can be expected taking into account the way it's actually coded, we can move on and talk about improvement.
Yes I'm not saying Sonarr is great although this is probably coming from the TVDB (or where ever Sonarr gets the info) and the fact i am searching the names in English. I guess if the show is dubbed and i search for the name in English the shows returns the audio as the dubbed one. Sonarr has many pending issues but i think this Bazarr shortcoming can not be blame fully on Sonarr. 

Picking French shows is an important point: very little French TV shows are dubbed to English. A lot of movies is the same. So it's more rare to find this issue happening when you pick those. Not that is see that as a problem as i preffer in original soundtracks  and that's why i need Bazarr to do it's thing. 

Why is not the expected behaviour? Because of this:
![image](https://user-images.githubusercontent.com/58043011/215959778-6f379080-0cbd-458f-9624-faddecb55639.png)
So when i pick "Exclude Audio" i do expect the actual Audio from the file to be used. In any case it makes no much sense to use Sonarr info as you see the info returned is not confiable and Sonarr / Radarr do not show it and don't provide any options to adjust it.

I can think in many cases where i would need to download subs even when the show is originally English: You download a dubbed version for whatever reason (listening the dubbed for learning or fun purposes)  for example. Or there is only that dubbed version available because how distribution works. 

Bazarr already does check the files i think it could take advantage of that to retrieve the audio tracks language.

**Comment by morpheus65535** [comment]
I'm currently working to reuse ffprobe cache for audio language. I'm also adding an option to treat undefined audio track language as one that you specify (global parameter). I'll add this settings for undefined language embedded subtitles track at the same time.

**Comment by morpheus65535** [comment]
@Arturoe1 it should be good in upcoming beta.13. Can you test and confirm please?

**Comment by siankatabg** [comment]
I didn't researched if my "issue" is related (don't have the time right now) and I didn't had the issues that the op has, but yesterday bazarr downloaded a bunch of English and Bulgarian subtitles on movies and shows that were fine in my collection for at least an year without a single change in the configs and the changes in this ticket sounds like the reason. I'm not complaining, 
yeah, it was working better for me before, but it's just for a few of them(probably those with the und language?), so I'm fine with that, just a feedback 👍

**Comment by morpheus65535** [comment]
> I didn't researched if my "issue" is related (don't have the time right now) and I didn't had the issues that the op has, but yesterday bazarr downloaded a bunch of English and Bulgarian subtitles on movies and shows that were fine in my collection for at least an year without a single change in the configs and the changes in this ticket sounds like the reason. I'm not complaining, yeah, it was working better for me before, but it's just for a few of them(probably those with the und language?), so I'm fine with that, just a feedback 👍

Bazarr previously used the audio languages provided by Sonarr and Radarr. Sometime, it was simply the language of the audio profiles so it was accurate at all. Now we use the real languages tags from the media file. If desired, you can treat undefined languages as a specific one but it's not enabled by default and undefined are just ignored.

Thanks for the feedback by the way!

**Comment by Dnkhatri** [comment]
> I'm currently working to reuse ffprobe cache for audio language. I'm also adding an option to treat undefined audio track language as one that you specify (global parameter). I'll add this settings for undefined language embedded subtitles track at the same time.

an undefined language track should be the original language of the show. I have shows with chinese, japanese, korean languages which have an undefined language in the video file.

**Comment by morpheus65535** [comment]
> an undefined language track should be the original language of the show. I have shows with chinese, japanese, korean languages which have an undefined language in the video file.

`Treat undefined as` is a last resort solution. You should always make sure to have your track properly identified.

We don't keep track of the original language. I know that beta Sonarr API can provide this bit I have no idea since when.

This could be an improvement in the future. As always, I'm open to PR.

**Comment by Arturoe1** [comment]
`This could be an improvement in the future. As always, I'm open to PR. `
If a may add something just treat “undefined” as undefined. Means always look for the subs. 

I would say do this to keep it simple, let the owner of the video just pick a good video with proper tags. 
for me it would be more than enough if just check the audio tracks and download if the audio tracks do not fit the sub language profile.

**Comment by morpheus65535** [comment]
> If a may add something just treat “undefined” as undefined. Means always look for the subs.

Unless I do not understand what you meant, this is exactly what Bazarr does: index undefined as `None` language and ignore it when calculating missing subtitles (desired subtitles minus existing subtitles minus cutoff reached minus exclude audio).

**Comment by Arturoe1** [comment]
`index undefined as None language and ignore it when calculating missing subtitles `
My apologies: I meant “none” or “undefined” audio meta tags  means search always for the subtitles. 

But this is in base to the video audio meta tags, not the sonarr information as we already know the info they send is not good (at least with the stable branch)

Even if the info is good it could be the case we download a video in a different language because reasons (availability, learning new languages, a dub could be fun) . Sonarr does not seem to be reading the video audio meta tags at all. At least in my experience.

**Comment by morpheus65535** [comment]
@Arturoe1 in the upcoming beta, default will be to use Sonarr/Radarr but there's a toggle in Settings-->Languages to enable deep inspection of media file to get audio tracks languages. You're going to have to enable it if you want to keep using the "real stuff".
