### ISSUE TITLE
Repeated error "Error trying to get releases from Github. Http error." using docker-compose

### ISSUE THREAD

**Issue by AfricaByTot0** [morpheus65535/bazarr#2053]
**Describe the bug**
Repeated errors trying to use Bazarr on docker-compose. 

**To Reproduce**
1. Install bazarr through docker-compose (attached below)
2. Use `docker-compose up -d`
3. Go to `localhost:6767`

**Expected behavior**
To see Bazarr up and running.

**Software (please complete the following information):**
 - Bazarr: Latest version
 - Radarr version 4.3.2.6857
 - Sonarr version 3.0.9.1549
 - OS: [Ubuntu server 22.04.1]

**Additional context**
Docker compose for bazarr:
` version: "3"
services:
        bazarr:
                container_name: bazarr
                image: cr.hotio.dev/hotio/bazarr
                environment:
                        - PUID=1000
                        - PGID=1000
                        - TZ=NZDT+13
                volumes:
                        - '/home/${USER}/server/configs/bazarr:/config'
                        - '/home/${USER}/server/media:/movies'
                        - '/home/${USER}/server/media:/tv'
                ports:
                         - '6767:6767'
                restart: unless-stopped `

Logs (full of this repeating):
`01/02/2023 15:04:39|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|`

**Comment by halali** [comment]
Yoi exeeded limit for api cals, you probably make lots of api cals somehow...

Wait aome time and it will work

**Comment by morpheus65535** [comment]
It could be something like PiHole preventing connection to github.

**Comment by AfricaByTot0** [comment]
> Yoi exeeded limit for api cals, you probably made lots of api cals somehow...
> 
> Wait aome time and it will work

The issue is I've had this issue for ages and whenever I wait it never works. All of my other docker containers are up no issue. Is there a way to see my API requests so I can curb the excessive ones?

**Comment by morpheus65535** [comment]
Bazarr is doing one call to the Github API every 6 hours to get releases. If Github prevent you from doing this and return a 403 (rate limit exceeded), it's because your IP is making a enormous amount of call to the API another way. From what I've read, the rate limit is 5000 calls every hour. Bazarr isn't responsible for that. You'll have to investigate what other piece of software is doing that.

**Comment by dreondre** [comment]
I'm running into the same problem and I'm suspecting the rate limit is caused by Bazarr restarting itself over and over again because of a different problem. The rate limit is a symptom of the actual problem, especially if running multiple instances.

Currently, I'm poring over debug logs to see if I can figure out on my own where the problem is.

**Comment by AfricaByTot0** [comment]
I've talked to github and done everything I could but I finally got it up. I changed  my time zone format away from "NZDT+13" and to "Pacific/Auckland". YMMW but that fixed the issue for me.

**Comment by morpheus65535** [comment]
@AfricaByTot0 where did you see that NZDT+13 could be a correct value for timezone? With LSIO and hotio images, you must use TZ database name. Here's a list of all possible values: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by AfricaByTot0** [comment]
Probably just me being dumb, definitely not on any official guides. Lesson learnt the hard way I guess
