### ISSUE TITLE
UK tv show “Better” mixed up with US tv serie “Better Call Saul” (provider: gestdown)

### ISSUE THREAD

**Issue by alneven** [morpheus65535/bazarr#2077]
**Describe the bug**
hello there,
as discussed in Discord
I have the UK show Better in my downloads and wanted to download ENG subtitles for it. The show has already 3 aired EPs. So today I turned the download of ENG sub in bazarr on and got very fast all the 3 episode matching sub downloaded. This was a bit odd for me, therefore I run the manuall search and checked the release group was LOL (old scene group, not even active in the UK). So I clicked the button to download the sub on my device and saw it is for Better Call Saul.
Then I asked for some advise on Discord and we came to the fact that this shouldn’t be the case even the tv show Better not yet exists on addic7ed (!)

**To Reproduce**
1. Go to Sonarr, add the UK tv show Better, download of the 3 released episodes
2. Check it in Bazarr, add the provider gestdown
3. Search
4. Verify entries / download the sub to your device (not server)

**Expected behavior**
Message: no subtitles found

**Screenshots**
![C178EA53-5C65-483C-800D-2569A6A21264](https://user-images.githubusercontent.com/16620485/221797724-492b5d4d-764d-4104-854b-9dd1f9567f67.jpeg)
![6F6492F5-2691-4C0E-9273-55F329852F89](https://user-images.githubusercontent.com/16620485/221797739-fbdd8db5-c5a7-49c9-ac3a-e7100dabae47.png)
![35AB81A2-67BF-4C3C-976A-88BE6D5FF5BD](https://user-images.githubusercontent.com/16620485/221797756-444d93e6-f763-482f-9da9-86c547f471a5.jpeg)
![2EFE2A96-6AD9-47C8-B6AF-8EDFAF9AF48A](https://user-images.githubusercontent.com/16620485/221797758-e0aab933-9d4f-4ee7-b7a0-edc7d04e2e95.jpeg)
![B9489BFE-9CCC-4D66-ACA7-80F3455B50A3](https://user-images.githubusercontent.com/16620485/221797761-ad143d09-929d-4c36-8e8e-20002a941f98.jpeg)
![BB049B7D-4C2C-458B-BE23-EC656E80A0B1](https://user-images.githubusercontent.com/16620485/221797763-06c36179-7eb9-4351-86b5-474b330beb9c.png)

**Software (please complete the following information):**
 - Bazarr: v1.1.4-ls184
 - Sonarr version 4.0.0.391-ls414
 - OS: ubuntu / docker environment 

**Additional context**

**Comment by alneven** [comment]
two extra screenshots

![5E79337A-1C3F-4272-B3EC-28361891F6E1](https://user-images.githubusercontent.com/16620485/221802115-295fd507-e741-44ea-9c5f-c94dfe0fffb9.jpeg)
![C6A6DFED-C38D-4D38-B773-668692265873](https://user-images.githubusercontent.com/16620485/221802122-65079e5f-8407-4adf-aa15-35061f35df1f.jpeg)

**Comment by morpheus65535** [comment]
@Belphemur could you take a look at this issue please? Seems strange to have a match on series and year since it's not the good one at all.

**Comment by Belphemur** [comment]
Definitely a problem.

Currently, I don't do exact match with the series name.

Addicted doesn't store the year of the series either (sometimes they do in the title when there are conflicts).

Addicted has a tendency of merging languages (as you can see on the screenshot), adding UK to weird place and not respecting tvdb naming scheme.

I need to think of a good way to fix this. I technically could get the dates from Tvdb for matching shows then return that to the provider and use it as part of the scoring.

**Comment by morpheus65535** [comment]
@Belphemur does the addic7ed provider (or yours of course) return the tvdb_id? We can compare it and assume year is a match if tvdb_id do match, right?

**Comment by Belphemur** [comment]
Addicted provider doesn't have the tvdb_id.
However, for the show I match with TvDB I could return it and use it for the parsing of the returned show in the gestdown provider. That'd be quite easy to add.

I'll see if I have time later today to do that.

# Logic 
Logic to be used for the gestdown provider in bazarr.

1. Match by TvDB id
2. If not found, match by exact name
3. if not found, return not found

**Comment by morpheus65535** [comment]
@Belphemur thanks!

If tvdb_id match, series/movie title and year should match. If tvdb_id is found, return [].

**Comment by Belphemur** [comment]
I just realized, it's a little more work on my side. I don't have the tvdb_id but the tmdb_id (since tvdb had ... shitty pricing for accessing their API --").

I'll implement track.tv to get the tvdb_id for the shows and return that.

I'll update this issue and use it for the modification to the gestdown provider.

(also unrelated @morpheus65535 the gestdown service is now getting around 30 Millions daily requests ^^, thanks to Cloudflare to cache around 70% of all those requests).

**Comment by morpheus65535** [comment]
@Belphemur why not get the tvdb_id for each series using this?

https://developers.themoviedb.org/3/tv/get-tv-external-ids

**Comment by Belphemur** [comment]
Hoooo, I didn't see they had that endpoint, thanks !
That going to make things quite easy :D

**Comment by Belphemur** [comment]
I have a working version, but Addicted being Addicted, I have 270 shows that have duplicate matching for TVDB_ID.
The issue is, Addicted don't always put the year for a show, actually, they only do it in case of dupe. 

I already have an algorithm in mind to fix most cases.

**Comment by morpheus65535** [comment]
@Belphemur in that case maybe you can match by number of seasons or number of episodes? Hope you get a solution to that issue!

**Comment by Belphemur** [comment]
@morpheus65535 Tried that, still lots of dupe (same amount actually, too many show stop at one season or more likely, old show stopped at 1 season. Remake just started so ... 1 season).

What I need to do is group the dupe together, find those that have the date set on them like `Accused (2023)` vs `Accused` and search for tv show for `Accused` and discard the one that started in 2023 to get the tvdb_id of `Accused`. (Most of the time it'd be the next show in the list from the search of TMDB).

**Comment by morpheus65535** [comment]
@Belphemur ok understood. Your strategy seems to be the best you can do with what you have available.

**Comment by Belphemur** [comment]
@morpheus65535 Everything is in place, I still have dupe, but real dupe where the same show is on Addicted but with different name.

I've updated the provider in #2078 to use the tvdb_id.

**Comment by morpheus65535** [comment]
@Belphemur thanks my friend, it's really appreciated!

@alneven your issue should be fixed in upcoming beta. Can you test and report quickly please?

**Comment by alneven** [comment]
> @alneven your issue should be fixed in upcoming beta. Can you test and report quickly please?

uh, @morpheus65535 I will check how can I do it, I'm currently on latest docker container, I guess I should to switch to tag "develop"

**Comment by morpheus65535** [comment]
@alneven yes if you're using LSIO images, switch to `linuxserver/bazarr:development`

**Comment by alneven** [comment]
Now I get “no result”
Its working.
