### ISSUE TITLE
Throttling addic7ed for 10 minutes, until 23/03/03 11:22, because of: ValueError. Exception info: 'too many values to unpack (expected 2)'

### ISSUE THREAD

**Issue by bajire72** [morpheus65535/bazarr#2080]
Hello when i want to use addic7ed, it say me this error : Throttling addic7ed for 10 minutes, until 23/03/03 11:22, because of: ValueError. Exception info: 'too many values to unpack (expected 2)'

Can you help me ?

**Comment by halali** [comment]
Please fill again the issue template dont remove it... and add debug log

**Comment by halali** [comment]
No news, good news
