### ISSUE TITLE
Wrong episode matching with Subf2m provider 

### ISSUE THREAD

**Issue by iEusKid** [morpheus65535/bazarr#2081]
Episode number is always marked as matching even if it doesn't match. 

Taking Vinland saga anime 2nd season as an example it only grabs the 5th episode subtitle for all season 2 ( episode 6 will grab 5th episode subtitle, same for all)

1. I “Force” update it to latest version (although it was on 1.2.0)
2. Removed all providers other than Sub2fm
3. Emptied the log just before importing S02E01 then downloaded the log after subtitle downloaded

https://gofile.io/d/1WKXg3

 @vitiko98

**Comment by vitiko98** [comment]
Thanks for the report. This is a great discovery.

It should be fixed in upcoming beta.
