### ISSUE TITLE
"title not matched" although it is correct but alternative name

### ISSUE THREAD

**Issue by iEusKid** [morpheus65535/bazarr#2085]
the provider is Subf2m

anime title is = Tomo-chan Is a Girl!
but when bazarr searches this appear in the logs

Listing subtitles with provider 'subf2m' and languages {<Language [ar]>}
Series title not matched: tomo-chan wa onnanoko! (tomo-chan is a girl!)
Series title not matched: tomo-chan wa onnanoko! (tomo-chan is a girl!) (2023)

it is the JPN name, i think this can be solved easily if we can enable "https://anidb.net/" database along with TVDB or as a replacement

log= https://gofile.io/d/23Zpef
--------
thanks a lot guys, i had an issue 2d ago and u solved it. respect.

**Comment by halali** [comment]
We are gerring metadata from sonarr. And this is not an issue. So im closing it.

**Comment by iEusKid** [comment]
ok that's fair,
but when it searches for subtitles even the name in sonarr metadata is exist between the brackets:
{
**Series title not matched: tomo-chan wa onnanoko! (tomo-chan is a girl!)
Series title not matched: tomo-chan wa onnanoko! (tomo-chan is a girl!) (2023)**
}

you see "tomo-chan is a girl!" exists but even with that it said not matched
