### ISSUE TITLE
Does not pick up changed file path

### ISSUE THREAD

**Issue by Y0ngg4n** [morpheus65535/bazarr#2086]
**Describe the bug**
It seems like bazarr does not pick up changed file names. So for example you have an mkv file and you convert it to mp4, Bazarr will not pick up the mp4 file and will always throw an error `[Errno 2] No such file or directory` on a manual or automated scan no matter how often you sync sonarr. I don´t know if this also applies to radarr but i think so.

**To Reproduce**
1. Import Episodes from Sonarr
2. Search for Subtitles
3. Convert one episode from .mkv to .mp4 for example
4. Search for Subtitles again
5. Check Logs

**Expected behavior**
It should recognize that the file changed.

**Software (please complete the following information):**
 - Bazarr: v1.1.4-ls184 by linuxserver.io
 - Sonarr version 3.0.9.1549
 - OS: Docker

**Comment by morpheus65535** [comment]
Bazarr will get the changed filename from Sonarr/Radarr. Make sure those two are aware of the change you probably made using an external software.

**Comment by halali** [comment]
Bazarr is geting file path from sonarr, so you need refresh your serie in sonarr to catch path change.

**Comment by morpheus65535** [comment]
If Sonarr is updated, Bazarr will get the new filename at worst during the next "sync episodes with Sonarr" task occurrence. You can trigger it manually from System-->Tasks.

**Comment by Y0ngg4n** [comment]
@morpheus65535 already did. Did not fix the Problem. 

Example:
![image](https://user-images.githubusercontent.com/30302975/222985880-22dbebaa-0242-43fd-ab79-8e0a0771e225.png)

It seems like sync with sonarr raises an exception: 
```
Job "Sync episodes with Sonarr (trigger: interval[1:00:00], next run at: 2023-03-05 23:04:43 CET)" raised an exception

Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/bazarr/bin/bazarr/sonarr/sync/episodes.py", line 46, in sync_episodes
    series_count = len(seriesIdList)
TypeError: object of type \'NoneType\' has no len()
```

**Comment by morpheus65535** [comment]
If you sync series first? Seems like you're running into a connection issue exception.

**Comment by Y0ngg4n** [comment]
yes if i try to sync series i get this exception. Connection is configured correct. It also recognices version number if i click on test.

**Comment by morpheus65535** [comment]
You probably have some malformed database. Maybe @halali can take a look. I'm afk right now.

**Comment by Y0ngg4n** [comment]
ok thank you.

**Comment by Y0ngg4n** [comment]
I dont know why but it suddenly worked.
