### ISSUE TITLE
Include name between brackets when searching 

### ISSUE THREAD

**Issue by iEusKid** [morpheus65535/bazarr#2087]
Sorry, i know i posted about this before.
But i asked to add new metadata provider, although it is not really necessary.

I tried with 5 animes, and all them not matched ALTHOUGH it is actually in the searched name as you can see

See this for example 

“By the Grace of the Gods”

{
Downloading best subtitles for <Episode ['By the Grace of the Gods', 2020, 2x9]>

Listing subtitles with provider 'subf2m' and languages {<Language [ar]>}

Series title not matched: kami-tachi ni hirowareta otoko 2nd season (by the grace of the gods season 2)

Series title not matched: kami-tachi ni hirowareta otoko 2nd season (by the grace of the gods season 2) (2023)
}

It is present between the brackets. 
it doesn’t seems a major problem because nothing needed to be added except to include the whole name when searching, or better prefer the name between brackets

**Comment by halali** [comment]
this is issue tracker, if you have any suggestions you can open FR https://bazarr.featureupvote.com/
