### ISSUE TITLE
Task progress notification is hiding actions on first subtitles of a show

### ISSUE THREAD

**Issue by anonyme123** [morpheus65535/bazarr#2090]
**Describe the bug**
The task progress notification overlays on top of the action buttons for the first 2 episodes of a show:
![003864-Brave Browser-Alice in Borderland (2020) - Bazarr (Series)](https://user-images.githubusercontent.com/19681420/223433592-6b27ae97-f0fc-4cd6-83c3-f7bcebb83a6b.jpg)

**To Reproduce**
1. Go to a show's page
2. Trigger any action
3. See the task progress notification is hiding the action buttons of the first 2 episodes of a show

**Expected behavior**
We should be able to access the action buttons at any time, maybe consider moving the progress notification somewhere else? And/or adding a 'dismiss' button on the notification?

**Software (please complete the following information):**
 - Bazarr: 1.2.0
 - Radarr version 4.3.2.6857
 - Sonarr version 3.0.10.1566
 - OS: Linux-3.10.0-1160.76.1.el7.x86_64

**Comment by morpheus65535** [comment]
We've planned to address that in an upcoming version through a notification center instead of the toaster notification. I'll close that issue because we're already tracking this somewhere else. Thanks for reporting!
