### ISSUE TITLE
Can't pick "no proxy" and now can't sync with Arrs even with blank proxy settings

### ISSUE THREAD

**Issue by namaneko** [morpheus65535/bazarr#2091]
**Describe the bug**
When I originally set up Bazarr I was going to have it use a proxy server ... but didn't think about how that meant it would use that proxy server not for its outgoing HTTP requests to the Internet but for all requests, including those that are local.

No problem ... I just cleared out the proxy settings.

Only problem, I get **InvalidProxyURL** no matter what I do.

I've verified that everything is blank in the bazarr.ini, I've tried using **No Proxy** as the type but then I get an error about control characters, and I've tried **none** which results in the same error.

![image](https://user-images.githubusercontent.com/51968355/223494229-14acaa40-43c5-4d54-986c-9b2b2e01a053.png)

![image](https://user-images.githubusercontent.com/51968355/223494316-85ef0f8b-56fa-41d1-bc0e-bd99642bb980.png)

**Software (please complete the following information):**
 - Bazarr: **1.2.0**
 - Radarr: **4.3.2.6857**
 - Sonarr: **3.0.10.1566**
 - OS: **Debian Linux 11**

**Comment by morpheus65535** [comment]
Click on the "x" at right of HTTP(s) and save. Restart Bazarr and it will work as expected.

**Comment by namaneko** [comment]
Ayyyooooo ... there we go. 

Having the dark mode plugin on made it difficult to see.

I guess this is my chance to request a dark mode. ;) 

Thanks, sir! For the quick reply and quick fix. :)

**Comment by morpheus65535** [comment]
Hummm there's a dark mode for a long time now. It follow operating system settings and can be toggled on/off with the button in the bottom left corner.
