### ISSUE TITLE
SuperSubtitles manual search doesn’t work anymore (under 1.2.0 latest, nor 1.2.1 development)

### ISSUE THREAD

**Issue by alneven** [morpheus65535/bazarr#2092]
**Describe the bug**
With provider SuperSubtitles the **manual search** is not working anymore after upgrading  to 1.2.0 master (nor 1.2.1-beta.0 development)

```
File "/app/bazarr/bin/bazarr/subtitles/manual.py", line 86, in manual_search
    logging.debug(f"BAZARR Skipping {s}, because it doesn\'t match our series/episode")
```

**To Reproduce**
1. Go to settings / providers and enable supersubtitles
2. Click on manual search at an episode
3. Go to the logs as there is no search result
4. See error: https://hastebin.com/share/nivijuyobu.rust

**Expected behavior**
Subtitle is listed and can be manually download (as earlier).

If I remove supersubtitles the manual search works with the other provider as it should be.
Currently the sub for True Lies is listed only on supersubtitles in Hungarian.
![58954C56-FA8F-48AE-A94F-3467AC5B5B44](https://user-images.githubusercontent.com/16620485/223850930-5adec9bf-82ae-4986-b7d4-f5471dee9ac9.jpeg)

Hosszupuska doesn’t have it. With removed supersubtitles provider it looks like normal:
![6EED06BE-E2D9-4358-8DA6-74273C5B5EBC](https://user-images.githubusercontent.com/16620485/223850649-e67875ed-ede1-4c70-967d-8ee8a1706aea.jpeg)

**Software (please complete the following information):**
 - Bazarr Version 1.2.1-beta.0 
 - Package Version v1.2.1-beta.0-ls481 by linuxserver.io
 - Sonarr Version 4.0.0.391
 - Radarr Version 4.4.2.6956
 - OS: Ubuntu Linux, all docker

**Additional context**
Debug LOG attached
[baz.txt](https://github.com/morpheus65535/bazarr/files/10925097/baz.txt)

**Comment by Achlys-8** [comment]
Same issue for me
Debug LOG attached 
[bazarr.log](https://github.com/morpheus65535/bazarr/files/10930711/bazarr.log)

**Comment by fraviktor** [comment]
I reverted the supersubtitles.py file to the previous version and it works as expected.
I think that the new version of supersubtitles.get_matches() function provides such an input to the manual.manual_search() which is not the required format. I didn't have much time for debugging, but I think it could be an easy fix.

**Comment by alneven** [comment]
Thanks for the hint, I have replaced the ```supersubtitles.py``` file from the previous stable version (1.1.4) and the search is working again

**Comment by vitiko98** [comment]
Fixed. Thanks.

**Comment by alneven** [comment]
@vitiko98 

I have now the latest development version
And I have this error with SuperSubtitles

```
BAZARR Manually searching subtitles for this file: /tv/La.Brea/Season.02/la.brea.s02e13.720p.web.h264-cakes.mkv

BAZARR Skipping <SuperSubtitlesSubtitle 'https://www.feliratok.eu//index.php?action=letolt&felirat=[1678540038](tel:1678540038)' [hu:None]>, because it doesn't match our series/episode
```

**Comment by alneven** [comment]
reverted back to 1.1.4 and its working:
```
11/03/2023 15:32:03|DEBUG   |root                            |BAZARR Manually searching subtitles for this file: /tv/La.Brea/Season.02/la.brea.s02e13.720p.web.h264-cakes.mkv|
11/03/2023 15:32:03|INFO    |subliminal_patch.core           |Using 3 threads for 3 providers ({'gestdown', 'hosszupuska', 'supersubtitles'})|
11/03/2023 15:32:03|DEBUG   |subliminal_patch.core           |Discarded providers: set() | New providers: {'gestdown', 'hosszupuska', 'supersubtitles'}|
11/03/2023 15:32:03|INFO    |subliminal_patch.core           |Listing subtitles with provider 'supersubtitles' and languages {<Language [hu]>}|
11/03/2023 15:32:03|INFO    |subliminal_patch.core           |Initializing provider supersubtitles|
11/03/2023 15:32:03|INFO    |subliminal_patch.providers.supersubtitles|Get series id from URL https://www.feliratok.eu/index.php?term=La Brea&nyelv=0&action=autoname|
11/03/2023 15:32:04|INFO    |subliminal_patch.providers.supersubtitles|Getting the list of subtitles for <Episode ['La Brea', 2021, 2x13]>|
11/03/2023 15:32:04|INFO    |subliminal_patch.providers.supersubtitles|Get IMDB id from URL https://www.feliratok.eu/index.php?tipus=adatlap&azon=a_1678540050|
11/03/2023 15:32:04|DEBUG   |subliminal_patch.providers.supersubtitles|IMDB ID found: tt11640018|
11/03/2023 15:32:06|INFO    |subliminal_patch.score          |<SuperSubtitlesSubtitle 'La Brea (2021) S02E13 [AMZN.WEB-DL.1080p-NTb, AMZN.WEB-DL.720p-NTb, WEBRip-ION10]' [hu]>: Computed score 340 with final matches {'episode', 'source', 'resolution', 'series', 'hearing_impaired', 'year', 'series_imdb_id', 'season', 'edition'}|
11/03/2023 15:32:06|INFO    |subliminal_patch.score          |<SuperSubtitlesSubtitle 'La Brea (2021) S02E13 [WEB.1080p-CAKES, WEB.720p-CAKES]' [hu]>: Computed score 355 with final matches {'release_group', 'episode', 'source', 'resolution', 'series', 'hearing_impaired', 'year', 'other', 'series_imdb_id', 'streaming_service', 'season', 'edition'}|
11/03/2023 15:32:06|DEBUG   |root                            |BAZARR 4 Subtitles have been found for this file: /tv/La.Brea/Season.02/la.brea.s02e13.720p.web.h264-cakes.mkv|
11/03/2023 15:32:06|DEBUG   |root                            |BAZARR Ended searching Subtitles for this file: /tv/La.Brea/Season.02/la.brea.s02e13.720p.web.h264-cakes.mkv|
```

**Comment by alneven** [comment]
@vitiko98 should I open a new issue for this?
