### ISSUE TITLE
Provider titrari.ro doesn't work

### ISSUE THREAD

**Issue by raclariu** [morpheus65535/bazarr#2093]
![titrariroproviderinput](https://user-images.githubusercontent.com/22458542/224356974-f063596d-6992-4f7d-9b72-e131a02f7a18.JPG)
**Describe the bug**
I have manually searched for a movie subtitle that is found on www.titrari.ro and bazarr doesn't find it, but it exists.

**To Reproduce**
1. Enable titrari.ro provider
2. Search for subtitle for a movie you have in Radarr, first on the actual website, then in Bazarr. I have done this by searching for Everything Everywhere All At Once
3. No results in Bazarr.

**Expected behavior**
Should find and download titrari.ro subtitles as they are the best subtitles for the Romanian language.

**Software (please complete the following information):**
 - Bazarr 1.2.0 via docker compose (linuxserver.io)
 - Radarr version 4.3.2.6857 via docker compose (linuxserver.io)
 - OS: Ubuntu 20.04

**Logs**
So here are the logs:
```
10/03/2023 17:00:59|DEBUG   |subliminal_patch.providers.subtitrarinoi|Found subtitle 'Everything Everywhere All at Once (2022) -> https://www.subtitrari-noi.ro/69972-subtitrari-noi.ro-Everything Everywhere All at Once (2022)-510.zip'|
10/03/2023 17:00:59|DEBUG   |subliminal_patch.providers.subtitrarinoi|Sorting by download count...|
10/03/2023 17:00:59|DEBUG   |subliminal_patch.providers.titrari|Sorting by download count...|
10/03/2023 17:00:59|DEBUG   |urllib3.connectionpool          |https://www.titrari.ro:443 "GET /?page=cautarepreaavansata&z7=&z2=&z5=6710474&z3=-1&z4=-1&z8=2&z9=All&z11=0&z6=0 HTTP/1.1" 200 None|
10/03/2023 17:00:59|DEBUG   |subliminal_patch.providers.titrari|Sorting by download count...|
10/03/2023 17:01:00|DEBUG   |urllib3.connectionpool          |https://www.titrari.ro:443 "GET /?page=cautarepreaavansata&z7=&z2=&z5=6710474&z3=-1&z4=-1&z8=1&z9=All&z11=0&z6=0 HTTP/1.1" 200 None|
10/03/2023 17:01:00|DEBUG   |subliminal_patch.providers.titrari|Sorting by download count...|
10/03/2023 17:01:00|DEBUG   |urllib3.connectionpool          |https://subf2m.co:443 "GET /subtitles/searchbytitle?query=everything%20everywhere%20all%20at%20once&l= HTTP/1.1" 200 None|
10/03/2023 17:01:00|DEBUG   |subliminal_patch.providers.subf2m|No results|
10/03/2023 17:01:00|DEBUG   |urllib3.connectionpool          |https://www.titrari.ro:443 "GET /?page=cautarepreaavansata&z7=&z2=&z5=6710474&z3=-1&z4=-1&z8=1&z9=All&z11=0&z6=0 HTTP/1.1" 200 None|
10/03/2023 17:01:00|DEBUG   |subliminal_patch.providers.titrari|Sorting by download count...|
10/03/2023 17:01:00|DEBUG   |urllib3.connectionpool          |https://feliratok.eu:443 "GET /index.php?search=Everything+Everywhere+All+at+Once&soriSorszam=&nyelv=&tab=film HTTP/1.1" 200 None|
10/03/2023 17:01:00|INFO    |subliminal_patch.providers.supersubtitles|Get IMDB id from URL https://www.feliratok.eu/index.php?tipus=adatlap&azon=a_1655482391|
```

### FIX
Might be a fix after testing a bit, I am not sure though.

When you manually search on the website through the advanced search function, the URL isn't /?page=cautarepreaavansata[...] it is actually /?page=cautarecutare[...]

**You can see the results here:**

**OLD search url (the one Bazarr tries to access)**
https://titrari.ro/index.php?page=cautarepreaavansata&z7=&z2=&z5=6710474&z3=-1&z4=-1&z8=1&z9=All&z11=0&z6=0

**NEW search url**
https://titrari.ro/index.php?page=cautarecutare&z7=&z2=&z5=6710474&z3=-1&z4=-1&z8=1&z9=All&z11=0&z6=0

I don't know why they've changed it, or if they change it often to break bazarr functionality so I don't know if it's a good idea, but considering they only change the first part of their URL, can an input field be added to this provider so when someone adds it, they can also type in that specific part of the URL (like cautarepreaavansata OR cautarecutare and so on in case they change it). Like in the screenshot for example.

Thank you!

**Comment by vitiko98** [comment]
I'm getting 500 errors with both links. Was that happening when you opened this issue?

**Comment by raclariu** [comment]
> I'm getting `500 status code` errors with both links. Was that happening when you opened this issue?

Both links work for me. First link returns 0 subs while the second link returns 2 subs for the selected movie. I explained what was happening in this post. Bazarr doesn't find any susbtitles from titrari.ro provider for any movie, but they exist if you manually search in the website. It's just thst Bazarr has the wrong part of the Url at the start as you can see in the logs. Probably this provider changed its advanced search url and broke Bazarr functionality. Try again the links and if you get 500 error go directly to titrari.ro and use advanced search. If you still get 500 error, maybe they blocked your country and should use an Eu vpn i guess.

**Comment by vitiko98** [comment]
I'm still getting the `500 status code`...

Anyway, I updated `cautarepreaavansata` to `cautarecutare` as you suggested. Since I can't test it myself, please confirm that this commit is working. You can test it in the upcoming beta.

**Comment by raclariu** [comment]
> I'm still getting the `500 status code`...
> 
> Anyway, I updated `cautarepreaavansata` to `cautarecutare` as you suggested. Since I can't test it myself, please confirm that this commit is working. You can test it in the upcoming beta.

Right now, the website is down for me as well, getting 500 error. They had some issues lately. Anyway, when the beta goes up, I will test it and come back with a response.
