### ISSUE TITLE
Automatic downloading of hearing impaired subtitles failing

### ISSUE THREAD

**Issue by lolman300** [morpheus65535/bazarr#2096]
**Describe the bug**
Automatic downloading of hearing impaired subtitles failing with 'Subtitles Type' set to 'Normal or hearing-impaired' in Language Profile.  Manual search includes failed match for 'hearing_impaired'.

**To Reproduce**
1. Go to TV episode with missing subtitles
2. Click on Subtitles -> Actions -> Search
3. Toast notification briefly displays 'Searching subtitles... [0/1] English]
4. Toast notification displays 'Searching subtitles... All Tasks Completed' without downloading any subtitles

**Expected behavior**
Automatic search should download the found subtitles

**Screenshots**
![Manual search shows available subtitles](https://user-images.githubusercontent.com/128029016/225557804-13327edd-6b36-4384-b7f0-de6ef551ec0f.png)

![Settings->Languages](https://user-images.githubusercontent.com/128029016/225554163-45f3be98-d4cb-46b6-a857-ebd269bd0ce1.png)

![Languages Profile (English)](https://user-images.githubusercontent.com/128029016/225558108-c0bc2ab5-88e3-479c-a74a-9b966249b015.png)

**Software (please complete the following information):**
 - Bazarr: v1.2.0
 - Radarr: v4.3.2.6857
 - Sonarr: v3.0.10.1567
 - OS: Linux-5.19.17-Unraid-x86_64-with

**Additional context**

Issue opened at the request of halali on Discord #support

Log file of unsuccessful automatic download (ignore incorrect month in pastebin title, should be MAR-16-2023)
https://pastebin.com/BfJwT919

Changing 'Subtitles Type' in Language Profile to 'Hearing-impaired required' allows automatic downloads to correctly match and download the found subtitles.  See following log file.
https://pastebin.com/qDBNc1Vt

**Comment by morpheus65535** [comment]
Are you able to confirm what's the last version where it worked as expected?

**Comment by lolman300** [comment]
Unfortunately I've only just set up Bazarr on my server around a week ago, so v1.2.0 is the only Bazarr version I've tested/used

**Comment by lolman300** [comment]
Pulled v1.2.1-beta.9-ls485 by linuxserver.io and tested - seems to be fixed!  Thanks!!

**Comment by morpheus65535** [comment]
Pleasure! Congrats! You've found a bug I introduced more than 2 years ago! ;-)
