### ISSUE TITLE
mass edit - remove HI Tag - Doesn'T do all subtitle

### ISSUE THREAD

**Issue by nodiaque** [morpheus65535/bazarr#2100]
**Describe the bug**
When selecting all subtitles and selecting remove HI, some subtitle keep HI and must be removed manually one by one

**Screenshots**
![image](https://user-images.githubusercontent.com/324425/226152201-40ec0a4b-b271-4ce5-8351-fd0f18e45fbc.png)

![image](https://user-images.githubusercontent.com/324425/226152216-c2a4717d-6e19-4417-b619-8b96169f0ec5.png)

**Software (please complete the following information):**
 - Bazarr: 1.2.0
 - OS: Unraid 6.11.5

**Comment by morpheus65535** [comment]
Bazarr, when running HI removal mods on already existing subtitles, won't rename the file. If the file is named as a HI subtitles, Bazarr will index it as a HI subtitles. Is that the case here? Check the subtitles filename and confirm please.

**Comment by morpheus65535** [comment]
No news, good news.
