### ISSUE TITLE
Special chars in filenames make them unreadable

### ISSUE THREAD

**Issue by gizzygizmo** [morpheus65535/bazarr#2101]
Bazarr doesn't seem to escap especial chars when trying to read files... which results in errors reading files with apostrophe, spanish chars, etc. Ther esulting error is "BAZARR mediainfo cannot analyze this video file" followed by the name + "Could it be corrupted".

The names either need to be in single quotes when passign to ffmpeg/mediainfo or the filenames need to have special chars escaped.

**To Reproduce**
1. Rename a file "Someone's file" 
2. Scan for subtitles
3. Check the log
4. Note the "cannot analyze this video file" message
5. Rename the file "Someones file"
6. Scan the file and watch it work fine

**Expected behavior**
Files should not be reported as "corrupted" if they simply have special chars in the name

**Software (please complete the following information):**
 - Bazarr: v1.2.1-beta.6 &  latest stable
 - OS: Ubuntu /w Docker images

Pretty sure we just need to put single quotes around filenames when executing ffmpeg/mediainfo or escape the special chars in the filename.

**Comment by morpheus65535** [comment]
Please provide a debug log while reproducing the issue.

**Comment by morpheus65535** [comment]
No news, good news.
