### ISSUE TITLE
TrueNAS: Does not autostart

### ISSUE THREAD

**Issue by sindreruud** [morpheus65535/bazarr#2104]
TrueNAS-13.0-U4
Freshly created iocage jail running latest release of FreeBSD (13.1-RELEASE-p7).
Bazarr installed with pkg from latest, which grabs bazarr-1.2.0.

Install goes fine, and can also start bazarr with
`/usr/local/etc/rc.d/bazarr start`
which makes the web gui accessible. So far all good.

Next up is to make it autostart and managing it with `service bazarr start` and `service bazarr stop` by adding it to the sysrc using this command
`echo 'bazarr_enable="YES"' >> /etc/rc.conf`

Confirmed that it is in the conf: 

```
> root@bazarr ~$ cat /etc/rc.conf
> cron_flags="$cron_flags -J 15"
> 
> # Disable Sendmail by default
> sendmail_enable="NO"
> sendmail_submit_enable="NO"
> sendmail_outbound_enable="NO"
> sendmail_msp_queue_enable="NO"
> 
> # Run secure syslog
> syslogd_flags="-c -ss"
> 
> # Enable IPv6
> ipv6_activate_all_interfaces="YES"
> ifconfig_epair0b="SYNCDHCP"
> 
> bazarr_enable="YES"
```

However, it will not respond to start, stop or status command, and it doesn't autostart on jail start:

```
> root@bazarr ~$ service bazarr status
> bazarr is not running.
> root@bazarr ~$ service bazarr start
> Starting bazarr.
> root@bazarr ~$ service bazarr status
> bazarr is not running.
```

The rc.d file points to 
`command_args="-f -p ${pidfile} ${procname} /usr/local/share/bazarr/bin/bazarr.py --no-update -c ${bazarr_datadir}"`

And I can confirm it is the right location

```
> root@bazarr ~$ ls -la /usr/local/share/bazarr/bin
> total 33
> drwxr-xr-x   2 root  wheel     4 Mar 24 14:50 __pycache__
> drwxr-xr-x   6 root  wheel     9 Mar 24 14:50 .
> drwxr-xr-x   3 root  wheel     4 Mar 24 14:50 ..
> drwxr-xr-x  10 root  wheel    15 Mar 24 14:50 bazarr
> -rw-r--r--   1 root  wheel  3661 Mar  3 03:12 bazarr.py
> drwxr-xr-x   3 root  wheel     3 Mar 24 14:50 frontend
> drwxr-xr-x  99 root  wheel   115 Mar 24 14:50 libs
> -rw-r--r--   1 root  wheel    61 Mar  3 03:12 requirements.txt
> -rw-r--r--   1 root  wheel     7 Mar  3 03:12 VERSION
```

So I am a bit stumped what to do next. Any one have any input? Anything I am overlooking here?

**Comment by morpheus65535** [comment]
I know nothing about those TrueNAS jails but they should be logging somewhere why it fails to start, right? I would look there since it's unrelated to Bazarr itself which is running fine when started manually.

**Comment by sindreruud** [comment]
After digging around some more I have realized that it actually spits out an error in the bazarr log file that I have somehow overlooked earlier.

So if i start it with `/usr/local/etc/rc.d/bazarr start` the log looks normal and it's just saying:

```
> 27/03/2023 17:29:57|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
```

However, if i do **service bazarr start** the log is now saying:

```
27/03/2023 17:35:54|ERROR   |root                            |BAZARR requires a rar archive extraction utilities (unrar, unar) and it can't be found.|
'Traceback (most recent call last):\n  
File "/usr/local/share/bazarr/bin/bazarr/init.py", line 198, in init_binaries\n    
    exe = get_binary("unar")\n  File "/usr/local/share/bazarr/bin/bazarr/utilities/binaries.py", line 73, in get_binary\n    
    raise BinaryNotFound\n
    utilities.binaries.BinaryNotFound\n\n

During handling of the above exception, another exception occurred:\n\n
Traceback (most recent call last):\n  
File "/usr/local/share/bazarr/bin/bazarr/init.py", line 204, in init_binaries\n    
    exe = get_binary("unrar")\n  
File "/usr/local/share/bazarr/bin/bazarr/utilities/binaries.py", line 73, in get_binary\n    
    raise BinaryNotFound\n
    utilities.binaries.BinaryNotFound'|
```

As far as I can see unrar was installed alongside bazarr:
```

root@bazarr ~$ pkg info unrar
unrar-6.12,6
Name           : unrar
Version        : 6.12,6
Installed on   : Mon Mar 27 13:04:58 2023 CEST
Origin         : archivers/unrar
Architecture   : FreeBSD:13:amd64
Prefix         : /usr/local
Categories     : archivers
Licenses       : UNRAR
Maintainer     : sunpoet@FreeBSD.org
WWW            : https://www.rarlab.com/
Comment        : Extract, view & test RAR archives
Options        :
        OPENSSL_AES    : on
Annotations    :
        FreeBSD_version: 1301000
        cpe            : cpe:2.3:a:rarlab:unrar:6.12:::::freebsd13:x64
        repo_type      : binary
        repository     : FreeBSD
Flat size      : 333KiB
Description    :
The UnRAR utility is a freeware program, distributed with source code and
developed for extracting, testing and viewing the contents of archives created
with the RAR archiver, version 1.50 and above.

The UnRAR utility is a minor part of the RAR archiver and contains RAR
uncompression algorithm. UnRAR requires very small volume of memory to operate.

WWW: https://www.rarlab.com/
```

But it seems bazarr is getting unrar binaries from a json located at: 
`/usr/local/share/bazarr/bin/bazarr/utilities/binaries.json`

But this json file doesn't have binaries for FreeBSD, only Linux, Mac and Windows (?) For instance:
```
{
    "system": "Linux",
    "machine": "x86_64",
    "directory": "unrar",
    "name": "unrar",
    "checksum": "2a63e80d50c039e1fba01de7dcfa6432",
    "url": "https://github.com/morpheus65535/bazarr-binaries/raw/master/bin/Linux/x86_64/unrar/unrar"
  },
```

Any idea whats going on here?

**Comment by morpheus65535** [comment]
Bazarr include pre-tested binaries for some platforms. It's not the case for FreeBSD. You must install the required binaries yourself. I don't know why but it seems Bazarr can't find urar/unrar in your jail using `which`. You'll have to fix this.

Why not use the FreeBSD package instead? It would deals with that for you.

**Comment by morpheus65535** [comment]
@mvanbaak can you jump in please? I've reached my limit with FreeBSD ;-)

**Comment by mvanbaak** [comment]
@sindreruud Do I understand correctly that `/usr/local/etc/rc.d/bazarr start` results in a correctly running bazarr, but `service bazarr start` doesn't ?

**Comment by sindreruud** [comment]
> @sindreruud Do I understand correctly that `/usr/local/etc/rc.d/bazarr start` results in a correctly running bazarr, but `service bazarr start` doesn't ?

Yes, correct. 

So `service bazarr start` is what's making it complain about not finding the unrar binaries

**Comment by sindreruud** [comment]
> I'm trying to reproduce this, but a totally new 13.1 jail on FreeBSD 13 does not show this problem.
That's interesting. Then hopefully I can figure out what's different/wrong on my end and make adjustments. Currently everything is as default as I can have it (i think). And it's also a totally new 13.1 jail, allthough running on TrueNAS and not FreeBSD. So maybe there is something there, with the settings of the iocage. I'll dig some more.

> I will probably not be able to fix this soon, as I cannot reproduce it at the moment and I'm pretty busy.
Totally understandable. 

Thank you so much @morpheus65535 and @mvanbaak for your work on this app and for taking the time to reply to me. Best of luck :) I will be sure to make a donation when I can.
