### ISSUE TITLE
Can't change settings tab

### ISSUE THREAD

**Issue by oversc0re** [morpheus65535/bazarr#211]
Hi there, thanks for the good work first!

I've installed Bazarr thorug linuxserver/docker and everything went smooth until initial configuration. 
After going to settings page, I can fill everything on General tab, but cannot switch to other tabs and I can't save either as "Some fields are in error and you can't save settings until you have corrected them. Be sure to check in every tabs." appears on top. 

Can you give me any suggestions?

Thanks, 
Over.

**Comment by morpheus65535** [comment]
Start by reading the wiki:

https://github.com/morpheus65535/bazarr/wiki/First-run

**Comment by oversc0re** [comment]
I did read the wiki before posting... except if I missunderstood anything:

In "General" tab:
Configure Bazarr settings (listening ip and port, base url and log level).
**Done.**

Enable the required integration (Sonarr and/or Radarr).
**Done.**
Configure Path Mappings only if you need it. Typical use case: Sonarr/Radarr access episode files trough local path (D:\episodes\file.mkv) but Bazarr access those same episode/movie files trough a network share (\server\episodes\file.mkv). In this case, you would be configuring Path Substitutions like this: D:\episodes --> \server\episodes. If you don't set this correctly, you'll get http error 500 later down the road.
**I don't need it**

Configure updates. Recommended values are "master" and automatic enabled.
**Done.**

In "Sonarr" tab:
Configure Sonarr ip, port, base url, SSL and API key.
Test your Sonarr configuration.
**Can't switch to Sonarr tab as mentioned in my first post.**

**Comment by morpheus65535** [comment]
Did you enable Sonarr/Radarr integration in general tab? Until then, those other tabs will remain unavailable.

**Comment by morpheus65535** [comment]
Was a pleasure, don’t hesitate if you have other issue.
