### ISSUE TITLE
Space character in search bar doesn't work

### ISSUE THREAD

**Issue by 2fst4u** [morpheus65535/bazarr#2115]
**Describe the bug**
Attempting to type a space character in the search bar just does nothing and ignores the character.

**To Reproduce**
1. Search for an item with a space character

**Expected behavior**
Space types correctly

**Screenshots**
![Screenshot_2023-04-10-07-01-26-78_3aea4af51f236e4932235fdada7d1643.jpg](https://user-images.githubusercontent.com/15257926/230791571-e568216b-d0ae-47b4-985b-9340631c6b1d.jpg)

"Star wars" was typed.

**Software (please complete the following information):**
 - Bazarr: v1.2.0
 - OS: Ubuntu 22.04 kubernetes

**Additional context**
I don't get this in any of my other web apps. It's very strange and inconsistent.

**Comment by halali** [comment]
What browser, cannot reproduce on chrome

**Comment by 2fst4u** [comment]
Ah could be browser specific. Firefox on android.

**Comment by morpheus65535** [comment]
Cannot reproduce on Firefox for macOS or iOS. I don't have an Android device to reproduce.

**Comment by 2fst4u** [comment]
It does seem to work fine in chrome but not Firefox.

This might seem trivial but I do consider it a bug. I haven't encountered this with any of my other apps so there's something going on there.

**Comment by morpheus65535** [comment]
I agree that's not the expected behavior but we rely on UI frameworks that may have bugs. They're gonna fix it over time and we'll benefit from that.

@LASER-Yi anything to add here?

**Comment by LASER-Yi** [comment]
> I agree that's not the expected behavior but we rely on UI frameworks that may have bugs. They're gonna fix it over time and we'll benefit from that.
> 
> @LASER-Yi anything to add here?

Let me check the issue first

**Comment by LASER-Yi** [comment]
I just update our UI library to the latest version. Could you help me testing it in the next upcoming beta version? (Should be v1.2.1-beta.16)

**Comment by 2fst4u** [comment]
Sure just let me know when to try the container version.

**Comment by 2fst4u** [comment]
> I just update our UI library to the latest version. Could you help me testing it in the next upcoming beta version? (Should be v1.2.1-beta.16)

I just tried it and it still has the same issue for me. I confirmed it was version 1.2.1-beta.16.

**Comment by morpheus65535** [comment]
@LASER-Yi anything else we can do to fix this?

**Comment by Aginarikar** [comment]
I did check this last week with
-Updated Firefox stable
-Updated Ubuntu 22.04 w/ 6.2.x kernel 
-Bazarr newest 1.2.x (linuxserver.io docker image)

Couldn't reproduce.

@2fst4u : Did you try disabling all Firefox extensions? Or even resetting Firefox settings.

**Comment by 2fst4u** [comment]
Seems to be working fine now.
