### ISSUE TITLE
Bazarr fails to read either episodes or movies from disk when "Use cached embedded subtitles parser results" is checked on

### ISSUE THREAD

**Issue by vkojchevski** [morpheus65535/bazarr#2118]
**Describe the bug**
Bazarr fails to read either episodes or movies from disk when "Use cached embedded subtitles parser results" is checked on for both movies and series.

**To Reproduce**
1. Newly installed Bazarr
2. Set all necessary settings to get language profiles assigned to the media and sonarr+radarr connections
3. Bazarr correctly imports Sonarr/Radarr lists but fails to scan the disk for them
4. Manual triggering of the related tasks results in errors "Failed to connect to backed" "Server offline"
5. Browser page refresh removes the error screen and opens up Bazarr again, but manual scans trigger the same errors
6. While turning off "Use cached embedded subtitles parser results" solves the problem initially, it comes back after a while

**Expected behavior**
For Bazarr to correctly scan the media on the disk

**Software (please complete the following information):**
 - Bazarr: v1.2.0-ls192 by linuxserver.io
 - Radarr version 4.3.2.6857
 - Sonarr version 3.0.10.1567
 - OS: Unraid 6.11.5

**Additional context**
I apologize that I don't have screenshots or more logs, I was more concerned about Bazarr working again for a fresh influx of media that I had, that I didn't manage to grab more details and my setup has changed quite a bit now as I use PostgreSQL as a DB. However I was able to consistently reproduce the problem (made couple of "fresh" installs) and if need be I am willing to do the extra work to make a dummy setup to reproduce it.

Let me go into some detail.
I recently had to remove Bazarr docker container (and its appdata), for unrelated reasons. So I made a fresh install and started configuring it. I made all the necessary changes to get it back to as it used to be before besides adding providers as I didn't want even the chance of Bazarr downloading new subtitles before it recognized its old ones. It properly connected and imported lists from  Sonarr/Radarr and shows the "live" icon next to their respective headers. 

However, after a day (enough for all scheduled tasks to run) I noticed that none of my existing subtitles are recognized (they are alongside the media file). Manually triggering the task to scan the disk results in the notification bubble showing for a brief moment, then soon after gives a server offline and failed to connect to backend error. Refreshing the page brings you back to Bazarr but triggering the same task results in the same errors. Logs didn't show anything obvious.

I've tried changing every relevant setting there is, making sure volume mapping is correct, trying both ffprobe and mediainfo. What made it work initially, was turning off "Use cached embedded subtitles parser results". However after a while the problem came back and any interaction (like initiating manual disk scan for a single movie) resulted in the same errors.
I am currently using it with PostgreSQL DB and for now (couple of days) it is issue free.

**Comment by morpheus65535** [comment]
I'm going to need the log file when you reproduce this issue. The frontend disconnecting from backend means that an unexpected exception have occurred in backend. It will be logged in Bazarr log file.

**Comment by morpheus65535** [comment]
Thanks for the feedback!
