### ISSUE TITLE
Subtitle search not working for series "New Girl"

### ISSUE THREAD

**Issue by msalem23** [morpheus65535/bazarr#2120]
**Describe the bug**
When conducting a manual search for subtitles for any episodes of the series New Girl, I get "Error 500
You have disconnected from the server". This happens only for New Girl, not other series.

**To Reproduce**
1. Click Series in the left pane
2. Click "New Girl" in the series list
3. Next to any episode, click the "Manual Search" button
4. Click the "Search" button
5. See error

**Expected behavior**
Results for subtitles should have populated.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 1.2.0
 - Radarr version 4.4.4.7068
 - Sonarr version 3.0.10.1567
 - OS: Windows 10 Pro

**Additional context**
Log file: https://gist.github.com/msalem23/adfe15aca0ce2bf3a1fa6587d34468c2

**Comment by halali** [comment]
Duplicate #2114 #2105 alreade fixed in development branch
