### ISSUE TITLE
Subtitle throttling on VIP OpenSubtitles.com

### ISSUE THREAD

**Issue by semiviral** [morpheus65535/bazarr#2121]
**Describe the bug**
Bazarr seems to be failing to download any (?) subtitles from opensubtitles.com, with a VIP subscribed account.

**To Reproduce**
1. Link a VIP OpenSubtitles account
2. Search all subtitles
3. Get throttled almost immediately

**Expected behavior**
Downloading 1000 subtitles per day, as the OpenSubtitles API (says it) allows.

**Software (please complete the following information):**
 - Bazarr: v1.2.0
 - Radarr version v4.4.4.7068
 - OS: Debian 11

**Additional context**
I'm not 100% sure this isn't an issue with OpenSubtitles, but I really have no way of telling.

**Comment by morpheus65535** [comment]
Can you try to empty `config/cache` directory and retry?

**Comment by semiviral** [comment]
Yes, I've already tried deleting it—no luck.

**Comment by morpheus65535** [comment]
Did you use your username or your email? Send me your username and I'll check with them.

**Comment by semiviral** [comment]
It was my username: idealness5269

**Comment by morpheus65535** [comment]
I've spoke with the admin and he's going to provide a test VIP account for me to run some test. I'll get back to you once I've been able to reproduce the issue (or not).

**Comment by morpheus65535** [comment]
So, I've got my test VIP account and, since yesterday, I've been able to download about 1500 subtitles without being throttled (not even once). I'm using v1.2.1-beta.19. I'm not sure what I can do other than that... :-/

**Comment by albino1** [comment]
I've hit a "too many requests" error a few times with a VIP account, though I'm not sure why.  Possibly with multiple searches going on simultaneously, like an upgrades process is going and then something new gets added and starts immediately searching.  It doesn't happen very often though, and I'm not sure if it's related, but thought I would mention it.

**Comment by COTMO** [comment]
I have also VIP account and version.1.2.1. I believe, I have this same issue.
Part of my log:
Throttling opensubtitlescom for 24 hours, until 23/05/03 20:36, because of: DownloadLimitExceeded. Exception info: 'Daily download limit reached. 9 subtitles have been downloaded and -4 remaining subtitles can be downloaded. Quota will be reset in 05 hours and 23 minutes.'

**Comment by morpheus65535** [comment]
@COTMO hummm that's strange... this message is built with data returned by the provider.

@opensubtitles can you share some insight here on why the API is returning those numbers?

**Comment by albino1** [comment]
I just got the error a bit ago, all it says in the log is:

`Throttling opensubtitles for 3 hours, until 23/05/02 23:13, because of: TooManyRequests. Exception info: None`

**Comment by morpheus65535** [comment]
@albino1 yours is related to opensubtitles.org and it's expected because the provider is globally throttling Bazarr. Nothing to worry about but consider migrating to opensubtitles.com.

**Comment by opensubtitles** [comment]
@albino1 I beleive this is for opensubtitles.org - which is ok.
@COTMO do you have VIP on opensubtitles.com and using username and password from .com in settings?
@morpheus65535 maybe it would be good to get info from here: https://opensubtitles.stoplight.io/docs/opensubtitles-api/ea912bb244ef0-user-informations
what API sees and add it always with these kind of problems.

**Comment by COTMO** [comment]
@opensubtitles Yes I have an VIP on opensubtitles.com and of course i'm using that specific login. The VIP has been transferred from opensubtitles.org. With opensubtitles.org I never had any of these issues.
I send to support of opensubtitles.com why I have this isssue. To make sure my VIP account is completly and correctly transferred. Mail support #726270.

**Comment by COTMO** [comment]
@morpheus65535 Can the issue be that I don't have the selection for VIP opensubtitles.com. Because when I add manually in the parameter "VIP=True" in the Config.ini. Everything seems to work normal as it should. I start to see at my account in opensubtitles.com he registers the downloads from the API. 
<img width="434" alt="afbeelding" src="https://user-images.githubusercontent.com/56978008/236014635-d5f7bb54-0dea-4c72-8058-af0f7a554234.png">
<img width="210" alt="afbeelding" src="https://user-images.githubusercontent.com/56978008/236015331-07f0305e-52b8-4978-9dfc-f34a5a160af6.png">

**Comment by morpheus65535** [comment]
@COTMO there's no VIP parameters and the manual change you made isn't doing anything. There's been a change on token validation on opensubtitles.com API yesterday. Maybe it was just enough to force an authentication and generate a new valid token.

**Comment by morpheus65535** [comment]
Is this still an issue?

**Comment by semiviral** [comment]
I'm not sure, as I'm now receiving this error:

```
INFO (get_providers:303) - Throttling opensubtitlescom for 10 minutes, until 23/05/11 01:15, because of: AuthenticationError. Exception info: 'Login failed: Unauthorized'
```

I've checked and double checked the authentication information, as well as removing and re-adding the provider. Are there any other steps that would make sense with the aforementioned error?

**Comment by morpheus65535** [comment]
@semiviral anything special with your password? Special characters?

**Comment by semiviral** [comment]
It does contain special characters, yes.

**Comment by morpheus65535** [comment]
> It does contain special characters, yes.

Can you test with something simple like letters and numbers? Just to rule out encoding issue.

**Comment by semiviral** [comment]
Same result with no symbols,

```
May 11 01:45:45 CURATOR bazarr[78989]: 2023-05-11 01:45:45,665 - root                             (7fb1197da700) :  INFO (get_providers:382) - BAZARR throttled providers have been reset.
May 11 01:46:30 CURATOR bazarr[78989]: 2023-05-11 01:46:30,774 - root                             (7fb1157d2700) :  INFO (get_providers:303) - Throttling opensubtitlescom for 10 minutes, until 23/05/11 01:56, because of: AuthenticationError. Exception info: 'Login failed: Unauthorized'
May 11 01:46:35 CURATOR bazarr[78989]: 2023-05-11 01:46:35,322 - root                             (7fb1157d2700) :  INFO (movies:107) - BAZARR All providers are throttled
```

**Comment by COTMO** [comment]
> Is this still an issue?
Everything works still fine now.

**Comment by COTMO** [comment]
@morpheus65535 Everything works fine.

**Comment by semiviral** [comment]
Is there a reason that Bazarr uses direct credential login, rather than the REST-based key/token API?

**Comment by morpheus65535** [comment]
@opensubtitles can you check out why this user isn't working as expected? idealness5269

**Comment by opensubtitles** [comment]
Hi

we located this use only on opensubtitles.com, he is VIP and all seems good. @semiviral can you log in successfully on www.opensubtitles.com ? If yes, then use same username and password in setting for opensubtitlescom provider. If nothing works:

- try to reset your password on opensubtitles.com
- update your config.

I dont see any reason why it should not work. You can contact us directly at our support and we can test more (reseting your password and test directly on API...)

**Comment by semiviral** [comment]
I have tired the above to no success. I'll open up a support ticket with @opensubtitles and close this issue, as it seems related to their service and not Bazarr.

**Comment by Cookie-Monster-Coder** [comment]
I am receiving the same error as @COTMO Is there any insight on why this is happening?

**Comment by morpheus65535** [comment]
> I am receiving the same error as @COTMO Is there any insight on why this is happening?

Wait for next release that include a fix or switch to beta where it's fixed.

**Comment by morpheus65535** [comment]
@Cookie-Monster-Coder beta.14 will include better debugging. Open your own issue with a debug log reproducing the issue once you've updated to .14.

**Comment by ruipin** [comment]
I'm getting something similar, e.g.

> Daily download limit reached. 16 subtitles have been downloaded and 984 remaining subtitles can be downloaded. Quota will be reset in 01 hours and 56 minutes.

Resetting the provider works for a while, until after ~10 downloads when it triggers the daily download limit error again.

**Comment by rojosinalma** [comment]
This is still happening to me, I changed my password in opensubtitlescom to a number only pw and I verified that my profile shows as VIP.

I also cleaned the cache folder and I still get throttled almost immediately after doing a search.
I'm using v1.4.0

**Comment by opensubtitlesdev** [comment]
hi,

could you:
- put the app in debug mode
- save the full log
- open a ticket to send us that log https://www.opensubtitles.com/en/contact/

opensubtitles

**Comment by rojosinalma** [comment]
Done

**Comment by opensubtitles** [comment]
426 is code, when we detect old Bazarr version - and upgrade is required. Will check your email.

**Comment by patillacode** [comment]
I am on the same situation, I recently purchased the (yearly) VIP status and I can't seem to download anything via Bazarr.


```
 INFO (get_providers:399) - Throttling opensubtitles for 12 hours, until 25/01/31 09:05, because of: PaymentRequired. Exception info: "'' ~ opensubtitles.py@423"
```

![Image](https://github.com/user-attachments/assets/283fa879-5a37-44c1-a08d-6c0bcd665648)


![Image](https://github.com/user-attachments/assets/a590ebfd-0632-49e1-ba5e-c53ff04bf4e2)

```
Bazarr Version

1.5.1
```


Any recommendations?

**Comment by opensubtitles** [comment]
Hi @patillacode 

your VIP status was not yet transfered to opensubtitles.org - as you can see on opensubtitles.com it is working ok - for transfering there is some delay. Now try again, it should work.

**Comment by patillacode** [comment]
@opensubtitles  Legend!

Working as expected

**Comment by theluke** [comment]
I just got VIP on opensubtitles.com, 1 year. ANd I am gettig limoted on bazarr and PLEX

**Comment by opensubtitlesdev** [comment]
here's an article to help you troubleshoot bazarr
https://opensubtitles.tawk.help/article/bazarr

for your account ,there might be an issue with your subscription, if for example you got it with a different email address as your account. for troubleshooting on personal details, better communicate personally, so please send us a ticket mentioning the email used on opensubtitles.com, and on fastspring if different.
