### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by vhtmldev** [morpheus65535/bazarr#2125]
Heyo,

System config:

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
Linux 5.4.0-147-generic

Unsure what happened, it was working one day and then all of sudden its not and throws this when i try to access the webui:

Apr 22 16:40:19 dls bazarr[3635]: Traceback (most recent call last):
Apr 22 16:40:19 dls bazarr[3635]:   File "/opt/bazarr/bazarr/main.py", line 22, in <module>
Apr 22 16:40:19 dls bazarr[3635]:     from init import *  # noqa E402
Apr 22 16:40:19 dls bazarr[3635]:   File "/opt/bazarr/bazarr/init.py", line 13, in <module>
Apr 22 16:40:19 dls bazarr[3635]:     from subliminal_patch.extensions import provider_registry
Apr 22 16:40:19 dls bazarr[3635]:   File "/opt/bazarr/bazarr/../libs/subliminal_patch/__init__.py", line 8, in <module>
Apr 22 16:40:19 dls bazarr[3635]:     from .providers import Provider
Apr 22 16:40:19 dls bazarr[3635]:   File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/__init__.py", line 72, in <module>
Apr 22 16:40:19 dls bazarr[3635]:     mod = importlib.import_module("subliminal_patch.providers.%s" % module_name.lower())
Apr 22 16:40:19 dls bazarr[3635]:   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
Apr 22 16:40:19 dls bazarr[3635]:     return _bootstrap._gcd_import(name[level:], package, level)
Apr 22 16:40:19 dls bazarr[3635]:   File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/zimuku.py", line 10, in <module>
Apr 22 16:40:19 dls bazarr[3635]:     from PIL import Image
Apr 22 16:40:19 dls bazarr[3635]: ModuleNotFoundError: No module named 'PIL'

Nothing has been changed config wise.

**Comment by shocker2** [comment]
I have the same issue, python 3.9 and Pillow-9.5.0.

**Comment by vhtmldev** [comment]
If it helps i have Python 3.8.10

**Comment by morpheus65535** [comment]
https://discord.com/channels/382221826564030464/382221826564030470/1099316701507621057
