### ISSUE TITLE
New install. Cant get Bazarr to start: "Setuptools is replacing distutils."

### ISSUE THREAD

**Issue by thracyturnix** [morpheus65535/bazarr#2128]
**Describe the bug**

sudo -H -u bazarr /usr/bin/python3 /opt/bazarr/bazarr.py
Python version greater than 3.10.x is unsupported. Current version is 3.11.2. Keep in mind that even if it works, you're on your own.
Bazarr starting...
/usr/lib/python3/dist-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
2023-04-28 08:34:56,785 - root                             (7f2ca9a6e040) :  INFO (init:86) - BAZARR installing requirements...
2023-04-28 08:34:57,593 - root                             (7f2ca9a6e040) :  ERROR (init:95) - BAZARR requirements.txt installation result: b'error: externally-managed-environment\n\n\xc3\x97 This environment is externally managed\n\xe2\x95\xb0\xe2\x94\x80> To install Python packages system-wide, try apt install\n    python3-xyz, where xyz is the package you are trying to\n    install.\n    \n    If you wish to install a non-Debian-packaged Python package,\n    create a virtual environment using python3 -m venv path/to/venv.\n    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make\n    sure you have python3-full installed.\n    \n    If you wish to install a non-Debian packaged Python application,\n    it may be easiest to use pipx install xyz, which will manage a\n    virtual environment for you. Make sure you have pipx installed.\n    \n    See /usr/share/doc/python3.11/README.venv for more information.\n\nnote: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.\nhint: See PEP 668 for the detailed specification.\n'
Bazarr exited.

**To Reproduce**

apt-get install python3-dev python3-pip python3-distutils
sudo useradd --system bazarr
sudo usermod -a -G media bazarr
sudo mkdir /etc/opt/bazarr
sudo chmod -R bazarr:media /etc/opt/bazarr
sudo -H -u bazarr /usr/bin/python3 /opt/bazarr/bazarr.py

Also tried systemd:

[Unit]
Description=Bazarr Daemon
After=syslog.target network.target

[Service]
WorkingDirectory=/opt/bazarr/
User=bazarr
Group=media
UMask=0002
Restart=on-failure
RestartSec=5
Type=simple
ExecStart=/usr/bin/python3 /opt/bazarr/bazarr.py
KillSignal=SIGINT
TimeoutStopSec=20
SyslogIdentifier=bazarr
ExecStartPre=/bin/sleep 30

[Install]
WantedBy=multi-user.target

Causes similar error

**Expected behavior**
Start program

**Software (please complete the following information):**
 - Bazarr:1.2.0
 - OS: Ubuntu 22

**Additional context**
Probably something stupid I have missed but cant figure out how to get it to start.

**Comment by morpheus65535** [comment]
`Python version greater than 3.10.x is unsupported. Current version is 3.11.2. Keep in mind that even if it works, you're on your own.`

Looks pretty clear to me as warning ;-)

**Comment by thracyturnix** [comment]
Thanks. I ended up using pyenv to run it as 3.10.x verion

**Comment by theFOAD** [comment]
> Thanks. I ended up using pyenv to run it as 3.10.x verion

Could you show your bazarr.service?  I've been trying to get this to work but although I can start bazarr from the commandline now, I can't seem to get the .service file right.  Thanks.

**Comment by thracyturnix** [comment]
```
[Unit]
Description=Bazarr Daemon
After=syslog.target network.target

# After=syslog.target network.target sonarr.service radarr.service

[Service]
WorkingDirectory=/opt/bazarr/
User=bazarr
Group=media
UMask=0002
Restart=on-failure
RestartSec=5
Type=simple
ExecStart=/usr/bin/python3 /opt/bazarr/bazarr.py
KillSignal=SIGINT
TimeoutStopSec=20
SyslogIdentifier=bazarr
ExecStartPre=/bin/sleep 30

[Install]
WantedBy=multi-user.target


```

**Comment by thracyturnix** [comment]
```
[Unit]
Description=Bazarr Daemon
After=syslog.target network.target

# After=syslog.target network.target sonarr.service radarr.service

[Service]
WorkingDirectory=/opt/bazarr/
User=bazarr
Group=media
UMask=0002
Restart=on-failure
RestartSec=5
Type=simple
ExecStart=/home/bazarr/.pyenv/bin/pyenv exec python /opt/bazarr/bazarr.py
KillSignal=SIGINT
TimeoutStopSec=20
SyslogIdentifier=bazarr
ExecStartPre=/bin/sleep 30

[Install]
WantedBy=multi-user.target

```

**Comment by theFOAD** [comment]
Thank you kindly, it's working now!

**Comment by DrTron** [comment]
As Python3.11 is now the default version in Debian stable (bookworm), any plans to make bazarr compatible with it?

**Comment by morpheus65535** [comment]
> As Python3.11 is now the default version in Debian stable (bookworm), any plans to make bazarr compatible with it?

No plan yet.

**Comment by DrTron** [comment]
Thanks for the update.
With even Debian stable moving past 3.10.x, and Ubuntu LTS likely following suit with 24.4 LTS, I'm thinking that is going to become a mainstream issue.

**Comment by morpheus65535** [comment]
> With even Debian stable moving past 3.10.x, and Ubuntu LTS likely following suit with 24.4 LTS, I'm thinking that is going to become a mainstream issue.

Maybe but that means I have to certify more than 100 dependencies with Python 3.11. It's not just our own code base. There's dozens of hours of testing involved and I don't have time for that right now.

**Comment by DrTron** [comment]
Oh, don't get me wrong, I totally understand that. A software project is a lot of work and that work is very often not appreciated.
But if you decide to tackle this and need help testing, I volunteer for that.

**Comment by ChristianMalazarte** [comment]
Is there a guide on how to get Bazarr working on Debian 12? 

So in the bazarr directory I did:
sudo python3 -m venv .venv
source .venv/bin/activate

But then what do I do? lol I'm a noob.
