### ISSUE TITLE
Not properly recognizing embedded subtitle tags.

### ISSUE THREAD

**Issue by TokerX** [morpheus65535/bazarr#2129]
As the title says Bazarr is not properly recognizing embedded subtitle tags.

![bazarr](https://user-images.githubusercontent.com/21122003/235250206-cbdc9624-1c5b-4b7e-bf39-6c367ae4eaeb.png)

As you can see the Traditional Chinese subtitles are supposedly missing from the MKV file, but they're clearly there.

The problem being that they're not properly read.

![bazarr2](https://user-images.githubusercontent.com/21122003/235250651-0bff1d5c-f33b-4fb6-bccc-a954d588cdfa.png)

This is a screenshot from gMKVExtractGUI, the first example is the file where they're not properly read, the second where they are.

In the first one there is a regional tag, which is either not read or not recognized (even though it should recognize zh-CHS and zh-Hans as Simplified and zh-CHT and zh-Hant as Traditional, not just zh-TW, because Traditional is not only used in Taiwan).

And honestly the second one is even worse because it just has the "zh" tag, which could be either, and it accepts this as "Traditional". Meaning that if there was just a Simplified Chinese subtitle with "zh" tag Bazarr would think it's Traditional. The lack of specificity is of course the fault of the person who made it, still Bazarr shouldn't assume this to be Traditional, and should probably ask whether or not it is.

And I haven't been able to check this for things as "es-419", but I suspect it to be ignored as well since Bazarr likes to call Latin American subtitles "es-MX" (even though Latin America is slightly bigger than Mexico).

And Bazarr certainly isn't alone in this, this is an issue with Plex as well (it does read them correctly with the tags I mentioned as external though). But if MKVToolNix can read and write all these tags, why can't you? You manage to read at least one tag, why not the other, more important, ones?

**Comment by morpheus65535** [comment]
I'm gonna be totally honest with you: I have no clue how those regional languages works. We're guessing them the best we can but, to be perfectly clear, it's a fucking mess. I'm speaking French Canadian and I dont give a shit about French French as it's ok to me. I have no plan to rework that part but I'm open to pull request improving this. I'll be happy to review it. In the mean time, I'll close this as this isn't planned to be fixed because it's not an issue to me.

**Comment by 1993alexey** [comment]
I'm following this issue. The exact same problem and hoping to get some traction. I have a lot of media with embedded zh-TW SRT subs, but Bazarr has redownloaded subtitles for all of them.

**Comment by morpheus65535** [comment]
@1993alexey show me ffprobe output where it's properly tagged but Bazarr don't index it properly?

**Comment by 1993alexey** [comment]
@morpheus65535, thank you for your quick response. I see the problem now. ffprobe might not be parsing the language correctly. 

```
  Stream #0:4(chi): Subtitle: subrip
    Metadata:
      BPS             : 51
      DURATION        : 02:47:31.916000000
      NUMBER_OF_FRAMES: 2119
      NUMBER_OF_BYTES : 65020
      _STATISTICS_WRITING_APP: mkvmerge v79.0 ('Funeral Pyres') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2023-09-14 22:01:26
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
```

Same file only using `mkvinfo`
```
| + Track
|  + Track number: 5 (track ID for mkvmerge & mkvextract: 4)
|  + Track UID: 6258560652631321214
|  + Track type: subtitles
|  + "Default track" flag: 0
|  + "Lacing" flag: 0
|  + Language: chi
|  + Codec ID: S_TEXT/UTF8
|  + Language (IETF BCP 47): zh-TW
```

The subtitles were added with MKVToolNix

**Comment by morpheus65535** [comment]
@1993alexey IIRC, mediainfo does support IETF BCP 47. You can install it and make sure it's in path then tell Bazarr to use it for embedded subtitles indexing.

**Comment by 1993alexey** [comment]
Thanks a lot! It fixed my problem.
