### ISSUE TITLE
Bazarr not recognizing embedded ASS subtitles

### ISSUE THREAD

**Issue by TokerX** [morpheus65535/bazarr#2132]
**Describe the bug**
ASS subtitles embedded in MKV files aren't being recognized.

The subtitles are properly named, except that even though they are labeled as "Forced", "SDH", "Simplified" and "Traditional" they don't actually have the extra tags for it (not that Bazarr would read them if there were there).

In other words, in the example screenshot is should actually see them double (e.g. there'd be 2 subtitles named filename.en.ass). 

The fact that they're double shouldn't be part of the problem since I have other files with Simplified and Traditional Chinese SRT subtitles and here Bazarr does say there's an embedded Traditional Chinese one (which is actually another bug, because without these extra tags it's just a assuming based on the fact that it sees "Chinese").

So, given that with SRT there's no real problem when it comes to recognizing the subtitles the only reason can be that these are ASS subtitles.

Have an MKV file with embedded ASS subtitles.

**Expected behavior**
For Bazarr to recognize ASS subtitles.

**Screenshots**
![brolzart](https://user-images.githubusercontent.com/21122003/235649584-975efd6b-81d9-40d5-8229-d5a26a6bf738.png)

**Software (please complete the following information):**
 - Bazarr: 1.2.1
 - Sonarr version 3.0.10.1567
 - OS: Windows 11

While filling out this last part I found another bug: it says Windows 10 instead of Windows 11 (the version number is correct though).
![bazzz_win](https://user-images.githubusercontent.com/21122003/235649454-f6e8c7fc-35ed-464d-8140-df108089adb5.png)

It's got the 22621 right...
![winoos](https://user-images.githubusercontent.com/21122003/235651566-6a4c6658-b92a-4d85-9aad-8c66f724989a.png)

**Comment by morpheus65535** [comment]
You probably have messed with `Use embedded subtitles` in Settings-->Subtitles. This is working perfectly fine. Click on `Scan disk` may help reindex the embedded subtitles.

Regarding the Windows version reported, this is provided by Python that interpret the operating system result, nothing I can fix on my side.

**Comment by TokerX** [comment]
![bazarr_subtitles](https://user-images.githubusercontent.com/21122003/236013027-924dc322-a259-4cf0-8d61-67581ae3ed05.png)
These are the settings. Apart from the parser (because it claims to give better results) I think they're all the default settings, no? Either way, it's not set to ignore ASS.

I unchecked "Show Only Desired Languages" to see if the other embedded subtitles are showing, did a rescan with Sonarr, then synced and updated with Sonarr, and updated all episode subtitles from disk.

No embedded subtitles are showing up now, no matter what format. And I know for a fact it was showing embedded subtitles earlier because I was wondering what that 3rd color (missing, external, embedded) was at the time. And no settings have been changed (apart from unchecking "Show Only Desired Languages" just now) since the initial set-up.

So that's kind of weird.

As for the Windows 11 thing. It's not that important lol, just noticed it at the time. And indeed it is a Python thing, just did a test myself. There is a workaround: if sys.getwindowsversion().build > 22000 returns true it's Windows 11. Doesn't really seem worth it to implement though.

**Comment by TokerX** [comment]
Changing the parser to ffprobe fixed it. No idea why mediainfo is no longer working.

**Comment by morpheus65535** [comment]
Is mediainfo still installed and in path? Something in log about missing binary?

**Comment by TokerX** [comment]
Yes to both. I think it stopped working after the previous reboot, but no idea why. I downloaded it again yesterday, but as I recall from a post here on Github I'd have to restart Bazarr as well. And a restart of Bazarr always seems to start the subtitle search from the beginning, and I would like it to finish for once (which at the current rate would be somewhere next week lol). It's not that urgent and probably caused by some weird Windows stuff (as usual) anyway. I do have a question about the difference between ffprobe and mediainfo, but I'll leave that for Discord.

As for the logs: nothing but the usual provider connection issues and throttling, and a lot of this:
Skipping 5 lines for [(10, 'OCR_fixes', {}), (40, 'common', {})] mod
Skipping 4 lines for [(10, 'OCR_fixes', {}), (40, 'common', {})] mod 

and one "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER."

The last one is clearly related to wrong encoding (either Chinese or Spanish accented characters) on a downloaded subtitle. 

The skipping 4 or 5 lines do have a bug icon, but given their frequency most likely related to downloaded subtitles as well? If it is somehow related to embedded subtitles it's an issue with ffprobe, because that's what it's set to now.

**Comment by morpheus65535** [comment]
ffprobe or mediainfo are only used to index embedded subtitles. Embedded subtitles extraction is always done by ffmpeg. 

I'm not that familiar with those mods as they have been implemented by pannal in subzero and are simply used as-is in Bazarr. I don't use them so I don't have any experience with them to help you on this one.
