### ISSUE TITLE
Supersubtitles provider (download) not functioning correctly since bazarr version 1.2.0

### ISSUE THREAD

**Issue by perlakiz** [morpheus65535/bazarr#2133]
**Describe the bug**
I have encountered this bug since version 1.2.0 and have tested all beta versions and the latest stable version 1.2.1, but the issue persists. There was a bug and fix related to search functionality, which is now working correctly #2095 . However, automatic download is not working and manual search followed by download button also doesn't work. There is no error message on the interface, it simply does not download.
If I click on the provider URL during manual search, it does download the subtitle to the client's computer, and I am able to upload it. All other providers I use are working correctly.
If I replace the subliminal_patch/providers/supersubtitles.py file with the supersubtitles.py file from the v1.1.4 tag, it works perfectly fine.

**To Reproduce**
1. Go to the specific tv show/movie.
2. Click on the search button.
OR
Click on the manual search button and then click on the download button in the search results.
4. The interface displays "Searching subtitles... All Tasks Completed" message, but nothing happens.

**Expected behavior**
The expected behavior is that automatic download works and for manual search, the download button functions properly.

**Screenshots**
![bazarr2](https://user-images.githubusercontent.com/72102760/235772964-c9cb8e1e-5b3c-4225-98a2-531910ff1ea9.jpg)

**Software (please complete the following information):**
 - Bazarr: v1.2.1-ls194 by linuxserver.io
 - Radarr version: 4.4.4.7068-ls170 by linuxserver.io
 - Sonarr version: 3.0.10.1567-ls189 by linuxserver.io
 - OS: Debian 11, all docker

**Additional context**
Logs:
2023-05-02 22:41:46,119 - root                             (7f1b0c2b7b38) :  ERROR (manual:193) - BAZARR No valid Subtitles file found for this file: xy.mkv

**Comment by morpheus65535** [comment]
@vitiko98 can you still take a look at that provider to see what wrong with it? Thanks.

**Comment by vitiko98** [comment]
```
tests/subliminal_patch/test_supersubtitles.py::test_list_episode_subtitles PASSED                                          
tests/subliminal_patch/test_supersubtitles.py::test_download_episode_subtitle PASSED                                     
tests/subliminal_patch/test_supersubtitles.py::test_list_and_download_movie_subtitles PASSED                                                                                            
tests/subliminal_patch/test_supersubtitles.py::test_download_movie_subtitle PASSED                                                                                                       
tests/subliminal_patch/test_supersubtitles.py::test_subtitle_reprs PASSED                                                                                                                
tests/subliminal_patch/test_supersubtitles.py::test_list_video_2 PASSED 
```

All download tests passed. :p

I have no idea what subtitles to look for your issue since there's zero information about the media. Please reproduce and share the debug log.

**Comment by vitiko98** [comment]
Fixed. Thank you!
