### ISSUE TITLE
yifysubtitles goes to MissingSchema state after automated search

### ISSUE THREAD

**Issue by Miniterror** [morpheus65535/bazarr#2139]
**Describe the bug**
Doing a manual search i can find subtitles and everything works.
Doing the automated search the Yifysubtitles goes in error state of MissingSchema.

**To Reproduce**
Open a movie manually and start a automated search.

**Expected behavior**
Automated search not yielding the MisscingSchema state

**Screenshots**
![image](https://user-images.githubusercontent.com/101180056/236782576-6a59dcde-cf27-4bd5-855e-45bf925ce411.png)

**Software (please complete the following information):**
 - Bazarr: 1.2.1
 - Radarr version: 4.4.4.7068
 - Sonarr version: 3.0.10.1566
 - OS: Ubuntu server 22.04 in LXC on Proxmox

**Additional context**
Pastebin to debug logging, first i do the manual search, after it i do the automated search.
https://pastebin.com/qi3qMJsW

**Comment by Jessomadic** [comment]
Also am getting this same error

**Comment by Jessomadic** [comment]
I'm on the Dev branch so when it updates i'll take a look

**Comment by Jessomadic** [comment]
Seems to have resolved the issue!
