### ISSUE TITLE
Language settings not saved

### ISSUE THREAD

**Issue by mvanlijden** [morpheus65535/bazarr#214]
The language settings are not saved properly. Bazarr also gives the error _"Some fields are in error and you can't save settings until you have corrected them. Be sure to check in every tabs."_ every time you open settings. If I update the settings and save it, it wil give an ok message and say it is working but I doubt that.

Initial setup ran fine and saved ok according to the messages. However when going into settings i received the above error. Now I see that the languages field in the subliminal tab is never saved. It is reset every time.  All other fields are saved fine to the config.ini. However i see no mention of the languages there.

I have tried saving with subtitles NL,EN active as default and both on sonarr and radarr.
Also tried to save with NL as single language. Both have had no effect.

 - Bazarr: 0.6.7
 - Radarr version 0.2.0.1120
 - Sonarr version 2.0.0.5252
 - OS: linuxserver docker on UnRaid 6.6.3

**Comment by halali** [comment]
Update your bazarr and delete bazarr.db file

**Comment by morpheus65535** [comment]
Dev image have been updated 3 hours ago with a fix for that. Master image is going to be updated following LSIO schedule. I'm not aware of when exactly it should be done but I hope it will be ASAP.

**Comment by morpheus65535** [comment]
Latest image have been updated yesterday. Please test and report back.

**Comment by thed1ceman2** [comment]
Just tested this and it doesn't appear to be working here (assuming it's in 0.6.7)

**Comment by morpheus65535** [comment]
It’s a known issue in 0.6.7. Please wait for 0.6.7.1 that should be released ASAP. You’ll need to delete your bazarr.db.

**Comment by morpheus65535** [comment]
0.6.7.1 image is available.

**Comment by mvanlijden** [comment]
Fixed with new version and deletion of bazarr.db.
Thanks!

**Comment by morpheus65535** [comment]
Good, thanks for the test!
