### ISSUE TITLE
Whisper provider throwing error

### ISSUE THREAD

**Issue by silverbullettruck2001** [morpheus65535/bazarr#2140]
I receive the following error when trying to use Whisper provider:
Throttling whisperai for 10 minutes, until 23/05/08 11:53, because of: KeyError. Exception info: 'detected_language'

**To Reproduce**
1. Deploy Whisper AI docker container
2. Configure Bazarr provider for Whisper AI container
3. Search for a subtitle
4. Review logs

**Expected behavior**
Whisper AI should generate an SRT file for the video file and then Bazarr should copy that file to the video file location with the appropriate name

**Software (please complete the following information):**
 - Bazarr: v1.2.1
 - Radarr: 4.4.4.7068
 - Sonarr: 3.0.10.1567
 - OS: Ubuntu 22.04.2 LTS

**Comment by morpheus65535** [comment]
@ayancey Could you take a look please?

**Comment by ayancey** [comment]
@silverbullettruck2001 Can you please enable debug logging and attach logs of the error happening?

**Comment by silverbullettruck2001** [comment]
@ayancey attached are the logs you requested.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/11425403/bazarr.log)

**Comment by ayancey** [comment]
@silverbullettruck2001 Can you please send me the media file `/media/movies/Who Done It The Clue Documentary (2022) [720p] [BluRay] [YTS.MX]/Who.Done.It.The.Clue.Documentary.2022.720p.BluRay.x264.AAC-[YTS.MX].mp4` so I can test for myself? My suspicion is that it can't determine the language of the file. Maybe because there's no talking in the first 30 seconds.

**Comment by silverbullettruck2001** [comment]
I could send it to you, but how do you want me to do that?  Also, I checked and there is talking within the first 30 seconds.  It starts at 16 seconds into it.  Also, as for the metadata solution.  How would I accomplish that?  What would I use to set that?

**Comment by silverbullettruck2001** [comment]
Also, is there a way on the Provider configuration I could just specify to always use English (or whatever language the user wants to specify)?  My entire library only contains English language audio files so I don't really need to have it detect it.  If the Provider is not configured with a language, then it could attempt to do the detection, but this would just allow it skip that if it's unnecessary.  Would that work?

**Comment by RedFox134** [comment]
> Also, is there a way on the Provider configuration I could just specify to always use English (or whatever language the user wants to specify)? My entire library only contains English language audio files so I don't really need to have it detect it. If the Provider is not configured with a language, then it could attempt to do the detection, but this would just allow it skip that if it's unnecessary. Would that work?


Pretty sure Whisper only translates into English by default.  When you specify the language you're telling Whisper what it's converting from.  So if I tell it Japanese I'm saying the audio it needs to translate from is in Japanese.  It's pretty good about guessing on its own, but it can speed it up a little if you tell it what language the audio you feed it is before it starts running.  Whisper might support more languages in the future, but I'm pretty sure it only supports translating to English right now.

Sorry if I misunderstood your ask here!  I agree if it isn't already passing the language Bazarr detected for the audio file it'd probably be nice to have it pass that into Whisper to speed up the translation to English.  I think if you submit a new enhancement [here](https://bazarr.featureupvote.com/) they'll review and approve or reject depending on how it fits into their roadmap.

**Comment by silverbullettruck2001** [comment]
I'm just trying to find a way to avoid the error and proceed with translation.  I figured since you suggested that it couldn't detect it there could just be a way to force a language so that it would skip trying to detect it.

**Comment by ayancey** [comment]
@silverbullettruck2001 Can you try to visit the ASR service in your web browser and test the /detect-language endpoint manually?

**Comment by morpheus65535** [comment]
No news, good news. Reopen if required!
