### ISSUE TITLE
Add support for Telegram Topics

### ISSUE THREAD

**Issue by didyouexpectthat** [morpheus65535/bazarr#2141]
Telegram updated its API to include a new function called Topics which allows you to have your bot talk into a thread rather than in the general area. 

Almost all of these issues are closed and implemented at time of writing: 
https://github.com/Lidarr/Lidarr/issues/3528
https://github.com/Sonarr/Sonarr/issues/5486
https://github.com/Radarr/Radarr/issues/8199
https://github.com/Tautulli/Tautulli/issues/1980
https://github.com/sct/overseerr/issues/3389

I am hoping to get the same functionality for Bazarr.

**Comment by didyouexpectthat** [comment]
Actually I realize again that this is for apprise. Sorry.

**Comment by yegle** [comment]
Apprise was updated to support Telegram topics.

This issue should be used to track the update of the vendored apprise.

**Comment by yegle** [comment]
https://github.com/caronc/apprise/pull/854/files
