### ISSUE TITLE
Using Faster Whisper instead of "normal" model

### ISSUE THREAD

**Issue by Deathproof76** [morpheus65535/bazarr#2144]
Repost because this issue https://github.com/ahmetoner/whisper-asr-webservice/issues/99 by @MrSaiclops got lost in the wrong repo and I'm interested as well:

"Hello,

I am running a Docker Container alongside Bazarr to generate subtitles for media that otherwise would not return a result. The compose looks like this:

  whisper-asr-webservice:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: Whisper
    environment:
      - ASR_MODEL=base
    ports:
      - 9000:9000
    restart: unless-stopped
This was retrieved from here: https://github.com/bazarr/wiki/pull/201/files

It's working fine, but I would like to have it use faster-whisper. Is it doing so automatically or do I need to change something?

Thanks!"

So yeah in short: ahmetoner/whisper-asr-webservice seems to be able to use faster-whisper now https://github.com/ahmetoner/whisper-asr-webservice/releases/tag/v1.1.0
https://github.com/guillaumekln/faster-whisper faster-whisper seems to quadruple performance and also lower ram requirements while having the same accuracy.
So far the new whisper provider seems to work well for my purposes and 4-times the performance would be great!

I used onerahmet/openai-whisper-asr-webservice:latest by mistake at first too and it seemed to work for me too. From what I can tell a pr by @ayancey https://github.com/ahmetoner/whisper-asr-webservice/pull/82 has been merged.

![Screenshot 2023-05-16 120022](https://github.com/morpheus65535/bazarr/assets/95944496/cc27f4b5-df9b-485d-bd10-1fe195bb83e0)
Maybe it's as easy as altering the default api request string a little bit.

Thanks for all the hard work btw!

**Comment by morpheus65535** [comment]
This is more a feature request than an issue but I'll let @ayancey give you feedback.

**Comment by ayancey** [comment]
In progress on this. I'm having issues getting faster-whisper to work.

**Comment by MrSaiclops** [comment]
Oh yay! Let me know if there's anything we can help tear or trial!

**Comment by morpheus65535** [comment]
@ayancey still working on this?

**Comment by morpheus65535** [comment]
@ayancey so what should we do? This is more a feature request than an issue. I see no reason to keep it open right now. I'll be happy to review a PR in the future when you get this fixed.
