### ISSUE TITLE
"Unknown" Radarr version on status page

### ISSUE THREAD

**Issue by sid3windr** [morpheus65535/bazarr#2148]
**Describe the bug**
Bazarr can't find Radarr's version.

**To Reproduce**
Configure Radarr and click "Test". Test button shows the Radarr version correctly. Save the configuration.

The "System>Status" page lists "unknown" and the following error is logged:

```21/05/2023 17:16:18|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): radarrhost:443|
21/05/2023 17:16:18|DEBUG   |urllib3.connectionpool          |https://radarrhost:443 "GET /api/system/status?apikey=(removed) HTTP/1.1" 404 0|
21/05/2023 17:16:18|DEBUG   |root                            |BAZARR cannot get Radarr version|
21/05/2023 17:16:18|DEBUG   |root                            |BAZARR got this Radarr version from its API: unknown|
```

When clicking the "Test" button, a secondary API URL is also tried successfully:

```
21/05/2023 17:21:40|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): radarrhost:443|
21/05/2023 17:21:40|DEBUG   |urllib3.connectionpool          |https://radarrhost:443 "GET /api/v3/system/status?apikey=(removed) HTTP/1.1" 200 None|
```

**Expected behavior**
Correct version displayed.

**Software (please complete the following information):**
 - Bazarr: 1.2.1
 - Radarr version 4.1.0.6175
 - OS: Debian Linux

**Comment by halali** [comment]
Your radarr host is probably wrong...

Its not recommended use reverse proxy to connect radarr...

And also this is for issues. Please come to discord for support.

**Comment by sid3windr** [comment]
The radarr host is correct, and as you can see it finds the version fine. It can also sync and work with Radarr just fine. As it's not trying the correct API version (which it does on the Radarr configuration page), this looks like an issue to me.

**Comment by morpheus65535** [comment]
Did you tried some dimple stuff like refresh browser or restart Bazarr?

Also, you've dismissed halali's advice about not connecting through proxy. You should give it a try.

**Comment by morpheus65535** [comment]
No news, good news. Reopen if required!
