### ISSUE TITLE
Sorting of language codes

### ISSUE THREAD

**Issue by mvanlijden** [morpheus65535/bazarr#215]
The list of languages comprised of a two character list, i think ISO 639-1 based?
However the sorting is done on ISO 639-2?

For example the language of The Netherlands is in our language Nederlands, but called Dutch in english.
ISO 639-1 = NL
ISO 639-2 = DUT (of sometimes NLD)

This makes it so the the NL is sorted in the D. This also happens with other languages and makes the list not very readible.

Maybe displaying all language info there will be an option? For Dutch then NL/DUT and EN/ENG etc

**Comment by morpheus65535** [comment]
Should be fixed by the same fix commited sooner today. I don't have this behavior iwth my setup.
