### ISSUE TITLE
Failed to send Pushover notification

### ISSUE THREAD

**Issue by thegabriele97** [morpheus65535/bazarr#2151]
**Describe the bug**
Unable to send Pushover notification. When I click on "Test" button, in the log page I see the following error: 

"Failed to send Pushover notification to ALL_DEVICES: Bad Request - Unsupported Parameters., error=400."

PushOver's Bazarr setting is configured in the following way: `pover://{user_key}@{app_key}`

**Software (please complete the following information):**
 - Bazarr: v 1.2.1
 - OS: Debian

**Comment by morpheus65535** [comment]
Apprise Pushover configuration steps can be found on their wiki: https://github.com/caronc/apprise/wiki/Notify_pushover
