### ISSUE TITLE
OpenSubtitles.com AuthenticationError

### ISSUE THREAD

**Issue by Petemir** [morpheus65535/bazarr#2152]
**Describe the bug**
Hello, thanks for the great app :) . I saw the notice and tried changing from OpenSubtitles.org to OpenSubtitles.com, but now I am getting an AuthenticationError. I went through several past issues (#2121 #1935 , [reddit](https://old.reddit.com/r/bazarr/comments/129gd9w/throttling_opensubtitlescom_for_10_minutes/)) and tried their suggestions, but no fix so far.

Please let me know if there's any more info you need.

Thanks!

I tried:
* Simplified my password (removing special characters and making it shorter)
* Removed the files in config/cache and restarting the docker container
* Deleting the providers (Settings/Providers), resetting the providers (System/Providers) , and re-configuring the providers (Setting/Providers) 
* Logged in with username, not e-mail (the same info available from config.ini works in OpenSubtitles.com)

**To Reproduce**
1. Add new OpenSubtitles.com provider, save
2. Go to an episode
3. Search subtitles for the episode
4. Try to download one of the OpenSubtitles.com subtitles
5. "AuthenticationError" appears on System/Providers

**Expected behavior**
I expect a working login to OpenSubtitles.com and be able to download subtitles from it.

**Logs**
(showing try 1/3)

```
24/05/2023 14:39:00|INFO    |subliminal_patch.providers.opensubtitlescom|Downloading subtitle <OpenSubtitlesComSubtitle 'https://www.opensubtitles.com/es/subtitles/legacy/xxxxxxxxx' [es:None]>|
24/05/2023 14:39:00|DEBUG   |urllib3.connectionpool          |https://api.opensubtitles.com:443 "POST /api/v1/download HTTP/1.1" 401 None|
24/05/2023 14:39:01|DEBUG   |subliminal_patch.providers.mixins|Retrying OpenSubtitlesComProvider, try: 1/3, exception: Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/mixins.py", line 47, in retry
    return f()
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/opensubtitlescom.py", line 394, in <lambda>
    lambda: checked(
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/opensubtitlescom.py", line 465, in checked
    raise AuthenticationError(f'Login failed: {response.reason}')
subliminal.exceptions.AuthenticationError: Login failed: Unauthorized
```

**Software (please complete the following information):**
 - Bazarr: v1.2.1
 - Radarr version     4.4.4.7068
 - Sonarr version     3.0.8.1507
 - OS: LibreElec  11.0.1

**Comment by ChrisHansenTech** [comment]
I have suddenly been having this exact same issue, it just started this week.

**Comment by morpheus65535** [comment]
Thanks for reporting but from our side, it seems to be some isolated events. The provider is returning a 401 when we send your credentials. I suggest you open a ticket on their support forums.

**Comment by enduity** [comment]
I have the same issue. Running the login request from Postman works with the exact same credentials.

**Comment by morpheus65535** [comment]
> I have the same issue. Running the login request from Postman works with the exact same credentials.

I don't know what to tell you. Yesterday alone we had 4 600 users logged in opensubtitles.com and they were able to download 170 000 subtitles.

I would really want to be able to help you but all those users are using the same code as you do and it works. We use the login endpoint as documented in the provider API docs.

**Comment by enduity** [comment]
Okay, restarting Bazarr seems to have suddenly fixed the issue now, also discovered that I wasn't looking for the cache in the right place, so maybe deleting that would've worked too. I added some extra logging to the provider code and, if this issue reoccurs, I will let you know what I can discover. Still wouldn't be ideal if always after some interval a restart is required for OpenSubtitles to work. Maybe the people for whom it works flawlessly are all VIP subscribers?

**Comment by Petemir** [comment]
> Okay, restarting Bazarr seems to have suddenly fixed the issue now, also discovered that I wasn't looking for the cache in the right place, so maybe deleting that would've worked too. I added some extra logging to the provider code and, if this issue reoccurs, I will let you know what I can discover. Still wouldn't be ideal if always after some interval a restart is required for OpenSubtitles to work. Maybe the people for whom it works flawlessly are all VIP subscribers?
> 
> 
> 
> EDIT: Also I am sorry for apparently not checking off the most basic troubleshooting step of them all, turning it off and on again :)

Hello, do you mind sharing the modified code? Restarting does not fix it for me, so I may benefit from extra debugging.

**Comment by Petemir** [comment]
> Thanks for reporting but from our side, it seems to be some isolated events. The provider is returning a 401 when we send your credentials. I suggest you open a ticket on their support forums.

Ok, thanks! I'll check on their side too, then.

**Comment by enduity** [comment]
I believe I have fixed it for now. I needed to change `Beaker` to `Bearer` [here](https://github.com/morpheus65535/bazarr/blob/b485dd9c716b784b9b945d5093161c60a8e21f80/libs/subliminal_patch/providers/opensubtitlescom.py#LL392C43-L392C43) and then clear the `cache` directory again. Then I reset the providers and it seems to work properly.

**Comment by morpheus65535** [comment]
> I believe I have fixed it for now. I needed to change `Beaker` to `Bearer` [here](https://github.com/morpheus65535/bazarr/blob/b485dd9c716b784b9b945d5093161c60a8e21f80/libs/subliminal_patch/providers/opensubtitlescom.py#LL392C43-L392C43) and then clear the `cache` directory again. Then I reset the providers and it seems to work properly.

OMFG... 2 things comes to mind right now:
1-how did I miss this one...
2-how in heel does it even works for all those users!

I'll fix that in upcoming beta. Thanks @enduity !

**Comment by Petemir** [comment]
> I needed to change `Beaker` to `Bearer` [here](https://github.com/morpheus65535/bazarr/blob/b485dd9c716b784b9b945d5093161c60a8e21f80/libs/subliminal_patch/providers/opensubtitlescom.py#LL392C43-L392C43)

Amazing find, thanks!!

**Comment by morpheus65535** [comment]
Will be fixed in upcoming beta that will be released during the night. Thanks and hopefully it will works for every users running into the same issue.

**Comment by enduity** [comment]
> > I believe I have fixed it for now. I needed to change `Beaker` to `Bearer` [here](https://github.com/morpheus65535/bazarr/blob/b485dd9c716b784b9b945d5093161c60a8e21f80/libs/subliminal_patch/providers/opensubtitlescom.py#LL392C43-L392C43) and then clear the `cache` directory again. Then I reset the providers and it seems to work properly.
> 
> OMFG... 2 things comes to mind right now: 1-how did I miss this one... 2-how in heel does it even works for all those users!
> 
> I'll fix that in upcoming beta. Thanks @enduity !

My theory is that there are for some reason quite big limits right now for unauthorized users with the new API and so they were able to download the subtitles even without proper login.

**Comment by morpheus65535** [comment]
As this is fixed, I'll close the issue.

**Comment by NiklasOlofsson** [comment]
Whats the thing with .com page having a pleace for adding "API consumers" where you can create different consumers with different settings per consumer. From that youll get an api key. I guess vi kan use the api using that key and setting up Bazarr as consumer and get a key we can ingest in Bazarr somehow.

**Comment by morpheus65535** [comment]
@NiklasOlofsson as stated multiple times, this apikey is static for all user of Bazarr, is embedded in the code and not configurable. This is the proper way to do it as discussed with os.com admin/dev. Here's the API doc if you want to read about it: https://opensubtitles.stoplight.io/docs/opensubtitles-api/e3750fd63a100-getting-started

**Comment by IIIdefconIII** [comment]
I went Providers -> op there pressed reset and the error went gone, maybe a bug?
