### ISSUE TITLE
Multiple Instances of Radarr and Sonarr 

### ISSUE THREAD

**Issue by almulder** [morpheus65535/bazarr#2157]
There is no way to add additional instances of  Radarr or Sonarr

Example: The ability to Add multiple instances, As I have Radarr: Movies, Movies 4K, Standup Comedy. 

How can I add them?

**Comment by morpheus65535** [comment]
This will never happens.

**Comment by halali** [comment]
If you jave multiple instances of radarr sonarr you need also multiple instance of bazarr
