### ISSUE TITLE
Throttling opensubtitlescom: Authenticacation Error

### ISSUE THREAD

**Issue by almulder** [morpheus65535/bazarr#2158]
**Describe the bug**
Throttling opensubtitlescom for 10 minutes, until 23/05/30 17:09, because of: AuthenticationError. Exception info: 'Login failed: Unauthorized'

**Expected behavior**
I have my username and password, I can log into opensubtitles.com without issue, but Bazarr keeps throwing error

**Software (please complete the following information):**
 - Bazarr:  v 1.2.1

**Additional context**
Would be great if there was a test button when setting up providers, instead of having to wait 10 mins between tries.

**Comment by morpheus65535** [comment]
Duplicate of #2152
