### ISSUE TITLE
Cant download or find PT-PT subitles on opensubtitles.com

### ISSUE THREAD

**Issue by VilhenaChen** [morpheus65535/bazarr#2159]
**Describe the bug**
Noticed that when using opensubtitles.com i cant download or find manually any subitles from PT-PT, only PT-BR, but using the "old" opensubtitles.org everyting works as expected

**Expected behavior**
Be able to download or find (manually) subitles for PT-PT

**Software (please complete the following information):**
 - Bazarr: [1.2.1]
 - OS: [Debian 11 64Bits]

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Can you test and confirm please?

**Comment by VilhenaChen** [comment]
From what i tested the issue is now fix on  v1.2.2-beta.12
Thanks
