### ISSUE TITLE
Apprise version bump to 1.4.0

### ISSUE THREAD

**Issue by yegle** [morpheus65535/bazarr#2163]
Hi,

Would it be possible to update the vendored apprise to 1.4.0?

There's a new feature in Apprise that allows Telegram notifications using topic: https://github.com/caronc/apprise/commit/e83cba66a62b313bc4d9006019819c8a47032cb5

It would be great if you can update the bundled version.

(Alternatively, maybe this should be a dependency in requirements.txt?)

**Comment by morpheus65535** [comment]
Should be updated in upcoming beta.
