### ISSUE TITLE
Translate Subtitle issue

### ISSUE THREAD

**Issue by jim608** [morpheus65535/bazarr#2166]
The Chinese Simplified and Chinese Traditional options of Translate Subtitle are opposite
Selecting to translate into Chinese Traditional will result in Chinese Simplified
Chinese Traditional = 體
Chinese Simplified  = 体
bazarr v1.2.1
(I use google translate to write this issue, you may understand wrong)

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Please test and confirm!

**Comment by jim608** [comment]
Just tested the beta and no problems found so far.
Thank you!!
