### ISSUE TITLE
Incomplete selection- or info-screen

### ISSUE THREAD

**Issue by COTMO** [morpheus65535/bazarr#2167]
**Describe the bug**
As you can see on the screenshots below. I don't have the complete selection- or info-screen.

**To Reproduce**
Screenshot 1:
Go to a movie and click on Translate.

Screenshot 2:
Go for example to a movie and search manually.
When having the overview go to the info-button.
You see incomplete infoscreen

**Expected behavior**
To see complete selection- or info-screen

**Screenshots**
Screenshot 1:
<img width="706" alt="afbeelding" src="https://github.com/morpheus65535/bazarr/assets/56978008/46ee0562-88bc-4bd7-adc2-a015506b8628">
Screenshot 2:
<img width="706" alt="afbeelding" src="https://github.com/morpheus65535/bazarr/assets/56978008/f4182a52-4c9d-4fb0-8010-088d6a71dec3">

**Software (please complete the following information):**
 - Bazarr: v1.2.2-beta.13
 - Radarr version 4.5.2.7388
 - Sonarr version 3.0.10.1567
 - OS: Synology -  Docker

**Additional context**

**Comment by morpheus65535** [comment]
@COTMO should be fixed in upcoming beta. Thanks for reporting.
