### ISSUE TITLE
Throttling embeddedsubtitles for 10 minutes, until 23/06/11 08:39, because of: UnicodeDecodeError. Exception info: 'charmap'

### ISSUE THREAD

**Issue by Cookies1488** [morpheus65535/bazarr#2168]
**Describe the bug**
While trying to search for wanted subtitles using embeddedsubtitles provider, I'm getting UnicodeDecodeError
**To Reproduce**
1. Go to 'Wanted' - "Episodes"
2. Click on 'Search All'
3. Get UnicodeDecodeError in "System" - "Providers" 
4. Search stops.
I tried different tv shows, it happened with only few of them from my library, anime mostly.
I'll attach debug log file. 
[bazarr (5).log](https://github.com/morpheus65535/bazarr/files/11714164/bazarr.5.log)

**Expected behavior**
Search for embedded subtitles runs without errors.

**Software (please complete the following information):**
 - Bazarr: [e.g. v 0.6.1]
 - Radarr version [e.g. v 0.2.0.0001]

 - Sonarr version [e.g. v 2.0.0.0001]
 - OS: [e.g. Windows 10]

**Additional context**

**Comment by vitiko98** [comment]
Fixed. Thanks!
