### ISSUE TITLE
UnicodeEncodeError in movie title causing 500 Error

### ISSUE THREAD

**Issue by petrichor8** [morpheus65535/bazarr#217]
**Description**
Movie with unicode in folder name causes 500 error, no movies listed.

**To Reproduce**
Have folder with unicode in title
1. eg:  Autómata (2014) 

**Expected behavior**
Shouldn't choke on unicode

**Software (please complete the following information):**
 - Bazarr: v0.6.7.1
 - Radarr version 0.2.0.1120
 - Sonarr version 2.0.0.5270
 - OS: Linux Mint 17.2 Rafaela

**Additional context**

`UnicodeEncodeError('ascii', u'/media/{obfuscated}/movies/adult/Aut\xf3mata (2014)/Aut\xf3mata.mkv', 37, 38, 'ordinal not in range(128)')`

```
Traceback (most recent call last):
  File "/opt/bazarr/bazarr/../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/opt/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/opt/bazarr/bazarr/main.py", line 153, in wrapper
    return func(*a, **ka)
  File "/opt/bazarr/bazarr/main.py", line 732, in movies
    output = template('movies', __file__=__file__, bazarr_version=bazarr_version, rows=data, languages=languages, missing_count=missing_count, page=page, max_page=max_page, base_url=base_url, single_language=single_language, page_size=page_size, current_port=port)
  File "/opt/bazarr/bazarr/../libs/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/opt/bazarr/bazarr/../libs/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "/opt/bazarr/bazarr/../libs/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/opt/bazarr/views/movies.tpl", line 82, in <module>
    %if os.path.isfile(row[2]):
  File "/usr/lib/python2.7/genericpath.py", line 37, in isfile
    st = os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 37: ordinal not in range(128)
```

**Possible Fix**
https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20

**Comment by morpheus65535** [comment]
Path with unicode character have proven to be working. You probably have something wrong on your system encoding configuration. 

Hint: https://unix.stackexchange.com/questions/145580/debian-thinks-my-file-system-is-encoded-as-iso-8859-1

**Comment by petrichor8** [comment]
System default for linux mint is UTF8, and in checking settings just to be sure, the `/etc/default/local` file contains `LANG="en_US.UTF-8"`

No other programs (sonarr/radarr/nzbget/etc) have issues with unicode in filepaths/names, and as show in the filepath in the original example, the system is fully supporting the characters.

`adult/Autómata (2014)/Autómata.mkv`

Thanks for the quick reply, but I don't think it's a system issue.  If I find any fixes, I'll send a pull request, at this point, I think it's likely there's an issue with unicode, but I may just rename folders to skirt the issue so I can use the program.

**Comment by petrichor8** [comment]
I was able to edit the `views/movies.tpl` file to encode the filepath/name, and fix the issue on my end, I'll set up a pull request for you to review

**Comment by petrichor8** [comment]
@pannal upstart file (https://github.com/morpheus65535/bazarr/issues/220)

**Comment by pannal** [comment]
This might be directly related to #190.
Can you try starting bazarr manually by `su - user`-ing into the user it should start with and see if the issue persists?

**Comment by pannal** [comment]
Possibly related: https://askubuntu.com/questions/682998/upstart-script-is-not-picking-system-default-environment-variable

**Comment by pannal** [comment]
Possible solution: https://stackoverflow.com/a/13425026

**Comment by pannal** [comment]
Oh, even more portable solution for your upstart script perhaps: https://stackoverflow.com/a/49473736

**Comment by petrichor8** [comment]
damn, that was it! 

I added 

`env LANG=en_US.UTF-8`

to my bazaar.conf file, and it runs just fine!

Thanks for hanging with me, and most of all for making this project!  I'm looking forward to turning it loose on my library!
