### ISSUE TITLE
Embedded Subtitle Provider: HI Fallback not working

### ISSUE THREAD

**Issue by eglia** [morpheus65535/bazarr#2171]
**Describe the bug**
The Hearing Impaired Fallback functionality is not working. The condition is detected correctly, but the subtitles are still reported as hearing impaired.

**To Reproduce**
1. Enable Hearing Impaired Fallback
2. Extract subtitles for a file with a single subtitle with HI = True
2. See that the subtitle is reported by the embedded provider with HI = True

**Expected behavior**
The subtitle should be marked as HI = False

**Screenshots**
![image](https://github.com/morpheus65535/bazarr/assets/17555261/5facda44-497b-45ae-a6e2-5f6711275e7b)
![image](https://github.com/morpheus65535/bazarr/assets/17555261/c7773b30-1fea-4780-b5fb-d7d5ccebe78c)
![image](https://github.com/morpheus65535/bazarr/assets/17555261/20f7ea97-ba83-40e7-ae63-1a91a148c615)
```
12/06/2023 08:56:39|DEBUG   |subliminal_patch.providers.embeddedsubtitles|Checking possible incomplete subtitles (max frames: 511)|
12/06/2023 08:56:39|DEBUG   |subliminal_patch.providers.embeddedsubtitles|Appending subtitle: <SUBRIP: FFprobeMkvSubtitleTags: en@HEARING_IMPAIRED>|
12/06/2023 08:56:39|DEBUG   |subliminal_patch.providers.embeddedsubtitles|Appending subtitle: <SUBRIP: FFprobeMkvSubtitleTags: de@GENERIC>|
12/06/2023 08:56:39|DEBUG   |subliminal_patch.providers.embeddedsubtitles|Checking HI fallback for 'de' language|
12/06/2023 08:56:39|DEBUG   |subliminal_patch.providers.embeddedsubtitles|HI fallback not needed: [<SUBRIP: FFprobeMkvSubtitleTags: de@GENERIC>]|
12/06/2023 08:56:39|DEBUG   |subliminal_patch.providers.embeddedsubtitles|Checking HI fallback for 'en' language|
12/06/2023 08:56:39|DEBUG   |subliminal_patch.providers.embeddedsubtitles|Checking HI fallback for 'de' language|
12/06/2023 08:56:39|DEBUG   |subliminal_patch.providers.embeddedsubtitles|Checking HI fallback for 'en' language|
12/06/2023 08:56:39|DEBUG   |subliminal_patch.providers.embeddedsubtitles|HI fallback: updating <SUBRIP: FFprobeMkvSubtitleTags: en@HEARING_IMPAIRED> HI to False (only subtitle found is HI)|
```

**Software (please complete the following information):**
 - Bazarr: 1.2.1
 - Radarr version 4.5.2.7388
 - Sonarr version 3.0.10.1567
 - OS: Docker (Linux)

**Additional context**
[The problematic code line.](https://github.com/morpheus65535/bazarr/blob/38d95c5a7ca427813fe213c57fd1c924fe18861e/libs/subliminal_patch/providers/embeddedsubtitles.py#L167) As the name implies, the function only checks for the condition, but does not modify the returned results.

**Comment by morpheus65535** [comment]
This feature is not meant to remove HI tags from the extracted HI subtitles but simply to allow use HI if non-HI isn't available. If you want to remove HI tags, you should use the mods tools.

**Comment by eglia** [comment]
But it doesn't do anything except reporting the condition in the debug log. So what's the point of it? The found subtitles look exactly the same with HI fallback enabled or disabled.
The problem I'm actually having is that automatic search actually chooses a subtitle from another provider with ~90% score instead of the embedded subtitle with 99% score (which is HI).

**Comment by morpheus65535** [comment]
@vitiko98 are you able to take a look at this one please?

**Comment by vitiko98** [comment]
My last commit will do the trick.

**Comment by morpheus65535** [comment]
@eglia can you test and confirm upcoming beta?
