### ISSUE TITLE
Whipserai: Score 241 is below min_score (324)

### ISSUE THREAD

**Issue by Mavyre** [morpheus65535/bazarr#2173]
**Describe the bug**
I followed everything in the Bazarr Wiki about adding Whisper AI. After a few days, no new subtitles were added by Whisper, so I decided to investigate. The debug log shows that WhisperAI discovered subtitle score always is 241, and might be down the min_score threashold.

**To Reproduce**
1. Go to https://wiki.bazarr.media/Additional-Configuration/Whisper-Provider/
2. Follow the guide and add WhisperAI provider
3. Try to search for new subtitles

**Expected behavior**
The Wiki should indicate the minimum score that WhisperAI is calculated at, so the user can configure its instance to actually use Whisper-generated subtitles.

**Logs**
```
14/06/2023 09:30:11|DEBUG   |subliminal_patch.core           |<WhisperAISubtitle None [en:forced:None]>: Found matches {'episode', 'series', 'season'}|
14/06/2023 09:30:11|DEBUG   |subliminal_patch.score          |Scores to use for <Episode ['tvshow', 2023, 3x1]>: {'hash': 359, 'series': 180, 'year': 90, 'season': 30, 'episode': 30, 'release_group': 15, 'source': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'streaming_service': 0, 'hearing_impaired': 1, 'edition': 0}|
14/06/2023 09:30:11|DEBUG   |subliminal_patch.score          |Matched hearing_impaired|
14/06/2023 09:30:11|INFO    |subliminal_patch.score          |<WhisperAISubtitle None [en:forced:None]>: Computed score 241 with final matches {'hearing_impaired', 'episode', 'series', 'season'}|
14/06/2023 09:30:11|INFO    |subliminal_patch.core           |<WhisperAISubtitle None [en:forced:None]>: Score 241 is below min_score (324)|
14/06/2023 09:30:11|INFO    |subliminal_patch.core_persistent|Downloaded 0 subtitle(s)|
```

**Software (please complete the following information):**
 - Bazarr: v1.2.1
 - Radarr version: 4.5.2.7388
 - Sonarr version: 3.0.9.1549
 - OS: Docker Container

**Additional context**
Sonarr score threashold is at 90%
Radarr score threashold is at 70%

**Comment by morpheus65535** [comment]
This isn't an issue, this is by design. This provider will always give a fixed score to subtitles it generate. We have no way of knowing if the generated subtitles is of better quality than the other. Globally, subtitles generated by this provider are of low quality. I wouldn't want that to be preferred over a perfectly good subtitles from another provider. If you want them to "download" automatically, you're going to have to lower your minimum score.

**Comment by Mavyre** [comment]
@morpheus65535 I clearly understand that this was by design. It makes sense, and I would have designed it the same way. However, is it possible to add to the wiki the default score of the Whisper generation?

The issue was more about documentation enhancement, than actually fixing things, as I can't find which minimum score to setup to allow whisperai subtitles to be selected

**Comment by morpheus65535** [comment]
Make sense, we'll add something about it. Can you try the same thing with a movie and give me the score? Thanks!

**Comment by Mavyre** [comment]
Sure, there you go!
```
Scores to use for <Movie ['mymovie', 2023]>: {'hash': 119, 'title': 60, 'year': 30, 'release_group': 15, 'source': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'streaming_service': 0, 'edition': 0, 'hearing_impaired': 1}|
15/06/2023 00:50:58|DEBUG   |subliminal_patch.score          |Matched hearing_impaired|
15/06/2023 00:50:58|INFO    |subliminal_patch.score          |<WhisperAISubtitle None [en:None]>: Computed score 61 with final matches {'hearing_impaired', 'title'}|
15/06/2023 00:50:58|INFO    |subliminal_patch.core           |<WhisperAISubtitle None [en:None]>: Score 61 is below min_score (84)|
15/06/2023 00:50:58|INFO    |subliminal_patch.core_persistent|Downloaded 0 subtitle(s)|
```

**Comment by morpheus65535** [comment]
Wiki updated to include mention about lowering the score and the static scores for episodes and movies: https://wiki.bazarr.media/Additional-Configuration/Whisper-Provider/

**Comment by Mavyre** [comment]
Sounds perfect! Thank you for your help!
