### ISSUE TITLE
Subtitles being "upgraded" even when no language profile

### ISSUE THREAD

**Issue by ascheel319** [morpheus65535/bazarr#2174]
**Describe the bug**
I have a couple of movies in my library that about every 12 hours try and "upgrade" the subs that it has, it looks like it's never actually an upgrade just going by the numbers. It seems to always grab the same subs. The other day I removed the only language profile I had from these 3 movies and they are still doing it. The movies in question are "The Chronicles of Narnia: The Voyage of the Dawn Treader" "Moana" and "The Hobbit: The Battle of the Five Armies". At first I was told maybe it was because of the special characters but that wouldn't explain Moana. I noticed this about 10 days ago but it might have been going on longer than that as that is when I fixed my subs provider issue (I put in my username instead of my full email for my opensubtitlescom account).

**To Reproduce**
I have no idea. Maybe add the 3 movies I stated? That's my only guess.

**Expected behavior**
To not grab subtitles on movies that are not requested

**Screenshots**
![image](https://github.com/morpheus65535/bazarr/assets/41492233/c291f4f5-6211-48bf-889d-d8beab66be3d)

**Software (please complete the following information):**
 - Bazarr: 1.2.1
 - Radarr version: 4.5.2.7388
 - OS: Unraid 6.11.5

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta, please test and confirm. Thanks for reporting!

**Comment by morpheus65535** [comment]
No news, good news.
