### ISSUE TITLE
Hearing Impaired option removes all .ass styles

### ISSUE THREAD

**Issue by moznr542** [morpheus65535/bazarr#2175]
**Describe the bug**
"Hearing Impaired" option under subtitles -> post-processing,  converts .ass to .srt with all styles (not just hearing impaired tags) removed, even with "Use Original Format" enabled under language profile.

**To Reproduce**
Manually upload .ass file with "Hearing Impaired" option enabled under subtitles -> post-processing

**Expected behavior**
"Hearing Impaired" option should not convert .ass to .srt with all styles removed. It should only modify tags meant for hearing impaired.

**Software (please complete the following information):**
 - Bazarr: 1.2.1
 - Sonarr version 3.0.10.1567
 - OS: Linux-5.15.0-75-generic-x86_64-with-glibc2.35

**Comment by morpheus65535** [comment]
Is that only happening with remove HI mods?

**Comment by moznr542** [comment]
Yes. If I disable remove HI, it works correctly.

**Comment by morpheus65535** [comment]
I meant: other mods doesn't do that? Only remove HI?

**Comment by morpheus65535** [comment]
Still something to fix here?

**Comment by morpheus65535** [comment]
No news, good news!
