### ISSUE TITLE
Bazarr get stuck starting since 1.2

### ISSUE THREAD

**Issue by arlllk** [morpheus65535/bazarr#2176]
**Describe the bug**
If I try to use any Bazarr release since 1.2 ([1.1.4](https://github.com/morpheus65535/bazarr/releases/tag/v1.1.4) is the last one without that problem), the container get stuck on initialization before it can open its ports, I have tried to use hotio and LSIO docker image, and I have the same problem with both

**To Reproduce**
1. Start any container with version 1.2.x
2. Check logs of container
4. Containter stuck on Starting new HTTPS connection

**Expected behavior**
Containter starts and open ports

**Software (please complete the following information):**
 - Bazarr: 1.2.2-beta.21
 - Radarr version 4.6.3.7511
 - Sonarr version 4.0.0.539
 - OS: Ubuntu 20.04.6 LTS

**Additional context**
All 1.2.x versions get stuck at the same point, I have tried with stable and nightly versions
`DEBUG (connectionpool:1003) - Starting new HTTPS connection (1): raw.githubusercontent.com:443`

Attached logs
[bazarr-log.txt](https://github.com/morpheus65535/bazarr/files/11796056/bazarr-log.txt)

In the logs at line 36-37 the connection with GitHub is successful

PS the container doesn't crash, it just get stuck for at least days

**Comment by halali** [comment]
You have issue to connect to github...

**Comment by morpheus65535** [comment]
Version 1.2.0 bring the announcements features that need to get file from https://raw.githubcontent.com. It looks that for some reason this specific url is blocked by something external to Bazarr.

**Comment by arlllk** [comment]
I believe the problem exist in the flow of writing the file, and not on the network connection
[On this line](https://github.com/morpheus65535/bazarr/blob/master/bazarr/app/announcements.py#L56)

And it look like is a permission error on my server, thanks

**Comment by morpheus65535** [comment]
@arlllk maybe but it should raise an exception if that's the case. Of course, Bazarr should have recursive write access in it's own directory.
