### ISSUE TITLE
All episodes in [dutch] but serie show [english] audio

### ISSUE THREAD

**Issue by windsurf** [morpheus65535/bazarr#2177]
All episodes in [dutch] but serie (header) show [english] audio.

For example "Baantjer", dutch original audio, dutch spoken on all the episodes. 
Still shows [english] as audio language in the HEADER.

Therefore a subtitle search on [dutch] wanted, it's obsolete for subtitle search/download.
There's no option to change the 'audio' value in the lists from [english] to [whatever]

Bazarr Version 1.2.1
Package Version v1.2.1-ls194 by linuxserver.io
Sonarr Version 3.0.10.1567
Radarr Version 4.5.2.7388

**Comment by morpheus65535** [comment]
Bazarr use the audio profile language from Sonarr. It's merely informative and isn't used. The audio language used for subtitles searching is the episode one that we get from the file. This isn't an issue.

**Comment by TRaSH-** [comment]
And what does Sonarr show?
