### ISSUE TITLE
Bazarr path mapping dropdown not showing correctly

### ISSUE THREAD

**Issue by ChrissprayCode** [morpheus65535/bazarr#2178]
**Describe the bug**
Path mapping dropdown for "Bazarr" not showing all the options. Settings > Radarr > Path Mappings > Bazarr.

**To Reproduce**

1. Install Bazarr with latest build
2. Add Radarr to Bazarr (IP, API Key etc), test
3. Scroll to "Path Mappings"
4. Set Radarr pathing to /data/media/movies/
5. Go to set Bazarr path, only shows '/app/','/bin/','/command/','/config/'

**Expected behavior**
Should be able to select the same path for Bazarr as I did for Radarr

**Screenshots**
![image](https://github.com/morpheus65535/bazarr/assets/84575404/07139b85-da8b-4ba5-b7ba-0818324a4cbc)

**Software (please complete the following information):**
Bazarr Version: 1.2.1
Package Version: v1.2.1-ls199 by linuxserver.io
Operating System: Linux-5.19.17-Unraid-x86_64-with
Python Version: 3.10.12
Bazarr Directory: /app/bazarr/bin
Bazarr Config Directory: /config

**Additional context**
From Discord: "Seems to be an issue with nightly. Path mapping dropdown only show first 5 items."

**Comment by morpheus65535** [comment]
Thanks for reporting, we're working on it (or will be).

**Comment by morpheus65535** [comment]
Fixed in latest beta.
