### ISSUE TITLE
Dev Build - JSON Decode Error With Supersubtitles

### ISSUE THREAD

**Issue by pchang388** [morpheus65535/bazarr#2180]
**Describe the bug**
* Use latest dev build from linuxserverio docker: `development-version-v1.2.2-beta.21`
* I did not notice this behavior previously on `1.2.1` image build, I was trying the dev build to see if it would help with an existing problem I had with opensubtitles.com
* It appears either the response from supersubtitles has changed (it's no longer JSON) or the way bazarr is handling the response has changeed
```
Throttling supersubtitles for 10 minutes, until 23/06/21 10:51, because of: JSONDecodeError. Exception info: 'Expecting value: line 1 column 1 (char 0)'
```

**To Reproduce**
1. Use image tag from linuxserverio as mentioned
2. Add supersubtitles as provider with SSL
3. Search for any subtitle that supersubtitles has
4. See JSON decode error pop up in logs
5. Notice no results from supersubtitles since the response is not valid when searching

**Expected behavior**
Supersubtitles is a known provider, it should be able to handle responses from their API

**Software (please complete the following information):**
- Bazarr: `development-version-v1.2.2-beta.21`
- Radarr version `4.5.2.7388`
- Sonarr version `3.0.10.1567`
- OS: Docker - linxserverio

**Comment by morpheus65535** [comment]
Can you provide debug log while reproducing this issue?

**Comment by pchang388** [comment]
I am also unable to reproduce after it happened for a few hours that day. I am chalking this one up as a provider issue for now that was intermittent. Will open a new issue with debug logs if it pops up again. Thanks!
