### ISSUE TITLE
Recognition of subtitles for movies

### ISSUE THREAD

**Issue by COTMO** [morpheus65535/bazarr#2181]
**Describe the bug**
Seems like it doesn't recognize the language of the existing subtitles.
And as consequence now it has missing subtitles for all the movies. 

**To Reproduce**
-

**Expected behavior**
Should recognize the language of the existing subtitles. 

**Screenshots**
<img width="1442" alt="afbeelding" src="https://github.com/morpheus65535/bazarr/assets/56978008/ed34d6fa-3568-49d6-b0da-689d2ccd5db1">
<img width="1442" alt="afbeelding" src="https://github.com/morpheus65535/bazarr/assets/56978008/3673e8c2-4b07-4a05-bc3d-c97975e8d13a">

**Software (please complete the following information):**
 - Bazarr: v1.2.2-beta.24
 - Radarr version 4.5.2.7388
 - Sonarr version 3.0.10.1567
 - OS: Linux-3.10.108-x86_64-with
 
**Additional context**

**Comment by morpheus65535** [comment]
Working on it.

**Comment by COTMO** [comment]
With the new beta all fine now. Thanks!
