### ISSUE TITLE
Error syncing tv shows from sonarr

### ISSUE THREAD

**Issue by danpowell88** [morpheus65535/bazarr#2188]
**Describe the bug**
When the sync task for sonarr runs it is throwing an exception and I end up with no episodes synced.

**To Reproduce**
Trigger a sync of episodes

**Expected behavior**
Episodes sync

**Screenshots**
```
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/bazarr/bin/bazarr/sonarr/sync/episodes.py", line 67, in sync_episodes
    item = [x for x in episodeFiles if x[\'id\'] == episode[\'episodeFileId\']]
TypeError: \'NoneType\' object is not iterable
```

**Software (please complete the following information):**
Bazarr Version 1.2.2
Package Version v1.2.2-ls512 by linuxserver.io
Sonarr Version 4.0.0.548
Radarr Version 4.5.2.7388
Operating System Linux-5.19.17-Unraid-x86_64-with
Python Version 3.10.12
Bazarr Directory /app/bazarr/bin
Bazarr Config Directory/config
Uptime 0d 00:03:52
Time Zone Australia/Brisbane

**Additional context**
I've tried this on both the latest and development tags of the linuxserverio docker container with the same result.

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Please test and confirm.

**Comment by morpheus65535** [comment]
No news, good news.
