### ISSUE TITLE
Embedded provider consuming all memory when stuck

### ISSUE THREAD

**Issue by vin047** [morpheus65535/bazarr#2194]
**Describe the bug**
Using only the embedded provider, bazarr gets stuck on a specific file and consumes all available memory.

**To Reproduce**
1. Remove all providers except embedded provider.
2. Run search on movies.
3. Once bazarr reaches the problematic file, it'll hang and consume all memory and swap space.

**Expected behavior**
Ideally bazarr should extract the subtitle correctly, but if there is an issue with the file, bazarr should report it in the logs and move on to the next file gracefully without consuming all available memory.

**Software (please complete the following information):**
 - Bazarr: 1.2.2
 - Radarr: 4.5.2.7388
 - Sonarr: 3.0.10.1567
 - OS: Linux, Debian 11

**Additional context**
Running bazarr inside an LXC container on Proxmox, Debian 11 host. Resources provisioned: 
- 1 CPU (host CPU type)
- 1 GB RAM
- 512 MB swap
- 4 GB hard disk

Bazarr was installed following the [Linux (Debian) install instructions](https://wiki.bazarr.media/Getting-Started/Installation/Linux/linux/).

Bazarr runs under its own user and group, `bazarr:bazarr`.

I have attached debug logs:
- The memory consumption balloons from (I think) line 3709.
- There is an ERROR on line 3836.
- I believe the process is killed by Proxmox host and the embedded provider is no longer available, as can be seen on line 3847.

[bazarr.log](https://github.com/morpheus65535/bazarr/files/11957767/bazarr.log)

**Comment by halali** [comment]
I think 1gb ram is little low if you want extract subtitles from file... If file is big you need more than 1gb ram to extract it.

**Comment by vitiko98** [comment]
> I think 1gb ram is little low if you want extract subtitles from file... If file is big you need more than 1gb ram to extract it.

While it's true that this device seems underpowered for this task, it's important to note that FFmpeg does not load the entire file in memory. Instead, the process is done in chunks; otherwise we wouldn't be able to extract subtitles from 4k files.


Best you can do for now is setting the timeout to a lower value to avoid hanging for too long.

![image](https://github.com/morpheus65535/bazarr/assets/59455966/b1916ff5-5783-4ee4-b1c8-65c1a1d6d5a6)

**Comment by morpheus65535** [comment]
Just to be sure, what is the output of this command: `/opt/bazarr/bin/Linux/x86_64/ffmpeg/ffmpeg -v warning -stats -y -i /pool1/media/movies/your.name.-2016/your.name.2016.bluray-1080p.proper.x264.dts.5.1[ja+en]-geek.mkv -map 0:4 -c:s copy -f srt /opt/bazarr/data/cache/embeddedsubtitlesprovider/your.name.2016.bluray-1080p.proper.x264.dts.5.1[ja+en]-geek.en.srt.srt -map 0:5 -c:s copy -f ass /opt/bazarr/data/cache/embeddedsubtitlesprovider/your.name.2016.bluray-1080p.proper.x264.dts.5.1[ja+en]-geek.en.ass.ass -map 0:6 -c:s copy -f ass /opt/bazarr/data/cache/embeddedsubtitlesprovider/your.name.2016.bluray-1080p.proper.x264.dts.5.1[ja+en]-geek.zh.ass.ass -map 0:7 -c:s copy -f ass /opt/bazarr/data/cache/embeddedsubtitlesprovider/your.name.2016.bluray-1080p.proper.x264.dts.5.1[ja+en]-geek.zh.ass.ass -map 0:8 -c:s copy -f ass /opt/bazarr/data/cache/embeddedsubtitlesprovider/your.name.2016.bluray-1080p.proper.x264.dts.5.1[ja+en]-geek.zh.ass.ass -map 0:9 -c:s copy -f ass /opt/bazarr/data/cache/embeddedsubtitlesprovider/your.name.2016.bluray-1080p.proper.x264.dts.5.1[ja+en]-geek.zh.ass.ass -map 0:10 -c:s copy -f ass /opt/bazarr/data/cache/embeddedsubtitlesprovider/your.name.2016.bluray-1080p.proper.x264.dts.5.1[ja+en]-geek.en.ass.ass -map 0:12 -c:s copy -f ass /opt/bazarr/data/cache/embeddedsubtitlesprovider/your.name.2016.bluray-1080p.proper.x264.dts.5.1[ja+en]-geek.zh.ass.ass -map 0:13 -c:s copy -f ass /opt/bazarr/data/cache/embeddedsubtitlesprovider/your.name.2016.bluray-1080p.proper.x264.dts.5.1[ja+en]-geek.zh.ass.ass -map 0:14 -c:s copy -f ass /opt/bazarr/data/cache/embeddedsubtitlesprovider/your.name.2016.bluray-1080p.proper.x264.dts.5.1[ja+en]-geek.zh.ass.ass -map 0:15 -c:s copy -f ass /opt/bazarr/data/cache/embeddedsubtitlesprovider/your.name.2016.bluray-1080p.proper.x264.dts.5.1[ja+en]-geek.zh.ass.ass -map 0:16 -c:s copy -f ass /opt/bazarr/data/cache/embeddedsubtitlesprovider/your.name.2016.bluray-1080p.proper.x264.dts.5.1[ja+en]-geek.zh.ass.ass -map 0:17 -c:s copy -f ass /opt/bazarr/data/cache/embeddedsubtitlesprovider/your.name.2016.bluray-1080p.proper.x264.dts.5.1[ja+en]-geek.zh.ass.ass`

**Comment by vin047** [comment]
Hm... the low resources don't seem to have this effect on any of my other files though, some of which are larger; bazarr handles them without issues.

> Just to be sure, what is the output of this command: ...

Output:
```
[matroska,webm @ 0x5c8c540] Could not find codec parameters for stream 11 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
```

In addition, the memory usage and swap space immediately fills up and the container stalls. So it looks like this is the underlying command thats causing the issue.

**Comment by morpheus65535** [comment]
@vitiko98 why would it works on track 11 when it's not even in the command?

**Comment by vitiko98** [comment]
> @vitiko98 why would it works on track 11 when it's not even in the command?

Looks like a FFmpeg warning related to the container. This doesn't seem to be related to the provider since it does not support PGS streams.

A bunch of ASS streams being extracted at once might be choking your system. This behavior is more related to FFmpeg; neither fese nor Bazarr is designed for complex memory management. In this case, they are acting as wrappers of FFmpeg. Reducing the timeout is the last resort.
