### ISSUE TITLE
BAZARR unable to index external subtitles: 'charmap' codec can't decode... character maps to <undefined>

### ISSUE THREAD

**Issue by vin047** [morpheus65535/bazarr#2196]
**Describe the bug**
Getting this issue with a specific file when doing a disk scan. The subtitle file was generated using Bazarr's embedded subtitle provider.

```shell
|BAZARR unable to index external subtitles
...
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 34309: character maps to <undefined>|
```

**To Reproduce**
1. Configure Bazarr to only use the embedded subtitle provider.
2. Wanted -> Movies -> Search All
3. After generating the srt file, the above error is present in the logs.
4. Doing disk scans trigger the error when it reaches said file.

**Expected behavior**
Generated srt file is valid and bazarr doesn't report an issue when scanning/decoding it.

**Software (please complete the following information):**
 - Bazarr: 1.2.2
 - Radarr version: 4.5.2.7388
 - Sonarr version: 3.0.10.1567
 - OS: Linux, Debian 11 (LXC container)

**Additional context**
Seen a few other threads mentioned with similar error. I believe i've set up locale properly though.

```bash
$ python3 -c "import sys; print(sys.getdefaultencoding())"
utf-8
```
```bash
$ locale
LANG=C
LANGUAGE=
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=
```
```bash
$ locale -a
C
C.UTF-8
POSIX
en_US.utf8
```

Attached relevant section of debug log after initiating scan. Also attached the srt file (that was generated using the embedded subtitle provider) which is giving the error.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/11970598/bazarr.log)
[subtitle.zip](https://github.com/morpheus65535/bazarr/files/11970601/subtitle.zip)

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Can you confirm?

**Comment by vin047** [comment]
Tested with the latest stable release (v1.2.3), looks like its working. Thanks!
