### ISSUE TITLE
does not "see" existing subtitles, keeps downloading repeatedly

### ISSUE THREAD

**Issue by rmichelena** [morpheus65535/bazarr#2197]
Not happening in all movies, just since upgraded to 1.2.2 and configured "language equals", I've caught at least one movie (there could be more) where this happens.
"wanted" shows the movie missing the subtitles (EN, ES as per profile)
the movie page also shows those missing
"history" shows downloads of those subtitles
the subtitles are on disk
and it keeps downloading the very same subtitles again
restarting the container and/or doing a manual scan (on that movie alone) does not solve it

Yesterday I upgraded to 1.2.2 and configured language equals only one line: ES-Latin = ES
and changed the default profile that was EN+ES+EA to just EN+ES

<img width="907" alt="Screenshot 2023-07-07 at 17 17 17" src="https://github.com/morpheus65535/bazarr/assets/77797875/309d56f4-94a5-4988-8f80-fc49485206fd">
<img width="772" alt="Screenshot 2023-07-07 at 16 57 09" src="https://github.com/morpheus65535/bazarr/assets/77797875/87347e98-332a-4139-ae38-9e0e37e9e872">
<img width="1241" alt="Screenshot 2023-07-07 at 16 56 23" src="https://github.com/morpheus65535/bazarr/assets/77797875/55be35f5-89b6-462d-9083-e9f38e518235">
<img width="1158" alt="Screenshot 2023-07-07 at 16 55 59" src="https://github.com/morpheus65535/bazarr/assets/77797875/c682a8df-396c-4b90-9d49-83810a0ebfa5">

**Comment by rmichelena** [comment]
Damn, sorry, I see it was already posted, same as #2189 

However, it's curious that it's been introduced in 1.2.2 and affects some random movie that had its subtitles there since long ago.

**Comment by morpheus65535** [comment]
That's normal, all external subtitles are reindex every time so it can affect previous or new subtitles.

**Comment by rmichelena** [comment]
Hey was it supposed to be fixed on 1.2.3 ?
Keeps happening... and only with that one movie.

**Comment by morpheus65535** [comment]
Enable debug log and scan disk for this movie.

**Comment by rmichelena** [comment]
attached the log and the subtitles
[bazarr.log](https://github.com/morpheus65535/bazarr/files/12135578/bazarr.log)
[subs.zip](https://github.com/morpheus65535/bazarr/files/12135581/subs.zip)

**Comment by morpheus65535** [comment]
For an unknown reason, this subtitles file encoding cannot be guessed properly. Did you try to blacklist it and get another one?

**Comment by rmichelena** [comment]
These subtitles were there since long ago ; then suddenly after upgrading to 1.2.2, they became invisible to Bazarr and it downloaded (same or other, dunno) again... and again, and again.
I really have solved the issue by configuring the movie as zero subtitles (no profile), and the subs remain there and Plex sees them. I just wanted to help in case it was a real bug. Which I think it might be (e.g. if I open the subs in TextEdit it has no problem guessing the encoding). Also because it's very unlikely that subs for the same movie in 3 different languages (en, es, es-MX) all have the same encoding problem. But as it hasn't happened in any other movie in my library, I have no theory as to why it happens. Maybe there is some word present in all 3 subs that throws it off, maybe it's related to the filename, whatever it is, it was introduced in 1.2.2

**Comment by morpheus65535** [comment]
Bazarr rely on external libraries to guess the encoding of the subtitles files. We've been using `charamel` for a long time but it's no longer maintained and doesn't support Python 3.11. We have to move to something else and the new library that we use is `charset-normalizer` and it's doing a pretty nice job. For your specific movie, it seems to be unable to guess properly. I'll try to look into this again but it may unfortunately be an isolated case.

I haven't seen any significative increase in downloads between 1.2.2 and now so I don't think it's affecting a lot of users.

**Comment by morpheus65535** [comment]
The problem seems to be with a specific subtitles file: `The.Wonders.[Le.Meraviglie].2014.DVDRip.x264.HORiZON-ArtSubs.sub`

Because there's no language code in the file name, Bazarr try to guess the language from the filename. The `guess_external_subtitles` function raise an unhandled exception that prevent the indexing of external subtitles to complete and even the other 2 external subtitles aren't indexed because of that. I'll handle this exception properly and simply ignore the problematic subtitles. With this, the other subtitles should get indexed properly and wn't be downloaded again.

**Comment by morpheus65535** [comment]
Should be fixed in upcoming 1.2.5-beta.0.
