### ISSUE TITLE
Two slashes are prefixed to Sonarr API Base URL using default settings

### ISSUE THREAD

**Issue by mattsson** [morpheus65535/bazarr#22]
When using the default settings, i.e. Sonarr's Base URL is set as `/`, two slashes are prefixed to the API URL:

`GET //api/episode?seriesId=75&apikey={key}`

This is fixed by changing `/` to nothing in the settings, which changes the URL to:

`GET /api/episode?seriesId=75&apikey={key}`

**Comment by morpheus65535** [comment]
Thank you for submitting a bug! It's been corrected and is now available in master branch.
