### ISSUE TITLE
linux upstart file in wiki

### ISSUE THREAD

**Issue by petrichor8** [morpheus65535/bazarr#220]
Here's the contents of the Upstart file I made for Debian/Ubuntu.

This is an init upstart file. It assumes you've installed Bazarr in: 
`/opt/bazarr`

You have to create a `bazarr.conf` file in `/etc/init/` (`sudo nano /etc/init/bazarr.conf`) that would contain the following text:

    description "Upstart Script to run Bazarr as a service on Ubuntu/Debian based systems, as well as others"
    author "A Bazarr User"
    
    #uncomment this line to use with UTF-8 OS
    #env LANG=en_US.UTF-8

    #Set user and group for the process if desired
    #setuid myUserID
    #setgid myGroupID
    
    #start after all services come up
    start on runlevel [2345]
    stop on runlevel [016]
    
    # Automatically restart process if crashed
    respawn
    
    #run startup file
    exec python /opt/bazarr/bazarr.py
    
Tested on linux mint 17.2 XFCE (Ubuntu 14.04) / python 2.7.12

**Comment by halali** [comment]
Just to let you know. Bazarr support python 2.7.13 and greater

**Comment by petrichor8** [comment]
You know what, I completely missed that line in the install, good looking out.  I can say that I have it running seemingly fine on 2.7.12, with a tweak for unicode filenames.  I'll have to look into updating python to a newer version.

**Comment by halali** [comment]
It run until you set form login.

**Comment by petrichor8** [comment]
_*edited to set the lang for utf-8 OS_

**Comment by morpheus65535** [comment]
Thanks!

**Comment by morpheus65535** [comment]
https://github.com/morpheus65535/bazarr/wiki/Upstart-script-for-Debian-Ubuntu

**Comment by pannal** [comment]
I would incorporate [this](https://stackoverflow.com/a/49473736) as a `script` tag inside the upstart file. Most people don't know about their locales and environments.

**Comment by petrichor8** [comment]
good point, got it working, updated file above

**Comment by morpheus65535** [comment]
Updated in wiki. Thanks!
