### ISSUE TITLE
Wrong MIME type for javascript scripts causes blank page

### ISSUE THREAD

**Issue by yoonsio** [morpheus65535/bazarr#2202]
**Describe the bug**

Javascript scripts render text instead of real javascript content.
For example, accessing /assets/index-cc035c9c.js returns a text response with the following content:
```
found: /assets/index-cc035c9c.js
```
This leads to a blank page because all javascript scripts fail to load with following error message:
```
hooks-2dd1664c.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**To Reproduce**
1. Deploy a bazarr server on the Kubernetes cluster using the image `linuxserver/bazarr:1.2.3`
2. Access the URL to see javascript resources returning the wrong content.

**Expected behavior**
Expected javascript files to return the correct content

**Screenshots**
<img width="1438" alt="Screenshot 2023-07-17 at 6 34 01 PM" src="https://github.com/morpheus65535/bazarr/assets/24367477/193b44be-11ae-432a-815e-5439ca000546">

**Software (please complete the following information):**
 - Bazarr: 1.2.3
 - Docker Image: linuxserver/bazarr:1.2.3
 - Radarr version N/A
 - Sonarr version N/A
 - OS: Ubuntu 22.04.2

**Additional context**

Might be related to old issue:
https://github.com/morpheus65535/bazarr/issues/1822

**Comment by morpheus65535** [comment]
I haven't speicifcally tested with LSIO docker image but this is working as expected with hotio's:

![image](https://github.com/morpheus65535/bazarr/assets/5130500/25dd11fe-3acd-4b7e-80bd-c55b13aa6d9f)

Maybe something related to your reverse proxy?

**Comment by yoonsio** [comment]
Resolved. Issues with reverse proxy.
