### ISSUE TITLE
Movies: "No items found"

### ISSUE THREAD

**Issue by orangebutblue** [morpheus65535/bazarr#2203]
I've set up Bazarr and it works fine with Sonarr, but it doesn't show anything from Radarr. The movies section is just empty and says "No items found"

The connection works fine. I was even able to map the paths.

It even says "LIVE" next to the movie entry in the navigation pane. But it just doesn't show anything. I've even manually run the "Update Movie list from Radarr" task.... nothing

the logs also don't indicate anything

```
BAZARR SignalR client for Radarr is connected and waiting for events.   15/07/2023 10:28:28 
BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...    15/07/2023 10:28:27 
BAZARR SignalR client for Radarr is connected and waiting for events.   15/07/2023 10:28:27 
BAZARR trying to connect to Radarr SignalR feed...  15/07/2023 10:28:27
```

I'm using Docker with the v1.2.3-ls202 by linuxserver.io image
Tried restarting/recreating the container, but nothing has worked. I've had it running for a few days now but there are still no movies in there

**Comment by morpheus65535** [comment]
You probably doesn't have movie file downloaded yet. Bazarr will only import movies (or episodes) that are available on disk and marked as Downloaded" in Radarr. You can obtain live support on Discord. This is for issues (ie bugs) with Bazarr, not configuration or understanding questions.

**Comment by orangebutblue** [comment]
I'm sorry. you were correct.
