### ISSUE TITLE
OpenSubtitles.com AuthenticationError 

### ISSUE THREAD

**Issue by YTolun** [morpheus65535/bazarr#2207]
**Describe the bug**
I have setup my first Bazarr container yesterday, added some providers -including OpenSubtitles. It was working fine for a couple of hours but then it stopped working even though I didn't hit my download limit on OS.  I have waited until my download coutner is reset but still it didn't work. I also tried another account to no avail.

When I search auto, it says tasks are completed but nothing happens, the sub is still missing. When I search manually, it finds the sub but for some reason wont download it. When I press download, nothing happens. 

On the debug logs I keep seeing `Provider 'opensubtitlescom' is discarded` for auto searches and after a manual search and download `Response Body: {"message":"invalid token","...` and `AuthenticationError: Login failed`

**Software (please complete the following information):**
 - Bazarr: 1.2.4

**Comment by YTolun** [comment]
For anyone who's having the same issue, restarting the container **didn't** work. HOWEVER, using the restart option from the top right (cogwheel) menu **WORKED**.

**Comment by morpheus65535** [comment]
The issue is related to token caching on their side. It's been fixed (from what they told me) 1 hour ago. The restart trick is purely coincidentally.
