### ISSUE TITLE
Pathing issues

### ISSUE THREAD

**Issue by phatassdk** [morpheus65535/bazarr#221]
Hi there,

Just found out about this project and I am super hyped! Have been waiting for something like this since sonarr was released!

Anyway - I seem to have some wierd mapping issue that I cannot seem to solve on my own.
Hope you guys can figure out what is wrong. :)

Notes: 
- I am only using Sonarr for now.
- I'm running Bazarr on a Synology NAS
- I'm running Sonarr on the same Synology NAS

Sonarr paths:
/volume1/Data/TV Shows/
![image](https://user-images.githubusercontent.com/37617980/48304794-07f4d480-e520-11e8-9a38-bb062bc94dc2.png)

Docker mapping:
![image](https://user-images.githubusercontent.com/37617980/48304800-2d81de00-e520-11e8-9b23-490ed4d9008e.png)

Bazarr paths:
![image](https://user-images.githubusercontent.com/37617980/48304811-53a77e00-e520-11e8-9b9b-97af2476fe79.png)

Issue:
![image](https://user-images.githubusercontent.com/37617980/48304818-8f424800-e520-11e8-89c8-49bd22d07972.png)

Anyone who can help? :)

**Comment by morpheus65535** [comment]
Permission issue?

**Comment by phatassdk** [comment]
Hi Morph,

It was a stupid error.
Was missing a "/" after the Bazarr path. :)

Thanks again. :)

/phatty

**Comment by bobbintb** [comment]
I've helped other users that have had the same issue. I suggest adding a check because there are plenty of users that never add a trailing slash and during setup it causes the whole thing to hang.
