### ISSUE TITLE
Multi-episode episodes subtitle ordering shifted

### ISSUE THREAD

**Issue by Accelerox** [morpheus65535/bazarr#2215]
**Describe the bug**
When bazarr downloads subtitles for shows that have multi-episodes the subtitles get shifted onto wrong episodes.
A good example is the classic show "The Office (US)".

I believe this is issue is due to sonarr/ bazarr/ opensubtitles running different meta data source (the movie db or the tv db) since the sources report different amounts of episodes in the same season.

**To Reproduce**
1. Add opensubtitles as provider
2. Download a series that have multi-episodes from sonarr (The Office Season 4 example).
3. From bazarr, download subtitles for this season.
4. Watch how subtitles are shifted on episodes.

**Expected behavior**
Bazarr downloading the correct subtitles and apply them to the right episodes.

**Screenshots**
<img width="295" alt="image" src="https://github.com/morpheus65535/bazarr/assets/67866341/b817edc0-1566-43c7-9b75-87c9f77d4d58">
<img width="1370" alt="image" src="https://github.com/morpheus65535/bazarr/assets/67866341/4f29139e-5b6e-4da6-a1a8-40b18d9f70d2">
PS: Not only are some subs missing but all after the first multi episode subtitles are shifted wrong.

https://www.opensubtitles.com/en/tvshows/2005-the-office

**Software (please complete the following information):**
 - Bazarr: 1.2.4
 - Radarr version -
 - Sonarr version 3.0.10.1567
 - OS: Ubuntu 20.04 LTS

**Additional context**
Since I believe this issues comes from the fact that the different databases report different amount of episodes I know that it may require some cooperation between arr teams to solve

TVDb reports 19 episodes https://thetvdb.com/series/the-office-us/seasons/official/4
MovieDB reports 18 episodes (used by open subtitles) https://www.opensubtitles.com/en/tvshows/2005-the-office

**Comment by morpheus65535** [comment]
Disclaimer: I don't want to be rude, just stating the facts. :-)

Opensubtitles.com use an unknown source for episodes numbering (1 to 18 but they skipped some numbers: 19 is probably a multi-episode second part). They are missing subtitles for the episodes you don't have subtitles.

themoviedb list 14 episodes (1 to 14)

Bazarr use the episode numbers provided by Sonarr (1 to 19) and query os.com API with this number. If os.com return the wrong subtitles, it's more of an os.com issue.

I don't think Sonarr want to change episode numbering source.

I won't implement some kind of episode numbers translation using different sources.

Is there anything that I've missed here?

**Comment by Accelerox** [comment]
You aren't. I'm just pointing out a non wanted behaviour from the arr system working in this configuration. I posted here and not on sonarr since it felt most subtitles related, maybe that was wrong now that I understand more.

Regarding the supposed missing subtitles:
- "Survivor man" has subtitles on opensubtitles.com 
- "The chair model" also
- "Did I stutter" also
- "Job fair" has indeed missing subtitles (I cant even see the episode on opensubtitles.com)

However, the three above missing has different reported episode numbering, which I presume would make os API return wrong subs.

<img width="879" alt="image" src="https://github.com/morpheus65535/bazarr/assets/67866341/b657382e-e3cc-4a28-8c49-e8af2690fde5">

<img width="658" alt="image" src="https://github.com/morpheus65535/bazarr/assets/67866341/370ec192-ec15-4227-bb24-deafcbc9dbca">

On the movieDB episodes, I thought since opensubs has "themovieDB" in the top for the description it would also use it for numbering, this was not the case. 

I fully understand if you won't implement any episode number translation, presumably quite inefficient way of dealing with the issue... Looks to me like a configuration mismatch between services since the chosen databases doesn't always work well togehter. But I thought I at least would make the issue known :-)

**Comment by morpheus65535** [comment]
Can you provide a debug log for the episode that should return a subtitles? Make sure tor redact your password to opensubtitles.com from the log (I've just patched Bazarr to not include it in the future).

**Comment by morpheus65535** [comment]
Their API doesn't return any result for this episode and those languages:
`curl --location 'https://api.opensubtitles.com/api/v1/subtitles?ai_translated=exclude&episode_number=11&imdb_id=386676&languages=en%2Csv&moviehash=abb292517c4f8df9&season_number=4' --header 'Api-Key: s38zmzVlW7IlYruWi7mHwDYl2SfMQoC1'`

**Comment by morpheus65535** [comment]
Yes I agree. I've asked the question to os.com admin and dev. I'll report back when they gave me news.

**Comment by morpheus65535** [comment]
Short answer from them: they are aware that episode numbering/ordering is tricky but nothing can be done on their side. Hopefully, it happens only for some specific series. I'll that issue for now.

**Comment by Accelerox** [comment]
What a strange answer since it's their sites and databses, what a bummer. Anyways, thanks for your work on bazarr.
