### ISSUE TITLE
no auto download 

### ISSUE THREAD

**Issue by sahara101** [morpheus65535/bazarr#2217]
Hello, my bazarr does not auto download episodes, nor clicking search. But if I go the episode and click on manual search, it finds the subtitle and from there I can download it. I know for sure that it downloaded after I installed the docker, but now it seems to not do anything. 

Release: v1.2.5-beta.8

Log uploaded.

[bazarr.log](https://github.com/morpheus65535/bazarr/files/12264400/bazarr.log)

Thank you!

**Comment by morpheus65535** [comment]
This is the normal behaviour because adaptive searching is enabled:

```
04/08/2023 22:29:38|DEBUG   |root                            |Adaptive searching is enable, we'll see if it's time to search again...|
04/08/2023 22:29:38|DEBUG   |root                            |Adaptive searching: attempts matching language ro: [['ro', 1690439523.882245], ['ro', 1691166403.510811]]|
04/08/2023 22:29:38|DEBUG   |root                            |Adaptive searching: initial search date for ro is 2023-07-27 09:32:03.882245|
04/08/2023 22:29:38|DEBUG   |root                            |Adaptive searching: latest search date for ro is 2023-08-04 19:26:43.510811|
04/08/2023 22:29:38|DEBUG   |root                            |Adaptive searching: delay after initial search value: 7 days, 0:00:00|
04/08/2023 22:29:38|DEBUG   |root                            |Adaptive searching: delta between latest search and now value: 3 days, 0:00:00|
04/08/2023 22:29:38|DEBUG   |root                            |Adaptive searching: it's been more than 1w since initial search, let's check if it's time to search again.|
04/08/2023 22:29:38|DEBUG   |root                            |Adaptive searching: it's been less than 3d since latest search, we're not ready to search yet.|
04/08/2023 22:29:38|DEBUG   |root                            |BAZARR Search is throttled by adaptive search for this episode /data/media/tv/Doctor Who/Season 18/Doctor-Who-(1963)_s18e1.avi and language: ro|
```

**Comment by BradMJustice** [comment]
Hello, I'm experiencing the same issue, but I do not have adaptive search enabled. I'm not sure how to provide a detailed log, the only logs I can find are very short:

06/08/2023 22:33:23|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
06/08/2023 22:33:23|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
06/08/2023 22:33:23|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
06/08/2023 22:33:23|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
06/08/2023 22:33:24|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
06/08/2023 22:52:10|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|

**Comment by morpheus65535** [comment]
@BradMJustice this board is for software issues, not configuration questions. Please go to Discord support channel.

**Comment by sahara101** [comment]
I disabled adaptive searching and have the same issue. I added gestdown and all started working again. Addic7ed and opensubtitles.com do not want to download.

**Comment by morpheus65535** [comment]
There's no issues with those providers (if you use anti-captcha with addic7ed). If you have configuration issues, come to Discord.
