### ISSUE TITLE
Python 3.7 Depreciation check incorrectly triggering

### ISSUE THREAD

**Issue by D0cR3d** [morpheus65535/bazarr#2218]
**Describe the bug**
I believe the Python 3.7 [depreciation check added in beta 9](https://github.com/morpheus65535/bazarr/commit/d284e629b7163bab1a4f9fb8f698fe82006c88db) is incorrectly triggering. Though this could be related to an edge case with my environment setup.

**To Reproduce**
1. Start bazarr with `/usr/bin/python3.9 bazarr.py`

Alternatively you can create a Pipfile and run `pipenv run python bazarr.py`

**Expected behavior**
Announcement of python 3.7 depreciation should not show

**Screenshots**
This screenshot is when I added sys.version_info into the announcement message
<img width="1486" alt="image" src="https://github.com/morpheus65535/bazarr/assets/13460915/d2427105-ac51-4fa3-a75a-8eda06eab2ad">

This screenshot is when I created a pipfile targeting python 3.9 then ran with `python3.9 -m pipenv run python bazarr.py`
<img width="267" alt="image" src="https://github.com/morpheus65535/bazarr/assets/13460915/8885c46e-88e8-4daf-bcd5-96975c52d043">

**Software (please complete the following information):**
 - Bazarr: v1.2.5-beta.9
 - Radarr version 4.7.3.7731
 - Sonarr version 3.0.10.1567
 - OS: Ubuntu 22.10

**Additional Info**
I can be reached in the Discord as D0cR3d if it's easier.

**Comment by halali** [comment]
What is output from command python3.9 --version

**Comment by D0cR3d** [comment]
Output is `Python 3.9.16`

**Comment by morpheus65535** [comment]
My bad. Stupid mistake on my side. I fixed it. Will be included in upcoming beta.
