### ISSUE TITLE
Pushover notification suddenly not working

### ISSUE THREAD

**Issue by marc0janssen** [morpheus65535/bazarr#2220]
**Describe the bug**
Logging reports:
A Connection error occurred sending Pushover:ALL_DEVICES notification.

I have read the wiki, it always worked before.

I am using, for ages. 
pover://{user_key}@{token}

I guess latest notifications came in early spring, after that I never received them again. 
Feel like a update broke the notifications.

**Software (please complete the following information):**
 - Bazarr: v1.2.4 (Docker linuxserver.io latest build)

**Comment by halali** [comment]
Provide debug log.

**Comment by marc0janssen** [comment]
[bazarr.log](https://github.com/morpheus65535/bazarr/files/12269815/bazarr.log)

**Comment by marc0janssen** [comment]
It looks like if I guild the requests through the proxy, they fail.

The proxy is operational... all other servers just connect fine through this proxy.

**Comment by morpheus65535** [comment]
Your proxy is refusing the connection. Nothing changed on Bazarr side about that. It's either you miss-configured it in Bazarr or something changed with your proxy.

**Comment by morpheus65535** [comment]
If you need help with your configuration, come by our support Discord channel. Closing for now.
