### ISSUE TITLE
Login with faulty credentials yields error 400

### ISSUE THREAD

**Issue by Accelerox** [morpheus65535/bazarr#2223]
Logging in to the web-ui with faulty credentials yields error 400 and no entry is created in the log (not in debug nor info) regarding the failed login attempt.

<img width="782" alt="image" src="https://github.com/morpheus65535/bazarr/assets/67866341/ded34f48-2ac3-4c68-85a7-fc151eaa365a">

**Reproduce**
1. Turn on Form Authentication
2. Log in with failed credentials
3. See error popup 400

**Expected behaviour**
A message regarding wrong auth and a print in the log info file regarding the failed login.

**Software**
 - Bazarr: 1.2.4
 - Radarr version 4.6.4.7568
 - Sonarr version 3.0.10.1567
 - OS: Ubuntu 20.04 LTS

**Comment by morpheus65535** [comment]
Already fixed in 1.2.5-beta. Thanks for reporting!

https://github.com/morpheus65535/bazarr/commit/486d2f9481982fef0ff0a30c314f74e9268cc7fd
