### ISSUE TITLE
subf2m is showing no results 

### ISSUE THREAD

**Issue by rokogan** [morpheus65535/bazarr#2227]
**Describe the bug**

subf2m is showing no results even tho the subtitles are available 

**Screenshots**
![brave_rRZjtI6UXc](https://github.com/morpheus65535/bazarr/assets/64978256/3b7e3549-5bb8-446c-84ec-d44e7de8c3d8)
![brave_znRuRgVDib](https://github.com/morpheus65535/bazarr/assets/64978256/7c5961e8-5ca8-4abf-ba88-1f3fd553f8d9)

**Software (please complete the following information):**
 - Bazarr: [v1.2.5-beta.12]
 - Radarr version [4.6.4.7568]
 - Sonarr version [3.0.10.1567]
 - OS: [e.g. Windows 10]

[bazarr.log](https://github.com/morpheus65535/bazarr/files/12329655/bazarr.log)

**Comment by morpheus65535** [comment]
Subf2m did implement some javascript solving to protect their site from bot and, unfortunately, us. This provider is not working until we find a way (if possible) to circumvent that. I'll be happy to accept some help if you're willing to take a look at this.

**Comment by Daocuong-main** [comment]
> Subf2m did implement some javascript solving to protect their site from bot and, unfortunately, us. This provider is not working until we find a way (if possible) to circumvent that. I'll be happy to accept some help if you're willing to take a look at this.

Has this issue been resolved?
