### ISSUE TITLE
Provider opensubtitles.com returns "invalid token"

### ISSUE THREAD

**Issue by Jacketbg** [morpheus65535/bazarr#2231]
This has been happening intermittently in the past months, usually after several downloads, but since today it's impossible to download a single subtitle. I have a VIP account:

<img height="240" alt="Screenshot 2023-08-18 at 13 20 45" src="https://github.com/morpheus65535/bazarr/assets/4333497/7a551087-4a42-42a5-9e9b-af4fb82c67f9">

<img height="240" alt="Screenshot 2023-08-18 at 13 20 26" src="https://github.com/morpheus65535/bazarr/assets/4333497/1deaf641-3463-4ed1-98a4-ceb627c8b2f2">

Bazarr is version 1.2.4, running on Debian 12 with venv Python 3.11

<img width="400" alt="Screenshot 2023-08-18 at 13 12 06" src="https://github.com/morpheus65535/bazarr/assets/4333497/46fd3009-5069-4a18-bdc0-3fa5e1695b9e">

Attached is the debug log when trying to manually search for a single episode.

[bazarr.log](https://github.com/morpheus65535/bazarr/files/12378251/bazarr.log)

I have tried stopping bazarr, deleting the data/cache directory and starting it again without any luck.

**Comment by morpheus65535** [comment]
Open an issue with them and provide this log. The issue is on their side and they seems to be unable to stabilize their service. There's nothing more that can be done on Bazarr side.

**Comment by opensubtitlesdev** [comment]
the log only shows the last failed request.... is there a way to have all the requests  to the API during a session added to the logs ? if we could see the requests and responses we could easily track the problem.

**Comment by opensubtitlesdev** [comment]
> Open an issue with them and provide this log. The issue is on their side and they seems to be unable to stabilize their service. There's nothing more that can be done on Bazarr side.

figuring out a way to have a log of the requests and response to our API would be a great help for us.

**Comment by opensubtitlesdev** [comment]
in the log file I can see: 

`
18/08/2023 13:07:52|DEBUG   |root                            |Request URL: https://api.opensubtitles.com/api/v1/download|
18/08/2023 13:07:52|DEBUG   |root                            |Request Headers: {'User-Agent': 'Bazarr/1.2.4', 'Api-Key': 's38zmzVlW7IlYruWi7mHwDYl2SfMQoC1', 'Content-Type': 'application/json', 'Accept': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJicW1PSFdsQk42emp1cHFLOWlsRGhKWW0xbEJiTXB1dSIsImV4cCI6MTY5MjQwODExNX0.zBqHZU7bHHx9KWjl2WrzuRRfQZ960wCfNdfVxbDzbyM', 'Content-Length': '41'}|
18/08/2023 13:07:52|DEBUG   |root                            |Request Body: b'{"file_id": 3740246, "sub_format": "srt"}'|
18/08/2023 13:07:52|DEBUG   |root                            |Response Status Code: 401|
`

request to download - > 401, token expired

then 

`
18/08/2023 13:07:52|DEBUG   |root                            |Authentication failed: clearing cache and attempting to login.|
18/08/2023 13:07:53|INFO    |engineio.server                 |6an_cNoTOdqS8sR1AAAC: Sending packet PING data None|
18/08/2023 13:07:53|INFO    |engineio.server                 |6an_cNoTOdqS8sR1AAAC: Received packet PONG data |
18/08/2023 13:07:54|DEBUG   |urllib3.connectionpool          |https://api.opensubtitles.com:443 "POST /api/v1/login HTTP/1.1" 200 316|
18/08/2023 13:07:54|DEBUG   |urllib3.connectionpool          |https://api.opensubtitles.com:443 "POST /api/v1/download HTTP/1.1" 401 80|

`


on the next request:
`
18/08/2023 13:07:54|DEBUG   |root                            |Request URL: https://api.opensubtitles.com/api/v1/download|
18/08/2023 13:07:54|DEBUG   |root                            |Request Headers: {'User-Agent': 'Bazarr/1.2.4', 'Api-Key': 's38zmzVlW7IlYruWi7mHwDYl2SfMQoC1', 'Content-Type': 'application/json', 'Accept': 'application/json', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJicW1PSFdsQk42emp1cHFLOWlsRGhKWW0xbEJiTXB1dSIsImV4cCI6MTY5MjQwODExNX0.zBqHZU7bHHx9KWjl2WrzuRRfQZ960wCfNdfVxbDzbyM', 'Content-Length': '41'}|

`

it's the same bearer token as on the previous request that failed who is sent:

`
'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJicW1PSFdsQk42emp1cHFLOWlsRGhKWW0xbEJiTXB1dSIsImV4cCI6MTY5MjQwODExNX0.zBqHZU7bHHx9KWjl2WrzuRRfQZ960wCfNdfVxbDzbyM'
`

check this one out....

**Comment by morpheus65535** [comment]
@opensubtitlesdev  and? We clear the cached token and you simply send us the same token again? If the token is expired, I would expect your API to send a new valid one when calling /login.

**Comment by opensubtitlesdev** [comment]
I can see the post to the login

18/08/2023 13:07:54|DEBUG |urllib3.connectionpool |[https://api.opensubtitles.com:443](https://api.opensubtitles.com/) "POST /api/v1/login HTTP/1.1" 200 316|

but not the response.... could you add it to the log, so we could see if the API is sending an expired token, or if it's the old one that's being kept ?

**Comment by morpheus65535** [comment]
I've added debug logging of successful login to upcoming beta.17.

**Comment by Jacketbg** [comment]
The issue is still present today.
Just upgraded to beta 17 and did the same test. Here's the log: [bazarr_2023082401.log](https://github.com/morpheus65535/bazarr/files/12429733/bazarr_2023082401.log)

I hope those tokens do not represent a security issue...
