### ISSUE TITLE
AuthenticationError on opensubtitles.com

### ISSUE THREAD

**Issue by Kaduo** [morpheus65535/bazarr#2232]
**Describe the bug**
Opensubtitles.com provider returns an AuthenticationError even though the credentials are correct. 

**To Reproduce**
1. Add opensubtitles.com as a provider.
2. Check the Providers tab in system to see the authentication error.

**Expected behavior**
I expected to be able to download subtitles from opensubtitles.com.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: v.1.2.4
 - Radarr: whatbox-372d15e
 - Sonarr: whatbox-2639c06
 - OS: Gentoo Linux

**Comment by morpheus65535** [comment]
Did you even tried to search if this was a known issue? The issue is on the provider side, not Bazarr. It's been ask and answered multiple times within the last two weeks.

**Comment by AeonLucid** [comment]
> Did you even tried to search if this was a known issue? The issue is on the provider side, not Bazarr. It's been ask and answered multiple times within the last two weeks.

Maybe it's an idea to keep a single issue open regarding the opensubtitles.com instability? Even though it's not an issue on the bazarr side, it would be nice to track the issue. I keep having issues with opensubtitles.com as well and as an user I keep checking the issues here but only find closed ones. Giving me the assumption that it is "fixed" on their side or that I have an entirely different issue althogether.

**Comment by morpheus65535** [comment]
> Maybe it's an idea to keep a single issue open regarding the opensubtitles.com instability?

You are right. I'll keep this one open waiting for them to completely fix the issue. Right now, the best thing you can do is open a ticket on their forum.

**Comment by Cookie-Monster-Coder** [comment]
I don't know if this is the same issue, but I get "ProviderError" in status.
Logs
```
Throttling opensubtitlescom for 10 minutes, until 23/09/18 04:00, because of: ProviderError. Exception info: "'Bad status code: 400' ~ opensubtitlescom.py@520"
```
I have vip and downloads are 0/1000

**Comment by morpheus65535** [comment]
> I don't know if this is the same issue, but I get "ProviderError" in status.

It's unrelated but we were waiting for someone to provide a debug log for that issue. Opensubtitles.com admins are trying to fix stuff on their side but they must have debug log.

**Comment by Cookie-Monster-Coder** [comment]
> > I don't know if this is the same issue, but I get "ProviderError" in status.
> 
> It's unrelated but we were waiting for someone to provide a debug log for that issue. Opensubtitles.com admins are trying to fix stuff on their side but they must have debug log.

I was using email in the username spot. When I enabled debugging I saw this
```
Response Body: {"message": "Error, invalid username/password   - remember to use your username and not your email to authenticate", "status": 400}|
```
I think that notice should be mentioned when filling out the providers info.

**Comment by morpheus65535** [comment]
> I think that notice should be mentioned when filling out the providers info.

First, thanks for reporting the debug message for this error. I've added a specific exception catching for this error in upcoming beta.

Regarding that it should be mentioned in the provider modal, I would say that's already the case. Is the field named email or username?

**Comment by morpheus65535** [comment]
Nothing left to fix here.
