### ISSUE TITLE
No error message when there's an error while searching for subtitles

### ISSUE THREAD

**Issue by kuba-orlik** [morpheus65535/bazarr#2235]
**Describe the bug**

When subtitle search doesn't succeed due to wrong mapping setup, no error message is displayed - instead it's made to look like everything went ok, but there are no search results.

**To Reproduce**

1. Setup radarr integration
2. Go to `/settings/radarr` and set up wrong path mappings at the bottom
3. Go to a movie view
4. Try searching for subtitles to a movie
5. A message appears saying that all tasks have been completed

**Expected behavior**

There's an error message explaining that searching for subtitles failed

**Screenshots**
![image](https://github.com/morpheus65535/bazarr/assets/2697916/14176f5a-1a44-4f03-a356-2d5b0b3a3d40)

**Software (please complete the following information):**
 - Bazarr: 1.2.4
 - OS: Linux

**Comment by morpheus65535** [comment]
Working on that. Thanks for the feedback!

**Comment by morpheus65535** [comment]
Should be better in upcoming beta release. If you find something else, don't hesitate. Thanks for reporting!
