### ISSUE TITLE
Broken provider(?): sucha

### ISSUE THREAD

**Issue by GermanG** [morpheus65535/bazarr#2242]
Maybe this was already reported, but coudn't find anything searching in issues.

Sucha plugin tries to reach an non resolvable hostname.

**Log**
```
Exception info: MaxRetryError("HTTPConnectionPool(host='sapidb.caretas.club', port=80): Max retries exceeded with url: /episode?query=Foundation+S02E03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb56e700f50>: Failed to establish a new connection: [Errno -5] Name has no usable address'))")
```

I fail to resolve `sapidb.caretas.club`, even checked in external DNS tools like nslookup.io or mxtoolbox to verify it's not an ISP issue blocking it.

I'm using bazarr v1.2.5-beta.23 on docker, in a Linux system.

**Comment by morpheus65535** [comment]
Yeah I think this provider is just dead. I'll keep that issue opened for a couple of weeks and look back just in case they get back online. If not, I'll remove it from Bazarr. Thanks for reporting!

**Comment by morpheus65535** [comment]
Provider removed in upcoming beta. Thanks!
