### ISSUE TITLE
Bazarr endless looping on Synology - ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by HiiiiiHa** [morpheus65535/bazarr#2244]
**Describe the bug**
Since few weeks\month and after updating Bazarr docker image, Bazarr is endless looping trying to restart.
I'm using synology with latest DSM and latest Image(linuxserver/Bazarr).

**To Reproduce**
Download latest Bazarr image
Launch container

**Screenshots**
![image](https://github.com/morpheus65535/bazarr/assets/81105552/d528d008-7757-46f9-9e82-59711a3778c3)

Traces:
Bazarr exited.
Bazarr starting...
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 20, in <module>
    from app.check_update import apply_update, check_releases, check_if_new_update  # noqa E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/app/check_update.py", line 14, in <module>
    from .config import settings
  File "/app/bazarr/bin/bazarr/app/config.py", line 8, in <module>
    from subliminal.cache import region
  File "/app/bazarr/bin/bazarr/../libs/subliminal/__init__.py", line 12, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/app/bazarr/bin/bazarr/../libs/subliminal/core.py", line 29, in <module>
    from babelfish import Language, LanguageReverseError
  File "/app/bazarr/bin/bazarr/../libs/babelfish/__init__.py", line 14, in <module>
    from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
  File "/app/bazarr/bin/bazarr/../libs/babelfish/converters/__init__.py", line 5, in <module>
    from pkg_resources import iter_entry_points, EntryPoint
ModuleNotFoundError: No module named 'pkg_resources'
Bazarr exited.
Bazarr starting...

**Software (please complete the following information):**
 - Bazarr: 
 - OS: DSM 7.2-64570 Update 1

Thanks

**Comment by morpheus65535** [comment]
Known issue when you use DSM to update container. Delete the container and recreate it by reusing your existing configs.

**Comment by HiiiiiHa** [comment]
Thanks, then do we have to perform this operation at each and every update? updating through portainer would work?

**Comment by morpheus65535** [comment]
> Thanks, then do we have to perform this operation at each and every update? updating through portainer would work?

This is unrelated to Bazarr but more to how docker images are built and deployed. DSM, Portainer, Watchtower, Ouroboros and any other tools can cause this kind of issue. Docker-compose is the way to go. LSIO have an aricle on that topic: https://docs.linuxserver.io/general/updating-our-containers

**Comment by matiasba** [comment]
What causes the actual problem? Just had the same thing happing to me using the Truenas Chart provided from TrueCharts. Having to reinstall the whole app its kind of a pain because there is no button to upload a backup and mounting its volume its not that simple.

**Comment by HiiiiiHa** [comment]
It worked for me to delete everything and recreate from scratch. But that limitation is impacting for Synology users. Most of them update images through "Container Manager", Portainer or even Watchtower I assume. I have 12 containers running and never faced such issue, even Radarr was updating properly until now.

**Comment by morpheus65535** [comment]
I hope you understand it's not a Bazarr issue, right? It is related to the docker image definition that changed (probably the PATH environment variable). If you're unhappy about this, you should raise your concern with LSIO or Hotio depending which one you're using. Honestly, you're gonna get the docker-compose upgrade method answer.

**Comment by morpheus65535** [comment]
> Might not be a bazarr issue but if all auto-updating images on multiple platforms are failing, including a workaround if possible might be a good thing.

It's an operating system issue, nothing that can be fixed inside Bazarr.

**Comment by HiiiiiHa** [comment]
What is the issue exactly? Why only Bazarr is facing issue? No pb for other container like Sonarr, bitwarden, adguard, komga ,...

**Comment by morpheus65535** [comment]
Unless I'm wrong, this issue occured when LSIO rebased their images from Alpine 3.17 to 3.18 on August 11th. If you deploy v1.2.4-ls207 and upgrade to v1.2.4-ls208 with DSM or Portainer, you will probably get the same issue again.

I'm using ouroboros myself and I've had similar issue with other images within the last year. I'm aware I should do it this way and I accept the consequence. This is unsupported by the images provider, they state it pretty clearly... what should I expect?

**Comment by matiasba** [comment]
I don't quite understand why changing the underling image OS would break the app. I sound like maybe some of the OS is persisting where it shouldn't.

**Comment by morpheus65535** [comment]
> I don't quite understand why changing the underling image OS would break the app. I sound like maybe some of the OS is persisting where it shouldn't.

Take a look at all the settings from your container, you didn't create them all by yourself and the image bring some with it when you create the container. Over time, the image may not need the same values to those settings and it may break the normal behaviour that have been tested by the image creator.

Like I said earlier, I suspect that the issue here is with the PATH environment variable defined by the previous image. When your simply recreate the container with the previous PATH env value, it wont inherit from the new expected value. Having a docker-compose with only the user defined environment variables insure that upon recreation, only those user defined variables are bring to the new container which inherit the new image defined environment variables.

I don't know how to explain it another way but this is the way it works.

**Comment by aeternias** [comment]
I don't use DSM, I use Portainer on Ubuntu and I also get this error. I deleted the entire stack, redeployed it and then it just doesn't work anymore. No errors, just halts. Everything worked perfect for 2 years until the latest update.

**Comment by morpheus65535** [comment]
@aeternias Portainer upgrade process is the same as DSM. They all work the same way and they all aren't supported.

"just halts" is a thing, there's always something in docker log or Bazarr log. If the error in log isn't exactly the same, open your own issue. If it's the same, the fix is documented up here.
