### ISSUE TITLE
subdivx.com provider not working, subtitles exist on their page but nothing is found on bazarr

### ISSUE THREAD

**Issue by bejaranoo** [morpheus65535/bazarr#2245]
my version:
v1.3.0-ls214 by linuxserver.io

**Screenshots**
![image](https://github.com/morpheus65535/bazarr/assets/67523369/3257558c-0df4-4c4f-bf0f-4af674868655)
![image](https://github.com/morpheus65535/bazarr/assets/67523369/b66cbd04-b8ef-4179-ab95-b73fc01a8e97)

I'm willing to put the time to help on solving this, since this is the main provider for latin america spanish subtitles, just need some guidance on where to look

**Comment by morpheus65535** [comment]
To my knowledge, there's been more than 98k subtitles downloaded from this provider in the last 7 days so it's probably some isolated case. I normally don't investigate those but, if you provide a debug log, I can take a look at it.

**Comment by bejaranoo** [comment]
Thanks!, here is the log:
[_bazarr_logs(1).txt](https://github.com/morpheus65535/bazarr/files/12651450/_bazarr_logs.1.txt)

I've been looking into it and it seems that is using the correct GET to see the available subs but it is still yielding 0 subtitles?
![image](https://github.com/morpheus65535/bazarr/assets/67523369/cfffa98c-0a0c-4013-be1a-cc8e9094750d)

**Comment by morpheus65535** [comment]
The only thing I see right now is that the year doesn't match. It shouldn't exclude the subtitles but only affect it's score. You don't see anything in interactive search?

**Comment by bejaranoo** [comment]
this is the interactive search?
![image](https://github.com/morpheus65535/bazarr/assets/67523369/365e4b08-e38b-4cba-b0e5-752df5006169)

**Comment by morpheus65535** [comment]
How sorry, I'm doing a lot of stuff at the same time. From your debug log, I can't why they got excluded from results. I would have to download the show and run the debugger on it. TBH, I don't have time to do that right now and it's still an isolated event.

**Comment by bejaranoo** [comment]
I understand, no worries. I'll try to find something and post any results

**Comment by vitiko98** [comment]
This will be fixed in upcoming beta version. Thanks for the report!
