### ISSUE TITLE
NZB360 integration failed after v1.2.5

### ISSUE THREAD

**Issue by TopperBG** [morpheus65535/bazarr#2248]
**Describe the bug**
Before v1.3.0 with NZB360 app (https://play.google.com/store/apps/details?id=com.kevinforeman.nzb360) we could check downloaded subtitles and/or start manual search.
Latest working version is v1.2.4

**To Reproduce**
1. Open NZB360 (already configured)
2. Click on some Movie
3. Open addition info. 
4. After v1.2.4 that error appear and missing any info for existing subtitles
![image](https://github.com/morpheus65535/bazarr/assets/23097319/2a9db729-b1b3-4b9a-b18e-9776a97fb741)

Working: displayed downloaded subtitles
![image](https://github.com/morpheus65535/bazarr/assets/23097319/2073ba76-3671-4b8c-a351-aceeab734d27)
or start search manualy missing.
Checked with docker image up to v1.2.4

**Software (please complete the following information):**
 - Bazarr: [v1.3.0 by [linuxserver.io](https://linuxserver.io/)]
 - Radarr version [4.7.5.7809-ls187 by [linuxserver.io](https://linuxserver.io/)]
 - Sonarr version [3.0.10.1567-ls206 by [linuxserver.io](https://linuxserver.io/)]
 - OS: [Ubuntu 22.04 LTS with Docker version 24.0.5, build 24.0.5-0ubuntu1~20.04.1]

**Comment by morpheus65535** [comment]
Why not open an issue with this software provider? He would probably require to adapt those API call and if required he can talk with us.

**Comment by TopperBG** [comment]
> Why not open an issue with this software provider? He would probably require to adapt those API call and if required he can talk with us.

Already done.
Is here any API changes anyway ?

**Comment by TopperBG** [comment]
Ok, will report that to the author of NZB360.
