### ISSUE TITLE
Deep analyze media file setting causing an exception on some files

### ISSUE THREAD

**Issue by damiensgit** [morpheus65535/bazarr#2250]
**Describe the bug**
I get ``Job "Sync with Sonarr (trigger: interval[1:00:00], next run at: 2023-09-20 10:09:04 UTC)" raised an exception `` errors in the log when syncing with Sonarr and  "Deep analyze media file to get audio tracks language." is enabled.

```python
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/sonarr/sync/series.py", line 100, in update_series
    sync_episodes(series_id=show[\'id\'], send_event=send_event)
  File "/app/bazarr/bin/bazarr/sonarr/sync/episodes.py", line 76, in sync_episodes
    episodes_to_add.append(episodeParser(episode))
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/sonarr/sync/parser.py", line 102, in episodeParser
    audio_language = embedded_audio_reader(path_mappings.path_replace(episode[\'episodeFile\']
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/utilities/video_analyzer.py", line 96, in embedded_audio_reader
    alpha3 = _handle_alpha3(detected_language)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/utilities/video_analyzer.py", line 16, in _handle_alpha3
    alpha3 = detected_language["language"].alpha3
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: \'str\' object has no attribute \'alpha3\
``` 

**To Reproduce**
Steps to reproduce the behaviour:
1. Unknown at this time, the error is occurring on one or more files in my media during a deep analysis

**Expected behaviour**
This use case is handled correctly and doesn't raise an exception

**Screenshots**
Setting causing issue:
![image](https://github.com/morpheus65535/bazarr/assets/50471/c9405564-3ae3-4fce-8ee1-d3c25db1e9e6)

**Software (please complete the following information):**

- Bazarr Version: 1.3.0
- Package Version: v1.3.0-ls214 by linuxserver.io
- Sonarr Version: 4.0.0.669
- Radarr Version: 5.0.2.8099
- Operating System: Linux-4.4.302+-x86_64-with
- Python Version: 3.11.5

**Additional context**
n/a

**Comment by morpheus65535** [comment]
This commit should help in upcoming beta debug this issue. Awaiting your feedback.

**Comment by morpheus65535** [comment]
No news, good news!
