### ISSUE TITLE
Keeps downloading subs, maybe "upgrade" scoring failure?

### ISSUE THREAD

**Issue by rmichelena** [morpheus65535/bazarr#2254]
**Describe the bug**
Subs are downloaded, and same subs are re-downloaded over and over.
It's not that it does not "see" the existing ones. They're shown in the UI as existing.
I also tried manually downloading another subs (different from the ones exhibiting this behavior); they also got "upgraded" by this subs which have the same score.

**To Reproduce**
Add "Ahsoka.S01E05.1080p.WEBRip.x265-KONTRAST" to your library.
Configure as "ES" (Spanish)
It will download a Spanish sub from OS with score 94.44 %
and will keep downloading it again and again
Download manually a Spanish sub from Argenteam, which has same score
later it will "upgrade" to the OS sub with same score, and keep downloading it again and again

**Screenshots**
Attached

**Software (please complete the following information):**
 - Bazarr: 1.3.0
 - Sonarr version 3.0.10.1567
 - OS: Ubuntu 18.04 

<img width="1200" alt="Screenshot 2023-09-25 at 12 10 51" src="https://github.com/morpheus65535/bazarr/assets/77797875/8c5eeee6-9c1c-4f0b-9c7a-06da64640463">
<img width="827" alt="Screenshot 2023-09-26 at 9 00 21" src="https://github.com/morpheus65535/bazarr/assets/77797875/64a672ab-86a2-4019-84c9-3505d9d76a63">

**Comment by morpheus65535** [comment]
Do you use `Language Equals` feature?

**Comment by rmichelena** [comment]
I'll have to get that file again... Sonarr just upgraded it (for one that has embedded subs)... history for that episode has been deleted from Bazarr (I didn't know that would happen, but makes sense)... will get that version again and try to do a debug when upgrading

**Comment by morpheus65535** [comment]
Still an issue here?

**Comment by morpheus65535** [comment]
1 month later: no news, good news!
