### ISSUE TITLE
Stuck trying to analyze files that does not exist anymore

### ISSUE THREAD

**Issue by rmichelena** [morpheus65535/bazarr#2255]
**Describe the bug**
I see in my log a few failure messages of the kind:
BAZARR Error ([Errno 2] No such file or directory:
and the video files it's trying to open, are files that do not exist anymore, some for a long time (days or weeks), since Sonarr or Radarr replaced them by better versions (or renamed them because of naming scheme changes).
In some cases it's even trying to process two generations back!
As per log copied below: this file Ahsoka S01E03, was first downloaded as KAG, then ELITE, and finally Goki (the current one).
And it's trying to analyze both KAG and ELITE (Goki had embedded subs)

**To Reproduce**
Probably the reason is a file was downloaded by Radarr or Sonarr, and very shortly replaced by another version (as can happen with Radarr and Sonarr); some interplay between Bazarr's syncing schedule and the times on which these occurred...
Also at least in one case, it's due to file renaming from Sonarr (added release group to name).

**Software (please complete the following information):**
 - Bazarr: 1.3.0
 - Radarr version 4.7.5.7809
 - Sonarr version 3.0.10.1567
 - OS: Ubuntu 18.04

``` Python
Traceback (most recent call last):
  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video
    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video
    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 834, in scan_video
    video.size = os.path.getsize(hash_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 50, in getsize
FileNotFoundError: [Errno 2] No such file or directory: \'/tv/Ahsoka/Season 1/Ahsoka - S01E03 - Part Three [WEBRip-1080p] -KAF.mkv\

Traceback (most recent call last):
  File "/app/bin/bazarr/subtitles/utils.py", line 41, in get_video
    video = parse_video(path, hints=hints, skip_hashing=skip_hashing, dry_run=used_scene_name, providers=providers,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/../libs/subzero/video.py", line 61, in parse_video
    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 834, in scan_video
    video.size = os.path.getsize(hash_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 50, in getsize
FileNotFoundError: [Errno 2] No such file or directory: \'/tv/Ahsoka/Season 1/Ahsoka - S01E03 - Part Three [HDTV-1080p] -ELiTE.mkv\
```

**Comment by morpheus65535** [comment]
Did you try to run the `Sync with Sonarr` task to fix this?

Can you provide a debug log if it doesn't fix it? Maybe there's some sort of conflict.

**Comment by rmichelena** [comment]
It does sync with Sonarr as per schedule, nothing shows in the logs but it does pick up new entries.
Anyway, enabled the debug log, manually triggered a sync, downloaded the log; attached.
I checked it and see no error message; also, the shows in question (Ahsoka, Foundation) both seem to sync fine.
It not only happens with shows, it also happens with movies; similar case, a movie was downloaded and just a few minutes later upgraded. Bazarr keeps trying to analyze the old (no longer existing) movie file.

[bazarr-2.log](https://github.com/morpheus65535/bazarr/files/12728977/bazarr-2.log)

**Comment by rmichelena** [comment]
we'll see; I did manually sync with both Sonarr and Radarr and will wait to see if this keeps happening
however, we're talking about files that were deleted some days ago or more - even if no live notification had been received, scheduled sync would've cleared them up already, wouldn't it?

**Comment by morpheus65535** [comment]
Yes it should. If it doesn't fix it, I'm gonna need the API output from Sonarr or Radarr API and your database to understand why it doesn't get updated.

**Comment by rmichelena** [comment]
well, keeps doing it ; here I attach my database. How do I get the API output from Sonarr o Radarr ?
[bazarr.db.zip](https://github.com/morpheus65535/bazarr/files/12740988/bazarr.db.zip)

**Comment by morpheus65535** [comment]
Can you provide an upgrade debug log?

**Comment by morpheus65535** [comment]
Sorry, doing too much stuff at the same time lol

**Comment by morpheus65535** [comment]
Still an issue here? You didn't provided the Sonarr API output.

**Comment by morpheus65535** [comment]
1 month later: no news, good news!
