### ISSUE TITLE
Automatic Subtitles Synchronization identifies multiple suitable formats

### ISSUE THREAD

**Issue by AzaZPPL** [morpheus65535/bazarr#2257]
**Describe the bug**
The Bazarr automatic subtitle synchronizer throws an error when attempting to load a subtitle file. The error message suggests that it cannot determine the subtitle file format because it identifies multiple suitable formats **({'tmp', 'srt'})**.

**To Reproduce**
1. Go to Settings->Subtitles in the menu
2. Enable "Automatic Subtitles Synchronization"
3. Search for a subtitle for either movies or series.
4. See error in logs.

**Expected behavior**
The software should sync the subtitle without throwing an error. 

**Screenshots**
Settings:
![Settings](https://github.com/morpheus65535/bazarr/assets/5494931/b66c01cb-2f73-4fc3-91a0-1fcd349e1d06)

Error:
![Errors](https://github.com/morpheus65535/bazarr/assets/5494931/c6e4b163-4e04-432c-9a38-45a9ab5fbb08)

**Software (please complete the following information):**
 - Bazarr: 1.3.0
 - Radarr version: 4.7.5.7809
 - Sonarr version: 4.0.0.682
 - OS: Unraid 6.11.5

**Additional context**
```
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/subzero/modification/main.py", line 51, in load
    self.f = pysubs2.SSAFile.from_string(content)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/pysubs2/ssafile.py", line 133, in from_string
    return cls.from_file(fp, format_, fps=fps, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/pysubs2/ssafile.py", line 160, in from_file
    format_ = autodetect_format(fragment)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/../libs/pysubs2/formats.py", line 80, in autodetect_format
    raise FormatAutodetectionError("Multiple suitable formats (%r)" % formats)
pysubs2.exceptions.FormatAutodetectionError: Multiple suitable formats ({\'tmp\', \'srt\'})
```

Log of bazarr with the errors
[bazarr.log](https://github.com/morpheus65535/bazarr/files/12736461/bazarr.log)

**Comment by morpheus65535** [comment]
Something is wrong with those specifics subtitles. Please provide them.

**Comment by morpheus65535** [comment]
Ok so the subtitles synchronization happens after the embeddedsubtitles provider completed the extraction process?

**Comment by AzaZPPL** [comment]
I'm not certain if it synchronizes after the sub extraction is completed. Is there a way to check that? Also, on another note, is it possible to retrigger a sync on the English embedded subtitles?

It only shows as the following, and I cannot choose to 'sync' it, like how I can with the NL and TR subtitles/
![afbeelding](https://github.com/morpheus65535/bazarr/assets/5494931/ad9970f4-b825-4ae2-9176-31c5a884a736)

**Comment by morpheus65535** [comment]
It's simply impossible to sync embedded su titles.

**Comment by AzaZPPL** [comment]
Ok, so the errors were not coming from the embedded subtitles. I managed to reproduce it.

I just asked bazarr to find me the 'NL' subtitles for Scrubs S04E04. While it's still searching for the subtitle it is already running the Subtitle Synchronizer. Which is weird because the file is not even found yet.

![afbeelding](https://github.com/morpheus65535/bazarr/assets/5494931/07f884c1-e2bb-4991-8a17-51e903bd08cf)

**Comment by AzaZPPL** [comment]
I just enabled debug logging to check what is going on. It seems that it can find the correct file and saves it. But somehow it still doesn't exist in the file system. After which the subtitle synchronizer kicks in, which it should. But since it doesn't exist, it just kicks the bucket.

![afbeelding](https://github.com/morpheus65535/bazarr/assets/5494931/98ed391c-93d6-4c31-ba7a-248a8d85f137)

**Comment by morpheus65535** [comment]
File won't exist because it's an invalid format. You're running one of the mods automatically and it fails to parse the downloaded subtitles.

**Comment by AzaZPPL** [comment]
Aha I see. I don't quite understand what mods are I'm guessing it's the post-processing part?

**Comment by AzaZPPL** [comment]
I've disabled all of the post-processing and it correctly works now, which is great but leaves me with a question.

Are we not supposed to use the post-processing at all when we are using the automatic subtitle syncing? The post-processing processes and the subtitle syncing happen at the same time. One of the mods is causing the file to be invalid because it's being processed. I would say the automatic subtitle synchronisation should wait for the post-processing and then afterward do the subtitle synchronisation.

What do you think?

**Comment by morpheus65535** [comment]
Those are the mods that I was referring to:

![image](https://github.com/morpheus65535/bazarr/assets/5130500/65be51ee-0928-4b33-9de2-a26b79c3fac6)

They are run on the content of the subtitles before it's save to disk and fails because the subtitles, as provided by the provider, is an invalid format when validated by pysubs2 Python module that we rely on.

If the subtitles would have gone through this validation and mods with success, it would have been saved on disk and subtitles synchronization would have started. In your case, it fails because Bazarr didn't save the file where it should because the original subtitles wasn't valid.

The way you see it happening is exactly how it is in a normal situation.

**Comment by AzaZPPL** [comment]
Aha, thanks for that explanation. It makes a lot more sense that way. With that I'll close this bug report.
