### ISSUE TITLE
Cannot run bazarr

### ISSUE THREAD

**Issue by shavedbroom** [morpheus65535/bazarr#2259]
i cannot get bazarr to start properly or open in browser, i get a 502

● bazarr.service - Bazarr for shavedbroom
     Loaded: loaded (/etc/systemd/system/bazarr.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2023-10-01 14:06:51 UTC; 2min 40s ago
   Main PID: 944639 (python3)
      Tasks: 121 (limit: 18955)
     Memory: 149.1M
        CPU: 2.916s
     CGroup: /system.slice/bazarr.service
             ├─944639 /opt/.venv/bazarr/bin/python3 /opt/bazarr/bazarr.py
             └─944640 /opt/.venv/bazarr/bin/python3 -u /opt/bazarr/bazarr/main.py

Oct 01 14:06:55 plexservarr bazarr.shavedbroom[944640]:     self._target(*self._args, **self._kwargs)
Oct 01 14:06:55 plexservarr bazarr.shavedbroom[944640]:   File "/opt/bazarr/bazarr/app/signalr_client.py", line 124, in start
Oct 01 14:06:55 plexservarr bazarr.shavedbroom[944640]:     self.connection.start()
Oct 01 14:06:55 plexservarr bazarr.shavedbroom[944640]:   File "/opt/bazarr/bazarr/../libs/signalrcore/hub/base_hub_connection.py", line 53, in start
Oct 01 14:06:55 plexservarr bazarr.shavedbroom[944640]:     return self.transport.start()
Oct 01 14:06:55 plexservarr bazarr.shavedbroom[944640]:   File "/opt/bazarr/bazarr/../libs/signalrcore/transport/websockets/websocket_transport.py", line 64, in start
Oct 01 14:06:55 plexservarr bazarr.shavedbroom[944640]:     self.negotiate()
Oct 01 14:06:55 plexservarr bazarr.shavedbroom[944640]:   File "/opt/bazarr/bazarr/../libs/signalrcore/transport/websockets/websocket_transport.py", line 101, in negotiate
Oct 01 14:06:55 plexservarr bazarr.shavedbroom[944640]:     raise HubError(response.status_code)\
Oct 01 14:06:55 plexservarr bazarr.shavedbroom[944640]: signalrcore.hub.errors.HubError: 400

**Comment by morpheus65535** [comment]
What version of Sonarr?

**Comment by shavedbroom** [comment]
Version 3.0.10.1567
im running swizzin FYI

**Comment by shavedbroom** [comment]
installed it manually and now its working fine
