### ISSUE TITLE
zimuku certificate verify failed

### ISSUE THREAD

**Issue by DarrenLuo** [morpheus65535/bazarr#2265]
**Describe the bug**
(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)'))), retrying in 5 seconds

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: v 1.3.0
 - OS: Debian

**Additional context**

**Comment by morpheus65535** [comment]
SSL/TLS certificate for this provider website is expired since August 16. Bazarr only report it and prevent an unsecure connection. The proper fix is them updating their certificate.
