### ISSUE TITLE
Custom Post-Processing

### ISSUE THREAD

**Issue by DavidHenryThoreau** [morpheus65535/bazarr#2267]
**Describe the bug**
I like Sonarr and Radarr connexion for post-processing tasks (like refreshing Jellyfin) 
Like this page : http://radarr.tld/settings/connect

**Software (please complete the following information):**
 - Bazarr: 1.3.1
 - Radarr version latest
 - Sonarr version latest
 - OS: Linux/Docker

**Additional context**
Can you add this page to Bazarr ?

**Comment by morpheus65535** [comment]
This is an issue tracker. It not suitable for feature request.

https://bazarr.featureupvote.com/
