### ISSUE TITLE
bazarr cannot start: ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by systemcrash** [morpheus65535/bazarr#2271]
**Describe the bug**

It's been like this for... at least two weeks. 

**To Reproduce**
1. `docker pull linuxserver/bazarr` (latest)
2. run container

**Expected behavior**
container starts. 

**Software (please complete the following information):**
https://docs.linuxserver.io/images/docker-bazarr
https://github.com/linuxserver/docker-bazarr/releases

**Additional context**
```log
Bazarr starting...
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/main.py", line 22, in <module>
    from app.check_update import apply_update, check_releases, check_if_new_update  # noqa E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/app/check_update.py", line 15, in <module>
    from .config import settings
  File "/app/bazarr/bin/bazarr/app/config.py", line 8, in <module>
    from subliminal.cache import region
  File "/app/bazarr/bin/bazarr/../libs/subliminal/__init__.py", line 12, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/app/bazarr/bin/bazarr/../libs/subliminal/core.py", line 29, in <module>
    from babelfish import Language, LanguageReverseError
  File "/app/bazarr/bin/bazarr/../libs/babelfish/__init__.py", line 14, in <module>
    from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
  File "/app/bazarr/bin/bazarr/../libs/babelfish/converters/__init__.py", line 5, in <module>
    from pkg_resources import iter_entry_points, EntryPoint
ModuleNotFoundError: No module named 'pkg_resources'
```

Last successful log message on previous shutdown:
```
03/10/2023 15:11:21|INFO    |root                            |BAZARR Running cache maintenance|
```

**Comment by morpheus65535** [comment]
Reported multiple times. Do not use Portainer, Watchtower, DSM or any other graphical tools to update containers. LSIO do warn you about that on their wiki.

**Comment by systemcrash** [comment]
None of the aforementioned graphical tools were used too update any container. 

ONLY image. via the docker command.

**Comment by morpheus65535** [comment]
How did you recreate the container?

**Comment by systemcrash** [comment]
I imported a skeleton JSON template. 

Nuked everything, caches, etc and started again. Problem seems fixed.

**Comment by morpheus65535** [comment]
You could have reused the config directory. The problem lies in the json you've used that probably includes "hidden" environments variables that have changed overtime.

**Comment by systemcrash** [comment]
Oh yeah, I kept my bazarr config around. That was handled ok. Just had the usual warning about table and column names. 

Thanks for your time. 🥇

**Comment by systemcrash** [comment]
BTW, config backs up to a zipfiel once in a while. Seems there's no compression there. The db is just stored? Fairly sure there are some space and CPU savings via zstandard to be had there also.

**Comment by morpheus65535** [comment]
> BTW, config backs up to a zipfile once in a while. Seems there's no compression there. The db is just stored? Fairly sure there are some space and CPU savings via zstandard to be had there also. 

I'll take a look at it.
