### ISSUE TITLE
Radarr version "unknown"

### ISSUE THREAD

**Issue by cavalli1021w** [morpheus65535/bazarr#2277]
**Describe the bug**
Status screen shows Radarr Version as "unknown".  Clicking on "Test" in Radarr section shows "Version: 5.0.3.8127"

**To Reproduce**
Go to status screen.  Refresh.  Reproduce.

**Expected behavior**
Status shows Radarr Version as "5.0.3.8127"

**Screenshots**

**Software (please complete the following information):**
Bazarr Version 1.3.2-beta.6
Sonarr Version 3.0.10.1567
Radarr Version 5.0.3.8127
Operating System Linux-6.1.21-v8+-aarch64-with-glibc2.31
Python Version 3.9.2

**Additional context**

**Comment by morpheus65535** [comment]
I can't reproduce the issue. Whatever I do, I always see the Radarr version in status. Did you try restarting both Radarr and Bazarr? I know it sounds strange but I don't see any other solution than that.

**Comment by morpheus65535** [comment]
Still something to fix here?

**Comment by morpheus65535** [comment]
No news, good news!
