### ISSUE TITLE
Multi-Episode File Gets Single-Episode Subtitle File

### ISSUE THREAD

**Issue by Progeny42** [morpheus65535/bazarr#2279]
**Describe the bug**
I have a handful of multi-episode files across my collection (`Stargate Atlantis - S01E01-E02` and `Battlestar Galactica - s04e19-e20` as two examples). As you can guess, both of these files were ripped by myself, as opposed obtained by other means, hence why the filename is sparse of any metadata. In both cases, the subtitle file downloaded is only for the first-part episode. See `screenshot 1`.

I tried using the Ogranise feature in Sonarr to automatically rename the file for Stargate Atlantis, resulting in `Stargate Atlantis (2004) - S01E01-E02 - Rising [HDTV-1080p][DTS 5.1][h264].mkv`. When this is the name, no change occurs.

Outside of this issue, I queried why Sonarr decided my own MKV was classified as HDTV-1080p, and it appears to be because Sonarr assumes that by default. I therefore renamed the format portion of the filename to `[Bluray-1080p Remux]`. When this is the filename, Bazarr correctly identifies the multi-episode subtitle file. It would appear that Bazarr is prioritising the file format over whether it is multi-episode or not. See `screenshot 2`.

**To Reproduce**
Perform a manual search on `Stargate Atlantis - S01E01-E02`, which is Episode 1 'Rising (1)'.
The highest scoring item, and therefore the one downloaded, is for the single part episode, whereas I have a multi-episode file.
See screenshot 1 for an example.

**Expected behavior**
The multi-episode file should be prioritised first before any formatting.

**Screenshots**
Screenshot 1 (`Stargate Atlantis - S01E01-E02`)
![image](https://github.com/morpheus65535/bazarr/assets/48336180/e8a8106c-0b1e-440f-b7d9-f6a60aea8211)
Screenshot 2 (`Stargate Atlantis (2004) - S01E01-E02 - Rising [Bluray-1080p Remux][DTS 5.1][h264].mkv`)
![image](https://github.com/morpheus65535/bazarr/assets/48336180/d6a69e56-abbd-4eb0-a849-5406504c8562)

**Software (please complete the following information):**
 - Bazarr: v1.3.1
 - Radarr version: N/A
 - Sonarr version v3.0.10.1567
 - OS: Linux-6.1.49-Unraid-x86_64-with (Running in Docker)

**Additional context**
Nothing more to add.

**Comment by morpheus65535** [comment]
The answer is quite simple: Bazarr will only search for the first episode number of multiple episodes file.

In fact, there's not even a way of searching for multi episodes on opensubtitles.com API. episode_number argument must be an integer.

**Comment by Progeny42** [comment]
Okay, I'll just have to sort them out as I come across them.

**Comment by morpheus65535** [comment]
That's the kind of stuff that kind be easily done with manual search but is hard to automate.
