### ISSUE TITLE
Docker on Synology, cant get past subliminal setting screen

### ISSUE THREAD

**Issue by internetR** [morpheus65535/bazarr#228]
I switched to the new docker container from linuxserver.io set-up everything, but I cant get past the subliminal settings screen. once I click te go to the Sonarr settings I get a black screen with a spinning disk. The log is not helpful

Linexserver.io discord support ended me this way

![schermafbeelding 2018-11-17 om 13 31 05](https://user-images.githubusercontent.com/40005654/48661100-0ae64c80-ea6d-11e8-959e-9debbb12a01a.png)

![schermafbeelding 2018-11-17 om 13 32 14](https://user-images.githubusercontent.com/40005654/48661114-47b24380-ea6d-11e8-824a-56a20e42a87f.png)

**Comment by morpheus65535** [comment]
Use something else than Safari. Bazarr is heavily tested with Chrome.

**Comment by internetR** [comment]
thank you, worked like a charm

**Comment by djismgaming** [comment]
Almost opened a new Bug report 😄 
Thanks. Worked nice. 👍 

Just out of curiosity though:

What makes this stage of the app (setup) be incompatible with Safari 12.0.1 and also with Firefox 63.0.3?

(remade linuxserver.io based container a couple of times just to be sure it wasn't the container's fault)

**Comment by morpheus65535** [comment]
@djismgaming Bazarr is tested with Chrome. It "should" run just fine with Firefox which is normally compliant to standards but we cannot guarantee it won't happen now and then that you find a UI bug. We are using a lot of Javascript & Jquery and we are relying on the Semantic UI framework. They are all highly dependant on strict respect to standards. Safari is clearly not in the same category regarding this topic... ;-)
