### ISSUE TITLE
Incorrect imdb_id Queried

### ISSUE THREAD

**Issue by Progeny42** [morpheus65535/bazarr#2280]
**Describe the bug**
When investigation an issue pertaining to `Stargate SG-1 (1997) - S01E22 - Within the Serpents Grasp (2)`, I enabled debug logging, and noted that the `series_imdb_id` was `tt0118480`, however, the query sent to the subtitle provider (opensubtitles.com) set the `imdb_id` to `118480`. See the attached log for an excerpt.

If I manually search for `118480` on opensubtitles.com, there are no results, but if I search for `tt0118480`, the correct results are found.

Due to a suggestion I raised (https://bazarr.featureupvote.com/suggestions/504324/consider-episode_title-when-scoring-subtitles), and an issue with how opensubtitles seems to number episodes for Stargate SG-1 compared to Sonarr and The TVDB, I don't think subtitles for this episode would download anyway.

**To Reproduce**
Perform a manual search of the episode `Stargate SG-1 (1997) - S01E22 - Within the Serpents Grasp 2 [SDTV][AC3 2.0][MPEG2].mkv`. No results are found.

**Expected behavior**
Subtitles should be found, as they do exist for this episode when browsing manually on opensubtitles (though due to the aformentioned suggestion, maybe one won't be found).

**Software (please complete the following information):**
 - Bazarr: v1.3.1
 - Radarr version: N/A
 - Sonarr version: v3.0.10.1567
 - OS: Linux-6.1.49-Unraid-x86_64-with (Running in Docker)

[Issue-2280.log](https://github.com/morpheus65535/bazarr/files/13170607/Issue-2280.log)

**Comment by morpheus65535** [comment]
The imdb ID sent to opensubtitles.com is properly formatted following theit API documentation:
`in GET values remove "tt" from IMDB ID & remove leading 0 in any "ID" parameters,`
https://opensubtitles.stoplight.io/docs/opensubtitles-api/6ef2e232095c7-best-practices

**Comment by Progeny42** [comment]
Ah of course, API vs UI differences. No problem.

**Comment by morpheus65535** [comment]
They need this to improve caching to the API and reduce the impact on back-end servers.
