### ISSUE TITLE
Outdated rarfile version

### ISSUE THREAD

**Issue by jvoisin** [morpheus65535/bazarr#2283]
**Describe the bug**
The current version (4.0) of rarfile bundled with bazarr doesn't support 7zip as a decompression backend, while the latest one ([4.1](https://github.com/markokr/rarfile/releases/tag/v4.1)) does.

It would be great to be able to use 7zip instead of unar/unrar, since the former is written in an horrible language to package, while the latter is non-free, making them unavailable in some distributions.

I'd be happy to send a pull-request one the dependency has been updated, to make bazarr able to use 7zip.
 
**To Reproduce**
1. Install bazarr on Alpine Linux
2. `python3 ./bazarr.py`
3. Be greeted with a stacktrace:

```console
(venv) /opt/Bazarr $ python3 ./bazarr.py 
Bazarr starting...
2023-10-28 20:45:41,935 - root                             (7f7ad951ab08) :  ERROR (init:228) - BAZARR requires a rar archive extraction utilities (unrar, unar) and it can't be found.
Traceback (most recent call last):
  File "/opt/Bazarr/bazarr/init.py", line 217, in init_binaries
    exe = get_binary("unar")
          ^^^^^^^^^^^^^^^^^^
  File "/opt/Bazarr/bazarr/utilities/binaries.py", line 73, in get_binary
    raise BinaryNotFound
utilities.binaries.BinaryNotFound

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/Bazarr/bazarr/init.py", line 226, in init_binaries
    rarfile.tool_setup(unrar=True, unar=False, bsdtar=False, force=True)
  File "/opt/Bazarr/bazarr/../libs/rarfile.py", line 3331, in tool_setup
    raise RarCannotExec("Cannot find working tool")
rarfile.RarCannotExec: Cannot find working tool

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/Bazarr/./bazarr/main.py", line 24, in <module>
    from init import *  # noqa E402
    ^^^^^^^^^^^^^^^^^^
  File "/opt/Bazarr/bazarr/init.py", line 239, in <module>
    init_binaries()
  File "/opt/Bazarr/bazarr/init.py", line 229, in init_binaries
    raise BinaryNotFound
utilities.binaries.BinaryNotFound
Bazarr exited.
(venv) /opt/Bazarr $ 
```

**Expected behavior**
Bazarr would be happy to use 7zip instead of unar/unrar

**Software (please complete the following information):**
 - Bazarr: git
 - OS: Alpine Linux

**Comment by morpheus65535** [comment]
Seems to make sense but I don't see including 7zip binaries. They're going to have to be user installed.

I'll gladly accept a PR for that including the upgrade of the rarfile dependency in libs. Make sur to update versions.txt.

**Comment by jvoisin** [comment]
I only suggested to bump rarfile.py, no to bundle [even more stuff](https://github.com/morpheus65535/bazarr/issues/2275).

Anyway, here is the pull-request bumping the version and adding 7z support: #2289

**Comment by morpheus65535** [comment]
Don't worry, wasn't expecting that. I just wanted to prevent you from working on something that wouldn't be accepted. Thanks!
