### ISSUE TITLE
Mismatched Episode Number Used in Query

### ISSUE THREAD

**Issue by Progeny42** [morpheus65535/bazarr#2284]
**Describe the bug**
Firefly (2002) is an annoying one to deal with, because the Aired order is not really desired (it was aired out of order), and so many people, including I, use the DVD order. Unfortunately, many resources, including `opensubtitles.com` do not recognise this order, and that causes problems.

I noticed however in the Debug logs of Bazarr that the query made to `opensubtitles.com` is not using the `episode` value from `GuessIt`, but I assume instead, the episode number according to the series.

For example, the episode `The Train Job` is episode 1 according to the aired order. However, for my purposes (to order it correctly in Plex), it is episode 2. `GuessIt` reflects that properly:

```
28/10/2023 23:05:46|DEBUG   |subliminal_patch.core           |GuessIt found: {
    "title": "Firefly",
    "year": 2002,
    "season": 1,
    "episode": 2,
    "episode_title": "The Train Job",
    "source": "Blu-ray",
    "screen_size": "1080p",
    "other": "Remux",
    "audio_codec": "DTS",
    "audio_channels": "5.1",
    "video_codec": "H.264",
    "container": "mkv",
    "type": "episode"
}
```

However, when the query is made to `opensubtitles.com`, the `episode_number` used is `1` (which also happens to be the episode `The Train Job` according to the Aired order.

```
28/10/2023 23:05:46|DEBUG   |urllib3.connectionpool          |https://api.opensubtitles.com:443 "GET /api/v1/subtitles?ai_translated=exclude&episode_number=1&imdb_id=303461&languages=en&moviehash=6bd488056a2f0ff3&season_number=1 HTTP/1.1" 200 None|
```

Uploaders to `opensubtitles.com` have thankfully added both DVD and Aired order subtitles under each episode, so that the right file does exist for automated systems such as Bazarr.

The top result shown in Bazarr after a manual search is `Firefly.S01E01.Serenity.2002.Bluray.576p.x264.AAC-AVX` by Uploader `anonim1979`.

If I go to the episode on `opensubtitles.com` myself, this entry does not appear. There are only 13 items present. The Bazarr log file says there are 14, and indeed it displays 14 when performing the manual search.

I performed a search using the exact same GET request myself using curl, and only 13 results were returned, matching the frontend of the website. Where is this extra entry coming from?

Anyway, back to my original point, as the `episode` number from Bazarr, rather than the filename itself via `GuessIt` is used, the incorrect episode is queried.

I have addressed this by manually downloading the correct subtitles for my DVD Ordered collection (thankfully it is only 14 episodes!), but I know other series have this issue (Futurama is another that has issues that I know of).

Should the query to providers use the episode number from `GuessIt` rather than the order from Bazarr?

If I perform the query myself using curl for the correct episode (2, which is `Bushwahacked` in Aired order), there are subtitles present for `The Train Job` (DVD order). The highest download is in fact a file specifically for `The Train Job`.

**To Reproduce**
- Perform a manual query of `Firefly (2002) - s01e02 - The Train Job [Bluray-1080p Remux][DTS 5.1][h264].mkv`
- Results for S01E01 The Train Job (Aired order) are returned.

**Expected behavior**
Results for S01E02 Bushwhacked (Aired order) should be returned, which as aforementioned, does contain subs for people that are using DVD order (which in this case, DVD order for S01E02 is The Train Job).

**Software (please complete the following information):**
- Bazarr: v1.3.1
- Radarr version: N/A
- Sonarr version: v3.0.10.1567
- OS: Linux-6.1.49-Unraid-x86_64-with (Running in Docker)

**Comment by morpheus65535** [comment]
Bazarr doesn't care about order. It use the episode number returned by Sonarr. Of course, I could stop overriding episode number guessed with the value we keep in database but it wont solve your problem: you'll get subtitles for the wrong episode if uploader doesn't use the same ordering you do. Anything I'm missing here?

**Comment by Progeny42** [comment]
No, you are correct. In cases like these, it would be preferable if the episode number from the file was used in preference to that from Sonarr, to workaround the fact Sonarr also does not support DVD ordering; a [reported issue back from 2014](https://github.com/Sonarr/Sonarr/issues/255).

At least in the case of Firefly, and Opensubtitles.com, there are uploads for each episode to account for DVD and Aired Order, so by using the episode number from the file rather than Sonarr, it should be more accurate.

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Let me know if it doesn't works as expected.
