### ISSUE TITLE
Performing a Manual Search on a Series Episode Scrolls the Page to the Top

### ISSUE THREAD

**Issue by Progeny42** [morpheus65535/bazarr#2285]
**Describe the bug**
As the title states, when performing a manual search for a particular Series episode, the webpage scrolls to the top when the Search Subtitles popup appears. This gets rather annoying when modifying multiple episodes in a season that are not the latest season.

**To Reproduce**
1. Go to a series
2. Scroll to the bottom and press the Search button for an episode

**Expected behavior**
The screen does not scroll to the top

**Screenshots**

**Software (please complete the following information):**
- Bazarr: v1.3.1
- Radarr version: N/A
- Sonarr version: v3.0.10.1567
- OS: Linux-6.1.49-Unraid-x86_64-with (Running in Docker)

**Comment by morpheus65535** [comment]
I agree, it's not desired.

@LASER-Yi could you take a look when you have some time?
