### ISSUE TITLE
Opensubtitles.com VIP not updating

### ISSUE THREAD

**Issue by AlliAlliAlli** [morpheus65535/bazarr#2287]
**Describe the bug**
I upgraded to opensubtitles.com VIP and I am still limited to only 20 downloads a day. Also none of those 20 downloads show up on my opensubtitles account.

**To Reproduce**
1. Upgrade account to VIP.
2. Start downloading subtitles.
3. Get throttled after 20.
4. Wait 24 hours.
5. Repeat 2-4

**Expected behavior**
I expected to be able to download up to 1000 subtitles a day after upgrading to VIP.

**Screenshots**
![Screenshot from 2023-11-03 00-16-23](https://github.com/morpheus65535/bazarr/assets/149752562/925367d5-0880-4f4c-86e1-3c8130d7a730)
![Screenshot from 2023-11-03 00-13-56](https://github.com/morpheus65535/bazarr/assets/149752562/599e5b46-2294-4c34-ae2c-2cc1c16cf992)

**Software (please complete the following information):**
 - Bazarr: 1.3.1
 - Radarr version 5.0.3.8127
 - Sonarr version 4.0.0.710
 - OS: Linux-6.2.0-35-generic-x86_64-with

**Additional context**
I've also tried shutting down bazarr, resetting the cache and restarting the program which didn't help. I've tried deleting the provider numerous times which didn't do anything. I've been trying to troubleshoot this for 2 days with no luck. I've also tried reading through closed issues but couldn't find any solutions but my apologizes if I've missed one somewhere with the answer. I've honestly just hit a wall and would appreciate any help at all.

**Comment by morpheus65535** [comment]
Please, do not submit image of logs. You find it useful to search through logs, it's the same for us.

It seems to be an issue with your account itself. Open an issue on opensubtitles.com and they will be able to help you with the log. They re able to see the whole response/request in there and debug with their own service logs.

If needed reopen this issue.
