### ISSUE TITLE
Forced embedded subtitles are not detected properly

### ISSUE THREAD

**Issue by dbarkar** [morpheus65535/bazarr#2288]
**Describe the bug**
When using embedded subtitles, Bazarr treats forced subtitles as full subtitles and doesn't trigger the search.

**To Reproduce**
1. Check "Use Embedded Subtitles" in Settings
2. Add to the library media file with embedded **forced** subtitles of desired language
3. Go to the library and press Search button
4. See that nothing happens - subtitles are considered as found.

**Expected behavior**
Bazarr should mark forced embedded subtitles differently (like it's done with HI) and start searching for full subtitles.

**Software (please complete the following information):**
 - Bazarr: v1.3.1
 - OS: Linux (docker)

**Additional context**
Maybe it's worth adding an option to ignore embedded forced subtitles (like it's done for PGS/ASS etc)

**Comment by morpheus65535** [comment]
Fixed in 1.3.2-beta:

![image](https://github.com/morpheus65535/bazarr/assets/5130500/ebd43c49-dbed-4583-9101-38e79a22a515)
