### ISSUE TITLE
[Feature Request] Separate the option "Download only monitored" between Sonarr/Radarr

### ISSUE THREAD

**Issue by TRaSH-** [morpheus65535/bazarr#229]
**Describe the solution you'd like**
Separate the option "Download only monitored" between Sonarr/Radarr,
This way you can choose if you want subs of monitored and/or unmonitored  series/movies.

**Comment by enchained** [comment]
I would also love a separate monitored option just for subs in Bazarr. There's a lot of cases where I want to monitor subs even if I don't monitor upgrades for the video file, and also lots of cases when I want to disable subs for specific episodes (like specials or something where subs are rarely ever found and I wouldn't want it forever hanging in "wanted")
