### ISSUE TITLE
Language= English, Subtitle Type= Hearing-impaired required ~ Not working

### ISSUE THREAD

**Issue by EmilianoNeme** [morpheus65535/bazarr#2293]
**Describe the bug**
The Hearing-impaired subtitle type for language profiles doesn't work. Bazarr will download Non-Hi subs if they high a higher score than Hi ones.

**To Reproduce**
1. Go to 'Settings' -> 'Sonarr' or 'Settings' -> 'Radarr'.
2. Set the minus score under 'Options' to something low, like "75".
3. Go to 'Settings' -> 'Languages'.
4. On 'Languages Filter' verify you have "English".
5. Set up a "Languages Profile" with "English" as the language and "Hearing-impaired required" as the "Subtitle Type" and make sure it is assigned to the movie/show.
6. Manually search for subtitles for the movie/episode, and verify there is a Hearing-impaired sub with a score higher than "75", and that there is a Non-Hi sub with a score even bigger than the highest rated Hearing-impaired one (For example, the highest rated Hi sub has a score of "82" while the highest rated Non-Hi one has a score of "93". Do not download the subtitle.
7.  Automatically search for missing subtitles for the content using the 'Search" button which triggers an automatic search and download of the missing sub, or wait until the scheduled task is executed.

**Expected behavior**
Bazarr downloads the Hearing-impaired sub with the highest score (82) which is bigger than the minimum value set in settings (75) even though there are other subs with a higher rating.

**Actual behavior**
Bazarr downloads the highest rated sub (93) which in this case is a Non-Hearing-impaired one even though there is a Hearing-impaired one whose score (82) is above the minimum value set in settings (75), and the Hi sub still shows up a missing.

**Alternative language profile behavior**
If you set up a "Languages Profile" with a second "Language" = "English" and the "Subtitle Type" =  "Normal or hearing-impaired required" and "Cutoff" = "Any" and follow the rest of the steps, then Bazarr downloads the highest rated sub (93) and doesn't report any missing Hi subs due to the "Cutoff". However the behavior is still wrong.

**Software:**
 - Bazarr: [v1.3.1] [MASTER] [linuxserver.io]
 - Radarr version [5.0.3.8127] [linuxserver.io]
 - Sonarr version [3.0.10.1567] [linuxserver.io]
 - OS: Docker [V4.25.0] • macOS [Sonoma 14.0] 

**Additional context**
I think this is a serious bug because there are user that truly need Hi subs, and for some content these subs are actually better, for example, in Sitcoms where they mention references.

Even though I have version 1.3.1 now, I recall experiencing the same issue with the previous 1.3.0.

**Comment by morpheus65535** [comment]
Is this happening with a specific provider? I think I can reproduce it with opensubtitles.com but did you experienced it with others?

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Can you test and confirm please?

**Comment by EmilianoNeme** [comment]
I haven't tested the beta yet. But I've just tried to replicate the problem with 2 files.

### This is what I get with all my providers enabled, included Open Subtitles
Bazarr downloads Open Subtitles' highest scored sub (Non-Hi in this case)



![1](https://github.com/morpheus65535/bazarr/assets/30270458/7f4e9f3a-9810-4b34-bbd6-176cf8078a9e)


### This is what I get if I remove Open Subtitles but keep the rest
Bazarr downloads the proper Hi sub.

![2](https://github.com/morpheus65535/bazarr/assets/30270458/f3f3263d-a17b-4c3c-ae9d-b3a38ab8dc67)

**Comment by EmilianoNeme** [comment]
Apparently the issue was caused by Open Subtitles. I will try the new version now.

**Comment by EmilianoNeme** [comment]
I have updated to the latest development version and searched for subs for the same movie file and I got Hi subs, so apparently the bug is fixed.

**Comment by morpheus65535** [comment]
Keep me informed if you get this back.
