### ISSUE TITLE
Error when downloading certain available subtitles

### ISSUE THREAD

**Issue by Drawmonster** [morpheus65535/bazarr#230]
**Describe the bug**
I noticed several random episodes missing from certain series. When performing a manual search, subs were found for the episodes. Clicking  to add the sub would result in a subtitle not being downloaded and an error message in the log.

**To Reproduce**
1. Go to missing episode in series
2. Click to do a manual search
3. Click on found subs

**Expected behavior**
Expected subs to be downloaded automatically, or at least for the sub to be downloaded when doing a manual search and adding the sub.

**Screenshots**
https://i.imgur.com/twa0iPW.png
https://i.imgur.com/7qiJb6V.png

**Software (please complete the following information):**
 - Bazarr: 0.6.7.1
 - Radarr version 0.2.0.1217
 - Sonarr version 2.0.0.5252
 - OS: Unraid using Docker

**Comment by morpheus65535** [comment]
Could you update to 0.6.9 and test again please? Submit a debug log if it is still not working.

**Comment by morpheus65535** [comment]
Is this still an issue or I can close it?

**Comment by morpheus65535** [comment]
No feedback. Closing this issue.
