### ISSUE TITLE
Whisper provider marking generated subtitles as "ENGLISH FORCED"

### ISSUE THREAD

**Issue by steeef** [morpheus65535/bazarr#2300]
**Describe the bug**
I'm successfully generating subtitles using the Whisper provider, configured as in the docs. However, the subtitles it's generating are marked as `ENGLISH FORCED`.

**To Reproduce**
1. Set up Whisper to run in Docker as describe in https://wiki.bazarr.media/Additional-Configuration/Whisper-Provider/
2. See subtitles generated as `ENGLISH FORCED`.

**Expected behavior**
Any subtitles generated by the Whisper provider should be marked as `ENGLISH`, as it's generating subtitles for all dialogue, not foreign languages.

**Screenshots**
An episode correctly marked as having English dialogue: ![An episode correctly marked as having English dialogue](https://github.com/morpheus65535/bazarr/assets/77589/152b8f11-359a-4478-8c55-70ee2f90754d)

Subtitle download history: ![Subtitle download history](https://github.com/morpheus65535/bazarr/assets/77589/ec012701-27c0-4a90-ba32-590e90e3b904)

mouseover info for the English Forced subtitles, showing that it was generated by Whisper: ![mouseover info for the English Forced subtitles, showing that it was generated by Whisper](https://github.com/morpheus65535/bazarr/assets/77589/799452b1-7012-497e-a75e-da3e6e273db6)

**Software (please complete the following information):**
 - Bazarr: v1.3.1
 - Radarr version v5.1.3.8246
 - Sonarr version v3.0.10.1567
 - OS: Linux: Debian Bookworm. All apps running in Docker containers.

**Additional context**
I've enabled deep inspection to identify what language the audio is in, and I've tried tweaking the Language settings so it's marked as done once `ENGLISH` (not `FORCED`) subtitles are found.

**Comment by morpheus65535** [comment]
@ayancey can you take a look at this one please?

**Comment by JaiZed** [comment]
@morpheus65535 This should be marked as fixed now, according to @ayancey.

**Comment by ayancey** [comment]
> @morpheus65535 This should be marked as fixed now, according to @ayancey.

I think it will close automatically when you fix gets merged into master: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by morpheus65535** [comment]
> > @morpheus65535 This should be marked as fixed now, according to @ayancey.
> 
> 
> 
> I think it will close automatically when you fix gets merged into master: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

I'll close it, just in case ;-)
