### ISSUE TITLE
"EN HI Required" as Language 1, "EN Non-Hi Required" as Language 2, and cutoff=any fails to download subtitles if there are not HI ones

### ISSUE THREAD

**Issue by EmilianoNeme** [morpheus65535/bazarr#2302]
**Bug**
Using a double language profile, with "**English -  Hearing-impaired Required**" as Language 1, "**English - Normal or hearing-impaired**" as Language 2, and "**Cutoff**=**Any**" fails to download subtitles if there aren't HI subs. 

 
<img width="847" alt="Screenshot 2023-11-21 at 8 28 23 PM" src="https://github.com/morpheus65535/bazarr/assets/30270458/1d159e1a-3f49-4241-90f1-a2a987a422b5">

**Expected behavior**
If there are no "Hearing-impaired"  then the app should download the "Normal" ones. 

**Software**
 - Bazarr: [v1.3.2-beta.14] [linuxserver.io] 
 - Radarr version [5.1.3.8246] [linuxserver.io] 
 - Sonarr version [3.0.10.1567] [linuxserver.io] 
 - OS: [Docker v4.25.1] [macOS Sonoma 14.0]

**Additional context**
Experienced with subs from providers and with embedded ones.

**Comment by EmilianoNeme** [comment]
> There's no such thing as non-HI required. You can simply have one language in your profile with "Normal or hearing-impaired" selected.

I apologize. I didn't use their exact names. With "non-HI required" I meant ""Normal or hearing-impaired". I've just fixed the post and added a picture.

**Comment by morpheus65535** [comment]
You've mist the point that your use case make no sense: if you want to searching as soon as you get one HI or normal subtitles, simple have one time English with "Normal or hearing-impaired" and remove the cutoff. Is there something I'm missing here?

**Comment by EmilianoNeme** [comment]
> You've mist the point that your use case make no sense: if you want to searching as soon as you get one HI or normal subtitles, simple have one time English with "Normal or hearing-impaired" and remove the cutoff. Is there something I'm missing here?

Maybe I didn't explain it properly. Also I don't fully understand what you say. My idea is to download HI subs but in case there are not HI subs, then download Non-Hi ones s a last resort. I could use Bazarr without the cutoff, but then if some movie or series doesn't have HI subs, Bazarr would download only the Non-HI ones and report the other ones as missing. I understand than the idea of the cut-off is to stop looking for subs as soon as it downloads one.

For example, it's rare to find Hi subs for Chinese movies, and shows quite often include embedded subs but they aren't always tagged as HI ones even if they are.

**Comment by EmilianoNeme** [comment]
Even if I change the cutoff as "En" I experience the problem.

**Comment by EmilianoNeme** [comment]
After further testing it seems like the cutoff isn't the bug. The problems seems to be that Language profiles with more than one language  are broken. It would only pay attention o the first language for some reason. If I modify the language profile to Normal or hearing-impaired as single language, remove the profile from the series and then re-add it, I'm able to get subs, but whenever I try with a dual language profile I get nothing.

**Comment by morpheus65535** [comment]
> My idea is to download HI subs but in case there are not HI subs, then download Non-Hi ones as a last resort.

Here's the language profile you need. Nothing less, nothing more...

![image](https://github.com/morpheus65535/bazarr/assets/5130500/c46df009-be5f-4ca9-b2f7-8090b263fdcb)

**Comment by EmilianoNeme** [comment]
> > My idea is to download HI subs but in case there are not HI subs, then download Non-Hi ones as a last resort.
> 
> Here's the language profile you need. Nothing less, nothing more...
> 
> ![image](https://user-images.githubusercontent.com/5130500/284752737-c46df009-be5f-4ca9-b2f7-8090b263fdcb.png)

Thank you! But wont that profile download the sub with the highest score rather than the HI ones?

**Comment by morpheus65535** [comment]
> Thank you! But wont that profile download the sub with the highest score rather than the HI ones?

Yes it will. There's no priority concept in languages profile anyway. Search is done in random order and cutoff "Any" will stop after the first one it finds.

**Comment by EmilianoNeme** [comment]
> > Thank you! But wont that profile download the sub with the highest score rather than the HI ones?
> 
> Yes it will. There's no priority concept in languages profile anyway. Search is done in random order and cutoff "Any" will stop after the first one it finds.

But I have been using a language profile with Hearing Impaired Required first and all the subs I got where HI

**Comment by morpheus65535** [comment]
> But I have been using a language profile with Hearing Impaired Required first and all the subs I got where HI

You were simply lucky. Again, there's no such thing as priority.

**Comment by morpheus65535** [comment]
Nothing left to fix here. I'll close this issue.
