### ISSUE TITLE
WhisperAI returns KeyError

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [morpheus65535/bazarr#2305]
**Describe the bug**
When using the sample docker compose provided on the wiki, Bazarr returns KeyError.

Log entry ->
Throttling whisperai for 10 minutes, until 23/11/24 15:10, because of: KeyError. Exception info: "''detected_language'' ~ whisperai.py@238"

**To Reproduce**
1. Manual search for any subtitle.
2. Go to System -> Providers
3. See that Whisper is listed as KeyError

**Expected behavior**
No keyerror and whisperAI should work

**Software (please complete the following information):**
 - Bazarr: 1.3.1
 - Package version: v1.3.1-ls224 by linuxserver.io
 - OS: Linux-6.2.16-11-bpo11-pve-x86_64-with

**Comment by morpheus65535** [comment]
Whisper is unable to detect the language of your media. We should catch this case but don't expect this media to works.

@ayancey you want to add something to prevent an uncaught KeyError exception?

https://github.com/morpheus65535/bazarr/blob/development/libs/subliminal_patch/providers/whisperai.py#L238-L240

**Comment by ayancey** [comment]
> Whisper is unable to detect the language of your media. We should catch this case but don't expect this media to works.
> 
> @ayancey you want to add something to prevent an uncaught KeyError exception?
> 
> https://github.com/morpheus65535/bazarr/blob/development/libs/subliminal_patch/providers/whisperai.py#L238-L240

I'll add a check for this, but I'm suspicious that there could have been another error on the backend that caused this.

**Comment by morpheus65535** [comment]
Having full Bazarr log and Whisper log would help I guess?

**Comment by ayancey** [comment]
> Having full Bazarr log and Whisper log would help I guess?

Yeah, that would be fantastic. whisper-asr-webservice's logs aren't as good as I would like

**Comment by morpheus65535** [comment]
@Gandalf-the-Blue can you provide both please?

**Comment by Gandalf-the-Blue** [comment]
Here is the full bazarr log

[bazarr.log](https://github.com/morpheus65535/bazarr/files/13463428/bazarr.log)

The logs for the Whisper service in docker only show the application startup and nothing else, Is there another place I need to look for the logs for this?

I've added my docker-compose, in case it helps
```
whisperasr:
    container_name: bazarr_whisper
    image: onerahmet/openai-whisper-asr-webservice:latest
    networks:
      - acquisition
    environment:
      - ASR_MODEL=large
    ports:
      - 3511:9000
    restart: unless-stopped
```

**Comment by morpheus65535** [comment]
@ayancey anyting else to do here?

**Comment by morpheus65535** [comment]
No news, good news!
