### ISSUE TITLE
Not detecting code pt-pt correctly as portuguese 

### ISSUE THREAD

**Issue by X-static** [morpheus65535/bazarr#2306]
**Describe the bug**
I created a post processing script to rename pt subtitles to pt-pt because I need to distinguish between Brazilian portuguese and portuguese (Portugal) on Plex and only the later are properly identified there.
The issue is that bazarr, despite recognizing them as portuguese, re-downloads them

**To Reproduce**
1. Use profile with language portuguese and Brazilian portuguese 
2. Add post processing script: `case "{{subtitles_language_code2}}" in "pt" ) cp "{{subtitles}}"  "{{directory}}"/"{{episode_name}}".pt-pt.srt ;; esac`
3. Script will rename .pt subtitle to .pt-pt
4. Bazarr will keep re-download the same subtitles

**Expected behavior**
Should properly detect subtitle with .pt-pt as portuguese and stop searching.

**Screenshots**
![Screenshot_2023-11-26-03-01-02-985_com vivaldi browser](https://github.com/morpheus65535/bazarr/assets/3238301/c52134c3-cf9e-46d0-9779-9f4f325f38b3)

As you can see, the .pt-pt subtitle is recognized as Portuguese but still display as missing.

**Software (please complete the following information):**
 - Bazarr: v1.3.1
 - Radarr version 5.1.3.8246
 - Sonarr version 3.0.10.1567
 - OS: Ubuntu 20.4

**Additional context**
As a workaround I changed the script to copy instead of move/rename but now I have duplicate subtitles.

**Comment by morpheus65535** [comment]
I've never tested with bash case directly in post-processing. I suggest you try with an external bash script and confirm if you still have the issue.

**Comment by X-static** [comment]
Hi, thank you for your reply. The bash wasn't the problem. The issue I was reporting was about bazarr not recognizing ".pt-pt" code as a European portuguese subtitle, wish is a widely known recognized code (on Plex, for example).
If I need a more complex script I'll changed it to an external bash script, but for not it's working.

**Comment by morpheus65535** [comment]
![image](https://github.com/morpheus65535/bazarr/assets/5130500/0b0c3d5b-7773-47ad-beb9-822d6b6c5497)

It's working perfectly fine for me... I don't know what wrong on your side... Scan disk doesn't work? If you unassign the language profile and reassign it, is the pt subtitles still marked as missing?

**Comment by X-static** [comment]
The scan disk works, bazarr "sees" the subtitle, the same as your example, but is marked as missing and will eventually download it again.
I tried to clear and reassign the profile language but the behavior is the same.
This is how I see it (the bottom line):
![Screenshot_2023-12-27-17-57-22-005_com vivaldi browser](https://github.com/morpheus65535/bazarr/assets/3238301/83c1d481-39f0-4887-9245-859bee2ae9c8)

**Comment by morpheus65535** [comment]
You are using languages equals settings?

**Comment by X-static** [comment]
No. Never used that setting.

**Comment by morpheus65535** [comment]
Fixed in upcoming beta.

**Comment by alexkiddddd** [comment]
Hi there, I have the same problem, I have added that script to bazarr and now I have the same subtitle twice, one named xxxx.pt.srt and other xxx.pt-pt.srt, is there any fix? My bazarr is version 1.4.2

Thanks

**Comment by X-static** [comment]
> Hi there, I have the same problem, I have added that script to bazarr and now I have the same subtitle twice, one named xxxx.pt.srt and other xxx.pt-pt.srt, is there any fix? My bazarr is version 1.4.2
> 
> Thanks

Hi. If you just want to rename the subtitle, use 'mv' instead of 'cp'. I do 'cp' because I have a subfolder for bazarr subtitles.
