### ISSUE TITLE
Custom search frequency in config file is no longer respected.

### ISSUE THREAD

**Issue by eeyoredk** [morpheus65535/bazarr#2308]
**Describe the bug**
After updating to v1.4.0 it is no longer possible to set custom frequency for the following in the config file.
-wanted_search_frequency
-wanted_search_frequency_movie
-upgrade_frequency

Bazarr ignores value larger than 24 and defaults to 6 hours
Also it seems that Bazarr ignores that upgrade is turned off

**To Reproduce**
1. Open config file
2. Edit values to larger than 24
3. Restart Bazarr
4. Verify in scheduled

**Expected behavior**
Bazarr should respect values in config file.

**Screenshots**
![image](https://github.com/morpheus65535/bazarr/assets/59906800/7d056317-ff7a-4e96-ae24-779418c51e79)
![image](https://github.com/morpheus65535/bazarr/assets/59906800/dfc5a51d-9fbe-443b-95fb-d4a50fdd74a9)
![image](https://github.com/morpheus65535/bazarr/assets/59906800/b29c2565-acca-4d5b-a7ab-318690ee6c7d)

**Software (please complete the following information):**
 - Bazarr: [v1.4.0]
 - OS: [Windows 11]

**Comment by morpheus65535** [comment]
It's never been supported to edit directly config file with values not accessible through UI. It may have worked before but won't be working in the future. The way to achieve what you want would be to add additional value to those configuration through the UI. You can either open a feature request or create a pull request with the required changes. Of course, it's always recommended to discuss before you do the implementation to have values that would be useful to others.

I'll take a look at the upgrade subtitles not being taken into account.

**Comment by morpheus65535** [comment]
This one seems to have been there for a while! It should be fixed in upcoming 1.4.1-beta.0.

**Comment by morpheus65535** [comment]
No news, good news!
