### ISSUE TITLE
Improve UX in Edit Series

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#2317]
**Describe the bug**
I know this is not critical but Bazarr is a mature software an every lite improvement maters.
The combo/list component in the UI is not intuitive.

**To Reproduce**
1. Go to a serie / movie
2. Click in Edit Series
![image](https://github.com/morpheus65535/bazarr/assets/10577978/c854f0ca-17e3-4885-b9d2-2c13073fa5cc)
3. I want to select None in Language Profile
![image](https://github.com/morpheus65535/bazarr/assets/10577978/bba52846-4a78-4980-824c-e64babdb195e)
4. It's confusing to me to not seen the None/Empty option in the list. I had to search in Reddit for a while until some user gave me the hint to click in the "X" near the list.

**Expected behavior**
The combo/list component should have the "None/Empty" element at the begining of the list. The "X" button is useful for more complex lists with multiple selections (to remove all selections at once).

**Software (please complete the following information):**
 - Bazarr: v1.4.0

**Comment by morpheus65535** [comment]
Unfortunately, the Select/MultiSelect component come from the Mantine UI framework that we use for Bazarr and the only way to clear the value is through the "x". Making it differently would require to define a custom component to implement a "None" item that would send an empty value to API. As we don't have a frontend dev anymore, it probably wont happens soon.

This isn't an issue but more a feature request. You can create one on https://bazarr.featureupvote.com/ and we'll see how it goes. Of course a proper PR would be great to!
