### ISSUE TITLE
error blacklisting a subtitle

### ISSUE THREAD

**Issue by rmichelena** [morpheus65535/bazarr#2318]
I tried to blacklist a subtitle and got "error 500" something about subtitle missing or permissions.
Log shows the following:
`Traceback (most recent call last):
  File "/app/bin/bazarr/subtitles/tools/delete.py", line 51, in delete_subtitles
    os.remove(path_mappings.path_replace(subtitles_path))
FileNotFoundError: [Errno 2] No such file or directory: \'/tv/Inspector Montalbano/Season 4/Inspector Montalbano - S04E01 - The Sense of Touch [HDTV-720p] -Me7alh.es.srt\`

However the subtitle was there and I was able to delete it (with the delete action) without problem.
futhermore, my (repeated) attempt to blacklist it, created a false entry on history: it shows a new "downloaded" (one month ago) event, when before my attempt to blacklist it, there was only one "downloaded" event in history. The one on top is the succesful delete (not blacklist).
<img width="733" alt="Screenshot 2023-12-10 at 17 18 25" src="https://github.com/morpheus65535/bazarr/assets/77797875/72317904-0edc-40bc-b89a-3b1ed7b21b78">

**Comment by morpheus65535** [comment]
I can't reproduce this issue. I've just tried to blacklist an episode subtitles without any issue. Are you able to reproduce it on demand?

**Comment by morpheus65535** [comment]
No news, good news!
