### ISSUE TITLE
Greek subs are jibberish

### ISSUE THREAD

**Issue by karserasl** [morpheus65535/bazarr#2323]
**Describe the bug**
The subtitles are downloading ok, but somewhere in processing, they turned into jibberish
`2
00:00:12,730 --> 00:00:14,480
Î¤Î£Î‘ ÎŸÎ¥Î� ÎŸÎ¥ | Î Î‘Îš Î“ÎšÎ™ÎŸÎ¥ Î“Î™ÎŸÎ�Î“Î
`

**Software (please complete the following information):**
Nightly (happens in latest also)
Latest *Arrs

**Comment by morpheus65535** [comment]
Do you encode subtitles to UTF8 in Settings-->Subtitles?

**Comment by karserasl** [comment]
Tried with and without utf8.
When automatic sync is on, it messed with the subs.

The thing is, not with all subs.. And i went back to v1.3.0, and it still happening. I just didnt saw it.

The subtitle has some emojis, dunno if thats what is causing this.

`1
00:00:01,590 --> 00:00:09,980
Χρονισμός και Υπότιτλοι:
🐩 Woof, Woof, Kiss Me! 💋 Team @Viki.com`

**Comment by morpheus65535** [comment]
"Should" be fixed in upcoming beta. Can you try it and confirm please?

**Comment by karserasl** [comment]
Hello

Yes i confirm its fixed now.
