### ISSUE TITLE
WhisperAI provider throttled unnecessarily on bad video file

### ISSUE THREAD

**Issue by JaiZed** [morpheus65535/bazarr#2325]
**Describe the bug**
If an audio stream cannot be successfully extracted by ffmpeg from a video file, then a RuntimeError is raised and the WhisperAI provider is throttled for 10 minutes.

**To Reproduce**
1. Create a video file with a “bad” audio stream.
2. The easiest way is to simply remove the audio stream from an MKV file.
3. Submit this file to WhisperAI.
4. Instant 10 minute throttle

**Expected behavior**
This is a problem with the input and not the WhisperAI provider.
It didn’t even get a chance to see the file and there’s nothing wrong with the provider itself, so it shouldn’t be throttled.

**Software (please complete the following information):**
 - Bazarr: v1.4.1

**Comment by morpheus65535** [comment]
I'm pretty sure you can submit a PR that will return no subtitles on list() or will gracefully fails on download(). ;-)

**Comment by morpheus65535** [comment]
I'll close this issue as we're working on a PR to fix it and there's nothing else to do here.
