### ISSUE TITLE
Authentication Password / MD5 Hash Fault

### ISSUE THREAD

**Issue by crodriguez6497** [morpheus65535/bazarr#2326]
Sorry, i'm back again with a similar issue to my previous report...
https://github.com/morpheus65535/bazarr/issues/2309#issue-2016810300

**Describe the bug**
When entering a password consisting only of numbers for either form or basic authentication, bazarr will throw a 500 ERROR and subsequently set authentication type to null and does not set a username or password in the config. This can only be rectified by manually inputting the MD5 hash (password), username, and authentication type in the config.yml.

Relevant config.yml portion:
auth:
apikey: REDACTED
password: ''
type: null
username: ''

Without digging too much into it, I am assuming it expects a string value type and is misinterpreting a numeric input as a different value type, thus leading to errors with hash generation.

**To Reproduce**
1. Settings>General>Authentication
2. Select either Basic or Form
3. Enter a username + Password(only numbers)
4. Save

**Expected behavior**
Bazarr accepts passwords for authentication that consist only of numbers.

**Software (please complete the following information):**
System 1:
Bazarr Version: 1.4.0
Package Version: v1.4.0-ls225 by linuxserver.io
Sonarr Version: 3.0.10.1567
Radarr Version: 5.1.3.8246
Operating System: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with
Python Version: 3.11.6

System 2:
Bazarr Version: 1.4.0
Package Version: v1.4.0-ls227 by linuxserver.io
Sonarr Version: 4.0.0.734
Radarr Version: 5.1.3.8246
Operating System: Linux-6.1.64-Unraid-x86_64-with
Python Version: 3.11.6

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Thanks for reporting!
