### ISSUE TITLE
Authentication issue with opensubtitles.com

### ISSUE THREAD

**Issue by GitTimeraider** [morpheus65535/bazarr#2327]
**Describe the bug**

**To Reproduce**
1. Go to 'Bazarr and search for a subtitle (manually, automatically or through task)'
4. See error appear under system -> providers and in the log

**Expected behavior**
Make use of opensubtitlescom without errors

**Screenshots**

**Software (please complete the following information):**
Linuxserver.io docker image version v1.4.0 (Release of 28-11-2023)
Running in Docker

**Additional context**
Debug logs:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/13686747/bazarr.log)

**Comment by GitTimeraider** [comment]
Stuff tried:
Clear out cache
Change username and password to be easy
Adjust the values in the config yaml

Issue still happens after a search

**Comment by morpheus65535** [comment]
Do not use your email address but your username. Other than that, it's either you have mistyped username/password or there's an issue with your account and you must contact the provider admins.

**Comment by GitTimeraider** [comment]
> Do not use your email address but your username. Other than that, it's either you have mistyped username/password or there's an issue with your account and you must contact the provider admins.

Only used my mail to test once, used my username after enabling debug log.

Havent mistyped any data, can login on the opensubtitles.com website with exactly the same credentials

What can I say to opensubtitles.com that can make them check it? If I mention Bazarr, will they know where to check deeper outside of simply telling me to make sure my credentials are correct?

**Comment by GitTimeraider** [comment]
Ended up fully removing the persistent volume (the /config). repulling the docker image and throwing in a freshly made opensubtitles account.

Yet to encounter the issue after that.
