### ISSUE TITLE
Renaming post-processing don't work

### ISSUE THREAD

**Issue by firu82** [morpheus65535/bazarr#2328]
**Describe the bug**
 Renaming subtitles using the 3 letter code not work 

**To Reproduce**
Go to custom post processing
test two codes:
mv "{{subtitles}}" "{{directory}}/{{episode_name}}.{{subtitles_language_code3}}.srt" && echo
and
mv "{{subtitles}}" "{{directory}}"/"{{episode_name}}.{{subtitles_language_code3}}".srt

Download subtitle
no change subtitle with 2 code digit
no event show in logs

I don't know if I'm getting the code wrong or if it's a bug in the system since I don't see any error in the log to rename

thanks for the help
"information):**
 - Bazarr: [v 1.4.0]
 - Radarr version [ v 3.0.10.1567]
 - Sonarr version [ v 5.1.3.8246]
 - OS: [Linux-5.13.x-x86_64]
 - all Docker Linuxserver

**Comment by morpheus65535** [comment]
It may be because of a hearing-impaired subtitles language code. You should use this (tested successfully):
`mv "{{subtitles}}" "{{directory}}"/"{{episode_name}}.{{subtitles_language_code3_dot}}".srt`

**Comment by firu82** [comment]
hello tanks for the help!

This:  mv "{{subtitles}}" "{{directory}}"/"{{episode_name}}.{{subtitles_language_code3_dot}}".srt
and
 mv "{{subtitles}}" "{{directory}}"/"{{episode_name}}.{{subtitles_language_code3}}".srt

tested and work perfect

I don't know if it's my problem or a bug when I download the subtitle I get a 409 error, permission errors? But when you do a disk scan the sub appears with the code3

**Comment by morpheus65535** [comment]
Sounds like a permission issue to me: `Unable to save subtitles file. Permission or path mapping issue?`
