### ISSUE TITLE
[Feature Request] Upstart script for FreeNas/FreeBSD

### ISSUE THREAD

**Issue by Waterboy1602** [morpheus65535/bazarr#233]
I would like to have an upstart script for FreeBSD. I already succeeded in running Bazarr, but it would be a lot easier if it started automatically.

Thank you already for all your effort!

**Comment by morpheus65535** [comment]
We do not provide startup script. You can find some on the wiki that have been provided by users. You can submit yours if you manage to get it done. Just don't expect help from us regarding this. Good luck! ;-)
