### ISSUE TITLE
Bazaar keeping HDDs spun up (Follow Up to #2044)

### ISSUE THREAD

**Issue by k29t59dh** [morpheus65535/bazarr#2330]
To follow-up on https://github.com/morpheus65535/bazarr/issues/2044

I've almost solved it by:

1. Enabling _Skip video file hash calculation_
2. Enabling _Defer searching of subtitles until scheduled task execution_ for sonarr and radarr and instead:
3. manually triggering search via API calls from sonarr/radarr scripts when new media's added

Despite that the scheduled search and upgrade tasks still spin up the disks, so the one remaining piece would be a _Never_ option for _Search and Upgrade Subtitles_:
<img width="318" alt="Screenshot 2023-12-17 at 3 01 10 PM" src="https://github.com/morpheus65535/bazarr/assets/76966241/3245daef-b5e7-4edc-9f2d-36b9dda80339">

I tried to hack it in (at least to test) but I couldn't find the frontend sources in my docker install. Maybe someone more knowledgable can tackle that.

I can post my sonarr and radarr scripts if anyone else would like to use them.

**Comment by morpheus65535** [comment]
Bazarr does already search for subtitles when new media is imported in Sonarr/Radarr. I don't know why you use external script to achieve that.

If you want to create a PR to dev branch for a "Never", you need to edit at least those files:
- for settings Validator: https://github.com/morpheus65535/bazarr/blob/development/bazarr/app/config.py
- to deal with it in scheduler: https://github.com/morpheus65535/bazarr/blob/development/bazarr/app/scheduler.py
- items from drop down: https://github.com/morpheus65535/bazarr/blob/development/frontend/src/pages/Settings/Scheduler/options.ts#L34

**Comment by k29t59dh** [comment]
> Bazarr does already search for subtitles when new media is imported in Sonarr/Radarr. I don't know why you use external script to achieve that.

Right, I misremembered. I added that because I think in some cases bazarr would "upgrade" imported subtitles even with _Upgrade Manually Downloaded or Translated Subtitles_ disabled - maybe an import timing issue. So I trigger it manually only when none are present.

Thanks for the links, I'll take another look at it.

**Comment by JaiZed** [comment]
Actually, I’ve been looking at for the last few days and I’m just about done with an implementation that should handle all your current concerns.
Basically, almost every task will have a Manually option.

**Comment by morpheus65535** [comment]
@k29t59dh Something else to fix here?

**Comment by morpheus65535** [comment]
No news, good news!

**Comment by k29t59dh** [comment]
I just noticed this - I'll test it out. Helps enormously, thank you.

**Comment by JaiZed** [comment]
Good to hear that it's working as intended.
Just doing our part to save energy and keep the Earth green, 1 watt at a time. 😀
