### ISSUE TITLE
Zimuku subtitle provider not working

### ISSUE THREAD

**Issue by richerzhagen** [morpheus65535/bazarr#2334]
**Describe the bug:**
When enabling Zimuku as a subtitle provider i am getting the following error:
`Throttling zimuku for 10 minutes, until 23/12/20 05:55, because of: IndexError. Exception info: "'list index out of range' ~ zimuku.py@142"|`

**To Reproduce:**
I made an account on anti-captcha and put funds in it. copied the Anti-Captcha Account Key into Bazarr subtitle settings, and enabled Zimuku as subtitle provider.

**Expected behavior:**
Subtitles should be downloaded from Zimuku.

**Software:**
Bazarr Version:        1.4.1-beta.7
Package Version:    v1.4.1-beta.7-ls557 by linuxserver.io

**Additional context:**
Reply from morpheus65535 on discord: 
"I guess they made changes to the website when they changed domain name and it prevent our parser to works properly."

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Let me know if not!
