### ISSUE TITLE
Error 406 subscene.username must is_type_of <class 'str'> but it is 123123

### ISSUE THREAD

**Issue by Am0rphous** [morpheus65535/bazarr#2341]
**Describe the bug**
Hi! When adding Subscene account under Settings -> Providers, I get following error:
````
Error 406
subscene.username must is_type_of <class 'str'> but it is 123123
````
where `123123` is a numeric example of my Subscene account, which consists of only numbers.

**To Reproduce**
1. Run latest docker container `lscr.io/linuxserver/bazarr:latest`
2. Navigate to the server e.g. `http://10.0.0.11:6767`
3. In Settings and under Provider, choose "Subscene" when adding a provider account.
4. After writing my username which contains numbers, the error appears, and I am unable to proceed adding my Subscene account.

**Expected behavior**
Successfully being able to add  a Subscene account, where the username consists of only numbers.

**Software (please complete the following information):**
 - Bazarr: v1.4.0 (2023-11-28) Master
 - OS: Ubuntu 22.04 with kernel 5.15.0-91-generic

**Comment by morpheus65535** [comment]
Already fixed in dev branch: https://github.com/morpheus65535/bazarr/commit/c97a98d4f2141a34fd798612457f678f10ce0461

**Comment by Am0rphous** [comment]
Thanks @morpheus65535 and happy new year!

**Comment by morpheus65535** [comment]
Same to you!
