### ISSUE TITLE
Addic7ed Throttling 

### ISSUE THREAD

**Issue by Kev1n121** [morpheus65535/bazarr#2343]
Addic7ed Throttling addic7ed for 10 minutes, until 24/01/04 07:16, because of: ValueError. Exception info: "'not enough values to unpack (expected 2, got 1)' ~ addic7ed*Describe the bug**

1. try to get sub for scenes
2 i am using sonarr with bazarr

**Comment by morpheus65535** [comment]
We need full debug log reproducing the issue to try to fix this. Please provide it.

**Comment by morpheus65535** [comment]
One month later.. no news, good news!
