### ISSUE TITLE
Legendasdivx, password problem.

### ISSUE THREAD

**Issue by Havokdan** [morpheus65535/bazarr#2344]
**Describe the bug**
Good morning, I have a problem with the legendasdivx provider, I enter the password, save the provider, however, when I click on the provider settings and use the icon to display the password, I see that the password is different from the one I entered, I redid the procedure countless times times to make sure I didn't copy or type it wrong, and the problem persists.

**To Reproduce**
1. I click to add the LegendasDivx provider;
2. I add my username and password, and click to save the changes;
3. An error message appears with a provider next to the system tray, in addition to the error message in the list of configured providers.

**Expected behavior**
Let there be no error, as the data entered is correct, I don't know why bazarr changes my password.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr Version 1.4.0
 - OS: Windows 10

**Additional context**

**Comment by morpheus65535** [comment]
Your password contain only numeric characters? If the answer is yes, this bug is already fixed in upcoming 1.4.1.

**Comment by Havokdan** [comment]
> Your password contain only numeric characters? If the answer is yes, this bug is already fixed in upcoming 1.4.1.

Yes, only numbers, so I'll wait for the next version, for now I'll keep the provider disabled until then, thanks.
