### ISSUE TITLE
utilities.binaries.BinaryNotFound For every video

### ISSUE THREAD

**Issue by FrankTheTank908** [morpheus65535/bazarr#2347]
**Describe the bug**

I tried reinstalling and also seeing if unrar and ffmpwg/ffprobe were installed.

Not sure why I'm getting this error now when a month or two ago it was working great

**To Reproduce**
1. Go to 'scan for any subtitles and error in logs'
2. Click on 'any video'
3. Scroll to 'scan'

**Expected behavior**

I expected to see results of providers

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: [v1.4.1-beta.12]
 - Radarr version [v5.2.6.8376]
 - Sonarr version [v4.0.0.748]
 - OS: [Windows 10]

**Additional context**

This is my error for every video it try's to get data to search for subtitles 

Traceback (most recent call last):
  File "c:\\bazarr\\bazarr\\subtitles\\utils.py", line 49, in get_video
    refiner(original_path, video)
  File "c:\\bazarr\\bazarr\\subtitles\\refiners\\ffprobe.py", line 32, in refine_from_ffprobe
    data = parse_video_metadata(file=path, file_size=file_id.file_size,
  File "c:\\bazarr\\bazarr\\utilities\\video_analyzer.py", line 162, in parse_video_metadata
    mediainfo_path = get_binary("mediainfo")
  File "c:\\bazarr\\bazarr\\utilities\\binaries.py", line 73, in get_binary
    raise BinaryNotFound
utilities.binaries.BinaryNotFound

**Comment by morpheus65535** [comment]
You selected mediainfo to analyse media files without having it installed and in your system path env variable.

**Comment by morpheus65535** [comment]
Could be easily solved in support channel BTW.
