### ISSUE TITLE
Mass Edit UI bug with only a few subtitles

### ISSUE THREAD

**Issue by NLZ** [morpheus65535/bazarr#2348]
**Describe the bug**
Trying to use Mass Edit with only few episodes won't show all the actions on the same screen, have to scroll inside the window.

**To Reproduce**
1. Pick a series with only a few subtitles
2. Click Mass Edit
3. Select some subs and click Select Action

**Expected behavior**
The whole Action list should be visible at the same time.

**Screenshots**
![image](https://github.com/morpheus65535/bazarr/assets/884277/c5870018-ef16-40d5-a2ce-b6710ecf4400)
![image](https://github.com/morpheus65535/bazarr/assets/884277/a64f5b96-25d8-4cbe-b131-ced77c3868a5)
![image](https://github.com/morpheus65535/bazarr/assets/884277/eb118876-162e-4c01-881f-cdc6807a745e)

**Software (please complete the following information):**
 - Bazarr: v1.4.0
 - Radarr version n/a
 - Sonarr version n/a
 - OS: Windows 10, Firefox 121.0

**Additional context**
n/a

**Comment by morpheus65535** [comment]
Should be fixed in nightly build.
