### ISSUE TITLE
Error getting releases from github

### ISSUE THREAD

**Issue by seannymurrs** [morpheus65535/bazarr#235]
I see the following error in my logs. 

BAZARR Error trying to get releases from Github. Connection Error.

**Comment by morpheus65535** [comment]
Please provide a complete log.

**Comment by seannymurrs** [comment]
23/11/2018 01:11:03|ERROR|BAZARR Error trying to get video information for this file: /Volumes/Media/Videos/Movies/Constantine City of Demons - The Movie (2018)/Constantine City of Demons - The Movie 2018 Remux-1080p.mkv|'Traceback (most recent call last):\n  File "/Applications/bazarr/bazarr/get_subtitle.py", line 51, in download_subtitle\n    video = Video.fromname(sceneName)\n  File "bazarr/../libs/subliminal/video.py", line 107, in fromname\n    return cls.fromguess(name, guessit(name))\n  File "bazarr/../libs/subliminal/video.py", line 93, in fromguess\n    return Episode.fromguess(name, guess)\n  File "bazarr/../libs/subliminal/video.py", line 170, in fromguess\n    raise ValueError(\'Insufficient data to process the guess\')\nValueError: Insufficient data to process the guess'|
23/11/2018 01:11:03|INFO|BAZARR Finished searching for missing subtitles. Check histories for more information.|
23/11/2018 04:00:03|INFO|BAZARR All existing episode subtitles indexed from disk.|
23/11/2018 04:00:03|INFO|BAZARR All missing episode subtitles updated in database.|
23/11/2018 04:10:57|INFO|BAZARR Updated to latest version. Restart required.  11 files changed, 88 insertions(+), 214 deletions(-)|
23/11/2018 04:11:03|ERROR|BAZARR Error trying to get video information for this file: /Volumes/Media/Videos/Movies/Constantine City of Demons - The Movie (2018)/Constantine City of Demons - The Movie 2018 Remux-1080p.mkv|'Traceback (most recent call last):\n  File "/Applications/bazarr/bazarr/get_subtitle.py", line 51, in download_subtitle\n    used_sceneName = True\n  File "bazarr/../libs/subliminal/video.py", line 107, in fromname\n    return cls.fromguess(name, guessit(name))\n  File "bazarr/../libs/subliminal/video.py", line 93, in fromguess\n    return Episode.fromguess(name, guess)\n  File "bazarr/../libs/subliminal/video.py", line 170, in fromguess\n    raise ValueError(\'Insufficient data to process the guess\')\nValueError: Insufficient data to process the guess'|
23/11/2018 04:11:03|INFO|BAZARR Finished searching for missing subtitles. Check histories for more information.|
23/11/2018 05:00:36|INFO|BAZARR All existing movie subtitles indexed from disk.|
23/11/2018 05:00:36|INFO|BAZARR All missing movie subtitles updated in database.|
23/11/2018 07:11:03|ERROR|BAZARR Error trying to get video information for this file: /Volumes/Media/Videos/Movies/Constantine City of Demons - The Movie (2018)/Constantine City of Demons - The Movie 2018 Remux-1080p.mkv|'Traceback (most recent call last):\n  File "/Applications/bazarr/bazarr/get_subtitle.py", line 51, in download_subtitle\n    used_sceneName = True\n  File "bazarr/../libs/subliminal/video.py", line 107, in fromname\n    return cls.fromguess(name, guessit(name))\n  File "bazarr/../libs/subliminal/video.py", line 93, in fromguess\n    return Episode.fromguess(name, guess)\n  File "bazarr/../libs/subliminal/video.py", line 170, in fromguess\n    raise ValueError(\'Insufficient data to process the guess\')\nValueError: Insufficient data to process the guess'|
23/11/2018 07:11:03|INFO|BAZARR Finished searching for missing subtitles. Check histories for more information.|
23/11/2018 07:45:51|INFO|Bazarr is being restarted...|
23/11/2018 07:45:53|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:6767/|
23/11/2018 07:46:48|INFO    |root                            |BAZARR Settings saved succesfully.|
23/11/2018 07:46:52|INFO    |root                            |Bazarr is being restarted...|
23/11/2018 07:46:54|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:5656/|
23/11/2018 07:51:53|ERROR   |root                            |BAZARR Error trying to get releases from Github. Connection Error.|'Traceback (most recent call last):\n  File "bazarr/main.py", line 1447, in system\n    r = requests.get(url_releases, timeout=15)\n  File "bazarr/../libs/requests/api.py", line 72, in get\n    return request(\'get\', url, params=params, **kwargs)\n  File "bazarr/../libs/requests/api.py", line 58, in request\n    return session.request(method=method, url=url, **kwargs)\n  File "bazarr/../libs/requests/sessions.py", line 512, in request\n    resp = self.send(prep, **send_kwargs)\n  File "bazarr/../libs/requests/sessions.py", line 622, in send\n    r = adapter.send(request, **kwargs)\n  File "bazarr/../libs/requests/adapters.py", line 511, in send\n    raise SSLError(e, request=request)\nSSLError: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases (Caused by SSLError(SSLError(1, u\'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)\'),))'|
23/11/2018 09:27:45|ERROR   |root                            |BAZARR Error trying to get video information for this file: /Volumes/Media/Videos/Movies/Constantine City of Demons - The Movie (2018)/Constantine City of Demons - The Movie 2018 Remux-1080p.mkv|'Traceback (most recent call last):\n  File "/Applications/bazarr/bazarr/get_subtitle.py", line 52, in download_subtitle\n    video = Video.fromname(sceneName)\n  File "bazarr/../libs/subliminal/video.py", line 107, in fromname\n    return cls.fromguess(name, guessit(name))\n  File "bazarr/../libs/subliminal/video.py", line 93, in fromguess\n    return Episode.fromguess(name, guess)\n  File "bazarr/../libs/subliminal/video.py", line 170, in fromguess\n    raise ValueError(\'Insufficient data to process the guess\')\nValueError: Insufficient data to process the guess'|
23/11/2018 09:27:45|INFO    |root                            |BAZARR Finished searching for missing subtitles. Check histories for more information.|
23/11/2018 10:47:33|ERROR   |root                            |BAZARR Error trying to get video information for this file: /Volumes/Media/Videos/Movies/Constantine City of Demons - The Movie (2018)/Constantine City of Demons - The Movie 2018 Remux-1080p.mkv|'Traceback (most recent call last):\n  File "/Applications/bazarr/bazarr/get_subtitle.py", line 52, in download_subtitle\n    video = Video.fromname(sceneName)\n  File "bazarr/../libs/subliminal/video.py", line 107, in fromname\n    return cls.fromguess(name, guessit(name))\n  File "bazarr/../libs/subliminal/video.py", line 93, in fromguess\n    return Episode.fromguess(name, guess)\n  File "bazarr/../libs/subliminal/video.py", line 170, in fromguess\n    raise ValueError(\'Insufficient data to process the guess\')\nValueError: Insufficient data to process the guess'|
23/11/2018 10:47:33|INFO    |root                            |BAZARR Finished searching for missing subtitles. Check histories for more information.|
23/11/2018 11:18:29|ERROR   |root                            |BAZARR Error trying to get releases from Github. Connection Error.|'Traceback (most recent call last):\n  File "bazarr/main.py", line 1447, in system\n    r = requests.get(url_releases, timeout=15)\n  File "bazarr/../libs/requests/api.py", line 72, in get\n    return request(\'get\', url, params=params, **kwargs)\n  File "bazarr/../libs/requests/api.py", line 58, in request\n    return session.request(method=method, url=url, **kwargs)\n  File "bazarr/../libs/requests/sessions.py", line 512, in request\n    resp = self.send(prep, **send_kwargs)\n  File "bazarr/../libs/requests/sessions.py", line 622, in send\n    r = adapter.send(request, **kwargs)\n  File "bazarr/../libs/requests/adapters.py", line 511, in send\n    raise SSLError(e, request=request)\nSSLError: HTTPSConnectionPool(host=\'api.github.com\', port=443): Max retries exceeded with url: /repos/morpheus65535/Bazarr/releases (Caused by SSLError(SSLError(1, u\'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)\'),))'|

**Comment by seannymurrs** [comment]
I installed OpenSSL via home brew, but am still getting the error. My guess, from looking around online, is that I now have two versions of OpenSSL installed, and things are still pointing towards the old one. Not sure how to switch.

**Comment by morpheus65535** [comment]
Maybe this: https://discourse.roots.io/t/github-and-new-cryptographic-standard/11701/8

**Comment by seannymurrs** [comment]
I followed a few different guides, and I’m relatively sure OpenSSL has been updated, but I’m still getting the error.

**Comment by morpheus65535** [comment]
I don't have a Mac to test it out but I can assure you that updating work well under Windows and Linux. This is clearly something related to your environment.

**Comment by seannymurrs** [comment]
Hmm, not really sure what to do then.

**Comment by morpheus65535** [comment]
Maybe try this instead: `brew install --force openssl`

The thing is that you need to be sure you've updated your OpenSSL and that you are running Bazarr with your brew python binary, not the one from macOS.

There's nothing more I can do on my side than give you those hint. The python binary used to run Bazarr use an old version of OpenSSL that do not support the minimal version of TLS required by Github.

**Comment by seannymurrs** [comment]
Figured it out eventually. Had to update pip, then install pyopenssl via pip. That seemed to fix things.

**Comment by morpheus65535** [comment]
Ok, thank you for reporting it! Maybe it will help someone else one day. :-)
