### ISSUE TITLE
aRGENTeaM provider shutdown

### ISSUE THREAD

**Issue by jcastilloalonso** [morpheus65535/bazarr#2352]
**Describe the bug**
aRGENTeaM provider decided to shutdown starting Jan 1st 2024. https://argenteam.net/ has the shutdown notice and Bazarr is failing to download subtitles.

**To Reproduce**
N/A

**Expected behavior**
Remove the provider from the list or add a notice that it has shutdown and is not working.

**Screenshots**
N/A

**Software (please complete the following information):**
 - Bazarr: v1.4.1-beta.13 and earlier

**Additional context**
N/A

**Comment by morpheus65535** [comment]
Provider removed in upcoming beta. Thanks for reporting!
