### ISSUE TITLE
Provider zimuku domain update

### ISSUE THREAD

**Issue by milktoffee** [morpheus65535/bazarr#2355]
I found an error in the log:
`HTTPSConnectionPool(host='so.zimuku.org', port=443): Max retries exceeded with url: /search?q=Billions.S05 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1006)'))), retrying in 5 seconds...`

Provider zimuku changed their main domain name to **srtku.com**, I would like you to update this.

 - Bazarr: [v 1.4.0]

**Comment by morpheus65535** [comment]
Already fixed in 1.4.4-beta.
