### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by Tarek-Hasan** [morpheus65535/bazarr#2365]
Sorry to bother you.
I tried to find info on Bazarr's cli interface, but couldn't find any. I was planning to make a modified version of Bazarr to use with media players like, MPC-BE and MPC-HC etc.

**Comment by morpheus65535** [comment]
What do you mean? The arguments that can be used when you start Bazarr?

**Comment by Tarek-Hasan** [comment]
I'm referring to, using command line to search and download subtitle instead of using GUI.

**Comment by morpheus65535** [comment]
There's nothing like this in Bazarr. You can use the API to reproduce the GUI behaviour. The API doc is referred in System-->Status in the link at the bottom.

**Comment by morpheus65535** [comment]
> OK Thanks, API will do. But why not add API Doc to github or wiki? Google search also ended with no results. Why make it so complicate to find!! People before me also got into this situation like, #741. I had to go through all the hassle of setup bazarr on windows just get the list of API call. Please, for the love of people's sanity, add API Doc to a wiki.

The issue you're referring to was reported at a time where the API was undocumented and reserved to Bazarr GUI. As the API is documented in the code and evolve from one Bazarr version to another, we keep the doc packaged with Bazarr so you always get the last changes. This wont change.
