### ISSUE TITLE
Language Profile - Must contain - Not working in automatic search

### ISSUE THREAD

**Issue by EmilianoNeme** [morpheus65535/bazarr#2379]
**Bug / Steps to Reproduce**
When manually searching for a single subtitle in a show's episode list, and the show has a language profile with a "must contain - word" assigned, Bazarr properly displays only subtitles that match that criteria, however when doing automatic searches / mass searching for subs in the "Wanted" section, Bazarr ignores the specific word and instead downloads the highest rated sub.

**Expected behavior**
Bazarr should download only subs that match the specified word.

**Software:**
 - Bazarr: [v1.4.1 - Master]
 - Radarr version [5.2.6.8376-ls197 by [linuxserver.io](https://linuxserver.io/)]
 - Sonarr version [3.0.10.1567-ls218 by [linuxserver.io](https://linuxserver.io/)]
 - OS: [macOS Sonoma 14.2.1 - Docker 4.27.1]

**Additional context**
I know this is what is happening, because I checked the score - in the history section - for the subtitles downloaded manually vs the score of the automatically downloaded subs, and they differ, being the last ones the highest rated one. However I require the use of the specific word, because it retrieves good subs - The top rated ones have some bugs in this case.

**Comment by morpheus65535** [comment]
Will be fixed in upcoming beta. Thanks for reporting!
