### ISSUE TITLE
Bazarr isn’t detecting subtitles?

### ISSUE THREAD

**Issue by seannymurrs** [morpheus65535/bazarr#238]
I recently re-did my sonarr, radarr, bazarr setup using all Docker containers. Everything seemed to work ok, except bazarr isn’t detecting any of my current subtitle files. I’m using the same media library as before, so nothing’s changed in the actual files themselves. For some reason, bazarr is showing all my shows and movies are missing subtitles, even though a good majority of them have either embedded subtitles or srt files in the same folder as the movie itself.

I didn’t have this issue previously on my Mac (before using Docker). Is there some setting or configuration I’m missing?

**Comment by seannymurrs** [comment]
> Could you provide screenshots for settings? Do you have checkmark ls alongside your series and movies path?

Attached are screenshots of my settings pages and series/movie pages. When I go into a specific movie that I know has a srt file, it says "No subtitles detected for this movie." Also, if I try and search for subtitles, it doesn't seem to actually do anything either.

![img_2038](https://user-images.githubusercontent.com/6283769/49083126-bb94de80-f219-11e8-99cd-6f538ede2fb9.jpg)
![img_2037](https://user-images.githubusercontent.com/6283769/49083127-bb94de80-f219-11e8-84bb-c1b5e5bd65f1.jpg)
![img_2036](https://user-images.githubusercontent.com/6283769/49083128-bb94de80-f219-11e8-8afd-26b6c2e5bc8c.jpg)
![img_2033](https://user-images.githubusercontent.com/6283769/49083129-bc2d7500-f219-11e8-9bd7-18f8d0068aca.jpg)

**Comment by morpheus65535** [comment]
Everything seems to be alright. Could you provide a debug log?

**Comment by seannymurrs** [comment]
> Everything seems to be alright. Could you provide a debug log?

Sure thing. Attached is a PDF of my log output.
[bazarr.pdf](https://github.com/morpheus65535/bazarr/files/2620249/bazarr.pdf)

**Comment by morpheus65535** [comment]
Could you please provide it in a text file like bazarr.log? You have a download button for log file in System-->Log

**Comment by seannymurrs** [comment]
Sorry about that. The download button wasn't working on my iPhone. Attached is the log in .log format.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/2621356/bazarr.log)

**Comment by seannymurrs** [comment]
Just a quick update. I thought maybe the issue could be resolved by nuking my bazarr, sonarr, and radarr containers and building them from scratch again. Thanks to Docker, that doesn’t take too much time. Unfortunately, I’m having the exact same issue. Bazarr is finding all my movies and shows just fine, but it’s not detecting any of the subtitle files already there.

**Comment by morpheus65535** [comment]
I see a lot of found subtitles in your log file. Have you been through it and look at those series/movies to be sure they are not listed here?

**Comment by seannymurrs** [comment]
Yes. See the attached screenshot for an example. The logs show the art file was found, but it’s still showing as missing. 
![c51662a7-ff54-4093-ab79-fbcfd77a7a30](https://user-images.githubusercontent.com/6283769/49262322-e8144a80-f413-11e8-806e-481b0af8c2d1.jpeg)

**Comment by Dragao75** [comment]
Maybe interesting: 
So I removed all my existing subs for Serie 'The 100' and let bazarr search them. 
Bazarr finds subs and downloaded them. 

But still it reports that the serie has no subtitles.. (does this take a while?)
<img width="1080" alt="screen shot 2018-12-01 at 11 36 51" src="https://user-images.githubusercontent.com/19911558/49327149-af808800-f55d-11e8-9b73-17b462cf82da.png">
<img width="1111" alt="screen shot 2018-12-01 at 11 39 10" src="https://user-images.githubusercontent.com/19911558/49327154-c0c99480-f55d-11e8-8f96-42e040c81579.png">


hmm (see screenshots)

**Comment by halali** [comment]
You havent issue? You just have bad encoded subtitles.

**Comment by Dragao75** [comment]
> You havent issue? You just have bad encoded subtitles.

You might think that. But the Most of the subs that are there have been downloaded by Bazarr in the past.  So if they are in deed bad.. Why does Bazarr download bad subs.. As I do not think Bazarr does download bad subs it must be something else.

**Comment by morpheus65535** [comment]
Please provide some of the subtitles file in a zip file and I'll try to see what's the issue. Also, give us some information about your operating system.

**Comment by morpheus65535** [comment]
@Dragao75 Please come to Discord for support. WE're going to need a debug log and maybe a copy of your bazarr.db.

**Comment by Dragao75** [comment]
Please tell me how to go to discord. Never use discord before.

**Comment by halali** [comment]
https://discordapp.com/invite/MH2e2eb

**Comment by morpheus65535** [comment]
After some discussion, it seems to be resolved.

**Comment by pcdevil** [comment]
Hello,
I think I have the same / very similar issue:
- Bazarr shows missing subtitles
- Clicking on the download button will result to get all missing subtitles (it will be in the folder)
- Debug logs have a `BAZARR storing those languages to DB: [['hu', u'/tv/Game of Thrones/s08e03.srt']]` line
- I am using LSIO's Docker image behind a NGINX reverse-proxy
- As I inspected the bazarr.db file I see the corresponding row's `subtitles` field is empty and the `missing_subtitles` field still has the `'hu'` value
- There is no sign of error in the logs

Can you help me @morpheus65535, what was the conclusion on the other's issue?

(PS: didn't wanted to open other issue since they are kind of related, but doing it if you think it would be better)

**Comment by morpheus65535** [comment]
@pcdevil If you click on Scan filesystem button for that show, does it store the new subtitle in DB or not at all?

**Comment by pcdevil** [comment]
Not at all :(

This is the same for every tv show (and I don't use it for movies).

**Comment by morpheus65535** [comment]
I suggest you come to Discord and we'll see how we can help you fix this issue. Thanks.

**Comment by eyalgindi** [comment]
The same issue on my system, subs are being downloaded by Bazarr but yet after scan still show as missing.

**Comment by pcdevil** [comment]
Hey @eyalgindi,
For me it was a mapping issue. In the **System - General** submenu the **Path Mappings for shows** had a `/tv/ -> /tv/` mapping. You have to omit mappings with the same source and destination directory. This is a known issue and [warned in the Wiki too to avoid it](https://github.com/morpheus65535/bazarr/wiki/Settings-General#path-mappings-for-shows).

Examine your config and look for this settings to see whether you have this setup or not. If not I recommend to log in to Discord, after a general troubleshooting they were very kind to help me too and solved the issue in matter of minutes!

**Comment by morpheus65535** [comment]
This could also be related to #461.

**Comment by eyalgindi** [comment]
@pcdevil 
This just did it.
Thanks a lot!

@morpheus65535 
Thanks,
I'm running docker on PC (Ubuntu 18.04)
