### ISSUE TITLE
Inconsistent hearing impaired/non-hearing impaired flagging

### ISSUE THREAD

**Issue by lawadr** [morpheus65535/bazarr#2386]
**Describe the bug**
When a subtitle is downloaded that is tagged as non-hearing impaired, but is scanned as hearing impaired, it is flagged as hearing impaired in Bazarr while saved without the "sdh" or "hi" in the file name. On rescan, it is re-flagged as non-hearing impaired in Bazarr.

**To Reproduce**
- Find a subtitle that is flagged by the provider as non-hearing impaired but is detected as hearing impaired by Bazarr
- Download the subtitle via a search or manual download
- Notice that Bazarr detects it as `<LANGUAGE> HI`
- Click "Scan Disk" and notice it getting changed to `<LANGUAGE>`

**Expected behavior**
Either it gets flagged as `<LANGUAGE>` and stays as `<LANGUAGE>` after a re-scan, or it gets saved with "sdh" or "hi" in the filename and continuously gets detected as `<LANGUAGE> HI` every re-scan.

**Software (please complete the following information):**
 - Bazarr: v1.4.1

**Comment by lawadr** [comment]
It looks like the subtitle is saved to file based on what the provider thinks the language is. If it thinks it's English but not hearing impaired it'll get saved as `*.en.srt` for example

After that, `guess_external_subtitles` is called which reads the file and finds it to be hearing impaired. It is then saved to the database as being hearing impaired.

On re-scan, the language of an external subtitle is initially set based on its filename, which in this case is English non-hearing impaired as it's still just `*.en.srt`.

When `guess_external_subtitles` is called again, it does not read the file to change the language to hearing impaired because of the `previously_indexed_subtitles_to_exclude` argument. This makes it forever treated as non-hearing impaired.

**Comment by morpheus65535** [comment]
Yeah, I've been aware of that for a while but, probably out of laziness, I never fixed it.

I think that, while downloading a subtitles file, we should always validate if it's HI or not. The file should be named accordingly, not using the language known by the provider. guess_external_subtitles should then return the same value on each execution. Make sense?

**Comment by morpheus65535** [comment]
This should be fixed in upcoming beta. Keep me informed if it's as expected.
