### ISSUE TITLE
cant download subtitles

### ISSUE THREAD

**Issue by jauzin23** [morpheus65535/bazarr#2389]
**Describe the bug**
cant download any subtitles and get the following error when manually installing: 
![image](https://github.com/morpheus65535/bazarr/assets/91629535/0149e877-85d8-4209-9550-3f622f72d868)
i always get hash error and video or audio codec

**Comment by morpheus65535** [comment]
It's not an error and this isn't the proper place to get support. Come to our Discord support channel.

**Comment by casodb** [comment]
I see its closed any fix for the issue?

**Comment by morpheus65535** [comment]
> I see its closed any fix for the issue?

There's no issue, it's simply that those criteria doesn't match between video and subtitles. The score is calculated based on that. There's nothing to fix.
