### ISSUE TITLE
Exception on /api/movies [PATCH] (docker, Ubuntu)

### ISSUE THREAD

**Issue by goshpolly** [morpheus65535/bazarr#2390]
First time user, so forgive me if I'm being stupid. I've run through the wiki and set up everything as suggested that I can see. Indexing from radarr and sonarr succeeded, and I've set up opensubtitles.com with a valid username (not email) and password which has status "Good".  But every time I do a manual "Search" on a series or movie it throws an error 500, immediately disconnecting from the server, and logs reports:

Exception on /api/series [PATCH]

**To Reproduce**
1. Go to any series/movie
2. Click on 'Search'
3. Look bottom right

**Expected behavior**
Should correctly contact the provider and search for subtitles.

**Software (please complete the following information):**
 - Bazarr: v1.4.2-beta.2 (default installed by docker)
 - Radarr version 5.2.6.8376
 - Sonarr version 4.0.0.748
 - OS: Ubuntu 22.04

**Additional context**
Trace:

Traceback (most recent call last):
  File "/app/bin/bazarr/subtitles/pool.py", line 85, in decorated
    profile_id = kwargs["profile_id"]
                 ~~~~~~^^^^^^^^^^^^^^
KeyError: \'profile_id\'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/bin/bazarr/../libs/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/../libs/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/../libs/flask_restx/api.py", line 405, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/../libs/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/../libs/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/api/utils.py", line 30, in wrapper
    return actual_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/api/series/series.py", line 212, in patch
    series_download_subtitles(seriesid)
  File "/app/bin/bazarr/subtitles/mass_download/series.py", line 84, in series_download_subtitles
    for result in generate_subtitles(path_mappings.path_replace(episode.path),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/subtitles/pool.py", line 87, in decorated
    profile_id = args[args_spec.index("profile_id")]
                 ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: tuple index out of range

**Comment by morpheus65535** [comment]
This has been fixed post beta.2 but the release pipeline is broken. I'll fix that ASAP. Thanks!

**Comment by goshpolly** [comment]
Oh thank you! I take there's no easy way to deploy the fix now into a docker compose install? If not, no worries, I'll be patient.

**Comment by morpheus65535** [comment]
No, no easy way.

**Comment by morpheus65535** [comment]
Should be fixed in beta.4
