### ISSUE TITLE
Problem with PT-PT subtitles

### ISSUE THREAD

**Issue by alexkiddddd** [morpheus65535/bazarr#2396]
**Describe the bug**
my bazarr has stopped downloading PT-PT subtitles, I have configured PT-PT and PT-BR subtitles and when I do a manual search the only results are from PT-BR subs, if I remove PT-BR from languages the search results are always empty. I have checked the provider and everythings seems ok because it gives me PT-BR subs, it seems it is hiding the PT-PT ones.

**To Reproduce**
Add a profile with portuguese and brazilian portuguese language
Go to a movie and do a manual check, only brazilian portuguese subtitles are shown

**Expected behavior**
It was expected to show portuguese subtitles and brazilian portuguese subs.

**Software (please complete the following information):**
 - Bazarr: [1.4.1]
 - OS: [QNAP Docker]

**Comment by morpheus65535** [comment]
Duplicate #2380
