### ISSUE TITLE
Edit tools change ASS subtitle's content to SRT format without change file extension.

### ISSUE THREAD

**Issue by boydaihungst** [morpheus65535/bazarr#2399]
**Describe the bug**
When I use tools, in the image below, the content of the subtitle will convert from ASS to SRT format, but the file extension is still the same (.ass).

**To Reproduce**
1. Go to `movie/tv shows page`
2. Hover over the `subtitle button`, which is an external ASS subtitle.
3. After tools panel is shown up, click on any button in the `tools` section
4. After the subtitle editing job is done, check the subtitle's content using any file explorer. The content is convert to SRT format, and the file extension is still `.ass`

**Expected behavior**
Keep `.ass` file extension and the content should be in `ASS` format with changed content. If it's not possible, then change file extension to srt or asking user to save to `srt` file before processing.

**Screenshots**
![image](https://github.com/morpheus65535/bazarr/assets/38396158/8c3e7b48-6a24-466c-8303-a5df833ee2d0)

**Software (please complete the following information):**
 - Bazarr: 1.4.1
 - Radarr version: 4.0.1.929
 - Sonarr version: 5.3.6.8612
 - OS: Linux-6.2.0-39-generic-x86_64-with-glibc2.37 (Ubuntu server 23.04)

**Additional context**
Before `Adjust times`
![image](https://github.com/morpheus65535/bazarr/assets/38396158/cf0858cd-f57d-49e5-8881-b0e6f0c1af9c)
After `Adjust times`
![image](https://github.com/morpheus65535/bazarr/assets/38396158/9affbc22-4019-451f-8984-09a52f04fd3d)

My configuration file (Removed sensitive infomation)
https://pastebin.com/RMrFnz6Y

Logs file: 
[bazarr.log](https://github.com/morpheus65535/bazarr/files/14326422/bazarr.log)

**Comment by JaiZed** [comment]
We can make your desired behaviour happen:
`Keep .ass file extension and the content should be in ASS format with changed content. `

However, note that after the ffmpeg tool does its thing, the text of the ASS file will be preserved and corrections made, but it looks like it may lose some of the fancier annotations along the way. Is that going to be acceptable to most ASS subtitle users?

**Comment by boydaihungst** [comment]
Actually, I would love to have a preview window like git diff. But I know that would be a lot of work. So maybe showing a warning to the user before processing is ok.

**Comment by JaiZed** [comment]
`So maybe showing a warning to the user before processing is ok.`
Well, who knows what many of these tools will do to the original subtitles.
It’s best to always have a backup or to be able to easily download another copy.
