### ISSUE TITLE
Run bazarr as a service

### ISSUE THREAD

**Issue by Julien-D** [morpheus65535/bazarr#24]
Hi,
I'd like to run Bazarr as a service (daemon) in Linux. It would allow me to automatically start Bazarr at startup.
How could I do that?
Thanks in advance
Julien

**Comment by Julien-D** [comment]
I managed to do it (at least for Debian).
The step-by-step is as follow (considering bazarr is in /home/nzbdrone/bazarr):
`sudo nano /etc/systemd/system/ bazarr.service
`
Then paste:
```
[Unit]
Description=Bazarr

[Service]
User=nzbdrone
ExecStart=/usr/bin/python /home/nzbdrone/bazarr/bazarr.py

[Install]
WantedBy=multi-user.target
```
Then run
```
sudo systemctl --system daemon-reload
sudo systemctl enable bazarr
```
That's it!

I guess it could help people if this would be added to the README file

PS: great script!

**Comment by morpheus65535** [comment]
Thanks, I'm planning to build a wiki where all this could find it place.
