### ISSUE TITLE
Error - mk3d is not a valid file-format, maybe search crashes?

### ISSUE THREAD

**Issue by smathev** [morpheus65535/bazarr#240]
**Describe the bug**
Bazarr has trouble when a file is in an unrecognized format, for instance .mk3d seems to cause it to bug out.

**To Reproduce**
Create (or have) a movie-file with the extension .mk3d and have Bazarr scan that folder. The error should be in the logs after the scan:

```
|ERROR|BAZARR Error trying to get video information for this file: ("MOVIENAME").mk3d|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/get_subtitle.py", line 48, in download_subtitle\n    video = scan_video(path)\n  File "/app/bazarr/bazarr/../libs/subliminal/core.py", line 424, in scan_video\n    raise ValueError(\'%r is not a valid video extension\' % os.path.splitext(path)[1])\nValueError: u\'.mk3d\' is not a valid video extension'|
```

**Expected behavior**
Bazarr should get subtitles for the file, since it is a video-file, albeit in Stereoscopic 3d.

**Software (please complete the following information):**
 - Bazarr: v0.6.7.1
 - Radarr version: 0.2.0.1217
 - Sonarr version: 2.0.0.5252
 - OS: Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-34-generic x86_64)

**Additional context**
I'm not sure if Bazarr abandons the subtitle search after an .mk3d-file or if it finishes its search. The fact that the bug is classified as an error in the code leads me to believe that Bazarr crashes its search. If it is simply a warning that mk3d is not a valid file-format, I should think that the bug/log-issue should be classified as a warning.

Thanks in advance.

**Comment by morpheus65535** [comment]
We rely on Subliminal to detect external subtitles and it does support mk3d container. Nothing I can do about it. I sure don't want to start developing my own video file analyzing library. ;-)

**Comment by smathev** [comment]
Ok, I have forwarded the issue to Subliminal for additional support, the weird thing is that it seems to break Bazarr, as it always finishes at that file.

I still have 1050 files which need subtitles, and Sub-Zero (the Plex-plugin) is able to find a lot more subtitles then Bazarr at the moment, so I think it might be because the error presented above is causing Bazarr to end its search.

I know Bazarr is early in its development, and I would love to help in anyway I can, so don't see this as complaints. This is merely additional information, in the hopes of furthering the development. Let me know if there is anything I can do to help with the development.
