### ISSUE TITLE
Subtitle's content is messed up while watching in Jellyfin and uploading new file.

### ISSUE THREAD

**Issue by boydaihungst** [morpheus65535/bazarr#2400]
**Describe the bug**
Subtitle's content is messed up while watching in Jellyfin and then upload with new file, even after deleted old subtitle and reupload or close Jellyfin and reupload. The content after uploading is kinda like a binary file. 

**To Reproduce**
1. Go to "Jellyfin website"
3. Click on "Play movie A with the external subtitle'
4. Wait until the movie is playing, then go to the movie page in bazarr website
5. Click on "Upload" button
6. Upload any "srt/ass" subtitle.
7. After uploaded successfully, check the file content with any file explorer.

**Expected behavior**
The new subtitle should have correct content with the file was uploaded.

**Screenshots**
The file before uploading (the file I uploaded has `.srt` extension, this `bak` file is a backup)
![image](https://github.com/morpheus65535/bazarr/assets/38396158/c185f825-2c61-4991-b5ef-81cc2cd80657)
The file after uploading
![image](https://github.com/morpheus65535/bazarr/assets/38396158/3d3b8fac-9776-4753-94ab-dd723aaa4cd8)

**Software (please complete the following information):**
 - Bazarr: 1.4.1
 - Radarr version: 4.0.1.929
 - Sonarr version: 5.3.6.8612
 - OS: Linux-6.2.0-39-generic-x86_64-with-glibc2.37 (Ubuntu server 23.04)

**Additional context**
In Jellyfin I was using this config, normally it doesn't watch subtitle files. 
![image](https://github.com/morpheus65535/bazarr/assets/38396158/2b97d48e-acc6-4664-8302-efcc09162ef0)

Folder's permissons
![image](https://github.com/morpheus65535/bazarr/assets/38396158/4344e3de-c6d3-442b-b3b3-411e050f56ee)

My configuration file (Removed sensitive infomation)
https://pastebin.com/RMrFnz6Y

My bazarr logs: 
[bazarr.log](https://github.com/morpheus65535/bazarr/files/14326334/bazarr.log)

**Comment by JaiZed** [comment]
Can you attach a copy of the file before uploading?

**Comment by boydaihungst** [comment]
Of course. Please rename it to `.srt`, github doesn't allow me to upload a `.srt` file 
[Mr. and Mrs. Smith (2005).vi.txt](https://github.com/morpheus65535/bazarr/files/14354051/Mr.and.Mrs.Smith.2005.vi.txt)

**Comment by boydaihungst** [comment]
I disabled `Encode Subtitles To UTF8` because I thought this bug would happen #2399. Looks like it doesn't affect at all. Thanks for helping me.
