### ISSUE TITLE
Bazarr doesn't run after a reboot

### ISSUE THREAD

**Issue by ElEmFurt** [morpheus65535/bazarr#2401]
**Describe the bug**
I am getting a site cannot be reached error when running Bazarr after a reboot. I have reinstalled Bazarr 5-6 times backing up my config and then copy-pasting keys back to get it to run. I have tried restarting the service and it doesn't work, until I delete the existing config. If I try to restore the older config (either copy pasting via a merge tool or just plain replacing the new config with the old one), it doesn't run. I have to do everything from scratch in the new config for it to run. This is a pain to setup, especially when Bazarr runs perfectly until I reboot/shutdown my PC.

**Screenshots**
![image](https://github.com/morpheus65535/bazarr/assets/73025802/0fc1f1dc-06e7-412c-b199-dc7d60bc3657)

**Software (please complete the following information):**
 - Bazarr: [e.g. v 0.6.1]
 - Radarr version [e.g. v 0.2.0.0001]
 - Sonarr version [e.g. v 2.0.0.0001]
 - OS: [e.g. Windows 10]

**Additional context**
I checked the log file and all I see is this:

> 2024-02-20 22:01:42|INFO    |root                            |Bazarr is being restarted...|
> 2024-02-20 22:01:57|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
> 2024-02-20 22:01:57|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
> 2024-02-20 22:01:57|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
> 2024-02-20 22:01:57|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
> 2024-02-20 22:01:57|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
> 2024-02-20 22:02:02|INFO    |root                            |Using opensubtitlescom again after 24 hours, (disabled because: DownloadLimitExceeded)|
> 2024-02-20 22:02:47|WARNING |apprise                         |Failed to deliver payload to PushBullet:Unauthorized - Invalid Token., error=401.|
> 2024-02-20 22:10:50|WARNING |retry.api                       |('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')), retrying in 5 seconds...|
> 2024-02-20 22:10:58|WARNING |apprise                         |Failed to deliver payload to PushBullet:Unauthorized - Invalid Token., error=401.|
> 2024-02-20 22:11:34|WARNING |apprise                         |Failed to deliver payload to PushBullet:Unauthorized - Invalid Token., error=401.|
> 2024-02-20 22:21:53|ERROR   |root                            |BAZARR SignalR client for Radarr connection as been lost. Trying to reconnect...|
> 2024-02-20 22:23:21|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
> 2024-02-20 22:26:29|WARNING |retry.api                       |('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')), retrying in 5 seconds...|
> 2024-02-20 22:26:29|WARNING |retry.api                       |('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')), retrying in 5 seconds...|
> 2024-02-20 22:26:29|WARNING |retry.api                       |('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')), retrying in 5 seconds...|
> 2024-02-20 22:26:35|WARNING |retry.api                       |('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')), retrying in 5 seconds...|
> 2024-02-20 22:27:06|WARNING |retry.api                       |('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')), retrying in 5 seconds...|
> 2024-02-20 22:27:14|WARNING |apprise                         |Failed to deliver payload to PushBullet:Unauthorized - Invalid Token., error=401.|

Both Radarr and Sonarr are working properly on their resp. ports and no errors in connecting to them. **What am I missing here?**

**Comment by hnorgaar** [comment]
Bazarr version 0.6.1 is 4 years old, get latest version and see if it fixes it

**Comment by morpheus65535** [comment]
@hnorgaar he simply didn't fill the versions part and left default values of the form.

@ElEmFurt what did you put in Settings-->General as listening address?

![image](https://github.com/morpheus65535/bazarr/assets/5130500/64d7b4a7-9ca9-4122-945f-9cbde33f798b)

**Comment by ElEmFurt** [comment]
My bad, I forgot to update the version numbers for the various apps, my first time here reporting a bug on Bazarr.

Here they are:
**Software:**

**Bazarr** version [1.4.2] - did a fresh download and reinstall after reading your replies (just to ensure I have the latest).
**Radarr** version [**5.3.6.8612 — Feb 18 2024**]
**Sonarr** version [**3.0.10.1567 — Mar 13 2023**] - not the latest (updated it now to **4.0.1.929 — Jan 20 2024**)
**OS**: [**Windows 10 Pro - O.S. Build 19045.3570**]

I am baffled at why Sonarr is outdated, coz I assumed that the auto-update would take care of it, didn't know there was a newer beta for Sonarr, updated the version of this manually on my setup.

Also I filled in 192.168.0.2 in my listening IP (same as my desktop) and 6767 as the port, didn't change that.

After reinstalling Bazarr, it's down again - and I see this in the logs.

> 2024-02-21 23:38:07|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
> 2024-02-21 23:38:07|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
> 2024-02-21 23:38:07|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
> 2024-02-21 23:38:07|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
> 2024-02-21 23:38:07|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|

**Comment by ElEmFurt** [comment]
Forgot to add, I tried restoring from backup and even that failed.

**Step 1** - after deleting the current config file and restarting the service. I went to the backup page.
![image](https://github.com/morpheus65535/bazarr/assets/73025802/63923cd7-4952-4271-9a57-379a3253be89)

Step 2 - I clicked the restore button and got this notification.
![image](https://github.com/morpheus65535/bazarr/assets/73025802/9d0485a0-7f5e-4259-8c09-d9d0536cc9a9)
![image](https://github.com/morpheus65535/bazarr/assets/73025802/ceaf4416-92db-4129-b452-5e3bd9794455)
![image](https://github.com/morpheus65535/bazarr/assets/73025802/b53f22da-21f5-44e5-bdde-6a795e8f698e)

Step 3 - after a manual refresh, back to square one, that the page doesn't work with a backup of any sort.
![image](https://github.com/morpheus65535/bazarr/assets/73025802/e742350d-f9ab-4502-86ff-729a3dc16461)

**Comment by JaiZed** [comment]
Try the simplest possible case.
Delete your configuration again and start Bazarr successfully.
After it’s up and running, don’t add any new configuration, just try the Restart menu from within Bazarr. It should restart within a few seconds.
Then try and restart it again from the menu.
If that works for a few times, simply shut down your computer and restart it.
Does Bazarr now come up after your computer restarts with no configuration?

**Comment by hnorgaar** [comment]
Do not change listening/host IP, keep it as 0.0.0.0

**Comment by ElEmFurt** [comment]
> change listening/host IP, keep it as 0.0.0.0. So either install again or edit your config.yaml file with this change

I followed the suggestions by @hnorgaar and @JaiZed  and changing the IP to 0.0.0.0 worked and it now works with a restart be it, a machine restart, service restart or app restart. It is odd though that the application doesn't work when using a local address, especially one on which it has been installed.

Thanks everyone for helping out with this. I will monitor the application and report back incase I find anything.

**Comment by morpheus65535** [comment]
My guess would be that the Bazarr service start before the network stack is fully configured. The web server isn't able to bind to that IP so it fails and stay like that.
