### ISSUE TITLE
Subdivx provider raises JSONDecodeError when searching for subtitles

### ISSUE THREAD

**Issue by avraham** [morpheus65535/bazarr#2406]
**Describe the bug**
Subdivx provider raises JSONDecodeError when searching for subtitles.
This started to happen yesterday.

**To Reproduce**
1. Go to a movie and manually search for subtitles.
2. No subtitles are found and there are error messages in the logs. This happen regardless if there are subtitles in the website or not.

**log files**
[bazarr.log](https://github.com/morpheus65535/bazarr/files/14389200/bazarr.log)
[bazarr (1).log](https://github.com/morpheus65535/bazarr/files/14389201/bazarr.1.log)

Software (please complete the following information):

Bazarr: 1.4.2  package: v1.4.2-ls239 by linuxserver.io
Radarr version 5.2.6.8376

**Comment by vitiko98** [comment]
This was fixed with one of the latest commits. Can you update and try reproducing the issue?

**Comment by avraham** [comment]
Yes. It's fixed in v1.4.3-beta.2.
Thank you.
