### ISSUE TITLE
Problem with yifysubtitles links

### ISSUE THREAD

**Issue by mat926** [morpheus65535/bazarr#2409]
**Describe the bug**
There's a linking issue with Yify subtitles where it's not pointing to the actual yify domain. 

**To Reproduce**
1. Go to manual search for any movie
2. Hover over yifysubtitles link. 
3. Observe URL location on bottom left points to local IP
4. Click on the yifysubtitles link

**Expected behavior**
It should direct link me to the actual yify subtitle page. 

**Screenshots**
![image](https://github.com/morpheus65535/bazarr/assets/46114199/528b64c9-7508-40bf-b023-a7620737a4ae)

![image](https://github.com/morpheus65535/bazarr/assets/46114199/157b3ffa-acd8-41aa-9db5-567ef6797c78)

**Software (please complete the following information):**
 - Bazarr: 1.4.1
 - Radarr version 5.2.6.8376
 - Sonarr version 4.0.1.929
 - OS: Synology DM 7.2

**Comment by JaiZed** [comment]
Fixed in v1.4.3-beta.3
