### ISSUE TITLE
Blank white page after login

### ISSUE THREAD

**Issue by Blisk** [morpheus65535/bazarr#2410]
**Describe the bug**

When I login I get blank white page
**To Reproduce**
open web UI
type username and password
and get white blank page

**Expected behavior**
I should get bazarr page

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 1.4.1.0
 - Radarr version 5.3.4
 - Sonarr version 4.0.1
 - OS: qnap

**Additional context**

**Comment by morpheus65535** [comment]
It could be the effect of an improperly configured reverse proxy or some security tools.

Anyway, please get back to Discord support channel as you've started earlier. This board is for confirmed bug tracking.
