### ISSUE TITLE
Sync settings changes aren't being applied without restarting Bazarr

### ISSUE THREAD

**Issue by dnsv504** [morpheus65535/bazarr#2413]
**Describe the bug**
Changes under "Settings > Subtitles > Synchronizarion / Alignement" aren't being applied without restarting Bazarr.

**To Reproduce**

1. Go to "Settings > Subtitles > Synchronizarion / Alignement" and toggle either or both of "No Fix Framerate" and "Gold-Section Search". 
2. In the same section enable "Automatic Subtitle Synchronization".
3. Click on "Save" at the top.
4. Add media and search for missing subtitles.

**Expected behavior**
The new subtitle should be auto-synced with the right settings for "No Fix Framerate" and "Gold-Section Search". Instead, the old settings are still being used. It works correct after restarting Bazarr.

**Screenshots**
N/A

**Software (please complete the following information):**
 - Bazarr: 1.4.2
 - Radarr version: 5.3.6.8612
 - Sonarr version: 4.0.2.1183
 - OS: Alpine 3.11 through linuxserver/bazarr

**Additional context**
N/A

**Comment by morpheus65535** [comment]
Fixed.
