### ISSUE TITLE
UnboundLocalError: cannot access local variable \'i\' where it is not associated with a value

### ISSUE THREAD

**Issue by cotko** [morpheus65535/bazarr#2417]
seems this trace is trying to use `i` which is not in scope:

https://github.com/morpheus65535/bazarr/blob/56d54e405b96feca13db9f96257c82a12f039c94/bazarr/radarr/sync/movies.py#L196

**Comment by JaiZed** [comment]
What makes you think it’s not in scope?
Do you have an error message to show this?

**Comment by cotko** [comment]
Actually it's not "not in scope", instead it's not set if loop is not ran first. This was in my case where I did not set correct mapping between bazarr and radarr, so there were no files to loop.
I fixed this in my docker directly just to find out that it then reported that file under "x/y" did not exist, which is a bit better hint about the misconfiguration:)

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta.
