### ISSUE TITLE
Bug(UI): Wanted tables is overflowed

### ISSUE THREAD

**Issue by boydaihungst** [morpheus65535/bazarr#2419]
**Describe the bug**
The cells in the table of episodes/movies from Wanted page have `white-space: nowrap;` which makes the UI overflowing if the episode's name is very long.

**To Reproduce**
1. Go to "Bazarr" website
2. Click on `Wanted`
3. Click on  `Episodes` or `Movies`
4. Wait until a list of episodes or movies is shown up.

**Expected behavior**
The UI should not be overflowed (at least on desktop Web UI). I notice we added `white-space: nowrap` to episode's div tag. If I remove it from the browser, UI looks so much better.

**Screenshots**
**Before** remove `white-space: nowrap`
![image](https://github.com/morpheus65535/bazarr/assets/38396158/2cc35b30-560c-4250-9b14-f6738b8054b1)

**After** remove `white-space: nowrap`
![image](https://github.com/morpheus65535/bazarr/assets/38396158/d0a0b2cf-8857-4b53-91b5-aed3779bd1d0)

**Software (please complete the following information):**
 - Bazarr: 1.4.3-beta.5
 - Radarr version: 5.3.6.8612
 - Sonarr version: 4.0.2.1183
 - OS: Linux-6.2.0-39-generic-x86_64-with-glibc2.37 (Ubuntu server 23.04)

**Additional context**

**Comment by morpheus65535** [comment]
Wanted-->Episodes view should be fixed in upcoming beta. Movies doesn't seems to have the same issue. Let me know if there's still something to fix.
