### ISSUE TITLE
Error when using embeddedsubtitles provider

### ISSUE THREAD

**Issue by BaukeZwart** [morpheus65535/bazarr#2423]
`TypeError. Exception info: "'FFprobeVideoContainer.copy_subtitles() got an unexpected keyword argume' ~ embeddedsubtitles.py@223"`

**To Reproduce**
Run manual subtitle search with embeddedsubtitles provider enabled

**Expected behavior**
No error

**Software (please complete the following information):**
 - Bazarr: v1.4.3-beta.7 - Docker
 - Radarr version 5.4.2.8659
 - Sonarr version 4.0.2.1262
 - OS: DSM 7.2 Synology

**Comment by JaiZed** [comment]
We need an exception trace as a minimum.
A log file would be preferable.

**Comment by BaukeZwart** [comment]
Debug log of the issue
[bazarr.log](https://github.com/morpheus65535/bazarr/files/14499106/bazarr.log)

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Thanks for reporting!
