### ISSUE TITLE
not converting HI subs embedded to normal if only HI subs are available

### ISSUE THREAD

**Issue by scratchmex** [morpheus65535/bazarr#2429]
**Describe the bug**
I have the HI embedded subs only and it doesn't try to convert them to normal subs. It looks like the episode is marked as having all subs required even though I have in my profile `Normal or hearing-impaired`.

**Expected behavior**
To have the original embedded HI subs and the post-processed normal subs extracted from the embedded.

I think this is not actually a bug but a feature request as the profile is very clear with Normal **or** hearing-impaired. In my case I want to have both. The default behavior should be to try to get the non-impaired anyway 

**Screenshots**

![image](https://github.com/morpheus65535/bazarr/assets/4014888/603ccf2b-c629-4aed-8f61-73db129943fa)

![image](https://github.com/morpheus65535/bazarr/assets/4014888/9917ba02-8388-437b-ad12-3de8be28bf56)

![image](https://github.com/morpheus65535/bazarr/assets/4014888/3fa23785-e055-41dd-bc71-4b222901230c)

**Software (please complete the following information):**
 - Bazarr: 1.4.2
 - Radarr version NA
 - Sonarr version NA
 - OS: NA

**Comment by morpheus65535** [comment]
This isn't a bug. The "or" is really a "or". Bazarr will get the one with the highest score without caring if it's HI or not.

**Comment by scratchmex** [comment]
Can we force non-HI?

**Comment by morpheus65535** [comment]
Not now but I'm planning to implement that in the future.

**Comment by scratchmex** [comment]
this is issue can track that feature

**Comment by morpheus65535** [comment]
> this is issue can track that feature

#2475 No ETA
