### ISSUE TITLE
[permission error] Subtitle not downloaded to dir

### ISSUE THREAD

**Issue by simkin** [morpheus65535/bazarr#243]
**Describe the bug**
For some reason bazarr is not downloading files to disk, possibly caused by some obscure permission error? I am running the bazarr service as bazarr:users and granted the "users" group write access to all dirs. The default group for the bazarr user is also set to "users". When I change/su to the bazarr user and navigate to a DIR the application has problems with, I can create a file without issues.

**To Reproduce**
1. Run application under user bazarr:users
2. chgrp -R users /dikkert/Server/Videos/
3. chmod -R g+rwx /dikkert/Server/Videos/
4. Try to download a subtitle for a movie/serie
5. See error
6. chmod 777 /DIR/
7. Try to download a subtitle for a movie/serie
8. Success

**Manual validation**
1. su - bazarr
2. cd "/path/to/dir"
3. touch test.file
4. observe file created as bazarr:users

**Expected behavior**
I expect that bazarr is also able to write to the dir

**Software (please complete the following information):**
 - Bazarr: v 0.6.9
 - OS: Debian Stretch
- FS: ZFS with ACL enabled

LOG:
![image](https://user-images.githubusercontent.com/958263/49512833-6a2ac600-f88f-11e8-83cf-21a8b4befcda.png)

**Comment by morpheus65535** [comment]
Could you provide a debug log please?

**Comment by simkin** [comment]
> Could you provide a debug log please?

yes, will do that. Could you please tell me how to set log level to debug?

**Comment by morpheus65535** [comment]
In settings—>General.

**Comment by simkin** [comment]
Gottit. And guess what, I am now unable to reproduce the issue. I think the service was first running as bazarr:bazarr instead of bazarr:users. I thought I restarted the service after changing, guess not. All working correctly now! Thanks for this great tool!!
