### ISSUE TITLE
Betaseries treats not found as authentication error

### ISSUE THREAD

**Issue by cookieguru** [morpheus65535/bazarr#2431]
**Describe the bug**
The existing code checks the response code, and if it is 400, it assumes it is an inalid API key:

https://github.com/morpheus65535/bazarr/blob/902d1e62b8251c36a622f96bc40d6ef9f052997e/libs/subliminal_patch/providers/betaseries.py#L99-L100

However looking at the actual request, assuming we call with a valid key and a valid TVDB ID we get a HTTP 400, but the body indicates that this isn't an authentication error but rather a "notice" that there is no data available

```plain
curl -i "https://api.betaseries.com/shows/episodes?key=validkey&thetvdb_id=410359&season=1&episode&subtitles=1&v=3.0"
HTTP/1.1 400 Bad Request

{
    "errors": [
        {
            "code": 4001,
            "text": "No series found."
        }
    ]
}
```
(other headers not shown)

However making the same call but with a diferent TVDB ID (such as one featured on the betaseries homepage) results in a HTTP 200:
```plain
curl -i "https://api.betaseries.com/shows/episodes?key=validkey&thetvdb_id=413033&season=1&episode&subtitles=1&v=3.0"
HTTP/1.1 200 OK

{"episodes":[/*snip*/],"errors":[]}
```

If we make the same reuest ith an intentionally bad API key, we still see a HTTP 400 (rant: this should actually be a 401), but we see a different code in the response body:
```plain
curl -i "https://api.betaseries.com/shows/episodes?key=bad&thetvdb_id=413033&season=1&episode&subtitles=1&v=3.0"
HTTP/1.1 400 Bad Request

{
    "errors": [
        {
            "code": 1001,
            "text": "Mauvaise clé API."
        }
    ]
}
```

**To Reproduce**
1. [Acquire an API key for betaseries](https://www.betaseries.com/en/compte/api)
2. Add betaseries provider with that API key
3. Make a request to betaseries is for an episode that does not exist on betaseries
4. See error:
```plain
Using betaseries again after 12 hours, (disabled because: AuthenticationError)
Throttling betaseries for 12 hours, until 24/03/15 07:03, because of: AuthenticationError. Exception info: "'Invalid token provided' ~ betaseries.py@100"
```

**Expected behavior**
No error raised for episode not found

**Software (please complete the following information):**
 - Bazarr: 1.4.2

---

I don't know what the solution is here; check the code in the errors array body, check for the episodes key in the root of the payload body, something else...?  [The API docs](https://developers.betaseries.com/docs/making-requests) do not enumerate what each of the codes are.

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Thanks for the investigation!
