### ISSUE TITLE
Fix the version info

### ISSUE THREAD

**Issue by nahid6970** [morpheus65535/bazarr#2439]
when i update all my software using winget bazarr keeps getting updated every time even though its already in the latest version

Name           Id              Version       Available      Source
------------------------------------------------------------------
Microsoft Edge Microsoft.Edge  122.0.2365.92 122.0.2365.106 winget
Bazarr         Morpheus.Bazarr Unknown       1.4.2          winget
2 upgrades available.

(1/1) Found Bazarr [Morpheus.Bazarr] Version 1.4.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...

here even bazarr is already at the latest version and i already updated it few seconds ago and hwn i run the winget update command it again downloads the same version and installs it again and again.

**Comment by morpheus65535** [comment]
I have no idea who created this package but it's not supported by our team (I've never heard of winget before I read this issue).

I suggest you contact the package maintainer so he can fix it.
