### ISSUE TITLE
Bug(UI): manually uploading subtitles dialog with a long file name doesn't wrap or work break

### ISSUE THREAD

**Issue by boydaihungst** [morpheus65535/bazarr#2448]
**Describe the bug**
Manually uploading subtitles dialog with long file name, which has each words separated by a special character, doesn't wrap. Please see the image below.

**To Reproduce**
1. Go to "Bazarr" website
2. Click on `Wanted episode/movie`
3. Click on any  `Episode` or `Movie`
4. Click on `manual upload` button. Then select the long name sub.
5. Check the manual import dialog.

**Expected behavior**
The file name should be wrap or break word, e.g: 
```
a.really.longggggggg...01.srt
a.really.longggggggg...S01E01.srt
# Or break word
a.really.longggggggg
gggggggggggggggg
ggggggggg.name.w
ithout.whitespace.01.srt
```
We should somehow show the number in the file name, so that when users import multiple files, they will know which episode number it is.

**Screenshots**
![Screenshot_20240409-104910_Firefox_Nightly](https://github.com/morpheus65535/bazarr/assets/38396158/4c8b4b10-1fe2-4cc4-ada7-4074c1b8b720)

**Software (please complete the following information):**
 - Bazarr: 1.4.3-beta.15
 - Radarr version:  5.3.6.8612
 - Sonarr version:  4.0.3.1413
 - OS: Linux Ubuntu Server 23.04 (kernel-6.2.0-39-generic-x86_64-with-glibc2.37)
- Python Version: 3.11.4

**Additional context**
Example subfile name for testing: `a.really.longgggggggggggggggggggggggggggggggg.name.without.whitespace.01.srt`
`a.really.longgggggggggggggggggggggggggggggggg.name.without.whitespace.S01E01.srt`

**Comment by boydaihungst** [comment]
@morpheus65535 it break UI of other places on mobile. 
![Screenshot_20240417-090617_Firefox_Nightly](https://github.com/morpheus65535/bazarr/assets/38396158/358ca81a-0322-4d83-885b-ed95856acac7)
![Screenshot_20240417-090629_Firefox_Nightly](https://github.com/morpheus65535/bazarr/assets/38396158/f3e4dabb-0b1c-4e79-bdb2-e16efd14ffb6)

**Comment by morpheus65535** [comment]
@boydaihungst yeah you're right. Thanks for reporting.

@anderson-oki I think we're gonna need a more specific fix for upload modal.

**Comment by anderson-oki** [comment]
Yeah let me open a PR only for that modal, and perhaps we can manually apply where needed.

**Comment by anderson-oki** [comment]
@morpheus65535 This should do the trick #2459. Sorry about that.

**Comment by morpheus65535** [comment]
> @morpheus65535 This should do the trick #2459. Sorry about that.

Not a big deal, thanks.
