### ISSUE TITLE
Titlovi

### ISSUE THREAD

**Issue by makita86** [morpheus65535/bazarr#2451]
Bazarr not dowloadinh subs from titlovi.com
It displays auth error
Sonarr version 4.0.3.1413
Bazarr 1.4.2
**Describe the bug**

Bazarr not dowloading subs from titlovi.com

**To Reproduce**
1. System providers tab displays titlovi auth error

**Expected behavior**
Should download subtitles from titlovi.com

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 1.4.2
 - Sonarr version 4.0.3.1413
 
[bazarr.log](https://github.com/morpheus65535/bazarr/files/14968042/bazarr.log)

**Comment by morpheus65535** [comment]
Fill the issue form properly (that's mandatory) and provide debug log please.
