### ISSUE TITLE
Series not matched in scoring on OpenSubtitles due to multiple instances of show (f.e. 2004 /2016)

### ISSUE THREAD

**Issue by Mirx** [morpheus65535/bazarr#246]
F.e. When searching for the show Shadowhunters, the series isn't matched in the subliminal scoring which is extremely problematic as series makes up for 50% of the scoring. 

This is the result of multiple instances of the show being present, and the title does not match the scene name.

Shadowhunters - https://www.opensubtitles.org/en/search/sublanguageid-all/idmovie-12840

Shadowhunters: The Mortal Instruments (2016)  - https://www.opensubtitles.org/en/ssearch/sublanguageid-all/idmovie-405711

Logfile:
https://pastebin.com/R3tAjsQ4

This is a generic problem for subtitles download tools, and mostly it is solved by implementing some sort a mapping.

In the case of subzero, the IMDBid is used to overwrite the matching results so series is matched.

https://github.com/pannal/Sub-Zero.bundle/blob/master/Contents/Libraries/Shared/subliminal_patch/score.py

**To Reproduce**
1. Search any subtitle for the show Shadowhunters

**Expected behavior**
Series should be matched resulting in a 50% increase of the scoring result.

**Comment by morpheus65535** [comment]
What is your minimum score settings for movies?

**Comment by Mirx** [comment]
I guess you mean series instead of movies. Both are set to Bazarr defaults, so for series it's 90%.
As series makes up for 50%, setting it to a value which would support a computed score below 180 would result is a ton of false positives.

Computed score 162 with final matches set(['episode', 'format', 'season', 'year', 'video_codec', 'resolution', 'hearing_impaired'])|

With an series match added to the compute that would have been 342 and a 95% match.

**Comment by morpheus65535** [comment]
We should have complete integration of subliminal_patch from SubZero in the next weeks. This should solve your issue.
