### ISSUE TITLE
Bug(subtitles provider): animetosho stopped other providers if there is no series_anidb_id attribute 

### ISSUE THREAD

**Issue by boydaihungst** [morpheus65535/bazarr#2463]
**Describe the bug**
```
BAZARR Error ('Movie' object has no attribute 'series_anidb_id') trying to get video information for this file: /mnt/hdd/Movie/Kung Fu Panda 4 (2024) [tmdbid-1011985]/Kung Fu Panda 4 (2024).mkv
```

Animetosho would stop other providers from searching subtitles for the movie if it can't find the `series_anidb_id` attribute even with `Search Enabled Providers Simultaneously` enabled.

**To Reproduce**
Prerequisites: enabled animetosho provider and any other provider
1. Go to 'setting' > 'subtitles'
2. Switch on 'Search Enabled Providers Simultaneously'
3. Go to any movie
4. Click the search button
5. Subtitle not found with the bug log above. 
6. Remove the animetosho provider, and search again
7. Subtitle download without problem.

**Expected behavior**
Should skip the animetosho provider if there isn't anidb_id and use the rest of the providers.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr:  1.4.3-beta.23
 - Sonarr Version: 4.0.4.1491
- Radarr Version: 5.4.6.8723
- Operating System: Linux-6.2.0-39-generic-x86_64-with-glibc2.37 (Ubuntu server 23.04)
- Python Version: 3.11.4

**Additional context**

**Comment by morpheus65535** [comment]
@anderson-oki can you look into this please?

**Comment by anderson-oki** [comment]
Its an issue with the refiner when its not an episode, i cant continue right not but ill open a fix in a couple hours.

**Comment by morpheus65535** [comment]
This one should have been fixed in latest nightly release. Can you test and confirm please?

**Comment by boydaihungst** [comment]
I can confirm that It's fixed. Thank you both 👍
