### ISSUE TITLE
Cutoff menu missing :forced

### ISSUE THREAD

**Issue by arockincanada** [morpheus65535/bazarr#2466]
When trying to setup for forced subtitle download only, by adding both forced and normal versions to my profile, but selecting normal version in cutoff menu, only "en" is shown for both.

1. Go to Languages
2. Edit Language Profile to include English - Forced, and English - Normal
3. Open Cutoff menu and "en" is shown twice with no indication of which one is forced.

Bazarr: v1.4.2

**Comment by anderson-oki** [comment]
Maybe something like this could do the trick:

![Screenshot 2024-04-25 at 11 01 26](https://github.com/morpheus65535/bazarr/assets/12686241/c2a75eed-91d3-4298-8864-73029f444616)

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Thanks for reporting!
