### ISSUE TITLE
Anime Tosho KeyError

### ISSUE THREAD

**Issue by PassiveLemon** [morpheus65535/bazarr#2468]
**Describe the bug**
The Anime Tosho provider reports KeyErrors.

**To Reproduce**
1. Use Anime Tosho

**Screenshots**
`INFO (get_providers:384) - Throttling animetosho for 10 minutes, until 24/04/23 23:41, because of: KeyError. Exception info: "''name'' ~ animetosho.py@145"`

**Software (please complete the following information):**
 - Bazarr: 1.4.3-beta.24
 - Radarr version 5.4.6.8723
 - Sonarr version 4.0.4.1491
 - OS: Docker

**Additional context**
I don't exactly know how to even use the AniDB integration but for API Client, I just put the name of the client as it I made it on AniDB. I tried to manually query an anime using their HTTP API and that client name and I was successful in that regard.

**Comment by anderson-oki** [comment]
I will take a look into this one. But i might ask for more details to confirm the issue.

**Comment by anderson-oki** [comment]
@PassiveLemon what is the anime name season and episode you can reproduce the issue. It seems the subtitle has no name, so i need a sample.

**Comment by PassiveLemon** [comment]
I turned debug mode on and waited filtered for the error.
Something that turned up was:
```
Unexpected error in provider 'animetosho': Traceback (most recent call last): File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/core.py", line 366, in list_subtitles_provider results = self[provider].list_subtitles(video, to_request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/providers/animetosho.py", line 93, in list_subtitles return [s for s in self._get_series(video.series_anidb_episode_id) if s.language in languages] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/app/bazarr/bin/bazarr/../custom_libs/subliminal_patch/providers/animetosho.py", line 145, in _get_series if lang.alpha3 == 'por' and subtitle_file['info']['name'].lower().find('brazil'): ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^KeyError: 'name'
```
That happened at 19:22:08.
At 19:22:07, `Searching with series name: Jujutsu Kaisen (TV)`

I tried downloading the logs but nothing happened so here's a screenshot of the log page. Sorry about that.
JJK:
![image](https://github.com/morpheus65535/bazarr/assets/72527881/610f4d8c-8d38-4e26-a964-04a5baefcdba)
Anime Tosho error:
![image](https://github.com/morpheus65535/bazarr/assets/72527881/ce8361e2-bba6-41d5-aa1f-8a671e3ccbd0)

**Comment by PassiveLemon** [comment]
Nvm, the log file did download, just not on the first 2 tries. 
[bazarr.log](https://github.com/morpheus65535/bazarr/files/15102068/bazarr.log)

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Let us know if not!
