### ISSUE TITLE
Cannot unpack non-iterable NoneType

### ISSUE THREAD

**Issue by PassiveLemon** [morpheus65535/bazarr#2469]
**Describe the bug**
Not sure what it is but it returns an error when trying to get video information for a file.

**To Reproduce**
Not sure how to reproduce. It might just be bad media.

**Screenshots**
`ERROR (utils:55) - BAZARR Error (cannot unpack non-iterable NoneType object) trying to get video information for this file: /data/shows/General/Death's Game (2023) [imdbid-tt26225038]/S01E01 [WEBDL-1080p].mkv`
It does this for every episode in the series season.

**Software (please complete the following information):**
 - Bazarr: 1.4.3-beta.24
 - Radarr version 5.4.6.8723
 - Sonarr version 4.0.4.1491
 - OS: Docker

**Comment by anderson-oki** [comment]
Let me take care of this one.
