### ISSUE TITLE
cant' install bazarr

### ISSUE THREAD

**Issue by caeillus** [morpheus65535/bazarr#2477]
**Describe the bug**
I can't install bazarr.
I have error message after laucnh : python3 -m pip install -r requirements.txt

root@osmc:/opt/bazarr# python3 -m pip install -r requirements.txt
Ignoring pywin32: markers 'platform_system == "Windows"' don't match your environment
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (52.0.0)
Requirement already satisfied: lxml<5.0.0,>=4.3.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (4.6.3)
Requirement already satisfied: numpy>=1.12.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (1.19.5)
Collecting webrtcvad-wheels>=2.0.10 (from -r requirements.txt (line 4))
  Using cached webrtcvad-wheels-2.0.11.post1.tar.gz (69 kB)
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement Pillow>=9.0.0 (from versions: none)
ERROR: No matching distribution found for Pillow>=9.0.0

**Software (please complete the following information):**
 - Sonarr version 4.0.4.1491
 -  Prowlarr version 1.16.2.4435
 - OSMC Kodi version : 20.5

**Comment by morpheus65535** [comment]
This isn't a bug, your operating system simply seems to not be supported by dependencies. Maybe someone will be able to help you on Discord.

**Comment by caeillus** [comment]
ok
