### ISSUE TITLE
[Docker] Permission denied 'config/config' on startup

### ISSUE THREAD

**Issue by TheHolyWaffle** [morpheus65535/bazarr#248]
**Describe the bug**
Bazarr fails to startup properly in the official docker container

**To Reproduce**
1. Install dockerimage linuxserver/bazarr:latest
2. Launch a container with volumes mapped to: /config, /tv and /movies, map port from 6767 to 6767
3. An error in log appears to indicate a permission denied '/config/config'

**Screenshots**
![image](https://user-images.githubusercontent.com/787914/49680739-6322d400-fa98-11e8-8061-77335800050c.png)

This is on a synology NAS server using the docker container package.

**Comment by TheHolyWaffle** [comment]
Ah, I wasn't aware. Let me try that out....

**Comment by morpheus65535** [comment]
You can find detailled instructions here: https://hub.docker.com/r/linuxserver/bazarr/

**Comment by TheHolyWaffle** [comment]
Yep, that was the issue. Fixed it together with https://www.naschenweng.info/2016/11/03/synology-docker-nzbget/

**Comment by morpheus65535** [comment]
Good news! Have fun!
