### ISSUE TITLE
Non-Movie Files Registered As Needing Subs

### ISSUE THREAD

**Issue by thegranddesign** [morpheus65535/bazarr#2490]
**Describe the bug**
For example, if there is a file in the directory named `trailer.mp4`, Bazaar is registering that it needs a subtitle file when I don't care about it.

I'm not sure if the proper thing would be to add an "excluded pattern" to the configuration or to always exclude "special" files that aren't ever going to have subtitles.

**To Reproduce**
1. Add a movie file
2. Add a subtitle for that movie
3. Add a trailer movie file
4. Refresh the list

**Expected behavior**
The movie should be considered "completed'

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: latest
 - Radarr version latest
 - Sonarr version latest
 - OS: Debian

**Additional context**
N/A

**Comment by jaycedk** [comment]
Try moving trailers to a sub dir.
\movies\SomeKickassMovie\trailers\trailer.mp4

**Comment by thegranddesign** [comment]
@jaycedk yeah but I'd prefer to keep everything in the same directory with the movie file. Regardless, I looked at Radarr and it looks like Radarr is picking up the wrong video file as the movie file so I'm going to say this is a Radarr issue for now and close this.

**Comment by morpheus65535** [comment]
We use the main movie provided by Radarr when importing and don't use other movie files. If it wasn't properly tagged in Radarr, this may be the cause. Don't hesitate to reopen if you're facing this again while being properly tagged in Radarr.
