### ISSUE TITLE
SubDivx returning 0 results

### ISSUE THREAD

**Issue by cacafuti8888** [morpheus65535/bazarr#2499]
**Describe the bug**
Subdivx provider returning 0 results. Logs appear to be looking for season/episode format "1x01" instead of "S01E01" returning no matching results.

**Software (please complete the following information):**
 - Bazarr: v1.4.3-beta.38
 - Radarr version 5.5.3.8819
 - Sonarr version 4.0.4.1668
 - OS: RaspberryOS Bookworm

[bazarr.log](https://github.com/morpheus65535/bazarr/files/15360568/bazarr.log)

**Comment by morpheus65535** [comment]
If you're referring to Star Trek: Discovery S01E08, there's no subtitles returned because the only one available is Forced.

```
2024-05-18 09:28:14|DEBUG   |subliminal_patch.providers.subdivx|Series matched? False [<Episode ['Star Trek: Discovery', 2017, 5x8]> -> Star Trek: Discovery S01E08] [title distance: 0]|
2024-05-18 09:28:14|DEBUG   |subliminal_patch.providers.subdivx|Skipping unsupported subtitles: Star Trek: Discovery S01E08 - FORZADO|
```

The `1x08` is only the string representation of the video object, subtitles are searched using S01E08.

**Comment by cacafuti8888** [comment]
> If you're referring to Star Trek: Discovery S01E08, there's no subtitles returned because the only one available is Forced.
> 
> ```
> 2024-05-18 09:28:14|DEBUG   |subliminal_patch.providers.subdivx|Series matched? False [<Episode ['Star Trek: Discovery', 2017, 5x8]> -> Star Trek: Discovery S01E08] [title distance: 0]|
> 2024-05-18 09:28:14|DEBUG   |subliminal_patch.providers.subdivx|Skipping unsupported subtitles: Star Trek: Discovery S01E08 - FORZADO|
> ```
> 
> The `1x08` is only the string representation of the video object, subtitles are searched using S01E08.

Hello, tanks for the quick response. I'm actually looking for the s05e08, I don't know why in a manual search for that episode's subtitle bazarr is searching for the entire series. It happens with every subtitle that I search, subdivx never return any result. On subdivx website, star trek discovery reports 6 subtitles (one of them as you pointed is forced) and s05e08 reports 2. I don't know what I'm missing, if there's something wrong with my configuration or if it's subdivx plug in.

I know that subdivx is giving you a headache but it's a very popular source of subtitles for Spanish talking people. What bothers me is that nobody reported anything before me, and it's happening me at least one month.

**Comment by morpheus65535** [comment]
There's no subtitles for S05E08.

![image](https://github.com/morpheus65535/bazarr/assets/5130500/1e1601d6-114d-43bb-be5f-50826964741a)

**Comment by cacafuti8888** [comment]
> There's no subtitles for S05E08.
> 
> ![image](https://github.com/morpheus65535/bazarr/assets/5130500/1e1601d6-114d-43bb-be5f-50826964741a)
> 

The thing is if you remove the ":" on the query it gives you two results. ![Screenshot_2024-05-25-10-31-08-776_com.brave.browser.jpg](https://github.com/morpheus65535/bazarr/assets/16649341/a718479f-3414-4ea8-9871-39374307f846)

I don't know if it's subdivx fault for not putting the correct show's name or not. It's weird because for example it happens also with the show Ahsoka that (as far as I can see) has no ":" or anything similar. Bazarr can't find subtitles.

Maybe a way to simplify queries without simbols? I don't know.

Thank you for your time.

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Let me know!

**Comment by cacafuti8888** [comment]
Hi, just posting to tell that everything seems working as expected now, final episode's subtitle of star trek discovery just downloaded automatically.

I looked the changes that you made to the code but my knowledge is basically zero... What was the problem?

Anyway, thank you for the time and the effort to analyze and fix the problem.

**Comment by morpheus65535** [comment]
> I looked the changes that you made to the code but my knowledge is basically zero... What was the problem?

I've added series title sanitation to deal with `:` and we now compare the subdivx title to alternative titles on top of main title in Sonarr.

**Comment by cacafuti8888** [comment]
> > I looked the changes that you made to the code but my knowledge is basically zero... What was the problem?
> 
> I've added series title sanitation to deal with `:` and we now compare the subdivx title to alternative titles on top of main title in Sonarr.

Nice. Again, thanks for the fix, that was quick. And for everything you did. Keep the good work!
