### ISSUE TITLE
Fix from subliminal

### ISSUE THREAD

**Issue by zeppelinlg** [morpheus65535/bazarr#250]
Hi,

There are some fix on subliminal. I don't know if it's usefull for bazarr but for example the search url for addict7d has changed.
https://github.com/Diaoul/subliminal/commit/883a1a633e977d7d99a1578dfd4c344416bebaaf

Thanks for your work

**Comment by halali** [comment]
We are already on latest subliminal dev.

**Comment by morpheus65535** [comment]
We already have an earlier version of Subliminal than the one you refered. In the future, we will be running from the Sub-Zero patched version so we are definitely not merging newer version of Subliminal anymore. Thanks for the tips! :-)
