### ISSUE TITLE
Can't download subtitles from legendasdivx. Bazaar using wrong links to parse results.

### ISSUE THREAD

**Issue by extazyz** [morpheus65535/bazarr#2509]
**Describe the bug**
Can't download subtitles from legendasdivx.pt of pt-pt language.

Whenever I search for a subtitle ,  it uses a wrong url to search for the subtitle.

**To Reproduce**
Automatic or Manually Search says not subtitles found.

**Expected behavior**
**I know the URL's i'm gonna show below aren't filtering for PT-PT , but i couldnt find the string to show PT-PT only, take them as an example as proof that subtitles do exist.**

Downloads the subtitle that is available on the website.
For eg: when searching legendasdivx for Better Call Saul S02E04 , Bazaar is trying to use this url which returns 0 results:
`https://www.legendasdivx.pt/modules.php?name=Downloads&file=jz&d_op=search&op=_jz00&query=%2522better%20call%20saul%2520s02e04%2522&form_cat=28`

When it should be using this url that has the subtitles:
`https://www.legendasdivx.pt/modules.php?name=Downloads&file=jz&d_op=search&op=_jz00&query=%2522better%20call%20saul%2520s02e04`

Also when it search's for the season pack, it uses (that also returns zero results):
`https://www.legendasdivx.pt/modules.php?name=Downloads&file=jz&d_op=search&op=_jz00&query=%2522better%20call%20saul%2520s02%2522&form_cat=28`

When it should be using instead:
`https://www.legendasdivx.pt/modules.php?name=Downloads&file=jz&d_op=search&op=_jz00&query=%2522better%20call%20saul%2520s02`

**Screenshots**
Broken URL that Bazarr is using for search single EP
![EP_BrokenURL](https://github.com/morpheus65535/bazarr/assets/171158194/ee3b962d-9eb8-4474-9770-aebfcf62d87f)
Fixed URL for Single EP that Bazarr should be using instead
![EP_CorrectURL_to_be_used_instead](https://github.com/morpheus65535/bazarr/assets/171158194/19186427-ca95-45a5-83f5-b54274ae0ae4)
Season broken URL:
![Season_Pack_Broken_URL](https://github.com/morpheus65535/bazarr/assets/171158194/a54367b9-f3ce-4d3d-9c76-fcb8e20dacfa)
Season Pack URL that bazarr should be using:
![Season_Pack_Correct_URL_to_be_used](https://github.com/morpheus65535/bazarr/assets/171158194/41238f69-b261-49f7-9f00-5f1e610c9e36)

**Software (please complete the following information):**
 - Bazarr: 1.4.3-beta.41
 - Radarr version 5.6.0.8846
 - Sonarr version 4.0.4.1668
 - OS: Debian 12

**Additional context**
Log attached.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/15486137/bazarr.log)

**Comment by extazyz** [comment]
Found that the working urls with PT-PT language filter that should be used by bazaar instead are:

Single EP ( https://www.legendasdivx.pt/modules.php?name=Downloads&file=jz&d_op=search&op=_jz00&query=better%20call%20saul%2520s02e04%2522&form_cat=28 )

Season ( https://www.legendasdivx.pt/modules.php?name=Downloads&file=jz&d_op=search&op=_jz00&query=better%20call%20saul%2520s02%2522&form_cat=28 )

**Comment by anderson-oki** [comment]
I managed to got an invite, but the account is not yet activated. I will take a look into once i can login.

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta.
