### ISSUE TITLE
Issues with starting Bazarr

### ISSUE THREAD

**Issue by sholcomb101** [morpheus65535/bazarr#251]
I was working through the installation instructions on the Wiki. 

I have GIT installed and Python 3.7.1

Bazarr installed in c:\bazarr

I get the following error hen trying to launch the script.

C:\bazarr>python bazarr.py
  File "bazarr.py", line 15
    print 'bazarr.py -h --no-update --config <config_directory>'
                                                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('bazarr.py -h --no-update --config <config_directory>')?

**Comment by morpheus65535** [comment]
First sentence in the `Running from source` page of the wiki:

`bazarr require Python 2.7.13 or greater (v3 not supported) and can be run from source. This will use git as updater, so make sure that is installed.`

**Comment by sholcomb101** [comment]
Good lord I am an idiot. Thanks for pointing out my brainlessness nicely.

**Comment by morpheus65535** [comment]
Np have fun!
