### ISSUE TITLE
Subtitle sync operation does not respect Path Mapping for Radarr/Sonarr

### ISSUE THREAD

**Issue by tnyeanderson** [morpheus65535/bazarr#2512]
**Describe the bug**

If you have a Path Mapping set up for Radarr or Sonarr, it is not respected during a subtitle sync operation. Instead, the path from the database (e.g. the un-rewritten path directly from Radarr/Sonnar) is used.

Errors from the logs (one from Radarr, one from Sonarr):

```
ERROR (video_analyzer:271) - Video file "/data/movies/path/to/file.mp4" cannot be found for analysis
ERROR (video_analyzer:271) - Video file "/data/tv/path/to/file.mp4" cannot be found for analysis
```

**To Reproduce**

Have a Radarr instance which uses the `/data/movies` base path, or a Sonarr instance with a `/data/tv` base path.

Mount these directories at a different path in the Bazarr docker container. For example, map those directories to `/movies` and `/tv` inside the container with `-v /data/movies:/movies -v /data/tv:/tv`.

In the Bazarr web interface, go to **Settings > Radarr**  and set up a Path Mapping from `/data/movies` to `/movies`. Repeat for Sonarr settings and paths.

Go to any movie in your library which has a subtitle file, and select **... > Sync** to begin the sync process. The web interface will make it seem like everything worked (success message, etc).

Check the logs and see the above statements.

Alternatively, go to any show in your library which has an episode with a subtitle file. Click **Mass Edit**, select an episode, then click **Select Action > Sync**. See the corresponding log.

**Expected behavior**

Bazarr should look for the video file according to the configured Path Mappings when a Sync operation is performed on a subtitle file.

**Screenshots**

N/A

**Software (please complete the following information):**

 - Bazarr: 1.4.3
 - Radarr version 5.2.6.8376
 - Sonarr version 4.0.1.929
 - OS: linux/docker
 
**Additional context**

I believe the problem is [here](https://github.com/morpheus65535/bazarr/blob/97ea3a81242f604007fcd54c54f4acf17a97fade/bazarr/utilities/video_analyzer.py#L115-L136).

I think that before calling `data = parse_video_metadata(media_data.path, ...)`, we should derive `path_mappings.path_replace_movie(media_data.path)`, and send that value as the path instead.

**Comment by tnyeanderson** [comment]
Opened #2513 to propose a fix.

**Comment by morpheus65535** [comment]
If you debug, you'll see that paths already get to this function properly mapped. We unmap them in parse_video_metadata() depending of the media type.

Is this a new instance of Bazarr? Have you tried refreshing browser or even restarting Bazarr? Looks like a frontend cache glitch to me.

**Comment by tnyeanderson** [comment]
I've confirmed the bug by adding debugging statements as you describe.

>If you debug, you'll see that paths already get to this function properly mapped.

This is not correct, at least in my case. Add `logging.info(file)` as the very first line in the `parse_video_metadata` function and you will see that it is using the path from Radarr, not the path resolved by the Path Mapping. This is also clear by looking at the calling function, which uses the path from the database directly (which I assume is the path directly from Radarr; am I wrong about that?)

>We unmap them in parse_video_metadata() depending of the media type.

The only unmapping of paths that happens in that function is regarding the cache (either storing the ffprobe data to the cache or retreiving the data from the cache based on the path), which is unrelated to this issue, since this issue occurs specifically when there is *not* a usable entry in the cache and the information has to be retrieved from the file itself. Any unmapping that happens in the caller happens after the calls which cause this issue on lines 124/135.

Not only that, but based on my reading and understanding of the code at this point, and at least with my current deployment, the unmap functions you are referencing on lines 231/236/301/306 actually don't do anything right now, since the path sent to those calls is the already-unmapped/never-mapped path. Of course, fixing the issue as described in my PR would make those calls useful again, so they will definitely be needed once the fix is in place.

>Is this a new instance of Bazarr? Have you tried refreshing browser or even restarting Bazarr? Looks like a frontend cache glitch to me.

Existing instance, restarted multiple times, cleared cache and refreshed in browser. This really seems to just be an implementation bug.

I tested the linked PR and it solves the problem (the error no longer appears). Reopening.

**Comment by morpheus65535** [comment]
I agree, there's something odd here and I can't explain why it works in both case for me... 

One thing for sure is that if we receive a non-mapped subtitles path in parse_video_metadata(), we shouldn't map the path in those 2 places:
https://github.com/morpheus65535/bazarr/blob/master/bazarr/sonarr/sync/parser.py#L103
https://github.com/morpheus65535/bazarr/blob/master/bazarr/radarr/sync/parser.py#L90

If we don't change it in those 2 files, parse_video_metadata() will receive a mapped path here:
https://github.com/morpheus65535/bazarr/blob/master/bazarr/utilities/video_analyzer.py#L78

If you add this to your PR, I think we're good but if you're willing to take a look, it would be appreciated.

**Comment by tnyeanderson** [comment]
I think there might be some confusion when I say "sync". What I am talking about is the subsync functionality that tries to sync a subtitle file's timestamps with the actual video file. I'm *not* talking about syncing the metadata from radarr/sonarr. I think the files you linked are regarding the latter, and are unrelated to this issue.

I agree that the call to `embedded_audio_reader`, which then calls `parse_video_metadata`, is using the mapped path, which is why I assume that part actually works.

The issue I'm talking about is regarding the call to `subtitles_sync_references`, which takes only a subtitle path, looks up the movie file path from the database based on the subtitle path, and then calls `parse_video_metadata` with that derived path. In this function, which is the focus of my PR, the paths are not mapped before the call to `parse_video_metadata`.

I think the PR solves this issue. We can probably continue the conversation on the PR to talk about implementation details.

**Comment by morpheus65535** [comment]
Sorry for the delay. I totally understood what you were talking about. My point is that the 2 files I were referencing we're already providing mapped paths when there's no need to do so when we're mapping them further down the chain.

Of course your PR fix you issue but having the same paths being mapped twice may cause further issues. What I was asking is if you could check to be sure that it was the only occurrence with double mapping so it could get fix within the same PR.

Thanks.

**Comment by tnyeanderson** [comment]
Hi, I think there is still a misunderstanding.

>One thing for sure is that if we receive a non-mapped subtitles path in parse_video_metadata(), we shouldn't map the path in those 2 places:

The `parse_video_metadata` function **should not** receive non-mapped path. It **should** receive a **mapped** path (the actual path to the file as visible to bazarr). The fact that the path is already mapped in the two places you mentioned is a *good* thing. It is what makes those functions work correctly at the moment.

By contrast, `subtitles_sync_references` is *not* using the mapped path when it calls `parse_video_metadata`, which is why it is broken. My PR corrects this mistake by deriving the mapped path from inside `subtitles_sync_references` before calling `parse_video_metadata`.

>My point is that the 2 files I were referencing we're already providing mapped paths when there's no need to do so when we're mapping them further down the chain.

They are not being mapped further down the chain. The `parse_video_metadata` function *does not map the path before looking for the file on the filesystem*. It expects to receive an *already-mapped path* as its first parameter.

>having the same paths being mapped twice may cause further issues. What I was asking is if you could check to be sure that it was the only occurrence with double mapping so it could get fix within the same PR.

There are no occurrences of double-mapping that I can find in the code, including the files/lines you provided. Based on my tracing of callers to `parse_video_metadata`, *all calls to `parse_video_metadata` are already correctly sending the mapped path except for the call from `subtitles_sync_references`*. Therefore, to my knowledge, there is no further work to be done on this PR.

**Comment by morpheus65535** [comment]
Will be fixed by your PR. I'll merge it once rebased on dev branch. Sorry for the confusion. Thanks!
