### ISSUE TITLE
[Provider Request] Add Subs.ro for subtitles

### ISSUE THREAD

**Issue by vtmocanu** [morpheus65535/bazarr#252]
Hi,
Thank you very much for your work, I really like this Radarr/Sonarr companion :+1: 
Can you please also add subs.ro as a provider?
They have an API: http://api.subs.ro/examples/
Thanks again!
Vlad

**Comment by marcel5454** [comment]
Would also highly appreciate this to be added!

**Comment by denisgabriel5** [comment]
I opened a PR for this. 

https://github.com/morpheus65535/bazarr/pull/2964
