### ISSUE TITLE
Unable to distinguish already download subtitles from  unavailable subtitles

### ISSUE THREAD

**Issue by alculete** [morpheus65535/bazarr#2523]
**Describe the bug**
Unable to distinguish already downloaded subtitles from  unavailable subtitles
Please make already downloaded/ available subtitles green or blue  

![image](https://github.com/morpheus65535/bazarr/assets/2129497/b8e58ee4-e36e-4703-910c-a7a92de4eddc)

**Comment by alculete** [comment]
Running 1.4.4-beta.0

**Comment by morpheus65535** [comment]
Fixed in 1.4.4-beta.1

**Comment by alculete** [comment]
Linuxserver.io still on beta0, but since this is fixed this can be closed.

**Comment by morpheus65535** [comment]
https://hub.docker.com/layers/linuxserver/bazarr/development-version-v1.4.4-beta.1/images/sha256-2bc19f3c488c68d848b195bcc1020a646d67852ba87cfdf96eda6f8ddf865582?context=explore
