### ISSUE TITLE
https redirects to http with wrong port when using reverse proxy

### ISSUE THREAD

**Issue by kbirger** [morpheus65535/bazarr#253]
**Describe the bug**
If you set up an NGINX reverse proxy to Bazarr and use HTTPS, a request to /bazarr (or whatever your root path is) will redirect to http://HOST:443/bazarr

**To Reproduce**
1. set base path to /bazarr
2. save / reload
3. set up nginx reverse proxy (see below) for location /bazarr to point to upstream bazarr server
4. `curl -i https://HOST/bazarr` 

```
HTTP/2 303
server: nginx
date: Thu, 13 Dec 2018 13:29:53 GMT
content-type: text/html; charset=UTF-8
content-length: 0
access-control-allow-origin: *
location: **http:**//HOST.work:**443**/bazarr/series
```

**Expected behavior**
redirect with 30X to **https:**//HOST/bazarr/series

**Software (please complete the following information):**
 - Bazarr: 0.6.9.1
 - OS: Mint Linux

**Additional context**
nginx config:

```nginx
    upstream bazarr {
        server 127.0.0.1:6767;
        keepalive 512;
    }

    location  /bazarr {
        proxy_pass   http://bazarr;
        auth_basic          off;
    }


```

The problem seems to be with the redirect() function in main.py

**Comment by morpheus65535** [comment]
Have you tried with configuration from the wiki?

https://github.com/morpheus65535/bazarr/wiki/Reverse-proxy-Nginx

**Comment by halali** [comment]
I'm not using reverse proxy. But your's is redirected to http:// instead https://

**Comment by kbirger** [comment]
@morpheus65535 - i didn't see that on the wiki. Something like that does work. I suppose the Host header is used to do the check? I know Sonarr and Radarr work without having to rewrite headers. It might still be worthwhile to make it detect in the same way as the other two apps, because it makes it simpler to set up the reverse proxy, but also more reliable

@halali - nope. proxy_pass is the directive that says "for some request, forward that request to THIS backend and proxy back the response". It is in no way a redirect. bazarr does not run its own TLS.

**Comment by morpheus65535** [comment]
Sonarr and Radarr recommand to rewrite headers. You can take a look at Sonarr wiki:

https://github.com/Sonarr/Sonarr/wiki/Reverse-Proxy
