### ISSUE TITLE
Is syncing suppose to take ~ 4 hours?

### ISSUE THREAD

**Issue by Motophan** [morpheus65535/bazarr#2532]
linuxserver docker container

I cant acsess localhost:8989 since sonarr is bare metal, so I use something to the effect of example.com/sonarr, https, port 443.

My domain name is NOT cloudflared cdn proxied, ive checked, but is secured via letsencrypt tls cert via nginx

nginx proxypass is 
```

location /bazarr/ {
    proxy_pass              http://127.0.0.1:6767/bazarr/;
    proxy_set_header        X-Real-IP               $remote_addr;
    proxy_set_header        Host                    $http_host;
    proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto       $scheme;
    proxy_http_version      1.1;
    proxy_set_header        Upgrade                 $http_upgrade;
    proxy_set_header        Connection              "Upgrade";
    proxy_redirect off;

    auth_basic              "What's the password?";
    auth_basic_user_file    /etc/htpasswd.d/htpasswd.gentoo;

    # Allow the Bazarr API through if you enable Auth on the block above
    location /bazarr/api {
        auth_request off;
        proxy_pass http://127.0.0.1:6767/bazarr/api;
    }
}

```

which works, and then in the config.yaml of bazarr I set the /bazarr url path and the /sonarr url path of my sonarr client. 

I have 2500 series

**Comment by morpheus65535** [comment]
Support is done on Discord. 

Never connect Bazarr to Sonarr/Radarr through a reverse proxy. Do a direct connection using your docker host IP and normal port, not 443.
