### ISSUE TITLE
"Automatic Subtitle Sync" sometimes cuts off the first minute of subtitles when using "No Fix Framerate"

### ISSUE THREAD

**Issue by goaliedude3919** [morpheus65535/bazarr#2535]
**Describe the bug**
With "Automatic Subtitle Sync" enabled, it sometimes cuts off the first minute of subtitles.

**To Reproduce**
1. Enable "Automatic Subtitle Sync" (Series Score Threshold is set to 100), and enable "No Fix Framerate"
2. Do a Manual Search for S11E01 of Taskmaster UK
3. Click the Download button for the subtitle found on OpenSubtitles (https://www.opensubtitles.com/en/subtitles/taskmaster-s11e01-its-not-your-fault-1080p-all4-web-dl-aac2-0-x264-ntb)
4. The resulting .srt file is missing the first minute of subtitles.

**Expected behavior**
I expect the sync process to not remove content from the subtitle file.

**Screenshots**
https://i.imgur.com/IQYlg0V.png
https://i.imgur.com/ao7w34V.png

**Software (please complete the following information):**
 - Bazarr: v1.4.3-ls254 by linuxserver.io

**Additional context**

**Comment by morpheus65535** [comment]
Bazarr is relying on ffsubsync which isn't perfect. If you want to improve it, open an issue on their issues tracker. There nothing that can be done about it on our side.

https://github.com/smacke/ffsubsync/
