### ISSUE TITLE
Downloading HI version of subtitles

### ISSUE THREAD

**Issue by phpavelic** [morpheus65535/bazarr#2537]
Since a day or two ago it started downloading a lot of Serbian subtitles and now HI version of those subtitles as well.
It really goes through a lot of movies and series, even the ones that already had subtitles downloaded.

I have 3 languages setup if relevant; croatian, serbian and bosnian.

It most likely happened after the latest update on development branch that gets updated automatically on my instance. 

Note that I have not touched anything for months since it was working as expected.

**Comment by morpheus65535** [comment]
Duplicate #2536
