### ISSUE TITLE
Wrong language extracted from embedded subs

### ISSUE THREAD

**Issue by bonswouar** [morpheus65535/bazarr#2538]
**Describe the bug**
Sometimes I have the wrong language extracted from the embedded subtitles with Bazarr, it seems to happen mostly when there are many different srt languages embedded, and only with the English one (I have no issue with French).

Last example with a TV show containing 42 embedded subtitles, after comparing the Bazarr srt with the embedded ones I found out it was **Filipino** that got extracted instead of **English**.
Here is the mediainfo part for this srt:
```
Text #12
ID                                       : 14
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Title                                    : Filipino
Language                                 : fil
Default                                  : No
Forced                                   : No
```
While it also contains:
```
Text #2
ID                                       : 4
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Title                                    : English [SDH]
Language                                 : English
Default                                  : No
Forced                                   : No
```
**To Reproduce**
1. Set English ("normal or HI") in your Languages
2. Add Embedded Subtitles provider with HI fallback enabled
3. Add a Movie or Show with many different embedded subtitles (although for some - most - it works as expected)
4. Check the English subtitle that got extracted, notice it's not English.

**Expected behavior**
Should extract the right (English) subtitles

**Screenshots**
1.
![image](https://github.com/morpheus65535/bazarr/assets/615053/37a0805b-96de-40a6-b01b-da479b8670fe)
2.
![image](https://github.com/morpheus65535/bazarr/assets/615053/64e6b219-ebe1-40ed-8656-f38798513f0d)
3.
![image](https://github.com/morpheus65535/bazarr/assets/615053/30bf0426-b12f-45bc-80b7-2f4438a60c00)
4.
![image](https://github.com/morpheus65535/bazarr/assets/615053/49411f16-781a-4b41-b8ac-14028e470c03)

**Software (please complete the following information):**
 - Bazarr: v1.4.3
 - Radarr: 5.6.0.8846
 - Sonarr: 4.0.5.1710
 - OS: Debian

**Additional context**
As this doesn't happen with most of the content I'm not sure it's always Filipino that gets selected instead of English, although I'm pretty sure it never ever happened for French. And for this specific show it happened for all episodes consistently

**Comment by JaiZed** [comment]
Bazarr is actually trying to do what you asked it to do.

First of all, note that **fil** is not a proper 2 letter language code for Filipino. Even mediainfo shows you **fil** instead of Filipino for the Language, whereas it shows English for the actual English language track.
Therefore, **fil** will be treated as an unknown language track in this case.

Second, you have chosen the option: _use subtitles with unknown info/language as fallback language_.
Then, you specify **en** as the fallback language.

Putting those two facts together, Bazarr will treat the unknown **fil** language as **en**, the fallback language and save that.

To confirm, please try disabling the option above and extracting the subtitle again to see what the results are. 

There are many videos that have only a single subtitle track that is not marked properly or at all and winds up usually being English. That is the reason for this option to exist. It works well most of the time, until it doesn't, like in this case.

**Comment by bonswouar** [comment]
> First of all, note that **fil** is not a proper 2 letter language code for Filipino. Even mediainfo shows you **fil** instead of Filipino for the Language, whereas it shows English for the actual English language track. Therefore, **fil** will be treated as an unknown language track in this case.

I did expect that, but shouldn't it be less strict about those language codes? _(I see "fil" is in `iso-639-3.tab` although I don't know how it's used)_
This video is from a popular provider (as you can guess with the 42 languages), I don't know what are the good practices but actual Filipinos might have troubles with this provider then..

> Second, you have chosen the option: _use subtitles with unknown info/language as fallback language_. Then, you specify **en** as the fallback language.
> 
> Putting those two facts together, Bazarr will treat the unknown **fil** language as **en**, the fallback language and save that.

I understand that, but as unknown is the fallback, shouldn't it prioritize English HI (that is known)?

> To confirm, please try disabling the option above and extracting the subtitle again to see what the results are.

I confirm it works! It did grab the English HI subtitle.

> There are many videos that have only a single subtitle track that is not marked properly or at all and winds up usually being English. That is the reason for this option to exist. It works well most of the time, until it doesn't, like in this case.

I also understand that, that's why I'd prefer to keep this option on..

If you think it shouldn't be fixed and have recommendations on how to get around that (keep English fallback if unknown, but prioritize English HI when included), I'm open to suggestions!

**Comment by JaiZed** [comment]
We are using and processing the 2 letter language codes that are standard within these files. I don't believe there is a 3 letter code for Filipino, so this provider can do whatever they want with their own media but it's not a standard code.
Actual Filipinos will mostly be streaming on the service and will select the **fil** subtitle track as appropriate via their media player.

I have not looked at the code but the embedded subtitles provider will probably stop looking when it finds the first matching subtitle language. If the undefined **fil** is found first, then it will be used.
Regardless, in the more general case, if there is more than one subtitle track that matches, then you still have the same problem of choosing between the two; like choosing between a normal and director's commentary tracks, both of which are marked as **en**.

Currently, Bazarr has no concept of priorities when trying to choose which subtitle track fulfills the user's request. This may be added at some time in the future.

In this case, I believe you're trying to get perfect automated results from imperfect data. The safest thing to do would be to turn the switch off and to manually intervene more often, if you are most interested in the quality of your subtitles.

**Comment by morpheus65535** [comment]
Filipino doesn't even have a 2 letters language code. It's not included in Bazarr since we only support languages  that have a 2 letters language code. It's then considered and unknown.

**Comment by bonswouar** [comment]
Thanks for your answer!
Yes a priority system could be nice somehow.
Although before going too deep into this, at least prioritize recognized languages before using the fallback would make sense, no?
And if there are more than one match, subtitle position could make sense too (here the English HI sub is the 2nd one, while Filipino is 14th)
It seems this would fix most of my issues personally, although I'm sure there are always hedge cases

**Comment by morpheus65535** [comment]
@vitiko98 anything we can make for this one?

**Comment by vitiko98** [comment]
I'll have a look.

**Comment by vitiko98** [comment]
I'm by no means an expert in the field, but I will make the code assume Filipino is Tagalog.
