### ISSUE TITLE
Docker instance can't download any subtitles "Path does not exist"

### ISSUE THREAD

**Issue by vsercu** [morpheus65535/bazarr#254]
BAZARR Error saving subtitles file to disk for this file:/media/series/South Park/Season 22/South.Park.S22E10.1080p.WEB.h264-TBS.mkv
Exception
Traceback (most recent call last):
 File "/app/bazarr/bazarr/get_subtitle.py", line 119, in download_subtitle
  video = scan_video(path)
 File "/app/bazarr/bazarr/../libs/subliminal/core.py", line 420, in scan_video
  raise ValueError(\Path does not exist\)
ValueError: Path does not exist

v@tali:/media/series/South Park/Season 22$ ls -lah /media/series/South\ Park/Season\ 22
total 4.3G
**drwxrwxrwx  2 emby emby 4.0K Dec 14 23:59 .**
drwxrwxr-x 26 emby emby 4.0K Sep 28 00:01 ..

Any ideas? Running Ubuntu 14.04.

**Comment by morpheus65535** [comment]
How is your path mapping? Do you have checkmark alongside the path of series on main page?

**Comment by vsercu** [comment]
Indeed there also seems to be a problem with all series.
Directory is not empty, this is the listing:

nt@tali:/media/series/South Park/Season 22$ ls -lah
total 4.3G
drwxrwxrwx  2 emby emby 4.0K Dec 14 23:59 .
drwxrwxr-x 26 emby emby 4.0K Sep 28 00:01 ..
-rwxrwxr-x  1 emby emby  343 Sep 28 01:45 season.nfo
-rwxrwxr-x  1 emby emby  38K Sep 28 17:42 south.park.s22e01.internal.720p.web.h264-bamboozle.en.srt
-rwxrwxr-x  1 emby emby  35K Sep 28 17:42 south.park.s22e01.internal.720p.web.h264-bamboozle.en.txt
-rwxrwxr-x  1 emby emby 185M Sep 28 00:00 south.park.s22e01.internal.720p.web.h264-bamboozle.mkv
-rwxrwxr-x  1 emby emby 1.7K Sep 28 18:06 south.park.s22e01.internal.720p.web.h264-bamboozle.nfo
-rwxrwxr-x  1 emby emby  16K Sep 28 01:45 south.park.s22e01.internal.720p.web.h264-bamboozle-thumb.jpg
-rwxrwxr-x  1 emby emby  35K Oct 10 19:04 South.Park.S22E02.A.Boy.and.a.Priest.720p.AMZN.WEBRip.DDP2.0.x264-NTb.en.srt
-rwxrwxr-x  1 emby emby 284M Oct  6 00:00 South.Park.S22E02.A.Boy.and.a.Priest.720p.AMZN.WEBRip.DDP2.0.x264-NTb.mkv
-rwxrwxr-x  1 emby emby 2.3K Oct 10 19:16 South.Park.S22E02.A.Boy.and.a.Priest.720p.AMZN.WEBRip.DDP2.0.x264-NTb.nfo
-rwxrwxr-x  1 emby emby  25K Oct  6 00:05 South.Park.S22E02.A.Boy.and.a.Priest.720p.AMZN.WEBRip.DDP2.0.x264-NTb-thumb.jpg
-rwxrwxr-x  1 emby emby  33K Oct 12 17:23 South.Park.S22E03.The.Problem.With.a.Poo.720p.AMZN.WEBRip.DDP2.0.x264-NTb.en.srt
-rwxrwxr-x  1 emby emby 263M Oct 12 17:19 South.Park.S22E03.The.Problem.With.a.Poo.720p.AMZN.WEBRip.DDP2.0.x264-NTb.mkv
-rwxrwxr-x  1 emby emby 2.5K Oct 17 00:48 South.Park.S22E03.The.Problem.With.a.Poo.720p.AMZN.WEBRip.DDP2.0.x264-NTb.nfo
-rwxrwxr-x  1 emby emby  12K Oct 12 17:24 South.Park.S22E03.The.Problem.With.a.Poo.720p.AMZN.WEBRip.DDP2.0.x264-NTb-thumb.jpg
-rwxrwxr-x  1 emby emby  39K Oct 19 01:26 South.Park.S22E04.720p.HDTV.x264-AVS.en.srt
-rwxrwxr-x  1 emby emby 362M Oct 18 03:38 South.Park.S22E04.720p.HDTV.x264-AVS.mkv
-rwxrwxr-x  1 emby emby 2.0K Oct 19 01:47 South.Park.S22E04.720p.HDTV.x264-AVS.nfo
-rwxrwxr-x  1 emby emby  30K Oct 18 05:18 South.Park.S22E04.720p.HDTV.x264-AVS-thumb.jpg
-rwxrwxr-x  1 emby emby  29K Nov  1 14:18 South.Park.S22E05.720p.HDTV.x264-AVS.en.srt
-rwxrwxr-x  1 emby emby 349M Nov  1 03:41 South.Park.S22E05.720p.HDTV.x264-AVS.mkv
-rwxrwxr-x  1 emby emby 2.1K Nov  1 15:23 South.Park.S22E05.720p.HDTV.x264-AVS.nfo
-rwxrwxr-x  1 emby emby 119K Nov  1 03:59 South.Park.S22E05.720p.HDTV.x264-AVS-thumb.jpg
-rwxrwxr-x  1 emby emby  37K Nov 14 23:59 South.Park.S22E06.iNTERNAL.720p.WEB.h264-BAMBOOZLE.en.srt
-rwxrwxr-x  1 emby emby 185M Nov  8 08:04 South.Park.S22E06.iNTERNAL.720p.WEB.h264-BAMBOOZLE.mkv
-rwxrwxr-x  1 emby emby 2.1K Nov 21 22:23 South.Park.S22E06.iNTERNAL.720p.WEB.h264-BAMBOOZLE.nfo
-rwxrwxr-x  1 emby emby 137K Nov  9 02:02 South.Park.S22E06.iNTERNAL.720p.WEB.h264-BAMBOOZLE-thumb.jpg
-rwxrwxr-x  1 emby emby  36K Nov 21 00:37 South.Park.S22E07.Nobody.Got.Cereal.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264.-YFN.en.srt
-rwxrwxr-x  1 emby emby 845M Nov 16 18:20 South.Park.S22E07.Nobody.Got.Cereal.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264.-YFN.mkv
-rwxrwxr-x  1 emby emby 2.3K Nov 21 01:04 South.Park.S22E07.Nobody.Got.Cereal.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264.-YFN.nfo
-rwxrwxr-x  1 emby emby 101K Nov 16 23:23 South.Park.S22E07.Nobody.Got.Cereal.UNCENSORED.1080p.WEB-DL.AAC2.0.H.264.-YFN-thumb.jpg
-rwxrwxr-x  1 emby emby  37K Dec 11 21:21 South.Park.S22E08.Buddha.Box.1080p.HULU.WEB-DL.AAC2.0.H.264-monkee.en.srt
-rwxrwxr-x  1 emby emby 658M Nov 29 06:38 South.Park.S22E08.Buddha.Box.1080p.HULU.WEB-DL.AAC2.0.H.264-monkee.mkv
-rwxrwxr-x  1 emby emby 1.9K Dec 11 21:26 South.Park.S22E08.Buddha.Box.1080p.HULU.WEB-DL.AAC2.0.H.264-monkee.nfo
-rwxrwxr-x  1 emby emby 531M Dec  7 14:04 South.Park.S22E09.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv
-rwxrwxr-x  1 emby emby 2.1K Dec 15 03:07 South.Park.S22E09.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.nfo
-rwxrwxr-x  1 emby emby  33K Dec 12 02:27 South.Park.S22E09.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb-thumb.jpg
-rwxrwxr-x  1 emby emby 713M Dec 13 08:35 South.Park.S22E10.1080p.WEB.h264-TBS.mkv
-rwxrwxr-x  1 emby emby 1.9K Dec 16 14:48 South.Park.S22E10.1080p.WEB.h264-TBS.nfo
-rwxrwxr-x  1 emby emby  30K Dec 14 23:59 South.Park.S22E10.1080p.WEB.h264-TBS-thumb.jpg


I've played around with different path mappings, but that didn't seem to have effect...

**Comment by vsercu** [comment]
Managed to fix it. It was a typo in my docker config, which mapped the docker volumes wrong. The translation in the GUI was good, but didn't check the directories on disk.

Thanks for your assistance!
