### ISSUE TITLE
A redirection exception occurred.

### ISSUE THREAD

**Issue by sc1994** [morpheus65535/bazarr#2546]
**Describe the bug**

**To Reproduce**
1. Reproduction steps: Subtitle synchronization feature for any episode

**Expected behavior**
A redirection exception occurred.

**Screenshots**
![image](https://github.com/morpheus65535/bazarr/assets/22900800/3d8fd2d9-fc19-42de-a644-9d5fa3e1844e)
![image](https://github.com/morpheus65535/bazarr/assets/22900800/e47e36ae-1e43-4ef8-9993-3b469dc058f8)
![image](https://github.com/morpheus65535/bazarr/assets/22900800/0014dbbf-2f79-4571-b739-857861b047f8)

**Software (please complete the following information):**
 - Bazarr: 1.4.4-beta.9
 - Radarr version 5.7.0.8881
 - Sonarr version 4.0.5.1760
 - OS: Ubuntu 22.04 Docker 26.1.3

**Additional context**
The API for the subtitle synchronization operation redirected me, but the redirection was to my gateway address (client local area network). I can't understand why this is happening, or if there is an issue with my configuration. I don't recall configuring anything related to IP addresses or gateways.

**Comment by morpheus65535** [comment]
Hummm I've never seen that one. It's obviously seems related to something redirecting queries in your browser. Bazarr wouldn't do that and have no idea of your network configuration.

**Comment by morpheus65535** [comment]
No news, good news!
