### ISSUE TITLE
Error saving Subtitles file to disk: AttributeError("module 'pysubs2' has no attribute 'ContentNotUsable'")

### ISSUE THREAD

**Issue by adapowers** [morpheus65535/bazarr#2549]
**Describe the bug**
On some subtitle searches, even with available subs, nothing happens, but the error can be seen in logs:
BAZARR Error saving Subtitles file to disk for this file <file>: AttributeError("module 'pysubs2' has no attribute 'ContentNotUsable'")

**To Reproduce**
1. Go to 'Brave Bang Bravern! (2024) - S01E09'
2. Click on 'Search'
3. Scroll to Settings > Logs

**Expected behavior**
The subtitle would download automatically.

**Software:**
 - Bazarr: 1.44
 - Radarr version: 5.7.0.8882
 - Sonarr version: 4.0.5.1760
 - OS: macOS Sonoma 14.4

**Additional context**

This happens with other files too. It's **possible** that a thing they have in common is characters like . !, but I can't be certain yet.

**Comment by adapowers** [comment]
I just verified that this is only a problem on the `:development` version; 1.43 works okay.

**Comment by morpheus65535** [comment]
@anderson-oki seems related to your upgrade of pysubs2 since 1.4.4-beta.

**Comment by anderson-oki** [comment]
ContentNotUsable has been removed and it is being missused by Bazarr as per https://github.com/tkarabela/pysubs2/commit/c95870b00dcf43f54ecaf01ee62aa3999c112572#diff-c0f1f87b923e2644057bf1b1e3f7b9efd408c5c6f9bd72b5294a626b442ad237.

I will check what is an appropriated fix.

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta.
