### ISSUE TITLE
Linux hosted Bazarr working with Windows hosted Radarr fails as a result of path separator issue between disparate environments

### ISSUE THREAD

**Issue by LesKent** [morpheus65535/bazarr#2555]
**Describe the bug**
I've had Windows based Radarr and Bazarr working for a long time with no issues. I'm in the process of migrating everything to Linux. I setup a new Bazarr server running under Linux to work with the existing Windows Radarr server. After getting it all configured it would synchronize with Radarr correctly but would not download any subtitles. Digging into the logs and database I was able to determine the issue is with how Windows uses '\\' for the path separator and Linux using a '/'. 

On Windows the path to the NAS media is : \\\\xxxx\movies
On Linux the path to the NAS media is: /mnt/xxxx/movies

Path mapping configuration was setup in Bazarr to map Windows Radarr '\\\\xxxx\\movies' to Linux Bazarr '/mnt/xxxx/movies" and this appeared to work correctly for scanning the disk and probing files. 

An example key debug debug error, Bazarr would log during subtitle update process:
bazarr.log.2024-06-25:2024-06-25 02:58:28|DEBUG   |root                            |BAZARR no media with this path have been found in database: \\\\xxxx\\movies\\Embryo (1976)\\Embryo (1976) - [WEBDL-720P][AAC 2.0][X264][imdbid=tt0074475].mkv

Yet the Path field in the table_movies table for this item has:
'\\\\xxxx\\movies\\Embryo (1976)/Embryo (1976) - [WEBDL-720P][AAC 2.0][X264][imdbid=tt0074475].mkv'

Where the path separator between the directory and filename is a '/' failing to match the Windows path with the '\\' separator. 

**Software (please complete the following information):**
 - Bazarr: 1.4.3
 - Radarr version 5.7.0.8882
 - OS: Windows Server 2019, Ubuntu 23.10

**Comment by halali** [comment]
This isn't an issue... use path mappings. If you will have other support question come to discord.

This channel is for issues only

**Comment by LesKent** [comment]
> This isn't an issue... use path mappings. If you will have other support question come to discord.
> 
> This channel is for issues only

This is a bug. I spent many hours confirming this. 

If you read my message I did path mappings correctly and the issue is the separator character stored in the database being converted by Bazarr to the POSIX separator character of the Bazarr hosted OS, that being '/' for the part in between final directory path (per movie media directory) and the title filename, which has nothing to do with path mappings which handles the media root directory mapping. 

The error is because it is trying to lookup in the database a full path provided by Radarr, which uses Windows '\\' separators against the database path field that is modified by Bazarr and stored with a single POSIX separator for the last part of the full path. As I stated the path mapping part works correctly for scanning the correct media directory to search for existing subtitles, both imbedded and external. 

Th bottom line is the path field in the Bazarr database is storing the original Radarr Windows format path sent but Bazarr is changing only the final path separator to POSIX which is causing the lookup bug.

'\\xxxx\movies\Embryo (1976)\\Embryo (1976) - [WEBDL-720P][AAC 2.0][X264][imdbid=tt0074475].mkv' is not equal to
'\\xxxx\movies\Embryo (1976)/Embryo (1976) - [WEBDL-720P][AAC 2.0][X264][imdbid=tt0074475].mkv'
the problem------------------^

**Comment by morpheus65535** [comment]
After investigating, I agree with @halali, you probably had a path mapping issue since we only store unmapped path inside table_movie.path column. Is it possible that you had inverted side in path mapping somehow? I'm still not sure how you achieved that. If you stop Bazarr, rename your database, start Bazarr and let it recreate your database, how does the paths look?

**Comment by anderson-oki** [comment]
@LesKent did you had chance to check the last comment?

**Comment by LesKent** [comment]
I'm sorry I was away on a trip. I did play around with this a little, including as a test writing a SQL trigger to modify the Path field to change the '/' to a '\\' whenever it was stored, and while that did fix the one error I was getting ("no media with this path have been found in database"), but then it got an error in a different place as part of the download process so it still failed. 

I came to the conclusion that there is inconsistent handling of how that separator character between filename and the per movie final directory path but I don't have good enough skills with C# and the Bazarr code base to fix it easily myself and in the end it was easier for me to just migrate Radarr to run under Linux instead since that was my longer term goal, which I did and it is now all working fine for me. 

There is definitely a bug in how these separators are handled between Windows and Linux, and I'm sure it will happen if either side does not match, just the issue will be reversed, but I suspect few people would most likely ever mix OSes this way, which is why you have not seen this problem before. 

I'm confident the path mapping feature can't fix this issue because that part handles the front root part of the path and has nothing to do with the final path separator between the per movie directory and the filename.

**Comment by morpheus65535** [comment]
Unfortunately, if you're unable to run the test we've asked for, we won't be able to determine if there's really an issue here (although I highly doubt it). Like Ia said, we don't store mapped path but simply the one returned by Radarr and map it on the fly when we need to use it.
