### ISSUE TITLE
Updating to beta

### ISSUE THREAD

**Issue by s1h4d0w** [morpheus65535/bazarr#2557]
**Describe the bug**
This is probably a stupid issue, but I'm trying to translate some subs and have the issue from #2519 so I was trying to update my Bazarr to v1.4.4-beta.12. 

I used the Windows installer to install Bazarr because that's pretty much all I know. I've downloaded the `bazarr.zip` for 1.4.4-beta1.2 and tried to extract the contents to my C:\Bazarr folder, but that failed on the `requirements.txt` file, then another, etc. So I've tried any combination of overwriting files, extracting as admin, moving every existing file to a "backup" folder and copying it in then, deleting the migrations folder, etc. Of course I stopped the Bazarr service before trying any of this.

But whatever I do, Bazarr keeps telling me I'm using 1.4.3. How do I update?

**Expected behavior**
That I can update my Bazarr

**Screenshots**
![image](https://github.com/morpheus65535/bazarr/assets/5654654/90c5e5d2-852b-4a25-9926-5c182e2d0274)

**Software (please complete the following information):**
 - Bazarr: v1.4.3
 - Radarr version 5.7.0.8882
 - OS: Windows 11 Professional

**Comment by morpheus65535** [comment]
Why not simply change branch to development in Settings-->General and force a Bazarr update in System-->Tasks?

**Comment by s1h4d0w** [comment]
This is exactly why I started with `This is probably a stupid issue`, because it was. Thank you, that's all I needed! I hadn't seen the branch setting.
