### ISSUE TITLE
Translating subtitles breaks them

### ISSUE THREAD

**Issue by s1h4d0w** [morpheus65535/bazarr#2558]
**Describe the bug**
I decided to translate some English subtitles to German, but when testing I noticed everything got completely desynced after a while. Checking the subtitle files the translation seems to mess up where certain lines go.

For example in the original English subs we have this:
```
49
00:06:01,294 --> 00:06:02,663
Hey.
Hey.

50
00:06:02,730 --> 00:06:05,065
It took a couple weeks,
but it looks like things
```

But the translated German subtitles look like this:
```
49
00:06:01,294 --> 00:06:02,663
Hey.

50
00:06:02,730 --> 00:06:05,065
Hey.

51
00:06:05,132 --> 00:06:06,910
Es hat ein paar Wochen gedauert,
aber es sieht so aus, als ob die Dinge
```

So whatever was said on `50` has been moved to `51`.

**To Reproduce**
1. Take the below file and rename it to `.srt`
2. Use Radarr to translate it

[2-Headed.Shark.Attack.2012.1080p.BluRay.x265-RARBG.en.txt](https://github.com/user-attachments/files/16031003/2-Headed.Shark.Attack.2012.1080p.BluRay.x265-RARBG.en.txt)

**Expected behavior**
That every line of the subtitles is still in the same place

**Screenshots**
![image](https://github.com/morpheus65535/bazarr/assets/5654654/6dec5433-9d12-4bfa-8168-66ef5c637eaa)

English original:
![image](https://github.com/morpheus65535/bazarr/assets/5654654/5492511b-fd52-4213-a04a-0479bbb9cb18)
German translated:
![image](https://github.com/morpheus65535/bazarr/assets/5654654/4bc9599a-3c65-46c5-9956-5ab42629e607)

**Software (please complete the following information):**
 - Bazarr: 1.4.4-beta.12
 - Radarr version 5.7.0.8882
 - OS: Windows 11 Professional

**Comment by morpheus65535** [comment]
I'm able to reproduce the issue but can't find out why Google Translate replace the single newline character between those two "Hey." with two. I'll need to investigate more closely into this but I won't have spare time for a week or two.

**Comment by s1h4d0w** [comment]
No worries, glad you could reproduce! I'd like to translate a bunch of subtitles for cheesy shark movies for the bday of my brother in law, but he won't have his bday for another 1,5 months.

**Comment by jooleer** [comment]
If you don't have too many files and the issue would not be fixed before the files are needed, you could use a website like this one:
https://translate-subtitles.com/

It keeps the sub's time sync correct, however the translations seem slightly different to the ones you posted.

**Comment by anderson-oki** [comment]
We are still investigating, it seems it is an issue with Google Translate itself treats the input based on their own logic, changing slight the input gives different outputs.

For example https://translate.google.com/m?tl=de&sl=auto&q=Just+learn.%0A%0AAnd+kirk%2C%0A%0Anot+everything's+about%0Athe+impossible+conquest.%0A%0ABuck+up+and+pay+attention.%0A%0ANothing's+impossible%2C+sir.%0A%0AHey.%0AHey.%0A%0AIt+took+a+couple+weeks❌

Vs 

https://translate.google.com/m?tl=de&sl=auto&q=not+everything's+about%0Athe+impossible+conquest.%0A%0ABuck+up+and+pay+attention.%0A%0ANothing's+impossible%2C+sir.%0A%0AHey.%0AHey.%0A%0AIt+took+a+couple+weeks

**Comment by s1h4d0w** [comment]
I sadly have 91 files I need to translate. I used those sites but they all have low daily limits, even paid for the VIP service at translatesubtitles.co but quickly found out that while their limited free service works perfect, their VIP service is broken and only translates part of the file.

**Comment by s1h4d0w** [comment]
Correction, https://translate-subtitles.com works really well, so thanks!

**Comment by Martinspire** [comment]
I have the same issue. I think its also interesting that the translation files are being sent with those numbers and time markers. I would've assumed those would be stripped in order to only translate the text and not have it mess with anything else. Which is also what that translate website is doing and why that still works. It would be nice to at least have the option to do that, even if for some subtitles the translation is a bit too fast for the amount of text to read.

**Comment by morpheus65535** [comment]
This one should be fixed in upcoming beta. Sorry for the delay!

**Comment by Martinspire** [comment]
> This one should be fixed in upcoming beta. Sorry for the delay!

So will it be more like how that website above does it (in chunks of text rather than the complete file)?

**Comment by s1h4d0w** [comment]
> > This one should be fixed in upcoming beta. Sorry for the delay!
> 
> So will it be more like how that website above does it (in chunks of text rather than the complete file)?

Bedankt/thanks Martin! I’ve translated everything manually now with the mentioned website. Any plans on trying to detect sentences, merge them, translate them and pull them back apart, so that you have smarter translations and not just line by line translations?

Guessing the pulling them back apart and dividing words over lines would be difficult…

**Comment by morpheus65535** [comment]
> So will it be more like how that website above does it (in chunks of text rather than the complete file)?

It has never been the complete file. We were extracting the text from the subtitles and sending it 5000 characters at a time by grouping before sending and splitting after receiving the translated text.
