### ISSUE TITLE
Create a Security.txt

### ISSUE THREAD

**Issue by 4rdr** [morpheus65535/bazarr#2559]
Can an email be added for security related bugs?

**Comment by morpheus65535** [comment]
I prefer not to. You can always come see me on Discord.

**Comment by 4rdr** [comment]
I do not have a discord and would like to report something.

**Comment by morpheus65535** [comment]
We din't have an official email. It's either here as an issue or in private on Discord.

**Comment by 4rdr** [comment]
I'll just add it to my repo

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Thanks for reporting!
