### ISSUE TITLE
No Subtitles found despite there being subtitles available from OpenSubs

### ISSUE THREAD

**Issue by sasjafor** [morpheus65535/bazarr#256]
**Describe the bug**
There is a problem where subtitles are available on opensubtitles.org, but they are not downloaded by bazarr and manual search returns no results. I have set the score limit to 0 for movies and yet no subtitles are downloaded or found.

**To Reproduce**
Steps to reproduce with example movie
1. Here https://www.opensubtitles.org/en/search/sublanguageid-eng/idmovie-460, subtitles in english are clearly available.
2. No subtitles are found with a manual search ![image](https://user-images.githubusercontent.com/17381598/50183732-3d58c300-0313-11e9-8ba4-6becb3ab96ad.png)

**Expected behaviour**
If minimum score is set to 0, all subtitles that are available on opensubs for that movie should be found by bazarr.

**Software (please complete the following information):**
 - Bazarr: 0.6.9.1
 - Radarr 0.2.0.1217
 - Sonarr2.0.0.5252
 - OS: Linux-4.18.14-unRAID-x86_64-with

**Additional context**
My suspicion is that this is a problem with the name not matching up. "Return of the Jedi" vs "Star Wars: Episode VI - Return of the Jedi". I could try to look at more examples to see if the name is always different when no subtitles are found.

**Comment by morpheus65535** [comment]
Your guess it probably good. The title doesn't match and there is some minimal criteria that must match regardless of the minimum score you set. For movie, title is the one required. For episodes, series title, season number and episode title must match.

**Comment by sasjafor** [comment]
Alright, but that is a problem, because Radarr pulls the name from some database and I don't think I could change it, nor would I want to.
Does Bazarr allow me to change the name of a movie? Even better would probably be an option to choose a custom name when doing a manual search. Kind of like in Plex, where you can choose a name to search for a match without changing the actual name of the library item.
I suspect there is no easy way to handle this automatically, since there would already need to be an existing mapping between Radarr/Bazarr titles and opensubs movie titles, plus a mapping for other databases where the names don't match up.
So a manual adjustment by the users is probably the easiest way to do this.

**Comment by sasjafor** [comment]
The thing is, I don't know of a way of renaming movies in Radarr. Except renaming the file, which I definitely don't want to do, because of plex.

![image](https://user-images.githubusercontent.com/17381598/50214810-76c81780-0381-11e9-8dc8-fe517b6ab8bf.png)
Here you can see that Radarr actually has a name for "Return of the Jedi" which matches the name used by opensubtitles, but Bazarr seems to just use the name of the file without the year. In my case "Return of the Jedi".
Enabling the use scene name feature doesn't help, because I think that only looks at the downloaded files.

**Comment by halali** [comment]
so you have problem with your file name, not with bazarr...
you can easily download movies with better tagged filename...

**Comment by sasjafor** [comment]
No, it's the name that Radarr gave during rename. And scene name is not available because it's an older file.
I think Bazarr should look at the names that Radarr provides to get more reliable matching, because all the information is there. Bazarr just doesn't use it yet.
Or as I said, enable Plex like manual search.

**Comment by sasjafor** [comment]
Alright, maybe it's a problem with my naming scheme in Radarr, simply {Movie Title} ({Release Year}). But good to know that refiners are coming. Thanks for the clarification.

**Comment by morpheus65535** [comment]
Just don’t hold your breath... :-)

**Comment by Visne** [comment]
Is this already fixed? Because I'm having this problem, but I can't really change the file names as Kodi has a pretty strict naming scheme.

**Comment by halali** [comment]
No, its not something that have to be fixed, its not an issue at all. And i think kodi can recognize original filename without renaming it.

**Comment by Visne** [comment]
@halali Well that simply isn't the case, I tried not changing the file/folder names and Kodi recognized an entirely different show.

But since Sonarr/Radarr already know what show/movie is stored where, can Bazarr not access this data directly and use it to search for subtitles? Or is this data not accessible to Bazarr?

**Comment by morpheus65535** [comment]
@Visne Bazarr is using filename, ffprobe, scenename obtain from Sonarr/Radarr API and, on top of that, it refine the previously obtained information using all the metadata available in Sonarr/Radarr. 

Obviously, your issue is somewhere else. I suggest you open your own issue instead of necromancing issue closed for a long time. Don't forget to properly document your case using the issue template and provide screenshot and debug log.
