### ISSUE TITLE
Language Equivalents are not being considered when evaluating existing subs, only when downloading

### ISSUE THREAD

**Issue by rmichelena** [morpheus65535/bazarr#2560]
1.4.4 beta 13

this is minor... but it is
I have language equals set to es = es-MX
I download a movie that has embedded es-MX
the movies profile is set to EN + ES
the embedded es-MX does show on the movie's embedded subs list, if the preference for "Show Only Desired Languages" is off; otherwise it does not show
it goes on to download "es"
so, what happens is that the "language equals" seem not to be applying to embedded subs. Upon further reflecting upon it, I think they're in general not being applied to existing subs (which would consider the "es-MX" as satisfying the profile for "es"), are only being used to evaluate searched subs for download.

it's not a great problem, better to have more subs than to have none, but nevertheless it's not the expected behavior.
The way "language equals" was implemented was nevertheless always a stop-gap measure, a hack . The ideal would be to have a more sophisticated cut-off mechanism (groups within the languages profile) so that the subs can maintain their identity, but still accept either of the language group as satisfying the cut-off.

**Comment by hnorgaar** [comment]
I havent tested if there is a problem with Equal, but to clarify equal as I think you are doing it wrong, as it should be Target= Language profile and Source = The language Bazarr can also look for, so opposite

**Comment by vitiko98** [comment]
Language equals feature is specific to the modified `subliminal` module (the internal system of providers and subtitles). Embedded subtitle languages are handled by another module, so equals are out of scope.

**Comment by morpheus65535** [comment]
> Language equals feature is specific to the modified `subliminal` module (the internal system of providers and subtitles). Embedded subtitle languages are handled by another module, so equals are out of scope.

That answers the question. Thanks for your return!
