### ISSUE TITLE
PWA Not Working. 404 Error

### ISSUE THREAD

**Issue by TaylanTatli** [morpheus65535/bazarr#2562]
**Describe the bug**
PWA was not working on Android, so I checked it on PC and saw a syntax error in manifest.json. While trying to check what's inside manifest.json file, it just shows 404 Not found error. I assume manifest.json is not available for built web page.

**To Reproduce**
1. Go to Bazarr website
2. Open Dev-tools
3. Try to open manifest.json or
4. Just see it on Application tab on Dev tools

**Expected behavior**
It should just be available and works.

**Screenshots**

![Ekran görüntüsü 2024-07-03 005327](https://github.com/morpheus65535/bazarr/assets/754514/c4176ab0-c009-42dd-aadc-7a49de35f8de)
![Ekran görüntüsü 2024-07-03 005353](https://github.com/morpheus65535/bazarr/assets/754514/d8b19cb1-f436-4173-a647-9f3b3efe230b)
![Ekran görüntüsü 2024-07-03 005409](https://github.com/morpheus65535/bazarr/assets/754514/12ee1420-561d-4588-946a-185ae21d23bc)

**Software (please complete the following information):**
 - Bazarr: v1.4.3
 - Radarr version 5.7.0.8882
 - Sonarr version 4.0.6.1805
 - OS: Debian 12.5

**Comment by TaylanTatli** [comment]
Now checked the file in container and it seems there. So it's not used, I guess.
![Ekran görüntüsü 2024-07-03 005905](https://github.com/morpheus65535/bazarr/assets/754514/9302cd5c-d6f2-4434-88a6-ba9e8293aecb)

**Comment by anderson-oki** [comment]
Thank you for your investigation @TaylanTatli. The manifest file was not being properly used during the build. I will work on a fix, might be able to be included on the beta next week.

**Comment by TaylanTatli** [comment]
> Thank you for your investigation @TaylanTatli. The manifest file was not being properly used during the build. I will work on a fix, might be able to be included on the beta next week.

Thank you for your work.

**Comment by anderson-oki** [comment]
It will be fixed on the next Beta release.
