### ISSUE TITLE
Listen on ipv6

### ISSUE THREAD

**Issue by zaidranger** [morpheus65535/bazarr#2565]
**Describe the bug**
Can't access bazarr using ipv6 even after setting :: as address in general settings
**To Reproduce**
1. Go to 'Settings'
2. Click on 'General'
3. Scroll down to 'Address'
4. Input :: or any ipv6 address
5. Nothing happends and bazarr still listen on 0.0.0.0 ipv4

**Expected behavior**
Bazarr starts listening on ipv6

**Software (please complete the following information):**
 - Bazarr: v1.4.4-beta.15
 - OS: Ubuntu Server 24.04

**Additional context**
I'm not sure if this is a configuration error on my part or an intended behaviour, thanks in advance for replying and sorry if this isn't a bug.

**Comment by morpheus65535** [comment]
IPv6 is currently unsupported. It would be a feature request and not a bug. I agree that it should be supported but it would have to prioritized.
