### ISSUE TITLE
Manual search & download works but not bulk download

### ISSUE THREAD

**Issue by vurtomatic** [morpheus65535/bazarr#257]
**Describe the bug**
Bazarr only downloads when manually searching for an episode's subtitle in the Wanted list. 

"Download wanted subtitles" doesn't do anything.

After manually searching and downloading subtitles for an episode, the episode remains in the Wanted list and there is no change to the Badge number.

**To Reproduce**
1. Go to 'Wanted'
2. Click on 'Download wanted subtitles'
3. Nothing happens

1. Go to 'Wanted'
2. Click on search for individual episode
3. Subtitle is downloaded
4. Wanted list isn't updated, episode still shows as missing subtitle

**Expected behavior**
Subtitles should be downloaded, Wanted list and Badge number should be updated

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 0.6.9.1 
 - Sonarr version: 2.0.0.5252 
 - OS: Linux-4.18.20-unRAID-x86_64-with 

**Additional context**
Log attached
[bazarr(1).log](https://github.com/morpheus65535/bazarr/files/2700512/bazarr.1.log)

**Comment by vurtomatic** [comment]
The 3-hour mark came and went. I can see from the log that Bazarr triggered the "Search for wanted subtitles" task and the log shows success:

```
20/12/2018 15:11:17|INFO    |apscheduler.executors.default   |Running job "Search for wanted subtitles (trigger: interval[3:00:00], next run at: 2018-12-20 18:11:17 PST)" (scheduled at 2018-12-20 15:11:17.593643-08:00)|
20/12/2018 15:11:23|INFO    |apscheduler.executors.default   |Job "Search for wanted subtitles (trigger: interval[3:00:00], next run at: 2018-12-20 18:11:17 PST)" executed successfully|
```
But no changes to the Wanted list and no subtitles downloaded.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/2700976/bazarr.log)

**Comment by morpheus65535** [comment]
Is this issue fixed with proper path mapping?

**Comment by vurtomatic** [comment]
Hi, yes it's fixed. The path mapping in Bazarr had to be left empty. Thank you and sorry I forgot to close this.

**Comment by charludo** [comment]
Hi, I have the same issue, but path mapping appears to be correct. (Sorry for reopening this old issue, but the error description matches precisely).

**Comment by morpheus65535** [comment]
@charludo Please open a new issue and fill the required information. I suggest you also provide a debug log where you reproduce the issue.
