### ISSUE TITLE
High disk usage running in Docker on WSL

### ISSUE THREAD

**Issue by tnbao** [morpheus65535/bazarr#2582]
**Describe the bug**
When bazarr runs for a few hours, the disk stores media from sonarr and radarr usage shoots up to 100%. After restart the container it's gone (`docker compose restart bazarr`). After a few hours of running, it happened again.

**Expected behavior**
The container should run fine without any issues.

**Screenshots**
![fulldisk20240716](https://github.com/user-attachments/assets/1a4a5581-1410-4c03-b929-a423af14dbdd)

**Software (please complete the following information):**
 - Bazarr: [v 1.4.3]
 - Radarr version [v 5.7.0.8882]
 - Sonarr version [v 4.0.6.1805]
 - OS: [Windows 11]
 - wsl --version
```
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3593
```

**Additional context**
The WSL distro is Debian 12 (bookworm)

**Comment by anderson-oki** [comment]
Can you identify what is the Task that is running that is causing the high disk usage? Such as a scheduled scan, index, subtitle download, etc?

**Comment by tnbao** [comment]
> Can you identify what is the Task that is running that is causing the high disk usage? Such as a scheduled scan, index, subtitle download, etc?

No tasks are running, subtitles are not downloading too. Just noticed that when bazarr stopped, the issue is gone.

**Comment by morpheus65535** [comment]
Probably some indexing task. Initial scan can be hard on disk IO because of embedded subtitles indexing.

**Comment by anderson-oki** [comment]
@tnbao 

Are you still experiencing issues with high Disk Usage?

**Comment by morpheus65535** [comment]
No news, good news!
