### ISSUE TITLE
YIFY Subtitles Forbidden URL

### ISSUE THREAD

**Issue by lgwapnitsky** [morpheus65535/bazarr#2586]
YIFY Subtitles is throttled due to a forbidden URL, as seen in the log entry:

`Throttling yifysubtitles for 10 minutes, until 24/07/18 04:43, because of: HTTPError. Exception info: "'403 Client Error: Forbidden for url: https://yifysubtitles.ch/movie-imdb/tt' ~ yifysubtitles.py@152"`

**To Reproduce**
Enable YIFY Subtitles and start a subtitle search

**Expected behavior**
No error should occur

**Software (please complete the following information):**
 - Bazarr: v 1.4.3
 - Radarr version 5.7.0.8882
 - Sonarr version 4.0.8.1874
 - OS: Debian 12

**Comment by anderson-oki** [comment]
I made a couple tests myself and it seems to be working fine, they could had been an unstable at the time, you could be trying to search for too many subtitles, or your ip got banned, it is hard to tell.

Can you provide the full log file and we can take a quick look again. See if the issue still persists and let us know.

**Comment by anderson-oki** [comment]
By checking our statistics it seems that something is really happening, there are several users being affected, they might had changed something, let me reopen the issue for now,

**Comment by anderson-oki** [comment]
@lgwapnitsky Can you identify the URL that is causing 403?

**Comment by morpheus65535** [comment]
No news, good news!

**Comment by monorise19891** [comment]
> YIFY Subtitles is throttled due to a forbidden URL, as seen in the log entry:
> 
> `Throttling yifysubtitles for 10 minutes, until 24/07/18 04:43, because of: HTTPError. Exception info: "'403 Client Error: Forbidden for url: https://yifysubtitles.ch/movie-imdb/tt' ~ yifysubtitles.py@152"`
> 
> **To Reproduce**
> Enable YIFY Subtitles and start a subtitle search
> 
> **Expected behavior**
> No error should occur
> 
> **Software (please complete the following information):**
>  - Bazarr: v 1.4.3
>  - Radarr version 5.7.0.8882
>  - Sonarr version 4.0.8.1874
>  - OS: Debian 12
> 
>
