### ISSUE TITLE
zimuku.py does not handle archives with ZIP or RAR suffix, only handles zip or rar

### ISSUE THREAD

**Issue by waterloo3122** [morpheus65535/bazarr#2588]
**Describe the bug**
some subtitles from provider zimuku are suffixed with ZIP or RAR, not normally small cased zip or rar

logs:
2024-07-22 10:35:01,189 - subliminal_patch.providers.zimuku (7f28a286eb38) :  DEBUG (zimuku:340) - Identified zip archive
2024-07-22 10:35:01,189 - subliminal_patch.providers.zimuku (7f28a286eb38) :  DEBUG (zimuku:341) - Identified zip archive with filename attachment; filename="[zmk.pw]xxx.xxx.S02E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.ZIP"

then download error occured

**Expected behavior**
should handle ZIP or RAR suffixed subtitle archives

**Software (please complete the following information):**
 - Bazarr: master

**Comment by waterloo3122** [comment]
<img width="810" alt="image" src="https://github.com/user-attachments/assets/1a5797c3-e75d-469c-a422-82c7adde782b">

adding code to zimuku.py may solve the problem

**Comment by waterloo3122** [comment]
is it also  possilble to hand 7zip archived subtitles?

**Comment by anderson-oki** [comment]
I'm unable to test but filename seems to be fine to cast to lowercase. Using:

`filename = r.headers["Content-Disposition"].lower()`

Any help testing this would be appreciated @waterloo3122.

Can you edit your file and replace the line 319 with the code i sent above.

**Comment by morpheus65535** [comment]
@waterloo3122 were you able to test this?

**Comment by anderson-oki** [comment]
No News, Good News! 

The issue will be applied and it will be fixed on the upcoming beta!
