### ISSUE TITLE
Episode History gives error 500

### ISSUE THREAD

**Issue by mcrommert** [morpheus65535/bazarr#2596]
I was on latest and have moved to beta and this happens on both

When i try to open episode history I get an error 500 and an exception 

> Traceback (most recent call last):
> 
>   File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 870, in full_dispatch_request
> 
>     rv = self.dispatch_request()
> 
>          ^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 855, in dispatch_request
> 
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/app/bazarr/bin/bazarr/../libs/flask_restx/api.py", line 402, in wrapper
> 
>     resp = resource(*args, **kwargs)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/app/bazarr/bin/bazarr/../libs/flask/views.py", line 110, in view
> 
>     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/app/bazarr/bin/bazarr/../libs/flask_restx/resource.py", line 41, in dispatch_request
> 
>     resp = meth(*args, **kwargs)
> 
>            ^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/app/bazarr/bin/bazarr/api/utils.py", line 30, in wrapper
> 
>     return actual_method(*args, **kwargs)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/app/bazarr/bin/bazarr/api/episodes/history.py", line 132, in get
> 
>     \'external_subtitles\': [y[1] for y in ast.literal_eval(x.external_subtitles) if y[1]],
> 
>                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/lib/python3.12/ast.py", line 112, in literal_eval
> 
>     return _convert(node_or_string)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/lib/python3.12/ast.py", line 111, in _convert
> 
>     return _convert_signed_num(node)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/lib/python3.12/ast.py", line 85, in _convert_signed_num
> 
>     return _convert_num(node)
> 
>            ^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/lib/python3.12/ast.py", line 76, in _convert_num
> 
>     _raise_malformed_node(node)
> 
>   File "/usr/lib/python3.12/ast.py", line 73, in _raise_malformed_node
> 
>     raise ValueError(msg + f\': {node!r}\')
> 
> ValueError: malformed node or string: None #
> 
> >

**Comment by morpheus65535** [comment]
It seems you had an episode where external subtitles haven't been indexed yet. Is it still an issue?

**Comment by morpheus65535** [comment]
No news, good news!
