### ISSUE TITLE
Search button on a series does nothing if it has embedded subtitles even though settings is set to extract them

### ISSUE THREAD

**Issue by Imjustjokingwithya** [morpheus65535/bazarr#2599]
**Describe the bug**
Clicking Search (all) button whilst on a series that has embedded subtitles does nothing even though providers has embedded subtitles and subtitles has use embedded subtitles disabled. Searching for indibidual subtitles on episodes works and succesful grabs embedded subtitle, the issue is that search all button does nothing so you have to manually click search on each episodes subtitle which is inconvenient and time consuming.

**To Reproduce**
1. Go to series and choose a show with with media files that have embedded subtitles
2. Click search button near scan disk at the top
3. Nothing happens

**Expected behavior**
Expected behavior would be it succesfully grabbing all wanted subtitles from the media file for all episodes though in this case it does nothing.

**Screenshots**
![1](https://github.com/user-attachments/assets/23a10ba2-c2d7-45ae-911e-4dcb1528a6b8)
![2](https://github.com/user-attachments/assets/d995513a-744b-4cc6-b169-65432c6437e9)

**Software (please complete the following information):**
 - Bazarr: 1.4.3
 - Radarr version 5.7.0.8882
 - Sonarr version 4.0.6.1805
 - OS: Debian GNU/Linux 12 (bookworm)

**Additional context**
Everything is run on docker.

**Comment by morpheus65535** [comment]
Please provide debug log while you're reproducing the issue.

**Comment by Imjustjokingwithya** [comment]
> Please provide debug log while you're reproducing the issue.

Sure, [bazarr.log](https://github.com/user-attachments/files/16546455/bazarr.log). Enabled debug, clicked search all button twice, nothing happened, searched manually for a couple subtitles and it worked, disabled debug.

**Comment by morpheus65535** [comment]
`BAZARR no episode for that sonarrSeriesId have been found in database or they have all been ignored because of monitored status, series type or series tags: 61`

Did you enable monitored only or excluded specific type or tag?
