### ISSUE TITLE
Cannot connect to radarr nor sonarr

### ISSUE THREAD

**Issue by joaopedrocg27** [morpheus65535/bazarr#2600]
**Describe the bug**
I keep getting AssertionError(b'') when creating the sonarr and radarr integration
 
**To Reproduce**

Follow the guide to configure the apps -> https://wiki.bazarr.media/Getting-Started/Setup-Guide/

**Expected behavior**
test should be successfull
**Screenshots**
<img width="1372" alt="image" src="https://github.com/user-attachments/assets/44352ea6-6369-4c26-a895-0ff50db1d100">

**Software (please complete the following information):**
 - Bazarr: [1.4.3]
 - OS: Linux on kubernetes

**Additional context**

using HTTP proxy but this domain is excluded since this is internal traffic to the cluster.
with wrong domain it fails with HTTP errors but with wrong API keys and with the correct one this error appears
external postgresQL DB

**Comment by joaopedrocg27** [comment]
<img width="1450" alt="image" src="https://github.com/user-attachments/assets/bfd32689-e178-4db5-9732-31fa8719db05">
<img width="1447" alt="image" src="https://github.com/user-attachments/assets/5e1f4ea1-06fa-4ed4-8fb6-30486414b8e9">
<img width="1449" alt="image" src="https://github.com/user-attachments/assets/32ddedea-e9a7-47c3-ae1a-190fcb5b2f9f">

**Comment by joaopedrocg27** [comment]
Also weird if I enable the SSL, it removes the `http` part
<img width="1331" alt="image" src="https://github.com/user-attachments/assets/e853f69e-ceb3-4375-ba47-f6efc265dfe1">

**Comment by morpheus65535** [comment]
Do not put the protocol in address field, only the host name.

**Comment by joaopedrocg27** [comment]
I tried everything :) The issue was a space before the address. Maybe a trim is needed here.

Now I am having issues with the proxy, it sends traffic to the exclusions. 

<img width="1256" alt="image" src="https://github.com/user-attachments/assets/bd1ca9d9-5144-4f89-90d5-b8f174ffabc8">
<img width="696" alt="image" src="https://github.com/user-attachments/assets/c2350f32-8ad0-4b1a-b8ed-b9b889a8e3a8">

**Comment by morpheus65535** [comment]
Wildcard wont work. It's a python limitation, nothing we can do about, sorry.

**Comment by joaopedrocg27** [comment]
sorry, read that wrong, this is correct then right? 
<img width="1319" alt="image" src="https://github.com/user-attachments/assets/ca8b9610-9fd2-4b4c-9d1b-8cd2d20f72fd">


I could even remove the sonarr and radarr ones right?

**Comment by joaopedrocg27** [comment]
Working now! Thank you. Awesome app
