### ISSUE TITLE
Issue with MacOS setting to run at login

### ISSUE THREAD

**Issue by recoi1er** [morpheus65535/bazarr#2607]
**Describe the bug**
2 issues on this KB https://wiki.bazarr.media/Getting-Started/Autostart/MacOS/macos/ 

First is that what do you mean by "Paste the following into the document and change the location of the logs to /Users/" are you referring to one of these strings?

    <key>StandardErrorPath</key>
    <string>/usr/local/var/log/bazarr.log</string>

or 

    <key>StandardOutPath</key>
    <string>/usr/local/var/log/bazarr.log</string>

Second issue, Automator is gone from MacOS now. Is there anyway that Bazarr could be released like all the others in this series (Prowlarr, Radarr, Sonarr) where it just has an app icon on install that is easily added to login items?

**To Reproduce**
First first issue, just wanting clarification to a step you have here: https://wiki.bazarr.media/Getting-Started/Autostart/MacOS/macos/ 

For the second issue, on MacOS go to Applications folder > Utilities > Automator is gone, searching online somewhat confirms this that they had planned to remove it back in 2020/21 and would take a couple years, seems like hardly anyone noticed though

**Comment by morpheus65535** [comment]
Contrary to other ARRs, Bazarr is written in Python which isn't compiled and can't be deployed or started like the others.

I haven't wrote those instructions. If you able to help the community, I would gladly accept a PR where you properly modify this file: https://github.com/bazarr/wiki/blob/main/docs/Getting-Started/Autostart/MacOS/macos.md

I'll close this issue as I'm unable to fix it by myself.

**Comment by theblastinglab** [comment]
I don't know Python but I found this guide, looks like you can get it to compile and make installations simpler:

https://medium.com/@jackhuang.wz/in-just-two-steps-you-can-turn-a-python-script-into-a-macos-application-installer-6e21bce2ee71

Or Py2App https://py2app.readthedocs.io/en/latest/

Maybe someone with Python knowledge could do this?

**Comment by recoi1er** [comment]
I don't know Python but I found this guide, looks like you can get it to compile and make installations simpler:

https://medium.com/@jackhuang.wz/in-just-two-steps-you-can-turn-a-python-script-into-a-macos-application-installer-6e21bce2ee71

Or Py2App https://py2app.readthedocs.io/en/latest/

Maybe someone with Python knowledge could do this?

**Comment by morpheus65535** [comment]
We've been trying this a couple of years ago but the large dependencies caused major trouble. We'll see if we can revisit this in the upcoming months.

**Comment by recoi1er** [comment]
Sounds good! Until then I will try to remember to start Bazarr in Terminal!
