### ISSUE TITLE
Bazarr not auto downloading subs in wanted list

### ISSUE THREAD

**Issue by beyondunreal79** [morpheus65535/bazarr#261]
New movies that radar grabs show in sub title wanted list, but they don't auto download. If I go into wanted list I can manually download them, but the movie continues shows in wanted list, Any ideas?

**Comment by morpheus65535** [comment]
Come to Discord channel and you’ll get support.

**Comment by shudack** [comment]
Hi,

I have the same problem. I have some subtitles found it, but they don't auto download.. only manual force download.

Force missing subtitles:
![image](https://user-images.githubusercontent.com/17851196/58269970-945e3a80-7d80-11e9-9830-24b131fdcb08.png)


Manual Download:
![image](https://user-images.githubusercontent.com/17851196/58269921-7690d580-7d80-11e9-8f80-daab5623eb38.png)


Software (please complete the following information):

Bazarr: 0.7.4
Radarr version 0.2.0.1344
Sonarr version 2.0.0.5322
OS: Linux 4.9.177-28 aarch64-with-Ubuntu-18.04-bionic
Python version: 2.7.15rc1

Can you help? I can provide more information.

Best regards,
Shudack

**Comment by morpheus65535** [comment]
@shudack I would say the same: come to Discord and we'll help you configure it properly.
