### ISSUE TITLE
Almost all Arabic subtitles are grabbed by Bazarr as HI-Subtitles while they are not.

### ISSUE THREAD

**Issue by Fhd-pro** [morpheus65535/bazarr#2612]
**Describe the bug**

We have discussed this issue on discord but I just got the chance to submit it for tracking, The issue is all my recent downloaded Arabic subtitles are HI as per Bazarr but they are not. The reason was found due to how the Arabic subtitles are translated by using regex that gives false HI trigger to Bazarr.

All the following regex are mostly found in all Non-HI Arabic subtitles due to many reason grammars language rules or translator choice sometimes .. etc

HI_REGEX = re.compile(r'[*¶♫♪].{3,}[*¶♫♪]|[\[\(\{].{3,}[\]\)\}](?<!{\\an\d})')

**To Reproduce**
Auto downloaded subtitles or manual upload all will trigger false HI subtitle if it's contain the above regex.

**Expected behavior**
Only real impaired subtitles to be tagged as HI.

**Screenshots**
N/A

**Software**
 N/A

**Additional context**

Thank you again and sorry if this post didn't follow specific rules or liens to introduce the issue. **To be honest I thought about this issue and I can't find a perfect solution, the only way is providers must tag the subtitles type manually as part or their services and Bazarr to be able to scan that tag prior to the download but again those providers have no obligation to do that except maybe open subtitles since are profiting and have quality obligation.**

**Comment by Fhd-pro** [comment]
I tried to edit the post but it's not possible. One of the suggested solutions is to CAP these regext. It's not going to fix it but it will surely increase the quality of the determination and you may scan how many are available in HI subtitles against the false ones to reach suitable CAP for these regext.

**Comment by morpheus65535** [comment]
Sorry for the delay, it should be fixed in upcoming beta.

**Comment by Fhd-pro** [comment]
> Sorry for the delay, it should be fixed in upcoming beta.

Thank you for your hard work

 How did you manage it? I couldn't understand much except that the Arabic is excluded now or is the fix something else. I'm interested because it's a complicated case (at least from my humble perspective).

**Comment by morpheus65535** [comment]
> How did you manage it?

If the subtitles is based on a specific language from a list of languages, we now exclude the parenthesis from our detection regex (in fact we have two different regex).
