### ISSUE TITLE
Movie stuck in bazarr list

### ISSUE THREAD

**Issue by ThibeauSwerts** [morpheus65535/bazarr#2613]
**Describe the bug**
Movie stuck in list and can't be deleted or edited due to file or file location simply not existing, sync of the list doesn't update the location to the new one either.

**To Reproduce**
Unfortunately no clue on how it happend or how to reproduce (tried recreating the issue with other movies but no luck)

**Expected behavior**
One of the movies from radarr had to be removed due to bad quality, so it was deleted and the movie was downloaded from another source, the file name changed too with this.

The issue comes in that if I fully delete the movie subtitles I supposedly have according to bazarr or if I want to search for new subtitles for said movie bazarr will throw an error 500 Subtitles file not found or permission issue. since well the location simply doesn't exist on my device,
I tried a sync of the list multiple times, I tried fully deleting the movie out of radarr and sync again only to see the same error 500 again.

**Software (please complete the following information):**
 - Bazarr: v1.4.3
 - Radarr version: 5.8.3.8933
 - OS: Windows 11

**Comment by JaiZed** [comment]
Did you try going to that movie page and clicking on "Scan Disk"?

**Comment by morpheus65535** [comment]
Maybe remove the movie from Radarr, sync in System-->Tasks and reimport the movie in Radarr?

**Comment by ThibeauSwerts** [comment]
ok so maybe i wasn't too clear (that's on me)
The main issue is that the movie is simply not in radarr nor is the file location actually on the device the folder simply does not exist yet bazarr keeps throwing an error 500 can't delete since well it does indeed not exist at all 

**Log printout below:**
Traceback (most recent call last):
  File "c:\\bazarr\\bazarr\\subtitles\\tools\\delete.py", line 65, in delete_subtitles
    os.remove(path_mappings.path_replace_movie(subtitles_path))
FileNotFoundError: [WinError 3] The system cannot find the path specified: \'X:\\\\Movies\\\\IF (2024)\\\\IF (2024) WEBDL-2160p.nl.srt\

**The thing that have been tried are the following:**
1. Deleting the movie in radarr -> sync in bazarr
2. Scan disk (gives the error 500 since the location and the movie simply don't exist)
3. manually triggered both a disk scan and sync after fully deleting the movie from radarr
4. tried making a dummy file with the path and name (also didn't work)

if there is any way to forcefully delete it from the bazarr list the issue could also be resolved but as far as I can see manual deletion from bazarr is not an option

**Comment by JaiZed** [comment]
If you’re on Windows, then get the free SQLite DB Browser, open bazarr.db, search for and remove the offending line from the table_movies table in bazarr.db.
Of course, make a backup first and shutdown Bazarr before editing the database.

**Comment by JaiZed** [comment]
The other option is to simply add the movie in Radarr, along with an actual movie file. Then, after syncing and possibly scanning the disk, Bazarr should pick up the new file.
Also, if X:\Movies no longer exists, you should make sure that it is removed as a root folder in Radarr.

**Comment by ThibeauSwerts** [comment]
The SQlite browser fixed the issue thank you
