### ISSUE TITLE
Error restoring from backup

### ISSUE THREAD

**Issue by aymanbagabas** [morpheus65535/bazarr#2615]
**Describe the bug**
I get this error when trying to restore backup. Bazarr completly crashes and stops working.

```
Aug 11 16:14:37 media bazarr[12712]: ERROR:root:Unable to delete /var/lib/bazarr/db/bazarr.db
Aug 11 16:14:37 media bazarr[12712]: Traceback (most recent call last):
Aug 11 16:14:37 media bazarr[12712]:   File "/nix/store/n9ivz97r313ih9m213wxavngivaisibj-bazarr-1.4.2/share/bazarr/bazarr/utilities/backup.py", line 131, in restore_from_backup
Aug 11 16:14:37 media bazarr[12712]:     os.remove(restore_database_path)
Aug 11 16:14:37 media bazarr[12712]: FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/bazarr/restore/bazarr.db'
Aug 11 16:14:44 media bazarr[12717]: 2024-08-11 16:14:44,408 - flask_migrate                    (7f7739c34740) :  ERROR (__init__:113) - Error: Can't locate revision identified by '452dd0f0b578'
```

**To Reproduce**
1. Put backup files in `backups`
2. Go to the web UI and restore a backup

**Expected behavior**
Backup restores properly

**Software (please complete the following information):**
 - Bazarr: v1.4.2
 - OS: NixOS

**Comment by morpheus65535** [comment]
Deprecated version. Please update and test again.

**Comment by aymanbagabas** [comment]
Updating Bazarr to v1.4.3 fixed the issue, thank you!

**Comment by cryptolukas** [comment]
The problem exists for me on 1.4.5 and 1.5.0 :(

**Comment by morpheus65535** [comment]
> The problem exists for me on 1.4.5 and 1.5.0 :(

No, your error is completely different. Check my answer to your question on Discord.
