### ISSUE TITLE
LegendasDivX with EOFError

### ISSUE THREAD

**Issue by ciberboy** [morpheus65535/bazarr#2618]
**Describe the bug**
Tool is unable to download available subtitles from LegendasDivX

**To Reproduce**
1. Add LegendasDivX as provider
2. Let the tool run the check
3. Try to download a previously confirmed as existing subtitle
4. Do a manual search and confirm that it isn't listed on the search results
5. Go to System --> Providers and the EOFError should be displayed

**Expected behavior**
LegendasDivX to work

**Screenshots**
![image](https://github.com/user-attachments/assets/6350d732-bf57-43cc-bd42-7c946f5ab76e)

**Software (please complete the following information):**
 - Bazarr: 1.4.3
 - Radarr version 5.8.3.8933
 - Sonarr version 4.0.8.1874
 - OS: LibreElec / Docker

**Comment by morpheus65535** [comment]
Did you configured username and password? Can you provide a full debug log while reproducing the issue?

**Comment by ciberboy** [comment]
Yes I did:
![image](https://github.com/user-attachments/assets/4342f731-10a6-4559-8d02-c633cc288947)

This is the latest information from the log.
![image](https://github.com/user-attachments/assets/058e67b6-cc42-4656-8845-acfe53a0d62b)

Also attached the full log
[bazarr.log](https://github.com/user-attachments/files/16589004/bazarr.log)

**Comment by anderson-oki** [comment]
@ciberboy

I'm unable to reproduce the issue, can you please **enable** the debug logs, reset the provider, and try to use the Manual Download subtitles. Once you have done this and get the EOFError again, please re-attach the logs to the issue.

**Comment by anderson-oki** [comment]
No news, good news!
