### ISSUE TITLE
Opensubtitles 100% not added as it is garbage

### ISSUE THREAD

**Issue by aroundmyroom** [morpheus65535/bazarr#262]
**Describe the bug**
Result of sub is 100% match, download manually, but the sub is not added
the log is very clear: the file is garbage. and therefore not added.

**Expected behavior**

WebUI should describe that despite a 100% match the sub could not be added. Due to the reason stated in the log: the file was 'garbage'. Due to the 100% match another source of that sub with a lower score is never being added.

If possible I would like to see a snippit of the download sub to determine if it is gargage yes/no

**Comment by morpheus65535** [comment]
Could you provide a debug log please?

**Comment by aroundmyroom** [comment]
Actually I would .. 

 

But the garbage part is not saved in the log it was in the cli .. 

Damn.

 

But it should have been in this part:

 

02/01/2019 15:37:10|DEBUG   |root                            |BAZARR 4 subtitles have been found for this file: /media/usenet/TV/Bodyguard (2018)/Season 1/Bodyguard.S01E04.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv|

02/01/2019 15:37:10|DEBUG   |root                            |BAZARR Ended searching subtitles for this file: /media/usenet/TV/Bodyguard (2018)/Season 1/Bodyguard.S01E04.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv|

02/01/2019 15:37:26|DEBUG   |root                            |BAZARR Manually downloading subtitles for this file: /media/usenet/TV/Bodyguard (2018)/Season 1/Bodyguard.S01E04.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv|

02/01/2019 15:37:26|INFO    |subliminal.core                 |Downloading subtitle <OpenSubtitlesSubtitle '1956053579' [nl]>|

02/01/2019 15:37:26|INFO    |subliminal.core                 |Downloading subtitle <OpenSubtitlesSubtitle '1956053579' [nl]>|

02/01/2019 15:37:26|INFO    |subliminal.core                 |Initializing provider opensubtitles|

02/01/2019 15:37:26|INFO    |subliminal.providers.opensubtitles|Logging in|

02/01/2019 15:37:27|DEBUG   |subliminal.providers.opensubtitles|Logged in with token 'h5erQsYnot1JtQ7fzE5NmoFywa8'|

02/01/2019 15:37:27|INFO    |subliminal.providers.opensubtitles|Downloading subtitle <OpenSubtitlesSubtitle '1956053579' [nl]>|

02/01/2019 15:37:27|ERROR   |subliminal.core                 |Unexpected error in provider 'opensubtitles', discarding it|Traceback (most recent call last):  File "bazarr/../libs/subliminal/core.py", line 199, in do$

02/01/2019 15:37:27|DEBUG   |subliminal.core                 |Terminating initialized providers|

02/01/2019 15:37:27|INFO    |subliminal.core                 |Terminating provider opensubtitles|

02/01/2019 15:37:27|INFO    |subliminal.providers.opensubtitles|Logging out|

02/01/2019 15:37:27|DEBUG   |subliminal.providers.opensubtitles|Logged out|

02/01/2019 15:37:27|DEBUG   |root                            |BAZARR Subtitles file downloaded for this file:/media/usenet/TV/Bodyguard (2018)/Season 1/Bodyguard.S01E04.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv|

02/01/2019 15:37:27|INFO    |subliminal.score                |Computing score of <OpenSubtitlesSubtitle '1956053579' [nl]> for video <Episode ['Bodyguard', 1x4]> with {'hearing_impaired': False}|

02/01/2019 15:37:27|DEBUG   |subliminal.score                |Using scores {'hash': 359, 'format': 7, 'series': 180, 'audio_codec': 3, 'year': 90, 'hearing_impaired': 1, 'episode': 30, 'season': 30, 'video_codec': 2$

02/01/2019 15:37:27|DEBUG   |subliminal.score                |Found matches set(['episode', 'format', 'series', 'year', 'audio_codec', 'season', 'video_codec', 'resolution', 'release_group'])|

02/01/2019 15:37:27|DEBUG   |subliminal.score                |Matched hearing_impaired|

02/01/2019 15:37:27|INFO    |subliminal.score                |Computed score 360 with final matches set(['episode', 'format', 'series', 'year', 'hearing_impaired', 'audio_codec', 'season', 'video_codec', 'resolution$

02/01/2019 15:37:27|INFO    |subliminal.core                 |Scanning video 'Bodyguard.S01E04.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv' in '/media/usenet/TV/Bodyguard (2018)/Season 1'|

02/01/2019 15:37:27|DEBUG   |subliminal.core                 |Size is 1057940991|

02/01/2019 15:37:27|DEBUG   |subliminal.core                 |Computed hashes {'thesubdb': 'a46fc5f5022c7899814c358248346e5b', 'opensubtitles': 'a12be552a196f8a2', 'shooter': '7ee0ab0b94f00b73065bc5b9d930a179;2eed88$

02/01/2019 15:37:27|ERROR   |subliminal.core                 |Skipping subtitle <OpenSubtitlesSubtitle '1956053579' [nl]>: no content|

 

 

 

But I know probably what is happening

 

Especially if you are new all subs are loaded and checked, I have around 160 shows, what happens is that opensubtitles and addic7ed will ‘ban’ the IP for hammering the site for a period of time

 

It seems that than Bazarr gets some data from opensubtitles but the downloaded sub is than not valid anymore hence you get the message that the srt is bogus and no file is added.

 

I think this is the case. Cause today now everything is settled, the e04 with 100% is downloaded fine

 

I think even if you press download and the issue is ‘no content’ it should be displayed

 

Greets!

Dennis

 





 

Van: morpheus65535 <notifications@github.com> 
Verzonden: donderdag 3 januari 2019 17:23
Aan: morpheus65535/bazarr <bazarr@noreply.github.com>
CC: AroundMyRoom <dennis@aroundmyroom.com>; Author <author@noreply.github.com>
Onderwerp: Re: [morpheus65535/bazarr] Opensubtitles 100% not added as it is garbage (#262)

 

Could you provide a debug log please?

**Comment by morpheus65535** [comment]
Throttling is being implemented in the next upcoming releases and it’s going to take care of this.
