### ISSUE TITLE
Provider podnapisi is showing no result

### ISSUE THREAD

**Issue by nate9976** [morpheus65535/bazarr#2620]
When automatic search or manual, provider "podnapisi" returns no results even if subtitles do exists.

**To Reproduce**
Steps to reproduce the behavior (example on movie: Pirates of the Caribbean: At World's End):
1. Go to Settings -> Providers -> Add provider Podnapisi (Verifiy SSL does not affect the bug)
2. Go to Settings -> Languages -> Add New Profile -> Name: Slovenian -> Add Language -> Slovenian (Normal)
3. Go to Movies -> Pirates of the Caribbean: At World's End -> Edit Movie -> Languages Profile: Slovenian
4. Go to Movies -> Pirates of the Caribbean: At World's End -> Manual -> Search
5. No result

**Expected behavior**
To return/show  existing subtitles.

**Screenshots**
Bazaar result:
![image](https://github.com/user-attachments/assets/35b93398-1580-49fb-a150-af23dded4ae2)

Podnapisi website result:
![image](https://github.com/user-attachments/assets/f40668f4-ddb5-4381-81e3-02b86ab65e77)

XML result from query method in PodnapisiProvider:
![image](https://github.com/user-attachments/assets/80b2c6bb-5b1b-4387-8bd4-cbd8cb3631e9)

**Software (please complete the following information):**
 - Bazarr: 1.4.3

**Additional context**
Posnapisi API returns only 1 result, even if there are multiple results. Most likely different issue/not part of this issue.

**Fix**
Fix:
In file: bazarr > custom_libs > subliminal_patch > providers > podnapisi.py
Line: 212

xml.find() is missing .text

line without fix:
if not xml.find('pagination/results') or not int(xml.find('pagination/results').text):

line with fix:
if not xml.find('pagination/results').text or not int(xml.find('pagination/results').text):

**Comment by morpheus65535** [comment]
Thanks, I've just merged #2621
