### ISSUE TITLE
Important settings are not persisted in database

### ISSUE THREAD

**Issue by abelfodil** [morpheus65535/bazarr#2626]
**Describe the bug**
Hello, I have a Postgres integration with Bazarr and whenever I save Providers, Sonarr or Radarr related settings, upon container destruction the settings are cleared.

**To Reproduce**
1. Have a Postgresql setup
2. Go to Providers tab
3. Add a provider
4. Click save
5. Destroy container or delete Bazarr data folder 
6. Restart the app
7. Settings are cleared

**Expected behavior**
I expect the settings to be persisted inside the database but I do not 

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 1.4.3 ( v1.4.3-ls262 by linuxserver.io)
 - OS:  Linux-5.15.0-118-generic-x86_64-with

**Additional context**
Here's my k8s manifest: https://github.com/arch-anes/self-hosted-services/blob/main/kubernetes/services/bazarr.yml

**Comment by morpheus65535** [comment]
Configurations are saved in config.yaml, not database. The /config directory must be bind somehow to a persistent volume or a directory on your host.

**Comment by abelfodil** [comment]
This is not the case in Radarr nor Sonarr. Would you please reconsider this design decision?

**Comment by morpheus65535** [comment]
> This is not the case in Radarr nor Sonarr. Would you please reconsider this design decision?

We are going the other way and are planning to move more stuff to config.yaml and keep only ephemeral stuff in database that can be rebuilt easily.

There's virtually no chance that we move everything to database.

**Comment by abelfodil** [comment]
Do you have a mechanism to notify users about backward incompatible config? e.g. if you move notification provider config out of DB.

Otherwise, could you pls kindly reference this issue to get notified?

**Comment by morpheus65535** [comment]
You should refer to releases notes. Version number will be increased (minor, not patch level) and we may (or not) add something to the announcements section in Bazarr.
