### ISSUE TITLE
Subdivx timing out

### ISSUE THREAD

**Issue by elkinjosetm** [morpheus65535/bazarr#2633]
**Describe the bug**
Searching for subs on Subdivx is timing out with the following message in the logs:

```

HTTPSConnectionPool(host='www.subdivx.com', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...

```

**To Reproduce**
Just search any movie with this provider

**Software (please complete the following information):**
 - Bazarr: v1.4.3
 - Radarr version: 5.9.1.9070
 - Sonarr version: 4.0.8.1874
 - OS: Linux

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta.
