### ISSUE TITLE
Cutoff language seems broken

### ISSUE THREAD

**Issue by bassterror** [morpheus65535/bazarr#2635]
**Describe the bug**
I switched to beta since v1.4.4-beta.28 because I needed the PostgreSQL fix, but I noticed that the cutoff language doesn't seem to work properly, which wasn't the case in v1.4.3. In the screenshots below you can see that after downloading BG sub it still tries to find EN:FORCED sub even though BG is the cutoff.

**Expected behavior**
After reaching the cutoff to stop searching for the other languages.

**Screenshots**
![lang_prof](https://github.com/user-attachments/assets/59ef3c53-992e-4da9-9ba4-1400c69a0e06)

![io2](https://github.com/user-attachments/assets/b9c4dce5-d21a-4437-bc50-ad411502c9a1)

![wanted](https://github.com/user-attachments/assets/e47c23ab-db4e-43db-b4e9-7d84408fa782)

**Software (please complete the following information):**
 - Bazarr: 1.4.4-beta.34
 - Radarr: 5.9.1.9070-ls234
 - Sonarr: 4.0.9.2244-ls252
 - OS: Linux

**Comment by morpheus65535** [comment]
It should be fixed in upcoming beta. Can you test and confirm please?

**Comment by bassterror** [comment]
Tested it and it's working perfectly. Thank you!
