### ISSUE TITLE
Web interface not accessible

### ISSUE THREAD

**Issue by UniverseXXX** [morpheus65535/bazarr#2637]
**Describe the bug**
The web interface is not opening, and I am seeing this browser error - This site can’t be reached.
This started happening a month ago, I'm running a dev version, however, switching to a stable version won't fix the issue.

**Expected behavior**
Accessing web interface as normal.

**Screenshots**

> Linuxserver.io version: v1.4.4-beta.35-ls625
> Build-date: 2024-08-27T06:34:45+00:00
> ───────────────────────────────────────
> [custom-init] No custom files found, skipping...
>     
> /app/bazarr/bin/bazarr/../custom_libs/subzero/language.py:165: SyntaxWarning: invalid escape sequence '\.'
>   IETF_MATCH = ".+\.([^-.]+)(?:-[A-Za-z]+)?$"
> /app/bazarr/bin/bazarr/../custom_libs/subzero/language.py:166: SyntaxWarning: invalid escape sequence '\.'
>   ENDSWITH_LANGUAGECODE_RE = re.compile("\.([^-.]{2,3})(?:-[A-Za-z]{2,})?$")
> /app/bazarr/bin/bazarr/../custom_libs/subzero/language.py:170: SyntaxWarning: invalid escape sequence '\.'
>   language_match = re.match(".+\.([^\.]+)$" if not ietf
> Connection to localhost (127.0.0.1) 6767 port [tcp/*] succeeded!
> [ls.io-init] done.
> 2024-08-27 10:01:52,104 - root                             (7fc438b75b30) :  INFO (signalr_client:122) - BAZARR trying to connect to Sonarr SignalR feed...
> 2024-08-27 10:01:52,108 - root                             (7fc438958b30) :  INFO (signalr_client:189) - BAZARR trying to connect to Radarr SignalR feed...
> 2024-08-27 10:01:52,108 - root                             (7fc4698d0b28) :  INFO (server:79) - BAZARR is started and waiting for request on http://0.0.0.0:6767
> 2024-08-27 10:01:52,113 - root                             (7fc43873bb30) :  INFO (signalr_client:150) - BAZARR SignalR client for Sonarr is connected and waiting for events.
> 2024-08-27 10:01:52,118 - root                             (7fc43851eb30) :  INFO (signalr_client:217) - BAZARR SignalR client for Radarr is connected and waiting for events.
> 2024-08-27 10:01:52,235 - root                             (7fc438958b30) :  ERROR (series:152) - BAZARR cannot insert series /tv/Dark Matter (2024) because of (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "table_shows_path_key"
> DETAIL:  Key (path)=(/tv/Dark Matter (2024)) already exists.
> [SQL: INSERT INTO table_shows ("tvdbId", "alternativeTitles", audio_language, fanart, "imdbId", monitored, overview, path, poster, "profileId", "seriesType", "sonarrSeriesId", "sortTitle", tags, title, year) VALUES (%(tvdbId)s, %(alternativeTitles)s, %(audio_language)s, %(fanart)s, %(imdbId)s, %(monitored)s, %(overview)s, %(path)s, %(poster)s, %(profileId)s, %(seriesType)s, %(sonarrSeriesId)s, %(sortTitle)s, %(tags)s, %(title)s, %(year)s)]
> [parameters: {'tvdbId': 393159, 'alternativeTitles': "['Materia oscura', 'Dark Matter Der Zeitenlaeufer']", 'audio_language': '[]', 'fanart': '/MediaCover/560/fanart.jpg', 'imdbId': 'tt19231492', 'monitored': 'True', 'overview': 'Jason Dessen is abducted into an alternate version of his life. To get back to his true family, he embarks on a harrowing journey to save them from the most terrifying foe imaginable: himself.', 'path': '/tv/Dark Matter (2024)', 'poster': '/MediaCover/560/poster-250.jpg', 'profileId': 1, 'seriesType': 'standard', 'sonarrSeriesId': 560, 'sortTitle': 'dark matter 2024', 'tags': '[]', 'title': 'Dark Matter (2024)', 'year': '2024'}]
> (Background on this error at: https://sqlalche.me/e/20/gkpj)
> 2024-08-27 10:01:53,740 - root                             (7fc4380e4b30) :  ERROR (movies:35) - BAZARR error when trying to select this movie from database: /movies/The Other Boleyn Girl (2008)/The Other Boleyn Girl (2008) - Bluray-1080p - h265 DTS-HD MA - - RuTracker.mkv
> 2024-08-27 10:01:54,176 - root                             (7fc4380e4b30) :  ERROR (movies:35) - BAZARR error when trying to select this movie from database: /movies/Kill Bill 1 (2003)/Kill Bill Vol. 1 (2003) - WEBDL-2160p - x265 DTS-HD MA - Uncut - BLKFLX.mkv

**Software (please complete the following information):**
 - Bazarr: v1.4.4-beta.35
 - Radarr: 5.9.1.9070
 - Sonarr: 4.0.9.2244
 - OS: Docker

**Comment by anderson-oki** [comment]
GitHub issues are for bug report. This seems to be an isolated issue in due to some configuration or something that was not properly updated in the database. Please go to Discord to seek for support help.
