### ISSUE TITLE
[Provider request] Add subtitri.bg то Bazarr

### ISSUE THREAD

**Issue by iNfRaS0NiC** [morpheus65535/bazarr#2642]
Hello,
It would be great (if possible) to add https://subtitri.bg/ as a provider to your excellent Bazarr. 
This website is starting to make more and more subtitles in Bulgarian, so I think its a must.
Thank you.

**Comment by morpheus65535** [comment]
https://wiki.bazarr.media/Troubleshooting/FAQ/#im-missing-or-want-a-subtitle-provider-added-to-bazarr
