### ISSUE TITLE
Greek is not the same as Modern Greek

### ISSUE THREAD

**Issue by Vitaspiros** [morpheus65535/bazarr#2650]
**Describe the bug**
I have some movies imported from Radarr whose audio language shows up as "Greek". If I set up a profile with the language "Modern Greek (1453-)" and the "Exclude if matching audio" option set, Bazarr tries to download subtitles even for the Movies with Greek audio, because "Greek" is not "Modern Greek (1453-)". This is semi-solved by enabling the "Deep analyze media file to get audio tracks language" option, which is not very accurate.

**To Reproduce**
1. Have some movies with Greek audio
2. Go to Settings > Languages
3. Add "Modern Greek (1453-)" to the Languages Filter
4. Create a Language Profile with the language "Modern Greek (1453-)" and the option "Exclude if matching audio set"
5. Save
6. Bazarr will show that there are missing subtitles for the movies with Greek audio language

**Expected behavior**
Bazarr should recognize that the "Modern Greek (1453-)" language is the same as "Greek" and not show missing subtitles for that movie.

**Screenshots**
The first three movies with Greek audio language show missing subtitles:
![Screenshot from 2024-09-07 12-44-44](https://github.com/user-attachments/assets/22baa2eb-954b-47ab-91a7-19708761876a)

With the "Deep analyze media file to get audio tracks language" on, the movies get recognized as "Modern Greek (1453-)", which makes them not show any missing subtitles:
![Screenshot from 2024-09-07 12-45-02](https://github.com/user-attachments/assets/e64b2a5b-1a2d-4f79-b29d-0f8f2cf22220)
However, this is not a solution, because (at least in my case), this option misinterprets many movies' languages.

**Software (please complete the following information):**
 - Bazarr: v1.4.3 (LSIO container running on Docker)
 - Radarr version: 5.9.1.9070 (LSIO container running on Docker)
 - Sonarr version: I don't use Sonarr yet.
 - OS: Debian 12 (Bazarr and Radarr are running as Docker containers)

**Additional context**
No additional context.

**Comment by hnorgaar** [comment]
That will depend on the naming of the subs with language code .EL, I guess they are named with GR and that Bazarr wont recognize that. Should be EL

**Comment by morpheus65535** [comment]
> That will depend on the naming of the subs with language code is EL, I guess they are named with GR and Bazarr wont recognize that. Should be EL

I think he's referring to the full name that doesn't match between Bazarr and Sonarr/Radarr.

**Comment by Vitaspiros** [comment]
> > That will depend on the naming of the subs with language code is EL, I guess they are named with GR and Bazarr wont recognize that. Should be EL
> 
> I think he's referring to the full name that doesn't match between Bazarr and Sonarr/Radarr.

Idk really, it could be both, but the problem is that I don't want Greek subtitles for the movies that are already in Greek, and because of this it doesn't work.

**Comment by morpheus65535** [comment]
This should be fixed in upcoming beta. Let me know if there's still an problem.
