### ISSUE TITLE
Some SyntaxWarning from custom_libs/subzero/language.py

### ISSUE THREAD

**Issue by FaBMak** [morpheus65535/bazarr#2656]
**Describe the bug**
Some SyntaxWarning from custom_libs/subzero/language.py

**To Reproduce**
1. Run Docker Bazarr from LISO - https://docs.linuxserver.io/images/docker-bazarr/
2. docker logs bazarr
3. See Warnings

**Extracted LOGs**
`/app/bazarr/bin/bazarr/../custom_libs/subzero/language.py:165: SyntaxWarning: invalid escape sequence '\.'  
  IETF_MATCH = ".+\.([^-.]+)(?:-[A-Za-z]+)?$"  

/app/bazarr/bin/bazarr/../custom_libs/subzero/language.py:166: SyntaxWarning: invalid escape sequence '\.'  
  ENDSWITH_LANGUAGECODE_RE = re.compile("\.([^-.]{2,3})(?:-[A-Za-z]{2,})?$")  

/app/bazarr/bin/bazarr/../custom_libs/subzero/language.py:170: SyntaxWarning: invalid escape sequence '\.'  
  language_match = re.match(".+\.([^\.]+)$" if not ietf
`

**Software:**
 - Bazarr: [Linuxserver.io version: v1.4.3-ls264]
 - OS: [Linux Debian 12]

**Additional context**
After escaping this lines with an additional \ (Backslash), the Warnings are gone.

**Comment by morpheus65535** [comment]
Should be fixed in upcoming 1.4.4. Reopen if it's not the case.

**Comment by gonsaaa** [comment]
Just updated to 1.44 and this is still appearing.

**Comment by morpheus65535** [comment]
Will be fixed in upcoming beta. Thanks for reporting!
