### ISSUE TITLE
Embedded Subtitles unable to detect pt-BR

### ISSUE THREAD

**Issue by raphaelshiga** [morpheus65535/bazarr#2662]
Using MKVToolNix is possible to check the presence of Brazilian Portuguese subtitles as a track, but these subtitles are not imported on Bazarr.

Why?
The Brazilian subs (pt-BR) are recognized as plain portuguese (por) by ffprobe.

It seems an issue related to ffprobe itself (I've tried some ffprobe commands to list all tags and I couldn't find the one responsible for the Region). Even so, I'm not familiar to Embedded Subtitles implementation on Bazarr, and if it is exclusively based on ffprobe to manage subtitles, so I decided to post here.

Accordingly to Matroska website (https://www.matroska.org/technical/elements.html), the element LanguageBCP47 (where pt-BR is set) should "invalidate", other Language elements set on the same track.

The expected behavior would be to check for the element "LanguageBCP47" instead of the "Language" element (this last one visually showing as an obsolete element on MKVToolNix).

Software:
 - Bazarr: 1.4.4
 - OS: https://github.com/linuxserver/docker-bazarr

Screenshots:

MKVToolNix
![image](https://github.com/user-attachments/assets/e4cf2afc-6119-4f8f-87df-8a036a090e5d)

Bazarr Logs:
![image](https://github.com/user-attachments/assets/5bac0c76-132f-44e5-a7df-a953ce57f07b)
![image](https://github.com/user-attachments/assets/0795b32a-64b2-439f-9b44-8ccb846c4826)
![image](https://github.com/user-attachments/assets/62fb9c12-3e89-4e07-abdb-bc9079d38903)

PS. It seems like all languages that have a Region variation would have the same issue, but speaking about portuguese itself, I can assure that even being the same language, the region variation is huge. (For instance, between Brazil and Portugal).

**Comment by morpheus65535** [comment]
Can you provide a link to a video file with this kind of tag so I can adapt the code to use it?

**Comment by raphaelshiga** [comment]
@morpheus65535 yes, sure.

Follow a link with a public domain movie that contains pt-BR subtitles:

https://1drv.ms/u/s!Ajs7vyy5cbwkgsl0vnPXEdMExGeAaA

This is not the original movie that I had the issue, a pt-BR sub can be found in this case, but I could see in the logs that's not using the embedded subtitles plugin (it's downloading from opensubtitles.com).

Even so, the missing subtitle will be easily reproduced if you only let the embedded subtitle plugin as available to test.

**Comment by morpheus65535** [comment]
ffprobe doesn't report this tag so there's not much we can do about it:
```
  Stream #0:2(por): Subtitle: subrip (srt) (default)
      Metadata:
        BPS             : 69
        DURATION        : 02:09:00.924000000
        NUMBER_OF_FRAMES: 1668
        NUMBER_OF_BYTES : 66993
        _STATISTICS_WRITING_APP: mkvmerge v87.0 ('Black as the Sky') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2024-09-23 02:46:59
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
```

**Comment by raphaelshiga** [comment]
@morpheus65535

Yes, I mentioned and tested ffprobe/ffmpeg other parameters expecting some different argument that could show this info, but I couldn't find any. After open this issue I became aware of a feature request on ffmpeg project to implement this IETF BCP 47 tag/element check, but it is not yet implemented.

I don't really know how extensive or difficult would be to implement a different approach on bazarr itself. Where instead of relying on ffprobe to get this additional info, you could use mkvtoolnix.

Follow a screenshot of "mkvinfo filename.mkv" result showing this additional element.

![Screenshot_20240924_182842_JuiceSSH](https://github.com/user-attachments/assets/29e17860-cc99-4381-8e13-7330e5d30474)

Food for thought.

**Comment by morpheus65535** [comment]
Bazarr rely on an external Python module named knowit to parse media file. This module support ffprobe, mediainfo and mkvmerge. Bazarr implement both ffprobe and mediainfo but they doesn't seem to  support BCP47. We currently have no support for mkvmerge which seems to support BCP47 correctly. Unfortunately, I have no plan to support an additional utility as it cause multiple changes to the caching code and will require a lot of testing to prevent unwanted cache invalidation and full re-indexing of media files. I guess, for now, you'll have to wait for ffprobe to merge that PR. :-/

**Comment by hfoletto** [comment]
Hey!

Sorry for the late reply here, just wanted to check if there has been any updates on this topic.

Thanks!
