### ISSUE TITLE
Manual upload won’t work with certain language profiles

### ISSUE THREAD

**Issue by frant4** [morpheus65535/bazarr#2670]
**Describe the bug**
When a language profile has both a normal subtitle type and a forced subtitle type in the same language, manual upload won’t work for movies/series with that language profile assigned.

https://discord.com/channels/382221826564030464/540191312964485120/1285747674620100630

**Software (please complete the following information):**
 - Bazarr: [v1.4.4]
 - OS: [Linux-6.1.99-Unraid-x86_64-with]

**Comment by morpheus65535** [comment]
Should be fixed by upcoming #2675

**Comment by anderson-oki** [comment]
#2675 is merged. It will be fixed on the upcoming beta.
