### ISSUE TITLE
Error when searching for a show

### ISSUE THREAD

**Issue by timeshadowrider** [morpheus65535/bazarr#2674]
Tried searching for a show and got this error.

Error: [@mantine/core] Duplicate options are not supported. Option with value "My Happy Marriage (2023)" was provided more than once at Ic (http://********/assets/@mantine/core-Su47KUfs.js:44:144901) at Xo (http://********/assets/@mantine/core-Su47KUfs.js:44:146074) at Uc (http://********/assets/vendors-BAK-HwJ-.js:38:17000) at yu (http://********/assets/vendors-BAK-HwJ-.js:40:3139) at Zm (http://********/assets/vendors-BAK-HwJ-.js:40:44737) at Ym (http://********/assets/vendors-BAK-HwJ-.js:40:39727) at W0 (http://********/assets/vendors-BAK-HwJ-.js:40:39655) at vl (http://********/assets/vendors-BAK-HwJ-.js:40:39508) at Pu (http://********/assets/vendors-BAK-HwJ-.js:40:35875) at Ud (http://********/assets/vendors-BAK-HwJ-.js:40:36678)

**Comment by anderson-oki** [comment]
@timeshadowrider 

What is the Bazarr version you are running? Also, do you have 2 records of My Happy Marriage (2023)? 🤔

**Comment by timeshadowrider** [comment]
Version - v1.4.4

Yes, I have a copy of the Anime as well as the live action movie one each
in Radar and Sonarr

**Comment by anderson-oki** [comment]
@timeshadowrider 

One more question. Do they have the same sonarrId or radarrId or they are different? Only the title and year is the same?

**Comment by timeshadowrider** [comment]
I'm not sure how to find the id....

Both are using the trash guide naming:

Radarr looks like this:

My Happy Marriage (2023) {imdb-tt19869122} 

Sonarr: just says "Metadata is provided by TheTVDB"

Anime naming:

{Series TitleYear} - S{season:00}E{episode:00} - {absolute:000} - {Episode CleanTitle} [{Custom Formats }{Quality Full}]{[MediaInfo VideoDynamicRangeType]}[{MediaInfo VideoBitDepth}bit]{[MediaInfo VideoCodec]}[{Mediainfo AudioCodec} { Mediainfo AudioChannels}]{MediaInfo AudioLanguages}{-Release Group}

**Comment by anderson-oki** [comment]
Let me ask a different question. if you go to Series or Movies list, the URL has the id it has on bazarr as a number. Do you have 3 unique ones?

`{url}/series/{id}` or `{url}/movies/{id}`

**Comment by anderson-oki** [comment]
> I only have the 2, on in Radar and one in Sonarr

Ah okay @timeshadowrider so nevermind my question. I understand now.

**Comment by timeshadowrider** [comment]
TV Series
http://10.0.0.100:6767/series/848

Movies:
http://10.0.0.100:6767/movies/1162

**Comment by anderson-oki** [comment]
It will be fixed on the upcoming beta.

**Comment by timeshadowrider** [comment]
Awesome, thanks for the update!
