### ISSUE TITLE
+100% CPU load after < 24h

### ISSUE THREAD

**Issue by logicalshrapnel** [morpheus65535/bazarr#268]
**Describe the bug**
Less than 24 hours after restarting the bazarr service the top command reports it using >100% CPU. It runs fine for a long time and downloads subtitles as desired, but eventually it eats up the processor and never lets go. This is 100% reproduce-able.

**To Reproduce**
1. Start the bazarr service
2. Wait serveral hours
3. Check load on server
4. kill bazarr
5. Load on server returns to normal

**Expected behavior**
Normal load

**Screenshots**
    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 2396 myuser 20   0 1974080 426376   9596 S 122.5  3.5 501:37.64 python

**Software (please complete the following information):**
Bazarr version
0.6.9.1
Sonarr version
2.0.0.5252
Radarr version
0.2.0.1217
Operating system
Linux-4.9.0-8-amd64-x86_64-with-debian-9.6
Python version
2.7.13

**Additional context**
Let me know what logs etc. to attach and I'll gladly assist.

**Comment by morpheus65535** [comment]
I've seen your comment on Discord. I suggest you come back to us on Discord next time you face this issue with a debug log and we'll happily help you. :-)
