### ISSUE TITLE
Translating subs

### ISSUE THREAD

**Issue by FiyiK** [morpheus65535/bazarr#2684]
**Describe the bug**
Translating 1 subtitle takes 10 minutes (depending on the characters)

**To Reproduce**
Click translate

**Expected behavior**
Translating happened in a few seconds before

**Software (please complete the following information):**
 - Bazarr: newest
 - Radarr version newest
[bazarr.log](https://github.com/user-attachments/files/17165120/bazarr.log)

 - Sonarr version newest
 - OS: W11

LOG added

**Comment by morpheus65535** [comment]
Please enable debug log in Settings-->General and run the translation again. Disable debug logging then provide the new log file.

**Comment by FiyiK** [comment]
Log added: 
[bazarr (1).log](https://github.com/user-attachments/files/17174482/bazarr.1.log)

**Comment by morpheus65535** [comment]
> I forgot to disable debug logging. I disabled and added new log file; 
> 
> [bazarr (2).log](https://github.com/user-attachments/files/17174488/bazarr.2.log)
> 
> 
> 
> I must say, today was a little faster then yesterday, but still very slow compared to previous bazarr editions.

I'm AFK for the weekend and I'll look into this on Monday.

Unfortunately, we'll never be able to use Google Translate the way we did before since it's corrupting text format on multilines text sent as a whole. We have to send each line as a separate request so it take more time but at least it provide working subtitles.

**Comment by FiyiK** [comment]
Sure, thank you.

Maybe something important. Movies translates very fast. So looks like radarr is giving no issues. Only issues with content from Sonarr.

**Comment by FiyiK** [comment]
Do we have any possibilities of AI translate or Bing translator instead for bazarr?

**Comment by morpheus65535** [comment]
We use the deep-translator module to interface with Google Translate. It supports other translation solutions but it would require additional code to support them (frontend and backend). https://deep-translator.readthedocs.io/en/latest/

**Comment by FiyiK** [comment]
I would like to support you again if we could add such feature.. What do you think?

**Comment by morpheus65535** [comment]
We're dependent on the throttling done on Google side. If they ask to slow down, we comply since we do not want your IP to be blocked from further requests. It may be the reason why you get slow results using batch mode. Single element translation seems to works fine.

**Comment by morpheus65535** [comment]
From your logs, I see 61 seconds to send 988 requests to Google Translate. Of course it's not as good as it was but it's not that bad. All other translations took less than a minute. We're far from the 10 minutes you said earlier.

**Comment by morpheus65535** [comment]
> I would like to support you again if we could add such feature.. What do you think?

I'm taking about this. We surely need to think about an alternative. You're donation will of course be appreciated once we've implemented such feature.

**Comment by FiyiK** [comment]
No true, maybe the last time i put that log, it was a little faster as usual, but it is true that sometimes when i badge translate, over time it gets slower and slower even to 5/10 minutes for one sub. I remember you told me some time ago to make a donation externally. Can you point me in the right direction? I'll donate some funds in advance as a sign of appreciation.

Your awesome as always. Thank you to prioritize and look for alternative options.

**Comment by morpheus65535** [comment]
You can find the donation link in Bazarr UI at the bottom left (small heart icon).

**Comment by morpheus65535** [comment]
There's not much to do, we move to slower translation to have better result and prevent corruption of subtitles file (lines added or removed). It's far from optimal but I don't have time to implement another kind of translation engine that would use something else than Google Translate website.

**Comment by FiyiK** [comment]
Can i not install older versions and disable auto update? This is really something which makes bazarr unusable for me.

**Comment by morpheus65535** [comment]
Yes you can but you wont get all the newest fixes and features. TBH, if you're relying on Bazarr only to translate subtitles, you may not be using the proper tools. Subtitles translation is a last resort solution and this isn't what we prioritize for Bazarr since we want to offer a downloading tools for online providers.

**Comment by FiyiK** [comment]
No, i rely on Bazarr for many other things, other things which work excellent, but translating subs is just one of the important things for me which i need regularly.

However, thank you a lot, i see that you're looking for solutions. That's awesome.

**Comment by morpheus65535** [comment]
I'll close this issue since I keep thinking about a solution to do this better but right now I don't have anything specific in mind. I'll keep that on my to-do list.
