### ISSUE TITLE
SubDivx not finding subtitles (JSONDecodeError)

### ISSUE THREAD

**Issue by avraham** [morpheus65535/bazarr#2686]
**Describe the bug**
SubDivx is not finding subtitles. Enabling debug mode, an error JSONDecodeError is shown.

**To Reproduce**
1. Go to 'wanted movie or episode'
2. Click on 'search subtitle'
3. See not found message while subtitles are actually available on the website.
4. See error in log

**Expected behavior**
It should find subtitles 

**Screenshots**
<img width="1022" alt="Screenshot 2024-09-27 at 12 32 17 p m" src="https://github.com/user-attachments/assets/cf8478f6-0361-4a03-ba00-4b7d08605f18">

**Software:**
 - Bazarr: 1.4.4
 - Radarr version 5.11.0.9244
 - Sonarr version 4.0.9.2244
 - OS: Linux-5.10.103-v8+-aarch64-with

**Log File**
[Bazarr system log (1).log](https://github.com/user-attachments/files/17168820/Bazarr.system.log.1.log)

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Thanks for reporting!
