### ISSUE TITLE
Translations of embedded English hearing-impaired subtitles to Portuguese result in a `500 Error`

### ISSUE THREAD

**Issue by YetAnotherTechBro** [morpheus65535/bazarr#2689]
**Describe the bug**

Firstly, thank you for the fantastic work on the subtitle translation refactor. It has become much more reliable and accurate! 🙇 

Recently, I’ve encountered an issue when translating embedded English hearing-impaired subtitles into Portuguese. The error message says `Error 500` and `You have disconnected from the server`.

<img width="452" alt="image" src="https://github.com/user-attachments/assets/41694af8-0fad-4723-85ac-a3c0cfe75efc">

This error doesn't happen when translating to other languages like Spanish or when translating non-hearing-impaired English subtitles into Portuguese. Moreover, if I use the `Remove HI Tags` tool, the translation proceeds without issue.

Despite the error message, I can still use Bazarr normally, which leads me to believe it might be an uncaught exception with a generic error message.

**To Reproduce**
1. Enable "Embedded Subtitles" as a provider.
1. Locate content with embedded English hearing-impaired subtitles and download it.
1. Attempt to translate the subtitles into Portuguese.
1. Observe the error.

**Expected behavior**
The translation from hearing-impaired English to Portuguese occurs without errors.

**Software (please complete the following information):**
 - **Bazarr Version:** 1.4.4
 - **Package Version:** v1.4.4-ls269 by linuxserver.io
 - **OS:** Linux-6.8.0-76060800daily20240311-generic-x86_64
 - **Python Version:** 3.12.6

**Additional context**

- [Logs](https://github.com/user-attachments/files/17196472/bazarr.log)
- [Subtitle](https://github.com/user-attachments/files/17196475/subtitle.en.hi.srt.txt)

**Note:** I had to append `.txt` to the subtitle file to upload it on GitHub.

**Comment by YetAnotherTechBro** [comment]
I’ve also noticed that when using the "Mass Edit" feature to translate multiple subtitles at once, the process slows down significantly after a certain point, taking several minutes. The logs show that this is due to hitting the rate limit.

Although the translations eventually complete, the resulting subtitles are either still in the original language or a mix of the original and the target translation language.

I suspect this is a bug, as we have backoff logic in place to handle timeouts properly.

**Comment by morpheus65535** [comment]
Yeah definitely a bug but we're too close to releasing an urgent fix in 1.4.5 so I'll postpone this one for a couple of days. I'm planning to rework the translation tool anyway.

**Comment by morpheus65535** [comment]
The Portuguese translation issue should be fixed in upcoming beta.

**Comment by YetAnotherTechBro** [comment]
Thanks for your help!

Just out of curiosity, what is the typical release schedule for Bazarr's stable versions? Do you follow specific criteria when deciding to merge development into the main branch?

**Comment by morpheus65535** [comment]
There's no typical delay. We try do it once every 1 to 2 months unless we have some urgent issue to fix. It's the case in 1.4.4 and we'll release 1.4.5 in the upcoming hours.

**Comment by YetAnotherTechBro** [comment]
Got it, thank you!

**Comment by YetAnotherTechBro** [comment]
> The Portuguese translation issue should be fixed in upcoming beta.

I just tested the fix in v1.4.5, and the EN:HI to PT translation is working now. Thank you! 🙇‍♀️
