### ISSUE TITLE
[Provider Request] Support for Titlovi.com and podnapisi.net as a subtitle provider

### ISSUE THREAD

**Issue by neno20st** [morpheus65535/bazarr#269]
Hi
Can you add in subtitles sources: 

https://titlovi.com/
https://www.podnapisi.net/

They have huge Series/TV subtitles database for Balkan area, Croatian, Serbian, Bosnian languages. 

Thanks

**Comment by halali** [comment]
Added in development branch bazarr version 0.7.1
