### ISSUE TITLE
[FEAT] Add missing repo/site https://www.easternspirit.org/forum/index.php?/

### ISSUE THREAD

**Issue by Arkadietz** [morpheus65535/bazarr#2695]
Hello,

Could you please add the following repo/site (https://www.easternspirit.org/forum/index.php?/files/) for subs?

Thank you in advance.

**Comment by morpheus65535** [comment]
https://bazarr.featureupvote.com/

**Comment by Arkadietz** [comment]
It's there from a long time.
https://bazarr.featureupvote.com/suggestions/577513/add-missing-subs-repo-easternspiritorg

**Comment by Arkadietz** [comment]
> https://bazarr.featureupvote.com/

It's there from a long time.
https://bazarr.featureupvote.com/suggestions/577513/add-missing-subs-repo-easternspiritorg

**Comment by morpheus65535** [comment]
Why did you open an issue for it if you had added it a long time ago to feature requests board? Did you take a look at how many provider requests there is? No one upvoted this request. There's not much chance we prioritize this over much more popular providers...
