### ISSUE TITLE
Value error

### ISSUE THREAD

**Issue by moreje** [morpheus65535/bazarr#2696]
**Describe the bug**
Addic7ed provider fails with Value error :

Throttling addic7ed for 10 minutes, until 24/10/05 12:19, because of: ValueError. Exception info: "'too many values to unpack (expected 2)' ~ addic7ed.py@112"

**To Reproduce**
1. configure addic7ed  provider
2. let bazarr test its access
3. go to status or providers section

**Expected behavior**
fully functionnal addic7ed provider

**Software (please complete the following information):**
Bazarr Version  1.4.5
Package Version v1.4.5-ls642 by linuxserver.io
Sonarr Version 4.0.9.2457
Radarr Version 5.12.1.9277
Operating System Linux-6.2.16-20-bpo11-pve-x86_64-with
Python Version 3.12.6
Database Engine Sqlite 3.45.3
Database Version 1e38aa77a491

**Additional context**

**Comment by morpheus65535** [comment]
You're using username/password or cookies/user-agent? Don't fill both

**Comment by moreje** [comment]
OK, it was not clear that I have to choose...
But now, with only login/pwd, I get: authentication error :(

**Comment by morpheus65535** [comment]
I agree it's not clear. I'll see if I can do better.

Did you configure an anti-captcha provider? It's a requirement for addic7ed. 

You can also simply use gestdown provider which is a proxy for addic7ed that doesn't require all those complications.

**Comment by JaiZed** [comment]
@moreje Is there a reason that you don’t just use gestdown instead of Addic7ed?

**Comment by moreje** [comment]
@JaiZed @morpheus65535 the only reason is that I didn't know this provider ;) I've added it on my list ;) thank you
