### ISSUE TITLE
Suddenly unable to connect to Bazarr in browser

### ISSUE THREAD

**Issue by ejlkemper** [morpheus65535/bazarr#2697]
**Describe the bug**

Unable to connect in browser
Been using it for months now, all of a sudden it stopped?

**To Reproduce**
restart bazarr 
updated  latest (was it already, but....)
restart bazarr 
same error

**Expected behavior**
Bazarr running in browser

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: latest download
 - OS: Debian 5.10.223-1 (2024-08-10) x86_64

**Additional context**

trying to recover as stated in one of the hints.....

sqlite> .recover
PRAGMA foreign_keys=OFF;
BEGIN;
PRAGMA writable_schema = on;
PRAGMA writable_schema = off;
COMMIT;

after that still the same error.

This is what it says with "sudo systemctl status bazarr" 
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) file is not a database

but the db file is loooking ok:
50737152 Oct  4 04:05 bazarr.db

Any hints and tips?
Don't want to re-install it (again) if I don't need to... :-)

**Comment by morpheus65535** [comment]
The bazarr.db file itself seems to be corrupt. Are you able to edit the file in a SQlite database editor? ex.: https://sqlitebrowser.org

**Comment by ejlkemper** [comment]
Hi, thanks for the help!

I can access the db with the provided tool , but get this when trying to open it?

![Screenshot from 2024-10-07 10-14-39](https://github.com/user-attachments/assets/333ac9ef-22d7-4d84-a216-778a49cf7e1d)

**Comment by ejlkemper** [comment]
Additional...
I found a backup with a db and config.yaml from a month ago.
I can access that db, so it looks like the db is indeed corrupt.
but when I restore these files in the appropriate dirs, and restart, it start like a new install?
De db shrinks to a tiny file and all the settings are blank....

Cheers
Erik

**Comment by ejlkemper** [comment]
Ok, fixed it.
stopped bazarr, restored the two files again and did a full reboot of the server.
That did the trick.

Thanks for the help!

Cheers
Erik

**Comment by pcmkrt** [comment]
@morpheus65535 what would you be looking to do if you can open the bazarr.db in the DB browser? I have the same issue but not as lucky with having backups like Erik.

**Comment by morpheus65535** [comment]
> [@morpheus65535](https://github.com/morpheus65535) what would you be looking to do if you can open the bazarr.db in the DB browser? I have the same issue but not as lucky with having backups like Erik.

Do you get the same SQLcypher decryption modal?

**Comment by pcmkrt** [comment]
> > [@morpheus65535](https://github.com/morpheus65535) what would you be looking to do if you can open the bazarr.db in the DB browser? I have the same issue but not as lucky with having backups like Erik.
> 
> Do you get the same SQLcypher decryption modal?

No, I dont. It just opens up. However, I found that I just moved that corrupted /opt/bazarr/data/db/bazarr.db to my backup folder then restarted the service, it rebuilt the db file and now I am able to connect again.
