### ISSUE TITLE
Unique Constraint Error

### ISSUE THREAD

**Issue by pooley182** [morpheus65535/bazarr#2700]
**Describe the bug**
I set up Bazarr for the first time last night, I've never used it before I don't have an existing config or DB. (which seems to be the cause of the issue described in #2384)
It is still in the process of importing all my media from Sonarr but I'm seeing the following types of error in the logs a lot.
```
BAZARR cannot insert episodes because of (sqlite3.IntegrityError) UNIQUE constraint failed: table_episodes.sonarrEpisodeId
```

**To Reproduce**
1. Honestly, I don't know. I've not done anything except deploy a Bazarr docker container and link it to my existing Sonarr/Radarr instances.

**Expected behavior**
No errors.

**Screenshots**
<img width="1917" alt="image" src="https://github.com/user-attachments/assets/5b12ad03-12c2-4e25-a425-f5e15e678935">

**Software (please complete the following information):**
 - Bazarr: 1.4.5
 - Radarr version: 5.11.0.9244
 - Sonarr version: 4.0.9.2244
 - OS: Linux, Unraid, docker container

**Additional context**
I'm not sure if there's two sync threads running at the same time that are conflicting with each other. So this might go away once my initial library is imported.

If the container is restarted the logs remain quiet for a little while, but sure enough the errors reappear after some time.

My Sonarr library is pretty large with over 35k episodes, it has been trying to do it's first sync with Sonarr since I started Bazarr about 15 hours ago

**Comment by pooley182** [comment]
Debug log, in case it's useful.
[bazarr.log](https://github.com/user-attachments/files/17279027/bazarr.log)

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Can you confirm please?

**Comment by rich-r** [comment]
> Should be fixed in upcoming beta. Can you confirm please?

1.4.6-beta.3 fixed the issue for me but required a new database. 

Here's what I tried: 
Recreated the issue on 1.4.5 on a new database
Upgraded to 1.4.6-beta.3, using the existing db and observed the issue 
Ran 1.4.6-beta.3 on a new database, which resolved the issue

**Comment by morpheus65535** [comment]
Let me know if it happens again!
