### ISSUE TITLE
Subtitrari noi AttributeError

### ISSUE THREAD

**Issue by ciotorcristian** [morpheus65535/bazarr#2708]
**Describe the bug**
Subtitrari noi provider is throttling sometimes due to the following errors:

```
Throttling subtitrarinoi for 10 minutes, until 24/10/09 10:42, because of: AttributeError. Exception info: "''NoneType' object has no attribute 'namelist'' ~ utils.py@117" | 2024-10-09 10:32:36 | 
 Using subtitrarinoi again after 10 minutes, (disabled because: AttributeError) | 2024-10-09 10:32:35 |  
 Throttling subtitrarinoi for 10 minutes, until 24/10/09 09:30, because of: AttributeError. Exception info: "''NoneType' object has no attribute 'namelist'' ~ utils.py@117" | 2024-10-09 09:20:51 |  
 Using subtitrarinoi again after 10 minutes, (disabled because: AttributeError) | 2024-10-09 09:20:42 |  
 Throttling subtitrarinoi for 10 minutes, until 24/10/09 03:30, because of: AttributeError. Exception info: "''NoneType' object has no attribute 'namelist'' ~ utils.py@117" | 2024-10-09 03:20:42
```

If further info are needed please tell me and i will try to gather it.

**To Reproduce**
1. Try to download any subtitle in romanian
2. Receive the above errors

**Expected behavior**
Subtitrari noi provider to not throw errors.

**Software (please complete the following information):**
Bazarr Version 1.4.5
Package Version v1.4.5-ls271 by linuxserver.io
Sonarr Version 4.0.9.2244
Radarr Version 5.11.0.9244
Operating System Linux-6.1.0-25-amd64-x86_64-with

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Can you test and confirm the content of the subtitles please?

**Comment by ciotorcristian** [comment]
Latest beta fixes this. Thanks!
