### ISSUE TITLE
Proxy Config using apache2 and proxy.conf file

### ISSUE THREAD

**Issue by djratza** [morpheus65535/bazarr#2710]
**Describe the bug**

Using the wiki for configuring the proxy is not suitable for me as I do not want to use a new VirtualHost file, instead I would like to use the proxy.conf file. If I use the proxy.conf file with the information from Wiki I can login into bazarr but the redirect does not work.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: [e.g. v 0.6.1]
 - Radarr version [e.g. v 0.2.0.0001]
 - Sonarr version [e.g. v 2.0.0.0001]
 - OS: [e.g. Windows 10]

**Additional context**
I found this config to work:
  <Location /bazarr>
  ProxyPreserveHost on
    ProxyPass http://127.0.0.1:6767/bazarr
    ProxyPassReverse http://127.0.0.1:6767/bazarr
    # WebSocket support for Bazarr
    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /(.*) ws://localhost:6767/$1 [P,L]
  </Location>
  
  Adding the RewriteCond and Rule did the trick, maybe it is helpful for others,

**Comment by morpheus65535** [comment]
Please submit a PR for this file updating the instructions. I don't use Apache so I have no idea how to interpret those. Thanks!

https://github.com/bazarr/wiki/blob/main/docs/Additional-Configuration/Reverse-Proxy-Help.md
