### ISSUE TITLE
Upload subtitles rename with 'hi' when select 'Normal' type

### ISSUE THREAD

**Issue by WROIATE** [morpheus65535/bazarr#2716]
**Describe the bug**

Hi,
I tried to upload subtitles and select the `Normal` type, but got a wrong format subtitle file with `hi` ext finally, such as `S01E06.zh-TW.hi.ass`

****
**To Reproduce**
1. Go to series page
2. Click on `Upload`
3. Choose file and select `Normal` type

**Expected behavior**
Don't add Hearing-Impaired ext when select `Normal` type

**Screenshots**
![image](https://github.com/user-attachments/assets/0d56cac2-3ee3-4ea5-8b08-8a529fe9c7b5)
![image](https://github.com/user-attachments/assets/d8e575ad-cfdc-47ae-8b7c-3481c9f40fde)

**Software (please complete the following information):**
 - Bazarr: 1.4.5
 - Sonarr version 4.0.9.2244
 - OS: Docker on Unraid

**Additional context**

**Comment by morpheus65535** [comment]
Shouldn't happens in upcoming beta for .ass subtitles.
