### ISSUE TITLE
Hearing Impaired subtitles not properly named when manually uploading

### ISSUE THREAD

**Issue by Metropolis76** [morpheus65535/bazarr#2719]
**Describe the bug**
Hearing Impaired subtitles that are manually uploaded through Bazarr are not being named properly to include the extension defined in settings.

**To Reproduce**
1. Go to any movie or TV Show within Bazarr
2. Manually Upload a subtitle and mark it as Hearing Impaired
3. Once imported the file name will not include the extension defined within Bazarr's Settings

**Expected behavior**
Subtitles marked as Hearing Impaired on manual upload are named accordingly. (Title.[LanguageCode].sdh|hi|cc.[SubtitleExtension])

**Screenshots**
[image](https://github.com/user-attachments/assets/183597f7-096e-4a72-b2d4-3b7c1aa4621e)

Image of a subtitle marked as English HI, but does not include the Hearing Impaired extension in it's filename

**Software (please complete the following information):**
 - Bazarr: 1.4.5
 - Radarr version: 5.12.2.9335
 - Sonarr version: 4.0.9.2244
 - OS: Linux, running all of the above services in Docker

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta, thanks for reporting!
