### ISSUE TITLE
Every day the same subtitles are downloaded

### ISSUE THREAD

**Issue by pven** [morpheus65535/bazarr#272]
Every day the same subtitles are downloaded (around 35 subs). This happens for some series, not for all. It happens automatically, I found out by the notifications I get via Telegram. ( I don't think it is the same issue as described in https://github.com/morpheus65535/bazarr/issues/120 )

**Expected behavior**
Download it once, not daily

**Software (please complete the following information):**
 - Bazarr: newest I guess
 - OS: Synology (newest DSM)

Can I somehow fix this?

**Comment by pven** [comment]
[config.ini.txt](https://github.com/morpheus65535/bazarr/files/2760105/config.ini.txt)

Can I sent the log in a PM orso? (I don't want to share it here)

**Comment by morpheus65535** [comment]
Why is there `diskstation2:` in your series path mapping settings? Remove this and run this task: `Update all episodes subtitles from disk`.

You can come to Discord for live support.

**Comment by pven** [comment]
Hm, I get back to this when bazarr is up-and-running again.

(When starting bazarr it told me there was an update. I click on restart, and now it won't start and complains I need to run pip install gevent ...)

**Comment by morpheus65535** [comment]
Way easier with docker. Is that an option for you?

**Comment by pven** [comment]
Nope, my Synology (DS214+) does not support that. But let me check pip install gevent, it shows a lot of errors but that should be fixable.

**Comment by morpheus65535** [comment]
Be sure it's Python 2.7 pip, not 3.x.

**Comment by pven** [comment]
I am running on the version from one week ago. I removed the diskstaton2-text, and it looks like it is not downloaden all the daily subs! Thx for that. Regarding pip install gevent: I am working on it, it is not that easy on my Synology.

**Comment by morpheus65535** [comment]
Did you mean "now downloading" instead of "not downloading"? If everything related to the issue is now working fine, I suggest we close it.
