### ISSUE TITLE
X-Real-IP header doesn't seem to be considered

### ISSUE THREAD

**Issue by tetebueno** [morpheus65535/bazarr#2721]
**Describe the bug**
Bazarr receives the client IP on the `X-Real-IP` header but in the logs the gateway IP is being shown.

**To Reproduce**
1. Configure Nginx reverse proxy just like the [wiki shows](https://wiki.bazarr.media/Additional-Configuration/Reverse-Proxy-Help/#using-nginx-and-bazarr-base-url).
2. Log into Bazarr
3. Check logs, the `Successful authentication from ... for user...` shows the gateway IP.

**Expected behavior**
Client IP sent on `X-Real-IP` header is used.

**Screenshots**
N/A

**Software (please complete the following information):**
 - Bazarr: 1.4.3-beta.34
 - Radarr version N/A
 - Sonarr version N/A
 - OS: Linux-6.5.0-35-generic-x86_64-with

**Additional context**
Both Nginx and Bazarr are configured through Docker compose on sepparate stacks.

**Comment by morpheus65535** [comment]
Bazarr should properly log `X-Forwarded-For` which is the proper header to use in that case. If this doesn't work when properly configured in nginx location, then we have a bug that need investigation. Please confirm if `X-Forwarded-For` works as expected.

**Comment by tetebueno** [comment]
Just tested again monitoring connections on the Docker network the Bazarr container is in with Wireshark and I can confirm header value is not being shown in logs:

## Request captured by Wireshark

![photo_2024-10-21_16-13-14](https://github.com/user-attachments/assets/64b59ece-63ba-4e88-8a7b-97cf2f4ceed4)

```
POST /api/system/account?action=login HTTP/1.1
Host: bazarr.example.com
X-Real-IP: 192.168.0.99
X-Forwarded-For: 192.168.0.99
X-Forwarded-Host: bazarr.example.com
X-Forwarded-Proto: https
Connection: keep-alive
...
```
## Logs shown in container's stdout
```
2024-10-21 16:02:04,431 - XXX                             (...) :  INFO (helper:19) - Successful authentication from 172.28.0.1 for user XXX
```

The IP of the network's gateway `172.28.0.1` is shown instead of `192.168.1.3` which is sent in both `X-Real-IP` and `X-Forwarded-For` headers.

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Let me know!

**Comment by tetebueno** [comment]
Just tested with Docker image tag `1.4.6-development` and worked just fine. Thanks.
