### ISSUE TITLE
Wrong message displayed when auto-syncing in progress

### ISSUE THREAD

**Issue by eben0** [morpheus65535/bazarr#2724]
When **Automatic Subtitles Synchronization** is enabled and the current subtitle score is below the threshold, the "Downloading Subtitles" message is still displayed and has not been changed to "Syncing Subtitles".
This is misleading because the user thinks the subtitle is still downloading.

1. Go to 'Settings' -> 'Subtitles' -> Automatic Subtitles Synchronization'.
4. Enable and set Threshold.
5. Download subtitles with a score below the configured threshold.

**Expected behavior**
Once downloading is complete and syncing starts the "Downloading Subtitles" message is changed to "Syncing Subtitles".

 - Bazarr: v1.4.5
 - OS: Docker

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Thanks for reporting!
