### ISSUE TITLE
RegieLive JSONDecodeError

### ISSUE THREAD

**Issue by ciotorcristian** [morpheus65535/bazarr#2727]
**Describe the bug**
When searching for subs, RegieLive provider throws the following error. I couldn't find a pattern yet.

Throttling regielive for 10 minutes, until 24/10/18 01:48, because of: JSONDecodeError. Exception info: "'Expecting value: line 1 column 1 (char 0)' ~ regielive.py@95"	2024-10-18 01:38:36
Throttling regielive for 10 minutes, until 24/10/18 01:35, because of: JSONDecodeError. Exception info: "'Expecting value: line 1 column 1 (char 0)' ~ regielive.py@95"	2024-10-18 01:25:37

**To Reproduce**
1. Download a large number of subs
2. Get the error

**Expected behavior**
The provider shouldn't raise any erros

**Software (please complete the following information):**
 Bazarr Version 1.4.6-beta.6
Package Version v1.4.6-beta.6-ls646 by linuxserver.io
Sonarr Version 4.0.9.2244
Radarr Version 5.12.2.9335
Operating System Linux-6.1.0-25-amd64-x86_64-with
Python Version 3.12.7

**Comment by JaiZed** [comment]
This is a provider website issue.
The error means that no subtitle data was returned by the website.
The provider code could probably be updated to issue better error messages in this case.

**Comment by JaiZed** [comment]
Fixed in upcoming beta.

**Comment by ciotorcristian** [comment]
Didn't encountered this again. Thanks!
