### ISSUE TITLE
Error with subsynchro - JSONDecodeError

### ISSUE THREAD

**Issue by Therock99999** [morpheus65535/bazarr#2735]
**Describe the bug**
 Getting errors when searching for subtitles with subsynchro.

**To Reproduce**
1. Go to a show or movie.
2. Click on search
3. Go to System > Logs
4. Error: Throttling subsynchro for 10 minutes, until 24/10/25 10:29, because of: JSONDecodeError. Exception info: "'Expecting value: line 1 column 1 (char 0)' ~ subsynchro.py@94"

**Expected behavior**
 The provider shouldn't raise any errors.

**Software (please complete the following information):**
 - Bazarr: 1.4.6-beta.11
 - Radarr version:  5.12.2.9335
 - Sonarr version: 4.0.9.2244
 - OS: Linux-5.10
 - Python Version: 3.12.7

**Comment by JaiZed** [comment]
Should be fixed in upcoming beta.
