### ISSUE TITLE
strangely downloading wrong subtitles from Subdivx

### ISSUE THREAD

**Issue by rmichelena** [morpheus65535/bazarr#2739]
it downloads subtitles from Subdivx for "Nautilus S01E02", also E04 and E05
However when I do a manual search in Bazarr, those do not show up.
Searching them in the Subdivx website, those subtitles do not exist.

The subs downloaded seem to correspond to a tv show called "Episodes"; at least the S02 one...
Maybe the fact that the show is called "Episodes" confuses something?

I don't know how to diagnose/troubleshoot this, since manual searches do not trigger it... I just wake up to find it's downloaded these subs. There's nothing to be found in the logs. And I couldn't enable "debug log" for a moment, I'd have to leave it enabled for days, which I guess is not practical...

This happened first in beta5, I just deleted the subs, but beta11 has just downloaded them again.

**Comment by anderson-oki** [comment]
@rmichelena Can you check on your logs what is the URL or what is the search that is being performed, and then try to search directly on subdivx and see if it gives the same result, maybe we can identify what is the issue.

**Comment by morpheus65535** [comment]
No news, good news!
