### ISSUE TITLE
Missing: Match TV series

### ISSUE THREAD

**Issue by aroundmyroom** [morpheus65535/bazarr#274]
2019-01-17 07:30:28,630 - subliminal.providers.addic7ed    (7fda2198e700) :  ERROR (addic7ed:300) - No show id found for 'Will And Grace' ({'year': None})

I understand this as the show is known as Will & Grace, but I do not modify shownames as they are released and many times I see: Will and Grace S09E010 etc.. how are we able to match this within Bazarr?
Is there no feature in the system where where we can match a series towards what is in Bazarr?

**Comment by morpheus65535** [comment]
Nothing like manual mapping is available in Bazarr at the moment. Maybe in the future.
