### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by punteroanull** [morpheus65535/bazarr#2740]
Bazarr docker image doesn't runs, it throws an error:

    from bazarr.app.get_args import args
  File "/app/bazarr/bin/bazarr/app/get_args.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr.py", line 10, in <module>

build_version | Linuxserver.io version:- v1.1.4-ls180
 Build-date:- 2023-02-02T14:28:57-06:00

maintainer | chbmb

**Comment by morpheus65535** [comment]
Did you look at the build date? This is version 1.1.4 and we're now at 1.5.5.

**Comment by JaiZed** [comment]
It's actually 1.4.5 we're at, but the point still stands as valid. 😉

**Comment by punteroanull** [comment]
Linuxserver.io version: v1.4.5-ls275

Same issue with this one ;)

**Comment by morpheus65535** [comment]
So it definitely looks like an issue with the image itself for a specific architecture. You should open an issue with them.
