### ISSUE TITLE
Subtitle upgraded every time

### ISSUE THREAD

**Issue by bonswouar** [morpheus65535/bazarr#2743]
**Describe the bug**
For some reason **one specific movie** in my library does get upgraded for (apparently) every subtitle upgrade check.
And some **specific episodes** of some shows too

**To Reproduce**
1. I don't have a clue
2. Check movies/shows history

**Expected behavior**
Subtitles should be upgraded only when the score is higher

**Screenshots**
History of the Movie:
![image](https://github.com/user-attachments/assets/80997d79-e036-4fc6-997a-5b8e6de2513b)

And of one specific episode of some Show (while all other episodes of the season don't have the issue):
![image](https://github.com/user-attachments/assets/95f96d2e-a2d6-4874-9891-69309342f65b)
_**Note that it even upgraded to a lower score at some point?! (96.11 vs 99.17)**_

**Software (please complete the following information):**
 - Bazarr: 1.4.5
 - Radarr version 5.14.0.9383
 - Sonarr version 4.0.10.2544
 - OS: Debian

**Additional context**
I didn't find anything special in the logs (i.e only the whisperai query for the movie), and I can't find a pattern for the specific movie/episodes it happens to.. 
On a side note, should subtitle with 100% score be even checked for upgrade?

**Comment by morpheus65535** [comment]
There's been a couple of fixes to subtitles upgrade process since v1.4.6-beta.3. It may worth testing.

**Comment by JaiZed** [comment]
Please check your Debug logs for SQL errors.
If there is some sort of key error with this specific movie, the database will show that the movie requires a subtitle. Afterwards when it successfully downloads the subtitle, if it is unable to update the database, then it's like the download didn't happen at all and it will try to download the subtitle again in the future, over and over again.

**Comment by bonswouar** [comment]
@JaiZed I've enabled debug logs and didn't find any sql error. I've also checked the logs for weird behavior but I'm not sure what to look for (i.e I didn't find an obvious log for comparing the current score with best found score - maybe that's a clue?)
@morpheus65535 I've just updated to 1.4.6-beta.15, will let you know if this still happens

**Comment by bonswouar** [comment]
@morpheus65535 Unfortunately there's apparently still the same problem with 1.4.6-beta.15

Could you point me to what to look for in the logs maybe?

**Comment by JaiZed** [comment]
If it's only happening with one movie, then I doubt it is much of a software version issue.
There is something very specific about that movie that is different.
If you could share a copy of your bazarr.db file along with the name of the movie on Discord, it would help to narrow this down and perhaps squash a bug that might also be happening for you on the TV show side, as well.
If not, a couple of things to try:
1) Remove the movie from Radarr and add it back in again.
2) If that doesn't work, remove the movie and replace it with a different version of the same movie. 

If either of those work, your problem is gone but we won't know why. Sharing the db would probably help us solve it.

**Comment by bonswouar** [comment]
@JaiZed it actually doesn't happen to only one movie, I've just found another one:
![image](https://github.com/user-attachments/assets/caa23cfa-67fe-4a84-bcbb-0b7294b6bb7c)
And some episodes also as I was saying

I'd prefer to find the origin of the problem rather that remove a movie/episode every time I have an issue! 😅

**Comment by morpheus65535** [comment]
> @morpheus65535 Bazarr keeps replacing subtitles that I manually synced. Maybe if there was a locking mechanism, to avoid upgrades or downloads in these cases or a pre-check script (more flexible) to evaluate the presence of some file like ".sub-is-sync" before downloading subtitles.

This is a feature request, please open one on the proper platform.

**Comment by morpheus65535** [comment]
This should have been fixed in 1.4.6-beta.20. Let use know if your still face that issue in the future.
