### ISSUE TITLE
If IPv6 is unavailable then OSError: [Errno 97] Address family not supported by protocol

### ISSUE THREAD

**Issue by colemar** [morpheus65535/bazarr#2744]
**Describe the bug**
OSError: [Errno 97] Address family not supported by protocol

**To Reproduce**
1. Have an Ubuntu machine with IPv6 disabled
2. `python bazarr.py`
3. See error above

**Expected behavior**
Bazarr can start and listen on all available interfaces when `ip: '*'` in `data/config/config.yaml` even if IPv4 only.
At least mention the workaround below in `https://wiki.bazarr.media/Getting-Started/Installation/Linux/linux/`

**Software (please complete the following information):**
 - Bazarr: 1.4.5
 - OS: Ubuntu 22.04.3

**Workaround**
Set `ip: '0.0.0.0'` in `data/config/config.yaml`.

**Comment by morpheus65535** [comment]
Duplicate from #2738
