### ISSUE TITLE
No subtitles found

### ISSUE THREAD

**Issue by DePalmo** [morpheus65535/bazarr#2746]
**Describe the bug**
I have a fresh installation of Bazaar and older installation of Sonarr. Did follow Wiki pages for configuration and have set everything up, but the Bazarr still does not found any subtitles. Searching manually for the subtitles does yield results, same goes for XML file if I extract the URL from logs and visit that page/site.

**To Reproduce**
1. Have serie "9-1-1" added in Sonarr. In my case, I'm downloading MiNX release.
2. Install Bazarr for Windows by following official instructions.
3. Connect Sonarr with Bazarr, again following the instructions.
4. Add subtitle "Language Profile" for English and add that profile to the serie mentioned above.
5. Search manually for subtitle, in my case for S08E01. Subtitle is there: https://www.podnapisi.net/subtitles/search/old?sXML=1&sL=en&sK=9+1+1&sTS=8&sTE=1&sY=2018

**Expected behavior**
I would expect a list of all available subtitles so that I can choose from it, which one I want.

**Screenshots**
-

**Software (please complete the following information):**
 - Bazarr: v1.4.5
 - Sonarr version v4.0.10.2544
 - OS: Windows 10

**Additional context**
Log file: 
[bazarr-2024-11-02.txt](https://github.com/user-attachments/files/17607055/bazarr-2024-11-02.txt)

**Comment by hnorgaar** [comment]
First of all I would recommend you to use gestdown instead of Podnapisi as provider, also check if you have ticked "Download Only Monitored" in Sonarr settings of Bazarr.

**Comment by DePalmo** [comment]
I'm using Podnapisi with a good reason: they have subtitles in my native language. While OpenSubtitles sometimes does have and other times does not. I have checked Gestdown and it looks like I won't find any Slovenian subtitles there either.

**Comment by anderson-oki** [comment]
@hnorgaar 

Sorry, i'm not very familiar with these providers, but what is the relation of Gestdown and Podnapisi? I know gestdown is a proxy for addic7ed.

**Comment by hnorgaar** [comment]
No relation except to be 2 providers in Bazarr, however for shows I do prefer Gestdown as its a lot more stable. But not for Slovenian subs it seems, which was not mentioned in the problem description, only EN

**Comment by DePalmo** [comment]
For EN subtitles I solved the issue by adding OpenSubtitles.com / .org and it's now working. The issue persists for EN subtitles and Podnapisi provider. But since that provider times out most of the times, I won't use it for EN subtitles.

Closing this one for now.
