### ISSUE TITLE
Restore from backup does nothing

### ISSUE THREAD

**Issue by DePalmo** [morpheus65535/bazarr#2748]
**Describe the bug**
I have created a backup of Bazarr through the web interface and saved the file. Then I reinstalled Windows 10 machine and installed fresh version of Bazarr back, copied the backup file into `%PROGRAMDATA%\Bazarr\backup` and tried to restore the instance. The service did stop, web interface showed a 500 error (normal, since the service was not available), but when the service booted back up, the Bazarr was still in default configuration (aka. fresh from installation). Did try few times and it dodn't work.

Then I stopped the service manually, copied bazarr.db into `db` folder and config.yaml into `config` folder, started the service and the instance was updated as it should be.

**To Reproduce**
1. Have a Bazarr installed with personalized config
2. Create backup through web interface
3. (in my case) Reinstall Windows (but I assume something less drastic can be done, probably Bazarr reinstall? Didn't test)
4. Copy the backup file to backup folder
5. Try to restore the Bazarr instance
6. See how it fails

**Expected behavior**
Backup should be restored.

**Screenshots**
None.

**Software (please complete the following information):**
 - Bazarr: v1.4.5 (both, old and new installations)
 - OS: Windows 10 Pro, 22H2

**Additional context**

**Comment by morpheus65535** [comment]
Debug log while reproducing the issue?

**Comment by DePalmo** [comment]
Can't provide it, since I already resolved my issue and didn't think of creating a debug log. When I will have more time, I will provide it.
