### ISSUE TITLE
Downloading subtitle over and over with a score 100%

### ISSUE THREAD

**Issue by klu16** [morpheus65535/bazarr#2749]
**Describe the bug**
Bazarr is downloading the same subtitle multiple times from the same provider, even if it has a score 100%. Screenshot below. 

**To Reproduce**
n/a

**Expected behavior**
When a score is 100%, stop downloading it. 

**Screenshots**
![Screenshot_2024-11-08-14-55-41-831_org mozilla firefox](https://github.com/user-attachments/assets/d556175b-a52c-4bdc-8464-3f8effd7f851)

**Software (please complete the following information):**
Bazarr Version

1.4.5

Sonarr Version

4.0.9.2244

Radarr Version

5.11.0.9244

Operating System

Linux-6.8.12-2-pve-x86_64-with-glibc2.35

Python Version

3.10.12

Database Engine

Sqlite 3.37.2

Database Version

1e38aa77a491 

**Additional context**

**Comment by morpheus65535** [comment]
What is the icon to the left of those actions in your history? Can you show me please?

**Comment by klu16** [comment]
Hi @morpheus65535. This is the screenshot from the start of downloading it:

![Screenshot_2024-11-12-06-48-19-085_org mozilla firefox](https://github.com/user-attachments/assets/38bcd1df-8101-47e3-a6b0-e0e4856e9fa0)

As you can see, it was downloaded 22 times already, last one 5h ago.

By the way, it's happening with this particular episode only.

Thanks a lot!

**Comment by morpheus65535** [comment]
This should be fixed in upcoming beta. Let us know if not!

**Comment by klu16** [comment]
Hi @morpheus65535 :)
I have just installed the latest beta
`Bazarr Version: 1.4.6-beta.21`
I will observe the behavior for a few days and let you know again in the separate comment.
Thanks again for your work!

**Comment by klu16** [comment]
I think I has been fixed :)
It hasn't upgraded this (or any) particular sub for a few days now and it sometimes would do that several times in one day.
Thank you 🙏 Cheers!

**Comment by klu16** [comment]
Hi @morpheus65535. 

It happened again after a few months unfortunately, for a different series.

![Image](https://github.com/user-attachments/assets/56deb09e-0d17-40f8-aff3-d46bf177fc51)

**Comment by morpheus65535** [comment]
Debug log?

**Comment by klu16** [comment]
I enabled the debug log now. I'm waiting for the subtitle to get downloaded again.

**Comment by morpheus65535** [comment]
You can force the upgrade by running the task in System-->Tasks.

**Comment by klu16** [comment]
[bazarr.log](https://github.com/user-attachments/files/19473537/bazarr.log)

Log attached.

Subtitles were re-downloaded at 19:31.
Episode title is "Hit The Floor" (Grey's Anatomy S21E09)

**Comment by morpheus65535** [comment]
Can you send me your database in private on Discord so I can match subtitles IDs and confirm what's causing this?

**Comment by klu16** [comment]
> Can you send me your database in private on Discord so I can match subtitles IDs and confirm what's causing this?

Sent in DM on Discord, as requested. Thanks!

**Comment by morpheus65535** [comment]
@klu16 upcoming beta should fix it definitely (I hope). Let me know!

**Comment by klu16** [comment]
> [@klu16](https://github.com/klu16) upcoming beta should fix it definitely (I hope). Let me know!

After updating to v1.5.2-beta.33, the issue seems fixed. I manually ran the upgrade task and the subtitle wasn't downloaded this time. Thanks a lot!! ☺️
