### ISSUE TITLE
"This path doesn't seems to be valid"

### ISSUE THREAD

**Issue by romquenin** [morpheus65535/bazarr#275]
**Describe the bug**
Hello firts of all a want to thank you for this great awaited service.

I have installed Bazarr's docker image from linuxserver on my synology nas using this code:

```
sudo docker create \
   --name=bazarr \
   -e PUID=1001 \
   -e PGID=1001 \
   -e TZ=Europe/Paris \
   -p 6767:6767 \
   -v /volume1/docker/bazarr:/config \
   -v /volume1/video/MOVIES:/video/MOVIES \
   -v /volume1/video/TV\ SHOWS:/video/TV\ SHOWS \
   --restart unless-stopped \
   linuxserver/bazarr

```

When  access the ui with "/settings" i can make all the basic setup but unfortunately when i'm triyng to add Sonarr or Radarr the app gets really slow then freeze for 2 minutes comes back and non of them are added

Sonarr and Radarr are installed on my nas from the synocommunity package app and i can access remotely both apps with api code from my android app nzb360.

The path for my tv shows is :  /volume1/video/TV SHOWS
The path for my movies is :  /volume1/video/MOVIES

I'm using the same PUID and PGID for "oragnizr".

![screenshot_2019-01-19 settings - bazarr](https://user-images.githubusercontent.com/34734431/51429830-3cb59400-1c13-11e9-81e8-faeb7dc89960.png)

![screenshot_2019-01-19 diskstation - synology diskstation](https://user-images.githubusercontent.com/34734431/51429743-ec8a0200-1c11-11e9-8f2e-774d32c09051.png)

![screenshot_2019-01-19 settings - bazarr 1](https://user-images.githubusercontent.com/34734431/51429857-8dc58800-1c13-11e9-94be-87e9bb03b785.png)

![screenshot_2019-01-19 diskstation - synology diskstation 1](https://user-images.githubusercontent.com/34734431/51429855-87cfa700-1c13-11e9-8264-98089db85655.png)

Thank you for your help.

 - Bazarr: [7.0.0]
 - Radarr version [0.2.0.1217]
 - Sonarr version [2.0.0.5252

 - OS: [e.g. Windows 10]

**Comment by romquenin** [comment]
I have finally been able to login with radarr and sonarr.

But i'm facing now " This path doesn't seems to be valid" issue. Here i my last config:

![screenshot 2019-01-20 at 03 48 54](https://user-images.githubusercontent.com/34734431/51434651-75328d80-1c66-11e9-84c9-3610364dc312.png)

**Comment by morpheus65535** [comment]
Please provide the path of an episode as seen by Sonarr.

**Comment by romquenin** [comment]
Hello morpheus65535, i have found the path for a  serie but not for episode? I'm sorry but i don't know where to find this info.
Could you please point me in the right direction.

Here is the path for one tv show:

> /volume1/video/TV SHOWS/grown-ish

Thanks.

**Comment by morpheus65535** [comment]
Path mapping for shows:
Sonarr: `/volume1/video/TV SHOWS/`
Bazarr: `/video/TV SHOWS/`

Path mapping for movies:
Sonarr: `/volume1/video/MOVIES/`
Bazarr: `/video/MOVIES/`

Save this then restart Bazarr.

**Comment by romquenin** [comment]
Thanks morpheus i edited the path and this issue is now solved.

Now i have another problem, it seemse that my addict7ed account doesn't load properly. I have triple checked my username and password and for sure it's not related.

![screenshot 2019-01-20 at 18 22 11](https://user-images.githubusercontent.com/34734431/51442791-c41d0900-1ce0-11e9-9eca-047fcebe8933.png)

Since more than 3 years 90 percent of my tv shows are downloaded automaticly with sonarr so i guess the naming should be correct?
I have noticed that for my movies database Bazarr have only scrapped the 19 movies i have dowloaded from radarr(i have more than 1000 movies), is it  normal?

Thank you very much morpheus i really hope you will help to make it work.

**Comment by romquenin** [comment]
Hello morpheus, thank you for your answer.

My addic7ed password is composed with only lettres and numbers. Should i try to create à New account with a New password ?

Sorry for my previous stupid question, I get lost in translation sometimes.

Thanks.

**Comment by morpheus65535** [comment]
La dernière version corrigeait aussi un bug au niveau du stockage des mots de passe des providers dans le fichier de config. J’allais justement te suggérer de faire la mise à jour. :-)

Merci pour le big des popups. J’ai fait la correction et j’attend que LSIO rebuild les images.

**Comment by tonyperuca** [comment]
Hello morpheus65535, I'm using a 8tb Seagate connected to the router Asus-AC68U with the paths:
Sonarr - \\Asus-ac68u\seagate8tb\Seriados\
Radarr - \\Asus-ac68u\seagate8tb\Filmes\
Tried everything and no way. Can you help me? Thank you!

**Comment by morpheus65535** [comment]
> Hello morpheus65535, I'm using a 8tb Seagate connected to the router Asus-AC68U with the paths:
> Sonarr - \Asus-ac68u\seagate8tb\Seriados
> Radarr - \Asus-ac68u\seagate8tb\Filmes
> Tried everything and no way. Can you help me? Thank you!

Don't resurrect an issue. We are answering you on Discord.
