### ISSUE TITLE
"Error 500 Episode file not found. Path mapping issue?" (path correct, sync ok)

### ISSUE THREAD

**Issue by Maitresinh** [morpheus65535/bazarr#2753]
**Describe the bug**

I've changed (corrected) the location of a TV show on Sonarr
It appears changed, but when i look for subs, it shows an error 500

**To Reproduce**
1. Go to TV show
2. Click on Search Subs
3. see error 500

**Expected behavior**

Bazarr found the subs (or at least the show itself on the mapped path

**Software (please complete the following information):**
 - Bazarr: 1.4.6-beta.16
 - Radarr version v1.4.6-beta.16-ls652 by linuxserver.io
 - Sonarr version 4.0.10.2544
 - OS:  Unraid last version

**Additional context**

The mapped path is the same everywhere (sonnarr, radarr, bazarr)
I've tried to add it on bazarr manually. Same result
I've tried to manually sync in the tasks . Same result

**Comment by morpheus65535** [comment]
This should be first addressed by Discord support channel. Have you been there? Also, without a debug log, docker-compose and some screenshots of your path mapping, there's not much we can do.

**Comment by JaiZed** [comment]
Have you tried simply removing that TV show from Sonarr and then adding it back in?

**Comment by Maitresinh** [comment]
Thanks for your answer. How can you erase a TV show on bazarr ? i couln't find it.

**Comment by morpheus65535** [comment]
> Thanks for your answer. How can you erase a TV show on bazarr ? i couln't find it.

Sonarr, not Bazarr.

**Comment by Maitresinh** [comment]
Thanks. That was simple at the end :)

**Comment by Maitresinh** [comment]
Solved

**Comment by KennethHoff** [comment]
I personally solved a similar issue on my Synology NAS by fixing the permissions. I was under the impression that Sonarr and Bazarr used the same user/group, but they had their own set. That's a good thing though, as long as you're aware of it.
