### ISSUE TITLE
Embedded PGS are not detected for extraction purposes

### ISSUE THREAD

**Issue by zazabozaza** [morpheus65535/bazarr#2754]
**Describe the bug**
I've set up bazarr solely for the purpose of automatically extracting embedded subtitles from newly added media. Ive noticed that if the embedded subtitles are PGS bazarr cannot detect it. The only provider I have is embedded subtitles only

**To Reproduce**
Find media that has PGS subtitles to be extracted
Search for subtitles for that media
No subtitles are detected

**Expected behavior**
Extraction of PGS subtitles

**Screenshots**

**Software (please comple
![Screenshot 2024-11-11 004732](https://github.com/user-attachments/assets/798d2f33-f9a6-4856-9294-dc51a6c137e2)
![Screenshot 2024-11-11 004900](https://github.com/user-attachments/assets/33db6ba2-b8fa-4454-b6ca-c0f0d87ae37c)
te the following information):**
 - Bazarr: 1.4.5

**Comment by morpheus65535** [comment]
Support is done on Discord support channel. This is a bug reporting system.
