### ISSUE TITLE
Subtitle files as symlinks

### ISSUE THREAD

**Issue by asardaes** [morpheus65535/bazarr#2755]
**Describe the bug**
Hello, I wanted to write a post-process script that would move the downloaded file and then create symlink in the original location, but it seems that after doing so, Bazarr still considered the subtitles as missing. Is this completely unsupoorted? 

**To Reproduce**
Store a subtitle in the same location as the media file, move it, and create a symlink in the original location.

**Expected behavior**
Symlink recognized as subtitle file.

**Software (please complete the following information):**
 - Bazarr: latest docker image

**Additional context**

**Comment by morpheus65535** [comment]
I've never seen anyone doing that and it's definitely untested. Why would you do that?

**Comment by morpheus65535** [comment]
Then why not use subtitles folder absolute option in Settings-->Subtitles to save them directly in the path you want instead of doing some complicated post-processing script?

**Comment by asardaes** [comment]
Because I still want other programs to see the files when scanning the library.

Anyway, I just wanted to be sure. Python usually assumes a file exists even if it's a symlink, but maybe there's more to it in bazarr.

**Comment by morpheus65535** [comment]
We do some file size check and os.path.isfile() is used and may ignore symlink.

Sorry but like I said we never tested that use case.

**Comment by asardaes** [comment]
All right, it was just a question, thanks for checking.
