### ISSUE TITLE
WhisperAI cannot transcribe Chinese audio

### ISSUE THREAD

**Issue by sinofool** [morpheus65535/bazarr#2758]
**Describe the bug**
Whisper AI provider unable to transcribe Chinese language.

**To Reproduce**
1. Setup a profile language request Chinese Simplified and English subtitles 
2. Setup Whisper provider with subgen or whisper asr
3. Manual search for a video with Chinese audio.
4. Only "Translate Chinese audio to English SRT" returned 

**Expected behavior**
Expected to have a result of "Transcribe Chinese audio to Chinese Simplified SRT"

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: v1.4.5
 - Radarr version v5.14.0.9383
 - Sonarr version v4.0.10.2544
 - OS: Docker on Debian

**Additional context**
Debug log shows it found two options including transcribe from Chi audio to Chi, but not show ZH in the results. 
I didn't find how the ISO code mapping to languages.

**Comment by JaiZed** [comment]
Should be fixed in next beta.
