### ISSUE TITLE
[Question] When using WhisperAI, can bazarr tag the page or subs?

### ISSUE THREAD

**Issue by Hello-World-Traveler** [morpheus65535/bazarr#2760]
Somewhere below it will say AI subs without having to look at the history or providers name be attached to each row? 
![Screenshot 2024-11-16 at 12-48-13 Ambulance - Bazarr (Series)](https://github.com/user-attachments/assets/ee193198-e060-480c-aedd-0539912522ec)

**Comment by morpheus65535** [comment]
Not possible. Please get to Discord for question, this is an bug reporting system.
