### ISSUE TITLE
'NoneType' object has no attribute 'close'

### ISSUE THREAD

**Issue by destpstrzy** [morpheus65535/bazarr#2773]
**Describe the bug**
Bazarr in development mode dosn't start.
Logs:

> 2024/11/25 19:25:07 | stderr | AttributeError: 'NoneType' object has no attribute 'close'
> -- | -- | --
> 2024/11/25 19:25:07 | stderr | ^^^^^^^^^^^^^^^^^
> 2024/11/25 19:25:07 | stderr | self.server.close()
> 2024/11/25 19:25:07 | stderr | File "/app/bazarr/bin/bazarr/app/server.py", line 97, in close_all
> 2024/11/25 19:25:07 | stderr | self.close_all()
> 2024/11/25 19:25:07 | stderr | File "/app/bazarr/bin/bazarr/app/server.py", line 100, in shutdown
> 2024/11/25 19:25:07 | stderr | self.shutdown()
> 2024/11/25 19:25:07 | stderr | File "/app/bazarr/bin/bazarr/app/server.py", line 74, in configure_server
> 2024/11/25 19:25:07 | stderr | self.configure_server()
> 2024/11/25 19:25:07 | stderr | File "/app/bazarr/bin/bazarr/app/server.py", line 42, in __init__
> 2024/11/25 19:25:07 | stderr | ^^^^^^^^
> 2024/11/25 19:25:07 | stderr | webserver = Server()
> 2024/11/25 19:25:07 | stderr | File "/app/bazarr/bin/bazarr/app/server.py", line 108, in <module>
> 2024/11/25 19:25:07 | stderr | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024/11/25 19:25:07 | stderr | from app.server import webserver, app  # noqa E402
> 2024/11/25 19:25:07 | stderr | File "/app/bazarr/bin/bazarr/main.py", line 43, in <module>
> 2024/11/25 19:25:07 | stderr | Traceback (most recent call last):
> 2024/11/25 19:25:07 | stderr |  
> 2024/11/25 19:25:07 | stderr | During handling of the above exception, another exception occurred:
> 2024/11/25 19:25:07 | stderr |  
> 2024/11/25 19:25:07 | stderr | OSError: [Errno 99] Address not available
> 2024/11/25 19:25:07 | stderr | ^^^^^^^^^^^^^^^^^^^^^^
> 2024/11/25 19:25:07 | stderr | return self.socket.bind(addr)
> 2024/11/25 19:25:07 | stderr | File "/app/bazarr/bin/bazarr/../libs/waitress/wasyncore.py", line 395, in bind
> 2024/11/25 19:25:07 | stderr | self.bind(sockaddr)
> 2024/11/25 19:25:07 | stderr | File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 364, in bind_server_socket
> 2024/11/25 19:25:07 | stderr | self.bind_server_socket()
> 2024/11/25 19:25:07 | stderr | File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 243, in __init__
> 2024/11/25 19:25:07 | stderr | ^^^^^^^^^^^^^^
> 2024/11/25 19:25:07 | stderr | last_serv = TcpWSGIServer(
> 2024/11/25 19:25:07 | stderr | File "/app/bazarr/bin/bazarr/../libs/waitress/server.py", line 78, in create_server
> 2024/11/25 19:25:07 | stderr | ^^^^^^^^^^^^^^^^^^
> 2024/11/25 19:25:07 | stderr | self.server = create_server(app,
> 2024/11/25 19:25:07 | stderr | File "/app/bazarr/bin/bazarr/app/server.py", line 46, in configure_server
> 2024/11/25 19:25:07 | stderr | Traceback (most recent call last):
> 2024/11/25 19:25:07 | stdout | Closing webserver...
> 2024/11/25 19:25:07 | stdout | Closing database...
> 2024/11/25 19:25:07 | stderr | 2024-11-25 19:25:07,090 - root                             (7f7c3ab70b28) :  ERROR (server:73) - BAZARR cannot start because of unhandled exception.
> 2024/11/25 19:24:51 | stdout | [custom-init] No custom files found, skipping...
> 2024/11/25 19:24:51 | stdout |  
> 2024/11/25 19:24:51 | stdout | ───────────────────────────────────────
> 2024/11/25 19:24:51 | stdout | Build-date: 2024-11-25T08:43:21+00:00
> 2024/11/25 19:24:51 | stdout | Linuxserver.io version: v1.4.6-beta.22-ls656

**To Reproduce**
Download development version in docker compose and start

**Comment by morpheus65535** [comment]
`OSError: [Errno 99] Address not available`

You're trying to bind Bazarr to an IP not available to the container (wild guess here that you're using Docker). Leave the listening IP to `0.0.0.0` or use an IP acutally accessible to the docker container. The Docker host IP isn't available to a process in the container.

**Comment by destpstrzy** [comment]
That helped. Thanks.
