### ISSUE TITLE
Capitalization of season and episode number not correct

### ISSUE THREAD

**Issue by TheFes** [morpheus65535/bazarr#278]
**Describe the bug**
Subtitles are downloaded by Bazarr, but instead of naming them "Series Name - S01E02 - Episode Name.en.srt" they are named "Series Name - s01e02 - Episode Name.en.srt". The video file has the S01E2 with capitals.

The History will say that a subtitle is downloaded, but it will not show as downloaded. So it will download it again on the next run. It will then overwrite the sub with the same filename, so again with the lower case s and e.

It doesn't do this for all my subtitles. It could be that the sub was already there with the incorrect lower case part, and that it simply uses the same name, and doesn't correct it to upper case. So it overwrites the existing sub, because it doesn't see that it's there, but then still uses the incorrect name of the sub which was already there. But I'm not sure about this.
If I rename the sub to match the capitalization of the video file, and do a scan for subs on that series, it will find them. 

**Expected behavior**
It would be nice if the filename would exactly match the video file, so that there are no differences in capitalization. 

**Screenshots**
Result in Windows folder (difference between upper case S01E05 and lower case s01e05
![result in folder](https://user-images.githubusercontent.com/28803438/51549695-2a359780-1e6b-11e9-9ba5-809e2d92dc6e.png)

Result in Bazarr (subtitles still missing)
![result in bazarr](https://user-images.githubusercontent.com/28803438/51549696-2a359780-1e6b-11e9-9a5c-f2990ab08d39.png)

Download result in Bazarr History
![history](https://user-images.githubusercontent.com/28803438/51549697-2a359780-1e6b-11e9-93d2-a2ae30dd8355.png)

**Software (please complete the following information):**
 - Bazarr: [v 0.7.2]
 - Sonarr version [v 2.0.0.5252]
 - OS: [Windows 10]

**Additional context**

**Comment by morpheus65535** [comment]
Could you provide a debug log please? I would like to see where the capital lettes are lost.

**Comment by TheFes** [comment]
Sorry, how can I enable debug logging, or where can I find it?

**Comment by TheFes** [comment]
Okay, here's what I did
For Supernatural S01E05 I removed the already downloaded (but incorrectly named) Dutch sub
For Supernatural S01E06 I removed the already downloaded (but incorrectly named) English sub

I have added a screenshot of the start status (with deleted subs and already downloaded subs) and a screenshot of the end result. I also added the log, but since Bazarr was also performing a scan a lot of subs were downloaded during this period as well.

Hope this helps

Screenshot start status in folder
![01 folder status before downloads](https://user-images.githubusercontent.com/28803438/51557512-6b36a780-1e7d-11e9-8702-9511ed4ca07e.png)


Screenshot end result in folder
![02 folder status end result](https://user-images.githubusercontent.com/28803438/51557506-640f9980-1e7d-11e9-8d02-40ad020c7333.png)


Log
[bazarr.log](https://github.com/morpheus65535/bazarr/files/2784146/bazarr.log)

**Comment by morpheus65535** [comment]
That's really strange because when I look at your log, the file is clearly saved with capital S and E:
`Saving <OpenSubtitlesSubtitle '249530' [nl]> to 'I:\\Series\\Supernatural\\Season 01\\Supernatural - S01E06 - Skin.nl.srt'`

I've tested and I cannot reproduce it with another series. :-/

**Comment by TheFes** [comment]
First of all, thanks for the swift responses.

However I think I was not clear in my test results.
I removed the EN subtitle for S01E06, so there was no EN subtitle in the folder. There was a NL subtitle with the incorrect filename (Supernatural - s01e06 - Skin.srt). 
You can see in the screenshots that both subtitles were updates around 19:30, so for both new versions were downloaded. But for the NL one, the wrong filename was kept.

So:
Bazarr doesn't find the existing subtitle if the capitalization isn't exactly the same as the video filename
When downloading the "missing" subtitle, it uses the same filename as the existing one, so the capitalization stays incorrect. So Bazarr still can find the (newly downloaded) sub.

**Comment by TheFes** [comment]
I did a new test

I started with TWD S02E08. I replaced the contents of the EN sub with only the text "test" making it only 1 KB in filesize, to see if actually anything happens to the file

So this is the start state in the folder, the EN subtitle with the incorrect lowercase s02e08 is marked. You can see that it is only 1 KB
![01a - folder contents](https://user-images.githubusercontent.com/28803438/51565318-00dc3200-1e92-11e9-8159-c0c8e4e57486.png)

While there are two subs downloaded, Bazarr doesn't recognize the EN sub, because of the lowercase part. 
![01b - bazarr status](https://user-images.githubusercontent.com/28803438/51565375-25380e80-1e92-11e9-9d8d-7f97ab7f08c3.png)

When I manually start a download for the EN sub, Bazarr starts searching. It will actually download it, as you can see from the filesize, it changed to 33KB. 
![02a - folder status](https://user-images.githubusercontent.com/28803438/51565423-51ec2600-1e92-11e9-896a-0934291fb342.png)

However the filename was not changed, so Bazarr stil doesn't recognize it.
![02b - bazarr status](https://user-images.githubusercontent.com/28803438/51565466-616b6f00-1e92-11e9-818c-a87faf8500c8.png)

When I delete the subtitle completely, and then download it again, it will give it the proper name.
![03a - folder status](https://user-images.githubusercontent.com/28803438/51565502-747e3f00-1e92-11e9-92ad-12176e742ba7.png)

Now Bazarr also recognizes it.
![03b - bazarr status](https://user-images.githubusercontent.com/28803438/51565521-83fd8800-1e92-11e9-87e7-8057d8bae2e2.png)

In the history you can see that it has been downloaded 3 times.
![04 bazarr history](https://user-images.githubusercontent.com/28803438/51565535-911a7700-1e92-11e9-8a37-ee9f96f29e4d.png)

And here's the log of this tests
[05 bazarr.log](https://github.com/morpheus65535/bazarr/files/2784620/05.bazarr.log)

**Comment by TheFes** [comment]
So, for me it would be nice if Bazarr would either correct the capitalization when downloading, so it matches the video filename, or it should ignore the capitalization when checking for subtitles, so it can actually find the existing ones.

Thanks a lot for your support so far, and the development on Bazarr!

**Comment by morpheus65535** [comment]
If I understand correctly, when Bazarr replace an existing subtitles file, it doesn’t name it correctly? I just want to be sure to have the right test case to reproduce it.

**Comment by TheFes** [comment]
Well, I think the main issue iw that Bazarr doesn't find the existing subtitle when the (lower/upper) case in the video file name is not a perfect match to the subtitle case. 
In my earlier example you can see this for Supernatural S01E05 Booldy Mary
![02 folder status end result](https://user-images.githubusercontent.com/28803438/51557506-640f9980-1e7d-11e9-8d02-40ad020c7333.png)

The episode is called "Supernatural - S01E05 - Bloody Mary.avi"
The English subtitle is called "Supernatural - s01e05 - Bloody Mary.srt"

I must admit that I don know where this difference comes from, but I think I have this issue for 800-900 files, more or less randomly on my Series drives.

Because of this difference, Bazarr doesn't recognize that there already is a sub, and downloads a new one. While doing that, it will overwrite the existing sub, keeping the same, incorrect filename. So next scan it will do the same.

When playing this episode in Emby, I can select the sub, so for Emby there is no issue in recognizing the English subtitle with the mismatch in lower and upper case.
![screenshot 2019-01-23 at 07 08 09](https://user-images.githubusercontent.com/28803438/51586880-217ea900-1edf-11e9-810c-933ee18d4e8d.png)

So, for me, the issue would also be solved if Bazarr would be able to find the subtitles which have the mismatch between lower and upper case compared to the video filename. 

Please note that I'm using both Bazarr and Emby on a Windows 10 system. I'm not an expert on Linux systems, but it could be that there is a difference between Windows and Linux about seeing upper/lower case as the same.

**Comment by TheFes** [comment]
Okay, clear. Any idea when 0.8 dev can be expected? In a few weeks, or either days or months.

**Comment by morpheus65535** [comment]
I would say 1 or 2 weeks maximum in dev branch.

**Comment by morpheus65535** [comment]
You can try 0.7.1 in dev branch now.

**Comment by TheFes** [comment]
If anything it seems to have made it worse.
- Updated to 0.7.1 yesterday
- Full refresh done at planned times overnight

Now I have over 1300 missing episode subs, instead of the 900 I had before
No subtitles have been downloaded since the update

I was already on 0.7.1, but somehow Bazarr thought I still needed to restart to apply an update
- Pressed the restart button, nothing happened (retried a couple of times)
- Rebooted the system. Message about update is gone now, but I'm still on 0.7.1

Tried to start a manual scan of all subtitles, but I get this message in the log:
"Execution of job "Update all episodes subtitles from disk (trigger: cron[hour='4'], next run at: 2019-01-28 09:50:20 CET)" skipped: maximum number of running instances reached (1)"

**Comment by TheFes** [comment]
Oh, small additional. When I try a manual download of a subtitle, it seems to be doing something, but nothing appears in the History

**Comment by morpheus65535** [comment]
Ok thanks, I'll look into this tonight. BTW small fixes in dev branch doesn't implies that we change the version number. It would never end.

**Comment by morpheus65535** [comment]
I've just commit some change to help recognize those dutch subtitles. Please update and confirm if it fix this issue. We'll see after that for the lower vs upper case issue.

**Comment by TheFes** [comment]
Updated, and all subtitles updated from disk.
"BAZARR All missing episode subtitles updated in database."

Unfortunately, without result. Still 1400 missing, and dut is recognized as none.

And, still no subtitle downloaded at all since I have updated to 0.7.1, last downloaded subtitle was over 24 hours ago, where before 0.7.1 it downloaded about 800 subtitles per day (mostly these not recognized lowercase subtitles)

**Comment by morpheus65535** [comment]
Did you restart Bazarr after updating? Mine is detecting `.sub.srt` as `nl` without any issue. Please provide a debug log (clear it first) while running a disk scan for a series where you should find this kind of subtitles.

**Comment by TheFes** [comment]
Hi,

I think I did a restart this morning (at least it was morning here in the Netherlands, not sure where you are located). But when I wanted to create the debug log you requested I saw there was a new version available.
I installed it and restarted, and did a new Series subs update. The issue with the .dut.srt not being recognized is resolved now, I'm back to 1024 missing subs.
I did  a check with a manual download of a subtitle, and that also works. So it seems Bazarr can download again. 
Will do a full wanted subs download now to check if that also works. (I do understand that the issue with the lowercase is not resolved, I just want to know if the download works again).

Anyway, I'm confident that the lower/uppercase issue will also be resolved in the near futures. If there are updates which I can test, please let me know!

Thanks for your work and the great support!

**Comment by TheFes** [comment]
Seems to be working fine now. The examples I gave in my earlier posts are all recognized now.
Thanks for the support!
