### ISSUE TITLE
Provider opensubtitlescom throttle count 1 of 5, waiting 5sec and trying again

### ISSUE THREAD

**Issue by paulVex** [morpheus65535/bazarr#2789]
Hello or Moin from germany 
ive got an Problem that i cant solve by my self.
about me:
I installed bazarr on my docker and have filled in my account data from Opensubtitles.com Name;Password
and i have VIP but i always get an "Provider opensubtitlescom throttle count 1 of 5, waiting 5sec and trying again error" befor that it was an diffrent error "ProviderErrror" im glad that this isnt the case anymore.
sometimes it installes some subtitles (3-10+ if im lucky)but somedays nothing. How can this be solved. Ive read about upgrading to a beta version but im to dump to that on a docker its an new universe to me. im on version v1.4.5

here is a bit longer log 

<html>
<body>

2024/12/11 18:27:33 | stdout | 2024-12-11 18:27:32,816 - root                             (7f991647a8) :  INFO (get_providers:438) - Provider opensubtitlescom throttle count 1 of 5, waiting 5sec and trying again
-- | -- | --
2024/12/11 18:17:24 | stdout | 2024-12-11 18:17:23,608 - root                             (7f991647a8) :  INFO (get_providers:438) - Provider opensubtitlescom throttle count 1 of 5, waiting 5sec and trying again
2024/12/11 18:09:38 | stdout | 2024-12-11 18:09:36,444 - root                             (7f991647a8) :  INFO (get_providers:438) - Provider opensubtitlescom throttle count 1 of 5, waiting 5sec and trying again
2024/12/11 17:39:08 | stdout | 2024-12-11 17:39:08,183 - root                             (7f9d06f7a8) :  INFO (series:125) - BAZARR Finished searching for missing Series Subtitles. Check History for more information.
2024/12/11 17:38:58 | stdout | 2024-12-11 17:38:58,021 - root                             (7f9993d7a8) :  INFO (get_providers:438) - Provider opensubtitlescom throttle count 1 of 5, waiting 5sec and trying again
2024/12/11 17:38:29 | stdout | 2024-12-11 17:38:28,921 - root                             (7f9c3287a8) :  INFO (movies:114) - BAZARR Finished searching for missing Movies Subtitles. Check History for more information.
2024/12/11 17:35:58 | stdout | 2024-12-11 17:35:58,494 - root                             (7f9993d7a8) :  INFO (get_providers:438) - Provider opensubtitlescom throttle count 3 of 5, waiting 5sec and trying again
2024/12/11 17:35:22 | stdout | 2024-12-11 17:35:22,699 - root                             (7f9993d7a8) :  INFO (get_providers:438) - Provider opensubtitlescom throttle count 2 of 5, waiting 5sec and trying again
2024/12/11 17:34:09 | stdout | 2024-12-11 17:34:09,648 - root                             (7f9993d7a8) :  INFO (get_providers:438) - Provider opensubtitlescom throttle count 1 of 5, waiting 5sec and trying again
2024/12/11 17:33:43 | stdout | 2024-12-11 17:33:41,440 - apscheduler.executors.default    (7f9c3287a8) :  ERROR (base:131) - Job "Sync with Sonarr (trigger: interval[1:00:00], next run at: 2024-12-11 18:30:49 CET)" raised an exception
2024/12/11 17:19:36 | stdout | 2024-12-11 17:19:35,400 - root                             (7f9993d7a8) :  INFO (get_providers:438) - Provider opensubtitlescom throttle count 1 of 5, waiting 5sec and trying again
2024/12/11 17:15:54 | stdout | 2024-12-11 17:15:54,028 - root                             (7f9993d7a8) :  INFO (get_providers:438) - Provider opensubtitlescom throttle count 1 of 5, waiting 5sec and trying again
2024/12/11 17:13:43 | stdout | 2024-12-11 17:13:42,600 - root                             (7f9d06f7a8) :  INFO (get_providers:438) - Provider opensubtitlescom throttle count 1 of 5, waiting 5sec and trying again

</body>
</html>

**Comment by paulVex** [comment]
+ this error just got up Throttling opensubtitlescom for 10 minutes, until 24/12/11 18:52, because of: ProviderError. Exception info: "'Gateway Time-out' ~ opensubtitlescom.py@550"

**Comment by morpheus65535** [comment]
There's issues on the provider API itself, not in Bazarr. You can't do anything about it, you must wait for them to fix it.

This is a bug reporting system, if you need to support, please come to Discord support channel.
