### ISSUE TITLE
Is pip really needed?

### ISSUE THREAD

**Issue by pven** [morpheus65535/bazarr#279]
I am having a lot of trouble while installing pip on my Synology DS214+. It just does not want to work, so this means I am running an older version of Bazarr since pip is needed. Is there any way to not use pip? I know it is a stupid question, and I can probably guess the answer. But I am desperate (but just not desperate enough to buy a new Synology). ;-)

**Comment by morpheus65535** [comment]
In fact you need to install gevent python module. It seems that it is included in Synology Python Module package: https://www.synology.com/en-global/dsm/packages/PythonModule

You can try installing this and update Bazarr to latest version. However, I have no idea which version of gevent is packaged.

**Comment by pven** [comment]
Wtf ... thanks to your message I checked further in the package-overview and found out that Python module was not installed. I installed it, and now I don't get the pip-is-missing-error anymore. :-)

You are great. Thanks!
