### ISSUE TITLE
No movies found from radarr

### ISSUE THREAD

**Issue by jertim123** [morpheus65535/bazarr#2791]
I used radarr and bazarr for more than a year now.
I installed and configured both on my synology nas and it worked fine.
A few months ago it stopped working (I think after an update of synology or bazarr)
The connection to radarr is fine when I click test but no movies are found and nothing in history
I have downloaded movies in radarr (and in my radarr download folder)
But it seems bazarr doesnt sees them?

![image](https://github.com/user-attachments/assets/a402f5b1-dd05-4894-8008-a7122f502be1)
![image](https://github.com/user-attachments/assets/f8a16b33-241f-4910-97ed-4e0aa4423381)

**Comment by morpheus65535** [comment]
This is a bug reporting board. For support, please come to our Discord support server.
