### ISSUE TITLE
Can't add subscene.cam to the providers list

### ISSUE THREAD

**Issue by araghamdi** [morpheus65535/bazarr#2792]
Greetings

Per the application guides, subscene is part of the list, but I can't find or add it.
I would appreciate your support. 

Below is a screenshot and the application version.

![Screenshot 2024-12-13 at 9 05 24 PM](https://github.com/user-attachments/assets/f17be52d-05d9-4006-a37e-ba68e6e02117)

 - Bazarr: [1.4.5]
 - Operating System [Linux-4.4.302+-x86_64-with-glibc2.36]

**Comment by morpheus65535** [comment]
Subscene.com is dead:

![image](https://github.com/user-attachments/assets/81481539-137e-4975-a2cb-6cb2b291723d)

**Comment by araghamdi** [comment]
It is back, this is the new url https://subscene.cam/

**Comment by araghamdi** [comment]
> Subscene.com is dead:
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/81481539-137e-4975-a2cb-6cb2b291723d)
> 
> 

It is back, this is the new url https://subscene.cam/

**Comment by morpheus65535** [comment]
We've been fighting against them for years to keep access to their site using Bazarr. They made it pretty clear they don't want us and implemented latest Cloudflare protection that we're not able to circumvent. I don't plan to bring back that provider. There's plenty others, choose another one.
