### ISSUE TITLE
Better handling of "TooManyRequests"

### ISSUE THREAD

**Issue by stefandevo** [morpheus65535/bazarr#28]
Logs are full of errors, but in the end, it's just  Too May Request.
Suggest to check upon this error and once received, wait x seconds/minutes before executing again.

`Unexpected error in provider u'addic7ed'`

```
'Traceback (most recent call last):
File "/Library/Python/2.7/site-packages/subliminal/core.py", line 118, in list_subtitles_provider
return self[provider].list_subtitles(video, provider_languages)
File "/Library/Python/2.7/site-packages/subliminal/providers/addic7ed.py", line 273, in list_subtitles
return [s for s in self.query(video.series, video.season, video.year)
File "/Library/Python/2.7/site-packages/subliminal/providers/addic7ed.py", line 238, in query
raise TooManyRequests()
TooManyRequests'
```

**Comment by morpheus65535** [comment]
I'm going to have to take a look at this. You eventually get rid of this error when you'll get less missing subtitles but, in the mean time, it's kind of noisy... ;-)

**Comment by morpheus65535** [comment]
Even in debug mode, I cannot get a more detailed traceback where I could pinpoint the exact place where I need to catch exception. Nothing related to bazarr in this... Got an idea?

**Comment by morpheus65535** [comment]
It's not possible with v2 of Subliminal. Exception cannot be catched: https://github.com/Diaoul/subliminal/issues/875

I keep it open as a reminder when v3 is going to get out.

**Comment by Freekers** [comment]
Isn't it possible to just add a wait of X minutes whenever this message popups in the logfile as a temporary fix, as suggested by @stefandevo ? Thanks!

**Comment by morpheus65535** [comment]
@Freekers I can't even catch those error so I can't take action on it. They are send directly to logger. I'm gonna close this one as I have a story to better manage exception from Subliminal when version 3 will be available... if it is one day...
