### ISSUE TITLE
[Feature Request] Auto-Update include restart

### ISSUE THREAD

**Issue by rg9400** [morpheus65535/bazarr#280]
Right now, bazarr grabs the latest version automatically if the option is turned on, but it still requires the user the click the link to manually restart bazarr. Ideally, after grabbing the release, bazarr should restart automatically with no manual touch.

It should be part of the update task itself. So even if the user will manually trigger the update, the restart should happen automatically as a part of this process.

**Comment by morpheus65535** [comment]
Done in master.
