### ISSUE TITLE
When renaming a movie folder in radarr, bazarr does not update paths.

### ISSUE THREAD

**Issue by onedr0p** [morpheus65535/bazarr#2802]
**Describe the bug**

I recently changed my paths in radarr from `Blues Brothers 2000 (1998)` to `Blues Brothers 2000 (1998) {imdb-tt0118747}` is there a "supported" way in bazarr to have this reflected, or do I need to resort to editing the sqlite file with the path changes? I've tried turning off radarr and turning it back on in bazarr but it doesn't look like it cleans up the database.

**To Reproduce**

Change Movie **folder** path in Radarr, bazarr will not update the paths.

**Expected behavior**

Bazarr to update the paths from Radarr

**Screenshots**

```
BAZARR cannot update movie /media/Library/Movies/Blues Brothers 2000 (1998) {imdb-tt0118747}/Blues Brothers 2000 (1998) {imdb-tt0118747} [BLURAY-1080p][AC3 5.1][x264]-BHDStudio.mp4 because of (sqlite3.IntegrityError) FOREIGN KEY constraint failed [SQL: UPDATE table_movies SET "alternativeTitles"=?, audio_codec=?, audio_language=?, fanart=?, file_size=?, format=?, "imdbId"=?, monitored=?, movie_file_id=?, overview=?, path=?, poster=?, "radarrId"=?, resolution=?, "sceneName"=?, "sortTitle"=?, tags=?, title=?, "tmdbId"=?, updated_at_timestamp=?, video_codec=?, year=? WHERE table_movies."tmdbId" = ?] [parameters: ("['The Blues Brothers 2000']", 'AC3', "['English']", '/MediaCover/3362/fanart.jpg?lastWrite=638705095610106682', 7966960213, 'Bluray', 'tt0118747', 'True', 3594, "...", '/media/Library/Movies/Blues Brothers 2000 (1998) {imdb-tt0118747}/Blues Brothers 2000 (1998) {imdb-tt0118747} [BLURAY-1080p][AC3 5.1][x264]-BHDStudio.mp4', '/MediaCover/3362/poster-500.jpg?lastWrite=638705095608946661', 3362, '1080p', 'Blues.Brothers.2000.1998.BluRay.1080p.DD.5.1.x264-BHDStudio', 'blues brothers 2000', '[]', 'Blues Brothers 2000', '11568', '2024-12-24 12:01:24.327085', 'h264', '1998', '11568')] (Background on this error at: https://sqlalche.me/e/20/gkpj)
```

**Software (please complete the following information):**
 - Bazarr: 1.5.0
 - Radarr version: [5.17.0.9555](https://github.com/Radarr/Radarr/releases/tag/v5.17.0.9555)
 - Sonarr version: [4.0.11.2793](https://github.com/Sonarr/Sonarr/releases/tag/v4.0.11.2793)
 - OS: Docker

**Comment by morpheus65535** [comment]
What's the output of this SQL query in your original database (could be from last backup)?

`SELECT * FROM table_movies WHERE radarrId = 3362;`

**Comment by onedr0p** [comment]
Nothing came back with that radarrId, it could have been due to me editing the DB but here is the entry from the database that relates to the post.

```
['The Blues Brothers 2000'] | AC3 | ['English'] |   | /MediaCover/8659/fanart.jpg?lastWrite=638687365545182907 |   | 7966960213 | Bluray | tt0118747 | [] | True | 31200 | Finally released from prison, Elwood Blues is once again enlisted by Sister Mary Stigmata in her latest crusade to raise funds for a children's hospital. Hitting the road to re-unite the band and win the big prize at the New Orleans Battle of the Bands, Elwood is pursued cross-country by the cops. | /media/Library/Movies/Blues Brothers 2000 (1998)/Blues Brothers 2000 (1998) {imdb-tt0118747} [Bluray-1080p][AC3 5.1][x264]-BHDStudio.mp4 | /MediaCover/8659/poster-500.jpg?lastWrite=638687365544462893 | 1 | 8659 | 1080p | Blues.Brothers.2000.1998.BluRay.1080p.DD.5.1.x264-BHDStudio | blues brothers 2000 | [['en', '/media/Library/Movies/Blues Brothers 2000 (1998)/Blues Brothers 2000 (1998) {imdb-tt0118747} [Bluray-1080p][AC3 5.1][x264]-BHDStudio.en.srt', 97484]] | [] | Blues Brothers 2000 | 11568 | h264 | 1998 |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
```

I think my issue was I did the imdb folder renaming in radarr when I was on 1.4.x, then upgraded to 1.5.0. I know that someone did the imdb folder migration when using 1.5.0 and the paths were updated correctly. Maybe this is a niche issue and I should have done the upgrade to 1.5.0 before renaming the folder paths in radarr?

**Comment by morpheus65535** [comment]
So what's the radarrId for this movie now?

**Comment by onedr0p** [comment]
I ended up completely wiping the old bazarr DB and starting fresh, in the old DB it was 8659.

**Comment by onedr0p** [comment]
Feel free to close this issue, it should be fairly easy to reproduce the issue if you wanted to look more into it:

- Deploy bazarr 1.4.3
- Rename movie path in radarr
- Upgrade to bazarr 1.5.0
- Refresh radarr task in bazarr
