### ISSUE TITLE
Bazarr Fails on Python 3.13+ Due to SQLAlchemy and Removed Modules (imghdr, pipes)

### ISSUE THREAD

**Issue by remanifest** [morpheus65535/bazarr#2803]
**Describe the bug**
When running Bazarr with Python 3.13+, the following errors occur due to deprecated or removed modules:

- SQLAlchemy: The bundled SQLAlchemy library is outdated and fails with the following error due to stricter subclassing checks in Python 3.13+:
`AssertionError: Class <class 'sqlalchemy.sql.elements.SQLCoreOperations'> directly inherits TypingOnly but has additional attributes {'__firstlineno__', '__static_attributes__'}`
- imghdr: The imghdr module has been removed in Python 3.13, causing crashes in deathbycaptcha.
- pipes.quote: The pipes module has been removed, leading to failures in libfilebot.

These issues prevent Bazarr from starting successfully on systems with Python 3.13+.

**To Reproduce**
1. Run Bazarr on a system with Python 3.13 or later.
2. Start the Bazarr service.
3. Observe crashes in the logs.

**Expected behavior**
Bazarr should start without errors and function correctly when running on Python 3.13 or later. 

**Software:**
 - Bazarr:  v 1.5.0
 - Radarr v 5.16.3.9541
 - Sonarr v 4.0.11.2680
 - OS: Arch Linux (kernel 6.12.6)
 - Python: v 3.13.1

**Additional context**
I initially discovered these issues on Bazarr v1.4.5. After updating to v1.5.0, I confirmed the problems persist.

To resolve the issues locally, I applied the following fixes:

1. SQLAlchemy: The bundled sqlalchemy.util was replaced with the latest version from the system-installed SQLAlchemy:
`cp -R /usr/lib/python3.13/site-packages/sqlalchemy/util/* /usr/lib/python3.13/site-packages/bazarr/libs/sqlalchemy/util/`

2. imghdr:
- Replaced imghdr.what functionality with python-magic:
```python
import magic

def what(_, img):
    mime = magic.Magic(mime=True)
    img_type = mime.from_buffer(img)
    if img_type.startswith("image/jpeg"):
        return 'jpeg'
    elif img_type.startswith("image/png"):
        return 'png'
    elif img_type.startswith("image/gif"):
        return 'gif'
    return None
```
- Saved file as `imghdr.py` in the `custom_libs` folder
- Updated deathbycaptcha.py to import the new `what` function:
```python
from imghdr import what
```
3. Replaced `pipes.quote` with `shlex.quote` in `main.py` located in `custom_libs/libfilebot`:
```python
from shlex import quote
```

**Comment by morpheus65535** [comment]
Python 3.13 is untested, unsupported and Bazarr won't even start. Use 3.8 to 3.12.

**Comment by azulu** [comment]
3.13 has been out for a few months, now. Is there no workaround other than downgrading?

**Comment by morpheus65535** [comment]
> 3.13 has been out for a few months, now. Is there no workaround other than downgrading?

No workaround possible. We depends on more than a hundreds external module that must all support 3.13 before we can officially support 3.13.

**Comment by remanifest** [comment]
> 3.13 has been out for a few months, now. Is there no workaround other than downgrading?

One fix is what I posted when I opened this, which was in an effort to increase usability for others and to help the package maintainer.

Another more elegant solution exists in the bazarr PKGBUILD for Arch Linux. Effectively, there's a patch to define a custom strtobool function, and remove the import of the strtobool library (which is deprecated) in `get_args.py`. Then, you can `sed -i 's/from pipes/from shlex/ custom_libs/libfilebot/main.py`

Instead of using `imghdr.what`, you can use magic to do the same thing. This becomes `imghdr.py`, and gets written to `custom_libs/imghdr.py`
```python
import magic

def what(_, img):
    mime = magic.Magic(mime=True)
    img_type = mime.from_buffer(img)
    if img_type.startswith("image/jpeg"):
        return 'jpeg'
    elif img_type.startswith("image/png"):
        return 'png'
    elif img_type.startswith("image/gif"):
        return 'gif'
    return None
```

**Comment by morpheus65535** [comment]
Like I said on Discord, this rely on python-magic module that as a lot of dependencies and some seems to need to be compiled directly on client (so they cannot be vendored and must be added to requirements.txt). I'm really not a fan and this is the reason why we did not implement the proposed changes.

**Comment by remanifest** [comment]
> Like I said on Discord, this rely on python-magic module that as a lot of dependencies and some seems to need to be compiled directly on client (so they cannot be vendored and must be added to requirements.txt). I'm really not a fan and this is the reason why we did not implement the proposed changes.

I can understand the reticence to use magic, given the fact that it would require external dependencies on non-Linux systems. A `filetype` implementation would very likely do the same job, with a high degree of accuracy:
```python
import filetype

_IMG_MIME = {
    'image/jpeg': 'jpeg',
    'image/png': 'png',
    'image/gif': 'gif'
}

def what(_, img):
    img_type = filetype.guess(img)
    return _IMG_MIME.get(img_type.mime) if img_type else None
``` 
This is working for me locally as well, and should alleviate external dependency and vendoring concerns. The benefit of this is that you can expand the mime map easily enough, and for the types we're working with so far, filetype is highly accurate and efficient, because we're just using a single dictionary.

**Comment by morpheus65535** [comment]
@remanifest willing to create a PR based on dev branch? SQLalchemy should already be recent enough. I'll try to test it on 3.8 to 3.13 and we'll merge it if results are good.

**Comment by remanifest** [comment]
> [@remanifest](https://github.com/remanifest) willing to create a PR based on dev branch? SQLalchemy should already be recent enough. I'll try to test it on 3.8 to 3.13 and we'll merge it if results are good.

Happy to do it:
https://github.com/morpheus65535/bazarr/pull/2899

Thank you for explaining the reasons why this was a sub optimal solution in its first iteration!

**Comment by morpheus65535** [comment]
I don't get any error with the changes we've made. It should be working with upcoming 1.5.2-beta.37. Let me know if you get some issues.

**Comment by d4rkfella** [comment]
Only issue i had was with lxml failing to compile, had to upgrade the version to > 5.0.0 . Could be a skill issue tho.

**Comment by morpheus65535** [comment]
> Only issue i had was with lxml failing to compile, had to upgrade the version to > 5.0.0 . Could be a skill issue tho.

5.3.0 seems to be widely used already (hotio images). No problem there so I guess we're good.

**Comment by remanifest** [comment]
1.5.2-beta.37 is working very nicely for me
