### ISSUE TITLE
SDH Subtitles From opensubtitles.com Being Imported as Forced

### ISSUE THREAD

**Issue by Xewdy444** [morpheus65535/bazarr#2806]
**Describe the bug**
SDH subtitles from opensubtitles.com are often also falsely marked as forced, and I don't believe that Bazarr is handling this correctly at the moment. If you have a language profile that includes forced subtitles, Bazarr will download and import any subtitles that have the forced flag set that match the specified language on opensubtitles.com. The problem with this is that users are allowed to mark subtitles as both SDH and forced on opensubtitles.com, and these often end up being regular SDH subtitles that are incorrectly marked as forced as well. Bazarr then imports these subtitles as forced given the forced flag being set. The intended behavior seems to be that the subtitles should be either one or the other based on the naming logic seen here: https://github.com/morpheus65535/bazarr/blob/6ec304d13d5ed8a217f0f6d6ee98ecc98cac87af/bazarr/subtitles/processing.py#L56C1-L61C29. My proposed solution is to mark all subtitles with both the SDH and forced flag set as just SDH for this subtitles provider.

Example of SDH subtitles with both flags set: https://www.opensubtitles.com/en/subtitles/yellowstone-2018-s03e10-720p-amzn-webrip-x264-galaxytv

**To Reproduce**
1. Create a language profile on Bazarr that includes forced subtitles
2. Have Bazarr download subtitles from opensubtitles.com that have both the SDH and forced flag set to fill this missing language profile
3. Observe that Bazarr labels the subtitles as HI in the history menu but imports them as forced (and names the subtitles file as such)

**Expected behavior**
Subtitles with both the SDH and forced flags set should be considered as just SDH. These subtitles should not be imported to fill a missing forced subtitles language profile.

**Screenshots**
![image](https://github.com/user-attachments/assets/f352385c-b5e1-4aa9-8c82-76c9439ebbf1)
![image](https://github.com/user-attachments/assets/c7b74f73-ffb6-429d-8619-f370893ab1b7)

**Software**
 - Bazarr version 1.5.0
 - Radarr version 5.16.3.9541
 - Sonarr version 4.0.11.2793
 - OS: Unraid
 
 I've opened a pull request with a proposed fix here: https://github.com/morpheus65535/bazarr/pull/2807

**Comment by morpheus65535** [comment]
Merged, thanks!
