### ISSUE TITLE
latest update deleted Movies History

### ISSUE THREAD

**Issue by rmichelena** [morpheus65535/bazarr#2810]
have been on nightly for some time, now updated from 1.5.0 directly to 1.5.1 beta 1 (skipped beta 0)
everything seems fine except that my Movies History is now empty.
(Series History is fine)

Ubuntu 24.0.2, latest Sonarr (4.0.11.2680) and Radarr (5.16.3.9541)

**Comment by morpheus65535** [comment]
Yes sorry about that. I've fixed the bug that caused this in upcoming beta but you'll have to restire your latest backup to restore history.

**Comment by rmichelena** [comment]
Mmm... can't... when I try to restore from latest backup, it says "Error 400: Filename not Provided" - then goes on restarting the UI, but nothing changed.

**Comment by morpheus65535** [comment]
I'll debug that tomorrow. You can do it manually by stopping Bazarr and restoring the database in the zipped backup to config/db.

**Comment by rmichelena** [comment]
Did it. Stopped container. Manually restored bazarr.db from zipped backup. Started container.
Movies history is blank. Which makes sense, because it's the same as upgrading from 1.5.0 to beta1 (beta1 encounters a good database and breaks it).

**Comment by rmichelena** [comment]
So stopped, manually restored from zip, installed stable 1.5.0, everything fine now. Will wait for next beta :)

**Comment by morpheus65535** [comment]
I created the fix this afternoon. It hasn't been released yet. You'll have to wait for tomorrow image.

**Comment by morpheus65535** [comment]
Fix confirmed to works. Once in 1.5.0-beta.2, restore your latest backup pre-1.5.0-beta.1 and you should be fine.

**Comment by rmichelena** [comment]
Yes, everything seems fine now. Updated from 1.5.0 to b2 without issues. Haven't checked it backups do restore in b2.

**Comment by morpheus65535** [comment]
Haven't checked restore yet. I will in upcoming days.
