### ISSUE TITLE
Unable to index external subtitles after download (OSError: [Errno 5] I/O error)

### ISSUE THREAD

**Issue by renanwillian** [morpheus65535/bazarr#2813]
**Describe the bug**
I'm experiencing an issue with Bazarr where, after it downloads subtitles for some movies, it fails to index the subtitles correctly. The movie's subtitles are present in the folder, but Bazarr is unable to index them, and it continuously tries to download them again.

**To Reproduce**
1. I have the movie "Watchmen (2009) Dir Cut 720p BRRip.mp4" in the movie folder.
2. Bazarr downloads the subtitles "Watchmen (2009) Dir Cut 720p BRRip.en.srt" (English) and "Watchmen (2009) Dir Cut 720p BRRip.pt-BR.srt" (Portuguese).
3. The subtitles are located in the same folder as the movie.
4. Bazarr fails to index the external subtitles and logs the following error:

BAZARR unable to index external subtitles.
```
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/subtitles/indexer/movies.py", line 95, in store_subtitles_movie
    subtitles = guess_external_subtitles(full_dest_folder_path, subtitles, "movie",
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bazarr/bin/bazarr/subtitles/indexer/utils.py", line 127, in guess_external_subtitles
    text = f.read()
           ^^^^^^^^
OSError: [Errno 5] I/O error
```

**Expected behavior**
The subtitles should be indexed after download.

**Debug logging**
BAZARR storing those languages to DB: []	2024-12-30 02:10:15	
BAZARR unable to index external subtitles.	2024-12-30 02:10:15	
external subs: found {'Watchmen (2009) Dir Cut 720p BRRip.en.srt': <Language: alpha3=eng>, 'Watchmen (2009) Dir Cut 720p BRRip.pt-BR.srt': <Language: alpha3=por;country=BR>}	2024-12-30 02:10:15	
Found subtitles {'Watchmen (2009) Dir Cut 720p BRRip.en.srt': <Language: alpha3=eng>, 'Watchmen (2009) Dir Cut 720p BRRip.pt-BR.srt': <Language: alpha3=por;country=BR>}	2024-12-30 02:10:15	
external subs: scanning path /movies/Watchmen (2009)/Watchmen (2009) Dir Cut 720p BRRip.mp4	2024-12-30 02:10:15	
BAZARR returning this binary: /usr/bin/ffprobe	2024-12-30 02:10:15	
BAZARR is trying to index embedded subtitles.	2024-12-30 02:10:15	
BAZARR started subtitles indexing for this file: /movies/Watchmen (2009)/Watchmen (2009) Dir Cut 720p BRRip.mp4	

**Inside docker container:**
root@1ca8c17b3806:/movies/Watchmen (2009)# ls -l
total 12582912
-rwxrwxrwx 1 1000 users     138653 Dec 30 01:58 'Watchmen (2009) Dir Cut 720p BRRip.en.srt'
-rwxrwxrwx 1 1000 users 1078973614 Jun 18  2012 'Watchmen (2009) Dir Cut 720p BRRip.mp4'
-rwxrwxrwx 1 1000 users     169829 Dec 30 01:58 'Watchmen (2009) Dir Cut 720p BRRip.pt-BR.srt'

**Software (please complete the following information):**
- Bazarr Version: 1.5.0
- Package Version: v1.5.0-ls284 by linuxserver.io
- Radarr Version: 5.16.3.9541
- Operating System: Linux-6.8.4-3-pve-x86_64-with

**Additional context**
The issue seems to affect only some movies. Other movies with subtitles are being indexed correctly.
I have already tried deleting the .srt files, but Bazarr downloads them again without indexing them.

**Comment by morpheus65535** [comment]
`OSError: [Errno 5] I/O error` sounds like a disk was full when subtitles were written or the disk is simply failing. I would check the first and run diagnostic tools on your disk.

**Comment by renanwillian** [comment]
Thanks for the quick response! As confirmed through diagnostics, the drive was failing indeed.
