### ISSUE TITLE
[Wiki Request] Add info about sometimes requires "python-dev" package to install docs

### ISSUE THREAD

**Issue by MichaIng** [morpheus65535/bazarr#282]
We just ran into an issue where `pip install gevent` throws an error on a Raspberry Pi Raspbian machine, while on a similar Debian x86_64 it did not: https://github.com/Fourdee/DietPi/issues/2435

Error message, end of stack trace: `greenlet.h:8:20: fatal error: Python.h: No such file or directory`

Solution was to install `python-dev`, as can be found from various sources in the internet, when searching the above error. Interestingly it is not required on Debian x86_64 but on RPi Raspbian, so it seems to depend either on the CPU architecture (ARM vs x86) or the specific repo (Raspbian vs Debian).
Raspbian and Debian ship pretty much similar packages, so I guess it's the architecture.

However, it would prevent users from running into and hanging on the same issue, if you could add it to your install instructions: https://github.com/morpheus65535/bazarr/wiki/Installation-Running-from-Source
- EG: 
  > If `pip` fails with above error, install `python-dev` and retry

**Comment by morpheus65535** [comment]
Thanks for reporting this! I’ll add it to the wiki.

**Comment by garret** [comment]
I had the issue with the distribution DietPi on a Raspberry Pi 3B. DietPi is based on Raspbian as I know.

**Comment by MichaIng** [comment]
@morpheus65535 
Jep looks good 👍. However I am still not sure, if it's true for Raspbian only, or for ARM devices (e.g. Debian armhf/arm64) in general. E.g. perhaps x86 build libs are natively included into python(-pip), while other archs are not. Would need some testing.

But at least on Raspbian (thus ARM for sure), it is definitely required.

We aim to add Bazarr as software option natively into DietPi (`dietpi-software` automated install) by times: https://github.com/Fourdee/DietPi/issues/2045
As always there are more requests than time to implement, but great is that Bazarr installs quite easy, and it's the logic addition to Sonarr/Radarr/Lidarr to have a complete media download solution.
Then at latest we will run install tests on many different ARM devices and will find out more about where python-dev is required and where not.

**Comment by morpheus65535** [comment]
Ok, I've added a mention about other ARM based distro that could require it. Keep me informed of your result.

I've looked at DietPi and it look pretty nice. Haven't heard of it before. Thanks for integrating Bazarr!
