### ISSUE TITLE
Can't configure Radarr after installation

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#285]
**To Reproduce**
1. In the installation wizard configure only Sonarr
2. End the installation wizard and restart Bazarr
3. Try to enable Radarr, you will see the error in the screenshot. I can't save the config even if I fill the Radarr API token.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/10577978/51715753-56534300-203a-11e9-896d-1ce31bc80b7c.png)

**Software (please complete the following information):**
 - Bazarr Ver. 0.7.0.4

**Comment by ngosang** [comment]
Ok, the screenshot is wrong. I did:
1. Enable Radarr (with the switch)
2. Go to Radarr tab and configure the API token
3. Click the test button, It said everything was ok.
4. I can't click the save button, was disabled and I can see the red message.

**Comment by halali** [comment]
Ok can you check latest development branch? I pushed possible fix.

**Comment by morpheus65535** [comment]
Did you click somewhere else in the page after running the test? Could be a validation not triggered.

**Comment by ngosang** [comment]
Yes, I tried everything... The only way was editing the page to remove the "disable" class in the button so I can press it.
I will test development in the following days.

**Comment by ngosang** [comment]
@halali fix works!! I can save now.

@morpheus65535 Please, don't take my issues as something bad. I'm opening these issues because I'm using this software and I think the feedback will help improve the software.

The @halali change fix the major problem, but another minor improvement will be mark the "Not tested recently" text in red. It's not easy to figure out what is the error/missing field.
![imagen](https://user-images.githubusercontent.com/10577978/51853721-40d76500-2329-11e9-92fa-cef1041b3597.png)

**Comment by ngosang** [comment]
Just print in red the message "Not tested recently" or "Test failed..."

**Comment by morpheus65535** [comment]
@ngosang Don’t worry, I don’t take it bad.

Putting it in red would means it need to be tested. The way it is only means it haven’t been tested recently. If you come back to settings later on, it still gonna be in red even if it have been tested and worked before. I don’t see this as an improvement.
