### ISSUE TITLE
Typo error in Radarr configuration

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#286]
**Describe the bug**
In the Radarr tab I see Sonarr in red

**Screenshots**
![imagen](https://user-images.githubusercontent.com/10577978/51715834-974b5780-203a-11e9-8aa4-fb9dfec95673.png)

**Software (please complete the following information):**
 - Bazarr Ver. 0.7.0.4

**Comment by halali** [comment]
Thanks for report... been fixed in development branch
