### ISSUE TITLE
Strange error for some shows

### ISSUE THREAD

**Issue by stefandevo** [morpheus65535/bazarr#29]
I see some strange errors for some shows:

```No show id found for u'Berlin Station' ({'year': None})```

What does this mean?

**Comment by morpheus65535** [comment]
Those error a related to small bugs in subliminal library which is used by Bazarr to download subtitles. Some providers return error with some series. Other provider are going to get subtitles. I'll take a look if I can just hide those errors.

**Comment by morpheus65535** [comment]
Should not be seen anymore in your logs. :-)
