### ISSUE TITLE
Minor issue in user interface

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#290]
**Describe the bug**
In Wanted tab, I don't have movies nor series but the pagination is enabled. I can go to page 2, 3...

**Screenshots**
![imagen](https://user-images.githubusercontent.com/10577978/51717527-7803f880-2041-11e9-81b3-9cc457ed0689.png)

**Software (please complete the following information):**
 - Bazarr Ver. 0.7.0.4

**Comment by morpheus65535** [comment]
Fixed in upcoming v0.7.1. Thanks!
