### ISSUE TITLE
[Feature request] Don't show the wanted icon when it's zero

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#291]
In Radarr & Sonarr when you see an icon in the top menu mean you need to perform some manual action... IMHO we should hide the counter when it's 0.
![imagen](https://user-images.githubusercontent.com/10577978/51854308-c9a2d080-232a-11e9-8b9c-d91edde8adb2.png)

**Comment by morpheus65535** [comment]
I see the logic behind your request. We’re going to think about it but it’s going to be a low priority even if we decide to go that way.

**Comment by morpheus65535** [comment]
This is now done in dev branch. You can test it.
