### ISSUE TITLE
Bazarr service goes to paused state when trying to start it.

### ISSUE THREAD

**Issue by nmbrg** [morpheus65535/bazarr#294]
**Describe the bug**
When trying to start the bazarr service on Windows Server 2012 R2, it just goes to a paused state right away.

**To Reproduce**
1. Follow the installation instuctions for windows (nssm).

**Expected behavior**
Expected it to work..

**Software (please complete the following information):**
 - Bazarr: latest available on github (pulled it from there right now)
 - OS: Windows Server 2012 R2

**Comment by nmbrg** [comment]
Not sure how i would start it in a command prompt. because just running the .py file results in a "ERROR: (main:53) - BAZARR require gevent Python module to be installed using pip." Bazarr exited.

the way i installed it (as service) was as follow:

1. download zip from github: https://github.com/morpheus65535/bazarr
2. extracted said zip to c:/bazarr
3. opened a command prompt as administrator
4. ran "nssm install bazarr" in command prompt.
5. added python path  "C:\Python27\python.exe"
6. added Startup Directory: "C:\Python27"
7. added Arguments: "C:\bazarr\bazarr.py"
8. unchecked "console windows" under the process tab.
9. clicked "install service".
10. ran "nssm start bazarr" in command prompt. (by the way, you've misstyped the info at the instructions page, you're saying we should run "command nssm start bazarr".)
11. and here the service just goes from "starting" to "paused".

**Comment by nmbrg** [comment]
Yes, that's were i red the instructions..
https://github.com/morpheus65535/bazarr/wiki/Using-NSSM-on-Windows

**Comment by morpheus65535** [comment]
https://github.com/morpheus65535/bazarr/wiki/Installation-Running-from-Source

**Comment by NightMean** [comment]
I followed the same instructions and I have the same problem, Bazarr works perfectly but nssm is unable to start it,
I made .py files to open in pythonw.exe all the time and made shortcut from the bazarr.py and added that to the startup folder. I guess it's not that good of a solution but ti does the same trick.

**Comment by morpheus65535** [comment]
I don't support NSSM myself but if you find the solution, don't hesitate to share with us and we'll update the wiki. Good luck!

**Comment by NightMean** [comment]
I've just followed the Tautulli wiki Windows Interactive installation as I know it works and it's bit easier
[https://github.com/Tautulli/Tautulli-Wiki/wiki/Install-as-a-daemon#windows](url)
