### ISSUE TITLE
Sonarr samba share path mapping

### ISSUE THREAD

**Issue by gszigethy** [morpheus65535/bazarr#297]
Just found Bazarr, awesome, thanks for all your efforts!

I found an issue with the path mapping. When you have Samba/Windows shares on Sonarr and Bazarr runs on a different machine, the path mapping becomes an issue.

Steps to Reproduce:
- Set  up Sonarr on a machine that downloads to a remote share (NAS), where Sonarr paths look like the following: \\192.168.11.10\d\data\sorozat\
- Under this share Sonar names the folders by {Series Title}\Season {season:00}, so the full path of a series is \\192.168.11.10\d\data\sorozat\{Series Title}\Season {season:00}, for instance \\192.168.11.10\d\data\sorozat\The Good Doctor\Season 02.
- Bazarr runs on the NAS hosting the data, so the above path from Bazarr perspective is on localhost under  /srv/tomb/jbod/data/sorozat/, for instance ls -la /srv/tomb/jbod/data/sorozat/The Good Doctor/
- Note there is a space in the folder name as Sonarr names it. So if I want to list that directory in SSH, I have to escape the whitespace: ls -la /srv/tomb/jbod/data/sorozat/The\ Good\ Doctor/
- Set up the mapping in Bazarr:

![image](https://user-images.githubusercontent.com/46370269/52272374-dcc72900-2946-11e9-8859-c0f21d4615b1.png)
- Paths get messed up upon download:
```
2019-02-05 13:07:18,681 - root                             (7f7ee471e700) :  ERROR (get_subtitle:264) - BAZARR Error saving subtitles file to disk for this file: /srv/tomb/jbod/data/sorozat/The Good Doctor\Season 01\The.Good.Doctor.S01E01.720p.HDTV.x264-KILLERS.mkv
2019-02-05 13:07:22,505 - root                             (7f7ee471e700) :  ERROR (get_subtitle:264) - BAZARR Error saving subtitles file to disk for this file: /srv/tomb/jbod/data/sorozat/The Good Doctor\Season 01\The.Good.Doctor.S01E02.720p.HDTV.x264-KILLERS.mkv
2019-02-05 13:07:26,227 - root                             (7f7ee471e700) :  ERROR (get_subtitle:264) - BAZARR Error saving subtitles file to disk for this file: /srv/tomb/jbod/data/sorozat/The Good Doctor\Season 01\The.Good.Doctor.S01E03.720p.HDTV.x264-KILLERS.mkv
```
- Notice that the first part of the path is the local path mapped in Bazarr. The 2nd part of the path is the subfolder structure from Sonarr, with backslash as per windows/Samba naming, and whitespaces are not escaped. Thus, Bazarr is unable to store the file as such folder doesn't exist.

Wrong path resolution:
root@llamaduck:/var/lib/bazarr# ls -la /srv/tomb/jbod/data/sorozat/The Good Doctor\Season 01\The.Good.Doctor.S01E03.720p.HDTV.x264-KILLERS.mkv
ls: cannot access '/srv/tomb/jbod/data/sorozat/The': No such file or directory
ls: cannot access 'Good': No such file or directory
ls: cannot access 'DoctorSeason': No such file or directory
ls: cannot access '01The.Good.Doctor.S01E03.720p.HDTV.x264-KILLERS.mkv': No such file or directory

Correct path:
root@llamaduck:/var/lib/bazarr# ls -la /srv/tomb/jbod/data/sorozat/The\ Good\ Doctor/Season\ 01/The.Good.Doctor.S01E03.720p.HDTV.x264-KILLERS.mkv 
-rw-rw-r-- 1 root users 1043468762 Aug 12 20:07 /srv/tomb/jbod/data/sorozat/The Good Doctor/Season 01/The.Good.Doctor.S01E03.720p.HDTV.x264-KILLERS.mkv
root@llamaduck:/var/lib/bazarr# 

**Software (please complete the following information):**
 - Bazarr: latest git cloned from development branch on 5th of February. Running on Debian. Data stored on this NAS.
 - Sonarr v2.0.0.5301 on Windows 10. Samba shares mounted from the NAS.

Maybe I'm using it wrong, any help would be greatly appreciated.

**Comment by gszigethy** [comment]
Just started working - no idea why.

**Comment by morpheus65535** [comment]
lol ok :-)
