### ISSUE TITLE
setup instructions?

### ISSUE THREAD

**Issue by Zeusy123** [morpheus65535/bazarr#3]
just install your script on windows 10, looks fecking awesome, just what ive been looking for:)

Setup instructions would be nice!

in particular, the paths, ive put in "D:\Current\Series Source" which is my tvseries folder, all series are in seperate folders below this path.

I dont know what to put into bizarr path???

I've also put in the apikey from sonnarr and saved settings, but still nothing happening.

the log sats:
--------------
Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2017-11-09 14:03:25 CET)" raised an exception

'Traceback (most recent call last):
File "C:\\Python27\\lib\\site-packages\\apscheduler\\executors\\base.py", line 125, in run_job
retval = job.func(*job.args, **job.kwargs)
File "D:\\Appz\\bazarr\\get_series.py", line 39, in update_series
current_shows_sonarr.append(show[\'tvdbId\'])
TypeError: string indices must be integers'
-----------------

Your help would be appreciated and thankyou for putting so much of your time into this project;)

**Comment by Zeusy123** [comment]
figured it out:)
path = the installed folder of your sonarr installation and the full path for your bazarr installation.
I entered those and restarted bazarr, now series are imported :)

**Comment by Zeusy123** [comment]
I clicked on update all eposides and i see the cricle "loading" but doesnt finish, been doing rthat doe 25mins so far and still nothing :-/

**Comment by Zeusy123** [comment]
just forced this to stop updating eps, to check thel ogs and in there is loads of 👍 


Element with id 0x55b0 is not in the specs | 13 seconds ago
-- | --
  | Element with id 0x313131 is not in the specs | 22 seconds ago
  | Element with id 0x313131 is not in the specs | 22 seconds ago
  | Element with id 0x313131 is not in the specs | 23 seconds ago
  | Execution of job "Add new episodes from Sonarr (trigger: interval[0:01:00], next run at: 2017-11-09 15:13:11 CET)" skipped: maximum number of running instances reached (1)

**Comment by Zeusy123** [comment]
When i click on series, i get error page saying:

Error: 500 Internal Server Error

Sorry, the requested URL 'http://localhost:6767/episodes/1437' caused an error:

Internal Server Error
Exception:

NameError("name 'actual_languages' is not defined",)
Traceback:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\bottle.py", line 862, in _handle
    return route.call(**args)
  File "C:\Python27\lib\site-packages\bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "D:\Appz\bazarr\bazarr.py", line 167, in episodes
    return template('episodes', no=no, details=series_details, seasons=seasons_list, url_sonarr_short=url_sonarr_short, base_url=base_url)
  File "C:\Python27\lib\site-packages\bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "C:\Python27\lib\site-packages\bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "C:\Python27\lib\site-packages\bottle.py", line 3396, in execute
    eval(self.co, env)
  File "D:\Appz\bazarr\views\episodes.tpl", line 160, in <module>
    %if actual_languages is not None:
NameError: name 'actual_languages' is not defined

**Comment by morpheus65535** [comment]
First, thanks for trying bazarr :-)

I'm gonna have to work on a wiki but between work and family, time is missing to make this as well documented as I would like.

Path mapping is for sonarr path vs bazarr path (in case you're not accessing the filesystem the same way. Ex.: Sonarr access your episodes files trough "D:\Current\Series Source" but bazarr is running on another computer and can access files trough "\\server\Series". So when bazarr path from Sonarr, it replace the sonarr path by the bazarr path to get access to the files.

How many episodes do you have? Updating all episodes can takes some time as it open each and every files to check for internal subtitles. In my setup, it takes 20 minutes to scan 2500 mkv. Do and "update all episodes" and let it finish (it will :-) ).

The "Element with id 0x313131 is not in the specs" error means that an invalid attribute is found by the enzyme library. I have no control over that but it's not harmfull and everything should work properly.

The 500 error is caused by an incomplete scan of internal subtitles on one or more of your episodes.

**Comment by Zeusy123** [comment]
good mornig, thanks for the reply:)

in sonar path ive put D:\Current\Series Source | in bazar, I've left empty.
restarted.
and then click update all eposides.

Ive 34k eps in my libary on a very fast server, so will give you the time it takes to complete if it ever does;)

**Comment by Zeusy123** [comment]
question, if it finds a subtitles for an eposide, does it use 2 letter country format or 3?

example : eps = The Walking Dead S01E03
The english subtitles file will be saved as The Walking Dead S01E03.en.srt
or will it use 3 letter and save subtitles file as The Walking Dead S01E03.eng.srt

And will it only get srt files and no other type of subtitle file?

**Comment by Zeusy123** [comment]
another question:)

radarr is a sonarr variation but for movies only.
is it possible for bazarr to work with radarr also???

**Comment by Zeusy123** [comment]
ok its now stopped updating all eps. but when i click on a series, im still getting:

Error: 500 Internal Server Error

Sorry, the requested URL 'http://localhost:6767/episodes/1437' caused an error:

Internal Server Error
Exception:

NameError("name 'actual_languages' is not defined",)
Traceback:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\bottle.py", line 862, in _handle
    return route.call(**args)
  File "C:\Python27\lib\site-packages\bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "D:\Appz\bazarr\bazarr.py", line 167, in episodes
    return template('episodes', no=no, details=series_details, seasons=seasons_list, url_sonarr_short=url_sonarr_short, base_url=base_url)
  File "C:\Python27\lib\site-packages\bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "C:\Python27\lib\site-packages\bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "C:\Python27\lib\site-packages\bottle.py", line 3396, in execute
    eval(self.co, env)
  File "D:\Appz\bazarr\views\episodes.tpl", line 160, in <module>
    %if actual_languages is not None:
NameError: name 'actual_languages' is not defined

**Comment by Zeusy123** [comment]
FYI: ive reinstalled clean bazarr, and can now see the eps pages ok :)
so above error no longer seen.

**Comment by Zeusy123** [comment]
Correction, the update all eps, stopped after about 20mins and now that error:

Error: 500 Internal Server Error

is back:(

**Comment by morpheus65535** [comment]
You don't have to specify Sonarr path if Sonarr and Bazarr access files with the same path. Path substitution is only used when Sonarr and Bazarr access a single files from two different path (ex.: one locally and the other trough a network share).

**Comment by morpheus65535** [comment]
Bazarr rely on Subliminal and Enzyme libraries to detect and download subtitles. 2 and 3 letters are supported. As far as I know, Subliminal only support .srt files.

**Comment by morpheus65535** [comment]
I have no plan to support Radarr for now. I have plenty of work to do to stabilize the actual integration with Sonarr.

**Comment by morpheus65535** [comment]
You got a 500 error because Bazarr is trying to do path substitution with a source but no destination. For what I understand of your setup, you're running both software on the same computer. If I'm right, you don't need to use path substitution at all. Leave those fields empty.

**Comment by Zeusy123** [comment]
Morpheus, thankyou for the instructions, ive followed them exactly and im still getting the internal 500 error.
as this server is windows server 2008 and all sonarr etc is all on drive D

In path mapping I have all empty.
Ive the correct api key for sonnarr in bazarr and correct listening port.
In sublinimal Ive opensubtitles, and english,french etc... selected.
I have updated sereies and yes it has found them all and showing the correct paths.
I have about 400 series and ive cleared the yellow tool from about 20 and select 2 series only to update with the subtitles of english,french, etc.. and saved. 
I then clicked update all eposides and it took about an hour or so to compelete.
When i click a series from series page i get:

Error: 500 Internal Server Error

Sorry, the requested URL 'http://localhost:6767/episodes/1437' caused an error:

Internal Server Error
Exception:

NameError("name 'actual_languages' is not defined",)
Traceback:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\bottle.py", line 862, in _handle
    return route.call(**args)
  File "C:\Python27\lib\site-packages\bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "D:\Appz\bazarr\bazarr.py", line 167, in episodes
    return template('episodes', no=no, details=series_details, seasons=seasons_list, url_sonarr_short=url_sonarr_short, base_url=base_url)
  File "C:\Python27\lib\site-packages\bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "C:\Python27\lib\site-packages\bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "C:\Python27\lib\site-packages\bottle.py", line 3396, in execute
    eval(self.co, env)
  File "D:\Appz\bazarr\views\episodes.tpl", line 160, in <module>
    %if actual_languages is not None:
NameError: name 'actual_languages' is not defined
-------------------------
When i click a serieslink which i have told to find subtitles, i get the same error, the url = http://localhost:6767/episodes/652

Gives 500 internal error.

I have also click on update NEW epsoised and still not working:(
Ive spent lot of time trying to get this to work and I fear, I'll have to try other alternatives:(

**Comment by morpheus65535** [comment]
Thank you for your patience. I’ll take a look at the code to exclude those not configured yellow series when updating all episodes. I’ll come back to you when it will be done.

For what it worth, I use bazarr in priduction environnent without path mappings and it works well enough that I can even forget it.

Thanks again!

**Comment by Zeusy123** [comment]
Thanks for the reply morph, any ETA?? I will wait a few days if you beleive u will have it done by then if not, no worries;)

**Comment by morpheus65535** [comment]
Je vais regarder ça lundi et je te reviens. :-)

**Comment by Zeusy123** [comment]
J'attends avec impatience mardi alors :) Merci beaucoup.

**Comment by morpheus65535** [comment]
J'y ai bossé mais c'est pas complet. En plus, je dois perfectionner la mécanique de mise à jour de bazarr. Je travail là-dessus cette semaine.

**Comment by Zeusy123** [comment]
Merci, je vais attendre jusqu'à la semaine prochaine avant d'essayer autre chose;)

**Comment by Zeusy123** [comment]
Any update yet my friend?? ;)

**Comment by morpheus65535** [comment]
Yes, it’s more robust but I’m facing a major memory leak under linux and docker. You can use the development branch on Windows but I suggest you give me a couple of days so I can finish refactoring database connection process. I’m working on it as we speak.

**Comment by Zeusy123** [comment]
just grabbed the dev branch and overwrite excisting files with it.
Can now confirm that I can now view the series pages :)

**Comment by morpheus65535** [comment]
Have you updated your python module eith pip and the requirements.txt? Just to be sure you got everything? Also take a look at the dev readme file. Instructions have been adapted.

**Comment by Zeusy123** [comment]
ok gonna start from scratch again to ensure  your instructions are correct:)

**Comment by morpheus65535** [comment]
Again, I suggest you wait a couple of day so I can finish stabilizing the code. You wont have to do it again in a week :-)

**Comment by Zeusy123** [comment]
ok, now we getting somewhere:)
its found all 400 sereis i have in my sonarr, I can now see the individual eposides.
I have selected about 4 subtitles sources 
I have told it i just want english.
I told 1 tvseries to update with english subs.
I can see when viewing the sereis page, that it sees the series is missing the subtitles.
When I click Download wanted subtitles from sereis page i get:

Error: 500 Internal Server Error

Sorry, the requested URL 'http://localhost:6767/wanted_search_missing_subtitles' caused an error:
the log:

Execution of job "Add new episodes from Sonarr (trigger: interval[0:01:00], next run at: 2017-11-17 18:45:32 CET)" skipped: maximum number of running instances reached (1) | 22 seconds ago
-- | --
  | Execution of job "Add new episodes from Sonarr (trigger: interval[0:01:00], next run at: 2017-11-17 18:44:32 CET)" skipped: maximum number of running instances reached (1) | a minute ago
  | Execution of job "Add new episodes from Sonarr (trigger: interval[0:01:00], next run at: 2017-11-17 18:43:32 CET)" skipped: maximum number of running instances reached (1) | 2 minutes ago
  | Execution of job "Add new episodes from Sonarr (trigger: interval[0:01:00], next run at: 2017-11-17 18:42:32 CET)" skipped: maximum number of running instances reached (1) | 3 minutes ago
  | Job "Search for wanted subtitles (trigger: interval[0:15:00], next run at: 2017-11-17 18:57:13 CET)" raised an exception

---------

**Comment by Zeusy123** [comment]
from dos windows the error:
Serving on http://OWNEROR-G6FV6LT:6767
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\bottle.py", line 862, in _handle
    return route.call(**args)
  File "C:\Python27\lib\site-packages\bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "D:\Appz\bazarr\bazarr.py", line 217, in wanted_search_missing_subtit
list
    wanted_search_missing_subtitles()
  File "D:\Appz\bazarr\get_subtitle.py", line 92, in wanted_search_missing_s
tles
    wanted_download_subtitles(episode[0])
  File "D:\Appz\bazarr\get_subtitle.py", line 80, in wanted_download_subtitl
    del message
UnboundLocalError: local variable 'message' referenced before assignment

**Comment by Zeusy123** [comment]
Also i have series which has all subtitles already, the format of all my srt files is Top Gear S01E09.en.srt for english 2digit country code = EN
heres is my full list of languages that I use:

![image](https://user-images.githubusercontent.com/24862324/32962056-565be52e-cbcb-11e7-8735-40b284fe9231.png)

for some reason bazarr doesnt see them:(
These srt files are IN the series folder, AND also attached to the actual episode video file in mkv format.

Any ideas why not seeing them??

**Comment by morpheus65535** [comment]
I'm fixing the error message you posted 2 hours ago. Was trying to delete a variable that didn't exist in this sub.

**Comment by morpheus65535** [comment]
If you let some more time to Bazarr, they will actually be there... here's how it works:

Bazarr first run work in 3 steps:
1 - Import series from Sonarr
2 - Import episodes from Sonarr
3 - Detect subtitles for each episodes

Step 1 is really fast. 
Step 2 is fast enough (you may have to wait a couple of minutes before seeing each and every episodes listed.
Step 3 is slow... like really slow when you got thousands of episodes that need to be analysed for internal and external subtitles.

This is for the initial run. After that, step 1 is still fast.
Step 2 is going to be incremental very soon (history API of Sonarr have been modified 2 weeks ago to do that).
Step 3 already do subtitles detection on episodes that do not have been analysed yet.

Once a day, at 4am, I do a full "step 2" (not incremental) to be sure that the DB reflect the reality on disk.

**Comment by morpheus65535** [comment]
Btw: Bazarr do not take care of internal subtitles track that do not have a valid language tag. If I can't tell to the user witch language it is, I do not want him to see it at all.

**Comment by Zeusy123** [comment]
all my srt files and attach srt's to video files, have language tag.
I'll leave this running overnight see if any update in morning.

**Comment by morpheus65535** [comment]
You can expect to analyse from 1 to 5 episodes by second depending of hardware and if files arr available locslly or trough the network.

If it doesn’t work, we’ll find a way for you to share one of those problematic episode with me so I can test it. 

Thanks again and good night!

**Comment by Zeusy123** [comment]
good morning:)
just letting u know still hasnt found any subtitles in any of the series:( will be happy to send you an eposide so u can check your end, but not sure how to?

**Comment by morpheus65535** [comment]
Can you post the result of « pip list » please? I’ll compare with mine. 

Is it possible to access your Bazarr instance remotely? Maybe a remote assistance session? If not possible, is dropbox or similar services a possibility? Ftp server maybe?

Thanks!

**Comment by morpheus65535** [comment]
Have you enabled auto update in settings? With branch are you updating from?

**Comment by Zeusy123** [comment]
updating from dev branch
still isnt searching for srts by itself.
If i view a series and click on a en language box, it will download the srt file correctly.

**Comment by morpheus65535** [comment]
Ok so the actual subtitles column is populated. The missing subtitles seems to be ok. The problem is it doesn’t search for missing subtitles automatically? Am I right?

Is there something in the log?

**Comment by Zeusy123** [comment]
Yes correct its not searching automatically.

I forsee one problem:

Lets say i have The Walking Dead S01E02.mkv file which already has EN.srt & ZH.srt (english & chineses) ATTACHED to the source mkv file.  Im guessing your script will see that.  (But does it also scan the folder the source file is in and check for all srt files? As if you script downloads the srts to the folder it does not attach them to the source mkv file, so if it doesnt also scan the folder, it will contiually downlaod the srts all the time as the downloaded srts are not attache to the source.

Using above example: i have told your script I need also ES (spanish) of the walking dead eps.
As you script scans the source file for the languages srt attached to the source. and does not scan if the srt file is in the folder.  It will continually downlaod the ES.srt file.  

hard to explain really, but I hope you understand?

**Comment by morpheus65535** [comment]
Ok, I assume that by ATTACHED, you meen a subtitle track inside a MKV container, am I right? 

Bazarr will detect to kind of subtitles: subtitle tracks inside MKV container and .srt file with the same name as the episode file (.mkv) with the language code (2 or 3 letters).

Exemple:

Episode file: toto.mkv
Included subtitles tracks: en, fr
External subtitle files: toto.zh.srt, toto.es.srt

Bazarr is going to report that: toto.mkv --> en, fr, zh(x), es(x)
(Those with an "x" are deletable because they are external .srt files.

So, if the downloaded .srt file have the same name (with language code) and is in the same folder, Bazarr should detect it and not download it again.

Does it answer your question?

**Comment by Zeusy123** [comment]
once again my friend, a big THANKYOU for your help on this:)

1) yes you understand my ATTACHED comment correctly, meaning attached to the source file, written into the mkv file as I will need todo with all subittles bazarr finds.

2) My bazarr is not detecting any srt in the folder OR attached:(

3) as you clearly state it should read srt in folder with same name etc.. then my double of conitunally redownloading the same srt file wont happen.  My question was due to bazarr seening nothing attached and no srts file in the fodler, when there is clearly.

**Comment by Zeusy123** [comment]
dont want to put my email or skype to get you acess to my server so u can debug yourself as I'm sure ill not be the only one with problems:) Could also show you my python script for attaching the srts to the mkv files ;)

**Comment by morpheus65535** [comment]
You can reach me on Discord: https://discord.gg/MH2e2eb

**Comment by Zeusy123** [comment]
did a clean fresh install as per your instruction on frontpage of github
