### ISSUE TITLE
Unresponsive UI when large number subtitles being searched for

### ISSUE THREAD

**Issue by decairn** [morpheus65535/bazarr#300]
**Describe the bug**
When searching for a large number of subtitles the Bazarr web page will not open in a new browser tab. Chrome F12 network console shows it never returning.

**To Reproduce**
Select a large number of subtitles to find, search them.
Open a new browser tab
Open the Bazarr URL
The page is never rendered

**Expected behavior**
The Bazarr web page would open and allow regular navigation and actions while a search is occurring in the background.

**Screenshots**
N/A

**Software (please complete the following information):**
 - Bazarr: 0.71
 - Radarr version 0.2.0.1293
 - Sonarr version 2.0.0.5301
 - OS: client Win 10 Chrome, Bazarr on Synology 918 Docker linuxserver.io/bazarr

**Additional context**
Stopped Docker while Bazarr not returning, restarted it.  Subtitle wanted count reduced, so it was actively downloading content while denying UI access.

**Comment by morpheus65535** [comment]
How's the CPU usage when large amount of subtitles are downloaded? We're heavily using multi-threading when searching for subtitles so it could cause high ressources usage that render UI unavailable. I don't have a Synology to run test then I'm unable to reproduce this behaviour.

**Comment by morpheus65535** [comment]
Ok I can reproduce it. I'll look into it ASAP.

**Comment by morpheus65535** [comment]
Can you try development branch and confirm if it's working for you?

**Comment by decairn** [comment]
Unless there is a publicly available docker image of the development branch I will not be able to test.  The linuxserver.io docker does not look to have one.

Synology CPU was ~25%, with ~15% showing on the container process.

**Comment by morpheus65535** [comment]
linuxserver/bazarr:development

**Comment by decairn** [comment]
That fixed it.

**Comment by morpheus65535** [comment]
Thanks!
