### ISSUE TITLE
AttributeError("'NoneType' object has no attribute 'check'",)

### ISSUE THREAD

**Issue by Fgruntjes** [morpheus65535/bazarr#303]
**Describe the bug**
When trying to search for a new movie I get the fatal error: `AttributeError("'NoneType' object has no attribute 'check'",)` The problem started when I updated the docker images.

**To Reproduce**
1. Go to a 'Movies'
2. Click on 'Download missing subtitles'

**Expected behavior**
Search for some subtitles

**Screenshots**
```
Error: 500 Internal Server Error
Sorry, the requested URL 'https://subs.wfkclan.nl/search_missing_subtitles_movie/28' caused an error:

Internal Server Error
Exception:
AttributeError("'NoneType' object has no attribute 'check'",)
Traceback:
Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 135, in wrapper
    return func(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 889, in search_missing_subtitles_movie
    movies_download_subtitles(no)
  File "/app/bazarr/bazarr/get_subtitle.py", line 527, in movies_download_subtitles
    providers_list, providers_auth, str(movie[3]), movie[5], 'movie')
  File "/app/bazarr/bazarr/get_subtitle.py", line 247, in download_subtitle
    language_hook=None)  # fixme
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 734, in download_best_subtitles
    subtitles = pool.download_best_subtitles(pool.list_subtitles(video, languages - video.subtitle_languages),
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 453, in list_subtitles
    itertools.repeat(languages, len(self.providers))):
  File "/app/bazarr/bazarr/../libs/concurrent/futures/_base.py", line 581, in result_iterator
    yield future.result()
  File "/app/bazarr/bazarr/../libs/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/app/bazarr/bazarr/../libs/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 437, in list_subtitles_provider
    provider_subtitles = super(SZAsyncProviderPool, self).list_subtitles_provider(provider, video, languages)
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 140, in list_subtitles_provider
    if not provider_registry[provider].check(video):
AttributeError: 'NoneType' object has no attribute 'check'
```

**Software (please complete the following information):**
- Bazarr version 0.7.1
- Sonarr version 2.0.0.5301
- Radarr version 0.2.0.1293
- Operating system Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with
- Python version 2.7.15
- Docker image linuxserver/bazarr sha256:9e9b2c826e43718ddcabb5b3595699f373be3277c52d7763853dd4562705544d (latest)

**Additional context**
Well after filling out the entire bug report I wanted to add some debug logging. So enabled the debug log , and saved settings and afterwards the issue was solved.

**Comment by Fgruntjes** [comment]
So also issue solved by re saving the settings, just leaving this here so it might help soneone with the same issue.

**Comment by uaktags** [comment]
Great, fixed it for me. Is this something that could/should be fixed during a version upgrade? I feel like root-cause is now known, and workaround, but what would the solution itself be?

**Comment by morpheus65535** [comment]
To be honest, we clearly know the issue, the fix but the root cause is still unknown. Something between 0.7.0.5 and 0.7.1 cause this. Unfortunately, it coincides with the merge of Sub-Zero base code into Bazarr and we changed a couple thousand of line of code during this merge so it make it quite difficult to pinpoint the root cause precisely. :-/

**Comment by morpheus65535** [comment]
@halali just told me that the dev branch already contain a fix for this issue. Once we merge dev to master, this shouldn’t be an issue anymore.

**Comment by uaktags** [comment]
Awesome, thanks for the feedback and clarification!

**Comment by eyadsibai** [comment]
> So also issue solved by re saving the settings, just leaving this here so it might help someone with the same issue.

which settings?

**Comment by eyadsibai** [comment]
I am having similar issue

**Comment by halali** [comment]
Please open new issue with all info and new debug log.

**Comment by morpheus65535** [comment]
> > So also issue solved by re saving the settings, just leaving this here so it might help someone with the same issue.
> 
> which settings?

Providers
