### ISSUE TITLE
Add Ability to Reconfigure Providers in WebUI

### ISSUE THREAD

**Issue by Sivrat** [morpheus65535/bazarr#305]
The only time I see to configure provider settings is during initial configuration, at least in the UI.

If additional providers are being added to compatibility, or users end up setting new accounts to existing providers, we will need some way to update without reinstalling or manually editing the config files.

**Comment by morpheus65535** [comment]
Mate, have you looked in Settings-->Subliminal-->Subtitles Providers section?

**Comment by Sivrat** [comment]
I did not, and am evidently blind.
