### ISSUE TITLE
[Provider Request] Add subdivx.com as a provider

### ISSUE THREAD

**Issue by Panderine** [morpheus65535/bazarr#307]
Subdivx is the most popular site for Spanish subtitles. Please add it to this great software.

**Comment by ngosang** [comment]
@morpheus65535 Working code in python https://github.com/mgaitan/subdivx-download

**Comment by morpheus65535** [comment]
Added in PR #448. Thanks to @ngosang !

**Comment by Panderine** [comment]
Thank you !!!
