### ISSUE TITLE
[Feature Request] search for subtitles on download

### ISSUE THREAD

**Issue by Panderine** [morpheus65535/bazarr#308]
As far as I understand, right now subtitles are searched every 3 hours. Could you make that the same event that trigger the inclusion from sonarr/radarr when it finishes downloading launches the searching as well. Sort of a just-in-time search.

**Comment by Wesleyl89** [comment]
Would love to have this feature!

There is someone who made something similar which you can use as a webhook inside Sonarr/Radarr https://github.com/KirovAir/superliminal

**Comment by Zeusy123** [comment]
Also suggested this to morph:)
was thinking a simple "connect" custom script to on download/upgrade pass moviename to bazarr and immediately search for subs.

**Comment by morpheus65535** [comment]
@Zeusy123 in fact the "connect" idea won't work because it can take up to 5 minutes for Bazarr to be aware of a new episode/movie. During this time, if Sonarr ask for a subtitles search, Bazarr won't have the required information to do it. I've got another idea that will work.

**Comment by Dr0bac** [comment]
+1 for idea..i usually download movies manually and after download is done, i wach it..with current settings i must go to bazarr and hit button to search for subtitles..

**Comment by morpheus65535** [comment]
Functionality added in dev branch (v0.7.4).

**Comment by GeoCookie** [comment]
Hi there,

It's work like a charm with movies :) Thanks for this, it's great improvement!

For series, what’s happen if we download a whole season with +5 episodes? Will Bazarr lookup for the subtitles of the first five episodes? Or will it do nothing?

**Comment by Panderine** [comment]
sorry for delay, I notice this is working!. Thanks for making it happend :D

**Comment by morpheus65535** [comment]
@GeoCookie If more than 5 episodes are synced during the same execution, there will be no subtitles searching and it's going to happen durinthe next search for wanted subtitles (every 3 hours).

@Panderine Thanks!

**Comment by Zeusy123** [comment]
muhahahah, shall get to testing now :)

**Comment by Zeusy123** [comment]
@Morph works brilliant :) thankyou!!
