### ISSUE TITLE
Feature: remove subtitle request for a season

### ISSUE THREAD

**Issue by stefandevo** [morpheus65535/bazarr#31]
I have this season of a series where I have included subtitles in the MKV file; the system did not recognize this ( he recognized external ones). So I now have one show's season that is still in my wanted list, but I cannot remove it (per subtitle, or per season).
1. can we have a feature to remove wanted subtitles (one by one, or per season)
2. can bazarr recognize backed subtitles in MKV?

ps: BTW great product!

**Comment by Julien-D** [comment]
I think it should work. One of the features is: `Scan your existing library for internal and external subtitles and download any missing`
Maybe you have to let some time to Bazarr so it can scan all your files.

**Comment by stefandevo** [comment]
I know it "shoud" work but for this it isn't. Scanning was done - I have 6 seasons, only season 5 has these embedded subtitles - and the other seasons where processed ok. If @morpheus65535 provides me a contact address I can provide this MKV file.

**Comment by morpheus65535** [comment]
@Julien-D is right. Bazarr analyse each file and detect included subtitles if and only if the subtitles track language is a valid 3 characters code (ie: eng, fre, etc.).

@stefandevo I have no plan to implement wanted subtitles on a per season basis. It would require for Bazarr to keep track of seasons. Actually, seasons are only at the UI level. Bazarr only link episode to series.

**Comment by stefandevo** [comment]
Would you care to have a look at the MKV file? Because for example VLC recognized the DUTCH subtitles in it.

**Comment by morpheus65535** [comment]
If you can share it with me some way (ftp, dropbox, etc.), I can take a look at it.

You can also try to run this piece of code after changing the file variable:

    import enzyme
    import babelfish
    import pycountry

    file = 'path/to/mkv/file'

    with open(file, 'rb') as f:
        mkv = enzyme.MKV(f)

    for subtitle_track in mkv.subtitle_tracks:
        print subtitle_track.language

**Comment by morpheus65535** [comment]
Do you get an "nl" subtitles in Bazarr? It seems it's the alpha_2 version of the alpha_3 "dut" in pycountry.languages.

**Comment by stefandevo** [comment]
Bazarr does not recognize any subtitle for this file

**Comment by morpheus65535** [comment]
I've just merge it to master. You can force an update or you will get it in the next 6 hours.
