### ISSUE TITLE
Show not found, but at least one provided did have the subtitle

### ISSUE THREAD

**Issue by FrAllard** [morpheus65535/bazarr#311]
I see that Bazarr is unable to find some of my show and they all have something in common, they have the year in their title like "The Show Name (2018)"

The provider Addic7ed had the subtitles that I downloaded manually and then did a rescan of local disk and Bazarr did find them.

I'm not sure I can mention show names, so I didn't. To reproduce the problem you need to have a show with the year in it's title, I'm not sure if all show with the year in the title are affected. I had 4 different shows in the wanted list.

**Software (please complete the following information):**
 - Bazarr: [e.g. v 0.7.1]
 - Radarr version [e.g. v 0.2.0.1293]
 - Sonarr version [e.g. v 2.0.0.5301]
 - OS: Docker on Ubuntu Server 18.04.2 LTS

**Comment by morpheus65535** [comment]
If you can give a try to the dev branch, it contain a fix related to this issue.

**Comment by FrAllard** [comment]
Thanks that did the trick!

**Comment by morpheus65535** [comment]
Super! Au besoin viens nous voir sur Discord. :-)

**Comment by FrAllard** [comment]
J'aimerais bien aller vous voir sur Discord, mais je ne trouve nulle part votre serveur Discord... Je suis nouveau sur Discord, je suis un vieux de la vieille avec le bon IRC ;-)

**Comment by morpheus65535** [comment]
Nous avons aussi un serveur dédié à Bazarr. Vous trouverez le lien dans Bazarr sous System-->Status (dans le bas).
