### ISSUE TITLE
Cannot update Bazarr running on Qnap NAS

### ISSUE THREAD

**Issue by StoneTheDog** [morpheus65535/bazarr#312]
**Describe the bug**
I get an error message when I try to update Bazarr on my Qnap NAS

**To Reproduce**
1. I have de-selected automatic updates in Settings -> General -> Updates
2. Execute 'Update bazarr from source on Github' in System -? Tasks
3. Goto System -> Logs

**Expected behavior**
I expect Bazarr to run the update

**Screenshots**
![image](https://user-images.githubusercontent.com/47794684/53043142-bee9e000-347f-11e9-9f1b-f2dbc3667115.png)

**Software (please complete the following information):**
 - Bazarr: v 0.6.9.1
 - OS: Linux-4.2.8-x86_64-with-glibc2.2.5

**Additional context**
Bazarr is running on a Qnap NAS TS-251

**Comment by morpheus65535** [comment]
How did you install Bazarr? Using `git clone`?

**Comment by StoneTheDog** [comment]
I installed it using the qpkg from here: [https://www.qnapclub.eu/en/qpkg/686](url) ....
It installed perfectly and runs well, just the update is not going well ...

**Comment by morpheus65535** [comment]
I'm sorry but I'm not able to support qpkg as I'm not the one who produce them and don't even have a QNAP to test it. See with the package creator.
