### ISSUE TITLE
Fetched subs are wrong 9 out of 10 times.

### ISSUE THREAD

**Issue by maxtheking** [morpheus65535/bazarr#313]
**Describe the bug**
So i recently switched from Sub-Zero to Bazarr for getting subtitles for my movies and TV shows on my Plex server, only to find out that the subs that Bazarr gets from opensubtitles.org are wrong 9 out of 10 times. They are either extremely out of sync, or don't match the movie at all. I'm not renaming the file names, they're all original. Tested on Plex desktop, Plex Chrome and Plex mobile. Any ideas on what could cause this? The settings i'm using in Bazarr are mostly stock.

**Expected behavior**
Bazarr downloads the correct subtitles.

**Software:**
 - Bazarr Ver. 0.7.1
 - Radarr Ver. 0.2.0.1293
 - Sonarr Ver. 2.0.0.5301
 - OS: Debian 9 x64

**Comment by morpheus65535** [comment]
This result is quite surprising. Can you provide a copy of your config.ini file while obfuscating sensitive data? I would also like to have a debug log that would cover a couple of subtitles search. Thanks!

**Comment by maxtheking** [comment]
@morpheus65535 Sure! Couldn't upload the config.ini here, because the file format isn't supported. Copied the contents in a [pastebin](https://pastebin.com/FinVzHhQ) instead. As for the debug log, i don't really know where to find it. All i have are the logs located in /opt/Bazarr/data/log/, and these don't update when i search for subtitles for. a movie. But i attached the logfile anyway. 
[bazarr.log](https://github.com/morpheus65535/bazarr/files/2884364/bazarr.log)

**Comment by halali** [comment]
Debug log would be great

**Comment by morpheus65535** [comment]
Thanks for config.ini file. You can enable debug log in Settings-->General-->Enable debug logging.

**Comment by maxtheking** [comment]
@morpheus65535 Enabled it. Searched for subtitles for the movie 'Back to the Future Part II', and attached the debug log  below.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/2884560/bazarr.log)

**Comment by morpheus65535** [comment]
Could you switch to development branch and force an update? I think this is related to an issue with the omdb refiner that have been fixed and should be merge to master branch soon.

**Comment by maxtheking** [comment]
Changed to dev. branch. How do i force a update though? Running the script with 'python check_update.py' resulted in errors.

**Comment by morpheus65535** [comment]
Go to System—>tasks—>update from source on github.

**Comment by maxtheking** [comment]
Thanks. Ran the updater, which resulted in en error. Error message attached below
![err1](https://user-images.githubusercontent.com/43993269/53121786-52d9ab80-3555-11e9-8170-d4b4d076433f.JPG)

**Comment by morpheus65535** [comment]
In command line go to bazarr directory and run `git pull`. Restart bazarr if successful.

**Comment by maxtheking** [comment]
The command git pull results in the output 'fatal: No remote repository specified.  Please, specify either a URL or a remote name from which new revisions should be fetched.' Do i need to specify the .git URL after the command? If i do that, i get a list of files which will be overwritten, which is basically everything.

**Comment by morpheus65535** [comment]
By bad: `git pull origin development`.

**Comment by maxtheking** [comment]
That doesn't work either. Throws the error 'fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights'
Forgot to mention i'm running from source, so the Bazarr repo isn't known on the OS

**Comment by morpheus65535** [comment]
How did you install? You followed the wiki?

**Comment by maxtheking** [comment]
Yep. Just followed the instructions on the wiki!

**Comment by morpheus65535** [comment]
Either you have a permission error or you have something wrong with your .git directory. I suggest you take a backup copy of your data directory and restart from scratch the installation following the wiki direction: https://github.com/morpheus65535/bazarr/wiki/Installation-Running-from-Source

Before starting Bazarr, restore your backup of the data directory.

On it's running, switch to dev branch and force the update in System-->Tasks.

**Comment by maxtheking** [comment]
Thanks. I just did a fresh install of the entire VM, that seems to have fixed the update problem. I was now able to update to the dev. build from the web UI just fine. But when i now search for subtitles for a movie, i get a Internal server (500) error. 
![err2](https://user-images.githubusercontent.com/43993269/53174996-6172a200-35eb-11e9-925c-0cf37023927e.JPG)

**Comment by morpheus65535** [comment]
Fixed now in dev branch. Please test.

**Comment by maxtheking** [comment]
It's now working fine in latest dev branch, thanks!
