### ISSUE TITLE
Mux Subtitles into Files

### ISSUE THREAD

**Issue by Ashkaan** [morpheus65535/bazarr#314]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
It would be great if Bazarr could mux in and/or mux out subtitles to the video files.  You could always be sure that the file itself had exactly the subtitles that you want and none that you don't.

**Describe alternatives you've considered**
There is no alternative

**Additional context**
None needed.

**Comment by morpheus65535** [comment]
Mux in is available through post processing and external command line tool. As for mux out, I got no plan to integrate this kind of functionality inside Bazarr because they heavily rely on external executable that would be difficult to port between operating systems.
