### ISSUE TITLE
[Bug] Movies can't be excluded from subtitle downloading

### ISSUE THREAD

**Issue by Froghut** [morpheus65535/bazarr#315]
When going to a Movie detail page, then "Edit Movie", the subtitle language can't be set to "None" like you can do for TV Shows.

**Comment by halali** [comment]
You dont want to set None, just remove all languages

**Comment by Froghut** [comment]
how would I remove all languages for one specific movie? Can't find anything on the movie detail page or the edit movie popup. Also isn't it still strange to have two different workflows for tv series and movies?

**Comment by halali** [comment]
![image](https://user-images.githubusercontent.com/17801420/53087221-e637c000-3506-11e9-8421-fbaaa387c7cd.png)

**Comment by Froghut** [comment]
Ah, I had enabled "single language" - after disabling that I was able to delete languages shown in your image. Thanks!

**Comment by morpheus65535** [comment]
This is an issue when using single language that need to be fixed. None isn't available in menu. I reopen the issue to keep track of it.

**Comment by halali** [comment]
Fix pushed to development branch. Thanks for report
