### ISSUE TITLE
Bazarr doesn't detect subtitles that he have downloaded

### ISSUE THREAD

**Issue by GeoCookie** [morpheus65535/bazarr#316]
Hello everyone,

I am having a problem with Bazarr and I need the help of the experts. :)
Bazarr does not detect the subtitles he downloads. It happens to download (I see them next to the video file) but are still marked as not found on the web interface.
I tried to read the logs but I do not see anything that seems to be a problem.

I have attached some screenshots and a verbose log file in which we must see an English subtitle search (for Nutcracker) and a disk analysis.
I run Bazarr in a Docker container (linuxserver / docker-bazarr)

Thank you in advance for your help !

Bazarr says EN subtitle is missing
![2019-02-20 13_41_21-the nutcracker and the four realms - bazarr](https://user-images.githubusercontent.com/43962716/53093470-cbba1280-3517-11e9-8416-a60bf506c1ea.png)

But the subtitle seems to be well downloaded
![movie subtitles](https://user-images.githubusercontent.com/43962716/53093521-f015ef00-3517-11e9-9fcc-724ec2f58658.png)

I got the problem for my entire library. Bazarr downloads a lot of subtitles but still saying they are missing
![statistics](https://user-images.githubusercontent.com/43962716/53093543-fefca180-3517-11e9-968a-4769beeb165d.png)
![wanted](https://user-images.githubusercontent.com/43962716/53093549-02902880-3518-11e9-819c-3eb1e946c303.png)

[bazarr.log](https://github.com/morpheus65535/bazarr/files/2884659/bazarr.log)
[The Nutcracker and the Four Realms (2018) - Bluray-1080p x264 AC3[FR+EN] [FR] lost.en.srt.zip](https://github.com/morpheus65535/bazarr/files/2884665/The.Nutcracker.and.the.Four.Realms.2018.-.Bluray-1080p.x264.AC3.FR%2BEN.FR.lost.en.srt.zip)

**Comment by GeoCookie** [comment]
PS : that's my first post on Github, hope i have respect the rules :)

**Comment by morpheus65535** [comment]
Tu peux essayer avec l'image linux/server:development ?

**Comment by GeoCookie** [comment]
@morpheus65535 Merci pour ton retour.
Je suis passé sur l'image de développement, mais le problème semble persister. Tu trouveras en PJ le fichier de log de cette version.

PS : j'ai récupérer les fichiers de config de la version stable. Je peux essayer de repartir sur une config vierge si besoin :)

Bonne soirée

[bazarr.zip](https://github.com/morpheus65535/bazarr/files/2886153/bazarr.zip)

**Comment by morpheus65535** [comment]
J'ai beau tout tester, j'arrive pas à reproduire ton problème... :-/

Tu peux faire un scan manuel des fichiers pour le film Nutcracker? Il détecte le sou-titre?

**Comment by GeoCookie** [comment]
Salut,

C'est ce que je fais et que tu devrais retrouver dans les logs. Je lance le téléchargement du sous titre anglais, puis je lance un scan manuel depuis la page du film.

Je vais essayer de repartir from scratch avec la version de dev ce midi

**Comment by GeoCookie** [comment]
Re,

Je suis reparti de zéro avec la version de dév, et malheureusement, même problème.
Le problème vient peut-être de l'image Docker. Je vais essayer de l'installer directement sur le système pour voir.

Bonne journée

Bazarr a téléchargé le fichier de sous-titre
![01](https://user-images.githubusercontent.com/43962716/53153794-7cc4b980-35b9-11e9-85b5-ebf7f459ebb2.png)

Je le vois bien sur mon partage, avec la bonne date de modif
![02](https://user-images.githubusercontent.com/43962716/53153851-982fc480-35b9-11e9-8401-901c1c700516.png)

Mais pas Bazarr
![image](https://user-images.githubusercontent.com/43962716/53153914-b85f8380-35b9-11e9-8d25-e42fc72cfd62.png)

Un gros fichier de logs verbeux si ça peut aider
[bazarr.zip](https://github.com/morpheus65535/bazarr/files/2888286/bazarr.zip)

**Comment by morpheus65535** [comment]
Tu peux me mettre une photo d'écran de la page principale listant les films? Merci!

**Comment by GeoCookie** [comment]
Je ne sais pas si c'est ça que tu veux;
![01](https://user-images.githubusercontent.com/43962716/53168464-f5883d80-35da-11e9-8f31-6d6f41aaf036.png)
(cette capture est prise sur la version de dev ou je n'ai mis que les films, pas les séries)

Et j'ai testé d'installer Bazarr sur mon pc en W10, ça fonctionne bien! Je vais essayer tester sur un rpi maintenant.

**Comment by GeoCookie** [comment]
Petit complément sur la version de dev : j'ai ce message d'erreur quand je clique sur "Download missing subtitles" depuis la page d'un film. Je ne sais pas si ca a un lien avec mon problème
![03](https://user-images.githubusercontent.com/43962716/53170017-439f4000-35df-11e9-88a9-a587220e5297.png)

![02](https://user-images.githubusercontent.com/43962716/53170021-4732c700-35df-11e9-8e8e-09d1df03034f.png)

**Comment by morpheus65535** [comment]
C’est bien ce que je voulais merci. Je te reviens.

**Comment by morpheus65535** [comment]
Pour la dev actuelle, j’ai intégré un bug hier soir. On a déjà un autre issue qui en parle. Je vais tâcher de régler ça aujourd’hui.

**Comment by morpheus65535** [comment]
J’ai l’impression qu’il y a quelque chose de particulier avec ton Linux. Pour une valeur sure je te recommande Docker.

**Comment by GeoCookie** [comment]
Je suis déjà sur Docker, j'utilise cette image : https://github.com/linuxserver/docker-bazarr
En as-tu une autre à me conseiller?

**Comment by morpheus65535** [comment]
Ah non c’est l’image officielle qui fonctionne très bien normalement. Tu as envisagé un problème de pgid et guid?

**Comment by GeoCookie** [comment]
Ils sont bons, j'utilise le même pour les conteneurs Sonarr et radarr. Et bazarr arrive bien à écrire les sous-titres sur le nas.
________________________________

**Comment by morpheus65535** [comment]
L'erreur 500 est fixée en dev. Tu peux tester?

**Comment by GeoCookie** [comment]
Bonjour @morpheus65535,

L'erreur 500 est bien corrigée (je vois la loupe tourner sur elle-même). Malheureusement, mon problème persiste.
Il me semble malgré tout avoir noté une différence. Avant, Bazarr téléchargeait systématiquement les sous-titre dès que je cliquais sur la loupe. Maintenant, il ne les télécharge plus qu'une fois. Il les a téléchargé la première fois que j'ai cliqué sur la loupe. Les fois d'après, il n'a rien fait (j'ai quand même vu le message de recherche en bas à droite). Je ne sais pas si je suis très clair...

**Comment by morpheus65535** [comment]
Étant toujours incapable de reproduire ton problème, je vais te recommander de passer sur notre channel de support Discord ou tu pourras recevoir de l'aide dans la configuration de Bazarr. Je ne sais pas d'où vient ton problème mais ça fonctionne très bien avec tous les tests que je fais.

**Comment by GeoCookie** [comment]
Ok j'irais faire un tour sur Discord à mon retour de congés.
Merci

**Comment by GeoCookie** [comment]
Bonjour @morpheus65535,

Juste un petit retour pour te dire que tout fonctionne bien depuis mon retour de congés, sans n'avoir rien fait de particulier, à part la mise à jour de mes conteneurs. Ce problème restera un mystère :)

Encore merci pour ton aide !

**Comment by morpheus65535** [comment]
Ok merci du retour!
