### ISSUE TITLE
Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2019-02-21 23:50:48 EET)" raised an exception

### ISSUE THREAD

**Issue by dimitrov-adrian** [morpheus65535/bazarr#318]
**Describe the bug**
Got a lot of errors (repeat by 1 minute)

```
Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2019-02-21 23:50:48 EET)" raised an exception
```

```
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/bazarr/get_series.py", line 96, in update_series
  series_to_update)
OperationalError: unable to open database file
```

**Software (please complete the following information):**
 - Bazarr: v0.7.1 (from master)
 - Sonarr version 2.0.0.5301
 - OS: Docker on synology

**Additional context**
Restart does not helps, tried complete reset container, and it works for few days, then again got the error.

**Comment by morpheus65535** [comment]
Please provide a debug log. I've got no way of debugging without it.

**Comment by dimitrov-adrian** [comment]
[bazarr.log](https://github.com/morpheus65535/bazarr/files/2893926/bazarr.log)

**Comment by morpheus65535** [comment]
As this debug log do not cover the moment when it stop working, there not a lot of thing I can do to see why the DB stayed in locked mode. Can you provide a copy of your DB? Maybe on Discord in private.

**Comment by morpheus65535** [comment]
Any news? Is it permission related finally?

**Comment by dimitrov-adrian** [comment]
Well, may be it was permission issue indeed, I have tried chmoding and chowning without success.
Recreated container with not not exported volume and seems to works fine 2 days. Really not sure what was causing the issue.

**Comment by morpheus65535** [comment]
Let's keep it that way for a couple of days to see if thing changes. Keep me informed.

**Comment by morpheus65535** [comment]
My understanding is that it's working properly now. Please re-open this issue if you still have issue.
