### ISSUE TITLE
Job "series_download_subtitles (trigger: date[2019-02-22 08:09:56 CET], next run at: 2019-02-22 08:09:56 CET)" raised an exception

### ISSUE THREAD

**Issue by stefandevo** [morpheus65535/bazarr#319]
**Describe the bug**
Downloads are not working anymore

**Software (please complete the following information):**
Bazarr version
0.7.2
Sonarr version
2.0.0.5252
Radarr version
0.2.0.1293
Operating system
Darwin-17.7.0-x86_64-i386-64bit
Python version
2.7.10

**Comment by morpheus65535** [comment]
Can you provide the exception (the trace)?

**Comment by stefandevo** [comment]
I am going to close this for now. I deleted everything, re-installed everything, and left the program alone, updating whenever it felt too instead of forcing it. it seems to work for the moment.

**Comment by morpheus65535** [comment]
Ok keep in touch if it breaks again.
