### ISSUE TITLE
Database gets locked after a while

### ISSUE THREAD

**Issue by stefandevo** [morpheus65535/bazarr#320]
**Describe the bug**
I did a clean install of everything, re-entered everything. After a few hours running, I get lots of exceptions, and all seems to be pointed to:

Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2019-02-22 02:53:27 CET)" raised an exception
Traceback (most recent call last):
 File "bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/Users/USER/bazarr/bazarr/bazarr/get_series.py", line 87, in update_series
  db.commit()
OperationalError: database is locked

I also upgraded to dev branch but same result.

**Software (please complete the following information):**
Bazarr version
0.7.2
Sonarr version
2.0.0.5252
Radarr version
0.2.0.1293
Operating system
Darwin-17.7.0-x86_64-i386-64bit
Python version
2.7.10

**Comment by morpheus65535** [comment]
Please provide debug log.

**Comment by stefandevo** [comment]
I am going to close this for now. I deleted everything, re-installed everything, and left the program alone, updating whenever it felt too instead of forcing it. it seems to work for the moment.
