### ISSUE TITLE
Bazarr won't start anymore

### ISSUE THREAD

**Issue by NobleAuditore** [morpheus65535/bazarr#322]
I get this error when I try and run it from an Admin cmd:

C:\WINDOWS\system32>"C:\Program Files\bazarr\bazarr.py"
Bazarr starting...
2019-02-23 19:34:36,144 - root                             (b74) :  ERROR (main:53) - BAZARR require gevent Python module to be installed using pip.
Bazarr exited.

**Comment by morpheus65535** [comment]
The error is quite simple to interpret. You need to install gevent. See the wiki (run from sources).

**Comment by NobleAuditore** [comment]
Hey sorry, I'm very bad at this. I'm unsure which version of gevent to install. https://pypi.org/project/gevent/#files

Also, I don't understand why I install it at all? Like why did Bazarr stop working all of a sudden? I've had it up and running for quite some time.

**Comment by morpheus65535** [comment]
That’s a new requirement since a couple of weeks. You just need to run `pip install gevent` in a command prompt.

**Comment by NobleAuditore** [comment]
`C:\WINDOWS\system32>pip install gevent
'pip' is not recognized as an internal or external command,
operable program or batch file.`

Is what I get

**Comment by morpheus65535** [comment]
Python isn’t in your system path. Try this: `c:\python27\python -m pip install gevent`

**Comment by NobleAuditore** [comment]
Thank you! Bazarr is up and running again!
