### ISSUE TITLE
Wrong message during setup wizard

### ISSUE THREAD

**Issue by serkef** [morpheus65535/bazarr#324]
**Describe the bug**
In the setup wizard, when configuring the Radarr connection, the message 

 > You must test your **Sonarr** connection settings before saving settings.

**To Reproduce**
1. Fresh install Bazarr
2. Open UI
3. [wizard starts]
4. Go to 4th step (Radarr setup)

**Expected behavior**
> You must test your **Radarr** connection settings before saving settings.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/3225779/53298458-cc5feb00-382e-11e9-94fc-99025986ff53.png)

**Software (please complete the following information):**
 - Bazarr: [e.g. v 0.7.1]
 - Radarr version [e.g. v 0.2.0.5301]
 - Sonarr version [e.g. v 0.2.0.1293]
 - OS: [e.g. Windows 10]

**Comment by serkef** [comment]
Seems trivial, the wrong string is included in `views/wizard.tpl`.
I would like to fix it.

**Comment by halali** [comment]
Thanks, i missed that... fixed in development branch
