### ISSUE TITLE
Add the OpenSubtitles VIP Provider

### ISSUE THREAD

**Issue by darthShadow** [morpheus65535/bazarr#327]
**Is your feature request related to a problem? Please describe.**
According to the official [docs](http://trac.opensubtitles.org/projects/opensubtitles/wiki/XMLRPC#LogIn), there is a separate API server for VIP members which is supposed to be much more stable and faster. Using this should result in fewer error responses due to server load. Subliminal has just added support for this in the develop branch with the PR [#957](https://github.com/Diaoul/subliminal/commit/be472d93d3310d9a981c232261f5f29bbbb8ad13)

**Describe the solution you'd like**
Option to configure the VIP provider.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by darthShadow** [comment]
I just checked the latest version and there appears to be support for the VIP via the sub-zero patched version of subliminal. Not sure whether it would be better to use the official VIP provider from Subliminal or continue using the patched version...

**Comment by halali** [comment]
Its same.

**Comment by darthShadow** [comment]
Yeah, functionality-wise its pretty much the same. Just wanted to get it done the official way so we can eventually remove the need for the patched version.

**Comment by morpheus65535** [comment]
There's no plan to get rid of patched version of subliminal for now. It provide a lot of functionalities out of the box that are still not present in official version. Thanks for your feedback!
