### ISSUE TITLE
Bazarr does not detect existing subtitles nor does detect it's own downloaded subtitles

### ISSUE THREAD

**Issue by DeviDarkL** [morpheus65535/bazarr#328]
**Describe the bug**
Bazarr does not detect existing subtitles nor does detect it's own downloaded subtitles. It does not download subtitles automatically. 

**To Reproduce**
When I click on "Download wanted subtitles nothing happens. I have to manually click on the magnifying glass icon on each TVshow page.

**Software (please complete the following information):**
 - Bazarr: [e.g. v 0.7.2]
 - Sonarr version [e.g. v 2.0.0.5301]
 - OS: [Windows 10]

**Comment by morpheus65535** [comment]
You definitely have something not configured correctly. Please come see us on Discord for support!
