### ISSUE TITLE
Updates fail

### ISSUE THREAD

**Issue by Julien-D** [morpheus65535/bazarr#33]
When I try to update Bazarr (in the "tasks" tab), I have the following error message in the logs:
`Job "Update bazarr from source on Github (trigger: interval[6:00:00], next run at: 2017-12-29 20:37:12 CET)" raised an exception
`
```
'Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job
retval = job.func(*job.args, **job.kwargs)
File "/home/nzbdrone/bazarr/check_update.py", line 14, in check_and_apply_update
repo.remotes[remote_name].fetch()
File "/usr/local/lib/python2.7/dist-packages/pygit2/remote.py", line 405, in fetch
check_error(err)
File "/usr/local/lib/python2.7/dist-packages/pygit2/errors.py", line 64, in check_error
raise GitError(message)
GitError: there is no TLS stream available'
```
What is the origin of this message?

**Comment by morpheus65535** [comment]
If you still got this error on every update, could you please run this from Bazarr directory:

    git pull origin master

Replace "master" by "development" based on your settings.

Do you still got an error?

**Comment by Julien-D** [comment]
The `git pull` and `git pull origin master` commands works but the update though UI still does not. I have the same error.

**Comment by morpheus65535** [comment]
Seems to be related to a missing parameters when building libgit2 from sources. Take a look at:

https://github.com/libgit2/libgit2/issues/3786

**Comment by morpheus65535** [comment]
I'm currently replacing the update mechanism with something less fragile... you can try it with the development branch now. I'll give it a try for a couple of days before merging it to master. It won't require libgit2 and will only rely on gitpython and git executable that must be in path.

**Comment by Julien-D** [comment]
Yes, it works in the development branch.
Thanks Morpheus
Great work!

**Comment by morpheus65535** [comment]
👍
