### ISSUE TITLE
Bazarr is restarting, please wait and it doesn't restart.

### ISSUE THREAD

**Issue by rickytin** [morpheus65535/bazarr#333]
Bazarr version 0.7.2
Sonarr version 3.0.0.348
Radarr version 0.2.0.1293
Operating system Windows-10-10.0.18312

I update to the latest development version and then "Bazarr is restarting, please wait" and it doesn't restart.

I delete Bazarr and install it again with git and it work but then it make the update to the latest version and it doesn't restart.

**Comment by halali** [comment]
I will need debug log...

**Comment by morpheus65535** [comment]
I’ve made a revert on the last commit. Reinstall and update and you should be all good. Please give me feedback.

**Comment by rickytin** [comment]
Yes now is working, thanks.
