### ISSUE TITLE
Error when bulk searching for wanted subtitles

### ISSUE THREAD

**Issue by creativefre** [morpheus65535/bazarr#337]
**Describe the bug**
Error when bulk searching for new subtitles.
Already had this error like 3 times when trying again.

Error: 500 Internal Server Error
Sorry, the requested URL 'http://localhost:6767/wanted_search_missing_subtitles' caused an error:

Internal Server Error
Exception:
TypeError('expected string or buffer',)
Traceback:
Traceback (most recent call last):
  File "c:\bazarr\bazarr\bazarr\../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "c:\bazarr\bazarr\bazarr\../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "c:\bazarr\bazarr\bazarr\main.py", line 135, in wrapper
    return func(*a, **ka)
  File "c:\bazarr\bazarr\bazarr\main.py", line 1066, in wanted_search_missing_subtitles_list
    wanted_search_missing_subtitles()
  File "c:\bazarr\bazarr\bazarr\get_subtitle.py", line 660, in wanted_search_missing_subtitles
    wanted_download_subtitles(episode[0])
  File "c:\bazarr\bazarr\bazarr\get_subtitle.py", line 573, in wanted_download_subtitles
    episode[7], 'series')
  File "c:\bazarr\bazarr\bazarr\get_subtitle.py", line 247, in download_subtitle
    language_hook=None)  # fixme
  File "c:\bazarr\bazarr\bazarr\../libs/subliminal_patch\core.py", line 737, in download_best_subtitles
    compute_score=compute_score)
  File "c:\bazarr\bazarr\bazarr\../libs/subliminal_patch\core.py", line 355, in download_best_subtitles
    matches = s.get_matches(video)
  File "c:\bazarr\bazarr\bazarr\../libs/subliminal_patch\providers\opensubtitles.py", line 46, in get_matches
    matches = super(OpenSubtitlesSubtitle, self).get_matches(video)
  File "c:\bazarr\bazarr\bazarr\../libs/subliminal\providers\opensubtitles.py", line 81, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'episode'}))
  File "c:\bazarr\bazarr\bazarr\../libs/subliminal_patch\subtitle.py", line 359, in guess_matches
    if video.series and 'title' in guess and sanitize(guess['title']) == sanitize(video.series):
  File "c:\bazarr\bazarr\bazarr\../libs/subliminal\utils.py", line 111, in sanitize
    string = re.sub(r'[%s]' % re.escape(''.join(characters)), ' ', string)
  File "C:\Python\Python27\lib\re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

**Expected behavior**
Bulk searching be able to find the subtitle

**Screenshots**
![error](https://user-images.githubusercontent.com/23296871/53811315-61fb2900-3f59-11e9-8eec-efdf2087bc3e.PNG)

**Software:**
 - Bazarr: V0.7.1
 - Radarr version v 0.2.0.1293
 - Sonarr version v 2.0.0.5301
 - OS: Windows 10

**Comment by morpheus65535** [comment]
Can you switch to dev branch in settings, force an update, restart Bazarr and confirm if it's still an issue in 0.7.2? Thanks!

**Comment by morpheus65535** [comment]
Thanks for reporting this one. I've pushed a fix in dev. You can force an update, restart and test again? Thanks!

**Comment by creativefre** [comment]
The script is running now. No errors untill now, I will let you know if the script finished succesfull!
Thanks for the fast respons and fix!

**Comment by creativefre** [comment]
Now I get this error:

05/03/2019 16:07:47|ERROR   |apscheduler.executors.default   |Job "manual_wanted_search_missing_subtitles (trigger: date[2019-03-05 15:59:06 CET], next run at: 2019-03-05 15:59:06 CET)" raised an exception|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/apscheduler\\executors\\base.py", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 597, in wanted_search_missing_subtitles\n    wanted_download_subtitles(episode[0])\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 509, in wanted_download_subtitles\n    episode[7], \'series\')\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 156, in download_subtitle\n    language_hook=None)  # fixme\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 740, in download_best_subtitles\n    compute_score=compute_score)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 355, in download_best_subtitles\n    matches = s.get_matches(video)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\providers\\opensubtitles.py", line 46, in get_matches\n    matches = super(OpenSubtitlesSubtitle, self).get_matches(video)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal\\providers\\opensubtitles.py", line 81, in get_matches\n    matches |= guess_matches(video, guessit(self.movie_release_name, {\'type\': \'episode\'}))\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\subtitle.py", line 359, in guess_matches\n    if video.series and \'title\' in guess and sanitize(guess[\'title\']) == sanitize(video.series):\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal\\utils.py", line 111, in sanitize\n    string = re.sub(r\'[%s]\' % re.escape(\'\'.join(characters)), \' \', string)\n  File "C:\\Python\\Python27\\lib\\re.py", line 155, in sub\n    return _compile(pattern, flags).sub(repl, string, count)\nTypeError: expected string or buffer'|

**Comment by morpheus65535** [comment]
Please enable debug logging in settings and provide a complete debug log.

**Comment by creativefre** [comment]
Normally the previous error didn't reoccur. And the script executed as normal.
Here are my log files:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/2933778/bazarr.log)

[bazarr.log.2019-03-05.zip](https://github.com/morpheus65535/bazarr/files/2933784/bazarr.log.2019-03-05.zip)

**Comment by morpheus65535** [comment]
@pannal Can you take a look at this one please?

**Comment by morpheus65535** [comment]
Is it still an issue with 0.7.3?

**Comment by Yoshi2889** [comment]
Just wanted to say it's been working fine for me in the last few releases, sorry for not replying earlier :)
