### ISSUE TITLE
Subtitles section on does not work as expected.

### ISSUE THREAD

**Issue by barneh** [morpheus65535/bazarr#340]
**Describe the bug**
The Subtitles section on the Series tab does not count my subtitles in my series. Most of the just shown 0/0, even I do have all the subtitles for some series. If I go into a series, Radarr shows the correct number of subtitles for every season, as shown in the screenshots.

**Expected behavior**
Showing how many subtitles I have collected for every series I have.

**Screenshots**
![seriesview](https://user-images.githubusercontent.com/16772925/53879147-06d73e00-400e-11e9-8b57-60a86749dfc2.jpg)
![serievikings](https://user-images.githubusercontent.com/16772925/53879163-0d65b580-400e-11e9-805b-8f22f433d1bc.jpg)
![seriethewalkingdead](https://user-images.githubusercontent.com/16772925/53879167-1060a600-400e-11e9-9d77-59147daffa17.jpg)

**Software**
 - Bazarr: 0.7.2 (Development branch) Even got the same problem on 0.7.1 Master branch 
 - Radarr version  [don't use]
 - Sonarr version 2.0.0.5301
 - OS: Windows 10, version: 1809

**Additional context**
I have Bazarr set to collect English (en) & Swedish (sv).
I installed Bazarr with help from the Windows section here: https://github.com/morpheus65535/bazarr/wiki/Installation-Running-from-Source but I'm not running Bazarr as a service with NSSM. I made a bat-file contained the line 'python bazarr.py' and made it into a *.exe file and drop it in Windows Startup folder for the user.
Bazarr have no problem collect series from Sonarr and does scrape the disk for subtitles without any errors in the log.

**Comment by halali** [comment]
Can you please post screenshot for Vikings series with episodes season 5.

**Comment by barneh** [comment]
@halali here you have it!
![vikingsseason5](https://user-images.githubusercontent.com/16772925/53889805-57a76080-4027-11e9-8fb6-29136956d723.jpg)

**Comment by halali** [comment]
You have probably enabled settings download only monitored under settings/sonarr... And unmonitored episodes in sonarr

**Comment by morpheus65535** [comment]
@Barneh does it fix your issue?

**Comment by TheFes** [comment]
> @halali here you have it! And it looks strange when it says 5/20 right?
> 
> ![vikingsseason5](https://user-images.githubusercontent.com/16772925/53889805-57a76080-4027-11e9-8fb6-29136956d723.jpg)

5/20 seems to be the right number.
There are 20 episodes. 5 of them have all requested subtitles.
Hence 5/20

**Comment by barneh** [comment]
> @barneh does it fix your issue?
Yes the @halali suggestion was spot on it was what he suggestion.
![sonarrdownloadonymonitored](https://user-images.githubusercontent.com/16772925/53988873-cb7b6300-4124-11e9-9b31-e63baf44a0c0.jpg)



> > @halali here you have it! And it looks strange when it says 5/20 right?
> > ![vikingsseason5](https://user-images.githubusercontent.com/16772925/53889805-57a76080-4027-11e9-8fb6-29136956d723.jpg)
> 
> 5/20 seems to be the right number.
> There are 20 episodes. 5 of them have all requested subtitles.
> Hence 5/20
Yes but I think it's a bit confusing, since I would like an option that says okay for that particular eposide, if I have one out of two (too many) languages downloaded for that episode. And as I can understand this options isn't available @halali @morpheus65535?
But since this maybe is a probably a new feature, you can close this issue @morpheus65535.

Thanks for great support and the work that has been done with Bazarr!

**Comment by morpheus65535** [comment]
Thanks for the feedback. You’re right, this is a new functionality so I’m going to close this issue.
