### ISSUE TITLE
LanguageReverseError() on one movie

### ISSUE THREAD

**Issue by huuub** [morpheus65535/bazarr#341]
**Describe the bug**
Everything works but one movie gives me problems
Star Wars (1977)$ ls -lrt
total 3268464
-rw-r--r-- 1 jeroen docker 2821163135 Apr  4  1997 'Star Wars - 1977 - Bluray-1080p.mkv'
-rwxrwxr-x 1 jeroen docker      77724 Dez 25  2015 'Star Wars - 1977 - Bluray-1080p.16.srt'
-rwxrwxr-x 1 jeroen docker     131754 Dez 25  2015 'Star Wars - 1977 - Bluray-1080p.15.srt'
-rwxrwxr-x 1 jeroen docker     107759 Dez 25  2015 'Star Wars - 1977 - Bluray-1080p.3.srt'
-rwxrwxr-x 1 jeroen docker      79085 Dez 25  2015 'Star Wars - 1977 - Bluray-1080p.2.srt'
-rwxrwxr-x 1 jeroen docker     108998 Dez 25  2015 'Star Wars - 1977 - Bluray-1080p.1.srt'
-rwxrwxr-x 1 jeroen docker     101523 Dez 25  2015 'Star Wars - 1977 - Bluray-1080p.9.srt'
-rwxrwxr-x 1 jeroen docker     104946 Dez 25  2015 'Star Wars - 1977 - Bluray-1080p.8.srt'
-rwxrwxr-x 1 jeroen docker     109854 Dez 25  2015 'Star Wars - 1977 - Bluray-1080p.7.srt'
-rwxrwxr-x 1 jeroen docker     102998 Dez 25  2015 'Star Wars - 1977 - Bluray-1080p.6.srt'
-rwxrwxr-x 1 jeroen docker     110267 Dez 25  2015 'Star Wars - 1977 - Bluray-1080p.5.srt'
-rwxrwxr-x 1 jeroen docker     103317 Dez 25  2015 'Star Wars - 1977 - Bluray-1080p.4.srt'
-rwxrwxr-x 1 jeroen docker      74013 Dez 25  2015 'Star Wars - 1977 - Bluray-1080p.14.srt'
-rwxrwxr-x 1 jeroen docker      79571 Dez 25  2015 'Star Wars - 1977 - Bluray-1080p.13.srt'
-rwxrwxr-x 1 jeroen docker     101547 Dez 25  2015 'Star Wars - 1977 - Bluray-1080p.12.srt'
-rwxrwxr-x 1 jeroen docker      97373 Dez 25  2015 'Star Wars - 1977 - Bluray-1080p.11.srt'
-rwxrwxr-x 1 jeroen docker      78177 Dez 25  2015 'Star Wars - 1977 - Bluray-1080p.10.srt'
-rwxrwxr-x 1 jeroen docker  174435072 Dez 25  2015 'Star Wars - 1977 - Bluray-1080p.ac3'
-rwxrwxr-x 1 jeroen docker  174415872 Dez 25  2015  Harmy.ANH.2.5_track18_eng.ac3
-rwxrwxr-x 1 jeroen docker  174935040 Dez 25  2015  Harmy.ANH.2.5_track17_eng.ac3
-rw-r--r-- 1 jeroen docker        643 Jan  5 13:40  movie.xml
-rw-r--r-- 1 jeroen docker        416 Jan  5 13:40  Star.Wars.1977.Bluray-1080p.xml
-rw-r--r-- 1 jeroen docker     134958 Jan  5 13:56 'Star Wars - 1977 - Bluray-1080p.nl.srt'
-rw-r--r-- 1 jeroen docker      55854 Jan  5 14:03 'Star Wars - 1977 - Bluray-1080p.pl.srt'
-rw-r--r-- 1 jeroen docker     134958 Mär  7 10:34 'Star Wars - 1977 - Bluray-1080p.srt'

Error:
Error: 500 Internal Server Error
Sorry, the requested URL 'https://bazarr.home.huuub.com/scan_disk_movie/62' caused an error:

Internal Server Error
Exception:
LanguageReverseError()
Traceback:
Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 135, in wrapper
    return func(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 867, in scan_disk_movie
    movies_scan_subtitles(no)
  File "/app/bazarr/bazarr/list_subtitles.py", line 335, in movies_scan_subtitles
    store_subtitles_movie(path_replace_movie(movie[0]))
  File "/app/bazarr/bazarr/list_subtitles.py", line 140, in store_subtitles_movie
    subtitles = search_external_subtitles(file)
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 634, in search_external_subtitles
    only_one=only_one))
  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 597, in _search_external_subtitles
    language = Language.fromietf(language_code)
  File "/app/bazarr/bazarr/../libs/subzero/language.py", line 62, in inner
    instance = f(cls, base, *args, **kwargs)
  File "/app/bazarr/bazarr/../libs/subzero/language.py", line 127, in fromietf
    return Language(*Language_.fromietf(ietf).__getstate__())
  File "/app/bazarr/bazarr/../libs/babelfish/language.py", line 123, in fromietf
    language = cls.fromalpha2(language_subtag)
  File "/app/bazarr/bazarr/../libs/babelfish/language.py", line 109, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/app/bazarr/bazarr/../libs/babelfish/converters/__init__.py", line 165, in reverse
    raise LanguageReverseError(code)
LanguageReverseError: u'14'

**Comment by morpheus65535** [comment]
`Star Wars - 1977 - Bluray-1080p.14.srt`: 14 isn’t a valid language. 14 need to be replaced by valid IETF language code.
