### ISSUE TITLE
"high" cpu usage when doing nothing

### ISSUE THREAD

**Issue by evertonstz** [morpheus65535/bazarr#342]
**Describe the bug**
Don't know if it's only in my side, but bazarr seems to be a little off in CPU usage when doing nothing, in my system it stays around 2% of CPU usage. Its not much but over time it'll add up on energy costs.
Other apps usage when doing nothing, on average, in my system:
emby: 0.20%
sonarr: 0.05%
deluge: 0.50%
nzbget: 0.10% (this is actually downloading a file, pretty impressive tbh)
radarr: 0.02%
ombi: 0.17%

After seing those numbers you can see why bazarr is a little off...

**Expected behavior**
Use as minimal resources as possible when doing nothing.

**Software (please complete the following information):**
 - Bazarr: v0.7.1
 - OS: Docker container

**Comment by morpheus65535** [comment]
Bazarr use more CPU if the web UI is open somewhere. As client poll for notifications every second it generate CPU load. In my case, with no web UI opened, my CPU usage look like this:

![image](https://user-images.githubusercontent.com/5130500/54072288-d8907300-4246-11e9-9023-1861588bb533.png)

It stay under 1% all the time except for nightly full indexing where it goes up to 3%.

TBH, I would be curious to see the power consumption difference if you stop Bazarr container. I suspect that 2% CPU usage doesn't count for a single US$/Euro over a year... I'm not sure using my computer to rework Bazarr to gain 1% in CPU usage won't cost me more than what it's going to save you... ;-)

**Comment by evertonstz** [comment]
@morpheus65535 after rebuilding the docker container my consumption is the same as yours: under 1% when idle and ~2.5% when indexing. I'm not sure what was causing the problem but I'm sure it wasn't Bazarr and it was related with the container itself. If it happens again I'll be sure to document it better.

**Comment by morpheus65535** [comment]
Thanks for your feedback!
