### ISSUE TITLE
Bazarr is restarting, please wait and it doesn't restart.

### ISSUE THREAD

**Issue by rickytin** [morpheus65535/bazarr#343]
Bazarr version 0.7.2
Sonarr version 3.0.0.348
Radarr version 0.2.0.1293
Operating system Windows-10-10.0.18312

I update to the latest development version and then "Bazarr is restarting, please wait" and it doesn't restart.

**Comment by morpheus65535** [comment]
Please run `git pull` from Bazarr directory and confirm if the issue is fixed after restarting.

**Comment by rickytin** [comment]
Yes I run git pull and it's fix after restart, thanks.

**Comment by spikemixture** [comment]
I have the same issue running bazarr in docker on a Qnap NAS.

The restarting does not restart. 
If i restart the docker I must restart all settings as they r gone. 
And I get to restarting again and same result. 
Bazarr 0.8.2.4
Sonarr 3.0.3.741
Radarr 0.2.0.1480

**Comment by morpheus65535** [comment]
> I have the same issue running bazarr in docker on a Qnap NAS.
> 
> The restarting does not restart.
> If i restart the docker I must restart all settings as they r gone.
> And I get to restarting again and same result.
> Bazarr 0.8.2.4
> Sonarr 3.0.3.741
> Radarr 0.2.0.1480

Did you ever think about updating to latest first? 0.8.2.4 is like 6 months old...

**Comment by spikemixture** [comment]
> > I have the same issue running bazarr in docker on a Qnap NAS.
> > The restarting does not restart.
> > If i restart the docker I must restart all settings as they r gone.
> > And I get to restarting again and same result.
> > Bazarr 0.8.2.4
> > Sonarr 3.0.3.741
> > Radarr 0.2.0.1480
> 
> Did you ever think about updating to latest first? 0.8.2.4 is like 6 months old...

I make a habit of using the latest version of everything.

I have **8.4.2** I had the number the wrong way around .

_I also cannot install direct on qnap - that is why i am trying Docker. 
Error	28/03/2020	08:35:57 PM	System	127.0.0.1	App Center	App Installation	[App Center] Failed to install Bazarr due to data file error._

**Comment by morpheus65535** [comment]
@spikemixture I have no idea how you run it on Qnap but from my amd64 system using linuxserver/bazarr:latest it works fine.

**Comment by spikemixture** [comment]
> @spikemixture I have no idea how you run it on Qnap but from my amd64 system using linuxserver/bazarr:latest it works fine.

Great . That's a very helpful answer. 
Why bother even replying ?

**Comment by spikemixture** [comment]
was a setting in a url while installing was wrong
