### ISSUE TITLE
Option to disable scanning of embedded subtitles

### ISSUE THREAD

**Issue by madknave** [morpheus65535/bazarr#344]
**Is your feature request related to a problem? Please describe.**
Scaning of embedded subtitles works great and I have no issues with, except that subtitles stored per video file dissapear often enough triggering the embedded subtitles scanning as an infinite loop. I have noticed that the embeded subtitles dissapear after a timeout communication with Sonarr/Radarr (which happens with big libraries and while Sonarr/Radarr is doing its daily refresh of series)

**Describe the solution you'd like**
Option one: Make Bazarr to not delete the embedded subtitle information if there is any type of timeout communication errors with Sonarr/Radarr (preferred option)

Option two: Give the option to avoid the scanning of embedded subtitles all together.

**Describe alternatives you've considered**
I have activated the option to download only monitored show/movies in Sonarr/Radarr, but Bazarr still wants to scan the embeded subtitles in all the video files.

**Additional context**
The reason for the request is that the video scanning for embeded subtitles is a high downaload quota consumption for systems with cloud mounted filesystems (rclone). I'm just trying to reduce the unnecesary api calls.

**Comment by morpheus65535** [comment]
Just disable "Use embedded subtitles" in Subliminal settings. You can also disable nightly scan for both sonarr and radarr (default value is everyday at 4/5am).

**Comment by madknave** [comment]
Embedded subtitles option is off in the settings, but Bazarr still tries to scan the video files for the embedded subtitles.

**Comment by morpheus65535** [comment]
This option only tell Bazarr to not take care of embedded subtitles when determining missing subtitles.

The other options I've been mentionning disable nightly scan so you won't be scanning file system and won't generate API request to cloud service.

**Comment by madknave** [comment]
I understand that that's what the embedded subtitle option does, and although off, Bazarr still tries to obtain that information from the video.

The nightly scan option is also off in the settings. The problem, I assume, arises when Bazarr is doing another one of the other tasks (Sync episodes or Update series) and there is a timeout from Sonarr.  When this happens, the embedded information already stored for the video disappears, thus triggering another scan for those video files.

**Comment by morpheus65535** [comment]
Even if you disable "use embedded subtitles", they are going to be indexed by Bazarr. This is a normal behavior.

Your issue isn't related to that and should be addressed correctly. Losing information isn't a nromal behavior and I highly suggest you come to Discord to ask for help. You'll be able to provide a debug log so the support team is able to better help you. Communication will be easier that way.
