### ISSUE TITLE
Systemd start stop script leave one process active

### ISSUE THREAD

**Issue by Jorman** [morpheus65535/bazarr#345]
Hi, from awhile I've some problem shutting down my system, take over 30 minutes to reboot, seems that one process stuck the shutdown.
Yesterday I tried, before a reboot, to stop all unnecessary process, the results is that all was ok! So is a service problem.

I've to make some test to see what process makes this shutdown so slow, but I noticed that when bazarr start 2 process:
![111](https://user-images.githubusercontent.com/5203988/54200207-23bab800-44cb-11e9-9f32-39127c57a367.PNG)
Then when I stop the service, one process remain active:
![222](https://user-images.githubusercontent.com/5203988/54200345-76946f80-44cb-11e9-8b8f-4733382f0cbc.PNG)

Do you think this can be a problem? (I not yet tested my theory, later I'll try to make some test disabling half of process that I disabled 1st time)
Is possible to make a fix for this?

**Comment by morpheus65535** [comment]
bazarr.py is the daemon process for Bazarr. main.py is the child process doing all the magic. If you force quit the daemon, the child process will get lost. You need to gracefully exit the daemon process.

Another option would be to run directly main.py but you'll lose the ability to restart bazarr from the web UI.

**Comment by Jorman** [comment]
First I've to make a test, maybe is not bazarr the problem for my slow shutdown

In case the problem is bazarr , what do you think if I make a simple script that run after the systemd shutdown?

**Comment by morpheus65535** [comment]
I suggest you read this post and define KillSignal in your systemd configuration: https://raspberrypi.stackexchange.com/questions/77738/how-to-exit-a-python-daemon-cleanly

**Comment by Jorman** [comment]
Ok thanks! I'll try to make a clean exit.
I'm using the recommended systemd service for bazarr, do you think that must be updated with the
`KillSignal=SIGINT`
?

**Comment by Jorman** [comment]
Maybe I misunderstood the lecture!
This's the systemd service
```
[Unit]
Description=Bazarr Daemon
After=syslog.target network.target

[Service]
MemoryMax=150M
WorkingDirectory=/opt/Bazarr/
User=muletto
Group=muletto
UMask=0002
Restart=on-failure
RestartSec=5
Type=simple
ExecStart=/usr/bin/python /opt/Bazarr/bazarr.py
KillMode=process
KillSignal=SIGINT
TimeoutStopSec=20
SyslogIdentifier=bazarr

[Install]
WantedBy=multi-user.target
```
I tried to stop the service and I got this error, from journalctl:
```
Mar 12 19:46:32 Qnap systemd[1]: Started Bazarr Daemon.
Mar 12 19:52:14 Qnap systemd[1]: Stopping Bazarr Daemon...
Mar 12 19:52:14 Qnap bazarr[13441]: Bazarr starting...
Mar 12 19:52:14 Qnap bazarr[13441]: 2019-03-12 19:46:52,827 - root                             (7f252fba15c0) :  INFO (main:1937) - BAZARR is started and waiting for re
Mar 12 19:52:14 Qnap bazarr[13441]: Traceback (most recent call last):
Mar 12 19:52:14 Qnap bazarr[13441]:   File "/opt/Bazarr/bazarr/main.py", line 1938, in <module>
Mar 12 19:52:14 Qnap bazarr[13441]:     server.serve_forever()
Mar 12 19:52:14 Qnap bazarr[13441]:   File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 367, in serve_forever
Mar 12 19:52:14 Qnap bazarr[13441]:     self.start()
Mar 12 19:52:14 Qnap bazarr[13441]:   File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 305, in start
Mar 12 19:52:14 Qnap bazarr[13441]:     self.init_socket()
Mar 12 19:52:14 Qnap bazarr[13441]:   File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 1490, in init_socket
Mar 12 19:52:14 Qnap bazarr[13441]:     StreamServer.init_socket(self)
Mar 12 19:52:14 Qnap bazarr[13441]:   File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 146, in init_socket
Mar 12 19:52:14 Qnap bazarr[13441]:     self.socket = self.get_listener(self.address, self.backlog, self.family)
Mar 12 19:52:14 Qnap bazarr[13441]:   File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 157, in get_listener
Mar 12 19:52:14 Qnap bazarr[13441]:     return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
Mar 12 19:52:14 Qnap bazarr[13441]:   File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 256, in _tcp_listener
Mar 12 19:52:14 Qnap bazarr[13441]:     sock.bind(address)
Mar 12 19:52:14 Qnap bazarr[13441]:   File "<string>", line 1, in bind
Mar 12 19:52:14 Qnap bazarr[13441]: socket.error: [Errno 98] Address already in use: ('0.0.0.0', 6767)
Mar 12 19:52:14 Qnap bazarr[13441]: Traceback (most recent call last):
Mar 12 19:52:14 Qnap bazarr[13441]:   File "/opt/Bazarr/bazarr.py", line 68, in <module>
Mar 12 19:52:14 Qnap bazarr[13441]:     time.sleep(0.001)
Mar 12 19:52:14 Qnap bazarr[13441]: KeyboardInterrupt
Mar 12 19:52:34 Qnap systemd[1]: bazarr.service: State 'stop-sigterm' timed out. Killing.
Mar 12 19:52:34 Qnap systemd[1]: bazarr.service: Killing process 13441 (python) with signal SIGKILL.
Mar 12 19:52:34 Qnap systemd[1]: bazarr.service: Main process exited, code=killed, status=9/KILL
Mar 12 19:52:34 Qnap systemd[1]: Stopped Bazarr Daemon.
Mar 12 19:52:34 Qnap systemd[1]: bazarr.service: Unit entered failed state.
Mar 12 19:52:34 Qnap systemd[1]: bazarr.service: Failed with result 'timeout'.
```
And the process
`python -u /opt/Bazarr/bazarr/main.py`
Is still in execution

Any idea?

**Comment by morpheus65535** [comment]
To be honest, I have never been an expert with systemd. You can try to get help on Discord from other users but, as stated on the wiki, we do not officialy support this because we don't have the knowledge/time to do it.

**Comment by Jorman** [comment]
Ok no problem.
Many thanks!

I'll try to find a way, always that this is the problem.
So if I find a solution, do you mind if I udate the systemd script? Or do you think I'll create a problem for the trigger update inside bazarr?

**Comment by morpheus65535** [comment]
If you update the systemd script, please share it here so I can modify the wiki accordingly. Thanks!

**Comment by Jorman** [comment]
I confirm! I had to modify my systemd service in order to not have shutdown problem, so this's my systemd service
```
[Unit]
Description=Bazarr Daemon
After=syslog.target network.target

[Service]
MemoryMax=150M
WorkingDirectory=/opt/Bazarr/
User=muletto (or username of choice)
Group=muletto (or group of choice)
UMask=0002
Restart=on-failure
RestartSec=5
Type=simple
ExecStart=/usr/bin/python /opt/Bazarr/bazarr.py (double check your location)
KillSignal=SIGINT
TimeoutStopSec=20
SyslogIdentifier=bazarr

[Install]
WantedBy=multi-user.target
```

But I don't know if this can make some problem with the update trigger inside Bazarr

**Comment by ronajon** [comment]
i can confirm the systemd script of Jorman works
with the wiki systemd script after shutting down bazarr.service it left one process running

`
ronajon@zolder:/opt/bazarr$ sudo systemctl status bazarr.service
● bazarr.service - bazarr Daemon
   Loaded: loaded (/etc/systemd/system/bazarr.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2019-05-12 09:34:37 CEST; 17s ago
 Main PID: 24429 (python)
    Tasks: 8 (limit: 4565)
   CGroup: /system.slice/bazarr.service
           ├─24429 /usr/bin/python /opt/bazarr/bazarr.py
           └─24431 /usr/bin/python -u /opt/bazarr/bazarr/main.py

May 12 09:34:37 zolder systemd[1]: Started bazarr Daemon.
ronajon@zolder:/opt/bazarr$ sudo ps -aux | grep bazarr
ronajon  24429  0.2  0.2 175464  9112 ?        Ssl  09:34   0:00 /usr/bin/python /opt/bazarr/bazarr.py
ronajon  24431 35.8  7.5 782056 301812 ?       Sl   09:34   0:11 /usr/bin/python -u /opt/bazarr/bazarr/main.py
ronajon  24592  0.0  0.0  14728   992 pts/3    S+   09:35   0:00 grep --color=auto bazarr
ronajon@zolder:/opt/bazarr$ sudo systemctl stop bazarr.service
ronajon@zolder:/opt/bazarr$ sudo ps -aux | grep bazarr
ronajon  24431 30.8  7.5 782056 301812 ?       Sl   09:34   0:12 /usr/bin/python -u /opt/bazarr/bazarr/main.py
ronajon  24622  0.0  0.0  14728   944 pts/3    S+   09:35   0:00 grep --color=auto bazarr
`

please update the wiki

**Comment by morpheus65535** [comment]
@ronajon Done!
