### ISSUE TITLE
Error trying to get video information for this file

### ISSUE THREAD

**Issue by pven** [morpheus65535/bazarr#346]
When searching for a sub, the warning/error below is shown in the log (for now I've enabled debugging):
```
2/03/2019 20:39:25|ERROR   |root                            |BAZARR Error trying to get video information for this file: /volume1/remote/media/TV/Nice Serie/Season 01/the.serie.s01e10.1080p.web.x264-tbs.mkv|Traceback (most recent call last):  File "/volume1/@appstore/bazarr/bazarr/get_subtitle.py", line 69, in get_video    refine_from_db(original_path,video)  File "/volume1/@appstore/bazarr/bazarr/get_subtitle.py", line 670, in refine_from_db    if int(data[4]) > 0: video.year = int(data[4])TypeError: int() argument must be a string or a number, not 'NoneType'|
```

1. Search for a sub
2. Check the log

 - Bazarr: [e.g. v 0.7.2]
 - OS: Synology (newest DSM, no beta)

**Comment by marcel5454** [comment]
Im having the exact same error after the latest update

**Comment by morpheus65535** [comment]
I've push a fix to dev branch, can you test it please?

**Comment by marcel5454** [comment]
Pulled the latest dev release and it seems to be fixed.

**Comment by morpheus65535** [comment]
@pven and for you?

**Comment by rallyemax** [comment]
@morpheus65535 

I don't know how to say this without sounding like a d*ck, but you're using dev/master branches incorrectly, mate. Untested code shouldn't go into master, with patches to the inevitable bugs being routed via dev. If you want to separate out new features into some sort of development (or any other) branch, that's great. It should be done. But they should be tested before being merged into master. And if you decide to **not** sequester untested code in a side branch, and simply dump it in master, you should also immediately submit any bug fixes into master as well. There may not be a single correct workflow in git, but it's probably the prototype of incorrect to place untested (i.e. bad) code in master and the fixes to that bad code in a development side branch.

**Comment by morpheus65535** [comment]
@rallyemax Don't worry, I'm always happy to discuss about what could be improved :-)

Regarding branch flow, every reading that I can find always state that master is the final destination: https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow

We are developing minor fixes in dev but major functionalities are developed in features branches. New features are tested by a limited group of users in dev before being merged to master and released.

Unfortunately, we are not able to test each and every use case as you can imagine. There is so many combination of Sonarr/Radarr version, enabled providers, enabled languages and so many other settings that can make think broke.

From time to time, some bug get through the dev branch up to master branch and can impact our main users group. That's something we try to avoid as much as possible by testing the dev branch thoroughly but, as a previously said, we cannot get everything.

Again, thanks for your feedback!

**Comment by pven** [comment]
> @pven and for you?

Sorry, I did not have time yet to look at it. Will get back to this asap.

**Comment by pven** [comment]
I am currently running the dev-branche. I will let you know over some hours if the error is gone. (As far as I know, I can not trigger it?)

**Comment by pven** [comment]
I just noticed another simular error, but I think it is more some kind of warning: 'Insufficient data to process the guess' ?

```
23/03/2019 10:10:29|ERROR   |root                            |BAZARR Error trying to get video information for this file: /volume1/remote/media/TV/Nice Show/Season 01/Nice.Show.Part.8.720p.HDTV.x264-TURBO-Obfuscated.mkv|'Traceback (most recent call last):\n  File "/volume1/@appstore/bazarr.dev/bazarr/get_subtitle.py", line 65, in get_video\n    video = parse_video(path, hints=hints, providers=providers, dry_run=dont_use_actual_file)\n  File "/volume1/@appstore/bazarr.dev/bazarr/../libs/subzero/video.py", line 58, in parse_video\n    skip_hashing=skip_hashing)\n  File "/volume1/@appstore/bazarr.dev/bazarr/../libs/subliminal_patch/core.py", line 522, in scan_video\n    video = Video.fromguess(path, guessed_result)\n  File "/volume1/@appstore/bazarr.dev/bazarr/../libs/subliminal/video.py", line 93, in fromguess\n    return Episode.fromguess(name, guess)\n  File "/volume1/@appstore/bazarr.dev/bazarr/../libs/subliminal/video.py", line 170, in fromguess\n    raise ValueError(\'Insufficient data to process the guess\')\nValueError: Insufficient data to process the guess'|
```

**Comment by morpheus65535** [comment]
> I just noticed another simular error, but I think it is more some kind of warning: 'Insufficient data to process the guess' ?
> 
> ```
> 23/03/2019 10:10:29|ERROR   |root                            |BAZARR Error trying to get video information for this file: /volume1/remote/media/TV/Nice Show/Season 01/Nice.Show.Part.8.720p.HDTV.x264-TURBO-Obfuscated.mkv|'Traceback (most recent call last):\n  File "/volume1/@appstore/bazarr.dev/bazarr/get_subtitle.py", line 65, in get_video\n    video = parse_video(path, hints=hints, providers=providers, dry_run=dont_use_actual_file)\n  File "/volume1/@appstore/bazarr.dev/bazarr/../libs/subzero/video.py", line 58, in parse_video\n    skip_hashing=skip_hashing)\n  File "/volume1/@appstore/bazarr.dev/bazarr/../libs/subliminal_patch/core.py", line 522, in scan_video\n    video = Video.fromguess(path, guessed_result)\n  File "/volume1/@appstore/bazarr.dev/bazarr/../libs/subliminal/video.py", line 93, in fromguess\n    return Episode.fromguess(name, guess)\n  File "/volume1/@appstore/bazarr.dev/bazarr/../libs/subliminal/video.py", line 170, in fromguess\n    raise ValueError(\'Insufficient data to process the guess\')\nValueError: Insufficient data to process the guess'|
> ```

GuessIt cannot guess the episode from your file name.

**Comment by pven** [comment]
The error in my first comment did not pop up anymore today,

**Comment by pven** [comment]
I am switching back to the master branche.

**Comment by morpheus65535** [comment]
You should be all good as master branch include this fix.

**Comment by thierrybla** [comment]
I am also getting this on newest master branch today.

Error:
`Traceback (most recent call last):
 File "/usr/local/bazarr/bazarr/get_subtitle.py", line 65, in get_video
  video = parse_video(path, hints=hints, providers=providers, dry_run=dont_use_actual_file)
 File "/usr/local/bazarr/bazarr/../libs/subzero/video.py", line 58, in parse_video
  skip_hashing=skip_hashing)
 File "/usr/local/bazarr/bazarr/../libs/subliminal_patch/core.py", line 522, in scan_video
  video = Video.fromguess(path, guessed_result)
 File "/usr/local/bazarr/bazarr/../libs/subliminal/video.py", line 93, in fromguess
  return Episode.fromguess(name, guess)
 File "/usr/local/bazarr/bazarr/../libs/subliminal/video.py", line 170, in fromguess
  raise ValueError(\Insufficient data to process the guess\)
ValueError: Insufficient data to process the guess`

**Comment by drlmorice** [comment]
I'm getting this error. no subtitles downloading. Any suggestions?

**Comment by halali** [comment]
Open new issue with all needed info. And debug log
