### ISSUE TITLE
macOS X LaunchAgent plist for Bazarr

### ISSUE THREAD

**Issue by davidnewhall** [morpheus65535/bazarr#347]
**Problem:**

There is no clear documentation about how to auto start Bazarr on a Mac.

**Solution:**

I'm providing a LaunchAgent plist file that can be installed at `~/Library/LaunchAgents/` and used to 
auto-start and auto-re-start Bazarr on a Mac. I recommend adding this file to the wiki and documenting how it's installed and utilized.

**Alternatives**

There are a few solutions to auto starting daemons and applications on a Mac. I have spent no time considering them or trying to make them work with this application. I've written LaunchAgents for a [handful of applications](https://github.com/davidnewhall/autotyed/tree/bece0ec3577aa97729fcd0d03ecea3cf5c49fbd2/startup/macos) and this was on my hit-list. I'm happy to contribute back.

**Additional context**

Documentation to go along with the file file: 

As-is, the LaunchAgent expects bazarr to be cloned or installed at `/Applications/bazarr`. If this is counter to other documentation I recommend amending the file contents. 

The LaunchAgent should be named `com.github.morpheus65535.bazarr.plist` - again, if you'd like something else, update the `Label` in the file itself as well.

The file is installed to `~/Library/LaunchAgents` and **the service will start when the user logs into the system.** After installation, the service can be started immediately by running `launchctl load ~/Library/LaunchAgents/com.github.morpheus65535.bazarr.plist`. The service can be stopped by running the same command replacing `load` with `unload`.

Logs are written to `/usr/local/var/log/bazarr.log`.

Here's the file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>com.github.morpheus65535.bazarr</string>
    <key>ProgramArguments</key>
    <array>
      <string>/usr/local/bin/python</string>
      <string>/Applications/bazarr/bazarr.py</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardErrorPath</key>
    <string>/usr/local/var/log/bazarr.log</string>
    <key>StandardOutPath</key>
    <string>/usr/local/var/log/bazarr.log</string>
  </dict>
</plist>
```

Regards,
-david

**Comment by davidnewhall** [comment]
This also assumes python is @ `/usr/local/bin`. If people are using system python instead of installing it form `brew` they're going to have a bad time anyway.

**Comment by morpheus65535** [comment]
Thanks for providing feedback on how to install on MacOS. Has we aren't MacOS user, we'll benefit from your work and I'll add this in the wiki pretty soon.

**Comment by morpheus65535** [comment]
Done.
