### ISSUE TITLE
Refresh Item in Plex after adding subtitles

### ISSUE THREAD

**Issue by marcel5454** [morpheus65535/bazarr#348]
**Is your feature request related to a problem? Please describe.**
When adding subtitles to the Folder Plex does not refresh metadata most of the times and therefore the subtitles do not show up in Plex. I then have to refresh Metadata manually. 

**Describe the solution you'd like**
On completed download refresh metadata for Item (Movie/Tv Show)

**Describe alternatives you've considered**
I tried using post processing and the Plex Media Scanner Command line tool but since it needs the section ID for either Movies or TV Show I have not found a practical solution yet.

**Comment by halali** [comment]
You can just enable in plex settings/library `Run a partial scan when changes are detected`
As we don't indexing content from plex we don't have plex id for shows or movies.

**Comment by morpheus65535** [comment]
BTW we tried to use Plex notification system but it is so badly documented and poorly maintained that appraiser developer stopped working on it. Your only way out of it is to enable scanning based on file system detection in Plex.

**Comment by neckaros** [comment]
Yes but unfortunately it does not work on FUSE file systems like recline gdrive mounts.
A notification to plex to do a partial scan à la sonarr and Radarr would be great!

**Comment by halali** [comment]
I use gdrive mount and it work for me normally. If you have issue with your mount type, try to use another type.
