### ISSUE TITLE
Not selecting the correct subtitle for the filename on opensubtitles

### ISSUE THREAD

**Issue by tekert** [morpheus65535/bazarr#351]
When auto searching for subtitles on opensubtitles from bazarr, and multiple subtitle versions are found, bazarr picks the wrong one.

Example, doing a manual search on a sub reports this:
1) 91.94% 	es	False	opensubtitles	6 6
2) 91.94%	        es	False	opensubtitles	6 6

one leads to the correct one (had the exact filename on the details section) the other doesn't

 - Bazarr: [0.7.2]
 - Sonarr version [2.0.0.5301]

**Comment by morpheus65535** [comment]
Please provide a full debug log to give us some more substance to work on.

**Comment by tekert** [comment]
Sorry, i just realized had debug disabled, here are the logs, took a capture from the moment i pressed auto search for that particular episode.

To light this particular case:
A manual search throws these two spanish subs for 'Fear.the.Walking.Dead.S04E01.720p.HDTV.x264-FLEET[rartv].mkv'
1) https://www.opensubtitles.org/en/subtitles/7379449/fear-the-walking-dead-what-s-your-story-es
2) https://www.opensubtitles.org/en/subtitles/7333413/fear-the-walking-dead-what-s-your-story-es

1 is wrong and is auto selected, 2 is the correct one.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/2970674/bazarr.log)

**Comment by morpheus65535** [comment]
Those two subtitles aren't matched on release_group and both of them match the same others criteria (in different order):
1. ['episode', 'hearing_impaired', 'title', 'series', 'year', 'season']
2. ['episode', 'title', 'series', 'year', 'season', 'hearing_impaired']

They both have a score of 331 and then the first one is selected by default.

The question is now: why does the release_group does not match for the second one... Can you try using the version 0.7.2.1 in dev branch? I've added some debug logging that could be helpful.

Thanks!

**Comment by tekert** [comment]
Here are the logs of the dev branch doing the same exact steps, had to copy the master db file to make the test quicker.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/2972892/bazarr.log)

**Comment by morpheus65535** [comment]
@tekert Thanks I don't see what's the problem but I'll refer to the expert ;-)

@pannal You have an idea why result number 2 doesn't match on release_group?

**Comment by morpheus65535** [comment]
@tekert BTW you can go from master to dev and the opposite without any issue keeping the same bazarr.db.

**Comment by pannal** [comment]
This is essentially a "can't fix". OpenSubtitles doesn't provide the alternative release names that you can see on their site for a subtitle to the API. We simply can't see it.

**Comment by morpheus65535** [comment]
Blacklisting is on the to-do list.
