### ISSUE TITLE
Can not connect to Sonarr/Radarr with correct settings

### ISSUE THREAD

**Issue by thibmaek** [morpheus65535/bazarr#352]
**Describe the bug**
Connecting with the Sonarr and Radarr API is impossible. Connection settings seem OK, have read some similar issues on this repo already.

**Expected behavior**
Bazarr can connect to Radarr/Sonarr

**Software (please complete the following information):**
 - Bazarr: 0.7.2 (linuxserver/bazarr:latest)
 - Radarr version v0.2.0.1293 (linuxserver/radarr:latest)
 - Sonarr version [e.g. v 2.0.0.0001] (linuxserver/sonarr:latest)
 - OS: Debian 9 with Docker (latest)

**Additional context**
Attached docker container config, compose file, error log.
URL http://host.local:7878/api/movie?apiKey=xxxxx returns valid and expected JSON.
API keys are 100% correct.

```plaintext
Traceback (most recent call last):
 File "/app/bazarr/bazarr/get_movies.py", line 31, in update_movies
  r = requests.get(url_radarr_api_movies, timeout=15, verify=False)
 File "/app/bazarr/bazarr/../libs/requests/api.py", line 75, in get
  return request(\get\, url, params=params, **kwargs)
 File "/app/bazarr/bazarr/../libs/requests/api.py", line 60, in request
  return session.request(method=method, url=url, **kwargs)
 File "/app/bazarr/bazarr/../libs/requests/sessions.py", line 524, in request
  resp = self.send(prep, **send_kwargs)
 File "/app/bazarr/bazarr/../libs/requests/sessions.py", line 637, in send
  r = adapter.send(request, **kwargs)
 File "/app/bazarr/bazarr/../libs/requests/adapters.py", line 516, in send
  raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host=\192.168.64.7\, port=7878): Max retries exceeded with url: /api/movie?apikey=xxxxxxxxxxx(Caused by NewConnectionError(\: Failed to establish a new connection: [Errno 111] Connection refused\,))
```

```yaml
# docker-compose.htpc.yaml
version: '2'

services:
  sonarr:
    image: linuxserver/sonarr
    hostname: host-sonarr
    volumes:
      - sonarr_config:/config
      - ./tv:/tv
      - ./downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8989:8989
    env_file: .env
    restart: unless-stopped
    mem_limit: 4096m

  radarr:
    image: linuxserver/radarr
    hostname: host-radarr
    volumes:
      - radarr_config:/config
      - ./movies:/movies
      - ./downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 7878:7878
    env_file: .env
    restart: unless-stopped
    mem_limit: 4096m

  bazarr:
    image: linuxserver/bazarr
    hostname: host-bazarr
    volumes:
      - bazarr_config:/config
      - ./movies:/movies
      - ./tv:/tv
    ports:
      - 6767:6767
    mem_limit: 4096m
    restart: unless-stopped

volumes:
  sonarr_config:
  radarr_config:
  bazarr_config:
```

![image](https://user-images.githubusercontent.com/6213695/54477660-027b0400-480a-11e9-967d-93d97abcf0c4.png)

**Comment by thibmaek** [comment]
Nevermind, turns out the previous IP addresses were being cached by bazarr.
I restarted using the UI (docker-compose restart did not work) and now I get results!

**Comment by morpheus65535** [comment]
That’s strange but if it works, that’s a good news! ;-)

**Comment by DennisYildirim** [comment]
Well I just restarted using the UI aswell but that did not help. It simply won't let me connect Bazarr to either radarr or sonarr..

**Comment by morpheus65535** [comment]
> Well I just restarted using the UI aswell but that did not help. It simply won't let me connect Bazarr to either radarr or sonarr..

From your other post, it seems more like a Docker network configuration issue to me.
