### ISSUE TITLE
Bazaar doesn't recognize embedded subtitles in .mp4 files

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#353]
**Describe the bug**
In some files, Bazaar doesn't recognize embedded subtitles.

**To Reproduce**
1. Add the TV Series "Mind Field" in Sonarr
2. Download the full S03 (magnet:?xt=urn:btih:25a342ad2e5e646c6fb460d26c27d204a375dc8f&dn=Mind.Field.S03.1080p.WEB-DL.x264-ULT)
3. Wait until download completes
4. Every downloaded chapter has 10 embedded subtitles, including English and Spanish
5. Configure Bazarr with English and Spanish subtitles
6. Bazaar doesn't recognize all embedded subtitles. See the screenshot.
NOTE: I did tests with file Mind.Field.S03E05.Should.I.Die.1080p.WEB-DL.x264-ULT.mp4

**Expected behavior**
Bazaar should recognize all embedded subtitles to avoid downloading more subtitles. In this case the subtitles are not available in the providers.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/10577978/54634338-4d06b580-4a82-11e9-946e-b71cc44e5654.png)

**Software (please complete the following information):**
 - Bazarr: 0.7.2.1
 - Sonarr version  2.0.0.5301
 - OS: Linux

**Comment by morpheus65535** [comment]
Did you enable "use embedded subtitles" in settings-->subliminal? If not, you need to run a full scan for series to index embedded subtitles.

**Comment by ngosang** [comment]
> Did you enable "use embedded subtitles" in settings-->subliminal?

Yes, I did

I found the problem... The file extension is .mp4, no .mkv.
Why you only support .mkv? I think .mp4 and .avi extensions are also common and supported by Sonarr.

```
DEBUG (list_subtitles:30) - BAZARR started subtitles indexing for this file: /media/SEA3TB/TV_EN/Mind Field/Season 03/Mind.Field.S03E03.The.Stilwell.Brain.1080p.WEB-DL.x264-ULT.mp4
DEBUG (list_subtitles:53) - BAZARR This file isn't an .mkv file.
```

**Comment by morpheus65535** [comment]
Yes but we rely on the enzyme library to detect embedded subtitles and this library only support EBML marking language used in mkv container.

**Comment by ngosang** [comment]
@morpheus65535 Some alternatives:
Several formats, maintained: https://github.com/vstinner/hachoir
https://hachoir.readthedocs.io/en/latest/metadata.html#
https://github.com/vstinner/hachoir/blob/master/hachoir/metadata/video.py

Only mp4, not tested => https://github.com/billnapier/mp4file/blob/master/src/example.py

**Comment by morpheus65535** [comment]
Hachoir is not supported anymore on Python 2.x. I'll take a look at mp4file. Thanks!
