### ISSUE TITLE
addic7ed is not working

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#355]
**Describe the bug**
addic7ed is not working for me anymore. It worked fine several weeks ago.

**To Reproduce**
1. I configure addic7ed with my user and pass. Credentials are right, I can login in the website.
2. I see this traces in DEBUG => #354

**Expected behavior**
To work

**Software (please complete the following information):**
    Bazarr: 0.7.2.1
    Sonarr version 2.0.0.5301
    OS: Linux

**Comment by morpheus65535** [comment]
Addic7ed added a reCaptcha to login and that broke our provider (as those of any other subtitles downloader available). There's nothing we can do until they release an API and we develop a new provider to use it.
