### ISSUE TITLE
Bazarr and HAProxy returns HTTP_REFERER error

### ISSUE THREAD

**Issue by bserrao** [morpheus65535/bazarr#357]
Hello, 
I'm having trouble running Bazarr behind HAProxy. Anyone here using bazarr and haproxy?
Radarr, Sonarr and other web apps are running fine using the same haproxy setup.

Some options like save config, search for subtitles, ... , return this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/bazarr/bazarr/../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/bazarr/bazarr/main.py", line 136, in wrapper
    return func(*a, **ka)
  File "/usr/local/lib/bazarr/bazarr/main.py", line 1793, in manual_search_movie_json
    ref = request.environ['HTTP_REFERER']
KeyError: 'HTTP_REFERER'
```
Anyone knows how to solve this?
Thanks,

**Comment by morpheus65535** [comment]
Bazarr rely on HTTP_REFERER header. Your proxy need to forward this header to Bazarr and not intercept it.

**Comment by bserrao** [comment]
I managed to forward the Referer header with this settings on Haproxy:
`option forwardfor header Referer`
or
 `http-request set-header Referer $[src]`
And now i can save the config changes, search subtitles, ... but when saving settings i'm getting this error:

```
Error: 404 Not Found
Sorry, the requested URL 'http://bazarr.reguila.online/%3A%3Affff%3Ax.xxx.xx.xxx?saved=true' caused an error:

Not found: '/::ffff:x.xxx.xx.xxx'
```
where the 'x' represents my IPv4 address.
Bazarr log shows this:
(7ff1338cb600) :  INFO (main:1441) - BAZARR Settings saved succesfully.
and setting are indeed saved.

Any clue?

**Comment by morpheus65535** [comment]
Sorry but no clue. I've never work with HAproxy.

**Comment by bserrao** [comment]
Already solved it after reviewing all my haproxy configs :) Thanks for pointing me in the right direction.

Here goes the solution as it might help others...There's no need to "force" the Referer header as i've done before. 
In my config i had this (because of ssl security...):

`http-response set-header Referrer-Policy no-referrer`

I've just changed this to:

`http-response set-header Referrer-Policy no-referrer-when-downgrade`

Cheers

**Comment by morpheus65535** [comment]
Thanks for sharing your solution!
