### ISSUE TITLE
Sync with Radarr fails

### ISSUE THREAD

**Issue by petwri** [morpheus65535/bazarr#358]
Syncing with Radarr seems to fail, logging gives me the error message

```
Traceback (most recent call last):
 File "/home/main/.bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/home/main/.bazarr/bazarr/get_movies.py", line 87, in update_movies
  resolution = movie[\movieFile\][\quality\][\quality\][\resolution\].lstrip(\r\).lower()
KeyError: \resolution\
```

**Software:**
 - Bazarr 0.7.2.1
 - Radarr version 0.2.0.1067
 - OS Linux-4.12.14-041214-generic-x86_64-with-Ubuntu-16.04-xenial
 - Python 2.7.12

**Comment by morpheus65535** [comment]
Can you try the dev branch? I've made a small fix and I would like to know if you are now able to get movies from radarr. Thanks!

**Comment by petwri** [comment]
Seems to work with the fix.
