### ISSUE TITLE
Option to not append language to subtitle filename

### ISSUE THREAD

**Issue by peskdale** [morpheus65535/bazarr#36]
Bazarr appends the language of the subtitle file into it's filename -  e.g. `sometitle.en.srt` - making it easy to organise multiple external subtitle tracks for the same video.

However, some DLNA servers and players only serve external subtitles if they have _exactly_ the same filename. Thus, subtitle files which have the language appended to them do not get served by these devices.

For users who are only interested in one language of subtitle for a video, it would nice to have an option not to append the language in the filename, in order to make them compatible with a wider number of players.

Alternatively, implementation of #21 would probably solve this use-case equally well.

**Comment by morpheus65535** [comment]
I'm going to take a look at it. Should be possible without to much effort. Would you prefer a global settings or a per series settings?

**Comment by peskdale** [comment]
Global would be better - since this is solving a player-side issue, per-series would be redundant for anyone who needs to use it.

**Comment by morpheus65535** [comment]
Ok. I’ll look at it after getting kids to school.

**Comment by morpheus65535** [comment]
I've think about it a lot and I can't do it. If I don't put the language in subtitles filename, I got no way of detecting which language it is when I'll be indexing it later. If I can't tell which language it is, I can't decide if I have to download a subtitles for a desired language.

I think we'll have to go with #21 but I don't know when I'm going to implement this. I have to find a way of doing it without relying on external program...

**Comment by morpheus65535** [comment]
I'm going to take a look at [langdetect ](https://github.com/Mimino666/langdetect) python module. Maybe I can fall back to this in case filename doesn't contain the language code.

**Comment by morpheus65535** [comment]
You can try it with dev branch. Go to bottom of settings --> subliminal.

Give me your comments please.

**Comment by peskdale** [comment]
Will give it a try when I’m not at work - probably Friday.

Thanks for looking into this.

**Comment by peskdale** [comment]
After a few false starts due to a series having a language set as ' ', I've gotten it to work. Functionally, seems to work as expected - langdetect is produces a result, and the filenames are not suffixed.

However, I think the sample size of langdetect is too small. With all the timing information included in an srt file, the first 5 lines from the file is not enough if the opening sentence is only one or two words longs.

For Doctor Who, here's what I ended up with:
![image](https://user-images.githubusercontent.com/5855217/34872566-44332a76-f789-11e7-8316-17ac0f4fc43c.png)

10x02 - Smile:
```
1
00:00:00,155 --> 00:00:01,404
- So...
- So...

```

10x03 - Thin Ice: (this one seems to be more of an anomaly, though increased sample size would still help)
```
1
00:00:14,040 --> 00:00:16,080
Ok. I have questions.

2
```

10x05 - Oxygen:
```
1
00:00:02,000 --> 00:00:03,360
Space...

2
```

10x11 - World Enough and Time:
```
1
00:00:26,160 --> 00:00:27,440
No.

2
```

I imagine 5 lines of actual dialogue would be better. This could probably be done with regex by taking the first 5 lines that start with a letter (thus ignoring blank lines, and lines with enumeration and timings).

**Comment by peskdale** [comment]
After some further thought, simply extending the xrange to 20 lines is enough to get the desired result (this guarantees at least 5 of the lines have dialogue). I altered the script on my server to test this with the above episodes, and it seems to work well.

If you wanted to be more thorough, and eliminate the numerical data, this code works:
```python
text = []
while len(text) < 4:
    line = next(f)
    if line[0].isalpha():
        text.append(line)
```

**Comment by morpheus65535** [comment]
I was looking into isalpha as we speak. I don't think neither that excluding useless line would worth the computing required to do it. I'll extend to 20 lines for now.

I still need to figure the decoding part because I'm getting in trouble if I try to read an UTF8 subtitles file without it.

Got an idea?

**Comment by morpheus65535** [comment]
I've used chardet module and it seems to do a pretty good job. You can try it?

**Comment by peskdale** [comment]
I wasn't encountering any issues to begin with UTF-8 subs (as far as I know), so I'm not entirely sure that my testing will be useful in that regard.

Code errors spotted:
- xrange count needs increasing on line 38 (`def list_subtitles`)
- Line 74 needs to be replaced by the new conversion method (`def store_subtitles`)

I've tested the current dev branch with the above errors fixed, and it seems to be performing as expected for me.

**Comment by morpheus65535** [comment]
You're right for those errors. I've removed the list_subtitles function that wasn't used anymore and only created confusion. I updated the store_subtitles with everything required. Should be working now.

**Comment by morpheus65535** [comment]
Have you had a chance to test it?

**Comment by morpheus65535** [comment]
I didn't get any trouble with this. I'm merging to master.

**Comment by peskdale** [comment]
Sorry for the lack of response... for some reason I'm not getting email notifications for all your messages. This is working fine for me too.
