### ISSUE TITLE
Minor bug in execution frecuency

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#360]
**Describe the bug**
In System / Tasks, I can't see the execution frequency for "Update all episodes subtitles from disk". At means nothing for me..

**Screenshots**
![imagen](https://user-images.githubusercontent.com/10577978/54865991-ec6fc500-4d6e-11e9-89c3-0ab832de66d3.png)

**Comment by morpheus65535** [comment]
What is the value of `Full sync frequency` in Settings-->Sonarr?

**Comment by ngosang** [comment]
![imagen](https://user-images.githubusercontent.com/10577978/54866673-58562b80-4d77-11e9-8d3d-9c9855ffcb14.png)

**Comment by halali** [comment]
Fix pushed to development branch
