### ISSUE TITLE
Renamed file is not administrated in bazarr?

### ISSUE THREAD

**Issue by pven** [morpheus65535/bazarr#361]
I just had to rename some files on disk. Sonarr is picking this up quite fast.  But Bazarr keeps referring to the old filenames. How can I tell Bazarr I renamed some files?

I am using Bazarr Ver. 0.7.2.1

**Comment by pven** [comment]
After some hours it fixed itself.

**Comment by morpheus65535** [comment]
It shouldn't take more than 5 minutes to have change made in Sonarr updated in Bazarr.
