### ISSUE TITLE
Unable to save subtitle after chmod has been included

### ISSUE THREAD

**Issue by Woutch** [morpheus65535/bazarr#362]
**Describe the bug**
Whenever Bazarr tries to dowload a subtitle (auto or manually) it finds one but does not save it. 
This started when the CHMOD option has been added.

The problem here is I have a mounted smb share in linux with fixed user and permissions:
fstab: 
/mnt/downloads cifs file_mode=0777,dir_mode=0777,username=xxxx,password=xxxxxx

**To Reproduce**
Donwload a subtitle

**Expected behavior**
subtitle gets saved in to movie folder

**Software
 - Bazarr: v 0.7.2
 - OS: Debian 9

**Additional context**
The problem here is that the chmod commands errors not able to change the permissions.
I am able to fix this by commenting out the chmod line in the sources.
get_subtitles.py lines 147 and 358

But these get reset every restart by git ;-)

Sonar has the option to enable or disable these chmods. 
Is it possible to make this optional?

Thanks!!!!

**ERROR**
 File "/home/services/bazarr/bazarr/bazarr/get_subtitle.py", line 176, in download_subtitle
  path_decoder=force_unicode
 File "/home/services/bazarr/bazarr/bazarr/../libs/subliminal_patch/core.py", line 841, in save_subtitles
  os.chmod(subtitle_path, chmod)
OSError: [Errno 1] Operation not permitted: \/mnt/media/Series/****/Season ****/****.en.srt\

**Comment by halali** [comment]
Settings for enable chmod was added in a1a1ee68f1f7af63a697c5236178c9fc51ca21cd to develepment branch...

Please give it try and let me know.

**Comment by Woutch** [comment]
just gave it a test run. Works perfectly.

Disabled I could download sutitles as before the latest versions.
Enabled it could not execute chmod as in the latest version.

Thanks!

**Comment by halali** [comment]
Thanks, so i close it
