### ISSUE TITLE
Error: 500 Internal Server Error @ System page

### ISSUE THREAD

**Issue by ShadXo** [morpheus65535/bazarr#363]
Error: 500 Internal Server Error
Sorry, the requested URL 'http://192.168.3.10:6767/system' caused an error:

Internal Server Error
Exception:
SyntaxError('unexpected EOF while parsing', ('<unknown>', 0, 0, ''))
Traceback:
Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 136, in wrapper
    return func(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 1568, in system
    releases = ast.literal_eval(f.read())
  File "/usr/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

Bottom of other pages say: Bazarr Ver. 0.7.2.1

Im using the linuxserver-bazarr image. I remember it always used to work, it stopped working after updates long time ago and didn't say anything hoping It would fix itself :).

Did a new pull, also cleared the container to start with new image.

**Comment by morpheus65535** [comment]
Can you try to delete the `releases.txt` file in your Bazarr config directory? After deletion, restart Bazarr and wait at least 6 hours and try again to access System page.

**Comment by ShadXo** [comment]
Oke, just did that. (The file is empty)

**Comment by TheFes** [comment]
I had the same (but on all pages, not only system), removing the releases.txt and restarting solved it. 
Waiting 6 hours was not needed.

**Comment by morpheus65535** [comment]
I've added a fix for that in dev branch. We'll catch if there's problem reading the file and log the issue. Releases tab will be empty but you'll have access to it.
