### ISSUE TITLE
Error while running Sonarr V3

### ISSUE THREAD

**Issue by halali** [morpheus65535/bazarr#37]
Hi

Sonarr Version: 2.0.0.4991 (Phantom branch)

error
```Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-01-11 14:45:18 CET)" raised an exception
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "D:\apps\bazarr\get_series.py", line 13, in update_series
    get_profile_list()
  File "D:\apps\bazarr\get_series.py", line 82, in get_profile_list
    profiles_list.append([profile['id'], profile['language'].capitalize()])
KeyError: 'language'

**Comment by morpheus65535** [comment]
You can give me the JSON returned from the API?
http://**server**:8989/api/profile?apikey=**key**

**Comment by halali** [comment]
'''
[
  {
    "name": "Any",
    "cutoff": {
      "id": 1,
      "name": "SDTV"
    },
    "items": [
      {
        "quality": {
          "id": 0,
          "name": "Unknown"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 1,
          "name": "SDTV"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 8,
          "name": "WEBDL-480p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 2,
          "name": "DVD"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 4,
          "name": "HDTV-720p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 9,
          "name": "HDTV-1080p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 10,
          "name": "Raw-HD"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 5,
          "name": "WEBDL-720p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 6,
          "name": "Bluray-720p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 3,
          "name": "WEBDL-1080p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 7,
          "name": "Bluray-1080p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 16,
          "name": "HDTV-2160p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 18,
          "name": "WEBDL-2160p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 19,
          "name": "Bluray-2160p"
        },
        "allowed": false
      }
    ],
    "id": 1
  },
  {
    "name": "SD",
    "cutoff": {
      "id": 1,
      "name": "SDTV"
    },
    "items": [
      {
        "quality": {
          "id": 0,
          "name": "Unknown"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 1,
          "name": "SDTV"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 8,
          "name": "WEBDL-480p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 2,
          "name": "DVD"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 4,
          "name": "HDTV-720p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 9,
          "name": "HDTV-1080p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 10,
          "name": "Raw-HD"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 5,
          "name": "WEBDL-720p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 6,
          "name": "Bluray-720p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 3,
          "name": "WEBDL-1080p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 7,
          "name": "Bluray-1080p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 16,
          "name": "HDTV-2160p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 18,
          "name": "WEBDL-2160p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 19,
          "name": "Bluray-2160p"
        },
        "allowed": false
      }
    ],
    "id": 2
  },
  {
    "name": "HD-720p",
    "cutoff": {
      "id": 4,
      "name": "HDTV-720p"
    },
    "items": [
      {
        "quality": {
          "id": 0,
          "name": "Unknown"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 1,
          "name": "SDTV"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 8,
          "name": "WEBDL-480p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 2,
          "name": "DVD"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 9,
          "name": "HDTV-1080p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 10,
          "name": "Raw-HD"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 6,
          "name": "Bluray-720p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 5,
          "name": "WEBDL-720p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 4,
          "name": "HDTV-720p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 3,
          "name": "WEBDL-1080p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 7,
          "name": "Bluray-1080p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 16,
          "name": "HDTV-2160p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 18,
          "name": "WEBDL-2160p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 19,
          "name": "Bluray-2160p"
        },
        "allowed": false
      }
    ],
    "id": 3
  },
  {
    "name": "HD-1080p",
    "cutoff": {
      "id": 9,
      "name": "HDTV-1080p"
    },
    "items": [
      {
        "quality": {
          "id": 0,
          "name": "Unknown"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 1,
          "name": "SDTV"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 8,
          "name": "WEBDL-480p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 2,
          "name": "DVD"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 4,
          "name": "HDTV-720p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 9,
          "name": "HDTV-1080p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 10,
          "name": "Raw-HD"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 5,
          "name": "WEBDL-720p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 6,
          "name": "Bluray-720p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 3,
          "name": "WEBDL-1080p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 7,
          "name": "Bluray-1080p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 16,
          "name": "HDTV-2160p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 18,
          "name": "WEBDL-2160p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 19,
          "name": "Bluray-2160p"
        },
        "allowed": false
      }
    ],
    "id": 4
  },
  {
    "name": "Ultra-HD",
    "cutoff": {
      "id": 16,
      "name": "HDTV-2160p"
    },
    "items": [
      {
        "quality": {
          "id": 0,
          "name": "Unknown"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 1,
          "name": "SDTV"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 8,
          "name": "WEBDL-480p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 2,
          "name": "DVD"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 4,
          "name": "HDTV-720p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 9,
          "name": "HDTV-1080p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 10,
          "name": "Raw-HD"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 5,
          "name": "WEBDL-720p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 6,
          "name": "Bluray-720p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 3,
          "name": "WEBDL-1080p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 7,
          "name": "Bluray-1080p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 16,
          "name": "HDTV-2160p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 18,
          "name": "WEBDL-2160p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 19,
          "name": "Bluray-2160p"
        },
        "allowed": true
      }
    ],
    "id": 5
  },
  {
    "name": "HD - 720p/1080p",
    "cutoff": {
      "id": 9,
      "name": "HDTV-1080p"
    },
    "items": [
      {
        "quality": {
          "id": 0,
          "name": "Unknown"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 1,
          "name": "SDTV"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 8,
          "name": "WEBDL-480p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 2,
          "name": "DVD"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 4,
          "name": "HDTV-720p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 9,
          "name": "HDTV-1080p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 10,
          "name": "Raw-HD"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 5,
          "name": "WEBDL-720p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 6,
          "name": "Bluray-720p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 3,
          "name": "WEBDL-1080p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 7,
          "name": "Bluray-1080p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 16,
          "name": "HDTV-2160p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 18,
          "name": "WEBDL-2160p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 19,
          "name": "Bluray-2160p"
        },
        "allowed": false
      }
    ],
    "id": 6
  },
  {
    "name": "SD / 720P",
    "cutoff": {
      "id": 4,
      "name": "HDTV-720p"
    },
    "items": [
      {
        "quality": {
          "id": 0,
          "name": "Unknown"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 2,
          "name": "DVD"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 9,
          "name": "HDTV-1080p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 10,
          "name": "Raw-HD"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 8,
          "name": "WEBDL-480p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 1,
          "name": "SDTV"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 5,
          "name": "WEBDL-720p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 6,
          "name": "Bluray-720p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 4,
          "name": "HDTV-720p"
        },
        "allowed": true
      },
      {
        "quality": {
          "id": 3,
          "name": "WEBDL-1080p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 7,
          "name": "Bluray-1080p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 16,
          "name": "HDTV-2160p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 18,
          "name": "WEBDL-2160p"
        },
        "allowed": false
      },
      {
        "quality": {
          "id": 19,
          "name": "Bluray-2160p"
        },
        "allowed": false
      }
    ],
    "id": 7
  }
]

**Comment by halali** [comment]
Sonarr v3 have separate profiles for languages.

**Comment by morpheus65535** [comment]
I don't see any information relative to language in those profiles. You mean there is another API endpoint that will return this information?

**Comment by morpheus65535** [comment]
You can give me the JSON returned from the API?
http://server:8989/api/series?apikey=key

**Comment by halali** [comment]
[
  {
    "title": "Marvel's Agents of S.H.I.E.L.D.",
    "alternateTitles": [
      {
        "title": "Marvel Agents of SHIELD",
        "seasonNumber": -1
      },
      {
        "title": "Agents of SHIELD",
        "seasonNumber": -1
      }
    ],
    "sortTitle": "marvels agents s h i e l d",
    "seasonCount": 5,
    "totalEpisodeCount": 113,
    "episodeCount": 94,
    "episodeFileCount": 94,
    "sizeOnDisk": 53160269436,
    "status": "continuing",
    "overview": "The missions of the Strategic Homeland Intervention Enforcement and Logistics Division.",
    "nextAiring": "2018-01-13T02:00:00Z",
    "previousAiring": "2018-01-06T02:00:00Z",
    "network": "ABC (US)",
    "airTime": "21:00",
    "images": [
      {
        "coverType": "fanart",
        "url": "/MediaCover/1/fanart.jpg?lastWrite=636485107070161935"
      },
      {
        "coverType": "banner",
        "url": "/MediaCover/1/banner.jpg?lastWrite=636477732889818145"
      },
      {
        "coverType": "poster",
        "url": "/MediaCover/1/poster.jpg?lastWrite=636464720357103370"
      }
    ],
    "seasons": [
      {
        "seasonNumber": 0,
        "monitored": false,
        "statistics": {
          "episodeFileCount": 0,
          "episodeCount": 0,
          "totalEpisodeCount": 13,
          "sizeOnDisk": 0,
          "percentOfEpisodes": 0.0
        }
      },
      {
        "seasonNumber": 1,
        "monitored": false,
        "statistics": {
          "previousAiring": "2014-05-14T01:00:00Z",
          "episodeFileCount": 22,
          "episodeCount": 22,
          "totalEpisodeCount": 22,
          "sizeOnDisk": 8507636618,
          "percentOfEpisodes": 100.0
        }
      },
      {
        "seasonNumber": 2,
        "monitored": false,
        "statistics": {
          "previousAiring": "2015-05-13T01:45:00Z",
          "episodeFileCount": 22,
          "episodeCount": 22,
          "totalEpisodeCount": 22,
          "sizeOnDisk": 8503094438,
          "percentOfEpisodes": 100.0
        }
      },
      {
        "seasonNumber": 3,
        "monitored": false,
        "statistics": {
          "previousAiring": "2016-05-18T01:45:00Z",
          "episodeFileCount": 22,
          "episodeCount": 22,
          "totalEpisodeCount": 22,
          "sizeOnDisk": 8663965166,
          "percentOfEpisodes": 100.0
        }
      },
      {
        "seasonNumber": 4,
        "monitored": true,
        "statistics": {
          "previousAiring": "2017-05-17T01:00:00Z",
          "episodeFileCount": 22,
          "episodeCount": 22,
          "totalEpisodeCount": 22,
          "sizeOnDisk": 22196197376,
          "percentOfEpisodes": 100.0
        }
      },
      {
        "seasonNumber": 5,
        "monitored": true,
        "statistics": {
          "nextAiring": "2018-01-13T02:00:00Z",
          "previousAiring": "2018-01-06T02:00:00Z",
          "episodeFileCount": 6,
          "episodeCount": 6,
          "totalEpisodeCount": 12,
          "sizeOnDisk": 5289375838,
          "percentOfEpisodes": 100.0
        }
      }
    ],
    "year": 2013,
    "path": "E:\\Serial\\Agents of Shield",
    "profileId": 7,
    "languageProfileId": 1,
    "seasonFolder": true,
    "monitored": true,
    "useSceneNumbering": false,
    "runtime": 45,
    "tvdbId": 263365,
    "tvRageId": 32656,
    "tvMazeId": 31,
    "firstAired": "2013-09-23T22:00:00Z",
    "lastInfoSync": "2018-01-11T11:24:39.4843738Z",
    "seriesType": "standard",
    "cleanTitle": "marvelsagentsshield",
    "imdbId": "tt2364582",
    "titleSlug": "marvels-agents-of-s-h-i-e-l-d",
    "certification": "TV-PG",
    "genres": [
      "Action",
      "Drama",
      "Science-Fiction",
      "Suspense"
    ],
    "tags": [],
    "added": "2016-04-01T11:32:27.5254459Z",
    "ratings": {
      "votes": 267,
      "value": 8.5
    },
    "qualityProfileId": 7,
    "id": 1
  },

**Comment by halali** [comment]
![image](https://user-images.githubusercontent.com/17801420/34834661-d9e9b8ba-f6f2-11e7-8337-4b6f8e1cc46d.png)

**Comment by morpheus65535** [comment]
Ok so there is now a "languageProfileId" field returned by the API. I'm going to try to find how to retrieve those language profiles trough the API.

**Comment by morpheus65535** [comment]
Ok, I got it: http://**server**:8989/api/v3/languageprofile?apikey=**key**

**Comment by morpheus65535** [comment]
I've ask to Sonarr dev if they are going to keep the v3 in the API url in final release of v3: https://forums.sonarr.tv/t/v3-api-path-modifed/17327

**Comment by morpheus65535** [comment]
Markus confirmed that the v3 is going to stay. I'll work on something in dev branch and comeback to you.

**Comment by morpheus65535** [comment]
You can try it on development branch. Give me your feedback please.

**Comment by halali** [comment]
ok, now it load tv shows and wanted language and give this error
```
Job "Add new episodes from Sonarr (trigger: interval[0:01:00], next run at: 2018-01-12 06:51:19 CET)" raised an exception
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "D:\apps\bazarr\get_episodes.py", line 143, in add_new_episodes
    new_scan_subtitles()
  File "D:\apps\bazarr\list_subtitles.py", line 149, in new_scan_subtitles
    store_subtitles(path_replace(episode[0]))
  File "D:\apps\bazarr\list_subtitles.py", line 72, in store_subtitles
    detected_language = langdetect.detect(text)
  File "C:\Users\Halali\AppData\Roaming\Python\Python27\site-packages\langdetect\detector_factory.py", line 130, in detect
    return detector.detect()
  File "C:\Users\Halali\AppData\Roaming\Python\Python27\site-packages\langdetect\detector.py", line 136, in detect
    probabilities = self.get_probabilities()
  File "C:\Users\Halali\AppData\Roaming\Python\Python27\site-packages\langdetect\detector.py", line 143, in get_probabilities
    self._detect_block()
  File "C:\Users\Halali\AppData\Roaming\Python\Python27\site-packages\langdetect\detector.py", line 150, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
LangDetectException: No features in text.
```

And there is no existing subtitles

**Comment by halali** [comment]
langdetect problem is maybe i have subtitles taged like eng no en

becouse now emby is managing my subtitles

**Comment by morpheus65535** [comment]
You can try again? I have increased number of line used by langdetect from 5 to 20.

I'm going to look at your other error later tonight but it seems unable to load a thumbs or fanart from Sonarr. I'm going to add some more exception handling on that.

**Comment by halali** [comment]
New error

```
Job "Add new episodes from Sonarr (trigger: interval[0:01:00], next run at: 2018-01-13 07:59:51 CET)" raised an exception
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "D:\apps\bazarr\get_episodes.py", line 143, in add_new_episodes
    new_scan_subtitles()
  File "D:\apps\bazarr\list_subtitles.py", line 152, in new_scan_subtitles
    store_subtitles(path_replace(episode[0]))
  File "D:\apps\bazarr\list_subtitles.py", line 73, in store_subtitles
    text = [next(f) for x in xrange(20)]
StopIteration

**Comment by morpheus65535** [comment]
I've made a change that should take care of your StopIteration error. Run task "Update all episodes from Sonarr" and report back please.

**Comment by halali** [comment]
```
Job "Add new episodes from Sonarr (trigger: interval[0:01:00], next run at: 2018-01-13 21:07:05 CET)" raised an exception
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "D:\apps\bazarr\get_episodes.py", line 143, in add_new_episodes
    new_scan_subtitles()
  File "D:\apps\bazarr\list_subtitles.py", line 120, in new_scan_subtitles
    store_subtitles(path_replace(episode[0]))
  File "D:\apps\bazarr\list_subtitles.py", line 42, in store_subtitles
    text = text.decode(encoding)
  File "C:\Python27\lib\encodings\cp1254.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 182: character maps to <undefined>

**Comment by morpheus65535** [comment]
Thanks for your time taken to debug this. Unfortunately, I cannot test everything with my media library... :-/

If you can give it a try, I added some logging so we're going to know which subtitles file is problematic.

**Comment by halali** [comment]
for some subtitles give this error
```
Error trying to detect character encoding for this subtitles file: \\server\Serial\Gotham\Season 4\Gotham - S04E03 - A Dark Knight- They Who Hide Behind Masks HDTV-720p.DIMENSION.cze.srt
Traceback (most recent call last):
  File "D:\apps\bazarr\list_subtitles.py", line 43, in store_subtitles
    text = text.decode(encoding)
  File "C:\Python27\lib\encodings\cp1254.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9e in position 73: character maps to <undefined>
Error trying to detect character encoding for this subtitles file: \\server\Serial\Gotham\Season 4\Gotham - S04E08 - A Dark Knight- Stop Hitting Yourself HDTV-720p.AVS.cze.srt
Traceback (most recent call last):
  File "D:\apps\bazarr\list_subtitles.py", line 43, in store_subtitles
    text = text.decode(encoding)
  File "C:\Python27\lib\encodings\cp1254.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9e in position 69: character maps to <undefined>

**Comment by morpheus65535** [comment]
You can send me some of those file so I can unit test it?

**Comment by morpheus65535** [comment]
Your subtitles encoding were wrongly recognized as Windows-1254 by chardet (accuracy was only 45%). I've switched to UnicodeDammit which give much better result and detect your subtitles encoding as Windows-1252 (which is true). You can give it a try!

**Comment by halali** [comment]
Stll same

```
Error trying to detect character encoding for this subtitles file: \\server\Serial ukoncene\Stargate Atlantis\Season 3\Stargate Atlantis - S03E18 - Submersion SDTV.Sonarr.slo.srt
Traceback (most recent call last):
  File "D:\apps\bazarr\list_subtitles.py", line 43, in store_subtitles
    text = text.decode(encoding.original_encoding)
  File "C:\Python27\lib\encodings\cp1254.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 154: character maps to <undefined>

**Comment by morpheus65535** [comment]
I've added a warning to delete the subtitles that cannot be decoded. Nothing more I can do about it.
