### ISSUE TITLE
InsecureRequestWarning: Unverified HTTPS request is being made

### ISSUE THREAD

**Issue by iGino** [morpheus65535/bazarr#370]
This error appears repeatedly when running Bazarr from Terminal:

```
/Applications/bazarr/bazarr/../libs/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
```

Bazarr version: 0.7.2.1
Sonarr version: 2.0.0.5322
Radarr version: 0.2.0.1293
Operating system: Darwin-17.7.0-x86_64-i386-64bit [macOS High Sierra 10.13.6 (17G5019)]
Python version: 2.7.10
Bazarr config directory: /Applications/bazarr/data

I'm using nginx for Bazarr, Sonarr, and Radarr without issue.

**Comment by morpheus65535** [comment]
Start by updating your Python version, minimum supported version is 2.7.13.

You can take a look at this (first result of google search): https://stackoverflow.com/questions/27981545/suppress-insecurerequestwarning-unverified-https-request-is-being-made-in-pytho

**Comment by iGino** [comment]
Sorry, I do have the latest version of Python 2 (2.7.16), but I didn't launch the app using `python2` out of habit... same error with latest version, FYI.

In regards to the URL you provided, I did check around the internet first, however, all "solutions" were to ignore warnings with something like `python2 -W ignore bazarr.py` but that disables ALL warnings, right, even important ones?

**Comment by iGino** [comment]
FIXED with:

`export PYTHONWARNINGS="ignore:Unverified HTTPS request"`

**Comment by morpheus65535** [comment]
Thank you for reporting your fix. I hope it will help others.

**Comment by dimitrov-adrian** [comment]
I got same problem on docker with v0.7.5.1, setting `PYTHONWARNINGS="ignore:Unverified HTTPS request"` as @iGino mention seems to fix the warning
