### ISSUE TITLE
Bazarr subtitles crashing Plex

### ISSUE THREAD

**Issue by luizbird** [morpheus65535/bazarr#371]
**Describe the bug**
Hello. Every subtitle downloaded by Bazarr (no matter where from) makes Plex unable to run the video. Plex plays the movie for about 4 seconds than freezes and return the error "Conversion failed. The transcoder exited due to an error."

If I remove the subtitle, Plex works fine. If I manually download the subtitle, from the same source as Bazarr, everything goes fine.

I tried to reinstall Bazarr and also Plex but had no lucky.

Any idea how to fix it?

I'm running the latest Bazarr version in Docker, runing on OpenMediaVault environment.

Older subtitles downloaded by Bazarr (like 1 month ago) work fine too. only the new ones shows this problem.

**Comment by morpheus65535** [comment]
I'm running the same setup (LinuxServer Plex and Bazarr docker image on OMV) and have no problem.

Please check your Plex log to see what is the issue. Probably something related to permissions. You can set in settings the desired permissions for subtitles file created by Bazarr.

**Comment by luizbird** [comment]
I have no clue which number to set on permissions. Any advise?

**Comment by morpheus65535** [comment]
You can’t go wrong with 777. It’s equivalent to rwx/rwx/rwx.

**Comment by morpheus65535** [comment]
Can I close this one?

**Comment by morpheus65535** [comment]
Closing because no answer.

**Comment by luizbird** [comment]
Sorry for not getting back to you. Updating the permissions as you advised worked like a charm! Thank you.

**Comment by morpheus65535** [comment]
Thanks for the feedback!
