### ISSUE TITLE
How to update ?

### ISSUE THREAD

**Issue by Trefex** [morpheus65535/bazarr#372]
Hi,

I am on 0.6.9.1 and i see that in the release page there is 0.7.2.1.

However, nowhere can I find how to update to that new version.

I am running the docker image on Synology.

Thanks for any help

**Comment by morpheus65535** [comment]
If you are running inside Docker container, you need to pull the new image an recreate your container. I think there’s option to do both in one step in Synology UI but I don’t know where exactly.

LinuxServer do not let program update automatically inside a running container.

**Comment by Trefex** [comment]
Thanks it worked.

**Comment by dimitrov-adrian** [comment]
Well, there is no such option in Synology's UI. But you can do pull image, stop container, clear, and then start again, no need to remove and launch again.

**Comment by morpheus65535** [comment]
You can also use Portainer with have the "recreate" button and it can pull latest version of image before recreating the container.

In my case, I use Watchtower that do the job automatically.
