### ISSUE TITLE
Error during job executing

### ISSUE THREAD

**Issue by Trefex** [morpheus65535/bazarr#373]
Hi,

I see following error in log periodically as movie update runs.

```Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/bazarr/get_movies.py", line 154, in update_movies
  movies_to_update)
IntegrityError: UNIQUE constraint failed: table_movies.radarrId
```

I am running on latest version inside Docker container.

Any help where to start debug this?
Thanks

**Comment by morpheus65535** [comment]
You have reinstalled Radarr without starting from scratch in Bazarr. Bazarr keep track of Radarr movies ID it get from Radarr. If you reinstall Radarr, it will assign new ID to your movies (which cause duplicate ID to happens). Either you open you bazarr.db and delete everything in table_movies and table_history_movies or you delete your DB and start from scratch.

**Comment by Trefex** [comment]
Everytime I update radarr i have to re-start from scratch Bazarr?

**Comment by morpheus65535** [comment]
Update, no. But if you have duplicate ID it's because you have reinstalled Radarr from scratch or somehow lose you Radarr DB.

**Comment by Trefex** [comment]
Ok I drop the DB and now get many errors like this on restart.

```
Traceback (most recent call last):
 File "/app/bazarr/bazarr/list_subtitles.py", line 145, in store_subtitles_movie
  only_one=settings.general.getboolean(\single_language\))
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 637, in search_external_subtitles
  only_one=only_one))
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 607, in _search_external_subtitles
  language = Language.rebuild(list(languages)[0], forced=forced)
IndexError: list index out of range
```

Maybe it is only temporary?

**Comment by Trefex** [comment]
Actually it is not temporary.

No external subs can be indexed...

**Comment by halali** [comment]
What Branch are you using?

**Comment by morpheus65535** [comment]
Did you enable single language? Does your path mapping work for movies? Do you have warning alongside the movies path in main Movies page?

**Comment by Trefex** [comment]
I dropped everything and started from scratch.

Wizard is not possible to complete.

```Some fields are in error and you can't save settings until you have corrected them. Be sure to check in every tabs.```

**Comment by Trefex** [comment]
I use bazarr latest from linuxserver.io on empty config dir.

**Comment by morpheus65535** [comment]
Did you enable at least one provider and one enabled language?

I suggest you come on Discord for interactive debug with the support team.

**Comment by morpheus65535** [comment]
Can I close this one?

**Comment by Trefex** [comment]
Hi yes I started from scratch.

**Comment by morpheus65535** [comment]
Thanks

**Comment by IngoVals** [comment]
For anyone coming here from a google search. Notice that you seem have to remove `bazaar.db-wal` and `bazaar.db-shm` as well. When you empty the db tables.
