### ISSUE TITLE
This path doesn't seems to be valid

### ISSUE THREAD

**Issue by kazmur** [morpheus65535/bazarr#376]
I'm running Bazarr through Docker on my Mac Mini, but no matter how I try, I keep getting "This path doesn't seems to be valid" for my TV-shows. I also can't get any of my Radarr-movies to show up.

Bazarr:
<img width="930" alt="Skärmavbild 2019-04-03 kl  00 50 44" src="https://user-images.githubusercontent.com/21258336/55441417-1c0ea080-55ab-11e9-849e-3a9510d9b221.png">
<img width="930" alt="Skärmavbild 2019-04-03 kl  00 52 20" src="https://user-images.githubusercontent.com/21258336/55441440-30529d80-55ab-11e9-8525-00d8d32f0d1e.png">

Sonarr:
<img width="930" alt="Skärmavbild 2019-04-03 kl  00 51 34" src="https://user-images.githubusercontent.com/21258336/55441456-3cd6f600-55ab-11e9-9b48-fc55b9b4a9da.png">

Radarr:
<img width="930" alt="Skärmavbild 2019-04-03 kl  00 52 03" src="https://user-images.githubusercontent.com/21258336/55441470-482a2180-55ab-11e9-97dd-ba122a8712f2.png">

Docker/Terminal:
<img width="404" alt="Skärmavbild 2019-04-03 kl  00 52 58" src="https://user-images.githubusercontent.com/21258336/55441480-4fe9c600-55ab-11e9-9fba-3f72ec441143.png">

Software:
 - Bazarr: 0.7.2.1
 - Docker: 2.0.0.3 (31259)
 - Sonarr: 3.0.1.418
 - Radarr: 0.2.0.1293

I tried reading about path mapping in the wiki, but I'm just not making any sense of it, sorry.
Any ideas on how to solve this? I'm new to Docker/Terminal.

**Comment by morpheus65535** [comment]
Path mapping for series:
Sonarr: `/Users/HTPC/Downloads/Complete/TV`
Bazarr: `/tv`

Path for movies:
Radarr: `/Users/HTPC/Downloads/Complete/Film`
Bazarr: `/movies`

**Comment by morpheus65535** [comment]
Regarding movies, you need to wait 5 minutes to get the list of movies synced from Radarr.

**Comment by kazmur** [comment]
> Path mapping for series:
> Sonarr: `/Users/HTPC/Downloads/Complete/TV`
> Bazarr: `/tv`
> 
> Path for movies:
> Radarr: `/Users/HTPC/Downloads/Complete/Film`
> Bazarr: `/movies`

Thanks, I can't believe I didn't try that combo before :) Works great!

**Comment by kazmur** [comment]
> Regarding movies, you need to wait 5 minutes to get the list of movies synced from Radarr.

Unfortunately, the list is still blank. I've had Bazarr running for about 12 hours, and I also tried manually updating the movies list. The connection to Radarr is working fine according to the test in settings.
Any ideas?

**Comment by morpheus65535** [comment]
Please provide a debug lof regarding this synchronization issue and I'll look into it.

**Comment by kazmur** [comment]
> Please provide a debug lof regarding this synchronization issue and I'll look into it.

I cleared the log file and ran a movie update. 
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3038232/bazarr.log)

**Comment by morpheus65535** [comment]
It looks like Radarr isn'T returning a single movie...

Can you send me the JSON returned when you do a call to Radarr API: `http://10.x.x.x:7878/api/system/status?apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

**Comment by morpheus65535** [comment]
Oh we got the problem: Bazarr only index movies where a media file exist on disk.

**Comment by kazmur** [comment]
> Oh we got the problem: Bazarr only index movies where a media file exist on disk.

Oh, I didn't know that. I figured Bazarr picked up the monitored list from Radarr and presented it as is :) 
I always delete the movies in Radarr after they've been downloaded, to keep things clean.

**Comment by morpheus65535** [comment]
So in your case, « clean » will means « no subtitles ». As stated on Bazarr page, we rely on data provided by Radarr. We don’t scan disk for movies, only existing subtitles.

**Comment by kazmur** [comment]
> So in your case, « clean » will means « no subtitles ». As stated on Bazarr page, we rely on data provided by Radarr. We don’t scan disk for movies, only existing subtitles.

So basically, I should keep the movies in Radarr from now on?

**Comment by morpheus65535** [comment]
And probably reindex existing movies if you want subtitles for them.

**Comment by kazmur** [comment]
> And probably reindex existing movies if you want subtitles for them.

Will do! Thanks for your help. Now I can check of Bazarr on my usenet noob-list ;)

**Comment by morpheus65535** [comment]
Have fun!
