### ISSUE TITLE
Using opensubtitles again after 20 minutes, (disabled because: ServiceUnavailable)|

### ISSUE THREAD

**Issue by pven** [morpheus65535/bazarr#377]
Is it me, or is something wrong with opensubtitles? (I get this message a lot the last days.)

```
03/04/2019 10:01:33|INFO    |jobs                            |Using opensubtitles again after 20 minutes, (disabled because: ServiceUnavailable)|
```

When logging in to opensubtitels it looks ok to me.

I am using Bazarr Ver. 0.7.2.1

**Comment by morpheus65535** [comment]
The opensubtitles API is having downtime since 2 or 3 days. The website is working well but api.opensubtitles.org doesn't. Nothing wrong on your side.
