### ISSUE TITLE
Search for subtitles accesses the media files (and spinning up my disks)

### ISSUE THREAD

**Issue by gbougiakas** [morpheus65535/bazarr#378]
Hello all,

I have a radarr, sonarr, bazarr setup going on, on an Unraid server and up to yesterday I could not figure out why most of my hard drives in the array would not spin down (or spinning up all the time).
I have:

- Dynamix Cache plugin so filesystem structure / folder and file names are stored in RAM to avoid disk spin up
- Plugin that logs which files were accessed (cannot remember its name)
- Disabled "ignore subs with wrong fps" in Bazarr because I guessed that it will need to access the actual movie file in order to figure the fps.
- Disabled "check for embedded subs" for the same reason as above.

No matter the settings in Bazarr when search for subtitles is running, media files are accessed and disks spin up. One cannot change the interval of the search and the default is 3 hours. Having both English and a secondary (rare) language as wanted, this means that every 3 hour interval subtitle search will search for subtitles for tons of media and spin up most of my disks.

I know Bazarr uses subliminal for the actual subtitle search and download so if you think that this is a subliminal issue please let me know so I can open the ticket at subliminal's github.

I shut down Bazarr container last night, spun down all my disks, woke up this morning and all disks are still spun down.

Any feedback to have subtitle search that will not wake up my disks would be greatly appreciated!

Cheers.

**Comment by morpheus65535** [comment]
Can you try the dev branch? I've made a small change last night for those with use embedded subtitles disabled. I'm not sure it will fix your issue but at least we'll eliminate that cause.

**Comment by gbougiakas** [comment]
OK, I will try. Is the name of the dev tag/branch "dev" or "development"?

**Comment by morpheus65535** [comment]
Development but if you are running from source, you can simply switch in settings, force an update in system and restart.

**Comment by gbougiakas** [comment]
Ok thanks, will do that when I get home. If you don't mind explaining what you changed last night I would appreciate it.

**Comment by morpheus65535** [comment]
Bazarr was still indexing embedded subtitles but was taking them into account when calculating missing subtitles. Now, it doesn’t index it at all.

**Comment by gbougiakas** [comment]
Ok, it sounds promising. I will report back with my findings. Thanks!

**Comment by gbougiakas** [comment]
I think that this improved things a lot. It's not accessing mkv files if you don't check for embedded subs.

**Comment by Dr0bac** [comment]
How is this improved? It doesn't matter if bazarr access one mkv or all of them, hdd will spin up from sleep.

**Comment by morpheus65535** [comment]
@Dr0bac You understand that to perform a subtitles search, we need to get the properties of the media file to have the better match? That include having a hash of the file. I don't see how to get it without waking up the HDD...

**Comment by Dr0bac** [comment]
@morpheus65535 if i check setting "use scene name when avaliable" does bazarr then check properties of media file?

**Comment by morpheus65535** [comment]
At the moment, no. But you'll get less precise results.

**Comment by gbougiakas** [comment]
@Dr0bac well imagine having 1000 mkv files that require subtitles and these are spread across 10 disks in an Unraid array and all the disks are spun down.

Before @morpheus65535 fix Bazarr would read all 1000 mkv files resulting for all 10 disks to spin up.
Now it will read some (like 5% of those mkv files) resulting 1 or 2 disks to spin up.

Hence, it's better.

@morpheus65535 There are 2 things that I would like to figure out, or have an option to configure them. One is whether Bazarr abandons an mkv after a couple of days/months and does not search over and over again for subtitles.
Second I would like the option to set the intervals for all actions (ie search for missing subs runs every 3 hours, I would like to be able to configure that).

Thanks for the swift response.

Regards

**Comment by piratx** [comment]
@gbougiakas I think like radarr/sonarr, bazarr have the little ribbon that let the system know if an episode/show/movie is monitored or not? That's the manual way though. 

> Bazarr was still indexing embedded subtitles but wasn't taking them into account when calculating missing subtitles. Now, it doesn’t index them at all.
@morpheus65535 Embedded subtitles should be an option to check or uncheck too. Most of times embedded are  English subtitles and then when you have bazarr search for 2 languages (eng and greek for example) result is to have two english choices when you watch something.

**Comment by morpheus65535** [comment]
@gbougiakas 
> One is whether Bazarr abandons an mkv after a couple of days/months and does not search over and over again for subtitles.

Enable the adaptive searching settings. It does exactly that.
> Second I would like the option to set the intervals for all actions (ie search for missing subs runs every 3 hours, I would like to be able to configure that).

There's already a feature request for that.

**Comment by morpheus65535** [comment]
@piratx The "Use embedded subtitles" settings doesn't meet your requirement?

**Comment by piratx** [comment]
@morpheus65535 I have it off right now and I still see twice the English substitles in most of episodes/movies. Maybe I need to delete all english subtitles and let it do it's job.

**Comment by morpheus65535** [comment]
With master branch(0.7.2.1), Bazarr is still indexing embedded subtitles but don't take them into account when it calculate the missing subtitles. In dev branch, I've made a fix to not index them at all. You still have to reindex the whole library to remove those unwanted embedded subtitles. You can do this for a single movie by clicking on scan disk or, globally using the scheduled tasks.

**Comment by piratx** [comment]
@morpheus65535 Will change my master to development and try this later. Thank you ^^
