### ISSUE TITLE
Multiple errors when attempting manual search

### ISSUE THREAD

**Issue by neuman1812** [morpheus65535/bazarr#379]
**Describe the bug**
Attempting to do a manual search of subtitles results in many different errors.  Not sure which one is the issue.

**To Reproduce**
1. Go to movie
2. Click on manual search
3. No subtitles found

**Expected behavior**
Some subtitles should be found.

**Software (please complete the following information):**
 - Bazarr: v0.7.2.1
 - Radarr version 0.2.0.1293

Operating System: Raspbian GNU/Linux 9 (stretch)
Kernel: Linux 4.14.98-v7+
Architecture: arm (Raspberry Pi)

**Additional context**
Debug Log: https://hastebin.com/gitokowica.coffeescript

**Comment by morpheus65535** [comment]
Regarding the first error, make sure you have unrar installed.

For the other errors, please see this link: https://stackoverflow.com/questions/48843728/intermittent-getrandom-initialization-failed-using-scrapy-spider

**Comment by neuman1812** [comment]
Thank you,  both thoses solutions cleaned up some errors.  However after a reboot,  subtitles are still not found:

debug log :https://hastebin.com/enasuwoqop.rb

**Comment by morpheus65535** [comment]
All your provider are still discarded due to SSL error. You probably having something else missing on your OS installation. For LegendasTV, the archive seems to be corrupted.

**Comment by neuman1812** [comment]
This is the same setup I've had for several months now.  I've only noticed
these errors in the past week or two.

After checking, it's only happening with movies.  All my tv shows are fine.

**Comment by morpheus65535** [comment]
Something is wrong with your installation: you should be using subliminal_patch instead of normal subliminal. Please run `git pull` from bazarr directory and restart Bazarr. If it doesn't fix your issue, keep your data directory and reinstall.

**Comment by neuman1812** [comment]
https://hastebin.com/viporirape.cs

--I think I'll just reinstall at this point...

**Comment by morpheus65535** [comment]
Shouldn't hurt... ;-)
