### ISSUE TITLE
Some fields are in error, but don't know which

### ISSUE THREAD

**Issue by BlackFayah** [morpheus65535/bazarr#382]
**Describe the bug**
I am getting the following error: `Some fields are in error and you can't save settings until you have corrected them. Be sure to check in every tabs.` However, I have no clue where I can find the error. Nothing is red, no exclamation marks, nothing.

**To Reproduce**
1. Go to 'Settings'
2. Notice the error

**Expected behavior**
It should be clearly visible what's causing the error, so it's easy to fix it.

**Screenshots**
![image](https://user-images.githubusercontent.com/16139664/55669988-97f43b80-587e-11e9-8472-0275cebd38af.png)

**Software (please complete the following information):**
 - Bazarr: v0.7.3
 - Radarr version: v0.2.0.1293
 - Sonarr version: v2.0.0.5322
 - OS: Ubuntu 16.04 LTS

**Comment by morpheus65535** [comment]
Check to be sure you have at least one language and one provider enabled. Test connection to Sonarr and Radarr also.

**Comment by BlackFayah** [comment]
I think I found it. At the "Subliminal" tab, there is an option `Upgrade previously downloaded subtitles`, which was unchecked, but one of the fields that show up when you check that option, `Number of days to go back in history to upgrade subtitles (up to 30)`, was in error (it was set to `None`). So apparently unchecking the option doesn't make this error go away.

**Comment by morpheus65535** [comment]
You are right. I’ve pushed a fix for that last night.
