### ISSUE TITLE
Manual search and download do not work for 2 providers

### ISSUE THREAD

**Issue by dixonbg** [morpheus65535/bazarr#383]
**Describe the bug**
Manual search and download do not work for subsunacs.net and subs.sab.bz providers.
Also the provider link is not working

**To Reproduce**
1. Go to any movie in Bazarr that exists in the above provider
2. Delete the existing files, if any
2. Click on 'Manually search for subtitles'
3. Find any entry of 'subsunacs' or 'subssabbz'
4. The provider link is http://192.168.1.81:6767/movie/null
5. Clicking download closes popup and nothing happens. The debug log shows nothing.

**Expected behavior**
Provider link should point to the provider's website. Download button should download the subtitle files.

**Screenshots**
![image](https://user-images.githubusercontent.com/11996493/55675355-fc88b800-58c9-11e9-890e-1ebf4ae16956.png)

**Software (please complete the following information):**
Bazarr version 0.7.2.1
Sonarr version 2.0.0.5322
Radarr version 0.2.0.1293
Operating system Linux-4.18.20-unRAID-x86_64-with
Python version 2.7.15

**Additional context**
Search and automatic download works fine. I haven't verified if these 2 are the only providers that have this issue. These are the ones I've noticed.

**Comment by morpheus65535** [comment]
@dimitrov-adrian You want to take a look at this one as you're the one who developed those providers? Thanks!

**Comment by dimitrov-adrian** [comment]
@morpheus65535 yes, #384 should fix it.

**Comment by morpheus65535** [comment]
@dimitrov-adrian Thanks!

@dixonbg Can you test it in dev branch please?

**Comment by dixonbg** [comment]
Works perfect!
Thank you!
