### ISSUE TITLE
After switching to sonarr v3 bazarr shows episodes of one show with name of the other

### ISSUE THREAD

**Issue by enchained** [morpheus65535/bazarr#389]
**Describe the bug**
I go to the show "Station 19", it's path is correct, but it's poster and episodes list are from "This is Us". Similar mix up happens for every show from sonarr it seems. 
I guess it's an internal id conflict or something? Is there any way to fix this without a complete reinstall? I don't want to disturb current radarr setup.

**To Reproduce**
1. Install and set up sonarr v3 without restoring backup from previous sonarr version
2. Change sonarr port and key in bazarr
3. Restart bazarr
4. Be confused

**Expected behavior**
Some way to clear rescan/reset is needed.

**Software (please complete the following information):**
 - Bazarr: 0.7.2.1
 - Sonarr version 3.0.1.418
 - OS: Linux-4.19.4-arch1-1-ARCH-x86_64-with (docker)

**Comment by morpheus65535** [comment]
It's not possible to reuse an existing Bazarr instance while starting from scratch on Sonarr or Radarr. You have to either empty some table in the DB with the proper tools or delete de bazarr.db file and Bazarr will rescan your entire library. You'll have to redefine providers and desired languages.

**Comment by enchained** [comment]
Thanks for the hints.
I used sqlite3 to copy .schema, drop tables table_episodes, table_shows and table_history, recreated from schema, started again, rescanned and it works now, without resetting radarr data.
For anyone having similar issues in the future, I list my steps:

- linux: install sqlite(sqlite3)
- stop bazarr
- find your bazarr config with db folder and file
- in cli run `sudo sqlite3 bazarr.db` (db was readonly for me without sudo)
- in aql prompt run `.schema`, copy results somewhere
- decide which tables do you need to reset judging by the schema
- delete those tables by `DROP TABLE tablename` command, then paste the whole command from schema that creates each deleted table from scratch (or I heard you also can just delete contents without recreation: https://www.tutorialspoint.com/sqlite/sqlite_truncate_table.htm)

- windows: I guess you can use something like https://sqlitebrowser.org/ for that, after stopping bazarr

**Comment by morpheus65535** [comment]
`DELETE from tablename` would also have done the job without having to recreate the table. Thanks for sharing your resolution step.
