### ISSUE TITLE
Bazarr cannot save settings

### ISSUE THREAD

**Issue by filledk** [morpheus65535/bazarr#39]
hello there, i am total linux noob, im running bazarr in docker (for sonarr) and cannot get it to save the settings i put in there, even tho i restart the docker container...

what should i do?

here is the log file>

14/01/2018 23:27:44|INFO|Bazarr is started and waiting for request on http://0.0.0.0:6767/|
14/01/2018 23:28:44|ERROR|Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-01-14 22:29:44 UTC)" raised an exception|Traceback (most recent call last):  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "/bazarr/get_series.py", line 13, in update_series    get_profile_list()  File "/bazarr/get_series.py", line 75, in get_profile_list    url_sonarr_api_series = url_sonarr + "/api/profile?apikey=" + apikey_sonarrTypeError: coercing to Unicode: need string or buffer, NoneType found|
14/01/2018 23:29:44|ERROR|Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-01-14 22:29:44 UTC)" raised an exception|Traceback (most recent call last):  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "/bazarr/get_series.py", line 13, in update_series    get_profile_list()  File "/bazarr/get_series.py", line 75, in get_profile_list    url_sonarr_api_series = url_sonarr + "/api/profile?apikey=" + apikey_sonarrTypeError: coercing to Unicode: need string or buffer, NoneType found|
14/01/2018 23:30:44|ERROR|Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-01-14 22:30:44 UTC)" raised an exception|Traceback (most recent call last):  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "/bazarr/get_series.py", line 13, in update_series    get_profile_list()  File "/bazarr/get_series.py", line 75, in get_profile_list    url_sonarr_api_series = url_sonarr + "/api/profile?apikey=" + apikey_sonarrTypeError: coercing to Unicode: need string or buffer, NoneType found|
14/01/2018 23:31:44|ERROR|Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-01-14 22:31:44 UTC)" raised an exception|Traceback (most recent call last):  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "/bazarr/get_series.py", line 13, in update_series    get_profile_list()  File "/bazarr/get_series.py", line 75, in get_profile_list    url_sonarr_api_series = url_sonarr + "/api/profile?apikey=" + apikey_sonarrTypeError: coercing to Unicode: need string or buffer, NoneType found|
14/01/2018 23:32:44|ERROR|Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-01-14 22:33:44 UTC)" raised an exception|Traceback (most recent call last):  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "/bazarr/get_series.py", line 13, in update_series    get_profile_list()  File "/bazarr/get_series.py", line 75, in get_profile_list    url_sonarr_api_series = url_sonarr + "/api/profile?apikey=" + apikey_sonarrTypeError: coercing to Unicode: need string or buffer, NoneType found|
14/01/2018 23:33:44|ERROR|Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-01-14 22:34:44 UTC)" raised an exception|Traceback (most recent call last):  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "/bazarr/get_series.py", line 13, in update_series    get_profile_list()  File "/bazarr/get_series.py", line 75, in get_profile_list    url_sonarr_api_series = url_sonarr + "/api/profile?apikey=" + apikey_sonarrTypeError: coercing to Unicode: need string or buffer, NoneType found|
14/01/2018 23:34:44|ERROR|Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-01-14 22:35:44 UTC)" raised an exception|Traceback (most recent call last):  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "/bazarr/get_series.py", line 13, in update_series    get_profile_list()  File "/bazarr/get_series.py", line 75, in get_profile_list    url_sonarr_api_series = url_sonarr + "/api/profile?apikey=" + apikey_sonarrTypeError: coercing to Unicode: need string or buffer, NoneType found|
14/01/2018 23:35:44|ERROR|Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-01-14 22:36:44 UTC)" raised an exception|Traceback (most recent call last):  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "/bazarr/get_series.py", line 13, in update_series    get_profile_list()  File "/bazarr/get_series.py", line 75, in get_profile_list    url_sonarr_api_series = url_sonarr + "/api/profile?apikey=" + apikey_sonarrTypeError: coercing to Unicode: need string or buffer, NoneType found|
14/01/2018 23:36:44|ERROR|Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-01-14 22:36:44 UTC)" raised an exception|Traceback (most recent call last):  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "/bazarr/get_series.py", line 13, in update_series    get_profile_list()  File "/bazarr/get_series.py", line 75, in get_profile_list    url_sonarr_api_series = url_sonarr + "/api/profile?apikey=" + apikey_sonarrTypeError: coercing to Unicode: need string or buffer, NoneType found|
14/01/2018 23:37:44|ERROR|Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-01-14 22:38:44 UTC)" raised an exception|Traceback (most recent call last):  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "/bazarr/get_series.py", line 13, in update_series    get_profile_list()  File "/bazarr/get_series.py", line 75, in get_profile_list    url_sonarr_api_series = url_sonarr + "/api/profile?apikey=" + apikey_sonarrTypeError: coercing to Unicode: need string or buffer, NoneType found|
14/01/2018 23:38:22|INFO|Bazarr is started and waiting for request on http://0.0.0.0:6767/|
14/01/2018 23:39:22|ERROR|Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-01-14 22:40:22 UTC)" raised an exception|Traceback (most recent call last):  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "/bazarr/get_series.py", line 13, in update_series    get_profile_list()  File "/bazarr/get_series.py", line 75, in get_profile_list    url_sonarr_api_series = url_sonarr + "/api/profile?apikey=" + apikey_sonarrTypeError: coercing to Unicode: need string or buffer, NoneType found|
14/01/2018 23:40:22|ERROR|Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-01-14 22:41:22 UTC)" raised an exception|Traceback (most recent call last):  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "/bazarr/get_series.py", line 13, in update_series    get_profile_list()  File "/bazarr/get_series.py", line 75, in get_profile_list    url_sonarr_api_series = url_sonarr + "/api/profile?apikey=" + apikey_sonarrTypeError: coercing to Unicode: need string or buffer, NoneType found|
14/01/2018 23:41:22|ERROR|Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-01-14 22:42:22 UTC)" raised an exception|Traceback (most recent call last):  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "/bazarr/get_series.py", line 13, in update_series    get_profile_list()  File "/bazarr/get_series.py", line 75, in get_profile_list    url_sonarr_api_series = url_sonarr + "/api/profile?apikey=" + apikey_sonarrTypeError: coercing to Unicode: need string or buffer, NoneType found|
14/01/2018 23:41:56|INFO|Bazarr is started and waiting for request on http://0.0.0.0:6767/|
14/01/2018 23:42:55|ERROR|Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-01-14 22:43:55 UTC)" raised an exception|Traceback (most recent call last):  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "/bazarr/get_series.py", line 13, in update_series    get_profile_list()  File "/bazarr/get_series.py", line 75, in get_profile_list    url_sonarr_api_series = url_sonarr + "/api/profile?apikey=" + apikey_sonarrTypeError: coercing to Unicode: need string or buffer, NoneType found|
14/01/2018 23:43:55|ERROR|Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-01-14 22:43:55 UTC)" raised an exception|Traceback (most recent call last):  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "/bazarr/get_series.py", line 13, in update_series    get_profile_list()  File "/bazarr/get_series.py", line 75, in get_profile_list    url_sonarr_api_series = url_sonarr + "/api/profile?apikey=" + apikey_sonarrTypeError: coercing to Unicode: need string or buffer, NoneType found|
14/01/2018 23:44:55|ERROR|Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-01-14 22:44:55 UTC)" raised an exception|Traceback (most recent call last):  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "/bazarr/get_series.py", line 13, in update_series    get_profile_list()  File "/bazarr/get_series.py", line 75, in get_profile_list    url_sonarr_api_series = url_sonarr + "/api/profile?apikey=" + apikey_sonarrTypeError: coercing to Unicode: need string or buffer, NoneType found|
14/01/2018 23:45:55|ERROR|Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-01-14 22:46:55 UTC)" raised an exception|Traceback (most recent call last):  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "/bazarr/get_series.py", line 13, in update_series    get_profile_list()  File "/bazarr/get_series.py", line 75, in get_profile_list    url_sonarr_api_series = url_sonarr + "/api/profile?apikey=" + apikey_sonarrTypeError: coercing to Unicode: need string or buffer, NoneType found|
14/01/2018 23:46:29|INFO|Bazarr is started and waiting for request on http://0.0.0.0:6767/|
14/01/2018 23:50:46|INFO|Bazarr is started and waiting for request on http://0.0.0.0:6767/|
14/01/2018 23:53:51|INFO|Bazarr is started and waiting for request on http://0.0.0.0:6767/|

**Comment by morpheus65535** [comment]
Thanks for giving a try to Bazarr!

Have you configured a mapping between the `/bazarr/data` directory inside the docker container and a directory on your docker host where the container have read/write access?

It's this part of the docker container creation command line argument:
`-v /path/to/config/directory/on/host:/bazarr/data`

Replace `/path/to/config/directory/on/host` by the path of your directory on your docker host.

**Comment by morpheus65535** [comment]
After talking to another user who got the same problem, we figured out that some settings were not completed and the form validation didn't allow the submit (save button) to occur. I'm working on to manage those case but in the mean time, just be sure to select providers and languages in subliminal tab of settings.

**Comment by morpheus65535** [comment]
You can do an update from System-->Tasks, restart bazarr and it should be easier now.
