### ISSUE TITLE
Cannot save subtitle files

### ISSUE THREAD

**Issue by iggyfrog** [morpheus65535/bazarr#390]
**Describe the bug**
I am using Sonarr on Windows so my paths are windows based with spaces.

by series path is \\192.168.50.xxx\data\Movies\Series\ and my NAS requires authentication whwn used by linux and cannot avoid this.

I have mounted the cifs share to my linux on /mnt/storage and created a path mapping so that  \\192.168.50.xxx\data\Movies\Series\ points to /mnt/storage

then I receive the below:

![image](https://user-images.githubusercontent.com/49525828/55963662-ee48ec00-5c7b-11e9-928a-f02acef26090.png)

**Software (please complete the following information):**
 - Bazarr: 0.7.2.1
 - Radarr version 2.0.0.5322
 - Sonarr version [e.g. v 2.0.0.0001]
 - OS bazarr : debian 8
- OS Sonarr : Windows 10

**Comment by morpheus65535** [comment]
Enable debug log, rerun your test and provide a complete log.

**Comment by iggyfrog** [comment]
I installed everything on debian so I cannot reproduce now

**Comment by morpheus65535** [comment]
Reopen your issue if required.
