### ISSUE TITLE
Issue using DeathByCaptcha.com

### ISSUE THREAD

**Issue by atlgeek007** [morpheus65535/bazarr#391]
Using linuxserver/bazarr:development docker image.

I turned on DeathByCaptcha.com in the anti-captcha settings with my username/password.

I then re-enabled addic7ed, reinputting my username/password.

Whenever I search for subtitles, I get this in my logs :

 ` Unexpected error in provider 'addic7ed': Traceback (most recent call last): File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 162, in list_subtitles_provider results = self[provider].list_subtitles(video, provider_languages) File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 99, in __getitem__ provider.initialize() File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/addic7ed.py", line 115, in initialize pitcher = pitchers.get_pitcher()("Addic7ed", self.server_url + 'login.php', site_key, File "/app/bazarr/bazarr/../libs/subliminal_patch/pitcher.py", line 33, in get_pitcher raise Exception("AntiCaptcha class not given, exiting")Exception: AntiCaptcha class not given, exiting`

**Comment by morpheus65535** [comment]
I've pushed a fix, can you try it please?

**Comment by atlgeek007** [comment]
how long will it take the linuxserver development docker to update? :-)

**Comment by morpheus65535** [comment]
If I'm correct it should be in 10 minutes. Every hour in fact.

**Comment by morpheus65535** [comment]
Fixed.
