### ISSUE TITLE
Questions/Advices on how to deal languages with Radarr

### ISSUE THREAD

**Issue by GeoCookie** [morpheus65535/bazarr#392]
Hello everyone,

I would like your opinions and advice on how to use Radarr because I am having problems with language management.

I am French and I like watching movies in their native language. So I created several profiles with different languages. For English movies, no problem, everything works fine. But it gets complicated when I want to download a foreign movie. The main problem is the misinterpretation (in my opinion) of Radarr on terms related to the movie language and subtitles.

Some examples that I met:
• If no term indicates the language of the movie in the name of the torrent, Radarr assumes that the movie is in English. In fact, most of the time, this means that the file is in the original language of the movie.
(the movie below is in french, but found english by Radarr)
![Radarr - sans info](https://user-images.githubusercontent.com/43962716/56033407-d7aa9f80-5d24-11e9-97c7-5277f68936df.png)

• The problem also arises for the term "VO". If Radarr finds the word VO, he considers the file as English, which is not the case. A torrent with VO for an Italian movie means that it is in Italian, not in English
(i have no exemple right now)

• Some terms are misinterpreted as "VOSTFR" or "Multi".
(the movie below is in dutch, but found french by Radarr)
![Radarr - vostfr](https://user-images.githubusercontent.com/43962716/56033420-ded1ad80-5d24-11e9-8b04-9695b6019c72.png)
(the movie below contains french language, but found english by Radarr)
![Radarr - multi](https://user-images.githubusercontent.com/43962716/56033447-ed1fc980-5d24-11e9-8093-80a342fd4d7d.png)

How do you manage these situations? I tried to play with Custom Profiles but to have a functional system, I ended up with a real labyrinth.

Some ideas that I have that could simplify things:
• One thing that would be great would be for Radarr to manage the download of movies in their original language. For example, we can set "Original language" on the profile and Radarr gets the language from the metadata (TheMovieDB has this information). It will reduce the numer of used profiles. 
• It would be nice if we could edit the terms associated with a language. For example, that I can delete "VOSTFR" of the French language terms.

Thanks again for your work! :)

**Comment by morpheus65535** [comment]
@GeoCookie Even if I would really like to help you, I don't get why you ask this on Bazarr's Github page... Why not ask on Radarr's Github page or on Radarr's Discord server? I propose you move this question over there. Thanks.

**Comment by GeoCookie** [comment]
Oups i'm so sorry, i posted my message on the wrong page... :(
