### ISSUE TITLE
Bazarr doesn't recognize existing external subs

### ISSUE THREAD

**Issue by gmatranga86** [morpheus65535/bazarr#393]
Bazarr doesn't recognize existing external subs. Only the embedded subs.

here's is some logs:

12/04/2019 18:13:38|DEBUG   |root                            **|BAZARR Subtitles file saved to disk: /tv/The Big Bang Theory/Season 12/The Big Bang Theory - S12E18 - The Laureate Accumulation HDTV-720p.it.srt|**
12/04/2019 18:13:38|DEBUG   |root                            |BAZARR started subtitles indexing for this file: /tv/The Big Bang Theory/Season 12/The Big Bang Theory - S12E18 - The Laureate Accumulation HDTV-720p.mkv|
12/04/2019 18:13:38|DEBUG   |root                            |BAZARR is trying to index embedded subtitles.|
12/04/2019 18:13:38|DEBUG   |root                            |BAZARR embedded subtitles detected: en|
12/04/2019 18:13:38|DEBUG   |subliminal_patch.core           **|external subs: scanning path /tv/The Big Bang Theory/Season 12/The Big Bang Theory - S12E18 - The Laureate Accumulation HDTV-720p.mkv|**
12/04/2019 18:13:38|DEBUG   |subliminal_patch.core           |Found subtitles {}|
12/04/2019 18:13:38|DEBUG   |subliminal_patch.core           **|external subs: found {}|**
12/04/2019 18:13:38|DEBUG   |root                            |BAZARR storing those languages to DB: [['en', None]]|
12/04/2019 18:13:38|DEBUG   |root                            |BAZARR ended subtitles indexing for this file: /tv/The Big Bang Theory/Season 12/The Big Bang Theory - S12E18 - The Laureate Accumulation HDTV-720p.mkv|

the sub is in the file system and with the correct permission (0775).

Why is searching for that path??? That path is a file!!!

Bazarr Ver. 0.7.2.1
Via Docker Images linuxserver/bazarr:arm32v7-latest

**Comment by morpheus65535** [comment]
The path being a file it totally correct. We are looking for subtitles for that file.

Can you provide config.ini file while redacting sensible information to give me a little bit more context? Thanks.

**Comment by gmatranga86** [comment]
Hi @morpheus65535 ,

thank you for your reply.
Sure, here is my config file (with obscured sensible data).

[config.zip](https://github.com/morpheus65535/bazarr/files/3075043/config.zip)

**Comment by morpheus65535** [comment]
I've just tested italian subtitles with 0.7.3 in dev branch and it works perfectly well. You can try the dev branch using linuxserver/bazarr:development.

Maybe the subtitles filename doesn't perfectly match the episode filename? It should be The Big Bang Theory - S12E18 - The Laureate Accumulation HDTV-720p.it.srt. Be sure the case match also.

**Comment by gmatranga86** [comment]
I've tried with the development image for armv7. But there are not changes :(

2019-04-13 11:35:21,440 - root                             (76feb4a4) :  DEBUG (get_subtitle:192) - BAZARR Subtitles file saved to disk: /tv/The Big Bang Theory/Season 12/The Big Bang Theory - S12E18 - The Laureate Accumulation HDTV-720p.it.srt,
2019-04-13 11:35:21,478 - root                             (76feb4a4) :  DEBUG (list_subtitles:30) - BAZARR started subtitles indexing for this file: /tv/The Big Bang Theory/Season 12/The Big Bang Theory - S12E18 - The Laureate Accumulation HDTV-720p.mkv,
2019-04-13 11:35:21,663 - subliminal_patch.core            (76feb4a4) :  DEBUG (core:642) - external subs: scanning path /tv/The Big Bang Theory/Season 12/The Big Bang Theory - S12E18 - The Laureate Accumulation HDTV-720p.mkv,
2019-04-13 11:35:21,667 - subliminal_patch.core            (76feb4a4) :  DEBUG (core:651) - external subs: found {},
2019-04-13 11:35:21,672 - root                             (76feb4a4) :  DEBUG (list_subtitles:110) - BAZARR ended subtitles indexing for this file: /tv/The Big Bang Theory/Season 12/The Big Bang Theory - S12E18 - The Laureate Accumulation HDTV-720p.mkv

Maybe is just a my problem of the docker image and not Bazarr.

**Comment by morpheus65535** [comment]
I've done my test with the same image so it probably related to volume binding and/or path mapping issue. Please come to Discord for live support.

**Comment by izeen** [comment]
also have this issue all of a sudden :(

**Comment by morpheus65535** [comment]
@izeen As I'm not able to reproduce it, I suggest you also come to Discord for live support.

**Comment by gmatranga86** [comment]
Hi guys,

finally i've solved installing Bazarr directly on host instead Docker.
I don't know why, but the problem is only with Docker Version (maybe the configuration... i use portainer for manage my containers).

**Comment by morpheus65535** [comment]
It was probably a path mapping issue.
