### ISSUE TITLE
Custom Subtitle Folder doesn't seem to be honoured...

### ISSUE THREAD

**Issue by hami** [morpheus65535/bazarr#394]
**Description**
After setting the custom subtitle folder in the subliminal settings, the srt files are still being downloaded alongside the media.

**Steps**
1. Go to "Settings > Subliminal".
2. Click on "Subtitle folder" dropdown, and choose "Relative path to media file".
3. Enter "/subs/" in the "Custom Subtitle folder" field.
4. Save settings.
5. Go to a movie and manually or automatically download a subtitle

**Expected behavior**
It's expected that the subtitle would be downloaded into the "subs" folder within the media folder, but it downloads alongside the media – ignoring the Subliminal setting.

**Software**
 - Bazarr: 0.7.2.1
 - Radarr: 0.2.0.1293
 - Sonarr: 2.0.0.5322
 - OS: Ubuntu 18.04.2 LTS
 - Docker: 18.09.5
 - Container: linuxserver/bazarr

**Additional context**
Sub-Zero (2.6.4.2911) is still running in my Plex plugins, pointing to the same "subs" folder within the media folders. Some of the SRT files have been already populated by Sub-Zero, which Bazarr can't see in scans either.

All folders are owned by the "docker" group, and are 755.

**Comment by halali** [comment]
Put there just `subs` without / when you have / at the begging bazarr think its absolute path.

**Comment by hami** [comment]
I changed it to just "subs" without the / on either side, and restarted Bazarr (but not the container), and it's still downloaded the srt in the media folder.

Would it matter that I'm deleting an existing srt via Bazarr, then downloading it again as the test?

**Comment by hami** [comment]
I stand corrected, it is actually downloading into the "subs" folder as intended when I view the directory in my terminal, but the Bazarr UI is displaying it's path as in the media folder incorrectly.

When scanning the movie's folder in Bazarr, existing subtitles are also showing a path as being in the media which is correct. A scan doesn't move the srt to the "subs" folder though, which may be symptom of the same issue.

**Comment by halali** [comment]
Bazarr is not supposed to move subs... When you chose subfolder bazarr will search indide this folder and downloading new to it... But move existing subs have to by self.

**Comment by morpheus65535** [comment]
Fix have been pushed to dev branch. Please test and report.
