### ISSUE TITLE
Use Post-processing to force "Search for wanted subtitles"

### ISSUE THREAD

**Issue by Dr0bac** [morpheus65535/bazarr#395]
Bazarr only search for subtitles every 3 hours. I usually watch movies right after movie is downloaded.. While waiting for this feature to be implemented
https://github.com/morpheus65535/bazarr/issues/308
can you tell me is there a way to force that with post processing script?

Also one question.. I see in settings that Titlovi.com require anti-captcha now , i downloaded  manually in bazarr one subtitle from Titlovi.com and it didn't require captcha.. So i'm confused, are titlovi.com have some kind of daily limit, or similar so i need anti-captcha system?

**Comment by morpheus65535** [comment]
Post processing happens only after a subtitles is downloaded. As of now, there’s no way to automatically search for subtitles as soon as an item is added to Bazarr. 

Regarding Titlovi and reCaptcha, I haven’t experienced it myself but @panni have so he implemented anti-captcha for this provider.

**Comment by Dr0bac** [comment]
Ok, i understand, so is there a command that i can add to radarr/sonarr post processing option to force

Add movie/episode to bazarr

Than force

Search wanted episodes

**Comment by morpheus65535** [comment]
Not really. I’ll look into this later and if it easy I’ll implement it in dev branch.

**Comment by morpheus65535** [comment]
Functionality added in dev branch (v0.7.4). Please test and report.

**Comment by Dr0bac** [comment]
Tried today with one movie, everything went fine.. will try tomorow with couple more movies..
You didn't add toggle for this.. so this will be default behaviour? Also how is it working? If bazarr detect new movie/episode in the list then it will download subtitles for that movie/episode or it will try to download subtitles for movies/episodes in wanted list?

**Comment by morpheus65535** [comment]
It’s the default behavior. It will search for subs for added or upgraded episodes/movies if there’s maximum 5 new items in this sync occurence. That prevent to extend the initial scan for nothing.
