### ISSUE TITLE
[Provider Request] Add Betaseries as EN / FR subtitle provider

### ISSUE THREAD

**Issue by hergonoway** [morpheus65535/bazarr#396]
Betaseries is a french alternative to Trakt.tv. It provides an authentificated API (via token from what I quickly red) and has endpoints dedicated to Subtitles. These subtitles are provided by the community or gathered from Addic7ed. 

Languages are VO (Assimilated as EN) and FR

https://www.betaseries.com/api/methodes/subtitles

**Comment by morpheus65535** [comment]
Merci on verra si on peut l’ajouter en temps et lieu!

**Comment by hergonoway** [comment]
I hope it could be implemented, lots of FR subtitles are on Addic7ed, it may be a good way to bypass recent restriction from Addic7ed

**Comment by MMM-M** [comment]
+1

**Comment by lennvilardi** [comment]
+1

**Comment by morpheus65535** [comment]
Should be available in dev branch now. Thanks to @Mexx62!
