### ISSUE TITLE
Radarr timeout

### ISSUE THREAD

**Issue by tkdrob** [morpheus65535/bazarr#397]
Radarr times out with really large number of movies. My radarr collection is huge, over 15000. Is there a solution to this?

 - Bazarr: 0.7.3
 - Radarr version 0.2.0.1293
 - OS: DSM

**Comment by morpheus65535** [comment]
Please provide a debug log.

**Comment by tkdrob** [comment]
14/04/2019 08:50:58|INFO    |root                            |BAZARR Log file emptied|
14/04/2019 08:50:58|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): 10.***.***.***:5003|
14/04/2019 08:50:58|DEBUG   |urllib3.connectionpool          |http://10.***.***.***:5003 "GET /api/system/status?apikey=********05 HTTP/1.1" 200 None|
14/04/2019 08:51:11|DEBUG   |apscheduler.scheduler           |Looking for jobs to run|
14/04/2019 08:51:11|DEBUG   |apscheduler.scheduler           |Next wakeup is due at 2019-04-14 08:56:11.374641-04:00 (in 299.982461 seconds)|
14/04/2019 08:51:11|INFO    |apscheduler.executors.default   |Running job "Update movies list from Radarr (trigger: interval[0:05:00], next run at: 2019-04-14 08:56:11 EDT)" (scheduled at 2019-04-14 08:51:11.374641-04:00)|
14/04/2019 08:51:11|DEBUG   |root                            |BAZARR Starting movie sync from Radarr.|
14/04/2019 08:51:11|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): 10.***.***.***:5003|
14/04/2019 08:51:11|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): 10.***.***.***:5003|
14/04/2019 08:51:11|DEBUG   |urllib3.connectionpool          |http://10.***.***.***:5003 "GET /api/system/status?apikey=********05 HTTP/1.1" 200 None|
14/04/2019 08:51:11|DEBUG   |urllib3.connectionpool          |http://10.***.***.***:5003 "GET /api/profile?apikey=********05 HTTP/1.1" 200 None|
14/04/2019 08:51:11|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): 10.***.***.***:5003|
14/04/2019 08:51:26|ERROR   |root                            |BAZARR Error trying to get movies from Radarr. Timeout Error.|Traceback (most recent call last):  File "/app/bazarr/bazarr/get_movies.py", line 31, in update_movies    r = requests.get(url_radarr_api_movies, timeout=15, verify=False)  File "/app/bazarr/bazarr/../libs/requests/api.py", line 75, in get    return request('get', url, params=params, **kwargs)  File "/app/bazarr/bazarr/../libs/requests/api.py", line 60, in request    return session.request(method=method, url=url, **kwargs)  File "/app/bazarr/bazarr/../libs/requests/sessions.py", line 524, in request    resp = self.send(prep, **send_kwargs)  File "/app/bazarr/bazarr/../libs/requests/sessions.py", line 637, in send    r = adapter.send(request, **kwargs)  File "/app/bazarr/bazarr/../libs/requests/adapters.py", line 529, in send    raise ReadTimeout(e, request=request)ReadTimeout: HTTPConnectionPool(host='10.1.0.5', port=5003): Read timed out. (read timeout=15)|
14/04/2019 08:51:26|DEBUG   |root                            |BAZARR All movies synced from Radarr into database.|
14/04/2019 08:51:27|DEBUG   |root                            |BAZARR All movie missing subtitles updated in database.|
14/04/2019 08:51:27|INFO    |apscheduler.executors.default   |Job "Update movies list from Radarr (trigger: interval[0:05:00], next run at: 2019-04-14 08:56:11 EDT)" executed successfully|

**Comment by morpheus65535** [comment]
So Radarr is taking more than 15 seconds to serialize JSON and respond to Bazarr. We can increase this timeout but your Synology will be busy (like 100% CPU usage) more than 15 seconds every 5 minutes (when we refresh movies list). I'm not sure you want to go that way...

**Comment by tkdrob** [comment]
Perhaps you can provide the option to increase the duration between syncs and the time to wait longer than 15 seconds before timing out

**Comment by morpheus65535** [comment]
The first one, we already have a feature request for it. The second part have been addressed in a fix I just committed to dev branch. Timeout is now 60 seconds. I f this is still insuffisant, your hardware is clearly undersized for the usage you want to do.

**Comment by jean-paullizotte** [comment]
Good morning, if the case may be.
I understand this issue is closed, but I just put Radarr on a Raspberry Pi V4 and I've got a similar experience.

The CPU threads on the device never went over 20%. However I realize that this appliance's throughput or I/O  may be sub-optimal compared to what is expected.

Of course thanks to this post I could just go into the file and manually edit the timeout to a ludicrous number (a WGET gives me results in about 4 minutes) (my library has 6000 movies in it).

I just thought these metrics could help you set it to something it make sense, for edge cases.

Cheers!

**Comment by derinbay** [comment]
@jean-paullizotte Hello, I'm having the same problem with my rpi 4.. Which file did you edit?

**Comment by morpheus65535** [comment]
> @jean-paullizotte Hello, I'm having the same problem with my rpi 4.. Which file did you edit?
> 
> Edit: Ok I've found it. It's at /app/bazarr/bin/bazarr/get_movies.py inside bazarr container. Changing 60s to 180s inside this file, fixed my problem.

It will be overwritten on every new releases.

**Comment by derinbay** [comment]
> > @jean-paullizotte Hello, I'm having the same problem with my rpi 4.. Which file did you edit?
> > Edit: Ok I've found it. It's at /app/bazarr/bin/bazarr/get_movies.py inside bazarr container. Changing 60s to 180s inside this file, fixed my problem.
> 
> It will be overwritten on every new releases.

Yeah, of course.. I'll create a script for after updating new releases I think.
Thanks

**Comment by drjp81** [comment]
Im creating my own container image "from" the one supplied by the community.
I like to add powershell among other things, for post processing and handling my downloads.
So I've added a step where I "searh and replace" in the file the 60 seconds to 500. When I see that there is a newer version I just launch a build the image with this. 

And it will always be good. 

But yes, by all means a parameter in the app would be great.
I haven't looked at the source code yet for the app. I am competent in .NET, but I'm not sure I'm ready to contribute something here. We'll see.

**Comment by coryallegory** [comment]
Timeout parameter for configuration requested here for Sonarr, but same issue noted here for Radarr
https://bazarr.featureupvote.com/suggestions/82885/allow-users-to-configure-sonarr-api-timeout-time

**Comment by morpheus65535** [comment]
> Timeout parameter for configuration requested here for Sonarr, but same issue noted here for Radarr

Each and every connection to Sonarr/Radarr have a timeout of 60 seconds. If your Sonarr or Radarr instance aren't able to answer a request in less than 60 seconds, you're definitely running and underpowered device and should upgrade it.

**Comment by morpheus65535** [comment]
Make your PR to dev branch and I'll review it.
