### ISSUE TITLE
scan disk for subtitles pb does not work

### ISSUE THREAD

**Issue by klebercabral** [morpheus65535/bazarr#399]
**Describe the bug**
scan disk for subtitles pb does not work

**Expected behavior**
|BAZARR external subtitles detected: pb|

 - Bazarr: after v 0.7.1
 - OS: armhf

**Comment by morpheus65535** [comment]
First, update to last version 0.7.3. If you still have the issue, provide a complete debug log so I can investigate.

**Comment by klebercabral** [comment]
17/04/2019 19:25:37|DEBUG   |root                            |Bazarr version: 0.7.3|
17/04/2019 19:25:37|DEBUG   |root                            |Bazarr branch: master|
17/04/2019 19:25:37|DEBUG   |root                            |Operating system: Linux-4.14.98-v7+-armv7l-with|
17/04/2019 19:25:37|DEBUG   |root                            |Python version: 2.7.15|
17/04/2019 19:25:40|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:6767/bazarr/|
17/04/2019 19:25:49|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): 172.***.***.***:8989|
17/04/2019 19:25:49|DEBUG   |urllib3.connectionpool          |http://172.***.***.***:8989 "GET /sonarr/api/MediaCover/5/fanart.jpg?apikey=********8d HTTP/1.1" 200 None|
17/04/2019 19:25:49|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): 172.***.***.***:8989|
17/04/2019 19:25:49|DEBUG   |urllib3.connectionpool          |http://172.***.***.***:8989 "GET /sonarr/api/MediaCover/5/poster-250.jpg?apikey=********8d HTTP/1.1" 200 None|
7/04/2019 19:26:23|DEBUG   |subliminal_patch.core           |external subs: found {}|
17/04/2019 19:26:23|DEBUG   |root                            |BAZARR storing those languages to DB: [['en', None]]|

**Comment by morpheus65535** [comment]
This isn't a complete debug log. I need to see what happen between 19:25:49 and 19:26:23. If you don't want to put it here, come see me in private on Discord.

**Comment by klebercabral** [comment]
> This isn't a complete debug log. I need to see what happen between 19:25:49 and 19:26:23. If you don't want to put it here, come see me in private on Discord.

[bazarr.log](https://github.com/morpheus65535/bazarr/files/3092044/bazarr.log)

**Comment by morpheus65535** [comment]
Thank you. I suppose your file have `.pb.srt` as extension? I fit's the case it is not supported. It need to be `.pob.srt` or `.pt-br.srt`.

**Comment by klebercabral** [comment]
It's pt-br.srt

**Comment by morpheus65535** [comment]
I've taken a look at your debug log and I can see that 4 minutes later, after you've restarted Bazarr, the same episode is scanned again and this time the external subtitles file are there:
```
17/04/2019 19:30:21|DEBUG   |root                            |BAZARR started subtitles indexing for this file: /tv/American Gods/Season 1/American.Gods.S01E01.720p.BluRay.X264-REWARD.mkv|
17/04/2019 19:30:21|DEBUG   |root                            |BAZARR is trying to index embedded subtitles.|
17/04/2019 19:30:21|DEBUG   |root                            |BAZARR embedded subtitles detected: en|
17/04/2019 19:30:21|DEBUG   |root                            |BAZARR embedded subtitles detected: en|
17/04/2019 19:30:21|DEBUG   |subliminal.core                 |Found subtitles {u'American.Gods.S01E01.720p.BluRay.X264-REWARD.pt-BR.srt': <Language [pt-BR]>}|
17/04/2019 19:30:21|DEBUG   |root                            |BAZARR external subtitles detected: pb|
17/04/2019 19:30:21|DEBUG   |root                            |BAZARR storing those languages to DB: [['en', None], ['en', None], ['pb', u'/tv/American Gods/Season 1/American.Gods.S01E01.720p.BluRay.X264-REWARD.pt-BR.srt']]|
17/04/2019 19:30:21|DEBUG   |root                            |BAZARR ended subtitles indexing for this file: /tv/American Gods/Season 1/American.Gods.S01E01.720p.BluRay.X264-REWARD.mkv|
```
Are they still listed in this series page?

**Comment by klebercabral** [comment]
This point downgrade to version 0.7.0.5

**Comment by morpheus65535** [comment]
Ok. Well, subliminal_patch that we get from SubZero doesn't seems to handle your subtitles file correctly. My issue here is that it works for me with latest dev version: 
![image](https://user-images.githubusercontent.com/5130500/56444908-ce8f7480-62c8-11e9-9f86-f891a16e7cb1.png)

If I can'T reproduce it, it make it difficult to fix it... :-/

**Comment by klebercabral** [comment]
on version 0.7.4:

![screen](https://user-images.githubusercontent.com/14235806/56445297-f97ec600-62d2-11e9-94d6-6cfc8c3af846.png)

**Comment by morpheus65535** [comment]
Can you show me a screenshot of the files in directory? And maybe share your config.ini file (mask confidential data please).

**Comment by klebercabral** [comment]
![ls](https://user-images.githubusercontent.com/14235806/56445694-ee2c9a00-62d4-11e9-8932-7ba616784983.png)

[config.txt](https://github.com/morpheus65535/bazarr/files/3099402/config.txt)

**Comment by morpheus65535** [comment]
Can you save your settings once with version 0.7.4? Just to be sure to have default values for custom folder saved. Thanks.

**Comment by morpheus65535** [comment]
And try to scan directory.

**Comment by klebercabral** [comment]
![screen](https://user-images.githubusercontent.com/14235806/56446191-93487200-62d7-11e9-8799-c3959c1e4abb.png)

![reboot](https://user-images.githubusercontent.com/14235806/56446229-d0acff80-62d7-11e9-813e-a4b3af6aa4cc.png)

persist error:

![error](https://user-images.githubusercontent.com/14235806/56446260-0520bb80-62d8-11e9-9517-d92d79212fdb.png)

**Comment by morpheus65535** [comment]
I have no clue what is your issue and cannot reproduce it. I suggest you come to Discord support server and we'll try to help you.

**Comment by klebercabral** [comment]
> I have no clue what is your issue and cannot reproduce it. I suggest you come to Discord support server and we'll try to help you.

I am using the linuxserver/bazarr image tagged arm32v7-development
I made a fresh clean installation with version 0.7.4 and the error persists

**Comment by klebercabral** [comment]
![Captura de Tela 2019-04-20 às 09 46 49](https://user-images.githubusercontent.com/14235806/56457443-65a00f00-6351-11e9-8ba1-a05b9befd096.png)
![Captura de Tela 2019-04-20 às 09 47 29](https://user-images.githubusercontent.com/14235806/56457444-6638a580-6351-11e9-9ff7-5ab6668b044c.png)

**Comment by morpheus65535** [comment]
Is this still an issue? This is probably a path mapping issue. Please come to Discord and we'll help you configure it properly. Thanks.

**Comment by klebercabral** [comment]
error persist in version 0.7.5

**Comment by morpheus65535** [comment]
Still, you didn't come to Discord for support...
