### ISSUE TITLE
Cannot detect some embedded subtitles (Enzyme)

### ISSUE THREAD

**Issue by peskdale** [morpheus65535/bazarr#40]
Due to a known issue with Enzyme, subtitle tracks with 'default' subtitle language (usually English) are not being detected when Bazarr scans for embedded subtitles in videos.

Original enzyme issue - https://github.com/Diaoul/enzyme/issues/29
PR with fix (was never pulled to master) - https://github.com/Diaoul/enzyme/pull/30

Branch from PR with fixes - https://github.com/aulemahal/enzyme/tree/fixDefaults

I've tested this fix with latest Bazarr master - seems to solve the problem.

**Comment by peskdale** [comment]
I put a copy of the fixed version in my bazarr directory (.../bazarr/enzyme). This took priority over the pip-installed package.

**Comment by morpheus65535** [comment]
You can remove your copy of enzyme in bazarr directory. I have added a LIBS directory in Bazarr and added it to sys.path. I've putted a modified copy of enzyme in it. Give it a try (dev branch) and give me your feedback. Thanks!

**Comment by peskdale** [comment]
I'm afraid it's preferring to use the version pip installed rather than your local copy in libs. I had to uninstall the pip package to make it use the local copy.

Uninstalling pip's enzyme package isn't a solution, because users may have other applications that require it.

Running with the package uninstalled, the following error was seen during startup:
`Could not load 'thesubdb': The 'enzyme>=0.4.1' distribution was not found and is required by the application`

**Comment by morpheus65535** [comment]
If I only copy the files from the PR, can I get into a version conflict if user got an older version of enzyme?

**Comment by peskdale** [comment]
For testing purposes, I've got bazarr.py printing `sys.path`. Here was the result with the current dev branch:

`['/opt/bazarr', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-arm-linux-gnueabihf', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/pi/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', 'libs/']`

Changing the append to an insert:
`sys.path.insert(1,(os.path.join(os.path.dirname(__file__), 'libs/')))`

Results in the following:
`['/opt/bazarr', 'libs/', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-arm-linux-gnueabihf', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/pi/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']`

After which, the libs directory takes priority over any pip installed packages, and the fix works.

**Comment by peskdale** [comment]
Alternatively, this might provide a tidier answer:
https://stackoverflow.com/questions/1260792/import-a-file-from-a-subdirectory/1260832

**Comment by morpheus65535** [comment]
Why did you insert after the first element of sys.path and before (1 vs 0)?

**Comment by morpheus65535** [comment]
The alternative seems to be good but you need to import your module this way: from libs import enzyme

This is probably not the way subliminal is going to call it and we'll be using to different versions of enzyme in Bazarr. :-/

**Comment by peskdale** [comment]
I only chose 1 so that it was after my bazarr directory in the list. Seemed a sensible choice while testing, but not a nessesity.

**Comment by morpheus65535** [comment]
Ok, for now I've inserted it first (0). We'll see if we got problem with that but everything seems to be working just fine.
