### ISSUE TITLE
Cloudflare error

### ISSUE THREAD

**Issue by jaycedk** [morpheus65535/bazarr#400]
Getting this error in the log
ERROR (__init__:240) - Error executing Cloudflare IUAM Javascript. Cloudflare may have changed their technique, or there may be a bug in the script.
Is anyone else seeing this

**Comment by morpheus65535** [comment]
@panni please look into this.

**Comment by pannal** [comment]
On subscene?

**Comment by jaycedk** [comment]
Sorry the logs do not say, but yes i have subscene enabled

**Comment by alouchee** [comment]
i have the same issue 
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3095534/bazarr.log)

**Comment by pannal** [comment]
Are you running bazarr on online seedboxes by any chance and not from your home IPs?

**Comment by jaycedk** [comment]
Its my own home ip.

**Comment by jaycedk** [comment]
I did open this ticket earlier.
https://github.com/morpheus65535/bazarr/issues/301
About over using api calls, but that was rejected.

**Comment by alouchee** [comment]
> Are you running bazarr on online seedboxes by any chance and not from your home IPs?

I'm using home IP only and I called my ISP to change my IP and once they did I checked and some issue

**Comment by jaycedk** [comment]
Guess it has something to do with this, Hens my previus comment.
https://www.reddit.com/r/kodi/comments/bbhtr6/subscene_fix_please/

**Comment by jaycedk** [comment]
OK this makes scense https://myip.ms/info/whois/104.27.144.220/k/1658049507/website/subscene.com
Thay changed ip. guessing is a cloudflare dns problem. but thats almost a month ago.

**Comment by jaycedk** [comment]
Found this i an kodi forum.
https://forum.kodi.tv/showthread.php?tid=184854&page=24

**Comment by jaycedk** [comment]
Hmm is there anyway to disable the captcha manualy.
https://forum.opensubtitles.org/viewtopic.php?f=1&t=14559&start=180
I now know it's not your fault, is a combination between cloudflare and subscene ip change.
Guess thay have to sort that for them self.
Will let the errors keep coming and going.
It seams like the ip ban is only 48 hours, it started working this morning.
But was baned again after 2 hours or so.

**Comment by morpheus65535** [comment]
@jaycedk is it fix since last commit to dev branch 2 days ago?

**Comment by jaycedk** [comment]
I will update and have a look, when I off work :)

**Comment by jaycedk** [comment]
Just updated.
Will post logs tomorrow.
Heading to bed, and letting it run its once over.

**Comment by jaycedk** [comment]
Hi guys.
Im not seeing the error any more.
Good job, thank you :)

**Comment by morpheus65535** [comment]
Thanks!
