### ISSUE TITLE
Upgrading subtitles every few hours

### ISSUE THREAD

**Issue by pven** [morpheus65535/bazarr#401]
It looks like since the last version Bazarr is updating the subtitles every run. This morning I had 129 notifications from Bazarr, and now I already have 79 new notifications.

I've enabled debug-info to find out what is going on, but during the runs it creates a lot of debug-information.

I am using version 0.7.3. No mappings have been defined.

How can I stop Bazarr from updating subs (not all subs btw) every run?

**Comment by morpheus65535** [comment]
Please provide a debug log even if it seems to big. I really need it to be able to help you.

**Comment by pven** [comment]
I don't like to put the logs online, so I've mailed it to you. Can you please check if that is sufficient?

**Comment by pven** [comment]
Today it looks like only new subs are searched, as expected. Maybe Bazarr was just confused for some days?

**Comment by morpheus65535** [comment]
Ok if the problem arise again, reopen this issue and we’ll look into it.
