### ISSUE TITLE
Add chmod to wiki

### ISSUE THREAD

**Issue by pven** [morpheus65535/bazarr#402]
I was trying to find out what the option 'Enable chmod' does. But since it is not mentioned in the wiki ( https://github.com/morpheus65535/bazarr/wiki/Settings-General ) , I can only guess.

Can the general settings part in the wiki please be updated?

Thanks!

**Comment by morpheus65535** [comment]
chmod change the permissions on a file in Linux. I will update the wiki ASAP.

**Comment by morpheus65535** [comment]
Done!
