### ISSUE TITLE
Allow multiple instances of Sonarr/Radarr

### ISSUE THREAD

**Issue by rubasace** [morpheus65535/bazarr#404]
I'm handling two separate radarr instances right now, one for 4K and one for 1080p. That forces me to also use 2 instances of bazarr as I cannot configure multiple radarr connections. 

I would like to have the possibility of integrating bazarr with multiple radarr instances as configuration for both will be exactly the same and having everything duplicated complicates things if I want to change something.

PS: I know there's a closed issue where it was only asked if there's need for multiple instances. I'm just suggesting the idea of allowing it on a single bazarr instance as I think simplifies things a lot

**Comment by morpheus65535** [comment]
As it’s a very specific use case and would be highly risky to have conflict between id provided by multiple instance, my answer is still the same: use multiple Bazarr instance.

**Comment by danihengeveld** [comment]
I am also running into this issue and I think it is a very common use case. For 1080p + 4k setup it is recommended to run multiple radarr/sonarr instances. But it seems illogical to me to run 2 bazarr instances (with the same exact config except the radarr and sonarr instances it connects to), why not support multiple?

**Comment by morpheus65535** [comment]
> I am also running into this issue and I think it is a very common use case. For 1080p + 4k setup it is recommended to run multiple radarr/sonarr instances. But it seems illogical to me to run 2 bazarr instances (with the same exact config except the radarr and sonarr instances it connects to), why not support multiple?

Because we would get conflicting series and episodes ID between both instances. Those ID are primary keys and must be unique.
