### ISSUE TITLE
ValueError: Timezone offset does not match system offset: -10800 != -14400. Please, check your config files.

### ISSUE THREAD

**Issue by VenomRo666** [morpheus65535/bazarr#405]
today i encounter this issue, first time that happens. 8th of april the time here in Chile was changed to 1 less hour, but i dont know how to resolve the issue

**Comment by morpheus65535** [comment]
Please provide the bazarr.log file.

**Comment by VenomRo666** [comment]
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3099410/bazarr.log)
this was the last log i have, know in the console shows:

Bazarr starting...
Traceback (most recent call last):
  File "bazarr\main.py", line 24, in <module>
    from update_db import *
  File "C:\ProgramData\Bazarr\bazarr\bazarr\update_db.py", line 7, in <module>
    from scheduler import execute_now
  File "C:\ProgramData\Bazarr\bazarr\bazarr\scheduler.py", line 66, in <module>
    if str(get_localzone()) == "local":
  File "C:\ProgramData\Bazarr\bazarr\bazarr\../libs/tzlocal\win32.py", line 95, in get_localzone
    utils.assert_tz_offset(_cache_tz)
  File "C:\ProgramData\Bazarr\bazarr\bazarr\../libs/tzlocal\utils.py", line 38, in assert_tz_offset
    raise ValueError(msg)
ValueError: Timezone offset does not match system offset: -10800 != -14400. Please, check your config files.

**Comment by morpheus65535** [comment]
Look like we have an issue with your timezone information. What is your timezone so I can run some test?

**Comment by VenomRo666** [comment]
Originaly is (UTC-04:00) Santiago, but since here in Chile the 7th of april Daylight Saving Time Ended we backwarded time in 1 hour.

**Comment by morpheus65535** [comment]
Did you restart Bazarr since the DST change?

**Comment by VenomRo666** [comment]
before yesterday was running fine, then it surely updated bazarr and then yesterday didn't wanted to start with that issue.

**Comment by morpheus65535** [comment]
This part of Bazarr haven't change since March 9 2018. Do you have made other changes on your computer? Do you have tzlocal installed through PIP?

**Comment by VenomRo666** [comment]
i dont think i have that package, i just downloaded bazarr and was running it on windows, i didnt make any changes to windows either.

**Comment by morpheus65535** [comment]
I can reproduce it.

I've opened an issue with upstream library having the issue:

https://github.com/regebro/tzlocal/issues/73

**Comment by morpheus65535** [comment]
Are you running docker image or from source?

**Comment by VenomRo666** [comment]
> Are you running docker image or from source?

From Source

**Comment by morpheus65535** [comment]
Ok another user had success by not defining the TZ environment variable but he's using Docker. :-/

**Comment by morpheus65535** [comment]
I've pushed a fix to dev branch if you want to test it.

**Comment by VenomRo666** [comment]
> I've pushed a fix to dev branch if you want to test it.

Hi morpheus, sorry for the late on the response, i downloaded it and it opened like it should.

Thank you
