### ISSUE TITLE
Wanted subtitles never download, leave no history

### ISSUE THREAD

**Issue by Spass1966** [morpheus65535/bazarr#407]
**Describe the bug**
I have the same number of wanted subtitles as when I first started using Bazarr. I have verified that the API keys for Sonarr and Radarr are correct. I have VIP status on OpenSubtitles.

**To Reproduce**
1. Click Wanted
2. Click Download wanted subtitles

**Software (please complete the following information):**
 - Bazarr: latest development as of today
 - Radarr version 0.2.0.1293
 - Sonarr version 2.0.0.5322
 - OS: Synology DSM

**Logs**
https://gist.github.com/Spass1966/7e9da79ba7e3619311f84d695b9b9e0e

**Comment by morpheus65535** [comment]
Your issue is because you only have OpenSubtitles enabled and it is throttled because service is unavailable. Either it is really unavailable or your IP is temporary or permanently blocked (VPN?). You can try to activate an other provider and search for a single episode subtitles. You should see the missing count decrease by one.

**Comment by Spass1966** [comment]
@morpheus65535 Actually those throttled messages in the log are from before I paid for and activated VIP status with OS. You can see that they disappear later in the logs because I became VIP. Doing a manual search still does not download the subtitles.

**Comment by Spass1966** [comment]
I have also ticked the VIP checkbox under Subliminal.

**Comment by halali** [comment]
Can you provide full debug log?

**Comment by Spass1966** [comment]
I already did. The gist shows full debug logs after I checked the box for
debug logs and restarted.

**Comment by halali** [comment]
You use docker on your Synology? It looks as bad pathmappings... Can you provide screenshot of your volume mappings for sonarr radarr and bazarr

**Comment by morpheus65535** [comment]
Can you provide a debug log of a manual search and download process?

**Comment by Spass1966** [comment]
Pathmappings were correct, the issue is my fault: I didn't provide the correct password to my OpenSubtitles account. The error message I received was that I wasn't VIP, which I knew was false so I re-entered my account password and voila.

Apologies to the team.

**Comment by morpheus65535** [comment]
No problem, have fun! :-)
