### ISSUE TITLE
Download forced subtitle option

### ISSUE THREAD

**Issue by ramonleon627** [morpheus65535/bazarr#412]
Now that pannal is contributing here, perhaps adding a forced subtitles option is possible, considering this functionality exists in the Sub-Zero bundle.  I'm aware that bazarr uses Subliminal and it doesn't have this feature, but that repo doesn't seem to be maintained anymore.  See here for the OpenSubtitles API feature that can differentiate forced subtitles: 

https://forum.opensubtitles.org/viewtopic.php?f=8&t=15856

**Comment by morpheus65535** [comment]
We are already working on that functionality that should be included before 0.8. I’ll close this issue because we already have another feature request for this.
