### ISSUE TITLE
Update to v3 UI

### ISSUE THREAD

**Issue by TJohnson93** [morpheus65535/bazarr#417]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by morpheus65535** [comment]
There's no plan to move to v3 UI up to v1.0 of Bazarr. It's something we have in mind for v2 but we'll see when we get there. I'm going to close this feature request as we manage this in a list on our side. Thanks.
