### ISSUE TITLE
Hearing-Impaired - Skip

### ISSUE THREAD

**Issue by beisat** [morpheus65535/bazarr#424]
I'm unsure if this should be a bug or a feature request, as the Wiki for me is not precise what correct behavior should be. Even though I set subliminal default settings to **Hearing-impaired: No** (and also double check that the series I'm scanning for is set to No), it downloads the hearing-impaired subtitles because they have a higher rating on opensubtitles. Wiki just sais: 
"Enable this to **require** hearing-impaired subtitles instead of standard one." So maybe this is as expected? Anyway, I strongly dislike having hearing-impaired subtitles and I really wish bazarr would not download them if the switch is set to off (or add a second switch, as subliminal itself has true/false/none as settings afaik). The metadata on opensubtitles is correct (e.g. if I do a manual search), but bazarr just ignores that I want without hearing-impaired:(

**Comment by beisat** [comment]
Attached as discussed in the discord, here the logs. Though based on morpheus65535 edit, it seems to be a feature request and not a bug.

![Annotation 2019-05-03 111726](https://user-images.githubusercontent.com/50216534/57131975-621f7580-6d9e-11e9-81e7-28fc5ed4211e.jpg)
[bazarr_edited_log.log](https://github.com/morpheus65535/bazarr/files/3141467/bazarr_edited_log.log)

Thanks

**Comment by morpheus65535** [comment]
I was seeing this as a feature request because we’ll have to implement yes/no/don’t care. This is new.

**Comment by beisat** [comment]
Ok thanks a lot for all your hard work, hope it makes the cut, as I love using bazarr but this is really making it difficult for me.
Any chance you could point me in the direction of where in the code base I could set this value / variable hardcoded to false already in my bazarr (as a workaround until / if the feature gets implemented), I tried to find it myself but failed miserably. I'm assuming there must be one line where you pass all the parameters to subliminal for search, but maybe I see things to simple for such a complex app.

**Comment by morpheus65535** [comment]
I've pushed a fix in dev branch to force hearing impaired respect. Can you give it a try?

**Comment by beisat** [comment]
That was fast! Thanks a lot. I just gave it a try. Seems to work really well, at least on first try. I will keep it running and report back if any issues creep up.
