### ISSUE TITLE
Errno2 - no such files or directory when saving subs

### ISSUE THREAD

**Issue by florian434** [morpheus65535/bazarr#425]
**Describe the bug**
Hi, I got some strange issue : Bazarr used to work fine for at least a Month and since a few day and without touching anything I got an Error when saving sub to disk.

I tried to reinstall Bazarr Stable or Dev from the beginning but I still got the same Issue.
My video files and Sub are on a Synology Share with "Everyone" in RW. If I check the network path from my Server i can successfully create folder on the Share.

Bazarr 0.7.4 Dev - 0.7.3 Stable
Windows Server 2016

Error (I know it is a VOST file but it is just an example) :
![image](https://user-images.githubusercontent.com/24958237/57138877-111a7c00-6db4-11e9-9d05-8d4819b83b5f.png)

Synology ACL : 
![image](https://user-images.githubusercontent.com/24958237/57138949-40c98400-6db4-11e9-83aa-6061df23acfe.png)

I attachedd my full log files too
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3141980/bazarr.log)

Any idea ?

**Comment by morpheus65535** [comment]
I've pushed a fix (90645838538bb7346ff9cb60eb76302526e5eb92) in dev branch. Can you try it?

**Comment by florian434** [comment]
Thanks but still same issue after update : 
![image](https://user-images.githubusercontent.com/24958237/57141437-7e311000-6dba-11e9-8965-01a3de895865.png)

Logs : 
[bazarr (1).log](https://github.com/morpheus65535/bazarr/files/3142140/bazarr.1.log)

**Comment by morpheus65535** [comment]
Do you have this issue with another episode or just this one?

**Comment by florian434** [comment]
No every episode now. For the records, this one worked a few days ago, no more now : 
![image](https://user-images.githubusercontent.com/24958237/57149732-ae81aa00-6dcc-11e9-9af9-6b3dd6b1d40b.png)

logs : 
[bazarr (2).log](https://github.com/morpheus65535/bazarr/files/3142645/bazarr.2.log)

**Comment by morpheus65535** [comment]
You understand that we didn't change a thing in master branch since April 11? If this is something new it must be something that have changed on your side. :-/

**Comment by florian434** [comment]
Yes I do, but not intentional, maybe the last Windows Update. I tried the docker Image on Synology and it is working so I will leave the Windows version for now.

Thanks for your help and your great work ;)
