### ISSUE TITLE
Add notifications 

### ISSUE THREAD

**Issue by thyeestes** [morpheus65535/bazarr#43]
Would it be possible to add notification support, like pushover?

**Comment by morpheus65535** [comment]
It's something that could be implemented. It depend on how many users would like to have it. I won't use it but maybe some will. As soon as feathub is back online, I'm going to add this one for vote.

**Comment by morpheus65535** [comment]
You can try it in development branch for now. Give me your feedback please.

**Comment by thyeestes** [comment]
I changed the branch to development and ran the update task manually. I get this error:

Traceback (most recent call last): File "/usr/local/python/lib/python2.7/site-packages/apscheduler/executors/base.py", line 125, in run_job retval = job.func(*job.args, **job.kwargs) File "/volume1/@appstore/bazarr/check_update.py", line 29, in check_and_apply_update result = g.pull('origin', branch) File "/usr/local/python/lib/python2.7/site-packages/git/cmd.py", line 551, in return lambda *args, **kwargs: self._call_process(name, *args, **kwargs) File "/usr/local/python/lib/python2.7/site-packages/git/cmd.py", line 1010, in _call_process return self.execute(call, **exec_kwargs) File "/usr/local/python/lib/python2.7/site-packages/git/cmd.py", line 821, in execute raise GitCommandError(command, status, stderr_value, stdout_value)GitCommandError: Cmd('git') failed due to: exit code(1) cmdline: git pull origin master stdout: 'Updating 249c5e9..58e40d3' stderr: 'From https://github.com/morpheus65535/bazarr * branch master -> FETCH_HEADerror: Your local changes to the following files would be overwritten by merge:	scheduler.pyPlease commit your changes or stash them before you merge.Aborting'

I think this is because I had to change scheduler.py because it wouldn't install on my Synology. I changed this line, because it was complaining during install that no correct timezone could be found.
"scheduler = BackgroundScheduler({'apscheduler.timezone': 'Europe/Amsterdam'})"

This is something I found using on the Internet as my knowledge to Python and Linux are quite minimal. Could you give me a suggestion on how to proceed?

**Comment by morpheus65535** [comment]
I've rebased the docker image. You should remove your bazarr container, pull the bazarr image to refresh it and recreate the bazarr container using those instructions: https://github.com/morpheus65535/bazarr/wiki/Installation---Docker

**Comment by morpheus65535** [comment]
8257183b6810ba1bbf9d0d22573a6ef8123c2d2c should fix your problem without modification required on your side.

**Comment by morpheus65535** [comment]
BTW notifications are now in master branch.

**Comment by thyeestes** [comment]
Thanks for the fast fixes.

I have a DS216Play so Docker is not available since it is a 32bit NAS. I installed Bazarr direclty in DSM and it wouldn't install without the modification of providing a timezone somewhere. I choose the scheduler.py.

I will check it out in the master branch

**Comment by morpheus65535** [comment]
In this case you need to define the Timezone at OS level, don't patch everything over it. Which version of DSM you're running?

**Comment by morpheus65535** [comment]
You need to understand that if you start modifying Bazarr sources, you will not be able to update it anymore.

**Comment by thyeestes** [comment]
I have my time zone defined in DSM, but apparently Bazarr doesn't recognizes this. I'm running DSM 6.1.4-15217 Update 5.

I know it is not ideal to change source files, but due to my lack of knowledge I didn't know another way. Strangely enough I think Bazarr is updating automatically, because I receive these notifications that I should restart Bazarr for changes to become effective. So I run my start-stop-status script and after that the notification about restarting is gone, so assume Bazarr is updated. Although version number stays 0.3.2

**Comment by thyeestes** [comment]
This was the reason I changed scheduler.py in the first place:

__/usr/local/python/lib/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/volume1/@appstore/python/lib/python2.7/site-packages/zope': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
Requirement already satisfied: gitpython in /volume1/@appstore/python/lib/python2.7/site-packages
Requirement already satisfied: gitdb2>=2.0.0 in /volume1/@appstore/python/lib/python2.7/site-packages (from gitpython)
Requirement already satisfied: smmap2>=2.0.0 in /volume1/@appstore/python/lib/python2.7/site-packages (from gitdb2>=2.0.0->gitpython)
Requirement already satisfied: langdetect in /root/.local/lib/python2.7/site-packages
Requirement already satisfied: six in /volume1/@appstore/python/lib/python2.7/site-packages (from langdetect)
Requirement already satisfied: apprise in /root/.local/lib/python2.7/site-packages
Requirement already satisfied: decorator in /root/.local/lib/python2.7/site-packages (from apprise)
Requirement already satisfied: requests-oauthlib in /root/.local/lib/python2.7/site-packages (from apprise)
Requirement already satisfied: urllib3 in /volume1/@appstore/python/lib/python2.7/site-packages (from apprise)
Requirement already satisfied: click>=5.0 in /volume1/@appstore/python/lib/python2.7/site-packages (from apprise)
Requirement already satisfied: oauthlib in /root/.local/lib/python2.7/site-packages (from apprise)
Requirement already satisfied: requests in /volume1/@appstore/python/lib/python2.7/site-packages (from apprise)
Requirement already satisfied: six in /volume1/@appstore/python/lib/python2.7/site-packages (from apprise)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /volume1/@appstore/python/lib/python2.7/site-packages (from requests->apprise)
Requirement already satisfied: certifi>=2017.4.17 in /volume1/@appstore/python/lib/python2.7/site-packages (from requests->apprise)
Requirement already satisfied: idna<2.7,>=2.5 in /volume1/@appstore/python/lib/python2.7/site-packages (from requests->apprise)
Traceback (most recent call last):
  File "/usr/local/bazarr/bazarr.py", line 88, in <module>
    from scheduler import *
  File "/volume1/@appstore/bazarr/scheduler.py", line 13, in <module>
    scheduler.add_job(check_and_apply_update, 'interval', hours=6, max_instances=1, coalesce=True, misfire_grace_time=15, id='update_bazarr', name='Update bazarr from source on Github')
  File "/usr/local/python/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 413, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/usr/local/python/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 907, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/usr/local/python/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 892, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
  File "/usr/local/python/lib/python2.7/site-packages/apscheduler/triggers/interval.py", line 38, in __init__
    self.timezone = astimezone(timezone)
  File "/usr/local/python/lib/python2.7/site-packages/apscheduler/util.py", line 86, in astimezone
    'Unable to determine the name of the local timezone -- you must explicitly '
ValueError: Unable to determine the name of the local timezone -- you must explicitly specify the name of the local timezone. Please refrain from using timezones like EST to prevent problems with daylight saving time. Instead, use a locale based timezone name (such as Europe/Helsinki)_._

I copied back the original scheduler.py and git pull the latest update. Now when I want to start Bazarr again I get this error. As mentioned last time resolved it by hard coding the timezone: 
scheduler = BackgroundScheduler({'apscheduler.timezone': 'Europe/Amsterdam'}) in scheduler.py

**Comment by morpheus65535** [comment]
Which version of DSM?

Have you looked at this: https://github.com/rembo10/headphones/issues/2921

Is your timezone correctly set in shell? If not, this is where you should fix the problem, not in Bazarr.

**Comment by thyeestes** [comment]
DSM Version: DSM 6.1.4-15217 Update 5

I had a look at the link but there is no real solution.

When I run 'date' in the shell it shows the correct time and date.

**Comment by morpheus65535** [comment]
With date, is the timezine correct?

**Comment by thyeestes** [comment]
![image](https://user-images.githubusercontent.com/21059883/35299414-88804a1a-0085-11e8-86a0-d87d6a532cff.png)

**Comment by morpheus65535** [comment]
I don't know what to say, I don't have a Synology NAS to test it. From what I know, no one ever reported problem with Bazarr on Synology but they are probably using it through docker. I suggest you open an issue on https://github.com/agronholm/apscheduler reporting that APScheduler cron jobs are not working on your setup. Maybe they'll be able to help you with that. Sorry. :-/

**Comment by thyeestes** [comment]
No problem. As mentioned earlier I cannot use Docker since it is not available for my NAS.

I will keep searching and meanwhile I changed scheduler.py again to get Bazarr running.

Thanks for your replies.

**Comment by morpheus65535** [comment]
Yes I understand for Docker, the guys at Synology doesn't seems to have interest in compiling an x86 version of Docker even if Docker itself is compatible with x86.

The solution would be for you to find a way that APScheduler recognize your timezone from OS. I would be looking in this direction.

Good luck!

**Comment by thyeestes** [comment]
Just found a solution I think.

I just have run " echo "Europe/Amsterdam" >  /etc/timezone" change scheduler.py back to original and restarted Bazarr. It now starts without errors and the update task is also working when I start it manually.

Thanks again!

**Comment by morpheus65535** [comment]
If you restart your Synology, doesn't it still work or do you have to run the "echo" again?

**Comment by thyeestes** [comment]
After a reboot it still works. Just verified it.

**Comment by morpheus65535** [comment]
Good to know. Thanks!

**Comment by thyeestes** [comment]
No problem.

Now back on topic :-) I've configured Pushover over notifications, but that does not seem to work. Subtitles are downloaded but I do not receive a notification. Another strange things is that one specific subtitle is downloaded over and over again. Should create a new issues for that?

**Comment by morpheus65535** [comment]
Ok, I've not tried Pushover but Pushbullet works here. Got something in the log?

For the other problem, yes open a different issue please.

**Comment by thyeestes** [comment]
I've configured Pushover like pover:://{user_id}@{token} where I replaced user_id with my user key and token with the API token. In the logs is the following message: pover:://user_id@token is an unparseable server url.

**Comment by morpheus65535** [comment]
Use only one ":", not two.

**Comment by morpheus65535** [comment]
I've opened an issue with @caronc so he could correct the syntax in his wiki:

https://github.com/caronc/apprise/issues/3

**Comment by thyeestes** [comment]
Yes that solved it.

**Comment by morpheus65535** [comment]
Good news! Have fun! :-)

**Comment by thyeestes** [comment]
Thanks for the support, quick replies and keep up the good work!
