### ISSUE TITLE
Bazarr keep external hdd awake

### ISSUE THREAD

**Issue by Dr0bac** [morpheus65535/bazarr#430]
After i installed bazarr i noticed that my external hdd where my radarr/sonarr media is stored, sometimes stay awake until reboot, than again after reboot hdd goes to sleep and after sometime hdd wake up and stay awake and when i look at hdd led, it does not blink at all (there are no read/write operations)

For one week i turned bazarr off and hdd is ok, it goes to sleep like it should..

**Comment by morpheus65535** [comment]
That's a normal behaviour if Bazarr is actively downloading subtitles. In my case, I have no missing subtitles most of the time and HDD are parked except during the nightly rescan at 4/5am.

What version of Bazarr are you using?

**Comment by Dr0bac** [comment]
No, all subtitles are downloaded. Also my hdd sleep after 30 minutes of inactivity, subtitles are downloaded if i have something in wanted every 3 hours.. i didn't downloaded any movie or series in my testing time..also it's strange that i don't see any activity in hdd..i tried inotify wait, and nothing is accessed in that time..bazarr is on 0.7.4 develop version, but i turned off auto updates to see if this is problem..i don't know how to test this properly. To clarify my hdd will stay for days awake because of this without any activity

**Comment by morpheus65535** [comment]
The only task that runs frequently are those one:

- Update series list from Sonarr
- Sync episodes with Sonarr
- Update movies list from Radarr

None of them access media disk. They access bazarr.db. Do you store your Bazarr data directory on your media disk?

**Comment by Dr0bac** [comment]
No, everything is on sd card (Raspberry pi). I will turn on debug loging and inotify wait and will see if i can catch what is going on.. maybe bazarr check some movie file and get stuck..i don't think that those task that you mentioned are problems, because on device start everything is normal and after some time (hours) problem begin..

Tell me, that bazarr.db file, does bazarr only read it freaquently or it's rewrite it like radarr/sonarr do it. I ask because it's on sd card?

**Comment by morpheus65535** [comment]
Ok I'll be happy to help with your debug log analyzing.

Everytime we get updated metadata from Sonarr or Radarr, we update the DB to keep in sync. It shouldn't happens often unless your have plenty of upgraded episodes/movies every day.

**Comment by Dr0bac** [comment]
@morpheus65535  i think that i found what is keeping hdd awake.
It's swap file, on dietpi system it is located on external drive i guess to preserve sd card.
Reason why i noticed this after i installed bazarr is because bazarr is using good chunk of raspberry pi memory

![vlcsnap-2018-12-13-08h55m40s110](https://user-images.githubusercontent.com/43797966/57933142-c1ac7380-78bc-11e9-9f56-0274ec56b22d.png)

You can see on screenshot that bazarr is using the most memory on my system - 14 % (140 mb i guess)
Is there a way to lower that down little bit? thanks..

**Comment by morpheus65535** [comment]
I'm going to try to see if I can lower memory consumption in normal situation but when we parse JSON from Sonarr and Radarr it take lot of memory and I guess you'll get into the same situation... :-/

**Comment by Dr0bac** [comment]
I was thinking, so if the problem is within swap file, i don't have problem with active memory usage, i have problem with cached memory that it is stored in swap file, because ram is full with cache..
I guess that's why my ext hdd is kept awaken after few days after system is powered on.
Maybe bazarr have problem like jackett did?
https://github.com/Jackett/Jackett/issues/4966

I'm just guessing, I know very little about linux systems..

**Comment by morpheus65535** [comment]
Yes but I need to investigate why we use that much cached memory. It's not a problem most of the time but in your case, it's less than ideal.

**Comment by Dr0bac** [comment]
After few days, swap file begin to fill. Bazarr active memory consumption is really low (i have zero movies and tv shows in radarr/sonarr at the moment) i don't know if bazarr memory will be higher if i have good amount of movies and tv shows..
In "top" i looked at VIRT and plex and bazarr are using most of that 300 and 250 mb i guess. but radarr and sonarr are not far from them maybe at 150-200 mb.

I disabled swap file.. I think i can live without it.

![gfgfg](https://user-images.githubusercontent.com/43797966/58132753-6bc02e80-7c22-11e9-80de-06263014f98e.png)

**Comment by morpheus65535** [comment]
My guess is that cached memory will increase when you’ll start to parse JSON from Sonarr/Radarr and analyze video file for embedded subtitles.

**Comment by morpheus65535** [comment]
Is this still an issue?

**Comment by Dr0bac** [comment]
I disabled swap file that was on my ext hdd so i it doesn't wake anymore. About amount of cached memory that bazarr is using i didnt looked into that after i disabled swap file

**Comment by morpheus65535** [comment]
Thanks for the feedback. I'll close this issue but you can reopen it if you face it again. I'll rework some part of Bazarr in the next month to reduce memory usage.
