### ISSUE TITLE
Error saving subtitles to disk

### ISSUE THREAD

**Issue by jaretclifton** [morpheus65535/bazarr#431]
**Describe the bug**
It appears there may be a bug in how Bazarr is parsing the "Bazarr path" to a TV show as it uses a different path than Sonarr (Sonarr is running on a windows host, Bazarr is on a Ubuntu 18.04 container).

The path appears to be correct except for a few additional characters and a trailing backslash after the entire path/filename. The correct path is "/media/fs01/TV Shows/SERIES/SEASONXX/EPISODE". There is no "u/" before /media. See log entry below.

**Software (please complete the following information):**
Bazarr version
0.7.5
Sonarr version
3.0.1.493
Radarr version
0.2.0.1344
Operating system
Linux-4.15.18-14-pve-x86_64-with-Ubuntu-18.04-bionic
Python version
2.7.15rc1
Bazarr directory
/
Bazarr config directory
/opt/bazarr/data

**Additional context**
Traceback (most recent call last):
 File "/opt/bazarr/bazarr/get_subtitle.py", line 176, in download_subtitle
  path_decoder=force_unicode
 File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 848, in save_subtitles
  with open(subtitle_path, \w\) as f:
IOError: [Errno 2] No such file or directory: u\/media/fs01/TV Shows/SEAL Team/Season 01/SEAL Team - S01E18 - Credible Threat.srt\

**Comment by jaretclifton** [comment]
Note: This only happens on a few shows while it works perfectly on others. There does not seem to be a clear pattern as to what series triggers the failure, but when it does fail, multiple of the same series fail in succession.

**Comment by morpheus65535** [comment]
You probably have misconfigured your path mapping. Did you first spoke with the support team on Discord?

**Comment by jaretclifton** [comment]
I haven't spoken with them because I don't believe it to be a misconfiguration. It works perfectly with almost every show. The base path is correct and subtitles get dropped in correct folders for most shows. It seems there is an issue possibly parsing some show locations but not all.

**Comment by morpheus65535** [comment]
`u` before the path means it's a Unicode string and the trailing backslash is only used in logs as a line feed indicator.

Many users are using Bazarr and Sonarr the same way you do. Please provide a screenshot of your path mapping configuration so we can double check it.

**Comment by jaretclifton** [comment]
![image](https://user-images.githubusercontent.com/20193366/57640997-c666e400-75ab-11e9-8181-de85aec00f22.png)

**Comment by jaretclifton** [comment]
Sonarr full path: \\fs01.midland.local\Storage\TV Shows
Radarr full path: \\fs01.midland.local\Storage\Movies

**Comment by jaretclifton** [comment]
As you can see, some paths show as correct while some do not:

![image](https://user-images.githubusercontent.com/20193366/57641092-06c66200-75ac-11e9-956e-ca25fc0d84ab.png)

**Comment by morpheus65535** [comment]
Does those with a exclamation mark actually have a directory created and accessible on disk?

**Comment by jaretclifton** [comment]
All of them that Bazarr has tried to download subtitles for do indeed have a folder with that exact path available. I can ssh to the host, copy and paste that path and can see the exact file referenced in the logs.

**Comment by morpheus65535** [comment]
Can you send me in private on Discord a complete debug log and a copy of your bazarr.db? I'm curious to understand what is the issue here...

**Comment by morpheus65535** [comment]
Of course path on Linux are case sensitive. What happen if you remove `Seal Team` from Sonarr, add it again and force Series and Episode sync? Does it fix your issue?

**Comment by jaretclifton** [comment]
I'm aware Linux is case sensitive, that's why I mentioned it. I renamed the folder to SEAL team and Bazarr is happy. However, a correctly named folder for Into the Badlands is experiencing a Unicode encoding error and failing to save the file.

![image](https://user-images.githubusercontent.com/20193366/57684325-7892c000-762d-11e9-99db-19aded14a664.png)

**Comment by morpheus65535** [comment]
Can you provide the output from `python -c "import sys; print sys.getfilesystemencoding()"`?

**Comment by jaretclifton** [comment]
python -c "import sys; print sys.getfilesystemencoding()"
ANSI_X3.4-1968

**Comment by morpheus65535** [comment]
@Pannal is it related to https://github.com/pannal/Sub-Zero.bundle/issues/70?

**Comment by phampyk** [comment]
I was having the same problem, but kept trying and found the reason why. When you create the container you already give the path /media/series/ to /tv/ so when you put the bazarr path you need to put /tv/ only. 
That fixed it for me :) 
You need to put the path you give to your container, not the original path of the ubuntu filesystem

**Comment by phampyk** [comment]
I managed to fix it!!
So I've got a synology with series in /volume2/series and an ubuntu with bazarr and path to shows /media/series.
First of all when you make the docker container you give a path to tv shows called /tv/ (mine pointed to /media/series/) so when you do the start config instead of putting /media/series for the show you need to put only /tv/.

Then I had problem with some of the shows, so I checked and it was a problem of permissions of those folders, but not in ubuntu, but my synology. I gave writting permissions and now everything works as it should.
Hope it helps! :)

**Comment by pannal** [comment]
@morpheus65535 not really, his filesystem encoding is essentially ASCII and should be fixed inside his environment to something modern like UTF-8.

**Comment by morpheus65535** [comment]
In that case I'm going to close this one as it is related to an uncommon environment.
