### ISSUE TITLE
Save settings Error: 500 Internal Server Error

### ISSUE THREAD

**Issue by teodorch85** [morpheus65535/bazarr#435]
When trying to save settings i get this error. 
I use linuxserver latest server docker.
I tried to delete releases.txt, restart and wait 6 hours (the file was re-created) but didn't help.

>Sorry, the requested URL 'http://192.168.1.2:6767/save_settings' caused an error:

Internal Server Error

Exception:

KeyError('HTTP_REFERER',)

Traceback:

Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 137, in wrapper
    return func(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 1186, in save_settings
    ref = request.environ['HTTP_REFERER']
KeyError: 'HTTP_REFERER'

> 
Bazarr version
0.7.4
Sonarr version
2.0.0.5322
Radarr version
0.2.0.1344
Operating system
Linux-4.19.41-Unraid-x86_64-with
Python version
2.7.15
Bazarr directory
/run/s6/services/bazarr
Bazarr config directory
/config

**Comment by morpheus65535** [comment]
There's 3 possible reasons for that error:
- You're trying to access the `/save_settings` URL directly (maybe by refreshing);
- You're using a reverse proxy that do not forward the  `http_referer` headers;
- You're are using some security software that prevent your browser to send the same headers. You can use private navigation mode to be sure no extension interfere.

**Comment by teodorch85** [comment]
>     * You're are using some security software that prevent your browser to send the same headers. You can use private navigation mode to be sure no extension interfere.

That was it!
I had already disabled all security addons on Firefox but the problem remained.
I tried private navigation with firefox and nothing changed.

I lastly used EDGE browser and it worked!

Thank you!
