### ISSUE TITLE
Unsupported language code for subscene

### ISSUE THREAD

**Issue by math625f** [morpheus65535/bazarr#436]
**Describe the bug**
When I try having Bazarr search for subtitles for the two movies "Iron Man 3" and "Guardians of Galaxy Vol. 2" I get the same error. Bazarr was able to find subtitles for 16 other movies with the exact same options. 
Log error:

```
Unexpected error in provider 'subscene': 
  Traceback (most recent call last): 
    File "C:\Users\User\Documents\bazarr\bazarr\../libs/subliminal_patch\core.py", line 162, in list_subtitles_provider 
      results = self[provider].list_subtitles(video, provider_languages) 
    File "C:\Users\User\Documents\bazarr\bazarr\../libs/subliminal_patch\providers\subscene.py", line 151, in list_subtitles 
      return [s for s in self.query(video) if s.language in languages] 
    File "C:\Users\User\Documents\bazarr\bazarr\../libs/subliminal_patch\providers\subscene.py", line 242, in query 
      subtitles += self.parse_results(video, film) 
    File "C:\Users\User\Documents\bazarr\bazarr\../libs/subliminal_patch\providers\subscene.py", line 179, in parse_results 
      subtitle = SubsceneSubtitle.from_api(s) 
    File "C:\Users\User\Documents\bazarr\bazarr\../libs/subliminal_patch\providers\subscene.py", line 50, in from_api 
      return cls(Language.fromsubscene(s.language.strip()), s.title, hearing_impaired=s.hearing_impaired, 
    File "C:\Users\User\Documents\bazarr\bazarr\../libs/subzero\language.py", line 62, in inner 
      instance = f(cls, base, *args, **kwargs) 
    File "C:\Users\User\Documents\bazarr\bazarr\../libs/subzero\language.py", line 118, in fromcode 
      return Language(*Language_.fromcode(code, converter).__getstate__()) 
    File "C:\Users\User\Documents\bazarr\bazarr\../libs/babelfish\language.py", line 109, in fromcode 
      return cls(*language_converters[converter].reverse(code)) 
    File "C:\Users\User\Documents\bazarr\bazarr\../libs/subliminal_patch\converters\subscene.py", line 76, in reverse 
      raise ConfigurationError('Unsupported language code for subscene: %s' % code)
ConfigurationError: Unsupported language code for subscene:
```

**To Reproduce**
Use subscene to find Danish subtitles for the two movies mentioned.

**Expected behavior**
The expected behaviour is to have Bazarr find the subtitles succesfully.

**Software (please complete the following information):**
 - Bazarr: 0.7.5
 - Radarr version: 0.2.0.1344
 - OS: Windows 10 Pro

**Comment by pannal** [comment]
Can you get me the subtitle link from subscene from those files? The language code is empty.

**Comment by math625f** [comment]
I'm not entirely sure what you're asking, so here's a paste of a cleaned log for you. As you can see from the log, it seems to me it's finding another movie than Iron Man 3, "The Caged Flower", and I'm assuming this is what's causing the issue? I didn't spot this when I originally posted about this issue.
[Log](https://pastebin.com/WkTJtRx8)

**Comment by morpheus65535** [comment]
@pannal Something else we can do for this one?

**Comment by morpheus65535** [comment]
Can you try the dev branch? Don't forget to define a username and password for Subscene in settings and provide an anti-captcha provider.

**Comment by math625f** [comment]
I'm already on the dev branch. I haven't tested it in the last couple of days though, but I'll report back when I get home.

As for anti-captcha provider, I didn't realise Subscene required one? I was able to download the other subtitles without one, has that changed?

**Comment by morpheus65535** [comment]
As they are using cloudflare, yes, anti-captcha could be required. You can try without but if they ask for a captcha to be solved, you're going to be fu****...

**Comment by math625f** [comment]
The update fixed the issue with the original movie I was having problems with, but a nearly identical issue is now present with another movie (This time it's two Harry Potter Movies)

`Traceback (most recent call last): File "C:\Users\User\Documents\bazarr\bazarr\../libs/subliminal_patch\core.py", line 162, in list_subtitles_provider results = self[provider].list_subtitles(video, provider_languages) File "C:\Users\User\Documents\bazarr\bazarr\../libs/subliminal_patch\providers\subscene.py", line 216, in list_subtitles return [s for s in self.query(video) if s.language in languages] File "C:\Users\User\Documents\bazarr\bazarr\../libs/subliminal_patch\providers\subscene.py", line 325, in query subtitles += self.parse_results(video, film) File "C:\Users\User\Documents\bazarr\bazarr\../libs/subliminal_patch\providers\subscene.py", line 245, in parse_results subtitle = SubsceneSubtitle.from_api(s) File "C:\Users\User\Documents\bazarr\bazarr\../libs/subliminal_patch\providers\subscene.py", line 60, in from_api return cls(Language.fromsubscene(s.language.strip()), s.title, hearing_impaired=s.hearing_impaired, File "C:\Users\User\Documents\bazarr\bazarr\../libs/subzero\language.py", line 62, in inner instance = f(cls, base, *args, **kwargs) File "C:\Users\User\Documents\bazarr\bazarr\../libs/subzero\language.py", line 118, in fromcode return Language(*Language_.fromcode(code, converter).__getstate__()) File "C:\Users\User\Documents\bazarr\bazarr\../libs/babelfish\language.py", line 109, in fromcode return cls(*language_converters[converter].reverse(code)) File "C:\Users\User\Documents\bazarr\bazarr\../libs/subliminal_patch\converters\subscene.py", line 76, in reverse raise ConfigurationError(Unsupported language code for subscene: %s % code)ConfigurationError: Unsupported language code for subscene: Cambodian/Khmer`

Still didn't have any problems with Captcha, but I'm guessing it's only a matter of time...
Don't spend too much energy on this issue, it's only about 1/5 movies I'm unable to find subtitles for automatically, I can do it myself in these cases :)

**Comment by pannal** [comment]
That should only be a log entry by now, if you're running develop, not a real Traceback.

**Comment by math625f** [comment]
![image](https://user-images.githubusercontent.com/22494364/59961000-6aa84880-94d1-11e9-8aec-8d12c393057a.png)
I don't know what to tell you, as you can see on the image, I have selected the development branch, and it's telling me that no new updates are available, and that is the error I am getting.

**Comment by morpheus65535** [comment]
Did you receive any update to Bazarr in the last weeks?

**Comment by math625f** [comment]
Hi! I just returned from being away from my computer.

After updating bazarr this is the new error I am getting:

`Traceback (most recent call last): 
   File "C:\Users\User\Documents\bazarr\bazarr\../libs/subliminal_patch\core.py", line 260, in download_subtitle self[subtitle.provider_name].download_subtitle(subtitle) 
   File "C:\Users\User\Documents\bazarr\bazarr\../libs/subliminal_patch\providers\subscene.py", line 257, in download_subtitle archive = ZipFile(archive_stream)
   File "C:\Python27\lib\zipfile.py", line 793, in __init__ self._RealGetContents() 
   File "C:\Python27\lib\zipfile.py", line 834, in _RealGetContents raise BadZipfile, "File is not a zip file"BadZipfile: File is not a zip file`

**Comment by morpheus65535** [comment]
Did you subscribe to an anti-captcha provider?

**Comment by math625f** [comment]
No - I'm currently not in a position where I'm willing to pay to download my subtitles, I'll do it manually instead.

Thank you for your time and support, I'll mark this issue as closed :)
