### ISSUE TITLE
Subtitle gets downloaded over and over

### ISSUE THREAD

**Issue by thyeestes** [morpheus65535/bazarr#44]
I have one subtitle that gets downloaded over and over. I configured Bazarr to download only Dutch subtitles (single language). In every run it downloads the subtitle from opensubtitles, but then it gets marked as 'Af' Afrikaans. When I open the SRT file it look perfectly Dutch to me.

**Comment by morpheus65535** [comment]
Can you send me the subtitles file so I can run unit test on it?

**Comment by thyeestes** [comment]
[Queen of the South - S01E03 - Estrategia de Entrada.zip](https://github.com/morpheus65535/bazarr/files/1661364/Queen.of.the.South.-.S01E03.-.Estrategia.de.Entrada.zip)
This is the one which is seen as Afrikaans.

Thanks.

**Comment by morpheus65535** [comment]
You're right. Subliminal cannot detect the language soo Bazarr fall back to manual detection. I've incresed the number of lines used to detect language from 20 to 100 and now it's fine: 6134d88f7fc6f5e8b699162d3ec9a8d7096dc321

You can update and restart bazarr.

**Comment by thyeestes** [comment]
Thanks a lot. That solved the problem.
