### ISSUE TITLE
Bazarr does not auto downloading subtitles

### ISSUE THREAD

**Issue by shudack** [morpheus65535/bazarr#440]
**Describe the bug**
New movies that sonarr/radatr grabs show in subtitle wanted list, but they don't auto download.

**To Reproduce**
If I go into wanted list I can manually download them, but the movie continues shows in wanted list.

**Expected behavior**
Auto download the subtitles to series/movies folder.

**Screenshots**
Force missing subtitles:
![image](https://user-images.githubusercontent.com/17851196/58269970-945e3a80-7d80-11e9-9830-24b131fdcb08.png)

Manual Download:
![image](https://user-images.githubusercontent.com/17851196/58269921-7690d580-7d80-11e9-8f80-daab5623eb38.png)

**Software (please complete the following information):**
- Bazarr: 0.7.4
- Radarr version 0.2.0.1344
- Sonarr version 2.0.0.5322
- OS: Linux 4.9.177-28 aarch64-with-Ubuntu-18.04-bionic
- Python version: 2.7.15rc1

**Additional context**
Can you help? I can provide more information.

Best regards,
Shudack

**Comment by shudack** [comment]
Solved! Problem in path permissions

**Comment by talpazzo** [comment]
shudack can you elaborate? I have the same problem. Thank you

**Comment by shudack** [comment]
Come to Discord and morpheus65535 will help you configure it properly. My problem was in path to folder permissions, I used 755 on folders I want for subtitles.

**Comment by talpazzo** [comment]
@shudack thank you
