### ISSUE TITLE
Death by captcha "AccessDeniedException"

### ISSUE THREAD

**Issue by romquenin** [morpheus65535/bazarr#443]
Bonjour @morpheus65535 ! Merci de continuer a developper "bazarr" c'est vraiment top.

J'ai un souci avec le service "death by captcha" sur lequel je me suis inscrit pour je l'espère enfin récupérer les sous titres de "addic7ed".
Bien que j'ai plusieurs fois vérifié mon password et redémarrer "bazarr", malheureusement cela ne fonctionne pas.

J'utilise l'image docker "linuxserver" ver.0.7.4 sur un nas "synology"

![Screenshot 2019-05-25 at 12 59 25](https://user-images.githubusercontent.com/34734431/58368411-02c00b80-7eed-11e9-9b1b-7ae75eb100b4.png)

Merci pour ton aide.

**Comment by morpheus65535** [comment]
Est-ce que tu as essayé avec un mot de passe contenant uniquement des caractères "simple"? J'ai l'impression que tu dois avoir un caractère qui est mal enregistré ou lu depuis le fichier de config.ini.

**Comment by romquenin** [comment]
Mon mot de passe était "DEATHbycaptch4". Je viens de le modifier pour quelque chose de plus simple, cela ne fonctionne toujours pas avec les mêmes erreurs sur le log.

**Comment by morpheus65535** [comment]
J'ai beau essayer, je n'arrive pas à reproduire. Ça fonctionne bien avec mon username/password. Je ne vois pas d'autres possibilités qu'une erreur de saisie de ton côté. :-/

**Comment by romquenin** [comment]
Je vais continuer d'essayer différents password.

Merci encore pour ton aide.

**Comment by morpheus65535** [comment]
C’est sois le username, sois le mot de passe mais, chose certaine, il y a quelque chose qui ne va pas.

**Comment by morpheus65535** [comment]
Du nouveau?

**Comment by romquenin** [comment]
Bonjour @morpheus65535 ! Malheureusement non, Bazarr ne veut pas accepter mes username et password. J'ai contacter la team DBP pour être sur d'utiliser le bon username et ils m'ont confirmé que oui. Je t'avoue que je suis coincé sans comprendre pourquoi.
Si tu as besoin d'informations complémentaires je serais ravi de te les fournir.
Merci pour ton retour et pour ce merveilleux logiciel.

**Comment by morpheus65535** [comment]
Passes me voir sur Discord et on fera une séance TeamViewer.
