### ISSUE TITLE
Missing Zimuku provider in wizard installer

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#447]
In the installer wizard, there are less providers than in settings (after completing the wizard). I found Zimuku is missing.
I saw you have 2 template files, one for each page. This could be hard to maintain. You should put the providers in a new template and import if from both templates, if the template framework allows it.

**Comment by halali** [comment]
I dont think this template allow blueprints

**Comment by morpheus65535** [comment]
Yes just look at how I import menu.tpl in each page. I think that having an imported providers.tpl could be a good idea.

**Comment by morpheus65535** [comment]
This is fixed in dev branch.
