### ISSUE TITLE
Run custom script after download

### ISSUE THREAD

**Issue by peskdale** [morpheus65535/bazarr#45]
It would be nice to be able to run a custom script after the download of a subtitle file. This would ideally work in a similar way to Sonarr, with variables such as filename and path that can be passed on for the script for use.

For example, I have a bash script that does some minor formatting adjustments to make them more compatible with my devices. I'm currently running this manually as needed.

**Comment by morpheus65535** [comment]
Please, feature requests should be posted to Feathub: https://feathub.com/morpheus65535/bazarr

Thanks!
