### ISSUE TITLE
[Bug] Unable to send telegram notifications

### ISSUE THREAD

**Issue by foux** [morpheus65535/bazarr#452]
**Describe the bug**
Unable to send notifications using telegram

**To Reproduce**
Set up telegram notifications following the Wiki.
Test the notifications

**Expected behavior**
we should receive a notification. But instead we get those errors in the log :  
`Could not load URL: tgram://_bot_token_/`

**Software (please complete the following information):**
 - Bazarr: v0.7.4
 - OS: Docker

**Additional context**
The telegram URL has been set following https://github.com/caronc/apprise/wiki with an URL in the format `tgram://_bot_token_/`

**Comment by madjo1983** [comment]
hi,

Any solution on this topic ?

Cheers,

**Comment by morpheus65535** [comment]
> hi,
> 
> Any solution on this topic ?
> 
> Cheers,

This issue have been solved 19 months ago. Please don't bring it back from the dead. You can find configuration instructions there: https://github.com/caronc/apprise/wiki/Notify_telegram

**Comment by HelderCFerreira** [comment]
tgram://_bot_token_/_chat_id
