### ISSUE TITLE
Hash match is ignored for opensubtitles provider

### ISSUE THREAD

**Issue by MoshiMoshi0** [morpheus65535/bazarr#453]
For subtitles searched by opensubtitles ~~or napiproject (and probably others)~~ i am getting this debug message:
`Ignoring hash as other matches are wrong (missing: set([...])) and (<...>)`

Looking at the source [here](https://github.com/morpheus65535/bazarr/blob/59ac0a8b910189c6a958270e91080aab16560e81/libs/subliminal_patch/score.py#L64-L83) it seems like the episode is required to have this matches: `{"series", "season", "episode", "format"}` to have a valid hash match. ~~This ignores the fact that some providers might not return a match for all of those. For example `Napisy24` is 100% hash matched as the api does not return any other data.~~ (this code is only for opensubtitles)

Looking further into other providers some of them use `guess_matches` function to fill in guessed matches from guessit, like so:
`matches |= guess_matches(video, guessit(release, {'type': 'episode', "single_value": True}))`
This probably should be added to all providers or run globally in [compute_score (score.py)](https://github.com/morpheus65535/bazarr/blob/59ac0a8b910189c6a958270e91080aab16560e81/libs/subliminal_patch/score.py#L32).

But even if this was added there still exists a case where a filename is simple (like Title - SXXEXX.mkv) so guessit wont guess all required matches for the hash to be included.

**Software:**
 - Bazarr: v0.7.4
 - OS: docker image

**Comment by morpheus65535** [comment]
Regarding guessit result that could be incomplete, we refine the video object with metadata from Sonarr/Radarr.

For the rest, maybe @pannal can give us some insight.

**Comment by MoshiMoshi0** [comment]
Dug a little deeper and I maybe know what is happening? It seems like the uploaded file on opensubtitles has bad name (`Suits - 8x15 - Stalking Horse 720p -AVS.txt`) so guessit is not able to extract the format from the file that is required for the hash.

Opensubtitles runs `guess_matches` only on the subtitle filename and release name (pretty much always the same). Partial fix would be to also run `guess_matches` on the video filename which should have the format included in `compute_score` like I mentioned above. Full fix would be to maybe add a option called "strict hash" that would determine if the `{"series", "season", "episode", "format"}` matches are required for the hash to be valid. 

But I think this is what `hash_verifiable` is for that I asked about in another issue. It is only used in opensubtitles provider. This should be controlled be in the gui and not hardcoded to true. 
Also imo this whole portion of code could be moved to opensubtitles provider and the whole `hash_verifiable` should be removed from the base `Subtitle` class:

https://github.com/morpheus65535/bazarr/blob/59ac0a8b910189c6a958270e91080aab16560e81/libs/subliminal_patch/score.py#L64-L83

As "hash verifiable" can mean different things for different providers.

**Comment by MoshiMoshi0** [comment]
Do you want me to create a PR with this feature? It will move the whole `hash_verifiable` code to opensubtitles because it is only used by that provider, and add a configuration option to enable/disable hash verification.

It will modify subliminal_patch, I guess you wont merge that without pannal aproval?

**Comment by morpheus65535** [comment]
@MoshiMoshi0 Thanks for the suggestion. I would attach with @pannal first and submit your PR to https://github.com/pannal/Sub-Zero.bundle/tree/develop-2.6/Contents/Libraries/Shared/subliminal_patch. We'll merge it to Bazarr after that.

**Comment by pannal** [comment]
What purpose does running `guess_matches` on your local video filename serve?

There should simply be an option to skip hash verification, otherwise that completely defeats the purpose of the hash verification itself (OS returns *many* badly tagged subs).

**Comment by MoshiMoshi0** [comment]
> What purpose does running guess_matches on your local video filename serve?

Yea I think this would be wrong, I wanted to get the matches from the filename as a backup.
But we want to match the subtitle to the file so that would generate false positives.

> There should simply be an option to skip hash verification, otherwise that completely defeats the purpose of the hash verification itself (OS returns many badly tagged subs).

Yes that would be the easy way, but do you do this option globally or per provider? If you do this globally then you cant run the hash verification for one provider but not the other. If you do this per provider this adds a config option for each one, and a lot of duplicated html code in bazarr.

> Why move the hash_verifiable stuff to OS, though? There might be other providers in the future that need that.

My reasoning is that each provider might have different concept of what a hash verification is. 

I think it would be better to move the `hash_verifiable` code to OS `get_matches` to cleanup the code since no other provider is using it anyway. And just return empty matches if we want to invalidate the subtitle.

Or maybe move it to a new method `verify_matches(video, matches)` but I dont think it is necessary to add another method when this can be done in `get_matches`

This way the validation code is in the provider class, and it is more generic. Also then you dont have to change any core functions if you want to make a change in hash verification, you just change the provider code.

There is also this code that is kinda duplicate of the code in `score.py` i posted above:
https://github.com/morpheus65535/bazarr/blob/a0e7e63286f2a9af929bfcc21280f1193588c952/libs/subliminal_patch/core.py#L394-L407

and in bazarr:
https://github.com/morpheus65535/bazarr/blob/a0e7e63286f2a9af929bfcc21280f1193588c952/bazarr/get_subtitle.py#L300-L308

You remove the hash match in `compute_score` but then ignore the subtitle anyway.

All this imo adds way too much complexity for a thing that should be determined by the providers.

**Comment by morpheus65535** [comment]
@pannal What do we do for this one?

**Comment by morpheus65535** [comment]
@MoshiMoshi0 I'll close this one as we don't have feedback from pannal but if you feel there's still something to do here, feel free to reopen it. Thanks!

**Comment by admiralfalco** [comment]
was there ever any movement on this. I'm stuck with the hash failing. Am I missing something rediculous on how to bypass different checks on the search? Could this not simply a bypass check panel on the profile?

**Comment by morpheus65535** [comment]
> was there ever any movement on this. I'm stuck with the hash failing. Am I missing something rediculous on how to bypass different checks on the search? Could this not simply a bypass check panel on the profile?

There's no bypass, you reduce your minimum score. Get to Discord for support.
