### ISSUE TITLE
SyntaxError: Missing parentheses

### ISSUE THREAD

**Issue by algarih** [morpheus65535/bazarr#458]
**Describe the bug**
so i have followed the installation instruction
and i get this message :

> C:\bazarr>python bazarr.py
  File "bazarr.py", line 19
    print "Bazarr starting..."
                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Bazarr starting...")?

**Software (please complete the following information):**
 - Bazarr: lateast version
 - Radarr lateast version
 - Sonarr lateast version
 - OS:  Windows 10

**Comment by morpheus65535** [comment]
Bazarr isn’t compatible with Python 3.x. Please read the wiki.

**Comment by algarih** [comment]
thank you for such a quick reply, i'm gonna install an old version now
