### ISSUE TITLE
Assrt not working?

### ISSUE THREAD

**Issue by madcowGit** [morpheus65535/bazarr#460]
(sorry, i clicked back/forward and the form must have reset)

**Describe the bug**
When I search for chinese subtitles (with assrt), manually or automatically I dont get any results and I doubt if it is working

**To Reproduce**
I have as assrt API key
I configured bazarr
when I click manual download i see no results

**Expected behavior**
Expect some results because i get some results when i manually search from the website.

**Software (please complete the following information):**
 - Bazarr: [v 0.7.5]
 - Radarr version [0.2.0.1344]
 - Sonarr version [2.0.0.5322]
 - OS: [Synology DSM. Running from Docker with linuxserver.io Bazarr image]

**Additional context**
added is the debug log where I forced a manual search for an episode of Chernobyl
[bazarr (2).log](https://github.com/morpheus65535/bazarr/files/3258573/bazarr.2.log)

**Comment by morpheus65535** [comment]
Please complete the required information in issue template and provide a debug log.

**Comment by madcowGit** [comment]
(edit my post)

**Comment by morpheus65535** [comment]
`HTTPError: 400 Client Error: Bad Request for url: https://api.assrt.net/v1/sub/search?q=Chernobyl+S01E05&token=3CvHVYqXZfiexXjqKoMCRoujiCnSaaEm&is_file=1`

They probably have changed something on the site but as I don't read a single word of Chinese, I don't know how to fix it... :-/

**Comment by madcowGit** [comment]
What can I do to help? If I manually check the link I get a page with:
{"status":20001,"errmsg":"invalid token"}

**Comment by morpheus65535** [comment]
Please provide a new debug log.

**Comment by madcowGit** [comment]
[bazarr (3).log](https://github.com/morpheus65535/bazarr/files/3267084/bazarr.3.log)

**Comment by morpheus65535** [comment]
That's strange, we should see those 8 potentials subtitles in debug log and the provider is terminated after the search is initiated. Could you try the same thing but only keep assrt provider enabled?

**Comment by madcowGit** [comment]
[bazarr (4).log](https://github.com/morpheus65535/bazarr/files/3268268/bazarr.4.log)

**Comment by madcowGit** [comment]
alternatively, do you have a docker image that you suggest i can try out?

**Comment by morpheus65535** [comment]
@madcowGit This is definitely not an issue with the Docker image you are using. It's the official one.

@pannal There's something wrong with Assrt provider. It's expecting a language code like this:
```
<type 'dict'>: {u'lang': {u'langlist': {u'langchs': True, u'langdou': True, u'langcht': True, u'langeng': True}, u'desc': u'\u82f1 \u7b80 \u7e41 \u53cc\u8bed'}, u'videoname': u'Jumanji.Welcome.to.the.Jungle.2017.BluRay.720p.x264.AC3-CMCT', u'upload_time': u'2018-05-06 13:05:10', u'vote_score': 0, u'release_site': u'CMCT', u'subtype': u'SSA', u'native_name': u'\u52c7\u6562\u8005\u7684\u6e38\u620f\uff1a\u51b3\u6218\u4e1b\u6797.Jumanji.Welcome.to.the.Jungle.2017.BluRay.720p.x264.AC3-CMCT.\u7b80\u7e41\u82f1\u53cc\u8bed\u5b57\u5e55', u'id': 631037, u'revision': 0}
```
And we are providing this:
```
language = {Language} zh-Hant
 alpha3 = {str} 'zho'
 basename = {unicode} u'zh-Hant'
 country = {NoneType} None
 forced = {bool} False
 script = {Script} Hant
  code = {str} 'Hant'
  name = {unicode} u'Han (Traditional variant)'
```
Could you take a look?

**Comment by morpheus65535** [comment]
Probably related to #349

**Comment by pannal** [comment]
Is this still an issue? I can find subs for that exact name.

**Comment by madcowGit** [comment]
Yes.
I just tried a manual search and I am getting a no results from assrt

**Comment by madcowGit** [comment]
@pannal 
could it be a locale issue? Are you also running bazarr from a docker container?

is there a way to get extended logging to see what's going on?

**Comment by morpheus65535** [comment]
@madcowGit As per Linux Server policies, there is no way of updating the software inside the container. Each time a new release of Bazarr is made available, LSIO build a new image with the new version of Bazarr. So, yes, you should pull the new version of the image. 0.8 should be released within a week FYI.

**Comment by morpheus65535** [comment]
Is this still an issue?

**Comment by madcowGit** [comment]
I just tried 0.8.1 and still dont get any subtitles from assrt

**Comment by morpheus65535** [comment]
you have other providers that are working?

**Comment by madcowGit** [comment]
I tested some. I get subtitles from: opensubtitles, supersubtitles, tvsubtitles, podnapsi, zimuku

**Comment by morpheus65535** [comment]
So there's something wrong with this provider. @pannal is there an updated version of this provider in sub-zero?

**Comment by pannal** [comment]
I'll have a look when I'm back from vacation (little over a week). There haven't been any changes to assrt in subliminal_patch for over a year.

**Comment by dimotsai** [comment]
Hi guys,

The provider was initially written in SubZero by me. But I haven't been using Plex/SubZero for quite a long time. 😛 (I've moved to Emby by the way)

There are two main types of Chinese subtitles in this website, `zh-Hant` and `zh-Hans`, which represent Chinese written in Traditional and Simplified scripts respectively.
It seemed that Bazarr doesn't support IETF language tags with different scripts. So OP's setting `zh` would never match `zh-Hans` from Assrt.

Here is the example:
Since `Assrt` does not use standard language code, `chs` was converted to `zh-Hans` in IETF language tag by the `assrt` converter in `subliminal_patch`.
```
         {
            "subtype":"SSA",
            "id":632151,
            "lang":{
               "desc":"英 简 双语",
               "langlist":{
                  "langeng":true,
                  "langchs":true,
                  "langdou":true
               }
            },
            "vote_score":0,
            "upload_time":"2019-06-07 16:27:13",
            "native_name":"切尔诺贝利 (2019).Chernobyl.S01 第一季全",
            "videoname":"web h.264\/ 265 tbs",
            "release_site":"Orange字幕组",
            "revision":0
         },
```

And then `assrt` provider started matching the language code to the Bazarr's setting:
```
24/11/2019 02:42:43|DEBUG   |subliminal_patch.providers.assrt|Check if <Language [zh-Hans]> in set([<Language [zh]>])|
```
Sadly, there is way these two would match...

Don't know if we should consider `zh-Hans` and `zh` or `zh-Hant` and `zh` as the same thing?
SubZero did support IETF language tags if I remember correctly.

**Comment by dimotsai** [comment]
@pannal @morpheus65535 Any thought? I can help with the patch if you want.

**Comment by morpheus65535** [comment]
HEy @dimotsai. Thank you for your time. Bazarr is getting language from `pycountry.languages`: https://github.com/morpheus65535/bazarr/blob/1f8b5bd2e19fee20abd245334c7a72a7913af20d/bazarr/get_languages.py#L13

We are already adding Brazilian Portugal so we can probably manage to have language tags. I would totally be open to a PR for this. I don't have time to do it by myself.

Thanks!

**Comment by dimotsai** [comment]
OK. I would implicitly convert zh-Hans and zh-Hant to zh for now if selected language is Chinese (without script). The behavior should be compatible with or without script tag. An user should be able to select specific language scripts after your change.

**Comment by morpheus65535** [comment]
Thanks. I’m waiting for your PR.

**Comment by morpheus65535** [comment]
@dimotsai PR have been merged to dev branch. Thanks to him!

@madcowGit Please confirm if ti fixes the issue for you.

@pannal I'm not sure how it's gonna fit with Subzero but I guess you'll want to exclude this from upstream.

**Comment by madcowGit** [comment]
@morpheus65535 could you help me with some instructions? 
I downloaded the latest docker image from linuxserver/bazarr. That gives me version 0.8.3.4. I am not getting any subtitles from assrt.net. But I have a feeling this is not the right version to test with

**Comment by madcowGit** [comment]
Great it works! Thanks for all your help.

I tested the latest development docker image from linuxserver

**Comment by morpheus65535** [comment]
Thanks for the test!

I'll close this for this time but next you're free to do it by yourself once it's fixed! :-)
