### ISSUE TITLE
New Apprise version: Mattermost subpath support

### ISSUE THREAD

**Issue by ADIX7** [morpheus65535/bazarr#462]
There is a new version of Apprise that supports Mattermost in subfolder: caronc/apprise#116 
Currently I can't use bazarr with mattermost because I host it in a subfolder :(

**Comment by morpheus65535** [comment]
I've updated Apprise in dev branch. You can give it a try and give me your feedback please?

**Comment by ADIX7** [comment]
I wont have time today but hopefully I can test it on the weekend! (probably sunday)

**Comment by ADIX7** [comment]
I can confirm that the updates version works perfectly with mattermost installed in subfolder!

**Comment by morpheus65535** [comment]
Good news! Thanks for the feedback!
