### ISSUE TITLE
[Feature Request] check/test credentials for subtitle providers/Anti-captcha providers

### ISSUE THREAD

**Issue by TRaSH-** [morpheus65535/bazarr#464]
**Describe the solution you'd like**
A check credential button like we've with Sonarr/Radarr,
so you can test if the put in credentials are correct and you're able to connect to the subtitle provider

**Comment by morpheus65535** [comment]
This one would require major rework of subliminal_patch providers system. I don't see this in our plan at least while SZ still rely on subliminal_patch.

**Comment by TRaSH-** [comment]
isn't it possible to add a extra script that when pressing the test button to see if it's able to connect to that provider ?
i know of another subtitle search program also written in python that has that,
but not based on subliminal.

**Comment by morpheus65535** [comment]
That’s the point, it would need to be integrated to the providers engine in subliminal_patch.

**Comment by morpheus65535** [comment]
Feature Request have been moved to http://features.bazarr.media

Please go upvote so we can priorize your feature request.
