### ISSUE TITLE
[Feature Request] make the system/status page as the default start page

### ISSUE THREAD

**Issue by TRaSH-** [morpheus65535/bazarr#465]
**Describe the solution you'd like**
make the system/status page as the default start page,

**Comment by morpheus65535** [comment]
May I ask why? Personally, I haven't been on that tab for weeks...

**Comment by jaycedk** [comment]
Make a bookmark of the http://ip:port/system
Then you are only 1 click away :D

**Comment by morpheus65535** [comment]
I wont do this one. Sorry.
