### ISSUE TITLE
Can't set the right path for bazarr TV-Series (\\nas\TV-Series\)

### ISSUE THREAD

**Issue by behtjes** [morpheus65535/bazarr#466]
I have bazarr installed on my raspberry pi 3 (also running osmc on it). The only problem I have is the "this path doesn't seems to be valid" message. 

All my tv-series are on my synology NAS, in the same network. I can get access to my NAS on windows by typing in \\nas or  \\192.168.0.101 (I've also tried to enable the guest so no login is needed). But nothing seems to work:

I've tried several paths:
\\nas\TV-Series\
\\nas\
\\nas\volume1\TV-Series\
\\1\92.168.0.101\volume1\TV-Series\
nfs://192.168.0.101/TV-Series/

The sonarr path is:
/volume1/TV-Series/

What am I missing? A file sharing option on my Synology nas? Or a config setting in Bazarr?

**Comment by morpheus65535** [comment]
In path for **Sonarr**: `/volume1/TV-Series/`
In path for **Bazarr**: `\\192.168.0.101\TV-Series\`

Don't forget the trailing slash and backslash.

Restart Bazarr for that settings to take effect.

**Comment by behtjes** [comment]
Tried that. But it doesn't work. Could you take a look to see what's wrong? I've removed authentication for now: https://bazarr.advatise.nl

**Comment by morpheus65535** [comment]
Don't do this. Come to Discord instead and we'll fix it in no time.

**Comment by behtjes** [comment]
Im quite new to GitHub. What / where is discord?

**Comment by morpheus65535** [comment]
Discord is the chat platform where lives the community: https://discord.gg/MH2e2eb

**Comment by behtjes** [comment]
Ah ok! I'm going on vacation right now, so I'll contact you later! Thanks
