### ISSUE TITLE
[Feature Request] Tell Sonarr/Radarr which version to download based on available subtitles

### ISSUE THREAD

**Issue by sotiris-bos** [morpheus65535/bazarr#469]
**Is your feature request related to a problem? Please describe.**
I let sonarr and radarr download automatically based on quality. Sometimes, there is no available subtitle for the specific version (scene) but there are for other versions of the same quality. In that case, I either have to sync the subtitles myself it is usually easier and faster to just download a different version.

**Describe the solution you'd like**
I would like bazarr to be able to tell sonarr/radarr to download a version with available subtitles. I thought tags might be helpful but you cannot set per-episode tags on sonarr. Frankly, I have no idea how this could be implemented, I would just like it if it was possible.

**Describe alternatives you've considered**
Manually downloading different versions.

**Additional context**

**Comment by morpheus65535** [comment]
Feature Request have been moved to http://features.bazarr.media

Please go upvote so we can priorize your feature request.
