### ISSUE TITLE
Provider order of preference

### ISSUE THREAD

**Issue by sotiris-bos** [morpheus65535/bazarr#470]
**Is your feature request related to a problem? Please describe.**
I am getting a lot of false positives, mainly from opensubtitles where the wrong file gets uploaded either automatically or manually. I also need to use opensubtitles sometimes as I can't find proper subtitles anywhere else.

**Describe the solution you'd like**
Provider order of preference. Provider A is number 1, provider B is number 2, etc, opensubtitles is last (damn opensubtitles!). If there is a subtitle on No.1 that scores above the minimum, then download from No.1. If not, download from No.2 etc etc.

**Describe alternatives you've considered**
Disabling opensubtitles.

**Additional context**
This was mentioned here: https://github.com/morpheus65535/bazarr/issues/128 but might have been overlooked.

**Comment by morpheus65535** [comment]
It’s just not possible with subliminal as it is. There’s some scoring adjustments but nothing that we can configure.
