### ISSUE TITLE
[Feature request] Choose hour of Sonarr and Radarr full sync

### ISSUE THREAD

**Issue by Ansem93** [morpheus65535/bazarr#472]
**Is your feature request related to a problem? Please describe.**
By default Bazarr does a full sync at 4 and 5am. The problem is that my nas is sleeping at that hour.
I have my nas sleep while I'm not at home, so I would like to chat that hour to a different one.

**Describe the solution you'd like**
Under the the frequency choise, add a textbox to choose the hour.

**Additional context**
![immagine](https://user-images.githubusercontent.com/6626218/59563182-bf157900-9036-11e9-854c-ee91fc385691.png)

**Comment by morpheus65535** [comment]
Feature Request have been moved to http://features.bazarr.media

Please go upvote so we can priorize your feature request.
