### ISSUE TITLE
UnknownFPSError on each media file with subtitle in MicroDVD format

### ISSUE THREAD

**Issue by MoshiMoshi0** [morpheus65535/bazarr#473]
**Describe the bug**
The Video class does not seem to have its `fps` field populated anywhere. This causes any subtitle downloaded in MicroDVD format to fail the conversion to SRT.

**To Reproduce**
1. Download a subtitle that is in MicroDVD format
1. Subtitle conversion fails with the exception below

**Expected behavior**
The subtitle is downloaded and converted to SRT.

**Proposed solution**
My solution would be to add a new refiner that uses MediaInfo to read the fps from the media files. I could start work on a PR if this is accepted as solution, this will modify `subliminal_patch` package.

**Software:**
 - Bazarr: v0.7.5

**Additional Data**:
**Message:**
Couldn't convert subtitle to .srt format: Traceback (most recent call last): File "/app/bazarr/bazarr/../libs/subliminal_patch/subtitle.py", line 251, in is_valid subs = pysubs2.SSAFile.from_string(text, fps=self.plex_media_fps) File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 118, in from_string return cls.from_file(fp, format_, fps=fps, **kwargs) File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 152, in from_file impl.from_file(subs, fp, format_, fps=fps, **kwargs) File "/app/bazarr/bazarr/../libs/pysubs2/microdvd.py", line 42, in from_file raise UnknownFPSError("Framerate was not specified and "UnknownFPSError: Framerate was not specified and cannot be read from the MicroDVD file.

**Exception:**
Traceback (most recent call last): File "/app/bazarr/bazarr/../libs/subliminal_patch/subtitle.py", line 251, in is_valid subs = pysubs2.SSAFile.from_string(text, fps=self.plex_media_fps) File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 118, in from_string return cls.from_file(fp, format_, fps=fps, **kwargs) File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 152, in from_file impl.from_file(subs, fp, format_, fps=fps, **kwargs) File "/app/bazarr/bazarr/../libs/pysubs2/microdvd.py", line 42, in from_file raise UnknownFPSError("Framerate was not specified and "UnknownFPSError: Framerate was not specified and cannot be read from the MicroDVD file.

**Comment by morpheus65535** [comment]
Radarr provide the info trough their API and we could refine from there: https://github.com/morpheus65535/bazarr/blob/bed98832ed2a5b596265712bb3c0ac77d28ed264/bazarr/get_subtitle.py#L727

As for Sonarr, I unfortunately see no other way than using mediainfo binary but I would do it from `refine_from_db()` also.

What do you think about this?

**Comment by MoshiMoshi0** [comment]
The best way would be to do it as a refiner and preferably also add ability to the webui to enable/disable refiners.

I guess you guys really dont want to edit the `subliminal_patch` package for some reason.
In that case I think I would do it in a separate `refine_from_mediainfo` below the call to `refine_from_db` to not mix both refining methods here: 
https://github.com/morpheus65535/bazarr/blob/bed98832ed2a5b596265712bb3c0ac77d28ed264/bazarr/get_subtitle.py#L63-L67

But this needs to be optional as it will spin up the disks. The `get_video` method would need either access to the config or a new argument `use_mediainfo`.

**Comment by morpheus65535** [comment]
I agree that this should be an optional refiner (default to true?). `use_mediainfo` would be a good thing as we could need to use ti in the future. I would accept a PR on those terms. :-)

As for modifying `subliminal_patch`, it's still an upstream dependencies and any changes need to be done in sub-zero source code. As this change is only required in Bazarr (SZ refine from Plex who have the FPS), it shouldn't be done in subliminal_patch. Any issue that affect both are done directly in SZ code.

Thanks!

**Comment by MoshiMoshi0** [comment]
Fixed with #479
