### ISSUE TITLE
Don't download (better) subtitles if already watched

### ISSUE THREAD

**Issue by itavero** [morpheus65535/bazarr#475]
**Is your feature request related to a problem? Please describe.**
Not a real problem, but it would be nice if I could also have Bazarr know about my what I've already watched (via Plex for instance) so that it will no longer search for subtitles for the stuff I've already seen.

**Describe the solution you'd like**
Integrate with Plex Media Server (or perhaps also Trakt) to figure out which episodes and movies have been fully watched.
When they are fully watched, unmark them as Wanted.
This could even be a one time thing, so that, if you thought the subtitles that came with the download or via some other medium weren't that good, you can still mark them as wanted again (in case you share your PMS with other users).

**Describe alternatives you've considered**
So far, none, to be honest, other than manually changing the entry in Bazarr each time I've watched something.

**Comment by morpheus65535** [comment]
Feature Request have been moved to http://features.bazarr.media

Please go upvote so we can priorize your feature request.
