### ISSUE TITLE
Job "Update movies list from Radarr" raised an exception

### ISSUE THREAD

**Issue by tommyvange** [morpheus65535/bazarr#476]
**Describe the bug**
Recently Bazarr has started to bug out with my Radarr. It refuses to get the movies list from Radarr, when I test-connect to Radarr; it connects fine, so I have no idea why it's happening.

**To Reproduce**
I have no idea how to reproduce, as far as I know, I didn't make any changes; it just stopped working.

**Expected behavior**
I expected for it to grab the movie list from Radarr.

**Screenshots**
https://i.gyazo.com/9ce1ab1beca556b406ee81ae59bde8f3.png
https://i.gyazo.com/d07f18b43d51a2999cbf32679ea1ec88.png

**Software (please complete the following information):**
 - Bazarr: 0.6.9.1
 - Radarr version 0.2.0.1217
 - OS: Windows 10 PRO

**Additional context**

**Comment by morpheus65535** [comment]
You haven’t dine anything? Did you reinstall Radarr or restart Radarr from scratch?

**Comment by tommyvange** [comment]
> You haven’t dine anything? Did you reinstall Radarr or restart Radarr from scratch?

Oh thats right, i completely forgot. My radarr corrupted and I had to reinstall it, how do I go about fixing the issue?

**Comment by morpheus65535** [comment]
Either you delete your bazarr.db and reconfigure your language and notification settings or you edit this file with ans SQlite database editor like `DB Browser for SQlite` on Windows and empty the `table_movies` table, save and restart Bazarr.

**Comment by tommyvange** [comment]
> Either you delete your bazarr.db and reconfigure your language and notification settings or you edit this file with ans SQlite database editor like `DB Browser for SQlite` on Windows and empty the `table_movies` table, save and restart Bazarr.

Yep, that did the trick (deleting the db)! Thank you for the help :)
