### ISSUE TITLE
Subtitles from avistaz.to?

### ISSUE THREAD

**Issue by MoeJoe87** [morpheus65535/bazarr#477]
Hi

Would it be possible to get subtitles from this private torrent tracker? Could help also with an account for the implementation.

**Comment by morpheus65535** [comment]
We don’t get subtitles from torrent tracker, only from subtitles providers sites.

**Comment by MoeJoe87** [comment]
Is there a provider for Thai Movies....looking for english subs. I see only chinese provider...is there not an asian provider?

**Comment by morpheus65535** [comment]
Not that I'm aware of. But has I have no interest in those subtitles, I'm not the best one to confirm or deny it's existence.
