### ISSUE TITLE
Setting for sonarr scenename or video filename

### ISSUE THREAD

**Issue by phdelodder** [morpheus65535/bazarr#48]
Currently the system determines whether to use sonarr scenename or the filename.

It would be preferable to let the user chooses the method.

**Comment by phdelodder** [comment]
Please also add logging for the guess name, and perhaps the name of the subtitle that is being selected/downloaded

**Comment by morpheus65535** [comment]
BTW add minimum score settings.

**Comment by morpheus65535** [comment]
Could you please test with the dev branch and report back please?

**Comment by phdelodder** [comment]
Testing was OK

**Comment by morpheus65535** [comment]
Thank you! I've merged it to master.
