### ISSUE TITLE
Unable to start Bazarr

### ISSUE THREAD

**Issue by f3bruary** [morpheus65535/bazarr#480]
**Describe the bug**

I cannot seem to start Bazarr. I installed all the requirements in the txt file using pip. And gevent is also installed. Using Python 2.7.9, I get this error:

`Bazarr starting...
ERROR:root:BAZARR require gevent Python module to be installed using pip.
Traceback (most recent call last):
  File "bazarr/main.py", line 31, in <module>
    import gevent
  File "/usr/local/lib/python2.7/dist-packages/gevent/__init__.py", line 87, in <module>
    from gevent._hub_local import get_hub
ImportError: cannot import name get_hub
Bazarr exited.`

**Software (please complete the following information):**
 - Bazarr: [e.g. v 0.7.5.1]
 - OS: [e.g. Debian 8.6 headless]

**Comment by f3bruary** [comment]
I see now that Python 2.7.13 is required. Please close if that's what's causing this. Unfortunately 2.7.9 is the latest version in the Debian repo's :(

**Comment by morpheus65535** [comment]
Yes you need 2.7.13 that is available only still Debian 9.
