### ISSUE TITLE
Need to update media paths

### ISSUE THREAD

**Issue by skywayskase** [morpheus65535/bazarr#481]
I moved both my Sonarr and Radarr installs from windows to docker on an Ubuntu server. I updated the server information and the remote path mappings in Bazarr and confirmed that I could communicate with both new instances, however, all my movies and shows are still displaying their old windows path in Bazarr, and I can't figure out how to update them.

**Comment by morpheus65535** [comment]
Did you reinstall Sonarr and Radarr or did you move your config directories? Can you provide a debug log?

**Comment by skywayskase** [comment]
I setup the new instances of Radarr and Sonarr from scratch and pointed Bazarr at the new instances. How long do you want me to run debug mode before downloading the log and uploading here?

**Comment by morpheus65535** [comment]
If you start from scratch with Sonarr or Radarr, you need to do the same with Bazarr.
