### ISSUE TITLE
bazarr scene name with radarr

### ISSUE THREAD

**Issue by A-Alhashem** [morpheus65535/bazarr#482]
**Describe the bug**
Bazarr cannot grab a scene name from radarr if radarr uses a custom script like [sickbeard_mp4_automator](https://github.com/mdhiggins/sickbeard_mp4_automator).

With Sonarr and using the mp4 script, bazarr can successfully grab the scene name and searches the subtitles for that name.

However with Radarr, if used with the mp4 script, bazarr cannot grab the scene name.

this mp4 script is used to change mkv container to mp4, with optional audio encoding to other formats as well as other encoding features. Useful for plex players to direct play everything.

Maybe Radarr's API is different than Sonarr's, but checking Radarr API for a specific media file, it does contain release_group as well as other info such as source, name and resolution.

**To Reproduce**
Just that without script, scene name is grabbed. With script, cannot grab scene name.

**Expected behavior**
Bazarr should grab the scene name from Radarr with pp mp4 script, similar to how Sonarr+mp4 script works and bazarr can grab the scene name from sonarr.

If somehow the file is manipulated with Radarr's script. Radarr does also store the release_group, name and source of the file by using this method.

http://LOCAL_IP:PORT/api/movie/123?apikey=YOUR_RADARR_API_KEY

where 123 is the movie ID radarr stores.

**Screenshots**
![RadarrAPI](https://user-images.githubusercontent.com/44728397/60305212-8c2b8900-9944-11e9-8dea-495b1ae6a5e8.PNG)

**Software (please complete the following information):**
 - Bazarr: v 0.8
 - Radarr version 0.2.0.1344
 - Sonarr version 2.0.0.5322
 - OS: Windows 10 Pro

**Additional Information:**
Radarr's specific media file "History" tab still contains the actual name of the file downloaded/grabbed (located where you would edit a specific movie, it would have 4 tabs "History", "Search", "File" and "Title"). If that could also be grabbed from API as a workaround.

**Comment by morpheus65535** [comment]
This is related to Radarr API issue when using post processing script. I suggest you open the issue on their Github page.
