### ISSUE TITLE
[Feature Request] Bazarr for Synology NAS

### ISSUE THREAD

**Issue by mesquitafmr** [morpheus65535/bazarr#483]
A Bazarr package would be nice, there is already the version in Python and you could add it to the Synocommunity repository.

They even have a framework to help you with that https://github.com/SynoCommunity

**Comment by LifeBlast** [comment]
That would be a nice feature.
I like it better with SynoCommunity and Python the inside docker..

**Comment by morpheus65535** [comment]
This one as already been requested to SynoCommunity developer. I'll close it here and you can support it on their GitHub issue tracker: https://github.com/SynoCommunity/spksrc/issues/3535
