### ISSUE TITLE
Multiple directorys

### ISSUE THREAD

**Issue by luttman** [morpheus65535/bazarr#484]
I have radarr setup with different  paths

/mnt/tdrive/Movies/ 
/mnt/tdrive/Documentaries/ 

But Bazarr will only locate the first one

**Comment by morpheus65535** [comment]
What do you mean by « locate »?

**Comment by luttman** [comment]
Bazarr wont find the movies under 
/mnt/tdrive/Documentaries/

**Comment by halali** [comment]
Can you please fill issue with correct informations? With this info is impossible to help you

**Comment by luttman** [comment]
I have radarr setup with 2 filepaths, 
/mnt/tdrive/Movies/
/mnt/tdrive/Documentaries/

Radar will only locate movies from 
/mnt/tdrive/Movies/

**Comment by halali** [comment]
Ok what bazarr version you run, in what setup.

**Comment by luttman** [comment]
Running it on Debian 9
Bazaar
Ver, 0.7.5.1
Using docker
linuxserver/bazarr:latest

Have mounted /mnt/ in bazaar so it has the same filestructure

**Comment by halali** [comment]
Can you enable debug logging refresh your library and post that log here?

**Comment by morpheus65535** [comment]
Is this still an issue?
