### ISSUE TITLE
Custom words

### ISSUE THREAD

**Issue by mobamoba** [morpheus65535/bazarr#485]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to insert a custom word into every subtitle on renaming. Specifically, the word "default" as in TITLE.default.srt. I'm guessing I could do this with a custom post-processing script but thought I would see if it's a feature worth adding as people could insert their language as well. Thanks.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by morpheus65535** [comment]
If you disable ‘single language’, language code will be included in the filename like this: movie.en.srt. 

Having custom tag is not in our plan.
