### ISSUE TITLE
Bazarr is not starting on windows

### ISSUE THREAD

**Issue by algarih** [morpheus65535/bazarr#490]
Hi there,

Bazarr was working before i restarted my PC, now it is not working suddenly, but i notice the service is running.

Regards

**Comment by morpheus65535** [comment]
Could you provide the log file please?

**Comment by algarih** [comment]
this i found in C:\bazarr\data\log

[http://txt.do/119pb](url)

**Comment by halali** [comment]
You cant have torrent download folder same like your media folder... Sonarr take your toreents part files and try estract embedded subs with no success.

**Comment by morpheus65535** [comment]
I agree with @halali, you should start by doing setup of Sonarr correctly following their wiki. Next, you start fresh with Bazarr by emptying your data directory. Open an issue after that if you still need help. You can also come to Discord channel for support.

**Comment by algarih** [comment]
thank you all i will try to make a fresh install for both
