### ISSUE TITLE
Bazarr misidentifying matching Greek subtitle on subs4series

### ISSUE THREAD

**Issue by sotiris-bos** [morpheus65535/bazarr#492]
**Describe the bug**
Bazarr finds two subtitles on subs4series for The.Alienist.S01E07.Many.Sainted.Men.1080p.AMZN.WEB-DL.DD.2.0.H.264-SiGMA-AsRequested-Obfuscated. Subtitles are named:
1.The Alienist S01E07 WEBRip x264-TBS & 720p/1080p TBS
2. The Alienist S01E07 - Many Sainted Men (720p WEBRip 2CH x265 HEVC-PSA & 1080p AMZN WEBRip DDP2 0 x264-SiGMA)

Number 2 is a single subtitle file that fits all releases listed in its name. One of those (releases in its name) matches the release I initiated the search for exactly. Yet, bazarr misidentifies it and scores both subtitles listed above with 92.22%. I know this is a problem with subs4series using titles containing multiple releases but I wonder if it can be remedied.

**Software (please complete the following information):**
 - Bazarr: 0.8 (latest development version)
 - Sonarr version 2.0.0.5322
 - OS: FreeNAS 11.2-U5 jail

**Comment by morpheus65535** [comment]
@pkoutsias Is that even possible?

**Comment by pkoutsias** [comment]
From previously provided logs, it seems that GuessIt has trouble filtering out some keywords in the file name and misidentifies the release group as SiGMA-AsRequested:

```
11/07/2019 21:40:01|INFO    |subliminal_patch.core           |Determining basic video properties for 'The.Alienist.S01E04.These.Bloody.Thoughts.1080p.AMZN.WEB-DL.DD.5.1.H.264-SiGMA-AsRequested-Obfuscated.mkv' in '/media/Series/The Alienist/Season 1'|
11/07/2019 21:40:01|DEBUG   |subliminal_patch.core           |GuessIt found: {
    "title": "The Alienist", 
    "season": 1, 
    "episode": 4, 
    "episode_title": "These Bloody Thoughts", 
    "screen_size": "1080p", 
    "streaming_service": "Amazon Prime", 
    "format": "WEB-DL", 
    "audio_codec": "AC3", 
    "audio_channels": "5.1", 
    "video_codec": "h264", 
    "release_group": "SiGMA-AsRequested", 
    "container": "mkv", 
    "type": "episode"
}|
```

That's why it doesn't match with the correct subtitle. @sotiris-bos could you please rename your file, rescan and check again to verify the issue?

**Comment by morpheus65535** [comment]
That make sense. I should have drinked at least a coffee before answering to this issue... ;-)

Thanks!

**Comment by sotiris-bos** [comment]
I tried renaming the file but Sonarr will not pick up the name change and thus, I believe, Bazarr can't find the file because it is looking for the original name.

I doubt if it is due to the AsRequested though. The same thing does not happen with episode 5:

Filename: The.Alienist.S01E05.Hildebrandts.Starling.1080p.AMZN.WEB-DL.DD.5.1.H.264-SiGMA-AsRequested-Obfuscated.mkv

Opensubtitles: The.Alienist.S01E05.Hildebrandts.Starling.1080p.AMZN.WEB-DL.DD+5.1.H.264-SiGMA.srt 
Bazarr score: 99.72% 
link: https://www.opensubtitles.org/en/subtitles/7279565/the-alienist-hildebrandt-s-starling-el

Subs4Series: The Alienist S01E05 1080p AMZN WEB-DL DD5 1 H 264-SIGMA 
Bazarr score: 95.56% 
link: https://www.subs4series.com/greek-subtitles/sca046fc8dc/the-alienist-s01e05-1080p-amzn-web-dl-dd5-1-h-264-sigma

I think it is down to the name of S01E04 subtitle containing the name of another release that is causing the problem.

**Comment by pkoutsias** [comment]
Just checked on my build and the release group of the video file is recognized as 
![image](https://user-images.githubusercontent.com/5034122/61477953-2d808a80-a999-11e9-8a6c-80405770702d.png)

Sonarr will detect the new filename if you rescan the tv show and then radarr will be updated, too.
