### ISSUE TITLE
How do i stop the task auto download wanted subtitles

### ISSUE THREAD

**Issue by darkh3r0** [morpheus65535/bazarr#493]
I Just want Bazarr to search only one time after downloading from sonarr/radarr and NOT replace every 6 hours existing subtitles that i downloaded manually. Some of auto downloaded subtitles are bad even with 95% votes so thats why i search manually.
how i do  that is it possible?

**Comment by morpheus65535** [comment]
Disable subtitles upgrade for manually downloaded subtitles in settings.
