### ISSUE TITLE
Issue when ffprobe x64 is in PATH

### ISSUE THREAD

**Issue by gschaffner** [morpheus65535/bazarr#495]
Hello,

I noticed recently that Bazarr does not detect the presence of SUBT-encoded subtitles embedded in an MKV container. Shown below is a SUBT stream in an MKV container.

![vlc_nJ7D4ABNqn](https://user-images.githubusercontent.com/11418203/61587763-fcdd5400-ab44-11e9-91a5-8d024c8f7935.png)

Though I cannot find any online references to this, it appears that the SUBT codec is merely another name for the SRT codec. As shown below, MKVToolNix can extract the subtitle stream from the Matroska container and detects it as the SRT codec.

![cmd_QH5iDKM7oH](https://user-images.githubusercontent.com/11418203/61587767-0f578d80-ab45-11e9-8061-f8eaf26468bc.png)

Implementing the SUBT codec would save users the hassle of having to extract, rename, and re-insert SUBT subtitles as SRT throughout their library.

I am not familiar with this codebase, but from what I can tell, implementing this support would be as simple as adding the ".subt" format to the lists [here](https://github.com/morpheus65535/bazarr/blob/bed98832ed2a5b596265712bb3c0ac77d28ed264/libs/subliminal_patch/core.py#L49) and [here](https://github.com/morpheus65535/bazarr/blob/bed98832ed2a5b596265712bb3c0ac77d28ed264/libs/subliminal_patch/core.py#L591).

**Comment by gschaffner** [comment]
[Here](https://forum.videohelp.com/threads/377125-How-do-I-Mux-subtitles-into-MP4-as-a-plain-text) is an example of a user using SRT and SUBT interchangeably.

**Comment by morpheus65535** [comment]
The embedded subtitle detection is made by this method: https://github.com/morpheus65535/bazarr/blob/70306519467c30c0628b7db2bf120fbc31aeb4c4/bazarr/embedded_subs_reader.py#L20

We rely on ffprobe if it’s available or on enzyme if not. Does ffprobe detect your subt track correctly?

**Comment by gschaffner** [comment]
ffprobe is available in my system PATH (not just user PATH), and it does detect the SUBT track as SubRip format.

```
Stream #0:3(eng): Subtitle: subrip
    Metadata:
      BPS             : 134
      BPS-eng         : 134
      DURATION        : 00:27:33.267000000
      DURATION-eng    : 00:27:33.267000000
      NUMBER_OF_FRAMES: 608
      NUMBER_OF_FRAMES-eng: 608
      NUMBER_OF_BYTES : 28431
      NUMBER_OF_BYTES-eng: 28431
      _STATISTICS_WRITING_APP: mkvmerge v20.0.0 ('I Am The Sun') 64-bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v20.0.0 ('I Am The Sun') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2019-07-19 10:46:36
      _STATISTICS_WRITING_DATE_UTC-eng: 2019-07-19 10:46:36
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
```

For the same video file that I have been testing on, I found this error logged every time Bazarr tries to analyze it:
```
20/07/2019 18:25:33|ERROR   |root                            |BAZARR error when trying to analyze this .mkv file: F:\path\to\video.mkv|'Traceback (most recent call last):
  File "c:\\program files (x86)\\bazarr\\bazarr\\list_subtitles.py", line 37, in store_subtitles
    subtitle_languages = embedded_subs_reader.list_languages(file)
  File "c:\\program files (x86)\\bazarr\\bazarr\\embedded_subs_reader.py", line 24, in list_languages
    subtitle_languages = subprocess.check_output([self.ffprobe, "-loglevel", "error", "-select_streams", "s", "-show_entries", "stream_tags=language", "-of", "csv=p=0", file.encode(locale.getpreferredencoding())], universal_newlines=True, stderr=subprocess.STDOUT).strip()
  File "C:\\Program Files (x86)\\Bazarr\\WinPython\\python-2.7.13\\lib\\subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\\Program Files (x86)\\Bazarr\\WinPython\\python-2.7.13\\lib\\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\\Program Files (x86)\\Bazarr\\WinPython\\python-2.7.13\\lib\\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application'|
```

Removing ffprobe from my PATH, restarting Bazarr, and testing again results in the same error in the log.

I can also confirm that a copy of ffprobe does exist at `C:\Program Files (x86)\Bazarr\bin\Windows\i386\ffprobe\ffprobe.exe`.

**Comment by halali** [comment]
thats mean you use 32bit ffprobe aplication in 64bit python... Probably

**Comment by morpheus65535** [comment]
WinPython included in Windows Installer version of Bazarr is 32bits so it's probably the other way around: Bazarr is picking up your 64bits ffprobe executable because you probably haven't restarted Bazaar service or your computer after modifying the system path.

**Comment by gschaffner** [comment]
That was it; thank you @morpheus65535.

I'm still not sure why VLC and MakeMKV give my subtitle codec as "subt" on some videos.
