### ISSUE TITLE
radarr API language list issue

### ISSUE THREAD

**Issue by raidenlal** [morpheus65535/bazarr#496]
**Describe the bug**
-the radarr/api/profile API returns list of profiles and in each profile it returns a LIST of languages
-bazarr expects radarr to supply only one language per profile, not a list (https://github.com/morpheus65535/bazarr/blob/development/bazarr/get_movies.py#L222 - here it fails with AttributeError: \dict\ object has no attribute \capitalize\)

**To Reproduce**
1. get latest development version of radarr and bazarr from dockerhub
2. try to sync movies from radarr

**Expected behavior**
Movies get synced from radarr to bazarr

**Screenshots**
n/a

**Software (please complete the following information):**
 - Bazarr: 0.8
 - Radarr version 2.0.0.1404
 - Sonarr version 3.0.2.537-ls102 by linuxserver.io
 - OS: Linux-4.9.125-linuxkit-x86_64-with (docker on windows)

**Additional context**
https://www.reddit.com/r/radarr/comments/cfz9v2/radarr_api_language_list_per_profile_bug/
https://www.reddit.com/r/bazarr/comments/cfz3a6/changed_api_in_radarr_develop_branch/

**Comment by halali** [comment]
We dont support radarr preview version, untill they release it.

**Comment by raidenlal** [comment]
doesn't it make sense to prepare your dev with next release of radarr? no way to test (and use new features of) new radarr in this way

**Comment by morpheus65535** [comment]
We are going to speak with Radarr’s dev to see how mature the new API is.

**Comment by halali** [comment]
https://github.com/Radarr/Radarr/issues/3635
