### ISSUE TITLE
Can't download installer

### ISSUE THREAD

**Issue by barbidule** [morpheus65535/bazarr#497]
FYI, the download of the zip containing the .exe here https://github.com/bazarr/bazarr.github.io/releases/latest/download/bazarr.zip gets stuck at the end (the security analysis) and the download is never shown as completed (although it is)

**Comment by morpheus65535** [comment]
The issue is on your side. Probably related to your security software or your vrowser configfuration. I've just tested it with Chrome and Edge and it's working perfectly well.

**Comment by barbidule** [comment]
Tried with chrome and edge from two machines, same problem

**Comment by morpheus65535** [comment]
Sorry to say again but it's working perfectly well. The issue is on your side with your computer configuration (antivirus, security suite, browser configuration, etc.). It's totally unrelated to Bazarr.
