### ISSUE TITLE
{{subtitles_language_code3}} not working

### ISSUE THREAD

**Issue by Zeusy123** [morpheus65535/bazarr#498]
{{subtitles_language_code3}}
The 3-letter ISO-639 language code of the subtitles language. 

is bemant todo 3 letter launguage codes such as (eng) - current when this is set it is still doing 2 digit codes such as (en) even if 3 digit code is set.

**Comment by morpheus65535** [comment]
I've just tested but I cannot reproduce. I get the 3 characters language code without any issue.

**Comment by Zeusy123** [comment]
Serously??  ive 3 servers all same settings and all generate 2 digita not 3:(
How can we debug?

**Comment by Zeusy123** [comment]
just examined my log file and see a LOT of 

|BAZARR Error trying to get video information for this file: /home/TVSeries/1280 Series/2 Broke Girls/Season 5/2.Broke.Girls.S05E01.And.the.Wrecking.Ball.WEBDL-1080p.AC3+5.1.h264-Mixed.mp4|'Traceback (most recent call last):\n  File "/opt/bazarr/bazarr/get_subtitle.py", line 71, in get_video\n    refine_from_mediainfo(original_path, video)\n  File "/opt/bazarr/bazarr/get_subtitle.py", line 852, in refine_from_mediainfo\n    media_info = MediaInfo.parse(path, library_file=exe)\n  File "/opt/bazarr/bazarr/../libs/pymediainfo/__init__.py", line 256, in parse\n    lib  cls._get_library(library_file)\n  File "/opt/bazarr/bazarr/../libs/pymediainfo/__init__.py", line 187, in _get_library\n    lib = lib_type(library)\n  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__\n    self._handle = _dlopen(self._name, mode)\nOSError: /usr/bin/mediainfo: cannot dynamically load executable'|

Would this have something todo with it?

**Comment by morpheus65535** [comment]
Having 2 letters in subtitle name is the normal behaviour. 

I would try some thing like this on Windows:
`ren "{{subtitles}}" "{{directory}}\{{episode_name}}.{{subtitles_language_code3}}.srt"`

I have not tested this but it should be close to what you want to achieve.

**Comment by Zeusy123** [comment]
now its clear, thankyou, im on ubuntu18
so gonnar try:
rename "{{subtitles}}" "{{directory}}/{{episode_name}}.{{subtitles_language_code3}}.srt"

looks ok?

**Comment by morpheus65535** [comment]
Is `rename` an official Linux command? I’ve always used `mv`. The rest look good.

**Comment by Zeusy123** [comment]
ah yes
