### ISSUE TITLE
post process bug

### ISSUE THREAD

**Issue by Zeusy123** [morpheus65535/bazarr#499]
in post processing / settings section, if you put in 
mv "{{subtitles}}" "{{directory}}/{{episode_name}}.{{subtitles_language_code3}}.srt"

To get 3 digit codes, AFTER you save, the last " is deleted.

I also tried putting in 
mv "{{subtitles}}" '{{directory}}/{{episode_name}}.{{subtitles_language_code3}}.srt'

And the final ' was deleted.

**Comment by morpheus65535** [comment]
Can you try to put a backslash before the trailing quote mark?

**Comment by Zeusy123** [comment]
did mv "{{subtitles}}" "{{directory}}/{{episode_name}}.{{subtitles_language_code3}}.srt/"
saved and ends up mv "{{subtitles}}" "{{directory}}/{{episode_name}}.{{subtitles_language_code3}}.srt

have u got it to write 3 letters??

**Comment by morpheus65535** [comment]
I haven’t tested it. Maybe test the workaround in #309.

**Comment by Zeusy123** [comment]
As you know I grab 33 languages, so not possible to goto just 1.
really need a solution if possible.
TRash form support channel was kind enough to make a bash script https://github.com/TRaSH-/Tutorials-FAQ/blob/master/Bazarr/2to3_language_code.sh
follow his instruction:
"create a extra folder in the Bazarr install location and name it "scripts"
cd to scripts cd scripts
put in that folder the script i linked you and make sure you make the script executable chmod +x 2to3_language_code.sh
then in Bazarr you add in the post-processing line "/scripts/2to3_language_code.sh"

But sadly still not working:(

I also tested with bazarr in docker and stil lthe same:(

Please Help! :)

**Comment by Zeusy123** [comment]
strange now mv "{{subtitles}}" "{{directory}}/{{episode_name}}.{{subtitles_language_code3}}.srt/"
working:-/

**Comment by morpheus65535** [comment]
The proposed solution is to add `2>&1` at the end of your post processing command like this:
`mv "{{subtitles}}" "{{directory}}/{{episode_name}}.{{subtitles_language_code3}}.srt" 2>&1`
