### ISSUE TITLE
Docker arm64/aarch64 version

### ISSUE THREAD

**Issue by phdelodder** [morpheus65535/bazarr#50]
The current docker build isn't compatible with arm64/aarch64, can a compatible version be created? 

The error I receive with the current docker build: standard_init_linux.go:195: exec user process caused "exec format error"

**Comment by morpheus65535** [comment]
Using the Dockerfile provded yesterday, you have been able to build the docker image on your own infrastructure (I don't have a arm64 device). Report back when you had a chance to test that everything is working.

    FROM lsiobase/alpine.python.arm64:3.7

	# set python to use utf-8 rather than ascii.
	ENV PYTHONIOENCODING="UTF-8"

	VOLUME /tv

	RUN apk add --update git py-pip jpeg-dev && \
	    apk add --update --virtual build-dependencies build-base python-dev libffi-dev zlib-dev  && \
	    git clone -b master --single-branch https://github.com/morpheus65535/bazarr.git /bazarr && \
	    pip install -r /bazarr/requirements.txt && \
	    apk del --purge build-dependencies

	VOLUME /bazarr/data

	EXPOSE 6767

	CMD ["python", "/bazarr/bazarr.py"]
