### ISSUE TITLE
Job "Update Movies list from Radarr" raised an Exception

### ISSUE THREAD

**Issue by redlandmover** [morpheus65535/bazarr#502]
**Describe the bug**
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/bazarr/get_movies.py", line 26, in update_movies
  get_profile_list()
 File "/app/bazarr/bazarr/get_movies.py", line 221, in get_profile_list
  profiles_list.append([profile[\id\], profile[\language\].capitalize()])
AttributeError: \dict\ object has no attribute \capitalize\

Perhaps stringifying the `profile[\language\]` before calling `.capitalize()`? 

I'm a ruby dev, only a little of python knowledge. :P

**To Reproduce**
I've seen the error when running the "Update Movies list from Radarr" job.

**Expected behavior**
An exception not being thrown.

**Screenshots**

**Software (please complete the following information):**
Bazarr version
0.7.5.1
Sonarr version
3.0.2.551
Radarr version
2.0.0.1413
Operating system
Linux-4.19.56-Unraid-x86_64-with
Python version
2.7.16
Bazarr directory
/run/s6/services/bazarr
Bazarr config directory
/config

**Additional context**

**Comment by morpheus65535** [comment]
We don't support Radarr preview/dev branch. We will once it's stabilized but it's too early in development stage for now.

**Comment by redlandmover** [comment]
cool. makes sense. 

loving bazarr! keep it up.

**Comment by morpheus65535** [comment]
Thanks for the feedback!
