### ISSUE TITLE
Adding Legendasdivx.pt

### ISSUE THREAD

**Issue by silveringking** [morpheus65535/bazarr#503]
I see this project lacks a very good eu-pt (and good br-pt) website, I recommend this one:

https://www.legendasdivx.pt/index.php

I have been using this project maybe since 2004 or 2005 it is a very old and has a huge collection, it is pretty good I would recommend it anyway even if there was another one of the same quality.

Kind regards,

**Comment by morpheus65535** [comment]
Duplicate of #210
