### ISSUE TITLE
BAZARR unable to index external subtitles.

### ISSUE THREAD

**Issue by MichaelSoe** [morpheus65535/bazarr#509]
I've installed Bazarr inside a jail on XigmaNAS (FreeBSD NAS OS, similar to FreeNAS) and I get the following error when indexing my movie and series library: 
```
BAZARR unable to index external subtitles.

Traceback (most recent call last):
 File "/usr/local/bazarr/bazarr/list_subtitles.py", line 137, in store_subtitles_movie
  only_one=settings.general.getboolean(\single_language\))
 File "/usr/local/bazarr/bazarr/../libs/subliminal_patch/core.py", line 653, in search_external_subtitles
  only_one=only_one))
 File "/usr/local/bazarr/bazarr/../libs/subliminal_patch/core.py", line 581, in _search_external_subtitles
  if not entry.is_file(follow_symlinks=False):
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 500, in is_file
  st = self.stat(follow_symlinks=follow_symlinks)
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 480, in stat
  self._lstat = lstat(self.path)
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 465, in path
  self._path = join(self._scandir_path, self.name)
 File "/usr/local/lib/python2.7/posixpath.py", line 73, in join
  path += \/\ + b
 File "/usr/local/lib/python2.7/encodings/utf_8.py", line 16, in decode
  return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: \utf8\ codec can\t decode byte 0x83 in position 1: invalid start byte
```
I have no idea what the problem could be. These subtitles where downloaded using the SubZero Plex plugin and all play fine on Plex. I also don't think that this is a path mapping issue, since the software runs inside the same jail as Sonarr and Radarr, so it should have access to the same folder structure.

The permissions are currently 0664 for both media and subtitle files, but i've also tried 0775, but to no avail.

Any idea what could be causing this ?

Thanks in advance!

**Comment by halali** [comment]
Possible related to #421

**Comment by MichaelSoe** [comment]
> Possible related to #421

I've tried what was mentioned there: explicitly set my locale to en_US, which applied to my system, since locale now returns the following:
`
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=en_US.UTF-8
`

But I'm still getting the same error, even after restarting both the jail and the NAS itself.

**Comment by morpheus65535** [comment]
What is the output from this command in your jail?

`python -c "import sys; print sys.getdefaultencoding()"`

**Comment by MichaelSoe** [comment]
This returns:
`ascii`
So I'm guessing the problem lies there. I've searched a bit on how to change this value, but can't seem to find a solution that works for my system.

After finding out that setting PYTHONIOENCODING to utf-8 could be the solution (as described [here](https://stackoverflow.com/questions/2276200/changing-default-encoding-of-python)), I had found a [link](https://github.com/hhatto/autopep8/issues/148#issuecomment-48603775) on how to do this on FreeBSD, but even after a restart this doesn't seem to work.

**Comment by morpheus65535** [comment]
Maybe this could help: https://github.com/morpheus65535/bazarr/issues/515#issuecomment-521261307

**Comment by morpheus65535** [comment]
Did you fix your system encoding issue? Can I close this issue?

**Comment by MichaelSoe** [comment]
Sorry for the late response, I didn't have much time to look further into the issue and I'm still not able to fix it. I've done some more research and discovered that the environment variable wasn't being set on restart, so I first had to fix that.

I was able to set the variable on startup by setting the variable in the `.cshrc`-file in the root folder of the current user (this depends on the shell that you're using). 

After that, the code that you mentioned (`python -c "import sys; print sys.getdefaultencoding()"`) still returned `ascii`.

I've also tried the solution in the comment that you've linked (reloading the settings), but since that's for macOS, I've tried to find the FreeBSD equivalent of that (also tried the macOS solution: that didn't give any feedback, but also no error).
Also checked out the link that you've mentioned on #515, but both `LC_ALL` and `LANG` are set to `en_US.UTF-8`.

**Comment by morpheus65535** [comment]
I don't know what to say, I have no experience with FreeBSD jail. I suggest you try the Docker way or the Windows Installer version if you want to be sure to have all the requirements included.

**Comment by MichaelSoe** [comment]
Alright, thanks for the help anyway! 
The following couple of days I don't have any time to look further into the issue, but once I do, I'll try the Docker way. I'll update this ticket with how I got it working.

**Comment by morpheus65535** [comment]
Is this still an issue?

**Comment by morpheus65535** [comment]
I close it. Reopen if required.

**Comment by martijnk-cmd** [comment]
Hello,

Got the exact same issue. FreeBSD 12.1. Current Bazarr version.

**BAZARR unable to index external subtitles.**

python -c "import sys; print sys.getdefaultencoding()" indeed shows ascii but I think this is normal behavior as python's default encoding is indeed ascii (according to their docs). 

python -c 'import sys; print sys.stdout.encoding' does show UTF-8 which is what matters and seems correct.

Also, I had SABNzbd complaining that I was using ASCII, changed all to UTF-8 and it stopped complaining, however Bazarr still doesn't seem to like it.

`Traceback (most recent call last):
 File "/usr/local/bazarr/bazarr/list_subtitles.py", line 159, in store_subtitles_movie
  subtitles = search_external_subtitles(file, languages=get_language_set())
 File "/usr/local/bazarr/bazarr/../libs/subliminal_patch/core.py", line 667, in search_external_subtitles
  only_one=only_one, match_strictness=match_strictness))
 File "/usr/local/bazarr/bazarr/../libs/subliminal_patch/core.py", line 582, in _search_external_subtitles
  if not entry.is_file(follow_symlinks=False):
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 500, in is_file
  st = self.stat(follow_symlinks=follow_symlinks)
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 480, in stat
  self._lstat = lstat(self.path)
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 465, in path
  self._path = join(self._scandir_path, self.name)
 File "/usr/local/lib/python2.7/posixpath.py", line 73, in join
  path += \/\ + b
 File "/usr/local/lib/python2.7/encodings/utf_8.py", line 16, in decode
  return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: \utf8\ codec can\t decode byte 0xa3 in position 3: invalid start byte`

**Comment by morpheus65535** [comment]
@martijnk-cmd did you try the dev branch? Could be fixing your issue. You could even try dev branch with >= Python 3.6.

**Comment by martijnk-cmd** [comment]
> @martijnk-cmd did you try the dev branch? Could be fixing your issue. You could even try dev branch with >= Python 3.6.

Ah right I will try that, didn't know there was a Python 3.6 version as well. Will try and report back. Thanks!

**Comment by martijnk-cmd** [comment]
Well the errors changed but I get one additional error now.

`BAZARR unable to index external subtitles.`

gives:

`Traceback (most recent call last):
 File "/usr/local/bazarr/bazarr/list_subtitles.py", line 143, in store_subtitles_movie
  subtitles = search_external_subtitles(reversed_path, languages=get_language_set())
 File "/usr/local/bazarr/bazarr/../libs/subliminal_patch/core.py", line 669, in search_external_subtitles
  only_one=only_one, match_strictness=match_strictness))
 File "/usr/local/bazarr/bazarr/../libs/subliminal_patch/core.py", line 584, in _search_external_subtitles
  if not entry.is_file(follow_symlinks=False):
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 500, in is_file
  st = self.stat(follow_symlinks=follow_symlinks)
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 480, in stat
  self._lstat = lstat(self.path)
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 465, in path
  self._path = join(self._scandir_path, self.name)
 File "/usr/local/lib/python3.6/posixpath.py", line 94, in join
  genericpath._check_arg_types(\join\, a, *p)
 File "/usr/local/lib/python3.6/genericpath.py", line 151, in _check_arg_types
  raise TypeError("Can\t mix strings and bytes in path components") from None
TypeError: Can\t mix strings and bytes in path components`

And new error is:

`BAZARR error when trying to analyze this .mkv file: /path/to/1080pmovie.mkv`

`Traceback (most recent call last):
 File "/usr/local/bazarr/bazarr/list_subtitles.py", line 117, in store_subtitles_movie
  subtitle_languages = embedded_subs_reader.list_languages(reversed_path)
 File "/usr/local/bazarr/bazarr/embedded_subs_reader.py", line 27, in list_languages
  data = parser.parseFfprobe(file)
 File "/usr/local/bazarr/bazarr/../libs/pyprobe/pyprobe.py", line 42, in parseFfprobe
  fdict = self._executeFfprobe(inputFile)
 File "/usr/local/bazarr/bazarr/../libs/pyprobe/pyprobe.py", line 73, in _executeFfprobe
  outputJson = self._executeParser(self._ffprobe, commandArgs, inputFile)
 File "/usr/local/bazarr/bazarr/../libs/pyprobe/pyprobe.py", line 182, in _executeParser
  command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True
 File "/usr/local/lib/python3.6/subprocess.py", line 423, in run
  with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument \text\`

**Comment by morpheus65535** [comment]
Please update to latest dev. The new error have been fixed 2 days ago.

**Comment by martijnk-cmd** [comment]
Ah right I forgot to do a git pull.

Now I only get the one error: TypeError: Can\t mix strings and bytes in path components

**Comment by morpheus65535** [comment]
Ok, I'll fix this tonight. Please open a dedicated issue for that one. Thanks!

**Comment by martijnk-cmd** [comment]
Will do, thanks for the help!!
