### ISSUE TITLE
OperationalError('user-defined function raised exception',)

### ISSUE THREAD

**Issue by tigre-bleu** [morpheus65535/bazarr#51]
I have the following exception leading to error 500:

```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/pi/.local/lib/python2.7/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "bazarr.py", line 150, in series
    c.execute("SELECT tvdbId, title, path_substitution(path), languages, hearing_impaired, sonarrSeriesId, poster, audio_language FROM table_shows ORDER BY title ASC LIMIT 15 OFFSET ?", (offset,))
OperationalError: user-defined function raised exception
```
What could cause that? I recently added path substitution but I am not sure if it is linked. The error started after last restart due to update.

**Comment by morpheus65535** [comment]
Please show me your path substitution settings. You can access settings directly using /settings in url.

**Comment by tigre-bleu** [comment]
`/media/nas/videos/Séries > /media/series`

This shortcut was a workaround because I have the impression than subliminal has issues with long paths.

I confirm the issue is linked to the path substitusion. If I remove it then the exception disappears.

**Comment by morpheus65535** [comment]
Ok, just to be sure: why are you using path substitution? You should only be using this if Sonarr and Bazarr access the same file using different path.

Subliminal doesn't have any problem with long path. I would be more suspicious about accentuated "e" in "Séries". FYI, I got one episode with this path and it works perfectly: ```\\serveur\media\series_rosalie\Henry Hugglemonster\Season 01\Henry.Hugglemonster.S01E19.A.Funny.Thing.Happened.on.the.Way.to.Monsterschool.-.Summergrams.720p.WEB-DL.x264.AAC.mp4```

If you want, we could chat on Discord and we can take care of that issue. I speak french so it should be easier. :-)

**Comment by morpheus65535** [comment]
If you still have this issue, open it back. For now, I close it.
