### ISSUE TITLE
/usr/bin/mediainfo: cannot dynamically load executable

### ISSUE THREAD

**Issue by xpokor02** [morpheus65535/bazarr#514]
Hi ,
I get error:
BAZARR Error trying to get video information for this file

Traceback (most recent call last):
 File "/root/bazarr/bazarr/get_subtitle.py", line 69, in get_video
  refine_from_mediainfo(original_path, video)
 File "/root/bazarr/bazarr/get_subtitle.py", line 874, in refine_from_mediainfo
  media_info = MediaInfo.parse(path, library_file=exe)
 File "/root/bazarr/bazarr/../libs/pymediainfo/__init__.py", line 256, in parse
  lib = cls._get_library(library_file)
 File "/root/bazarr/bazarr/../libs/pymediainfo/__init__.py", line 187, in _get_library
  lib = lib_type(library)
 File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
  self._handle = _dlopen(self._name, mode)
OSError: /usr/bin/mediainfo: cannot dynamically load executable

Bazarr Ver. 0.8

mediainfo (0.7.91-1) installed

Thanks

**Comment by morpheus65535** [comment]
Please update Bazarr and confirm if it's still an issue. Thanks.

**Comment by xpokor02** [comment]
Thanks for update it worked (as I understand it, you disabled it entirely on linux as I did manually).

**Comment by morpheus65535** [comment]
Exactly. There's is too many possible issue on Linux with mediainfo library.

**Comment by MoshiMoshi0** [comment]
@morpheus65535 i dont understand why did you disable this entirely for linux instead of fixing it.

You can see that it is trying to load mediainfo executable not the library, the correct lib would be "libmediainfo.so.0".

I'll try to fix this and make a pr.

**Comment by morpheus65535** [comment]
@MoshiMoshi0 I’m currently reworking the whole embedded subtitles and video properties refiners around ffprobe.

**Comment by MoshiMoshi0** [comment]
Oh, ok nice. Ill wait with the pr then.
