### ISSUE TITLE
Bazarr keeps re-downloading the same movie sub on every scan.

### ISSUE THREAD

**Issue by TRaSH-** [morpheus65535/bazarr#517]
**Describe the bug**
During every scan Bazarr keeps re-downloading the same movie subtitle over and over.
It happend with a movie a few days ago,
so i just decided to remove the wanted language and was done with it,
then i got a new movie and it happend again.
It only happend with movies and not episodes.

Here you can see the constant re-downloading.
![image](https://user-images.githubusercontent.com/6155095/63045748-4d8c6680-bed1-11e9-9bbc-13b50194f197.png)

Here you can see that the subtitle is present.
![image](https://user-images.githubusercontent.com/6155095/63045858-87f60380-bed1-11e9-8534-85960f443ba2.png)

I've added the debug log from the start it does a searching for that movie
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3503009/bazarr.log)

Also it looks like it's getting it twice,
i even tried to delete the sub to see if their was a issue with the sub

**Software (please complete the following information):**
Bazarr version 0.8
Sonarr version 3.0.2.577
Radarr version 0.2.0.1358
Operating system Linux-4.19.56-Unraid-x86_64-with
Python version 2.7.16
OS: Unraid Dockers

**Comment by TRaSH-** [comment]
added a extra log file with only 1 provider enabled
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3506203/bazarr.log)

**Comment by morpheus65535** [comment]
This should fix your issue. It was broader than what was expected but I think I've fixed all problem.
