### ISSUE TITLE
Multiple requests per second to /notifications

### ISSUE THREAD

**Issue by Groofster** [morpheus65535/bazarr#518]
Opening the bazarr website creates an infinite number of request to /notifications with referer /series. And it's not only infinite, it's requesting it between 3 and 5 times a second.

I also have 700+ movies, missing 16 subtitles but can't even find a single request to /notifications with /movies as the referer.

I have 80 series with over 1800 episodes, missing only 26 subtitles but this number of requests is showing up as a 10% load on my brand new i7 server.

1. Go to 'https://<my bazarr website>/'
2. Open the developer options and select the network tab
3. Be amazed by the power of javascript ;)

I'm not sure what a sane number of requests would be.....

Below screenshot was taken 3 to 4 minutes after opening the bazarr website. The number of requests is already up to 1200. No clicks on my part, just letting it rip.....

![Screenshot from 2019-08-15 10-52-48](https://user-images.githubusercontent.com/9840579/63084549-b6182980-bf4b-11e9-8aff-99adda455256.png)

 - Bazarr version: 0.7.5.1
 - Radarr version: 0.2.0.1358 
 - Sonarr version: 2.0.0.5338
 - OS: latest linuxserver.io docker image on Ubuntu 19.10

If there's anything I can provide, please let me know.

**Comment by morpheus65535** [comment]
Thank you for reporting this. Ajax long polling wasn't working as expected. It should be fixed now in DEV branch 0.8 that should be merge to master soon.

**Comment by Groofster** [comment]
I have checked out the development branch and tested it. Big improvement, thanks for the quick fix, hope to see it in master soon.
