### ISSUE TITLE
Job "Update movies list from Radarr (trigger: interval[0:05:00],  raised an exception

### ISSUE THREAD

**Issue by svenvg93** [morpheus65535/bazarr#519]
While checking the logging I saw the following error flooding the file.
Can't seem to find what is causing this error.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
<img width="734" alt="Screenshot 2019-08-16 at 20 45 47" src="https://user-images.githubusercontent.com/4511676/63190692-02a45780-c067-11e9-8d04-3163cf4d4fc1.png">

**Software (please complete the following information):**
 - Bazarr: 0.7.5.1
 - Radarr version 2.0.0.1422
 - Sonarr version 3.0.2.587
 - OS: unRAID Docker

**Comment by morpheus65535** [comment]
Duplicate #496 .

Radarr v2 not supported for now.

**Comment by halali** [comment]
Morpheus mean radarr preview version
