### ISSUE TITLE
Small UI Bug - Poster float left not stretching divdetails

### ISSUE THREAD

**Issue by davidhantson** [morpheus65535/bazarr#52]
https://github.com/morpheus65535/bazarr/blob/22b86cb083403e1873f47017ee57377d292f64ac/views/episodes.tpl#L110

In the template file you can do a style="clear:both" on the last <p> tag inside the #divdetails , or just add a empty div with that style. 

When the Poster is oversized it will stretch the black details box nicely down.

**Comment by morpheus65535** [comment]
Thanks for reporting this one to me. Can you try the dev branch ad report if everything is ok?
