### ISSUE TITLE
Forced Subtitle Naming

### ISSUE THREAD

**Issue by animosity22** [morpheus65535/bazarr#521]
**Describe the bug**
For naming standards, Plex/Emby are expecting the language code and forced after it:

Movie_Name (Release Date).[Language_Code].ext OR
Movies/Movie_Name (Release Date).[Language_Code].ext
Movies/Movie_Name (Release Date).[Language_Code].forced.ext

and I'm trying to change it from:

```
-rw-rw-r--  1 felix felix        3083 Aug 18 07:31 'The Fate of the Furious (2017).forced.srt'
-rw-rw-r--  1 felix felix 10565504832 Jun 28  2017 'The Fate of the Furious (2017).mkv'
```

which seems to only put the forced in there. I wasn't sure if I was missing an option or that isn't there yet. 

***Software (please complete the following information):**
Bazarr version
0.8
Sonarr version
3.0.2.587
Radarr version
0.2.0.1358
Operating system
Linux-5.2.8-arch1-1-ARCH-x86_64-with-glibc2.2.5
Python version
2.7.16
Bazarr directory
/opt/bazarr
Bazarr config directory
/opt/bazarr/data

**Comment by morpheus65535** [comment]
Just disable single language option in settings.

**Comment by animosity22** [comment]
So sorry I missed reading that checkbox!

Thanks for the quick reply to my easy question of the day.
