### ISSUE TITLE
Bazarr will not load when run as different user

### ISSUE THREAD

**Issue by no00wa** [morpheus65535/bazarr#522]
**Describe the bug**
When running the Bazarr service under windows (bazarr installed with the complete package) it will only load the interface when run as "local system account". When changing to a user with admin rights it will simple never load the interface.

The logs do not show anything reflecting issues or whatnot, nothing is added.

**To Reproduce**
Start Bazarr under a different user

**Expected behavior**
Bazarr to work and to access sonarr/radarr network paths under said user

**Screenshots**
n.a.

**Software (please complete the following information):**
 - Bazarr: v0.8
 - Radarr version: n.a.
 - Sonarr version: n.a.
 - OS: Windows 10 - 1903

**Additional context**
n.a.

**Comment by morpheus65535** [comment]
I've just started my VM with Bazarr installed with the Windows installer and it's been updating without any problem. You should make sure that the user account running Bazarr have write privilege to the app directory to update itself correctly.
I had to restart it manually after upgrade but it's working well.
Can you provide a debug log? You can for Bazarr to start in debug mode with `--debug` command line parameter.

**Comment by no00wa** [comment]
Did not "fix" the issue but i am running the service now under the user that is also logged in. Somehow sonarr/radarr/bazarr are also checking UNC credentials that are stored in the windows credential manager and so that works fine without me needing to add the local user to my NAS for write access to show/movie folders.
