### ISSUE TITLE
Using the Manual Search gives me an error when sub is from opensubtitles

### ISSUE THREAD

**Issue by alcmoraes** [morpheus65535/bazarr#523]
I'm trying to use the Manual Search to download a subtitle from a TV Show. If I click on the Opensubtitle link at `Provider` column, I can download it via browser. But if I use the `Download` button to download via Bazarr, nothing happens. Logs says `No valid subtitles file found for this file`.

1. Go to any TV Show
2. Click on Manual Search for an episode
3. Download a subtitle from OpenSubtitles provider
4. See error on Logs

**Expected behavior**
The subtitle would be downloaded and appear on the `Existent subtitles` column.

**Screenshots**
![image](https://user-images.githubusercontent.com/2521595/63233437-8183c680-c206-11e9-9241-af569f07fdfa.png)

![image](https://user-images.githubusercontent.com/2521595/63233150-cd357080-c204-11e9-81b9-e7dc586444e3.png)
As said:
1. Clicking on `opensubtitles` link works.
2. Clicking on `download button` from `legendastv` works.
3. Clicking on `download button` from `opensubtitles` *does not* works.

 - Bazarr: Latest developer branch as of writing this bug
 - OS: Ubuntu 18.10

The last lines of bazarr logs shows the following:

```
...
18/08/2019 21:40:27|ERROR   |root                            |BAZARR No valid subtitles file found for this file: /mnt/cthulhu/TV Shows/Brickleberry/Brickleberry - S01E01 - Welcome to Brickleberry SDTV.mp4|'None'|
18/08/2019 21:51:26|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:6767/|
18/08/2019 21:51:54|ERROR   |root                            |BAZARR No valid subtitles file found for this file: /mnt/cthulhu/TV Shows/Brickleberry/Brickleberry - S01E01 - Welcome to Brickleberry SDTV.mp4|'None'|
18/08/2019 21:54:13|ERROR   |root                            |BAZARR No valid subtitles file found for this file: /mnt/cthulhu/TV Shows/Brickleberry/Brickleberry - S01E01 - Welcome to Brickleberry SDTV.mp4|'None'|
```

As a programmer myself (not python), I was able to going on further investigation...

I've noticed the error throws from [get_subtitle.py:L410](https://github.com/morpheus65535/bazarr/blob/master/bazarr/get_subtitle.py#L410) and that the subtitle is generated from a Base64 ([get_subtitle.py:L388](https://github.com/morpheus65535/bazarr/blob/master/bazarr/get_subtitle.py#L388)).

I've tracked down the exact Base64 giving this error by inspecting the Manual Search modal on the webapp. And here it is.

```
Y2NvcHlfcmVnCl9yZWNvbnN0cnVjdG9yCnAxCihjc3VibGltaW5hbF9wYXRjaC5wcm92aWRlcnMu
b3BlbnN1YnRpdGxlcwpPcGVuU3VidGl0bGVzU3VidGl0bGUKcDIKY19fYnVpbHRpbl9fCm9iamVj
dApwMwpOdFJwNAooZHA1ClMnbW92aWVfbmFtZScKcDYKUyciQnJpY2tsZWJlcnJ5IiBXZWxjb21l
IHRvIEJyaWNrbGViZXJyeScKcDcKc1MnZW5jb2RpbmcnCnA4ClMnYXNjaWknCnA5CnNTJ3NraXBf
d3JvbmdfZnBzJwpwMTAKSTAwCnNTJ21vdmllX3llYXInCnAxMQpJMjAxMgpzUydoZWFyaW5nX2lt
cGFpcmVkJwpwMTIKSTAwCnNTJ3F1ZXJ5X3BhcmFtZXRlcnMnCnAxMwooZHAxNApTJ21vdmllYnl0
ZXNpemUnCnAxNQpJOTUzODQwOTgKc1Mnc3VibGFuZ3VhZ2VpZCcKcDE2ClMnZW5nJwpwMTcKc1Mn
bW92aWVoYXNoJwpwMTgKUyc5Y2E5ZTFhMWQwMjY2ZjAwJwpwMTkKc3NTJ3Nlcmllc19zZWFzb24n
CnAyMApJMQpzUydmaWxlbmFtZScKcDIxClMnQnJpY2tsZWJlcnJ5LlMwMUUwMS5IRFRWLngyNjQt
TE9MLWVuZy5zcnQnCnAyMgpzUydjb250ZW50JwpwMjMKTnNTJ3Njb3JlJwpwMjQKSTM1OQpzUydm
cHMnCnAyNQpTJzIzLjk3NicKcDI2CnNTJ2hhc2gnCnAyNwpTJzljYTllMWExZDAyNjZmMDAnCnAy
OApzUydtYXRjaGVkX2J5JwpwMjkKUydtb3ZpZWhhc2gnCnAzMApzUydtb3ZpZV9pbWRiX2lkJwpw
MzEKUyd0dDIzMzA3MDAnCnAzMgpzUydtb3ZpZV9yZWxlYXNlX25hbWUnCnAzMwpTJ0JyaWNrbGVi
ZXJyeS5TMDFFMDEuSERUVi54MjY0LUxPTCcKcDM0CnNTJ21vdmllX2tpbmQnCnAzNQpTJ2VwaXNv
ZGUnCnAzNgpzUydfaXNfdmFsaWQnCnAzNwpJMDAKc1Mnd3JvbmdfZnBzJwpwMzgKSTAwCnNTJ21v
ZHMnCnAzOQpOc1MnbGFuZ3VhZ2UnCnA0MApnMQooY3N1Ynplcm8ubGFuZ3VhZ2UKTGFuZ3VhZ2UK
cDQxCmczCk50UnA0MgooVmVuZwpwNDMKTk5JMDAKdGJzUydzdWJ0aXRsZV9pZCcKcDQ0CkkxOTUz
MzY2MjYzCnNTJ3Nlcmllc19lcGlzb2RlJwpwNDUKSTEKc1MncGxleF9tZWRpYV9mcHMnCnA0NgpO
c1MncGFnZV9saW5rJwpwNDcKUydodHRwOi8vd3d3Lm9wZW5zdWJ0aXRsZXMub3JnL2VuL3N1YnRp
dGxlcy80ODIzMjA5L3NpZC1oMUpUUndFVmxqZzl1emNQb3NrcGFjYmVhUmIvYnJpY2tsZWJlcnJ5
LXdlbGNvbWUtdG8tYnJpY2tsZWJlcnJ5LWVuJwpwNDgKc1MncmVsZWFzZV9pbmZvJwpwNDkKZzM0
CnNiLg==
```

By doing a `decode` on that, I've noticed a really weird pattern. That I could'nt say if it was supposed to be that way:

```
...
p32
sS'movie_release_name'
p33
S'Brickleberry.S01E01.HDTV.x264-LOL'
p34
sS'movie_kind'
p35
S'episode'
p36
...
```

Any help?

Congrats on the tool btw. It helped me a lot already! :)

**Comment by alcmoraes** [comment]
*EDIT*: Just noticed, Base64 from `legendastv` (who is working) has the same format, so I believe that was normal.

Well, anyway, the `opensubtitles` is not passing the `is_valid()` check.

**Comment by halali** [comment]
Please can you provide debug log? And bazarr version? I think you post file hash BTW.

**Comment by morpheus65535** [comment]
I've tested a manual download from opensubtitles and I've been able to achieve it without any issue.

![image](https://user-images.githubusercontent.com/5130500/63265597-ff25f180-c25b-11e9-8625-44fe72a9d218.png)

To be honest, that's not a functionality I used quite often but it should work as expected unless opensubtitles return an error during download.

**Comment by Blackbat007** [comment]
It is still an issue. I've just installed Bazarr this morning for the first time, and came here looking for a solution to the problem as I am also getting the same "No valid subtitles file found for this file" error.

**Comment by halali** [comment]
Maybe some security tool damaged that file. Or something.

**Comment by emilnymann** [comment]
I am experiencing the same issue. [Here's a debug log.](https://paste.ee/p/bG3bp)

**Comment by morpheus65535** [comment]
@pannal Somethings going wrong with opensubtitles provider. Subliminal_patch is_valid() return False when the subtitle is perfectly fine. Have you ever seen that?

**Comment by Kabraxist** [comment]
Seems like I'm having the same issue. Podnapisi works, opensubtitles doesn't. Only Error I'm getting is:
`04/09/2019 09:57:02|DEBUG   |root                            |BAZARR Subtitles file downloaded for this file:/home/quickboxuser/Emby/Series/Forever (2018)/Season 1/Forever (2018) - S01E01 - Together Forever.mp4|
04/09/2019 09:57:02|ERROR   |root                            |BAZARR No valid subtitles file found for this file: /home/quickboxuser/Emby/Series/Forever (2018)/Season 1/Forever (2018) - S01E01 - Together Forever.mp4|None|`

**Comment by emilnymann** [comment]
> Maybe we are hitting into some kind of API limit?

I don't think it's an API limit, because adding a show in Sonarr and having Bazarr find subtitles for it without any user interaction works just fine, even from opensubtitles. It's only manual download and manual search.

**Comment by morpheus65535** [comment]
Are you guys using Homebrew installed python or "real" python binaries?

**Comment by Kabraxist** [comment]
I installed it with apt-get, and required binaries by pip.

**Comment by morpheus65535** [comment]
`python --version` ?

**Comment by Kabraxist** [comment]
2.7.12

**Comment by morpheus65535** [comment]
You should at least update to 2.7.13 which is the minimal version supported by Bazarr.

**Comment by Kabraxist** [comment]
Upgraded to 2.7.16 and that really seems to fix it. Thanks!

**Comment by morpheus65535** [comment]
@alcmoraes , @Blackbat007 , @emilnymann , can you confirm if upgrading to Python >= 2.7.13 fix your issue? Thanks,

**Comment by emilnymann** [comment]
I am already running Bazarr with Python 2.7.16.

**Comment by lutzky** [comment]
I believe I'm experiencing the same issue - manual downloads are failing. Full logs at https://pastebin.com/gm6qGC3i. Note that this occurs only for opensubtitles. Possibly-pertinent log lines are "22/09/2019 09:18:47|DEBUG   |subliminal_patch.providers.opensubtitles|Token not valid.|" and friends (though I double-checked my opensubtitles login).

**Comment by lutzky** [comment]
Ah, interesting - when trying to download from the opensubtitles website, I get the following error in the UI:

> Sorry, maximum download count for IP: <ip> exceeded. If you will continue trying to download, your IP will be blocked by our firewall. For more information read our FAQ or contact us, if you think you should not see this error. This deny will be removed after around 24 hours, so be patient.

That, uh, makes sense, I've been trying to get bazarr to download subtitles for my entire collection, and possibly, uh, encouraging it with manual downloads 😅 

The unfortunate thing is that this is returned as an HTTP 404, with nothing particularly useful in the response headers for identifying this:

```
access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept
access-control-allow-origin: *
age: 0
cache-control: no-cache, must-revalidate, post-check=0, pre-check=1
cf-ray: <REDACTED>
content-encoding: br
content-type: text/html; charset=UTF-8
date: Sun, 22 Sep 2019 12:04:57 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
set-cookie: PHPSESSID=<REDACTED>; expires=Sun, 22-Sep-2019 18:04:57 GMT; Max-Age=21600; path=/; domain=.opensubtitles.org; HttpOnly
set-cookie: logged=1; expires=Sun, 22-Sep-2019 12:29:57 GMT; Max-Age=1500; path=/; domain=.opensubtitles.org
status: 404
strict-transport-security: max-age=600; includeSubDomains
vary: Accept-Encoding
x-cache: MISS
x-cache-backend: web4
x-frame-options: SAMEORIGIN
x-memcached: false
x-ratelimit-remaining: 40
x-robots-tag: noindex, nofollow
x-via: fw2.int.opensubtitles.org
```

Hell, even `x-ratelimit-remaining` is trying to hint at more capacity being available 😞 . I can't think of a way around this other than looking for the specific string "maximum download count", which is brittle.

**Comment by morpheus65535** [comment]
@lutzky your issue is unrelated to this one. Yours is more related to OS exception and is being addressed globally in not yet merged PR. The one discussed here is more about the `is_valid()` function that return False sometimes for unknown reason when doing a manual search/download..

**Comment by morpheus65535** [comment]
Is this still an issue? I talk about the `no valid subtitles` error of course.

**Comment by morpheus65535** [comment]
I'm closing this one. Please reopen if you still have this issue.

**Comment by helix-noise** [comment]
Hello,

I'm experiencing the same problem when I'm manual downloading from opensubtitles.org

[bazarr.log](https://github.com/morpheus65535/bazarr/files/8808124/bazarr.log)

**Comment by morpheus65535** [comment]
> Hello,
> 
> I'm experiencing the same problem when I'm manual downloading from opensubtitles.org Python version 3.7.13
> 
> [bazarr.log](https://github.com/morpheus65535/bazarr/files/8808124/bazarr.log)

Don't necro a 3 years old issue... open yours please.
