### ISSUE TITLE
Subdivx is not working

### ISSUE THREAD

**Issue by agusaon** [morpheus65535/bazarr#524]
**Describe the bug**
Subdivx is not working either by automatic or manual download.

**To Reproduce**
Add Subdivx as subtitle provider and try to download a subtitle.

**Expected behavior**
Start downloading a subtitle.

**Screenshots**
Not applicable.

**Software (please complete the following information):**
 - Bazarr: 0.8
 - Sonarr version: 2.0.0.5338
 - OS: Raspbian

**Additional context**
The log file is showing:

`HTTPSConnectionPool(host='www.subdivx.com', port=443): Max retries exceeded with url: /index.php?pg=1&accion=5&buscar=Billions+S04E12&oxdown=1 (Caused by SSLError(SSLError(1, u'[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:727)'),)), retrying in 5 seconds...
`

**Comment by halali** [comment]
problem is a weak ssl DH key used by the subdivx server

**Comment by morpheus65535** [comment]
Works for me this morning. They probably had an issue with their certificate and they have fixed it.

**Comment by agusaon** [comment]
So the error seems to be related to this: https://200ok.ch/posts/2019-07-02_openssl_responded_ssl_dh_key_too_small.html

@morpheus65535 do you know where can I add ssl_version=tls1_2 in bazzar's code so that it falls back to an older ssl protocol?

**Comment by agusaon** [comment]
Ok, so I found the solution in case anyone finds the same issue running Raspbian Buster. The thing is Subdivx is running with an older SSL certificate https://github.com/psf/requests/issues/4775

The only way to change this would be to speak to the subdivx admin and tell them to upgrade their security. But for now, what I did (although it's not really safe) was to change the last 2 lines in /etc/ssl/openssl.cnf to:

`MinProtocol = TLSv1.1
CipherString = DEFAULT@SECLEVEL=1
`

 @morpheus65535 maybe this could be added so that anyone running the server from source on raspbian cold know. And if anyone knows of a better solution, that'd be awesome.

**Comment by morpheus65535** [comment]
Thank you for providing the result of your debug session. I'll keep that one in mind!

**Comment by mclssk** [comment]
works for me!!! thanks!!!

**Comment by jalarab** [comment]
Not working for me las few weeks.

**Comment by morpheus65535** [comment]
@jalarab open a new issue with debug log while reproducing the issue.

**Comment by jalarab** [comment]
I received this message:
Using subdivx again after 6 hours, (disabled because: ParseResponseError)
That the website is working well
