### ISSUE TITLE
Error updating movie list from Radarr

### ISSUE THREAD

**Issue by tehniemer** [morpheus65535/bazarr#527]
**Describe the bug**
Movie list isn't being updated from Radarr

**To Reproduce**
1. Install and configure Bazarr
2. Connect Radarr and test settings to confirm valid
3. Watch logs

**Expected behavior**
Bazarr connects to radarr and pulls movie list

**Screenshots**
```
2019-08-31 12:38:10,404 - apscheduler.executors.default    (7fd17c7ceb20) :  ERROR (base:131) - Job "Update movies list from Radarr (trigger: interval[0:05:00], next run at: 2019-08-31 12:43:10 CDT)" raised an exception
```

**Software (please complete the following information):**
 - Bazarr: 0.8
 - Radarr version: 2.0.0.1427
 - Sonarr version: 3.0.3.616
 - OS: Docker

**Additional context**
All docker containers are from Linuxserver

**Comment by morpheus65535** [comment]
If I’m not wrong, Radarr v2.x is Aphrodite and is currently not supported as the API is unstable.

**Comment by tehniemer** [comment]
I see, you are correct, it is Aphrodite.
