### ISSUE TITLE
non english characters are f up

### ISSUE THREAD

**Issue by icf20** [morpheus65535/bazarr#528]
**Describe the bug**
for some reasons the downloaded file is F up 

**To Reproduce**
1. Go to https://www.opensubtitles.com/en/subtitles/dave-chappelle-the-age-of-spin-2017-1080p-webrip-dd5-1-x264-trollhd
2. Click on  download edit 
3, compare to the version bazarr downloads

version downloaded by bazarr
```
1
00:00:07,882 --> 00:00:09,634
<i>El e Dave.</i>

2
00:00:10,176 --> 00:00:12,053
<i>Îºi câºtgã pâinea cu glume porcoase.</i>

3
00:00:12,762 --> 00:00:15,932
<i>Privirea aceea e locul
în care se petrece munca grea.</i>

4
00:00:16,016 --> 00:00:19,477
<i>Indicã un ºir de gânduri profunde,</i>
```

version manually downloaded

```
1
00:00:07,882 --> 00:00:09,634
<i>El e Dave.</i>

2
00:00:10,176 --> 00:00:12,053
<i>Îşi câştgă pâinea cu glume porcoase.</i>

3
00:00:12,762 --> 00:00:15,932
<i>Privirea aceea e locul
în care se petrece munca grea.</i>

4
00:00:16,016 --> 00:00:19,477
<i>Indică un şir de gânduri profunde,</i>

```

**Expected behavior**
see correctly the romanian characters

**Software (please complete the following information):**
 - Bazarr: Bazarr Ver. 0.8
 - Radarr Radarr Ver. 0.2.0.1358
 - OS: linux + docker

**Comment by icf20** [comment]
![image](https://user-images.githubusercontent.com/17784575/64068064-0a512800-cc33-11e9-928e-0a2a155861ea.png)

this image is what i get if i open both file and copy all in the one downloaded by bazarr and then save in sublimetext


if i repeat the copy all paste all i dont get any warning 


https://en.wikipedia.org/wiki/Windows-1252

**Comment by morpheus65535** [comment]
Did you try to disable `Encode subtitles to UTF-8` in Settings—>Subtitles?

**Comment by morpheus65535** [comment]
Is this one fixed?

**Comment by icf20** [comment]
![image](https://user-images.githubusercontent.com/17784575/64359835-7227ba00-d009-11e9-931a-cdad058ff127.png)

dint have that enabled
