### ISSUE TITLE
Error renaming some subtitles (Spanish)

### ISSUE THREAD

**Issue by lordvault** [morpheus65535/bazarr#529]
**Description**
On some subtitles the system is generating an error on the logs is trying to replace the original video file. Maybe an error renaming the sub file.

**To Reproduce**
1. Add a movie/series
2. The video has top rate.
3. Try to download 

**Expected behavior**
The subtitle must add the subtitle extension at the end of the file.

**Screenshots**
![image](https://user-images.githubusercontent.com/6520372/64207197-c5f79f00-ce61-11e9-9007-57de3d1a8fbd.png)

**Software (please complete the following information):**
 - Bazarr: [v 0.8.0]
 - Radarr version [v 0.2.0.5358]
 - OS: [Windows 10]

**Additional context**

Providers: Opensubtitle and subdivx.  

![image](https://user-images.githubusercontent.com/6520372/64207876-23402000-ce63-11e9-9a2b-3558ad78934d.png)

**Comment by morpheus65535** [comment]
What provider? Do you use path mapping?

**Comment by morpheus65535** [comment]
Btw click on one of the error to get the complete error and paste it here.

**Comment by lordvault** [comment]
Updated post with the error. I'm using opensubtitles and subdivx I saw the error for both.

**Comment by morpheus65535** [comment]
Try disabling utf8 conversion in settings—>subtitles.

**Comment by lordvault** [comment]
The setting is off :O 
![image](https://user-images.githubusercontent.com/6520372/64208252-0e17c100-ce64-11e9-8b57-45b2f394270c.png)

**Comment by lordvault** [comment]
I downloaded one of the files manually and i saw some spanish characters like 'ñ' and accents on the name of the files, maybe thats the issue. 

![image](https://user-images.githubusercontent.com/6520372/64208926-e6752880-ce64-11e9-8569-d892ce656b34.png)

**Comment by morpheus65535** [comment]
Did you tried to enable the settings and try again?

**Comment by lordvault** [comment]
I did it but the error persist.
![image](https://user-images.githubusercontent.com/6520372/64212223-445a3e00-ce6e-11e9-8099-70fc85c9cc74.png)

**Comment by morpheus65535** [comment]
What is your locale in Windows?

**Comment by lordvault** [comment]
![image](https://user-images.githubusercontent.com/6520372/64218389-00bffe00-ce87-11e9-8201-e25b237eea3e.png)

Its on spanish. 
Bazarr has a temporal folder to dowmload the subs?. Or is printed in any log the complete path of the subtitle to rename ?

**Comment by morpheus65535** [comment]
You can enable debug logging in settings-->general, clear the log and try to reproduce the issue?

**Comment by lordvault** [comment]
Here is the log on debug. 
![image](https://user-images.githubusercontent.com/6520372/64222535-08d36a00-ce96-11e9-9aa9-b92a53ff257f.png)

**Comment by morpheus65535** [comment]
Please provide the bazarr.log file by downloading it from System-->Logs-->Download log file.

**Comment by lordvault** [comment]
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3572554/bazarr.log)

**Comment by morpheus65535** [comment]
Can you reproduce this with `Encode subtitles to UTF8` enabled in Settings-->Subtitles? Can you provide a new debug log even if the error looks like it's the same? Thanks.

**Comment by lordvault** [comment]
I dont know why but today with the Encode subtitles to UTF8 enabled the subtitle imports start to work. 
Tnks for your help.
