### ISSUE TITLE
Non-english character in Series Name borks Bazarr

### ISSUE THREAD

**Issue by Kabraxist** [morpheus65535/bazarr#530]
I have this series tracked in Sonarr, which has a Turkish "Ç" letter in it's name. Whenever I add that series to Sonarr, Bazarr tasks seems to work in background but I can't access the frontend until I remove that series.

![image](https://user-images.githubusercontent.com/14184502/64409780-3ab12000-d092-11e9-86fa-86b079fb449e.png)

In Sonarr:
![image](https://user-images.githubusercontent.com/14184502/64409808-4bfa2c80-d092-11e9-9694-41ab0bc08a6f.png)

**Comment by morpheus65535** [comment]
Probably the same issue as #421 .
