### ISSUE TITLE
Can't open bazarr WebUi

### ISSUE THREAD

**Issue by i420** [morpheus65535/bazarr#531]
I installed bazarr before and it was working fine but after playing around with docker and reinstalling bazarr it won't work anymore, I can't manage to open the web ui. docker is uninstalled now and also reinstalled bazarr couple times after the docker uninstall but it won't work anymore here are my log and config files.

its seems the IP has changed to 212. ***. ***. ***, I see in the previous log files where bazarr was running fine the IP was set to 0. ***. ***. *** (0.0.0.0)
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3584755/bazarr.log)
[config.txt](https://github.com/morpheus65535/bazarr/files/3584759/config.txt)

**Comment by halali** [comment]
You have change your ip in data/config/config.ini to 0.0.0.0

**Comment by i420** [comment]
> 
> 
> You have change your ip in data/config/config.ini to 0.0.0.0

It's working now thanks!
