### ISSUE TITLE
"Scan disk for subtitles" will end's with server error and strange path

### ISSUE THREAD

**Issue by theerror** [morpheus65535/bazarr#532]
Seems, that all configuration setup are valid. It's correct path - no issue there:

![image](https://user-images.githubusercontent.com/4508328/64464448-42aba700-d108-11e9-8710-cfc00ae693ac.png)

however, when I click on "Scan disk for subtitles" I will get error page with quote strange path (duplicated "Movies/Movies"):

![image](https://user-images.githubusercontent.com/4508328/64464677-1e9c9580-d109-11e9-9a31-654a84606f37.png)

I tried severals change in path mapping, however it will break movie overview or the searching.

Bazarr version 0.8
Sonarr version 2.0.0.5322
Radarr version 0.2.0.1358
Operating system
Linux-4.4.59+-x86_64-with (container from Linuxserver)

**Comment by theerror** [comment]
and seems, that trying to download subs makes no difference :(

![image](https://user-images.githubusercontent.com/4508328/64465062-e72ee880-d10a-11e9-8a90-58ce1388a98e.png)

**Comment by morpheus65535** [comment]
That's a bug I've found a couple of days ago but I haven't fixed it in dev or master branch yet. I'll do it tonight in dev and I should merge it to master during the weekend.

https://github.com/morpheus65535/bazarr/commit/5eba6db10daf1bb28a0dedb1210ca48cd8cb211a

If you want to "fix" this, change your volume mapping for the container to not have `movies` multiple time. Come to Discord if you want live support about it.

**Comment by theerror** [comment]
actually just realised the same, that it could be issue in multiple nested replacement... so fine you found it!

**Comment by morpheus65535** [comment]
Merged to master a couple of minutes ago.
