### ISSUE TITLE
provider subscene.com

### ISSUE THREAD

**Issue by bison529** [morpheus65535/bazarr#534]
**Describe the bug**
i want to use subscene as provider for subtitles, because Arab Translators focus on this site.
but when i choose subscene alone as provider in bazarr with my account in subscene give me nothing in search for subtitles. also i already enabled Anti-captcha.

**Software (please complete the following information):**
 - Bazarr: [v0.8]
 - Radarr version [v0.2.0.1358]
 - Sonarr version [v3.0.3.624]
 - OS: [Ubuntu 16.04]

**Comment by morpheus65535** [comment]
Please provide a debug log.

**Comment by bison529** [comment]
when i click om debug log show empty!

![image](https://user-images.githubusercontent.com/55077641/64524052-6a685e00-d306-11e9-944a-6d606ae8b7fa.png)

**Comment by morpheus65535** [comment]
You need to enable debug logging first in Settings-->General.

**Comment by bison529** [comment]
this is log file:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3590021/bazarr.log)

thanks

**Comment by morpheus65535** [comment]
No subtitles have a good enough score: `Score 102 is below min_score (108)`. Reduce minimum score for movie to 80% in Settings but don't expect perfectly in sync subs.

**Comment by bison529** [comment]
okay, i put minimum score for movie to 50% but nothing download automatic, but when i use manually search i found some subtitles score 80% !!.
if i put minimum score 50% must be download any score upper 50%, right?

**Comment by morpheus65535** [comment]
Yes it should. Please provide another debug log once minimum score is changed to 50%.

**Comment by bison529** [comment]
this log file after i change minimum score to %50
[bazarr (1).log](https://github.com/morpheus65535/bazarr/files/3590098/bazarr.1.log)

**Comment by morpheus65535** [comment]
`BAZARR Subtitles file saved to disk: /mnt/unionfs/Movies/The Green Mile (1999)/The Green Mile (1999) Bluray-1080p - hdmi.srt`

I suggest you disable single language mode if you don't need it.

**Comment by morpheus65535** [comment]
Is this still an issue?

**Comment by morpheus65535** [comment]
I close it. Reopen if required.
