### ISSUE TITLE
Bazarr oblivious to mysteriously missing subtitles

### ISSUE THREAD

**Issue by tommit** [morpheus65535/bazarr#535]
Sometimes I find to my surprise that:
1. Radarr (with the help of the torrent client) has successfully downloaded a movie, renamed it **{Movie Title} ({Release Year}).mkv** and put it in a folder named **{Movie Title} ({Release Year})**
2. Bazarr lists the movie on the **localhost:6767/movies** page and says on the **localhost:6767/wanted** page that _"No missing movie subtitles"_
3. Yet there is not subtitle file in the movie folder

And I'm not sure what causes this, but I have a theory which I believe to be (at least partly) correct. I believe that the following has happened:
1. Radarr (...the torrent client) has downloaded the movie
2. Bazarr has downloaded subtitles for the movie
3. Radarr has downloaded a better version of the movie and replaced the old version, and in the process, also deleted the downloaded subtitle file
4. Bazarr never becomes aware that the subtitle file has been deleted, and therefore it never re-downloads it automatically

Like I said, I'm not sure this is what happens, but if it is, I think the solution is that Bazarr should from time to time do a full disk scan to check for missing subtitles, including those movies it has already downloaded the subtitles for.

I can update this report with more information the next time this happens.

I'm currently using the following versions, but I'm not sure which versions the apps were on the last time this issue occurred:

Bazarr version 0.8.1
Radarr version 0.2.0.1358
Sonarr version 3.0.3.625
Windows 10

Here are some of the relevant Bazarr settings I'm using:
![Bazarr Subtitles Options](https://user-images.githubusercontent.com/7393895/64645799-557eee00-d41e-11e9-8e43-e6a6a6bb704e.png)

**Comment by halali** [comment]
You can set full sync frequency in settings/radarr to daily at 5am

**Comment by tommit** [comment]
The **Bazarr > Settings > Radarr > Full sync frequency** setting has always been set to **Daily (at 5am)** in my setup. So, that setting doesn't explain this issue I've been seeing. It is possible that I've always observed the issue within the (at most) 24h window where the subtitle file has been deleted but Bazarr hasn't yet noticed it missing. But that's quite unlikely because the issue has occurred with at least four different movies, and typically I don't watch the movies (and notice the subtitles missing) for many weeks after downloading them. But the next time the issue occurs, I can gather more information and post a new bug report about it where I can refer to this one.

**Comment by morpheus65535** [comment]
Bazarr should get the new path from Radarr during the "every 5 minutes" job that sync movies. If the path have changed, Bazarr will scan for existing subtitles and download missing subtitles. If the filename doesn't change because you are renaming file at a point where two different release have the same name, Bazarr won'T detect the change and no scan will occur.

**Comment by tommit** [comment]
My movie title/folder naming is simply: **{Movie Title} ({Release Year})**. No video quality or anything like that in the name, which means my paths always stay the same. Here's a screenshot of my **Radarr > Settings > Media Management** page:
![Radarr - Settings - Media Management](https://user-images.githubusercontent.com/7393895/64690320-bfd47480-d498-11e9-848f-7e0eae97acb8.png)

I've also been relying on [Infuse](https://firecore.com/infuse) to download the correct metadata (poster and such) based on the file/folder name, and at least [their documentation](https://support.firecore.com/hc/en-us/articles/215090947-Metadata-101) doesn't mention anything about including video quality or other data in the filename, which makes me a bit wary of changing the naming.

**Comment by morpheus65535** [comment]
Finding good subtitles highly depend on having the good information to have a good match. If you rely on subtitles, I highly suggest that you don't rename movie files, only the directory.

**Comment by tommit** [comment]
Okay, I changed my **Radarr > Settings > Media Management > Standard Movie Format** to **{Original Filename}**. Which I suppose means I won't have this issue anymore and I probably won't be able to provide any further information about the original issue, and therefore it's fine by me to close this report.

**Comment by morpheus65535** [comment]
Feel free to reopen it if needed.
