### ISSUE TITLE
Napisy24 and Napiprojekt providers not working

### ISSUE THREAD

**Issue by drikqlis** [morpheus65535/bazarr#536]
**Describe the bug**
When trying to use Napisy24 and Napiprojekt providers no subtitles are returned no matter the file, even though providers have subtitles for them. Other providers work, i tested it on two separate bazarr instances on Ubuntu and Windows 10 and nothing is found each time. Napisy24 in debug log returns:
`Skipping provider 'napisy24': not a valid video`
And Napiprojekt returns:
`DEBUG (napiprojekt:41) - No subtitles found`
Full example log is attached.

**To Reproduce**
1. Go to Settings -> Subtitles.
2. Enable Napisy24 and Napiprojekt providers.
3. Set enabled languages to Polish.
4. Try to manaully or automatically search for subtitles for any movie or episode.

**Expected behavior**
Subtitles should be found, especially when searching manually. In the exemple log i searched for movie Ant-Man and you can clearly see that providers have subtitles for that movie:
https://napisy24.pl/komentarze?napisId=89453
https://www.napiprojekt.pl/napisy1,1,1-dla-37681-Ant-Man-(2015)

**Screenshots**
![obraz](https://user-images.githubusercontent.com/19647553/64681341-d3271600-d47f-11e9-811f-e898ee41f3e5.png)
![obraz](https://user-images.githubusercontent.com/19647553/64682451-c4416300-d481-11e9-88f9-5db051fbda8e.png)
![obraz](https://user-images.githubusercontent.com/19647553/64682468-cefbf800-d481-11e9-8895-8e6ee5a718ab.png)
![obraz](https://user-images.githubusercontent.com/19647553/64683224-2484d480-d483-11e9-969b-cbce0bd03a61.png)

**Software (please complete the following information):**
 - Bazarr: v 0.81
 - Radarr version: v 0.2.0.1358
 - Sonarr version: v 2.0.0.5338
 - OS: Checked on two instances - Ubuntu 18.0.4 LTS and Windows 10 1903
 - Python: Windows - 2.7.16, Ubuntu: 2.7.15+

**Additional context**
Other providers like opensubtitles and podnapisi work as expected.

**Files**
[debug.log](https://github.com/morpheus65535/bazarr/files/3599797/debug.log)

**Comment by morpheus65535** [comment]
@MoshiMoshi0 is it working for you?

**Comment by MoshiMoshi0** [comment]
Yes they both work for me fine, but im on v0.8.

It seems the hash did not get computed for napisy24 provider for some reason.
Don't know about napiproject, probably just the hash did not match anything.

**Comment by morpheus65535** [comment]
@MoshiMoshi0 thanks!

Do you use path mapping?

**Comment by drikqlis** [comment]
On the test Windows instance i have path mapping, but on Ubuntu it is not needed so it's empty.

I reverted the test instance to 0.8 and napisy24 seems to be searching now but i still don't get any results on anything. How does this hash matching works, does the file has to be identical?

**Comment by morpheus65535** [comment]
That the principle behind the hash concept. :-)

Your file hash must match the hash of the file as reported by the provider.

**Comment by drikqlis** [comment]
Does other providers also work using hash? My files are reencoded but I get results from providers like opensubtitiles or podnapisi.

**Comment by halali** [comment]
You are renaming and reencoding subs, so you remove most of informations that bazarr need to match best subtitlea... Every provider work with different source informations. So some providers can match some subs and another will don't... Also dont expect subtitlea will match your file timing, with your usecase is it very hard.

**Comment by morpheus65535** [comment]
I agree, you don't have a lot of chance of getting good subtitles. I'll close this issue as the provider are working as expected.
