### ISSUE TITLE
exception raised when search missing is activated

### ISSUE THREAD

**Issue by ligii** [morpheus65535/bazarr#539]
**Describe the bug**
When go for subtitles exception is raised, and subtitles are not downloaded.
 
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/bazarr/get_subtitle.py", line 593, in series_download_subtitles
  \series\)
 File "/app/bazarr/bazarr/get_subtitle.py", line 269, in download_subtitle
  track_event(category=downloaded_provider, action=action, label=downloaded_language)
 File "/app/bazarr/bazarr/analytics.py", line 34, in track_event
  visitor.unique_id = unique_id
 File "/app/bazarr/bazarr/../libs/pyga/entities.py", line 425, in __setattr__
  raise ValueError(\Visitor unique ID has to be a 32-bit integer between 0 and 0x7fffffff\)
ValueError: Visitor unique ID has to be a 32-bit integer between 0 and 0x7fffffff

**Software (please complete the following information):**
Bazarr version - development branch
0.8.2
Sonarr version
2.0.0.5338
Radarr version
0.2.0.1358
Operating system
Linux-4.19.0-6-amd64-x86_64-with
Python version
2.7.16
Bazarr directory
/app/bazarr
Bazarr config directory
/config

**Additional context**
If analytics is disabled - everything works fine

**Comment by morpheus65535** [comment]
Could you try to remove the `visitor` key in `analytics` section of `config.ini` and try again with analytics enabled? It will generate a new Visitor Unique ID.

**Comment by ligii** [comment]
Still doesn't work.

**Comment by morpheus65535** [comment]
huh... ok.. strange one... I'll close it but reopen if you face the issue again.

**Comment by morpheus65535** [comment]
Found the issue. Fixed now. TY
