### ISSUE TITLE
Segmentation fault on startup

### ISSUE THREAD

**Issue by peskdale** [morpheus65535/bazarr#54]
Since 0a6b82e (Update to stop using "import pip" which is an unsupported usage.) I've been unable to reliably start and run bazarr.

Debugging with gdb:
```
(gdb) run bazarr.py
Starting program: /usr/bin/python bazarr.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0005f708 in visit_decref (op=<optimized out>, data=<optimized out>, op=<optimized out>)
    at ../Modules/gcmodule.c:360
360     ../Modules/gcmodule.c: No such file or directory.
```

Traceback:
```
(gdb) py-bt
Traceback (most recent call first):
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/home/pi/.local/lib/python2.7/site-packages/pycountry/db.py", line 67, in _load
    tree = json.load(f)
  File "/home/pi/.local/lib/python2.7/site-packages/pycountry/db.py", line 42, in load_if_needed
    self._load()
  File "/opt/bazarr/get_languages.py", line 7, in <module>
    for lang in pycountry.languages
  File "bazarr.py", line 81, in <module>
    from get_languages import *
```

OS is Raspbian Stretch on a Pi 3. I've done a fresh OS install today to rule out issues with my install. Can't figure out why this could be happening - any ideas?

**Comment by morpheus65535** [comment]
I've removed dust on my Pi3 and I'm installing everything. I'll come back soon.

**Comment by morpheus65535** [comment]
Ok, I've made it to run. I've edited the wiki. You need to install libjpeg8-dev. I've made a small change to the update process so required module would be installed for user, not system. This way, you don't need to run Bazarr as root (or sudo).

**Comment by morpheus65535** [comment]
Ok, I get segfault after the initial execution of bazarr (the initial one run perfectly). If I run it with sudo, it run smoothly.

You seem to be way better than me with Linux and I would appreciate getting your help on that one.

BTW: if I comment out the "from update_modules import *" in bazarr.py, everything works fine...

**Comment by peskdale** [comment]
After a lot of experimenting, moving ` from update_modules import *` earlier in `bazarr.py` to before `from PIL import Image` stops the segfaulting when run as a regular user.

Shouldn't all of those imports happen after `update_modules` has run anyway? I notice requests and pycountry are also being imported earlier.

Is libjpeg8-dev actually needed? This didn't seem to fix any fault.

**Comment by morpheus65535** [comment]
Regarding libjpeg8-dev: on Raspbian stretch lite, I couldn't build Pillow without it.

**Comment by morpheus65535** [comment]
If you run `python -m pip install --user -r requirements.txt`, how long does it take? Mine is installing over and over again even if requirements are already satisfied from last execution... strange...

**Comment by peskdale** [comment]
It takes a while - it does seem like it's reinstalling every time.

**Comment by morpheus65535** [comment]
It's strange because I don't get this under Windows 10 or Debian 9.4 (stretch)... And I can't found anything about this and Raspbian on the web. :-/

**Comment by morpheus65535** [comment]
I've moved update_modules up but I need to keep it after some import (os, sys, sqlite, logging, etc.) if I want everything keeps working. Seems to be working for me. Could you try it please?

**Comment by peskdale** [comment]
Latest master working for me.

**Comment by morpheus65535** [comment]
Thank you for taking the time to debug this with me!
