### ISSUE TITLE
Bazarr history is empty

### ISSUE THREAD

**Issue by rickytin** [morpheus65535/bazarr#541]
In Bazarr Ver. 0.8.2 development the history for series and movies is empty.
I have been using Bazarr for almost a year and it is the first time I see the history empty.

**Comment by morpheus65535** [comment]
Please send me your bazarr.db file on Discord in private. I need to see what's wrong with your DB to understand the issue.

**Comment by rickytin** [comment]
Thanks for the help, already send.
