### ISSUE TITLE
File location

### ISSUE THREAD

**Issue by modem7** [morpheus65535/bazarr#542]
Hey guys, 

The way I run my media server is: Sonarr/Radarr dumps completed file into a seperate dedicated hard drive, and then I push those to the storage array. 

Is there a way that I can get Bazarr to be pointed towards the storage array (much like Sonarr/Radarr's import feature) so that I can have it scan all my media for subtitles?

Thanks!

**Comment by morpheus65535** [comment]
Bazarr can work with any file. The only condition is that Sonarr/Radarr are responsible for providing the path to the media file. If Sonarr provide the path and Bazarr is able to read/write to that directory, no problem.
