### ISSUE TITLE
Python 3.x in the future?

### ISSUE THREAD

**Issue by icecore2** [morpheus65535/bazarr#544]
In the code, I saw the string that Python 3 isn't supported.
There will be a change in the near future?

b.w The support of Python 2.x is ending soon.(https://pythonclock.org)

**Comment by morpheus65535** [comment]
Near future: probably not. We are aware of the support ending soon but the code base is large and dependencies numerous. It's going to be a lot of work to make it work under Python 3.

We have a feature request for this so I'll close this issue.
