### ISSUE TITLE
Unnecessary amount of requests to Sonarr

### ISSUE THREAD

**Issue by jyggen** [morpheus65535/bazarr#546]
I was watching the access log on one of my servers and noticed that Bazarr is, in my opinion, doing a whole lot of unnecessary requests to Sonarr. More specifically it's doing about 100 requests during a couple of seconds every minute to `/api/system/status?apikey=<key>` which seems insane.

I'm not sure what Bazarr needs from that endpoint every minute, maybe it's a health check or something, but a hundred requests to get the same information just seems absurd to me. Surely this is unintentional and a bug somewhere? :)

Running Bazarr 0.8.1 and Sonarr 2.0.0.5338.

Thanks!

**Comment by jyggen** [comment]
After further investigation I'm note entirely sure it's Bazarr to be honest. Sorry about that! I'll reopen if it actually is Bazarr :)

**Comment by jyggen** [comment]
Sorry about the back-and-forthing here, but I shut down Bazarr completely and the requests stopped, so something is definitely suspicious here :)

**Comment by morpheus65535** [comment]
Should be fixed by now in dev branch.

**Comment by morpheus65535** [comment]
Did you get a chance to test it?

**Comment by jyggen** [comment]
Sadly I'm currently running Bazarr in a [docker container](https://github.com/linuxserver/docker-bazarr), so I'm not sure there's a way for me to easily test it. I'll look into it when I have some more time to dive into it :)

**Comment by morpheus65535** [comment]
You can try with linuxserver/bazarr:development

**Comment by jyggen** [comment]
Ah, I missed there was a development tag. Tested it now and it seems to be fixed indeed!

**Comment by morpheus65535** [comment]
Good, thanks for reporting!
