### ISSUE TITLE
Request Provider turkcealtyazi.org

### ISSUE THREAD

**Issue by emrahkaval** [morpheus65535/bazarr#547]
Hello,
Can you add https://turkcealtyazi.org/ support for subtitles?
There is no official api but some peoples write api for it https://github.com/febalci/turkcealtyazi.org-API

**Comment by morpheus65535** [comment]
Feature and provider requests must me created on https://bazarr.featureupvote.com/.

**Comment by casab** [comment]
https://github.com/morpheus65535/bazarr/pull/2836

I have implemented this.
