### ISSUE TITLE
Using post-processing to encore to utf-8 bom

### ISSUE THREAD

**Issue by lukjod** [morpheus65535/bazarr#549]
As my 2014 pre web os LG TV only supports utf-8 bom encoded srt to display right characters im trying to call postprocessing script

/share/CACHEDEV1_DATA/.qpkg/Python3/src/bin/python3.6 /share/CACHEDEV1_DATA/.qpkg/Python3/src/bin/cvt2utf convert "{{subtitles}}" -b --nobak

which i need directly to point me to new created srt file but always getting wrong output.
which value to use in {{........}} to directly get /path_to/name.srt 

python script to encode
https://github.com/x1angli/cvt2utf

**Comment by morpheus65535** [comment]
By default, Bazarr directly save with UTF8 BOM. You don'T need ay post processing for that.

**Comment by lukjod** [comment]
well, it doesnt work that way and eg notepad++ show just utf-8 after bazarr downloaded srt file which after ssh command as above changes to utf-8 BOM and works good on my tv.
Can You please help me to get valid path to bazarr downloaded srt file?

**Comment by morpheus65535** [comment]
Add quote around the accolades.

**Comment by lukjod** [comment]
nope, won´t help, but i used them from start in this way

**Comment by morpheus65535** [comment]
Did you make it work?

**Comment by lukjod** [comment]
unfortunately using cron script which changes pl.srt subs from utf-8 to utf-8 bom every 10 mins, probably it can be better but im not too good on scripts

**Comment by morpheus65535** [comment]
Sorry for not being able to help you more. Enjoy!
