### ISSUE TITLE
Gevent error on Synology DS916+

### ISSUE THREAD

**Issue by NjayNL** [morpheus65535/bazarr#564]
I got the following error on my synology running dsm 6.2 using the linux installaton wiki.

root@DS916:/volume1/Bazarr/bazarr# /volume1/@appstore/python/bin/python2.7 bazarr.py
Bazarr starting...
ERROR:root:BAZARR require gevent Python module to be installed using pip.
Traceback (most recent call last):
  File "bazarr/main.py", line 30, in <module>
    import gevent
ImportError: No module named gevent
Bazarr exited.

Gevent is installed when i check it with PIP

any ideas?

**Comment by halali** [comment]
Install gevent by pip install gevent

**Comment by NjayNL** [comment]
it's installed

**Comment by NjayNL** [comment]
when trying to run with python bazarr.py it's gives an error on a too low python version i need to adjust my start script to the correct version installed on my syno box

**Comment by halali** [comment]
Error say you have missing gevent module

**Comment by morpheus65535** [comment]
Minimal version of Python is 2.7.13. Be sure you are installing gevent using the right pip if you have multiple version of Python installed.

**Comment by NjayNL** [comment]
> Minimal version of Python is 2.7.13. Be sure you are installing gevent using the right pip if you have multiple version of Python installed.

How do i do that? All python versions seems installed in the same directory

**Comment by morpheus65535** [comment]
I don't know. It's related to your hardware/operating system and I'm not familiar with Synology NAS.

**Comment by dimitrov-adrian** [comment]
@NjayNL why not install via docker? I am using it in that way and it works without issues at all.

**Comment by halali** [comment]
Closings this.

**Comment by NjayNL** [comment]
If anyone wants to know i have solved but using the following command for synology /volume1/@appstore/python/bin/pip2.7 install gevent
