### ISSUE TITLE
Authentification for WebUI access

### ISSUE THREAD

**Issue by secret-liar** [morpheus65535/bazarr#57]
Hi!

Would it be possible to add a login/password prompt in order to access the WebUI?

Thanks!

**Comment by Freekers** [comment]
+1 from me for this one 👍

**Comment by jeroenpardon** [comment]
and from me 👍

**Comment by danjames92** [comment]
Preferably forms login ala Sonarr / Radarr.

**Comment by morpheus65535** [comment]
Is basic auth also required or only forms login?

**Comment by danjames92** [comment]
I'm sure people would love both options.

**Comment by morpheus65535** [comment]
I've implemented it in dev branch. Could you please try it? Only basic auth for now. For auth is another ball game. Please report!

**Comment by Freekers** [comment]
I am short on time the coming few weeks. I cannot promise you whether or not I can test this for you in the next couple of weeks, but I'll see what I can do.

**Comment by morpheus65535** [comment]
No problem!

@secret-liar Did you have time to test this one?

**Comment by secret-liar** [comment]
Hi!

Sorry I was busy and I forgot to test.
For me it's working :)
A form would be ideal but this is great for now ;)

Le mer. 8 août 2018 16 h 10, morpheus65535 <notifications@github.com> a
écrit :

**Comment by morpheus65535** [comment]
Good news. Form require me to manage session cookie on the client browser.

I'll merge this to master soon.
