### ISSUE TITLE
Error trying to get best subtitles for this file

### ISSUE THREAD

**Issue by Sharmii** [morpheus65535/bazarr#58]
I get this error:

`'Traceback (most recent call last):\n File "/opt/Bazarr/bazarr/get_subtitle.py", line 35, in download_subtitle\n best_subtitles = download_best_subtitles([video], {Language(language)}, providers=providers, min_score=minimum_score, hearing_impaired=hi, provider_configs=providers_auth)\n File "/opt/Bazarr/bazarr/libs/subliminal/core.py", line 647, in download_best_subtitles\n compute_score=compute_score)\n File "/opt/Bazarr/bazarr/libs/subliminal/core.py", line 227, in download_best_subtitles\n if self.download_subtitle(subtitle):\n File "/opt/Bazarr/bazarr/libs/subliminal/core.py", line 182, in download_subtitle\n if not subtitle.is_valid():\n File "/opt/Bazarr/bazarr/libs/subliminal/subtitle.py", line 85, in is_valid\n if not self.text:\n File "/opt/Bazarr/bazarr/libs/subliminal/subtitle.py", line 76, in text\n return self.content.decode(self.guess_encoding(), errors=\'replace\')\nTypeError: decode() argument 1 must be string, not None'`

Anyone got an idea?

**Comment by morpheus65535** [comment]
Bazarr catch an exception in returned by Subliminal. I suppose there is a problem with the subtitles file returned by your provider. Maybe look if this provider is in problem?

**Comment by morpheus65535** [comment]
Seems to be a recurring error on SickRage to:
https://github.com/SickRage/SickRage/issues/2667

Happened 6 days ago for a user. Maybe a bug in Subliminal 2.0.5. Maybe it's going to be fixed in Subliminal 3.

**Comment by Sharmii** [comment]
Okay thanks 👍
