### ISSUE TITLE
Version check code chokes on python 2.7.15rc

### ISSUE THREAD

**Issue by kbirger** [morpheus65535/bazarr#580]
**Describe the bug**
Version check chokes on rc versions of python.

Sorry I'm on a phone, so I'm skipping the template. I know where the bug is anyway.

For whatever reason, my Mint Linux has python 2.7.15rc1 on it. In the first few lines of bazarr.py you try to take each version segment and call int() on it. So you're calling int('15rc1').

I would imagine there's a version comparison package out there somewhere

**Comment by morpheus65535** [comment]
Fixed directly in master branch: https://github.com/morpheus65535/bazarr/commit/e7bebc495f1d5ba9ee454b6d2cc4ecef27e84b87

Thanks for reporting.

**Comment by kbirger** [comment]
Thanks for the quick turnaround @morpheus65535
