### ISSUE TITLE
Error when trying to download subs

### ISSUE THREAD

**Issue by Byt3C0d3** [morpheus65535/bazarr#581]
**Describe the bug**
I have a show with episodes which are missing a sub. I have addic7ed configured (creds are correct). Addic7ed has the subtitle I'm looking for (manually confirmed), but the app says no subs were found. There's an error in the logs.

**To Reproduce**
1. Go to a show's page and find an episode that has missing subtitles which are available from your subtitle providers
2. Hit manual search.
3. You see an error about not being able to find subs, and the log shows an error. (see end)

**Expected behavior**
A list of subs pops up for you to download

**Software (please complete the following information):**
 - Bazarr: 0.8.1 (head of master as of 8-18-19
 - Sonarr version 3.0.3.644
 - OS: Linux Mint 19

**Additional context**

> Traceback (most recent call last): File "/home/user/bazarr/bazarr/get_subtitle.py", line 334, in manual_search language_hook=None) # fixme File "/home/user/bazarr/bazarr/../libs/subliminal_patch/core.py", line 694, in list_all_subtitles subtitles = pool.list_subtitles(video, languages - video.subtitle_languages) File "/home/user/bazarr/bazarr/../libs/subliminal_patch/core.py", line 219, in list_subtitles provider_subtitles = self.list_subtitles_provider(name, video, languages) File "/home/user/bazarr/bazarr/../libs/subliminal_patch/core.py", line 140, in list_subtitles_provider if not provider_registry[provider].check(video):AttributeError: NoneType object has no attribute check

**Comment by morpheus65535** [comment]
Do you have an anti-captcha provider configured?

**Comment by Byt3C0d3** [comment]
Thanks! I disabled addic7ed and that did the trick. I think maybe when I had originally set this up addic7ed didn't use captchas, or the case was handled differently.

Feel free to close this, but I wonder if it would make sense to flag a warning, or prevent enabling providers that you've flagged as requiring captcha resolvers if none are configured.

**Comment by morpheus65535** [comment]
In fact addic7ed have been discarted because no anti-captcha was enabled. The problem is that you didn't had any other provider enabled then it failed.
