### ISSUE TITLE
Job "Update series list from Sonarr" raised an exception

### ISSUE THREAD

**Issue by cinco** [morpheus65535/bazarr#587]
Hi,

 I cant update my Series list from sonarr. Sonar has new series dont be displayed in bazarr.

When execute Job "update series list from sonarr":

![image](https://user-images.githubusercontent.com/125763/65392369-a1992f00-dd4a-11e9-9b69-47b1b66a4b41.png)

> Message
> Job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2019-09-22 15:09:13 -03)" raised an exception

> Exception
> Traceback (most recent call last):
>  File "/usr/lib/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
>   retval = job.func(*job.args, **job.kwargs)
>  File "/usr/lib/bazarr/bazarr/get_series.py", line 27, in update_series
>   audio_profiles = get_profile_list()
>  File "/usr/lib/bazarr/bazarr/get_series.py", line 146, in get_profile_list
>   profiles_json = requests.get(url_sonarr_api_series, timeout=60, verify=False)
> UnboundLocalError: local variable \url_sonarr_api_series\ referenced before assignment

Test connection with Sonarr:
![image](https://user-images.githubusercontent.com/125763/65392503-10c35300-dd4c-11e9-80cf-3c0763ae5f67.png)

**Software:**
 - Bazarr version - 0.8.1
 - Sonarr version - 10.0.0.41181
 - Radarr version - 0.2.0.1358
 - Operating system- Linux-5.2.14-arch2-1-ARCH-x86_64-with-glibc2.2.5
 - Python version - 2.7.16

**Comment by halali** [comment]
What is your sonarr version. Version you have in issue isn't exist.

**Comment by halali** [comment]
And thats the issue, we auport sonarr v2 and v3 we dont support self compiled sonarr with unknown version
