### ISSUE TITLE
subs4free provider not working

### ISSUE THREAD

**Issue by morpheus65535** [morpheus65535/bazarr#589]
I get this error when I try to search for a Greek subtitles from this provider:
`Skipping provider 'subs4free': not a valid video`

**Comment by morpheus65535** [comment]
@pkoutsias could you take a look please? Thanks!

**Comment by pkoutsias** [comment]
@morpheus65535 subs4free is a movies only site, maybe you search for an episode?

**Comment by morpheus65535** [comment]
Indeed, it was the issue... Thanks for your help! :-)
