### ISSUE TITLE
subtitriid provider not working

### ISSUE THREAD

**Issue by morpheus65535** [morpheus65535/bazarr#590]
I cannot get search result when searching for a Latvian subtitles for this provider:
`Skipping provider 'subtitriid': no language to search for`

@girtskokars could you take a look please? Thanks!

**Comment by morpheus65535** [comment]
My mistake... forget it!

**Comment by girtskokars** [comment]
correct me if i'm wrong, but isn't it just a debug message that gets logged out when the provider is enabled, but movie/series is not configured to download the language that the provider supports?

tested with the subtitriid provider - if i remove "Latvian" language from movie "Subtitles languages" and search for subtitles - indeed it does print out this message, if i add it back in - it does not (just downloads the subtitle)

**Comment by morpheus65535** [comment]
Sorry, my bad... I had forced=true... 🤦‍♂
