### ISSUE TITLE
Exception after downloading subtitle, process stops

### ISSUE THREAD

**Issue by Seketh** [morpheus65535/bazarr#591]
Running on a Raspberry Pi 4, Raspian Buster.

After sucessfully downloading a subtitle, I get the following error:

`Job "manual_wanted_search_missing_subtitles (trigger: date[2019-09-23 12:37:16 WEST], next run at: 2019-09-23 12:37:16 WEST)" raised an exception
`

`Traceback (most recent call last): File "/opt/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job retval = job.func(*job.args, **job.kwargs) File "/opt/bazarr/bazarr/get_subtitle.py", line 890, in wanted_search_missing_subtitles wanted_download_subtitles(episode.path, i, count_episodes) File "/opt/bazarr/bazarr/get_subtitle.py", line 794, in wanted_download_subtitles history_log(1, episode.sonarr_series_id.sonarr_series_id, episode.sonarr_episode_id, message, path, language_code, provider, score) File "/opt/bazarr/bazarr/utils.py", line 32, in history_log TableHistory.score: score File "/opt/bazarr/bazarr/../libs/peewee.py", line 1785, in inner return method(self, database, *args, **kwargs) File "/opt/bazarr/bazarr/../libs/peewee.py", line 1856, in execute return self._execute(database) File "/opt/bazarr/bazarr/../libs/peewee.py", line 2572, in _execute return super(Insert, self)._execute(database) File "/opt/bazarr/bazarr/../libs/peewee.py", line 2321, in _execute return self.handle_result(database, cursor) File "/opt/bazarr/bazarr/../libs/peewee.py", line 2579, in handle_result return database.last_insert_id(cursor, self._query_type) File "/opt/bazarr/bazarr/../libs/peewee.py", line 3035, in last_insert_id return cursor.lastrowid File "/opt/bazarr/bazarr/../libs/playhouse/sqliteq.py", line 88, in lastrowid self._wait() File "/opt/bazarr/bazarr/../libs/playhouse/sqliteq.py", line 63, in _wait raise self._excIntegrityError: NOT NULL constraint failed: table_history.id`

Bazarr won't download any more subtitles. I've tried other subtitle providers, and the same thing happens. The process continues to search for subtitles normally if none are found.

This might be somehow related to rclone. My files are on Google Drive and encrypted with rclone, although I have no issues with any other service that uses the mounts.

**Comment by morpheus65535** [comment]
I see you are running dev branch. Are you fully updated? Could you provide a complete debug log please where I can see what happens when you reproduce the issue?

**Comment by Seketh** [comment]
Yes, it's a fresh install. I tried stable, had the error, then tried dev.

Please find the debug log attached.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3646535/bazarr.log)

**Comment by morpheus65535** [comment]
Thanks. I’m looking into it. If you start from scratch with master then, once the db is created, you should be fine. The problem seems to be related to blank db creation in dev branch. Table_history.id should be an auto increment field and it is not define correctly in new code.

**Comment by Seketh** [comment]
Thank you for looking into this.

Installing master from scratch also doesn't work, just tried it. Here's the log, hope it helps:

[bazarr_master.log](https://github.com/morpheus65535/bazarr/files/3647542/bazarr_master.log)

**Comment by morpheus65535** [comment]
This last error is unrelated. Just disable Analytics in settings and it's going to be working. I have a patch in dev branch for this issue but I want to be sure that we don't face db issue before merging it to master.

**Comment by Seketh** [comment]
With Analytics disabled it's working correctly, thanks.

**Comment by morpheus65535** [comment]
I've just pushed a fix in dev branch. If you are willing, could you try to update Bazarr source and restart a new DB from scratch? Thanks!

**Comment by Seketh** [comment]
Good news! Just tried dev from scratch and it's working.

Thank you for fixing this so quickly (and for the software).

Best regards!

**Comment by morpheus65535** [comment]
Thank you for testing it so quickly! :-)
