### ISSUE TITLE
Death by Captcha Access denied

### ISSUE THREAD

**Issue by theimmortal68** [morpheus65535/bazarr#593]
I am attempting to set up Addic7ed as a subtitles provider. I have an account with Addic7ed and I just setup an account with a positive balance on Death by Captcha. I have entered the credentials into the settings for both Addic7ed and Death by Captcha (verified multiple times including looking at it in config.ini). However, Bazarr does not retrieve any results from Addic7ed, even though I know they exist. In my log I am getting the following error message when doing a manual search:

```
bazarr.log:23/09/2019 15:07:25|ERROR   |subliminal_patch.core           |Unexpected error in provider 'addic7ed': Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 162, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 99, in __getitem__    provider.initialize()  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/addic7ed.py", line 120, in initialize    result = pitcher.throw()  File "/opt/bazarr/bazarr/../libs/subliminal_patch/pitcher.py", line 84, in throw    data = self._throw()  File "/opt/bazarr/bazarr/../libs/subliminal_patch/pitcher.py", line 213, in _throw    data = self.client.decode(timeout=self.timeout, type=4, token_params=payload)  File "/opt/bazarr/bazarr/../libs/deathbycaptcha.py", line 203, in decode    uploaded_captcha = self.upload(captcha, **kwargs)  File "/opt/bazarr/bazarr/../libs/deathbycaptcha.py", line 476, in upload    response = self._call('upload', data)  File "/opt/bazarr/bazarr/../libs/deathbycaptcha.py", line 414, in _call    self._call('login', self.userpwd.copy())  File "/opt/bazarr/bazarr/../libs/deathbycaptcha.py", line 444, in _call    raise AccessDeniedException('Access denied, check your credentials')AccessDeniedException: Access denied, check your credentials|Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 162, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 99, in __getitem__    provider.initialize()  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/addic7ed.py", line 120, in initialize    result = pitcher.throw()  File "/opt/bazarr/bazarr/../libs/subliminal_patch/pitcher.py", line 84, in throw    data = self._throw()  File "/opt/bazarr/bazarr/../libs/subliminal_patch/pitcher.py", line 213, in _throw    data = self.client.decode(timeout=self.timeout, type=4, token_params=payload)  File "/opt/bazarr/bazarr/../libs/deathbycaptcha.py", line 203, in decode    uploaded_captcha = self.upload(captcha, **kwargs)  File "/opt/bazarr/bazarr/../libs/deathbycaptcha.py", line 476, in upload    response = self._call('upload', data)  File "/opt/bazarr/bazarr/../libs/deathbycaptcha.py", line 414, in _call    self._call('login', self.userpwd.copy())  File "/opt/bazarr/bazarr/../libs/deathbycaptcha.py", line 444, in _call    raise AccessDeniedException('Access denied, check your credentials')AccessDeniedException: Access denied, check your credentials|
```

**Comment by morpheus65535** [comment]
Do you have special characters or uppercase letters in your username/password?

**Comment by theimmortal68** [comment]
I did have a special character. They require an uppercase, lowercase, and either a number or special character. I changed my password and it seems to authenticate now but it fails to solve the captcha:

**Comment by morpheus65535** [comment]
I don’t use DBC but Anti-Captcha. I have no issue with AC. Do DBC take credit for unsolved Captcha?

**Comment by azza10** [comment]
I believe you don't pay for unsolved captchas.
I have been using DBC for about a week with no issues til now. I received an email yesterday stating that I have been marking captchas wrong that were correctly solved.

As bazarris the only software using my DBC account it must be something to do with it.

These are the solved stats on my DBC account.

https://photos.app.goo.gl/uKSwZEvJQ5UPeqoF6

**Comment by theimmortal68** [comment]
I just went back to check on it and always to be working at the moment.  DBC does 3 failed and 2 successful, so at least it's taking properly. I will see if it continues to work or if it's intermittent.

**Comment by azza10** [comment]
There is definitely an issue with too many failed. Maybe a timeout is set too low? I'm not sure how login is verified by bazarr.

**Comment by morpheus65535** [comment]
Ok keep me informed. We use a module to interface with DBC and it looks like it a bit old and have been updated. Maybe we should run a test if you want. How do you run Bazarr? From source? Docker? Windows installer?

**Comment by azza10** [comment]
I run windows installed.
Windows 10.

**Comment by morpheus65535** [comment]
First, stop Bazarr service in `services.msc`. 

In Bazarr directory, go to `libs` directory and rename `deathbycaptcha.py` in `deathbycaptcha.py.bkp`.

Save this file in the same directory under this name: `deathbycaptcha.py`
https://raw.githubusercontent.com/codevance/python-deathbycaptcha/master/deathbycaptcha/__init__.py

Start Bazarr service and run a test.

**Comment by theimmortal68** [comment]
I run bazarr from source on Ubuntu.

**Comment by azza10** [comment]
Bazarr refuses to connect with the new file in place. Old one back and it works again. Not going to be a drop in fix unfortunately...

**Comment by morpheus65535** [comment]
Thanks.

@pannal looks like somethings wrong with DBC. You wanna take a look?

**Comment by morpheus65535** [comment]
Seems to be working fine for other users. Is it still an issue?

**Comment by azza10** [comment]
Hey mate, they disabled my accounts ability to report a captcha as failed, I still seem to be able to log in to DBC and get subs from addic7ed so I guess that's a no?

Kind of a workaround, but if it ain't broke.

To be clear, I'm not sure it's actually resolved the original issue I was having with bazarr. Just that even with them disabling my account from reporting false failures it seems like everything is still working.

**Comment by morpheus65535** [comment]
Ok, we'll see if someone else face the same issue. We'll investigate if it's the case. Thanks for your answer!

**Comment by jbusuttil83** [comment]
Hi, is it normal to have captchas not solved when using with DBC?
 Exception info: "Addic7ed: Couldn't solve captcha!

**Comment by morpheus65535** [comment]
@jbusuttil83 Don't necropost on a one year old issue. Open a new one and provide all the information required.
