### ISSUE TITLE
Provider 'opensubtitles' is discarded

### ISSUE THREAD

**Issue by sand3rk** [morpheus65535/bazarr#594]
**Describe the bug**
When I first installed Bazarr it was working fine. No it does not download subtitles when downloading manual or automatic.

LOG:

  | Terminating provider opensubtitles | a few seconds ago
-- | -- | --
  | Terminating initialized providers | a few seconds ago
  | Downloaded 0 subtitle(s) | a few seconds ago
  | : Score 12 is below min_score (84) | a few seconds ago
  | Provider 'opensubtitles' is discarded | a few seconds ago
  | :  Trying to download subtitle with matches set(['year',  'hearing_impaired', 'imdb_id', 'title']), score: 91; release(s):  Toy.Story.4.2019.DVDRip.XviD.AC3-EVO | a few seconds ago
  | Provider 'opensubtitles' is discarded | a few seconds ago
  | :  Trying to download subtitle with matches set(['year', 'video_codec',  'title', 'resolution', 'hearing_impaired', 'imdb_id']), score: 95;  release(s): Toy.Story.4.2019.1080p.WEBRip.x264.AAC2.0-SHITBOX | a few seconds ago
  | https://api.opensubtitles.org:443 "POST /xml-rpc HTTP/1.1" 200 201 | a few seconds ago
  | DNS: Falling back to default DNS or IP on api.opensubtitles.org | a few seconds ago
  | Starting new HTTPS connection (1): api.opensubtitles.org:443 | a few seconds ago
  | Downloading subtitle | a few seconds ago
  | Downloading subtitle | a few seconds ago
  | :  Trying to download subtitle with matches set(['year', 'video_codec',  'format', 'title', 'resolution', 'hearing_impaired', 'imdb_id']), score:  102; release(s): Toy.Story.4.2019.1080p.BluRay.x264-SPARKS | a few seconds ago
  | : Computed score 3 with final matches set(['video_codec', 'hearing_impaired']) | a few seconds ago

**Expected behavior**
To auto download the subs, or manually.

**Comment by morpheus65535** [comment]
Please provide a complete log file instead of just some part copied from the UI. I suspect you're searching for Forced subtitles instead of normal one.

**Comment by sand3rk** [comment]
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3657330/bazarr.log)

I set:
Forced = false (Movies default settings)

**Comment by morpheus65535** [comment]
Ok... no clue... Really strange. Were you using 0.8.1 prior to your new installation? Are you using Pi-Hole or something like this?

**Comment by sand3rk** [comment]
0.8.1 fresh install.
Yes PFblockerNG, I will check logs. But it was working fine yesterday...

**Comment by sand3rk** [comment]
Ok'e, really weird, I did nothing. But Bazarr just downloaded the missing sub... 
Thanks for developing!

**Comment by morpheus65535** [comment]
I've just tested OS and it works for me also. Keep me informed if the problem come back.
