### ISSUE TITLE
Error Job "Update series list from Sonarr" raised an exception

### ISSUE THREAD

**Issue by Dukko** [morpheus65535/bazarr#596]
Not sure what's going on.

`Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/bazarr/get_series.py", line 27, in update_series
  audio_profiles = get_profile_list()
 File "/app/bazarr/bazarr/get_series.py", line 146, in get_profile_list
  profiles_json = requests.get(url_sonarr_api_series, timeout=60, verify=False)
UnboundLocalError: local variable \url_sonarr_api_series\ referenced before assignment`

Bazarr v. 0.8.1
Sonarr v. 2.0.0.5338

**Comment by morpheus65535** [comment]
Please show me the JSON returned by your Sonarr API: `http://sonarr:8989/api/system/status?apikey=INSERT_API_KEY_HERE`

**Comment by Dukko** [comment]
"version": "2.0.0.5338",
  "buildTime": "2019-08-14T21:57:18Z",
  "isDebug": false,
  "isProduction": true,
  "isAdmin": false,
  "isUserInteractive": false,
  "startupPath": "/opt/NzbDrone",
  "appData": "/config",
  "osName": "ubuntu",
  "osVersion": "18.04",
  "isMonoRuntime": true,
  "isMono": true,
  "isLinux": true,
  "isOsx": false,
  "isWindows": false,
  "branch": "master",
  "authentication": "none",
  "sqliteVersion": "3.22.0",
  "urlBase": "/sonarr",
  "runtimeVersion": "5.20.1.34",
  "runtimeName": "mono"
}

**Comment by morpheus65535** [comment]
On what hardware are you running Sonarr and Bazarr?

**Comment by Dukko** [comment]
Ubuntu server with individual docker containers in a stack. Bazarr can 
see Sonarr fine when testing though.

------ Original Message ------

**Comment by morpheus65535** [comment]
I’ll add some logging in dev branch to see why it fail to get sonarr version.

**Comment by Ic3Nine** [comment]
I'm getting the same issue on v3

"version": "3.0.0.348",
"buildTime": "2018-12-29T14:21:37.89175Z",
"isDebug": false,
"isProduction": true,
"isAdmin": true,
"isUserInteractive": false,
"startupPath": "C:\ProgramData\Sonarr\bin",
"appData": "C:\ProgramData\Sonarr",
"osName": "Windows",
"osVersion": "10.0.17134.0",
"isMonoRuntime": false,
"isMono": false,
"isLinux": false,
"isOsx": false,
"isWindows": true,
"branch": "master",
"authentication": "none",
"sqliteVersion": "3.8.7.2",
"urlBase": "",
"runtimeVersion": "4.6.2",
"runtimeName": "dotNet"

**Comment by morpheus65535** [comment]
I've added more logging to dev branch. If you could try with this and provide a debug log, it would be appreciated. Thanks!

**Comment by ilcavero** [comment]
I have what might be the same issue on 0.8.2.2 and sonarr 2.0.0.5338
`Traceback (most recent call last):
 File "/usr/lib/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/usr/lib/bazarr/bazarr/get_series.py", line 157, in update_series
  added_series
 File "/usr/lib/bazarr/bazarr/../libs/peewee.py", line 5979, in insert
  return ModelInsert(cls, cls._normalize_data(__data, insert))
 File "/usr/lib/bazarr/bazarr/../libs/peewee.py", line 5963, in _normalize_data
  (key, data))
ValueError: Unrecognized field name: "alternate_title" in {......}.`
```

**Comment by morpheus65535** [comment]
Yes it as been corrected in both master and dev. It need to have a "s" at the end and it is there. There no reason to have this issue unless you'Re not "really" on 0.8.2.2. I don't say you're lying but just that the update process is maybe not complete. Tell me more about your environment.

**Comment by ilcavero** [comment]
you are right, I'm only on 0.8.2, the "releases" tab confused me. I'm on the aur package https://aur.archlinux.org/packages/bazarr that's just a bit behind. Thanks
