### ISSUE TITLE
Schedule 'Search for wanted subtitles' to only occur at night.

### ISSUE THREAD

**Issue by maxtheking** [morpheus65535/bazarr#598]
**Describe the bug**
By default Bazarr will search for wanted subtitles every 3 hours, and since my Libary is huge it will take quite some time, and also consume a lot of CPU power. Is there a way to change the subtitle search to only happen at night, at 4am for example?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 0.8.1
 - Radarr version [e.g. v 0.2.0.0001]
 - Sonarr version [e.g. v 2.0.0.0001]
 - OS: [e.g. Windows 10]

**Additional context**

**Comment by morpheus65535** [comment]
This is a feature request and it shouldn't be done here.

There's already a commit to be able to customize the search frenquency. You can choose from every 3, 6, 12 or 24 hours. This is available in dev now and should be merged to master soon.

490e4ad5158a67d0fb5d824691006f65e65d6dd8

**Comment by halali** [comment]
Also i suggest enable adaptive searching
