### ISSUE TITLE
Subtitles not being detected

### ISSUE THREAD

**Issue by Zanhard** [morpheus65535/bazarr#599]
Running bazarr 0.8.1 in a docker container using LSIO image. Running on arch linux host. Detects movies and tv shows, paths are correct, show up in wanted. Manually downloaded subtitles show up in the history, but under the individual show/movie the subtitle is not listed even when they exist on the disk. Following error is being received in the bazarr log:
File "/app/bazarr/bazarr/list_subtitles.py", line 161, in store_subtitles_movie
  only_one=settings.general.getboolean(\single_language\))
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 659, in search_external_subtitles
  only_one=only_one))
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 622, in _search_external_subtitles
  language = Language.fromietf(language_code)
 File "/app/bazarr/bazarr/../libs/subzero/language.py", line 62, in inner
  instance = f(cls, base, *args, **kwargs)
 File "/app/bazarr/bazarr/../libs/subzero/language.py", line 127, in fromietf
  return Language(*Language_.fromietf(ietf).__getstate__())
 File "/app/bazarr/bazarr/../libs/babelfish/language.py", line 123, in fromietf
  language = cls.fromalpha2(language_subtag)
 File "/app/bazarr/bazarr/../libs/babelfish/language.py", line 109, in fromcode
  return cls(*language_converters[converter].reverse(code))
 File "/app/bazarr/bazarr/../libs/babelfish/converters/__init__.py", line 165, in reverse
  raise LanguageReverseError(code)
LanguageReverseError: u\re\

**Comment by morpheus65535** [comment]
What language are you searching for?

**Comment by Zanhard** [comment]
I have it set to single language, English.

**Comment by zendi1** [comment]
How do i set paths correctly when running bazarr using docker in dsm m, while sonarr/radarr are running directly via dsm?

**Comment by morpheus65535** [comment]
@Zanhard don’t enable single language. It doesn’t work well.

**Comment by Zanhard** [comment]
I have disabled single language and attempted again with the same result. I cleared the log and manually triggered each item in the task list. I also went to wanted and selected download all wanted. Finally I went into a movie, selected scan disk for subtitles. I also clicked English to force manual download. Subtitle exists on disk, and the download action shows in history for the manually triggered download. No others have downloaded.og has same error message as last time. I've tried versions 0.8 and 0.8.1.

Traceback (most recent call last):
 File "/app/bazarr/bazarr/list_subtitles.py", line 161, in store_subtitles_movie
  only_one=settings.general.getboolean(\single_language\))
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 659, in search_external_subtitles
  only_one=only_one))
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 622, in _search_external_subtitles
  language = Language.fromietf(language_code)
 File "/app/bazarr/bazarr/../libs/subzero/language.py", line 62, in inner
  instance = f(cls, base, *args, **kwargs)
 File "/app/bazarr/bazarr/../libs/subzero/language.py", line 127, in fromietf
  return Language(*Language_.fromietf(ietf).__getstate__())
 File "/app/bazarr/bazarr/../libs/babelfish/language.py", line 123, in fromietf
  language = cls.fromalpha2(language_subtag)
 File "/app/bazarr/bazarr/../libs/babelfish/language.py", line 109, in fromcode
  return cls(*language_converters[converter].reverse(code))
 File "/app/bazarr/bazarr/../libs/babelfish/converters/__init__.py", line 165, in reverse
  raise LanguageReverseError(code)
LanguageReverseError: u\re\

**Comment by morpheus65535** [comment]
Please provide a debug log (emptied before reproducing). `re` isn't a valid language code and I don't know from where it get this.

**Comment by Zanhard** [comment]
Reproduced by pressing "Update subtitles from disk" task button.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3668153/bazarr.log)

**Comment by Zanhard** [comment]
You pointed out the language code so I went into subtitles settings, cleared English from languages, refreshed the page to verify the language field was empty, then specified English again. Cleared log and tried again with same result. Should I try with a different language selected?

**Comment by Zanhard** [comment]
I tried again setting the language in settings to Arabic, using the movie editor and setting movies to Arabic and trying again with the same result.

**Comment by morpheus65535** [comment]
You didn't enable debug log prior to reproduce. I can't see anything with this disabled.

**Comment by Zanhard** [comment]
My mistake:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3668383/bazarr.log)

**Comment by morpheus65535** [comment]
can you provide a copy of your bazarr.db? I'm not sure what's happening.. BTW you're not running 0.8.1 but dev branch 0.8.2.

**Comment by Zanhard** [comment]
[bazarr.zip](https://github.com/morpheus65535/bazarr/files/3668716/bazarr.zip)

**Comment by Zanhard** [comment]
I was on 0.8.1 but someone on discord suggested I try the development branch to see if it made a difference.

**Comment by morpheus65535** [comment]
Can you show me your path mapping please?

**Comment by Zanhard** [comment]
Sonarr:
/media/Movies/Shows - > /tv
Radarr:
/media/Movies/Movies - > /movies

**Comment by morpheus65535** [comment]
I have no idea why but it seems that Bazarr is unable to update existing subtitles.... I'm kind of lost as they are detected but cannot be written to DB.

**Comment by Zanhard** [comment]
Not sure if it could be a file permission thing? Seems weird since sonarr radarr are able to write to those locations and they are in containers as well. I can try installing it onto the host machine and not use a container and see if it makes a difference.

**Comment by morpheus65535** [comment]
> /media/Movies/Shows

Why are you referring to the physical path on the docker host if Sonarr (and Radarr btw) are runninf inside a container? What is the path of a random episode as seen by Sonarr? And one random movie as seen by Radarr?

**Comment by Zanhard** [comment]
Movie inside radarr:
/movies/<movie title>/<movie file>

Show in radarr:
/tv/<series name>/<season #>/<episode files>

**Comment by Zanhard** [comment]
Hmm before when I had /tv - > /tv (or /movies - > /movies) I was setting mapping errors. I've tried changing the path mapping again and it seems to be working now, not sure what has changed.
