### ISSUE TITLE
Add support of development branch of subliminal

### ISSUE THREAD

**Issue by TMadMac** [morpheus65535/bazarr#60]
Bazarr should be able to run development branch of subliminal. (Give me the badge "subliminal v3 required" ;) )

Subliminal in master branch is way too old and inefficient (2 yers old). Even if project maintener sqays new release will comming soon ... it does not append.

I do a little test:
- file name "Brooklyn.Nine-Nine.S05E14.720p.WEB.x264-TBS[rarbg]"
- bazarr (on branch development) using embedded lib subliminal (v2.0.5)
- looking for french subtitle
- no match found, even if I can see on addic7ed a subtitle wiuth those informations : 5 | 14 | The Box | French | WEB-TBS
- switch the embedded subliminal lib of bazarr to the development branch of subliminal
- "voilà" ! the subtitle is found.

**Comment by morpheus65535** [comment]
If you want, we could discuss about it on Bazarr Discord channel (in french btw): https://discord.gg/MH2e2eb

**Comment by morpheus65535** [comment]
You can try it in dev branch.

**Comment by morpheus65535** [comment]
I agree with you that keeping Subliminal up-to-date is going to be an issue. Diaoul doesn't appear to be working on it and I understand that he have a personal and professional life that may request more time.

Supporting both version is going to be tricky on my side. Every time I am going to use a new functionality or providers, I'm going to have to develop some logic to differentiate 2.0.5 and 2.1.0dev in my code. I don't want to go there (BTW I also got a personal/professional life that need my time ;-) )

**Comment by TMadMac** [comment]
Fully agreed !
