### ISSUE TITLE
Helping a nub to set it up

### ISSUE THREAD

**Issue by zendi1** [morpheus65535/bazarr#600]
I am trying to use linuxserver/bazarr on Docker in my Synology NAS via Docker.
Sonarr/Radarr are running outside of docker with no probs whatsoever

Unfortunately i struggle to set up the correct paths to my moviefiles. The listing of the files works but bazarr tells me'this path doesn't seems to be valid'

How can i set it up right?

**Comment by morpheus65535** [comment]
Come to Discord for live support.
