### ISSUE TITLE
Error trying to get video information for this file

### ISSUE THREAD

**Issue by varac** [morpheus65535/bazarr#601]
**Describe the bug**

Bazarr won't  download subtitles for some movies. In the logs you see an `IndexError: list index out of range` (see below for the Traceback).

**To Reproduce**
1. Download a (popular) movie (in my case an .avi)
2. Click on the movie
3. Click on `Manual search`
4. Windows pop up with empty search result
5. Go to system logs
6. Clicking on the `BAZARR Error trying to get video information for this file:` log msg will show:

```
Error trying to get video information for this file: …
Traceback (most recent call last):
 File "/app/bazarr/bazarr/get_subtitle.py", line 70, in get_video
  refine_from_ffprobe(original_path, video)
 File "/app/bazarr/bazarr/get_subtitle.py", line 978, in refine_from_ffprobe
  if \codec\ in data[\audios\][0]:
IndexError: list index out of range
```

**Expected behavior**

I can choose from a list of subtitles which one to download.

**Software (please complete the following information):**
 - Bazarr: 0.8.1
 - Radarr version: 0.2.0.1358
 - Sonarr version: 2.0.0.5338
 - OS: Docker image `linuxserver/bazarr:63d954a00841`

**Comment by varac** [comment]
Manually executing ffprobe on the movie works from inside the container:

```
root@bazarr-74dd584f6-d7cgh:/movies/radarr/# ffprobe ****.avi
ffprobe version 4.1.4 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 8.3.0 (Alpine 8.3.0)
  configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --disable-stripping --disable-static --disable-librtmp --enable-vaapi --enable-vdpau --enable-libopus --disable-debug
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '*****.avi':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2019-07-22T19:41:01.000000Z
  Duration: 00:01:41.23, start: 0.000000, bitrate: 43428 kb/s
    Stream #0:0(eng): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p(tv), 468x272 [SAR 1:1 DAR 117:68], 24 kb/s, 30 fps, 30 tbr, 30k tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2019-07-22T19:41:01.000000Z
      handler_name    : Mainconcept MP4 Video Media Handler
      encoder         : AVC Coding
```

**Comment by morpheus65535** [comment]
There's no audio track in your video file?

**Comment by varac** [comment]
@morpheus65535 Ugh, I didn't realize until now but indeed the audio track is missing. However, bazarr should deal with such situation better and notify the user accordingly.

**Comment by morpheus65535** [comment]
I totally agree on that part! Bazarr shouldn't crash if there's no audio track for a video file. I'll add something to address that. Thanks!

**Comment by morpheus65535** [comment]
Can you test with `linuxserver/bazarr:development`? I've made some serious reworking of that part of code and I just want to be sure the issue is still there in dev branch. Thanks!

**Comment by varac** [comment]
Unfortunatly I removed the video file without audio track, will try once I encounter one again.
