### ISSUE TITLE
Bazarr is flashing a CMD window on screen randomly

### ISSUE THREAD

**Issue by Flippage** [morpheus65535/bazarr#602]
**Describe the bug**
So as of about a week ago, I updated my system to the correct version of Python (didn't realise why Bazarr wouldn't launch). Since then, we've been seeing CMD windows flash on screen constantly.

Sometimes it would do it multiple times a minute, sometimes once an hour. Very intermittent.

After scanning my PC for viruses, clearing my services out, disabling scheduled tasks, running DISM/SFC scans, I finally managed to track it down by taking a screen recording and pausing on the perfect frame.

The CMD window that's flashing up is an FFPROBE process launched by Bazarr.

**To Reproduce**
No idea how to reproduce this. It didn't happen as of a few weeks ago, but my Bazarr wasn't working then either.

**Expected behavior**
Run all processes in the background, and never take over the UI.

**Screenshots**
Here's the screengrab of the window. It flashes so quick it was a headache to finally catch the window with some visible text.
![image](https://user-images.githubusercontent.com/10948118/66033701-f2790680-e546-11e9-98d7-cd81bcc9b53c.png)

**Software (please complete the following information):**
 - Bazarr: 0.8.1
 - OS: Windows 10 x64 (Build 1903)

Sorry if the explanation was a bit long-winded, I'm just chuffed that I managed to figure out what was causing the issue. I'll have to keep Bazarr disabled until there's a fix cause it drives my wife insane.

Thanks,
Flippage

**Comment by morpheus65535** [comment]
Are you running Bazarr in a cmd window or as a service?

**Comment by Flippage** [comment]
It's a shortcut in my shell:startup folder that runs pythons.exe with bazarr.py parameter. 

That's how I run Sonarr and radarr as well. Is there a better way to do it?

**Comment by morpheus65535** [comment]
Never run it as pythonw.exe. Run it in a command window with python.exe as described in the wiki.

**Comment by Flippage** [comment]
Ok I'll try the NSSM process on the wiki and see how that goes. Cheers.
