### ISSUE TITLE
Replace SSL with TLS or HTTPS

### ISSUE THREAD

**Issue by meffect** [morpheus65535/bazarr#603]
Replace SSL with TLS or HTTPS 

SSL doesn't exist anymore

**Comment by morpheus65535** [comment]
Although I agree that SSL isn't as secure as it was, it is still used and TLS is slowly making is way in peoples mind. TLS could be confusing for most people that are using Sonarr and Radarr can still see the SSL protocol used in their respective settings.

**Comment by meffect** [comment]
Thats why I said HTTPS, so your not bound to whatever backend encryption standard is used
