### ISSUE TITLE
TV Greek Subtitles are found but wrong ones downloaded

### ISSUE THREAD

**Issue by greatvc** [morpheus65535/bazarr#604]
Hi to all!

On tv shows if a Greek subtitle exists on any of the Greek Sites it downloads the wrong one.
Example:

> Raising Dion | 1x01 | Episode 1 | 6 hours ago | Modern Greek (1453-) subtitles downloaded from subz with a score of 94.17% using this scene name: Raising.Dion.S01E01.720p.WEBRip.X264-METCON

> 
Grey's Anatomy | 16x01 | Nothing Left to Cling To | 6 hours ago | Modern Greek (1453-) subtitles downloaded from subs4series with a score of 93.06% using this scene name: Greys.Anatomy.S16E01.480p.x264-mSD-Obfuscated

The one downloaded is wrong, another show or something. On the site if you download manually the subtitle it is the correct one. I thought it was only from subs4series but as you can see it is for other site too. Don't get confused its not that it is out of sync or something, it is Greek but is from another show or episode.

You can find attach the logs i can download from the app. If you need further info let me know
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3691466/bazarr.log)

On Movies, the download of Greek subtitles is Correct. Also no issues with English on both TV and Movies.

Also this is from day one i think. I installed Bazarr recently and now that the TV season is started i can see the bug.

Bazarr version
0.8.1
Sonarr version
2.0.0.5338
Radarr version
0.2.0.1358
Operating system
Darwin-18.7.0-x86_64-i386-64bit
Python version
2.7.16
Bazarr directory
Bazarr config directory
/Applications/bazarr/data

Looking forward to crashing this bug! :+1:

**Comment by halali** [comment]
Please provide Debug log for this issue.

**Comment by greatvc** [comment]
Here you go @halali 
I did a delete of subtitle and manual download and it again returns another Greek Subtitle so it was easy to reproduce. 
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3692982/bazarr.log)

**Comment by halali** [comment]
Sorry, i think i dont understand what is your issue, because in log file you searched for 

`Greys.Anatomy.S16E01.480p.x264-mSD-Obfuscated.mkv`

And you get 

`https://www.subs4series.com/tv-series/greys-anatomy/s0b0897bb5e/season-16/episode-1`

And thats is good... i dont understand what different subtitles you get

**Comment by greatvc** [comment]
Hi Halali and thanks for the reply
I examined the debug log a bit more and if you do you will see the differences.

This part is correct as you say

> ownloading subtitle <Subs4SeriesSubtitle 'https://www.subs4series.com/tv-series/greys-anatomy/s0b0897bb5e/season-16/episode-1' [el:None]>|

but below we see that it actually downloads another subtitle:

> 
>  |https://www.subs4series.com:443 "GET /greek-subtitles/scb6e3f06d5/greys-anatomy-s16e01-720p1080p-amzn-web-dl-ddp5-1-h-264-ntb-nothing-left-to-cling-to HTTP/1.1" 200 None|
> 05/10/2019 11:02:24|DEBUG   |urllib3.connectionpool          |https://www.subs4series.com:443 "GET /includes/anti-block-layover.php?launch=1 HTTP/1.1" 200 None|
> 05/10/2019 11:02:24|DEBUG   |urllib3.connectionpool          |https://www.subs4series.com:443 "GET /includes/anti-block.php HTTP/1.1" 200 None|
> 05/10/2019 11:02:25|DEBUG   |urllib3.connectionpool          |https://www.subs4series.com:443 "GET /getSub-<span style="color:red">**tkMTU3MDI2MjU0NDEzOTkxNjE4NDE1NDM0ODY3ODg**</span>=.html HTTP/1.1" 302 None|

The one in bold is wrong. 

> The correct link is: https://www.subs4series.com/getSub-**tkMTU3MDM1MDU0Mzc1NDk1ODA4ODI3NTE0Mjc1MzI**=.html

Attached are the subtitles downloaded from the site directly and the one i have from bazarr

[bazarr subtitle.txt](https://github.com/morpheus65535/bazarr/files/3694124/bazarr.subtitle.txt)
[correct subtitle.txt](https://github.com/morpheus65535/bazarr/files/3694125/correct.subtitle.txt)

**Comment by halali** [comment]
@pkoutsias can you please look to this issue?

**Comment by greatvc** [comment]
> @pkoutsias can you please look to this issue?

hi all! is there any update with this issue ?

**Comment by greatvc** [comment]
> @pkoutsias can you please look to this issue?

pretty please can someone take a loot at this. It is easy reproduce and the logs are clear. The issue is very persistant on Grey's Anatomy and Emergence

**Comment by greatvc** [comment]
Don't want to rant and be excessive but can someone explain to me why this bug should be looked by a Greek Developer (which is one if i understood correctly).
The logs are clear, it founds one hash key link it then downloads another link with different hash. This has nothing to do with Greek language or understanding Greek.
I'm not an expert but i assume a developer in the project can solve this without knowing Greek.

Since this is an open project and it is based on donation, i'm willing to assist a developer by donating and finally fix this. 
I'm open to suggestions and in any way i can help.

thank you

**Comment by morpheus65535** [comment]
We al get that you would like to have this provider working again but, keep in mind:
1. @pkoutsias is the one who developed this provider and we greatly appreciate his contribution. He remain the best person to fix the issue.
2. I've never developed a single provider so I'm not an expert and cannot take back his work easily.
3. I'm currently working to fix a major DB issue that affect thousands of users (higher priority than this issue).
4. Bazarr dev team is, in fact, 2 actives developers to maintain and fix everything where Sonarr and Radarr have dozens.

We'll look into this when we get the time. We do not prioritize based on donation. You are free to make one and we'll appreciate but it won't make this being fixed faster.

**Comment by greatvc** [comment]
> We al get that you would like to have this provider working again but, keep in mind:
> 
> 1. @pkoutsias is the one who developed this provider and we greatly appreciate his contribution. He remain the best person to fix the issue.
> 2. I've never developed a single provider so I'm not an expert and cannot take back his work easily.
> 3. I'm currently working to fix a major DB issue that affect thousands of users (higher priority than this issue).
> 4. Bazarr dev team is, in fact, 2 actives developers to maintain and fix everything where Sonarr and Radarr have dozens.
> 
> We'll look into this when we get the time. We do not prioritize based on donation. You are free to make one and we'll appreciate but it won't make this being fixed faster.

Appreciate the feedback

**Comment by gmerciel** [comment]
Hi @greatvc, I took a look at this, but I couldn't find any issue (I'm using v0.8.2.4) downloading greek subtitles for a series (Agents of SHIELD) from subs4series. The error you pointed out on your previous post is actually normal, if you try to access again with the link you provided as correct, you will realise it's no longer valid, and if you try again you will get a different link.

Is it possible that you have something else in your setup that could be replacing your downloaded file? Maybe a plugin from KODI? I would also try updating to latest version.

Hope it helps

**Comment by greatvc** [comment]
It is not happening on all series, specific ones and always wrong are from Grey's Anatomy, Emergence ans Watchmen. The link maybe stops to be valid after a couple of days but the logs are clear. It has the wrong hash on the download link.

Nothing on KODI or anywhere else. The latest version of Bazarr is running

**Comment by gmerciel** [comment]
The link is valid only for a few minutes. I don't have any of the series you mention on my sonarr, so let me added Grey's Anatomy, download S16E01 and try with that one.

**Comment by gmerciel** [comment]
I've just downloaded an episode of Grey's Anatomy, and the subtitles were downloaded without a problem, exactly the sames I get from the web page. I would look again if there's anything else besides bazarr downloading subtitles, but I can confirm it's not a problem with bazarr itself.

**Comment by morpheus65535** [comment]
Thank you @gmerciel !
