### ISSUE TITLE
Replace existing not creating new file

### ISSUE THREAD

**Issue by g4m3r7ag** [morpheus65535/bazarr#605]
**Describe the bug**
When Bazarr is replacing an existing SRT file it is not creating a new file and removing the existing but issuing an O_CREAT|O_TRUNC call. When using a cloud drive along with a MergerFS mount that should write local first this causes Bazarr to save to the cloud drive as MergerFS does not receive a create function. 

The delay with saving to a cloud drive causes Bazarr to throw an IO error and advise it did not download the SRT even though it did. MergerFS dev advised alternative method to replacing the file would be to create a temp file for the new SRT then rename it replacing the original, this will allow MergerFS to recognize the create function and then write to the local mount first.

**Comment by morpheus65535** [comment]
Can you test dev branch and confirm it's now working as expected? Thanks!

**Comment by morpheus65535** [comment]
Merged to master just now.

**Comment by g4m3r7ag** [comment]
Just tested this and it appears to be fixed. Removed the cache writes from my rclone mount, restarted/updated the Bazarr container and manually downloaded an existing subtitle and it went to the local directory as it should according to the MergerFS mount. Thank you.

**Comment by morpheus65535** [comment]
Thank you for testing!

@pannal This one could be merged upstream to support MergerFS.
