### ISSUE TITLE
Subdivx failing to retrieve existing subtitles 

### ISSUE THREAD

**Issue by this-is-hydrad** [morpheus65535/bazarr#608]
**Describe the bug**
Bazarr is failing to retrieve existing subtitles from subdivx provider.

**To Reproduce**
1. Go to Disenchantment S1 E 18
2. Click on search manual subtitles
3. Go to logs (debugging mode)
4. See error:

Unexpected error in provider 'subdivx': Traceback (most recent call last): File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 162, in list_subtitles_provider results = self[provider].list_subtitles(video, provider_languages) File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 173, in list_subtitles episode=video.episode, year=video.year) File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 146, in query ).find("a", {'target': 'new'})["href"].replace('http://', 'https://')TypeError: 'NoneType' object has no attribute '__getitem__' | 8 minutes ago
-- | --
  | https://www.subdivx.com:443 "GET /index.php?pg=1&accion=5&buscar=Disenchantment+S01E18&oxdown=1 HTTP/1.1" 200 None

**Expected behavior**
It should correctly retrieve the available subtitle 

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 0.8.1
 - OS: Linuxserver docker image

**Comment by morpheus65535** [comment]
Please update to 0.8.2 and confirm if the issue still exist.

**Comment by gmerciel** [comment]
I was having the same issue. Updating solved it! Thanks!
