### ISSUE TITLE
Question: Orange label in manual search?

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#609]
In the last update, I see there are more info in the manual search window. In most tv series, the orange label has the filename, but in some series, it's none. I don't understand how you get the orange label. I think I'm having problems finding subtitles when the label is none.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/10577978/66338816-29ce2580-e942-11e9-86d9-d2d364a7ea2c.png)

**Software (please complete the following information):**
 - Bazarr: 0.8.2.1

**Comment by halali** [comment]
Its scenename from radarr sonarr. Where is none, radarr sonarr don't provide this info... Maybe because it wasn't downloaded by sonarr radarr

**Comment by ngosang** [comment]
True. Are you using the scene name or the filename to perform the subtitle search?

**Comment by halali** [comment]
Depend on your settings, but if you rename your files i suggest keep that setting enabled

**Comment by ngosang** [comment]
@halali thank you, all clear. Could you add a pop-up in the blue and orange labels with the description? (file path and scene name)

**Comment by morpheus65535** [comment]
Label added in dev branch.
