### ISSUE TITLE
Series list order should match the one of Sonarr

### ISSUE THREAD

**Issue by TMadMac** [morpheus65535/bazarr#61]
Bazarr series ordered by name are not the same as the one of Sonarr.
Sonarr sort by name, excluding "the"

"The americans" for exemple will be at start of list in Sonarr, at end with Bazarr.

**Comment by morpheus65535** [comment]
You can try it in dev branch. Thanks for your suggestion!

**Comment by TMadMac** [comment]
Fast and done !

Thank you, the match is perfect between both UI (sonarr/bazarr)

**Comment by morpheus65535** [comment]
Merged to master branch. Thanks for testing!
