### ISSUE TITLE
Error when trying to analyze this .mkv file

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#610]
I'm getting hundreds of errors like this in the last release.
![imagen](https://user-images.githubusercontent.com/10577978/66339329-37d07600-e943-11e9-8d12-78cb26754740.png)

**Software (please complete the following information):**
 - Bazarr: 0.8.2.1

**Comment by morpheus65535** [comment]
Should be fix in dev, can you test it?

**Comment by morpheus65535** [comment]
Thanks!
