### ISSUE TITLE
Error when updating Series list from Sonarr: Unrecognized field name: "alternate_title"

### ISSUE THREAD

**Issue by nantoine555** [morpheus65535/bazarr#613]
**Describe the bug**
Unable to import a series from sonarr. Other series are imported fine.

Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/bazarr/get_series.py", line 157, in update_series
  added_series
 File "/app/bazarr/bazarr/../libs/peewee.py", line 5979, in insert
  return ModelInsert(cls, cls._normalize_data(__data, insert))
 File "/app/bazarr/bazarr/../libs/peewee.py", line 5963, in _normalize_data
  (key, data))
ValueError: Unrecognized field name: "alternate_title" in {\poster\: u\/MediaCover/93/poster-250.jpg\, \tvdb_id\: 365069, \sort_title\: u\why women kill\, \audio_language\: u\English\, \alternate_title\: "[u\Perch\\\\xe9 le donne uccidono\]", \year\: 2019, \path\: u\/mnt/unionfs/tv/Why Women Kill\, \title\: u\Why Women Kill\, \fanart\: u\/MediaCover/93/fanart.jpg\, \sonarr_series_id\: 93, \overview\: u"Three women living in three different decades: a housewife in the \60s, a socialite in the \80s and a lawyer in 2019, deal with infidelity in their marriages."}.

**To Reproduce**

1. Go to Sonarr
2. Click on Add Series "Why Women Kill "
3. Wait for Bazarr syncing from Sonarr

**Expected behavior**
A correct series import

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: v0.8.2 
 - Sonarr version: 2.0.0.5338
 - OS: Linux Debian 9

**Comment by nantoine555** [comment]
Bazarr Version:
0.8.2.1
Sonarr Version:
2.0.0.5338
Radarr Version:
0.2.0.1358
Operating System:
Linux-4.9.0-11-amd64-x86_64-with
Python Version:
2.7.16

**Comment by halali** [comment]
Fixed in latest dev

**Comment by morpheus65535** [comment]
Fixed in dev branch. Should be merged today.

**Comment by nantoine555** [comment]
Corrected in 0.8.2.2, thank you!
