### ISSUE TITLE
addic7ed in french

### ISSUE THREAD

**Issue by bibi32** [morpheus65535/bazarr#615]
Hello, could you check subtitle in french with addic7ed for sonarr please.
That work for me in english but not in french.
Thanks.

**Comment by morpheus65535** [comment]
Working for me.

![screenshot](https://user-images.githubusercontent.com/5130500/66347707-f3cd7900-e922-11e9-971b-459c4c80bb46.png)

**Comment by bibi32** [comment]
I reinstall bazarr with default setting with Anti-Captcha and that dosen't work.
![Capture d’écran_2019-10-08_00-02-05](https://user-images.githubusercontent.com/26071810/66352057-2bf2ad00-e95f-11e9-9625-b07f4a51c753.png)

**Comment by morpheus65535** [comment]
Please show me NCIS config modal.

**Comment by bibi32** [comment]
you want this ??

![Capture d’écran_2019-10-08_07-25-44](https://user-images.githubusercontent.com/26071810/66369504-f8367800-e99c-11e9-9d23-dbc53ca6c2df.png)

**Comment by morpheus65535** [comment]
That's strange, can you clear your log, enable debug logging and reproduce the manual search? Provide me this log please.

**Comment by bibi32** [comment]
log clear

[bazarr.log.zip](https://github.com/morpheus65535/bazarr/files/3702027/bazarr.log.zip)

There is not a option in sonarr or addic7ed ??

**Comment by morpheus65535** [comment]
Log says it search for `fr` but returned none (only 4 english one were available). I don't know why you don't get french subtitles... :-/

**Comment by bibi32** [comment]
always the same result tonight, if is not bazarr, you have any suggestions ??

**Comment by morpheus65535** [comment]
Send me you bazarr.db. Can be done on Discord.

**Comment by morpheus65535** [comment]
May I close this issue or is it still happening?
