### ISSUE TITLE
Update Bazarr from source on Github raised an exception

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#616]
In Bazarr 0.8.2.1, I clicked in the task Update Bazarr from source on Github. The update was successful but I see this error in the log (after the update is completed).

Message
Job "Update Bazarr from source on Github (trigger: interval[6:00:00], next run at: 2019-10-08 04:49:09 CEST)" raised an exception
Exception
Traceback (most recent call last):
 File "XXX/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "XXX/bazarr/bazarr/check_update.py", line 54, in check_and_apply_update
  updated()
 File "XXX/bazarr/bazarr/check_update.py", line 300, in updated
  updated(restart=False)
 File "XXX/bazarr/bazarr/check_update.py", line 302, in updated
  System.update({System.updated: 1}).execute()
 File "XXX/bazarr/bazarr/../libs/peewee.py", line 1785, in inner
  return method(self, database, *args, **kwargs)
 File "XXX/bazarr/bazarr/../libs/peewee.py", line 1856, in execute
  return self._execute(database)
 File "XXX/bazarr/bazarr/../libs/peewee.py", line 2321, in _execute
  return self.handle_result(database, cursor)
 File "XXX/bazarr/bazarr/../libs/peewee.py", line 2332, in handle_result
  return database.rows_affected(cursor)
 File "XXX/bazarr/bazarr/../libs/peewee.py", line 3038, in rows_affected
  return cursor.rowcount
 File "XXX/bazarr/bazarr/../libs/playhouse/sqliteq.py", line 94, in rowcount
  self._wait()
 File "XXX/bazarr/bazarr/../libs/playhouse/sqliteq.py", line 61, in _wait
  raise ResultTimeout(\results not ready, timed out.\)
ResultTimeout: results not ready, timed out.

![imagen](https://user-images.githubusercontent.com/10577978/66347789-69ead380-e955-11e9-8c70-8e03b6a0d134.png)

**Software (please complete the following information):**
 - Bazarr: 0.8.2.1

**Comment by morpheus65535** [comment]
So it restarted?

**Comment by ngosang** [comment]
> So it restarted?

Yes, it restarted correctly. I'm running Bazarr as a systemd service. If you look at the traces, `Bazarr starting...` is not using the logger.

```
Oct 07 22:49:12 XXX bazarr[440]: 2019-10-07 22:49:12,655 - root                             (7f6d7fa1f0) :  INFO (check_update:53) - BAZARR Updated to latest version. Restart required.  7 files changed, 11 insertions(+), 15 deletions(-
Oct 07 22:49:12 XXX bazarr[440]: 2019-10-07 22:49:12,667 - root                             (7f91cfb1f0) :  INFO (main:213) - Bazarr is being restarted...
Oct 07 22:49:17 XXX bazarr[440]: 2019-10-07 22:49:17,683 - peewee.sqliteq                   (7f9a7a51f0) :  INFO (sqliteq:138) - writer received shutdown request, exiting.
Oct 07 22:49:17 XXX bazarr[440]: 2019-10-07 22:49:17,688 - root                             (7f6d7fa1f0) :  INFO (check_update:299) - BAZARR Restart failed, please restart Bazarr manualy
Oct 07 22:49:47 XXX bazarr[440]: 2019-10-07 22:49:47,698 - apscheduler.executors.default    (7f6d7fa1f0) :  ERROR (base:131) - Job "Update Bazarr from source on Github (trigger: interval[6:00:00], next run at: 2019-10-08 04:49:09 CEST)
Oct 07 22:49:49 XXX bazarr[440]: Bazarr starting...
Oct 07 22:49:59 XXX bazarr[440]: 2019-10-07 22:49:59,043 - root                             (7f7d99abd0) :  INFO (main:2489) - BAZARR is started and waiting for request on http://0.0.0.0:6767/
```

**Comment by ngosang** [comment]
@morpheus65535 Since the updater is working, I give this low priority. Maybe you have other issues to take care about.

**Comment by morpheus65535** [comment]
lol I’m just bleeding from both ears right now! ;-)

I’ll try to test it later. Thanks!

**Comment by morpheus65535** [comment]
@halali could you take a look and find why restart after update doesn't work?

**Comment by animosity22** [comment]
Hmm, not sure if related, I get this when it tries to restart:

```
12/10/2019 13:06:41|INFO    |peewee.sqliteq                  |writer received shutdown request, exiting.|
12/10/2019 13:06:41|INFO    |root                            |BAZARR Restart failed, please restart Bazarr manualy|
12/10/2019 13:07:11|ERROR   |apscheduler.executors.default   |Job "Update Bazarr from source on Github (trigger: interval[6:00:00], next run at: 2019-10-12 19:06:35 EDT)" raised an exception|'Traceback (most recent call last):\n  File "/opt/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File "/opt/bazarr/bazarr/check_update.py", line 54, in check_and_apply_update\n    updated()\n  File "/opt/bazarr/bazarr/check_update.py", line 300, in updated\n    updated(restart=False)\n  File "/opt/bazarr/bazarr/check_update.py", line 302, in updated\n    System.update({System.updated: 1}).execute()\n  File "/opt/bazarr/bazarr/../libs/peewee.py", line 1785, in inner\n    return method(self, database, *args, **kwargs)\n  File "/opt/bazarr/bazarr/../libs/peewee.py", line 1856, in execute\n    return self._execute(database)\n  File "/opt/bazarr/bazarr/../libs/peewee.py", line 2321, in _execute\n    return self.handle_result(database, cursor)\n  File "/opt/bazarr/bazarr/../libs/peewee.py", line 2332, in handle_result\n    return database.rows_affected(cursor)\n  File "/opt/bazarr/bazarr/../libs/peewee.py", line 3038, in rows_affected\n    return cursor.rowcount\n  File "/opt/bazarr/bazarr/../libs/playhouse/sqliteq.py", line 94, in rowcount\n    self._wait()\n  File "/opt/bazarr/bazarr/../libs/playhouse/sqliteq.py", line 61, in _wait\n    raise ResultTimeout(\'results not ready, timed out.\')\nResultTimeout: results not ready, timed out.'|
12/10/2019 13:07:13|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:6767/bazaar/|
```

**Comment by morpheus65535** [comment]
I've updated dev branch with a fix for this.

**Comment by halali** [comment]
Is this still an issue ?
