### ISSUE TITLE
Request: Avoid Empty log redirection

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#617]
If I click in the `Empty log` button. Bazarr redirects me to the Tasks tab. The right think will be stay in the Logs tab to see result.

![imagen](https://user-images.githubusercontent.com/10577978/66348335-994e1000-e956-11e9-8dba-e2016ac06ce7.png)

**Software (please complete the following information):**
 - Bazarr: 0.8.2.2

**Comment by morpheus65535** [comment]
`Empty log` isn't an AJAX call and log table isn't dynamic. I have to reload the page and I cannot activate a tab with Semantic UI.
