### ISSUE TITLE
Request: Disable Movies tab in wanted page

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#618]
I have disabled Radarr/Movies.

History page is right (movies is disabled and I can't click).
![imagen](https://user-images.githubusercontent.com/10577978/66348969-0dd57e80-e958-11e9-8b3f-622f0141d206.png)

Wanted page (I see the 0 counter in movies and I can click in the tab). I expect to see the same as in History page.
![imagen](https://user-images.githubusercontent.com/10577978/66348997-1e85f480-e958-11e9-9d23-21b9075b1a3f.png)

NOTE: I opened several issues today. I don't expect to be fixed fast, most of them are cosmetic / low priority. You can add a label and focus in more important things until you have time.

**Software (please complete the following information):**
 - Bazarr: 0.8.2.2

**Comment by morpheus65535** [comment]
Fix pushed to dev. Thanks for reporting!

**Comment by ngosang** [comment]
Tested in dev. 👍
