### ISSUE TITLE
Display counters of ready subtitles

### ISSUE THREAD

**Issue by TMadMac** [morpheus65535/bazarr#62]
On "Series" display and on "Episodes" display, a counter of how many subtitles are available would be great. Think of those counters in Sonarr when you can see in a blink how many episodes left to download in a series or a season.

I really like to see:
- a column "Subtitles" on the "Series" display with counter like 12/14 showing 2 subtitles are missing.
- a counter for each season on the "Episodes" display with counter like 2/6 showing 2 subtitles are missing for the season.

It would help to find where are missing subtitles, without having to run the full Wanted list.

**Comment by morpheus65535** [comment]
I agree with your suggestion to add a column to the series view. On the episode view, I would prefer to add it to the right of "Season 1" (like in Sonarr). Is it ok for you? I'm going to take a look at this today or tomorrow.

**Comment by TMadMac** [comment]
You perfectly understand what I want.

**Comment by morpheus65535** [comment]
You can give it a try with the dev branch.
