### ISSUE TITLE
Update after installation makes Bazarr unusable (Windows 10)

### ISSUE THREAD

**Issue by ilker-aktuna** [morpheus65535/bazarr#620]
I have installed Bazarr on my Windows 10 PC today with the Windows installer.
After install, Bazarr updated itself from master branch. (I see it in the log file)

Then , after update and service start, when I try to access Bazarr for the first time on Web UI, I get the error:

> Error: 500 Internal Server Error
> Sorry, the requested URL 'http://192.168.254.20:6767/wizard' caused an error:
> 
> Internal Server Error
> Exception:
> AttributeError("'tuple' object has no attribute 'code2'",)
> 
> Traceback (most recent call last):
>   File "c:\program files (x86)\bazarr\bazarr\../libs/bottle.py", line 862, in _handle
>     return route.call(**args)
>   File "c:\program files (x86)\bazarr\bazarr\../libs/bottle.py", line 1740, in wrapper
>     rv = callback(*a, **ka)
>   File "c:\program files (x86)\bazarr\bazarr\main.py", line 139, in wrapper
>   File "c:\program files (x86)\bazarr\bazarr\main.py", line 237, in wizard
>     @route(base_url + 'save_wizard', method='POST')
>   File "c:\program files (x86)\bazarr\bazarr\../libs/bottle.py", line 3619, in template
>     return TEMPLATES[tplid].render(kwargs)
>   File "c:\program files (x86)\bazarr\bazarr\../libs/bottle.py", line 3409, in render
>     self.execute(stdout, env)
>   File "c:\program files (x86)\bazarr\bazarr\../libs/bottle.py", line 3396, in execute
>     eval(self.co, env)
>   File "c:\program files (x86)\bazarr\views\wizard.tpl", line 114, in <module>
>     % include('wizard_subtitles')
>   File "c:\program files (x86)\bazarr\bazarr\../libs/bottle.py", line 3386, in _include
>     return self.cache[_name].execute(env['_stdout'], env)
>   File "c:\program files (x86)\bazarr\bazarr\../libs/bottle.py", line 3396, in execute
>     eval(self.co, env)
>   File "c:\program files (x86)\bazarr\views\wizard_subtitles.tpl", line 108, in <module>
>     <option value="{{language.code2}}">{{language.name}}</option>
> AttributeError: 'tuple' object has no attribute 'code2'

**To Reproduce**
1. install fresh Bazarr on Windows from installer
2. let it update
3. open Web UI

**Expected behavior**
Access to Bazarr UI.

**Software (please complete the following information):**
 - Bazarr: installer from Bazarr site
 - OS: Windows 10

**Comment by morpheus65535** [comment]
Restart Bazarr service. It should be fine after that.

**Comment by danielxb-ar** [comment]
Similar problem: OperationalError('no such column: t1.forced',)

Traceback (most recent call last):
  File "c:\program files (x86)\bazarr\bazarr\../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "c:\program files (x86)\bazarr\bazarr\../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "c:\program files (x86)\bazarr\bazarr\main.py", line 134, in wrapper
    return func(*a, **ka)
  File "c:\program files (x86)\bazarr\bazarr\main.py", line 621, in series
    current_port=settings.general.port)
  File "c:\program files (x86)\bazarr\bazarr\../libs/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "c:\program files (x86)\bazarr\bazarr\../libs/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "c:\program files (x86)\bazarr\bazarr\../libs/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "c:\program files (x86)\bazarr\views\series.tpl", line 78, in <module>
    %for row in rows:
  File "c:\program files (x86)\bazarr\bazarr\../libs/peewee.py", line 6486, in __iter__
    self.execute()
  File "c:\program files (x86)\bazarr\bazarr\../libs/peewee.py", line 1785, in inner
    return method(self, database, *args, **kwargs)
  File "c:\program files (x86)\bazarr\bazarr\../libs/peewee.py", line 1856, in execute
    return self._execute(database)
  File "c:\program files (x86)\bazarr\bazarr\../libs/peewee.py", line 2027, in _execute
    cursor = database.execute(self)
  File "c:\program files (x86)\bazarr\bazarr\../libs/peewee.py", line 2962, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "c:\program files (x86)\bazarr\bazarr\../libs/playhouse\sqliteq.py", line 248, in execute_sql
    return self._execute(sql, params, commit=commit)
  File "c:\program files (x86)\bazarr\bazarr\../libs/peewee.py", line 2956, in execute_sql
    self.commit()
  File "c:\program files (x86)\bazarr\bazarr\../libs/peewee.py", line 2732, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "c:\program files (x86)\bazarr\bazarr\../libs/peewee.py", line 2949, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: no such column: t1.forced

**Comment by danielxb-ar** [comment]
Restarting the service not solve the problem

**Comment by morpheus65535** [comment]
@danielxb-ar please provide a copy of your bazarr.db.

**Comment by danielxb-ar** [comment]
Here is the bazarr.db

Sorry my english, español es mi lengua

The 1st error i got is the same that ilker-aktuna send, after uninstall and delete C:\programdata\bazarr and reinstall, the wizard works ok, 
[bazarr.zip](https://github.com/morpheus65535/bazarr/files/3705291/bazarr.zip)

**Comment by morpheus65535** [comment]
This database looks like an old one. Your missing most recent columns.

**Comment by ilker-aktuna** [comment]
I have the same issue. Restarting service does not solve the problem.
@morpheus65535 :
According to  your last response , the DB is old. But then how can we make it updated ?
I believe, the updater updates the code but does not update the DB. So how will it be updated ?

Btw, if I reinstall Bazarr from installer, and prevent the update, I can use it with old version.

**Comment by danielxb-ar** [comment]
In my case i delete the bazarr folder in programdata, so the bazarr.db is the one in the setup i download from the web

**Comment by morpheus65535** [comment]
Fix on it's way. Only in dev by now but I should release it to master tonight.

**Comment by danielxb-ar** [comment]
Thanks

**Comment by ilker-aktuna** [comment]
can you inform when it is on master ?
I want to use the master branch because that will be the one that's going to get updates, right ?

**Comment by morpheus65535** [comment]
Anyway if you use the windows installer it’s the only branch you have access (master).

**Comment by ilker-aktuna** [comment]
so is it fixed on installer now ?

**Comment by morpheus65535** [comment]
Nope. I’ll keep you informed once it’s done. It’s only 3pm in my time zone so it’s work time.

**Comment by mrmrmrmr1** [comment]
hi,

shall we have it soon ?

**Comment by morpheus65535** [comment]
0.8.2.4 have been released and include a fix for your issue.

**Comment by mrmrmrmr1** [comment]
new release is corrupted I believe.

After the update I see the following lines in log:
10/10/2019 14:48:39|INFO    |root                            |BAZARR Downloading update from: https://github.com/morpheus65535/bazarr/tarball/master|
10/10/2019 14:56:46|INFO    |root                            |BAZARR Extracting file: c:\program files\bazarr\bazarr\..\master-github|
10/10/2019 14:59:29|INFO    |root                            |BAZARR Deleting file: c:\program files\bazarr\bazarr\..\master-github|
10/10/2019 14:59:30|ERROR   |root                            |BAZARR Invalid update data, update failed: ['morpheus65535-bazarr-18900e4', 'morpheus65535-bazarr-474f936']|
10/10/2019 14:59:44|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:6767/|

**Comment by morpheus65535** [comment]
Restart the Bazarr service again and you shoul be fine.

**Comment by mrmrmrmr1** [comment]
tried it just now and same error log
it just cant update.

**Comment by morpheus65535** [comment]
Oh sorry I misread your log.

@halali any idea why we get this error?
`BAZARR Invalid update data, update failed: ['morpheus65535-bazarr-18900e4', 'morpheus65535-bazarr-474f936']`

**Comment by halali** [comment]
Bad git clone? Have no idea

**Comment by morpheus65535** [comment]
@halali He's running Windows installer so he's updating from releases tar, not with git.

**Comment by ilker-aktuna** [comment]
I have the same issue. any fix available ?

**Comment by morpheus65535** [comment]
Not yet.

**Comment by ilker-aktuna** [comment]
but I see v0.8.2.4 now on web UI.

v0.8.2.4
From newest to oldest:
- Fix for missing DB fields when upgrading from 0.7.5

**Comment by morpheus65535** [comment]
Is this your current version in Status tab (or bottom of each page)? Or you just see it in Releases tab?

**Comment by ilker-aktuna** [comment]
oh sorry it is just in releases. I had thought that if I see it in releases then I have the latest version.

on bottom of each page I see:
Bazarr Ver. 0.8.2.2

**Comment by morpheus65535** [comment]
Force an update in system/tasks and restart service

**Comment by ilker-aktuna** [comment]
why ? is it fixed ?

**Comment by morpheus65535** [comment]
@mrmrmrmr1 Where did you install Bazarr? Are you running it from Program Files?

**Comment by morpheus65535** [comment]
@ilker-aktuna I'm not sure what issue you are refering to so, first, the initial issue is solved (`t1.forced`). @mrmrmrmr1 have an other issue with `Invalid update data` error that is not fixed yet.

**Comment by ilker-aktuna** [comment]
I have the same issue with mrmrmmrmr1 .
it does not update because of invalid update.

**Comment by morpheus65535** [comment]
Where did you install Bazarr?

**Comment by ilker-aktuna** [comment]
from the win32 installer.

**Comment by morpheus65535** [comment]
Ok, I rephrase it again: what directory did you choose when you installed with Windows installer?

**Comment by ilker-aktuna** [comment]
I left it default (Program Files/Bazarr)

**Comment by morpheus65535** [comment]
Please uninstall, install it again but not in Program Files. Let say C:\Bazarr.

**Comment by danielxb-ar** [comment]
Installed in C:\bazar, same error. Is the one in the download section of www.bazarr.media ?

**Comment by morpheus65535** [comment]
Yes. I’m still working but I’ll test it later.

**Comment by danielxb-ar** [comment]
Ok, no problem

**Comment by morpheus65535** [comment]
Ok, it's working for me... Did the user user running your Bazarr service is member of administrators group? I'm running it from C:\Bazarr and either with SYSTEM user or with my own user having admins privileges it's working fine... :-/

**Comment by danielxb-ar** [comment]
In my case i'm member of administrators, but didn't work

**Comment by morpheus65535** [comment]
Did you try to empty your `update` directory? (../Bazarr/update)

**Comment by danielxb-ar** [comment]
I delete both bazarr folders (C:\Program Files (x86) and c:\programdata)
Are others folder i miss ?

**Comment by danielxb-ar** [comment]
Sorry, you say after the installation empty the update folder ?

**Comment by morpheus65535** [comment]
No you don't need to delete it after installation. I was wondering if there's some failed update stuck there...

**Comment by danielxb-ar** [comment]
some windows registry ? some folder i miss ?

**Comment by morpheus65535** [comment]
I've uninstalled everything, deleted both Bazarr directories, Bazarr service was removed... I'm totally clean.

I've downloaded the installer from Bazarr website and installed Bazarr to C:\Bazarr. I've changed nothing else. Bazarr log after this:
```
10/10/2019 21:10:42|INFO    |root                            |BAZARR Downloading update from: https://github.com/morpheus65535/bazarr/tarball/master|
10/10/2019 21:10:49|INFO    |root                            |BAZARR Extracting file: c:\bazarr\bazarr\..\master-github|
10/10/2019 21:10:59|INFO    |root                            |BAZARR Deleting file: c:\bazarr\bazarr\..\master-github|
10/10/2019 21:11:06|INFO    |root                            |BAZARR Restart failed, please restart Bazarr manualy|
10/10/2019 21:11:06|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:6767/|
```

Then, I restarted Bazarr service manually and got this in log:
```
10/10/2019 21:12:18|INFO    |root                            |BAZARR is up to date|
10/10/2019 21:12:22|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:6767/|
```

It's just working... :-/

(There's nothing in registry or anywhere else...)

**Comment by morpheus65535** [comment]
I'm updating my test machine to Windows 10 1903 just to be sure there's nothing preventing it to run with this version... I don't expect having different behaviour but just in case...

**Comment by danielxb-ar** [comment]
Wizard Started !

**Comment by morpheus65535** [comment]
What did you do?!?

**Comment by danielxb-ar** [comment]
The same i do 4 hours ago, but now it's working ! maybe a mistake i made

**Comment by morpheus65535** [comment]
Si it seems that running it outside of Program Files made the trick?

**Comment by danielxb-ar** [comment]
Yes, but in the previous attempt i use C:\bazarr, like now

**Comment by danielxb-ar** [comment]
Well, one more day of work and then enjoy your weekend, thanks for all

**Comment by ilker-aktuna** [comment]
ok. it works if I install it under C:\Bazarr
but why do we have to do this ? its default path was under Program Files , so that means it WAS working there previously. There's something in the installer or update file that makes this problem. Can't solve it ? 
I don't like to put anything under root folder of my drive.

**Comment by morpheus65535** [comment]
Program Files is a special directory for Windows with restricted access. Bazarr is unable to write update file to this directory. I shouldn't have set it as default and will change that.

**Comment by ilker-aktuna** [comment]
ok , that's understandable. But I have 2 questions;
1. I noticed Bazarr just this week and started with this installer. Since it is now version 8.2.4 , There must be a long history of updates and it should be working until now. Because before me, nobody else had reported this issue. Why do we have this issue just now , and why did not occur before ? If it was already there, you should have probably changed the default installation directory.
2. I also use Sonarr and Radarr. They are also in Program Files and can update themselves. Just like other Windows apps. Is Bazarr only app that can not reach the Program Files directory ? Btw, it is not a restricted directory. It is the default directory of Windows OS and all programs install there , and update themselves. This is like that since Windows 95 I believe.

**Comment by morpheus65535** [comment]
1. I don't know we didn't face this issue before. Probably because most user don't used the default path, are running with administrator privileges or because they aren't getting updated and they aren't even aware of the issue...

2. By default, Sonarr and Radarr install in %ProgramData%, not in %ProgramFiles% or %ProgramFiles(x86)%. Modifying content of Program Files directories require administrative elevated privileges since Windows 2000 (not sure about NT4). Sonarr and Radarr are developed in .NET and use native libraries to circumvent UAC. As Bazarr is developed in Python, we don't have the same facilities.

**Comment by ilker-aktuna** [comment]
anyway, I didn't change the path (Still installed under Program Files) and it suddenly started working. I hope it continues to work like that. Because it is good there :)

**Comment by morpheus65535** [comment]
As I haven't changed a thing on the Bazarr updater or installer since mid June, there's probably something that have changed on your side. Let's hope it continue to work as expected! :-)

**Comment by halali** [comment]
Can i close this ?
