### ISSUE TITLE
Bazarr don't identify some subs already in folder

### ISSUE THREAD

**Issue by felipevigo** [morpheus65535/bazarr#622]
After install Bazarr and intial configuration it founds some subs and miss others that are aleady in folder.
My library is structured like this: ShowName/Season/Filename. Subs are using the same name of video and I can take as example:

`Legends.of.Tomorrow.S04E10.The.Getaway.1080p.Amazon.WEB-DL.DD+5.1.H.264-QOQ` - it didn't found any subtitle file even sub are in folder with same filename.
```
09/10/2019 13:09:35|DEBUG   |root                            |BAZARR started subtitles indexing for this file: /mnt/secret/Series/DC's Legends of Tomorrow/Season 4/Legends.of.Tomorrow.S04E10.The.Getaway.1080p.Amazon.WEB-DL.DD+5.1.H.264-QOQ.mkv|
09/10/2019 13:09:35|DEBUG   |subliminal_patch.core           |external subs: scanning path /mnt/secret/Series/DC's Legends of Tomorrow/Season 4/Legends.of.Tomorrow.S04E10.The.Getaway.1080p.Amazon.WEB-DL.DD+5.1.H.264-QOQ.mkv|
09/10/2019 13:09:35|DEBUG   |subliminal_patch.core           |Found subtitles {}|
09/10/2019 13:09:35|DEBUG   |subliminal_patch.core           |external subs: found {}|
09/10/2019 13:09:35|DEBUG   |root                            |BAZARR storing those languages to DB: []|
09/10/2019 13:09:35|DEBUG   |root                            |BAZARR ended subtitles indexing for this file: /mnt/secret/Series/DC's Legends of Tomorrow/Season 4/Legends.of.Tomorrow.S04E10.The.Getaway.1080p.Amazon.WEB-DL.DD+5.1.H.264-QOQ.mkv|
```

`Legends.of.Tomorrow.S04E09.Lucha.de.Apuestas.1080p.NF.WEB-DL.DD+5.1.x264-QOQ` - it found external subs and stores in db as Brazilian Portuguese.
```
09/10/2019 13:09:34|DEBUG   |root                            |BAZARR started subtitles indexing for this file: /mnt/secret/Series/DC's Legends of Tomorrow/Season 4/Legends.of.Tomorrow.S04E09.Lucha.de.Apuestas.1080p.NF.WEB-DL.DD+5.1.x264-QOQ.mkv|
09/10/2019 13:09:34|DEBUG   |subliminal_patch.core           |external subs: scanning path /mnt/secret/Series/DC's Legends of Tomorrow/Season 4/Legends.of.Tomorrow.S04E09.Lucha.de.Apuestas.1080p.NF.WEB-DL.DD+5.1.x264-QOQ.mkv|
09/10/2019 13:09:35|DEBUG   |subliminal_patch.core           |Found subtitles {u'Legends.of.Tomorrow.S04E09.Lucha.de.Apuestas.1080p.NF.WEB-DL.DD+5.1.x264-QOQ.srt': <Language [pt-BR]>}|
09/10/2019 13:09:35|DEBUG   |subliminal_patch.core           |external subs: found {u'Legends.of.Tomorrow.S04E09.Lucha.de.Apuestas.1080p.NF.WEB-DL.DD+5.1.x264-QOQ.srt': <Language [pt-BR]>}|
09/10/2019 13:09:35|DEBUG   |root                            |BAZARR external subtitles detected: pt-BR|
09/10/2019 13:09:35|DEBUG   |root                            |BAZARR storing those languages to DB: [['pt-BR', u"/mnt/secret/Series/DC's Legends of Tomorrow/Season 4/Legends.of.Tomorrow.S04E09.Lucha.de.Apuestas.1080p.NF.WEB-DL.DD+5.1.x264-QOQ.srt"]]|
09/10/2019 13:09:35|DEBUG   |root                            |BAZARR ended subtitles indexing for this file: /mnt/secret/Series/DC's Legends of Tomorrow/Season 4/Legends.of.Tomorrow.S04E09.Lucha.de.Apuestas.1080p.NF.WEB-DL.DD+5.1.x264-QOQ.mkv|
```

Here's my logfile [bazarr.log](https://github.com/morpheus65535/bazarr/files/3708396/bazarr.log)

Right now I've enabled "Single Lnaguage" but I tried with this setting disabled and got the same.

Please let me know if you need anything else from me on this.
Thanks in advance

**Comment by morpheus65535** [comment]
I would like to see the listing of file in this directory and the permission for those files.

How are your running Bazarr? From source? Docker? Windows Installer?

**Comment by felipevigo** [comment]
[dirlist.txt](https://github.com/morpheus65535/bazarr/files/3709814/dirlist.txt)

I'm running on a distro called DietPi (Debian Buster based) from source. I also tried to run as root and regular user (dietpi user).
Python version is 2.7.16

**Comment by morpheus65535** [comment]
Bazarr is probably unable to detect language from text in file. Did you try to rename the subtitle file as `.pb.srt` instead of only `.srt`?

**Comment by felipevigo** [comment]
No, all my subs has no language code in filename. I'll try to change and return.
Thanks a lot !!!

**Comment by morpheus65535** [comment]
Even if you keep only one language, I highly suggest keeping the language name in subtitles filename as it make it easier to be recognized by different software in a consistent way.

**Comment by felipevigo** [comment]
Bingo !
I'll use your suggestion on language on filename.
Thanks a lot for this !!!!

**Comment by morpheus65535** [comment]
Always a pleasure, enjoy!
