### ISSUE TITLE
Request: Improve existing subtitles display (with many languages)

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#623]
I don't have a proposal. Low priority.
If you want a file with a ton of subtitles => `Stranger.Things.S03E07.iNTERNAL.1080p.WEB.X264-AMRAP`

![imagen](https://user-images.githubusercontent.com/10577978/66510745-e60c2500-ead5-11e9-9ed5-3c1aa2dbfdab.png)

**Software (please complete the following information):**
 - Bazarr: 0.8.2.2

**Comment by morpheus65535** [comment]
#525  :-)
