### ISSUE TITLE
Napisy24 not working

### ISSUE THREAD

**Issue by aspik** [morpheus65535/bazarr#626]
**Describe the bug**
Napisy24 shows AuthenticationError

**To Reproduce**
1. Go to '"Settings" ->"Subtitles" ->
2. Enable provider 'Napisy24.'
3. Enter username and password
4. Gives AuthenticationError in "System" ->"Providers" for napisy24

**Expected behavior**
napisy24 has status "Good"

**Software (please complete the following information):**
 - Bazarr: v0.8.2.4
 - Radarr version n/a
 - Sonarr version: 2.0.0.5338
 - OS: Docker image from Linuxserver.io

**Additional context**
tried also without username and password, same problem. Thanks for looking into it!

**Comment by morpheus65535** [comment]
I confirm that I have the same issue. @MoshiMoshi0 you can take a look at this one? Thanks!

**Comment by MoshiMoshi0** [comment]
The account has to have api privilages. Does your account have them?
You can only create an api account by messaging the admins.

**Comment by aspik** [comment]
Thanks for the response! I didn't know that my account needs to have special rights to make API calls. I'll get in contact with the admin and will try again when I have sufficient rights.

**Comment by MoshiMoshi0** [comment]
The default account should be working fine, ive been always using it.
I updated to v0.8.2.4 and it also works so I dont really know why it doesnt for you.

**Comment by morpheus65535** [comment]
@aspik You can read this information by hovering the exclamation mark icon alongside of the username field.

@MoshiMoshi0 Sorry for the disturbance, my account didn't have API access and I didn't try empty fields. My bad... :-/

**Comment by aspik** [comment]
ok, figured it out, my firewall was blocking the api url. After adding the url to the DNSBL Whitelist I can use the default account! Sorry for the trouble...

**Comment by PrzemekSkw** [comment]
Hello, I have the same situation. I have Bazarr v0.9.5 [master]. I try new account, empty credentials and still have error `AuthenticationError`. @aspik How to get API url?
regards.

**Comment by morpheus65535** [comment]
> Hello, I have the same situation. I have Bazarr v0.9.5 [master]. I try new account, empty credentials and still have error `AuthenticationError`. @aspik How to get API url?
> regards.

This provider require an account and you must contact the site admin to get the permission to call the API using this account.
