### ISSUE TITLE
Missing instructions on Wiki pages

### ISSUE THREAD

**Issue by lucianor** [morpheus65535/bazarr#628]
**Describe the bug**
On the page Installation Running from Source 
(https://github.com/morpheus65535/bazarr/wiki/Installation-Running-from-Source)

On the Linux section, there are dependencies for Ubuntu / Raspbian with packages libxml2-dev libxslt1-dev. If these are not installed, the pip install requirements won't work - will not compile the code.

On the page, systemd service file for Debian Ubuntu (https://github.com/morpheus65535/bazarr/wiki/systemd-service-file-for-Debian-Ubuntu), I suggest you add an instruction on how to actually enable the service with sudo systemctl enable bazarr

**To Reproduce**
1. Go to Wiki pages
2. Check missing instructions as described above

**Expected behavior**
Wiki pages should contain additional information as described above.

**Comment by morpheus65535** [comment]
Wiki updated, thanks for your help!
