### ISSUE TITLE
I can't download subtitles with the following providers

### ISSUE THREAD

**Issue by thonsouza** [morpheus65535/bazarr#629]
I am trying these two subtitle providers.
I get the following messages in the logs

`Using` legendastv again after 10 minutes, (disabled because: `AttributeError)`
`Using` opensubtitles again after 10 minutes, (disabled because: `Unauthorized)`

 Any suggestion?

**Comment by morpheus65535** [comment]
I am using both of them. Probably a configuration error on your side. I suggest you come to Discord Support channel and the support team will be there to help you.
