### ISSUE TITLE
Multiple Job "Sync episodes with Sonarr" raised an exception

### ISSUE THREAD

**Issue by tigre-bleu** [morpheus65535/bazarr#63]
I have a lot of these exceptions in the logs:

03/05/2018 00:00:45|ERROR|Job "Sync episodes with Sonarr (trigger: interval[0:05:00], next run at: 2018-05-03 00:05:39 CEST)" raised an exception|'Traceback (most recent call last):\n  File "/home/pi/.local/lib/python2.7/site-packages/apscheduler/executors/base.py", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File "/opt/bazarr/get_episodes.py", line 51, in sync_episodes\n    c.execute(\'\'\'INSERT INTO table_episodes(sonarrSeriesId, sonarrEpisodeId, title, path, season, episode, scene_name) VALUES (?, ?, ?, ?, ?, ?, ?)\'\'\', added_episode)\nIntegrityError: UNIQUE constraint failed: table_episodes.path'|

Can't really figure what's wrong...

**Comment by morpheus65535** [comment]
Nothing to worry about. Sonarr think that a multi-episode (ex.: S01E01-02) is to episode. When I call the Sonarr API, it return to Bazarr 2 episodes with the same path. I have a constraint on the database that refuse to have to episode with the same path. It's not a bug, it's not a feature, it's like a normal anomaly... ;-)

**Comment by tigre-bleu** [comment]
Ok, understood :-)
