### ISSUE TITLE
Language "eng" is not recognized.

### ISSUE THREAD

**Issue by Zixim** [morpheus65535/bazarr#630]
Raising this after a conversation in Discord : 
[link to discord convo](https://discordapp.com/channels/382221826564030464/540191312964485120/632532729426345997)

In short : an embedded subtitle track, with the `Language` field set to `eng`, will not be recognized as a valid English subtitle.

Maybe this is because Bazarr is only parsing `en` as being `english` ?

edit : Or is it because the subtitle track doesn't have a `Name` field ?

**Comment by morpheus65535** [comment]
Bazarr index `eng` just fine. The issue is maybe as it is in ASS format. It would be good if you can provide send me the file so I can run some test with it. PM me in Discord.

**Comment by morpheus65535** [comment]
Can you update from dev branch and test it? First run a scan for South Park to see if Bazarr can see all the available subtitles. Run a full disk scan if it fix your issue.

**Comment by Zixim** [comment]
But, i don't have South Park, @morpheus65535  ?

**Comment by morpheus65535** [comment]
lol sorry I mixed up two issues... :-)

Good I'll merge it to master in a couple of days.
