### ISSUE TITLE
Bazarr not detecting spanish sub as downloaded and shows it as still missing.

### ISSUE THREAD

**Issue by Panderine** [morpheus65535/bazarr#632]
**Describe the bug**
I have a srt file next to the video file by Bazarr stills tell me I don't have subs for the file.

**Software (please complete the following information):**
 - Bazarr: 0.8.2.4
- Docker image (hotio/bazarr:latest)

![image](https://user-images.githubusercontent.com/4042199/66784619-60abba80-eeb1-11e9-9a43-7e3b1f689dca.png)

![image](https://user-images.githubusercontent.com/4042199/66784646-74efb780-eeb1-11e9-8382-0a88f0ea78ff.png)

**Comment by Panderine** [comment]
In the logs I see it detects the sub as "ES"  and sometimes as "spanish". Please take a look at this "inconsistency" : 
Existing subtitles: ES
Missing subtitle: ES 

If it exist, why it says is missing?

![image](https://user-images.githubusercontent.com/4042199/66784784-d57ef480-eeb1-11e9-93f2-9aace95eec92.png)

**Comment by morpheus65535** [comment]
It's a known issue but I cannot reproduce it... a lot of people are impacted by this these days... :-/

**Comment by Panderine** [comment]
It started happening recently ... maybe it interprets "ES" and "SPANISH" as two different things? it only happens with Spanish language?

**Comment by morpheus65535** [comment]
No it seems to be happening with all kind of language.

**Comment by morpheus65535** [comment]
Should be fixed in 0.8.3 currently in dev branch. Reopen if it's still an issue.

**Comment by Panderine** [comment]
Ok I don't see the existing/missing inconsistency anymore. But i have tons of files where subtitles are missing but they are there. Bazarr even redownloads them successfully, but still flags them as missing.
