### ISSUE TITLE
404 Issue

### ISSUE THREAD

**Issue by MiranoV** [morpheus65535/bazarr#636]
Good day,

i have just changed a setting in bazarr: Base url. to: /bazarr

i then restarted bazarr and im getting this error: (see photo 1)

How do i revert this using a file browser? on windows server 2019 datacenter
![1](https://user-images.githubusercontent.com/38530348/66841890-9fea1200-ef6a-11e9-9794-ecf43953a4ca.PNG)

**Comment by MiranoV** [comment]
its trying to find bazarr on http://localhost:6767/bazarr/ while it is on http://localhost:6767/bazarr

**Comment by morpheus65535** [comment]
You can edit config.ini file.

**Comment by MiranoV** [comment]
where is the config.ini file located?

**Comment by morpheus65535** [comment]
As documented on the wiki, when you use the Windows Installer version, those kind of file are located in %programdata%\Bazarr
