### ISSUE TITLE
Existing downloaded subtitle file not found

### ISSUE THREAD

**Issue by vtzarkov** [morpheus65535/bazarr#637]
Existing downloaded subtitle file not found
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3732750/bazarr.log)
**Software (please complete the following information):**
 - Bazarr: 0.8.2.4
 - Radarr version 0.2.0.1358
 - Sonarr version 2.0.0.5338
 - OS: Linux docker container

**Comment by morpheus65535** [comment]
Try disabling single language mode.

**Comment by vtzarkov** [comment]
it is working with disabled "single language mode"

**Comment by morpheus65535** [comment]
Can you provide the subtitles file that was problematic?

**Comment by vtzarkov** [comment]
here it is, it is happening so far only with movies subs so far
[El.Camino.A.Breaking.Bad.Movie.2019.HDRip.XviD.AC3-EVO.txt](https://github.com/morpheus65535/bazarr/files/3734940/El.Camino.A.Breaking.Bad.Movie.2019.HDRip.XviD.AC3-EVO.txt)

**Comment by morpheus65535** [comment]
Can you reproduce this issue using 0.8.3 in dev branch? `linuxserver/bazarr:development`

**Comment by morpheus65535** [comment]
I've added a fix that could help you in 0.8.3 currently in dev branch: https://github.com/morpheus65535/bazarr/commit/8b3821b43bd75a03c9ebb9789965ba161b0907ed
