### ISSUE TITLE
"Error: 500 Internal Server Error" from http://localhost:6767/save_settings

### ISSUE THREAD

**Issue by Jacob-Lasky** [morpheus65535/bazarr#638]
**Describe the bug**
I get an Error: 500 Internal Server Error after clicking "Save Settings" and the settings do not save.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Save Settings', before OR after saving any changes
3. See error

**Expected behavior**
I expect the server to save and then return me to http://localhost:6767

**Screenshots**
[![Screenshot](https://gyazo.com/d565f98bc14f0da40e50578d46fea954/raw)](https://gyazo.com/d565f98bc14f0da40e50578d46fea954)

**Software:**
 - Bazarr (in docker): 0.8.2.4
 - Radarr (in docker, binhex radarr) version 0.2.0.1358
 - Sonarr (in docker, binhex sonarr) version 2.0.0.5338
 - OS: Linux-4.19.56-Unraid-x86_64-with

**Additional context**
Changing different settings and then clicking "Save Settings" doesn't fix the error. I've already restarted the docker and restarted bazarr, neither of which fixed the problem.

**Comment by morpheus65535** [comment]
Duplicate #102 and #435.
