### ISSUE TITLE
Job "Update series list from Sonarr" raised an exception

### ISSUE THREAD

**Issue by Freekers** [morpheus65535/bazarr#64]
Hi,

I'm running the latest available version of bazarr on Windows Server 2016 in combination with Python 2.7. Sonarr is running on a remote box (Synology NAS) and is behind a reverse proxy so that I can use my SSL certificate without too much hassle. I've configured Sonarr (i.e. remote IP/hostname, SSL port, checkmark for SSL and the API key) but upon running the 'Update series list from Sonarr' task, I get the following error:

`Traceback (most recent call last): File "C:\Python27\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job retval = job.func(*job.args, **job.kwargs) File "C:\git\bazarr\get_series.py", line 20, in update_series get_profile_list() File "C:\git\bazarr\get_series.py", line 84, in get_profile_list if type(profiles_json_v3.json()) != list: File "C:\Python27\lib\site-packages\requests\models.py", line 892, in json return complexjson.loads(self.text, **kwargs) File "C:\Python27\lib\json\__init__.py", line 339, in loads return _default_decoder.decode(s) File "C:\Python27\lib\json\decoder.py", line 364, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode raise ValueError("No JSON object could be decoded")ValueError: No JSON object could be decoded`

What could this be causing? The firewall is not blocking the port (on both machines) and the API of Sonarr is compatible with the reverse proxy as I'm also using the same setup in the nzb360 app on my Android phone.

Thank you very much!

Kind regards.

**Comment by morpheus65535** [comment]
Are you using a self signed SSL certificate or an authentic one?

**Comment by Freekers** [comment]
I am using an authentic one from Let's Encrypt.

However, could it be that what I am trying to achieve isn't possible at all? Since Sonarr is on a different machine, how will Bazarr 'push'/transfer the subtitles to that other machine? I didn't enter any credentials for the remote machine anyway, except for the API key of Sonarr.

Thanks!

**Comment by morpheus65535** [comment]
I don't know if Python Requests module trust the Let's Encrypt root certificate. Various issues talk about it not supporting it. The "fix" seems to not verify the SSL certificate when doing an HTTPS request. I'm not sure that's really a fix...

It's true that your setup won't work. Bazarr need to access the file system where the episode are. Why aren't you running the Docker version directly from your Synology NAS?

**Comment by Freekers** [comment]
Thanks for your reply.

My Synology model does not support docker. I guess I could run it from source, but I need to look into that. The issue is that my Synology doesn't have much RAM, so any extra overhead might be an issue in terms of resources.

What if I make a WEBDAV connection to my NAS, i.e. mount it as a local harddrive on the Windows server, would that work?

**Comment by morpheus65535** [comment]
I understand for your Syno.

If you are running Bazarr as a logged on user on Windows, you could just mount a drive to a samba, nfs or webdav share. Webdav is probably the slower method. Just make sure that the user have read/write access to your share. Sonarr and Bazarr accessing file trough different path, you'll need to configure path substitution in Bazarr( ie.: /volume/series --> z:\series ).

**Comment by morpheus65535** [comment]
Is your Windows machine able to reach Sonarr without going trough the reverse proxy?

**Comment by Freekers** [comment]
Okay, that would work for me.

Yes, when I don't use the reverse proxy, i.e. without SSL, Bazarr is able to reach Sonarr from the Winodws machine

**Comment by morpheus65535** [comment]
Good! Should I consider this issues resolved?

**Comment by Freekers** [comment]
This issue seems to be resolved, but I do have another issue now which is hard to solve as no logging is being made.

When I press the 'wrench' icon to edit a series to add languages to the series and press save, the loading icon shows up forever. I let it sit there for 2 hours but nothing happens. Logging is set to debug but is empty. How can I troubleshoot this?

Thank you

**Comment by morpheus65535** [comment]
Is your path substitution working? On the Series page, do you have a checkmark in front of the path for each series?

**Comment by Freekers** [comment]
Yes, I have a checkmark in front of the path for each series: https://i.imgur.com/bjakRNg.png

**Comment by morpheus65535** [comment]
The initial issue is resolved. We'll continue on Discord for the second one.
