### ISSUE TITLE
How to open a second instance of Bazarr on Windows 10?

### ISSUE THREAD

**Issue by gelsas** [morpheus65535/bazarr#640]
How to open a second instance of Bazarr on Windows 10?

(Just install it a second time to a different location ? Or will there be a problem because of same service name ?)

**Comment by morpheus65535** [comment]
You need to install once, change listening port, use nssm.exe (available in Bazarr install directory) to rename service and change config directory path parameter. After that, you can install another instance with default values.

**Comment by gelsas** [comment]
Perfect. Thank you. 

Where can I find the bazarr.db file ?

**Comment by gelsas** [comment]
Also where exactly can I change the config directory path parameter?

**Comment by halali** [comment]
In nssm service editor
