### ISSUE TITLE
pip: command not found (FreeNAS iocage)

### ISSUE THREAD

**Issue by sindreruud** [morpheus65535/bazarr#642]
Hi,

following the install tutorial for FreeBSD from the wiki https://github.com/morpheus65535/bazarr/wiki/Installation-FreeBSD. 

I am installing inside an iocage jail on a FreeNAS 11.2 U6. Coming to the step where it calls for:
`# pip install -r requirements.txt`
It just returns:
`pip: Command not found`

The solution is to make a symbolic link for package pip-2.7 package, like so:
```
# which pip-2.7
/usr/local/bin/pip-2.7
# ln -s /usr/local/bin/pip-2.7 /usr/local/bin/pip
```
 
This should be added to the wiki. This will however spit out a warning when using pip:
`DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.`

**Comment by morpheus65535** [comment]
I've added a mention in the wiki. Thanks!
