### ISSUE TITLE
Cannot parse releases caching file

### ISSUE THREAD

**Issue by kimme1024** [morpheus65535/bazarr#644]
**Describe the bug**
I have some leftover subtitles in my wantedlist remaining to be downloaded. Can't do it manually either. It finds the subtitle but doesn't download it as it did with the rest.
Since the last import the logs show following error:

BAZARR cannot parse releases caching file: /Users/XBMC/Applications/bazarr/data/config/releases.txt

**To Reproduce**
Happens on every refresh, automatic and manual

**Expected behavior**
It should download the missing subtitles in the wantedlist, obviously :)

**Software (please complete the following information):**
 - Bazarr: 0.8.2.4
 - Radarr version 0.2.0.1358
 - Sonarr version 2.0.0.5338
 - OS: OSX

**Complete error output**
BAZARR cannot parse releases caching file: /Users/XBMC/Applications/bazarr/data/config/releases.txt
Exception
Traceback (most recent call last):
 File "bazarr/main.py", line 1994, in system
  with open(os.path.join(args.config_dir, \config\, \releases.txt\), \r\) as f:
IOError: [Errno 2] No such file or directory: \/Users/XBMC/Applications/bazarr/data/config/releases.txt\

**Comment by morpheus65535** [comment]
@halali Is it something you ever seen?

**Comment by halali** [comment]
Is that path exist? /Users/XBMC/Applications/bazarr/data/config/releases.txt\

**Comment by morpheus65535** [comment]
No update. I close it. Reopen if you are still experiencing this issue.

**Comment by kimme1024** [comment]
Hi, 

Sorry for the late reply. I lost sight of this topic.
I still have the issue.
I checked the file and it doesn't exist indeed.

Do I just have to create the file there and does Bazarr fill it in or what should I do with this?

Thanks in advance!

**Comment by morpheus65535** [comment]
Create an empty text file with this name. It should have been created automatically of course. I’ll look into it later.

**Comment by kimme1024** [comment]
I just created it and it was immediately filled by bazarr.
however the error still remains.

**Comment by morpheus65535** [comment]
Permissions?

**Comment by kimme1024** [comment]
I gave full (777) permission to the file but the error remains

**Comment by morpheus65535** [comment]
This is definitely related to your setup. I can delete the releases.txt file and Bazarr recreate it from scratch at startup.
