### ISSUE TITLE
Is there a way to prioritize recently downloaded episodes/movies?

### ISSUE THREAD

**Issue by cdemi** [morpheus65535/bazarr#645]
Since I have just setup Bazaar, it has been downloading missing subtitles from my library, which is fine. However, is it possible to have it download subtitles for the recently downloaded stuff immediately rather than waiting for the whole queue to finish?

Right now I have to force a search on the episode to skip the queue

**Comment by morpheus65535** [comment]
Every 3 hours, Bazarr start to search for missing subtitles (series first then movies) from the latest added to Bazarr to the oldest. Automatic search should be searching your newest episode first.
