### ISSUE TITLE
ValueError: Timezone offset does not match system offset:

### ISSUE THREAD

**Issue by TheOzzyman** [morpheus65535/bazarr#647]
I'm starting using Bazarr in Windows without Docker (I've used before in Docker and in Linux).
When I try to start the bazarr.py, I've got the problem below:
C:\Bazarr>python bazarr.py
Bazarr starting...
Traceback (most recent call last):
  File "bazarr\main.py", line 24, in <module>
    from update_db import *
  File "C:\Bazarr\bazarr\update_db.py", line 7, in <module>
    from scheduler import execute_now
  File "C:\Bazarr\bazarr\scheduler.py", line 65, in <module>
    if str(get_localzone()) == "local":
  File "C:\Bazarr\bazarr\../libs/tzlocal\win32.py", line 95, in get_localzone
    utils.assert_tz_offset(_cache_tz)
  File "C:\Bazarr\bazarr\../libs/tzlocal\utils.py", line 38, in assert_tz_offset
    raise ValueError(msg)
ValueError: Timezone offset does not match system offset: -7200 != -10800. Please, check your config files.

I already searched google for that and I've found this same issue here with another user, but I wasn't able to find some sollution.

Remember, I'm using Windows 10 Pro (without Docker installed at all) and Python 2.7.13 (64-bit).

Thanks.

**Comment by jethromorais** [comment]
This problem was fixed on #646 , change your branch to dev and update.
This fixed for me ;-)

**Comment by morpheus65535** [comment]
Windows Installer doesn't give him the possibility to change branch. He'll have to wait for me to merge this to master branch.

**Comment by TheOzzyman** [comment]
There is something can I do here to workaround ?

**Comment by jethromorais** [comment]
There's a temporary fix on #646

Obrigado,
Jethro Morais
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by morpheus65535** [comment]
Change your timezone to something else than Brazil.

**Comment by TheOzzyman** [comment]
I've changed my timezone to GMT-2 and it worked.
It's not a sollution, but a workaround.
