### ISSUE TITLE
OpenSubtitles LanguageConvertError

### ISSUE THREAD

**Issue by vavdagic** [morpheus65535/bazarr#648]
**Describe the bug**
OpenSubtitles throws LanguageConvertError exception when ever used. No exception info.

Throttling opensubtitles for 10 minutes, until 19/10/26 20:03, because of: LanguageConvertError. Exception info: ''

**Software (please complete the following information):**
 - Bazarr: v0.8.2.4
 - Radarr version 0.2.0.1358
 - Sonarr version 2.0.0.5338
 - OS: Ubuntu 18

**Comment by vavdagic** [comment]
Issue was due to Serbo-Croatioan language. Maybe you should remove it from the list.

**Comment by morpheus65535** [comment]
It’s just that opensubtitles doesn’t support this language. It doesn’t mean I have to remove it as other providers may support it.

**Comment by nikolicjakov** [comment]
I dont have Serbo-Croatian language added and i am still getting this error message all the time. I have Croatian, Bosnian and Serbian but no Serbo-Croatian.

@morpheus65535 do you have any idea why this is popping up? Btw i have opensubtitles VIP account.

**Comment by morpheus65535** [comment]
@nikolicjakov open new issue and provide debug log.
