### ISSUE TITLE
Bazarr doesn't get subtitles from Legendas.TV

### ISSUE THREAD

**Issue by Zamana** [morpheus65535/bazarr#649]
**Describe the bug**
I have 6 subtitle providers configured, but it seems that Bazarr only downloads from Opensubtitles.

As I try to download the exact releases advertised by the Legendas.TV site, would be nice if Bazarr grab the subtitles from Legendas.TV, but it doesn't.

I tried to disable Opensubtitles, but then no subtitles were downloaded.

Is this a bug (in Bazarr or in Legendas.TV api/service) or is there a way to set preferences regarding subtitles providers?

Thanks.
Regards.

**Software (please complete the following information):**
 - Bazarr: v 0.8.1
 - Radarr version: v 0.2.0.0.1344
 - Sonarr version: v 0.2.0.0.5338
 - OS: LXC under Proxmox 6 (Debian 10 based)

**Comment by morpheus65535** [comment]
I've just tested with v0.8.2 and it works fine. I suggest you wait for v0.8.3 as we are having DB issue with v0.8.2.

**Comment by 1RF17** [comment]
Same problem here. It's part of Providers, this message occurs:

![erro](https://user-images.githubusercontent.com/12552870/67891272-00fc1300-fb31-11e9-89d9-00328adfb628.PNG)

**Comment by morpheus65535** [comment]
Check your username/password. It's still work for me right now. I've just downloaded a subs from legendas a minute ago.

**Comment by 1RF17** [comment]
Username/password is correct.

In log, show me this: 

`31/10/2019 09:18:07|INFO    |root                            |Throttling legendastv for 10 minutes, until 19/10/31 09:28, because of: AttributeError. Exception info: "'NoneType' object has no attribute 'rfind'"|`

I'am using Bazarr Version 0.8.2.4 and Python Version: 2.7.16

**Comment by morpheus65535** [comment]
Could you try dev version of Bazarr (0.8.3)?
