### ISSUE TITLE
armhf docker image?

### ISSUE THREAD

**Issue by faulander** [morpheus65535/bazarr#65]
Hi,
it would be awesome to get an armhf docker image for us raspberry guys! :)

Cheers,
   Harald

**Comment by faulander** [comment]
will try the next few days

**Comment by morpheus65535** [comment]
docker logs for the container?

**Comment by morpheus65535** [comment]
Ok first, show aren't detected, they are synced from Sonarr (metadata). Second, path substitution is useful only if Sonarr and Bazarr see episode trough a different path. If both of them see episode trough /tv/11.22.63/Season 01/s01e01.mkv (for example), you don't need it.

**Comment by faulander** [comment]
ok, now i restarted the container and it recognizes the files - they are checkmarked.
And now it doesn't scan the HD like the last time when i installed it from source. 

Your armhf docker image works btw - it was my system that prevented it from working.

**Comment by morpheus65535** [comment]
Ok, I've noticed it last week. Path substitution require restart even if it shouldn't. I'll look into it.

Thanks for the feedback on docker image. I'll close the issue. Feel free to open another one if you run into problems again.
