### ISSUE TITLE
7z archived subs

### ISSUE THREAD

**Issue by vanko95** [morpheus65535/bazarr#650]
I have a problem when bazarr trying to download subs archived in 7z format. Could you add 7z support in bazarr?

**Comment by morpheus65535** [comment]
Which provider?

**Comment by morpheus65535** [comment]
@dimitrov-adrian you have the same issue?

**Comment by vanko95** [comment]
Error in log is 
Throttling subsunacs for 10 minutes, until 19/10/31 09:41, because of: ValueError. Exception info: 'Not a valid archive'

**Comment by dimitrov-adrian** [comment]
Well, this is not exactly an error but more like a warning, since the bazarr does not supports 7z archives

https://github.com/morpheus65535/bazarr/blob/master/libs/subliminal_patch/providers/subsunacs.py#L169

**Comment by morpheus65535** [comment]
Would it be possible to achieve it using https://github.com/dsoprea/PyEasyArchive?

**Comment by dimitrov-adrian** [comment]
Yes of course, but this library seems to be replacement also to zip and rar, so it might require a lot of code rewrite to migrate RarFile() and ZipFile(), or at least to add aliases.

If other providers will require 7z in future, then definitely it worth.

**Comment by morpheus65535** [comment]
Ok, thanks for your input. I'll see if I want to go there in the future.
