### ISSUE TITLE
bazarr unable to detect Sonarr v3

### ISSUE THREAD

**Issue by agneevX** [morpheus65535/bazarr#654]
**Describe the bug**
I was using Sonarr v2.* (nzbdrone), upgrading to Sonarr v3 rendered bazarr unusable until a re-clone of the repo. 

**To Reproduce**
1. [Upgrade Nzbdrone to Sonarr V3](https://sonarr.tv/#downloads-v3-linux-ubuntu)
2. Execute `python /opt/bazarr/bazarr.py`
3. See error (output below)

**Expected behavior**
Bazarr should launch and warn of failed connection to sonarr.

**Terminal Output**
```
agneev@server1:/opt/bazarr$ python bazarr.py
Bazarr starting...
Traceback (most recent call last):
  File "bazarr/main.py", line 46, in <module>
    from get_episodes import *
  File "/opt/bazarr/bazarr/get_episodes.py", line 13, in <module>
    from get_subtitle import episode_download_subtitles
  File "/opt/bazarr/bazarr/get_subtitle.py", line 39, in <module>
    from analytics import track_event
  File "/opt/bazarr/bazarr/analytics.py", line 16, in <module>
    sonarr_version = get_sonarr_version()
  File "/opt/bazarr/bazarr/utils.py", line 108, in get_sonarr_version
    logging.DEBUG('BAZARR cannot get Sonarr version')
TypeError: 'int' object is not callable
^CTraceback (most recent call last):
  File "bazarr.py", line 83, in <module>
    time.sleep(1)
KeyboardInterrupt
```

**Software:**
 - Bazarr: v0.8.24
 - Sonarr version: 3.0.3.652 [phantom-develop]
 - OS: Ubuntu 18.04, 64-bit

**Comment by morpheus65535** [comment]
Already fixed in dev branch: https://github.com/morpheus65535/bazarr/commit/5ec8f20ccfde31257d5015318648ff9f93f60b52
