### ISSUE TITLE
Existing downloaded subtitle file not found or updated in bazarr

### ISSUE THREAD

**Issue by shudack** [morpheus65535/bazarr#655]
Existing downloaded subtitle file not found
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3800980/bazarr.log)

Settings of Subtitles:
![image](https://user-images.githubusercontent.com/17851196/68077392-f94f9f00-fdba-11e9-88e0-270a29fedf13.png)
![image](https://user-images.githubusercontent.com/17851196/68077399-0bc9d880-fdbb-11e9-9177-06cc7c598193.png)

In this case, I have all subtitles downloaded by Bazarr, and don't updated with completes status:
![image](https://user-images.githubusercontent.com/17851196/68077408-33b93c00-fdbb-11e9-9078-5b462ac3e92b.png)

Software (please complete the following information):

Bazarr: 0.8.3 (Branch development)
Sonarr version 2.0.0.5338
Radarr version 0.2.0.1358
OS: Linux-4.9.196-63-aarch64-with-Ubuntu-18.04-bionic

**Comment by morpheus65535** [comment]
`Single language` is probably the worst idea I ever had... please try to disable it and have your subtitles include `.pt.srt`.

**Comment by shudack** [comment]
Don't work in single language, I tried but it's worst. Can you revert all and back before the single language, maybe it's better in my opinion

**Comment by morpheus65535** [comment]
Impossible. Single language is there since rhe beginning of Bazarr. I’ll see if I can fix it.

**Comment by shudack** [comment]
Ok, If you need help, I can help you in this thread.

**Comment by morpheus65535** [comment]
Could you try my latest fix in dev branch?

**Comment by shudack** [comment]
Sure, I attach here the log.

[bazarr.log](https://github.com/morpheus65535/bazarr/files/3803747/bazarr.log)

**Comment by morpheus65535** [comment]
I just made an additional fix. I also suggest, as the log say, that you install ffmpeg.

**Comment by shudack** [comment]
Issue is fixed. No errors in log. But now, don't find any subtitules.

[bazarr.log](https://github.com/morpheus65535/bazarr/files/3804361/bazarr.log)

![image](https://user-images.githubusercontent.com/17851196/68127553-05984100-ff0e-11e9-8afb-97c6621b59ea.png)

**Comment by shudack** [comment]
I attach log detailed for "Update all Episode Subtitles from disk"

[bazarr.log](https://github.com/morpheus65535/bazarr/files/3804800/bazarr.log)

**Comment by morpheus65535** [comment]
You don't have any desired subtitles languages for your series...

**Comment by shudack** [comment]
Yes, I have.

![image](https://user-images.githubusercontent.com/17851196/68138448-7cd6d080-ff20-11e9-82e0-271cfde80e10.png)

**Comment by shudack** [comment]
Last log have error in:
|ERROR   |subliminal_patch.core           |Cannot parse language code u'h264-BAMBOOZLE'|
|ERROR   |subliminal_patch.core           |Cannot parse language code u'x264-NTb'|
|ERROR   |subliminal_patch.core           |Cannot parse language code u'x264-lucidtv'|
....

[bazarr.log](https://github.com/morpheus65535/bazarr/files/3805014/bazarr.log)

**Comment by morpheus65535** [comment]
You have default language enabled but in your previous screenshot the is nothing in the "Subtitle lanaguage(s)" column.

**Comment by morpheus65535** [comment]
Default tooltip: `Apply only to series added to Bazarr after enabling this option.`

**Comment by shudack** [comment]
Back to the initial problem, I have the subtitles downloaded to disk by bazarr, but in the interface doesn't appear as downloaded.

![image](https://user-images.githubusercontent.com/17851196/68206553-e90b1000-ffc4-11e9-906e-858d4a5112cd.png)

**Comment by morpheus65535** [comment]
Did you disable `single language`? Does your subtitles file include the language code? Could be a path mapping issue.

**Comment by shudack** [comment]
I don't disable single language. Is need the subtitles file include the language code (pt)? :|

**Comment by morpheus65535** [comment]
You understand that if you don’t include the language code in filename, the only way we have to determine that language is to guess it from the text and it can fail. Most users don’t use single language and let Bazarr add language code in subtitles filename.

**Comment by shudack** [comment]
No, If I choose Portuguese, it will download the Portuguese subtitle, because it knows it is the selected parameter, so when you list the subtitles you know that I already included the subtitle. The logic that has been implemented does not seem to me to be the correct one. But if your system looks like this, I use it that way.

**Comment by shudack** [comment]
With single language off, it works.. I will keep this logic. Thank you
