### ISSUE TITLE
[Question] Is there a way to set Hearing Impared to Yes, but if not found download normal subs?

### ISSUE THREAD

**Issue by cdemi** [morpheus65535/bazarr#657]
I would prefer Hearing Impaired subtitles, but sometimes, some releases only have non-hearing impaired subtitles. In that case, I would prefer those subtitles instead of none.

Is there a way to achieve it?

**Comment by morpheus65535** [comment]
Actually, no. You can make a feature request for this and we’ll look into it.

**Comment by cdemi** [comment]
Thanks! Here is a link just in case anyone looks up this thread in the future: https://bazarr.featureupvote.com/suggestions/63594/fallback-to-nonhearing-impaired-subtitles-if-no-hearing-impaired-subtitles-are-f
