### ISSUE TITLE
jobs sonarr and radarr not working

### ISSUE THREAD

**Issue by MoiZie** [morpheus65535/bazarr#658]
**Describe the bug**
Just found and installed from source on ubuntu

**To Reproduce**
1. update sonarr and / or radarr

**Expected behavior**
it works

**Software (please complete the following information):**
Bazarr Version:
0.8.2.4
Sonarr Version:
0.2.0.1358
Radarr Version:
2.0.0.5338
Operating System:
Linux-5.3.0-19-generic-x86_64-with-Ubuntu-19.10-eoan
Python Version:
2.7.17rc1

**Additional context**
debug log:
sonarr failure:
Details
Message
Job "Update Series list from Sonarr (trigger: interval[0:01:00], next run at: 2019-11-04 18:42:55 CET)" raised an exception
Exception
Traceback (most recent call last): File "/home/moizie/opt/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job retval = job.func(*job.args, **job.kwargs) File "/home/moizie/opt/bazarr/bazarr/get_series.py", line 29, in update_series audio_profiles = get_profile_list() File "/home/moizie/opt/bazarr/bazarr/get_series.py", line 184, in get_profile_list profiles_json = requests.get(url_sonarr_api_series, timeout=60, verify=False)UnboundLocalError: local variable url_sonarr_api_series referenced before assignment

Radarr failure:
Details
Message
Job "Update Movie list from Radarr (trigger: interval[0:05:00], next run at: 2019-11-04 18:49:25 CET)" raised an exception
Exception
Traceback (most recent call last): File "/home/moizie/opt/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job retval = job.func(*job.args, **job.kwargs) File "/home/moizie/opt/bazarr/bazarr/get_movies.py", line 37, in update_movies audio_profiles = get_profile_list() File "/home/moizie/opt/bazarr/bazarr/get_movies.py", line 307, in get_profile_list profiles_list.append([profile[id], profile[language][name].capitalize()])TypeError: string indices must be integers

**Comment by MoiZie** [comment]
Both sonarr and radarr run locally and are thus added as 127.0.0.1 with correct ports, 'test connection' works.

**Comment by morpheus65535** [comment]
Sonarr API is returning garbage and Bazarr cannot confirm it's version.

Radarr v2 API is subject to changes. That's probably the issue here.

**Comment by MoiZie** [comment]
So... Bazarr doesn't work at all? Is this a bug at my side? Is Bazarr outdated? What is the problem?

**Comment by morpheus65535** [comment]
You can update to 0.8.3 but it works for a lot of people: over 150 000 subtitles downloaded yesterday and more than 730 000 search. I guess the issue is on your side. :-/

**Comment by MoiZie** [comment]
Obviously, but where do I start? The debug log just has the error shown above; debug logging in sonarr / radarr doesn't show anything regarding an incoming API connection. Everything is running locally in an ubuntu virtual machine for testing. Is Ubuntu Eaon not yet supported?

**Comment by MoiZie** [comment]
I updated to Bazarr 0.8.3 (well, the program did that just by itself I guess)

Bazarr Version:
0.8.3
Sonarr Version:
Radarr Version:
2.0.0.5338
Operating System:
Linux-5.3.0-19-generic-x86_64-with-Ubuntu-19.10-eoan
Python Version:
2.7.17rc1

Now Sonarr doesn't show any version information at all.

**Comment by MoiZie** [comment]
BAZARR cannot get Radarr version | a few seconds ago
-- | --
  | http://127.***.***.***:8989 "GET /api/system/status?apikey=********33 HTTP/1.1" 401 None | a few seconds ago
  | DNS: Falling back to default DNS or IP on 127.***.***.*** | a few seconds ago
  | Starting new HTTP connection (1): 127.***.***.***:8989 | a few seconds ago
  | http://192.***.***.***:8989 "GET /api/system/status?apikey=********f9 HTTP/1.1" 200 None | a few seconds ago



the bottom one is my sonarr; that works right now. The upper part (notice the different api key is correctly entered) provides a 401 error using 127.0.0.1 as the address.

**Comment by morpheus65535** [comment]
So the issue happen when you try to connect to Sonarr using 127.0.0.1? Strange...

**Comment by MoiZie** [comment]
Wait, that's strange... It tries to use the correct sonarr port (8989) and api key (f9). and the next entry uses the radarr api key (33) with the sonarr port (8989), but with the radarr ip address (127....)

**Comment by MoiZie** [comment]
[sonarr]
ssl = False
apikey = f9
full_update = Daily
full_update_day = 6
ip = 192.168.x.x
full_update_hour = 4
only_monitored = False
port = 8989
base_url =

[radarr]
ssl = False
apikey = 33
full_update = Daily
full_update_day = 6
ip = 192.168.x.x
full_update_hour = 5
only_monitored = False
port = 7878
base_url =

**Comment by morpheus65535** [comment]
Ok, so: 

First, Bazarr doesn't seems to be supporting connection to Sonarr and Radar using loop back address. Maybe some security software on your computer because I've just teste it and it works for me on vanilla Windows 10.

Second, there's some mixup in variable when there's an issue contacting either Sonarr or Radarr. I'll check it.

**Comment by morpheus65535** [comment]
I've just push a fix to dev branch for second issue.
