### ISSUE TITLE
bazarr doesn't recognize existing subtitles

### ISSUE THREAD

**Issue by faulander** [morpheus65535/bazarr#66]
I have files in the format:
The.100.S05E01.Eden.HDTV-720p.Proper.CRAVERS.mkv
Subtitle is:
The.100.S05E01.Eden.HDTV-720p.Proper.CRAVERS.en.srt

i tried with single language and multi language (with only english as parameter) - still doesn't recognize a single existing subtitle out of ~1000.

**Comment by morpheus65535** [comment]
How long since you started Bazarr from scratch? There'S 2 choices here: your path substitution isn't set right (do you have a checkmark in front of your series path on the main page?) or Bazarr is still indexing subtitles from disk.

I've got the same release and, BTW, there is internal subtitles in this mkv. Bazarr will index it and you can see it in the UI.

**Comment by faulander** [comment]
Hi, 
thanks for the fast answer.
Yes, i have the checkmark for the shows and the scan is maybe 30 minutes ago.

The 100 was just an example - it's with all the shows the same ... can i check somewhere if it's still indexing?

**Comment by faulander** [comment]
![2018-05-05 13_08_30-bazarr](https://user-images.githubusercontent.com/38588197/39662650-7f6c2f86-5065-11e8-9e62-964f508e191e.png)
attached you see a screenshot. I manually indexed the first two shows and they are correct. The rest stays unindexed.

**Comment by faulander** [comment]
If i scan for "The Americans (2013)" manually, i get this error: 
![2018-05-05 13_11_36-error_ 500 internal server error](https://user-images.githubusercontent.com/38588197/39662682-f3cb4628-5065-11e8-85b7-a63cfa0fc588.png)
Does it have something to do, that it's one of the shows, were titel and path are different?
EDIT: No, tried with "The Flash" (where it's the same and it worked).
EDIT: UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 37: ordinal not in range(128)
is the error shell shows last.

**Comment by faulander** [comment]
and here's the full error for "Chicago Med":
root@DietPi:~/scripts/bazarr# Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "bazarr.py", line 289, in scan_disk
    series_scan_subtitles(no)
  File "/root/scripts/bazarr/list_subtitles.py", line 118, in series_scan_subtitles
    store_subtitles(path_replace(episode[0]))
  File "/root/scripts/bazarr/list_subtitles.py", line 35, in store_subtitles
    subtitles = core.search_external_subtitles(file)
  File "libs/subliminal/core.py", line 391, in search_external_subtitles
    if not p.startswith(fileroot) or not p.lower().endswith(SUBTITLE_EXTENSIONS):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 27: ordinal not in range(128)

**Comment by morpheus65535** [comment]
Is your system character encoding in UTF8?

**Comment by faulander** [comment]
https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte

**Comment by morpheus65535** [comment]
Are you running from source code or from the docker container?

**Comment by morpheus65535** [comment]
In a new python file, could you get me the result from this:

	import sys
	print sys.getdefaultencoding()

**Comment by faulander** [comment]
output is 'ascii'

**Comment by faulander** [comment]
i've changed the python default encoding to utf-8 and now i get:
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 40

seems i have files with strange filenames. I did setup a new NAS and copied over the files from the old one. It's still ext filesystem, but something must've happened.

**Comment by morpheus65535** [comment]
I've added setdefaultencoding('utf8') and tested it. Everything working fine for me. You probably got something strange on your system. File system encoding is something to look at.

**Comment by faulander** [comment]
yes, i found a workaround.
- using detox to clean up filenames. 
- re-index with sonarr
- re-indext with bazarr

then it works. You should maybe leave out unreadable files in your scan procedure though.

**Comment by morpheus65535** [comment]
I'll look into that into next weeks.
