### ISSUE TITLE
Web UI unresponsive after an update

### ISSUE THREAD

**Issue by A-Alhashem** [morpheus65535/bazarr#661]
**Describe the bug**
This is on dev branch.

After every update received, bazarr tries to restart, and when I try to connect to bazarr either locally or using nginx reverse proxy (domain name) I am greeted with my login screen, once I put my username and pass the web UI would go into indefinite duration of trying to open the next page.

If I do not even have a login screen (where its expected to go straight into the UI screen) it feels like its in a loading loop. Nothing appears.

Checking the logs, bazarr is still working but the UI stops opening with no errors. However, after every update the only logs I can see that still continues to produce is this:

```05/11/2019 17:04:33|WARNING |apscheduler.scheduler           |Execution of job "Update Movie list from Radarr (trigger: interval[0:05:00], next run at: 2019-11-05 17:04:33 +03)" skipped: maximum number of running instances reached (1)|```

```05/11/2019 17:05:33|WARNING |apscheduler.scheduler           |Execution of job "Update Series list from Sonarr (trigger: interval[0:01:00], next run at: 2019-11-05 17:05:33 +03)" skipped: maximum number of running instances reached (1)|```

and just keeps repeating those lines.

using windows 10 here, I can restart bazarr by going into services.msc and stopping/starting bazarr and it works successfully. Either that or just restarting my server PC solves the problem until the next update.

**To Reproduce**
1. bazarr tries to update to latest dev branch version
2. updates successfully, bazarr restarts.
3. the Web UI stops responding (or just goes into infinite loading loop but nothing shows)

**Expected behavior**
bazarr should re-load the Web UI after the update as usual.

**Software (please complete the following information):**
 - Radarr version [0.2.0.1358]
 - Sonarr version [2.0.0.5337]
 - OS: [Windows 10]

**Additional context**
i've installed bazarr by using github, not windows installer.
Not using docker or VM.
Intel NUC with an install of windows 10 Pro edition.

**Comment by morpheus65535** [comment]
Should be fixed for update that will happens **after** 0.8.3 now in master.
