### ISSUE TITLE
issue #632 still exists in v0.8.3.1

### ISSUE THREAD

**Issue by Panderine** [morpheus65535/bazarr#663]
I don't see the existing/missing inconsistency anymore. But i have tons of video files where subtitles are detected as missing but they are there. Bazarr even redownloads them successfully, but still flags them as missing.

**Comment by morpheus65535** [comment]
`Single language` is enabled?

**Comment by Panderine** [comment]
yes. I'll try without it as per issue #637

**Comment by Panderine** [comment]
The strange thing is that with single language on, it only failed with some. So some subtitles where correctly detected.

**Comment by morpheus65535** [comment]
When a subtitles filename doesn't include a language code, we have to rely on external Python library to guess the language of the text inside the file. It doesn't always work well and it doesn't support all possible languages. Could be the issue here. Only a debug log could prove my theory.
