### ISSUE TITLE
In Betaseries zip file, Bazarr take first subtitle file but not the better one

### ISSUE THREAD

**Issue by dtroncy** [morpheus65535/bazarr#664]
Hello,

If a Betaseries zip file contain more than 1 file, Bazarr take the first one and not the better one.

This is done by this function in **betaseries.py** :

````
def _get_subtitle_from_archive(archive):
    for name in archive.namelist():
        # discard hidden files
        if os.path.split(name)[-1].startswith('.'):
            continue

        # discard non-subtitle files
        if not name.lower().endswith(SUBTITLE_EXTENSIONS):
            continue

        return archive.read(name)

    return None
````

Is it possible to change this behaviour ?

**Comment by morpheus65535** [comment]
@Mexx62 You can take a look at this one please?

**Comment by Mexx62** [comment]
I'll take a look at it. The idea would be to compute the scores of each file and take the best, right?  

@dtroncy Do you have an example of file + provider that triggers this behavior that I could use to test the solution?

**Comment by kxzaon** [comment]
I have the exact same problem. Thes subtitles are the very best because they come from sous-titre.eu https://www.betaseries.com/srt/815017 but they don't sync with AMZN-KINGS release because this is not the first sub in the zip file. The perfect behaviour would be to list .zip subtitles and extract the one which match the release.

**Comment by dtroncy** [comment]
@ Mexx62, you can use this one as an example ([https://www.betaseries.com/srt/812108](url)].

In the zip file, you can find 2 files:
- Watchmen.S01E03.720p.WEB.h264-TBS.srt
- Watchmen.S01E03.WEBRip.x264-ION10.AMZN-KiNGS.srt

When Bazarr downloads the zip file on betaseries, it takes the first file in the zip file that is not necessarily the best one according to the file name.

It's almost the same example as @kxzaon.

**Comment by morpheus65535** [comment]
@Mexx62 did you had time to look into this?

**Comment by Mexx62** [comment]
I haven't had time yet to look into it, I think I'll be able to before the end of the week.  
Keeping you in touch :wink:

**Comment by morpheus65535** [comment]
No problem! Thanks! :-)

**Comment by morpheus65535** [comment]
Thanks to @Mexx62 !
