### ISSUE TITLE
Internal Server Error Traceback Auth.type == 'basic'

### ISSUE THREAD

**Issue by shudack** [morpheus65535/bazarr#665]
When I access to bazarr I come across the following error attached.
If I restart the bazarr, It's ok, but after 2h appear again the same error.

Can you help me to fix this?
Thanks

![image](https://user-images.githubusercontent.com/17851196/68400371-d54fdd00-016f-11ea-8a18-15e6ab14846b.png)

Auth in settings:
![image](https://user-images.githubusercontent.com/17851196/68401003-e4835a80-0170-11ea-90af-6e40483dd57e.png)

Software (please complete the following information):

Bazarr: 0.8.3.2 (Branch development)
Sonarr version 2.0.0.5338
Radarr version 0.2.0.1358
OS: Linux-4.9.196-63-aarch64-with-Ubuntu-18.04-bionic

**Comment by morpheus65535** [comment]
Could you provide a debug log please?

**Comment by shudack** [comment]
Never happened again!

**Comment by morpheus65535** [comment]
Ok, reopen it if required!
