### ISSUE TITLE
Error: 500 - AttributeError("'NoneType' object has no attribute 'request'",)

### ISSUE THREAD

**Issue by altendorfme** [morpheus65535/bazarr#668]
**Describe the bug**
Randomly Bazarr starts responding error 500 with the message below when trying to access:

```
Error: 500 Internal Server Error
Sorry, the requested URL 'https://XYZ:8443/bazarr/login' caused an error:

Internal Server Error

Exception:
AttributeError("'NoneType' object has no attribute 'request'",)

Traceback:
Traceback (most recent call last):
  File "/opt/Bazarr/bazarr/../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/opt/Bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/opt/Bazarr/bazarr/main.py", line 154, in login_form
    msg = bottle.request.query.get('msg', '')
AttributeError: 'NoneType' object has no attribute 'request'
```

**Software (please complete the following information):**
 - Bazarr: 0.8.3.2
 - OS: Debian 9

**Last days log:**
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3826853/bazarr.log)
[bazarr.2019-11-06.log](https://github.com/morpheus65535/bazarr/files/3826854/bazarr.2019-11-06.log)
[bazarr.2019-11-07.log](https://github.com/morpheus65535/bazarr/files/3826855/bazarr.2019-11-07.log)

**Comment by morpheus65535** [comment]
Could have been fixed by this fix: https://github.com/morpheus65535/bazarr/commit/2602a0550dfadaee2081dbac16eb0760e32535e1

Can you test dev branch and confirm?

**Comment by altendorfme** [comment]
I just upgraded to the dev branch, let you know if it happens again.

**Comment by altendorfme** [comment]
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3855178/bazarr.log)

The error came up again today, maybe it has something to do with LTZ being down.

**Comment by morpheus65535** [comment]
> [bazarr.log](https://github.com/morpheus65535/bazarr/files/3855178/bazarr.log)
> 
> The error came up again today, maybe it has something to do with LTZ being down.

Nothing I can do with that.
