### ISSUE TITLE
Legendas.tv: AttributeError

### ISSUE THREAD

**Issue by Zamana** [morpheus65535/bazarr#669]
**Describe the bug**
Legendas.tv is with AttributeError status

**To Reproduce**
Just check your Settings -> Providers

**Expected behavior**
I would like to see Status -> Good

**Screenshots**
<img width="1205" alt="legendas_attribute_error" src="https://user-images.githubusercontent.com/6900313/68544706-d3bb2a80-03a4-11ea-9da7-6974b7e59cd2.png">

**Software:**
 - Bazarr: 0.8.3.2
 - Radarr version 0.2.0.1344
 - Sonarr version 2.0.0.5338
 - OS: Alpine Linux 3.10 on an LXC container (Proxmox)

**Additional context**
My account at Legendas.TV is working fine for manual subtitles download.

**Comment by morpheus65535** [comment]
I've just tested it and it works fine for me. Are you still able to reproduce it?

**Comment by Zamana** [comment]
Hi.

Not anymore. It seems that that day the site was offline.

Anyway, after this, in order to force Bazarr to download from Legendas.TV, I disabled every other provider and it worked.

Thanks.
