### ISSUE TITLE
Disable/Set paging

### ISSUE THREAD

**Issue by secret-liar** [morpheus65535/bazarr#67]
Hi,

Would it be possible to add a setting to change the paging of the TV Show list?
To edit the number of TV Show or to disable it?

Thanks!

**Comment by faulander** [comment]
+1

**Comment by morpheus65535** [comment]
Merged to master. You can try it and give me feedback please?

**Comment by secret-liar** [comment]
Perfect! <3

**Comment by morpheus65535** [comment]
👍
