### ISSUE TITLE
Error: 500 Internal Server Error - TypeError('string indices must be integers, not str',)

### ISSUE THREAD

**Issue by TGM** [morpheus65535/bazarr#670]
**Describe the bug**
`Traceback (most recent call last):
  File "/bazarr/bazarr/../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/bazarr/bazarr/main.py", line 121, in wrapper
    return func(*a, **ka)
  File "/bazarr/bazarr/main.py", line 527, in series
    series_count = database.execute("SELECT COUNT(*) as count FROM table_shows", only_one=True)['count']
TypeError: string indices must be integers, not str`

**To Reproduce**
UNKNOWN at this point

![image](https://user-images.githubusercontent.com/584882/68599757-d2bff100-04a9-11ea-95aa-9253f34158f7.png)

**Software (please complete the following information):**
 - Bazarr: v0.8.3.2
 - Radarr  0.2.0.1358
 - Sonarr 2.0.0.5338
 - OS: FreeBSD

**Comment by morpheus65535** [comment]
Could you test dev branch for this fix?

**Comment by TGM** [comment]
The error doesn't pop-up anymore and the interface loads faster. Unfortunately there is no clear way to reproduce it.

**Comment by morpheus65535** [comment]
I was able to reproduce it by clicking on the restart button in System and by keeping the UI open.
