### ISSUE TITLE
1 show in provider status, but all good

### ISSUE THREAD

**Issue by animosity22** [morpheus65535/bazarr#671]
I have a 1 showing up meaning a provider is failed but they are all working. I'm assuming something is stuck somewhere but not sure how to force a recheck or actually clear the rror

**To Reproduce**
I am unsure what I did to create the issue.

**Expected behavior**
I'd expect the 1 to go away as all providers are good.

**Screenshots**
![image](https://user-images.githubusercontent.com/5088712/68766468-e9229580-05ec-11ea-9e98-7613c64b6a82.png)

**Software (please complete the following information):**
 - Bazarr: v0.8.3.3
 - OS: 
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

**Comment by morpheus65535** [comment]
That’s a known issue when you have a provider throttled then you disable it, it won’t be cleared. I need to fix this.

**Comment by morpheus65535** [comment]
Fixed in dev branch.
