### ISSUE TITLE
LanguageReverseError on Addicted

### ISSUE THREAD

**Issue by faulander** [morpheus65535/bazarr#674]
**Describe the bug**
LanguageReverseError on Addicted

**To Reproduce**
Doesn't download any subtitles from Addicted with above error.

**Expected behavior**

**Software (please complete the following information):**
 - Bazarr: 0.8.3.3
 - Sonarr version 2.0.0.5338
 - OS: Docker 

**Additional context**
I've posted the logs to Discord.

**Comment by morpheus65535** [comment]
Please add your debug log here.

**Comment by morpheus65535** [comment]
Is it still an issue? Addic7ed had issues during the weekend.

**Comment by morpheus65535** [comment]
I'm closing this one. Please reopen if you still have this issue.
