### ISSUE TITLE
Feature Request: Add abilty to use Captcha Breaker,

### ISSUE THREAD

**Issue by Zeusy123** [morpheus65535/bazarr#675]
Been thinking of using to save on anti captcha.
http://docu.gsa-online.de/captcha_breaker/options
Basically it runs on my system and fire capcha images @ it and it decodes them.

Wondering if anyway to add this feature?
Software give 5 days demo if you wish to try?

Thanks

**Comment by morpheus65535** [comment]
Why not use anti-captcha.com? It will cost you 0.0022US$ by month approximately... It doesn't worth that I put additional time with that software... :-/

**Comment by chemputer** [comment]
I know this is closed, but with the rising prices (and growing efficacy issues) of Death By Captcha and Anti-Captcha, I was curious if it might be considered to add support for and even integrate something like https://github.com/NoahCardoza/CaptchaHarvester, it does have a Python API, so it should be fairly straightforward and simple to do. 

Based on the example code, it does look pretty easy to integrate, I looked at the death by captcha code, and that seems complex  in comparison. 

If I knew the way Bazarr worked better I'd give it a shot myself, but right now I'd have to spend a fair bit of time familiarizing and whatnot first. If it's anywhere close to as easy as I think it is, someone familiar with the project shouldn't have much of an issue.

The downsides are it can only, as far as I can tell, solve hcaptcha, and recaptcha v2/v3, which is a decent amount, but not everything.

**Comment by morpheus65535** [comment]
@chemputer I have no plan to add other anti-captcha providers. In fact I'm more and more moving away from providers who implement protections like these. I have no time to fight with them and prefer to improve Bazarr features.

**Comment by chemputer** [comment]
I can respect that. I think you understood, but the way you phrased it as "providers" makes me a little unsure, so just to be clear, local solving only, not a paid service. (To be honest I'm not sure what I'd call that, but "Provider" does work I guess.)

If I put the time in myself and submit a PR would you take a look?

**Comment by morpheus65535** [comment]
@chemputer I was referring to the concept of a provider but in fact it's a solver, whenever it's local or remote.

Yes I would review and merge a PR for that.
