### ISSUE TITLE
Can't use remote SSH Sonarr & Radarr files paths

### ISSUE THREAD

**Issue by cristianmiranda** [morpheus65535/bazarr#678]
**Describe the bug**
First, thanks for building Bazarr. Hopefully it'll be my ultimate subtitles solution 😄 
I have a seedbox running Sonarr & Radarr. Bazarr is installed in a Raspberry Pi 4, at home (since the seebox doesn't allow me to install Bazarr 👎). 
I've mounted my seebox home (where all the tv shows and movies live) using sshfs. I've tested the mount and it's working just fine (I can access /home/pi/seedbox and list all files, permissions are ok).
I assumed that *Path Mappings For TV Shows* & *Path Mappings For Movies* would just work (I mapped /home/pi/seedbox/files/Plex/TV_Shows -> /home/pi/seedbox/files/Plex/TV_Shows (doesn't make any sense actually, but I couldn't come up with anything better).
When I go to "Wanted" tab, nothing is being picked up.

**To Reproduce**
1. Install Sonarr & Radarr on a linux machine
2. Install Bazarr in a different linux machine
3. Use *Path Mapping* in Settings as described before
4. Go to "Wanted", nothing being picked up

**Expected behavior**
I would expect that Bazarr does find media using my mounted seedbox on /home/pi/seedbox

**Screenshots**
-

**Software (please complete the following information):**
 - Bazarr: 0.8.3.3
 - Radarr: 0.2.0.1358
 - Sonarr: 2.0.0.5338
 - OS: Raspbian

Thanks! ❤️ And keep up the hard work! 💪

**Comment by morpheus65535** [comment]
Did you specified desired languages for your TV shoes and movies? This sound more like a support request. I suggest you come to Discord for live support.

**Comment by cristianmiranda** [comment]
Yes, the desired language for media files is selected. I've started a conversation on Discord's support channel. Thanks!
