### ISSUE TITLE
Automatic search does not work

### ISSUE THREAD

**Issue by ceekah** [morpheus65535/bazarr#679]
Hello guys! Keen user of Bazarr but running into some trouble i cannot figure out. Got everything setup in Docker and manual search works fine but automatic search does not seem to be working. When i force a subtitle search i will get a notification after 5s "Searching Completed. Please reload the page"  - nothing seems to be added but like i said, manual search finds all the subtitles i need. Bazarr version = 0.8.3.3 & debug logfile attached. (no errors while force auto-searching)

Got Bazarr working a while ago including automatic search but ran into some issue's with permissions. Have been removing/installing Bazarr a few times in Docker. I started a new /config folder so everything should be fresh with the lastest config files + software version.

Anyone any clue? If any information is missing, let me know!

[bazarr_3.log](https://github.com/morpheus65535/bazarr/files/3891458/bazarr_3.log)

**Comment by morpheus65535** [comment]
You have a path mapping issue. A path cannot start like that: `u'Multimedia/Series/American Horror Story/Season 9/American.Horror.Story.S09E01.1080p.WEB.H264.1-METCON-Obfuscated.mkv'`. You're missing something at the beginning.

**Comment by ceekah** [comment]
Thanks for the very quick response. This was indeed not the full path of my series/movies, i've corrected this mistake. Still sounds strange to me why the button "Download Missing Subtitle" does work (see screen). 

I've created a fully new Bazarr from start with now the correct folder mappings. Sadly, i still have the same issue. New log file added and forced a subtitle download of the movie "Crawl" - this one does work again!

Still no errors or invalid path's warnings..

Thank you for your time!

[bazarr (5).log](https://github.com/morpheus65535/bazarr/files/3893466/bazarr.5.log)
![Capture](https://user-images.githubusercontent.com/58034020/69662058-ec556100-1083-11ea-9071-b4d93972f1e7.PNG)

**Comment by ceekah** [comment]
Pretty sure this is indeed a path mapping or permission issue. I'll look further into this.
