### ISSUE TITLE
[Feature Request] Auto restart after auto update

### ISSUE THREAD

**Issue by secret-liar** [morpheus65535/bazarr#68]
Hi,

Would it be possible for Bazarr to autorestart when an update is downloaded from Github instead of doing it manually?

Thanks :)

**Comment by morpheus65535** [comment]
It was more difficult than anticipated. Maybe next time winter is coming, I take a look at it!

**Comment by theotherp** [comment]
You could take a look at sabnzbd or nzbhydra (v1) for hints. It took me forever to get it right so I know that it's not easy to accomplish.

**Comment by morpheus65535** [comment]
@theotherp thanks, I’ll take a look at it!

**Comment by nemchik** [comment]
Just to add to this (since it seems the primary interest is being able to auto restart) I'd also like to see a button in the UI to manually restart whenever I choose.

**Comment by morpheus65535** [comment]
This one have been pushed to development branch a couple of minutes ago. If you want to test it and report. Thanks! BTW you have restart and shutdown button in system.
