### ISSUE TITLE
Provider BetaSeries, 404 error

### ISSUE THREAD

**Issue by Ashyni** [morpheus65535/bazarr#680]
Hello,

Just starting using Bazarr few days ago, and notice some subtitles fetch with BetaSeries return a 404 error.

`Throttling betaseries for 10 minutes, until 19/11/27 14:10, because of: HTTPError. Exception info: u'404 Client Error: Not Found for url: https://subtitles.betaseries.com/addic7ed/The%20Big%20Bang%20Theory%20-%2012x24%20-%20The%20Stockholm%20Syndrome.AVS-SVA.French.HI.updated.Addic7ed.com.srt'`

`https://subtitles.betaseries.com/addic7ed/` return a limited list, that's why we got 404 error.

The API return a full list of subtitles in json with :
`https://api.betaseries.com/shows/episodes?thetvdb_id=80379&season=12&episode=24&subtitles=1&key=api_key&v=3`
   
`GET https://api.betaseries.com/shows/episodes`
Parameters:
-     key : API key (Required)
-     v : API version (Required)
-     id : ID show (Optional if thetvdb_id)
-     thetvdb_id : ID show TheTVDB (Optional if id)
-     season : season number (Optional)
-     episode : episode number (Optional)
-     subtitles : show subtitles (Optional)

example subtitle url return : (I didn't copy/paste the full json response)
`"https://www.betaseries.com/srt/812017"`

PS : unrelated to this topic, the description for the provider BetaSeries should be "API key", not "Token/Secret" (witch required login/password with the api key to be fetch, and it's not necessary to fetch subtitles url)

If you need more information tell me.

**Comment by morpheus65535** [comment]
@Mexx62 could you take a look at this one please?
