### ISSUE TITLE
Bazarr becomes unresponsive while trying to scan a bad format .sub file

### ISSUE THREAD

**Issue by Isilorn** [morpheus65535/bazarr#682]
**Describe the bug**
When Bazarr is scanning filesystem on disk, it will hang if scanning a bad format .sub file (like a binary file for example)

**To Reproduce**
1. Launch "Update all Movie Subtitles from disk"
2. Wait
3. Bazarr will reach 100% CPU for each thread after a while and become unresponsive

**Expected behavior**
Maybe there should be a test to ensure the scanned file is a text file before scanning it ?

**Screenshots**
![image](https://user-images.githubusercontent.com/7522688/69764669-79c2af00-1171-11ea-964b-72f175fd1ca9.png)

**Software (please complete the following information):**
 - Bazarr: v0.8.3.4 (using docker image linuxserver/bazarr:latest)
 - Radarr version v0.2.0.1358 (using docker image linuxserver/radarr:latest)
 - Sonarr version v2.0.0.5338 (using docker image linuxserver/sonarr:latest)
 - OS: Ubuntu 18.04, using Docker Engine v19.03.5

**Additional context**
After some scans ending with 100% CPU usage, I discovered that somehow I managed to download binary .sub files
>plex@phoenix:/volume1/Media/Films/April and the Extraordinary World (2015)$ file April\ and\ the\ Extraordinary\ World.sub
>April and the Extraordinary World.sub: MPEG sequence, v2, program multiplex`

When you launch the "Update all Movie Subtitles from disk" job and it reaches this kind of file, it starts to probe the charset on it
>27/11/2019 23:24:16|DEBUG   |subliminal_patch.core           |external subs: scanning path /Media/Films/April and the Extraordinary World (2015)/April and the Extraordinary World.mkv|
>27/11/2019 23:24:16|DEBUG   |subliminal_patch.core           |Found subtitles {u'April and the Extraordinary World.ro.srt': <Language [ro]>, u'April and the Extraordinary World.en.srt': <Language [en]>, u'April and the Extraordinary World.sub': None}|
>27/11/2019 23:24:16|DEBUG   |subliminal_patch.core           |external subs: found {u'April and the Extraordinary World.ro.srt': <Language [ro]>, u'April and the Extraordinary World.en.srt': <Language [en]>, u'April and the Extraordinary World.sub': None}|
>27/11/2019 23:24:16|DEBUG   |root                            |BAZARR falling back to file content analysis to detect language.|
>27/11/2019 23:24:17|DEBUG   |chardet.charsetprober           |SHIFT_JIS Japanese prober hit error at byte 8|
>27/11/2019 23:24:17|DEBUG   |chardet.charsetprober           |EUC-JP Japanese prober hit error at byte 4|
>27/11/2019 23:24:17|DEBUG   |chardet.charsetprober           |GB2312 Chinese prober hit error at byte 10|
>27/11/2019 23:24:18|DEBUG   |chardet.charsetprober           |EUC-KR Korean prober hit error at byte 4|
>27/11/2019 23:24:18|DEBUG   |chardet.charsetprober           |CP949 Korean prober hit error at byte 14|
>27/11/2019 23:24:18|DEBUG   |chardet.charsetprober           |Big5 Chinese prober hit error at byte 10|
>27/11/2019 23:24:19|DEBUG   |chardet.charsetprober           |EUC-TW Taiwan prober hit error at byte 3|

And after a while it gets unresponsive

**Comment by morpheus65535** [comment]
If you add a language code in filename (ie: subtitles.en.sub), do you still have the issue? I guess not but just to be sure...

**Comment by morpheus65535** [comment]
I've pushed a fix for this in dev branch: 304a5ff1b856f072104ac0e29a9adfb5379b3c0a

**Comment by Isilorn** [comment]
When renaming from 'April and the Extraordinary World.sub' to 'April and the Extraordinary World.fr.sub' with the master branch it doesn't try anymore to guess the charset and then no CPU usage (for this one :) )

And the fix is working with the development branch

> 28/11/2019 22:35:38|DEBUG   |root                            |BAZARR subtitles file doesn't seems to be text based. Skipping this file: /Media/Films/April and the Extraordinary World (2015)/April and the Extraordinary World.sub|

BTW I'm getting a new warning about Python depreciation but I guess linuxserver will fix it in the dependancies at some point

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/7522688/69832660-e4d2bb00-122f-11ea-8bfd-2770fe0f35d5.png">

Thanks a lot !

**Comment by morpheus65535** [comment]
Perfect, thanks for reporting and testing!

The deprecation warning is normal and will disappear once LSIO will have moved our dev image to Python 3.
