### ISSUE TITLE
BAZARR Error trying to get episodes from Sonarr. Http error.

### ISSUE THREAD

**Issue by masterholdy** [morpheus65535/bazarr#683]
**Describe the bug**
I've just installed Bazarr for the first time and have this 2 errors.
50% of my TV-Shows are flagged as "This path doesn't seem to be valid."
even tho the path is correct:

![error1](https://s19.directupload.net/images/191129/4qey7jn7.png)

my second error is that no matter what show i click on (doesnt matter if the first error is appearing or not) has the warning:
No episode files available for this Series or Bazarr is still synchronizing with Sonarr. Please come back later.
under system>logs i've got only one error (but this error appears multiple times)
BAZARR Error trying to get episodes from Sonarr. Http error.

Traceback (most recent call last):
 File "c:\\bazarr\\bazarr\\get_episodes.py", line 46, in sync_episodes
  r.raise_for_status()
 File "c:\\bazarr\\bazarr\\../libs/requests\\models.py", line 940, in raise_for_status
  raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:8989/api/episode?seriesId=50&apikey=KEY

if i open that url in my browser i get the following output
https://pastebin.com/raw/wWVheHfy

**Software (please complete the following information):**
 - Bazarr: 0.8.3.4
 - Radarr version 0.2.0.1358
 - Sonarr version 2.0.0.5338
 - OS: Windows 10

**Additional context**
i tested the connection (settings, sonarr, settings validation) and it tested successful

Edit: all the files inside my Staffel (\d+) folders contain my files in DL (german&english audio layer) all my files named Season (\d+) are english only - i have some shows just in englisch, some just in german, and most mixed
the error is not limited to one subset
some mixed are not flaged as invalid path, some are
same for just german or english

**Comment by morpheus65535** [comment]
Is E:\ a local drive or a SMB mapped drive?

The second issue is clearly a bug in Sonarr and is unrelated to Bazarr.

**Comment by masterholdy** [comment]
im using multiple drives / paths (D:\Serien, E:\, K:\)
all are local drives

any thing i could do to fix the second bug? or do i have to open a issue in sonarr's github repo?

**Comment by morpheus65535** [comment]
First issue: did you put anything in path mapping? I suppose Sonarr run locally?

It’s the first time I see the second issue. Sonarr API return garbage. I would suggest to open an issue on Sonarr GitHub and add a link to it here.

**Comment by masterholdy** [comment]
| Path for Sonarr: | Path for Bazarr |
| ------------- | ------------- |
| D:\Serien\  | D:\Serien\  |
| E:\  | E:\  |
| K:\ | K:\ |


yes sonarr runs locally

sonarr issue https://github.com/Sonarr/Sonarr/issues/3431

**Comment by morpheus65535** [comment]
Don't use path mapping if not required as described in the wiki under: https://github.com/morpheus65535/bazarr/wiki/Settings-General#path-mappings-for-shows

**Comment by masterholdy** [comment]
second issue: fixxed it // i just deleted the corrupt show and readded it

i used this mapping because if i didnt, every show was tagged as "invalid path"

**Comment by morpheus65535** [comment]
Good to know, thanks for the feedback!

**Comment by masterholdy** [comment]
the invalid pathing error ist still not fixed :3 after not using path for bazarr im getting the "this paths seems not to be valid" on every show

**Comment by morpheus65535** [comment]
Please come to Discord where support team is going to be able to help you with configuration issues.
