### ISSUE TITLE
Sonarr series ID not updated after re-import

### ISSUE THREAD

**Issue by Cry0nicS** [morpheus65535/bazarr#685]
**Describe the bug**
`sonarrSeriesId ` is not updated when a series is re-imported in Sonarr

**To Reproduce**
1. Import a series in sonarr and check it in bazarr
2. Remove the series from sonarr and make sure it doesn't show again in bazarr
3. Re-import the same series (I used the same files) in sonarr
4. Bazarr throws a permanent

>  No episode files available for this Series or Bazarr is still synchronizing with Sonarr. Please come back later.

**Expected behavior**
`sonarrSeriesId ` should be updated and the series should be available in bazarr under a new `episodes/{id}` ID.

**Screenshots**
![image](https://user-images.githubusercontent.com/29982205/70093292-bdf9f780-1628-11ea-97b0-cf96871b0b3a.png)

**Software (please complete the following information):**
Bazarr Version: 0.8.3.4
Sonarr Version: 3.0.3.659
Radarr Version: 0.2.0.1450
Operating System: Windows-10-10.0.18362
Python Version: 2.7.16

**Additional context**
Issue discussed in Discord's #support channel

**Comment by morpheus65535** [comment]
Should be fixed in dev branch.
