### ISSUE TITLE
BAZARR unable to index external subtitles

### ISSUE THREAD

**Issue by cdemi** [morpheus65535/bazarr#690]
**Describe the bug**
Recently (I suspect after Python upgrade), I am getting lots of `BAZARR unable to index external subtitles.` error logs.

The stack trace is:
```
Traceback (most recent call last):
 File "/app/bazarr/bazarr/list_subtitles.py", line 69, in store_subtitles
  subtitles = guess_external_subtitles(get_subtitle_destination_folder() or os.path.dirname(reversed_path), subtitles)
 File "/app/bazarr/bazarr/list_subtitles.py", line 370, in guess_external_subtitles
  text = f.read()
 File "/usr/lib/python3.7/codecs.py", line 322, in decode
  (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: \utf-8\ codec can\t decode byte 0xe9 in position 2700: invalid continuation byte
```

It does not seem to be one particular file only because the `decode byte` and `position` always changes

**Software (please complete the following information):**
 - Bazarr: 0.8.4
 - OS: Linux-4.4.0-169-generic-x86_64-with
 -  Python Version: 3.7.5

**Comment by cdemi** [comment]
After doing some more searching I found the comment: 509#issuecomment-521009909

Apparently in Python 3.0 the default encoding has changed and [in Python 3.6 further changes were made](https://docs.python.org/3/whatsnew/3.6.html). 

Unfortunately I am so unfamiliar with Python that I don't know the best approach how to tackle this?

Is it possible to set defaults in the docker image?

**Comment by morpheus65535** [comment]
Should be fixed by this commit to dev branch: https://github.com/morpheus65535/bazarr/commit/4260d8ddfe65bb02b6f12a97c023c81d15302b07
