### ISSUE TITLE
Throttling addic7ed for 10 minutes, because of: UnicodeDecodeError. Exception info: 'ascii'

### ISSUE THREAD

**Issue by cdemi** [morpheus65535/bazarr#693]
**Describe the bug**
In the error logs I can see that the addic7ed provider is getting disabled because of a `UnicodeDecodeError`. I suspect this is also related to the Python upgrade.

Unfortunately, the error message does not provide stack trace and I don't know exactly what to look for in the source code to enhance logging

**Software:**
 - Bazarr: 0.8.4
 - OS: Linux-4.4.0-169-generic-x86_64-with
 - Python Version: 3.7.5
 - Latest Docker container

**Comment by cdemi** [comment]
I think this might be related to https://github.com/morpheus65535/bazarr/issues/690#issuecomment-561714400 as well

**Comment by morpheus65535** [comment]
Addic7ed is working fine for me. It could be related to default encoding.

**Comment by morpheus65535** [comment]
Please provide a debug log while reproducing the issue.

**Comment by cdemi** [comment]
I have added `PYTHONIOENCODING=utf-8` as an environment variable on the container and it looks like it's working.

If you agree, I suggest this to be added to the Python 3 docker image

**Comment by morpheus65535** [comment]
And you can easily reproduce the issue by removing this environment variable?

**Comment by cdemi** [comment]
Yes after I removed it, the issue started arising again. Let's wait to see if other people have the same problem. If they do you cam add it to Dockerfile

**Comment by cdemi** [comment]
Btw, this also solved #690 for me

**Comment by morpheus65535** [comment]
> Btw, this also solved #690 for me

You were still having this issue even after the fix I pushed last night?

**Comment by morpheus65535** [comment]
> Yes after I removed it, the issue started arising again. Let's wait to see if other people have the same problem. If they do you cam add it to Dockerfile

Of course, if it's confirm I will ask LSIO to add it to the Dockerfile.

**Comment by cdemi** [comment]
Actually scratch that. Although I am not seeing the error in the log file, the provider is still being disabled because of `UnicodeDecodeError` in the provider list

**Comment by morpheus65535** [comment]
Could you provide a debug log while reproducing the provider being throttled?

**Comment by Benusnt** [comment]
Hello, 
I am also unable to see addic7ed subtitles:

|Throttling addic7ed for 10 minutes, until 19/12/16 01:16, because of: AccessDeniedException. Exception info: 'Access denied, check your credentials'|

I have a DBC account, and no captchas have been sent to resolve. I changed my addicted password, still no luck.

Would you have an idea as to how to resolve that matter?

Thanks

**Comment by morpheus65535** [comment]
@Benusnt this is a different issue. Please come to Discord if you need help configure your provider.

**Comment by cdemi** [comment]
With regards to this issue, I haven't noticed it happening again. To be honest I'm not really sure what the resolution was but I will close the issue until I have further information
