### ISSUE TITLE
Significant and prolonged CPU usage after upgrading from 0.8.2.4 to 0.8.3.4, when performing the "update all Movie Subtitles from disk" task

### ISSUE THREAD

**Issue by eltiel** [morpheus65535/bazarr#694]
**Describe the bug**
Significant and prolonged CPU usage after upgrading from 0.8.2.4 to 0.8.3.4, when performing the "update all **Movie Subtitles** from disk". No problems with **Episode Subtitles.**

**To Reproduce**
Not sure how to reproduce this, but all I did was upgrade from 0.8.2.4 to 0.8.3.4 and noticed that at 0500 hours the following day, the CPU usage spiked. The task ran for 12 hours before I terminated it manually. The following day, it spiked again.

**Expected behavior**
There should not be such a massive and prolonged CPU usage spike, as evidenced in the screenshot below. CPU utilization for the past 1-week was not anomalous, until I upgraded Bazarr. There were no configuration changes in any of my Bazarr, Sonarr or Radarr setups. There were no significant changes in the library content as well. At the most, 2-3 movies were added in the past week. 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/11868456/70196395-89c72980-1743-11ea-800d-9c7b585c6d94.JPG)

**Software (please complete the following information):**
 - Bazarr: 0.8.3.4
 - Radarr version: 0.2.0.1358
 - Sonarr version: 3.0.3.659
 - OS: Synology DSM 6.2

**Additional context**
Since the update, logs are full of the following entries:

`05/12/2019 05:25:21|WARNING |bs4.dammit                      |Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.|`

`05/12/2019 05:25:21|ERROR   |root                            |BAZARR Error trying to detect language for this subtitles file: /movies/redactedmoviename.sub You should try to delete this subtitles file manually and ask Bazarr to download it again.|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/list_subtitles.py", line 411, in guess_external_subtitles\n    text = text.decode(encoding.original_encoding)\n  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode\n    return codecs.utf_8_decode(input, errors, True)\nUnicodeDecodeError: \'utf8\' codec can\'t decode byte 0xba in position 3: invalid start byte'|
`

This happens consistently on any movies with .sub subtitles present.

**Comment by morpheus65535** [comment]
I've pushed a fix to dev branch tonight (https://github.com/morpheus65535/bazarr/commit/4260d8ddfe65bb02b6f12a97c023c81d15302b07), could you give it a try and tell me if it help? Thanks.

**Comment by eltiel** [comment]
It appears to have solved the problem. Manual trigger of the task completed in a mere 3 minutes with no significant CPU usage spike. Will continue to monitor. 

Many thanks for your extremely quick response, as well as your awesome work on Bazarr.

**Comment by morpheus65535** [comment]
Thanks I appreciate the feedback. I'll close this issue but don't hesitate to reopen it if you still face it. Enjoy!
