### ISSUE TITLE
Bazarr memory leak

### ISSUE THREAD

**Issue by rodalpho** [morpheus65535/bazarr#695]
I run Bazarr 0.8.3.4 in a LXC restricted to 8GB max RAM and OOMkiller regularly kills off the Bazarr process. I even bounce it nightly via cron to try to head it off.

As you can see below it was using 5.7GB of RAM (3.8GB anon) when killed, which rather seems like a lot of memory to download subtitles.

`[2543104.822333] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=nzb,mems_allowed=0,oom_memcg=/lxc.payload/nzb,task_memcg=/lxc.payload/nzb/system.slice/bazarr.service,task=python,pid=30461,uid=0`
`[2543104.822380] Memory cgroup out of memory: Killed process 30461 (python) total-vm:5753460kB, anon-rss:3802076kB, file-rss:0kB, shmem-rss:0kB
[2543104.945546] oom_reaper: reaped process 30461 (python), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB`

**Comment by morpheus65535** [comment]
Bazarr shouldn't use more than 150MB of RAM. You clearly have an issue. Does the memory consumption increase at a specific time of the day or is it progressive?

**Comment by rodalpho** [comment]
The crashes all seem to be around 5:20AM and Bazarr was configured to scan movies at 5AM daily. That's the only correlation I can find. 

Cron bounces Bazarr every morning at 5:50AM and right now at 3PM it's using 320MB resident, 2.2GB virt.

**Comment by morpheus65535** [comment]
That’s way too high. Can you enable debug log for let say an hour and provide the resulting log file?

**Comment by rodalpho** [comment]
Actually I had two processes running. The 5:37AM one is active, so that must have been after OOMkiller killed it and systemd started it back up. The 5:50AM process I just killed; it was not being used and Bazarr still functioned after I killed it.

`
root       990  0.0  5.5 2242256 327720 ?      Sl   05:37   4:24 /usr/bin/python -u /opt/Bazarr/bazarr/main.py`
`root      3519  0.0  0.1  26636  7852 ?        Ss   05:50   0:03 /usr/bin/python /opt/Bazarr/bazarr.py`

Sure, I just turned debug on.

**Comment by morpheus65535** [comment]
bazarr.py is just a daemon process. Nothing complex here. main.py is where the magic happen. ;-)

**Comment by rodalpho** [comment]
Ahh OK, gotcha. Will send a link to the debug log in 45m.

**Comment by rodalpho** [comment]
The debug log is here. Please let me know when you have it so I can delete, not sure if anything private is in there. I skimmed it and it looks OK, but it's 24k lines.

https://gist.githubusercontent.com/rodalpho/eac450dc478a06bac6cf8e7b2d86f4db/raw/b3c1161cf5f4d45813aec6be3adb63ec9190a0c5/gistfile1.txt

**Comment by scottrus** [comment]
Running Bazarr v0.8.3.4 from source on Ubuntu 18.04 LTS. My install is just a simple git clone, setup a user, and execute Bazarr via systemd. I'm not using containers. 

I installed it Wednesday evening and saw the attached memory usage after executing a full scan on Thursday at 4am (regular task schedule). You can see where the memory usage jumped up until I restarted it just before posting this comment. Great service, but seems to be using a ton of memory.

![bazarr memory](https://user-images.githubusercontent.com/13910092/70286573-be65d000-1799-11ea-9a22-c5e289062bef.png)

**Comment by morpheus65535** [comment]
@rodalpho @scottrus could you test development branch? I've pushed a fix last night that could be fixing your issue. I would be glad if you can confirm it. Thanks!

**Comment by rodalpho** [comment]
Sure, I just upgraded to 8.4.

I also deleted the debug log.

**Comment by scottrus** [comment]
@morpheus65535 Thank you! I'll pull dev in a little bit and run form that.

**Comment by scottrus** [comment]
Now running under development.

```
root@storzilla:/opt/bazarr# git log -1
commit e6cb1b1a8fcbc078f63c1289fed41c0f42425ce3 (HEAD -> development, origin/development)
Author: Louis Vézina <5130500+morpheus65535@users.noreply.github.com>
Date:   Thu Dec 5 14:43:48 2019 -0500

    Fix for wizard not enabling required languages.
root@storzilla:/opt/bazarr# git branch
* development
  master
```

I'm also on python 2.7.15+ but can move to 3.6 (or later) if you think it matters.

**Comment by morpheus65535** [comment]
@scottrus There'S no reason to. 0.8.4 is compatible with Python 2.7.15+ and I want to be sure we don't change too much variable in the equation.

**Comment by rodalpho** [comment]
Bazarr is up to 334MB this morning.

`root     19221  0.0  0.0  39664   216 ?        Ss   Dec05   0:00 /usr/bin/python /opt/Bazarr/bazarr.py
root     19222  0.0  5.7 2316660 334044 ?      Sl   Dec05  91:27 /usr/bin/python -u /opt/Bazarr/bazarr/main.py`

**Comment by scottrus** [comment]
Looks like I had the same behavior as yesterday. Since I'm watching more closely I can say

4am - small memory increase as we do scanning of episodes
5am - start scanning of movies
5:10am - large jump in memory consumption

I haven't killed the processes yet. If there are commands you need me to run to see what they are doing let me know.

Attaching Munin memory graph and log file (not debug) from today.

![memory-pinpoint=1575590422,1575643612](https://user-images.githubusercontent.com/13910092/70331708-00c8f480-180e-11ea-86c5-9b53ad9ede17.png)

[bazarr.log](https://github.com/morpheus65535/bazarr/files/3932700/bazarr.log)

**Comment by scottrus** [comment]
Not sure it matters, but from the log the Episode scan was still running when the Movie scan kicked off. 

```
06/12/2019 05:53:40|INFO    |root                            |BAZARR All existing episode subtitles indexed from disk.|
06/12/2019 07:41:27|INFO    |root                            |BAZARR All existing movie subtitles indexed from disk.|
```

**Comment by rodalpho** [comment]
My Bazarr is tracking 185 series and 397 movies, if that information is helpful to you.

**Comment by morpheus65535** [comment]
How many episode and movie files?

**Comment by rodalpho** [comment]
3588 episode files, 397 movie files.

**Comment by rodalpho** [comment]
After 2 days, 344MB. Definitely higher than you expected (150MB) but it hasn't brought up OOMkiller yet!


`root     19221  0.0  0.0  39664   216 ?        Ss   Dec05   0:00 /usr/bin/python /opt/Bazarr/bazarr.py`
`root     19222  0.0  6.0 2317428 352656 ?      Sl   Dec05 191:51 /usr/bin/python -u /opt/Bazarr/bazarr/main.py`

**Comment by chillyshackk** [comment]
If I can provide anything useful let me know but I use linuxserver/bazarr docker and I have seen it go up to almost 4gb of ram a couple of times now, to the point where I no longer let it run, I have 479 movies in radarr and 98 tv shows in sonarr, all running in docker / docker compose on manjaro, kernel 5.4.2-1-MANJARO (So it shouldn't be the memory leak from 5.4.2), bazarr is running as my user and not root, also set up using traefik 1.7 (latest 1.7), also have jellyfin, qbittorrent, nzbget, jackett, lidarr, everything works fine, only bazarr does this.

**Comment by rodalpho** [comment]
Well, NZBhydra2 has a memory leak too, but that isn't morpheus' problem. :)

**Comment by scottrus** [comment]
If I get time tomorrow  I’ll see if I can debug. I’m hoping this is something easy like not closing open files. 😊

**Comment by chillyshackk** [comment]
It was just to give a general idea of what I am running in case it could affect bazarr's behavior somehow. If more logs are needed I'll set bazarr to debug and wait until it happens again. For now since I am not missing many subs I turned it off. 

Also I am setup to download English and French subs.

**Comment by morpheus65535** [comment]
> If I can provide anything useful let me know but I use linuxserver/bazarr docker and I have seen it go up to almost 4gb of ram a couple of times now, to the point where I no longer let it run, I have 479 movies in radarr and 98 tv shows in sonarr, all running in docker / docker compose on manjaro, kernel 5.4.2-1-MANJARO (So it shouldn't be the memory leak from 5.4.2), bazarr is running as my user and not root, also set up using traefik 1.7 (latest 1.7), also have jellyfin, qbittorrent, nzbget, jackett, lidarr, everything works fine, only bazarr does this.

It would help to see a debug log as I'm presuming you have  probably issue with your setup. I have approximately the same number of movies and shows and Bazarr use 85MB of RAM with LSIO image.

**Comment by morpheus65535** [comment]
@scottrus Every media file is opened with ffprobe in a subprocess that should free up memory as soon as it exit. Just to be sure, I run garbage collector after scanning all episodes and again after running all movies.

**Comment by rodalpho** [comment]
305MB now after 4 days. It's still higher than you expected, but I'm not seeing a persistent leak with the dev version.


`root     19221  0.0  0.0  39664   216 ?        Ss   Dec05   0:01 /usr/bin/python /opt/Bazarr/bazarr.py`
`root     19222  0.0  5.3 2317684 312688 ?      Sl   Dec05 351:08 /usr/bin/python -u /opt/Bazarr/bazarr/main.py`

**Comment by morpheus65535** [comment]
@rodalpho that's a good news :-)

The difference could be related to the number of episode you have (approximately 3 times what I have) but I would be surprised...

**Comment by scottrus** [comment]
Episodes: 2751
Movies: 894

There are 99 existing sub files that produce a traceback during scanning due to invalid chars that I need to clean up.

**Comment by morpheus65535** [comment]
@scottrus could you provide an exemple of the trace?

**Comment by scottrus** [comment]
@morpheus65535 Actually, after cleaning up those 99 files I'm not seeing the issue any more? I just did a full scan of episodes and movies concurrently. 

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
bazarr    4812  0.0  0.0  26412  9496 ?        Ss   11:35   0:00 /usr/bin/python /opt/bazarr/bazarr.py
bazarr    4828 11.6  1.7 1886428 284432 ?      Sl   11:35   1:40 /usr/bin/python -u /opt/bazarr/bazarr/main.py
```

**Comment by scottrus** [comment]
I'll see what happens at the regularly scheduled cron job tonight.

**Comment by morpheus65535** [comment]
@scottrus You just need to change it at the bottom of Settings-->General and hit Save.

**Comment by morpheus65535** [comment]
I have memory profiled the whole stuff and cannot find what's wrong. Although your instances are using more memory than mine, it could be related to your architecture (mine is x86-64). If you don't face constant memory leak with dev image but just higher memory usage than expected, I'll close this one. Do you agree?

**Comment by scottrus** [comment]
I appreciate you looking into it. I’m good with it being closed.

**Comment by rodalpho** [comment]
I'm still at 315MB after 5 days so yeah, I think the dev version did the trick. Thanks again!
