### ISSUE TITLE
Version v0.8.3.4 does not handle files with numbers or accented characters

### ISSUE THREAD

**Issue by Zamana** [morpheus65535/bazarr#696]
**Describe the bug**
Version v0.8.3.4 does not handle files with numbers or accented characters

**To Reproduce**
1. Install version v0.8.3.4
2. Click on 'Series....' or 'Movies...'
3. See error

`Error: 500 Internal Server Error
Sorry, the requested URL 'http://bazarr.local:6767/series' caused an error:

Internal Server Error
Exception:
UnicodeEncodeError('ascii', u'/storage/plex/series/brazilian/Cine Holli\xfady', 41, 42, 'ordinal not in range(128)')
Traceback:
Traceback (most recent call last):
  File "/usr/local/bazarr/bazarr/../libs/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/bazarr/bazarr/../libs/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/bazarr/bazarr/main.py", line 122, in wrapper
    return func(*a, **ka)
  File "/usr/local/bazarr/bazarr/main.py", line 579, in series
    current_port=settings.general.port)
  File "/usr/local/bazarr/bazarr/../libs/bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/local/bazarr/bazarr/../libs/bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "/usr/local/bazarr/bazarr/../libs/bottle.py", line 3396, in execute
    eval(self.co, env)
  File "/usr/local/bazarr/views/series.tpl", line 82, in <module>
    %if os.path.isdir(row['path']):
  File "/usr/local/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfa' in position 41: ordinal not in range(128)`

**Expected behavior**
The Series or Movies page should show up.

**Screenshots**
![movies](https://user-images.githubusercontent.com/6900313/70270959-332e0f80-1784-11ea-8612-684be357633f.png)

![series](https://user-images.githubusercontent.com/6900313/70270966-36290000-1784-11ea-9ac5-6e9e9b0c339b.png)

**Software (please complete the following information):**
 - Bazarr: v.0.8.3.4
 - Radarr version 0.2.0.1358
 - Sonarr version 2.0.0.5338
 - OS: jail inside FreeNAS 11.2-U7

**Additional context**
Rolling back to v.0.8.3.3 until this is fixed.

**Comment by morpheus65535** [comment]
It's working perfectly fine for me with the `24` series. You are probably having an encoding issue in your jail. You should specify locale.

**Comment by Zamana** [comment]
Hello Morpheus.

Thanks for reply.

But how do you explain the fact that I didn't touched the jail in anyway? I just changed the Bazarr version: the new version give those errors, the previous not.

**Comment by morpheus65535** [comment]
Yes, I've got a bunch of `é`, `à` or `ù` begin a french speaking person. No issue when you fix the encoding of you computer correctly.

**Comment by Zamana** [comment]
But how do you explain the fact that I didn't touched the jail in anyway? I just changed the Bazarr version: the new version give those errors, the previous not. And the locale is the same.

**Comment by morpheus65535** [comment]
I can't but I haven't change that part of code in a while.
