### ISSUE TITLE
Bazarr attempting to load missing file when started

### ISSUE THREAD

**Issue by Kreeblah** [morpheus65535/bazarr#698]
**Describe the bug**
When attempting to start Bazarr as a systemd service on Linux, it attempts to load a non-existant Python file and fails to run.

**To Reproduce**
1. On an Ubuntu 18.04 host, go to /opt.
2. Clone the master repository.
3. Verify that /opt/bazarr (along with all the contents) has appropriate permissions for the user to run it as, or change ownership so that it does.
4. Use pip to install the dependencies required per the instructions in the Linux section of https://github.com/morpheus65535/bazarr/wiki/Installation-Running-from-Source
5. Use the example file listed at https://github.com/morpheus65535/bazarr/wiki/systemd-service-file-for-Debian-Ubuntu to create a systemd service file located at /lib/systemd/system/bazarr.service with a user and group appropriate to the Python file.
6. Run systemctl enable bazarr
7. Run systemctl daemon-reload
8. Run service bazarr start

**Expected behavior**
Bazarr should start.

**Actual behavior**
Bazarr terminates immediately, with the following line in /var/log/syslog:
Dec  7 21:45:02 server python[21930]: /usr/bin/python: can't open file '/opt/Bazarr/bazarr/bazarr.py': [Errno 2] No such file or directory

**Software (please complete the following information):**
 - Bazarr: Commit 672e69e88780d0a0d7e58d1f127662e8f7a9a311 from the master branch
 - OS: Ubuntu 18.04
 - Python: 2.7.15+
 - systemd: 237

**Additional context**
The relevant lines from my systemd file are:
WorkingDirectory=/opt/bazarr/
ExecStart=/usr/bin/python /opt/bazarr/bazarr.py

Using sudo to execute that same command under ExecStart as the user I have configured in my systemd file results in Bazarr running just fine.  That said, I'm not sure this is a systemd issue, per se, since there's nothing in my systemd service that has "/Bazarr" with a capital B anywhere in it that could be used for pathing.

**Comment by morpheus65535** [comment]
Is it `/opt/bazarr` or `/opt/Bazarr`? Make sure your case it the same everywhere.

**Comment by Kreeblah** [comment]
It's `/opt/bazarr` in both places:

```
user@server:~$ ls /opt/bazarr/bazarr.py 
/opt/bazarr/bazarr.py
user@server:~$ cat /lib/systemd/system/bazarr.service 
[Unit]
Description=Bazarr Daemon
After=syslog.target network.target
# After=syslog.target network.target sonarr.service radarr.service

[Service]
WorkingDirectory=/opt/bazarr/
User=xbmc
Group=xmbc
UMask=0002
Restart=on-failure
RestartSec=5
Type=simple
ExecStart=/usr/bin/python /opt/bazarr/bazarr.py
KillSignal=SIGINT
TimeoutStopSec=20
SyslogIdentifier=bazarr
ExecStartPre=/bin/sleep 30

[Install]
WantedBy=multi-user.target
```

There's really nowhere I can see here that it would be getting a capital-B Bazarr directory name from.

**Comment by morpheus65535** [comment]
It’s definitely in your service config somewhere. It’s nowhere in Bazarr source.

**Comment by Kreeblah** [comment]
I did some more testing, and apparently it's giving me the same error even if I remove the bazarr.py file entirely.  I was thinking that that was trying to load another Python module and failing, but I guess it really is a systemd issue.  I'm absolutely mystified as to how, though.

**Comment by morpheus65535** [comment]
I have no clue what is the problem from what I see. I hope you'll find where the problem is and be able to enjoy Bazarr. good luck!
