### ISSUE TITLE
Bazarr cannot find file(s) in volume

### ISSUE THREAD

**Issue by seik** [morpheus65535/bazarr#699]
**Describe the bug**
Bazarr cannot find folders/files with spaces.

**Expected behavior**
Bazarr should find the files.

**Screenshots**

<img width="820" alt="imagen" src="https://user-images.githubusercontent.com/9640279/70394775-62e54d80-19f8-11ea-8c9d-83867051d094.png">
<img width="740" alt="imagen" src="https://user-images.githubusercontent.com/9640279/70394765-46e1ac00-19f8-11ea-9f0f-152a25bd1505.png">

**Software:**
 - Bazarr: 0.8.3.4 
 - Radarr version 2.0.0.5338
 - Sonarr version  0.2.0.1450
 - OS: Docker (LinuxServer.io image)

**Aditional context**
I'm trying to find a solution here since I don't think bazar is not working... but, the volume is mounted and after entering by shell I can ls the exact same path bazarr says is not finding.

**Comment by halali** [comment]
You have to setup your pathmappings in bazarr general settings.

**Comment by seik** [comment]
Hi @halali, mappings are configured

<img width="881" alt="imagen" src="https://user-images.githubusercontent.com/9640279/70396774-2facb980-1a0c-11ea-8f00-3124ba344561.png">

Both sonarr and radarr are in containers, shows volume is mounted in /tv and movies in /movies.

**Comment by seik** [comment]
Welp, just checked the logs to see if something new appeared and got a bunch of these: 

<img width="741" alt="imagen" src="https://user-images.githubusercontent.com/9640279/70396842-df822700-1a0c-11ea-9fd3-240aa451d223.png">

Complete log here: https://gist.github.com/seik/2f4d5c9075c7cacdad583d2e56d70f51

**Comment by morpheus65535** [comment]
You inverted series and movies path in your path mapping. As they are the same, you don’t need it at all.

**Comment by seik** [comment]
@morpheus65535 wow sorry for the mistake. I deleted the mappings now but the problem persists. Bazarr seems to try to find the files without success.

I don't know if I should move this issue to discord since it seems more of my configuration than the project itself.

**Comment by morpheus65535** [comment]
No problem mate. Yes I suggest you move to Discord to get live support with the team.

**Comment by seik** [comment]
Just fixed the problem thanks to the awesome crew in the discord server. In case anyone wants to know what the problem was I didn't set up the PGID and PUID enviroment variables.
