### ISSUE TITLE
Only episodes/series with a "monitored" status should be checked for subtitles.

### ISSUE THREAD

**Issue by tim-durrant** [morpheus65535/bazarr#70]
For example, I only monitor Season 09 of NCIS:LA, so it would be more efficient for Bazarr to pre-check which episodes/series are "monitored" before checking for a subtitle.

**Comment by morpheus65535** [comment]
You're not the first to ask for this. Unfortunately, Bazarr doesn't keep track of season. We only render it in UI based on season and episode number returned from Sonarr. Would an option to search only for episodes monitored subtitles in Sonarr would meet your use case?

**Comment by morpheus65535** [comment]
I've commit this to dev branch. Could you please try it and report back?

Thanks!
