### ISSUE TITLE
Sub downloaded but Bazarr keep dowloading it

### ISSUE THREAD

**Issue by marchah** [morpheus65535/bazarr#700]
**Describe the bug**
Hi,

For `Once.Upon.A.Deadpool.2018.720p.WEB-DL.MkvCage.ws.mkv` Bazarr download the subtitles, it's present on my HD but Bazarr doesn't seem to know it has been downloaded already so it keep getting download every 3h.

**Screenshots**

<img width="1144" alt="Screen Shot 2019-12-09 at 7 55 45 AM" src="https://user-images.githubusercontent.com/818848/70479379-0e8eac00-1a92-11ea-885c-ba8c43b0960e.png">
<img width="629" alt="Screen Shot 2019-12-09 at 8 04 50 AM" src="https://user-images.githubusercontent.com/818848/70479406-1f3f2200-1a92-11ea-835f-366aec364a26.png">
<img width="1378" alt="Screen Shot 2019-12-09 at 8 07 04 AM" src="https://user-images.githubusercontent.com/818848/70479415-2403d600-1a92-11ea-8378-19db148099e2.png">

<img width="1030" alt="Screen Shot 2019-12-09 at 7 55 59 AM" src="https://user-images.githubusercontent.com/818848/70479401-1a7a6e00-1a92-11ea-9807-e02c6c34e2f4.png">

[bazarr.log](https://github.com/morpheus65535/bazarr/files/3942054/bazarr.log)

**Software (please complete the following information):**
 - Bazarr: 28.06.19

**Comment by morpheus65535** [comment]
Bazarr try to identify the language code from the subtitles filename and cannot get a language matching this code `ws`. I suggest you disable the `Use Single language` settings and you'll get subtitle ending with `.en.srt` that will be recognized without any issue.
