### ISSUE TITLE
The subtitles are found but not downloaded. Using Docker Image

### ISSUE THREAD

**Issue by giva01121** [morpheus65535/bazarr#701]
**Describe the bug**
Hello, 
I'm having issues downloading subtitles. I'm using docker image for the bazarr app. The subtitles are found but they aren't downloaded automatically, nor manually. When I try to download them manually the page is getting refreshed and nothing happens - the docker log is not updating also, the only displayed message is: 
`2019-12-11 10:21:12,851 - root                             (7f0599a16b20) :  INFO (get_subtitle:872) - BAZARR Finished searching for missing Subtitles. Check History for more information.
` 
Which is preventing me to trace the issue. Please advise if I can enable the app in debug mode

**To Reproduce**
1. Go to Series
2. Click on chosen series title
3. Click on 'Manual Search'
4. Download chosen subtitle release

**Expected behavior**
I'm expecting to be able to download subtitles via bazarr, either manually, either automatically

**Screenshots**
Here are the screenshots from the found subtitles:
![image](https://user-images.githubusercontent.com/58251102/70604393-4f590300-1c01-11ea-9167-721fc6075353.png)

Here are my mappings
![image](https://user-images.githubusercontent.com/58251102/70604144-c641cc00-1c00-11ea-86f0-430021f370bc.png)

**Software (please complete the following information):**
 - Bazarr: [v0.8.3.4-ls59] Running on Docker
 - Radarr version [v0.2.0.1358-ls36] Running on Docker
 - Sonarr version [2.0.0.5338-ls36] Running on Docker
 - OS: [Ubuntu 19.04]

**Additional context**
The user with which I'm starting the container is the same for each of my media apps. But for the other apps everything is working fine. Here's how I'm starting the docker container:

`sudo docker create --name=bazarr \
--restart=always \
-v /home/docker/bazarr/config:/config \
-v /mnt/Series:/data/series1 \
-v /mnt2/Series:/data/series2 \
-v /mnt/Movies:/data/movies1 \
-v /mnt2/Movies:/data/movies2 \
-v /mnt2/Download:/data/Download \
-e PGID=1000 -e PUID=1000 \
-e TZ=Europe/Sofia \
-p 4444:6767 \
linuxserver/bazarr`

here are the user permissions:
```
grigor@HP-8470p:~$ id
uid=1000(grigor) gid=1000(grigor) groups=1000(grigor),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),118(lpadmin),129(sambashare)
```

**Comment by halali** [comment]
Have you enabled single language setting?

**Comment by morpheus65535** [comment]
Is there something in history? What providers did you enable?

**Comment by giva01121** [comment]
@halali I've enabled it yes
@morpheus65535 nothing in history. Here are my providers, including open subtitles:
![image](https://user-images.githubusercontent.com/58251102/70628133-3f0c4c80-1c30-11ea-81c2-c965f21217db.png)

**Comment by morpheus65535** [comment]
Can you provide a debug log reproducing a search for wanted subtitles?

**Comment by giva01121** [comment]
Can you please explain me how to enable debug modw

**Comment by morpheus65535** [comment]
Settings-->General-->Enable debug logging.

**Comment by giva01121** [comment]
ok, I'm attaching the debug log. The strange thing is that when I try manual search, the subs are found with a score above 94%, but they aren't downloaded automatically. Here are more screenshots
Wanted:
![image](https://user-images.githubusercontent.com/58251102/70689939-35c9c100-1cbe-11ea-972d-58422a902ebe.png)

Manual Search
![image](https://user-images.githubusercontent.com/58251102/70690146-bd173480-1cbe-11ea-82c0-ff83cabae2f5.png)

Example Episodes:
![image](https://user-images.githubusercontent.com/58251102/70690290-0e272880-1cbf-11ea-8837-0ecfe9254b03.png)

Settings:
![image](https://user-images.githubusercontent.com/58251102/70690371-3f9ff400-1cbf-11ea-9eef-c1c279e95c13.png)
![image](https://user-images.githubusercontent.com/58251102/70690428-51819700-1cbf-11ea-8461-9580d7e83340.png)


[bazarr.log](https://github.com/morpheus65535/bazarr/files/3954306/bazarr.log)

**Comment by morpheus65535** [comment]
Could you send me your bazarr.db file in private on Discord? This one is really strange...

**Comment by giva01121** [comment]
@morpheus65535 I will be very happy to share with you the db file, but I'm not aware how to reach you via Discord. Can you provide me details please?

**Comment by morpheus65535** [comment]
https://discord.gg/MH2e2eb

Private message me once your on the Bazarr server.
