### ISSUE TITLE
Subtitles are not recognized as downloaded/available

### ISSUE THREAD

**Issue by screamerbg** [morpheus65535/bazarr#702]
**Describe the bug**
The subtitles are already available next to the video files (attached image 1), but Bazarr doesn't recognize them as such (attached image 2).

Renaming the video + subtitle files does help, but this should work fine out of the box

**To Reproduce**
1. Add "The X-Files" TV series in Sonarr
2. Recreate the file structure as shown in the first attached image. (The X-Files - Season 11 folder)
3. Check Bazaar - it doesn't seem to recognize the subtitle files

**Expected behavior**
Bazarr should correctly identify the subtitles files.

**Screenshots**
Image 1

<img width="726" alt="Screenshot 2019-12-12 at 15 17 25" src="https://user-images.githubusercontent.com/5940648/70725113-b48d2100-1cf3-11ea-9c77-cab69954a6dd.png">

Image 2
<img width="1098" alt="Screenshot 2019-12-12 at 15 25 43" src="https://user-images.githubusercontent.com/5940648/70725180-d71f3a00-1cf3-11ea-84bd-074990cad351.png">

Config
[config.ini.zip](https://github.com/morpheus65535/bazarr/files/3956488/config.ini.zip)

**Software (please complete the following information):**
 - Bazarr: 0.8.3.4 
 - Radarr version 0.2.0.1450
 - Sonarr version 2.0.0.5338
 - OS: Windows 7 (latest updates)

**Additional context**

**Comment by morpheus65535** [comment]
Your subtitles doesn't have language code in the filename. Bazarr have to guess from the text in the subtitles file and could fail. That's most certainly what happen for you.

**Comment by screamerbg** [comment]
How does it work for the other season of the same season without language code then? See below.

<img width="560" alt="Screenshot 2019-12-12 at 20 13 51" src="https://user-images.githubusercontent.com/5940648/70745600-08136500-1d1c-11ea-8487-6003ecd0c63c.png">

<img width="1073" alt="Screenshot 2019-12-12 at 20 14 16" src="https://user-images.githubusercontent.com/5940648/70745629-19f50800-1d1c-11ea-9a5e-048933e03bd6.png">

**Comment by morpheus65535** [comment]
No idea other than the langdetec library that we use is able to do its job.

**Comment by screamerbg** [comment]
Either way, is this a bug or not? :)
If it is - then why is this ticket closed?
If it's not and I shouldn't use subtitles without language code, then why there is a "Single Language" option in settings?

**Comment by morpheus65535** [comment]
A bug? No. Using subtitles without language code in filename is a bad idea (see my commit in dev branch: https://github.com/morpheus65535/bazarr/commit/74079bc445fdc906e6a9757a611c7262ed98a76c). Subzero use to take as granted that subtitles without language code have to be considered a the 1st desired language. Unfortunately, Bazarr doesn't have the concept of ordered desired language. I could probably add an option for this if single language is enabled but it doesn't make sense when multiple language are enabled.
