### ISSUE TITLE
Bazarr can't find too many movies/episodes when they are available in the subtitle website.

### ISSUE THREAD

**Issue by MrSmileir** [morpheus65535/bazarr#704]
Hi,

Bazarr is a great tool for me. but I have some problems with it. Bazarr can't find too many movies or Anime/Series episodes subtitles. they have a subtitle in the Subscene and need to download them manually!
my minimum score setting was about 60. but too many subs have not to score sometimes and I didn't get too many episodes/movies subs. so I set it to zero with upgrade feature to get better subs when available.
but after this change, still didn't get too many episodes, movies subtitles.

![2019 12 15 - 15 36 50](https://user-images.githubusercontent.com/17881816/70862625-f4524380-1f53-11ea-98a7-9766826d91ab.jpg)
![2019 12 15 - 15 37 03](https://user-images.githubusercontent.com/17881816/70862627-f74d3400-1f53-11ea-9fe8-bd524b79423b.jpg)
![2019 12 15 - 15 37 37](https://user-images.githubusercontent.com/17881816/70862629-f9af8e00-1f53-11ea-8993-fed80a5f092a.jpg)
![2019 12 15 - 15 38 01](https://user-images.githubusercontent.com/17881816/70862630-fae0bb00-1f53-11ea-875e-7eeddadd1499.jpg)

(Subscene)

**Software (please complete the following information):**
 - Bazarr Ver: 0.8.3.4
 - Radarr version: 0.2.0.1450
 - Sonarr version: 3.0.3.664
 - OS: Windows 10

logfile with the debug logging:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3964913/bazarr.log)

contacted with support in discord and he told me to create a Github issue.

**Comment by morpheus65535** [comment]
Those subtitles probably don't even have the required metadata to be considered by Bazarr(Subliminal). It could also be related to the stars in `The End of the F***ing World`.

**Comment by MrSmileir** [comment]
this one is an example. I have too many other series and movies with this problem.
also too many movies/anime/series have alternative names! it should know how to search for them.
like "ani ni tsukeru kusuri wa nai" it has a Japanese name and an English name: "please take my brother away"
some subtitle sites took it with the English name, some other (like Subscene) took Romaji name! and Bazarr can't find it at all!

about others without alternative names, look at pictures I attached, you would see "Beastars"! and Bazarr can't download subtitles for it!

**Comment by morpheus65535** [comment]
For the alternative titles, most of the provider should also search using them.

Please provide a debug log for Beastars. I'll look into it.

**Comment by MrSmileir** [comment]
please check the log file I attached in the first post.

**Comment by morpheus65535** [comment]
There's no Beastars episodes in your original log. That's the reason why I ask for a new one.

**Comment by MrSmileir** [comment]
[bazarr (2).log](https://github.com/morpheus65535/bazarr/files/3984849/bazarr.2.log)

**Comment by morpheus65535** [comment]
What anti-captcha provider are you using?

**Comment by morpheus65535** [comment]
I'll close this issue. Reopen it if required.

**Comment by MrSmileir** [comment]
sorry
some bad news came continuously and I forgot about this topic.
I'm using a static IP address to get less captcha problem, so not using any anti-captcha providers.
because of your answer, I created an anti-captcha.com account and tested it with. nothings new happened. logfile included.

[bazarr (3).log](https://github.com/morpheus65535/bazarr/files/4036736/bazarr.3.log)

**Comment by morpheus65535** [comment]
Are you using some sort of ad blocker like Pi-Hole? It seems you have connection problem to your providers and they got throttled to avoid hammering.
