### ISSUE TITLE
Bazarr uses all available RAM and crashes

### ISSUE THREAD

**Issue by Xe138** [morpheus65535/bazarr#705]
Bazarr quickly consumes all available RAM and crashes after a few hours in this state.  Bazarr had been running continuously for 1 week before the first occurrence.  Problem recurs immediately on restart.

1. Launch Bazarr
2. Wait

![Bazarr_memory](https://user-images.githubusercontent.com/50377201/71016003-82e4d300-20c2-11ea-942e-00c5c7b80d0f.PNG)

[bazarr.log](https://github.com/morpheus65535/bazarr/files/3974402/bazarr.log)

 - Bazarr: v 0.8.3.4
 - Radarr: v 0.2.0.1450
 - Sonarr: v 2.0.0.5338
 - OS: unRaid 6.8.0

**Comment by morpheus65535** [comment]
You probably have an issue with path mapping. Please tell me more about your environment (ie: Docker? config.ini file? etc.).

**Comment by Xe138** [comment]
Running the [linuxerver docker distribution](https://github.com/linuxserver/docker-bazarr)

Here is the build command:
`/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='bazarr' --net='bridge' --log-opt max-size='50m' --log-opt max-file='1' -e TZ="America/New_York" -e HOST_OS="Unraid" -e 'PUID'='99' -e 'PGID'='100' -p '6767:6767/tcp' -v '/mnt/user/media/Movies/':'/movies':'rw' -v '/mnt/user/media/Shows/':'/tv':'rw' -v '/mnt/user/appdata/bazarr':'/config':'rw' --memory=8G 'linuxserver/bazarr'`

I added the memory cap after the previous crashes to prevent it from taking down the whole system.

Additional Troubleshooting:
I found the Radarr database to be corrupted and restored to a previous version.  I don't know if this was causing the issue with bazarr or if it was caused by the memory crunch that bazarr created.  Bazarr has been running without issue for about 1 hour.  Continuing to monitor.

**Comment by darkmount** [comment]
I'm suffering the same issue. Started at around 2pm (CET) today for me. Received a warning my server was using high resources. Found bazarr consuming all available RAM (60GB).

[bazarr.log](https://gist.github.com/darkmount/02867aaa70e71e2b2eecfc67519bd091)

I too am using the linuxserver docker image. I have no updated any of this in weeks. My `docker-compose.yml` has nothing special about it 

Bazarr: v 0.8.3.4
Radarr: v 0.2.0.1450
Sonarr: v 3.0.3.652
OS: ubuntu 18.04 LTS

Could be unrelated (as I rarely access Bazarr) but I fired it up quickly to get the version number and noticed something odd in the UI. Movies aren't displaying their names...

<img width="1179" alt="bazarr-wanted-movies" src="https://user-images.githubusercontent.com/17112149/71022612-2bb22300-2101-11ea-8d82-fb04b1d958d1.png">

**Comment by Xe138** [comment]
Looks like there was a problem with TMDB last night that was returning blank strings: https://www.themoviedb.org/talk/5df84f8226dac1001755bc65

I thought this was a corrupted radarr database, but it looks like it was fine and has since been fixed on the TMDB side.  Could this have caused the issue with bazarr?  A problem with the handling of blank strings maybe?

**Comment by jasonla** [comment]
I'm also seeing the linuxserver image crash. I'll turn on debug logging to see if I can narrow it down.

**Comment by morpheus65535** [comment]
Thanks, I've deployed the latest image and I'll check also if I see the same behavior.

**Comment by morpheus65535** [comment]
I'm running for 3 hours now and I don't have any change in memory consumption. Although moving from `development` tag to `latest` tag had an impact on memory consumption (Python3:65MB vs Python2.7:110MB), I cannot see any memory leak.

In fact, here's my memory consumption over the last 2 weeks for my main instance that didn't get restarted unless a new image is available:

![image](https://user-images.githubusercontent.com/5130500/71046282-de848000-2105-11ea-993c-34042ce28ced.png)

I can't reproduce your issue... I would like to be able to reproduce it bu I can't :-/

**Comment by Xe138** [comment]
I was hoping this was caused by the TMDB API issue, which happened around the same time, but it looks like I got the same crash again yesterday around 18:00.  As shown below, it happens very quickly.  In this case I had the container's available memory capped at 8GB.

![bazarr_ram](https://user-images.githubusercontent.com/50377201/71114301-75504b80-219d-11ea-9745-69962b57b6bf.PNG)

Here are the full logs for the day (12/17): [bazarr_12_17.zip](https://github.com/morpheus65535/bazarr/files/3980086/bazarr_12_17.zip)

I experienced memory leaks starting at:
- 01:13:32
- 10:55:32
- 17:56:33

**Comment by morpheus65535** [comment]
Please provide your config.ini file but scramble username and password from it before. Don't alter path mapping.

**Comment by morpheus65535** [comment]
I've downloaded 400 Spanish subtitles in the last hour as a test and Bazarr memory usage changed from 101MB to 96MB. I don't see how you can get to that kind of memory usage...

**Comment by syrigx** [comment]
Same problem here using unraid/linuxserver image.

**Comment by morpheus65535** [comment]
Did you all tried the development image? `linuxserver/bazarr:development`

**Comment by fagenorn** [comment]
I can confirm using `linuxserver/bazarr:development` seems to have solved the ram usage issue.

**Comment by Xe138** [comment]
@morpheus65535 - here's my config.ini

[config.zip](https://github.com/morpheus65535/bazarr/files/3984866/config.zip)

**Comment by morpheus65535** [comment]
> @morpheus65535 - here's my config.ini
> 
> [config.zip](https://github.com/morpheus65535/bazarr/files/3984866/config.zip)
> 
> I have not tried the development branch yet. It's been running stable for the past 24 hours, but it's still using a lot of memory (~1GB).

Thanks, you should give a try to dev image.

**Comment by morpheus65535** [comment]
Do you guys search for specifics languages other than English? Do you have Forced subtitles =True or Both?

**Comment by fagenorn** [comment]
> 
> 
> Do you guys search for specifics languages other than English? Do you have Forced subtitles =True or Both?

![image](https://user-images.githubusercontent.com/18429405/71200417-4965c080-2298-11ea-9475-f44ca139c5f5.png)

**Comment by syrigx** [comment]
In my case the problem seems related to the recent TMDB issue. There is a blank movie in the list of wanted subtitles in bazarr, which corresponded to a blank movie in radarr. As soon as I manually searched for subtitles for movies, the ram leak happened. I tried both latest and development builds and the problem was identical. Even after I updated radarr's library, a single movie remained blank in bazarr. No problem when I manually searched for TV shows (I am using sonarr)

**Comment by Xe138** [comment]
> Do you guys search for specifics languages other than English? Do you have Forced subtitles =True or Both?

![Capture](https://user-images.githubusercontent.com/50377201/71206278-2aecce80-2272-11ea-8144-57637745d1b9.PNG)

**Comment by morpheus65535** [comment]
> In my case the problem seems related to the recent TMDB issue. There is a blank movie in the list of wanted subtitles in bazarr, which corresponded to a blank movie in radarr. As soon as I manually searched for subtitles for movies, the ram leak happened. I tried both latest and development builds and the problem was identical. Even after I updated radarr's library, a single movie remained blank in bazarr. No problem when I manually searched for TV shows (I am using sonarr)

I would really appreciate you send me your bazarr.db file on Discord in PM! I want to see what fields are blank and where does it get used and cause that memory leak. Thanks!

**Comment by syrigx** [comment]
I solved it by removing and re-adding the movie from radarr and bazarr picked up the movie with the full details. I didn't keep the previous db file. The problem was in the wanted subtitles section, where the movie name was blank. Disabling subtitle search for said item also fixed the problem

**Comment by Xe138** [comment]
I've been running the dev build for about 18 hours.  No leak and generally much lower memory usage.

![Capture](https://user-images.githubusercontent.com/50377201/71258659-c464c080-2304-11ea-8375-d03dbe9c2358.PNG)

**Comment by morpheus65535** [comment]
> I've been running the dev build for about 18 hours. No leak and generally much lower memory usage.
> 
> ![Capture](https://user-images.githubusercontent.com/50377201/71258659-c464c080-2304-11ea-8375-d03dbe9c2358.PNG)

Appreciate the feedback! Please keep me informed.

**Comment by animosity22** [comment]
I just noticed this today and saw the post as well. I run on Debian, no docker or anything else and will capture a bit more as I saw the process gobbling up all the memory:

![image](https://user-images.githubusercontent.com/5088712/71315268-a1cac880-2426-11ea-8fda-4f40851f8b2f.png)

It looks like something ran away on the Sonarr as my memory jumped up at 19:06

```
21/12/2019 19:08:29|WARNING |apscheduler.scheduler           |Execution of job "Update Series list from Sonarr (trigger: interval[0:01:00], next run at: 2019-12-21 19:08:25 EST)" skipped: maximum number of running instances reached (1)|
21/12/2019 19:11:43|WARNING |apscheduler.scheduler           |Execution of job "Update Series list from Sonarr (trigger: interval[0:01:00], next run at: 2019-12-21 19:09:25 EST)" skipped: maximum number of running instances reached (1)|
21/12/2019 19:11:43|WARNING |apscheduler.scheduler           |Execution of job "Sync episodes with Sonarr (trigger: interval[0:05:00], next run at: 2019-12-21 19:11:25 EST)" skipped: maximum number of running instances reached (1)|
```

The graph below, the yellow is Bazarr coming from netdata/grafana.

![image](https://user-images.githubusercontent.com/5088712/71315294-0128d880-2427-11ea-81d1-b05584989086.png)

**Comment by darkmount** [comment]
> It looks like something ran away on the Sonarr as my memory jumped up at 19:06

This is inline with timings in my [previous post and the log](https://github.com/morpheus65535/bazarr/issues/705#issuecomment-566683294).

> I would really appreciate you send me your bazarr.db file on Discord in PM!

I’ve yet to attempt fixing the issue due to holidays. I should be able to get my db file over to you if it’s still of use @morpheus65535 ?

**Comment by morpheus65535** [comment]
@animosity22 @darkmount are you guys running v0.8.4 from dev branch?

**Comment by animosity22** [comment]
I am not. I can switch over to test that later tonight as it seems to happen a few times a day.

**Comment by animosity22** [comment]
I flipped to 0.8.4 on the dev branch and changed to python3 instead of python2.

**Comment by darkmount** [comment]
> are you guys running v0.8.4 from dev branch?

I’m not. I’m running 0.8.3.4 from dev branch. Should I bump the container?

**Comment by morpheus65535** [comment]
> > are you guys running v0.8.4 from dev branch?
> 
> I’m not. I’m running 0.8.3.4 from dev branch. Should I bump the container?

Yes you should. In fact you should always keep it up to date with watchtower or ouroboros. That way you'll benefit of the daily fixes to dev branch.

**Comment by darkmount** [comment]
> Yes you should. In fact you should always keep it up to date with watchtower or ouroboros. That way you'll benefit of the daily fixes to dev branch.

Ok, will bump container and report back. Not sure I agree with running watchtower in a production server. Had it running for a while until it updated a load of images and broke things.

**Comment by animosity22** [comment]
No issues with memory after 24+ hours for me.

**Comment by animosity22** [comment]
Unfortunately, the issue popped up again this morning.

```
24/12/2019 08:17:12|INFO    |root                            |BAZARR Search is not active for this Movie /gmedia/Movies/The Town that Dreaded Sundown (2014)/The Town that Dreaded Sundown (2014).mkv Language: en:forced|
24/12/2019 08:17:12|INFO    |root                            |BAZARR Search is not active for this Movie /gmedia/Movies/The Quiet (2005)/The Quiet (2005).mp4 Language: en:forced|
24/12/2019 08:17:12|INFO    |root                            |BAZARR Search is not active for this Movie /gmedia/Movies/Teen Wolf (1985)/Teen Wolf (1985).mkv Language: en:forced|
24/12/2019 08:17:52|ERROR   |apscheduler.executors.default   |Job "Update Series list from Sonarr (trigger: interval[0:01:00], next run at: 2019-12-24 08:18:28 EST)" raised an exception|'Traceback (most recent call last):\n  File "/opt/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File "/opt/bazarr/bazarr/get_series.py", line 156, in update_series\n    list_missing_subtitles(no=added_series[\'sonarrSeriesId\'])\n  File "/opt/bazarr/bazarr/list_subtitles.py", line 202, in list_missing_subtitles\n    if episode_subtitles[\'subtitles\'] is not None:\nTypeError: string indices must be integers'|
24/12/2019 08:18:01|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:6767/bazarr/|
```

Which was around the same time monit restarted it as it started to run away:

```
Resource limit matched Service bazarr
                Date:        Tue, 24 Dec 2019 08:17:45
                Action:      restart
                Host:        gemini
                Description: total mem amount of 18.3 GB matches resource limit [total mem amount > 4.9 GB]
```

Anything you want me to turn on to help troubleshoot the issue?

**Comment by morpheus65535** [comment]
@animosity22 Thanks for reporting! I've added some logging for the next time it happen. It looks like your DB is returning a string instead of a result set... strange...

**Comment by animosity22** [comment]
I change over to debug logging and see if I get something.

```
Resource limit matched Service bazarr
                Date:        Tue, 24 Dec 2019 15:18:08
                Action:      restart
                Host:        gemini
                Description: total mem amount of 23.9 GB matches resource limit [total mem amount > 4.9 GB]
```

the logs have not much unfortunately.

```
24/12/2019 15:17:26|INFO    |root                            |BAZARR Search is not active for this Movie /gmedia/Movies/Take Shelter (2011)/Take Shelter (2011).mkv Language: en:forced|
24/12/2019 15:17:26|INFO    |root                            |BAZARR Search is not active for this Movie /gmedia/Movies/The Town that Dreaded Sundown (2014)/The Town that Dreaded Sundown (2014).mkv Language: en:forced|
24/12/2019 15:17:26|INFO    |root                            |BAZARR Search is not active for this Movie /gmedia/Movies/The Quiet (2005)/The Quiet (2005).mp4 Language: en:forced|
24/12/2019 15:17:26|INFO    |root                            |BAZARR Search is not active for this Movie /gmedia/Movies/Teen Wolf (1985)/Teen Wolf (1985).mkv Language: en:forced|
24/12/2019 15:18:45|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:6767/bazarr/|
24/12/2019 15:26:48|INFO    |root                            |Using opensubtitles again after 10 minutes, (disabled because: OpenSubtitlesError)|
```

**Comment by morpheus65535** [comment]
@animosity22 would it be possible to disable adaptive searching and confirm if the issue is still present?

**Comment by animosity22** [comment]
@morpheus65535  - yes, I have debug on true as well so if it happens again, I can hopefully give a better log.

**Comment by animosity22** [comment]
Same thing with adaptive off as well. I grabbed the last part of the debug log as well.


[debug.log.zip](https://github.com/morpheus65535/bazarr/files/4001026/debug.log.zip)

**Comment by morpheus65535** [comment]
Here's the last movie analyzed before getting crazy:

```
25/12/2019 13:49:18|DEBUG   |root                            |BAZARR Searching subtitles for this file: /gmedia/Movies/Little (2019)/Little (2019).mkv|
25/12/2019 13:49:18|DEBUG   |subzero.video                   |Parsing video: Little.2019.2160p.HDR.WEBRip.DTS-HD.MA.5.1.x265-BLASPHEMY.mkv, hints: {'title': '', 'type': 'movie'}|
25/12/2019 13:49:18|INFO    |subliminal_patch.core           |Determining basic video properties for 'Little.2019.2160p.HDR.WEBRip.DTS-HD.MA.5.1.x265-BLASPHEMY.mkv' in '/gmedia/Movies/Little (2019)'|
```

Something special with this movie?

@pannal you ever seen something like this with subliminal_patch?

**Comment by animosity22** [comment]
@morpheus65535  - Nothing I can tell. That movie has been there since 20-Sep in it's current state so I can't imagine what would change in that as the problem started ~7 days ago:

![image](https://user-images.githubusercontent.com/5088712/71494285-fb126d80-2813-11ea-9a2c-87c359b2ecef.png)

**Comment by pannal** [comment]
I've seen this before, exactly once. I wasn't able to detect what the issue is and the user (out of tens of thousands) never answered again.

I'm guessing this is in the detection side of things; might be the MKV video property detector.

Likely because SZ doesn't use that anymore and uses the Plex metadata for stream info, this never resurfaced again.

**Comment by animosity22** [comment]
Hmm, I had another item pop at 16;14 again and that seems to be the last thing scanned.

```
26/12/2019 16:14:10|INFO    |subliminal_patch.core           |<OpenSubtitlesSubtitle 'http://www.opensubtitles.org/en/subtitles/6812989/sid-,fHqLzJFG,Csc1ZRaOrRqlEOQ56/inferno-en' [en:forced:None]>: Score 1 is below min
_score (84)|
26/12/2019 16:14:10|INFO    |subliminal_patch.core           |Downloaded 0 subtitle(s)|
26/12/2019 16:14:10|DEBUG   |subliminal.core                 |Terminating initialized providers|
26/12/2019 16:14:10|INFO    |subliminal_patch.core           |Terminating provider opensubtitles|
26/12/2019 16:14:10|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): vip-api.opensubtitles.org:443|
26/12/2019 16:14:10|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on vip-api.opensubtitles.org|
26/12/2019 16:14:10|DEBUG   |urllib3.connectionpool          |https://vip-api.opensubtitles.org:443 "POST /xml-rpc HTTP/1.1" 200 171|
26/12/2019 16:14:10|DEBUG   |root                            |BAZARR No Subtitles were found for this file: /gmedia/Movies/Missing Link (2019)/Missing Link (2019).mkv|
26/12/2019 16:14:10|DEBUG   |sqlite3worker                   |execute: SELECT path, missing_subtitles, radarrId, hearing_impaired, sceneName, failedAttempts, title, forced FROM table_movies WHERE path = ? AND missing_su
btitles != '[]', ('/gmedia/Movies/Little (2019)/Little (2019).mkv',)|
26/12/2019 16:14:10|DEBUG   |sqlite3worker                   |Sleeping: 0.001 8aaf50c5-e6a4-4199-83e0-d12bbd61792f|
26/12/2019 16:14:10|DEBUG   |sqlite3worker                   |sql_queue: 0|
26/12/2019 16:14:10|DEBUG   |sqlite3worker                   |run: SELECT path, missing_subtitles, radarrId, hearing_impaired, sceneName, failedAttempts, title, forced FROM table_movies WHERE path = ? AND missing_subtit
les != '[]', ('/gmedia/Movies/Little (2019)/Little (2019).mkv',)|
26/12/2019 16:14:10|DEBUG   |sqlite3worker                   |run: commit|
26/12/2019 16:14:10|DEBUG   |sqlite3worker                   |execute: UPDATE table_movies SET failedAttempts=? WHERE radarrId=?, ("[['en:forced', 1566126468.528789]]", 3278)|
26/12/2019 16:14:10|DEBUG   |sqlite3worker                   |Sleeping: 0.001 1ccd54eb-90a3-429a-8d84-e30201162e49|
26/12/2019 16:14:10|DEBUG   |sqlite3worker                   |sql_queue: 0|
26/12/2019 16:14:10|DEBUG   |sqlite3worker                   |run: UPDATE table_movies SET failedAttempts=? WHERE radarrId=?, ("[['en:forced', 1566126468.528789]]", 3278)|
26/12/2019 16:14:10|DEBUG   |sqlite3worker                   |run: commit|
26/12/2019 16:14:10|DEBUG   |root                            |BAZARR Searching subtitles for this file: /gmedia/Movies/Little (2019)/Little (2019).mkv|
26/12/2019 16:14:10|DEBUG   |subzero.video                   |Parsing video: Little.2019.2160p.HDR.WEBRip.DTS-HD.MA.5.1.x265-BLASPHEMY.mkv, hints: {'title': '', 'type': 'movie'}|
26/12/2019 16:14:10|INFO    |subliminal_patch.core           |Determining basic video properties for 'Little.2019.2160p.HDR.WEBRip.DTS-HD.MA.5.1.x265-BLASPHEMY.mkv' in '/gmedia/Movies/Little (2019)'|
26/12/2019 16:14:12|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): 127.***.***.***:8989|
26/12/2019 16:14:12|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on 127.***.***.***|
26/12/2019 16:14:12|DEBUG   |urllib3.connectionpool          |http://127.***.***.***:8989 "GET /sonarr/api/system/status?apikey=********d5 HTTP/1.1" 200 None|
26/12/2019 16:14:12|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): 127.***.***.***:7878|
26/12/2019 16:14:12|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on 127.***.***.***|
26/12/2019 16:14:12|DEBUG   |urllib3.connectionpool          |http://127.***.***.***:7878 "GET /radarr/api/system/status?apikey=********2c HTTP/1.1" 200 None|
26/12/2019 16:14:12|DEBUG   |sqlite3worker                   |execute: SELECT COUNT(*) as count FROM table_episodes WHERE missing_subtitles != '[]', None|
26/12/2019 16:14:12|DEBUG   |sqlite3worker                   |Sleeping: 0.001 8938cd5d-f7c9-45d7-8531-4133c52b8cdd|
26/12/2019 16:14:12|DEBUG   |sqlite3worker                   |sql_queue: 0|
26/12/2019 16:14:12|DEBUG   |sqlite3worker                   |Sleeping: 0.002 8938cd5d-f7c9-45d7-8531-4133c52b8cdd|
26/12/2019 16:14:12|DEBUG   |sqlite3worker                   |run: SELECT COUNT(*) as count FROM table_episodes WHERE missing_subtitles != '[]', []|
```

**Comment by animosity22** [comment]
The movie Little (2019) does not show up in Bazarr when I try to search for it either:

![image](https://user-images.githubusercontent.com/5088712/71494596-3dd54500-2816-11ea-8647-9412355eef2c.png)

**Comment by morpheus65535** [comment]
@animosity22 it's normal that you can't find it in Bazarr as it cannot be indexed completely.

Could this movie be corrupted? Bazarr's master branch haven't changed since November 25th so nothing new on our side could have caused this issue 7 days ago... :-/

**Comment by animosity22** [comment]
mediainfo and ffprobe report information back and I can play it via Plex too. Let me dig around a bit more and see if removing that helps.

**Comment by morpheus65535** [comment]
Thanks. Of course, crashing and using all memory is not acceptable but if we can isolate this to a single movie, I'll be able to try to reproduce it and fix it.

**Comment by darkmount** [comment]
I also have this movie which, like animosity, has been floating around for quite a while. Different release though. I’ll enable debug logs and see if I can provide anything helpful.

**Comment by animosity22** [comment]
The error definitely went away as I removed Little and re-added it. I also had a few movies in Radarr that weren't showing up correctly.

Since I fixed that, it can scan that movie and it works fine.

I can also see the movie properly in Bazarr:

![image](https://user-images.githubusercontent.com/5088712/71528747-6fe6b580-28af-11ea-901a-b6600e029929.png)

As it shows up at the bottom now. So my assumption would be something wasn't quite right in Radarr and that was causing the issue. Since I grabbed the issue in debug, not sure what else to do in terms of sharing information to help pinpoint the problem. I do have dailies backups going for all my stuff so I can recreate the issue if there is anything else that would be helpful.

**Comment by morpheus65535** [comment]
@animosity22 can you send me your bazarr.db from yesterday on Discord in PM?

**Comment by morpheus65535** [comment]
@pannal The only thing that I see is that parse_video() hints get fed with an empty string as title. Could it make guessit run into some trouble?

It never get further than this:
https://github.com/morpheus65535/bazarr/blob/376d57e4e7abb1bd34e885bc13d9b77200637030/libs/subliminal_patch/core.py#L521

**Comment by darkmount** [comment]
So it seems the bazarr container on my server hasn’t tripped up since I bumped the docker image to v8.4 development version. It’s been running solid for around 72hrs now averaging 170mb RAM. 🤷‍♂

**Comment by animosity22** [comment]
So since I fixed Radarr, I've been 3 days with no issues so I'd assume it was a Radarr item with that movie.
