### ISSUE TITLE
Subdivx Parse Error

### ISSUE THREAD

**Issue by luisvillalobos528** [morpheus65535/bazarr#706]
Hi I been getting some error on subdivx provdier for like a week I would appreciate if you could look into it 

subdivx | ParseResponseError

I checked the logs and there's not even 1 mention of the error or anything let me know how can I help..

**Comment by morpheus65535** [comment]
I've just download an Italian subtitles from subdivx without any issue.

You can enable debug logging in settings and reproduce the issue. Provide the debug log and I'll look into it.

**Comment by morpheus65535** [comment]
Is it still an issue?
