### ISSUE TITLE
Add release date in Releases tab (under System)

### ISSUE THREAD

**Issue by barneh** [morpheus65535/bazarr#708]
**Describe the bug**
(This is not a bug, but a feature)
It would be nice if the release date had been added to the Release

**To Reproduce**
1. Go to 'System'
2. Click on 'Releases'

Both Sonarr and Radarr has this and it's nice to know if and when Bazarr has been updated to.

**Expected behavior**
See the date when the Bazarr has been updated.

**Screenshots**
In Radarr:
![image](https://user-images.githubusercontent.com/16772925/71091783-19d68b80-21a6-11ea-915c-2aec3ffcd7b9.png)

**Comment by morpheus65535** [comment]
Good idea but please do it by following #525.
