### ISSUE TITLE
Can't sync from Sonarr

### ISSUE THREAD

**Issue by faulander** [morpheus65535/bazarr#71]
After a needed reinstall, i cannot sync from Sonarr anymore. In the logs i only get:
Execution of job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-05-27 08:19:09 CEST)" skipped: maximum number of running instances reached (1)

What's the problem?

Sonarr: Version 2.0.0.5212
Bazarr:  Version: 0.4.1

**Comment by faulander** [comment]
additional info: I changed the Sonarr API Key (to make sure) and now i get:
'Traceback (most recent call last):\n File "/usr/lib/python2.7/site-packages/apscheduler/executors/base.py", line 125, in run_job\n retval = job.func(*job.args, **job.kwargs)\n File "/bazarr/get_series.py", line 20, in update_series\n get_profile_list()\n File "/bazarr/get_series.py", line 87, in get_profile_list\n profiles_list.append([profile[\'id\'], profile[\'language\'].capitalize()])\nTypeError: string indices must be integers'

**Comment by faulander** [comment]
and now i am back to the first error:
![2018-05-27 09_56_46-window](https://user-images.githubusercontent.com/38588197/40583722-5cfc709c-6194-11e8-8495-eb6ca42357ec.png)

**Comment by morpheus65535** [comment]
Sorry for the delay. It looks like Bazarr is not able to connect to Sonarr API. Could be a metwork related problem. Have you enabled Sonarr authentication?

**Comment by faulander** [comment]
No stacktrace, just:
![2018-05-30 18_41_01-window](https://user-images.githubusercontent.com/38588197/40734557-1101494a-6439-11e8-9af9-c53d27951f92.png)

and the exception:
Execution of job "Update series list from Sonarr (trigger: interval[0:01:00], next run at: 2018-05-30 10:49:09 CEST)" skipped: maximum number of running instances reached (1)

this was the last one for today, 8 hours ago ...

**Comment by morpheus65535** [comment]
Look like it's been taking more than a minute to get series list from Sonarr and process it to DB... Unless you got 10000 series, it's highly improbable.

Anyway, for the last 8 hours, this task is running smootly every minute. I wouldn't be scared if it doesn't happen again.

I suggest we close this one and you open another one if you run into this or another problem. Is this ok for you?

**Comment by faulander** [comment]
no, it doesn't sync the series!
Let me give you some details

**Comment by faulander** [comment]
![2018-05-30 18_48_14-](https://user-images.githubusercontent.com/38588197/40734950-303beada-643a-11e8-9715-998790fee1e4.png)

It didn't write any Logfiles for today, although it's running since a while - check docker ps

**Comment by morpheus65535** [comment]
The logfile for the current day is bazarr.log

**Comment by morpheus65535** [comment]
You wont see any mention of series updating process in log if everything went smoothly. Add a fake show to Sonarr and you should get it in the next minute.

**Comment by faulander** [comment]
I don't know how to give you details without mentioning shows.
Sonarr downloaded the red woman in a cape, season 02 episode 07.
it doesn't show up in bazarr.

**Comment by faulander** [comment]
aaaaaah, i got it!
It's just missing in the history in Bazarr.
When i check the detail page of the show, it's correct.

**Comment by morpheus65535** [comment]
lol ok. It should be in Bazarr five minutes after a file have been saved on this for this episode.

**Comment by morpheus65535** [comment]
History in Bazarr show subtitles downloaded or deleted from the web interface.

**Comment by faulander** [comment]
nope, it's been downloaded at: 
![2018-05-30 18_57_01-window](https://user-images.githubusercontent.com/38588197/40735375-593044f8-643b-11e8-8d7c-5ab4d655159b.png)

**Comment by faulander** [comment]
So, 10:52 - but doesn't show up in Bazarr History, although it shows it's subtitle in the overview page of the show itself.

**Comment by morpheus65535** [comment]
That's the Sonarr history. You won't see episode download in Bazarr history if Bazarr haven't downloaded a subtitles for it. If you see a subtitles for it in series page it's because it is internal to the mkv (hint: there's no "x" on it to delete it).

**Comment by faulander** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaah, i am SO dumb!
of course you are absolutely right. I though about internal subtitles, but i thought i read somewhere that you have no means to see if it has subtitles in it 👍 

thanks for your support - as always. I am sorry for stealing your time. where can i send some money to? It's an awesome product that saves me alot of time.

**Comment by faulander** [comment]
and i learned alot about bazarr and python today - thanks for that aswell :)

**Comment by morpheus65535** [comment]
I got no way to detect if a subtitles is hearign impaired or not. That's propably what you've read.

For the money, give it to a good cause! I don't accept donation, Bazarr is my way of giving back to the community for the good tools I've used over years.
