### ISSUE TITLE
ValueError: Path does not exist

### ISSUE THREAD

**Issue by sandro09021982** [morpheus65535/bazarr#710]
I have an AS1002T NAS. In it I installed and configured Sonarr. I installed Bazarr and set it up with the paths /volume1/TV Series/ and /tv/. Bazarr can't find the path and doesn't download the subtitles. I also tried to put the paths according to the information in the Asustor store: /volume1/Docker/Sonarr/tv/ and /tv/. The same happens.

Message
BAZARR Error trying to get video information for this file: /volume1/TV Series/Swamp Thing (2019)/Season 01/Swamp.Thing.S01E10.WEBRip.x264-ION10.mp4
Exception
Traceback (most recent call last):
 File "/app/bazarr/bazarr/get_subtitle.py", line 65, in get_video
  hash_from=hash_from)
 File "/app/bazarr/bazarr/../libs/subzero/video.py", line 60, in parse_video
  skip_hashing=skip_hashing, hash_from=hash_from)
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 488, in scan_video
  raise ValueError(\Path does not exist\)
ValueError: Path does not exist

 - Bazarr version: v 0.8.3.4
 - Radarr version: none
 - Sonarr version: v 2.0.05338
 - OS: ADM 3.4.5.RBJ3

**Comment by morpheus65535** [comment]
As this is a configuration support request, I suggest you get to Discord support channel to get live support. Github Issues are for bug reporting. Thanks.
