### ISSUE TITLE
Memory leak on Unraid Docker

### ISSUE THREAD

**Issue by Mizerka** [morpheus65535/bazarr#713]
I've started encrypting some disks (xfs) on my unraid array, and noticed that bazarr would cause a memory during scheduled jobs somewhere, causing it to eat up all memory it could (over 90gb in my case) and completely lock up all other services.

link to unraid thread I've opened with logs and such, for now keeping it bazarr off but would like to continue using it.

https://forums.unraid.net/topic/86291-strange-100-cpu-and-ram/

**Comment by morpheus65535** [comment]
Duplicate #705
