### ISSUE TITLE
Update Bazarr from source on Github raised an exception

### ISSUE THREAD

**Issue by pathed1969** [morpheus65535/bazarr#714]
**Describe the bug**
When the update task runs it generates the following error:

Traceback (most recent call last):
 File "b:\\bazarr\\bazarr\\../libs/apscheduler\\executors\\base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "b:\\bazarr\\bazarr\\check_update.py", line 43, in check_and_apply_update
  g.fetch(\origin\)
 File "b:\\bazarr\\bazarr\\../libs/git\\cmd.py", line 548, in
  return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
 File "b:\\bazarr\\bazarr\\../libs/git\\cmd.py", line 1014, in _call_process
  return self.execute(call, **exec_kwargs)
 File "b:\\bazarr\\bazarr\\../libs/git\\cmd.py", line 825, in execute
  raise GitCommandError(command, status, stderr_value, stdout_value)
GitCommandError: Cmd(\git\) failed due to: exit code(128)
 cmdline: git fetch origin
 **stderr: \fatal: \origin\ does not appear to be a git repository**
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.\

**To Reproduce**
1. Go to 'Tasks'
2. Click on 'Update Bazarr from source on Github'
3. See error

**Expected behavior**
The update should run without any errors.

**Software (please complete the following information):**
Bazarr Version: 0.8.3.4
Sonarr Version: 3.0.3.668
Radarr Version: 3.0.0.2325
Operating System: Windows-10-10.0.18362
Python Version: 2.7.15

**Additional context**
Downloaded and unpacked the sourcecode from 'https://github.com/bazarr/bazarr.github.io/releases/latest/download/bazarr.zip'.
Running the application using 'python B:\Bazarr\bazarr.py'.

**Comment by halali** [comment]
Please follow instructions how to install bazarr from source on wiki, this error you got because you didn't clone it by git.

**Comment by pathed1969** [comment]
OK, followed the guide on installing from source and now if works!
Thanks!
