### ISSUE TITLE
Windows Network Drive Path issue

### ISSUE THREAD

**Issue by gamespy5** [morpheus65535/bazarr#715]
I am using Radarr/Sonarr on the same Windows server as Bazarr, but I get invalid path issue when attempting to have bazarr reach to the media.

Sonarr path: `Z:\TV Shows`

I have tried to have bazarr use the same path and `\TV Shows` and `\TV Shows\` with no success.

**Comment by morpheus65535** [comment]
Mapped drive are unsupported. Please see the wiki and Discord support channel if required.
