### ISSUE TITLE
Job "Update Series list from Sonarr (trigger: interval[0:01:00], next run at: 2019-12-28 19:53:44 CET)" raised an exception

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#719]
**Describe the bug**
Job "Update Series list from Sonarr (trigger: interval[0:01:00], next run at: 2019-12-28 19:53:44 CET)" raised an exception
```
Traceback (most recent call last):
 File "/root/scripts/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/root/scripts/bazarr/bazarr/get_series.py", line 56, in update_series
  current_shows_db_list = [x[\sonarrSeriesId\] for x in current_shows_db]
TypeError: string indices must be integers, not str
```

**Software:**
 - Bazarr Ver. 0.8.4 
 - Python 3.6.8
 - Linux

**Comment by morpheus65535** [comment]
Please provide your bazarr.db. Looks like something is corrupted.

**Comment by ngosang** [comment]
Well, I restarted Bazarr several times and it's running for several days. I can't reproduce this bug anymore.
