### ISSUE TITLE
minor/cosmetic improvement: the menu hover is too close to the search bar

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#720]
The menu hover is too close to the search bar. let a bit more space. Remove a bit of padding and add margin-botom.

![image](https://user-images.githubusercontent.com/10577978/71549017-db677a80-29b6-11ea-8d83-d08d293e0133.png)

**Comment by morpheus65535** [comment]
Thank you for reporting this one. I won't fix it as we are in the process of reworking the whole interface.
