### ISSUE TITLE
Error when installing python requirements in Windows 10

### ISSUE THREAD

**Issue by PadreToio** [morpheus65535/bazarr#721]
**Describe the bug**
I have installed Python 3.8 in C:\Python38. When I try to install bazarr running from source it gives an error in the step of install python requirements.

**To Reproduce**
1. Python3.8 installed in C:\Python38. I have checked the box PATH in the installation windows.
2. Create a bazarr folder in C:\bazarr
3. In C:\bazarr open a Poweshell console
4. Run git clone https://github.com/morpheus65535/bazarr.git with sucess.
5. cd bazarr
6. In cd:\bazarr\bazarr install Python requirements using pip install -r requirements.txt
7. It gives an error! 

**Expected behavior**
I expected to work the same as Python 2.7 that I have previously used.

**Screenshots**
![download](https://user-images.githubusercontent.com/13244203/71563608-69606580-2a8a-11ea-90d7-3265f14f8b6a.png)

**Software (please complete the following information):**
 - Bazarr: can't install
 - Radarr version latest
 - Sonarr version latest
 - OS: Windows 10

**Additional context**
I have previously used bazarr using Python 2.7. I think the problem is because of Python 3.8 and something about directories. Because I have installed Python 3.8 in C:\Python38 and in the error description it says something about c:\\users.........

**Comment by morpheus65535** [comment]
Should be fixed now. Just `git pull` from bazarr directory to get the fix and restart the requirements.txt installation.

**Comment by PadreToio** [comment]
Thank you! Fixed.
