### ISSUE TITLE
Version 0.8.4 - Timezone Offset Error

### ISSUE THREAD

**Issue by ricardonolan** [morpheus65535/bazarr#723]
`Bazaar [0.8.4]`

```
/opt/bazarr$ sudo dpkg-reconfigure tzdata

Current default time zone: 'Europe/Dublin'
Local time is now:      Mon Dec 30 07:09:12 GMT 2019.
Universal Time is now:  Mon Dec 30 07:09:12 UTC 2019.
```

```
/opt/bazarr$ cat /etc/timezone
Europe/Dublin
```

```
/opt/bazarr$ python bazarr.py
Bazarr starting...
Traceback (most recent call last):
  File "bazarr/main.py", line 63, in <module>
    from scheduler import *
  File "/opt/bazarr/bazarr/scheduler.py", line 67, in <module>
    if str(get_localzone()) == "local":
  File "/opt/bazarr/bazarr/../libs/tzlocal/unix.py", line 165, in get_localzone
    _cache_tz = _get_localzone()
  File "/opt/bazarr/bazarr/../libs/tzlocal/unix.py", line 90, in _get_localzone
    utils.assert_tz_offset(tz)
  File "/opt/bazarr/bazarr/../libs/tzlocal/utils.py", line 38, in assert_tz_offset
    raise ValueError(msg)
ValueError: Timezone offset does not match system offset: 0 != 3600. Please, check your config files.
```

Above error present on master and development branches

**Comment by morpheus65535** [comment]
That's a known issue in an upstream library: https://github.com/regebro/tzlocal/issues/80

I'll check again with him for an ETA to get this fixed.

**Comment by ricardonolan** [comment]
Thanks for that.

**Comment by ricardonolan** [comment]
Is there any kind of workaround that can be used?

**Comment by ricardonolan** [comment]
Ok, for anyone interested, workaround is to set timezone to Europe/Lisbon, which has basically the same timezone.

**Comment by carlan** [comment]
> Ok, for anyone interested, workaround is to set timezone to Europe/Lisbon, which has basically the same timezone.

I was having the same issue this morning on same timezone as yours. I selected Belfast just for the sake of proximity and all wen't well.
Thanks!

**Comment by morpheus65535** [comment]
I've just pushed a dirty fix to dev branch (commented out the problematic check in tzlocal) if someone want to test it.
