### ISSUE TITLE
Bazaar scheduled tasks CRIPPLING system

### ISSUE THREAD

**Issue by daninfuchs** [morpheus65535/bazarr#725]
Hi there, I just installed Bazarr and I like it. Ish. So far. I'm dealing with one critical issue that's already caused server-wide downtime for me. Here's some points to consider;

 - I don't mean to sound snarky, I'm a bit autistic - sorry.
 - Some people (like myself) have REALLY BIG libraries
 - You are polling Sonarr for a series list every 60 seconds
 - You are syncing episodes(!!) with Sonarr every five minutes
 - You are updating the movie list from Radarr every five minutes
 - The latter two occur both at the same time
 - All of these occur on-the-minute, so all three of those tasks run in parallel, periodically
 - Some people (like myself) store their files on _networked filesystem_
 - As libraries grow larger, full-library polling becomes exponentially less efficient due to a smaller percentage of actual change vs new content added/updated
 - Sonarr and Radarr have built-in features to provide immediate notification of new/updated content, which makes polling unnecessary in the first place (though it still makes sense on a daily/weekly -- NOT once-per-minute -- schedule as a failsafe)

This is continually causing a cascading problem in my stack - just for the record, we're talking a 10GBit fiber link between two rack servers, one a (moderately busy) 24-core Xeon w/ 72GB of RAM, the other running a 72TB fileserver that's nearly full.

What I'm seeing:
_Incredible_ amounts of network and Disk IO spiking when hard-timed tasks that spawn and seemingly overlap (because they don't have time to finish between loops when the rig(s) is/are under high load) which results in the system running extra instances over and over and over and over and over until it starts bringing random services down and someone notices the server room is A) HOT, and B) LOUD.

What I would like to see:
 1) CONFIGURABLE timer durations for all tasks -- Lowest effort, but at least I can use it. For now I've got to just shut it off and stop using it.
 2) Notification-triggered action, via built-in Connect (ie, Webhook) integration w/ Sonarr/Radar/etc -- This feature was actually DESIGNED for interaction with services like this, just FYI, and is literally _orders of magnitude_ more efficient than even a pitiful hundred movies and thousand TV shows, let alone lists four and five digits long, respectively.
 3) Bare minimum, timers that pause countdown while they run, and only resume after their tasks are actually complete. Consider, a timer starts a task every five minutes. The task takes ten minutes to finish. The load it represents slows down all other tasks on the system by a percentage that increases exponentially with parallel task loads. How many copies of this task will spawn before the system comes down?

**Comment by morpheus65535** [comment]
Thank you for your feedback. I'll try to cover everything here:
- Series, episodes and movies sync with ***arr are only API call that only trigger disk when new item is added to index existing subtitles. Those 3 tasks, run in parallel, should complete in less than 5 seconds even with large libraries.
- Every other tasks frequency are configurable.
- The task manager doesn't allow 2 or more instance of the same tasks. If a new instance is planned while the previous isn't completed, it skip this planned execution and try again the next time.
- Webhook in Sonarr doesn't trigger when series are added. That doesn't suits our need.
- Before working for the last 3 months on porting all Bazarr and it's dependencies to Python 3, I was working to integrate with Sonarr/Radarr SignalR feed. I've made some progress with Sonarr 3 and Radarr 2 but cannot get it to work with previous version. I should start working back on that in the next weeks but don'T expect this to be in production until a couple of months.

In the meantime, I suggest you either accept the footprint of Bazarr or stop using it waiting for this new feature if it's unlivable for you.

**Comment by daninfuchs** [comment]
Thanks for your prompt reply. Reviewing your replies, clearly I've made some incorrect deductions on a few items, however I will counter with the following;

To your first point (Sorry, this one is longest but I'm reproducing things and this is where the detail needs to go) - Maybe they *should* complete in less than 5 seconds even with large libraries, but here's what I did just now;

- I started Bazaar again and let it settle, then (after "Update Series List from Sonarr" ran on its schedule) I asked it to run -only- the "Sync eposides with Sonarr" task, the first completion of that task (with only 10 hours of activity since Bazaar had been online) took the task four minutes, during which the 60-second timer triggered three times, taking ten to twelve seconds to complete each time.
- It took said task so long to complete that the Next Execution now says "in a minute" - the next time it ("Sync episodes with Sonarr") ran (typing as it runs, actually) it ran for ... three minutes, upon which the Next Execution says two minutes.

It clearly does not take "five seconds" to execute this task _on my system_, for whatever reason, even when started solo, NOT in parallel with the other two. This may be due to my remote filesystem issue, perhaps there's heavy load in place but that's kind of my point - cleanroom numbers don't matter. As a side note however, this does provide a workaround. I've manually triggered one task, offsetting its execution repeat time. At least with the three tasks not running in parallel, they all seem to get time to finish. I'll just have to make sure I do that every time Bazaar restarts, for now.


Addressing the second point - Seems like it wouldn't be so hard to add three more then, thank you for helping make my point, but I'm not complaining about the other tasks because they have initially-sane repeat values which I can change to what I consider sane.

Third - you stated that the tasks do not run concurrent instances of themselves, and I will agree to that. I mistakenly thought it was because I had several (six) pop-ups in the corner of my browswer window indicating progress, I'll accept that this was likely just due to a rendering error in Chrome, it seems to not handle multiple of those well. The "Update Series list from Sonarr" pop-up sometimes shows with the other ones' text if updates come in very quickly from Bazaar. Disregard that complaint. What I _was_ seeing though, were back-to-back runs, or runs so nearly back-to-back that they were almost constant.

Fourth - I was unaware of the new series notification limitation, but consider; Upon processing (grabbing/downloading/renaming) an episode OF a new series, Sonarr will tell you, wether you knew it was a series being monitored or not. Upon seeing an episode of a Bazaar-unregistered series, either act accordingly (if you already have all the other information you need) OR poll the API for either _just that series_, or if you must, the full sync task _at that time, after you find out it's required_. Or, keep that _one lightweight_ polling task and use the notifications for the other two heavyweights, eliminating 80% of the load issues. Also worthy of mention, I don't think _anybody_ (even me) is going to A) add a series every 60 seconds, to make it worth asking about every 60 seconds, OR B) CARE if Bazaar doesn't find out about a new series for five (ten, fifteen, thirty) minutes _while it actually downloads/imports_. Still though, that one task is not the greatest concern.

Fifth - I appreciate your work and the software is honestly pretty fantastic. It's a niche piece that has the potential to become a fully core piece of my software stack, filling a void that I've literally fielded complaints about recently from friends and family. This is partially why I care enough to be here, it's something I need and I frankly feel _many_ media stacks out there need it too.

For what it's worth, I'd be more than happy to burn some time helping out! I'm a moderately experienced code monkey, I've been involved with a few firmware-level projects and wrote an entire hardware-to-host interface app for one of them that was extraordinarily well-received by the community, and I have a lot of free time. If you so much as tell me what your development environment is on a base level, I'll set up and contribute. Or I'll just go away, if I rub you the wrong way.

Again, I apologize if I've come off brash or arrogant or whatever, I don't communicate so well. My intentions are positive. Thank you for your time.

**Comment by morpheus65535** [comment]
Sorry for the delay answering your post, Christmas time can get very busy... ;-)

We are always happy to have help and we'll be happy to review your PR. If you want to talk about it, don't hesitate to join me on Discord and I'll be able to give you more information on our stack that is currently evolving to Python 3.8, Flask, Jinja2, SQLite, etc.
