### ISSUE TITLE
addic7ed provider

### ISSUE THREAD

**Issue by Ashyni** [morpheus65535/bazarr#729]
Hello,

I'm having no results for the TV show 'Marvel's Cloak & Dagger' with addic7ed.
Logs:
Trying show ids: {'marvels cloak & dagger'}
Trying show ids: {'cloak & dagger'}
Trying manually give indeed no results for this request.

I'm having proper results with `marvel's cloak and dagger`, `marvel's cloak dagger`.
Ignoring `&` or replace it by `and` give good results, keep `marvel's` untouched give the best result too, `marvels` don't work for any marvel's tv show and `marvel s` is less accurate.

Another TV show that's give me trouble is Shameless (US),
Logs:
Trying show ids: {'shameless'}
`shameless us` and `shameless (us)` give the proper result, but (US) doesn't seems to be include in the query.

Another thing more featured oriented, i see a lot of French subs on addic7ed.com with bad release name, like AMZN.WEB-DL instead of NTb or NTG, it would be nice to have an option to match a part of the scene name instead of just the release group.

**Comment by morpheus65535** [comment]
@pannal Do you have the same issue with Sub-Zero? Look like an issue with subliminal_patch addic7ed provider.

**Comment by morpheus65535** [comment]
Is it still an issue?

**Comment by Ashyni** [comment]
Hello, with bazarr 0.8.4.1, yes.

Shameless instead of Shameless US, and no result for Marvel's cloak & dagger.

**Comment by morpheus65535** [comment]
Can you provide a debug log (emptied first) reproducing the issue while searching?

**Comment by Ashyni** [comment]
Here for Shameless US: https://pastebin.com/wtrSPQ82
and Marvel's Cloak and dagger: https://pastebin.com/fBftv65i

**Comment by morpheus65535** [comment]
I've been able to fix the Shameless issue in dev branch. As for Marvel Cloak & Dagger, I have no idea what is the issue. Something strange happening in subliminal_patch... :-/

**Comment by Ashyni** [comment]
Hey,
Thanks for the partial fix, as for marvel's, something in the sanitazition process to keep `'` or replace it by a space could be enough.
I don't know much about programming, want to help more, but ...

**Comment by morpheus65535** [comment]
Thanks for the feedback. Of course this is the first thing that I looked up but didn't found anything related. Maybe @pannal could help on this one.

**Comment by morpheus65535** [comment]
Marvel's Cloak & Dagger should be fixed in dev branch. Could you test it please?

**Comment by Ashyni** [comment]
I wait for linuxserver build to update and i keep you posted

**Comment by Ashyni** [comment]
New UI, awesome !!

Tested successfully, Shameless (US), Marvel's Cloak & Dagger, Dynasty (2017), The Flash (2014), Marvel's Runaways.

Nice work.

**Comment by morpheus65535** [comment]
Thanks for the feedback!
