### ISSUE TITLE
path encoding issue when deleting sub

### ISSUE THREAD

**Issue by Ashyni** [morpheus65535/bazarr#730]
Hello,

Since 0.8.4, deleting sub or auto/manual search per episode give an error related to the path:
Traceback (most recent call last): File "/app/bazarr/bazarr/main.py", line 1759, in remove_subtitles os.remove(subtitlesPath)FileNotFoundError: [Errno 2] No such file or directory: /data/TÃ©️lÃ©️chargements/0-Sonarr/Hawaii Five-0 (2010)/Season 9/Hawaii.Five-0.S09E25.720p.AMZN.WEB-DL.DDP5.1.H.264-AJP69.fr.srt

Everything else is working fine like 'downloads wanted subs' or 'downloads missing subs' for the entire tv show, subs are find and no error.

system and container report uft-8 as locale.
docker: linuxserver/bazarr:latest

**Comment by morpheus65535** [comment]
I've pushed a fix to dev branch. Can you test if it fix your issue please?

**Comment by Ashyni** [comment]
Delete sub, Manual/Auto search per episode works like a charm, no errors.

It's fixed, thanks.

Test with linuxserver/bazarr:7a50123e-ls68 (development).

**Comment by Ashyni** [comment]
But now the settings are not save correctly, just see that now, every true/false fall back to a default value.

**Comment by morpheus65535** [comment]
Thanks I've pushed another fix to correct my mistakes. Sorry for that.

**Comment by Ashyni** [comment]
All good, thanks again.
