### ISSUE TITLE
Bazarr not actively searching for subtitles

### ISSUE THREAD

**Issue by Rubeast** [morpheus65535/bazarr#732]
**Describe the bug**
My Bazarr works pretty well. I have linked it with Sonarr and Radarr and all my shows and movies are visible. The language is set for them all and they appear in the wanted list.
I have multiple providers, I have an anti captcha account, I have Opensubtitles VIP and have configured multiple providers.

I do have a really large list. There are > 30.000 missing episodes and 3700 missing movies.
When I go to a movie or episode and press the search button there, it finds the subtitle without problem. So I know it's not a naming issue.

The problem is that he just does not start to search.
For series he often will start downloading a show's subtitle. But then for multiple hours nothing. There are times that it won't download a thing for 6 hours.
For movies it will sometimes download a subtitle when a new one is added to the library. But it will never start searching for wanted movies. When I manually click the search button for a movie, it will find them most of the time.

**To Reproduce**
1. Wait..

**Expected behavior**
Should search for wanted subtitles

**Screenshots**
Here you can see the last time it auto downloaded a show (Arrested Development) and when I manually pressed search on a show (The End of the F***ing World)
![image](https://user-images.githubusercontent.com/5304947/71761588-50ade080-2ecc-11ea-8171-aeae80a94d5c.png)

**Software (please complete the following information):**
 - Bazarr: 0.8.3.4
 - Radarr version 0.2.0.1450
 - Sonarr version 3.0.3.654
 - OS: Linux with docker containers

**Additional context**
Log added
[bazarr (3).log](https://github.com/morpheus65535/bazarr/files/4021673/bazarr.3.log)

Maybe also good to know: I'm getting a lot of "504 Gateway Time-out" messages.
![image](https://user-images.githubusercontent.com/5304947/71762668-6f16da80-2ed2-11ea-8b83-e9b219851b28.png)

**Comment by halali** [comment]
Please fill issue template and provide more information and debug log.

**Comment by Rubeast** [comment]
Sorry about that. Didn't see the template. First time posting. I've edited my post.

**Comment by halali** [comment]
Yes it looks like from midnight until 7am you havent access to network. But i dont see any issue, there was also download limit exceeded exception. All providers have limits to downloaded subs per day. I suggest you to set automatic search for wanted subs for every 24 hours with your amount of missing subs, it can also take some time to download them. And next time please address debug log to your issue, is hard to search something in log with 100 000 lines.

**Comment by morpheus65535** [comment]
Is it fixed? Can I close this issue?

**Comment by Rubeast** [comment]
Sorry was not available the last couple of days.

> Yes it looks like from midnight until 7am you havent access to network. 

What do you mean? That the server was not connected to network? Because it was..

Yes. All providers have download limits, but for example with opensubtitles, I'm never reaching that limit.
Bazarr is also never searching for wanted movies. And I mean never. Only when new movies are added to my library it seems to look for a subtitle from time to time.

**Comment by Rubeast** [comment]
@morpheus65535 I'm guessing no one is replying because of the "Awaiting feedback" label you have added. This doesn't disappear when feedback is provided apparently.

**Comment by morpheus65535** [comment]
@halali could you continue helping him please?

**Comment by halali** [comment]
I cant see any issue in log, you maybe have low score when you look for subtitles for show released in 1985, that are arenamed probably outside sonarr/radarr because there is not scenename. and score for finded subs is low.

**Comment by Rubeast** [comment]
How do you explain that when I press the search button on a movie, it will almost always find the subtitle? 

I understand that shows released in 1985 are more difficult to find. But there are so many recent shows and movies that are just not being searched...

**Comment by halali** [comment]
Maybe you can make adressed debug log to your issue, because when you send 14mb log is hard find something.

**Comment by morpheus65535** [comment]
Please upgrade to 0.84, upgrade to Python 3.6 or greater and confirm if you still have the issue.

**Comment by morpheus65535** [comment]
Do you still have the issue?

**Comment by Rubeast** [comment]
Latest version is installed. Still not searching for subtitles.

> Make an adressed debug log
How?

**Comment by morpheus65535** [comment]
Enable debug log, empty log, reproduce the issue, disable debug log, provide the log.

**Comment by Rubeast** [comment]
What do you want me to do to reproduce the issue? Manually start the task "Search for wanted Subtitles" ?

**Comment by morpheus65535** [comment]
Yes but only for one series to not have an enormous log file.

**Comment by Rubeast** [comment]
I have added a log where the Wanted subtitles task is running.
Manually scanning a movie or show works most of the time like I said. It's the automated scanning that isn't downloading subtitles.

[2020.01.14 - bazarr.log](https://github.com/morpheus65535/bazarr/files/4061840/2020.01.14.-.bazarr.log)

**Comment by halali** [comment]
OK, i just looks arounf your 600 000 lines log.

1st dont make debug log of your issue when you indexing your library because 595 000 lines from log are from indexing and as i said is realy hard to search in it...

What i found is there isnt NL subs for show Bob's Burgers so thats why bazarr dont download them

**Comment by Rubeast** [comment]
The problem that he is non-stop indexing my library.  Is there a way to change this?
So when bazarr doesn't download subs for 3 days straight, that means that he keeps looking at shows that don't have that specific subtitle available? I understand that might slow things down.
I guess I just have to be more patient?

**Comment by morpheus65535** [comment]
And of course enable Adaptive Searching.

Take a look at https://github.com/morpheus65535/bazarr/wiki/FAQ-Performance-Tuning#enable-adaptive-searching

**Comment by Rubeast** [comment]
Yeah I already configured all the best practices I could find.
In any case, thanks for the help!
