### ISSUE TITLE
Bazarr not seeing movies

### ISSUE THREAD

**Issue by Rayrayrr** [morpheus65535/bazarr#733]
Hey guys.
I am using FreeNas 11.2
So I setup bazarr today and it sees all my tv shows which are in ”/mnt/TVShows”.

I also have “/mnt/Movies” which is where all the movies are stored. I can see the files in the shell.

Radar sees all the movies, files and quality.

So I am a bit confused why bazarr would see the tvshows but not movies when everything says it’s working. 

Debug log doesn’t really help.
This is what the log says when I run the update movie list task.

run: commit | a few seconds ago
  | run: SELECT configured, updated FROM system, [] | a few seconds ago
  | sql_queue: 0 | a few seconds ago
  | Sleeping: 0.001 b6a036a2-2c61-4148-b7e8-dd73b6ecd607 | a few seconds ago
  | execute: SELECT configured, updated FROM system, None | a few seconds ago
  | run: commit | a few seconds ago
  | run: SELECT COUNT(*) as count FROM table_movies WHERE missing_subtitles != '[]', [] | a few seconds ago
  | sql_queue: 0 | a few seconds ago
  | Sleeping: 0.001 9cc2bbf8-1118-431e-91e4-e1a18b85fc4d | a few seconds ago
  | execute: SELECT COUNT(*) as count FROM table_movies WHERE missing_subtitles != '[]', None | a few seconds ago

**Software (please complete the following information):**
 - Bazarr: 0.8.4
 - Radarr version 0.2.0.1358
 - Sonarr version 2.0.0.5322
 - OS: FreeBSD-11.2-STABLE-amd64-

Thanks in advance guys!

**Comment by halali** [comment]
Please provide debug log

**Comment by Rayrayrr** [comment]
I have uploaded the debug log as requested :)

[bazarr.log](https://github.com/morpheus65535/bazarr/files/4022620/bazarr.log)

**Comment by morpheus65535** [comment]
Is this fixed? Can I close it?

**Comment by Rayrayrr** [comment]
No, still having issues.
Still not grabbing movies from radarr.

**Comment by Rayrayrr** [comment]
Bazarr has finally populated movies. Must have just been taking its time :)
Thanks guys.
This can be closed now.
