### ISSUE TITLE
Doesn't auto download - opensubtitles' DNS error 

### ISSUE THREAD

**Issue by alhatmy** [morpheus65535/bazarr#734]
**Describe the bug**
Bazarr doesn't auto download subs, I have to click on each language/movie to download. They show well in wanted list as I'll take a screenshot now but doesn't download. I'm using opensuibtitles VIP and not sure what I should do to fix.

From the log;
without SSL
DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): vip-api.opensubtitles.org:80|
DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on vip-api.opensubtitles.org|

With SSL
DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): vip-api.opensubtitles.org:443|
DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on vip-api.opensubtitles.org|

**To Reproduce**
1. Even if I click on (Download wanted Subtitles) it won't do anything ... 

**Expected behavior**
To auto download subs ... 

**Screenshots**
![111](https://user-images.githubusercontent.com/17156241/71771118-995aad80-2f4f-11ea-8efc-caac89990602.PNG)

**Software (please complete the following information):**
 - Bazarr: 0.8.4
 - Radarr version 0.2.0.1450
 - Sonarr version 2.0.0.5338
 - OS: Linux with docker containers (Unraid OS)

**Additional context**
[bazarr - Copy.log.txt](https://github.com/morpheus65535/bazarr/files/4022386/bazarr.-.Copy.log.txt)

**Comment by morpheus65535** [comment]
This is completely unrelated to DNS.

Your path mapping isn't configured properly. Please see the wiki and chat with the support team on Discord if you cannot get it to work by yourself.

**Comment by alhatmy** [comment]
+ I recieve this error every few hours; Opensubtitles = ServiceUnavailable

![22](https://user-images.githubusercontent.com/17156241/71771377-3ff47d80-2f53-11ea-9119-b6b256272455.PNG)

& When I click on the missing subtitles it works, download each sub alone to the right path

**Comment by morpheus65535** [comment]
OpenSubtitle API is often unavailable for short period of time.

I know it works with manual search but I've seen this problem dozen of times and it's always a path mapping issue. There is no reason for the job to download missing subtitles to not run without flooding your log file.

**Comment by alhatmy** [comment]
Thanks ! I'll check it out now ... so path ...

**Comment by morpheus65535** [comment]
https://github.com/morpheus65535/bazarr/wiki/Settings-General#path-mappings-for-shows
