### ISSUE TITLE
0.84: Legendastv ~TypeError: expected str, bytes or os.PathLike object, not NoneType~

### ISSUE THREAD

**Issue by faacunha** [morpheus65535/bazarr#735]
**Describe the bug**
After the update to 0.8.4 Legendas.TV has status "TypeError" on the providers page

**To Reproduce**
1. Install or upgrade to 0.8.4 version with Python 3.8.1
2. Check System->Providers status after searching for a subtitle on LegendasTV

**Expected behavior**
Subtitle should be normally searched on the LegendasTV provider

**Software:**
 - Bazarr: 0.84
 - Radarr version: 2.0.0.5338
 - Sonarr version: 0.2.0.1450
 - OS: Linux-4.19.66-v7+-armv7l-with-glibc2.17
-  Python Version: 3.8.1

Subliminal installed and updated with all of its dependencies on Python3.8

**Additional context**
Debugging threw the following log:

`|Unexpected error in provider 'legendastv': Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 164, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 100, in __getitem__    provider = provider_registry[name](**self.provider_configs.get(name, {}))  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/legendastv.py", line 75, in __init__    rarfile.custom_check([rarfile.UNRAR_TOOL], True)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2823, in custom_check    p = custom_popen(cmd)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2812, in custom_popen    p = Popen(cmd, bufsize=0, stdout=PIPE, stdin=PIPE, stderr=STDOUT,  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__    self._execute_child(args, executable, preexec_fn, close_fds,  File "/usr/local/lib/python3.8/subprocess.py", line 1583, in _execute_child    and os.path.dirname(executable)  File "/usr/local/lib/python3.8/posixpath.py", line 152, in dirname    p = os.fspath(p)TypeError: expected str, bytes or os.PathLike object, not NoneType|Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 164, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 100, in __getitem__    provider = provider_registry[name](**self.provider_configs.get(name, {}))  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/legendastv.py", line 75, in __init__    rarfile.custom_check([rarfile.UNRAR_TOOL], True)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2823, in custom_check    p = custom_popen(cmd)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2812, in custom_popen    p = Popen(cmd, bufsize=0, stdout=PIPE, stdin=PIPE, stderr=STDOUT,  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__    self._execute_child(args, executable, preexec_fn, close_fds,  File "/usr/local/lib/python3.8/subprocess.py", line 1583, in _execute_child    and os.path.dirname(executable)  File "/usr/local/lib/python3.8/posixpath.py", line 152, in dirname    p = os.fspath(p)TypeError: expected str, bytes or os.PathLike object, not NoneType|`

Complete log is also attached.
[bazarr.log](https://github.com/morpheus65535/bazarr/files/4022462/bazarr.log)

**Comment by morpheus65535** [comment]
I confirm that I can reproduce this issue on my RPi running Raspbian 10 and Python 3.7.3:

```
Traceback (most recent call last):
  File "/home/pi/bazarr/bazarr/../libs/subliminal_patch/core.py", line 164, in list_subtitles_provider
    results = self[provider].list_subtitles(video, provider_languages)
  File "/home/pi/bazarr/bazarr/../libs/subliminal_patch/core.py", line 100, in __getitem__
    provider = provider_registry[name](**self.provider_configs.get(name, {}))
  File "/home/pi/bazarr/bazarr/../libs/subliminal_patch/providers/legendastv.py", line 75, in __init__
    rarfile.custom_check([rarfile.UNRAR_TOOL], True)
  File "/home/pi/bazarr/bazarr/../libs/rarfile.py", line 2823, in custom_check
    p = custom_popen(cmd)
  File "/home/pi/bazarr/bazarr/../libs/rarfile.py", line 2813, in custom_popen
    creationflags=creationflags)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1436, in _execute_child
    executable = os.fsencode(executable)
  File "/usr/lib/python3.7/os.py", line 809, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
  TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I'm going to try to fix this.

**Comment by faacunha** [comment]
Glad you could reproduce let me know if there is anything else I can help
you with

Em seg, 6 de jan de 2020 22:27, morpheus65535 <notifications@github.com>
escreveu:

**Comment by morpheus65535** [comment]
Does `sudo apt-get install unrar-free` fix your issue? If it is, I'll add this to the wiki.

**Comment by faacunha** [comment]
@morpheus65535 that seems to have done the trick yes:

> Brazilian Portuguese subtitles downloaded from legendastv with a score of 95.0% using filename guessing.

I believe this does deserve a place in the wiki, also, if you don't mind me asking, how did you find out unrar was the missing piece? Thanks

**Comment by morpheus65535** [comment]
That gives me a hint and I tried to run `unrar`from command prompt:

```
  File "/home/pi/bazarr/bazarr/../libs/subliminal_patch/providers/legendastv.py", line 75, in __init__
    rarfile.custom_check([rarfile.UNRAR_TOOL], True)
```

I'll add it to the wiki. Thanks for the confirmation.
