### ISSUE TITLE
Post-processing not working with Python 3

### ISSUE THREAD

**Issue by janpfo** [morpheus65535/bazarr#737]
**Describe the bug**

When enabling post-processing, it will download the subtitle, but it will not appear in history, and you have to manually scan the disk for the subtitle to show in Bazarr. 

It will download the subtitle, but not post-process it. 

**To Reproduce**
1. Go to 'Settings'
2. Enable 'Post-processing'
3. Download subtitle

**Expected behavior**
Download and post-process subtitle, it worked with an earlier dev version. 

**Software (please complete the following information):**
 - Bazarr: [0.8.4]
 - Python: [3.7.5]

**Additional context**
[bazarr.log](https://github.com/morpheus65535/bazarr/files/4023277/bazarr.log)

`Traceback (most recent call last):
File "/app/bazarr/bazarr/../libs/bottle.py", line 866, in _handle
return route.call(**args)

File "/app/bazarr/bazarr/../libs/bottle.py", line 1744, in wrapper
rv = callback(*a, **ka)

File "/app/bazarr/bazarr/main.py", line 129, in wrapper
return func(*a, **ka)

File "/app/bazarr/bazarr/main.py", line 1804, in get_subtitle
result = download_subtitle(episodePath, language, hi, forced, providers_list, providers_auth, sceneName, title,

File "/app/bazarr/bazarr/get_subtitle.py", line 264, in download_subtitle
logging.info('BAZARR Post-processing result for file ' + path + ' : ' + out)

TypeError: can only concatenate str (not "bytes") to str`

**Comment by janpfo** [comment]
Just tried with Bazarr version 0.8.4.1 and python 2.7, and it's working.

**Comment by morpheus65535** [comment]
I've pushed a fix to dev branch. Could you test it please?

**Comment by janpfo** [comment]
Same error.

**Comment by morpheus65535** [comment]
Should be fixed with last commit in dev. Please confirm.

**Comment by janpfo** [comment]
Confirmed working with commit 298a563

**Comment by morpheus65535** [comment]
Could be possible but doesn't worth the pain as I'm completely reworking the UI.

Thank for the confirmation. This will be include in next update to master.
