### ISSUE TITLE
BAZARR Error trying to get episodes from Sonarr. Timeout Error.

### ISSUE THREAD

**Issue by pietro95** [morpheus65535/bazarr#738]
Hello Everyone
Fresh install of Bazarr on Docker, trying to set up with last version of Sonarr, is able to pull out all of the series but it goes in timeout when it tries to list all of the episodes. Server is a Kimsufi KS-3 with 4GB of RAM and an Atom N2800 as CPU. I tried setting up Bazzar with both Local Container and public IP address but same error occurred. CPU is always around 7% of usage (monitored with netdata). 
Version:
Server Ubuntu 18.04, 
Bazarr 0.8.4
Sonarr 3.0.3.684

Log from the error:
```
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/urllib3/connectionpool.py", line 387, in _make_request
  six.raise_from(e, None)
 File "", line 2, in raise_from
 File "/app/bazarr/bazarr/../libs/urllib3/connectionpool.py", line 383, in _make_request
  httplib_response = conn.getresponse()
 File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
  response.begin()
 File "/usr/lib/python3.8/http/client.py", line 303, in begin
  version, status, reason = self._read_status()
 File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
  line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
 File "/usr/lib/python3.8/socket.py", line 669, in readinto
  return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/requests/adapters.py", line 439, in send
  resp = conn.urlopen(
 File "/app/bazarr/bazarr/../libs/urllib3/connectionpool.py", line 640, in urlopen
  retries = retries.increment(method, url, error=e, _pool=self,
 File "/app/bazarr/bazarr/../libs/urllib3/util/retry.py", line 368, in increment
  raise six.reraise(type(error), error, _stacktrace)
 File "/app/bazarr/bazarr/../libs/urllib3/packages/six.py", line 686, in reraise
  raise value
 File "/app/bazarr/bazarr/../libs/urllib3/connectionpool.py", line 600, in urlopen
  httplib_response = self._make_request(conn, method, url,
 File "/app/bazarr/bazarr/../libs/urllib3/connectionpool.py", line 389, in _make_request
  self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
 File "/app/bazarr/bazarr/../libs/urllib3/connectionpool.py", line 307, in _raise_timeout
  raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host=\172.17.0.5\, port=8989): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/app/bazarr/bazarr/get_episodes.py", line 46, in sync_episodes
  r = requests.get(url_sonarr_api_episode, timeout=60, verify=False)
 File "/app/bazarr/bazarr/../libs/requests/api.py", line 75, in get
  return request(\get\, url, params=params, **kwargs)
 File "/app/bazarr/bazarr/../libs/requests/api.py", line 60, in request
  return session.request(method=method, url=url, **kwargs)
 File "/app/bazarr/bazarr/../libs/requests/sessions.py", line 533, in request
  resp = self.send(prep, **send_kwargs)
 File "/app/bazarr/bazarr/../libs/requests/sessions.py", line 646, in send
  r = adapter.send(request, **kwargs)
 File "/app/bazarr/bazarr/../libs/requests/adapters.py", line 529, in send
  raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host=\172.17.0.5\, port=8989): Read timed out. (read timeout=60)
```

Thank you for your support!

**Comment by morpheus65535** [comment]
Restart Sonarr. It should be answering Bazarr in 60 seconds. I have series with more than 500 episodes and they get synced in less than a second on 10 years old hardware.

**Comment by morpheus65535** [comment]
I'm closing this one, please reopen if restarting Sonarr didn't fixed your issue.

**Comment by pietro95** [comment]
Hi Morpheus, thank you for your support but restart Sonarr container was the first thing I tried. After I opened this issue I left Bazarr doing its thing for a couple of hours and it finally did a first scan but unfortunately it start again throwing timeout error with both task "Update Series" and "Sync Episode" (in 18 hours I have 19 pages of error log). At this moment Bazarr episode list is not updated with Sonarr (for example, I don't see in bazarr the last Doctor Who episode which I have in my sonarr library). I just tried restarting sonarr container but didn't solve the issue.

**Comment by morpheus65535** [comment]
Please provide an emptied first debug log, your obfuscated config.ini file and your bazarr.db file.

**Comment by pietro95** [comment]
Attached you will find what you requested. Log is for the latest 10-15 minutes, hope is enough. 
[bazarr.log](https://github.com/morpheus65535/bazarr/files/4037276/bazarr.log)

[Bazarr DB+Config.zip](https://github.com/morpheus65535/bazarr/files/4037280/Bazarr.DB%2BConfig.zip)

Again, thank you for your support :)

**Comment by morpheus65535** [comment]
I don't see anything wrong. Maybe use the IP of your docker host that run Sonarr container instead of using your FQDN to call Sonarr. Could be related to some firewall or security software... You can also try to call directly the IP of the Sonarr container.

**Comment by morpheus65535** [comment]
Is it fixed?

**Comment by pietro95** [comment]
Hi Morpheus, sorry for the late reply. Unfortunately it is not fixed. I tried again with both IP address of the machine and also with local Sonarr Container IP, but with no result. There are no firewall on the machine... could it be related to where the episodes are? All my files are in Google Drive mounted with rclone...

**Comment by GermanG** [comment]
@pietro95 just an idea: if you access a bash prompt inside your docker instance you can try to telnet the ip/port from there, I really think it's an issue with the bazarr instance not getting there and not bazarr itself.

**Comment by morpheus65535** [comment]
@pietro95 we have a lot of user with Google Drive and rclone and it works fine but could require some tuning. I'm not using it myself so I can't help you on that.

Like @GermanG said, it looks as a networking configuration (or software impacting network communication) issue.

**Comment by halali** [comment]
@pietro95 is that rclone mounted in windows or Linux? Rclone mounted in windows seems to deadlocking sometimes when there are many uploading files, and that can cause lock all software that use that mounted drive. Im not sure how it work in linux, but probably different aw there isnt VFS needed.

**Comment by pietro95** [comment]
Hello and thank you to everyone! I hope to try what suggest by @GermanG tomorrow, but I think that Bazarr is reaching sonarr, because it managed to do a first scan, and I can see some episodes in Bazarr. Rclone is mounted on linux... I configured this server more than a year ago and everyting else is working flawless since then...

**Comment by morpheus65535** [comment]
Is it still an issue?

**Comment by pietro95** [comment]
Hi morpheus yes it is still an issue but I dint have any time to do some
test... I'm sorry to keep this issue opened for so long... I hope to do
some test in the next 2 days...

Il Ven 7 Feb 2020, 21:55 morpheus65535 <notifications@github.com> ha
scritto:

**Comment by morpheus65535** [comment]
> I don't see anything wrong. Maybe use the IP of your docker host that run Sonarr container instead of using your FQDN to call Sonarr. Could be related to some firewall or security software... You can also try to call directly the IP of the Sonarr container.

@pietro95 did you tried my suggestion?

**Comment by morpheus65535** [comment]
I'm gonna close this issue. Reopen it if it isn't fixed.
