### ISSUE TITLE
Bazarr almost never registering scene names of movies/shows

### ISSUE THREAD

**Issue by Loewkie** [morpheus65535/bazarr#740]
Both Sonarr/Radarr rename my files. Bazarr should recognize the scenename and use that to search for content. However, only a very select set of items actually has a known scenename in Bazarr. Why is that? Right now I'm afraid the scenename feature doesn't work properly.

**Comment by dhaos21** [comment]
I have also noticed this, at first i thought it was due to obfuscated files, then down to certain scene groups, but there is no rhyme or reason.

**Comment by morpheus65535** [comment]
I've just tested it and Bazarr use scenename perfectly if Sonarr provide it. There must be something wrong with Sonarr. You can do a call to Sonarr API to confirm if scenename is present (`/api/episodes...`).

**Comment by Loewkie** [comment]
I'll look into the API morpheus. How about Radarr for you? Because I have the same issues there.

**Comment by Loewkie** [comment]
There is a crucial difference within sonarr for correct and incorrect processing. 

A correct example:

![image](https://user-images.githubusercontent.com/12374285/71819168-661d3900-308b-11ea-8388-4587f1381b7d.png)

An incorrect example:

![image](https://user-images.githubusercontent.com/12374285/71819191-7d5c2680-308b-11ea-860c-b06afb17f417.png)

Apparently a lot of episodes are not registered as correctly processed. Even though they clearly exist....

**Comment by Loewkie** [comment]
Exactly the same cause seems to be to blame with Radarr. I will have to investigate what causes the absence of "correctly completed and processed from download client".

**Comment by Loewkie** [comment]
I can't get the API to work right now (am getting a 404 not found error), but I did find a potential workaround in the API:

https://github.com/Sonarr/Sonarr/wiki/History

The history endpoint allows you to find all history entries for episodes/movies. You could look into records -> sourceTitle for the original release info from the most recent entry in the history. So far I haven't been able to check whether this would work for both use cases, because I'm too dumb to get the API to work. Maybe if you could give me a GET example URL I can be of more use. I reach the API just fine, but I probably am doing something wrong when it comes to giving the episodeId.

Alternatively:

https://github.com/Sonarr/Sonarr/wiki/Release

The release endpoint might actually list the original name under "title", although I have again not been able to verify whether or not this is true because I'm too dumb to make a correct API call.

**Comment by Loewkie** [comment]
> There is a crucial difference within sonarr for correct and incorrect processing.
> 
> A correct example:
> 
> ![image](https://user-images.githubusercontent.com/12374285/71819168-661d3900-308b-11ea-8388-4587f1381b7d.png)
> 
> An incorrect example:
> 
> ![image](https://user-images.githubusercontent.com/12374285/71819191-7d5c2680-308b-11ea-860c-b06afb17f417.png)
> 
> Apparently a lot of episodes are not registered as correctly processed. Even though they clearly exist....

I'm pretty sure my large amount of "correctly completed" problems stem directly from QBitTorrent. It does very often not delete the torrent automatically (I've been doing it manually for a long time). So this in turn probably causes Sonarr/Radarr to think that the interaction with the download client did not complete correctly. The same is also true for manual imports, where this info also doesn't exist.

Let's hope that the history endpoint is able to solve this because through this API endpoint you're able to get the original source titles of:

- Manual imports
- Torrent last downloaded
- Correct completion of torrent client interaction (if exists)

**Comment by dhaos21** [comment]
like i said looking back on some recent movies i have done, probs 50 over the last few days all the ones that bazarr had problem s with are the ones i have had to manually import due to radarr not knowing what movie they are.

**Comment by dhaos21** [comment]
but if you are getting more or less all of your movies not registering then that seems to be a problem on your end, out of the 50 i had probably 4 or 5 that didn't import automatically.

**Comment by Loewkie** [comment]
Yes I'm pretty sure QBT is to blame unfortunately.

Still, it would be nice if an IF clause could be added to the scene release GET.
Try the current implementation, but if nothing is found try to obtain the best scene name from the history endpoint.

It would result in an implementation which deals correctly with all three cases, instead of just with one.

**Comment by morpheus65535** [comment]
As it is an issue with Sonarr/Radarr API, I suggest you open an issue for them to fix it on their side. I don't plan to add an additional API call when I already get blamed for making too much and waste CPU time and network IO. If, and only if, they don't want to fix it on their side, I'll see what I can do.
