### ISSUE TITLE
API for Bazarr

### ISSUE THREAD

**Issue by JagandeepBrar** [morpheus65535/bazarr#741]
Hi,

I'm the developer for an open-source iOS application for managing usenet applications (including related services like Radarr, Sonarr, etc.)

I've gotten a few requests to support Bazarr, but can't seem to find any documentation on an API.  Is there an API available for Bazarr, and if so is there any documentation available anywhere for it?

Thanks!

**Comment by morpheus65535** [comment]
Hey,

Currently Bazarr API is really limited to only meet Oscarr requirements:
- `/api/series/wanted`
- `/api/series/history`
- `/api/movies/wanted`
- `/api/movies/history`
Those endpoint currently return the 10 most recent items in a JSON array. No authentification required.

I'm currently reworking the whole UI that will be based on REST API. If you have further requirements, I can see how I can implement them.

**Comment by JagandeepBrar** [comment]
Thanks a lot for the quick response!

If you'll be releasing a new API in the near future, I may as well wait for that.

Ideally the "requirements" for the API would be similar to the other -rr services, inwhich you can view series and movies, the state of their downloaded status, and the ability to trigger a download of subtitles.

**Comment by morpheus65535** [comment]
You'll be able to do all that with the future API. I suggest you wait for the new API because the actual API won't match your expectations.

**Comment by JagandeepBrar** [comment]
@morpheus65535 Hey, just wondering if there is any update on the new API? Thanks!

**Comment by morpheus65535** [comment]
@JagandeepBrar Hey, in fact it could be considered almost final but is yet undocumented and will be available only in Bazarr 0.9 or greater. You can take a look at the code there:

https://github.com/morpheus65535/bazarr/blob/hermes/bazarr/api.py

The API require authentication using API key that can be passed as query string argument for GET request (`?apikey=#####`) or as POST data.

**Comment by anonyme123** [comment]
Hello,

The provided link appears dead =/ any update on making the API available?

**Comment by morpheus65535** [comment]
> Hello,
> 
> The provided link appears dead =/ any update on making the API available?

This was the link to the feature branch before we merge and remove it. You can now see the code in bazarr/api.py from any branch. BTW there's gonna be major changes in 0.9.4 that will to dev branch this week. I would work from that one instead of the one in master branch.

**Comment by anonyme123** [comment]
Got it thanks.
I'm having trouble understanding the code, would you have a documentation? I'm trying to change the language profile for one movie.

**Comment by morpheus65535** [comment]
> Got it thanks.
> I'm having trouble understanding the code, would you have a documentation? I'm trying to change the language profile for one movie.

No it's undocumented and you're on your own. It can change anytime.

**Comment by davidnewhall** [comment]
> No it's undocumented and you're on your own. It can change anytime.

That's extremely helpful.

**Comment by madjo1983** [comment]
> https://github.com/morpheus65535/bazarr/blob/hermes/bazarr/api.py

Hey ! This URL is no more available, if you can kindly resend please. I'm currently trying to call /api/movies/wanted with the API Key and Postman, but I'm not succeeding.
I'm using the API Key Auth:
![image](https://user-images.githubusercontent.com/26038638/212354751-6a3b4de0-7d30-46f9-be61-1b3a012387e6.png)

I put my key in the value, and I'm not sure what to put in the Key field:
![image](https://user-images.githubusercontent.com/26038638/212355023-c3d73c85-6a18-4304-9f73-4264149aad91.png)

I get this message:
![image](https://user-images.githubusercontent.com/26038638/212355105-6132a4c9-e461-4cd2-9017-5d8f1bdcc88a.png)

I'm struggling in finding some doc here, if you can kindly help me please.

Much appreciated.

**Comment by morpheus65535** [comment]
@madjo1983 check in System-->Status. There's a link to Swagger-UI.

**Comment by madjo1983** [comment]
> @madjo1983 check in System-->Status. There's a link to Swagger-UI.

Got it thanks !
![image](https://user-images.githubusercontent.com/26038638/212361645-3309b4dc-b079-4825-9406-37a9ebc5cd6b.png)
