### ISSUE TITLE
BAZARR Error trying to get episodes from Sonarr. Timeout Error.

### ISSUE THREAD

**Issue by pietro95** [morpheus65535/bazarr#743]
So I'm reopening issue #738 since my problem is still not solved. I have replied to the old issue but for reference this is my last message: 
Hi Morpheus, thank you for your support but restart Sonarr container was the first thing I tried. After I opened this issue I left Bazarr doing its thing for a couple of hours and it finally did a first scan but unfortunately it start again throwing timeout error with both task "Update Series" and "Sync Episode" (in 18 hours I have 19 pages of error log). At this moment Bazarr episode list is not updated with Sonarr (for example, I don't see in bazarr the last Doctor Who episode which I have in my sonarr library). I just tried restarting sonarr container but didn't solve the issue.

**Comment by morpheus65535** [comment]
I've reopened the previous issue instead.
