### ISSUE TITLE
Sending an interrupt signal (through `kill` command) doesn't kill child processes

### ISSUE THREAD

**Issue by smaarn** [morpheus65535/bazarr#746]
**Describe the bug**
Currently, if I run from a terminal the `python3 bazarr.py` command and then hit the infamous `Ctrl-C` keys, the process is killed and also any of its child processes.
Now, if I run the command in a forked process and then send explicitely the TERM signal to the parent process (e.g. by running `kill -SIGTERM <pid>`) the child processes aren't killed.

**To Reproduce**
1. In a terminal run (from within the bazarr home directory)
```
python3 bazarr.py &
echo $!>bazarr.pid
```
2. From another terminal run 
```
kill -SIGTERM bazarr.pid
```
3. Then run `ps auxwww | grep bazarr`
4. The child `python3 -u bazarr/main.py` process is still there

**Expected behavior**

Well, the proces should have ended also (e.g. the output should just return the current command's PID).

**Software (please complete the following information):**
 - Bazarr: v0.8.4
 - OS: OS X 10.12
 - Python: 3.7.6

**Additional context**

This causes concerns in basic external process handling mechanism which tend to use kill signals to stop a service.

**Comment by morpheus65535** [comment]
Did you try `kill -2` instead?

**Comment by smaarn** [comment]
@morpheus65535 just did and it seems the same issue occurs: the signal is indeed well received (in this case it exits the loop reading for the forker process output) but that's it. Even worse: if I resend the -2 signal the process exits but the child process keeps running.

To be honest, I'm currently working on fixing this but the point of this issue was to be sure

# that the behaviour was indeed not expected
# that there wasn't already some initiative done to fix this (meaning I'm glad to do it but there's no point if someone's already working on it ;) )

**Comment by morpheus65535** [comment]
This is of course an unexpected behavior and I'll be perfectly fine to accept a PR to fix this. :-)

Just make sure that it's also working fine on Windows and MacOS.

**Comment by smaarn** [comment]
Actually I'm testing it on mac os first (I'll validate it on a Synology). 
Trying to see if I can get a hold on a windows to validate it.

**Comment by morpheus65535** [comment]
If you can't, let me know and I'll try it myself. Thanks.
