### ISSUE TITLE
Stacktrace from startup in rebulk / regex

### ISSUE THREAD

**Issue by fryfrog** [morpheus65535/bazarr#748]
**Describe the bug**
Trying to start bazarr on Arch Linux using my AUR package throws a stack trace I'm having trouble understanding...

So it looks like bazarr includes a *ton* of the libraries it needs, but maybe the rebulk included isn't happy w/ the Python3 built in regex?

**Software (please complete the following information):**
 - Bazarr: 0.8.4
 - Python: 3.8.1
 - OS: Arch Linux

**Additional context**
```
[bazarr@apollo ~]$ /usr/bin/python /usr/lib/bazarr/bazarr.py --no-update --config /var/lib/bazarr
Bazarr starting...
Traceback (most recent call last):
  File "/usr/lib/bazarr/bazarr/main.py", line 36, in <module>
    from init import *
  File "/usr/lib/bazarr/bazarr/init.py", line 15, in <module>
    import subliminal
  File "/usr/lib/bazarr/bazarr/../libs/subliminal/__init__.py", line 12, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/usr/lib/bazarr/bazarr/../libs/subliminal/core.py", line 30, in <module>
    from guessit import guessit
  File "/usr/lib/bazarr/bazarr/../libs/guessit/__init__.py", line 6, in <module>
    from .api import guessit, GuessItApi
  File "/usr/lib/bazarr/bazarr/../libs/guessit/api.py", line 151, in <module>
    default_api = GuessItApi(rebulk_builder())
  File "/usr/lib/bazarr/bazarr/../libs/guessit/rules/__init__.py", line 50, in rebulk_builder
    rebulk.rebulk(episodes())
  File "/usr/lib/bazarr/bazarr/../libs/guessit/rules/properties/episodes.py", line 139, in episodes
    rebulk.chain(formatter={'season': int, 'episode': int},
  File "/usr/lib/bazarr/bazarr/../libs/rebulk/chain.py", line 115, in regex
    pattern = self.rebulk.build_re(*pattern, **kwargs)
  File "/usr/lib/bazarr/bazarr/../libs/rebulk/rebulk.py", line 133, in build_re
    return RePattern(*pattern, **kwargs)
  File "/usr/lib/bazarr/bazarr/../libs/rebulk/pattern.py", line 378, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/usr/lib/bazarr/bazarr/../libs/rebulk/loose.py", line 50, in call
    return function(*call_args, **call_kwargs)
  File "/usr/lib/python3.8/site-packages/regex/regex.py", line 348, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/usr/lib/python3.8/site-packages/regex/regex.py", line 585, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'formatter'
```

```
[bazarr@apollo ~]$ /usr/bin/python /usr/lib/bazarr/bazarr.py --no-update --config /var/lib/bazarr
Bazarr starting...
Traceback (most recent call last):
  File "/usr/lib/bazarr/bazarr/main.py", line 36, in <module>
    from init import *
  File "/usr/lib/bazarr/bazarr/init.py", line 15, in <module>
    import subliminal
  File "/usr/lib/bazarr/bazarr/../libs/subliminal/__init__.py", line 12, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/usr/lib/bazarr/bazarr/../libs/subliminal/core.py", line 30, in <module>
    from guessit import guessit
  File "/usr/lib/bazarr/bazarr/../libs/guessit/__init__.py", line 6, in <module>
    from .api import guessit, GuessItApi
  File "/usr/lib/bazarr/bazarr/../libs/guessit/api.py", line 151, in <module>
    default_api = GuessItApi(rebulk_builder())
  File "/usr/lib/bazarr/bazarr/../libs/guessit/rules/__init__.py", line 50, in rebulk_builder
    rebulk.rebulk(episodes())
  File "/usr/lib/bazarr/bazarr/../libs/guessit/rules/properties/episodes.py", line 139, in episodes
    rebulk.chain(formatter={'season': int, 'episode': int},
  File "/usr/lib/bazarr/bazarr/../libs/rebulk/chain.py", line 115, in regex
    pattern = self.rebulk.build_re(*pattern, **kwargs)
  File "/usr/lib/bazarr/bazarr/../libs/rebulk/rebulk.py", line 133, in build_re
    return RePattern(*pattern, **kwargs)
  File "/usr/lib/bazarr/bazarr/../libs/rebulk/pattern.py", line 378, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/usr/lib/bazarr/bazarr/../libs/rebulk/loose.py", line 50, in call
    return function(*call_args, **call_kwargs)
  File "/usr/lib/python3.8/site-packages/regex/regex.py", line 348, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/usr/lib/python3.8/site-packages/regex/regex.py", line 585, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'children'
```

**Comment by fryfrog** [comment]
Of interest is that I see a similar error from my `python-rebulk` package as well...

```
...
>           raise ValueError('unused keyword argument {!a}'.format(any_one))
E           ValueError: unused keyword argument 'marker'

/usr/lib/python3.8/site-packages/regex/regex.py:585: ValueError
```

**Comment by fryfrog** [comment]
Ugh, and it works *fine* on a clean system so it is somehow my fault. :p

**Comment by morpheus65535** [comment]
So I can close this?

**Comment by fryfrog** [comment]
I haven't figured out the problem, but I'll move to Discord and update this issue once I get it sorted out in case it helps someone in the future. :/

**Comment by fryfrog** [comment]
So this turned out to be the [python-regex](https://www.archlinux.org/packages/community/x86_64/python-regex/) package for some reason. The working system did not have it installed.

**Comment by ashleybone** [comment]
I think this issue should be re-opened.  The underlying problem here is indeed  a change to Matthew Barnett's regex package, which bazarr uses if it is installed on the system.  I believe the problem bazarr is having is the same as [this](https://bitbucket.org/mrabarnett/mrab-regex/issues/357/new-exception-valueerror-unused-keyword) (link to the regex bitbucket).

The version released on 2020.1.7 added a ValueError exception thrown by compile and other functions any time a unused keyword argument was found, the intent being to help users avoid typos.  However this broke some users of the package, so the 2020.1.8 version added an ignore_unused argument to compile and other functions to avoid this.  Unfortunately, the default value of ignore_unused is False, so regex is still throwing an exception when bazarr passes keywords it doesn't use.

**Comment by morpheus65535** [comment]
@ashleybone are you able to put the 2020.1.8 source inside Bazarr lib directory and check if it fix your issue?

**Comment by fryfrog** [comment]
It wouldn't, becauze bazarr would have to call it w/ `ignore_unused=True`.

**Comment by fryfrog** [comment]
I re-opened it, because while it only impacts Arch right now... eventually, its going to impact others.

**Comment by morpheus65535** [comment]
Ok so guessit should call regex with `ignore_unused=True`? Do we need to update something or could we rely on installed version of regex?

**Comment by fryfrog** [comment]
You're getting into Python territory I'm not sure of. I guess if you can *force* using the *python* version of regex instead of the pypi alternative [regex](https://pypi.org/project/regex/), that'd fix it right? Some how that package must take over regex from python's native?

**Comment by ashleybone** [comment]
I think that alone (ignored_unused=True) should solve the problem.  For newer versions of regex it will stop the exception from being thrown, and for older versions or just plain python re it will be treated, ironically, as a keyword argument and ignored.

**Comment by ashleybone** [comment]
Thought about this more and what I said is wrong.  The external regex module has kwargs throughout its interface, so using ignored_unused won't cause a problem, but the internal re module doesn't take them, so it won't like that.  But since bazarr is passing unused keyword args now and it works fine with internal re, you must have some mechanism that handles that already.  So I was wrong but it should still work :).

**Comment by morpheus65535** [comment]
@ashleybone are you able to test it and, if it works, submit a PR? It would be greatly appreciated. :-)

Thanks!

**Comment by ashleybone** [comment]
Sure, I'll take a crack at it this weekend.

**Comment by morpheus65535** [comment]
@ashleybone did you had time to look into this?

**Comment by edualm** [comment]
Not OP, but I have the same problem as I'm also running Arch.

Can any of you two point me to the code changes needed? I'll gladly try it out.

**Comment by fryfrog** [comment]
I think that is what @morpheus65535 is hoping @ashleybone will work out, the basics are above but I don't have the talent to apply that knowledge.

**Comment by edualm** [comment]
There are some ways to fix this - honestly, I just uninstalled the `regex` library from `pip2` and bazarr started working. This means that running bazarr in a `venv` would fix the issue.

Migrating to python3 also fixed it for me (probably because I didn't have that `regex` library installed), which is what I ultimately ended up doing.

**Comment by fryfrog** [comment]
^ That is how I "fixed" mine too.

**Comment by morpheus65535** [comment]
As we do not support Python 2.x anymore, I'll close this one. If someone face the issue with Python 3.x, feel free to reopen it.

**Comment by fryfrog** [comment]
This was an issue on Python 3, not 2.

**Comment by morpheus65535** [comment]
Yep sorry my bad!

**Comment by morpheus65535** [comment]
@ashleybone did you had time to work on that one?

**Comment by fryfrog** [comment]
Somehow `python-regex` got installed again and it started happening again... so it hasn't been fixed in the handful of months since I opened it! :)

**Comment by morpheus65535** [comment]
@fryfrog could you test dev branch? I've updated guessit and rebulk so it could possibly be fixed. No way to test it on my side.

**Comment by morpheus65535** [comment]
No answer. I close.
