### ISSUE TITLE
[Wiki] Update to FreeBSD installation tutorial

### ISSUE THREAD

**Issue by AudaciousTemplar** [morpheus65535/bazarr#749]
Hello,

I've successfully installed bazarr on FreeBSD but I had to make some changes to the instructions that are provided so I thought I would contribute by providing the steps that I took to get it working.

Firstly, the packages that I needed to install have changed to 
`pkg install git python3 py37-pip py37-libxml2 py27-libxslt py37-sqlite3`

Secondly, I would recommend updating the install directory from `/usr/local` to `/usr/local/share` as that is where radarr and sonarr install themselves, so it's more for alignment than anything.

Thirdly, this updates requires a user to be created for the bazarr client to be run as a daemon, the script is written for a user called `bazarr` but this can be changed by by adding `bazarr_user="bazarr"` to /etc/rc.conf

Then, from the install directory `/usr/local/share` run the following command `chown -R bazarr bazarr` where the first `bazarr` is the bazarr_user that you created.

Finally, I have rewritten the rc script so that I can start, stop, and check the status of the bazarr daemon.

**Please note** that I am no expert in rc scripting and this is just what I got to work. Also note that the bazarr daemon user **must** be unique as the daemon loses track of the extra process that is created by bazarr on startup so the stop command kills all processes being run off of the bazarr user. If anyone has a better solution for stopping the daemon, please contribute to this.

My rc script is as follows:
```
#!/bin/sh
# PROVIDE: bazarr
# REQUIRE: LOGIN
# KEYWORD: shutdown

# Add the following lines to /etc/rc.conf to enable bazarr:
# bazarr_enable="YES"
# Optionally add:
# Note: The bazarr_user must be unique as the stop_postcmd kills the other running process
# bazarr_user="bazarr"

. /etc/rc.subr

name="bazarr"
rcvar=bazarr_enable

load_rc_config $name

: ${bazarr_enable="NO"}
: ${bazarr_user:="bazarr"}
: ${bazarr_data_dir:="/usr/local/bazarr}

pidfile="/usr/local/bazarr/bazarr.pid"
procname="/usr/local/bin/python3"
command="/usr/sbin/daemon"
command_args="-f -p ${pidfile} ${procname} /usr/local/share/bazarr/bazarr.py"

start_precmd=bazarr_precmd
stop_postcmd=bazarr_postcmd

bazarr_precmd()
{
	export XDG_CONFIG_HOME=${bazarr_data_dir}

	if [ ! -d ${bazarr_data_dir} ]; then
		install -d -o ${bazarr_user} ${bazarr_data_dir}
	fi
}

bazarr_postcmd()
{
	killall -u ${bazarr_user}
}

run_rc_command "$1"
```

Let me know if anyone has any issues in getting this working.

**Comment by AudaciousTemplar** [comment]
I also need to add instructions to change ownership of the folder so that config of bazarr can be updated as non-root user

**Comment by morpheus65535** [comment]
Wiki updated, thanks.

Make sure you give Write permission to Bazarr directory or Bazarr won't be able to update itself.

We are working on a fix for orphaned child process exit.

**Comment by BJJLangedijk** [comment]
So I did run into an issue when trying to use Python 3 instead of Python 2.

`: ${bazarr_data_dir:="/usr/local/bazarr}`

Was missing a " after the dir, it should be like following:

`: ${bazarr_data_dir:="/usr/local/bazarr"}`

Also a weird thing I saw was that in the `command_args` you used a `/usr/local/share/bazarr` yet in all the other references this was `/usr/local/bazarr`.

After changing these around and tweaking it to work with my freenas install, it all seemed to work :)

**Comment by morpheus65535** [comment]
@BJJLangedijk thanks. I've made the change to wiki.
