### ISSUE TITLE
Error downloading subtitle from subdivx

### ISSUE THREAD

**Issue by mclssk** [morpheus65535/bazarr#750]
Hi! In my log exists:

BAZARR No valid Subtitles file found for this file: /mnt/plex_dades/media/Series/Arrow/Season 8/Arrow - S08E08 - Crisis on Infinite Earths (4) HDTV-720p.mkv

When I select file from subdivx server.

Can anybody help me please? thx!!!

My configuration is in VM Debian

![image](https://user-images.githubusercontent.com/2610945/72452047-2eb23900-37bd-11ea-8662-2ba810bf19ce.png)

**Comment by morpheus65535** [comment]
Please provide the subtitles url.

**Comment by mclssk** [comment]
Hi!

I see this:

`root@plex:/opt/bazarr/data/log# tail -f bazarr.log | grep subdivx
16/01/2020 08:48:06|INFO    |subliminal_patch.core           |Using 1 threads for 1 providers ({'subdivx'})|
16/01/2020 08:48:06|INFO    |subliminal_patch.core           |Downloading subtitle <SubdivxSubtitle 'https://www.subdivx.com/X6XNTg0MDk2X-arrow-s08e08.html' [es:None]> with score 350|
16/01/2020 08:48:06|INFO    |subliminal_patch.core           |Downloading subtitle <SubdivxSubtitle 'https://www.subdivx.com/X6XNTg0MDk2X-arrow-s08e08.html' [es:None]>|
16/01/2020 08:48:06|INFO    |subliminal_patch.core           |Initializing provider subdivx|
16/01/2020 08:48:06|INFO    |subliminal_patch.providers.subdivx|Downloading subtitle <SubdivxSubtitle 'https://www.subdivx.com/X6XNTg0MDk2X-arrow-s08e08.html' [es:None]>|
16/01/2020 08:48:06|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): www.subdivx.com:443|
16/01/2020 08:48:06|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on www.subdivx.com|
16/01/2020 08:48:07|DEBUG   |urllib3.connectionpool          |https://www.subdivx.com:443 "GET /X6XNTg0MDk2X-arrow-s08e08.html HTTP/1.1" 200 None|
16/01/2020 08:48:07|DEBUG   |urllib3.connectionpool          |https://www.subdivx.com:443 "GET /bajar.php?id=584096&u=8 HTTP/1.1" 302 None|
16/01/2020 08:48:07|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): www.subdivx.com:80|
16/01/2020 08:48:07|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on www.subdivx.com|
16/01/2020 08:48:07|DEBUG   |urllib3.connectionpool          |http://www.subdivx.com:80 "GET /sub8/584096.rar HTTP/1.1" 200 19677|
16/01/2020 08:48:07|DEBUG   |subliminal_patch.providers.subdivx|Identified rar archive|
16/01/2020 08:48:07|ERROR   |subliminal_patch.core           |Unexpected error in provider 'subdivx', Traceback: Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 259, in download_subtitle    self[subtitle.provider_name].download_subtitle(subtitle)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 179, in download_subtitle    subtitle_content = self._get_subtitle_from_archive(archive)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 248, in _get_subtitle_from_archive    return archive.read(name)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 771, in read    with self.open(fname, 'r', psw) as f:  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 756, in open    return self._file_parser.open(inf, psw)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1131, in open    return self._open_hack(inf, psw)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1474, in _open_hack    return self._open_hack_core(inf, psw, prefix, EMPTY)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1169, in _open_hack_core    return self._open_unrar(tmpname, inf, psw, tmpname)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1191, in _open_unrar    return PipeReader(self, inf, cmd, tmpfile)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2142, in __init__    super(PipeReader, self).__init__(rf, inf)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1983, in __init__    self._open()  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2165, in _open    self._proc = custom_popen(self._cmd)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2813, in custom_popen    creationflags=creationflags)  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__    restore_signals, start_new_session)  File "/usr/lib/python3.7/subprocess.py", line 1436, in _execute_child    executable = os.fsencode(executable)  File "/usr/lib/python3.7/os.py", line 809, in fsencode    filename = fspath(filename)  # Does type-checking of `filename`.TypeError: expected str, bytes or os.PathLike object, not NoneType|Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 259, in download_subtitle    self[subtitle.provider_name].download_subtitle(subtitle)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 179, in download_subtitle    subtitle_content = self._get_subtitle_from_archive(archive)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 248, in _get_subtitle_from_archive    return archive.read(name)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 771, in read    with self.open(fname, 'r', psw) as f:  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 756, in open    return self._file_parser.open(inf, psw)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1131, in open    return self._open_hack(inf, psw)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1474, in _open_hack    return self._open_hack_core(inf, psw, prefix, EMPTY)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1169, in _open_hack_core    return self._open_unrar(tmpname, inf, psw, tmpname)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1191, in _open_unrar    return PipeReader(self, inf, cmd, tmpfile)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2142, in __init__    super(PipeReader, self).__init__(rf, inf)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1983, in __init__    self._open()  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2165, in _open    self._proc = custom_popen(self._cmd)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2813, in custom_popen    creationflags=creationflags)  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__    restore_signals, start_new_session)  File "/usr/lib/python3.7/subprocess.py", line 1436, in _execute_child    executable = os.fsencode(executable)  File "/usr/lib/python3.7/os.py", line 809, in fsencode    filename = fspath(filename)  # Does type-checking of `filename`.TypeError: expected str, bytes or os.PathLike object, not NoneType|
16/01/2020 08:48:07|INFO    |root                            |Throttling subdivx for 10 minutes, until 20/01/16 08:58, because of: TypeError. Exception info: 'expected str, bytes or os.PathLike object, not NoneType'|
16/01/2020 08:48:07|INFO    |subliminal_patch.core           |Terminating provider subdivx|
`

**Comment by morpheus65535** [comment]
Install unrar-free.

**Comment by mclssk** [comment]
After install unrar:

`16/01/2020 12:14:38|ERROR   |subliminal_patch.core           |Unexpected error in provider 'subdivx', Traceback: Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 259, in download_subtitle    self[subtitle.provider_name].download_subtitle(subtitle)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 179, in download_subtitle    subtitle_content = self._get_subtitle_from_archive(archive)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 248, in _get_subtitle_from_archive    return archive.read(name)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 771, in read    with self.open(fname, 'r', psw) as f:  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 756, in open    return self._file_parser.open(inf, psw)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1131, in open    return self._open_hack(inf, psw)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1474, in _open_hack    return self._open_hack_core(inf, psw, prefix, EMPTY)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1169, in _open_hack_core    return self._open_unrar(tmpname, inf, psw, tmpname)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1191, in _open_unrar    return PipeReader(self, inf, cmd, tmpfile)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2142, in __init__    super(PipeReader, self).__init__(rf, inf)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1983, in __init__    self._open()  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2165, in _open    self._proc = custom_popen(self._cmd)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2813, in custom_popen    creationflags=creationflags)  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__    restore_signals, start_new_session)  File "/usr/lib/python3.7/subprocess.py", line 1436, in _execute_child    executable = os.fsencode(executable)  File "/usr/lib/python3.7/os.py", line 809, in fsencode    filename = fspath(filename)  # Does type-checking of `filename`.TypeError: expected str, bytes or os.PathLike object, not NoneType|Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 259, in download_subtitle    self[subtitle.provider_name].download_subtitle(subtitle)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 179, in download_subtitle    subtitle_content = self._get_subtitle_from_archive(archive)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 248, in _get_subtitle_from_archive    return archive.read(name)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 771, in read    with self.open(fname, 'r', psw) as f:  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 756, in open    return self._file_parser.open(inf, psw)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1131, in open    return self._open_hack(inf, psw)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1474, in _open_hack    return self._open_hack_core(inf, psw, prefix, EMPTY)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1169, in _open_hack_core    return self._open_unrar(tmpname, inf, psw, tmpname)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1191, in _open_unrar    return PipeReader(self, inf, cmd, tmpfile)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2142, in __init__    super(PipeReader, self).__init__(rf, inf)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1983, in __init__    self._open()  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2165, in _open    self._proc = custom_popen(self._cmd)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2813, in custom_popen    creationflags=creationflags)  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__    restore_signals, start_new_session)  File "/usr/lib/python3.7/subprocess.py", line 1436, in _execute_child    executable = os.fsencode(executable)  File "/usr/lib/python3.7/os.py", line 809, in fsencode    filename = fspath(filename)  # Does type-checking of `filename`.TypeError: expected str, bytes or os.PathLike object, not NoneType|
16/01/2020 12:14:38|INFO    |root                            |Throttling subdivx for 10 minutes, until 20/01/16 12:24, because of: TypeError. Exception info: 'expected str, bytes or os.PathLike object, not NoneType'|
16/01/2020 12:14:38|INFO    |subliminal_patch.core           |Terminating provider subdivx|`

**Comment by morpheus65535** [comment]
That's exactly the same error. Please provide the output of `unrar --version`.

**Comment by mclssk** [comment]
I've installed from APT:

root@plex:/opt/bazarr/data/log# unrar --version
unrar 0.0.1

**Comment by morpheus65535** [comment]
Did you restarted Bazarr after installing it?

**Comment by morpheus65535** [comment]
Related to: #735

**Comment by mclssk** [comment]
After restart:

`16/01/2020 12:36:17|DEBUG   |urllib3.connectionpool          |http://www.subdivx.com:80 "GET /sub8/584096.rar HTTP/1.1" 200 19677|
16/01/2020 12:36:17|DEBUG   |subliminal_patch.providers.subdivx|Identified rar archive|
16/01/2020 12:36:18|ERROR   |subliminal_patch.core           |Malformed RAR file from provider 'subdivx', skipping subtitle.|
  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 179, in download_subtitle
  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/subdivx.py", line 248, in _get_subtitle_from_archive
16/01/2020 12:36:18|INFO    |subliminal_patch.core           |Terminating provider subdivx|
`

**Comment by morpheus65535** [comment]
`16/01/2020 12:36:18|ERROR   |subliminal_patch.core           |Malformed RAR file from provider 'subdivx', skipping subtitle.|`

I guess it is self explanatory.
