### ISSUE TITLE
Pushbullet notification doesn't work

### ISSUE THREAD

**Issue by lukjod** [morpheus65535/bazarr#753]
On newest 0.8.4 nofification on downloaded subs doesn't work. 
Works testing but nothing more is coming.
Razarr and Sonarr notifications come thru without problems but nothing from Bazarr
It is installed on container station via docker linuxserver/jackett always newest release
Can this be connected to recent Python update change as earlier it worked ok?

Device:
Qnap ts-128a
Bazarr Version:
0.8.4
Sonarr Version:
2.0.0.5338
Radarr Version:
0.2.0.1450
Operating System:
Linux-4.2.8-aarch64-with
Python Version:
3.8.1

**Comment by morpheus65535** [comment]
Works perfectly fine for me with `linuxserver/bazarr:development`. Nothing changed about notification between master and dev branch so it should work for you to but you can try the dev branch just to be sure.

**Comment by lukjod** [comment]
well, it something more as program downloads subs but dont get any info on UI and must click refresh button to get sub files to show on ui.
log:
`17/01/2020 12:03:25|INFO    |root                            |BAZARR Log file emptied|
17/01/2020 12:15:42|WARNING |retry.api                       |HTTPSConnectionPool(host='www.podnapisi.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
17/01/2020 12:16:26|WARNING |apscheduler.scheduler           |Execution of job "movies_download_subtitles_24 (trigger: date[2020-01-17 12:16:26 CET], next run at: 2020-01-17 12:16:26 CET)" skipped: maximum number of running instances reached (1)|
17/01/2020 12:16:28|ERROR   |apscheduler.executors.default   |Job "movies_download_subtitles_24 (trigger: date[2020-01-17 12:15:27 CET], next run at: 2020-01-17 12:15:27 CET)" raised an exception|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File "/app/bazarr/bazarr/get_subtitle.py", line 692, in movies_download_subtitles\n    result = download_subtitle(path_replace_movie(movie[\'path\']),\n  File "/app/bazarr/bazarr/get_subtitle.py", line 264, in download_subtitle\n    logging.info(\'BAZARR Post-processing result for file \' + path + \' : \' + out)\nTypeError: can only concatenate str (not "bytes") to str'|
17/01/2020 12:18:03|ERROR   |apscheduler.executors.default   |Job "movies_download_subtitles_24 (trigger: date[2020-01-17 12:17:16 CET], next run at: 2020-01-17 12:17:16 CET)" raised an exception|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File "/app/bazarr/bazarr/get_subtitle.py", line 692, in movies_download_subtitles\n    result = download_subtitle(path_replace_movie(movie[\'path\']),\n  File "/app/bazarr/bazarr/get_subtitle.py", line 264, in download_subtitle\n    logging.info(\'BAZARR Post-processing result for file \' + path + \' : \' + out)\nTypeError: can only concatenate str (not "bytes") to str'|
17/01/2020 12:23:18|INFO    |root                            |BAZARR Settings saved succesfully.|
17/01/2020 12:25:14|INFO    |root                            |Throttling napisy24 for 10 minutes, until 20/01/17 12:35, because of: AuthenticationError. Exception info: 'Login failed'|
17/01/2020 12:25:38|WARNING |apscheduler.scheduler           |Execution of job "movies_download_subtitles_24 (trigger: date[2020-01-17 12:25:38 CET], next run at: 2020-01-17 12:25:38 CET)" skipped: maximum number of running instances reached (1)|
17/01/2020 12:25:51|ERROR   |apscheduler.executors.default   |Job "movies_download_subtitles_24 (trigger: date[2020-01-17 12:25:11 CET], next run at: 2020-01-17 12:25:11 CET)" raised an exception|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File "/app/bazarr/bazarr/get_subtitle.py", line 692, in movies_download_subtitles\n    result = download_subtitle(path_replace_movie(movie[\'path\']),\n  File "/app/bazarr/bazarr/get_subtitle.py", line 264, in download_subtitle\n    logging.info(\'BAZARR Post-processing result for file \' + path + \' : \' + out)\nTypeError: can only concatenate str (not "bytes") to str'|
17/01/2020 12:26:40|INFO    |root                            |BAZARR Settings saved succesfully.|
17/01/2020 13:34:38|INFO    |root                            |Using napisy24 again after 10 minutes, (disabled because: AuthenticationError)|
`

**Comment by morpheus65535** [comment]
Here's the relevant part:
```
Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/bazarr/bazarr/get_subtitle.py", line 692, in movies_download_subtitles
    result = download_subtitle(path_replace_movie(movie[\'path\']),
  File "/app/bazarr/bazarr/get_subtitle.py", line 264, in download_subtitle
    logging.info(\'BAZARR Post-processing result for file \' + path + \' : \' + out)
TypeError: can only concatenate str (not "bytes") to str
```

This is a bug in post-processing that have been fixed in dev branch. You can confirm by using dev image.

**Comment by lukjod** [comment]
ok on development version 084.1 all seems to be ok, notification send
thx
