### ISSUE TITLE
Enabling HI - what does it do?

### ISSUE THREAD

**Issue by ParsonsGlory** [morpheus65535/bazarr#754]
V.0.8.4 linuxserver docker.

- search for episode has score of 99.7 but 10 mismatches reported and file doesn't auto-download - see screenshot
- log shows file was rejected because Bazarr is set to force non HI and the available subtitle is flagged HI 
-  the subtitle on opensubtitles is flagged HI
- HI is not enabled in settings
- setting HI to true for the series allows the subtitle to auto-download

 So if HI isn't enabled then HI subtitles aren't downloaded - but what does enabling HI actually do? I'd assumed, possibly incorrectly, that enabling HI sets Bazaar to download HI only. But does enabling HI actually enable download of either HI or standard subtitles depending on whats available? If  both types of subtitles are available are both downloaded or is one type preferred?

The drop downs for the match on the screenshot are misleading. Shouldn't all attributes be matched except HI?

Great work by the way - very impressed!

[bazarr.log](https://github.com/morpheus65535/bazarr/files/4078596/bazarr.log)
![bazarr](https://user-images.githubusercontent.com/8316658/72639936-a05fd200-39cb-11ea-992c-8e3cccacf19c.PNG)

**Comment by morpheus65535** [comment]
HI is hearing-impaired. True is true, false is false: you want it or not. There's no "prefer" settings.

Regarding matches dropdown, if subliminal_patch (from Sub-Zero) have a match on hash, it doesn't take care of checking the others. That's the reason why they are in the doesn't match dropdown.

**Comment by ParsonsGlory** [comment]
So does setting the Hi flag to true effect download of standard subtitles? For example, if there is a standard subtitle for the release will it still be downloaded if the HI flag is set to true and there is no HI subtitle available?

**Comment by morpheus65535** [comment]
Like I said, setting HI to True is not equivalent to "prefer HI", it's "require HI". The same apply to HI = False.

**Comment by ParsonsGlory** [comment]
Ok got that. Prefer would be a good option but I guess I could just run two containers one with the Hi flag true and the other with the flag false?

**Comment by morpheus65535** [comment]
Yes you can.
