### ISSUE TITLE
Bazarr not autostarting in freebsd jail.

### ISSUE THREAD

**Issue by TobiasS1402** [morpheus65535/bazarr#757]
I followed the recently updated freebsd guide. I installed it and ran bazarr with python, it seemed to be working.

Next i created a user like this:
pw useradd bazarr -d /nonexistent -s /usr/bin/nologin -c "bazarr service account" -u 505
then i created the script, made it executable and then updated /etc/rc.conf.
I restarted the jail but it is not autostarting.

Can i take any steps to help me troubleshooting?

**Comment by morpheus65535** [comment]
I suggest you come to Discord for support. Maybe you'll find someone there who's using it in a jail.

**Comment by mvanbaak** [comment]
@TobiasS1402  This is a permissions issue. When you first started bazarr, it created the database file, the logs dir etc.
After adding the user bazarr and adding the rc script, bazarr is now running as user bazarr, and it cannot write to the logs and database. Please run a chown on the directory where you have those. That should fix the issue.

**Comment by TobiasS1402** [comment]
@mvanbaak Hm, weird. I just tried it, i chowned the directory for my bazarr user, then i impersonated as my bazarr user. I managed to manually start it. But when i reboot it it doesnt seem to execute the startup script or something.

**Comment by mvanbaak** [comment]
@TobiasS1402 How does the /usr/local/etc/rc.d/bazarr script look like?
And what did you put in /etc/rc.conf of the jail?

Here's the one I use. Some remarks:
- I use /usr/local/bazarr to store the config, db and logs (The rc script creates the dir if it does not exist)
- I use python3.7. If you use python3.6 change the script.
- I put bazarr_enable="YES" in /etc/rc.conf
```
#!/bin/sh
#
# Author: Michiel van Baak <michiel@vanbaak.eu>
#
# $FreeBSD: $
#
# PROVIDE: bazarr
# REQUIRE: LOGIN
# KEYWORD: shutdown

# Add the following lines to /etc/rc.conf to enable bazarr:
# bazarr_enable:   Set to NO by default. Set it to YES to enable it.
# bazarr_user:     The user account bazarr daemon runs as what
#                  you want it to be.
# bazarr_datadir:  Directory where bazarr user data lives.
#                  Default: /usr/local/bazarr

. /etc/rc.subr

name=bazarr
rcvar=bazarr_enable

load_rc_config ${name}

: ${bazarr_enable:=NO}
: ${bazarr_user:=bazarr}
: ${bazarr_datadir:="/usr/local/bazarr"}

pidfile="${bazarr_datadir}/bazarr.pid"
procname="/usr/local/bin/python3.7"
command="/usr/sbin/daemon"
command_args="-f -p ${pidfile} ${procname} /usr/local/share/bazarr/bazarr.py --no-update -c ${bazarr_datadir}"
start_precmd=bazarr_precmd

bazarr_precmd()
{
        if [ ! -d ${bazarr_datadir} ]; then
                install -d -o ${bazarr_user} ${bazarr_datadir}
        fi
}

run_rc_command "$1"
```

**Comment by TobiasS1402** [comment]
@mvanbaak Thank you for your reaction. I actually got it to work, i manually tried to run the script in the wiki and found that on line 21 one closing " was missing. The second part of the problem was python3, "Shared object "libpython3.7m.so.1.0" not found, required by "python3"".

After i fixed those problems it finally started automatically. cheers.
