### ISSUE TITLE
Subtitles for season packs aren't grabbed

### ISSUE THREAD

**Issue by dalaverd** [morpheus65535/bazarr#764]
Hello,

As you may already know, if Sonarr detects in one of your indexers that a full season download is available and you also selected to monitor all episodes of one season, then it may auto select this particular download. Sometimes, it already includes proper subtitles since it releases when all episodes were released.

My issue is that bazarr doesn't match this Sonarr behavior. It will only download a subtitle if the file or scene name matches **individually**. For some providers, it's not an issue, but for some it is. 
For example, Addic7ed doesn't have "bundled" subtitles for a complete season but Subscene does.

Here's a case where it was problematic :

1. The user selects to search for all episodes of Season 1 from "The Handmaids Tale"
2. Sonarr then grabs and downloads season pack "The.Handmaids.Tale.S01.1080p.BluRay.x264-YELLOWBiRD"
3. Bazarr grabs non-synced subtitles from OpenSubtitles which aren't "YELLOWBiRD".

In the end, Bazarr doesn't grab proper subtitles from Subscene because the one that match is a bundle :
https://subscene.com/subtitles/the-handmaids-tale-first-season/english/1733529

What would be the effort needed for Bazarr to provide an option to also look for subtitles bundles? 

Thank you

**Comment by morpheus65535** [comment]
Bazarr already look for subtitles pack (dependant of the providers of course). For Subscene, it is supported: https://github.com/morpheus65535/bazarr/blob/376d57e4e7abb1bd34e885bc13d9b77200637030/libs/subliminal_patch/providers/subscene.py#L91

Using manual search, does Bazarr return this subtitles pack in the search results?

**Comment by dalaverd** [comment]
It's surprising because it doesn't seem to find the wanted subtitles pack : 

![image](https://user-images.githubusercontent.com/4228254/72920328-0a071580-3d17-11ea-9d98-250c8d34813b.png)

Subscene works normally well for individual subtitles though.

**Comment by morpheus65535** [comment]
Please provide a debug log (previously emptied) while reproducing the issue.

**Comment by dalaverd** [comment]
[bazarr.log](https://github.com/morpheus65535/bazarr/files/4099800/bazarr.log)

**Comment by morpheus65535** [comment]
The LanguageReverseError is only the result, I can't see the cause in your log file as it doesn't happen during the time you reproduce the original behaviour.

As for the season pack, I see that Subscene doesn't return a single subtitle for your episode. I've tested on my side with something else and it works. I don't have anything to test the season pack unfortunately.
