### ISSUE TITLE
[RFE] - Ability to rename sub files (with country code)

### ISSUE THREAD

**Issue by MikeDawg** [morpheus65535/bazarr#765]
I would like to see the ability to rename, existing sub files, using the scheme provided by Bazarr.

The nearly equivalent of this practice is used in Sonarr, to rename the movie files, and in Radarr.

Just to clarify, if this RFE wasn't understood:

If I added a sub file, say, before I installed bazarr, then it will use the naming scheme of <movie name>.srt

After installing, and using bazarr, and uploading a subtitle, using bazarr, it will create subs with the naming scheme of:   <movie name>.<language/countrycode>.srt

It would be nice if there was some sort of renaming feature of bazarr, where it could go rename, the older subs, and include the language/country code, in the subtitle.

This is the difference between:

'Adventures in Babysitting (1987) [Bluray-720p].srt'
and
'Adventures in Babysitting (1987) [Bluray-720p].en.srt'

**Comment by morpheus65535** [comment]
Please see #525 .
