### ISSUE TITLE
Manual search - Download option is not working

### ISSUE THREAD

**Issue by lucianor** [morpheus65535/bazarr#766]
**Describe the bug**
When I want to manually search for a subtitle, I click on the Manual Search button, and it lists the multiple options from the two enabled providers I have (legendastv, opensubtitles). 
However, when I click the "Download" button next to an item, it shows the "Downloading subtitle" and return to the series episode list, but the subtitle is still showing as missing. 
Automatic search is working fine, so not a permission issue.
No file is created on the folder - checked that as well.
If legendastv is being used, I can see it drops the file inside the bazarr root folder (/opt/bazarr), probably because legendastv packs them in unrar.
An error is logged as well: "BAZARR No valid Subtitles file found for this file: /mnt/media/TVShows/The Night Manager/Season 1/The Night Manager - S01E03.mkv"

One thing to add: this was working in the past, and I haven't changed any configuration / folder permissions (chmod, chown, etc). The only change I made was installing Python 3 and changing the /etc/systemd/system/bazarr.service from:
ExecStart=/usr/bin/python /opt/bazarr/bazarr.py
To:
ExecStart=/usr/bin/python3 /opt/bazarr/bazarr.py
Reverting the change does not yield different results (besides getting the deprecration warning).
I keep Python 2 as the default for /usr/bin/python because of deluge in raspbian.

**To Reproduce**
1. Go to a series episode list, see that a subtitle is missing, and click on "manual search"
2. Click on download button, "Downloading subtitle" info is shown
3. Check back the series episode list, the subtitle that should have been download is still showing missing.
4. An error is logged: "An error is logged as well: "BAZARR No valid Subtitles file found for this file: /mnt/media/TVShows/The Night Manager/Season 1/The Night Manager - S01E03.mkv"

**Expected behavior**
After a manual search, selecting an item and downloading it should 1) mark the subtitle as downloaded on bazarr; 2) store the subtitle on the plex folder.

**Screenshots**
N/A

**Software (please complete the following information):**
Bazarr Version: 0.8.4
Sonarr Version: 2.0.0.5338
Radarr Version: 0.2.0.1450
Operating System: Linux-4.19.93-v7l+-armv7l-with-debian-10.2
Python Version: 3.7.3

**Additional context**
One thing to add: this was working in the past, and I haven't changed any configuration / folder permissions (chmod, chown, etc). The only change I made was installing Python 3 and changing the /etc/systemd/system/bazarr.service from:
ExecStart=/usr/bin/python /opt/bazarr/bazarr.py
To:
ExecStart=/usr/bin/python3 /opt/bazarr/bazarr.py
Reverting the change does not yield different results (besides getting the deprecration warning).
I keep Python 2 as the default for /usr/bin/python because of deluge in raspbian.

**Comment by morpheus65535** [comment]
Cannot reproduce. It's working perfectly fine for me. Please provide a debug log (emptied first) while reproducing the issue.

**Comment by lucianor** [comment]
There you have it:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/4103498/bazarr.log)

After looking at the log file, I tried downloading it from opensubtitles and it worked fine. The issue only applies to legendastv provider.

After looking at the log file, I see that the file is being download successfully but unpacking the rar file is failing (line 969 on the log):

```
23/01/2020 10:59:35|DEBUG   |subliminal_patch.core           |RAR Traceback: Traceback (most recent call last):
  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 259, in download_subtitle
    self[subtitle.provider_name].download_subtitle(subtitle)
  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/legendastv.py", line 258, in download_subtitle
    super(LegendasTVProvider, self).download_subtitle(subtitle)
  File "/opt/bazarr/bazarr/../libs/subliminal/providers/legendastv.py", line 515, in download_subtitle
    subtitle.content = fix_line_ending(subtitle.archive.content.read(subtitle.name))
  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 772, in read
    return f.read()
  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2010, in read
    raise BadRarFile("Failed the read enough data")
rarfile.BadRarFile: Failed the read enough data
```

So I manually downloaded the file and tried to unpack it directly on the command line. That worked fine.. so possibly an issue with the rar file unpacking?

```
pi@raspberrypi:~ $ wget https://ltv-backup.ams3.cdn.digitaloceanspaces.com/files/de/a6/legendas_tv_20160309144955000000.rar
--2020-01-23 11:36:30--  https://ltv-backup.ams3.cdn.digitaloceanspaces.com/files/de/a6/legendas_tv_20160309144955000000.rar
Resolving ltv-backup.ams3.cdn.digitaloceanspaces.com (ltv-backup.ams3.cdn.digitaloceanspaces.com)... 205.185.216.42, 205.185.216.10
Connecting to ltv-backup.ams3.cdn.digitaloceanspaces.com (ltv-backup.ams3.cdn.digitaloceanspaces.com)|205.185.216.42|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 123920 (121K) [binary/octet-stream]
Saving to: ‘legendas_tv_20160309144955000000.rar’

legendas_tv_20160309144955000000.rar  100%[=======================================================================>] 121.02K  --.-KB/s    in 0.03s

2020-01-23 11:36:31 (3.65 MB/s) - ‘legendas_tv_20160309144955000000.rar’ saved [123920/123920]

pi@raspberrypi:~ $ unrar e legendas_tv_20160309144955000000.rar

unrar 0.0.1  Copyright (C) 2004  Ben Asselstine, Jeroen Dekkers


Extracting from /home/pi/legendas_tv_20160309144955000000.rar

Extracting  The.Night.Manager.S01E03.1080p.HDTV.x264-MORiTZ.srt       OK
Extracting  The.Night.Manager.S01E03.1080p.WEB-DL.DD5.1.H.264-NM.srt  OK
Extracting  The.Night.Manager.S01E03.720p.WEB-DL.DD5.1.H.264-NM.srt   OK
Extracting  the_night_manager.1x03.720p_hdtv_x264-fov.srt             OK
Extracting  the.night.manager.s01e03.hdtv.x264-tla.srt                OK
Extracting  The.Night.Manager.S01E03.720p.iP.WEBRip.AAC2.0.H.264-BTW.srt OK
Extracting  Legendas.tv.url                                           OK
All OK
```

**Comment by morpheus65535** [comment]
Thank you for reporting those issues. Of course, I'll be happy to review a PR to fix them. :-)

**Comment by lucianor** [comment]
OK, I'll need to find some time to work through the feature request but I wonder if the bug could be identified and fixed?

**Comment by morpheus65535** [comment]
Sorry but which bug? Actually this provider use the first subtitles in archive. You proposed to do a PR to make it choose the best file. Is there a remaining issue other than that?

**Comment by lucianor** [comment]
Sorry I was not clear.

Yes, the issue is that when I select a subtitle for manual download from legendastv provider, it does not copy the file to the plex folder and the subtitle is still showing as pending on the bazarr UI.

This comment above describes in detail: https://github.com/morpheus65535/bazarr/issues/766#issuecomment-577711867

**Comment by morpheus65535** [comment]
I've just test again with `The 100 S06E13` and it works perfectly fine. I suppose there's something wrong with your archive.
