### ISSUE TITLE
HTTPError. Exception info: '403 Client Error: Forbidden for url:

### ISSUE THREAD

**Issue by savvasha** [morpheus65535/bazarr#767]
Now and then I am receiving the following error from some providers. Are they banning bazarr user-agent? If yes, is there a way to alter it?

Throttling subs4free for 10 minutes, until 20/01/22 16:44, because of: HTTPError. Exception info: '403 Client Error: Forbidden for url: https://www.sf4-industry.com/search_report.php?search=xxxxxxxxxx&searchType=1'
**Software (please complete the following information):**
 - Bazarr Version: 0.8.4
 - Sonarr Version: 2.0.0.5338
 - Radarr Version: 0.2.0.1450
 - OS: Linux-4.4.59+-x86_64-with

**Comment by morpheus65535** [comment]
They've implemented Captcha and are requiring it when user-agent start with Subliminal (which is the case for this provider. I've modified the user-agent to use Bazarr one but it's probably a temporary mesure and we'll have to implement anti-captcha for this provider. Let see if it works fine for now.

You can test it with dev image: `linuxserver/bazarr:development`.

**Comment by savvasha** [comment]
Great, thanks :)
