### ISSUE TITLE
After a path is changed in a source app, bazarr does not reflect the path change

### ISSUE THREAD

**Issue by ihithim** [morpheus65535/bazarr#768]
eg. in sonarr, a path is changed. Bazarr maintains the path at the point of import. 
'Series refreshes' do not update the path to the up to date location, nor is there any option in the 'edit series' modal to either force a path update or even manually edit the expected path and the series is listed with "path does not appear to be valid".

Ideally path changes would be picked up in series refreshes etc if the app realised the path was invalid.

**Comment by morpheus65535** [comment]
Should be fixed in dev branch. Can you test it?

**Comment by NimdaBE** [comment]
i have the same issue. it is resolved by removing the series from sonarr (without deleting the files), wait until bazarr removes it and then add it again in sonarr. The correct path is then also in bazarr. Sonarr will detect the files again and all is back to normal. Have not tested it yet with the dev branch...

**Comment by ihithim** [comment]
> Should be fixed in dev branch. Can you test it?

Sorry was away for some time. Works perfectly. Thanks!
