### ISSUE TITLE
development branch: titrari.ro provider doesn't work

### ISSUE THREAD

**Issue by fgordon-maker** [morpheus65535/bazarr#769]
**Describe the bug**
When subtitles are being searched using the "titrari.ro" website, an exception is thrown and the provider is throttled for 10 min.

**To Reproduce**
1. Configure titrari.ro provider
2. Search for any subtitle having the titrari.ro provider enabled.
3. The System tab - Providers sub-tab will show "TypeError" status in the titrari.ro provider.
4. The log file will contain the TypeError exception (see attached log excerpt)

**Expected behavior**
Search using titrari.ro to work

**Screenshots**
N/A

**Software (please complete the following information):**
 - Bazarr: v0.8.4 -  (development branch as of Jan 23, 2020, tag: "arm32v7-development")
 - Radarr version: 0.2.0.1450 - Dec 3 2019
 - Sonarr version: 2.0.0.5338 - Aug 15 2019
 - OS: docker (linuxserver/bazarr:arm32v7-development)

**Additional context**
N/A

Log file:
[bazarr_excerpt.log](https://github.com/morpheus65535/bazarr/files/4105592/bazarr_excerpt.log)

**Comment by morpheus65535** [comment]
@IIIspaceIII could you take a look?

**Comment by IIIspaceIII** [comment]
-fixed issue with pull request #770

**Comment by morpheus65535** [comment]
@fgordon-maker can you confirm it fixed your issue?

**Comment by fgordon-maker** [comment]
Yes. Thank you!
