### ISSUE TITLE
Issues running Windows 10 64-bit

### ISSUE THREAD

**Issue by oxman77** [morpheus65535/bazarr#77]
Hello,

I would like to emphasize that I am as noob as can be when it comes to python, so keep that in mind with my question.  Also, I hope that I am not overstepping by asking this.

I have followed the instructions from the wiki for windows (2.7.3). I could not get pip to work and tried to install separately but was unable.  I uninstalled all python and installed 2.7.9.  The wiki does say that 2.7 has to be used, so I think .9 is fine? I was able to continue on until starting bazarr. I typed "python bazarr.py" I then get:

C:\Program Files\bazarr>python bazarr.py
Traceback (most recent call last):
  File "bazarr.py", line 62, in <module>
    from bottle import route, run, template, static_file, request, redirect, response
ImportError: No module named bottle

When trying the last step for localhost:6767 I get refused.

I am sure that I am doing something wrong and any help would be greatly appreciated.

Thank you for your time!

**Comment by morpheus65535** [comment]
You're totally right, you can use any 2.7.x version of python (I'll change the wiki ASAP). PIP is unfortunately a requirement. You're going to have to make it work. The part where you install requirements.txt is where all required python module are installed. Your error is about bottle, the python framework used for Bazarr. It is installed with requirements.

**Comment by oxman77** [comment]
I see the requirements.txt, so somehow bottle is not installing? 

I am attaching the log file.

[pip.log](https://github.com/morpheus65535/bazarr/files/2091785/pip.log)

To be clear, .9 has pip built in, so it is working.

Thank you.

**Comment by oxman77** [comment]
Sorry, clicked the wrong button!!

**Comment by morpheus65535** [comment]
could you send me the return from "pip list" in a command line?

**Comment by morpheus65535** [comment]
You could try to update setuptools that seems to be old:

    python -m pip install --upgrade setuptools

**Comment by oxman77** [comment]
Before update:
pip (1.5.6)
setuptools (7.0

After::
pip (1.5.6)
setuptools (39.2.0)

Ran install again.  

Tried to start:
C:\Program Files\bazarr>python bazarr.py
Traceback (most recent call last):
  File "bazarr.py", line 62, in <module>
    from bottle import route, run, template, static_file, request, redirect, response
ImportError: No module named bottle

Updated log.

[pip.log](https://github.com/morpheus65535/bazarr/files/2092108/pip.log)

**Comment by morpheus65535** [comment]
Current pip version is 10.0.1...

    python -m pip install --upgrade pip

**Comment by oxman77** [comment]
Morpheus,
Thank you for your help, everything is up and working great.

Have a great day!
