### ISSUE TITLE
Hello I have this error 

### ISSUE THREAD

**Issue by romulusx76** [morpheus65535/bazarr#772]
Message
BAZARR error when trying to analyze this mkv file: /share/Videos/Series/American Horror Story/Season 4/American Horror Story - S04E01 - Monsters Among Us.mkv
Exception
Traceback (most recent call last):
 File "/share/CACHEDEV1_DATA/.qpkg/QBazarr/bazarr/bazarr/list_subtitles.py", line 39, in store_subtitles
  mkv = enzyme.MKV(f)
 File "/share/CACHEDEV1_DATA/.qpkg/QBazarr/bazarr/bazarr/../libs/enzyme/mkv.py", line 56, in __init__
  raise MalformedMKVError(\Parsing error: %s\ % e)
MalformedMKVError: Parsing error: Less than 1 bytes read (0)

**Comment by morpheus65535** [comment]
What version of Bazarr?

**Comment by romulusx76** [comment]
Version
3.0.3.688
Mono Version
5.20.1.19

**Comment by morpheus65535** [comment]
Why are you giving me your Sonarr version? I want to know Bazarr version.

**Comment by romulusx76** [comment]
ohh sorry

**Comment by romulusx76** [comment]
Bazarr version
0.7.3

**Comment by morpheus65535** [comment]
0.7.3 have been released in April 2019. We are now at 0.8.4. Please upgrade and re-open this issue if you still have problems.
