### ISSUE TITLE
subs4series, subz HTTPError

### ISSUE THREAD

**Issue by babos123** [morpheus65535/bazarr#773]
I am receiving the following errors:

Throttling subs4series for 10 minutes, until 20/01/25 06:42, because of: HTTPError. Exception info: '403 Client Error: Forbidden for url: https://www.subs4series.com/search_report.php?search=lady%20dynamite&searchType=1

Throttling subz for 10 minutes, until 20/01/25 06:42, because of: HTTPError. Exception info: '404 Client Error: Not Found for url: https://www.subz.xyz/typeahead/lady%20dynamite'

Propably same case with #767 issue

Bazarr Version:0.8.4.1
Sonarr Version:3.0.3.688
Radarr Version:3.0.0.2564
Operating System:Linux-4.15.0-72-generic-x86_64-with
Python Version:3.8.1

Just find that subz.xyz its closed so nothing to do with bazarr....
Or maybe had change url....dont know any other info

**Comment by evripidesk** [comment]
any news with this?

**Comment by babos123** [comment]
Maybe @pkoutsias can help here!

**Comment by morpheus65535** [comment]
Sorry O didn't had time this weekend to dive i to it. @pkoutsias you can check this one? Thanks!

**Comment by evripidesk** [comment]
Now and subs4free is not working 
Throttling subs4free for 10 minutes, until 20/01/29 15:41, because of: HTTPError. Exception info: '403 Client Error: Forbidden for url: https://www.sf4-industry.com/search_report.php?search=doctor%20sleep&searchType=1'

The link look ok

**Comment by morpheus65535** [comment]
@evripidesk subs4free have been fixed in dev branch.

**Comment by pkoutsias** [comment]
@morpheus65535 it seems that subz has shut down. I will remove it when I find time

**Comment by evripidesk** [comment]
Maybe replaced by this https://subztv.online/

**Comment by evripidesk** [comment]
Any news with subs4series?

**Comment by evripidesk** [comment]
Now for all movies with subs4free give the below error

BAZARR No valid Subtitles file found for this file

All other providers worked fine

**Comment by babos123** [comment]
for me both 
subs4free     HTTPError
subs4series  HTTPError

subz.xyz    propably closed

**Comment by morpheus65535** [comment]
@pkoutsias your help would be appreciated to fix those providers (and remove those not working anymore). Thanks!

**Comment by pkoutsias** [comment]
@morpheus65535 I'm too busy at the moment and cannot work on that. I will try this weekend to remove the closed provider and have a quick look at the other 2 for a quick fix.

**Comment by evripidesk** [comment]
Any luck with this?

**Comment by morpheus65535** [comment]
Merged to dev branch. Thanks @pkoutsias !
