### ISSUE TITLE
Bazarr claims port not available

### ISSUE THREAD

**Issue by jayschieber** [morpheus65535/bazarr#774]
Running inside docker container on Ubuntu 18.04, either latest or development branch, doesn't matter. I setup the container using:

docker create  --name=bazarr  -e TZ=America/Chicago  -e PGID=1000 -e PUID=1000  -v /etc/localtime:/etc/localtime:ro  -p 6767:6767  -v /home/me/configs/bazarr/config:/config  -v /media/virtual/Movies:/movies  -v /media/virtual/TV:/tv  --restart unless-stopped linuxserver/bazarr

It runs, but the web server is never accessible. Looking at the logs:

[services.d] starting services
[services.d] done.
/app/bazarr/bazarr/../libs/tzlocal/unix.py:141: SyntaxWarning: "is not" with a literal. Did you mean "!="?
Bazarr starting...
  while start is not 0:
2020-01-25 06:46:56,506 - root                             (7f05c4860d48) :  INFO (main:2259) - BAZARR is started and waiting for request on http://192.168.1.4:6767/
Traceback (most recent call last):
  File "/app/bazarr/bazarr/main.py", line 2261, in <module>
    server.start()
  File "/app/bazarr/bazarr/../libs/cherrypy/wsgiserver/__init__.py", line 2008, in start
    raise socket.error(msg)
OSError: No socket could be created -- (('192.168.1.4', 6767): [Errno 99] Address not available)

This looks like something else is using that port on the machine. But I kill the container and check all the ports with lsof, but nothing else shows up on 6767. I remove the container and remake it mapping port to 6768 with -p 6768:6767, but absolutely no change in behavior or logs.

**Comment by morpheus65535** [comment]
Nope, your issue is your trying to get Python listen on an address unknown inside the Docker container. 192.168.1.4 is your Docker host IP, not the container IP. Leave the listening IP to 0.0.0.0 as described in the wiki.

**Comment by jayschieber** [comment]
Yep, I see what happened now. I moved from running it on the sytem to within docker. When I copied the configuration over, config.ini was incorrect for which ip to listen to. Thanks!
