### ISSUE TITLE
DataTables warning: table id=logs - Ajax error

### ISSUE THREAD

**Issue by eltanque** [morpheus65535/bazarr#775]
Receiving this "browser" error when clicking on the system tab.
Bazarr Version: 0.8.4
Operating System: Windows-10-10.0.18362-SP0
Python Version: 3.8.0
Bazarr Directory: c:\bazarr
Bazarr Config Directory: C:\ProgramData\Bazarr
Chrome Version 79.0.3945.130 (Official Build) (64-bit)

**To Reproduce**
1. log in to bazarr
2. Click on "System"
3. See error. Pops up as a message from the browser
Full error message:
DataTables warning: table id=logs - Ajax error. For more information about this error, please see http://datatables.net/tn/7

when following the suggested steps to debug the error from the link: I find the following information:
Developer tools in chrome browser
Console: GET http://192.168.1.11:6767/logs?_=1580107506912 500 (Internal Server Error)

which eventually takes me to:
Error: 500 Internal Server Error
Sorry, the requested URL 'http://192.168.1.11:6767/logs?_=1580107506912' caused an error:
(screenshot attached)

Application won't load the log files

<img width="418" alt="Error" src="https://user-images.githubusercontent.com/25337285/73155085-a83b1700-412d-11ea-86c5-c4095a291e38.png">
<img width="986" alt="Error500" src="https://user-images.githubusercontent.com/25337285/73155090-ac673480-412d-11ea-90f9-314abfc70a99.png">

**Comment by eltanque** [comment]
A few more information
shutdown bazarr, deleted the (big/debug) log file, restarted PC (quicker than trying to figure out how to restart bazarr from windows) and error is gone.
But, enabled debug and did some manual subs search/download and the error is back. I guess it has to do with trying to load the debug log file to the browser.

**Comment by morpheus65535** [comment]
Can you provide your debug log file please?

**Comment by eltanque** [comment]
@morpheus65535 any way to send you the file privately?

**Comment by morpheus65535** [comment]
Discord PM

**Comment by morpheus65535** [comment]
I've pushed a fix to dev branch. Could you test it?

**Comment by eltanque** [comment]
On windows installer, I can only update from the master branch. Any instructions on how to get this dev branch, and also how to roll back?

**Comment by yenoromm** [comment]
I was experiencing this too, just hadn't gotten around to looking in to it. 8.4.1 fixes this issue for me.

**Comment by morpheus65535** [comment]
@eltanque no way other than stopping Bazarr and replace the modified file by the one from this commit in dev branch. Keep the original file to rollback.

**Comment by eltanque** [comment]
ok, but I need a bit more info in order to test.
1. which file do I need to download/replace and where do I find it
2. Can I install bazarr on a different PC and point it to the same Sonarr/Radarr in order to test this?
3. I know I can stop bazarr from the UI, but how do I restart it without having to restart the PC
This is on Win10
thx

**Comment by morpheus65535** [comment]
1. Replace `C:\Bazarr\bazarr\main.py` with this file: https://raw.githubusercontent.com/morpheus65535/bazarr/development/bazarr/main.py
2. Yes you can.
3. Using Windows Services console or in a command with administrative privileges `net start Bazarr`.

**Comment by eltanque** [comment]
ok, I've no idea what happened but:
Installed bazarr on a different machine (fresh download), copied all the config across. I'm going to assume it had the "old" main.py. So retraced my steps to reproduce the error, no error presented.
So decided to reproduce it again on my original machine. Redid the steps to get the error. Then stopped Bazarr, replaced main.py and then couldn't connect to the UI. The service started (at least that's what cmd and task manager was saying. Rebooted the machine and tried again, no luck. Service was running but couldn't connect to the UI. Stopped bazarr manually, replaced with the old main.py and restarted. Now I can't seem to reproduce the problem. 

PD: Just noticed my version is now 8.4.1 so I'm going to assume it has been fixed and maybe I was too late to test and provide this feedback. @morpheus65535  Appreciate the help and support regardless
Cheers

**Comment by morpheus65535** [comment]
I've merged changes to master last night so it confirm the fix is working. Enjoy!
