### ISSUE TITLE
UTF-8 characters changing on saving

### ISSUE THREAD

**Issue by dealelopez** [morpheus65535/bazarr#776]
In general setting, in the path for mapping folders if you insert special characters they are changed on saving so the path is not correct.

If the path contains _películas_, it changes for _pelÃ­culas_.

OS: Windows 10 Enterprise LTSC
Main language: Spanish
Version: 0.8.4

**Comment by morpheus65535** [comment]
What Bazarr version?

**Comment by dealelopez** [comment]
Sorry, I forgot to mention it. It's Bazarr Ver. 0.8.4

**Comment by morpheus65535** [comment]
I've pushed a fix to dev branch. Could you test it please? Unfortunately, you have to run from source to test it. If you installed with Windows Installer, you cannot change branch.

**Comment by dealelopez** [comment]
I used the Windows installer. What can I do?

**Comment by morpheus65535** [comment]
You can stop Bazarr and replace `C:\Bazarr\view\settings.tpl` with this file and restart Bazarr: https://raw.githubusercontent.com/morpheus65535/bazarr/development/views/settings.tpl

Keep a backup of the original file just in case.

**Comment by dealelopez** [comment]
It's working perfect.

Thanks a lot!
