### ISSUE TITLE
Cannot install required pkg on FreeNAS

### ISSUE THREAD

**Issue by Kenshin9977** [morpheus65535/bazarr#779]
The required pkg py37-libxslt as specified in the wiki isn't found.

- Under the Jail section I add a Jail, name it Bazarr with the release 11.2-RELEASE-p9, DHCP IPv4 and VNET then start it.

- I open a shell within the jail and type

`pkg install py37-libxslt`

- I get the following message

> pkg: No packages available to install matching 'py37-libxslt' have been found in

When normally the pkg should be installed.

I tried it on FreeNAS FreeNAS-11.2-U2.1

**Comment by morpheus65535** [comment]
@Kenshin9977 I have no idea what's the exact name of this package and I don't have FreeNAS. If you find the required package, please inform me so I can update the wiki.

**Comment by Kenshin9977** [comment]
Found it, it's  `libxslt` instead of `py37-libxslt`

**Comment by morpheus65535** [comment]
Thanks, I've modified the wiki.
