### ISSUE TITLE
Default settings for new series

### ISSUE THREAD

**Issue by morpheus65535** [morpheus65535/bazarr#78]
When a new series is imported from Sonarr, Bazarr does not take any action until the user manually sets what language options they want.

It would be great to have a default setting that gets automatically applied to any new series that get imported.

-----------------------------------
Asked by peskdale on feathub.

**Comment by Sharmii** [comment]
Same for movies would be great :-)

**Comment by morpheus65535** [comment]
Of course! :-)

**Comment by morpheus65535** [comment]
Could be tested in dev branch. Please give me feedback!

**Comment by peskdale** [comment]
Can't test for Radarr without downloading a new movie, which I'm not in a position to do at the moment.

Tested for Sonarr, in both normal and single language modes.

One bug I encountered (which upon further testing is also present in the current master): with single language mode enabled, I can still select multiple languages in Settings > Subliminal. This can result in one being set (and apply) multiple default langauges for a new series/movie, despite being in the single language mode.

The below screenshot illustrates an example of settings I was able to incorrectly set and apply:
![image](https://user-images.githubusercontent.com/5855217/41993494-96fb6c2c-7a43-11e8-8430-c00b8ba2804f.png)

**Comment by morpheus65535** [comment]
You are right, I missed this one. I’m going to empty serie and movie languages when single language is enabled. User will need to fill again this field in this case. Seems ok to you?

**Comment by peskdale** [comment]
Sounds good

**Comment by morpheus65535** [comment]
Thanks, I’ll code this tonight or tomorrow.

**Comment by morpheus65535** [comment]
Should be all good now.

**Comment by peskdale** [comment]
Tested - all good! :)

**Comment by peskdale** [comment]
Testing... will update shortly

**Comment by morpheus65535** [comment]
Thanks a lot!

**Comment by morpheus65535** [comment]
Merged to master.
