### ISSUE TITLE
Bazarr can't connect to a Sonarr/Radarr with log form enabled

### ISSUE THREAD

**Issue by Kenshin9977** [morpheus65535/bazarr#780]
In Sonarr/Radarr if you go to Settings, General, Security, Authentication and select Forms (Login page) you then need a login and password to access Sonarr/Radarr.
When doing that Bazarr fails the connection test.
When selecting the Authentication method "None" there are no issue.
Tried with Bazarr v0.8.4 in a jail under FreeNAS-11.2-U2.1

**Comment by morpheus65535** [comment]
Sonarr/Radarr connection testing is done through API and have nothing to do with form logging. You clearly having something else that impact the result of the test.
