### ISSUE TITLE
Pushover notifications not working

### ISSUE THREAD

**Issue by Kenshin9977** [morpheus65535/bazarr#781]
In the notifications section when enabling Pushover I type the following string :
`pover://{PUSHOVER_USER_KEY}@{PUSHOVER_API_KEY}`
The keys are working as I tested those with Sonarr
In Bazarr when clicking on "Test notification" I don't get any notification.

Might have its place on the apprise' Github, you'll tell me.

Tried with Bazarr v0.8.4 in a jail under FreeNAS-11.2-U2.1

**Comment by morpheus65535** [comment]
I can confirm the issue.

@caronc could you confirm if this issue is confirmed for you to?

**Comment by caronc** [comment]
Hi guys,

Unfortunately i can't confirm this issue.  It's working great for me right now.  Perhaps this is something you can test from the command line?  Consider adding `-vvvv` to the output to see where it might be going wrong for you?  Or is there a way to get extra debugging information through Bazarr?

Here is a screenshot of a few test messages I just sent to myself now (using Apprise):
![Screenshot_20200128-180240](https://user-images.githubusercontent.com/850374/73313237-a8ecaf80-41f8-11ea-980d-5d908eb67b55.png)

The syntax I used was:
```bash
# using Apprise v0.8.3:
# the line in the pushover.cfg file was:
#  pover://private_token@private_token
# -vvvv added extreme verbosity which didn't turn out to be needed
# as I received the messages okay.
apprise -c pushover.cfg \
    -b "not sure..."  -t "Bug might be specific to Bazarr?" -vvvv
```

Thoughts?

**Comment by morpheus65535** [comment]
@caronc thanks for taking the time to test it. I' run another test myself without changing anything and I can confirm __it is working__ perfectly fine.

@Kenshin9977 can you provide a debug log while reproducing the issue?

**Comment by Kenshin9977** [comment]
Of course, I get the following log when I click "Test notification"

> Unparseable URL pover://{USER_KEY}@{API_KEY}.

**Comment by morpheus65535** [comment]
What browser do you use? It looks like your browser is blocking some informations from being send to Bazarr.

**Comment by caronc** [comment]
Also double check your `{user_key}` and `{token}`, they should be each 30 characters long....
Your URL should look something like this:
`pover://usDhcKZiX6PwLwRx6wej39jCg6uSWB@a9JJtgWrf1PLEJUewubWtHW5Uk2MdL`

**Comment by Kenshin9977** [comment]
I'm really ashamed...
I left the '{' '}' believing they were necessary.
Sorry for the trouble guys

**Comment by morpheus65535** [comment]
No problem! Thanks @caronc  :-)
