### ISSUE TITLE
Upgrade previously downloaded Subtitles error

### ISSUE THREAD

**Issue by lukjod** [morpheus65535/bazarr#789]
Recently i got such error on:

Bazarr Version:
0.8.4.1
Sonarr Version:
2.0.0.5338
Radarr Version:
0.2.0.1450
Operating System:
Linux-4.14.24-qnap-x86_64-with
Python Version:
3.8.1
Bazarr Directory:
/app/bazarr
Bazarr Config Directory:
/config

`Job "Upgrade previously downloaded Subtitles (trigger: interval[12:00:00], next run at: 2020-01-31 21:24:57 CET)" raised an exception`
`Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/bazarr/get_subtitle.py", line 1091, in upgrade_subtitles
  if movie[\language\] in forced_languages:
TypeError: argument of type \NoneType\ is not iterable`

**Comment by morpheus65535** [comment]
Should be fixed in dev branch. Thanks for reporting!
