### ISSUE TITLE
2 languages

### ISSUE THREAD

**Issue by estimadarocha** [morpheus65535/bazarr#795]
Is it normal that if selected more than one language for example ptpt or ptbr it appears like not completed until both are downloaded? Shouldnt the logic be one or the other and not one and the other? 
And if the logic is really one and the other can we have a switch to have the option to select between modes? 

Just like sonarr and radarr when picking 720p and 1080p as soon as it grab 720 it continues to collect until it got 1080p but if it grabs 1080p it doesnt look more for 720. We should have something similar here for subs I believe. Thanks

**Comment by morpheus65535** [comment]
This as been asked before and would require to have languages profiles in Bazarr. There's no plan for that in current version. Maybe post v1.0.
