### ISSUE TITLE
Disk write regression in Bazarr 8.4.1

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#796]
With the latest release 8.4.1 the disk write has increased a lot. In the debug log I see a lot of `UPDATE table_shows .....` but I'm not sure if this is the cause. In the following graphs you can see the disk usage before and after the update.

![image](https://user-images.githubusercontent.com/10577978/73591091-8b666100-44ea-11ea-8f0c-fcbc45b35f97.png)

**Comment by morpheus65535** [comment]
Please provide a debug log.

**Comment by ngosang** [comment]
[bazarr(2).log](https://github.com/morpheus65535/bazarr/files/4142743/bazarr.2.log)

**Comment by morpheus65535** [comment]
I've just pushed a fix to dev branch. Could you please test it and confirm if it fix the disk write regression?

**Comment by ngosang** [comment]
It's fixed with https://github.com/morpheus65535/bazarr/commit/3ff4518b4ae837b490a8f63e091754d821eb33b1 I don't know if https://github.com/morpheus65535/bazarr/commit/d0d8388d9f2be1c021c9ee8c42c8bdd8fe4e738e fixes other issues, but it's working.
Updated to develop branch at 6:20
![image](https://user-images.githubusercontent.com/10577978/73775063-76f1c500-4785-11ea-88ff-e490491ae008.png)

**Comment by morpheus65535** [comment]
Thanks! The additional fix was to make sure it stay compatible with Python 2.7.x and that the same issue won't happen with movies.
