### ISSUE TITLE
Provider legendas.tv issue: "ValueError. Exception info: 'Not a valid archive"

### ISSUE THREAD

**Issue by v9999** [morpheus65535/bazarr#797]
**Describe the bug**
It looks like legendas.tv, the major portuguese-brazilian sub provider, is not working properly. It's now returning this error message: "Throttling legendastv for 10 minutes, until 20/02/02 11:04, because of: ValueError. Exception info: 'Not a valid archive".

Could this be API limiting?

I wonder if it would be possible to add http://legendaoficial.net/ to the provider list. It's another site focused on brazilian portuguese subs that does not require login and that has a better search engine.

**To Reproduce**
Just try searching subtitles in bulk in bazarr.

**Expected behavior**
Should download all the available releases.

**Software (please complete the following information):**
Everything is up to date docker images, running on a Raspberry Pi 4.

**Comment by morpheus65535** [comment]
It's working perfectly fine for me. From time to time, you can get a corrupted archive. Try another subtitles.

**Comment by GermanG** [comment]
Sorry for reviving this. But while discussing #834 this issue came to my mind.
@v9999 do you have unrar and unzip installed? That might be the issue.

Regards.

**Comment by v9999** [comment]
> Sorry for reviving this. But while discussing #834 this issue came to my mind.
> @v9999 do you have unrar and unzip installed? That might be the issue.
> 
> Regards.

Hello there, I have both installed. Nowadays I use legendas.tv alongside opensubtitles, so things seem to be working without issues.
