### ISSUE TITLE
Reduce memory usage: langdetect library

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#799]
I have been investigating memory usage in Bazarr. My NAS has very low resources and noticed that Bazarr is using too much memory for my system. When Bazarr starts, the memory usage is high but comparable to other apps with similar features. The problem comes when the task `Update all Episode Subtitles from disk` is launched.
![image](https://user-images.githubusercontent.com/10577978/73695609-c4652800-46da-11ea-81e0-b2b2517da20a.png)
There is an increase of 70 MB of RAM caused by this line => https://github.com/morpheus65535/bazarr/blob/376d57e4e7abb1bd34e885bc13d9b77200637030/bazarr/list_subtitles.py#L387 The langdetect library preloads 70 MB of dictionaries in memory, and it stores them in a global variable forever => https://github.com/morpheus65535/bazarr/blob/376d57e4e7abb1bd34e885bc13d9b77200637030/libs/langdetect/detector_factory.py#L121

**Replace langdetect with other library**
There are other libraries with the same capabilities. I suppose that some of them will have lower memory footprint. This list can be a good start => https://stackoverflow.com/a/47106810
If I find another library with lower memory usage are you willing to replace langdetect?

**Software (please complete the following information):**
 - Bazarr: 0.8.4.1

**Comment by morpheus65535** [comment]
Thanks, I appreciate the PR. I'll test it and see how it goes.

**Comment by morpheus65535** [comment]
Appreciate the help mate! :-)

**Comment by ngosang** [comment]
@morpheus65535 The memory fix is working fine. I launched all tasks several times manually and the memory is 90 MB less than before.
![image](https://user-images.githubusercontent.com/10577978/73776442-039d8280-4788-11ea-9607-80eb6eb8536b.png)
About the other concerns in #800 I can't say. All is working in my installation.
