### ISSUE TITLE
Provider Legendasdivx imdb search

### ISSUE THREAD

**Issue by crypto-vault** [morpheus65535/bazarr#801]
Newly added provider Legendasdivx also supports imdb search.

This could be implemented alongside with fulltext search.

Example:

https://www.legendasdivx.pt/modules.php?name=Downloads&d_op=search&imdbid=2584384

**Comment by morpheus65535** [comment]
@GermanG are we using imdbid when searching? If not could it be added?

**Comment by GermanG** [comment]
No, and yes. :) I'll add it to my ToDo list.

**Comment by GermanG** [comment]
Well, is not that simple, looks like the html we got back when looking for imdb is not even close to the fulltext one, so basically we need another scrapping logic for it.
Anyway I see the value of having an imdb id search for accuracy (all movies with sequels/prequels will have a better result set), but I'll need to invest more time into it.

**Comment by morpheus65535** [comment]
Thanks for this temporary improvement! Keep the imdb stuff on your to-do list for your next free time. ;-)

**Comment by GermanG** [comment]
Quick note (I'm adding it here to let @crypto-vault verify it)
https://www.legendasdivx.pt//modules.php?name=Downloads&file=jz&d_op=search&op=_jz00&query=tt2584384
Seems to provide the same html and it works with imdb ids

**Comment by crypto-vault** [comment]
@GermanG that seems to work.

**Comment by GermanG** [comment]
I've pushed the change to my repo/branch, I'll make a PR as soon as I test it.

**Comment by morpheus65535** [comment]
Should be fixed now. @crypto-vault could you test dev branch?

**Comment by crypto-vault** [comment]
@morpheus65535 Tested dev branch and it worked flawlessly downloading additional subtitles (also confirmed via debug logs)
