### ISSUE TITLE
All paths not valid

### ISSUE THREAD

**Issue by mobamoba** [morpheus65535/bazarr#804]
**Describe the bug**
Every single path listed as not valid (even though they all are).

**Software (please complete the following information):**
 - Bazarr: .8.4.1
 - OS: Windows and using Windows version of Bazarr

Here are some screenshots:
<img width="888" alt="Untitled" src="https://user-images.githubusercontent.com/11135869/74050926-f90c0480-49a4-11ea-90b2-fccf30794c70.png">

Error when searching for a sub:
Traceback (most recent call last):
 File "c:\\bazarr\\bazarr\\get_subtitle.py", line 69, in get_video
  video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,
 File "c:\\bazarr\\bazarr\\../libs\\subzero\\video.py", line 61, in parse_video
  return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,
 File "c:\\bazarr\\bazarr\\../libs\\subliminal_patch\\core.py", line 542, in scan_video
  video.size = os.path.getsize(hash_path)
 File "C:\\Bazarr\\WinPython\\python-3.8.0\\lib\\genericpath.py", line 50, in getsize
  return os.stat(filename).st_size
FileNotFoundError: [WinError 3] The system cannot find the path specified: \R:\\\\Sorted\\\\Project Runway\\\\Season 18\\\\Project Runway - 18x01 - Episode 1.8bit.mkv\

But as you can see the path exists:

<img width="617" alt="Untitled" src="https://user-images.githubusercontent.com/11135869/74051080-4ee0ac80-49a5-11ea-86a4-d849c3355026.png">

**Comment by morpheus65535** [comment]
RTFM...
https://github.com/morpheus65535/bazarr/wiki/FAQ-Common-Problems#this-path-doesnt-seems-to-be-valid

**Comment by mobamoba** [comment]
I did. I'm not running under a System service account and I already tried switch to UNCs and got the same error.

**Comment by morpheus65535** [comment]
Does it work if you run Bazarr using a command prompt opened as you current user?

**Comment by morpheus65535** [comment]
If you have used the Windows Installer, you are running as a service.

**Comment by morpheus65535** [comment]
https://docs.microsoft.com/en-us/windows/win32/services/services-and-redirected-drives

Do not use mapped drive for services. Even Microsoft say it... you need to use UNC path.

**Comment by mobamoba** [comment]
Okay when I tried before I tried first doing UNC paths (didn't work) then reset back to mapped drive and changed system account on the service to my actual account (also didn't work).

The thing that ended up working - and perhaps this is what the manual meant but if so I didn't understand it - was that you have to both, i.e. change System account AND map to UNC paths within Bazarr. I thought it was just one or the other but in my case it needed both.

**Comment by morpheus65535** [comment]
You need both.

**Comment by mobamoba** [comment]
Yes I misunderstood the manual link when I read it.
