### ISSUE TITLE
Unable to set subtitle language.

### ISSUE THREAD

**Issue by vegovs** [morpheus65535/bazarr#808]
**Describe the bug**
Unable to set subtitle language. Even tried changing config.ini and restarting but to no help.

"Subtitles / Subtitles languages / Enabled languages" must have at least one enabled language

**To Reproduce**
Install, setup. 

**Expected behavior**
Set language, no error message i.e: "Subtitles / Subtitles languages / Enabled languages" must have at least one enabled language

**Screenshots**
N\A

**Software (please complete the following information):**
 - Bazarr: Latest
 - Radarr version Latest
 - Sonarr version Latest
 - OS: Ubuntu 18.4

**Comment by morpheus65535** [comment]
Where are you getting this validation error? In wizard or settings?

**Comment by lehai730** [comment]
Just tried installing Bazarr today, I think I am facing this issue. I was trying to set things up from the wizard but there's no Languages from the dropdown menu in the series default settings.

![image](https://user-images.githubusercontent.com/11548860/74083615-7b3a1d00-4aba-11ea-8150-6a525f286da6.png)

**Comment by vegovs** [comment]
Apologies for the poor issue ticket, but is was in the wizard. While the languages are available in the dropdown "Enabled Languages", after saving the alert ""Subtitles / Subtitles languages / Enabled languages" must have at least one enabled language" shows at the top in the main menu.

**Comment by morpheus65535** [comment]
Guys, it work perfectly fine. You're trying to set a default desired language while the error say to set enabled languages. The field is in red in the screenshot above...

**Comment by lehai730** [comment]
you're right, I feel stupid now..Thanks for clearing that up.

**Comment by vegovs** [comment]
Nope, not me. The languages i set in Enabled Languages does not get saved while saving.

**Comment by vegovs** [comment]
Porly described issue.

**Comment by 2fst4u** [comment]
I don't understand why this issue has been closed. I have the same problem. Trying to set the subtitle languages enabled and it won't save. I can select the language I want, select it for the default for movies and shows, click "save" and it just doesn't save it.

**Comment by morpheus65535** [comment]
@2fst4u Just tested it and it works perfectly fine. Where did you install Bazarr? Looks like a permission issue while trying to write config or database to disk...

**Comment by 2fst4u** [comment]
FreeBSD instructions in the readme. I needed to give the bazarr folder more
permissions because the instructions weren't completely clear.

Which file or directory will it be having trouble saving to specifically?

**Comment by morpheus65535** [comment]
If you've followed the instructions of the wiki: https://github.com/morpheus65535/bazarr/wiki/Installation-FreeBSD

You need to make sure that the Bazarr user have recursive write access to `/usr/local/bazarr`.
