### ISSUE TITLE
REQ: Run movie search first

### ISSUE THREAD

**Issue by crypto-vault** [morpheus65535/bazarr#809]
Since typically there are more episodes Bazarr can't find subtitles for than movies, it exhausts providers limits, so when it reaches movies search some providers are already with a Next Retry time set.

If movies search was ran first, or an option to prioritize movies instead of series it would get more results for movies.

Another option would be to split search wanted subtitles task in two, for movies and series, so we could have different Execution Frequency for each.

**Comment by morpheus65535** [comment]
#525
