### ISSUE TITLE
False positive subtitles.

### ISSUE THREAD

**Issue by vegovs** [morpheus65535/bazarr#815]
**Describe the bug**
Bazarr claiming to have subtitles that does not exist. Tried to delete db and rebuild, same issue appeared. 

**To Reproduce**
Install, link to Sonarr, Radarr etc. 

**Expected behavior**
Not list non-existing subtitles. 

**Screenshots**
![image](https://user-images.githubusercontent.com/24651433/74171857-82366c00-4c2f-11ea-8a39-182b8d386d02.png)
![image](https://user-images.githubusercontent.com/24651433/74171915-9da17700-4c2f-11ea-993d-eb1c627baa58.png)

**Software (please complete the following information):**
 - Bazarr: Latest from Master.
 - Radarr version Latest from Master.
 - Sonarr version Latest from Master.
 - OS: Linux 18.04

**Comment by morpheus65535** [comment]
Those are subtitles embedded in mkv container. If you don't want to see them, disable `use embedded subitles` in Settings-->Subtitles.
