### ISSUE TITLE
betaseries : display file name

### ISSUE THREAD

**Issue by pbossert** [morpheus65535/bazarr#816]
Hi,

The betaseries api is providing the file name of the subtitles in which the version is very often present, it will be so much easier to get the right subtiles.
Could the file name be displayed in the table when you manual search a subtitle for an episode ? or maybe in the releases column ?

![image](https://user-images.githubusercontent.com/60900149/74189805-5c21c380-4c51-11ea-8382-f7fb3b69c457.png)

Thx in advance

**Comment by morpheus65535** [comment]
Isn't it already in the `Releases` column?

@Mexx62 could you take a look please?

**Comment by pbossert** [comment]
Hi,

Thanks for the quick reply (et merci pour ce logiciel ;))

The Releases is empty (n/a)

![image](https://user-images.githubusercontent.com/60900149/74220461-f6b0ef80-4caf-11ea-87e1-b4289bc88976.png)

**Comment by Mexx62** [comment]
I'll take a look at it.  
To summarize, I need to fetch the subtitle filename and put it in the releases column of the manual search modal?

**Comment by pbossert** [comment]
> I'll take a look at it.
> To summarize, I need to fetch the subtitle filename and put it in the releases column of the manual search modal?

Yes it would be great ;)
You already parse the filename in the betaseries.py provider (video_name field)
```
for sub in subs:
            language = _translateLanguageCodeToLanguage(sub['language'])
            if language in languages:
                # Filter seriessub source because it shut down so the links are all 404
                if str(sub['source']) != 'seriessub':
                    subtitles.append(BetaSeriesSubtitle(
                        sub['id'], language, **sub['file']**, sub['url'], matches, str(sub['source'])))
```

**Comment by GermanG** [comment]
@pbossert a quick hack I can think of (for you to test is)
```
--- a/libs/subliminal_patch/providers/betaseries.py
+++ b/libs/subliminal_patch/providers/betaseries.py
@@ -44,6 +44,10 @@ class BetaSeriesSubtitle(Subtitle):
     def download_link(self):
         return self.download_url
 
+    @property
+    def release_info(self):
+        return self.video_name
+
     def get_matches(self, video):
         matches = self.matches
```

**Comment by pbossert** [comment]
> @pbossert a quick hack I can think of (for you to test) is:
> 
> ```
> --- a/libs/subliminal_patch/providers/betaseries.py
> +++ b/libs/subliminal_patch/providers/betaseries.py
> @@ -44,6 +44,10 @@ class BetaSeriesSubtitle(Subtitle):
>      def download_link(self):
>          return self.download_url
>  
> +    @property
> +    def release_info(self):
> +        return self.video_name
> +
>      def get_matches(self, video):
>          matches = self.matches
> ```

C'ant really try this, I'm using the linuxserver/bazarr docker container on unraid :)

**Comment by GermanG** [comment]
@pbossert no problem, I'll test it this weekend myself then.

**Comment by morpheus65535** [comment]
Fixed in dev branch by @GermanG. Thanks!

**Comment by pbossert** [comment]
updated my container to the development version and it works like a charm !
thanks @morpheus65535 @GermanG @Mexx62
