### ISSUE TITLE
Support both .eng.srt and .eng.sdh.srt?

### ISSUE THREAD

**Issue by splerman** [morpheus65535/bazarr#819]
I'm new to Bazarr. For my series/movies, I typically store BOTH the regular english (.eng.srt) and the hearing-impaired english (.eng.sdh.srt).

I haven't found a way to have Bazarr download both versions and name them correctly.

Also, when scanning my folders, it shows the en version as found, but it doesn't show the .eng.srt version as any language.

Suggestions? Solutions?

Thanks!

**Comment by halali** [comment]
That subs are probably embedded in series/movie file

**Comment by splerman** [comment]
Sorry, I don't understand. These are not embedded subs. They are Subrip (.srt) files that are stored alongside the media file. Thus, I have three files: Movie.mp4, Movie.eng.srt, Movie.eng.sdh.srt. If I scan the folder with Bazarr, it shows me that an "en" file exists. It does not show anything for the hearing-impaired (.sdh.srt) file. If I have a .eng.srt file but no .eng.sdh.srt file, I'd like to be able to grab the hearing-impaired subtitle and store it as Movie.eng.sdh.srt...and vice versa.

**Comment by morpheus65535** [comment]
.sdh isn't an official naming convention. In fatc, there's no convention for hearing-impaired subtitles file naming. You can see Plex wiki about that: https://support.plex.tv/articles/200471133-adding-local-subtitles-to-your-media/

Bazarr doesn't support having normal and hearing-impaired subtitles file for the same language code.
