### ISSUE TITLE
Unable to disable download for series in single-language mode

### ISSUE THREAD

**Issue by peskdale** [morpheus65535/bazarr#82]
In single-language mode, I am unable to tell Bazarr that I no longer want to download subtitles for a series using the below dialogue:

![image](https://user-images.githubusercontent.com/5855217/41406773-468d418a-6fc5-11e8-954a-183c450db729.png)

A 'None' option needs adding to the dropdown, similar to how the batch series editor works:

![image](https://user-images.githubusercontent.com/5855217/41406972-ddd121a6-6fc5-11e8-88fb-c4a23a5c8d1a.png)

**Comment by morpheus65535** [comment]
Fix commited to dev branch. Can you test it please?

**Comment by morpheus65535** [comment]
Merged in master.

**Comment by peskdale** [comment]
Afraid I can't test at the moment as I've lost remote access to my server. Will verify when I next have access.

**Comment by morpheus65535** [comment]
No problem!

**Comment by peskdale** [comment]
Confirmed working in episodes view. Change need to be made to the same dropdown in `views/series.tpl` as well.

**Comment by morpheus65535** [comment]
Done, will be merge to master soon. Thanks!
