### ISSUE TITLE
No subtitles found via the provider Zimuku

### ISSUE THREAD

**Issue by yimingzhaomath** [morpheus65535/bazarr#820]
**Describe the bug**

I tried to download Chinese subtitles from the provider Zimuku. But I am not getting *any* results back. As an example, I tried with Doctor Who S12E07. The filename on my drive is: doctor.who.2005.s12e07.1080p.hdtv.h264-mtb.mkv. A manual search on the Zimuku website shows availability of a matching subtitle (a complete match of the filename actually).

This is most likely a provider-specific issue, since the same setup returns English subtitles from opensubtitles. However, as I stated, Zimuku is not returning anything for any media files. 

**To Reproduce**
Just try to download any Chinese subtitle from Zimuku

**Expected behavior**
Bazarr should have picked up the subtitle. But it's not.

**Screenshots**

<img width="1107" alt="Screen Shot 2020-02-13 at 5 44 12 PM" src="https://user-images.githubusercontent.com/13087183/74485328-83160a80-4e88-11ea-9199-f73898b59a4d.png">

No result according to Bazarr.

<img width="1256" alt="Screen Shot 2020-02-13 at 5 48 14 PM" src="https://user-images.githubusercontent.com/13087183/74485617-26ffb600-4e89-11ea-974a-6e8f2a4ca589.png">

It should be available.

**Software (please complete the following information):**
 - Bazarr: 0.8.4.1
 - Radarr version v0.2.0.1450
 - Sonarr version v3.0.3.698
 - OS: Ubuntu 18.04.3

**Additional context**
Relevant debug log is here: https://pastebin.com/raw/KbMsH39T

**Comment by GermanG** [comment]
Is this related to #783 ?

**Comment by yimingzhaomath** [comment]
Yes, I am guessing it's the same issue.
