### ISSUE TITLE
invalid path

### ISSUE THREAD

**Issue by BMooren** [morpheus65535/bazarr#824]
Hi all,

Just set up bazarr in docker following the wiki. When i want bazarr to search for subtitles, it states that for both sonarr and radarr 'this path doesn't seem valid'. 
![invalid path bazarr](https://user-images.githubusercontent.com/19759227/74593428-84cc0380-502b-11ea-8f51-2d4d58b86c99.jpg)
![invalid path bazarr series](https://user-images.githubusercontent.com/19759227/74593434-8dbcd500-502b-11ea-99ca-258e8af2c198.jpg)

docker mapping: 
![docker bazarr](https://user-images.githubusercontent.com/19759227/74593756-0c674180-502f-11ea-8abf-4e41459d8da2.jpg)

path mapping in bazarr: 
![path mappings](https://user-images.githubusercontent.com/19759227/74593758-0ec99b80-502f-11ea-932f-4c486e837e2c.jpg)

can't seem to figure out what i did wrong. 
Anyone who can help?

**Comment by morpheus65535** [comment]
https://github.com/morpheus65535/bazarr/wiki/FAQ-Common-Problems#this-path-doesnt-seems-to-be-valid

Come to Discord for support please.
