### ISSUE TITLE
Is possible to call bazarr from API?

### ISSUE THREAD

**Issue by Jorman** [morpheus65535/bazarr#825]
Hi, the idea behind is pretty simple, instead of Update Series list from Sonarr every 60sec and from sonarr every 5 minutes, is not possible to make 2 simple script to put on sonarr/radarr side and trigger it On import and On upgrade?
In this way every time radarr/sonarr upgrade or download a media file, tell to bazarr that some has changed and a rescan is needed.

Sounds so bad?

J

**Comment by morpheus65535** [comment]
The problem with this is that you would have to use webhook on Sonarr side for that and it doesn't announce series related action, only those related to episode. Bazarr won't be advised of new series. I still have on my back log to give the option to customize those default delay.

**Comment by Jorman** [comment]
Hi, thanks for reply.
I start from end, IMHO the best is to have the possibility to customize the delays and the possibility to trigger the update via API/dedicate page, like I can send a post to
`http://BAZARR_IP:PORT/Update_Sonarr (to update sonarr)`
`http://BAZARR_IP:PORT/Update_Radarr (to update radarr)`

Just to talk:
It's true what you say but is also true that you can trigger the script even on grabbing phase.
Btw, in general is true that in this way you don't have the "right now" situation from sonarr/radarr, but is also true that as soon as the script is triggered from sonarr/radarr the situation will update.
Ideally there're 2 possibilities:
1. By default, you add all with `Default Enabled` option and in this case you have to do nothing more, because when bazarr refresh all new movie/tv show,
2. You select what monitor, so until you can't see the new show/movie until the script is triggered, so you want to monitor that movie/show, you've to manually select it. Unless, you can read tags from radarr/sonarr, but is another story, lol.

So, what do you think?

**Comment by morpheus65535** [comment]
Actually, there isn't an official API in Bazarr. I have plan to add one in 0.9 but we're not there yet.

TBH, I have in mind of decoupling from Sonarr/Radarr to become a fully standalone software. In that case, we won't even call Sonarr or Radarr to get new media. That's the reason why I think that the MVP for that would be to just give the opportunity to the user to customize the sync frequency.

**Comment by Jorman** [comment]
I agree with you, if you think that you want to decouple Sonarr/Radarr, make no sense this idea and your solution is quite the best one.
We will see!

Thank you and thanks for your attention/works

**Comment by GermanG** [comment]
@morpheus65535 Sorry for jumping in, do you have any place you've put your thoughts/plans for bazaar future? That'd be interesting.

**Comment by morpheus65535** [comment]
@GermanG nothing else than the features requests page.

**Comment by Dr0bac** [comment]
I, who don't like to keep movies in my radarr after they are downloaded welcome your decision to make bazarr independent.
