### ISSUE TITLE
Error saving settings for legendasdivx

### ISSUE THREAD

**Issue by staterium** [morpheus65535/bazarr#826]
**Describe the bug**
When using the setup Wizard, when trying to save I was getting an error that a settings could not be retrieved. They are

settings_legendasdivx_username
settings_legendasdivx_password

**To Reproduce**
Install v 0.8.4.1
Complete Setup Wizard
Click Save

**Expected behavior**
Settings are saved

**Software (please complete the following information):**
 - Bazarr: 0.8.4.1
 - Radarr version N/A
 - Sonarr version N/A
 - OS: Windows 10

**Additional context**
I edited main.py and commented out 4 lines that make reference to legendasdivx, specifically lines 402,  403, 1538 and 1539 in my version. After restarting the service I could save the settings via the wizard

**Comment by morpheus65535** [comment]
Did you used the Windows Installer version or you installed from source? I cannot reproduce it with Python 3.8.1 under Windows 10. I've tested the wizard by enabling the provider or not, filling the username or not. Nothing to do.

**Comment by staterium** [comment]
I did use the windows installer. On the version that the installer installs, the code is looking for settings for 'legendasdivx', but there are only settings for 'legendastv':

https://imgur.com/a/bDHVtnJ

https://imgur.com/a/4UPCJBj

**Comment by morpheus65535** [comment]
I don't know what installer you got but I suggest you start from scratch. I've just tested it again on a brand new installation of Windows with the latest installe from www.bazarr.media and I get LegendasDivx both in main.py and in the UI. It works perfectly well.
