### ISSUE TITLE
Subdivx not working: ParseResponseError

### ISSUE THREAD

**Issue by vidalpascual** [morpheus65535/bazarr#828]
Hi,

I'm getting the error ParseResponseError from the subdivx provider.

I attach the log: [bazarr.log](https://github.com/morpheus65535/bazarr/files/4230993/bazarr.log)

Regards

**Comment by morpheus65535** [comment]
Please complete the informations required in the issue template.

**Comment by GermanG** [comment]
This should be solved in the latest dev (I madea PR fixing this, and it's merged)

**Comment by ngosang** [comment]
I confirm this is fixed after #806
