### ISSUE TITLE
Radarr Import Fails

### ISSUE THREAD

**Issue by dshokouhi** [morpheus65535/bazarr#83]
Hi,

I am just setting this up for the first time and my sonarr lists imports just fine however radarr is throwing the following error:

`Job "Update movies list from Radarr (trigger: interval[0:05:00], next run at: 2018-06-14 13:01:38 PDT)" raised an exception`

`'Traceback (most recent call last):\n File "C:\\Python27\\lib\\site-packages\\apscheduler\\executors\\base.py", line 125, in run_job\n retval = job.func(*job.args, **job.kwargs)\n File "C:\\bazarr\\get_movies.py", line 63, in update_movies\n separator == "\\\\"\nUnboundLocalError: local variable \'separator\' referenced before assignment'`

Let me know if you require more info from me.  Radarr is installed locally and my API key is correct.

**Comment by morpheus65535** [comment]
Can you confirm if it works now?

**Comment by dshokouhi** [comment]
Yup I just synced github so testing it now, my libarry is pretty large so hopefully it will be done soon

**Comment by dshokouhi** [comment]
yup it is working now for me thank you!!
