### ISSUE TITLE
Addic7ed provider and DeathbyCaptcha Error, time to solve ?

### ISSUE THREAD

**Issue by zaggash** [morpheus65535/bazarr#830]
Bazarr Ver. 0.8.4.2  ( development Branch )

There is an exception with the Addic7ed provider and DeathbyCaptcha
It looks like the process is not waiting the DeathbyCaptcha answer.

There is only 2s between the first captcha request and the error.
On DBC the average time to solve is about 12s so it make sense we have an exception here.
Or maybe I am missing something.
```
21/02/2020 16:38:16|INFO    |subliminal_patch.providers.addic7ed|Addic7ed: Solving captcha. This might take a couple of minutes, but should only happen once every so often|

21/02/2020 16:38:18|ERROR   |subliminal_patch.core           |Unexpected error in provider 'addic7ed' [...] Addic7ed: Couldn't solve captcha!|
```
The provider report an exception with the debug log below:

```
$>_ cat bazarr.log | grep -i subliminal | grep -i addic7ed
21/02/2020 16:38:16|INFO    |subliminal_patch.core           |Using 4 threads for 4 providers (['addic7ed', 'opensubtitles', 'podnapisi', 'tvsubtitles'])|
21/02/2020 16:38:16|INFO    |subliminal_patch.core           |Listing subtitles with provider 'addic7ed' and languages {<Language [fr]>}|
21/02/2020 16:38:16|INFO    |subliminal_patch.core           |Initializing provider addic7ed|
21/02/2020 16:38:16|DEBUG   |subliminal_patch.providers.addic7ed|Addic7ed: using random user agents|
21/02/2020 16:38:16|INFO    |subliminal_patch.providers.addic7ed|Addic7ed: Logging in|
21/02/2020 16:38:16|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on www.addic7ed.com|
21/02/2020 16:38:16|INFO    |subliminal_patch.providers.addic7ed|Addic7ed: Solving captcha. This might take a couple of minutes, but should only happen once every so often|
21/02/2020 16:38:17|INFO    |subliminal_patch.providers.addic7ed|Addic7ed: Couldn't solve captcha! Retrying|
21/02/2020 16:38:17|INFO    |subliminal_patch.providers.addic7ed|Addic7ed: Solving captcha. This might take a couple of minutes, but should only happen once every so often|
21/02/2020 16:38:17|INFO    |subliminal_patch.providers.addic7ed|Addic7ed: Couldn't solve captcha! Retrying|
21/02/2020 16:38:17|INFO    |subliminal_patch.providers.addic7ed|Addic7ed: Solving captcha. This might take a couple of minutes, but should only happen once every so often|
21/02/2020 16:38:18|ERROR   |subliminal_patch.core           |Unexpected error in provider 'addic7ed': Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 168, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 105, in __getitem__    provider.initialize()  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/addic7ed.py", line 136, in initialize    raise Exception("Addic7ed: Couldn't solve captcha!")Exception: Addic7ed: Couldn't solve captcha!|Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 168, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 105, in __getitem__    provider.initialize()  File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/addic7ed.py", line 136, in initialize    raise Exception("Addic7ed: Couldn't solve captcha!")Exception: Addic7ed: Couldn't solve captcha!|
21/02/2020 16:38:18|INFO    |subliminal_patch.core           |Discarding provider addic7ed|
```

I can send more if needed.

**Comment by zaggash** [comment]
Coming from https://github.com/morpheus65535/bazarr/issues/798

**Comment by morpheus65535** [comment]
@pannal could you see what's wrong here?

**Comment by zaggash** [comment]
Looks like it is something in this function:
https://github.com/morpheus65535/bazarr/blob/development/libs/subliminal_patch/providers/addic7ed.py#L128-L133

I don't know how to test it tho.
How to check the extracted data, I'm lost after this call:
https://github.com/morpheus65535/bazarr/blob/development/libs/subliminal_patch/pitcher.py#L33

I do not know where to look 👀

**Comment by morpheus65535** [comment]
I'm in the same position that's why I asked for @pannal help! :-)

**Comment by morpheus65535** [comment]
Can you try disabling `use random agent` in addic7ed settings?

**Comment by zaggash** [comment]
I just tried.
Didn't help, I have the same issue:
The log says it cannot resolve the captcha and then throttle the provider.

**Comment by zaggash** [comment]
Issue fixed after 8.4.2 update release

**Comment by morpheus65535** [comment]
That's pretty curious as I didn't make any other changes... I'll close this issue but re-open it if required.

**Comment by tun0** [comment]
I'm running into the same errors on 0.8.4.3 running in Kubernetes (Docker). It seems to me it doesn't even appear to be trying to use Death by Captcha (no mention of "death" in the debug log).
[bazarr (3).log](https://github.com/morpheus65535/bazarr/files/4529749/bazarr.3.log)

**Comment by morpheus65535** [comment]
@tun0 I've just tested and DBC is solving my Addic7ed captcha without any issue. I get throttled for connection timeout with Addic7ed from time to time but it should be good.

**Comment by tun0** [comment]
It seems authenticating against DBC is somehow failing. Will dig deeper.

**Comment by tun0** [comment]
There's something really funky going! While talking to DBC, the username and password get swapped!

**Comment by tun0** [comment]
To rule out funky chars, I config'ed `username` as username and `password` as password. Result:
`{"username": "password", "password": "username", "cmd": "login", "version": "DBC/Python v4.6"}`

**Comment by morpheus65535** [comment]
@tun0 can you tell me more about your setup?

**Comment by tun0** [comment]
@morpheus65535 I'm using the linuxserver docker image in my kubernetes cluster.
Currently trying to figure out why authentication tokens do work with the sample php code, but not with telnet, nor bazarr.

**Comment by morpheus65535** [comment]
DBC token is generated from username and password joined by a colon:

https://github.com/morpheus65535/bazarr/blob/376d57e4e7abb1bd34e885bc13d9b77200637030/bazarr/init.py#L27

If I remember correctly you have to restart Bazarr when you change either of those values.

**Comment by savahu** [comment]
This still does not work, or has this been solved in the development branch?

**Comment by morpheus65535** [comment]
> This still does not work, or has this been solved in the development branch?

This as been working for a long time. If you have an issue, you should open a new one instead of bringing back this one from the dead.
