### ISSUE TITLE
interactive search sometimes fails with attached error

### ISSUE THREAD

**Issue by zandadoum** [morpheus65535/bazarr#837]
when doing interactive searches, i often get this error (attached picture)

![image](https://user-images.githubusercontent.com/51913999/75154999-50350780-570f-11ea-9393-4b6126bca397.png)

[bazarr.log](https://github.com/morpheus65535/bazarr/files/4244663/bazarr.log)

example episode: Agent carter s01e01. this episode already had subs downloaded by BSplayer automatically. 
i did a interactive search for that episode. i even turned bsplayer off.
still throws error. attached error and attached log

**Comment by morpheus65535** [comment]
Please provide a copy of your bazarr.db. Can be done in PM on Discord.

**Comment by morpheus65535** [comment]
How long between the manual search process begin and the time you get the error? Looks like you're getting timed out because it takes to much time to run the search... 

What kind of hardware are you using to run Bazarr?
Did you disable `Search Enabled Providers Simultaneously` settings?

**Comment by zandadoum** [comment]
so, now I am trying, and the error doesn't pop right now. 
when it usually pops, it takes around 5-15seconds to show up

"Search Enabled Providers Simultaneously" is enabled.

I never changed any settings, this started happening after a recent update, but because the version number was always 0.8.4.1 (now 0.8.4.2) during several updates, I don't know when exactly it happened.

**Comment by morpheus65535** [comment]
I'm clueless with your log and DB. Everything seems to be fine.

**Comment by morpheus65535** [comment]
Do you still have that issue?

**Comment by zandadoum** [comment]
hello.
considering the issue didn't always happen and on top of that i rarely do interactive searches, i can not verify this.
i tried a few times last night and 4 out of 5 times everything worked and 1 time the search was just going infinite (waited over 10min. without result) but showed now error.

maybe this was a problem on one of the providers end and has since then been solved?
