### ISSUE TITLE
Search Results Appear Behind Listing Page

### ISSUE THREAD

**Issue by dshokouhi** [morpheus65535/bazarr#84]
1. Open  Bazarr
2. Navigate to any movie or series
3. Search for a word common among movies for a larger list (ex: black)

search results are showing up behind the listing

![results-behind](https://user-images.githubusercontent.com/1634145/41438429-1c4939f8-6fdc-11e8-83ed-2e3b83854a84.png)

**Comment by morpheus65535** [comment]
I've been searching how to fix this bug in Semantic-UI for hours... If you can find a way to make it work by forcing some CSS properties value, I would be grateful!

**Comment by sahil3bharmouri** [comment]
Let me help

**Comment by morpheus65535** [comment]
Of course! :-)
