### ISSUE TITLE
Still looking for removed language

### ISSUE THREAD

**Issue by shuffleznl** [morpheus65535/bazarr#841]
Initially I had two languages in Subtitle-settings.
After removing the secondary language, most content (also ones added after removal of language) is still looking for the removed i.e. non-existent language.

How can I (manually) remove all reference to the other language?
Primarily it's to limit API calls to providers.

**Comment by halali** [comment]
Please use discord for support. But i assume tou have to use mass editor to remove language also from existing series

**Comment by shuffleznl** [comment]
The way I phrased it indeed makes the issue out to be a support issue.
But I do believe it's a bug (remove language, it's no longer visible in any of GUI, but language still gets searched for) :)

**Comment by morpheus65535** [comment]
I agree that it could be cleaned from actual servies and movies. I'll take a look to this.

**Comment by morpheus65535** [comment]
Should be all good now in dev branch.
