### ISSUE TITLE
Download wanted subtitles traceback error

### ISSUE THREAD

**Issue by mattyrc** [morpheus65535/bazarr#849]
**Describe the bug**
Selecting the 'Download wanted subtitles' button throws a traceback error in bazarr.

**To Reproduce**
1. Launch bazarr from cli "python ./bazarr.py"
2. Select the 'Wanted' tab in the web UI
3. Select the "Download wanted subtitles" button
4. See Traceback error in cli

**Expected behavior**
Bazarr should search for and download all wanted subtitles.

**Software:**
 - Bazarr: v0.8.4.2 (Also tested in latest Master/Dev branch)
 - Radarr: v0.2.0.1480
 - Sonarr: v3.0.3.713
 - OS: Raspbian 10 (buster)
 - Python: 2.7.16 / 3.7.0

**Additional context**
Traceback (most recent call last):
  File "/opt/bazarr/bazarr/../libs/bottle.py", line 866, in _handle
    return route.call(**args)
  File "/opt/bazarr/bazarr/../libs/bottle.py", line 1744, in wrapper
    rv = callback(*a, **ka)
  File "bazarr/main.py", line 133, in wrapper
    return func(*a, **ka)
  File "bazarr/main.py", line 1191, in wanted_search_missing_subtitles_list
    scheduler.add_job(wanted_search_missing_subtitles, name='manual_wanted_search_missing_subtitles')
NameError: name 'wanted_search_missing_subtitles' is not defined

**Log**
[bazarr.log](https://github.com/morpheus65535/bazarr/files/4289903/bazarr.log)

**Comment by morpheus65535** [comment]
Can you test my fix in dev branch please?

**Comment by mattyrc** [comment]
This issue is no longer occurring on the latest dev branch. Thanks!
