### ISSUE TITLE
Add argument to force configuration and db path

### ISSUE THREAD

**Issue by fryfrog** [morpheus65535/bazarr#85]
Programs like radarr and sonarr take a `-data <path>` argument that lets one force the location of the configs. For packages, storing the package files in something like `/usr/lib/bazarr` is nice while the configs live in `/var/lib/bazarr`. :)

**Comment by pedrojvaz** [comment]
Where are the configs currently stored?

**Comment by morpheus65535** [comment]
In bazarr/db/bazarr.db SQlite database.

**Comment by morpheus65535** [comment]
From version 0.6.0 that is in dev branch for now, you can now use "--config /path/to/config/directory". Have fun!
