### ISSUE TITLE
RTL languages subtitles show punctuation marks in reverse

### ISSUE THREAD

**Issue by hawkash** [morpheus65535/bazarr#850]
This [issue](https://github.com/pannal/Sub-Zero.bundle/issues/409) was fixed by @pannal in sub-zero if it can be integrated to bazarr.

![Screen Shot 2020-03-06 at 10 41 58 AM](https://user-images.githubusercontent.com/37810955/76063137-2d6ce380-5f98-11ea-81a5-8c7d07fb2943.png)

**Comment by morpheus65535** [comment]
@pannal is there anything we should do in Bazarr to benefit from that fix you've made in SZ?

**Comment by morpheus65535** [comment]
We'll add support for subliminal_patch mods in the upcoming releases. No ETA right now.

**Comment by hawkash** [comment]
No rush. But there is one more thing if possible. When i manually upload a subtitle file through bazarr it doesn’t go through “encode subtitles to UTF8” process.

**Comment by morpheus65535** [comment]
> No rush. But there is one more thing if possible. When i manually upload a subtitle file through bazarr it doesn’t go through “encode subtitles to UTF8” process.

Please open a new issue for this.

**Comment by hawkash** [comment]
https://github.com/morpheus65535/bazarr/blob/376d57e4e7abb1bd34e885bc13d9b77200637030/libs/subzero/modification/mods/common.py#L142

**Comment by josdion** [comment]
@hawkash This should be fixed already. Can you check the development branch? In settings -> subtitles there is a new option - Reverse RTL. See if everything works as expected.

**Comment by morpheus65535** [comment]
No feedback, I close this.
