### ISSUE TITLE
Can't Get Video Information

### ISSUE THREAD

**Issue by genebeck** [morpheus65535/bazarr#855]
**Describe the bug**
While looking for subtitles program throws error

Message
BAZARR Error trying to get video information for this file: /volume1/Plex Media/Movies/1917 (2019)/1917 2019 DVDSCR-x265.mkv
Exception
Traceback (most recent call last):
 File "/app/bazarr/bazarr/get_subtitle.py", line 70, in get_video
  video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,
 File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video
  return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 495, in scan_video
  raise ValueError(\Path does not exist\)
ValueError: Path does not exist

**To Reproduce**
1. Go to any movie
2. Click on 'scan for subtitles'  does nothing
3. Click on 'manual search for subtitles' 
Box shows correct link to movie with no scenename and 'no subtitles found'
4. See error above

**Expected behavior**
Should find embedded subtitle

**Software (please complete the following information):**
Running on synology DS918+
 - Bazarr: [e.g. v 0.8.2] linuxserver/bazarr
 - Radarr version [e.g. v 0.2.0.1480] 
 - Sonarr version [e.g. v 2.0.0.5338]
 - OS: DSM 6.2.2-24922 Update 5

**Additional context**
Fails with any movie or tv program

**Comment by morpheus65535** [comment]
That's either a path mapping issue or a permission issue. Try with the wiki: https://github.com/morpheus65535/bazarr/wiki/Installation-Synology

If you can't get it working, come to Discord for support.

**Comment by genebeck** [comment]
I was able to sort this out with your guide.  I honestly missed special instructions for synology docker.  With the guide and a couple of path mapping it appears to be working correctly.

Thanks for the help.
