### ISSUE TITLE
Bsplayer name not resolved

### ISSUE THREAD

**Issue by robcsaszar** [morpheus65535/bazarr#857]
Since choosing bsplayer as provider I sometimes get this:
`HTTPConnectionPool(host='s9.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: /v1.php (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -2] Name does not resolve')), retrying in 5 seconds...`

**Comment by GermanG** [comment]
Fixed! ;-)

**Comment by ildoc** [comment]
I'm experiencing this on s3, s5, s9, s101 and s103 on v0.8.4.3.0

**Comment by morpheus65535** [comment]
@ildoc please test 0.8.4.4 in dev branch.
