### ISSUE TITLE
manual upload subtitle doesn't go through "encode subtitles to UTF8” process.

### ISSUE THREAD

**Issue by hawkash** [morpheus65535/bazarr#859]
**Describe the bug**
manually uploaded subtitle file is not saved as the UTF-8 character encoding.

**To Reproduce**
1. Go to 'localhost:6767'
2. Click on 'any movie title then click the manual upload icon'
3. upload subtitle file downloaded from subscene.com
4. play the movie in plex

**Expected behavior**
uploaded subtitle file saved as utf8 like the auto process

**Screenshots**
##### uploaded directly through bazarr :x:
![Screen Shot 2020-03-16 at 11 14 42 AM](https://user-images.githubusercontent.com/37810955/76736962-e7bed080-6778-11ea-8d01-aa894f9d2d30.png)

##### saved as utf8 using external tool and then uploaded using bazarr :white_check_mark:
![Screen Shot 2020-03-16 at 11 32 54 AM](https://user-images.githubusercontent.com/37810955/76737694-50f31380-677a-11ea-92a2-deba893ebd9c.png)

**Software:**
 - Bazarr: [0.8.4.2]
 - Radarr version [0.2.0.1480]
 - Sonarr version [3.0.3.717]
 - OS: [Linux-4.15.0-88-generic-x86_64]

**Comment by morpheus65535** [comment]
I've just pushed a fix to dev branch. Coud you test it please?

**Comment by morpheus65535** [comment]
No answer. I'm closing this one.
