### ISSUE TITLE
Change url base to not require trailing slash

### ISSUE THREAD

**Issue by fryfrog** [morpheus65535/bazarr#86]
In all the daemons I know of, url base does *not* include a trailing `/`. It would be nice if this matched. :)

For example, in Radarr the field is blank. And if set, should have `/radarr` for example.

**Comment by morpheus65535** [comment]
I agree that other software don't do it the same way. I'll look into making sure you don't need to specify the trailing slash in settings Sonarr and Radarr tabs. As for Bazarr, I don't pln to change it. To much testing required to be sure nothing is broken and no real benefit.

**Comment by fryfrog** [comment]
I change url base for my sonarr / radarr and it is working fine in bazarr, so you don't need to do anything there.

The benefit is mainly reduction in support. At least mention that you need the trailing slash. I didn't include it and my urls looked dumb like `/bazarrsettings`. There is significantly less friction when you conform to some "standards". :)

**Comment by morpheus65535** [comment]
Yeah I know. Should have done it like this in the beginning.

**Comment by morpheus65535** [comment]
Ok you've win... ;-)
