### ISSUE TITLE
Update all Episode/Movie Subtitles from disk causes memory page faults

### ISSUE THREAD

**Issue by kmlucy** [morpheus65535/bazarr#860]
**Describe the bug**
Running the tasks 'Update all Episode Subtitles from disk' and 'Update all Movie Subtitles from disk' cause dramatically increased rates of page faults. See the graphs below; 'A' is the start of the episode update, 'B' is the end of the episode update, 'C' is the start of the movie update, and 'D' is the end of the movie update.

**To Reproduce**
1. Run either task
2. Check page faults

**Expected behavior**
Updating subtitles should not cause page faults

**Screenshots**
![image](https://user-images.githubusercontent.com/13952475/76779143-42f4c100-6781-11ea-9d70-5b9e819e8538.png)

**Software**
 - Bazarr: 0.8.4.2
 - Radarr: 0.2.0.1480
 - Sonarr: 2.0.0.5344
 - OS: linuxserver Docker container

**Additional context**
I'm monitoring this through Netdata

**Comment by morpheus65535** [comment]
Did you limit the quantity of RAM Bazarr docker container could use?

**Comment by kmlucy** [comment]
I haven't. I don't have any issues with the amount of ram used.

**Comment by morpheus65535** [comment]
I haven'T seen anyone else with that issue. I'm not even sure how to investigate this as memory management in Python is done by Python itself. If Bazarr were leaking, I would have more power to fix it but with your issue, I don't know from were to start.

**Comment by kmlucy** [comment]
I'm not a programmer, so I can't really tell you how to proceed, but it's pretty clear what is causing it. Something with the two scans I mentioned is reliably causing the dramatic spikes in page faults. I would recommend trying to replicate it so you can see it for yourself first. 

Based on a few trials, I would say Bazarr is generating 90+% of the page faults on my system; none of the other Python based applications have this behavior.

**Comment by morpheus65535** [comment]
The issue happen during indexation of embedded subtitles using ffprobe. I've tried another libs (knowit) to get something more robust and tested (pymedusa is using it).

**Comment by morpheus65535** [comment]
I don't see any change except that it seems to be indexing external subtitles faster. I don't see what else I can change. The problem seems to be related to ffprobe.

As they are minor page fault, what is the real impact for you?

**Comment by kmlucy** [comment]
The main issue is that it seems to be causing issues with Netdata flushing its data from memory to disk.

**Comment by morpheus65535** [comment]
It seems that forking subprocess for ffprobe could be the root cause of this issue but it's the expected behavior. There's nothing I can really do about it. Minor page fault aren't problematic in normal situation and are pretty common. You'll have to see why Netdata doesn't manage it as expected.
