### ISSUE TITLE
guess_language doesn't detect correct language unless the file is UTF8

### ISSUE THREAD

**Issue by josdion** [morpheus65535/bazarr#862]
**Describe the bug**
If the subtitle file is without language code, bazarr is trying to detect it using guess_language function. I found that if the file is not UTF8 (in my case it's cp1251), the function return almost every time wrong language code or UNKNOWN.

**Software (please complete the following information):**
Bazarr Version: 0.8.4.2
Sonarr Version: 2.0.0.5344
Radarr Version: 0.2.0.1480

**Additional context**
I tested this on windows 10 with python 3.8 and on freenas with python 3.7.

**Comment by morpheus65535** [comment]
Can you provide a problematic subtitles file?

**Comment by josdion** [comment]
I've made a little modification of bazarr, so now all of my subtitles are detected correctly. I'll post a pull request to see what are changes. 

I'm attaching some of the unsupported files as far as I remember .
[subs.zip](https://github.com/morpheus65535/bazarr/files/4343271/subs.zip)

**Comment by mrjackyliang** [comment]
I think I'm also having the same issue. Bazarr is detecting files with unknown subtitles but fails to mention there are any subtitles.

**Comment by morpheus65535** [comment]
@mrjackyliang please provide a debug log (emptied first) while doing a disk scan for this specific series/movie.

**Comment by mrjackyliang** [comment]
Here is the debug log. The problem occurs for Season 1 (Episodes 7-18). In Plex, it will show `Unknown (SRT)`, which is OK. Subtitles shouldn't be missing.

[bazarr.log](https://github.com/morpheus65535/bazarr/files/4463627/bazarr.log)

**Comment by morpheus65535** [comment]
Those episode subtitles track probably don't have a valid language code tag so Bazarr is ignoring them.

**Comment by mrjackyliang** [comment]
Is there a way to allow unknown language subtitles? Not sure how I can fix this myself yet.

**Comment by morpheus65535** [comment]
Nope. Either you accept that and download external subs for desired languages or you edit your mkv to add the languages tags. Here's a tutotial: https://medium.com/@applehq/editing-mkv-language-tags-from-the-command-line-49e92ca60f4e

**Comment by mrjackyliang** [comment]
Gotcha. The article helps!!
