### ISSUE TITLE
Bazarr stopped downloading subtitles automatically. Manual searches/downloads work fine.

### ISSUE THREAD

**Issue by gbougiakas** [morpheus65535/bazarr#867]
It's been 5 days since bazarr stopped downloading subtitles automatically.

The only thing I changed around that time is switching off the "Use Embedded Subtitles" as this wakes up my unraid disks.

I enabled debug logging a couple of minutes ago but I don't think I can figure out what's broken by looking at the logs.

Any help would be appreciated.

[logs.zip](https://github.com/morpheus65535/bazarr/files/4354417/logs.zip)

**Comment by morpheus65535** [comment]
```
Throttling addic7ed for 10 minutes, until 20/03/19 14:14, because of: Exception. Exception info: 'AntiCaptcha class not given, exiting'

HTTPConnectionPool(host='gr.greek-subtitles.com', port=80): Read timed out. (read timeout=30), retrying in 5 seconds...

Throttling subs4series for 10 minutes, until 20/03/19 14:20, because of: AttributeError. Exception info: "'NoneType' object has no attribute 'contents'"

Not using subs4series until 20/03/19 14:20, because of: AttributeError
```

I would start by switching to dev branch and forcing an update. Some providers have been fixed in dev branch.

You cannot use addic7ed without an anti-captcha provider, disable it.

Some subtitles are found in your log but having a score lower than your minimal score. So it's working but nothing matching your criteria :-)

**Comment by gbougiakas** [comment]
Wow that was fast. I added anti captcha today just in case. I will disable it.
Any idea how to ride the dev branch from the docker container?

**Comment by morpheus65535** [comment]
ok so you're fine. I guess we still have issue with some providers. Could you empty your debug log and force a "search for wanted" in tasks? Provide the log please.

**Comment by gbougiakas** [comment]
It's been a couple of hours now. It still hasn't finished searching. It has successfully downloaded subs for series but not a single one for movies. maybe it's queued after the series. anyway I attach the log file so far
[bazarr.log.tar.gz](https://github.com/morpheus65535/bazarr/files/4355564/bazarr.log.tar.gz)

**Comment by morpheus65535** [comment]
Movies will run after series. We'll wait and see if your issue is fixed. Please report once it's completed.

**Comment by gbougiakas** [comment]
Hi eventually it downloaded some subs for movies too.

Logs as promised 
[bazarr.tar.gz](https://github.com/morpheus65535/bazarr/files/4358983/bazarr.tar.gz)

**Comment by morpheus65535** [comment]
You really think I'm going to read a more than 600k lines long log file? If you still have an issue, please be more precise: what is the remaining issue and provide a concise log file while reproducing this issue.

**Comment by gbougiakas** [comment]
Hi,

I have no issue now, I thinks that was clear. I just provided the logs after the whole search was completed because I thought you wanted them. Sorry, consider the case closed.

**Comment by morpheus65535** [comment]
Oh, ok. Thanks for the feedback! :-)
