### ISSUE TITLE
suggestion: adding subtitle uploader 

### ISSUE THREAD

**Issue by josdion** [morpheus65535/bazarr#875]
I have a suggestion to add a subtitle uploader username as a property of subtitle class. So providers can set this information and bazarr will eventually show it in the manual search dialog.

What do you think about that? If you like it I can make a PL.

![img1](https://user-images.githubusercontent.com/11270086/77232485-e55ddb80-6ba9-11ea-83a4-544e8648ffa4.png)

**Comment by morpheus65535** [comment]
It would require to edit each providers to get this information. I'm not against the idea but it's going to be a lot of work. Does it work it?

**Comment by josdion** [comment]
It's not required to edit providers at all, if they don't set uploader property, then the uploader column will just show n/a. Same as with the release information.

**Comment by morpheus65535** [comment]
That's what I meant. In fact I don't see the benefit of an additional column if most providers doesn't have metadata for it.

**Comment by josdion** [comment]
Тhey will never provide this information unless they are given the opportunity. My idea is to post PL with update to subtitle.py and providers which I use. So when someone make a new provider or edit existing one will be able to set it. Changing UI is not necessary for now and the screenshot was just an example how can look manual search dialog. But if the uploader username is not shown in the UI, probably nobody will bother to edit providers

**Comment by morpheus65535** [comment]
Ok go for it and add the column at the same time. We'll look to see if main providers can have this metadata.

**Comment by josdion** [comment]
What do you think about combining language and hearing impaired flag in a single column as labels and showing HI only when is set? I think it saves a little space and is more obvious when the HI flag is set.

**Comment by morpheus65535** [comment]
Sounds good to me! :-)

**Comment by morpheus65535** [comment]
Releases column is taking to much space IMO. Is there a way to have a max width?

**Comment by josdion** [comment]
Yes, bazarr interface is very narrow :)

Check how it looks with:
<th style="text-align: left; max-width: 30%;">Releases:</th>

**Comment by josdion** [comment]
`<th style="text-align: left; max-width: 30%;">Releases:</th>`

**Comment by morpheus65535** [comment]
BTW you should take a look at hermes branch that I'm working on :-)

**Comment by josdion** [comment]
> 
> 
> BTW you should take a look at hermes branch that I'm working on :-)

It looks good, though it's too red for me :)

I checked manual download dialog and it's even smaller than the current one. I hope you make it use all the space available on the page. As I have more ideas for adding information to it - like uploader rating, subtitle rating and so on :)

**Comment by morpheus65535** [comment]
I've made an easy fix that should please you. I suggest from now on you bring your previous fixes to hermes branch and start working directly onto that one. I'm working hard to release this in the next 4 to 6 weeks.

**Comment by josdion** [comment]
OK, that's great. I'll try to help as I can. Can you check the wizard mode in hermes. There is problem with wizard.html and {{ super() }}. It seems that a lot of things doesn't work for me and I'm trying to figure or why.

**Comment by josdion** [comment]
And if I skip wizard, by entering provider in config.ini, then it fails on `redirect('/settings')`. And I'm still not found a way to show the list with movies and TV shows. It's always empty.

**Comment by morpheus65535** [comment]
Wizard isn't developed yet in hermes. The easiest solution is to create a config with master/dev branch and then switch to hermes. Most settings page aren't done yet either (only general, sonarr and radarr work for now).

**Comment by morpheus65535** [comment]
I'm closing this issue as it is more a chat than something else. Please come see me on Discord if you want to continue this conversation.
