### ISSUE TITLE
Error: 500 Internal Server Error when manually uploading subtitles

### ISSUE THREAD

**Issue by ambaloo** [morpheus65535/bazarr#880]
**Describe the bug**
Getting error when manually uploading srt file, below the complete error :

Sorry, the requested URL 'http://192.168.1.128:6767/manual_upload_subtitle_movie' caused an error:

Internal Server Error

Exception:

AttributeError("'NoneType' object has no attribute 'filename'")

Traceback:

Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/bottle.py", line 866, in _handle
    return route.call(**args)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 1744, in wrapper
    rv = callback(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 133, in wrapper
    return func(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 1997, in perform_manual_upload_subtitle_movie
    _, ext = os.path.splitext(upload.filename)
AttributeError: 'NoneType' object has no attribute 'filename'

**Screenshots**
![image](https://user-images.githubusercontent.com/2873672/77310151-25ce6e00-6cfe-11ea-8193-44171f7a0302.png)

**Software :**
 - Bazarr: [0.8.4.2]
 - Radarr version [0.2.0.1480 ]
 - Sonarr version [2.0.0.5343]
 - OS: [Linux-4.19.0-8-amd64-x86_64]

I can provide more details if needed.

**Comment by morpheus65535** [comment]
It's simply because you didn't browse and select for a .srt file. If you did, what's the filename?

**Comment by ambaloo** [comment]
I did put the file and select the srt file.
SRT File : The.Two.Towers.2002.EC.BluRay.1080p.10bit.6.1.x265.HEVC-Qman.FR.srt
movies name : The.Lord.of.the.Rings.The.Two.Towers.2002.EXTENDED.PROPER.1080p.BluRay.H264.AAC-RARBG.mp4

Also tried to use the forced option.

**Comment by morpheus65535** [comment]
It's working perfectly fine for me in Chrome. What browser are you using?

**Comment by ambaloo** [comment]
Using Firefox, but tried with Chrome too, same issue.

Tried version 0.8.4.3 same issue, could it be python version (actually v3.8.2) 

P.S. using linuxserver docker version.

**Comment by morpheus65535** [comment]
I'm also using linuxserver docker images (dev and master) and it's working fine. It's clearly something on client side that is interfering with the upload process.

**Comment by ambaloo** [comment]
Probably I will investigate more, because I can't even fetch for subtitles for all languages (Movies ou TV shows)
Let's close this issue for now.
Thanks
