### ISSUE TITLE
BAZARR subtitles file doesn't seems to be text based

### ISSUE THREAD

**Issue by lukjod** [morpheus65535/bazarr#886]
Bazarr has problems with some utf-8 srt files

Bazarr Version:
0.8.4.3
Sonarr Version:
2.0.0.5344
Radarr Version:
0.2.0.1480
Operating System:
Linux-4.14.24-qnap-x86_64-with
Python Version:
3.8.2
Bazarr Directory:
/app/bazarr
Bazarr Config Directory:
/config

log 1
`Message
BAZARR subtitles file doesn't seems to be text based. Skipping this file: /movies/The Gentlemen (2019) [WEBDL-1080p, AC3, 5.1]/The Gentlemen (2019).srt
Exception
Traceback (most recent call last):
 File "/app/bazarr/bazarr/list_subtitles.py", line 385, in guess_external_subtitles
  raise UnicodeError
UnicodeError`

log 2
`Message
BAZARR subtitles file doesn't seems to be text based. Skipping this file: /movies/The Man of the Labyrinth (2019) [WEBDL-1080p, AC3, 5.1]/The Man of the Labyrinth (2019).srt
Exception
Traceback (most recent call last):
 File "/app/bazarr/bazarr/list_subtitles.py", line 386, in guess_external_subtitles
  text = text.decode(guess["encoding"])
UnicodeDecodeError: \ascii\ codec can\t decode byte 0xce in position 22375: ordinal not in range(128)`

problematic subs files

[The Gentlemen (2019).zip](https://github.com/morpheus65535/bazarr/files/4380858/The.Gentlemen.2019.zip)
[The Man of the Labyrinth (2019).zip](https://github.com/morpheus65535/bazarr/files/4380862/The.Man.of.the.Labyrinth.2019.zip)

**Comment by morpheus65535** [comment]
@josdion I guess you broke something here with your previous PR. Could you take a look please?

**Comment by morpheus65535** [comment]
@lukjod could you test latest fix to dev branch?

**Comment by lukjod** [comment]
2 errors gone 1 left
log:
`Message
BAZARR subtitles file doesn't seems to be text based. Skipping this file: /movies/The Hunt (2020) [WEBDL-1080p, EAC3, 5.1]/The Hunt (2020).srt
Exception
Traceback (most recent call last):
 File "/app/bazarr/bazarr/list_subtitles.py", line 386, in guess_external_subtitles
  text = text.decode(guess["encoding"])
UnicodeDecodeError: \ascii\ codec can\t decode byte 0xc3 in position 56684: ordinal not in range(128)`

subs file
[The Hunt (2020).zip](https://github.com/morpheus65535/bazarr/files/4386050/The.Hunt.2020.zip)

**Comment by morpheus65535** [comment]
@josdion something else to fix?

**Comment by lukjod** [comment]
and some occured after opensubtitles started to work all described as this one
log:
`Message
BAZARR subtitles file doesn't seems to be text based. Skipping this file: /tv/Gomorrah/Season 04/Gomorrah - S04E01 - Episode 1.srt
Exception
Traceback (most recent call last):
 File "/app/bazarr/bazarr/list_subtitles.py", line 385, in guess_external_subtitles
  raise UnicodeError
UnicodeError
`
sub file in PL language
[Gomorrah - S04E01 - Episode 1.zip](https://github.com/morpheus65535/bazarr/files/4387934/Gomorrah.-.S04E01.-.Episode.1.zip)

**Comment by josdion** [comment]
@lukjod I can't reproduce the problem with Gomorrah - S04E01 - Episode 1.zip. 

It is recognized as PL here and no exception.  Can you check it again?

**Comment by lukjod** [comment]
yes still same as here
log:
`Message
BAZARR subtitles file doesn't seems to be text based. Skipping this file: /tv/Gomorrah/Season 04/Gomorrah - S04E08 - Episode 8.srt
Exception
Traceback (most recent call last):
 File "/app/bazarr/bazarr/list_subtitles.py", line 385, in guess_external_subtitles
  raise UnicodeError
UnicodeError`
[Gomorrah - S04E08 - Episode 8.zip](https://github.com/morpheus65535/bazarr/files/4388757/Gomorrah.-.S04E08.-.Episode.8.zip)

**Comment by josdion** [comment]
Still can't reproduce the problem with Gomorrah files, but I hope the last PR will fix it. If not send the log with debug logging enabled.

**Comment by lukjod** [comment]
Have tested on newest version from development and no more errors
Thx @josdion

**Comment by tekert** [comment]
Seems this bug was reintroduced on the last stable version, never had this problem before but all of sudden after updating i get lots of:
```
Message
BAZARR subtitles file doesn't seems to be text based. Skipping this file: not-download-bazarr-file.srt
Exception
Traceback (most recent call last):
 File "c:\\bazarr\\bazarr\\list_subtitles.py", line 388, in guess_external_subtitles
  text = text.decode(guess["encoding"])
UnicodeDecodeError: \utf-8\ codec can\t decode byte 0xe9 in position 115: invalid continuation byte
```
This happens only in manually downloaded srt files from the web, the files in question are with encoding 1252 DOS terminated.

**Comment by josdion** [comment]
@tekert attach the problematic subtitle file

**Comment by tekert** [comment]
Here is one of many with this log:
Message
BAZARR subtitles file doesn't seems to be text based. Skipping this file: E:\Videos\Series\The Expanse\S03\The.Expanse.S03E08.720p.HDTV.x264-SVA.srt
Exception
Traceback (most recent call last):
 File "c:\\bazarr\\bazarr\\list_subtitles.py", line 388, in guess_external_subtitles
  text = text.decode(guess["encoding"])
UnicodeDecodeError: \utf-8\ codec can\t decode byte 0xbf in position 103: invalid start byte

[The.Expanse.S03E08.720p.HDTV.x264-SVA.zip](https://github.com/morpheus65535/bazarr/files/4513986/The.Expanse.S03E08.720p.HDTV.x264-SVA.zip)

**Comment by josdion** [comment]
@tekert please check the development branch as this should have already been fixed.

**Comment by Ceypt1c** [comment]
Hi. FYI, I'm still receiving this error "BAZARR subtitles file doesn't seems to be text based. Skipping this file: ". I dont have a lot of coding experience, but can try to help if needed. Thanks!

**Comment by josdion** [comment]
@Ceypt1c Attach one of these files here.

**Comment by Ceypt1c** [comment]
![Capture](https://user-images.githubusercontent.com/63569922/84067681-6351a780-a98d-11ea-8220-84d04bcedeae.PNG)

[Boiler Room[2000].txt](https://github.com/morpheus65535/bazarr/files/4747928/Boiler.Room.2000.txt)

FYI .srt changed to .txt for uploading purposes

**Comment by josdion** [comment]
@Ceypt1c Can you test development branch? It should be fixed now.

**Comment by Ceypt1c** [comment]
Hi. So far not seeing the error on v0.8.4.4. I'm not able to find development branch. I can check again in about another week and let you know. Thanks for checking into this!

**Comment by umairriaz82** [comment]
Hi, where can i find the development release?  After upgrading to v0.8.4.4, Bazarr app is not searching any subtitles and displays "file seems to be text based" for all subtitles scanned from the disk.

thanks in advance

**Comment by morpheus65535** [comment]
> Hi, where can i find the development release? After upgrading to v0.8.4.4, Bazarr app is not searching any subtitles and displays "file seems to be text based" for all subtitles scanned from the disk.
> 
> thanks in advance

How did you install Bazarr?

**Comment by umairriaz82** [comment]
> > Hi, where can i find the development release? After upgrading to v0.8.4.4, Bazarr app is not searching any subtitles and displays "file seems to be text based" for all subtitles scanned from the disk.
> > thanks in advance
> 
> How did you install Bazarr?

Downloaded the bazarr.zip file from https://www.bazarr.media.

**Comment by morpheus65535** [comment]
> Downloaded the bazarr.zip file from https://www.bazarr.media. I am running Bazarr on windows 10.

Unfortunately, the Windows Installer version of Bazarr cannot be switched to development branch. You'll have to wait for 0.9 to be merged to master branch and released. The other option is to install from source or use Docker.
