### ISSUE TITLE
Allow For Forced Only Subs And Languages

### ISSUE THREAD

**Issue by dshokouhi** [morpheus65535/bazarr#89]
It would be great if we can get just the forced flagged sub titles like the non-english parts of an english movie.  In addition if we can select english as well to get the whole subtitles.  I would personally like both.  It would also be great if shows/movies were identified to need forced sub titles too.

**Comment by morpheus65535** [comment]
Subliminal module (on which I rely to download subtitles from providers) doesn't give me this kind of possibilities.

**Comment by petwri** [comment]
But the same thing the other way round would work... I see bazarr consider forced subtitles as available subtitles and does not search for any. But i want the real deal - a complete subtitle file.

**Comment by lkgarrison** [comment]
@pannal Were forced subtitles built into Sub-Zero? Do you think it could also be added to this project?

**Comment by morpheus65535** [comment]
Yes it is build-in to Sub-Zero but we only reuse patched version of Subliminal from SZ. We need to adapt how we store and manage subtitles to be able to use them. It’s in the pipeline for the nexts weeks/months.
