### ISSUE TITLE
blank result from subscene.com 

### ISSUE THREAD

**Issue by dausruddin** [morpheus65535/bazarr#891]
**Describe the bug**
I use only subscene.com in my Bazarr installation. Since recently, Subscene won't produce any result. The search result is empty. But I can browse subscene.com perfectly fine in my browser.

**To Reproduce**
1. Search subtitle manually
2. Result will be blanked

**Expected behavior**
Automatic search working and manual search too.

**Screenshots**
![image](https://user-images.githubusercontent.com/5763466/77767938-bef1e180-707c-11ea-908f-2549d713cf2f.png)

**Software (please complete the following information):**
 - Bazarr: Ver. 0.8.4.2
 - Radarr: Ver. 0.2.0.1480
 - Sonarr: N/A 
 - OS: Ubuntu 18.04

**Additional context**
```
Throttling subscene for 10 minutes, until 20/03/27 22:43, because of: error. Exception info: 'BrotliDecompress failed'
```

**Comment by morpheus65535** [comment]
Works fine for me with 0.8.4.3 in dev branch:

![image](https://user-images.githubusercontent.com/5130500/77810116-39186b00-7069-11ea-8a11-0372d2d3ff95.png)

Could be corrupted cache. Maybe you can try to empty `bazarr/config/cache` directory?

**Comment by dausruddin** [comment]
Sorry but I don't have that path. But I have `./data/cache`. Is this what you meant?
Anyway I deleted all file inside `./data/cache` and issue still persist. 

So, I decided to reinstall. I deleted Bazarr folder and clone the git repo again. Unfortunately after setting up, the error still produced, and search result stays blank.
```
Throttling subscene for 10 minutes, until 20/03/28 09:56, because of: error. Exception info: 'BrotliDecompress failed'
```

Is there any files Bazarr create outside of its own folder?

**Comment by morpheus65535** [comment]
Do you have valid username/password set for Subscene?

What anti-captcha provider are you using?

Whatever I try, it's always working for me...

**Comment by dausruddin** [comment]
Sorry for late reply. Unfortunately I don't have any anti-captcha configured because they were working for me for at least a couple of months. 

I wanted to try anti-captcha, but they don't have a really cheap plan for me to test. Would be a waste if the issue persist after I bought a plan.

**Comment by morpheus65535** [comment]
Subscene require anti-captcha. Period.

10$us for a life time (I literally used 0.50%us in the last year) should be cheap enough to be afforded by anyone.

Over the last month, over 37 000 subtitles have been downloaded from Subscene using Bazarr. I guess we can say that it's working... ;-)

**Comment by dausruddin** [comment]
There goes my $11.60.....

Proof I bought a plan
![image](https://user-images.githubusercontent.com/5763466/78522096-c5abf180-77fe-11ea-9747-bba1fc3f9599.png)

Proof I loaded the key in my Bazarr
![image](https://user-images.githubusercontent.com/5763466/78522103-cd6b9600-77fe-11ea-8a24-dd577ba9160d.png)

Still getting the same error
![image](https://user-images.githubusercontent.com/5763466/78522116-da888500-77fe-11ea-8c4d-767c23997d3c.png)

I also already setup my subscene credentials in Bazarr
![image](https://user-images.githubusercontent.com/5763466/78522121-df4d3900-77fe-11ea-8b66-34a50ff037fc.png)

**Comment by morpheus65535** [comment]
@pannal although I cannot reproduce this behaviour, maybe you can see something wrong here?

**Comment by dausruddin** [comment]
Somehow after many times re-cloning repo between dev and stable, then running them over and over with errors popping up, it is working fine now. Also it returns result much faster than ever.

These are some errors I got out of nowhere with 500 error code returned in browser, then somehow after so many retry, it works again

```
Traceback (most recent call last):
  File "/home/user/bazarr/bazarr/../libs/bottle.py", line 866, in _handle
    return route.call(**args)
  File "/home/user/bazarr/bazarr/../libs/bottle.py", line 1744, in wrapper
    rv = callback(*a, **ka)
  File "bazarr/main.py", line 133, in wrapper
    return func(*a, **ka)
  File "bazarr/main.py", line 261, in wizard
    base_url=base_url)
  File "/home/user/bazarr/bazarr/../libs/bottle.py", line 3623, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/home/user/bazarr/bazarr/../libs/bottle.py", line 3413, in render
    self.execute(stdout, env)
  File "/home/user/bazarr/bazarr/../libs/bottle.py", line 3400, in execute
    eval(self.co, env)
  File "/home/user/bazarr/views/wizard.tpl", line 114, in <module>
    % include('wizard_subtitles')
  File "/home/user/bazarr/bazarr/../libs/bottle.py", line 3390, in _include
    return self.cache[_name].execute(env['_stdout'], env)
  File "/home/user/bazarr/bazarr/../libs/bottle.py", line 3400, in execute
    eval(self.co, env)
  File "/home/user/bazarr/views/wizard_subtitles.tpl", line 113, in <module>
    <option value="{{language['code2']}}">{{language['name']}}</option>
TypeError: string indices must be integers
```

```
Traceback (most recent call last):
  File "/home/user/bazarr-dev/bazarr/../libs/bottle.py", line 866, in _handle
    return route.call(**args)
  File "/home/user/bazarr-dev/bazarr/../libs/bottle.py", line 1744, in wrapper
    rv = callback(*a, **ka)
  File "bazarr/main.py", line 133, in wrapper
    return func(*a, **ka)
  File "bazarr/main.py", line 778, in movies
    max_page = int(math.ceil(missing_count / (page_size + 0.0)))
TypeError: unsupported operand type(s) for /: 'str' and 'float'
```

```
Traceback (most recent call last):
  File "/home/user/bazarr-dev/bazarr/../libs/bottle.py", line 866, in _handle
    return route.call(**args)
  File "/home/user/bazarr-dev/bazarr/../libs/bottle.py", line 1744, in wrapper
    rv = callback(*a, **ka)
  File "bazarr/main.py", line 133, in wrapper
    return func(*a, **ka)
  File "bazarr/main.py", line 771, in movies
    missing_count = database.execute("SELECT COUNT(*) as count FROM table_movies", only_one=True)
TypeError: string indices must be integers
```

**Comment by dausruddin** [comment]
Ok. After I had subscene working, I stopped bazar and run using systemd instead. Now the issue came back.

Then I rename bazarr folder from `bazarr-dev` to something else and run it, now i'm getting this error
```
Traceback (most recent call last):
  File "/home/user/bazarr-dev/bazarr/../libs/bottle.py", line 866, in _handle
  File "/home/user/bazarr-dev/bazarr/../libs/bottle.py", line 1744, in wrapper
  File "bazarr/main.py", line 133, in wrapper
    return func(*a, **ka)
  File "bazarr/main.py", line 892, in movie
    tmdbid = movies_details['tmdbId']
TypeError: string indices must be integers
```

**Comment by dausruddin** [comment]
I don't know why bazarr randomly throwing random errors like mentioned above. Here is another

```
Traceback (most recent call last):
  File "/home/user/bzd/bazarr/../libs/bottle.py", line 866, in _handle
    return route.call(**args)
  File "/home/user/bzd/bazarr/../libs/bottle.py", line 1744, in wrapper
    rv = callback(*a, **ka)
  File "bazarr/main.py", line 133, in wrapper
    return func(*a, **ka)
  File "bazarr/main.py", line 1675, in system
    return template('system', bazarr_version=bazarr_version,
  File "/home/user/bzd/bazarr/../libs/bottle.py", line 3623, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/home/user/bzd/bazarr/../libs/bottle.py", line 3413, in render
    self.execute(stdout, env)
  File "/home/user/bzd/bazarr/../libs/bottle.py", line 3400, in execute
    eval(self.co, env)
  File "/home/user/bzd/views/system.tpl", line 53, in <module>
    % include('menu.tpl')
  File "/home/user/bzd/bazarr/../libs/bottle.py", line 3390, in _include
    return self.cache[_name].execute(env['_stdout'], env)
  File "/home/user/bzd/bazarr/../libs/bottle.py", line 3400, in execute
    eval(self.co, env)
  File "/home/user/bzd/views/menu.tpl", line 78, in <module>
    % wanted_series = database.execute("SELECT COUNT(*) as count FROM table_episodes WHERE missing_subtitles != '[]'" + monitored_only_query_string_sonarr, only_one=True)['count']
TypeError: string indices must be integers
```

**Comment by dausruddin** [comment]
Boommm somehow bazarr is working again, including subscene. I cannot even understand what is happening, but I'm going to leave bazarr for now because I might get the issue next time I restarted it.

I'm going to play with it more later, maybe I can find the pattern.

**Comment by morpheus65535** [comment]
Your bazarr.db seems to be somehow corrupted or maybe you got a permission issue over it.

**Comment by dausruddin** [comment]
I tried opening the db file using [DB Browser for SQLite](https://sqlitebrowser.org/) on my Windows, also using command-line sqlite3 on my Linux server and they both can open the database and browse through the data.
I doubt there is a permission issue because I am running Bazarr using the same user as I'm logged in.

--------------------------------------------------------------------------------------------------

- So, I gambled and restarted Bazarr. Bazarr is working fine and Subscene too.
I was using `Python 3.8.2` installed using pyenv.
- ~~Then, I tried changing to system `Python 3.6.9`, and subscene stopped working again. After a restart, Bazarr now is giving me this error~~ Found something, check next point
  ```
  Traceback (most recent call last):
    File "/home/user/bzd/bazarr/../libs/bottle.py", line 866, in _handle
      return route.call(**args)
    File "/home/user/bzd/bazarr/../libs/bottle.py", line 1744, in wrapper
      rv = callback(*a, **ka)
    File "bazarr/main.py", line 133, in wrapper
      return func(*a, **ka)
    File "bazarr/main.py", line 892, in movie
      tmdbid = movies_details['tmdbId']
  TypeError: string indices must be integers
  ```
  DB Browser and [sqlite3 can open the database](https://serverfault.com/a/8051)
  ![image](https://user-images.githubusercontent.com/5763466/79033835-067f7e00-7be4-11ea-8c3b-c8dc74d1998a.png)
- Turned out there is a process keep running even I killed bazarr by CTRL+C
  ```
  user     17244  0.2  0.3 1121364 108276 pts/16 Sl   10:47   0:02 /usr/bin/python3 -u bazarr/main.py
  ```
  After killing this process, both `Python 3.8.2` (pyenv) and `Python 3.6.9` (system) can run Bazarr again without any error. I am wondering why that particular process stucked in the first place
  - Sadly subscene still not working on `Python 3.6.9` (system)
    ```
    Throttling subscene for 10 minutes, until 20/04/11 11:22, because of: error. Exception info: 'BrotliDecompress failed'
    ```
  - Then I tried `Python 3.8.2` (pyenv) and after 10 minutes waiting for the throttle to cool down, subscene is working fine now.

So my guesses are:
* Those errors I got earlier was caused by a process `/usr/bin/python3 -u bazarr/main.py` stucked
* `Python 3.8.2` (pyenv) has subscene working, but `Python 3.6.9` (system) is not. This need more testing.

Can we force a provider search? When I'm trying subscene which is throttled, it will quickly returning `{"data": null}` (the search interface still loading, maybe can fix that to show error message instead of infinite loading). I can only retry subscene after the 10 minutes passed by. It is hard to keep testing when I have 10 minutes cooldown.

**Comment by morpheus65535** [comment]
Hey, thanks for this thorough investigation! :-)

We had a lot of issues with Python 3.6.9 lately and I was already thinking about adjust requirement to use >=3.7. I think I'll do it right now. In fact, over the last 7 days, only 0.32% of Bazarr users were using 3.6.9. The impact won't be that big.

As for resetting throttling status, you've got the right trick by emptying the value in config.ini and restarting Bazarr.

So I guess we can consider this issue solved by using 3.8.2, right?

**Comment by dausruddin** [comment]
Yes I think this issue is solved. Thanks😁

But are you sure want to drop Python 3.6 support? Because that is the latest Python3 version on Ubuntu 18.04 by default.

**Comment by morpheus65535** [comment]
Yes I am, some of our dependencies have dropped support for 3.6.x anyway.

**Comment by dausruddin** [comment]
Okay. Thanks a lot for this awesome software😁
