### ISSUE TITLE
legendasdivx again

### ISSUE THREAD

**Issue by estimadarocha** [morpheus65535/bazarr#898]
@GermanG  can you confirm if everything fine with legendasdivx?

i am using 2 providers legendasdivx and opensubtitles and no matter what i do bazarr only return opensubtiles results, manual or automatic search.

small example:

Episode path is: /shared/tv/The Blacklist/Season 7/The Blacklist - S07E08 - The Hawaladar WEBDL-1080p NTb.mkv
Scenename is: The.Blacklist.S07E08.The.Hawaladar.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb

Score: |   | Provider: | Matching: | Releases: | Uploader: |  
-- | -- | -- | -- | -- | -- | --
100% | PT-BR | opensubtitles | 29 | The.Blacklist.S07E08.The.Hawaladar.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb; | clazevedo |  
100% | PT-BR | opensubtitles | 29 | The.Blacklist.S07E08.The.Hawaladar.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb | anonymous |  
99.44% | PT | opensubtitles | 92 | The Blacklist S07E08.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb | MaSousa |  
94.44% | PT-BR | opensubtitles | 74 | The.Blacklist.S07E08.iNTERNAL.720p.WEB.h264-BAMBOOZLE | clazevedo |  
92.5% | PT-BR | opensubtitles | 65 | The.Blacklist.S07E08.720p.HDTV.x264-AVS | anonymous |

**Comment by estimadarocha** [comment]
i am using:

Bazarr Version:
0.8.4.3

on docker with:


linuxserver/bazarr:development@sha256:b6ba8acb6e6b51e1590fc1e93e883537a7dc14cac4d3796d401fdb5c9bde16d6
--

**Comment by estimadarocha** [comment]
@morpheus65535 @GermanG problem solved... or partially solved... all the people using bazarr had been banned from Legendasdivx because suspicious activity... after small talk with webmaster we are now free to go again... but he kindly asks to put bazarr on user-agent to prevent similar behaviour on future, is it possible? thanks

**Comment by morpheus65535** [comment]
Fixed in dev branch.

**Comment by GermanG** [comment]
Thanks @morpheus65535 I was late to the party :)
