### ISSUE TITLE
Feature request: Add "Skip wrong FPS" option for Subsunacs, Subssabbz, Yavka.net providers

### ISSUE THREAD

**Issue by screamerbg** [morpheus65535/bazarr#899]
All the 3 Bulgarian subtitle providers are listing the video FPS when searching. Similar to the OpenSubtitles provider, there could be a "Skip wrong FPS" option for the 3 subtitle providers to enable this behavior and reduce the number of subtitle results with wrong FPS. This will be especially useful for movies with multiple releases.

CC @josdion

**Comment by morpheus65535** [comment]
#525
