### ISSUE TITLE
Bazarr Logo

### ISSUE THREAD

**Issue by hotio** [morpheus65535/bazarr#90]
Hey,

Don't take this the wrong way...I've noticed the logo's aren't of a really high quality, low res and pixelated.

I've recreated the logo as best as I could given the highest I could use was 128x128 as an SVG.

Are you interested in a PR to add the SVG into `static`?

Sample:
![bazarr](https://user-images.githubusercontent.com/26902309/41456760-be00043e-7081-11e8-9646-1b724037b4ff.png)
Not a 100% match

**Comment by morpheus65535** [comment]
Don't worry! I've done it in mspaint and never came back to it to improve quality!

Thanks, I'll work with that to update all images.

**Comment by hotio** [comment]
If you need the SVG just ask, modifying raster files feels dirty... :-)

**Comment by hotio** [comment]
It appears this logo is stolen from https://github.com/opensubtitles, so I'll close this. Perhaps you could let the community design a new logo from scratch?

**Comment by morpheus65535** [comment]
I don’t remember where it come from but it’s true I use something I found trough Google image when I started to work on Bazarr. At the time, Bazarr wasn’t dedicated to be release to public. You are right, I’m going to think about changing it in the near future. Of you’re willing to help on that, I would really appreciate it!

**Comment by hotio** [comment]
No biggie, would love to help, but I'm terrible at designing logos from scratch...

**Comment by morpheus65535** [comment]
Lol same for me... I would be at risk of hurting myself trying to do it ;-)

**Comment by sybenx** [comment]
![bazarr](https://github.com/morpheus65535/bazarr/assets/2048087/db3dbb1b-5192-4ee6-b815-36d998810c7e)
![bazarr2](https://github.com/morpheus65535/bazarr/assets/2048087/a52019d8-4ca2-4bc0-a6a2-ff65d98e6311)
![bazarr3](https://github.com/morpheus65535/bazarr/assets/2048087/d412794a-114c-47b8-b706-479b8dac830d)

AI generated, obv color can be changed, etc. I'm not an artist. My favorite is the bottom one. The top one might be the most in style with other "Arr" logos though.
