### ISSUE TITLE
Bazarr - Sonarr/Radarr Test Failed

### ISSUE THREAD

**Issue by Milithor** [morpheus65535/bazarr#900]
**Describe the bug**
When I enter my Sonarr / Radarr info (IP, Port & API Key) it seems that the test fails each time.

**Expected behavior**
Bazarr can connect to Radarr/Sonarr. Test passes, and if not provides a reason instead of only 'test failed'

**Software (please complete the following information):**

Bazarr: 0.8.4.2 (linuxserver/bazarr:latest)
Radarr version 0.2.0.1480 (Synology)
Sonarr version 2.0.0.5338 (Synology)
OS: Ubuntu Server 18.04

**Additional context**
I did a TCP dump and I'm seeing requests going out to Sonarr and replies returning.
No other reason is stated why it is not working.

After enabling debug logs, the only output was:
2020-03-31 14:58:55,239 - urllib3.connectionpool           (7f58a1ffb700) :  DEBUG (connectionpool:206) - Starting new HTTP connection (1): XX.XX.XX.XX:8989

Logs lack any form of statement around this 'test':
31/03/2020 13:39:43|INFO    |root                            |BAZARR Database created successfully|
31/03/2020 13:39:45|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:6767/|
31/03/2020 13:48:41|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:6767/|
31/03/2020 14:11:38|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:6767/|
31/03/2020 14:13:22|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:6767/|

OS: Linux
Code comes directly from Git
Running in Python3

**Comment by morpheus65535** [comment]
I suppose you are trying to reach Sonarr / Radarr by using 127.0.0.1 IP address?

**Comment by Milithor** [comment]
Hi!
Thanks for the quick response.
Unfortunately no, i'm pointing it to an IP in my own network.

For a separate service i'm running, the same destination client functions as network drive as well and that is perfectly working.

**Comment by morpheus65535** [comment]
Can you do a curl from inside the Bazarr container? Try to call Sonarr API status `/api/system/status?apikey=######################`

**Comment by rraymondgh** [comment]
What docker-compose network setup are you using?  
```
networks:
  htpc-network:
```
then under each component I have:
```
  bazarr:
    networks:
      - htpc-network
  radarr:
    networks:
      - htpc-network
```
that then means you need to put `sonarr` or `radarr` in IP so that the docker private network works.  `localhost` and `127.0.0.1` are your physical machine not the private docker network.

From Bazarr config.ini 
```
[sonarr]
ip = sonarr
port = 8989

[radarr]
ip = radarr
port = 7878
```

**Comment by morpheus65535** [comment]
It should work unless you have an issue with name resolution on your docker host. I'll see to add some logging in dev branch ASAP.

**Comment by Milithor** [comment]
I'm running it directly in Linux, not in Docker.
I'll have a look at doing a curl.

**Comment by Milithor** [comment]
{
"version": "2.0.0.5338",
"buildTime": "2019-10-31T10:50:26Z",
"isDebug": false,
"isProduction": true,
"isAdmin": false,
"isUserInteractive": false,
"startupPath": "/volume1/@appstore/nzbdrone/share/NzbDrone",
"appData": "/volume1/@appstore/nzbdrone/var/.config/NzbDrone",
"osName": "DSM",
"osVersion": "6.2.2",
"isMonoRuntime": true,
"isMono": true,
"isLinux": true,
"isOsx": false,
"isWindows": false,
"branch": "master",
"authentication": "none",
"sqliteVersion": "3.25.3",
"urlBase": "",
"runtimeVersion": "5.18.0.240",
"runtimeName": "mono"
}

This is the output coming from my browser.
If i do it on my linux server using CURL, it gives a timeout. Target Sonarr System is on the same 1gb switch and I'm reaching that same Sonarr system from my Linux server for fileshipping, Plex, ... and that all works. Firewall is disabled at time of testing. I'm a bit at a loss here..

**Comment by morpheus65535** [comment]
I added logging in dev branch for that, did you try it? `linuxserver/bazarr:development`

**Comment by dominikpflegerl** [comment]
I have the exact same problem, my bazarr installation cannot connect to either Sonarr nor Radarr.

My server's OS is Windows Server 2019. 
Sonarr, Radarr and Bazarr are all installed directly (and not through docker).

Ombi f.ex. with the exact same data has no problems connecting to Sonarr and Radarr, but Bazarr shows me a failed test everytime. At the setup I could connect to Sonarr, but not Radarr, but after setup I once again tested the Sonarr setup and then it failed. 

Calling Sonarr or Radarr API through a browser works.

**Comment by morpheus65535** [comment]
@dominikpflegerl that's not the same issue, you've got a 401 http status code that mean unauthorized. Check your Sonarr/Radarr API key.

**Comment by morpheus65535** [comment]
@Milithor Can I close this issue?
