### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by kevinverelst** [morpheus65535/bazarr#903]
Hi there, I just recently found out such a thing as bazarr exists so I quickly installed it on my Synology Nas. After some config and setup I got it running for sonarr but syncing the movies with radarr throws `
TypeError: string indices must be integers`
 Here is a screenshot of the error:
![image](https://user-images.githubusercontent.com/4036085/78185060-cba27b00-746a-11ea-95c9-b58c855ef3ad.png)

I have no experience in python but dove into the code and looked at line 99 of get_movies.py as displayed in the error. 
It seems that you expect there being a title property in the alternativeTitles property of a movie object.
```
 if 'alternativeTitles' in movie: 
       alternativeTitles = str([item['title'] for item in movie['alternativeTitles']])
 else:
        alternativeTitles = None
```

A quick look at the API tells me that it returns an array of strings instead of objects. 
![image](https://user-images.githubusercontent.com/4036085/78185541-8763aa80-746b-11ea-9346-1d115b368063.png)

I hope I gave you enough information and do please correct me if I'm wrong.

**Comment by morpheus65535** [comment]
First, sorry for the delay. I kind of forgot to answer this specific issue last weekend.

What version of Radarr are you using? This part of code haven't changed over the last 14 months and is normally working with v0.2x and with v3.x. 

I've just tested it and this is the JSON returned by the API:
```
{
    "title": "2 Fast 2 Furious",
    "alternativeTitles": [
      {
        "sourceType": "tmdb",
        "movieId": 1,
        "title": "The Fast and the Furious 2",
        "sourceId": 584,
        "votes": 0,
        "voteCount": 0,
        "language": {
          "id": 1,
          "name": "English"
        },
        "id": 504
      },
      {
        "sourceType": "tmdb",
        "movieId": 1,
        "title": "The Fast and the Furious 2 - 2 Fast 2 Furious",
        "sourceId": 584,
        "votes": 0,
        "voteCount": 0,
        "language": {
          "id": 1,
          "name": "English"
        },
        "id": 505
      }
    ],
    ...
```

I'm really curious how you'd get that kind of JSON returned. Did you actually tried to call the `movies` API endpoint (`http://localhost:7878/api/movie?apikey=abcdef...`)? What is the result?

**Comment by kevinverelst** [comment]
Hi, thank you for your answer. I checked my version of radarr and it seems I'm using version 0.2.0.654
![image](https://user-images.githubusercontent.com/4036085/78762911-cb334400-7984-11ea-91f0-9329a8445562.png)
I must add that I'm using the synology package but I'm not sure this has an influence. 

I indeed used the api call to get all the movies as this is the one your script calls:
![image](https://user-images.githubusercontent.com/4036085/78763303-4137ab00-7985-11ea-9890-2ff855248398.png)

**Comment by kevinverelst** [comment]
Mmh, it seems that i'm using a very old version of radarr from 18 april 2017 (https://github.com/Radarr/Radarr/releases/tag/v0.2.0.654) that could be a possible explanation to the  difference in API contract

**Comment by morpheus65535** [comment]
From what I can see, there's a newer version of the package: https://synocommunity.com/package/radarr

I suggest you update first the package and if it doesn't fix it, you should consider moving to Docker container instead of Synology package that are well known for being obsolete.

**Comment by kevinverelst** [comment]
I have checked the package updates and it seems I'm fully updated but I was already thinking about switching to the docker version. Anyhow, the chances of the problem being resolved once updated are very high so i'm going to close this issue. Thanks for the help.
