### ISSUE TITLE
Searching for all wanted subs results in an exception

### ISSUE THREAD

**Issue by wessel145** [morpheus65535/bazarr#904]
**Describe the bug**
When I search for all the missing subtitles. The counter at the right bottom starts with 1/<number of wanted> and then exits, the log shows the following error:

> Execution of job "manual_wanted_search_missing_subtitles (trigger: date[2020-04-02 20:31:27 CEST], next run at: 2020-04-02 20:31:27 CEST)" skipped: maximum number of running instances reached (1)

I checked and there was nothing else happening in bazarr, next executing for Search for wanted Subtitles is in 12 hours.

**To Reproduce**
1. Go to 'Wanted'
2. Click on 'Download wanted subtitles'
or
1. Go to 'tasks'
2. Execute task 'Search for wanted Subtitles' manually

3. wait a few seconds an 

**Expected behavior**
That it would download all the subs i'm missing

Enabled providers:
- addic7ed
- BSplayer
- opensubtitles
- Subscene
- Podnapisi
- Subscenter
- Supersubtitles
- TVsubtitles

**Software (please complete the following information):**

Bazarr Version:
0.8.4.3 (Docker development branch, since i got another error first, which was closed/solved in issue 849)
Sonarr Version:
3.0.3.750
Radarr Version:
3.0.0.2759
Operating System:
Linux-4.15.0-91-generic-x86_64-with

**Comment by wessel145** [comment]
Additional: By enabling debug logging i found it's still searching for the subs, but not showing any progress in the UI (except for logs, with debugging on). Maybe that's the issue here :) not sure

**Comment by halali** [comment]
Hi, you have enabled 8 providers and also bsplayer is realy slow in searching. Also depend how many subs yoi have missing. But it's normal when subtitles search take ao long when you have lot of missing subtitles and 8 enabled providers.

Its not error only information.
Im closing this as ita not an issue. 
If you need any support please come to discord and ask there.
