### ISSUE TITLE
Main page does not show any serie but pages work

### ISSUE THREAD

**Issue by pando85** [morpheus65535/bazarr#907]
**Describe the bug**
Main page does not show any serie but pages view work properly.

**To Reproduce**
1. Go to `/series`

**Expected behavior**
See all series...

**Screenshots**
`/series`
![image](https://user-images.githubusercontent.com/4646670/78423715-95324f00-7668-11ea-9518-a9ca23638a80.png)
`/series?page=1`
![image](https://user-images.githubusercontent.com/4646670/78423726-bc891c00-7668-11ea-9740-f2ad7f3b3501.png)

**Software (please complete the following information):**
 - Bazarr: [v 0.8.4.2 ]
 - OS: [Linux 3.10]

**Comment by halali** [comment]
You probably install bazarr and you didnt see it immediately, but bazarr need some time to index all files and subtitles...

Also you have bad pathmappings, tha triangel Near your series path.

Fix that and wait some tume to let it index... For support please come to discord.

**Comment by pando85** [comment]
Ok, so this is normal too:
```txt
(7f9cb772cb20) :  ERROR (base:980) - Error submitting job "Update Series list from Sonarr (trigger: interval[0:01:00], next run at: 2020-04-05 09:08:59 CEST)" to executor "default"
```
I don't have bad pathmappings I just have some series in Sonarr without download or monitoring, so just no episodes are there and not directory exists.

**Comment by halali** [comment]
Attache your debug log with this error, i have to see traceback for this error to know whats going on

**Comment by morpheus65535** [comment]
No answer. I'm closing this issue. Re-open it if required.
