### ISSUE TITLE
All /api endpoints do not require authentication

### ISSUE THREAD

**Issue by psxpaul** [morpheus65535/bazarr#908]
**Describe the bug**
All endpoints exposed under /api do not require authentication, even though basic or form login is enabled.

**To Reproduce**
1. Go to settings
2. Choose Forms (Login Page) from the Authentication drop down
3. Set a username and password
4. In a browser incognito tab, navigate to http://<bazarr_host>:<bazarr_port>/api/series/wanted
5. Json data of your wanted tv episodes is returned, without any authentication required

**Expected behavior**
Either an http 401 is returned, or a redirect to the login page should be returned.

**Software (please complete the following information):**
 - Bazarr: 0.8.4.2
 - Radarr version: n/a
 - Sonarr version: n/a
 - OS: Ubuntu 19.04

**Additional context**
Looking at the code, I'm guessing a `api_authorize()` call should be added to the beginning of all functions named `api_wanted()`, `api_history()`, and possibly `api_help()`.

**Comment by morpheus65535** [comment]
This legacy API is read only and is going to be deprecated in 0.9. I won't fix that until then.
