### ISSUE TITLE
Bazarr classifying as wrong language

### ISSUE THREAD

**Issue by mrcsmcl** [morpheus65535/bazarr#912]
Bazarr is classifying the subtitle as wrong language for movies. I use Brazilian Portuguese in all settings, but when it downloads the subtitle (right language on it) it gets classified as Portuguese. The problem is that it won't remove from the wanted tab and will keep download over and over and over. No matter what providers I select (I selected only one, a brazilian one, legendastv, but still). That happens only for movies, tv shows are ok. I even selected to download single languages and add only one to the field. Can I get some help? Bazarr Ver. 0.8.4.2, on docker.

**Comment by halali** [comment]
Disable single language will help you solve this issue.

**Comment by morpheus65535** [comment]
No answer. I'm closing this issue. Re-open it if required.

**Comment by mrcsmcl** [comment]
"Disable single language will help you solve this issue", it's a workaround. I think the bug should be fixed, since maybe my player don't support it. I have to change players, but that's not the best solution. The bug also happens on the latest version, Bazarr Ver. 0.8.4.4.

**Comment by halali** [comment]
Unfortunately this isnt issue that can be fixed... Because bazarr have to guess language from subtitles. And probably it guess as different language.

Honestly i dont know player that dont support language code.

**Comment by mrcsmcl** [comment]
I understand, but for example legendas.tv only have pt-br and en subtitles, maybe something that would help?

Players: for example, I used to use dlna on both my Samsung TVs using Serviio, and watch it in tv's own player. Both the TV and the server don't support it.

**Comment by halali** [comment]
You should try plex, samsung tv have his own app.
