### ISSUE TITLE
 Error saving Subtitles file to disk for this file

### ISSUE THREAD

**Issue by svenvg93** [morpheus65535/bazarr#914]
**Describe the bug**
Sometime when searching for a subtitle, I get the following error when trying to save a subtitle. 
If I manual upload the same file it works as expected.

```
 Traceback (most recent call last):
 File "/app/bazarr/bazarr/get_subtitle.py", line 412, in manual_download_subtitle
  saved_subtitles = save_subtitles(video.original_path, [subtitle], single=single,
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 874, in save_subtitles
  content = subtitle.get_modified_content(format=format, debug=debug_mods)
 File "/app/bazarr/bazarr/../libs/subliminal_patch/subtitle.py", line 340, in get_modified_content
  return fix_text(self.content.decode(encoding=self._guessed_encoding), **ftfy_defaults).encode(
UnicodeEncodeError: \latin-1\ codec can\t encode character \\\u2019\ in position 13701: ordinal not in range(256)
```

**To Reproduce**
1. Go to a Tv-Show
2. Click on Manual Search
3. Click on the download button of a subtitle
4. See error in log

**Expected behavior**
Subtitle should be saved

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: v0.8.4.2
 - Radarr version N/A
 - Sonarr version N/A
 - OS: Ubuntu

**Comment by morpheus65535** [comment]
Can you test dev branch? We've made some changes that haven't been merged to master yet.

**Comment by svenvg93** [comment]
I want to but there is no docker version i'm afraid

**Comment by morpheus65535** [comment]
What is the subtitles language?

**Comment by svenvg93** [comment]
subtitles language is dutch 

Just had this error again with a different file; 

`Traceback (most recent call last):
 File "/app/bazarr/bazarr/get_subtitle.py", line 423, in manual_download_subtitle
  saved_subtitles = save_subtitles(video.original_path, [subtitle], single=single,
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 874, in save_subtitles
  content = subtitle.get_modified_content(format=format, debug=debug_mods)
 File "/app/bazarr/bazarr/../libs/subliminal_patch/subtitle.py", line 353, in get_modified_content
  return fix_text(self.content.decode(encoding=self._guessed_encoding), **ftfy_defaults).encode(
UnicodeEncodeError: \latin-1\ codec can\t encode character \\\u2018\ in position 23582: ordinal not in range(256)`

**Comment by morpheus65535** [comment]
Please provide the link to download this subtitles.

**Comment by svenvg93** [comment]
https://www.opensubtitles.org/en/subtitles/8170547/ncis-schooled-nl

**Comment by morpheus65535** [comment]
@pannal somethign wrong in guess encoding in subliminal_patch for this Dutch subtitles. Sublimine Text 3 tell me it'S CP1252.

**Comment by svenvg93** [comment]
@morpheus65535 version 0.9 the problem persists with every subtitle.

`Traceback (most recent call last):
 File "/app/bazarr/bazarr/get_subtitle.py", line 418, in manual_download_subtitle
  saved_subtitles = save_subtitles(video.original_path, [subtitle], single=single,
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 874, in save_subtitles
  content = subtitle.get_modified_content(format=format, debug=debug_mods)
 File "/app/bazarr/bazarr/../libs/subliminal_patch/subtitle.py", line 367, in get_modified_content
  return fix_text(self.content.decode(encoding=self._guessed_encoding), **ftfy_defaults).encode(
TypeError: decode() argument \encoding\ must be str, not None `

https://www.opensubtitles.org/en/subtitles/8214872/billions-beg-bribe-bully-nl

**Comment by morpheus65535** [comment]
@svenvg93 I know, nothing have been done to fix it. :-/

I'm waiting on @pannal for this one.

**Comment by josdion** [comment]
@svenvg93 Can you test development branch again? I think it should be fixed now. 

[c89d54](https://github.com/morpheus65535/bazarr/commit/c89d542479af2205dc90f59ab71cf52e89b09b1a)

**Comment by morpheus65535** [comment]
No answer. Re-open this issue if you still need a fix.
