### ISSUE TITLE
Some issues I'm getting...

### ISSUE THREAD

**Issue by DatsiK96** [morpheus65535/bazarr#918]
Hello I just setup Bazarr for the first time, and I'm having some issues that I can't seem to get past... Here's some background info:

Installed on Windows
v0.8.4.2
Have both working Radarr/Sonarr
All three services are installed on the same windows server

So first off, I'm getting errors with attempting to download subs.
I've setup Anti Captcha, addic7ed, Subscene, and OpenSubtitles.
When I tested some movies, I get exceptions throughout the log files that I can't interpret.

09/04/2020 16:34:15|ERROR   |apscheduler.executors.default   |Job "movies_download_subtitles_1 (trigger: date[2020-04-09 16:34:15 PDT], next run at: 2020-04-09 16:34:15 PDT)" raised an exception|Traceback (most recent call last):  File "d:\bazarr\bazarr\../libs\apscheduler\executors\base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)  File "d:\bazarr\bazarr\get_subtitle.py", line 639, in movies_download_subtitles    if ast.literal_eval(movie['missing_subtitles']):  File "D:\Bazarr\WinPython\python-3.8.0\lib\ast.py", line 96, in literal_eval    return _convert(node_or_string)  File "D:\Bazarr\WinPython\python-3.8.0\lib\ast.py", line 95, in _convert    return _convert_signed_num(node)  File "D:\Bazarr\WinPython\python-3.8.0\lib\ast.py", line 74, in _convert_signed_num    return _convert_num(node)  File "D:\Bazarr\WinPython\python-3.8.0\lib\ast.py", line 66, in _convert_num    raise ValueError('malformed node or string: ' + repr(node))ValueError: malformed node or string: None|

Am I missing something here?

Secondly, every TV Show/Movie has a "this path doesn't seem to be valid" error. It's using a UNC path to a file share.

I don't really understand the whole path mappings settings... So I may have something improperly configured, it's currently all blank.

Lastly, it seems that the API connection to Sonarr/Radarr are functioning correctly, but when I test the connection, it says that it's wrong and I can't progress till fixing it. But according to the logs, it's able to connect just fine.

09/04/2020 16:34:24|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): {SONARRURL}|
09/04/2020 16:34:24|DEBUG   |urllib3.connectionpool          |{SONARRURL} "GET /api/system/status?apikey=******** HTTP/1.1" 200 322|
09/04/2020 16:51:43|INFO    |apscheduler.executors.default   |Job "Update Series list from Sonarr (trigger: interval[0:01:00], next run at: 2020-04-09 16:52:43 PDT)" executed successfully|
Thoughts? What can I provide to help?

Thank you.

**Comment by morpheus65535** [comment]
First error is the result of improperly configured path mapping. Come to Discord for help setting it correctly.

For the last one, I would be curious to know more about your setup. Does Sonarr/Radarr are installed on the same windows machine? What did you put in config before pressing Test button?

**Comment by DatsiK96** [comment]
Problems have been resolved.

Problem 1: seems to be related to a reverse proxy issue on the client side. Bypassing the proxy allows this to work.

Problem 2: Was because the windows service wasn't running as an account with share permissions (defaults to system context), changed the service to use a network account, all fixed. Also added mapped pathing which seemed to finalize the solution to this. I didn't see the wiki page before posting so sorry.

Problem 3: API testing was also related to the reverse proxy. Bypass the proxy and it works. There's a page in the wiki about reverse proxies, but I'm using IIS, not Apache or Nginx, so I think it has to do with this capability that apache has 

> "Apache 2.3.12 or greater is required to support AllowEncodedSlashes NoDecode which is required for Sonarr/Radarr config testing."

 if I could get that in IIS I'm sure this would be resolved.

Closing this. Thanks.
