### ISSUE TITLE
A tiny bit more help at the beginning

### ISSUE THREAD

**Issue by janlimpens** [morpheus65535/bazarr#92]
Hello, I managed to install the image using docker.

[docker ps] gives me
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                   PORTS               NAMES
7f7bc16d303e        morpheus65535/bazarr:latest   "/init python /baz..."   22 minutes ago      Restarting (1) 4 minutes ago                       bazarr

Now, what should I do next? I went to http://myip:6767, because that was the port I supplied, following the sample config, but the is no service running.

The wiki leaves this point completely out and as I have no experience with docker, I have no clue. I did this on a rasperypie2, with libreelec and the supplied docker add-on.

Any help?

Thanks!
Jan

**Comment by morpheus65535** [comment]
Could you please give me the output of:

    docker logs bazarr

**Comment by morpheus65535** [comment]
Hummm.. seems to be related to your docker installation on LibreElec. I have never tried and got no hardware to test it ATM. Sorry, you're going to need to use your google-fu. :-/

**Comment by janlimpens** [comment]
Ok, once I find something, I'll leave a note here, if that's ok.

Thanks!

**Comment by morpheus65535** [comment]
Sure! Thanks!

**Comment by janlimpens** [comment]
The error was raised because the docker compile was for a different architecture.
I found a docker container https://hub.docker.com/r/gwelican/bazarr-armhf/ that installs and runs, but I get the impression, that it is based on an older version of bazarr (0.4.1), where there seems to be no support for radarr. Difficult to say - this docker thing is a bit opaque for me. Also it cannot connect to my sonarr api.

**Comment by morpheus65535** [comment]
Have you tried the official armhf image? morpheus65535/bazarr:armhf-latest

**Comment by janlimpens** [comment]
This worked! I am sure it would be a great help for raspi users, if that were mentioned somewhere on the docker installation page.

Thanks!

**Comment by morpheus65535** [comment]
I will modify the wiki. My bad!
