### ISSUE TITLE
Manual upload subtitles not saving into custom subtitle folder

### ISSUE THREAD

**Issue by bin28281010** [morpheus65535/bazarr#920]
**Describe the bug**
Only manual upload subtitles not saving into the custom subtitle folder (my setting: relative path to media file), the auto-downloads subtitles work fine.

**To Reproduce**
1. Go to 'a series'
2. Click on 'manual upload'
4. upload successfully
5. error: subtitles upload to the wrong folder (my set is "relative path to media file", but it uploads to alongside the media file)

**Expected behavior**
manual upload successfully to my custom subtitle folder

**Screenshots**
none

**Software (please complete the following information):**
Bazarr Version:
0.8.4.2
Sonarr Version:
2.0.0.5344
Radarr Version:
0.2.0.1480
Operating System:
Linux-4.9.0-12-amd64-x86_64-with
Python Version:
3.8.2
Bazarr Directory:
/app/bazarr
Bazarr Config Directory:
/config

**Additional context**
none

**Comment by morpheus65535** [comment]
I've just pushed a fix to dev branch, could you test it please?

**Comment by bin28281010** [comment]
the latest version  v0.8.4.3? I have tested the version v0.8.4.3, the version works fine with manual uploads subtitles to the custom relative folder.

**Comment by morpheus65535** [comment]
Yes it is! Good to know and thanks for reporting!
