### ISSUE TITLE
Bazarr does not download new movie subs after adding language

### ISSUE THREAD

**Issue by Loewkie** [morpheus65535/bazarr#921]
First of all I'd like to thank you for all the work you've done on Bazarr. It's an absolute lifesaver and I can't thank you enough.

So I've recently added a language to all my shows and movies (German). And it seems that the movies that are newly added or updated on Radarr's side get German subtitles. However, all movies that were already present get ignored by the auto download utility. Problem being that it seems right now I have to manually download 1000 subtitles.

**To Reproduce**
1. Add new language
2. Wait
3. Movies that were already present do not obtain subtitles in new language

1. Add new language
2. Wait
3. Movies that were already present do obtain subtitles in new language

**Software (please complete the following information):**
 - Bazarr: 0.8.4.2 
 - Radarr version 0.2.0.1480
 - Sonarr version 3.0.3.750
 - OS: Windows 10

**Comment by morpheus65535** [comment]
I've just test it with dev branch (0.8.4.3) and it's working fine. I should merge it today and you should benefit from the last fixes once updated. Please confirm after that if this is still and issue.

**Comment by Loewkie** [comment]
OK thanks. After the update I'll give it an additional day to check whether it works or not. If not I'll come back to you on this. I'll also attach a log then because I forgot to do that here.

**Comment by morpheus65535** [comment]
Dev branch merged to master. Check and re-open this if you still have issue.

**Comment by Loewkie** [comment]
Unfortunately it still doesn't quite seem to work.

https://pastebin.com/00Dmedxb

**Comment by halali** [comment]
In debug is many malformed mkv files and also download limit reached on opensubtitles. If you haven't VIP membership you can download up to 200 subs.

So if you have 10 000 missing subs it can take some time.

**Comment by Loewkie** [comment]
what would 'malformed mkv's' mean exactly?

**Comment by halali** [comment]
Bazarr can't read if file contain embedded subs or not, for to me unknown reason.

**Comment by morpheus65535** [comment]
You're trying to make Bazarr access media file stored on mapped network drive (Z:\). That's unsupported and even Sonarr and Radarr wiki state that you shouldn't do this. At least configure path mapping in Bazarr to replace drive letter by UNC path.

**Comment by Loewkie** [comment]
I would still like to know if TV and Movie subtitles get put in separate queues or if they are all put into one big queue. If it's all one big queue then that already explains the problem and in that case I'd rather not switch a lot of things around since it's all been smooth sailing so far. Plex, Radarr, Sonarr and Bazarr never had any issue with my mapped drive.

**Comment by halali** [comment]
Its 2 separated queue but both are in one queue, first go series after that movies queue, if you want 2 separated queue i suggest you run 2 bazarr instances

**Comment by Loewkie** [comment]
Thank you @halali I honestly think in that case that there are no actual problems. The only problem being my media library being way to freaking large :D

**Comment by morpheus65535** [comment]
@Loewkie v0.9 will have those two queues running in parallel with to different scheduled tasks starting on a different schedule.

**Comment by Loewkie** [comment]
That sounds great!
