### ISSUE TITLE
No support for Sonarr/Radarr with http authentication enabled

### ISSUE THREAD

**Issue by glensc** [morpheus65535/bazarr#925]
In configuration panel, can't see place to fill username/password for authentication.

Additionally the "test" button could reveal reasons why the connection failed

**Comment by glensc** [comment]
Looks like filling API key helped.

**Comment by halali** [comment]
Yes, apikey is authentication for sonarr and radarr API

**Comment by glensc** [comment]
seems sonarr/radarr have special handling for looking into apikey and then falling back to basic auth.

so the support for inputting basic auth user/password would be still needed if the HTTP authentication is added on proxy level (in Nginx or Apache)

**Comment by halali** [comment]
No API key is for API authorization and username/pass is for UI authorization.

**Comment by glensc** [comment]
@halali, if I setup sonarr/radarr behind a reverse proxy and configure reverse proxy to enforce HTTP authentication, you can't access any resource under that path without providing HTTP authentication credentials.

So far I'm using HTTP authentication only from sonarr/radarr, reverse proxy only rewrites paths. So for me, problem is solved, but in general it might be still an issue.

**Comment by morpheus65535** [comment]
@glensc we don't support reverse proxy authentication, only the authentication mechanism integrated to Sonarr/Radarr. In fact, it's more safe to direct connect to Sonarr/Radarr without going through a reverse proxy.
