### ISSUE TITLE
Bazarr does not download new movie subs after adding language

### ISSUE THREAD

**Issue by Loewkie** [morpheus65535/bazarr#926]
Unfortunately it still doesn't quite seem to work.

https://pastebin.com/00Dmedxb

Please also see #921

**Comment by Loewkie** [comment]
Are series and movie queues treated separately or are all download loaded into one massive queue? One massive queue would explain my problem as it is still trying to obtain 10000 episode subtitles. Also, it seems that it prioritises new content?

**Comment by halali** [comment]
Can you please fill issue template? Im not sure whats your issue.

I log file i can see many malformed files and unavailable OS provider.

**Comment by Loewkie** [comment]
Ah yes , please refer to #921
