### ISSUE TITLE
Subtitles providers fail with DimensionalityError

### ISSUE THREAD

**Issue by h2xtreme** [morpheus65535/bazarr#927]
Like the title says queries to some subtitles sites fail with: DimensionalityError

Bazarr Version:
0.8.4.3
Sonarr Version:
3.0.3.750
Radarr Version:
3.0.0.2821
Operating System:
Linux-4.19.106-v7l+-armv7l-with-debian-10.3
Python Version:
3.7.3

Failed subtitles providers:

Opensubtitles
Legendasdivx

bsplayer is also giving an exception:

HTTPConnectionPool(host='s7.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: /v1.php (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...

**Comment by morpheus65535** [comment]
You're probably getting blocked by your internet provider or country. I would try using a VPN.

**Comment by h2xtreme** [comment]
Negative. I can access both sites and manually download subtitles without issue. 

Ping and telnet to tcp/443 are also fine.

**Comment by morpheus65535** [comment]
Unless you provide a debug log reproducing the issue, there's not much I can do to help you. FYI, over 28 000 subtitles have been downloaded from OpenSubtitles alone yesterday... I guess you have something wrong with your Bazarr config :-)

**Comment by h2xtreme** [comment]
[bazarr(1).log](https://github.com/morpheus65535/bazarr/files/4469998/bazarr.1.log)

Log attached.

**Comment by h2xtreme** [comment]
Missing Info:

Bazarr install is running on Debian 10 Buster

**Comment by morpheus65535** [comment]
Could be related to https://github.com/morpheus65535/bazarr/issues/728

**Comment by morpheus65535** [comment]
Debian buster seems to have enforced some limitation over openssl at operating system level. When providers don't comply, you get exception.

**Comment by h2xtreme** [comment]
The error on legendasdivx is this one:

`13/04/2020 15:53:09|ERROR   |subliminal_patch.core           |Unexpected error in provider 'legendasdivx': Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 186, in list_subtitles_provider    s.plex_media_fps = float(video.fps) if video.fps else None  File "/home/plex/.local/lib/python3.7/site-packages/pint/quantity.py", line 535, in __float__    raise DimensionalityError(self._units, 'dimensionless')pint.errors.DimensionalityError: Cannot convert from 'FPS' to 'dimensionless'|Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 186, in list_subtitles_provider    s.plex_media_fps = float(video.fps) if video.fps else None  File "/home/plex/.local/lib/python3.7/site-packages/pint/quantity.py", line 535, in __float__    raise DimensionalityError(self._units, 'dimensionless')pint.errors.DimensionalityError: Cannot convert from 'FPS' to 'dimensionless'|`

bsplayer:

`13/04/2020 15:53:18|INFO    |subliminal_patch.providers.bsplayer|ERROR: HTTPConnectionPool(host='s6.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: /v1.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa44d63d0>: Failed to establish a new connection: [Errno 111] Connection refused')).|`

podnapisi

`13/04/2020 15:53:08|WARNING |retry.api                       |HTTPSConnectionPool(host='www.podnapisi.net', port=443): Max retries exceeded with url: /subtitles/search/old?sXML=1&sL=pt&sK=The+Hustle&sY=2019 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls12_check_peer_sigalg', 'wrong signature type')])"))), retrying in 5 seconds...|`

opensubtitles:

`13/04/2020 16:35:58|ERROR   |subliminal_patch.core           |Unexpected error in provider 'opensubtitles': Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 186, in list_subtitles_provider    s.plex_media_fps = float(video.fps) if video.fps else None  File "/home/plex/.local/lib/python3.7/site-packages/pint/quantity.py", line 535, in __float__    raise DimensionalityError(self._units, 'dimensionless')pint.errors.DimensionalityError: Cannot convert from 'FPS' to 'dimensionless'|Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 186, in list_subtitles_provider    s.plex_media_fps = float(video.fps) if video.fps else None  File "/home/plex/.local/lib/python3.7/site-packages/pint/quantity.py", line 535, in __float__    raise DimensionalityError(self._units, 'dimensionless')pint.errors.DimensionalityError: Cannot convert from 'FPS' to 'dimensionless'|`

**Comment by morpheus65535** [comment]
Could you try to update `pint` module? `pip install -U pint`

I hope that it will solve # 1 and # 4.

# 2 seams to be related to provider stability. Your not the first having this issue.

# 3 is related to openssl configuration hardening done with Debian Buster. Nothing I can do on my side. You need to adjust those configurations if you want to use providers that do not meet the default one.

**Comment by h2xtreme** [comment]
My setup had pint on the version 0.9. Upgraded to 0.11 restarted bazarr but the error remains the same

**Comment by h2xtreme** [comment]
Update:

Regarding #3: I edited the SEClevel on debian ssl config and I moved passed the SSL Error but now I get the same error as the other providers: DimensionalityError

**Comment by morpheus65535** [comment]
Here's the output of `pip freeze` with Python 3.7.4 on Windows 10:
`lxml==4.4.1`

**Comment by h2xtreme** [comment]
My lxml is the 4.5.0

I think I figured the problem. I had the pip module for pint installed. With Python 3.6+ that's not needed, pint already comes in the standard python. The solution was delete the pip module (or the python3-pint package if using the one provided by the package manager)

More info here: https://pypi.org/project/Pint/

To summarize:

- DimensionalityError comes from an incompatible pint module. If running python3.6+ no need to install pint

- The SSL error on popnapisi, happens on Debian Buster (at least). This is an issue with popnapisi.net server that doesn't handle the TLS 1.2, SECLEVEL=2 setting. 
  
  There's 2 solutions for this:

  - Either discard the provider because its TLS/SSL configs are actually very crappy
  - Lower the SECLEVEL setting on /etc/ssl/openssl.cnf to SECLEVEL=1

  It's actually possible to check behaviour with following commands:

  More secure setting, fails to connect to website:
  `openssl s_client -connect www.podnapisi.net:443 -cipher DEFAULT@SECLEVEL=2`

  Less secure setting, connects to website:
  `openssl s_client -connect www.podnapisi.net:443 -cipher DEFAULT@SECLEVEL=1`

- bsplayer provider issue seems to also be on the provider side, for now no solution for this. Debugging this, I checked for subtitles dozens of times none of them worked with this provider

@morpheus65535: On the provider tab, any chance we get a button or something to clear the 10 minute throttling!? Waiting 10 minutes between tests was a bit of a pain :P

**Comment by morpheus65535** [comment]
Thank you very much for sharing the result of your long debugging session with us! :-)

I agree on the button to clear throttling status. I've put that on my to do list.

May I close this issue or do you want to wait on bsplayer investigation result?

**Comment by h2xtreme** [comment]
On the bsplayer, does it work for you!? It might be my ip/country being rejected on the server side.

The s3.api.bsplayer-subtitles.com server rejects my connection on port 80 (http) and port 443 (https).

Also their https uses a self-signed certificate. If it gives problems to more users and given the lack of security on connecting to this provider I would just drop support for it. 

You can close this for sure. The main issue reported was fixed.

Thanks for your help :)

**Comment by morpheus65535** [comment]
Do you mean `http://s3.api.bsplayer-subtitles.com/` doesn't work for you even from a browser? In my case, it work from my browser (return nothing but a 200 http status) and also work when I do a manual search in Bazarr.

**Comment by h2xtreme** [comment]
Nope. Not even on a browser. Connection refused everytime. I can access bsplayer-subtitles.com though. 

Must be a IP/country block server side. 

Also, don't if you're aware but bsplayer has more servers supporting the api. Might be useful

Check the list here:

https://github.com/realgam3/service.subtitles.bsplayer/blob/master/resources/lib/bsplayer.py

**Comment by morpheus65535** [comment]
Thanks a lot for the info!

**Comment by dmwyatt** [comment]
FWIW, I'm also getting connection refused to bsplayer both in bazaar logs and in a browser.

I can get it to work in the browser if I run it through a VPN running in an Azure cloud instance...

**Comment by vitiko98** [comment]
@hferreira23 This is fixed in current dev. Thanks a lot for your help!
