### ISSUE TITLE
SubsUnacs and SubsSabBz providers getting throttled due to invalid archive error

### ISSUE THREAD

**Issue by screamerbg** [morpheus65535/bazarr#928]
Both SubsUnacs and SubsSabBz providers may get throttled (effectively disabled) for 10+ minutes when any subtitles archive is broken. See below:

```
2020-04-12 21:33:06,346 - root                             (21b0) :  INFO (get_providers:172) - Throttling subsunacs for 10 minutes, until 20/04/12 21:43, because of: ValueError. Exception info: 'Not a valid archive'
```

**To Reproduce**
1. Add "The Hunger Games: Mockingjay - Part 2" to your Radarr. You can use any .MKV file - use naming that makes it look authentic, e.g. "The.Hunger.Games.Mockingjay.Part.2.2015.1080p.BluRay.x264.DTS-myrip"
2. Refresh Bazarr movies 
3. Check Bazarr settings and make sure that SubsUnacs provider is enabled.
4. Go to "Movies" -> ""The Hunger Games: Mockingjay - Part 2" in Bazarr and do manual search.
5. Observe your Bazarr logs for the error stated above. Also note that the manual search results  are lacking any subsunacs results even though subtitles are available for this movie on www.subsunacs.net.
6. Your next search for this or other movies will not use SubsUnacs because it's being throttled for 10 minutes.

**Expected behavior**
I would expect that the provider is not throttled and all matching subtitles discarded due to 1 subtitle archive being broken.

**Screenshots**
```
2020-04-12 21:33:06,346 - root                             (21b0) :  INFO (get_providers:172) - Throttling subsunacs for 10 minutes, until 20/04/12 21:43, because of: ValueError. Exception info: 'Not a valid archive'
```

**Software (please complete the following information):**
 - Bazarr: 0.8.4.4 (branch development)
 - Radarr version 0.2.0.1480
 - Sonarr version 2.0.0.5344
 - OS: Windows 10

**Additional context**

**Comment by morpheus65535** [comment]
I would gladly accept a PR to fix this :-)

**Comment by josdion** [comment]
Subtitles archive is not broken, but it's not supported. Currently only zip and rar files are supported and the archive file which you're trying to download is 7zip. But you're right this should not throttle the provider. I'll make PR to skip unsupported files and to log the error, instead of trowing an exception. 

@morpheus65535 what do you think about including additional library in bazarr to support more archive file formats? Something like [https://github.com/miurahr/py7zr](url) or [https://github.com/dsoprea/PyEasyArchive](url).

**Comment by morpheus65535** [comment]
@josdion of course we can better manage exception for that. In the future, we could also add more supported archive format but I'm always cautious when adding executable that would require maintenance over time.

**Comment by morpheus65535** [comment]
@screamerbg does this latest commit fix your issue?

**Comment by screamerbg** [comment]
@morpheus65535 Yes, it does, thank you.
