### ISSUE TITLE
Job "Update Bazarr from source on Github (trigger: interval[6:00:00], next run at: 2020-04-14 13:04:19 EEST)" raised an exception

### ISSUE THREAD

**Issue by dimitrow7** [morpheus65535/bazarr#930]
System: FreeNAS (FreeBSD) Jail installation. Current Ver. 0.8.4.2 

I used **root** for running user.

When update job run:

```
Traceback (most recent call last):
 File "/usr/local/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/usr/local/bazarr/bazarr/check_update.py", line 44, in check_and_apply_update
  g.fetch(\origin\)
 File "/usr/local/bazarr/bazarr/../libs/git/cmd.py", line 548, in
  return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
 File "/usr/local/bazarr/bazarr/../libs/git/cmd.py", line 1014, in _call_process
  return self.execute(call, **exec_kwargs)
 File "/usr/local/bazarr/bazarr/../libs/git/cmd.py", line 825, in execute
  raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd(\/usr/local/bin/git\) failed due to: exit code(128)
 cmdline: /usr/local/bin/git fetch origin
 stderr: \fatal: \origin\ does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.\
```

**Comment by morpheus65535** [comment]
You probably downloaded a copy of the source code from Github instead of doing a `git clone`.

**Comment by dimitrow7** [comment]
This is the exeption when the automatic updates run.

**Comment by morpheus65535** [comment]
I know but what it means is that Git isn't able to recognize the repository to get new the updated sources. You can try to do a `git pull` from inside Bazarr directory from the command line. If it doesn't work, make sure to backup your data directory, remove Bazarr directory and `git clone` again.

**Comment by fulder** [comment]
This error was found in an iocage bazarr plugin (see issue: https://github.com/fulder/iocage-plugin-bazarr/issues/1) and was caused by the bazarr plugin being installed from the `tar` archive instead of using `git` (just like you mentioned @morpheus65535 ). Changing it to a proper git clone seems to have fixed this issue. 

In other words this has probably nothing to do with bazarr itself but just incorrectly installation. This issue could maybe be closed?

**Comment by morpheus65535** [comment]
Thanks for the feedback! Of course, installing from tar is unsupported or you must use the `--no-update` or `--release-update` command line parameter.
