### ISSUE TITLE
|Job "Update Movie list from Radarr (trigger: interval[0:05:00], next run at: 2020-04-14 10:57:10 CDT)" raised an exception|

### ISSUE THREAD

**Issue by ExorDG** [morpheus65535/bazarr#932]
**Describe the bug**
I start to have issue with movies that were downloaded and imported by Radarr did not have subtitles for a few days to weeks. I noticed the issue a few days ago but it has been going on for past few weeks so I decided to check log and found this exception error. Probably not related but wanted to get this fixed to see if it will download subtitles to these movies that were imported by Radarr.

The exception error shown every 5 mins (the interval search):

14/04/2020 10:52:11|ERROR   |apscheduler.executors.default   |Job "Update Movie list from Radarr (trigger: interval[0:05:00], next run at: 2020-04-14 10:57:10 CDT)" raised an exception|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\../libs\\apscheduler\\executors\\base.py", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File "c:\\bazarr\\bazarr\\get_movies.py", line 272, in update_movies\n    movies_download_subtitles(altered_movie[2])\n  File "c:\\bazarr\\bazarr\\get_subtitle.py", line 681, in movies_download_subtitles\n    if ast.literal_eval(movie[\'missing_subtitles\']):\n  File "C:\\Bazarr\\WinPython\\python-3.8.0\\lib\\ast.py", line 96, in literal_eval\n    return _convert(node_or_string)\n  File "C:\\Bazarr\\WinPython\\python-3.8.0\\lib\\ast.py", line 95, in _convert\n    return _convert_signed_num(node)\n  File "C:\\Bazarr\\WinPython\\python-3.8.0\\lib\\ast.py", line 74, in _convert_signed_num\n    return _convert_num(node)\n  File "C:\\Bazarr\\WinPython\\python-3.8.0\\lib\\ast.py", line 66, in _convert_num\n    raise ValueError(\'malformed node or string: \' + repr(node))\nValueError: malformed node or string: None'|

**To Reproduce**
This error appears every interval search which is 5 mins.

**Expected behavior**
Expected no error when doing interval search.

**Software (please complete the following information):**
 - Bazarr: v0.8.4.3
 - Radarr version 0.2.0.1480
 - OS: Windows 10

**Comment by morpheus65535** [comment]
Use the batch editor and define a desired language (or `None`) for all your movies. That will recalculate the `missing_subtitles` column of the `table_movies` table

**Comment by ExorDG** [comment]
All movies listed are set to English and all the future movies will be set to English automatically. All the movies in the wanted list shows "en" button and clicking on it will download just fine. It just won't download subtitles when Radarr imported them.

**Comment by morpheus65535** [comment]
In fact there's only one problematic file which is Blade Runner 2049 (filename seems to not sync correctly). I suggest you remove it from Radarr, sync movie in Bazarr then import it again in Radarr. It should then sync correctly in Bazarr and index existing subtitles correctly.

**Comment by morpheus65535** [comment]
@ExorDG can I close this issue?

**Comment by ExorDG** [comment]
Go ahead. It seems to be working now. I have not checked the error yet but
most of movies now have subtitles.
