### ISSUE TITLE
Ways to differentiate Chinese Subtitles

### ISSUE THREAD

**Issue by saishowaguu2** [morpheus65535/bazarr#935]
Hello.

I am not sure if this the right place to request this.

I have setup Bazarr to download Chinese Subtitles.
However, it seems we can only select ZH. This results in subs that are be downloaded as zh-hans.

Is there a way to change Bazarr so it downloads zh-cn (for standard Mandarin), especially from the subtitle site Assrt?

This is somewhat related to issue #460

**Comment by morpheus65535** [comment]
Unfortunately it's not possible, Bazarr is based on ISO-639 that do not include a code for Mandarin. https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
