### ISSUE TITLE
Bazarr Failed connection test to Sonarr/Radarr

### ISSUE THREAD

**Issue by JustOMaR-ZX** [morpheus65535/bazarr#937]
Hello All, 
I'm trying to connect Bazarr to Sonarr and Radarr  but no luck, 
My setup is through docker, 

When connecting to the Jackett for example , I'm using 172.17.0.1 with the port and API Key. 

I have tried to do the same from Bazarr but it didn't work ..

https://i.imgur.com/jhkAGtH.jpg 

Please advise ..

**Comment by morpheus65535** [comment]
Use Sonarr or Radarr container name instead of ip address. Come to Discord for live support.
