### ISSUE TITLE
Manual upload won't work

### ISSUE THREAD

**Issue by Aurel004** [morpheus65535/bazarr#939]
**Describe the bug**
I try to manually upload a srt file corresponding to my episode (Fear the walking dead S05E08), it says it's processing but the file isn't added in the server nor marked as uploaded on Bazarr.

**To Reproduce**
1. Manually upload an episode
2. Select French
3. Forced unselected
4. Choose file
5. Save

**Expected behavior**
The subtitle file to be uploaded into the server and marked as done.

**Software (please complete the following information):**
 - Bazarr: 0.8.4.3
 - Radarr version 3.0.3.764
 - Sonarr version 0.2.0.1480
 - OS: Windows-10-10.0.18362-SP0

About logfile : I clicked save around 21h24m00s
[logFileBazarr.log](https://github.com/morpheus65535/bazarr/files/4512792/logFileBazarr.log)

**Additional context**
I'm running Sonarr and Radarr on a Synology and Bazarr on Windows 10, working fine when it finds the subs

**Comment by morpheus65535** [comment]
It seems that this episode doesn't have a path in DB or you have a bad path mapping.

I would also suggest you upgrade your Sonarr which is quite old.

**Comment by Aurel004** [comment]
For Sonarr (and Bazarr) the episode exists and path (for Sonarr) is : /volume1/Séries/Fear the Walking Dead/Saison 5/Fear the Walking Dead - S05E08 - WEBDL-1080p.mkv

I'm on Sonarr v3 not v2, my version is up to date now to the newest (21 Apr 2020) Sonarr 3.0.3.770

**Comment by morpheus65535** [comment]
I can see that it is added to history but there's no video path (empty string):

`INSERT INTO table_history (action, sonarrSeriesId, sonarrEpisodeId, timestamp, description,video_path, language, provider, score) VALUES (?,?,?,?,?,?,?,?,?), (4, '3', '222', 1587497056.2415473, 'French Subtitles manually uploaded.', '', 'fr', 'manual', 360)`

Of course a video file without a path cannot work. It looks like a path mapping issue. What is your path mapping configuration for Sonarr?

**Comment by Aurel004** [comment]
![image](https://user-images.githubusercontent.com/20973812/80012352-7f78b280-84cd-11ea-9d28-fff860d9fc8e.png)

And Bazarr is seeing it
![image](https://user-images.githubusercontent.com/20973812/80012425-9e774480-84cd-11ea-957e-82b15daea165.png)

**Comment by morpheus65535** [comment]
I've pushed a fix to dev branch, could you please test it and confirm if the issue persist? Thanks!

**Comment by Aurel004** [comment]
Working fine, thank you!
