### ISSUE TITLE
Bazarr Wont download subtitles. 

### ISSUE THREAD

**Issue by Chuchodavids** [morpheus65535/bazarr#940]
**Describe the bug**
I have tried everything. I even bought the OpenSubtitles premium thinking that Bazarr was not downloading files because I reached my daily limit. 
To be more precise Bazarr doesn't download automatically the subtitles. If I manually look for the subtitles it will find them. 

**To Reproduce**
1. Activated Opensubtitles account only, VIP activated, SSL activated and SKIP the wrong fps activated.
2. I click on Wanted icon, and then in DOwnload missing subtitles.
3. It starts to search for the subtitles but it won't grab anything. It just keeps "searching for series subtitles"
4. nothing happens

**Expected behavior**
I expect to download all the subtitles in bulk.

**Software (please complete the following information):**
 - Bazarr: v0.8.4.3
 - Radarr version [0.2.0.1480]
 - Sonarr version [2.0.0.5344]
 - OS: [Unraid Version: 6.8.3 ]

**Additional context**
It seems like the bug is being caused by the skip wrong FPS. After disabling it, now it is downloading. 
I know the whole point of "Skip wrong FPS is to not download wrong subtitles. However, when it is active no subtitles are downloaded.

**Comment by morpheus65535** [comment]
I've just verified and I have this settings enabled for Open Subtitles. It works fine for me. Could you provide a debug log while reproducing the issue? Please empty your log first.

**Comment by Chuchodavids** [comment]
Hello Morpheus. I did not answer because I started tinkering around after you said it worked for you. It seems to be working. I was reading through the logs and it skips a lot of subtitles because of the wrong FPS, which again I understand. Nonetheless, I would be way better if it is the case that no subtitles with the right FPS are found, download the one with the highest score. 
here are my logs just in case.
[bazarr (1).log](https://github.com/morpheus65535/bazarr/files/4517412/bazarr.1.log)

**Comment by morpheus65535** [comment]
This part of the code is shared with Sub-Zero and I cannot simply change this behaviour. This is not a "prefer matching FPS", it's an "ignore wron FPS" settings. TBH, you could disable this settings and have a minimum score that will exclude poorly matching subtitles and lets upgrade mechanism do it's work.

**Comment by Chuchodavids** [comment]
Hmm.. sounds good. Sorry that I created a whole threat just for this.

**Comment by morpheus65535** [comment]
No problem!
