### ISSUE TITLE
No scene name for manually imported movies

### ISSUE THREAD

**Issue by Zamana** [morpheus65535/bazarr#941]
**Describe the bug**
It seems there are no "scene name" when you manually import a film from Radarr.

**To Reproduce**
1. Search and download a movie using your torrent or nzb client
2. Add the movie into Radarr, but don't let it to download automatically.
3. In Radarr, go to "Wanted", "Manual Import", and import the movie.
4. Go to Bazarr, find the movie, and try to grab a subtitle.
5. You'll see that the "Scene Name" is empty...

**Expected behavior**
As long as the movie was imported using the "Raddar engine", the scene name should be there.

**Screenshots**
Attached.

**Software (please complete the following information):**
 - Bazarr: 0.8.4.2
 - Radarr version: 0.2.0.1480
 - OS: FreeNas 11.3-U2

<img width="923" alt="Screen Shot 2020-04-22 at 12 34 41" src="https://user-images.githubusercontent.com/6900313/80002258-c945a680-8495-11ea-8dda-41100dc36426.png">

**Comment by morpheus65535** [comment]
It's not an issue with Bazarr, Radarr do not populate this field when importing. Nothing we can do about it.

**Comment by Zamana** [comment]
Ok. I'm sorry for open the issue.

Thanks.
