### ISSUE TITLE
Bazarr doesn't update path after movie is upgraded

### ISSUE THREAD

**Issue by irritatedcone** [morpheus65535/bazarr#945]
**Describe the bug**
Movies get upgraded quite a bit in my library, first it might grab the 1080p release and upgrade it to 4k. Then it might upgrade the 4k release to 4k in x256 format. Bazarr doesn't seem to update this information. It results in "This Path may not be valid", since the file name changes.

**To Reproduce**
1. Download a movie
2. Have Bazarr index it
3. Upgrade the movie to another quality or codec - anything that changes the file name really
4. Go to Movies in Bazarr and see the Warning icon for the movie.

**Expected behavior**
I expect Bazarr to check if the path / filename has changed when it indexes the movies from Radarr.

**Software (please complete the following information):**
 - Bazarr: [e.g. v 0.8.4.2]
 - Radarr version [e.g. v 0.2.0.1480 ]
 - Sonarr version [e.g. v 3.0.3.717]
 - OS: [e.g. Linux-4.2.8-aarch64-with]

**Comment by josdion** [comment]
I think it is already fixed in bazarr 0.8.4.3

**Comment by irritatedcone** [comment]
Ah correct, I should have checked that, my bad.
