### ISSUE TITLE
BAZARR Error saving Subtitles file to disk for this file - notification

### ISSUE THREAD

**Issue by Blutti** [morpheus65535/bazarr#948]
**Describe the bug**
Currently, if a `BAZARR Error saving Subtitles file to disk for this file <bla>` error is generated it is only dumped to the log. It is not communicated to the user (that I can find anyway) that something went wrong

(The reason I got that error in the first place is that I didnt have write access to that file -> 100% my fault. Thats not what this BR is about :) )

**To Reproduce**
<Generate the error; e.g. by not having write access to the folder>

**Expected behavior**
I would expect an error counter/notification thingy above the 'system' icon (like what happens when you have incorrect credentials for providers).

**Screenshots**
![image](https://user-images.githubusercontent.com/9059852/80310402-d5559f00-87da-11ea-9d14-8a05e83b9ff5.png)

**Software (please complete the following information):**
- Bazarr: 0.8.4.3 (dockerized)
- Sonarr: 2.0.0.5344
- Radarr: 0.2.0.1480
- Python: 3.8.2
- Operating System: Linux-4.15.0-96-generic-x86_64-with

**Comment by morpheus65535** [comment]
That would be a feature request, could you create it following #525 please? Thanks.
