### ISSUE TITLE
Different subliminal scores for TV and Movies

### ISSUE THREAD

**Issue by peskdale** [morpheus65535/bazarr#95]
For TV shows, I use a minimum score of 90 to get good matches. However for movies, I need to lower the score to around 70 to get any matches.

It would be great to have two separate minimums scores - one for TV, one for movies.

**Comment by morpheus65535** [comment]
I was afraid someone would ask this one... ;-)

Got the same problem here. At 90, I don't get anything for movies. I'm going to add this one to the backlog.

**Comment by morpheus65535** [comment]
Coud you test this in dev branch and give me your feedback please?

**Comment by peskdale** [comment]
https://github.com/morpheus65535/bazarr/blob/development/get_subtitle.py#L24
Looks like you missed one. Python errors when searching for movie subtitles: `ValueError: could not convert string to float: True`

**Comment by morpheus65535** [comment]
Yeah you're right! Thanks!

**Comment by peskdale** [comment]
Seems to be working now. Looks good.

**Comment by morpheus65535** [comment]
Thanks!
