### ISSUE TITLE
test failed between sonarr & radarr

### ISSUE THREAD

**Issue by beans4me** [morpheus65535/bazarr#950]
**Background**
Just discovered Bazarr and trying to set it up but it won't connect. 
Running a win10 box with Sonarr, Radarr, Jacket and now Bazarr.

**Software Versions**
Sonarr v2.0.0.5344
Radarr v0.2.0.1480
Bazarr v0.8.4.3

**Problem**
When i go enter the info for the connection to test it always fails on both Sonarr and Radarr.
I tried the following based on reading through a few of the solved problems.
**IP address** - 127.0.0.1 and the machine IP. (i dont think this is my issue since everything is running on 1 win machine. I think this was related to Docker issue)
**Listening Port** - these are default from Sonarr (8989) and Radarr (7878), I can access the web portals fine from other computers.
**Base URL** - I tried a few things here "/", /sonarr/, /radarr/ based on some previous issue comments. no success here
**API Key** - pulled directly from Sonarr and Radarr and also regenerated new ones.

**Log file**
26/04/2020 10:35:58|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): 127.***.***.***:8989|
26/04/2020 10:35:58|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on 127.***.***.***|
26/04/2020 10:35:58|DEBUG   |urllib3.connectionpool          |http://127.***.***.***:8989 "GET /sonarr/api/system/status?apikey=********33 HTTP/1.1" 400 334|
26/04/2020 10:38:48|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): 127.***.***.***:8989|
26/04/2020 10:38:48|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on 127.***.***.***|
26/04/2020 10:38:48|DEBUG   |urllib3.connectionpool          |http://127.***.***.***:8989 "GET /api/system/status?apikey=********33 HTTP/1.1" 400 334|
26/04/2020 10:38:49|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): 127.***.***.***:8989|
26/04/2020 10:38:49|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on 127.***.***.***|
26/04/2020 10:38:49|DEBUG   |urllib3.connectionpool          |http://127.***.***.***:8989 "GET /api/system/status?apikey=********33 HTTP/1.1" 400 334|
26/04/2020 10:39:18|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): 127.***.***.***:8989|
26/04/2020 10:39:18|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on 127.***.***.***|
26/04/2020 10:39:18|DEBUG   |urllib3.connectionpool          |http://127.***.***.***:8989 "GET /api/system/status?apikey=********33 HTTP/1.1" 400 334|

Lastly I've tried to restart everything when all else failed and still seeing the same issue.

**Comment by halali** [comment]
Did you try also localhost?

**Comment by beans4me** [comment]
localhost worked. Thank you.
