### ISSUE TITLE
None of my Setting Save

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [morpheus65535/bazarr#951]
**Describe the bug**
Non of my Setting Save when trying to change anything from the Setting tab. I change something, hit save. Changes looks like it took place, but if I reload the page non of the settings stick.

**To Reproduce**
1. Go to Settings
2. Change something in Settings
3. Save
4. Nothing Saves

**Expected behavior**
Settings saves

**Software (please complete the following information):**
 - Bazarr: Ver. 0.8.4.3 
 - Radarr version 0.2.0.1480
 - Sonarr version 3.0.3.770
 - OS: [Linux]

**Comment by morpheus65535** [comment]
I would guess there's a permission issue on data directory.

**Comment by Cookie-Monster-Coder** [comment]
The ```config.ini``` file has read and write permissions. Bazarr automatically edits the ```throtteled_providers = {}``` line to reflect the current status. Also, when first setting up Bazarr, going through the wizard it saved all the settings to the file correctly. It just doesn't after the wizard. Logs don't show anything wrong.

**Comment by morpheus65535** [comment]
Could you provide your config.ini file please?

**Comment by Cookie-Monster-Coder** [comment]
> Could you provide your config.ini file please?

Sure. GitHub won't let me upload a .ini file. Hopefully this preserves the file permissions. https://easyupload.io/ct4nni

**Comment by morpheus65535** [comment]
I've just copied this config.ini file and other than added a listening port to Bazarr and Radarr, I did not change anything. I can start Bazarr on Windows 10 with Python 3.8.1, go to settings, generate a new APIKEY to replace the XXXXXXXX... and save config work perfectly well.

**Comment by Cookie-Monster-Coder** [comment]
I'm fine changing the settings manually in the file, I really doubt after everything is set up I"ll have to go back into the settings.

It just weird tho, everything else works fine. Database is being read/written to, and also the ```throtteled_providers = {}``` line in the config file, when a provider gets disabled. The only thing that doesn't work is changing the settings via UI.

Thanks for trying!

**Comment by morpheus65535** [comment]
Did you try changing browser or using an incognito mode?

Yes, basic auth password is hashed in config.ini. Form username and password must be set using Settings UI.

**Comment by Cookie-Monster-Coder** [comment]
Ok, So I found the issue. I'm using [Organizr Auth](https://docs.organizr.app/books/setup-features/page/serverauth), so in the Nginx config file I had ```auth_request /auth-0;``` which means only allows admin access to /bazarr. Apparently ```/bazarr/save_settings``` was being blocked by Nginx.

Opening up ```/bazarr/save_settings``` by adding
```
location /bazarr/save_settings {
     auth_request off;
     proxy_pass http://127.0.0.1:XXXXX/bazarr/save_settings;
}
```
in the location block for Bazarr seemed to opened up the 'API' (I guess?)

Everything seems to be working fine so far!
Thank you for your help!

**Comment by morpheus65535** [comment]
Thanks for sharing!
