### ISSUE TITLE
Problem with Python version

### ISSUE THREAD

**Issue by LongJohn-Silver** [morpheus65535/bazarr#953]
**Describe the bug**
I have both Python 2.7 and 3.8 installed on my system, and the only way I can run Bazarr using version 3.8 is by doing *python3.8 bazarr.py*. I can't seem to find a way to use autostart with Systemd, I tried replacing *ExecStart=/usr/bin/python /opt/bazarr/bazarr.py* from its default to *ExecStart=/usr/bin/python3.8 /opt/bazarr/bazarr.py* but the localhost won't open. 

**To Reproduce**
1. Try to enter Bazarr's GUI
2. Can't acess

**Expected behavior**
Bazarr automatically using Python's latest version.

**Software (please complete the following information):**
 - Bazarr Version: 0.8.4.3
 - Sonarr Version: 2.0.0.5344
 - Radarr Version: 0.2.0.1480
 - Operating System: Debian 10 Buster
 - Python Version: 3.8.2
 - Bazarr Directory:
 - Bazarr Config Directory: /opt/bazarr/data

**Comment by morpheus65535** [comment]
python3.8 is an "alias" or symlink for an executable stored somewhere else. You can try to find it using which command. Bazarr cannot do this for you.
