### ISSUE TITLE
Bazarr has not worked for two weeks, throws lots of errors

### ISSUE THREAD

**Issue by jds11111** [morpheus65535/bazarr#957]
To gather more information, I cleared the logs, enabled debugging, and ran a couple of tasks. But I can not interpret them. It looks like the logs are anonymized, but wanted confirmation before I upload anything.  Is this the place?

**Comment by morpheus65535** [comment]
You can start with the support team on Discord. Yes logs are anonymized so you can upload them safely.

**Comment by jds11111** [comment]
Thanks.  I wrote here because I was having troubles getting discord to work correctly.  However, in the meantime an update seems to have fixed it somehow.  Thanks for responding.
