### ISSUE TITLE
subsunacs provider issue

### ISSUE THREAD

**Issue by kurumuru** [morpheus65535/bazarr#958]
**Describe the bug**
There are subtitels on subsunacs page, but bazarr is not show them as available option.
[log](https://paste.ubuntu.com/p/4BzSxyybPr/)

**To Reproduce**
Go to series episode and click manual search, for example Narcos Mexico Season2 Episode 10.

**Expected behavior**
Available subtitle from subsunacs to be shown, at least.

**Screenshots**
https://imgur.com/TqPqUKt
https://imgur.com/mplv8tS

**Software (please complete the following information):**

Bazarr Version:
0.8.4.4
Sonarr Version:
2.0.0.5344
Radarr Version:
0.2.0.1480
Operating System:
Linux-4.19.0-8-amd64-x86_64-with
Python Version:
3.8.2
Bazarr Directory:
/app/bazarr
Bazarr Config Directory:
/config

**Additional context**
Provider was working as expected, 1 or 2 months ago.

**Comment by josdion** [comment]
@kurumuru I made a fix in development branch. Can you test it?

**Comment by kurumuru** [comment]
@josdion 
Are these changes applicable for subsunacs.py and yavkanet.py?
Once a image is ready on dockerhub, I'll test it.
10x

**Comment by josdion** [comment]
Yes, I'll fix them too.

**Comment by kurumuru** [comment]
Issue whit subsunacs privider seem to be resolved in latest docker image linuxserver/bazarr:development
