### ISSUE TITLE
LegendasDivx Doesn't work as expected.

### ISSUE THREAD

**Issue by CyberPoison** [morpheus65535/bazarr#959]
**Describe the bug**
The LegendasDivx Provider doesn't return any captive captions (Subtitles) when i found it by searching in the search bar. 

**How to reproduce** 

1º add the provider LegendasDivx and try to find a movie with the subtitles [eg: Dumbo(2019),etc..)
2º try manual import and the result was "nothing found " when in the LegendasDivx.pt you can find everything like expected.

**Expected behavior**
Find subtitles from LegendasDivx.pt and download it from there.

**Software (please complete the following information):**
 - Bazarr: 0.8.4.3
 - Radarr version: 3.0.0.2899
 - Sonarr version: not used
 - OS: Docker LinuxServer Image

**Additional context**
If required i can create an account to the devs check the problem since this provider allow only portugal and brazil registrations. 

Kind Regards

**Comment by guardiaopt** [comment]
Possibly your server is blocked, try contact me, guardiao at legendasdivx
Sometimes the ip can be blocked if bulk requests are made.
