### ISSUE TITLE
Bazarr creates subtitle files as root:root

### ISSUE THREAD

**Issue by jtasseroul** [morpheus65535/bazarr#96]
Setup : 

- Docker install, container image tag 0dd1db93-amd64, Bazarr version 0.5.4
- environment options set as PUID=xxxx and PGID=yyyy, confirmed in Docker logs
- upon checking in folders, srt files are owned by root:root and not xxxx:yyyy

**Comment by morpheus65535** [comment]
Can you give me `docker logs` output?

**Comment by jtasseroul** [comment]
There you are : 

[docker logs](https://imgur.com/uSOL9Wk)

**Comment by morpheus65535** [comment]
I've remembered that I actually never test this functionality... I've just done and fixed what was missing to make this work. You can pull the new image and recreate your container with PUID and PGID parameters. It should be working perfectly now.

Please, give me feedback!

**Comment by jtasseroul** [comment]
Whoo, so I've recreated the container and while I can't check if the issue is resolved, the docker logs are now full of stuff :  


Hit Ctrl-C to quit.,
Listening on http://0.0.0.0:6767/,
  file, filename, etc = imp.find_module(subname, path),
Bottle v0.12.13 server starting up (using WaitressServer())...,
/usr/lib/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/usr/lib/python2.7/site-packages/backports': missing __init__.py,
socket.error: [Errno 98] Address in use,
    return getattr(self._sock,name)(*args),
  File "/usr/lib/python2.7/socket.py", line 228, in meth,
    return self.socket.bind(addr),
  File "/usr/lib/python2.7/asyncore.py", line 342, in bind,
    self.bind(sockaddr),
  File "/usr/lib/python2.7/site-packages/waitress/server.py", line 294, in bind_server_socket,
    self.bind_server_socket(),
  File "/usr/lib/python2.7/site-packages/waitress/server.py", line 182, in __init__,
    sockinfo=sockinfo),
  File "/usr/lib/python2.7/site-packages/waitress/server.py", line 85, in create_server,
    server = _server(app, **kw),
  File "/usr/lib/python2.7/site-packages/waitress/__init__.py", line 11, in serve,
    serve(handler, host=self.host, port=self.port),
  File "/usr/lib/python2.7/site-packages/bottle.py", line 2813, in run,
    server.run(app),
  File "/usr/lib/python2.7/site-packages/bottle.py", line 3127, in run,
    run(host=ip, port=port, server='waitress'),
  File "/bazarr/bazarr.py", line 1225, in <module>,
Traceback (most recent call last):

**Comment by morpheus65535** [comment]
Don't worry about the first error about backports. It won't change a thing.

About this one: `socket.error: [Errno 98] Address in use`

There is obviously another process trying to use the same ip:port. Are you running to instances of Bazarr at the same time?

Those PIP error are probably caused by the network conflict. Fix this and you should be all good.

**Comment by morpheus65535** [comment]
Any news on this one?

**Comment by morpheus65535** [comment]
I got a permission error that prevent PIP from updating module since eaa7fc3. I'm gonna have to implement #81 ASAP.

**Comment by jtasseroul** [comment]
I wanted to see a naturally-triggered download happen just to be sure, and everything works as intended ! Fix is working, PUID/PGID is used as set.

**Comment by morpheus65535** [comment]
Fro now I've disabled this and the PUID and PGID won't have any effect. I've ask for help to the Linux Server guys and are waiting on a return. I hope they're going to be willing to create their own image and make that kind of stuff working like they always do.

I keep the issue open has a reminder.

**Comment by morpheus65535** [comment]
Should be fix in LSIO Bazarr image available in the next week.
