### ISSUE TITLE
Security Issues - Video Files deleted

### ISSUE THREAD

**Issue by DarkAllMan** [morpheus65535/bazarr#961]
Now I already know I should not made the GUI publicly available for my installation.
Nevertheless I did for testing purposes and my video files got wiped.
Someone gained access and removed all my video files and left a message in the Bazarr settings:
"All your files are exposed"
Just to let you guys know that there are people taking advantage of idiots like me :)

**Comment by morpheus65535** [comment]
I would say that I'm sorry for you but you should at least have set a password to access Bazarr. There's nothing more I can do.

**Comment by DarkAllMan** [comment]
There was a password set.....  That did not stop the attacker...

**Comment by halali** [comment]
As i good remember bazarr havent possibility to delete any video files. Bazarr have only function to delete subtitles.
