### ISSUE TITLE
Installing Bazarr on synology without docker

### ISSUE THREAD

**Issue by Dranaxel** [morpheus65535/bazarr#964]
Hello, I would like to point the fact it's possible to install Bazarr on synology without Docker (for low tier NAS).

You need to install entware-ng which is a cli package manager allowing you to access to multiple additional packages, here are the procedure: https://github.com/Entware/Entware-ng/wiki/Install-on-Synology-NAS

Then you basically follow the feeBSD procedure except you need to install python3-lxml before launching bazarr.py then it should works.

Hope this will help someone !

**Comment by morpheus65535** [comment]
Thanks for the feedback!
