### ISSUE TITLE
subssabbz, subsunacs and supersubtitles all show up as 'FeatureNotFound'

### ISSUE THREAD

**Issue by keithah** [morpheus65535/bazarr#965]
**Describe the bug**
When I have enabled subssabbz, subsunacs and supersubtitles the Providers tab show them all as 'FeatureNotFound' so it seems like they are not functioning

**To Reproduce**
1. Enable subssabbz, subsunacs and supersubtitles
2. Search subtitles
3. Look in Providers tab

**Expected behavior**
Subtitles to download via these providers and no error

**Screenshots**
<img width="515" alt="image" src="https://user-images.githubusercontent.com/684920/80992043-cd56ba00-8ded-11ea-9cae-0176b3e7cee6.png">

**Software (please complete the following information):**
 - Bazarr: 0.8.4.4
 - Radarr version  0.2.0.1484
 - Sonarr version 3.0.3.784
 - OS: Ubuntu Linux 18.04.4

**Comment by morpheus65535** [comment]
You haven't installed `requirements.txt` which include lxml.
