### ISSUE TITLE
FreeBSD wiki rc.d startup script issues and solutions

### ISSUE THREAD

**Issue by sindreruud** [morpheus65535/bazarr#966]
I have encountered some issues with the recently revised FreeBSD instructions on FreeNAS. I found a solution and thought I should make a bug report to have them fixed. Let me know if I should have posted this elsewhere.

The instructions calls for: 
> `cd /usr/local/share`
> Clone the repository using `git clone https://github.com/morpheus65535/bazarr.git` (this will download the files to /usr/local/bazarr)

This must be an error? Because it will download the files to `/usr/local/share`, and not `/usr/local/bazarr`

In the rc.d startup script it references:
```
pidfile="/usr/local/bazarr/bazarr.pid"
procname="/usr/local/bin/python3"
command="/usr/sbin/daemon"
command_args="-f -p ${pidfile} ${procname} /usr/local/bazarr/bazarr.py"
```

For it to work it needs to be corrected to:
```
pidfile="/usr/local/share/bazarr/bazarr.pid"
procname="/usr/local/bin/python3"
command="/usr/sbin/daemon"
command_args="-f -p ${pidfile} ${procname} /usr/local/share/bazarr/bazarr.py"
```

Alternatively, you can of course just cd into the correct path before git cloning. I don't know if it makes more sense to install Bazarr into `/usr/local/share/bazarr` or `/usr/local/bazarr`, I am not an expert at all.

And there is also a error with this command:
`chown -W bazarr_user /usr/local/share/bazarr`, because -W is not an allowed option. I guess it is meant to be `-R` to chown recursively. 

And lastly, thank you so much to everyone maintaining this project, and also making the instructions for FreeBSD / FreeNAS. Love it!

**Comment by halali** [comment]
I think better solution will be correct `cd /usr/local/share` to `cd /usr/local`
And we wont correct anything else.

Am i correct ?

**Comment by halali** [comment]
@TRaSH- this one is for you

**Comment by TRaSH-** [comment]
Thnx @sindreruud could you check if it's correct now.
