### ISSUE TITLE
Bazarr not following the config to ignore PGS subs

### ISSUE THREAD

**Issue by eltanque** [morpheus65535/bazarr#967]
**Describe the bug**
I've Bazarr, Radarr, Sonarr running on windows 10, latest versions
Configuration in Bazarr is set up to:
Use Embedded Subtitles = On/Yes <-- I want it to consider embedded since embedded SRTs are ok
Ignore Embedded PGS subitles = On/Yes  <-- but I want to exclude PGS because that doesn't play well with Plex, plex works better with srt.

When downloading a movie with no embedded subtitles through Radarr (monitored or unmonitored), bazarr will fetch subs. As expected

When downloading a movie with embedded PGS subtitles through radarr, Bazarr will identify the subs streams, in my case almost always there's an english PGS. Bazarr won't download an SRT for this file.

Manually searching for a sub, it finds and downloads the file, no issues

Haven't noticed the issue with TV shows recently, don't have one to test

**To Reproduce**
1. Download a movie with PGS subs
2. Let Bazarr search/download subs
3. No subs downloaded
4. No error on logs

**Expected behavior**
Subs downloaded as per config

**Screenshots**
N/A

**Software (please complete the following information):**
 - Bazarr: 0.8.4.3
 - Radarr version 0.2.0.1480
 - Sonarr version N/A
 - OS: Windows 10 Pro

**Additional context**
Logs:
https://pastebin.com/PmbKwDZU

**Comment by morpheus65535** [comment]
This issue have been fixed in dev branch and should be merged to master in 0.8.4.4.
