### ISSUE TITLE
Strange URL showing up in docker

### ISSUE THREAD

**Issue by Cruv** [morpheus65535/bazarr#97]
The log says that something is serving on http://fr.a2dfp.net

This URL is a blocked ad domain. Any idea why its showing up in the docker log?

**Comment by morpheus65535** [comment]
Oh... never seen that one... Could you share a copy of the log with me so I can investigate?

**Comment by Cruv** [comment]
[Bazarr-morpheus.txt](https://github.com/morpheus65535/bazarr/files/2159517/Bazarr-morpheus.txt)

**Comment by Cruv** [comment]
2018-07-03 13:31:19,stdout,Serving on http://fr.a2dfp.net:6767

that is the line I'm seeing that is concerning.

**Comment by Cruv** [comment]
Looking at the April MVPS hosts file provided at http://winhelp2002.mvps.org/hosts.txt
The domain fr.a2dfp.net is the first ad domain that they block by routing to 0.0.0.0

**Comment by morpheus65535** [comment]
Never seen that one. Look like a reverse lookup made on your setup. What is your setup?

**Comment by Cruv** [comment]
I'm running it on a Synology 1817+ using Docker. I grabbed the image from your Dockerhub page here https://hub.docker.com/r/morpheus65535/bazarr/

**Comment by Cruv** [comment]
If it was a reverse lookup just specific to my system, wouldn't the other docker images I'm running also put out that line in their log?

**Comment by morpheus65535** [comment]
Only if they are using 0.0.0.0 as an "all ip address". Sonarr and Radarr use "*" instead. Bottle-Py framework that I Bazarr rely on is using 0.0.0.0. I can't do nothing about that.

**Comment by Cruv** [comment]
So should I worry about this domain showing up or am I safe to continue as normal? I really appreciate you looking into this.

**Comment by morpheus65535** [comment]
You don't need to worry at all about this, I don't make any call to anything other than Sonarr and Radarr. Subliminal call providers but only those you specified in settings.

**Comment by Cruv** [comment]
Yeah I downloaded the zip and did a full text search as well and I don't see it in there. I'm clueless as to why its outputting that message.

**Comment by morpheus65535** [comment]
If you're ok with that, I'll close this issue. Thanks for your interest in Bazarr!
