### ISSUE TITLE
Search both Series and Movies by design?

### ISSUE THREAD

**Issue by redglory** [morpheus65535/bazarr#973]
Hi @morpheus65535, is searching Series and Movies sequentially by design?

When we open Movies Tab on Wanted subtitles and press "**Download wanted subtitles**" it starts to search for Series in the first place and when finished it searches for Movies.

I've spotted this:
```javascript
	$('#wanted_search_missing_subtitles_movies').on('click', function(){
		$(this).addClass('disabled');
		$(this).find('i:first').addClass('loading');
	    $.ajax({
            url: '{{base_url}}wanted_search_missing_subtitles'
        })
	});
```
This triggers missing subtitles not **movie** missing subtitles

I suppose this is done by design :)

**Comment by morpheus65535** [comment]
Yes it was but I'm fixing this in v0.9. There's going to be 2 different tasks and search buttons we'll kick start those different tasks.

**Comment by redglory** [comment]
@morpheus65535 that's great and how it's suppose to work (IMHO) :)

**Comment by redglory** [comment]
I'm going to close this 👍

**Comment by morpheus65535** [comment]
> @morpheus65535 that's great and how it's suppose to work (IMHO) :)

I agree. This was a relic of the initial Bazarr release that haven't been reviewed since.
