### ISSUE TITLE
Unable to integrate with Radarr

### ISSUE THREAD

**Issue by goncalo532** [morpheus65535/bazarr#975]
**Describe the bug**
Connection test with radarr fails on my windows hyper V VM, sonarr worked fine with same settings.

**To Reproduce**
1. Used 127.0.0.1,  Port:7878
2. Base url empty
3. Test
4.

**Expected behavior**
Successful test

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: Ver.0.8.4.3
- Radarr version Ver. 0.2.0.1480
 - Sonarr version Ver. 2.0.0.5344
 - OS: Windows 10 Hyper V VM
**Additional context**
Log:
09/05/2020 18:29:50|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): 127.***.***.***:7878|
09/05/2020 18:29:50|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on 127.***.***.***|
09/05/2020 18:29:50|DEBUG   |urllib3.connectionpool          |http://127.***.***.***:7878 "GET /api/system/status?apikey=********06 HTTP/1.1" 400 334|

**Comment by halali** [comment]
Please come to discord for support.
