### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#985]
`Python 3.7.0 or greater required. Current version is 3.6.9. Please upgrade Python.`

Many of us are using Ubuntu 18.04 LTS (with support until April 2023). That distribution comes with Python 3.6.9 and they are not going to upgrade Python. Also Python >= 3.5 still has official support from Python. https://en.wikipedia.org/wiki/CPython#Enterprise_Linux

Differences between Python 3.6 and Python 3.7 are not huge. Are you sure external libraries are not compatible? Could you patch those libraries?

**Comment by morpheus65535** [comment]
You can easily install 3.8 on ubuntu 19.04 using deadsnake PPA: https://linuxize.com/post/how-to-install-python-3-8-on-ubuntu-18-04/

**Comment by ngosang** [comment]
Yep, I already did, it works well.
I was thinking in other users, dropping support for 3.6 seems premature to me but it's your software. If you think it's not necessary you can close.

**Comment by morpheus65535** [comment]
To be honest, on top of dependencies dropping support for 3.6, I was investigating on a lot of issues opened by users that fixed them self by upgrading to Python 3.7. My free time is limited and I prefer to use it to improve Bazarr experience for the mass then on debugging older software stack of the minority. :-)
