### ISSUE TITLE
Error trying to get video information for this file

### ISSUE THREAD

**Issue by erhnamdfc** [morpheus65535/bazarr#989]
**Describe the bug**
"Error trying to get video information for this file" applies to all my file.

**To Reproduce**
Both automatic and manual search

**Expected behavior**
Finding subtitles and downloading them

**Software (please complete the following information):**
 - Bazarr:  0.8.4.3
 - Radarr version 0.2.0.1480
 - Sonarr version 2.0.0.5344
 - OS: Windows 10

**Additional context**
Message:
BAZARR Error trying to get video information for this file: /media/The Lion King (2019)/The Lion King 2019 RERiP 1080p BluRay x264-SPARKS-Scrambled.mkv

Exception:
Traceback (most recent call last):
 File "/app/bazarr/bazarr/get_subtitle.py", line 71, in get_video
  video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,
 File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video
  return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 547, in scan_video
  video.size = os.path.getsize(hash_path)
 File "/usr/lib/python3.8/genericpath.py", line 50, in getsize
  return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: \/media/The Lion King (2019)/The Lion King 2019 Bluray-1080p.mkv\

**Comment by halali** [comment]
You have bad setuped pathmappings, i dont think your windows is able access path /media.

Please come to discord for support
