### ISSUE TITLE
radarr not showing up in bazarr

### ISSUE THREAD

**Issue by poplolnman** [morpheus65535/bazarr#99]
hi,
i setup both sonarr and radarr, but while sonarr shows as connected and all the episodes monitored; radarr doesnt do this and none of the movies show up...

**Comment by morpheus65535** [comment]
Could you please add logs and a screenshot or your settings? I suspect a problem with your settings.

**Comment by poplolnman** [comment]
[bazarr.log](https://github.com/morpheus65535/bazarr/files/2168772/bazarr.log)

![screenshot_3](https://user-images.githubusercontent.com/12866874/42355851-37700992-809d-11e8-98e1-de15992e482e.png)

the api key was purposefully left out

**Comment by morpheus65535** [comment]
Can you show me a screenshot of the general tab in Radarr settings (not in Bazarr)?

Can you show me the result of this: http://127.0.0.1/api/system/status?apikey=**{insert_your_api_key_here}**

**Comment by poplolnman** [comment]
![screenshot_4](https://user-images.githubusercontent.com/12866874/42401705-e988f948-8144-11e8-81f5-25022d89f88b.png)

![screenshot_5](https://user-images.githubusercontent.com/12866874/42401782-4190c5e4-8145-11e8-9897-df2f4a555340.png)

**Comment by morpheus65535** [comment]
Have you tried to remove in Bazarr the "/" in Radarr Base URL and leave it empty?

Can you show me the result of this: http://127.0.0.1:44300/api/profile?apikey={insert_your_api_key_here}

**Comment by poplolnman** [comment]
Have you tried to remove in Bazarr the "/" in Radarr Base URL and leave it empty?

this worked, thank you for your help!

**Comment by morpheus65535** [comment]
No problem, I'll work that part so it won't affect other users.
