### ISSUE TITLE
open subtitles dont work

### ISSUE THREAD

**Issue by tribugames** [morpheus65535/bazarr#990]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: [e.g. v 0.6.1]
 - Radarr version [e.g. v 0.2.0.0001]
 - Sonarr version [e.g. v 2.0.0.0001]
 - OS: [e.g. Windows 10]

**Additional context**

**Comment by morpheus65535** [comment]
I'm going to take as much effort to resolve that issue that you took to open it. It works for me.
