### ISSUE TITLE
Post-Processing not saving output to System -> Logs

### ISSUE THREAD

**Issue by atmorell** [morpheus65535/bazarr#991]
**Describe the bug**
Post-Processing output is not saved in the Log panel, which makes it difficult to debug and test. 
![no-log](https://user-images.githubusercontent.com/20379/82200283-15520280-98ff-11ea-8aca-194732f7b695.png)

**To Reproduce**
Enable Post-Processing and enter a command that returns something to the console
e.g. ls -lah '{{episode_language_code3}}'

**Expected behavior**
System -> Logs -> Details : Showing dir output from the Post-processing command instead of  "Nothing returned from command execution"

**Software (please complete the following information):**
 - Bazarr: [e.g. v 0.8.4.3]
 - OS: Ubuntu

**Comment by morpheus65535** [comment]
I've set my post-processing to `ls -lah` and Bazarr is providing the output without any issue:

```
BAZARR Post-processing result for file /tv/The 100/Season 6/The.100.S06E13.720p.HDTV.x264-SVA[eztv] - Copie.mkv : total 20K drwxr-xr-x 4 root root 4.0K May 17 23:18 . drwxrwxr-x 5 root root 4.0K May 17 23:18 .. drwx-ws--T 2 root root 4.0K May 17 23:18 event -rwxr-xr-x 1 root root  337 May 17 23:18 run drwx------ 2 root root 4.0K May 17 23:18 supervise 
```

**Comment by atmorell** [comment]
I also get a result with a simple command. If I use any of the variables there is no output. Can you try:
ls -lah '{{episode_language_code3}}'

**Comment by morpheus65535** [comment]
Use double quotes.

**Comment by atmorell** [comment]
Same with "Double Quotes" 
![pp](https://user-images.githubusercontent.com/20379/82207306-e55c2c80-9909-11ea-98fe-8c83a9119dd0.png)
![result](https://user-images.githubusercontent.com/20379/82207311-e725f000-9909-11ea-8186-d7c0b7860267.png)

**Comment by morpheus65535** [comment]
I don't know what's different in your configuration but post-processing is used by hundred of users without any issue. I suggest you come talk to the other folks using it on Discord and they could possibly help you fix that.

**Comment by atmorell** [comment]
Alright, thank you anyway.
