### ISSUE TITLE
An error after a fresh install:  NoneType object has no attribute lower

### ISSUE THREAD

**Issue by jrasanen** [morpheus65535/bazarr#992]
**Describe the bug**
Got  an internal server error after installing Bazar for the first time

**To Reproduce**
1) Install on Windows 10 by downloading it from https://www.bazarr.media/#download
2) Run it

**Expected behavior**
Not receive an error on the wizard page

**Screenshots**
<img width="1151" alt="Screenshot 2020-05-22 at 13 52 39" src="https://user-images.githubusercontent.com/13303/82660820-abee2e80-9c33-11ea-93ee-60907b141f1f.png">
<img width="1282" alt="Screenshot 2020-05-22 at 13 54 11" src="https://user-images.githubusercontent.com/13303/82660939-bf999500-9c33-11ea-88d6-1f7e720b2b02.png">

**Software (please complete the following information):**
 - Bazarr: Latest master
 - OS: Windows 10 Pro 1909

**Comment by jrasanen** [comment]
By patching simpleconfigparser's `getboolean` into,

```python
        def getboolean(self, name):
            try:
                if not self.section:
                    return None
                return self.parser.getboolean(self.section, name)
            except Exception:
                return None
```

Bazarr starts up. An upstream fix to `simpleconfigparser` or making a helper function to Bazarr and wrapping the `getboolean` into try..except would fix this.

**Comment by morpheus65535** [comment]
For an unknown reason, settings didn't get reloaded after latest update installed and Bazarr restarted. Restarting Bazarr service manually (or restarting of course) fixed the issue. Next version of Bazarr is a complete rework so I'm not sure I will investigate a lot on that one and release a fix. I'll let it open and if I release a maintenance release for 0.8.4.4, I'll work on it.

Thanks for reporting!

**Comment by morpheus65535** [comment]
I've created a new installer that won't have this issue. It is now updated and new users won't be facing this issue.
