### ISSUE TITLE
Bazarr not recognizing internal subs

### ISSUE THREAD

**Issue by menzo2003** [morpheus65535/bazarr#993]
**Describe the bug**
Bazarr not recognizing internal subs of a movie.
A movie of mine has lots of internal subs but Bazarr does not see then and is downloading external subs.

the movie is: 
Avengers.Infinity.War.2018.1080p.BluRay.DTS.x264-Geek.mkv

**Expected behavior**
Bazarr should list all the internal subs.

**Screenshots**
Mediainfo copy of one of the languages Bazarr does not see:

Text #18
ID                                       : 21
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Language                                 : Dutch
Default                                  : No
Forced                                   : No

**Software (please complete the following information):**
 - Bazarr Ver. 0.8.4.4 
 - Radarr version 0.2.0.1480

 - OS: Ubuntu 20.04 armhf on a RaspberryPi 3B

**Comment by morpheus65535** [comment]
Did you enable "Use embedded subtitles" in Settings-->Subtitles?

**Comment by menzo2003** [comment]
Yeah, it works fine with other movies.

**Comment by morpheus65535** [comment]
> Yeah, it works fine with other movies.

Enable debug log, empty log, force a scan from disk for this movie and provide the debug log.

**Comment by menzo2003** [comment]
[bazarr.log](https://github.com/morpheus65535/bazarr/files/4671739/bazarr.log)

I hope this helps

**Comment by morpheus65535** [comment]
Do you have ffprobe (ffmpeg) installed?

If yes, could you try to uninstall it so Bazarr would use the one in Bazarr bin directory?

If not, can you give me the output of ffprobe in Bazarr bin directory: `ffprobe -v quiet -print_format json -show_format -show_streams -sexagesimal Avengers.Infinity.War.2018.1080p.BluRay.DTS.x264-Geek.mkv`

**Comment by menzo2003** [comment]
I did not have ffmpeg installed.
There seems to be no ffprobe in /opt/bazarr/bin/Linux/armv5tel folder only UnRaR, I guess my pi that is running armhf is running the armv5 code. ffprobe seems present in the i386 and x86_64 folders but it seems logical that my rapberrypi 3b cant run those.

![image](https://user-images.githubusercontent.com/31390707/82754838-fa383480-9dcf-11ea-8e61-440abfd30a79.png)

For a test I did install ffmpeg with apt separately and ran the command just to see the output.
[ffprobe from apt  avengers infinity.txt](https://github.com/morpheus65535/bazarr/files/4673573/ffprobe.from.apt.avengers.infinity.txt)

**Comment by morpheus65535** [comment]
Now that you've installed ffmpeg, Bazarr should be able to use it and detect the enclosed subtitles. What version of ffmpeg did you install?

**Comment by menzo2003** [comment]
With a re-scan bazarr did find all the internal subs, thanks!

I installed ffmpeg version 4.2.2-1ubuntu1 via apt. 
I guess the problem was that ffprobe did not come with the armhf package of bazarr or it is not listed as a dependency.

**Comment by morpheus65535** [comment]
Thanks for the feedback! I agree and will package the missing executable for arm platform.

**Comment by morpheus65535** [comment]
I cannot find reliable build for ffmpeg on aarch64 and armv5tel. I will add requirement to the wiki instead. How did you install ffmpeg? `apt-get install ffmpeg`?

**Comment by menzo2003** [comment]
I ran `apt install ffmpeg` so I got the armhf package for Ubuntu 20.04
This one:
https://packages.ubuntu.com/focal/ffmpeg

**Comment by morpheus65535** [comment]
I've added `ffmpeg` to requirements in wiki. Thanks for your help!
