### ISSUE TITLE
DataTables warning: table id=movies - Ajax error

### ISSUE THREAD

**Issue by h2xtreme** [morpheus65535/bazarr#994]
**Describe the bug**
DataTables warning: table id=movies - Ajax error error shows up when accessing or using any menu on Bazarr.

**To Reproduce**
Access to Bazarr

**Screenshots**
https://i.imgur.com/S1f6gIr.png

**Software (please complete the following information):**
 - Bazarr: Development, fully updated with git pull

**Comment by morpheus65535** [comment]
Please provide the browser console output while refreshing the page.

**Comment by h2xtreme** [comment]
`The “io” cookie will soon be rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To learn more about the “sameSite“ attribute, see https://developer.mozilla.org/docs/Web/HTTP/Cookies`

**Comment by morpheus65535** [comment]
What browser? Private mode? Some security software like "web protection" type?

**Comment by h2xtreme** [comment]
Firefox latest. No weird plugins or antivirus. Only Windows Defender.

**Comment by morpheus65535** [comment]
I've just installed Firefox and can access my Bazarr instance without any issue. Can you provide me a debug log and you bazarr.db file?

**Comment by JpF4E** [comment]
I am having the same issue using Chrome. Nothing loads. The warning appears on all tabs and it reloads automatically.
![image](https://user-images.githubusercontent.com/20103641/82757528-e47b3d00-9dd8-11ea-82ca-66ca8cba2d19.png)

**Comment by JpF4E** [comment]
This is my bazarr.db
[bazarr.zip](https://github.com/morpheus65535/bazarr/files/4673797/bazarr.zip)

Also, I cannot activate Debug mode. I enable the checkbox, click save and wait, then the page reloads and the checkbox is disabled again.

**Comment by halali** [comment]
You will need update your bazarr to latest dev veraion and restart. This is already fixed issue

**Comment by JpF4E** [comment]
`24/05/2020 14:59:05|ERROR   |apscheduler.executors.default   |Job "Update Bazarr from source on Github (trigger: interval[6:00:00], next run at: 2020-05-24 20:59:00 WEST)" raised an exception|'Traceback (most recent call last):\n  File "/opt/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File "/opt/bazarr/bazarr/check_update.py", line 54, in check_and_apply_update\n    updated()\n  File "/opt/bazarr/bazarr/check_update.py", line 286, in updated\n    from main import Server\n  File "/opt/bazarr/bazarr/main.py", line 87, in <module>\n    @app.route(\'/login/\', methods=["GET", "POST"])\n  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1314, in decorator\n    self.add_url_rule(rule, endpoint, f, **options)\n  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 98, in wrapper_func\n    return f(self, *args, **kwargs)\n  File "/opt/bazarr/bazarr/../libs/flask/app.py", line 1283, in add_url_rule\n    "existing endpoint function: %s" % endpoint\nAssertionError: View function mapping is overwriting an existing endpoint function: login_page'|`

Any clue?

**Comment by JpF4E** [comment]
I did "git pull" and it said it was already up to date. I also tried restarting bazarr with no success.

**Comment by halali** [comment]
So open config.ini and delete line where is apikey

**Comment by h2xtreme** [comment]
For me what worked was remove the database and restart the service. 

I don't exactly what I loose with a new DB, though...

**Comment by morpheus65535** [comment]
@h2xtreme if you still have your old bazarr.db file I would like to get it to see what was causing the issue and catch it for others.

**Comment by h2xtreme** [comment]
[bazarr.zip](https://github.com/morpheus65535/bazarr/files/4742265/bazarr.zip)

@morpheus65535 soory for the delay.

Attached the old database.

**Comment by morpheus65535** [comment]
> [bazarr.zip](https://github.com/morpheus65535/bazarr/files/4742265/bazarr.zip)
> 
> @morpheus65535 soory for the delay.
> 
> Attached the old database.

Thanks! I don't see anythings wrong but lets keep it for future reference just in case! ;-)
