### ISSUE TITLE
Special characters in series title cause query to fail for Assrt

### ISSUE THREAD

**Issue by Mr-Quin** [morpheus65535/bazarr#996]
**Describe the bug**
Subtitle search will fail if show name contain special characters like '\~' or '\!' for Assrt.net.
Bazarr log shows
`Throttling assrt for 10 minutes, until 20/05/23 00:57, because of: HTTPError. Exception info: '509 Server Error: for url: https://api.assrt.net/v1/sub/search?token={TOKEN}&q=Endro~%21+S01E06&is_file=1'`
So this is a 509 error, but thanks to that I found this weird edge case.

**To Reproduce**
1. There is a show titled "Endro~!"
2. Send a GET request to `https://api.assrt.net/v1/sub/search?token={TOKEN}&q=Endro~%21...` this will result in a error message from the server, which is apparently ignored by Bazarr 
`{"sub":{"result":"failed","subs":{},"action":"search"},"status":30002,"errmsg":"search engine is unavailable"}`
3. If the special characters are completely removed, the request will succeed. And in this case it will still return the correct results.
For the matter, using \%7E for '\~' also fails

**Expected behavior**
Possibly strip special characters for assrt? 

**Software (please complete the following information):**
 - Bazarr: v0.8.4.3, Docker
 - Radarr version 0.2.0.1480 Docker
 - Sonarr version 2.0.0.5344 Docker
 - OS: Ubuntu Server 18.04 LTS, Docker 18.09.9

**Additional context**
Maybe this is better to be fixed on Assrt's side.

Side note, but for the couple TV series I've tested with Assrt, including the season and episode number with the series title in the query will return no result even with `is_file=1` and `no_muxer=1` set. 
For the ones I've tried, each sub id will contain download links for all episodes. [https://assrt.net/xml/sub/626/626131.xml](https://assrt.net/xml/sub/626/626131.xml) 
So even if the above query succeeds, it will return an empty set and eventually lead to another 509 error.

**Comment by morpheus65535** [comment]
Can you try the fix I've pushed to dev branch?

**Comment by Mr-Quin** [comment]
I pulled the branch, doesn't work, it still includes the characters. 

> `Throttling assrt for 10 minutes, until 20/05/23 10:20, because of: HTTPError. Exception info: '509 Server Error:  for url: https://api.assrt.net/v1/sub/search?token=F9a2MFDRcktmLyFsBDLGzNPDLZZA2C4Z&q=Endro~%21+S01E12&is_file=1'`

`'~'.isascii()` returns `true`, might be the reason?
New UI looks good btw.

**Comment by morpheus65535** [comment]
You are right about `isascii`, I need to run test with `isalnum` instead later today. If you are able to edit the file and test it I would appreciate.

**Comment by Mr-Quin** [comment]
I tested isalnum, seems to fix this particular problem. I made a pull request for the change. 
Is there any way to make it search for the series and parse the results to get download links for individual episodes? Searching by episode doesn't with assrt in many cases.

**Comment by morpheus65535** [comment]
Actually, no. There's no way to search for season pack on assrt. Thanks for the PR!
