### ISSUE TITLE
Not finding subtitles

### ISSUE THREAD

**Issue by dabluecaboose** [morpheus65535/bazarr#998]
Hello, I apologize if this is a duplicate issue but I have been unable to find a solution for this problem.

As you may or may not know, there are a lot of scenes in Breaking Bad that are in Spanish with forced subtitles.  I have been going mad trying to get these to download in Bazarr.

I have several subtitle providers enabled in settings, and I've confirmed the subtitles exist by manually going to opensubtitles.  But when I click "manual search" I get "Scene Name: None" and "No Subtitles Found For This Episode"

I'm not sure what could be wrong, but I'd be happy to help troubleshoot in case this is a code issue and not an ID-10T error.

**Comment by morpheus65535** [comment]
Forced subs are always hard to find. I suggest you cone to Discord for support or questions.
